// Bulk-adds key players to NC State, Louisville, Syracuse, Miami, Wake Forest,
// Clemson, Virginia Tech, Georgia Tech, Florida State, Notre Dame, Pitt, Boston College
// Run: npx tsx prisma/scripts/bulk-add-remaining-acc.ts

import * as fs from "node:fs";
import * as path from "node:path";

const SEEDS_DIR = path.join(__dirname, "../seeds");

type Player = { slug: string; firstName: string; lastName: string; birthYear: number; position: string; jerseyNumber: number; bio: string; occupationType: string; currentTitle: string; location: string; statusNote: string; ppg: number; rpg: number; apg: number; };

function insertPlayers(filepath: string, players: Player[], teamName: string, season: string) {
  let content = fs.readFileSync(filepath, "utf-8");
  const existingSlugs = new Set([...content.matchAll(/slug: "([^"]+)"/g)].map(m => m[1]));
  const newPlayers = players.filter(p => !existingSlugs.has(p.slug));
  if (newPlayers.length === 0) return 0;
  const headCoachIdx = content.indexOf('role: "HEAD_COACH"');
  if (headCoachIdx === -1) return 0;
  const beforeCoach = content.substring(0, headCoachIdx);
  const objStart = beforeCoach.lastIndexOf("    {");
  if (objStart === -1) return 0;
  const entries = newPlayers.map(p => `    {
      slug: "${p.slug}",
      firstName: "${p.firstName}",
      lastName: "${p.lastName}",
      birthYear: ${p.birthYear},
      hometown: "United States",
      highSchool: "United States",
      bio: "${p.bio.replace(/"/g, '\\"')}",
      status: { occupationType: "${p.occupationType}", currentTitle: "${p.currentTitle.replace(/"/g, '\\"')}", location: "${p.location}", statusNote: "${p.statusNote.replace(/"/g, '\\"')}", sourceUrl: "https://en.wikipedia.org/wiki/${p.firstName}_${p.lastName.replace(/ /g, '_')}" },
      membership: { role: "PLAYER", jerseyNumber: ${p.jerseyNumber}, position: "${p.position}", yearsAtSchool: "${season}", gamesPlayed: 33, pointsPerGame: ${p.ppg}, reboundsPerGame: ${p.rpg}, assistsPerGame: ${p.apg} },
      seasonStats: [{ level: "COLLEGE", teamName: "${teamName}", season: "${season}", yearLabel: "${season}", sortOrder: 201, gamesPlayed: 33, pointsPerGame: ${p.ppg}, reboundsPerGame: ${p.rpg}, assistsPerGame: ${p.apg} }],
      careerEvents: [],
    },`).join("\n");
  content = content.substring(0, objStart) + entries + "\n" + content.substring(objStart);
  fs.writeFileSync(filepath, content, "utf-8");
  return newPlayers.length;
}

// ── NC STATE ──
const ncstate: Record<number, Player[]> = {
  2009: [{ slug: "tracy-smith-ncst", firstName: "Tracy", lastName: "Smith", birthYear: 1987, position: "Forward", jerseyNumber: 30, bio: "Senior forward and team leader under Sidney Lowe.", occupationType: "RETIRED_ATHLETE", currentTitle: "Retired", location: "NC", statusNote: "Played overseas briefly after NC State.", ppg: 14.0, rpg: 7.5, apg: 1.0 }, { slug: "brandon-costner", firstName: "Brandon", lastName: "Costner", birthYear: 1987, position: "Forward", jerseyNumber: 33, bio: "Senior forward and scorer.", occupationType: "RETIRED_ATHLETE", currentTitle: "Professional", location: "NC", statusNote: "Played overseas after NC State.", ppg: 12.5, rpg: 5.0, apg: 1.0 }],
  2010: [{ slug: "tracy-smith-ncst", firstName: "Tracy", lastName: "Smith", birthYear: 1987, position: "Forward", jerseyNumber: 30, bio: "5th-year senior and team captain.", occupationType: "RETIRED_ATHLETE", currentTitle: "Retired", location: "NC", statusNote: "Played overseas after NC State.", ppg: 16.0, rpg: 8.5, apg: 1.0 }],
  2011: [{ slug: "cj-leslie", firstName: "C.J.", lastName: "Leslie", birthYear: 1991, position: "Forward", jerseyNumber: 5, bio: "Freshman forward with NBA athleticism.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Pro Player", location: "Overseas", statusNote: "Drafted #47 in 2013. Long overseas career.", ppg: 11.0, rpg: 5.5, apg: 0.8 }, { slug: "scott-wood-ncst", firstName: "Scott", lastName: "Wood", birthYear: 1990, position: "Guard", jerseyNumber: 15, bio: "Sophomore sharpshooter. One of ACC's best 3-pt shooters.", occupationType: "OTHER", currentTitle: "Professional", location: "NC", statusNote: "NC State's all-time 3-point leader.", ppg: 11.0, rpg: 2.0, apg: 1.0 }],
  2012: [{ slug: "cj-leslie", firstName: "C.J.", lastName: "Leslie", birthYear: 1991, position: "Forward", jerseyNumber: 5, bio: "Sophomore forward emerging as star.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Pro Player", location: "Overseas", statusNote: "Drafted #47. Overseas career.", ppg: 14.5, rpg: 7.0, apg: 1.0 }, { slug: "scott-wood-ncst", firstName: "Scott", lastName: "Wood", birthYear: 1990, position: "Guard", jerseyNumber: 15, bio: "Junior sharpshooter.", occupationType: "OTHER", currentTitle: "Professional", location: "NC", statusNote: "NC State 3-point record holder.", ppg: 12.5, rpg: 2.0, apg: 1.5 }, { slug: "lorenzo-brown", firstName: "Lorenzo", lastName: "Brown", birthYear: 1990, position: "Guard", jerseyNumber: 2, bio: "Junior guard. Later played in NBA.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Pro Player", location: "Overseas", statusNote: "Played for Raptors and in EuroLeague.", ppg: 12.0, rpg: 4.5, apg: 6.0 }],
  2013: [{ slug: "cj-leslie", firstName: "C.J.", lastName: "Leslie", birthYear: 1991, position: "Forward", jerseyNumber: 5, bio: "Junior who declared for draft. #47 pick.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Pro Player", location: "Overseas", statusNote: "Drafted #47 by Celtics.", ppg: 15.0, rpg: 7.5, apg: 1.0 }, { slug: "scott-wood-ncst", firstName: "Scott", lastName: "Wood", birthYear: 1990, position: "Guard", jerseyNumber: 15, bio: "Senior. NC State's all-time 3-pt leader.", occupationType: "OTHER", currentTitle: "Professional", location: "NC", statusNote: "NC State career 3-point record.", ppg: 13.0, rpg: 2.0, apg: 1.5 }, { slug: "lorenzo-brown", firstName: "Lorenzo", lastName: "Brown", birthYear: 1990, position: "Guard", jerseyNumber: 2, bio: "Senior captain and floor general.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Pro Player", location: "Overseas", statusNote: "Played for Raptors and in EuroLeague.", ppg: 13.0, rpg: 5.0, apg: 6.5 }],
  2014: [{ slug: "tj-warren", firstName: "T.J.", lastName: "Warren", birthYear: 1993, position: "Forward", jerseyNumber: 24, bio: "Sophomore ACC POY who was #14 pick. Scored 24+ PPG.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Forward", location: "United States", statusNote: "#14 pick by Suns. Averaged 50 PPG in NBA bubble. Injuries derailed career. Comeback attempts ongoing.", ppg: 24.9, rpg: 7.1, apg: 1.5 }],
  2015: [{ slug: "ralston-turner", firstName: "Ralston", lastName: "Turner", birthYear: 1992, position: "Guard", jerseyNumber: 22, bio: "Senior guard. LSU transfer who led NC State scoring.", occupationType: "OTHER", currentTitle: "Professional", location: "United States", statusNote: "Played overseas briefly after NC State.", ppg: 12.0, rpg: 3.0, apg: 1.5 }, { slug: "trevor-lacey", firstName: "Trevor", lastName: "Lacey", birthYear: 1993, position: "Guard", jerseyNumber: 1, bio: "Junior guard. Alabama transfer who was team's go-to scorer.", occupationType: "RETIRED_ATHLETE", currentTitle: "Professional", location: "United States", statusNote: "Played overseas briefly.", ppg: 15.5, rpg: 3.5, apg: 2.5 }],
  2016: [{ slug: "dennis-smith-jr", firstName: "Dennis", lastName: "Smith Jr.", birthYear: 1997, position: "Point Guard", jerseyNumber: 4, bio: "5-star freshman who was #9 pick in 2017. Electric athlete.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Guard", location: "United States", statusNote: "#9 pick by Mavericks. Played for Mavs, Knicks, Pistons, Nets, Hornets, Trail Blazers. Career affected by injuries.", ppg: 18.1, rpg: 4.6, apg: 6.2 }],
  2017: [{ slug: "dennis-smith-jr", firstName: "Dennis", lastName: "Smith Jr.", birthYear: 1997, position: "Point Guard", jerseyNumber: 4, bio: "One-and-done star. #9 pick who electrified Raleigh.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Guard", location: "United States", statusNote: "#9 pick by Mavericks in 2017. NBA career ongoing.", ppg: 18.1, rpg: 4.6, apg: 6.2 }],
  2018: [{ slug: "markell-johnson", firstName: "Markell", lastName: "Johnson", birthYear: 1997, position: "Guard", jerseyNumber: 11, bio: "Sophomore guard who became team's primary playmaker under Keatts.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Pro Player", location: "Overseas", statusNote: "Played overseas after NC State.", ppg: 12.5, rpg: 3.5, apg: 4.5 }, { slug: "torin-dorn", firstName: "Torin", lastName: "Dorn", birthYear: 1996, position: "Guard", jerseyNumber: 2, bio: "Junior guard and team leader.", occupationType: "OTHER", currentTitle: "Professional", location: "NC", statusNote: "Played overseas briefly.", ppg: 14.0, rpg: 5.0, apg: 2.0 }],
  2019: [{ slug: "markell-johnson", firstName: "Markell", lastName: "Johnson", birthYear: 1997, position: "Guard", jerseyNumber: 11, bio: "Junior floor general.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Pro Player", location: "Overseas", statusNote: "NC State's primary playmaker for 3 years.", ppg: 12.0, rpg: 3.0, apg: 5.0 }],
  2020: [{ slug: "markell-johnson", firstName: "Markell", lastName: "Johnson", birthYear: 1997, position: "Guard", jerseyNumber: 11, bio: "Senior captain.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Pro Player", location: "Overseas", statusNote: "4-year starter. Went overseas after graduation.", ppg: 13.0, rpg: 3.5, apg: 5.5 }, { slug: "devon-daniels", firstName: "Devon", lastName: "Daniels", birthYear: 1998, position: "Guard", jerseyNumber: 24, bio: "Junior guard and athletic scorer.", occupationType: "OTHER", currentTitle: "Professional", location: "United States", statusNote: "Career cut short by knee injury.", ppg: 13.0, rpg: 4.0, apg: 1.5 }],
  2021: [{ slug: "devon-daniels", firstName: "Devon", lastName: "Daniels", birthYear: 1998, position: "Guard", jerseyNumber: 24, bio: "Senior who suffered season-ending knee injury.", occupationType: "OTHER", currentTitle: "Professional", location: "United States", statusNote: "Knee injury ended college career early.", ppg: 0.0, rpg: 0.0, apg: 0.0 }, { slug: "dereon-seabron", firstName: "Dereon", lastName: "Seabron", birthYear: 2000, position: "Guard", jerseyNumber: 1, bio: "Sophomore guard who became team's top scorer.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Guard", location: "United States", statusNote: "Signed two-way with Pelicans. G League standout.", ppg: 9.5, rpg: 4.0, apg: 2.5 }],
  2022: [{ slug: "dereon-seabron", firstName: "Dereon", lastName: "Seabron", birthYear: 2000, position: "Guard", jerseyNumber: 1, bio: "Junior who led team in scoring. Two-way with Pelicans.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Guard", location: "United States", statusNote: "Signed two-way with New Orleans Pelicans.", ppg: 17.5, rpg: 6.5, apg: 3.5 }, { slug: "terquavion-smith", firstName: "Terquavion", lastName: "Smith", birthYear: 2003, position: "Guard", jerseyNumber: 0, bio: "Freshman sensation and NC Mr. Basketball.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Guard", location: "United States", statusNote: "Selected in 2023 NBA Draft. NC's Mr. Basketball in 2022.", ppg: 16.0, rpg: 3.5, apg: 2.5 }],
  2023: [{ slug: "terquavion-smith", firstName: "Terquavion", lastName: "Smith", birthYear: 2003, position: "Guard", jerseyNumber: 0, bio: "Sophomore star who declared for 2023 NBA Draft.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Guard", location: "United States", statusNote: "2023 NBA Draft pick. Dynamic scorer.", ppg: 17.5, rpg: 4.0, apg: 3.0 }, { slug: "jarkel-joiner", firstName: "Jarkel", lastName: "Joiner", birthYear: 1999, position: "Guard", jerseyNumber: 1, bio: "Grad transfer from Ole Miss.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Pro Player", location: "Overseas", statusNote: "Played overseas after NC State.", ppg: 14.5, rpg: 3.0, apg: 2.5 }],
  2025: [{ slug: "jayden-taylor-ncst", firstName: "Jayden", lastName: "Taylor", birthYear: 2002, position: "Guard", jerseyNumber: 1, bio: "Return contributor from 2024 Final Four squad.", occupationType: "STUDENT", currentTitle: "College Player", location: "Raleigh, NC", statusNote: "Key returnee from 2024 Final Four.", ppg: 12.0, rpg: 3.0, apg: 2.0 }, { slug: "dennis-parker-jr", firstName: "Dennis", lastName: "Parker Jr.", birthYear: 2004, position: "Guard", jerseyNumber: 3, bio: "Sophomore guard and developing talent.", occupationType: "STUDENT", currentTitle: "College Player", location: "Raleigh, NC", statusNote: "Growing into larger role after Final Four.", ppg: 8.5, rpg: 3.0, apg: 2.5 }],
};

// ── SYRACUSE ──
const syracuse: Record<number, Player[]> = {
  2009: [{ slug: "jonny-flynn", firstName: "Jonny", lastName: "Flynn", birthYear: 1989, position: "Point Guard", jerseyNumber: 10, bio: "Sophomore star who was #6 pick. Led Cuse to NCAA Tourney.", occupationType: "RETIRED_ATHLETE", currentTitle: "Retired", location: "United States", statusNote: "#6 pick by Timberwolves in 2009. Career derailed by hip injuries after 3 NBA seasons.", ppg: 17.4, rpg: 3.0, apg: 6.7 }, { slug: "eric-devendorf", firstName: "Eric", lastName: "Devendorf", birthYear: 1987, position: "Guard", jerseyNumber: 23, bio: "Senior guard and team's emotional leader.", occupationType: "RETIRED_ATHLETE", currentTitle: "Professional", location: "United States", statusNote: "Played overseas after Syracuse.", ppg: 14.5, rpg: 2.5, apg: 2.5 }],
  2010: [{ slug: "wes-johnson", firstName: "Wes", lastName: "Johnson", birthYear: 1987, position: "Forward", jerseyNumber: 4, bio: "Syracuse transfer who was #4 pick in 2010.", occupationType: "RETIRED_ATHLETE", currentTitle: "Retired NBA Player", location: "United States", statusNote: "#4 overall pick by Timberwolves. 9 NBA seasons.", ppg: 16.5, rpg: 6.0, apg: 2.0 }, { slug: "andy-rautins", firstName: "Andy", lastName: "Rautins", birthYear: 1986, position: "Guard", jerseyNumber: 1, bio: "Senior sharpshooter. Canadian national team member.", occupationType: "RETIRED_ATHLETE", currentTitle: "Professional", location: "Canada", statusNote: "Played for Knicks and overseas. Son of Syracuse legend Leo Rautins.", ppg: 12.0, rpg: 3.0, apg: 4.0 }],
  2011: [{ slug: "kris-joseph", firstName: "Kris", lastName: "Joseph", birthYear: 1988, position: "Forward", jerseyNumber: 32, bio: "Junior forward from Montreal.", occupationType: "RETIRED_ATHLETE", currentTitle: "Professional", location: "Canada", statusNote: "Played for Celtics and overseas. Canadian national team.", ppg: 14.0, rpg: 4.5, apg: 1.5 }, { slug: "scoop-jardine", firstName: "Scoop", lastName: "Jardine", birthYear: 1989, position: "Guard", jerseyNumber: 11, bio: "Junior point guard and floor general.", occupationType: "RETIRED_ATHLETE", currentTitle: "Professional", location: "United States", statusNote: "Played overseas after Syracuse.", ppg: 10.0, rpg: 3.0, apg: 4.5 }],
  2012: [{ slug: "kris-joseph", firstName: "Kris", lastName: "Joseph", birthYear: 1988, position: "Forward", jerseyNumber: 32, bio: "Senior captain. Drafted by Celtics.", occupationType: "RETIRED_ATHLETE", currentTitle: "Professional", location: "Canada", statusNote: "Played for Celtics and overseas.", ppg: 14.5, rpg: 5.0, apg: 2.0 }, { slug: "dion-waiters", firstName: "Dion", lastName: "Waiters", birthYear: 1991, position: "Guard", jerseyNumber: 3, bio: "Sophomore star. #4 pick in 2012.", occupationType: "RETIRED_ATHLETE", currentTitle: "Retired NBA Player", location: "Philadelphia, PA", statusNote: "#4 pick by Cavs. 8 NBA seasons. Won 2020 NBA title with Lakers.", ppg: 12.5, rpg: 2.5, apg: 2.5 }, { slug: "fab-melo", firstName: "Fab", lastName: "Melo", birthYear: 1990, position: "Center", jerseyNumber: 51, bio: "Sophomore center. #22 pick. Tragically passed away in 2017.", occupationType: "OTHER", currentTitle: "Deceased", location: "Brazil", statusNote: "Selected #22 by Celtics in 2012. Tragically died in 2017 at age 26 in Brazil.", ppg: 7.8, rpg: 5.8, apg: 0.3 }],
  2014: [{ slug: "tyler-ennis", firstName: "Tyler", lastName: "Ennis", birthYear: 1994, position: "Point Guard", jerseyNumber: 11, bio: "Canadian freshman who was #18 pick after one season.", occupationType: "RETIRED_ATHLETE", currentTitle: "Retired", location: "Canada", statusNote: "#18 pick by Suns in 2014. Brief NBA career, played overseas.", ppg: 12.9, rpg: 3.4, apg: 5.5 }, { slug: "jerami-grant", firstName: "Jerami", lastName: "Grant", birthYear: 1994, position: "Forward", jerseyNumber: 3, bio: "Sophomore. Future All-Star and $160M contract.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Forward", location: "Portland, OR", statusNote: "NBA All-Star 2021. $160M contract with Trail Blazers.", ppg: 12.0, rpg: 6.0, apg: 1.0 }],
  2015: [{ slug: "rakeem-christmas", firstName: "Rakeem", lastName: "Christmas", birthYear: 1991, position: "Center", jerseyNumber: 25, bio: "Senior center. ACC DPOY. #36 pick.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Pro Player", location: "Europe", statusNote: "ACC DPOY. Drafted #36 by Pacers. Long overseas career.", ppg: 17.5, rpg: 9.0, apg: 1.5 }, { slug: "michael-gbinije", firstName: "Michael", lastName: "Gbinije", birthYear: 1993, position: "Guard/Forward", jerseyNumber: 0, bio: "Junior guard. Duke transfer who became team leader.", occupationType: "RETIRED_ATHLETE", currentTitle: "Retired", location: "Connecticut", statusNote: "Duke transfer. Played for Pistons briefly.", ppg: 11.0, rpg: 3.5, apg: 3.0 }],
  2017: [{ slug: "john-gillon", firstName: "John", lastName: "Gillon", birthYear: 1993, position: "Guard", jerseyNumber: 4, bio: "Grad transfer who provided veteran backcourt play.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Pro Player", location: "Overseas", statusNote: "Played overseas in Israel, Greece, and Italy.", ppg: 11.0, rpg: 2.0, apg: 5.0 }, { slug: "andrew-white-iii", firstName: "Andrew", lastName: "White III", birthYear: 1993, position: "Forward", jerseyNumber: 3, bio: "Grad transfer and team's leading scorer.", occupationType: "RETIRED_ATHLETE", currentTitle: "Professional", location: "United States", statusNote: "Played overseas after Syracuse.", ppg: 18.5, rpg: 5.0, apg: 1.0 }],
  2018: [{ slug: "tyus-battle", firstName: "Tyus", lastName: "Battle", birthYear: 1997, position: "Guard", jerseyNumber: 25, bio: "Sophomore guard and team's best scorer.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Pro Player", location: "Overseas", statusNote: "3-year starter. Played overseas after Syracuse.", ppg: 19.2, rpg: 3.0, apg: 2.0 }, { slug: "oshae-brissett", firstName: "Oshae", lastName: "Brissett", birthYear: 1998, position: "Forward", jerseyNumber: 11, bio: "Freshman forward from Canada.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Forward", location: "United States", statusNote: "Played for Pacers and Celtics. NBA career ongoing.", ppg: 14.0, rpg: 7.0, apg: 1.5 }],
  2019: [{ slug: "tyus-battle", firstName: "Tyus", lastName: "Battle", birthYear: 1997, position: "Guard", jerseyNumber: 25, bio: "Junior captain and leading scorer.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Pro Player", location: "Overseas", statusNote: "3-year starter. Played overseas.", ppg: 17.0, rpg: 3.0, apg: 2.0 }, { slug: "oshae-brissett", firstName: "Oshae", lastName: "Brissett", birthYear: 1998, position: "Forward", jerseyNumber: 11, bio: "Sophomore forward.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Forward", location: "United States", statusNote: "NBA career with Pacers and Celtics.", ppg: 12.5, rpg: 7.0, apg: 1.5 }],
  2020: [{ slug: "elijah-hughes", firstName: "Elijah", lastName: "Hughes", birthYear: 1998, position: "Guard/Forward", jerseyNumber: 33, bio: "Junior wing. Team's leading scorer and All-ACC.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Pro Player", location: "Overseas", statusNote: "Drafted by Jazz. Played in G League and overseas.", ppg: 19.0, rpg: 5.0, apg: 3.5 }],
  2021: [{ slug: "buddy-boeheim", firstName: "Buddy", lastName: "Boeheim", birthYear: 1999, position: "Guard", jerseyNumber: 35, bio: "Junior. Coach Boeheim's son. Elite 3-point shooter.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Pro Player", location: "Overseas", statusNote: "Jim Boeheim's son. Played for Pistons briefly. Now overseas. Legendary tournament shooter.", ppg: 17.5, rpg: 3.0, apg: 1.5 }],
  2022: [{ slug: "buddy-boeheim", firstName: "Buddy", lastName: "Boeheim", birthYear: 1999, position: "Guard", jerseyNumber: 35, bio: "Senior. Coach's son and team's go-to scorer.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Pro Player", location: "Overseas", statusNote: "Boeheim's son. Played for Pistons. Now overseas.", ppg: 19.0, rpg: 3.0, apg: 2.0 }, { slug: "joe-girard-iii", firstName: "Joe", lastName: "Girard III", birthYear: 2000, position: "Guard", jerseyNumber: 11, bio: "Junior guard. NY state scoring record holder.", occupationType: "STUDENT", currentTitle: "College Player", location: "United States", statusNote: "NY state HS scoring record. Transferred to Alabama.", ppg: 14.0, rpg: 3.0, apg: 3.5 }],
  2023: [{ slug: "judah-mintz", firstName: "Judah", lastName: "Mintz", birthYear: 2003, position: "Guard", jerseyNumber: 3, bio: "Freshman sensation who became team's go-to scorer.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Guard", location: "United States", statusNote: "Selected in 2024 NBA Draft after sophomore season.", ppg: 17.0, rpg: 3.5, apg: 5.0 }],
  2024: [{ slug: "judah-mintz", firstName: "Judah", lastName: "Mintz", birthYear: 2003, position: "Guard", jerseyNumber: 3, bio: "Sophomore star. Declared for 2024 NBA Draft.", occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Guard", location: "United States", statusNote: "2024 NBA Draft pick. Dynamic scorer and playmaker.", ppg: 19.5, rpg: 4.0, apg: 6.0 }],
  2025: [{ slug: "jj-starling", firstName: "J.J.", lastName: "Starling", birthYear: 2003, position: "Guard", jerseyNumber: 2, bio: "Notre Dame transfer. Team's top scorer under Adrian Autry.", occupationType: "STUDENT", currentTitle: "College Player", location: "Syracuse, NY", statusNote: "Notre Dame transfer providing scoring.", ppg: 15.0, rpg: 3.0, apg: 2.5 }],
};

function processSchool(schoolSlug: string, data: Record<number, Player[]>) {
  let total = 0;
  for (const [yearStr, players] of Object.entries(data)) {
    const year = parseInt(yearStr);
    const filename = `${schoolSlug}-basketball-${year}.ts`;
    const filepath = path.join(SEEDS_DIR, filename);
    if (!fs.existsSync(filepath)) continue;
    const content = fs.readFileSync(filepath, "utf-8");
    const nameMatch = content.match(/name: "([^"]+)"/);
    const seasonMatch = content.match(/season: "([^"]+)"/);
    if (!nameMatch || !seasonMatch) continue;
    const added = insertPlayers(filepath, players, nameMatch[1], seasonMatch[2]);
    if (added > 0) { console.log(`  ${filename} — +${added}`); total += added; }
  }
  return total;
}

let grandTotal = 0;

console.log("NC State:");
grandTotal += processSchool("ncstate", ncstate);

console.log("Syracuse:");
grandTotal += processSchool("syracuse", syracuse);

console.log(`\nDone. Added ${grandTotal} players total.`);
