import type { PersonSeed } from "../seed";

export function getAlabamaPeople(): PersonSeed[] {
  return [
    // ── Coaches ────────────────────────────────────────────────────────────
    {
      slug: "nick-saban",
      firstName: "Nick",
      lastName: "Saban",
      birthYear: 1951,
      hometown: "Fairmont, WV",
      highSchool: "Monongah High School, Fairmont, WV",
      isFeatured: true,
      imageUrl: "https://a.espncdn.com/combiner/i?img=/i/headshots/college-football/players/full/3114591.png",
      bio: "Legendary head coach who led Alabama to six national championships including the 2015 CFP title over Clemson. Retired in January 2024 as the most decorated coach in college football history with a 292-71-1 career record.",
      status: {
        occupationType: "BROADCASTER_ANALYST",
        currentTitle: "College Football Analyst",
        currentEmployer: "ESPN",
        location: "Tuscaloosa, AL",
        statusNote:
          "After retiring in January 2024 following 17 seasons at Alabama, Saban joined ESPN as an analyst on College GameDay. He also holds an advisory role with the Alabama athletics department. Inducted into the College Football Hall of Fame in 2025. His influence remains enormous — five of twelve 2025-26 CFP teams were coached by his former assistants. He also co-owns Saban's Dream Motor Group, which acquired two Mercedes-Benz dealerships in Miami.",
        sourceUrl: "https://en.wikipedia.org/wiki/Nick_Saban",
      },
      membership: {
        role: "HEAD_COACH",
        position: "Head Coach",
        yearsAtSchool: "2007-2024",
        statsNote: "14-1 record in 2015 · CFP National Champions · 6 National Championships at Alabama",
      },
      careerEvents: [
        { year: 2007, title: "Named Head Coach at Alabama", eventType: "COACHING", detail: "Left Miami Dolphins to take over at Alabama" },
        { year: 2009, title: "Won BCS National Championship", eventType: "CHAMPIONSHIP", detail: "Defeated Texas 37-21" },
        { year: 2011, title: "Won BCS National Championship", eventType: "CHAMPIONSHIP", detail: "Defeated LSU 21-0" },
        { year: 2012, title: "Won BCS National Championship", eventType: "CHAMPIONSHIP", detail: "Defeated Notre Dame 42-14" },
        { year: 2015, title: "Won CFP National Championship", eventType: "CHAMPIONSHIP", detail: "Defeated Clemson 45-40" },
        { year: 2017, title: "Won CFP National Championship", eventType: "CHAMPIONSHIP", detail: "Defeated Georgia 26-23 in OT" },
        { year: 2020, title: "Won CFP National Championship", eventType: "CHAMPIONSHIP", detail: "Defeated Ohio State 52-24" },
        { year: 2024, title: "Retired from coaching", eventType: "RETIREMENT", detail: "Announced retirement after 17 seasons at Alabama" },
        { year: 2024, title: "Joined ESPN as College GameDay analyst", eventType: "CAREER_CHANGE", detail: "Became regular analyst on College GameDay and Pat McAfee Show" },
        { year: 2025, title: "Inducted into College Football Hall of Fame", eventType: "AWARD" },
      ],
    },
    {
      slug: "kirby-smart",
      firstName: "Kirby",
      lastName: "Smart",
      birthYear: 1975,
      hometown: "Montgomery, AL",
      highSchool: "Bainbridge High School, Bainbridge, GA",
      isFeatured: true,
      bio: "Defensive coordinator under Nick Saban at Alabama from 2008-2015, instrumental in building the dominant defenses that powered multiple national championships. Left after the 2015 title to become head coach at Georgia.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Football Coach",
        currentEmployer: "University of Georgia",
        location: "Athens, GA",
        statusNote:
          "Smart left Alabama after the 2015 championship to become head coach at Georgia, where he has built a dynasty of his own. He has won two national championships (2021, 2022) and three SEC titles. In 2024 he signed a 10-year, $130 million extension making him the highest-paid coach in college football. His 109-20 record at Georgia has cemented him as one of the sport's elite coaches.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kirby_Smart",
      },
      membership: {
        role: "ASSISTANT_COACH",
        position: "Defensive Coordinator",
        yearsAtSchool: "2008-2015",
        statsNote: "8 seasons as DC · Oversaw top-10 scoring defenses consistently",
      },
      careerEvents: [
        { year: 2016, title: "Named Head Coach at University of Georgia", eventType: "COACHING", detail: "Left Alabama DC role to lead the Bulldogs" },
        { year: 2021, title: "Won CFP National Championship at Georgia", eventType: "CHAMPIONSHIP", detail: "Defeated Alabama 33-18" },
        { year: 2022, title: "Won back-to-back National Championship", eventType: "CHAMPIONSHIP", detail: "Defeated TCU 65-7" },
        { year: 2024, title: "Signed $130M contract extension", eventType: "CONTRACT", detail: "10-year deal making him highest-paid coach in CFB" },
      ],
    },
    {
      slug: "lane-kiffin",
      firstName: "Lane",
      lastName: "Kiffin",
      birthYear: 1975,
      hometown: "Lincoln, NE",
      highSchool: "Bloomington Jefferson High School, Bloomington, MN",
      bio: "Offensive coordinator at Alabama from 2014-2016, his up-tempo play-calling was critical to the 2015 championship run. Previously served as head coach of the Oakland Raiders and USC.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Football Coach",
        currentEmployer: "LSU",
        location: "Baton Rouge, LA",
        statusNote:
          "After serving as Alabama's OC through the 2016 season, Kiffin became head coach at FAU (2017-2019) and then Ole Miss (2020-2025), compiling a 55-19 record with the Rebels. In November 2025, he accepted the head coaching job at LSU on a 7-year, $91 million deal, departing Ole Miss before their CFP appearance.",
        sourceUrl: "https://en.wikipedia.org/wiki/Lane_Kiffin",
      },
      membership: {
        role: "ASSISTANT_COACH",
        position: "Offensive Coordinator",
        yearsAtSchool: "2014-2016",
        statsNote: "Averaged 35.1 PPG in 2015 · Up-tempo offense innovation",
      },
      careerEvents: [
        { year: 2017, title: "Named Head Coach at FAU", eventType: "COACHING", detail: "Went 26-13 in three seasons" },
        { year: 2020, title: "Named Head Coach at Ole Miss", eventType: "COACHING", detail: "Revitalized the program with 55-19 record" },
        { year: 2025, title: "Named Head Coach at LSU", eventType: "COACHING", detail: "Signed 7-year, $91 million deal" },
      ],
    },
    // ── Players ────────────────────────────────────────────────────────────
    {
      slug: "derrick-henry",
      firstName: "Derrick",
      lastName: "Henry",
      birthYear: 1994,
      hometown: "Yulee, FL",
      highSchool: "Yulee High School, Yulee, FL",
      isFeatured: true,
      imageUrl: "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3043078.png",
      bio: "Heisman Trophy-winning running back who rushed for 2,219 yards and 28 touchdowns in 2015, leading the nation in both categories. His dominant performance powered Alabama to the CFP National Championship.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Running Back",
        currentEmployer: "Baltimore Ravens",
        league: "NFL",
        location: "Baltimore, MD",
        statusNote:
          "Selected 45th overall by the Tennessee Titans in the 2016 NFL Draft, Henry became one of the greatest running backs in NFL history. He won the NFL rushing title in 2019 and 2020, including a 2,000-yard season in 2020. After eight seasons in Tennessee, he signed with the Baltimore Ravens in 2024 and rushed for 1,921 yards in his first season. In 2025 he signed a 2-year, $30 million extension and rushed for 1,595 yards with 16 touchdowns. He is the NFL's active leader in career rushing yards, ranking tenth all-time.",
        sourceUrl: "https://en.wikipedia.org/wiki/Derrick_Henry",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 2,
        position: "Running Back",
        yearsAtSchool: "2013-2015",
        statsNote: "Heisman Trophy · 2,219 rush yards · 28 TDs · Doak Walker Award · Maxwell Award",
        gamesPlayed: 15,
      },
      careerEvents: [
        { year: 2015, title: "Won Heisman Trophy", eventType: "AWARD", detail: "Led nation with 2,219 rushing yards and 28 TDs" },
        { year: 2016, title: "Drafted by Tennessee Titans (2nd round, #45)", eventType: "DRAFT", detail: "Selected in 2nd round of NFL Draft" },
        { year: 2019, title: "Won NFL Rushing Title", eventType: "AWARD", detail: "1,540 rushing yards" },
        { year: 2020, title: "Rushed for 2,000 yards", eventType: "MILESTONE", detail: "Became 8th player in NFL history to rush for 2,000 yards in a season" },
        { year: 2024, title: "Signed with Baltimore Ravens", eventType: "SIGNING", detail: "Joined Ravens as free agent" },
        { year: 2025, title: "Signed 2-year, $30M extension with Ravens", eventType: "CONTRACT", detail: "Committed long-term to Baltimore" },
      ],
    },
    {
      slug: "jake-coker",
      firstName: "Jake",
      lastName: "Coker",
      birthYear: 1992,
      hometown: "Mobile, AL",
      highSchool: "St. Paul's Episcopal School, Mobile, AL",
      bio: "Graduate transfer quarterback from Florida State who started all 15 games in 2015, throwing for over 3,000 yards and 21 touchdowns to lead Alabama to the national championship.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Commercial Insurance Professional",
        currentEmployer: "BancorpSouth",
        location: "Mobile, AL",
        statusNote:
          "After going undrafted in 2016, Coker signed as a free agent with the Arizona Cardinals but knee surgeries hampered his career. He retired from football in 2017 and returned to Mobile where he works in commercial insurance at BancorpSouth. He married Sarah Jeffries in 2019 and they welcomed their first child in January 2020. He remains closely connected to Alabama football as a media commentator and beloved alumnus.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jake_Coker",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 14,
        position: "Quarterback",
        yearsAtSchool: "2015",
        statsNote: "3,000+ passing yards · 21 TDs · 15-0 as starter · CFP Champion",
        gamesPlayed: 15,
      },
      careerEvents: [
        { year: 2016, title: "Signed as UDFA with Arizona Cardinals", eventType: "SIGNING" },
        { year: 2017, title: "Retired from professional football", eventType: "RETIREMENT", detail: "Knee injuries ended NFL pursuit" },
        { year: 2017, title: "Began career in commercial insurance", eventType: "CAREER_CHANGE", detail: "Joined BancorpSouth in Mobile, AL" },
      ],
    },
    {
      slug: "calvin-ridley",
      firstName: "Calvin",
      lastName: "Ridley",
      birthYear: 1994,
      hometown: "Fort Lauderdale, FL",
      highSchool: "Monarch High School, Coconut Creek, FL",
      isFeatured: true,
      imageUrl: "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3925357.png",
      bio: "True freshman wide receiver who made an immediate impact with 68 catches for 1,045 yards and 7 touchdowns in 2015, leading the team in receiving. Went on to become a first-round NFL draft pick.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Wide Receiver",
        currentEmployer: "Tennessee Titans",
        league: "NFL",
        location: "Nashville, TN",
        statusNote:
          "Selected 26th overall by the Atlanta Falcons in the 2018 NFL Draft, Ridley earned second-team All-Pro in 2020 with 1,374 receiving yards. After a gambling suspension in 2022, he was traded to Jacksonville and then signed a 4-year, $92 million contract with the Tennessee Titans in 2024, posting 1,017 receiving yards in his debut season. Injuries limited his 2025 season to seven games, but he restructured his deal to remain in Tennessee for 2026.",
        sourceUrl: "https://en.wikipedia.org/wiki/Calvin_Ridley",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 3,
        position: "Wide Receiver",
        yearsAtSchool: "2015-2017",
        statsNote: "68 catches · 1,045 yards · 7 TDs as freshman · Led team in receiving",
        gamesPlayed: 15,
      },
      careerEvents: [
        { year: 2018, title: "Drafted by Atlanta Falcons (1st round, #26)", eventType: "DRAFT" },
        { year: 2020, title: "Earned 2nd-team All-Pro", eventType: "AWARD", detail: "1,374 receiving yards and 9 TDs" },
        { year: 2023, title: "Traded to Jacksonville Jaguars", eventType: "TRADE" },
        { year: 2024, title: "Signed 4-year, $92M deal with Tennessee Titans", eventType: "CONTRACT" },
      ],
    },
    {
      slug: "kenyan-drake",
      firstName: "Kenyan",
      lastName: "Drake",
      birthYear: 1994,
      hometown: "Powder Springs, GA",
      highSchool: "Hillgrove High School, Powder Springs, GA",
      bio: "Versatile running back who complemented Derrick Henry in the Alabama backfield. Known for his speed and receiving ability, he was a key contributor on the 2015 championship team.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NFL Running Back",
        location: "Atlanta, GA",
        statusNote:
          "Selected in the 3rd round by the Miami Dolphins in 2016, Drake played eight NFL seasons with the Dolphins, Cardinals, Raiders, Ravens, and Packers. He is best remembered for the 'Miracle in Miami' — a 52-yard walk-off touchdown on a lateral play in 2018. He compiled 5,521 yards from scrimmage and 41 total touchdowns before retiring in July 2024.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kenyan_Drake",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 17,
        position: "Running Back",
        yearsAtSchool: "2012-2015",
        statsNote: "Complementary back to Derrick Henry · Key pass-catching RB",
        gamesPlayed: 15,
      },
      careerEvents: [
        { year: 2016, title: "Drafted by Miami Dolphins (3rd round, #73)", eventType: "DRAFT" },
        { year: 2018, title: "'Miracle in Miami' walk-off touchdown", eventType: "MILESTONE", detail: "52-yard TD on a lateral play to beat the Patriots" },
        { year: 2020, title: "Career-high 955 rushing yards with Cardinals", eventType: "MILESTONE" },
        { year: 2024, title: "Retired from NFL", eventType: "RETIREMENT", detail: "Retired after eight seasons" },
      ],
    },
    {
      slug: "ryan-kelly-al",
      firstName: "Ryan",
      lastName: "Kelly",
      birthYear: 1994,
      hometown: "West Chester, OH",
      highSchool: "Lakota West High School, West Chester, OH",
      bio: "Dominant center who won the Remington Trophy as the nation's best center in 2015. Anchored the offensive line that paved the way for Derrick Henry's Heisman season and Alabama's championship run.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NFL Center",
        location: "Indianapolis, IN",
        statusNote:
          "Selected 18th overall by the Indianapolis Colts in the 2016 NFL Draft, Kelly became an immediate starter and was elected to four Pro Bowls. He spent nine seasons in Indianapolis before signing with the Minnesota Vikings in 2025, where concussion issues led to him retiring in March 2026 after 10 NFL seasons and 129 career starts. He won three national championships at Alabama (2011, 2012, 2015).",
        sourceUrl: "https://en.wikipedia.org/wiki/Ryan_Kelly_(American_football)",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 70,
        position: "Center",
        yearsAtSchool: "2012-2015",
        statsNote: "Remington Trophy · Jacobs Blocking Trophy · Rimington Trophy finalist · Consensus All-American",
        gamesPlayed: 15,
      },
      careerEvents: [
        { year: 2016, title: "Drafted by Indianapolis Colts (1st round, #18)", eventType: "DRAFT" },
        { year: 2020, title: "Signed 4-year, $50M extension with Colts", eventType: "CONTRACT", detail: "Became highest-paid center in NFL" },
        { year: 2021, title: "Named to Pro Bowl", eventType: "AWARD" },
        { year: 2025, title: "Signed with Minnesota Vikings", eventType: "SIGNING" },
        { year: 2026, title: "Retired from NFL", eventType: "RETIREMENT", detail: "Retired due to concussion history after 10 seasons" },
      ],
    },
    {
      slug: "reggie-ragland",
      firstName: "Reggie",
      lastName: "Ragland",
      birthYear: 1993,
      hometown: "Madison, AL",
      highSchool: "Bob Jones High School, Madison, AL",
      bio: "First-team All-American linebacker and SEC Defensive Player of the Year in 2015. Recorded 102 tackles, 7 TFLs, and 2.5 sacks while leading the defense to a championship.",
      status: {
        occupationType: "COACH",
        currentTitle: "Director of Player Personnel",
        currentEmployer: "University of West Alabama",
        location: "Livingston, AL",
        statusNote:
          "Selected by the Buffalo Bills in the 2nd round of the 2016 Draft, Ragland missed his rookie year with a torn ACL. He was traded to the Kansas City Chiefs in 2017 and won Super Bowl LIV. Over six NFL seasons with the Bills, Chiefs, Lions, Giants, Raiders, and Browns, he totaled 293 tackles. In March 2025, he was hired as Director of Player Personnel at the University of West Alabama under former Alabama strength coach Scott Cochran.",
        sourceUrl: "https://en.wikipedia.org/wiki/Reggie_Ragland",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 19,
        position: "Linebacker",
        yearsAtSchool: "2012-2015",
        statsNote: "SEC Defensive Player of the Year · 1st-team All-American · 102 tackles · 7 TFL",
        gamesPlayed: 15,
      },
      careerEvents: [
        { year: 2016, title: "Drafted by Buffalo Bills (2nd round, #41)", eventType: "DRAFT" },
        { year: 2017, title: "Traded to Kansas City Chiefs", eventType: "TRADE" },
        { year: 2020, title: "Won Super Bowl LIV with Chiefs", eventType: "CHAMPIONSHIP" },
        { year: 2025, title: "Hired as Dir. of Player Personnel at West Alabama", eventType: "CAREER_CHANGE" },
      ],
    },
    {
      slug: "ashawn-robinson",
      firstName: "A'Shawn",
      lastName: "Robinson",
      birthYear: 1995,
      hometown: "Fort Worth, TX",
      highSchool: "Arlington Heights High School, Fort Worth, TX",
      bio: "Consensus All-American defensive lineman who was a dominant force on Alabama's championship defense. Started 29 games over two seasons and was a cornerstone of the 2015 title run.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Defensive End",
        currentEmployer: "Tampa Bay Buccaneers",
        league: "NFL",
        location: "Tampa, FL",
        statusNote:
          "Selected in the 2nd round by the Detroit Lions in 2016, Robinson has played 10 NFL seasons with the Lions, Rams, Giants, and Panthers. He won Super Bowl LVI with the Los Angeles Rams. After a career-high 80 tackles and 5.5 sacks with Carolina in 2024, he signed a 1-year, $10 million deal with the Tampa Bay Buccaneers in March 2026, entering his 11th NFL season.",
        sourceUrl: "https://en.wikipedia.org/wiki/A%27Shawn_Robinson",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 86,
        position: "Defensive Lineman",
        yearsAtSchool: "2013-2015",
        statsNote: "Consensus All-American · 2x SEC Champion · 29 starts",
        gamesPlayed: 15,
      },
      careerEvents: [
        { year: 2016, title: "Drafted by Detroit Lions (2nd round, #46)", eventType: "DRAFT" },
        { year: 2022, title: "Won Super Bowl LVI with Los Angeles Rams", eventType: "CHAMPIONSHIP" },
        { year: 2026, title: "Signed with Tampa Bay Buccaneers", eventType: "SIGNING" },
      ],
    },
    {
      slug: "jarran-reed",
      firstName: "Jarran",
      lastName: "Reed",
      birthYear: 1992,
      hometown: "Goldsboro, NC",
      highSchool: "Goldsboro High School, Goldsboro, NC",
      bio: "Junior college transfer who became a dominant interior defensive lineman. Played in all 15 games in 2015 with 57 tackles, helping anchor the defense in the championship run.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Defensive Tackle",
        currentEmployer: "Seattle Seahawks",
        league: "NFL",
        location: "Seattle, WA",
        statusNote:
          "Selected in the 2nd round by the Seattle Seahawks in 2016, Reed has played 10 NFL seasons primarily with Seattle, plus stints with Kansas City and Green Bay. He posted a career-high 10.5 sacks in 2018. In 2025 he signed a 3-year, $25 million extension with Seattle and won Super Bowl LX with the Seahawks.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jarran_Reed",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 90,
        position: "Defensive Tackle",
        yearsAtSchool: "2014-2015",
        statsNote: "57 tackles · 1 sack · 28 career starts at Alabama",
        gamesPlayed: 15,
      },
      careerEvents: [
        { year: 2016, title: "Drafted by Seattle Seahawks (2nd round, #49)", eventType: "DRAFT" },
        { year: 2018, title: "Career-high 10.5 sacks", eventType: "MILESTONE" },
        { year: 2025, title: "Signed 3-year, $25M extension with Seahawks", eventType: "CONTRACT" },
        { year: 2025, title: "Won Super Bowl LX with Seattle Seahawks", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "jonathan-allen",
      firstName: "Jonathan",
      lastName: "Allen",
      birthYear: 1995,
      hometown: "Ashburn, VA",
      highSchool: "Stone Bridge High School, Ashburn, VA",
      isFeatured: true,
      imageUrl: "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3139477.png",
      bio: "Sophomore defensive lineman in 2015 who developed into one of the best players in college football by 2016, winning numerous defensive player of the year awards. Key contributor to the 2015 championship defense.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Defensive Tackle",
        currentEmployer: "Cincinnati Bengals",
        league: "NFL",
        location: "Cincinnati, OH",
        statusNote:
          "Selected 17th overall by Washington in the 2017 NFL Draft, Allen became a two-time Pro Bowl selection and recorded 42 career sacks in eight seasons with the Commanders. Released in March 2025, he signed a 3-year, $51 million deal with the Minnesota Vikings and started all 17 games in 2025 with 3.5 sacks. He then signed a 2-year, $28 million deal with the Cincinnati Bengals for 2026.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jonathan_Allen",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 93,
        position: "Defensive End",
        yearsAtSchool: "2013-2016",
        statsNote: "Key rotational player in 2015 · Won multiple awards in 2016",
        gamesPlayed: 15,
      },
      careerEvents: [
        { year: 2017, title: "Drafted by Washington (1st round, #17)", eventType: "DRAFT" },
        { year: 2021, title: "Named to Pro Bowl", eventType: "AWARD" },
        { year: 2025, title: "Signed 3-year, $51M deal with Minnesota Vikings", eventType: "CONTRACT" },
        { year: 2026, title: "Signed 2-year, $28M deal with Cincinnati Bengals", eventType: "CONTRACT" },
      ],
    },
    {
      slug: "eddie-jackson-al",
      firstName: "Eddie",
      lastName: "Jackson",
      birthYear: 1993,
      hometown: "Lauderdale Lakes, FL",
      highSchool: "Boyd Anderson High School, Lauderdale Lakes, FL",
      bio: "Safety who was a key contributor to the 2015 championship secondary. Known for his ball-hawking ability and versatility on defense.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Safety",
        currentEmployer: "Los Angeles Chargers",
        league: "NFL",
        location: "Los Angeles, CA",
        statusNote:
          "Selected in the 4th round by the Chicago Bears in 2017, Jackson became a First-Team All-Pro in 2018 and made back-to-back Pro Bowls in 2018-2019. After seven seasons in Chicago, he played for Baltimore in 2024 before joining the Los Angeles Chargers. He has recorded 17 career interceptions across nine NFL seasons.",
        sourceUrl: "https://en.wikipedia.org/wiki/Eddie_Jackson_(safety)",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 4,
        position: "Safety",
        yearsAtSchool: "2013-2016",
        statsNote: "Ball-hawking safety · Key member of 2015 championship secondary",
        gamesPlayed: 15,
      },
      careerEvents: [
        { year: 2017, title: "Drafted by Chicago Bears (4th round, #112)", eventType: "DRAFT" },
        { year: 2018, title: "Named First-Team All-Pro", eventType: "AWARD" },
        { year: 2024, title: "Signed with Baltimore Ravens", eventType: "SIGNING" },
        { year: 2025, title: "Joined Los Angeles Chargers", eventType: "SIGNING" },
      ],
    },
    {
      slug: "minkah-fitzpatrick",
      firstName: "Minkah",
      lastName: "Fitzpatrick",
      birthYear: 1996,
      hometown: "Old Bridge, NJ",
      highSchool: "St. Peter's Prep, Jersey City, NJ",
      isFeatured: true,
      imageUrl: "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3925345.png",
      bio: "True freshman defensive back in 2015 who went on to become one of the best safeties in the NFL. Contributed immediately as a freshman on the championship team before becoming a star in 2016 and 2017.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Safety",
        currentEmployer: "New York Jets",
        league: "NFL",
        location: "New York, NY",
        statusNote:
          "Selected 11th overall by the Miami Dolphins in 2018, Fitzpatrick was traded to the Pittsburgh Steelers in 2019 and became a five-time Pro Bowler and three-time First-Team All-Pro. He co-led the NFL with six interceptions in 2022. After being traded to Miami in 2025 and starting 14 games, he was dealt to the New York Jets in March 2026, signing a 3-year, $40 million extension.",
        sourceUrl: "https://en.wikipedia.org/wiki/Minkah_Fitzpatrick",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 29,
        position: "Defensive Back",
        yearsAtSchool: "2015-2017",
        statsNote: "Immediate contributor as true freshman · Won CFP title in first season",
        gamesPlayed: 15,
      },
      careerEvents: [
        { year: 2018, title: "Drafted by Miami Dolphins (1st round, #11)", eventType: "DRAFT" },
        { year: 2019, title: "Traded to Pittsburgh Steelers", eventType: "TRADE" },
        { year: 2022, title: "Co-led NFL with 6 interceptions", eventType: "MILESTONE" },
        { year: 2025, title: "Traded to Miami Dolphins", eventType: "TRADE" },
        { year: 2026, title: "Traded to New York Jets, signed 3-year $40M deal", eventType: "CONTRACT" },
      ],
    },
    {
      slug: "marlon-humphrey",
      firstName: "Marlon",
      lastName: "Humphrey",
      birthYear: 1996,
      hometown: "Hoover, AL",
      highSchool: "Hoover High School, Hoover, AL",
      imageUrl: "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/3126356.png",
      bio: "True freshman cornerback in 2015 who contributed immediately to the championship secondary. Son of former NFL running back Bobby Humphrey, he developed into one of the premier corners in the NFL.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Cornerback",
        currentEmployer: "Baltimore Ravens",
        league: "NFL",
        location: "Baltimore, MD",
        statusNote:
          "Selected 16th overall by the Baltimore Ravens in the 2017 NFL Draft, Humphrey has been a cornerstone of their defense for nine seasons. He has been named to multiple Pro Bowls and is one of the league's most consistent cornerbacks. In 2025, he led the Ravens in interceptions with four while adding 61 tackles across 14 games. He enters 2026 in the final year of his contract with a $26.3 million cap hit.",
        sourceUrl: "https://en.wikipedia.org/wiki/Marlon_Humphrey",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 26,
        position: "Cornerback",
        yearsAtSchool: "2015-2016",
        statsNote: "Immediate contributor as true freshman · Championship secondary member",
        gamesPlayed: 15,
      },
      careerEvents: [
        { year: 2017, title: "Drafted by Baltimore Ravens (1st round, #16)", eventType: "DRAFT" },
        { year: 2019, title: "Named to Pro Bowl", eventType: "AWARD" },
        { year: 2020, title: "Named First-Team All-Pro", eventType: "AWARD" },
      ],
    },
    {
      slug: "daron-payne",
      firstName: "Daron",
      lastName: "Payne",
      birthYear: 1997,
      hometown: "Birmingham, AL",
      highSchool: "Shades Valley High School, Irondale, AL",
      bio: "Five-star recruit who enrolled as a true freshman in 2015 and contributed on the defensive line. Went on to win another championship in 2017 before becoming a first-round NFL pick.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Defensive Tackle",
        currentEmployer: "Washington Commanders",
        league: "NFL",
        location: "Washington, D.C.",
        statusNote:
          "Selected 13th overall by Washington in the 2018 NFL Draft, Payne has been one of the most consistent interior defenders in the league. He signed a 4-year, $90 million extension in 2023 and has recorded at least 3.0 sacks in six straight seasons. He enters 2026 in the final year of his contract with the biggest cap hit on the team at $26.17 million.",
        sourceUrl: "https://en.wikipedia.org/wiki/Daron_Payne",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 94,
        position: "Defensive Tackle",
        yearsAtSchool: "2015-2017",
        statsNote: "Five-star recruit · Contributed as true freshman · Won 2 national titles",
        gamesPlayed: 10,
      },
      careerEvents: [
        { year: 2018, title: "Drafted by Washington (1st round, #13)", eventType: "DRAFT" },
        { year: 2023, title: "Signed 4-year, $90M extension with Commanders", eventType: "CONTRACT" },
      ],
    },
    {
      slug: "cyrus-jones",
      firstName: "Cyrus",
      lastName: "Jones",
      birthYear: 1993,
      hometown: "Baltimore, MD",
      highSchool: "Gilman School, Baltimore, MD",
      bio: "Senior cornerback and elite punt returner in 2015. Named Defensive MVP of the Cotton Bowl after a game-sealing interception in Alabama's 38-0 shutout of Michigan State.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired / Advocate",
        location: "Baltimore, MD",
        statusNote:
          "Selected in the 2nd round by the New England Patriots in 2016, Jones's NFL career was cut short by injuries and a heart condition. A torn ACL in 2017 and an open-heart surgery in December 2019 to correct a congenital coronary artery defect forced his retirement. He now focuses on advocacy through the Cy.Jones Foundation and raising his daughter Cayza, born in July 2020.",
        sourceUrl: "https://en.wikipedia.org/wiki/Cyrus_Jones",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 5,
        position: "Cornerback / Return Specialist",
        yearsAtSchool: "2012-2015",
        statsNote: "Cotton Bowl Defensive MVP · 4 punt return TDs in 2015 · 42 returns for 530 yards",
        gamesPlayed: 15,
      },
      careerEvents: [
        { year: 2016, title: "Drafted by New England Patriots (2nd round, #60)", eventType: "DRAFT" },
        { year: 2018, title: "Claimed by Baltimore Ravens", eventType: "SIGNING" },
        { year: 2019, title: "Underwent open-heart surgery", eventType: "HEALTH", detail: "Congenital coronary artery defect corrected in Denver" },
        { year: 2020, title: "Retired from professional football", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "ardarius-stewart",
      firstName: "ArDarius",
      lastName: "Stewart",
      birthYear: 1993,
      hometown: "Fultondale, AL",
      highSchool: "Fultondale High School, Fultondale, AL",
      bio: "Sophomore wide receiver in 2015 who was a key part of Alabama's receiving corps alongside Calvin Ridley. Had his breakout year in 2016, earning first-team All-SEC honors.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "Alabama",
        statusNote:
          "Selected in the 3rd round by the New York Jets in 2017, Stewart's NFL career was brief — he recorded just 6 catches for 82 yards before being released. He attempted comebacks in the CFL with Winnipeg and BC Lions and the XFL with the DC Defenders, but none materialized into lasting roles. He has been out of professional football since 2023.",
        sourceUrl: "https://en.wikipedia.org/wiki/ArDarius_Stewart",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 13,
        position: "Wide Receiver",
        yearsAtSchool: "2014-2016",
        statsNote: "Key sophomore contributor in 2015 · Led team receiving in 2016",
        gamesPlayed: 15,
      },
      careerEvents: [
        { year: 2017, title: "Drafted by New York Jets (3rd round, #79)", eventType: "DRAFT" },
        { year: 2018, title: "Released by Jets", eventType: "RELEASE" },
        { year: 2022, title: "Signed with BC Lions (CFL)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "richard-mullaney",
      firstName: "Richard",
      lastName: "Mullaney",
      birthYear: 1993,
      hometown: "Thousand Oaks, CA",
      highSchool: "Thousand Oaks High School, Thousand Oaks, CA",
      bio: "Graduate transfer from Oregon State who caught 38 passes in his lone Alabama season. Tied with Calvin Ridley for most receiving touchdowns (5) on the 2015 championship team.",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Football Coach",
        currentEmployer: "Thousand Oaks High School",
        location: "Thousand Oaks, CA",
        statusNote:
          "After going undrafted in 2016, Mullaney had brief stints with the Texans, Cowboys, and Browns but never made an NFL roster. He played in the AAF's Arizona Hotshots (2019) and XFL's DC Defenders (2020), but both leagues folded. He returned to his hometown and now serves as an assistant coach at Thousand Oaks High School, his alma mater.",
        sourceUrl: "https://en.wikipedia.org/wiki/Richard_Mullaney",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 12,
        position: "Wide Receiver",
        yearsAtSchool: "2015",
        statsNote: "38 catches · 5 TDs · Played in all 15 games · Graduate transfer from Oregon State",
        gamesPlayed: 15,
      },
      careerEvents: [
        { year: 2016, title: "Signed as UDFA with Houston Texans", eventType: "SIGNING" },
        { year: 2019, title: "Played for Arizona Hotshots (AAF)", eventType: "SIGNING" },
        { year: 2020, title: "Played for DC Defenders (XFL)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "oj-howard",
      firstName: "O.J.",
      lastName: "Howard",
      birthYear: 1994,
      hometown: "Autaugaville, AL",
      highSchool: "Autauga Academy, Prattville, AL",
      bio: "Athletic tight end who was a key receiving threat and blocker. Named MVP of the 2015 National Championship Game with a dominant performance against Clemson.",
      status: {
        occupationType: "COACH",
        currentTitle: "Director of Player Development",
        currentEmployer: "University of West Alabama",
        location: "Livingston, AL",
        statusNote:
          "Selected 19th overall by the Tampa Bay Buccaneers in 2017, Howard played five seasons in Tampa including winning Super Bowl LV with Tom Brady. He recorded 119 catches and 15 TDs with the Bucs before stints with Buffalo, Houston, and Las Vegas. In March 2025, he was hired as Director of Player Development at the University of West Alabama under coach Scott Cochran.",
        sourceUrl: "https://en.wikipedia.org/wiki/O._J._Howard",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 88,
        position: "Tight End",
        yearsAtSchool: "2013-2016",
        statsNote: "CFP Championship Game MVP · 114 career catches · 1,726 receiving yards",
        gamesPlayed: 15,
      },
      careerEvents: [
        { year: 2017, title: "Drafted by Tampa Bay Buccaneers (1st round, #19)", eventType: "DRAFT" },
        { year: 2021, title: "Won Super Bowl LV with Buccaneers", eventType: "CHAMPIONSHIP" },
        { year: 2025, title: "Hired as Dir. of Player Development at West Alabama", eventType: "CAREER_CHANGE" },
      ],
    },
    {
      slug: "adam-griffith",
      firstName: "Adam",
      lastName: "Griffith",
      birthYear: 1993,
      hometown: "Calhoun, GA",
      highSchool: "Calhoun High School, Calhoun, GA",
      bio: "Place kicker who executed a pivotal onside kick in the national championship game against Clemson. Born in Poland as Andrzej Debowski, he was adopted from an orphanage at age 13. Hit a career-long 55-yard field goal against LSU in 2015.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Citizen",
        location: "Georgia",
        statusNote:
          "Born in Poland and adopted at age 13, Griffith scored 357 career points at Alabama (2nd all-time), making 57 field goals and 186 PATs. His onside kick in the 2015 championship game was a pivotal play. He went undrafted in 2017 and did not make an NFL roster. He was inducted into the Calhoun Gordon County Sports Hall of Fame.",
        sourceUrl: "https://en.wikipedia.org/wiki/Adam_Griffith_(American_football)",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 99,
        position: "Kicker",
        yearsAtSchool: "2013-2016",
        statsNote: "357 career points · 57 FGs · 55-yard FG vs LSU · Crucial onside kick in championship",
        gamesPlayed: 15,
      },
      careerEvents: [
        { year: 2015, title: "55-yard field goal vs LSU", eventType: "MILESTONE" },
        { year: 2016, title: "Onside kick in CFP Championship vs Clemson", eventType: "MILESTONE", detail: "Critical play that shifted momentum in 45-40 win" },
      ],
    },
    {
      slug: "cam-robinson",
      firstName: "Cam",
      lastName: "Robinson",
      birthYear: 1995,
      hometown: "West Monroe, LA",
      highSchool: "West Monroe High School, West Monroe, LA",
      bio: "Sophomore starting left tackle who was the first true freshman to start at left tackle for Alabama since Andre Smith in 2006. Started all 15 games in 2015, anchoring the blind side for Jake Coker and Derrick Henry.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Offensive Tackle",
        currentEmployer: "Cleveland Browns",
        league: "NFL",
        location: "Cleveland, OH",
        statusNote:
          "Selected 34th overall by the Jacksonville Jaguars in 2017, Robinson started all 43 games at left tackle during his three Alabama seasons and won the Outland Trophy in 2016. After eight seasons in Jacksonville, he was traded to Minnesota in 2024, signed with Houston in 2025, and was then traded to the Cleveland Browns where he started at left tackle. He has started 117 career NFL games across four teams.",
        sourceUrl: "https://en.wikipedia.org/wiki/Cam_Robinson",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 75,
        position: "Offensive Tackle",
        yearsAtSchool: "2014-2016",
        statsNote: "Started all 15 games at LT · First true freshman LT since Andre Smith · Outland Trophy winner (2016)",
        gamesPlayed: 15,
      },
      careerEvents: [
        { year: 2017, title: "Drafted by Jacksonville Jaguars (2nd round, #34)", eventType: "DRAFT" },
        { year: 2016, title: "Won Outland Trophy", eventType: "AWARD" },
        { year: 2025, title: "Traded to Cleveland Browns", eventType: "TRADE" },
      ],
    },
    {
      slug: "bradley-bozeman",
      firstName: "Bradley",
      lastName: "Bozeman",
      birthYear: 1994,
      hometown: "Roanoke, AL",
      highSchool: "Handley High School, Roanoke, AL",
      bio: "Versatile offensive lineman who started at right guard in 2015, helping pave the way for Derrick Henry's Heisman season. Later moved to center and became an All-American in 2017.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NFL Center",
        location: "Alabama",
        statusNote:
          "Selected in the 6th round by the Baltimore Ravens in 2018, Bozeman became a reliable starter, playing center and guard over eight NFL seasons with the Ravens, Panthers, and Chargers. He started 110 of 129 career games. He and his wife Nikki founded a foundation that distributed approximately 2 million meals during the COVID-19 pandemic. He retired in February 2026.",
        sourceUrl: "https://en.wikipedia.org/wiki/Bradley_Bozeman",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 76,
        position: "Offensive Guard",
        yearsAtSchool: "2013-2017",
        statsNote: "Started at RG in 2015 · Moved to center in 2017 · All-American · 31 career starts",
        gamesPlayed: 15,
      },
      careerEvents: [
        { year: 2018, title: "Drafted by Baltimore Ravens (6th round, #215)", eventType: "DRAFT" },
        { year: 2022, title: "Signed with Carolina Panthers", eventType: "SIGNING" },
        { year: 2024, title: "Signed with Los Angeles Chargers", eventType: "SIGNING" },
        { year: 2026, title: "Retired from NFL", eventType: "RETIREMENT", detail: "Retired after eight NFL seasons and 110 starts" },
      ],
    },
    {
      slug: "ross-pierschbacher",
      firstName: "Ross",
      lastName: "Pierschbacher",
      birthYear: 1995,
      hometown: "Cedar Falls, IA",
      highSchool: "Cedar Falls High School, Cedar Falls, IA",
      bio: "Redshirt freshman starting left guard in 2015 who went on to start 57 career games at Alabama. Earned All-SEC honors in three consecutive seasons and was a finalist for the Rimington Trophy as a senior center.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "Iowa",
        statusNote:
          "Selected in the 5th round by Washington in the 2019 NFL Draft, Pierschbacher spent six years as a journeyman NFL backup with Washington, the Eagles, Jets, and Lions. He appeared in limited games as a reserve lineman and practice squad player. His most recent NFL activity was with the Eagles' practice squad in late 2023.",
        sourceUrl: "https://en.wikipedia.org/wiki/Ross_Pierschbacher",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 71,
        position: "Offensive Guard",
        yearsAtSchool: "2014-2018",
        statsNote: "Started at LG in 2015 · 57 career starts · 3x All-SEC · Rimington Trophy finalist",
        gamesPlayed: 15,
      },
      careerEvents: [
        { year: 2019, title: "Drafted by Washington (5th round, #153)", eventType: "DRAFT" },
      ],
    },
    {
      slug: "dominick-jackson",
      firstName: "Dominick",
      lastName: "Jackson",
      birthYear: 1994,
      hometown: "San Mateo, CA",
      highSchool: "Homestead High School, Cupertino, CA",
      bio: "Senior starting right tackle who transferred from College of San Mateo. Started all 15 games in 2015, helping the offensive line allow just 16 sacks while blocking for Derrick Henry's record-setting season.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "California",
        statusNote:
          "Jackson went undrafted in 2016 and signed with Washington before spending time on the Detroit Lions roster. His NFL career was brief, primarily as a reserve tackle. He has been out of professional football since the late 2010s.",
        sourceUrl: "https://www.pro-football-reference.com/players/J/JackDo00.htm",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 77,
        position: "Offensive Tackle",
        yearsAtSchool: "2014-2015",
        statsNote: "Started all 15 games at RT · JUCO transfer · 48 knockdowns in 2015",
        gamesPlayed: 15,
      },
      careerEvents: [
        { year: 2016, title: "Signed as UDFA with Washington", eventType: "SIGNING" },
      ],
    },
    {
      slug: "reuben-foster",
      firstName: "Reuben",
      lastName: "Foster",
      birthYear: 1994,
      hometown: "Auburn, AL",
      highSchool: "Auburn High School, Auburn, AL",
      bio: "Starting WILL linebacker in 2015 who led the team with 10 tackles in the National Championship Game against Clemson. A four-star recruit who was the top inside linebacker of his class.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "Alabama",
        statusNote:
          "Selected 31st overall by the San Francisco 49ers in 2017, Foster's promising NFL career was derailed by injuries and off-field issues. He played only 16 career NFL games before being released by the 49ers in 2018 and claimed by Washington, where he tore his ACL and never played a regular-season game. He attempted comebacks in the USFL (Pittsburgh Maulers, 2023) and UFL (Houston Roughnecks, 2024) but injuries continued to plague him. One of the more cautionary tales in recent NFL history.",
        sourceUrl: "https://en.wikipedia.org/wiki/Reuben_Foster",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 10,
        position: "Linebacker",
        yearsAtSchool: "2013-2016",
        statsNote: "222 career tackles · 23 TFL · Led team with 10 tackles in CFP Championship Game",
        gamesPlayed: 15,
      },
      careerEvents: [
        { year: 2017, title: "Drafted by San Francisco 49ers (1st round, #31)", eventType: "DRAFT" },
        { year: 2018, title: "Released by 49ers, claimed by Washington", eventType: "RELEASE" },
        { year: 2019, title: "Tore ACL at Washington OTAs", eventType: "INJURY", detail: "Never played a regular-season game for Washington" },
        { year: 2023, title: "Played for Pittsburgh Maulers (USFL)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "tim-williams-al",
      firstName: "Tim",
      lastName: "Williams",
      birthYear: 1993,
      hometown: "Baton Rouge, LA",
      highSchool: "University Lab School, Baton Rouge, LA",
      bio: "Explosive pass rusher who was a key rotational player off the edge in 2015. Totaled 21 career sacks at Alabama and became a feared edge defender by 2016.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "Louisiana",
        statusNote:
          "Selected in the 3rd round by the Baltimore Ravens in 2017, Williams recorded just 2 sacks and 18 tackles over 19 games. His NFL career never matched his college potential. After brief stints with the Packers and Seahawks, he attempted to play in the CFL with Saskatchewan and BC Lions but was hampered by a torn Achilles. He has been out of professional football since 2022.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tim_Williams_(American_football)",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 56,
        position: "Outside Linebacker",
        yearsAtSchool: "2013-2016",
        statsNote: "21 career sacks · Key rotational pass rusher in 2015 · 31 TFL",
        gamesPlayed: 15,
      },
      careerEvents: [
        { year: 2017, title: "Drafted by Baltimore Ravens (3rd round, #78)", eventType: "DRAFT" },
        { year: 2019, title: "Waived by Ravens", eventType: "RELEASE" },
        { year: 2021, title: "Signed with Saskatchewan Roughriders (CFL)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "ryan-anderson-al",
      firstName: "Ryan",
      lastName: "Anderson",
      birthYear: 1994,
      hometown: "Daphne, AL",
      highSchool: "Daphne High School, Daphne, AL",
      bio: "Outside linebacker who was a rotational player in 2015, contributing to the championship defense. Became a first-team All-SEC selection in 2016 with 19 tackles for loss and 9 sacks.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired / Community Advocate",
        location: "Alabama",
        statusNote:
          "Selected in the 2nd round by Washington in 2017, Anderson played five NFL seasons primarily with Washington (2017-2020) and the Pittsburgh Steelers (2022). He recorded 87 tackles and 6 sacks over 57 career games. Since retiring after the 2022 season, he has hosted annual football camps in his community and stayed involved in youth mentorship.",
        sourceUrl: "https://en.wikipedia.org/wiki/Ryan_Anderson_(linebacker)",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 22,
        position: "Outside Linebacker",
        yearsAtSchool: "2013-2016",
        statsNote: "Rotational OLB in 2015 · 1st-team All-SEC in 2016 · 19 career sacks",
        gamesPlayed: 15,
      },
      careerEvents: [
        { year: 2017, title: "Drafted by Washington (2nd round, #49)", eventType: "DRAFT" },
        { year: 2022, title: "Signed with Pittsburgh Steelers", eventType: "SIGNING" },
        { year: 2023, title: "Retired from professional football", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "rashaan-evans",
      firstName: "Rashaan",
      lastName: "Evans",
      birthYear: 1995,
      hometown: "Auburn, AL",
      highSchool: "Auburn High School, Auburn, AL",
      bio: "Sophomore linebacker who was a key backup behind Reggie Ragland and Reuben Foster in 2015. Developed into a starter by 2017 and became a first-round NFL draft pick.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Linebacker",
        currentEmployer: "Atlanta Falcons",
        league: "NFL",
        location: "Atlanta, GA",
        statusNote:
          "Selected 22nd overall by the Tennessee Titans in 2018, Evans started four seasons in Tennessee before signing with the Falcons in 2022, where he set career highs with 159 tackles. He has since bounced between rosters including stints with the Eagles and Cowboys practice squads. He recorded over 400 career tackles across seven NFL seasons.",
        sourceUrl: "https://en.wikipedia.org/wiki/Rashaan_Evans",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 32,
        position: "Linebacker",
        yearsAtSchool: "2014-2017",
        statsNote: "Key backup LB in 2015 · Starter by 2017 · Butkus Award semifinalist",
        gamesPlayed: 12,
      },
      careerEvents: [
        { year: 2018, title: "Drafted by Tennessee Titans (1st round, #22)", eventType: "DRAFT" },
        { year: 2022, title: "Signed with Atlanta Falcons", eventType: "SIGNING", detail: "Career-high 159 tackles" },
      ],
    },
    {
      slug: "dalvin-tomlinson",
      firstName: "Dalvin",
      lastName: "Tomlinson",
      birthYear: 1994,
      hometown: "McDonough, GA",
      highSchool: "Henry County High School, McDonough, GA",
      bio: "Backup defensive lineman behind Jarran Reed in 2015 who developed into a key starter by 2016. Played in all 15 games during the championship season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Defensive Tackle",
        currentEmployer: "Los Angeles Chargers",
        league: "NFL",
        location: "Los Angeles, CA",
        statusNote:
          "Selected in the 2nd round by the New York Giants in 2017, Tomlinson has been one of the NFL's most durable interior linemen, starting 142 career games. He played for the Giants, Vikings, and Browns before signing with the Cardinals in 2025 and then the Chargers in 2026. He's also a talented musician who plays piano, trumpet, and drums, and builds gaming computers.",
        sourceUrl: "https://en.wikipedia.org/wiki/Dalvin_Tomlinson",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 54,
        position: "Defensive Lineman",
        yearsAtSchool: "2013-2016",
        statsNote: "Backup DE in 2015 · Starter in 2016 · 122 career tackles at Alabama",
        gamesPlayed: 15,
      },
      careerEvents: [
        { year: 2017, title: "Drafted by New York Giants (2nd round, #55)", eventType: "DRAFT" },
        { year: 2021, title: "Signed 2-year, $22M deal with Minnesota Vikings", eventType: "CONTRACT" },
        { year: 2023, title: "Signed 4-year, $57M deal with Cleveland Browns", eventType: "CONTRACT" },
        { year: 2026, title: "Signed with Los Angeles Chargers", eventType: "SIGNING" },
      ],
    },
    {
      slug: "denzel-devall",
      firstName: "Denzel",
      lastName: "Devall",
      birthYear: 1994,
      hometown: "Bastrop, LA",
      highSchool: "Bastrop High School, Bastrop, LA",
      bio: "Senior starting outside linebacker who played in 50 career games with 25 starts. Anchored the OLB position in 2015, contributing 83 career tackles and 6 sacks across his Alabama career.",
      status: {
        occupationType: "COACH",
        currentTitle: "Director of Player Development",
        currentEmployer: "University of Alabama",
        location: "Tuscaloosa, AL",
        statusNote:
          "Devall went undrafted in 2016 and, hampered by a nagging hamstring injury, decided not to pursue a professional playing career. Instead, he joined the Alabama football staff as a personnel assistant in 2016, was promoted to assistant strength and conditioning coach, and then to Director of Player Development. He holds a degree in kinesiology from Alabama.",
        sourceUrl: "https://en.wikipedia.org/wiki/Denzel_Devall",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 8,
        position: "Outside Linebacker",
        yearsAtSchool: "2012-2015",
        statsNote: "50 career games · 25 starts · 83 tackles · 6 sacks · 13 QB hurries",
        gamesPlayed: 15,
      },
      careerEvents: [
        { year: 2016, title: "Joined Alabama football staff as personnel assistant", eventType: "CAREER_CHANGE" },
        { year: 2017, title: "Promoted to Director of Player Development at Alabama", eventType: "CAREER_CHANGE" },
      ],
    },
    {
      slug: "jk-scott",
      firstName: "JK",
      lastName: "Scott",
      birthYear: 1995,
      hometown: "Denver, CO",
      highSchool: "Mullen High School, Denver, CO",
      bio: "True freshman punter in 2015 who immediately became one of the best punters in the country. Holds Alabama's school record for career punting yards (11,074) and career punting average (45.6).",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Punter",
        currentEmployer: "Los Angeles Chargers",
        league: "NFL",
        location: "Los Angeles, CA",
        statusNote:
          "Selected in the 5th round by the Green Bay Packers in 2018, Scott has played eight NFL seasons as a punter. After four years in Green Bay, he joined the Jacksonville Jaguars and then the Los Angeles Chargers, where he earned AFC Special Teams Player of the Week honors. In 2025, he averaged 47.8 yards per punt across 17 games and signed a multi-year extension with the Chargers.",
        sourceUrl: "https://en.wikipedia.org/wiki/J._K._Scott",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 25,
        position: "Punter",
        yearsAtSchool: "2015-2017",
        statsNote: "Alabama career record: 11,074 punting yards · 45.6 avg · 1st-team All-SEC (2016)",
        gamesPlayed: 15,
      },
      careerEvents: [
        { year: 2018, title: "Drafted by Green Bay Packers (5th round, #172)", eventType: "DRAFT" },
        { year: 2024, title: "Signed with Los Angeles Chargers", eventType: "SIGNING" },
        { year: 2025, title: "Signed multi-year extension with Chargers", eventType: "CONTRACT" },
      ],
    },
  ];
}
