import type { TeamSeed } from "./types";

export const bostonCollegeBasketball2023: TeamSeed = {
  slug: "boston-college-basketball-2023",
  name: "Boston College Eagles",
  season: "2022-2023",
  sport: "Men's Basketball",
  school: "Boston College",
  conference: "ACC",
  accomplishment: "2022-2023 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/103.png",
  mascotName: "Eagle",
  people: [
    {
      slug: "quinten-post",
      firstName: "Quinten",
      lastName: "Post",
      birthYear: 2000,
      hometown: "Amsterdam, Netherlands",
      highSchool: "Canarias Basketball Academy",
      bio: "Senior center from Netherlands. Transferred from Mississippi State.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        location: "San Francisco, CA",
        statusNote: "#52 pick by Warriors in 2024. On two-way contract with Golden State.",
        sourceUrl: "https://en.wikipedia.org/wiki/Quinten_Post",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Center", yearsAtSchool: "2022-2023", gamesPlayed: 28, pointsPerGame: 15.1, reboundsPerGame: 5.6, assistsPerGame: 1.2 },
      seasonStats: [{ level: "COLLEGE", teamName: "Boston College Eagles", season: "2022-2023", yearLabel: "2022-2023", sortOrder: 201, gamesPlayed: 28, pointsPerGame: 15.1, reboundsPerGame: 5.6, assistsPerGame: 1.2 }],
      careerEvents: [{ date: "2024-06-27", month: 6, day: 27, year: 2024, title: "Drafted #52 by Golden State Warriors", description: "Selected in 2024 NBA Draft after BC career." }],
    },
    {
      slug: "earl-grant",
      firstName: "Earl",
      lastName: "Grant",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Former College of Charleston HC hired to rebuild BC.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Currently coaching at Boston College.",
        sourceUrl: "https://en.wikipedia.org/wiki/Earl_Grant",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2022-2026" },
      seasonStats: [
        { level: "COACHING", teamName: "Boston College Eagles", season: "2022-2023", yearLabel: "2022-2023", sortOrder: 215 },
      ],
      careerEvents: [],
    },
  ],
};
