import type { TeamSeed } from "./types";

export const bostonCollegeBasketball2019: TeamSeed = {
  slug: "boston-college-basketball-2019",
  name: "Boston College Eagles",
  season: "2018-2019",
  sport: "Men's Basketball",
  school: "Boston College",
  conference: "ACC",
  accomplishment: "2018-2019 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/103.png",
  mascotName: "Eagle",
  people: [
    {
      slug: "ky-bowman",
      firstName: "Ky",
      lastName: "Bowman",
      birthYear: 1997,
      hometown: "Havelock, NC",
      highSchool: "Havelock",
      bio: "Junior guard. Declared for 2019 draft. Undrafted but signed with Warriors.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "Overseas",
        statusNote: "Played for Warriors and Hornets. Now plays overseas.",
        sourceUrl: "https://en.wikipedia.org/wiki/Ky_Bowman",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Guard", yearsAtSchool: "2018-2019", gamesPlayed: 32, pointsPerGame: 19.0, reboundsPerGame: 7.5, assistsPerGame: 4.0 },
      seasonStats: [{ level: "COLLEGE", teamName: "Boston College Eagles", season: "2018-2019", yearLabel: "2018-2019", sortOrder: 201, gamesPlayed: 32, pointsPerGame: 19.0, reboundsPerGame: 7.5, assistsPerGame: 4.0 }],
      careerEvents: [],
    },
    {
      slug: "jordan-chatman",
      firstName: "Jordan",
      lastName: "Chatman",
      birthYear: 1994,
      hometown: "Kennewick, WA",
      highSchool: "Kamiakin",
      bio: "Senior guard. BYU transfer.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "United States",
        statusNote: "Retired from basketball after BC career.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jordan_Chatman",
      },
      membership: { role: "PLAYER", jerseyNumber: 25, position: "Guard", yearsAtSchool: "2018-2019", gamesPlayed: 32, pointsPerGame: 13.5, reboundsPerGame: 3.3, assistsPerGame: 1.5 },
      seasonStats: [{ level: "COLLEGE", teamName: "Boston College Eagles", season: "2018-2019", yearLabel: "2018-2019", sortOrder: 201, gamesPlayed: 32, pointsPerGame: 13.5, reboundsPerGame: 3.3, assistsPerGame: 1.5 }],
      careerEvents: [],
    },
    {
      slug: "jim-christian",
      firstName: "Jim",
      lastName: "Christian",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Could not revive BC basketball.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Fired mid-2021 season.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jim_Christian",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2015-2021" },
      seasonStats: [
        { level: "COACHING", teamName: "Boston College Eagles", season: "2018-2019", yearLabel: "2018-2019", sortOrder: 211 },
      ],
      careerEvents: [],
    },
  ],
};
