import type { TeamSeed } from "./types";

export const bostonCollegeBasketball2011: TeamSeed = {
  slug: "boston-college-basketball-2011",
  name: "Boston College Eagles",
  season: "2010-2011",
  sport: "Men's Basketball",
  school: "Boston College",
  conference: "ACC",
  accomplishment: "2010-2011 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/103.png",
  mascotName: "Eagle",
  people: [
    {
      slug: "reggie-jackson-bc",
      firstName: "Reggie",
      lastName: "Jackson",
      birthYear: 1990,
      hometown: "Colorado Springs, CO",
      highSchool: "Palmer",
      bio: "Junior PG. #24 pick by Thunder in 2011.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "United States",
        statusNote: "13 NBA seasons. 2020 NBA Finals with Clippers/Lakers. Won 2023 title with Nuggets.",
        sourceUrl: "https://en.wikipedia.org/wiki/Reggie_Jackson_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Guard", yearsAtSchool: "2010-2011", gamesPlayed: 32, pointsPerGame: 18.2, reboundsPerGame: 4.3, assistsPerGame: 4.5 },
      seasonStats: [{ level: "COLLEGE", teamName: "Boston College Eagles", season: "2010-2011", yearLabel: "2010-2011", sortOrder: 201, gamesPlayed: 32, pointsPerGame: 18.2, reboundsPerGame: 4.3, assistsPerGame: 4.5 }],
      careerEvents: [{ date: "2011-06-23", month: 6, day: 23, year: 2011, title: "Drafted #24 by Oklahoma City Thunder", description: "Selected 24th overall in 2011 NBA Draft." }],
    },
    {
      slug: "biko-paris",
      firstName: "Biko",
      lastName: "Paris",
      birthYear: 1989,
      hometown: "Miami, FL",
      highSchool: "Brewster Academy",
      bio: "Junior guard and captain.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "United States",
        statusNote: "Played overseas briefly after BC.",
        sourceUrl: "https://en.wikipedia.org/wiki/Biko_Paris",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Guard", yearsAtSchool: "2010-2011", gamesPlayed: 32, pointsPerGame: 10.4, reboundsPerGame: 2.3, assistsPerGame: 3.2 },
      seasonStats: [{ level: "COLLEGE", teamName: "Boston College Eagles", season: "2010-2011", yearLabel: "2010-2011", sortOrder: 201, gamesPlayed: 32, pointsPerGame: 10.4, reboundsPerGame: 2.3, assistsPerGame: 3.2 }],
      careerEvents: [],
    },
    {
      slug: "steve-donahue",
      firstName: "Steve",
      lastName: "Donahue",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Struggled to maintain BC's success.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Fired 2014. Later coached at Penn.",
        sourceUrl: "https://en.wikipedia.org/wiki/Steve_Donahue",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2011-2014" },
      seasonStats: [
        { level: "COACHING", teamName: "Boston College Eagles", season: "2010-2011", yearLabel: "2010-2011", sortOrder: 203 },
      ],
      careerEvents: [],
    },
  ],
};
