import type { TeamSeed } from "./types";

export const bostonCollegeBasketball2009: TeamSeed = {
  slug: "boston-college-basketball-2009",
  name: "Boston College Eagles",
  season: "2008-2009",
  sport: "Men's Basketball",
  school: "Boston College",
  conference: "ACC",
  accomplishment: "NCAA Tournament (22-12)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/103.png",
  mascotName: "Eagle",
  people: [
    {
      slug: "tyrese-rice",
      firstName: "Tyrese",
      lastName: "Rice",
      birthYear: 1987,
      hometown: "Bayonne, NJ",
      highSchool: "Marist High School, Bayonne, NJ",
      isFeatured: true,
      bio: "The senior point guard who was the most electrifying scorer in BC history. He led the Eagles to the NCAA Tournament and was the ACC's most dynamic playmaker, famous for his crossover and pull-up three. He finished as BC's all-time leading scorer.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "Overseas",
        location: "Europe",
        statusNote: "After going undrafted in 2009, Rice built one of the most successful European basketball careers of any American college star. He has played professionally for over 15 years in Spain, Turkey, Russia, Israel, Germany, France, Greece, and China, winning championships in multiple countries. Most notably, he won the EuroLeague championship with Maccabi Tel Aviv in 2014 — one of the most prestigious titles in international basketball. His European career earnings have far exceeded what many lottery picks earned in the NBA.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tyrese_Rice",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Point Guard", yearsAtSchool: "2005-2009", statsNote: "BC all-time leading scorer • EuroLeague champion • ACC star", gamesPlayed: 34, pointsPerGame: 21.1, reboundsPerGame: 3.5, assistsPerGame: 4.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Boston College Eagles", season: "2008-09", yearLabel: "Senior", sortOrder: 204, gamesPlayed: 34, minutesPerGame: 36.0, pointsPerGame: 21.1, reboundsPerGame: 3.5, assistsPerGame: 4.8, fieldGoalPct: 0.420, threePointPct: 0.365 },
      ],
      careerEvents: [
        { year: 2009, title: "Went undrafted — began European career", eventType: "SIGNING" },
        { year: 2014, title: "Won EuroLeague championship with Maccabi Tel Aviv", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "rakim-sanders",
      firstName: "Rakim",
      lastName: "Sanders",
      birthYear: 1987,
      hometown: "Brooklyn, NY",
      highSchool: "Bishop Loughlin Memorial High School, Brooklyn, NY",
      bio: "A senior forward from Brooklyn who was BC's second-leading scorer and most versatile frontcourt player. His athleticism and scoring ability complemented Rice's backcourt brilliance.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Professional",
        location: "New York",
        statusNote: "After graduating from BC, Sanders played professional basketball overseas in several European countries. He has since returned to the New York area and transitioned to a career off the court.",
        sourceUrl: "https://bceagles.com/sports/mens-basketball/roster/rakim-sanders/",
      },
      membership: { role: "PLAYER", jerseyNumber: 45, position: "Forward", yearsAtSchool: "2005-2009", statsNote: "Senior • Brooklyn native • Athletic scorer", gamesPlayed: 34, pointsPerGame: 13.8, reboundsPerGame: 5.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Boston College Eagles", season: "2008-09", yearLabel: "Senior", sortOrder: 204, gamesPlayed: 34, minutesPerGame: 30.0, pointsPerGame: 13.8, reboundsPerGame: 5.5, fieldGoalPct: 0.460 },
      ],
      careerEvents: [],
    },
    {
      slug: "reggie-jackson-bc",
      firstName: "Reggie",
      lastName: "Jackson",
      birthYear: 1990,
      hometown: "Pordenone, Italy",
      highSchool: "South Seminole Christian Academy, Casselberry, FL",
      bio: "A freshman guard who was just beginning his BC career during the 2009 tournament run. Went on to have a long NBA career after transferring to — wait, actually Reggie Jackson played at BC for one year before being drafted. He was born in Italy to American military parents.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        league: "NBA / Free Agent",
        location: "United States",
        statusNote: "After 3 seasons at BC, Jackson was selected #24 overall by the Oklahoma City Thunder in 2011. He has played 13+ NBA seasons with the Thunder, Pistons, Clippers, Nuggets, and 76ers, averaging over 14 PPG for his career. He is one of the most successful NBA players to ever come out of Boston College, with career earnings exceeding $120 million.",
        sourceUrl: "https://en.wikipedia.org/wiki/Reggie_Jackson_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Guard", yearsAtSchool: "2008-2011", statsNote: "Freshman • Future #24 pick • 13-year NBA career", gamesPlayed: 34, pointsPerGame: 6.0, reboundsPerGame: 2.0, assistsPerGame: 1.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Boston College Eagles", season: "2008-09", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 34, minutesPerGame: 15.0, pointsPerGame: 6.0, assistsPerGame: 1.8 },
        { level: "PROFESSIONAL", teamName: "Oklahoma City Thunder", season: "2012-13", yearLabel: "2012-13", sortOrder: 302, gamesPlayed: 45, pointsPerGame: 13.9, assistsPerGame: 4.1 },
      ],
      careerEvents: [
        { year: 2011, title: "Selected #24 overall by the Oklahoma City Thunder", eventType: "DRAFT" },
      ],
    },
    {
      slug: "al-skinner",
      firstName: "Al",
      lastName: "Skinner",
      birthYear: 1952,
      hometown: "New York, NY",
      highSchool: "New York, NY",
      isFeatured: true,
      bio: "The head coach who built Boston College basketball into a consistent NCAA Tournament program in the 2000s. His teams made the tournament 6 times in 12 years, a level of sustained success unprecedented in BC basketball history.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Retired Head Coach",
        location: "Massachusetts",
        statusNote: "Al Skinner coached Boston College for 13 seasons (1997-2010), compiling a 247-164 record and making 6 NCAA Tournament appearances. He was fired in 2010 after a down season. Before BC, he coached at Rhode Island (1990-97). Skinner was a former ABA/NBA player with the New York Nets. His tenure at BC represents the program's golden era of basketball — no coach before or since has matched his tournament success at the school.",
        sourceUrl: "https://en.wikipedia.org/wiki/Al_Skinner",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "1997-2010", statsNote: "247-164 record • 6 NCAA Tournaments • BC's golden era" },
      seasonStats: [
        { level: "COACHING", teamName: "Boston College Eagles", season: "2008-09", yearLabel: "2008-09", sortOrder: 212, wins: 22, losses: 12, tournamentResult: "NCAA Tournament" },
      ],
      careerEvents: [
        { year: 2010, title: "Fired after 13 seasons at Boston College", eventType: "CAREER_CHANGE" },
      ],
    },
  ],
};
