import type { TeamSeed } from "./types";

export const dukeBasketball2016: TeamSeed = {
  slug: "duke-basketball-2016",
  name: "Duke Blue Devils",
  season: "2015-2016",
  sport: "Basketball",
  school: "Duke University",
  conference: "ACC",
  accomplishment: "23-11, Sweet Sixteen",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  mascotName: "Blue Devil",
  people: [
    {
      slug: "brandon-ingram",
      firstName: "Brandon",
      lastName: "Ingram",
      birthYear: 1997,
      hometown: "Kinston, NC",
      highSchool: "Kinston High School, Kinston, NC",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1627742.png",
      bio: "The consensus #2 overall pick in 2016, Ingram was a lanky 6'9\" wing who averaged 17.3 PPG as a freshman. His scoring versatility and length made him an elite NBA prospect from the moment he stepped on campus.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Small Forward",
        currentEmployer: "New Orleans Pelicans",
        league: "NBA",
        location: "New Orleans, LA",
        statusNote: "Selected #2 overall by the Los Angeles Lakers in 2016. After three seasons in LA, he was traded to New Orleans as part of the Anthony Davis deal. Named Most Improved Player in 2019-20 after averaging 23.8 PPG and making his first All-Star team. Signed a 5-year, $158 million max extension. Has averaged 20+ PPG in five consecutive seasons with the Pelicans.",
        sourceUrl: "https://en.wikipedia.org/wiki/Brandon_Ingram",
      },
      membership: { role: "PLAYER", jerseyNumber: 14, position: "Small Forward", yearsAtSchool: "2015-2016", statsNote: "17.3 PPG, 6.8 RPG · ACC ROY · Consensus All-American · #2 pick", gamesPlayed: 34, pointsPerGame: 17.3, reboundsPerGame: 6.8, assistsPerGame: 2.0 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Kinston High School", season: "2014-15", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 28.0, reboundsPerGame: 10.4, assistsPerGame: 3.1 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2015-16", yearLabel: "2015-16", sortOrder: 201, gamesPlayed: 34, minutesPerGame: 34.8, pointsPerGame: 17.3, reboundsPerGame: 6.8, assistsPerGame: 2.0, stealsPerGame: 0.9, blocksPerGame: 1.4, fieldGoalPct: 0.443, threePointPct: 0.341, freeThrowPct: 0.682 },
        { level: "PROFESSIONAL", teamName: "Los Angeles Lakers", season: "2016-17", yearLabel: "2016-17 (Rookie)", sortOrder: 301, gamesPlayed: 79, minutesPerGame: 28.8, pointsPerGame: 9.4, reboundsPerGame: 4.0, assistsPerGame: 2.1, fieldGoalPct: 0.402, threePointPct: 0.290, freeThrowPct: 0.621 },
        { level: "PROFESSIONAL", teamName: "Los Angeles Lakers", season: "2018-19", yearLabel: "2018-19", sortOrder: 303, gamesPlayed: 52, minutesPerGame: 33.8, pointsPerGame: 18.3, reboundsPerGame: 5.1, assistsPerGame: 3.0, fieldGoalPct: 0.491, threePointPct: 0.330, freeThrowPct: 0.675 },
        { level: "PROFESSIONAL", teamName: "New Orleans Pelicans", season: "2019-20", yearLabel: "2019-20 (All-Star, MIP)", sortOrder: 304, gamesPlayed: 62, minutesPerGame: 33.9, pointsPerGame: 23.8, reboundsPerGame: 6.1, assistsPerGame: 4.2, fieldGoalPct: 0.463, threePointPct: 0.391, freeThrowPct: 0.851 },
        { level: "PROFESSIONAL", teamName: "New Orleans Pelicans", season: "2022-23", yearLabel: "2022-23", sortOrder: 307, gamesPlayed: 45, minutesPerGame: 34.5, pointsPerGame: 24.7, reboundsPerGame: 5.8, assistsPerGame: 5.8, fieldGoalPct: 0.468, threePointPct: 0.331, freeThrowPct: 0.803 },
        { level: "PROFESSIONAL", teamName: "New Orleans Pelicans", season: "2024-25", yearLabel: "2024-25", sortOrder: 309, gamesPlayed: 55, minutesPerGame: 33.0, pointsPerGame: 22.5, reboundsPerGame: 5.5, assistsPerGame: 5.0, fieldGoalPct: 0.470, threePointPct: 0.350, freeThrowPct: 0.820 },
      ],
      careerEvents: [
        { year: 2016, title: "Selected #2 overall by Los Angeles Lakers", eventType: "DRAFT" },
        { year: 2019, title: "Traded to New Orleans in Anthony Davis deal", eventType: "TRADE" },
        { year: 2020, title: "Won NBA Most Improved Player Award", eventType: "AWARD" },
        { year: 2020, title: "Named to first NBA All-Star team", eventType: "AWARD" },
        { year: 2020, title: "Signed 5-year, $158M max extension", eventType: "CONTRACT" },
      ],
    },
    {
      slug: "luke-kennard",
      firstName: "Luke",
      lastName: "Kennard",
      birthYear: 1996,
      hometown: "Franklin, OH",
      highSchool: "Franklin High School, Franklin, OH",
      bio: "Freshman who showed elite shooting ability from day one, averaging 10.6 PPG off the bench and shooting 37.0% from three.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Shooting Guard",
        currentEmployer: "Memphis Grizzlies",
        league: "NBA",
        location: "Memphis, TN",
        statusNote: "Returned for his sophomore year, led Duke in scoring in 2016-17 at 19.5 PPG, and was drafted #12. Elite NBA shooter with career 44.1% from three.",
        sourceUrl: "https://en.wikipedia.org/wiki/Luke_Kennard",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Shooting Guard", yearsAtSchool: "2015-2017", statsNote: "10.6 PPG as freshman · 37% from three · Returned for sophomore year" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2015-16", yearLabel: "2015-16", sortOrder: 201, gamesPlayed: 34, minutesPerGame: 24.6, pointsPerGame: 10.6, reboundsPerGame: 3.3, assistsPerGame: 1.9, fieldGoalPct: 0.468, threePointPct: 0.370, freeThrowPct: 0.805 },
      ],
      careerEvents: [],
    },
    {
      slug: "grayson-allen",
      firstName: "Grayson",
      lastName: "Allen",
      birthYear: 1995,
      hometown: "Jacksonville, FL",
      highSchool: "Providence School, Jacksonville, FL",
      isFeatured: false,
      bio: "Sophomore who led the team in scoring at 21.6 PPG — the highest scoring average by a Duke player since J.J. Redick. Named first-team All-ACC.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Shooting Guard",
        currentEmployer: "Phoenix Suns",
        league: "NBA",
        location: "Phoenix, AZ",
        statusNote: "Stayed at Duke through 2018 (senior year), then selected #21 overall by Utah. Won NBA Championship with Milwaukee in 2021.",
        sourceUrl: "https://en.wikipedia.org/wiki/Grayson_Allen",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Shooting Guard", yearsAtSchool: "2014-2018", statsNote: "21.6 PPG (led team) · 1st-team All-ACC · 2015 champion" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2015-16", yearLabel: "2015-16", sortOrder: 202, gamesPlayed: 34, minutesPerGame: 34.5, pointsPerGame: 21.6, reboundsPerGame: 4.6, assistsPerGame: 3.5, stealsPerGame: 1.3, fieldGoalPct: 0.460, threePointPct: 0.418, freeThrowPct: 0.854 },
      ],
      careerEvents: [],
    },
    {
      slug: "matt-jones",
      firstName: "Matt",
      lastName: "Jones",
      birthYear: 1994,
      hometown: "Chatsworth, CA",
      highSchool: "DeSoto High School, DeSoto, TX",
      bio: "Junior guard who started 33 games and shot 41.5% from three. Reliable two-way player who was the team's best perimeter defender.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Business Development",
        currentEmployer: "Total Quality Logistics",
        location: "Chicago, IL",
        statusNote: "Returned for senior year in 2016-17 before transitioning to business career.",
        sourceUrl: "https://en.wikipedia.org/wiki/Matt_Jones_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 13, position: "Shooting Guard", yearsAtSchool: "2013-2017", statsNote: "10.4 PPG · 41.5% from three · Started 33 games" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2015-16", yearLabel: "2015-16", sortOrder: 203, gamesPlayed: 35, minutesPerGame: 30.5, pointsPerGame: 10.4, reboundsPerGame: 2.5, assistsPerGame: 2.2, stealsPerGame: 1.0, fieldGoalPct: 0.430, threePointPct: 0.415, freeThrowPct: 0.800 },
      ],
      careerEvents: [],
    },
    {
      slug: "marshall-plumlee",
      firstName: "Marshall",
      lastName: "Plumlee",
      birthYear: 1992,
      hometown: "Warsaw, IN",
      highSchool: "Christ School, Arden, NC",
      bio: "Senior center and third Plumlee brother to play at Duke. Had his best season as a senior, averaging 8.4 PPG and 7.0 RPG while starting all 34 games.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Investor",
        currentEmployer: "Blackstone",
        location: "New York, NY",
        statusNote: "Played 29 NBA games (Knicks/Bucks) before pivoting to military service — served as a U.S. Army Ranger in the 75th Ranger Regiment. Then earned an MBA from Harvard Business School (Class of 2024) and joined Blackstone as an investor.",
        sourceUrl: "https://en.wikipedia.org/wiki/Marshall_Plumlee",
      },
      membership: { role: "PLAYER", jerseyNumber: 40, position: "Center", yearsAtSchool: "2011-2016", statsNote: "8.4 PPG, 7.0 RPG · Senior captain · Started all 34 games" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2015-16", yearLabel: "2015-16 (Senior)", sortOrder: 205, gamesPlayed: 34, minutesPerGame: 24.3, pointsPerGame: 8.4, reboundsPerGame: 7.0, assistsPerGame: 0.8, blocksPerGame: 0.7, fieldGoalPct: 0.645, freeThrowPct: 0.518 },
        { level: "PROFESSIONAL", teamName: "New York Knicks", season: "2016-17", yearLabel: "2016-17", sortOrder: 301, gamesPlayed: 21, minutesPerGame: 6.5, pointsPerGame: 2.0, reboundsPerGame: 2.1, fieldGoalPct: 0.520 },
      ],
      careerEvents: [
        { year: 2016, title: "Signed as UDFA with New York Knicks", eventType: "SIGNING" },
        { year: 2018, title: "Enlisted in U.S. Army; served as Ranger", eventType: "OTHER" },
        { year: 2024, title: "Graduated from Harvard Business School", eventType: "STUDENT" },
        { year: 2024, title: "Joined Blackstone as investor", eventType: "CAREER_CHANGE" },
      ],
    },
    {
      slug: "derryck-thornton",
      firstName: "Derryck",
      lastName: "Thornton",
      birthYear: 1997,
      hometown: "Chatsworth, CA",
      highSchool: "Findlay Prep, Henderson, NV",
      bio: "Freshman point guard who started 21 games before losing his starting spot. Transferred to USC after the season.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Citizen",
        location: "California",
        statusNote: "Transferred to USC after his freshman year at Duke, then later transferred to UC Davis. Did not pursue professional basketball after college. Has maintained a low public profile since leaving basketball.",
        sourceUrl: "https://en.wikipedia.org/wiki/Derryck_Thornton",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Point Guard", yearsAtSchool: "2015-2016", statsNote: "7.5 PPG, 3.0 APG · Started 21 games · Transferred to USC" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Findlay Prep", season: "2014-15", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 16.5, reboundsPerGame: 3.5, assistsPerGame: 6.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2015-16", yearLabel: "2015-16", sortOrder: 201, gamesPlayed: 34, minutesPerGame: 22.5, pointsPerGame: 7.5, reboundsPerGame: 2.2, assistsPerGame: 3.0, fieldGoalPct: 0.370, threePointPct: 0.280, freeThrowPct: 0.650 },
      ],
      careerEvents: [
        { year: 2016, title: "Transferred to USC", eventType: "OTHER" },
      ],
    },
    {
      slug: "mike-krzyzewski",
      firstName: "Mike",
      lastName: "Krzyzewski",
      birthYear: 1947,
      hometown: "Chicago, IL",
      highSchool: "Weber High School, Chicago, IL",
      bio: "Legendary head coach defending the 2015 national championship. The 2015-16 team had a disappointing season by Duke standards, losing in the Sweet Sixteen.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Retired Head Coach",
        currentEmployer: "Duke University (Emeritus)",
        location: "Durham, NC",
        statusNote: "Retired after 2021-22 with 1,202 career wins.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Krzyzewski",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "1980-2022", statsNote: "23-11 · Sweet Sixteen · Defending champions" },
      seasonStats: [
        { level: "COACHING", teamName: "Duke Blue Devils", season: "2015-16", yearLabel: "2015-16", sortOrder: 1, wins: 23, losses: 11, tournamentResult: "Sweet Sixteen (lost to Oregon)" },
      ],
      careerEvents: [],
    },
  ],
};
