import type { TeamSeed } from "./types";

export const dukeBasketball2014: TeamSeed = {
  slug: "duke-basketball-2014",
  name: "Duke Blue Devils",
  season: "2013-2014",
  sport: "Men's Basketball",
  school: "Duke University",
  conference: "ACC",
  accomplishment: "NCAA R64 loss to Mercer (26-9)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  mascotName: "Blue Devil",
  people: [
    {
      slug: "jabari-parker",
      firstName: "Jabari",
      lastName: "Parker",
      birthYear: 1995,
      hometown: "Chicago, IL",
      highSchool: "Simeon Career Academy, Chicago, IL",
      isFeatured: true,
      imageUrl: "https://a.espncdn.com/combiner/i?img=/i/headshots/mens-college-basketball/players/full/2987622.png",
      bio: "A consensus First-Team All-American freshman who averaged 19.1 PPG and 8.7 RPG. Named USBWA Freshman of the Year. The #2 overall pick in the 2014 NBA Draft.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Joventut Badalona",
        league: "Spanish Liga ACB",
        location: "Barcelona, Spain",
        statusNote:
          "Selected #2 overall by the Milwaukee Bucks in 2014, Parker's NBA career was derailed by two ACL tears (2014, 2017). He showed flashes of stardom (20.1 PPG in 2016-17) but never fully recovered. After stints with the Bucks, Bulls, Wizards, Hawks, Celtics, and Kings, he moved overseas in 2023 — playing for FC Barcelona, Partizan Belgrade, and now Joventut Badalona on loan. Career NBA averages: 14.3 PPG over 7 seasons.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jabari_Parker",
      },
      membership: {
        role: "PLAYER", jerseyNumber: 1, position: "Power Forward", yearsAtSchool: "2013-2014",
        statsNote: "#2 overall pick • Consensus All-American • USBWA Freshman of Year • 19.1 PPG",
        gamesPlayed: 35, pointsPerGame: 19.1, reboundsPerGame: 8.7, assistsPerGame: 1.2,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Simeon Career Academy", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 33.7, reboundsPerGame: 14.3, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2013-14", yearLabel: "2013-14 (All-American, #2 pick)", sortOrder: 201, gamesPlayed: 35, pointsPerGame: 19.1, reboundsPerGame: 8.7, assistsPerGame: 1.2, fieldGoalPct: 0.501, threePointPct: 0.360, freeThrowPct: 0.755 },
        { level: "PROFESSIONAL", teamName: "Milwaukee Bucks", season: "2014-15", yearLabel: "2014-15 (Rookie, ACL tear)", sortOrder: 301, gamesPlayed: 25, pointsPerGame: 12.3, reboundsPerGame: 5.5, assistsPerGame: 1.7, fieldGoalPct: 0.498 },
        { level: "PROFESSIONAL", teamName: "Milwaukee Bucks", season: "2016-17", yearLabel: "2016-17 (2nd ACL tear)", sortOrder: 303, gamesPlayed: 51, pointsPerGame: 20.1, reboundsPerGame: 6.2, assistsPerGame: 2.8, fieldGoalPct: 0.490 },
        { level: "PROFESSIONAL", teamName: "Chicago Bulls", season: "2018-19", yearLabel: "2018-19", sortOrder: 305, gamesPlayed: 64, pointsPerGame: 14.3, reboundsPerGame: 6.2, assistsPerGame: 2.3, fieldGoalPct: 0.476 },
      ],
      careerEvents: [
        { year: 2014, title: "Selected #2 overall by the Milwaukee Bucks", eventType: "DRAFT" },
        { year: 2014, title: "Tore ACL in December (rookie season)", eventType: "INJURY" },
        { year: 2017, title: "Tore ACL again in February", eventType: "INJURY" },
        { year: 2023, title: "Moved to European basketball (FC Barcelona)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "rodney-hood",
      firstName: "Rodney",
      lastName: "Hood",
      birthYear: 1992,
      hometown: "Meridian, MS",
      highSchool: "Meridian High School, Meridian, MS",
      isFeatured: false,
      bio: "A transfer from Mississippi State who averaged 16.1 PPG. Selected #23 overall in the 2014 NBA Draft.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NBA Player",
        location: "Durham, NC",
        statusNote:
          "Selected #23 overall by Utah in 2014. Played 8 NBA seasons with the Jazz, Cavaliers, Trail Blazers, Bucks, and Clippers. Career 10.4 PPG over 408 games. Torn Achilles in 2020 hampered his later career. Announced retirement in November 2024 and returned to Duke to finish his degree. Exploring a coaching career.",
        sourceUrl: "https://www.si.com/college/duke/basketball/duke-basketball-product-announces-retirement-teases-move-11-21-24",
      },
      membership: {
        role: "PLAYER", jerseyNumber: 5, position: "Guard / Forward", yearsAtSchool: "2012-2014",
        statsNote: "Junior • Transfer from Mississippi State • 16.1 PPG • #23 pick",
        gamesPlayed: 35, pointsPerGame: 16.1, reboundsPerGame: 3.9, assistsPerGame: 2.1,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Meridian High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 29.2, reboundsPerGame: 8.1, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2012-13", yearLabel: "2012-13 (Sophomore)", sortOrder: 202, gamesPlayed: 35, pointsPerGame: 10.3, reboundsPerGame: 2.8, assistsPerGame: 1.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2013-14", yearLabel: "2013-14 (Junior, #23 pick)", sortOrder: 203, gamesPlayed: 35, pointsPerGame: 16.1, reboundsPerGame: 3.9, assistsPerGame: 2.1, fieldGoalPct: 0.495, threePointPct: 0.417 },
        { level: "PROFESSIONAL", teamName: "Utah Jazz", season: "2014-15", yearLabel: "2014-15 (Rookie)", sortOrder: 301, gamesPlayed: 76, pointsPerGame: 8.7, reboundsPerGame: 2.1, assistsPerGame: 1.4, fieldGoalPct: 0.420, threePointPct: 0.343 },
        { level: "PROFESSIONAL", teamName: "Utah Jazz", season: "2016-17", yearLabel: "2016-17", sortOrder: 303, gamesPlayed: 59, pointsPerGame: 12.7, reboundsPerGame: 3.1, assistsPerGame: 1.7, threePointPct: 0.378 },
        { level: "PROFESSIONAL", teamName: "Portland Trail Blazers", season: "2018-19", yearLabel: "2018-19 (traded)", sortOrder: 305, gamesPlayed: 52, pointsPerGame: 11.0, reboundsPerGame: 3.0, assistsPerGame: 1.5 },
      ],
      careerEvents: [
        { year: 2014, title: "Selected #23 overall by the Utah Jazz", eventType: "DRAFT" },
        { year: 2020, title: "Torn Achilles tendon", eventType: "INJURY" },
        { year: 2024, title: "Announced retirement; returned to Duke for degree", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "quinn-cook",
      firstName: "Quinn",
      lastName: "Cook",
      birthYear: 1993,
      hometown: "Washington, D.C.",
      highSchool: "DeMatha Catholic High School, Hyattsville, MD",
      isFeatured: false,
      imageUrl: "https://a.espncdn.com/combiner/i?img=/i/headshots/mens-college-basketball/players/full/63582.png",
      bio: "A junior point guard who would captain the 2015 championship team the following year.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        location: "Overseas",
        statusNote: "Went undrafted in 2015 but won two NBA championships — with the Warriors (2018) and Lakers (2020). After his NBA run, he played overseas in Russia, China, Puerto Rico, and Saudi Arabia. Still pursuing professional opportunities.",
        sourceUrl: "https://en.wikipedia.org/wiki/Quinn_Cook",
      },
      membership: {
        role: "PLAYER", jerseyNumber: 2, position: "Point Guard", yearsAtSchool: "2011-2015",
        statsNote: "Junior • Team leader • 11.6 PPG", gamesPlayed: 35, pointsPerGame: 11.6, reboundsPerGame: 2.2, assistsPerGame: 4.4,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "DeMatha Catholic High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 22.4, reboundsPerGame: 2.2, assistsPerGame: 7.7 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2013-14", yearLabel: "2013-14 (Junior)", sortOrder: 203, gamesPlayed: 35, pointsPerGame: 11.6, reboundsPerGame: 2.2, assistsPerGame: 4.4, threePointPct: 0.395 },
      ],
      careerEvents: [
        { year: 2015, title: "Won NCAA Championship with Duke (senior captain)", eventType: "CHAMPIONSHIP" },
        { year: 2018, title: "Won NBA Championship with Golden State Warriors", eventType: "CHAMPIONSHIP" },
        { year: 2020, title: "Won NBA Championship with Los Angeles Lakers", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "rasheed-sulaimon",
      firstName: "Rasheed",
      lastName: "Sulaimon",
      birthYear: 1994,
      hometown: "Houston, TX",
      highSchool: "Strake Jesuit College Prep, Houston, TX",
      isFeatured: false,
      bio: "A sophomore guard who was the first player ever dismissed from Duke's basketball program under Coach K (January 2015, after this season).",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "KK Buducnost Podgorica",
        league: "ABA League / Montenegrin League",
        location: "Podgorica, Montenegro",
        statusNote: "After being dismissed from Duke in January 2015, Sulaimon transferred to Maryland for his senior year. Went undrafted in 2016 but has built a successful overseas career in Turkey, Montenegro, and Croatia, winning league MVP awards abroad. Averaging 12.3 PPG in 2025-26 with KK Buducnost.",
        sourceUrl: "https://en.wikipedia.org/wiki/Rasheed_Sulaimon",
      },
      membership: {
        role: "PLAYER", jerseyNumber: 14, position: "Shooting Guard", yearsAtSchool: "2012-2015",
        statsNote: "Sophomore • 9.9 PPG • 41.0% from three • Later dismissed from team", gamesPlayed: 34, pointsPerGame: 9.9, reboundsPerGame: 2.4, assistsPerGame: 2.4,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Strake Jesuit College Prep", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 19.9, reboundsPerGame: 2.4, assistsPerGame: 5.1 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2012-13", yearLabel: "2012-13 (Freshman)", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 11.6, reboundsPerGame: 3.4, assistsPerGame: 1.9, threePointPct: 0.384 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2013-14", yearLabel: "2013-14 (Sophomore)", sortOrder: 202, gamesPlayed: 34, pointsPerGame: 9.9, reboundsPerGame: 2.4, assistsPerGame: 2.4, threePointPct: 0.410 },
      ],
      careerEvents: [
        { year: 2015, title: "Dismissed from Duke — first player ever dismissed by Coach K", eventType: "OTHER" },
        { year: 2015, title: "Transferred to University of Maryland", eventType: "OTHER" },
      ],
    },
    {
      slug: "amile-jefferson",
      firstName: "Amile",
      lastName: "Jefferson",
      birthYear: 1994,
      hometown: "Philadelphia, PA",
      highSchool: "Friends' Central School, Wynnewood, PA",
      isFeatured: false,
      imageUrl: "https://a.espncdn.com/combiner/i?img=/i/headshots/mens-college-basketball/players/full/2580052.png",
      bio: "A sophomore forward who would go on to play a program-record 150 games at Duke.",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Coach",
        currentEmployer: "Boston Celtics",
        league: "NBA",
        location: "Boston, MA",
        statusNote: "Played a record 150 games at Duke, won the 2015 title. After brief stints in the G-League, NBA, and Turkey, returned to Duke as Director of Player Development. Hired as Celtics assistant in July 2023. Won the 2024 NBA Championship as a Celtics assistant — full circle from his 2015 NCAA title.",
        sourceUrl: "https://en.wikipedia.org/wiki/Amile_Jefferson",
      },
      membership: {
        role: "PLAYER", jerseyNumber: 21, position: "Power Forward", yearsAtSchool: "2012-2017",
        statsNote: "Sophomore • Duke record 150 career games • Future NCAA + NBA champion as coach", gamesPlayed: 35, pointsPerGame: 5.0, reboundsPerGame: 5.5,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Friends' Central School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 12.5, reboundsPerGame: 10.2, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2012-13", yearLabel: "2012-13 (Freshman)", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 6.1, reboundsPerGame: 5.8, assistsPerGame: 0.5, fieldGoalPct: 0.631 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2013-14", yearLabel: "2013-14 (Sophomore)", sortOrder: 202, gamesPlayed: 35, pointsPerGame: 5.0, reboundsPerGame: 5.5, assistsPerGame: 0.5 },
      ],
      careerEvents: [
        { year: 2015, title: "Won NCAA National Championship with Duke", eventType: "CHAMPIONSHIP" },
        { year: 2023, title: "Hired as Boston Celtics assistant coach", eventType: "CAREER" },
        { year: 2024, title: "Won NBA Championship with Celtics", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "mike-krzyzewski",
      firstName: "Mike",
      lastName: "Krzyzewski",
      birthYear: 1947,
      hometown: "Chicago, IL",
      highSchool: "Weber High School, Chicago, IL",
      isFeatured: true,
      bio: "Suffered a stunning first-round upset loss to #14 Mercer despite having the #2 pick in the upcoming draft.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Special Advisor / Duke Ambassador",
        currentEmployer: "NBA / Duke University",
        location: "Durham, NC",
        statusNote: "Retired after the 2021-22 season with 1,202 victories and five national championships.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Krzyzewski",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "1980-2022", statsNote: "26-9 • Lost to #14 Mercer in R64 (stunning upset)" },
      careerEvents: [
        { year: 2014, title: "Lost to #14 Mercer 78-71 in NCAA Tournament first round", eventType: "OTHER" },
      ],
    },
    {
      slug: "tyler-thornton",
      firstName: "Tyler",
      lastName: "Thornton",
      birthYear: 1992,
      hometown: "Silver Spring, MD",
      highSchool: "Gonzaga College High School, Washington, DC",
      isFeatured: false,
      bio: "A senior captain who started 25 of 35 games, providing veteran leadership and tenacious defense. Finished his Duke career with 139 games played, 433 points, 264 assists, and 139 steals.",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Coach",
        currentEmployer: "Duke University",
        league: "NCAA",
        location: "Durham, NC",
        statusNote:
          "After graduating from Duke in 2014, Thornton built a coaching career at Marquette (graduate assistant under Steve Wojciechowski) and Howard University (six seasons, helping the Bison to back-to-back MEAC titles and NCAA Tournament bids in 2023 and 2024). Returned to Duke as assistant coach under Jon Scheyer in May 2025.",
        sourceUrl: "https://goduke.com/staff-directory/tyler-thornton/1371",
        linkedInUrl: "https://www.linkedin.com/in/tyler-thornton-7723251a5/",
      },
      membership: {
        role: "PLAYER", jerseyNumber: 3, position: "Guard", yearsAtSchool: "2010-2014",
        statsNote: "Senior Captain • 25 starts • 3.1 PPG, 2.4 APG • Defensive leader",
        gamesPlayed: 35, pointsPerGame: 3.1, reboundsPerGame: 2.1, assistsPerGame: 2.4,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Gonzaga College High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 9.7, reboundsPerGame: 2.1, assistsPerGame: 5.1 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2013-14", yearLabel: "2013-14 (Senior Captain)", sortOrder: 204, gamesPlayed: 35, pointsPerGame: 3.1, reboundsPerGame: 2.1, assistsPerGame: 2.4 },
      ],
      careerEvents: [
        { year: 2014, title: "Graduated from Duke; began coaching career at Marquette", eventType: "CAREER" },
        { year: 2019, title: "Joined Howard University coaching staff", eventType: "CAREER" },
        { year: 2025, title: "Returned to Duke as assistant coach under Jon Scheyer", eventType: "CAREER" },
      ],
    },
    {
      slug: "josh-hairston",
      firstName: "Josh",
      lastName: "Hairston",
      birthYear: 1992,
      hometown: "Fredericksburg, VA",
      highSchool: "Montrose Christian School, Rockville, MD",
      isFeatured: false,
      bio: "A senior forward who scored a season-high 12 points against Saint Louis and grabbed 5 rebounds against Creighton in the NCAA Tournament. Finished his four-year Duke career with 121 games played.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Sports Agent",
        currentEmployer: "Klutch Sports Group",
        location: "Los Angeles, CA",
        statusNote:
          "After Duke, Hairston played five years of professional basketball overseas in Switzerland, Germany, and Italy before transitioning to the business side as a sports agent. Now at Klutch Sports Group representing NBA players.",
        sourceUrl: "https://sportsagentblog.com/2020/07/20/former-duke-basketball-player-josh-hairston-has-eyes-set-on-becoming-an-nba-agent/",
        linkedInUrl: "https://www.linkedin.com/in/joshua-hairston-36b9811a4",
      },
      membership: {
        role: "PLAYER", jerseyNumber: 15, position: "Forward", yearsAtSchool: "2010-2014",
        statsNote: "Senior • 2.7 PPG, 1.4 RPG • 121 career games",
        gamesPlayed: 29, pointsPerGame: 2.7, reboundsPerGame: 1.4, assistsPerGame: 0.1,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Montrose Christian School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 9.1, reboundsPerGame: 4.8, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2013-14", yearLabel: "2013-14 (Senior)", sortOrder: 204, gamesPlayed: 29, pointsPerGame: 2.7, reboundsPerGame: 1.4, assistsPerGame: 0.1 },
      ],
      careerEvents: [
        { year: 2014, title: "Graduated from Duke; signed professional contract in Switzerland", eventType: "SIGNING" },
        { year: 2020, title: "Transitioned to sports agent career", eventType: "CAREER" },
        { year: 2022, title: "Joined Klutch Sports Group", eventType: "CAREER" },
      ],
    },
    {
      slug: "marshall-plumlee",
      firstName: "Marshall",
      lastName: "Plumlee",
      birthYear: 1992,
      hometown: "Warsaw, IN",
      highSchool: "Christ School, Arden, NC",
      isFeatured: false,
      bio: "A sophomore center who served as a reserve behind Jabari Parker and Amile Jefferson. Would later blossom into a starter as a senior and play in the NBA before becoming a U.S. Army Ranger.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Investor",
        currentEmployer: "Blackstone",
        location: "New York, NY",
        statusNote:
          "Went on to captain the 2015-16 Duke team, averaged 8.3 PPG and 8.6 RPG as a senior. Played 29 NBA games with the Knicks and Bucks. Served as a U.S. Army Ranger officer. Earned MBA from Harvard Business School (Class of 2024). Now an investor at Blackstone.",
        sourceUrl: "https://en.wikipedia.org/wiki/Marshall_Plumlee",
        linkedInUrl: "https://www.linkedin.com/in/marshallplumlee/",
      },
      membership: {
        role: "PLAYER", jerseyNumber: 40, position: "Center", yearsAtSchool: "2011-2016",
        statsNote: "Sophomore • Limited reserve role behind Parker and Jefferson",
        gamesPlayed: 28, pointsPerGame: 1.4, reboundsPerGame: 1.8, assistsPerGame: 0.2,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Christ School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 7.1, reboundsPerGame: 5.3, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2013-14", yearLabel: "2013-14 (Sophomore)", sortOrder: 202, gamesPlayed: 28, pointsPerGame: 1.4, reboundsPerGame: 1.8, assistsPerGame: 0.2 },
      ],
      careerEvents: [
        { year: 2015, title: "Won NCAA Championship with Duke", eventType: "CHAMPIONSHIP" },
        { year: 2016, title: "Captained Duke team as a senior; undrafted, signed with Knicks", eventType: "SIGNING" },
        { year: 2019, title: "Graduated from U.S. Army Ranger School", eventType: "CAREER" },
        { year: 2024, title: "Graduated from Harvard Business School; joined Blackstone", eventType: "CAREER" },
      ],
    },
    {
      slug: "matt-jones",
      firstName: "Matt",
      lastName: "Jones",
      birthYear: 1994,
      hometown: "DeSoto, TX",
      highSchool: "DeSoto High School, DeSoto, TX",
      isFeatured: false,
      bio: "A freshman guard who appeared in 32 games with four starts, shooting 29.4% from the field as he adjusted to the college game. Would become a key contributor on Duke's 2015 championship team.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Account Executive",
        currentEmployer: "Total Quality Logistics",
        location: "Chicago, IL",
        statusNote:
          "Jones played four seasons at Duke (2013-17), appearing in 143 games with 86 starts and winning the 2015 NCAA Championship. After going undrafted, he played in the G-League (Stockton Kings) and briefly in Taiwan. Transitioned to the business world in 2020: first as a landlord representation broker at JLL in San Francisco (2020-23), then as a Senior Associate at Alumni Ventures' Sports Fund (2023-25) focusing on sports tech investments. As of late 2025, he works at Total Quality Logistics in Chicago.",
        sourceUrl: "https://en.wikipedia.org/wiki/Matt_Jones_(basketball)",
        linkedInUrl: "https://www.linkedin.com/in/matt-jones-3751201ba/",
      },
      membership: {
        role: "PLAYER", jerseyNumber: 13, position: "Guard", yearsAtSchool: "2013-2017",
        statsNote: "Freshman • 32 games, 4 starts • 1.8 PPG • Future 2015 NCAA champion",
        gamesPlayed: 32, pointsPerGame: 1.8, reboundsPerGame: 0.8, assistsPerGame: 0.2,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "DeSoto High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 7.7, reboundsPerGame: 0.8, assistsPerGame: 2.3 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2013-14", yearLabel: "2013-14 (Freshman)", sortOrder: 201, gamesPlayed: 32, pointsPerGame: 1.8, reboundsPerGame: 0.8, assistsPerGame: 0.2, fieldGoalPct: 0.294 },
      ],
      careerEvents: [
        { year: 2015, title: "Won NCAA Championship with Duke", eventType: "CHAMPIONSHIP" },
        { year: 2017, title: "Graduated from Duke; joined G-League (Stockton Kings)", eventType: "CAREER" },
        { year: 2020, title: "Joined JLL as commercial real estate broker in San Francisco", eventType: "CAREER" },
        { year: 2023, title: "Joined Alumni Ventures Sports Fund as Senior Associate", eventType: "CAREER" },
        { year: 2025, title: "Joined Total Quality Logistics in Chicago", eventType: "CAREER" },
      ],
    },
    {
      slug: "semi-ojeleye",
      firstName: "Semi",
      lastName: "Ojeleye",
      birthYear: 1994,
      hometown: "Ottawa, KS",
      highSchool: "Ottawa High School, Ottawa, KS",
      isFeatured: false,
      bio: "A freshman forward who appeared in 17 games, shooting an efficient 50% from the field and 57.1% from three on limited attempts. Transferred to SMU after the season, where he became AAC Player of the Year.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Small Forward",
        currentEmployer: "Crvena Zvezda",
        league: "EuroLeague / ABA League",
        location: "Belgrade, Serbia",
        statusNote:
          "After transferring from Duke to SMU, Ojeleye blossomed into the AAC Player of the Year in 2016-17 (18.9 PPG, 6.8 RPG) and led SMU to the AAC regular season and tournament titles. Selected #37 overall by the Boston Celtics in 2017. Played 4 NBA seasons with the Celtics, Bucks, and Clippers (career 3.3 PPG). Moved to Europe in 2022, playing for Virtus Bologna (Italy/EuroLeague) and Valencia Basket (Spain). Signed with Crvena Zvezda in Belgrade for the 2025-26 season, averaging 7.5 PPG and 3.5 RPG in EuroLeague play.",
        sourceUrl: "https://en.wikipedia.org/wiki/Semi_Ojeleye",
      },
      membership: {
        role: "PLAYER", jerseyNumber: 37, position: "Forward", yearsAtSchool: "2013-2014",
        statsNote: "Freshman • 17 games • 1.6 PPG • 50% FG • Transferred to SMU",
        gamesPlayed: 17, pointsPerGame: 1.6, reboundsPerGame: 0.9, assistsPerGame: 0.1,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Ottawa High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 7.4, reboundsPerGame: 4.2, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2013-14", yearLabel: "2013-14 (Freshman, transferred to SMU)", sortOrder: 201, gamesPlayed: 17, pointsPerGame: 1.6, reboundsPerGame: 0.9, assistsPerGame: 0.1, fieldGoalPct: 0.500, threePointPct: 0.571, freeThrowPct: 0.909 },
        { level: "COLLEGE", teamName: "SMU Mustangs", season: "2016-17", yearLabel: "2016-17 (Senior, AAC POY)", sortOrder: 204, gamesPlayed: 33, pointsPerGame: 18.9, reboundsPerGame: 6.8, assistsPerGame: 1.0, fieldGoalPct: 0.478, threePointPct: 0.434 },
        { level: "PROFESSIONAL", teamName: "Boston Celtics", season: "2017-18", yearLabel: "2017-18 (Rookie)", sortOrder: 301, gamesPlayed: 73, pointsPerGame: 3.0, reboundsPerGame: 1.6, assistsPerGame: 0.3, fieldGoalPct: 0.371, threePointPct: 0.313 },
      ],
      careerEvents: [
        { year: 2014, title: "Transferred from Duke to SMU", eventType: "OTHER" },
        { year: 2017, title: "Named AAC Player of the Year at SMU", eventType: "AWARD" },
        { year: 2017, title: "Selected #37 overall by the Boston Celtics", eventType: "DRAFT" },
        { year: 2022, title: "Signed with Virtus Bologna (EuroLeague)", eventType: "SIGNING" },
        { year: 2025, title: "Signed with Crvena Zvezda in Belgrade", eventType: "SIGNING" },
      ],
    },
  ],
};
