import type { TeamSeed } from "./types";

export const dukeBasketball2020: TeamSeed = {
  slug: "duke-basketball-2020",
  name: "Duke Blue Devils",
  season: "2019-2020",
  sport: "Men's Basketball",
  school: "Duke University",
  conference: "ACC",
  accomplishment: "25-6, Season Ended by COVID-19",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  mascotName: "Blue Devil",
  people: [
    {
      slug: "tre-jones",
      firstName: "Tre",
      lastName: "Jones",
      birthYear: 2000,
      hometown: "Apple Valley, MN",
      highSchool: "Apple Valley High School, Apple Valley, MN",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1630200.png",
      bio: "Sophomore point guard who won ACC Player of the Year, averaging 16.2 PPG and 6.4 APG. Led Duke to a #1 seed before COVID-19 cancelled the tournament.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Point Guard",
        currentEmployer: "San Antonio Spurs",
        league: "NBA",
        location: "San Antonio, TX",
        statusNote: "Selected #41 overall by San Antonio. Has been a reliable backup PG, averaging career-best 8.8 PPG in 2023-24. Entering 6th NBA season.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tre_Jones",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Point Guard", yearsAtSchool: "2018-2020", statsNote: "ACC POY · 16.2 PPG, 6.4 APG · #41 pick · Season cut short by COVID" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2019-20", yearLabel: "2019-20 (ACC POY)", sortOrder: 202, gamesPlayed: 31, minutesPerGame: 34.8, pointsPerGame: 16.2, reboundsPerGame: 4.2, assistsPerGame: 6.4, stealsPerGame: 1.8, fieldGoalPct: 0.445, threePointPct: 0.363, freeThrowPct: 0.772 },
      ],
      careerEvents: [],
    },
    {
      slug: "vernon-carey-jr",
      firstName: "Vernon",
      lastName: "Carey Jr.",
      birthYear: 2001,
      hometown: "Fort Lauderdale, FL",
      highSchool: "University School, Fort Lauderdale, FL",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1630175.png",
      bio: "Freshman center and McDonald's All-American who dominated inside, averaging 17.8 PPG and 8.8 RPG. Named ACC Rookie of the Year.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        league: "NBA / Overseas",
        statusNote: "Selected #32 overall by Charlotte (traded to Brooklyn) in 2020. Has bounced between the NBA, G-League, and overseas, playing limited minutes with the Nets and Wizards. His NBA career hasn't matched his college production.",
        sourceUrl: "https://en.wikipedia.org/wiki/Vernon_Carey_Jr.",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Center", yearsAtSchool: "2019-2020", statsNote: "17.8 PPG, 8.8 RPG · ACC ROY · McDonald's AA · #32 pick", gamesPlayed: 31, pointsPerGame: 17.8, reboundsPerGame: 8.8, assistsPerGame: 1.2 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "University School", season: "2018-19", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 20.5, reboundsPerGame: 12.0, blocksPerGame: 3.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2019-20", yearLabel: "2019-20 (ACC ROY)", sortOrder: 201, gamesPlayed: 31, minutesPerGame: 30.2, pointsPerGame: 17.8, reboundsPerGame: 8.8, assistsPerGame: 1.2, blocksPerGame: 1.6, fieldGoalPct: 0.579, freeThrowPct: 0.674 },
        { level: "PROFESSIONAL", teamName: "Brooklyn Nets", season: "2020-21", yearLabel: "2020-21 (Rookie)", sortOrder: 301, gamesPlayed: 12, minutesPerGame: 5.5, pointsPerGame: 2.8, reboundsPerGame: 2.3, fieldGoalPct: 0.480 },
      ],
      careerEvents: [
        { year: 2020, title: "Selected #32 overall by Charlotte (traded to Brooklyn)", eventType: "DRAFT" },
      ],
    },
    {
      slug: "cassius-stanley",
      firstName: "Cassius",
      lastName: "Stanley",
      birthYear: 2000,
      hometown: "Los Angeles, CA",
      highSchool: "Sierra Canyon School, Chatsworth, CA",

      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1630235.png",      bio: "Athletic freshman guard who averaged 12.6 PPG with electric dunking ability. Won the 2021 NBA Slam Dunk Contest.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        league: "Overseas / G-League",
        statusNote: "Selected #54 overall by Indiana in 2020. Won the 2021 NBA Slam Dunk Contest. Has bounced between the NBA and G-League, with stints in Indiana and Cleveland. Currently playing overseas.",
        sourceUrl: "https://en.wikipedia.org/wiki/Cassius_Stanley",
      },
      membership: { role: "PLAYER", jerseyNumber: 14, position: "Shooting Guard", yearsAtSchool: "2019-2020", statsNote: "12.6 PPG · Athletic freak · Won 2021 NBA Dunk Contest", gamesPlayed: 31, pointsPerGame: 12.6, reboundsPerGame: 4.9, assistsPerGame: 0.8 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Sierra Canyon School", season: "2018-19", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 14.8, reboundsPerGame: 5.0, assistsPerGame: 2.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2019-20", yearLabel: "2019-20", sortOrder: 201, gamesPlayed: 31, minutesPerGame: 27.5, pointsPerGame: 12.6, reboundsPerGame: 4.9, assistsPerGame: 0.8, stealsPerGame: 0.5, fieldGoalPct: 0.497, threePointPct: 0.363, freeThrowPct: 0.696 },
        { level: "PROFESSIONAL", teamName: "Indiana Pacers", season: "2020-21", yearLabel: "2020-21 (Rookie)", sortOrder: 301, gamesPlayed: 13, minutesPerGame: 5.0, pointsPerGame: 2.0, reboundsPerGame: 0.5, fieldGoalPct: 0.370 },
      ],
      careerEvents: [
        { year: 2020, title: "Selected #54 overall by Indiana Pacers", eventType: "DRAFT" },
        { year: 2021, title: "Won NBA Slam Dunk Contest", eventType: "AWARD" },
      ],
    },
    {
      slug: "matthew-hurt",
      firstName: "Matthew",
      lastName: "Hurt",
      birthYear: 2000,
      hometown: "Rochester, MN",
      highSchool: "John Marshall High School, Rochester, MN",
      bio: "Freshman forward/center who showed flashes of his offensive repertoire with 9.7 PPG, including a 25-point game vs Georgia Tech. Returned for sophomore year.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        league: "G-League / Overseas",
        statusNote: "Returned for his sophomore year (2020-21) where he led Duke at 18.3 PPG and was named first-team All-ACC. Went undrafted in 2021 but has played in the G-League and overseas, including stints with Memphis's G-League affiliate.",
        sourceUrl: "https://en.wikipedia.org/wiki/Matthew_Hurt",
      },
      membership: { role: "PLAYER", jerseyNumber: 21, position: "Power Forward / Center", yearsAtSchool: "2019-2021", statsNote: "9.7 PPG as freshman · Returned for sophomore year (18.3 PPG)" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "John Marshall High School", season: "2018-19", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 30.0, reboundsPerGame: 10.5, assistsPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2019-20", yearLabel: "2019-20", sortOrder: 201, gamesPlayed: 31, minutesPerGame: 22.6, pointsPerGame: 9.7, reboundsPerGame: 3.8, fieldGoalPct: 0.456, threePointPct: 0.397, freeThrowPct: 0.857 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2020-21", yearLabel: "2020-21 (All-ACC)", sortOrder: 202, gamesPlayed: 24, minutesPerGame: 34.1, pointsPerGame: 18.3, reboundsPerGame: 6.2, assistsPerGame: 0.7, fieldGoalPct: 0.558, threePointPct: 0.441, freeThrowPct: 0.819 },
      ],
      careerEvents: [
        { year: 2021, title: "Named first-team All-ACC", eventType: "AWARD" },
      ],
    },
    {
      slug: "wendell-moore-jr",
      firstName: "Wendell",
      lastName: "Moore Jr.",
      birthYear: 2001,
      hometown: "Concord, NC",
      highSchool: "Cox Mill High School, Concord, NC",

      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1631112.png",      bio: "Freshman wing who averaged 5.2 PPG in a supporting role. Would develop into a first-team All-ACC player and first-round pick by his junior year.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard / Forward",
        league: "NBA / G-League",
        statusNote: "Developed into a first-round pick by 2022 after three years at Duke. Selected #26 overall.",
        sourceUrl: "https://en.wikipedia.org/wiki/Wendell_Moore_Jr.",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Small Forward", yearsAtSchool: "2019-2022", statsNote: "5.2 PPG as freshman · Later became 1st-team All-ACC and #26 pick" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2019-20", yearLabel: "2019-20", sortOrder: 201, gamesPlayed: 29, minutesPerGame: 19.3, pointsPerGame: 5.2, reboundsPerGame: 3.2, assistsPerGame: 1.4, fieldGoalPct: 0.409, threePointPct: 0.287 },
      ],
      careerEvents: [],
    },
    {
      slug: "mike-krzyzewski",
      firstName: "Mike",
      lastName: "Krzyzewski",
      birthYear: 1947,
      hometown: "Chicago, IL",
      highSchool: "Weber High School, Chicago, IL",
      bio: "The 2019-20 team was on track for a #1 seed before the NCAA Tournament was cancelled due to the COVID-19 pandemic. One of the great 'what if' seasons in Duke history.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Retired Head Coach",
        currentEmployer: "Duke University (Emeritus)",
        location: "Durham, NC",
        statusNote: "Retired after 2021-22 with 1,202 career wins.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Krzyzewski",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "1980-2022", statsNote: "25-6 · Season cancelled by COVID-19 · Projected #1 seed" },
      seasonStats: [
        { level: "COACHING", teamName: "Duke Blue Devils", season: "2019-20", yearLabel: "2019-20", sortOrder: 1, wins: 25, losses: 6, tournamentResult: "NCAA Tournament cancelled (COVID-19)" },
      ],
      careerEvents: [],
    },
    {
      slug: "jeff-capel",
      firstName: "Jeff",
      lastName: "Capel",
      birthYear: 1975,
      hometown: "Fayetteville, NC",
      highSchool: "South View High School, Hope Mills, NC",
      bio: "Associate head coach at Duke who was one of the top assistants and recruiters in college basketball.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "University of Pittsburgh",
        location: "Pittsburgh, PA",
        statusNote: "Left Duke in 2018 to become head coach at Pitt. Has rebuilt the Panthers program.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jeff_Capel",
      },
      membership: { role: "ASSISTANT_COACH", position: "Associate Head Coach", yearsAtSchool: "2011-2018", statsNote: "Top recruiter · Landed Zion, RJ, Cam class" },
      careerEvents: [
        { year: 2018, title: "Named head coach at University of Pittsburgh", eventType: "COACHING" },
      ],
    },
    {
      slug: "nate-james",
      firstName: "Nate",
      lastName: "James",
      birthYear: 1979,
      hometown: "Seattle, WA",
      highSchool: "Lower Merion High School, Ardmore, PA",
      bio: "Former Duke player (1997-2001) and assistant coach. Key recruiter and mentor to players.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "Austin Peay State University",
        location: "Clarksville, TN",
        statusNote: "Left Duke in 2021 to become head coach at Austin Peay. 2001 NCAA champion as a player.",
        sourceUrl: "https://en.wikipedia.org/wiki/Nate_James",
      },
      membership: { role: "ASSISTANT_COACH", position: "Assistant Coach", yearsAtSchool: "2007-2021", statsNote: "Former Duke player · Key recruiter" },
      careerEvents: [
        { year: 2021, title: "Named head coach at Austin Peay State University", eventType: "COACHING" },
      ],
    },
    {
      slug: "jon-scheyer",
      firstName: "Jon",
      lastName: "Scheyer",
      birthYear: 1987,
      hometown: "Northbrook, IL",
      highSchool: "Glenbrook North High School, Northbrook, IL",
      bio: "Former Duke player (2006-10) and 2010 national champion who served as associate head coach and head-coach-in-waiting.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "Duke University",
        league: "ACC",
        location: "Durham, NC",
        statusNote: "Succeeded Coach K in 2022. Has led Duke to three NCAA Tournaments in three seasons, including a Final Four in 2025.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jon_Scheyer",
      },
      membership: { role: "ASSISTANT_COACH", position: "Associate Head Coach / Coach-in-Waiting", yearsAtSchool: "2013-2022", statsNote: "2010 champion as player · Named successor to Coach K" },
      careerEvents: [
        { year: 2022, title: "Named head coach at Duke, succeeding Coach K", eventType: "COACHING" },
      ],
    },
  ],
};
