import type { TeamSeed } from "./types";

export const dukeBasketball2012: TeamSeed = {
  slug: "duke-basketball-2012",
  name: "Duke Blue Devils",
  season: "2011-2012",
  sport: "Men's Basketball",
  school: "Duke University",
  conference: "ACC",
  accomplishment: "Lost to #15 Lehigh in R64 (27-7)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  mascotName: "Blue Devil",
  people: [
    {
      slug: "austin-rivers",
      firstName: "Austin",
      lastName: "Rivers",
      birthYear: 1992,
      hometown: "Winter Park, FL",
      highSchool: "Winter Park High School, Winter Park, FL",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/203085.png",
      bio: "A dynamic one-and-done freshman who averaged 15.5 PPG and hit the iconic game-winning three-pointer against North Carolina. Son of NBA coach Doc Rivers.",
      status: {
        occupationType: "BROADCASTER_ANALYST",
        currentTitle: "Sports Analyst",
        currentEmployer: "ESPN / NBC Sports",
        location: "Los Angeles, CA",
        statusNote:
          "Selected #10 overall by the New Orleans Hornets in 2012. Played 11 NBA seasons with the Hornets/Pelicans, Clippers (under father Doc Rivers), Wizards, Rockets, Knicks, Nuggets, and Timberwolves. Career 8.8 PPG. After retiring, became a studio analyst for ESPN and NBC Sports, covering NBA games alongside his father Doc Rivers.",
        sourceUrl: "https://en.wikipedia.org/wiki/Austin_Rivers",
      },
      membership: {
        role: "PLAYER", jerseyNumber: 0, position: "Guard", yearsAtSchool: "2011-2012",
        statsNote: "Freshman • #10 overall pick • 15.5 PPG • Iconic buzzer-beater vs UNC",
        gamesPlayed: 34, pointsPerGame: 15.5, reboundsPerGame: 3.4, assistsPerGame: 2.1,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2011-12", yearLabel: "2011-12 (Freshman, UNC buzzer-beater)", sortOrder: 201, gamesPlayed: 34, pointsPerGame: 15.5, reboundsPerGame: 3.4, assistsPerGame: 2.1, fieldGoalPct: 0.423, threePointPct: 0.363, freeThrowPct: 0.768 },
        { level: "PROFESSIONAL", teamName: "New Orleans Hornets", season: "2012-13", yearLabel: "2012-13 (Rookie)", sortOrder: 301, gamesPlayed: 75, pointsPerGame: 6.2, reboundsPerGame: 1.7, assistsPerGame: 2.1, fieldGoalPct: 0.370 },
        { level: "PROFESSIONAL", teamName: "LA Clippers", season: "2015-16", yearLabel: "2015-16 (played for dad)", sortOrder: 304, gamesPlayed: 76, pointsPerGame: 8.9, reboundsPerGame: 2.3, assistsPerGame: 2.0, fieldGoalPct: 0.439, threePointPct: 0.355 },
        { level: "PROFESSIONAL", teamName: "Houston Rockets", season: "2018-19", yearLabel: "2018-19", sortOrder: 307, gamesPlayed: 47, pointsPerGame: 8.7, reboundsPerGame: 2.6, assistsPerGame: 1.4, threePointPct: 0.362 },
      ],
      careerEvents: [
        { year: 2012, title: "Hit game-winning three-pointer vs #5 North Carolina", eventType: "OTHER" },
        { year: 2012, title: "Selected #10 overall by the New Orleans Hornets", eventType: "DRAFT" },
        { year: 2015, title: "Traded to LA Clippers (coached by father Doc Rivers)", eventType: "TRADE" },
        { year: 2023, title: "Retired from NBA; became ESPN/NBC Sports analyst", eventType: "CAREER" },
      ],
    },
    {
      slug: "seth-curry",
      firstName: "Seth",
      lastName: "Curry",
      birthYear: 1990,
      hometown: "Charlotte, NC",
      highSchool: "Charlotte Christian School, Charlotte, NC",
      isFeatured: false,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/203552.png",
      bio: "A junior who averaged 13.2 PPG with elite three-point shooting.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Golden State Warriors",
        league: "NBA",
        statusNote: "Now playing with brother Steph on the Warriors in 2025-26.",
        sourceUrl: "https://en.wikipedia.org/wiki/Seth_Curry",
      },
      membership: { role: "PLAYER", jerseyNumber: 30, position: "Guard", yearsAtSchool: "2008-2013", statsNote: "Junior • 13.2 PPG • 41.6% from three", gamesPlayed: 34, pointsPerGame: 13.2, reboundsPerGame: 2.5, assistsPerGame: 2.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2011-12", yearLabel: "2011-12 (Junior)", sortOrder: 204, gamesPlayed: 34, pointsPerGame: 13.2, reboundsPerGame: 2.5, assistsPerGame: 2.5, threePointPct: 0.416 },
      ],
      careerEvents: [],
    },
    {
      slug: "mason-plumlee",
      firstName: "Mason",
      lastName: "Plumlee",
      birthYear: 1990,
      hometown: "Warsaw, IN",
      highSchool: "Christ School, Arden, NC",
      isFeatured: false,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/203486.png",
      bio: "A junior center who averaged 11.1 PPG and 9.2 RPG.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "Charlotte Hornets",
        league: "NBA",
        statusNote: "13th NBA season with the Hornets. 2016 Olympic gold medalist.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mason_Plumlee",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Center", yearsAtSchool: "2009-2013", statsNote: "Junior • 11.1 PPG, 9.2 RPG", gamesPlayed: 34, pointsPerGame: 11.1, reboundsPerGame: 9.2, assistsPerGame: 1.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2011-12", yearLabel: "2011-12 (Junior)", sortOrder: 203, gamesPlayed: 34, pointsPerGame: 11.1, reboundsPerGame: 9.2, assistsPerGame: 1.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "miles-plumlee",
      firstName: "Miles",
      lastName: "Plumlee",
      birthYear: 1988,
      hometown: "Warsaw, IN",
      highSchool: "Christ School, Arden, NC",
      isFeatured: false,
      bio: "The eldest Plumlee brother as a senior. Grabbed 22 rebounds against Maryland — the most ever by a Coach K player.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Professional Basketball Player",
        statusNote: "Selected #26 overall by Indiana in 2012. Played 7 NBA seasons with the Pacers, Suns, Bucks, and Hawks. Won an NBL championship with the Perth Wildcats (Australia) in 2020. Signed a notable 4-year, $50M deal with Milwaukee in 2016.",
        sourceUrl: "https://en.wikipedia.org/wiki/Miles_Plumlee",
      },
      membership: { role: "PLAYER", jerseyNumber: 21, position: "Forward / Center", yearsAtSchool: "2008-2012", statsNote: "Senior • 22 rebounds vs Maryland (Coach K record) • #26 pick", gamesPlayed: 34, pointsPerGame: 5.2, reboundsPerGame: 7.1, assistsPerGame: 0.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2011-12", yearLabel: "2011-12 (Senior)", sortOrder: 204, gamesPlayed: 34, pointsPerGame: 5.2, reboundsPerGame: 7.1, assistsPerGame: 0.5, fieldGoalPct: 0.610 },
        { level: "PROFESSIONAL", teamName: "Indiana Pacers", season: "2012-13", yearLabel: "2012-13 (Rookie)", sortOrder: 301, gamesPlayed: 62, pointsPerGame: 2.8, reboundsPerGame: 2.5, assistsPerGame: 0.2 },
        { level: "PROFESSIONAL", teamName: "Phoenix Suns", season: "2014-15", yearLabel: "2014-15", sortOrder: 303, gamesPlayed: 58, pointsPerGame: 7.8, reboundsPerGame: 6.3, assistsPerGame: 0.5, fieldGoalPct: 0.515 },
      ],
      careerEvents: [
        { year: 2012, title: "Selected #26 overall by the Indiana Pacers", eventType: "DRAFT" },
        { year: 2016, title: "Signed 4-year, $50M deal with Milwaukee Bucks", eventType: "SIGNING" },
        { year: 2020, title: "Won NBL Championship with Perth Wildcats (Australia)", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "quinn-cook",
      firstName: "Quinn",
      lastName: "Cook",
      birthYear: 1993,
      hometown: "Washington, D.C.",
      highSchool: "DeMatha Catholic High School, Hyattsville, MD",
      isFeatured: false,
      bio: "A freshman point guard averaging 4.4 PPG who would develop into the captain of the 2015 championship team.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        statusNote: "2x NBA champion (Warriors 2018, Lakers 2020).",
        sourceUrl: "https://en.wikipedia.org/wiki/Quinn_Cook",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Point Guard", yearsAtSchool: "2011-2015", statsNote: "Freshman • 4.4 PPG • Future 2x NBA champion", gamesPlayed: 33, pointsPerGame: 4.4, reboundsPerGame: 1.0, assistsPerGame: 1.9 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2011-12", yearLabel: "2011-12 (Freshman)", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 4.4, reboundsPerGame: 1.0, assistsPerGame: 1.9 },
      ],
      careerEvents: [],
    },
    {
      slug: "ryan-kelly",
      firstName: "Ryan",
      lastName: "Kelly",
      birthYear: 1991,
      hometown: "Raleigh, NC",
      highSchool: "Ravenscroft School, Raleigh, NC",
      isFeatured: false,
      bio: "A junior stretch forward who averaged 11.8 PPG.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Fukui Blowinds",
        league: "B.League (Japan)",
        statusNote: "Now in his 7th season in Japan, averaging 15.9 PPG with Fukui Blowinds.",
        sourceUrl: "https://en.wikipedia.org/wiki/Ryan_Kelly_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 34, position: "Forward", yearsAtSchool: "2009-2013", statsNote: "Junior • 11.8 PPG • Stretch four", gamesPlayed: 34, pointsPerGame: 11.8, reboundsPerGame: 5.4, assistsPerGame: 1.0 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2011-12", yearLabel: "2011-12 (Junior)", sortOrder: 203, gamesPlayed: 34, pointsPerGame: 11.8, reboundsPerGame: 5.4, assistsPerGame: 1.0 },
      ],
      careerEvents: [],
    },
    {
      slug: "mike-krzyzewski",
      firstName: "Mike",
      lastName: "Krzyzewski",
      birthYear: 1947,
      hometown: "Chicago, IL",
      highSchool: "Weber High School, Chicago, IL",
      isFeatured: true,
      bio: "Suffered one of the most shocking upsets in NCAA Tournament history — a loss to #15 seed Lehigh in the first round.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Special Advisor / Duke Ambassador",
        currentEmployer: "NBA / Duke University",
        location: "Durham, NC",
        statusNote: "Retired with 1,202 victories and five national championships.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Krzyzewski",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "1980-2022", statsNote: "27-7 • Lost to #15 Lehigh in R64 (historic upset)" },
      careerEvents: [
        { year: 2012, title: "Lost to #15 Lehigh 75-70 in NCAA Tournament (historic upset)", eventType: "OTHER" },
      ],
    },
  ],
};
