import type { TeamSeed } from "./types";

export const dukeBasketball2023: TeamSeed = {
  slug: "duke-basketball-2023",
  name: "Duke Blue Devils",
  season: "2022-2023",
  sport: "Men's Basketball",
  school: "Duke University",
  conference: "ACC",
  accomplishment: "27-9, Second Round (Jon Scheyer's First Season)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  mascotName: "Blue Devil",
  people: [
    {
      slug: "dereck-lively-ii",
      firstName: "Dereck",
      lastName: "Lively II",
      birthYear: 2004,
      hometown: "Philadelphia, PA",
      highSchool: "Westtown School, West Chester, PA",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1641724.png",
      bio: "The #1 overall recruit in the 2022 class who became one of the NCAA's best shot blockers. Averaged 7.3 PPG, 5.8 RPG, and 2.4 BPG as a freshman before being drafted #12 overall. His rim protection transformed Duke's defense.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "Dallas Mavericks",
        league: "NBA",
        location: "Dallas, TX",
        statusNote: "Selected #12 overall by the Dallas Mavericks in 2023. Had an incredible rookie season, becoming a key starter and helping Dallas reach the 2024 NBA Finals. Averaged 8.8 PPG, 6.9 RPG, and 1.1 BPG as a rookie while shooting 74.5% from the field. His rim protection and lob-catching ability have made him one of the best young centers in the NBA.",
        sourceUrl: "https://en.wikipedia.org/wiki/Dereck_Lively_II",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Center", yearsAtSchool: "2022-2023", statsNote: "7.3 PPG, 5.8 RPG, 2.4 BPG · #1 recruit · #12 pick", gamesPlayed: 36, pointsPerGame: 7.3, reboundsPerGame: 5.8, assistsPerGame: 0.8 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Westtown School", season: "2021-22", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 14.5, reboundsPerGame: 9.8, blocksPerGame: 4.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2022-23", yearLabel: "2022-23", sortOrder: 201, gamesPlayed: 36, minutesPerGame: 22.8, pointsPerGame: 7.3, reboundsPerGame: 5.8, blocksPerGame: 2.4, fieldGoalPct: 0.667, freeThrowPct: 0.624 },
        { level: "PROFESSIONAL", teamName: "Dallas Mavericks", season: "2023-24", yearLabel: "2023-24 (Rookie, Finals)", sortOrder: 301, gamesPlayed: 55, minutesPerGame: 22.5, pointsPerGame: 8.8, reboundsPerGame: 6.9, blocksPerGame: 1.1, fieldGoalPct: 0.745, freeThrowPct: 0.615 },
        { level: "PROFESSIONAL", teamName: "Dallas Mavericks", season: "2024-25", yearLabel: "2024-25", sortOrder: 302, gamesPlayed: 65, minutesPerGame: 28.0, pointsPerGame: 11.5, reboundsPerGame: 8.2, blocksPerGame: 1.5, fieldGoalPct: 0.700, freeThrowPct: 0.650 },
      ],
      careerEvents: [
        { year: 2023, title: "Selected #12 overall by Dallas Mavericks", eventType: "DRAFT" },
        { year: 2024, title: "Reached NBA Finals as a rookie", eventType: "MILESTONE" },
      ],
    },
    {
      slug: "kyle-filipowski",
      firstName: "Kyle",
      lastName: "Filipowski",
      birthYear: 2003,
      hometown: "Wilbraham, MA",
      highSchool: "Wilbraham & Monson Academy, Wilbraham, MA",
      isFeatured: true,
      bio: "Freshman center/forward who was Duke's leading scorer at 15.1 PPG. Named ACC Freshman of the Year and was one of the most efficient big men in college basketball.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center / Power Forward",
        currentEmployer: "Utah Jazz",
        league: "NBA",
        location: "Salt Lake City, UT",
        statusNote: "Returned for his sophomore year in 2023-24 before being drafted #32 overall by the Utah Jazz. Known for his high basketball IQ, passing ability, and shooting for a 7-footer. Working to establish himself as an NBA rotation player.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kyle_Filipowski",
      },
      membership: { role: "PLAYER", jerseyNumber: 30, position: "Center / Power Forward", yearsAtSchool: "2022-2024", statsNote: "15.1 PPG, 8.9 RPG · ACC FOY · All-ACC 2nd Team", gamesPlayed: 36, pointsPerGame: 15.1, reboundsPerGame: 8.9, assistsPerGame: 1.5 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Wilbraham & Monson Academy", season: "2021-22", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 20.5, reboundsPerGame: 10.0, assistsPerGame: 2.5, blocksPerGame: 2.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2022-23", yearLabel: "2022-23 (ACC FOY)", sortOrder: 201, gamesPlayed: 36, minutesPerGame: 33.4, pointsPerGame: 15.1, reboundsPerGame: 8.9, assistsPerGame: 1.5, blocksPerGame: 1.2, fieldGoalPct: 0.517, threePointPct: 0.318, freeThrowPct: 0.830 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2023-24", yearLabel: "2023-24", sortOrder: 202, gamesPlayed: 36, minutesPerGame: 33.0, pointsPerGame: 16.4, reboundsPerGame: 8.3, assistsPerGame: 2.8, fieldGoalPct: 0.505, threePointPct: 0.345, freeThrowPct: 0.815 },
        { level: "PROFESSIONAL", teamName: "Utah Jazz", season: "2024-25", yearLabel: "2024-25 (Rookie)", sortOrder: 301, gamesPlayed: 50, minutesPerGame: 15.0, pointsPerGame: 5.5, reboundsPerGame: 3.8, assistsPerGame: 1.2, fieldGoalPct: 0.460, threePointPct: 0.310, freeThrowPct: 0.780 },
      ],
      careerEvents: [
        { year: 2024, title: "Selected #32 overall by Utah Jazz", eventType: "DRAFT" },
      ],
    },
    {
      slug: "jeremy-roach",
      firstName: "Jeremy",
      lastName: "Roach",
      birthYear: 2002,
      hometown: "Leesburg, VA",
      highSchool: "Paul VI Catholic High School, Chantilly, VA",
      bio: "Junior point guard and three-year starter who averaged 13.2 PPG and 4.8 APG. Duke's most experienced guard and emotional leader.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        league: "NBA / G-League",
        statusNote: "Returned for his senior season in 2023-24 before signing as an undrafted free agent.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jeremy_Roach",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Point Guard", yearsAtSchool: "2020-2024", statsNote: "13.2 PPG, 4.8 APG · 3-year starter · Team leader" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2022-23", yearLabel: "2022-23", sortOrder: 203, gamesPlayed: 36, minutesPerGame: 31.5, pointsPerGame: 13.2, reboundsPerGame: 3.2, assistsPerGame: 4.8, stealsPerGame: 0.8, fieldGoalPct: 0.435, threePointPct: 0.370, freeThrowPct: 0.800 },
      ],
      careerEvents: [],
    },
    {
      slug: "dariq-whitehead",
      firstName: "Dariq",
      lastName: "Whitehead",
      birthYear: 2003,
      hometown: "Newark, NJ",
      highSchool: "Montverde Academy, Montverde, FL",
      isFeatured: false,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1641726.png",
      bio: "Five-star freshman wing who was the #2 recruit in the class but missed the first month with a foot injury. Showed flashes of elite talent when healthy.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Small Forward",
        currentEmployer: "Brooklyn Nets",
        league: "NBA",
        location: "Brooklyn, NY",
        statusNote: "Selected #20 overall by the Brooklyn Nets in 2023. Has been developing as a young wing in the NBA, splitting time between the roster and G-League. His ceiling remains high due to his length, athleticism, and two-way potential.",
        sourceUrl: "https://en.wikipedia.org/wiki/Dariq_Whitehead",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Small Forward", yearsAtSchool: "2022-2023", statsNote: "6.0 PPG · Missed first month (foot injury) · #2 recruit · #20 pick" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Montverde Academy", season: "2021-22", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 15.0, reboundsPerGame: 5.5, assistsPerGame: 2.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2022-23", yearLabel: "2022-23", sortOrder: 201, gamesPlayed: 28, minutesPerGame: 18.5, pointsPerGame: 6.0, reboundsPerGame: 2.5, assistsPerGame: 1.0, fieldGoalPct: 0.380, threePointPct: 0.320 },
        { level: "PROFESSIONAL", teamName: "Brooklyn Nets", season: "2023-24", yearLabel: "2023-24 (Rookie)", sortOrder: 301, gamesPlayed: 32, minutesPerGame: 12.5, pointsPerGame: 3.5, reboundsPerGame: 1.8, fieldGoalPct: 0.370, threePointPct: 0.300 },
        { level: "PROFESSIONAL", teamName: "Brooklyn Nets", season: "2024-25", yearLabel: "2024-25", sortOrder: 302, gamesPlayed: 55, minutesPerGame: 20.0, pointsPerGame: 8.0, reboundsPerGame: 3.0, assistsPerGame: 1.5, fieldGoalPct: 0.420, threePointPct: 0.340 },
      ],
      careerEvents: [
        { year: 2023, title: "Selected #20 overall by Brooklyn Nets", eventType: "DRAFT" },
      ],
    },
    {
      slug: "tyrese-proctor",
      firstName: "Tyrese",
      lastName: "Proctor",
      birthYear: 2003,
      hometown: "Sydney, Australia",
      highSchool: "NBA Global Academy, Canberra, Australia",
      bio: "Australian freshman point guard who showed poise and playmaking ability despite a steep learning curve in his first season in the US.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Duke University",
        league: "ACC",
        location: "Durham, NC",
        statusNote: "Became Duke's starting point guard as a sophomore and junior. Expected to be a 2025 NBA Draft pick.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/tyrese-proctor/16429",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Point Guard", yearsAtSchool: "2022-2025", statsNote: "5.5 PPG, 3.0 APG as freshman · Australian international" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2022-23", yearLabel: "2022-23", sortOrder: 201, gamesPlayed: 33, minutesPerGame: 22.5, pointsPerGame: 5.5, reboundsPerGame: 2.0, assistsPerGame: 3.0, fieldGoalPct: 0.375, threePointPct: 0.310 },
      ],
      careerEvents: [],
    },
    {
      slug: "mark-mitchell",
      firstName: "Mark",
      lastName: "Mitchell",
      birthYear: 2004,
      hometown: "Kansas City, MO",
      highSchool: "Sunrise Christian Academy, Bel Aire, KS",
      bio: "Five-star freshman forward who averaged 7.9 PPG. His athleticism and defensive potential made him a key contributor on a talented roster.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Duke University",
        league: "ACC",
        location: "Durham, NC",
        statusNote: "Returned for his sophomore season in 2023-24, improving to 11.5 PPG. Declared for the 2024 NBA Draft but went undrafted. Transferred to Missouri for the 2024-25 season.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mark_Mitchell_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 25, position: "Small Forward / Power Forward", yearsAtSchool: "2022-2024", statsNote: "7.9 PPG as freshman · 5-star recruit · Transferred to Missouri" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Sunrise Christian Academy", season: "2021-22", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 18.0, reboundsPerGame: 7.5, assistsPerGame: 2.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2022-23", yearLabel: "2022-23", sortOrder: 201, gamesPlayed: 36, minutesPerGame: 20.0, pointsPerGame: 7.9, reboundsPerGame: 3.5, assistsPerGame: 0.8, fieldGoalPct: 0.475, freeThrowPct: 0.690 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2023-24", yearLabel: "2023-24", sortOrder: 202, gamesPlayed: 36, minutesPerGame: 28.0, pointsPerGame: 11.5, reboundsPerGame: 5.2, assistsPerGame: 1.5, fieldGoalPct: 0.480, freeThrowPct: 0.720 },
      ],
      careerEvents: [
        { year: 2024, title: "Transferred to University of Missouri", eventType: "OTHER" },
      ],
    },
    {
      slug: "jacob-grandison",
      firstName: "Jacob",
      lastName: "Grandison",
      birthYear: 2000,
      hometown: "Chatsworth, CA",
      highSchool: "Sierra Canyon School, Chatsworth, CA",
      bio: "Grad transfer from Illinois who provided veteran scoring and shooting. Averaged 7.5 PPG and shot 35% from three.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard / Forward",
        league: "Overseas",
        statusNote: "Went undrafted after his season at Duke. Has played professionally overseas.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jacob_Grandison",
      },
      membership: { role: "PLAYER", jerseyNumber: 13, position: "Small Forward", yearsAtSchool: "2022-2023", statsNote: "7.5 PPG · Grad transfer from Illinois · Veteran shooter" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2022-23", yearLabel: "2022-23", sortOrder: 205, gamesPlayed: 36, minutesPerGame: 21.0, pointsPerGame: 7.5, reboundsPerGame: 2.5, assistsPerGame: 1.2, fieldGoalPct: 0.430, threePointPct: 0.350, freeThrowPct: 0.810 },
      ],
      careerEvents: [],
    },
    {
      slug: "ryan-young",
      firstName: "Ryan",
      lastName: "Young",
      birthYear: 2000,
      hometown: "Upper Darby, PA",
      highSchool: "Bonner-Prendergast Catholic High School, Drexel Hill, PA",
      bio: "Grad transfer center from Northwestern who provided veteran post presence. At 6-10 and 240 lbs, he was a tough matchup in the paint.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Citizen",
        location: "Pennsylvania",
        statusNote: "Played five college seasons across Northwestern and Duke. His basketball career concluded after the 2022-23 season.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/ryan-young/16430",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Center", yearsAtSchool: "2022-2023", statsNote: "5.8 PPG, 4.5 RPG · Grad transfer from Northwestern" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2022-23", yearLabel: "2022-23", sortOrder: 206, gamesPlayed: 34, minutesPerGame: 15.0, pointsPerGame: 5.8, reboundsPerGame: 4.5, fieldGoalPct: 0.540, freeThrowPct: 0.680 },
      ],
      careerEvents: [],
    },
    {
      slug: "jaylen-blakes",
      firstName: "Jaylen",
      lastName: "Blakes",
      birthYear: 2003,
      hometown: "Manakin-Sabot, VA",
      highSchool: "Blessed Sacrament Huguenot, Powhatan, VA",
      bio: "Sophomore guard known for his fearless on-ball defense and energy. Averaged 4.5 PPG off the bench.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Duke University",
        league: "ACC",
        location: "Durham, NC",
        statusNote: "Four-year Duke player known for defensive intensity.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/jaylen-blakes/14904",
      },
      membership: { role: "PLAYER", jerseyNumber: 32, position: "Point Guard", yearsAtSchool: "2021-2025", statsNote: "4.5 PPG · Defensive spark plug · Fan favorite" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2022-23", yearLabel: "2022-23", sortOrder: 202, gamesPlayed: 36, minutesPerGame: 12.0, pointsPerGame: 4.5, reboundsPerGame: 1.2, assistsPerGame: 1.8, stealsPerGame: 0.8, fieldGoalPct: 0.420, threePointPct: 0.350 },
      ],
      careerEvents: [],
    },
    {
      slug: "caleb-foster",
      firstName: "Caleb",
      lastName: "Foster",
      birthYear: 2005,
      hometown: "Wilmington, NC",
      highSchool: "Notre Dame High School, Sherman Oaks, CA",
      bio: "Five-star freshman point guard recruit who enrolled early. Did not play in 2022-23 (arrived for 2023-24).",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Duke University",
        league: "ACC",
        location: "Durham, NC",
        statusNote: "Five-star recruit who became a key player in 2023-24 and 2024-25.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/caleb-foster/17252",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Point Guard", yearsAtSchool: "2023-present", statsNote: "Did not play 2022-23 · Key player in subsequent years" },
      seasonStats: [],
      careerEvents: [],
    },
    {
      slug: "joey-baker",
      firstName: "Joey",
      lastName: "Baker",
      birthYear: 1999,
      hometown: "Fayetteville, NC",
      highSchool: "Trinity Christian School, Fayetteville, NC",
      bio: "Fifth-year senior who provided veteran shooting off the bench. A key presence in the locker room across five Duke seasons.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Citizen",
        location: "North Carolina",
        statusNote: "Five-year Duke player (2018-23) who shot 38% from three across his career. Went undrafted after graduation.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/joey-baker/11460",
      },
      membership: { role: "PLAYER", jerseyNumber: 13, position: "Small Forward", yearsAtSchool: "2018-2023", statsNote: "4.8 PPG · 5th-year senior · Career 38% from three" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2022-23", yearLabel: "2022-23 (5th year)", sortOrder: 205, gamesPlayed: 33, minutesPerGame: 12.0, pointsPerGame: 4.8, reboundsPerGame: 1.2, fieldGoalPct: 0.400, threePointPct: 0.380 },
      ],
      careerEvents: [],
    },
    {
      slug: "kale-catchings",
      firstName: "Kale",
      lastName: "Catchings",
      birthYear: 2003,
      hometown: "Las Vegas, NV",
      highSchool: "Brewster Academy, Wolfeboro, NH",
      bio: "Freshman forward who provided defensive energy and toughness. Son of former WNBA star Tamika Catchings.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        location: "Durham, NC",
        statusNote: "Son of WNBA legend Tamika Catchings. Played limited minutes as a freshman at Duke before transferring.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/kale-catchings/16428",
      },
      membership: { role: "PLAYER", jerseyNumber: 24, position: "Small Forward", yearsAtSchool: "2022-2023", statsNote: "1.5 PPG · Son of Tamika Catchings" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Brewster Academy", season: "2021-22", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 12.0, reboundsPerGame: 6.5, assistsPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2022-23", yearLabel: "2022-23", sortOrder: 201, gamesPlayed: 25, minutesPerGame: 6.0, pointsPerGame: 1.5, reboundsPerGame: 1.0, fieldGoalPct: 0.380 },
      ],
      careerEvents: [],
    },
    {
      slug: "christian-reeves",
      firstName: "Christian",
      lastName: "Reeves",
      birthYear: 2004,
      hometown: "Memphis, TN",
      highSchool: "Lausanne Collegiate School, Memphis, TN",
      bio: "Walk-on center who provided depth in practice. At 7-1, he gave the team a tall body to prepare against opposing big men.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Student",
        currentEmployer: "Duke University",
        location: "Durham, NC",
        statusNote: "Walk-on who contributed in practice and earned playing time in blowouts.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster",
      },
      membership: { role: "PLAYER", jerseyNumber: 33, position: "Center", yearsAtSchool: "2022-present", statsNote: "Walk-on · 7-1 center · Practice contributor" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2022-23", yearLabel: "2022-23", sortOrder: 207, gamesPlayed: 8, minutesPerGame: 2.0, pointsPerGame: 0.5, reboundsPerGame: 0.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "jon-scheyer",
      firstName: "Jon",
      lastName: "Scheyer",
      birthYear: 1987,
      hometown: "Northbrook, IL",
      highSchool: "Glenbrook North High School, Northbrook, IL",
      bio: "First-year head coach taking over from Coach K. Led Duke to a 27-9 record despite the enormous pressure of succeeding a legend.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "Duke University",
        league: "ACC",
        location: "Durham, NC",
        statusNote: "Former Duke player (2006-10) and 2010 national champion who succeeded Coach K. 27-9 in his first season (2022-23), 27-9 again in year two, and 33-5 with a Final Four in year three.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jon_Scheyer",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2022-present", statsNote: "27-9 · Second Round · First season as HC" },
      seasonStats: [
        { level: "COACHING", teamName: "Duke Blue Devils", season: "2022-23", yearLabel: "2022-23 (1st season)", sortOrder: 1, wins: 27, losses: 9, tournamentResult: "Second Round (lost to Tennessee)" },
      ],
      careerEvents: [
        { year: 2022, title: "Named head coach at Duke", eventType: "COACHING" },
      ],
    },
    {
      slug: "nolan-smith",
      firstName: "Nolan",
      lastName: "Smith",
      birthYear: 1988,
      hometown: "Hyattsville, MD",
      highSchool: "Oak Hill Academy, Mouth of Wilson, VA",
      bio: "Former Duke star (2007-11) and ACC Player of the Year who returned to Duke as an assistant coach.",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Coach",
        currentEmployer: "Duke University",
        league: "ACC",
        location: "Durham, NC",
        statusNote: "2010 national champion as a player, 2011 ACC POY. Joined Duke staff and is one of Scheyer's top assistants and recruiters.",
        sourceUrl: "https://en.wikipedia.org/wiki/Nolan_Smith",
      },
      membership: { role: "ASSISTANT_COACH", position: "Assistant Coach", yearsAtSchool: "2022-present", statsNote: "2010 champion · 2011 ACC POY · Elite recruiter" },
      careerEvents: [],
    },
    {
      slug: "chris-carrawell",
      firstName: "Chris",
      lastName: "Carrawell",
      birthYear: 1977,
      hometown: "St. Louis, MO",
      highSchool: "Cardinal Ritter College Prep, St. Louis, MO",
      bio: "Former Duke captain (1996-2000) and ACC Player of the Year who has been on the Duke coaching staff for over a decade.",
      status: {
        occupationType: "COACH",
        currentTitle: "Associate Head Coach",
        currentEmployer: "Duke University",
        league: "ACC",
        location: "Durham, NC",
        statusNote: "2000 ACC Player of the Year as a player. One of the longest-tenured assistants in Duke history. Associate head coach under Scheyer.",
        sourceUrl: "https://en.wikipedia.org/wiki/Chris_Carrawell",
      },
      membership: { role: "ASSISTANT_COACH", position: "Associate Head Coach", yearsAtSchool: "2011-present", statsNote: "2000 ACC POY · Longest-tenured Duke assistant" },
      careerEvents: [],
    },
  ],
};
