import type { TeamSeed } from "./types";

export const dukeBasketball2013: TeamSeed = {
  slug: "duke-basketball-2013",
  name: "Duke Blue Devils",
  season: "2012-2013",
  sport: "Men's Basketball",
  school: "Duke University",
  conference: "ACC",
  accomplishment: "Elite Eight (30-6)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  mascotName: "Blue Devil",
  people: [
    {
      slug: "seth-curry",
      firstName: "Seth",
      lastName: "Curry",
      birthYear: 1990,
      hometown: "Charlotte, NC",
      highSchool: "Charlotte Christian School, Charlotte, NC",

      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/203552.png",
      isFeatured: true,
      bio: "A senior sharpshooter who averaged 17.5 PPG and shot 43.8% from three. Named All-ACC First Team.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Golden State Warriors",
        league: "NBA",
        location: "San Francisco, CA",
        statusNote: "Went undrafted in 2013 but carved out an 11-year NBA career with 8 teams. Now playing alongside brother Stephen Curry on the Warriors. Career 44.3% three-point shooter, one of the best in NBA history.",
        sourceUrl: "https://en.wikipedia.org/wiki/Seth_Curry",
      },
      membership: {
        role: "PLAYER", jerseyNumber: 30, position: "Guard", yearsAtSchool: "2008-2013",
        statsNote: "Senior • All-ACC First Team • 17.5 PPG • 43.8% from three",
        gamesPlayed: 34, pointsPerGame: 17.5, reboundsPerGame: 3.9, assistsPerGame: 2.7,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Charlotte Christian School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 31.2, reboundsPerGame: 3.9, assistsPerGame: 5.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2012-13", yearLabel: "2012-13 (Senior, All-ACC)", sortOrder: 205, gamesPlayed: 34, pointsPerGame: 17.5, reboundsPerGame: 3.9, assistsPerGame: 2.7, threePointPct: 0.438 },
      
        { level: "PROFESSIONAL", teamName: "Sacramento Kings", season: "2014-15", yearLabel: "2014-15", sortOrder: 301, gamesPlayed: 18, minutesPerGame: 7.3, pointsPerGame: 4.1, reboundsPerGame: 0.3, assistsPerGame: 0.6, fieldGoalPct: 0.455, threePointPct: 0.364 },
        { level: "PROFESSIONAL", teamName: "Dallas Mavericks", season: "2016-17", yearLabel: "2016-17", sortOrder: 303, gamesPlayed: 70, minutesPerGame: 22.0, pointsPerGame: 12.8, reboundsPerGame: 2.0, assistsPerGame: 2.6, fieldGoalPct: 0.478, threePointPct: 0.425, freeThrowPct: 0.846 },
        { level: "PROFESSIONAL", teamName: "Portland Trail Blazers", season: "2018-19", yearLabel: "2018-19", sortOrder: 305, gamesPlayed: 74, minutesPerGame: 18.9, pointsPerGame: 7.9, reboundsPerGame: 1.5, assistsPerGame: 1.6, fieldGoalPct: 0.454, threePointPct: 0.450, freeThrowPct: 0.851 },
        { level: "PROFESSIONAL", teamName: "Dallas / Philadelphia", season: "2020-21", yearLabel: "2020-21", sortOrder: 307, gamesPlayed: 57, minutesPerGame: 28.0, pointsPerGame: 12.5, reboundsPerGame: 2.3, assistsPerGame: 2.9, fieldGoalPct: 0.491, threePointPct: 0.450, freeThrowPct: 0.911 },
        { level: "PROFESSIONAL", teamName: "Philadelphia / Brooklyn", season: "2021-22", yearLabel: "2021-22", sortOrder: 308, gamesPlayed: 46, minutesPerGame: 23.3, pointsPerGame: 10.0, reboundsPerGame: 1.9, assistsPerGame: 1.8, fieldGoalPct: 0.467, threePointPct: 0.400, freeThrowPct: 0.882 }
      ],
      careerEvents: [
        { year: 2013, title: "Went undrafted; began NBA journey through D-League", eventType: "CAREER" },
        { year: 2025, title: "Signed with Golden State Warriors — playing with brother Steph", eventType: "SIGNING" },
      ],
    },
    {
      slug: "mason-plumlee",
      firstName: "Mason",
      lastName: "Plumlee",
      birthYear: 1990,
      hometown: "Warsaw, IN",
      highSchool: "Christ School, Arden, NC",

      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/203486.png",
      isFeatured: true,
      bio: "A dominant senior center who averaged 17.1 PPG and 10.1 RPG. Named ACC POY runner-up and First-Team All-American.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "Charlotte Hornets",
        league: "NBA",
        location: "Charlotte, NC",
        statusNote: "Selected #22 overall by Brooklyn in 2013. Now in his 13th NBA season with the Hornets. 2016 Olympic gold medalist.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mason_Plumlee",
      },
      membership: {
        role: "PLAYER", jerseyNumber: 5, position: "Center", yearsAtSchool: "2009-2013",
        statsNote: "Senior • First-Team All-American • 17.1 PPG, 10.1 RPG • #22 pick",
        gamesPlayed: 36, pointsPerGame: 17.1, reboundsPerGame: 10.1, assistsPerGame: 1.8,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Christ School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 30.7, reboundsPerGame: 15.0, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2012-13", yearLabel: "2012-13 (Senior, All-American)", sortOrder: 204, gamesPlayed: 36, pointsPerGame: 17.1, reboundsPerGame: 10.1, assistsPerGame: 1.8, fieldGoalPct: 0.609 },
      
        { level: "PROFESSIONAL", teamName: "Brooklyn Nets", season: "2013-14", yearLabel: "2013-14 (Rookie)", sortOrder: 301, gamesPlayed: 70, minutesPerGame: 17.8, pointsPerGame: 7.4, reboundsPerGame: 4.4, assistsPerGame: 1.5, fieldGoalPct: 0.562 },
        { level: "PROFESSIONAL", teamName: "Brooklyn Nets", season: "2014-15", yearLabel: "2014-15", sortOrder: 302, gamesPlayed: 82, minutesPerGame: 21.8, pointsPerGame: 8.7, reboundsPerGame: 5.8, assistsPerGame: 2.0, fieldGoalPct: 0.568 },
        { level: "PROFESSIONAL", teamName: "Portland / Denver", season: "2016-17", yearLabel: "2016-17", sortOrder: 304, gamesPlayed: 82, minutesPerGame: 21.5, pointsPerGame: 9.1, reboundsPerGame: 6.4, assistsPerGame: 2.7, fieldGoalPct: 0.563 },
        { level: "PROFESSIONAL", teamName: "Denver Nuggets", season: "2018-19", yearLabel: "2018-19", sortOrder: 306, gamesPlayed: 82, minutesPerGame: 22.4, pointsPerGame: 7.8, reboundsPerGame: 6.4, assistsPerGame: 3.0, fieldGoalPct: 0.587 },
        { level: "PROFESSIONAL", teamName: "Detroit / Charlotte", season: "2021-22", yearLabel: "2021-22", sortOrder: 309, gamesPlayed: 56, minutesPerGame: 17.7, pointsPerGame: 5.3, reboundsPerGame: 4.1, assistsPerGame: 1.8, fieldGoalPct: 0.573 }
      ],
      careerEvents: [
        { year: 2013, title: "Selected #22 overall by the Brooklyn Nets", eventType: "DRAFT" },
        { year: 2016, title: "Won Olympic Gold with Team USA", eventType: "AWARD" },
      ],
    },
    {
      slug: "quinn-cook",
      firstName: "Quinn",
      lastName: "Cook",
      birthYear: 1993,
      hometown: "Washington, D.C.",
      highSchool: "DeMatha Catholic High School, Hyattsville, MD",
      isFeatured: false,
      bio: "A sophomore point guard who averaged 11.7 PPG and 5.3 APG. Would captain the 2015 championship team.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        statusNote: "2x NBA champion (Warriors 2018, Lakers 2020). Still playing professionally overseas.",
        sourceUrl: "https://en.wikipedia.org/wiki/Quinn_Cook",
      },
      membership: {
        role: "PLAYER", jerseyNumber: 2, position: "Point Guard", yearsAtSchool: "2011-2015",
        statsNote: "Sophomore • 11.7 PPG, 5.3 APG • Floor general",
        gamesPlayed: 36, pointsPerGame: 11.7, reboundsPerGame: 3.8, assistsPerGame: 5.3,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "DeMatha Catholic High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 22.5, reboundsPerGame: 3.8, assistsPerGame: 8.9 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2012-13", yearLabel: "2012-13 (Sophomore)", sortOrder: 202, gamesPlayed: 36, pointsPerGame: 11.7, reboundsPerGame: 3.8, assistsPerGame: 5.3 },
      ],
      careerEvents: [
        { year: 2015, title: "Won NCAA Championship (senior captain)", eventType: "CHAMPIONSHIP" },
        { year: 2018, title: "Won NBA Championship with Warriors", eventType: "CHAMPIONSHIP" },
        { year: 2020, title: "Won NBA Championship with Lakers", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "rasheed-sulaimon",
      firstName: "Rasheed",
      lastName: "Sulaimon",
      birthYear: 1994,
      hometown: "Houston, TX",
      highSchool: "Strake Jesuit College Prep, Houston, TX",
      isFeatured: false,
      bio: "A talented freshman guard who averaged 11.6 PPG and was named to the ACC All-Freshman Team.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "KK Buducnost Podgorica",
        league: "ABA League",
        statusNote: "After being dismissed from Duke in January 2015 (first ever by Coach K), transferred to Maryland. Built successful overseas career in Turkey, Montenegro, Croatia. 12.3 PPG in 2025-26.",
        sourceUrl: "https://en.wikipedia.org/wiki/Rasheed_Sulaimon",
      },
      membership: {
        role: "PLAYER", jerseyNumber: 14, position: "Shooting Guard", yearsAtSchool: "2012-2015",
        statsNote: "Freshman • ACC All-Freshman Team • 11.6 PPG",
        gamesPlayed: 36, pointsPerGame: 11.6, reboundsPerGame: 3.4, assistsPerGame: 1.9,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Strake Jesuit College Prep", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 22.4, reboundsPerGame: 3.4, assistsPerGame: 4.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2012-13", yearLabel: "2012-13 (Freshman)", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 11.6, reboundsPerGame: 3.4, assistsPerGame: 1.9, threePointPct: 0.384 },
      ],
      careerEvents: [
        { year: 2015, title: "Dismissed from Duke — first player dismissed by Coach K", eventType: "OTHER" },
      ],
    },
    {
      slug: "ryan-kelly",
      firstName: "Ryan",
      lastName: "Kelly",
      birthYear: 1991,
      hometown: "Raleigh, NC",
      highSchool: "Ravenscroft School, Raleigh, NC",
      isFeatured: false,
      bio: "A senior stretch forward who scored 36 points on his return from a 13-game absence (foot injury) against #1 Miami — one of the most memorable individual performances in Duke history.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Fukui Blowinds",
        league: "B.League (Japan)",
        location: "Fukui, Japan",
        statusNote: "Selected #48 overall by Lakers in 2013. Now in his 7th season in Japan, averaging 15.9 PPG with Fukui Blowinds.",
        sourceUrl: "https://en.wikipedia.org/wiki/Ryan_Kelly_(basketball)",
      },
      membership: {
        role: "PLAYER", jerseyNumber: 34, position: "Forward", yearsAtSchool: "2009-2013",
        statsNote: "Senior captain • 12.9 PPG • 36 pts vs #1 Miami on return from injury",
        gamesPlayed: 23, pointsPerGame: 12.9, reboundsPerGame: 5.3, assistsPerGame: 1.6,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Ravenscroft School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 24.4, reboundsPerGame: 9.9, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2012-13", yearLabel: "2012-13 (Senior, 36 vs Miami!)", sortOrder: 204, gamesPlayed: 23, pointsPerGame: 12.9, reboundsPerGame: 5.3, assistsPerGame: 1.6 },
      
        { level: "PROFESSIONAL", teamName: "Los Angeles Lakers", season: "2013-14", yearLabel: "2013-14 (Rookie)", sortOrder: 301, gamesPlayed: 48, minutesPerGame: 12.2, pointsPerGame: 4.6, reboundsPerGame: 2.1, assistsPerGame: 0.7, fieldGoalPct: 0.391, threePointPct: 0.342 },
        { level: "PROFESSIONAL", teamName: "Los Angeles Lakers", season: "2014-15", yearLabel: "2014-15", sortOrder: 302, gamesPlayed: 54, minutesPerGame: 12.7, pointsPerGame: 4.8, reboundsPerGame: 2.3, assistsPerGame: 0.5, fieldGoalPct: 0.397, threePointPct: 0.313 }
      ],
      careerEvents: [
        { year: 2013, title: "Scored 36 points vs #1 Miami on return from 13-game absence", eventType: "OTHER" },
        { year: 2013, title: "Selected #48 overall by the LA Lakers", eventType: "DRAFT" },
      ],
    },
    {
      slug: "amile-jefferson",
      firstName: "Amile",
      lastName: "Jefferson",
      birthYear: 1994,
      hometown: "Philadelphia, PA",
      highSchool: "Friends' Central School, Wynnewood, PA",
      isFeatured: false,
      bio: "A freshman forward who shot 63.1% from the field. Would play a record 150 games at Duke.",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Coach",
        currentEmployer: "Boston Celtics",
        league: "NBA",
        location: "Boston, MA",
        statusNote: "Duke record 150 career games. Won 2015 NCAA title and 2024 NBA title as Celtics assistant.",
        sourceUrl: "https://en.wikipedia.org/wiki/Amile_Jefferson",
      },
      membership: {
        role: "PLAYER", jerseyNumber: 21, position: "Forward", yearsAtSchool: "2012-2017",
        statsNote: "Freshman • 63.1% FG • 6.1 PPG, 5.8 RPG",
        gamesPlayed: 36, pointsPerGame: 6.1, reboundsPerGame: 5.8, assistsPerGame: 0.5,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Friends' Central School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 14.1, reboundsPerGame: 10.5, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2012-13", yearLabel: "2012-13 (Freshman)", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 6.1, reboundsPerGame: 5.8, assistsPerGame: 0.5, fieldGoalPct: 0.631 },
      ],
      careerEvents: [
        { year: 2015, title: "Won NCAA Championship", eventType: "CHAMPIONSHIP" },
        { year: 2024, title: "Won NBA Championship as Celtics assistant", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "alex-murphy",
      firstName: "Alex",
      lastName: "Murphy",
      birthYear: 1993,
      hometown: "Wakefield, RI",
      highSchool: "St. Mark's School, Southborough, MA",
      isFeatured: false,
      bio: "A redshirt freshman forward who played in 31 games in 2012-13, averaging 2.1 PPG and shooting 49.1% from the field. Murphy would transfer after the season — first to Florida, then to Northeastern — before turning pro and going on to represent Finland at the FIBA Basketball World Cup.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Power Forward",
        currentEmployer: "Fuenlabrada",
        league: "LEB Gold (Spain)",
        location: "Madrid, Spain",
        statusNote:
          "After playing 31 games at Duke as a redshirt freshman and then transferring to Florida (5.1 PPG) and Northeastern (14.1 PPG as senior), Murphy turned pro in 2017. Through his Finnish mother he holds Finnish citizenship and has represented the Finland national team, competing in the 2023 FIBA Basketball World Cup. He has played professionally in Finland, Hungary, Japan's B.League, and Spain's LEB Gold league with Fuenlabrada.",
        sourceUrl: "https://en.wikipedia.org/wiki/Alex_Murphy_(basketball)",
      },
      membership: {
        role: "PLAYER", jerseyNumber: 12, position: "Forward", yearsAtSchool: "2011-2013",
        statsNote: "Redshirt Freshman • 31 games • 2.1 PPG • 49.1% FG • Transferred to Florida",
        gamesPlayed: 31, pointsPerGame: 2.1, reboundsPerGame: 1.5, assistsPerGame: 0.3,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "St. Mark's School", season: "2011-12", yearLabel: "Senior", sortOrder: 101, pointsPerGame: 12.5, reboundsPerGame: 8.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2012-13", yearLabel: "2012-13 (RS Freshman, 31 games)", sortOrder: 201, gamesPlayed: 31, pointsPerGame: 2.1, reboundsPerGame: 1.5, assistsPerGame: 0.3, fieldGoalPct: 0.491 },
      ],
      careerEvents: [
        { year: 2013, title: "Transferred from Duke to University of Florida", eventType: "CAREER" },
        { year: 2016, title: "Transferred to Northeastern; averaged 14.1 PPG as senior", eventType: "CAREER" },
        { year: 2017, title: "Signed first professional contract in Finland", eventType: "SIGNING" },
        { year: 2023, title: "Represented Finland at FIBA Basketball World Cup", eventType: "OTHER" },
      ],
    },
    {
      slug: "mike-krzyzewski",
      firstName: "Mike",
      lastName: "Krzyzewski",
      birthYear: 1947,
      hometown: "Chicago, IL",
      highSchool: "Weber High School, Chicago, IL",
      isFeatured: true,
      bio: "Led Duke to the Elite Eight before falling to Louisville.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Special Advisor / Duke Ambassador",
        currentEmployer: "NBA / Duke University",
        location: "Durham, NC",
        statusNote: "Retired with 1,202 victories and five national championships.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Krzyzewski",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "1980-2022", statsNote: "30-6 • Elite Eight (lost to Louisville)" },
      careerEvents: [],
    },
    {
      slug: "tyler-thornton",
      firstName: "Tyler",
      lastName: "Thornton",
      birthYear: 1992,
      hometown: "Silver Spring, MD",
      highSchool: "Gonzaga College High School, Washington, DC",
      isFeatured: false,
      bio: "A junior guard who appeared in all 36 games with six starts, providing lockdown defense. Shot .392 from three-point range and ranked 10th in the ACC in steals (1.3 SPG).",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Coach",
        currentEmployer: "Duke University",
        league: "NCAA",
        location: "Durham, NC",
        statusNote:
          "After graduating from Duke in 2014, Thornton began coaching at Marquette under fellow Duke alum Steve Wojciechowski, then spent six seasons at Howard University helping lead the Bison to back-to-back MEAC titles and NCAA Tournament bids (2023, 2024). Returned to Duke as an assistant coach under Jon Scheyer in May 2025.",
        sourceUrl: "https://goduke.com/staff-directory/tyler-thornton/1371",
        linkedInUrl: "https://www.linkedin.com/in/tyler-thornton-7723251a5/",
      },
      membership: {
        role: "PLAYER", jerseyNumber: 3, position: "Guard", yearsAtSchool: "2010-2014",
        statsNote: "Junior • 3.6 PPG, 2.2 APG, 1.3 SPG • .392 from three",
        gamesPlayed: 36, pointsPerGame: 3.6, reboundsPerGame: 2.3, assistsPerGame: 2.2,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Gonzaga College High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 10.4, reboundsPerGame: 2.3, assistsPerGame: 4.9 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2012-13", yearLabel: "2012-13 (Junior, Elite Eight)", sortOrder: 203, gamesPlayed: 36, pointsPerGame: 3.6, reboundsPerGame: 2.3, assistsPerGame: 2.2, stealsPerGame: 1.3, threePointPct: 0.392 },
      ],
      careerEvents: [
        { year: 2014, title: "Graduated from Duke; began coaching career at Marquette", eventType: "CAREER" },
        { year: 2025, title: "Returned to Duke as assistant coach under Jon Scheyer", eventType: "CAREER" },
      ],
    },
    {
      slug: "josh-hairston",
      firstName: "Josh",
      lastName: "Hairston",
      birthYear: 1992,
      hometown: "Fredericksburg, VA",
      highSchool: "Montrose Christian School, Rockville, MD",
      isFeatured: false,
      bio: "A junior forward who appeared in 35 games with six starts, providing energy and rebounding off the bench during Duke's Elite Eight run.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Sports Agent",
        currentEmployer: "Klutch Sports Group",
        location: "Los Angeles, CA",
        statusNote:
          "After graduating from Duke in 2014, Hairston played professionally overseas for five years in Switzerland, Germany, and Italy. Transitioned to the business side of basketball in 2020, ultimately joining Klutch Sports Group as an agent representing NBA players.",
        sourceUrl: "https://sportsagentblog.com/2020/07/20/former-duke-basketball-player-josh-hairston-has-eyes-set-on-becoming-an-nba-agent/",
        linkedInUrl: "https://www.linkedin.com/in/joshua-hairston-36b9811a4",
      },
      membership: {
        role: "PLAYER", jerseyNumber: 15, position: "Forward", yearsAtSchool: "2010-2014",
        statsNote: "Junior • 35 games, 6 starts • Energy player off bench",
        gamesPlayed: 35, pointsPerGame: 2.4, reboundsPerGame: 1.9, assistsPerGame: 0.3,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Montrose Christian School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 8.6, reboundsPerGame: 5.5, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2012-13", yearLabel: "2012-13 (Junior, Elite Eight)", sortOrder: 203, gamesPlayed: 35, pointsPerGame: 2.4, reboundsPerGame: 1.9, assistsPerGame: 0.3 },
      ],
      careerEvents: [
        { year: 2014, title: "Graduated from Duke; signed first pro contract in Switzerland", eventType: "SIGNING" },
        { year: 2020, title: "Began career as NBA agent", eventType: "CAREER" },
        { year: 2022, title: "Joined Klutch Sports Group", eventType: "CAREER" },
      ],
    },
    {
      slug: "marshall-plumlee",
      firstName: "Marshall",
      lastName: "Plumlee",
      birthYear: 1992,
      hometown: "Warsaw, IN",
      highSchool: "Christ School, Arden, NC",
      isFeatured: false,
      bio: "A redshirt freshman center who saw limited action due to a stress fracture in his left foot suffered in the preseason. The youngest Plumlee brother would later captain the 2015-16 squad.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Investor",
        currentEmployer: "Blackstone",
        location: "New York, NY",
        statusNote:
          "Went on to captain the 2015-16 Duke team, then played 29 NBA games with the Knicks and Bucks. Served as a U.S. Army Ranger officer before earning his MBA from Harvard Business School (Class of 2024). Now an investor at Blackstone.",
        sourceUrl: "https://en.wikipedia.org/wiki/Marshall_Plumlee",
        linkedInUrl: "https://www.linkedin.com/in/marshallplumlee/",
      },
      membership: {
        role: "PLAYER", jerseyNumber: 40, position: "Center", yearsAtSchool: "2011-2016",
        statsNote: "Redshirt Freshman • Limited by stress fracture • 1.9 PPG, 2.3 RPG",
        gamesPlayed: 20, pointsPerGame: 1.9, reboundsPerGame: 2.3, assistsPerGame: 0.4,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Christ School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 7.8, reboundsPerGame: 6.0, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2012-13", yearLabel: "2012-13 (RS Freshman, stress fracture)", sortOrder: 201, gamesPlayed: 20, pointsPerGame: 1.9, reboundsPerGame: 2.3, assistsPerGame: 0.4 },
      ],
      careerEvents: [
        { year: 2016, title: "Captained Duke team as a senior; averaged 8.3 PPG, 8.6 RPG", eventType: "OTHER" },
        { year: 2016, title: "Signed with New York Knicks as undrafted free agent", eventType: "SIGNING" },
        { year: 2019, title: "Graduated from U.S. Army Ranger School", eventType: "CAREER" },
        { year: 2024, title: "Joined Blackstone as an investor after Harvard MBA", eventType: "CAREER" },
      ],
    },
    {
      slug: "todd-zafirovski",
      firstName: "Todd",
      lastName: "Zafirovski",
      birthYear: 1990,
      hometown: "Lake Forest, IL",
      highSchool: "Lake Forest Academy, Lake Forest, IL",
      isFeatured: false,
      bio: "A senior walk-on forward who earned a scholarship. Set career highs with 3 points against Cornell. Graduated from Duke with a Psychology degree and was simultaneously enrolled in the Fuqua MBA program.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Regional Sales Manager",
        currentEmployer: "ACP CreativIT",
        location: "Chicago, IL",
        statusNote:
          "Graduated from Duke in 2013 with a Psychology degree and a Markets & Management Studies certificate, then earned an MBA from Fuqua. Has been with ACP CreativIT since 2018, rising from account executive to Regional Sales Manager in the IT solutions industry.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/todd-zafirovski/4386",
        linkedInUrl: "https://www.linkedin.com/in/toddzafirovski/",
      },
      membership: {
        role: "PLAYER", jerseyNumber: 52, position: "Forward", yearsAtSchool: "2009-2013",
        statsNote: "Senior • Walk-on who earned scholarship • Career-high 3 pts vs Cornell",
        gamesPlayed: 10, pointsPerGame: 0.5, reboundsPerGame: 0.3, assistsPerGame: 0.0,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Lake Forest Academy", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 5.8, reboundsPerGame: 3.4, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2012-13", yearLabel: "2012-13 (Senior)", sortOrder: 204, gamesPlayed: 10, pointsPerGame: 0.5, reboundsPerGame: 0.3, assistsPerGame: 0.0 },
      ],
      careerEvents: [
        { year: 2013, title: "Graduated from Duke with Psychology degree and Fuqua MBA", eventType: "CAREER" },
        { year: 2018, title: "Joined ACP CreativIT", eventType: "CAREER" },
      ],
    },
    {
      slug: "rodney-hood",
      firstName: "Rodney",
      lastName: "Hood",
      birthYear: 1992,
      hometown: "Meridian, MS",
      highSchool: "Meridian High School, Meridian, MS",
      isFeatured: false,
      bio: "A transfer from Mississippi State who sat out the 2012-13 season per NCAA transfer rules. He quickly established himself as one of the best players in practice and would become a star the following season.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NBA Player",
        location: "Durham, NC",
        statusNote:
          "After sitting out 2012-13, Hood averaged 16.1 PPG as a junior and was selected #23 overall by the Utah Jazz in 2014. Played 8 NBA seasons with the Jazz, Cavaliers, Trail Blazers, Bucks, and Clippers (career 10.4 PPG). Torn Achilles in 2020 hampered his later career. Retired in November 2024 and returned to Duke to complete his degree.",
        sourceUrl: "https://www.si.com/college/duke/basketball/duke-basketball-product-announces-retirement-teases-move-11-21-24",
      },
      membership: {
        role: "PLAYER", jerseyNumber: 5, position: "Guard / Forward", yearsAtSchool: "2012-2014",
        statsNote: "Transfer from Mississippi State • Sat out 2012-13 per NCAA rules",
        gamesPlayed: 0,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Meridian High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 12.5, reboundsPerGame: 8.0, blocksPerGame: 1.5 },],
      careerEvents: [
        { year: 2014, title: "Selected #23 overall by the Utah Jazz", eventType: "DRAFT" },
        { year: 2020, title: "Torn Achilles tendon", eventType: "INJURY" },
        { year: 2024, title: "Announced retirement; returned to Duke for degree", eventType: "RETIREMENT" },
      ],
    },
  ],
};
