import type { TeamSeed } from "./types";

export const dukeBasketball2020: TeamSeed = {
  slug: "duke-basketball-2020",
  name: "Duke Blue Devils",
  season: "2019-2020",
  sport: "Men's Basketball",
  school: "Duke University",
  conference: "ACC",
  accomplishment: "25-6, Season Ended by COVID-19",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  mascotName: "Blue Devil",
  people: [
    {
      slug: "tre-jones",
      firstName: "Tre",
      lastName: "Jones",
      birthYear: 2000,
      hometown: "Apple Valley, MN",
      highSchool: "Apple Valley High School, Apple Valley, MN",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1630200.png",
      isFeatured: true,
      bio: "Sophomore point guard who won ACC Player of the Year, averaging 16.2 PPG and 6.4 APG. Led Duke to a #1 seed before COVID-19 cancelled the tournament.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Point Guard",
        currentEmployer: "San Antonio Spurs",
        league: "NBA",
        location: "San Antonio, TX",
        statusNote: "Selected #41 overall by San Antonio. Has been a reliable backup PG, averaging career-best 8.8 PPG in 2023-24. Entering 6th NBA season.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tre_Jones",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Point Guard", yearsAtSchool: "2018-2020", statsNote: "ACC POY · 16.2 PPG, 6.4 APG · #41 pick · Season cut short by COVID" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2019-20", yearLabel: "2019-20 (ACC POY)", sortOrder: 202, gamesPlayed: 31, minutesPerGame: 34.8, pointsPerGame: 16.2, reboundsPerGame: 4.2, assistsPerGame: 6.4, stealsPerGame: 1.8, fieldGoalPct: 0.445, threePointPct: 0.363, freeThrowPct: 0.772 },
      ],
      careerEvents: [],
    },
    {
      slug: "vernon-carey-jr",
      firstName: "Vernon",
      lastName: "Carey Jr.",
      birthYear: 2001,
      hometown: "Fort Lauderdale, FL",
      highSchool: "University School, Fort Lauderdale, FL",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1630176.png",
      isFeatured: true,
      bio: "Freshman center and McDonald's All-American who dominated inside, averaging 17.8 PPG and 8.8 RPG. Named ACC Rookie of the Year.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        league: "NBA / Overseas",
        statusNote: "Selected #32 overall by Charlotte (traded to Brooklyn) in 2020. Has bounced between the NBA, G-League, and overseas, playing limited minutes with the Nets and Wizards. His NBA career hasn't matched his college production.",
        sourceUrl: "https://en.wikipedia.org/wiki/Vernon_Carey_Jr.",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Center", yearsAtSchool: "2019-2020", statsNote: "17.8 PPG, 8.8 RPG · ACC ROY · McDonald's AA · #32 pick", gamesPlayed: 31, pointsPerGame: 17.8, reboundsPerGame: 8.8, assistsPerGame: 1.2 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "University School", season: "2018-19", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 20.5, reboundsPerGame: 12.0, blocksPerGame: 3.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2019-20", yearLabel: "2019-20 (ACC ROY)", sortOrder: 201, gamesPlayed: 31, minutesPerGame: 30.2, pointsPerGame: 17.8, reboundsPerGame: 8.8, assistsPerGame: 1.2, blocksPerGame: 1.6, fieldGoalPct: 0.579, freeThrowPct: 0.674 },
        { level: "PROFESSIONAL", teamName: "Brooklyn Nets", season: "2020-21", yearLabel: "2020-21 (Rookie)", sortOrder: 301, gamesPlayed: 12, minutesPerGame: 5.5, pointsPerGame: 2.8, reboundsPerGame: 2.3, fieldGoalPct: 0.480 },
      ],
      careerEvents: [
        { year: 2020, title: "Selected #32 overall by Charlotte (traded to Brooklyn)", eventType: "DRAFT" },
      ],
    },
    {
      slug: "cassius-stanley",
      firstName: "Cassius",
      lastName: "Stanley",
      birthYear: 2000,
      hometown: "Los Angeles, CA",
      highSchool: "Sierra Canyon School, Chatsworth, CA",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1630199.png",
      bio: "Athletic freshman guard who averaged 12.6 PPG with electric dunking ability. Won the 2021 NBA Slam Dunk Contest.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        league: "Overseas / G-League",
        statusNote: "Selected #54 overall by Indiana in 2020. Won the 2021 NBA Slam Dunk Contest. Has bounced between the NBA and G-League, with stints in Indiana and Cleveland. Currently playing overseas.",
        sourceUrl: "https://en.wikipedia.org/wiki/Cassius_Stanley",
      },
      membership: { role: "PLAYER", jerseyNumber: 14, position: "Shooting Guard", yearsAtSchool: "2019-2020", statsNote: "12.6 PPG · Athletic freak · Won 2021 NBA Dunk Contest", gamesPlayed: 31, pointsPerGame: 12.6, reboundsPerGame: 4.9, assistsPerGame: 0.8 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Sierra Canyon School", season: "2018-19", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 14.8, reboundsPerGame: 5.0, assistsPerGame: 2.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2019-20", yearLabel: "2019-20", sortOrder: 201, gamesPlayed: 31, minutesPerGame: 27.5, pointsPerGame: 12.6, reboundsPerGame: 4.9, assistsPerGame: 0.8, stealsPerGame: 0.5, fieldGoalPct: 0.497, threePointPct: 0.363, freeThrowPct: 0.696 },
        { level: "PROFESSIONAL", teamName: "Indiana Pacers", season: "2020-21", yearLabel: "2020-21 (Rookie)", sortOrder: 301, gamesPlayed: 13, minutesPerGame: 5.0, pointsPerGame: 2.0, reboundsPerGame: 0.5, fieldGoalPct: 0.370 },
      ],
      careerEvents: [
        { year: 2020, title: "Selected #54 overall by Indiana Pacers", eventType: "DRAFT" },
        { year: 2021, title: "Won NBA Slam Dunk Contest", eventType: "AWARD" },
      ],
    },
    {
      slug: "matthew-hurt",
      firstName: "Matthew",
      lastName: "Hurt",
      birthYear: 2000,
      hometown: "Rochester, MN",
      highSchool: "John Marshall High School, Rochester, MN",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1630562.png",
      bio: "Freshman forward/center who showed flashes of his offensive repertoire with 9.7 PPG, including a 25-point game vs Georgia Tech. Returned for sophomore year.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        league: "G-League / Overseas",
        statusNote: "Returned for his sophomore year (2020-21) where he led Duke at 18.3 PPG and was named first-team All-ACC. Went undrafted in 2021 but has played in the G-League and overseas, including stints with Memphis's G-League affiliate.",
        sourceUrl: "https://en.wikipedia.org/wiki/Matthew_Hurt",
      },
      membership: { role: "PLAYER", jerseyNumber: 21, position: "Power Forward / Center", yearsAtSchool: "2019-2021", statsNote: "9.7 PPG as freshman · Returned for sophomore year (18.3 PPG)" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "John Marshall High School", season: "2018-19", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 30.0, reboundsPerGame: 10.5, assistsPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2019-20", yearLabel: "2019-20", sortOrder: 201, gamesPlayed: 31, minutesPerGame: 22.6, pointsPerGame: 9.7, reboundsPerGame: 3.8, fieldGoalPct: 0.456, threePointPct: 0.397, freeThrowPct: 0.857 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2020-21", yearLabel: "2020-21 (All-ACC)", sortOrder: 202, gamesPlayed: 24, minutesPerGame: 34.1, pointsPerGame: 18.3, reboundsPerGame: 6.2, assistsPerGame: 0.7, fieldGoalPct: 0.558, threePointPct: 0.441, freeThrowPct: 0.819 },
      ],
      careerEvents: [
        { year: 2021, title: "Named first-team All-ACC", eventType: "AWARD" },
      ],
    },
    {
      slug: "wendell-moore-jr",
      firstName: "Wendell",
      lastName: "Moore Jr.",
      birthYear: 2001,
      hometown: "Concord, NC",
      highSchool: "Cox Mill High School, Concord, NC",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1631111.png",
      bio: "Freshman wing who averaged 5.2 PPG in a supporting role. Would develop into a first-team All-ACC player and first-round pick by his junior year.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard / Forward",
        league: "NBA / G-League",
        statusNote: "Developed into a first-round pick by 2022 after three years at Duke. Selected #26 overall.",
        sourceUrl: "https://en.wikipedia.org/wiki/Wendell_Moore_Jr.",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Small Forward", yearsAtSchool: "2019-2022", statsNote: "5.2 PPG as freshman · Later became 1st-team All-ACC and #26 pick" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2019-20", yearLabel: "2019-20", sortOrder: 201, gamesPlayed: 29, minutesPerGame: 19.3, pointsPerGame: 5.2, reboundsPerGame: 3.2, assistsPerGame: 1.4, fieldGoalPct: 0.409, threePointPct: 0.287 },
      ],
      careerEvents: [],
    },
    {
      slug: "jordan-goldwire",
      firstName: "Jordan",
      lastName: "Goldwire",
      birthYear: 1999,
      hometown: "Norcross, GA",
      highSchool: "Norcross High School, Norcross, GA",
      bio: "Junior guard who became a defensive catalyst, ranking among Duke leaders in steals. Stepped into a larger role when Tre Jones was injured, showing toughness and playmaking ability.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        league: "G-League / Overseas",
        statusNote: "Returned for his senior year at Duke in 2020-21, then transferred to Oklahoma as a grad transfer. Went undrafted in 2022 and has bounced between the G-League and overseas leagues, including stints with the Texas Legends and the Lobos Plateados de la BUAP in Mexico.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jordan_Goldwire",
      },
      membership: { role: "PLAYER", jerseyNumber: 23, position: "Guard", yearsAtSchool: "2017-2021", statsNote: "4.7 PPG, 1.5 SPG · Key defensive guard · Stepped up when Jones injured" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Norcross High School", season: "2016-17", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 12.0, reboundsPerGame: 3.5, assistsPerGame: 4.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2019-20", yearLabel: "2019-20", sortOrder: 201, gamesPlayed: 31, minutesPerGame: 19.1, pointsPerGame: 4.7, reboundsPerGame: 2.5, assistsPerGame: 2.3, stealsPerGame: 1.5, fieldGoalPct: 0.487, threePointPct: 0.354 },
      ],
      careerEvents: [
        { year: 2021, title: "Transferred to Oklahoma as graduate transfer", eventType: "TRANSFER" },
      ],
    },
    {
      slug: "jack-white",
      firstName: "Jack",
      lastName: "White",
      birthYear: 1997,
      hometown: "Traralgon, Australia",
      highSchool: "The Southport School, Southport, QLD, Australia",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1631298.png",
      bio: "Australian senior forward and team captain who provided veteran leadership and defensive toughness. A four-year letterwinner who was part of two ACC Tournament championship teams.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        league: "Overseas",
        statusNote: "Returned home to Australia after graduating and played two seasons for Melbourne United in the NBL. Made the NBA with the Denver Nuggets in 2022-23, earning an NBA championship ring. Had a 10-day contract with the Memphis Grizzlies in 2023-24. Signed with Bayern Munich in Germany in April 2025.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jack_White_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 41, position: "Power Forward", yearsAtSchool: "2016-2020", statsNote: "3.1 PPG, 2.9 RPG · Team captain · 4-year letterwinner" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2019-20", yearLabel: "2019-20 (Captain)", sortOrder: 201, gamesPlayed: 30, minutesPerGame: 15.6, pointsPerGame: 3.1, reboundsPerGame: 2.9, assistsPerGame: 0.8, fieldGoalPct: 0.395, threePointPct: 0.324 },
        { level: "PROFESSIONAL", teamName: "Melbourne United", season: "2020-21", yearLabel: "2020-21 (NBL)", sortOrder: 301, gamesPlayed: 36, minutesPerGame: 18.0, pointsPerGame: 6.5, reboundsPerGame: 4.2 },
        { level: "PROFESSIONAL", teamName: "Denver Nuggets", season: "2022-23", yearLabel: "2022-23 (NBA Champ)", sortOrder: 303, gamesPlayed: 10, minutesPerGame: 4.5, pointsPerGame: 1.2, reboundsPerGame: 1.0 },
      ],
      careerEvents: [
        { year: 2020, title: "Signed with Melbourne United (NBL Australia)", eventType: "SIGNING" },
        { year: 2023, title: "Won NBA Championship with Denver Nuggets", eventType: "AWARD" },
        { year: 2025, title: "Signed with Bayern Munich (Germany)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "javin-delaurier",
      firstName: "Javin",
      lastName: "DeLaurier",
      birthYear: 1998,
      hometown: "Mechanicsville, VA",
      highSchool: "Atlee High School, Mechanicsville, VA",
      bio: "Senior forward and team captain who was a four-year letterwinner and beloved teammate. Set career highs across the board in his senior season with 3.8 PPG and an incredible 74.7% field goal percentage.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        league: "Overseas",
        statusNote: "Went undrafted in 2020 but carved out a professional career through sheer determination. Played in the G-League, Canadian CEBL with the Niagara River Lions, and overseas in Israel with Hapoel Holon. Became the first CEBL player to sign an NBA contract when he inked a 10-day deal with the Milwaukee Bucks. Signed with Bursaspor in Turkey in 2025.",
        sourceUrl: "https://en.wikipedia.org/wiki/Javin_DeLaurier",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Power Forward / Center", yearsAtSchool: "2016-2020", statsNote: "3.8 PPG, 4.4 RPG · Team captain · 74.7% FG · 50 blocks" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2019-20", yearLabel: "2019-20 (Captain)", sortOrder: 201, gamesPlayed: 31, minutesPerGame: 16.3, pointsPerGame: 3.8, reboundsPerGame: 4.4, assistsPerGame: 0.7, blocksPerGame: 1.6, fieldGoalPct: 0.747 },
      ],
      careerEvents: [
        { year: 2021, title: "Signed 10-day contract with Milwaukee Bucks (first CEBL-to-NBA player)", eventType: "SIGNING" },
        { year: 2025, title: "Signed with Bursaspor Basketbol (Turkey)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "joey-baker",
      firstName: "Joey",
      lastName: "Baker",
      birthYear: 2000,
      hometown: "Fayetteville, NC",
      highSchool: "Trinity Christian School, Fayetteville, NC",
      bio: "Sophomore sharpshooter who provided a dangerous three-point threat off the bench, shooting 40.5% from beyond the arc. Had a breakout 22-point game against Wofford.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard / Forward",
        league: "Overseas",
        statusNote: "Stayed at Duke through 2021-22 as part of Coach K's final team, then transferred to Michigan for his final season. After going undrafted in 2023, he signed with Pieno Zvaigzdes Pasvalys in the Lithuanian Basketball League. Currently playing for the Joondalup Wolves in Australia's NBL1 West.",
        sourceUrl: "https://en.wikipedia.org/wiki/Joey_Baker",
      },
      membership: { role: "PLAYER", jerseyNumber: 13, position: "Small Forward", yearsAtSchool: "2018-2022", statsNote: "4.5 PPG · 40.5% from three · Breakout 22-point game vs Wofford" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Trinity Christian School", season: "2017-18", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 18.0, reboundsPerGame: 6.0, assistsPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2019-20", yearLabel: "2019-20", sortOrder: 201, gamesPlayed: 34, minutesPerGame: 14.2, pointsPerGame: 4.5, reboundsPerGame: 1.4, assistsPerGame: 0.5, fieldGoalPct: 0.432, threePointPct: 0.405 },
      ],
      careerEvents: [
        { year: 2022, title: "Transferred to Michigan as graduate transfer", eventType: "TRANSFER" },
      ],
    },
    {
      slug: "alex-oconnell",
      firstName: "Alex",
      lastName: "O'Connell",
      birthYear: 1999,
      hometown: "Roswell, GA",
      highSchool: "Blessed Trinity Catholic High School, Roswell, GA",
      bio: "Junior guard who provided scoring off the bench, averaging 5.2 PPG. A versatile wing who could shoot from distance and attack the basket.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        league: "Overseas",
        statusNote: "Transferred to Creighton after three seasons at Duke and had a strong senior year. Pursued a professional career in the G-League with the Westchester Knicks (New York affiliate). Signed with ALBA Berlin in the German Bundesliga in November 2025.",
        sourceUrl: "https://en.wikipedia.org/wiki/Alex_O%27Connell_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Shooting Guard", yearsAtSchool: "2017-2020", statsNote: "5.2 PPG, 2.2 RPG · Versatile bench scorer" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2019-20", yearLabel: "2019-20", sortOrder: 201, gamesPlayed: 29, minutesPerGame: 16.8, pointsPerGame: 5.2, reboundsPerGame: 2.2, assistsPerGame: 1.0, fieldGoalPct: 0.400, threePointPct: 0.270 },
      ],
      careerEvents: [
        { year: 2020, title: "Transferred to Creighton", eventType: "TRANSFER" },
        { year: 2025, title: "Signed with ALBA Berlin (Germany)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "justin-robinson",
      firstName: "Justin",
      lastName: "Robinson",
      birthYear: 1996,
      hometown: "San Antonio, TX",
      highSchool: "San Antonio Christian School, San Antonio, TX",
      bio: "Graduate transfer forward and son of NBA Hall of Famer David Robinson. A team captain who brought veteran leadership and energy, capping his career with a 13-point, 6-rebound, 4-block Senior Night performance against UNC.",
      status: {
        occupationType: "COACH",
        currentTitle: "Director of Player Development",
        currentEmployer: "Duke University",
        location: "Durham, NC",
        statusNote: "After graduating from Duke with a Master of Management Studies from the Fuqua School of Business, Robinson returned to Duke's coaching staff in November 2023 as Director of Player Development. The son of NBA legend David Robinson, he has found his calling in coaching and mentoring young players.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/coaches/justin-robinson/5016",
      },
      membership: { role: "PLAYER", jerseyNumber: 50, position: "Power Forward", yearsAtSchool: "2016-2020", statsNote: "2.8 PPG, 1.5 RPG · Team captain · Son of David Robinson · Fuqua MBA" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2019-20", yearLabel: "2019-20 (Captain)", sortOrder: 201, gamesPlayed: 28, minutesPerGame: 6.8, pointsPerGame: 2.8, reboundsPerGame: 1.5, assistsPerGame: 0.4, blocksPerGame: 1.1, fieldGoalPct: 0.500 },
      ],
      careerEvents: [
        { year: 2020, title: "Earned Master of Management Studies from Duke Fuqua School of Business", eventType: "EDUCATION" },
        { year: 2023, title: "Joined Duke coaching staff as Director of Player Development", eventType: "CAREER" },
      ],
    },
    {
      slug: "mike-buckmire",
      firstName: "Mike",
      lastName: "Buckmire",
      birthYear: 1998,
      hometown: "Blue Bell, PA",
      highSchool: "Germantown Friends School, Philadelphia, PA",
      bio: "Walk-on guard who earned a scholarship from Coach K in 2019 after two years of dedication in practice. A Duke legacy whose father was on the 1986 NCAA Championship soccer team.",
      status: {
        occupationType: "OTHER",
        statusNote: "Buckmire was a walk-on who earned a scholarship at Duke, graduating with his class. A Duke legacy — his father Michael was a member of Duke's 1986 NCAA championship men's soccer team. After graduating, he pursued a career outside of basketball.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/mike-buckmire/16336",
      },
      membership: { role: "PLAYER", jerseyNumber: 51, position: "Guard", yearsAtSchool: "2017-2021", statsNote: "Walk-on who earned scholarship · Duke legacy · Limited game action" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2019-20", yearLabel: "2019-20", sortOrder: 201, gamesPlayed: 8, minutesPerGame: 2.5, pointsPerGame: 0.4, reboundsPerGame: 0.7, fieldGoalPct: 0.250 },
      ],
      careerEvents: [
        { year: 2019, title: "Earned scholarship from Coach K after two years as walk-on", eventType: "AWARD" },
      ],
    },
    {
      slug: "mike-krzyzewski",
      firstName: "Mike",
      lastName: "Krzyzewski",
      birthYear: 1947,
      hometown: "Chicago, IL",
      highSchool: "Weber High School, Chicago, IL",
      bio: "The 2019-20 team was on track for a #1 seed before the NCAA Tournament was cancelled due to the COVID-19 pandemic. One of the great 'what if' seasons in Duke history.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Retired Head Coach",
        currentEmployer: "Duke University (Emeritus)",
        location: "Durham, NC",
        statusNote: "Retired after 2021-22 with 1,202 career wins.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Krzyzewski",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "1980-2022", statsNote: "25-6 · Season cancelled by COVID-19 · Projected #1 seed" },
      seasonStats: [
        { level: "COACHING", teamName: "Duke Blue Devils", season: "2019-20", yearLabel: "2019-20", sortOrder: 1, wins: 25, losses: 6, tournamentResult: "NCAA Tournament cancelled (COVID-19)" },
      ],
      careerEvents: [],
    },
    {
      slug: "jeff-capel",
      firstName: "Jeff",
      lastName: "Capel",
      birthYear: 1975,
      hometown: "Fayetteville, NC",
      highSchool: "South View High School, Hope Mills, NC",
      bio: "Associate head coach at Duke who was one of the top assistants and recruiters in college basketball.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "University of Pittsburgh",
        location: "Pittsburgh, PA",
        statusNote: "Left Duke in 2018 to become head coach at Pitt. Has rebuilt the Panthers program.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jeff_Capel",
      },
      membership: { role: "ASSISTANT_COACH", position: "Associate Head Coach", yearsAtSchool: "2011-2018", statsNote: "Top recruiter · Landed Zion, RJ, Cam class" },
      careerEvents: [
        { year: 2018, title: "Named head coach at University of Pittsburgh", eventType: "COACHING" },
      ],
    },
    {
      slug: "nate-james",
      firstName: "Nate",
      lastName: "James",
      birthYear: 1979,
      hometown: "Seattle, WA",
      highSchool: "Lower Merion High School, Ardmore, PA",
      bio: "Former Duke player (1997-2001) and assistant coach. Key recruiter and mentor to players.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "Austin Peay State University",
        location: "Clarksville, TN",
        statusNote: "Left Duke in 2021 to become head coach at Austin Peay. 2001 NCAA champion as a player.",
        sourceUrl: "https://en.wikipedia.org/wiki/Nate_James",
      },
      membership: { role: "ASSISTANT_COACH", position: "Assistant Coach", yearsAtSchool: "2007-2021", statsNote: "Former Duke player · Key recruiter" },
      careerEvents: [
        { year: 2021, title: "Named head coach at Austin Peay State University", eventType: "COACHING" },
      ],
    },
    {
      slug: "jon-scheyer",
      firstName: "Jon",
      lastName: "Scheyer",
      birthYear: 1987,
      hometown: "Northbrook, IL",
      highSchool: "Glenbrook North High School, Northbrook, IL",
      bio: "Former Duke player (2006-10) and 2010 national champion who served as associate head coach and head-coach-in-waiting.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "Duke University",
        league: "ACC",
        location: "Durham, NC",
        statusNote: "Succeeded Coach K in 2022. Has led Duke to three NCAA Tournaments in three seasons, including a Final Four in 2025.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jon_Scheyer",
      },
      membership: { role: "ASSISTANT_COACH", position: "Associate Head Coach / Coach-in-Waiting", yearsAtSchool: "2013-2022", statsNote: "2010 champion as player · Named successor to Coach K" },
      careerEvents: [
        { year: 2022, title: "Named head coach at Duke, succeeding Coach K", eventType: "COACHING" },
      ],
    },
  ],
};
