import type { TeamSeed } from "./types";

export const dukeBasketball2018: TeamSeed = {
  slug: "duke-basketball-2018",
  name: "Duke Blue Devils",
  season: "2017-2018",
  sport: "Basketball",
  school: "Duke University",
  conference: "ACC",
  accomplishment: "29-8, Elite Eight",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  mascotName: "Blue Devil",
  people: [
    {
      slug: "marvin-bagley-iii",
      firstName: "Marvin",
      lastName: "Bagley III",
      birthYear: 2000,
      hometown: "Phoenix, AZ",
      highSchool: "Sierra Canyon School, Chatsworth, CA",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628963.png",
      bio: "The consensus #1 recruit who reclassified to join Duke a year early. Averaged 21.0 PPG and 11.1 RPG — recording 22 double-doubles, the most by a Duke freshman ever. Named ACC Player of the Year and Rookie of the Year.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Power Forward / Center",
        league: "NBA / Overseas",
        statusNote: "Selected #2 overall by Sacramento in 2018. Injuries and inconsistency have plagued his NBA career. Played for Sacramento, Detroit, and Washington over six seasons, averaging around 10 PPG. His athleticism and touch remain elite but he has struggled to find a permanent home. Currently seeking a roster spot.",
        sourceUrl: "https://en.wikipedia.org/wiki/Marvin_Bagley_III",
      },
      membership: { role: "PLAYER", jerseyNumber: 35, position: "Power Forward", yearsAtSchool: "2017-2018", statsNote: "21.0 PPG, 11.1 RPG · ACC POY · ACC ROY · #2 pick · 22 double-doubles", gamesPlayed: 33, pointsPerGame: 21.0, reboundsPerGame: 11.1, assistsPerGame: 0.8 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Sierra Canyon School", season: "2016-17", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 32.5, reboundsPerGame: 14.8, blocksPerGame: 2.8 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2017-18", yearLabel: "2017-18 (ACC POY)", sortOrder: 201, gamesPlayed: 33, minutesPerGame: 32.9, pointsPerGame: 21.0, reboundsPerGame: 11.1, assistsPerGame: 0.8, blocksPerGame: 0.8, fieldGoalPct: 0.614, freeThrowPct: 0.628 },
        { level: "PROFESSIONAL", teamName: "Sacramento Kings", season: "2018-19", yearLabel: "2018-19 (Rookie)", sortOrder: 301, gamesPlayed: 62, minutesPerGame: 25.3, pointsPerGame: 14.9, reboundsPerGame: 7.6, blocksPerGame: 1.0, fieldGoalPct: 0.502, freeThrowPct: 0.692 },
        { level: "PROFESSIONAL", teamName: "Sacramento Kings", season: "2020-21", yearLabel: "2020-21", sortOrder: 303, gamesPlayed: 43, minutesPerGame: 24.3, pointsPerGame: 14.1, reboundsPerGame: 7.4, fieldGoalPct: 0.504, freeThrowPct: 0.716 },
        { level: "PROFESSIONAL", teamName: "Detroit Pistons", season: "2021-22", yearLabel: "2021-22", sortOrder: 304, gamesPlayed: 58, minutesPerGame: 23.3, pointsPerGame: 11.1, reboundsPerGame: 6.4, fieldGoalPct: 0.497, freeThrowPct: 0.660 },
        { level: "PROFESSIONAL", teamName: "Washington Wizards", season: "2023-24", yearLabel: "2023-24", sortOrder: 306, gamesPlayed: 42, minutesPerGame: 18.0, pointsPerGame: 8.0, reboundsPerGame: 5.5, fieldGoalPct: 0.480, freeThrowPct: 0.650 },
      ],
      careerEvents: [
        { year: 2018, title: "Selected #2 overall by Sacramento Kings", eventType: "DRAFT" },
        { year: 2022, title: "Traded to Detroit Pistons", eventType: "TRADE" },
      ],
    },
    {
      slug: "wendell-carter-jr",
      firstName: "Wendell",
      lastName: "Carter Jr.",
      birthYear: 2000,
      hometown: "Atlanta, GA",
      highSchool: "Pace Academy, Atlanta, GA",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628976.png",
      bio: "Five-star freshman center who was the team's defensive anchor. Averaged 13.5 PPG, 9.1 RPG, and 2.0 BPG, earning All-ACC Freshman Team honors.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "Orlando Magic",
        league: "NBA",
        location: "Orlando, FL",
        statusNote: "Selected #7 overall by the Chicago Bulls in 2018. Traded to Orlando in 2021 and has become the Magic's starting center, averaging a career-best 12.8 PPG in 2022-23. Signed a 4-year, $50 million extension with Orlando in 2023. A dependable two-way center entering his 8th NBA season.",
        sourceUrl: "https://en.wikipedia.org/wiki/Wendell_Carter_Jr.",
      },
      membership: { role: "PLAYER", jerseyNumber: 34, position: "Center", yearsAtSchool: "2017-2018", statsNote: "13.5 PPG, 9.1 RPG, 2.0 BPG · All-ACC Freshman · #7 pick", gamesPlayed: 37, pointsPerGame: 13.5, reboundsPerGame: 9.1, assistsPerGame: 2.0 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Pace Academy", season: "2016-17", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 22.0, reboundsPerGame: 12.5, blocksPerGame: 3.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2017-18", yearLabel: "2017-18", sortOrder: 201, gamesPlayed: 37, minutesPerGame: 28.5, pointsPerGame: 13.5, reboundsPerGame: 9.1, assistsPerGame: 2.0, blocksPerGame: 2.0, fieldGoalPct: 0.560, freeThrowPct: 0.743 },
        { level: "PROFESSIONAL", teamName: "Chicago Bulls", season: "2018-19", yearLabel: "2018-19 (Rookie)", sortOrder: 301, gamesPlayed: 44, minutesPerGame: 25.6, pointsPerGame: 10.3, reboundsPerGame: 7.0, blocksPerGame: 1.3, fieldGoalPct: 0.483, freeThrowPct: 0.748 },
        { level: "PROFESSIONAL", teamName: "CHI / Orlando Magic", season: "2020-21", yearLabel: "2020-21", sortOrder: 303, gamesPlayed: 56, minutesPerGame: 28.0, pointsPerGame: 12.0, reboundsPerGame: 8.0, blocksPerGame: 1.0, fieldGoalPct: 0.505, freeThrowPct: 0.730 },
        { level: "PROFESSIONAL", teamName: "Orlando Magic", season: "2022-23", yearLabel: "2022-23", sortOrder: 305, gamesPlayed: 56, minutesPerGame: 29.5, pointsPerGame: 12.8, reboundsPerGame: 7.1, assistsPerGame: 2.4, blocksPerGame: 0.9, fieldGoalPct: 0.522, threePointPct: 0.326, freeThrowPct: 0.755 },
        { level: "PROFESSIONAL", teamName: "Orlando Magic", season: "2024-25", yearLabel: "2024-25", sortOrder: 307, gamesPlayed: 58, minutesPerGame: 27.0, pointsPerGame: 10.5, reboundsPerGame: 6.8, assistsPerGame: 2.0, fieldGoalPct: 0.510, freeThrowPct: 0.740 },
      ],
      careerEvents: [
        { year: 2018, title: "Selected #7 overall by Chicago Bulls", eventType: "DRAFT" },
        { year: 2021, title: "Traded to Orlando Magic", eventType: "TRADE" },
        { year: 2023, title: "Signed 4-year, $50M extension with Magic", eventType: "CONTRACT" },
      ],
    },
    {
      slug: "gary-trent-jr",
      firstName: "Gary",
      lastName: "Trent Jr.",
      birthYear: 1999,
      hometown: "Columbus, OH",
      highSchool: "Prolific Prep, Napa, CA",
      isFeatured: false,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1629018.png",
      bio: "Freshman guard who shot 40.2% from three and was Duke's most reliable perimeter shooter. Son of former NBA player Gary Trent Sr.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Shooting Guard",
        currentEmployer: "Milwaukee Bucks",
        league: "NBA",
        location: "Milwaukee, WI",
        statusNote: "Selected #37 by Sacramento (traded to Portland) in 2018. Had breakout seasons in Portland (15.3 PPG) and Toronto (18.3 PPG in 2022-23). Signed with Milwaukee in 2024. Known as one of the NBA's best perimeter defenders and a streaky shooter. Career-best 18.3 PPG with the Raptors.",
        sourceUrl: "https://en.wikipedia.org/wiki/Gary_Trent_Jr.",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Shooting Guard", yearsAtSchool: "2017-2018", statsNote: "14.5 PPG · 40.2% from three · #37 pick", gamesPlayed: 37, pointsPerGame: 14.5, reboundsPerGame: 4.2, assistsPerGame: 1.4 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Prolific Prep", season: "2016-17", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 24.0, reboundsPerGame: 5.0, assistsPerGame: 3.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2017-18", yearLabel: "2017-18", sortOrder: 201, gamesPlayed: 37, minutesPerGame: 29.6, pointsPerGame: 14.5, reboundsPerGame: 4.2, assistsPerGame: 1.4, stealsPerGame: 1.0, fieldGoalPct: 0.438, threePointPct: 0.402, freeThrowPct: 0.817 },
        { level: "PROFESSIONAL", teamName: "Portland Trail Blazers", season: "2019-20", yearLabel: "2019-20", sortOrder: 302, gamesPlayed: 61, minutesPerGame: 16.8, pointsPerGame: 8.9, reboundsPerGame: 1.7, stealsPerGame: 0.6, fieldGoalPct: 0.399, threePointPct: 0.382, freeThrowPct: 0.778 },
        { level: "PROFESSIONAL", teamName: "Portland Trail Blazers", season: "2020-21", yearLabel: "2020-21", sortOrder: 303, gamesPlayed: 57, minutesPerGame: 33.1, pointsPerGame: 15.3, reboundsPerGame: 2.4, stealsPerGame: 1.0, fieldGoalPct: 0.425, threePointPct: 0.387, freeThrowPct: 0.773 },
        { level: "PROFESSIONAL", teamName: "Toronto Raptors", season: "2021-22", yearLabel: "2021-22", sortOrder: 304, gamesPlayed: 70, minutesPerGame: 36.3, pointsPerGame: 16.5, reboundsPerGame: 2.8, stealsPerGame: 1.7, fieldGoalPct: 0.414, threePointPct: 0.385, freeThrowPct: 0.848 },
        { level: "PROFESSIONAL", teamName: "Toronto Raptors", season: "2022-23", yearLabel: "2022-23", sortOrder: 305, gamesPlayed: 75, minutesPerGame: 35.0, pointsPerGame: 18.3, reboundsPerGame: 2.6, stealsPerGame: 1.2, fieldGoalPct: 0.435, threePointPct: 0.368, freeThrowPct: 0.867 },
        { level: "PROFESSIONAL", teamName: "Milwaukee Bucks", season: "2024-25", yearLabel: "2024-25", sortOrder: 307, gamesPlayed: 62, minutesPerGame: 28.0, pointsPerGame: 13.5, reboundsPerGame: 2.5, stealsPerGame: 1.0, fieldGoalPct: 0.420, threePointPct: 0.370, freeThrowPct: 0.850 },
      ],
      careerEvents: [
        { year: 2018, title: "Selected #37 by Sacramento (traded to Portland)", eventType: "DRAFT" },
        { year: 2021, title: "Traded to Toronto Raptors for Norman Powell", eventType: "TRADE" },
        { year: 2024, title: "Signed with Milwaukee Bucks", eventType: "SIGNING" },
      ],
    },
    {
      slug: "grayson-allen",
      firstName: "Grayson",
      lastName: "Allen",
      birthYear: 1995,
      hometown: "Jacksonville, FL",
      highSchool: "Providence School, Jacksonville, FL",
      isFeatured: false,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628425.png",
      bio: "Senior captain who led the team in experience. Averaged 15.5 PPG and was the emotional leader of the 2017-18 squad that reached the Elite Eight.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Shooting Guard",
        currentEmployer: "Phoenix Suns",
        league: "NBA",
        location: "Phoenix, AZ",
        statusNote: "Selected #21 overall by Utah in 2018. Won NBA Championship with Milwaukee in 2021 (45.3% from three in Finals). Has played for Jazz, Grizzlies, Bucks, and Suns. A reliable shooter and tough competitor at the NBA level.",
        sourceUrl: "https://en.wikipedia.org/wiki/Grayson_Allen",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Shooting Guard", yearsAtSchool: "2014-2018", statsNote: "15.5 PPG · Senior captain · 2015 champion · #21 pick" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2017-18", yearLabel: "2017-18 (Senior)", sortOrder: 204, gamesPlayed: 37, minutesPerGame: 33.8, pointsPerGame: 15.5, reboundsPerGame: 4.6, assistsPerGame: 3.3, stealsPerGame: 1.2, fieldGoalPct: 0.451, threePointPct: 0.378, freeThrowPct: 0.864 },
        { level: "PROFESSIONAL", teamName: "Utah Jazz", season: "2018-19", yearLabel: "2018-19 (Rookie)", sortOrder: 301, gamesPlayed: 38, minutesPerGame: 9.6, pointsPerGame: 3.3, reboundsPerGame: 0.8, fieldGoalPct: 0.380, threePointPct: 0.308, freeThrowPct: 0.833 },
        { level: "PROFESSIONAL", teamName: "Memphis Grizzlies", season: "2020-21", yearLabel: "2020-21", sortOrder: 303, gamesPlayed: 50, minutesPerGame: 18.0, pointsPerGame: 10.6, reboundsPerGame: 2.2, assistsPerGame: 2.2, fieldGoalPct: 0.448, threePointPct: 0.385, freeThrowPct: 0.872 },
        { level: "PROFESSIONAL", teamName: "Milwaukee Bucks", season: "2021-22", yearLabel: "2021-22 (Champion)", sortOrder: 304, gamesPlayed: 66, minutesPerGame: 25.3, pointsPerGame: 11.1, reboundsPerGame: 3.4, assistsPerGame: 2.2, fieldGoalPct: 0.447, threePointPct: 0.409, freeThrowPct: 0.878 },
        { level: "PROFESSIONAL", teamName: "Phoenix Suns", season: "2023-24", yearLabel: "2023-24", sortOrder: 306, gamesPlayed: 56, minutesPerGame: 22.0, pointsPerGame: 8.5, reboundsPerGame: 2.8, assistsPerGame: 2.5, fieldGoalPct: 0.430, threePointPct: 0.395, freeThrowPct: 0.860 },
      ],
      careerEvents: [
        { year: 2018, title: "Selected #21 overall by Utah Jazz", eventType: "DRAFT" },
        { year: 2022, title: "Won NBA Championship with Milwaukee Bucks", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "trevon-duval",
      firstName: "Trevon",
      lastName: "Duval",
      birthYear: 1999,
      hometown: "New Castle, DE",
      highSchool: "IMG Academy, Bradenton, FL",
      bio: "The #1 point guard recruit in the 2017 class who ran Duke's offense. His passing and speed were elite, but his outside shooting was inconsistent. Averaged 10.3 PPG and 5.6 APG.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Point Guard",
        league: "Overseas / G-League",
        statusNote: "Went undrafted in 2018 despite being the top PG recruit. Has bounced between the G-League and overseas leagues, playing in Japan, Puerto Rico, and various G-League teams. His inability to shoot from the outside limited his NBA prospects despite elite athleticism.",
        sourceUrl: "https://en.wikipedia.org/wiki/Trevon_Duval",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Point Guard", yearsAtSchool: "2017-2018", statsNote: "10.3 PPG, 5.6 APG · #1 PG recruit · Elite passer" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "IMG Academy", season: "2016-17", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 18.4, reboundsPerGame: 4.2, assistsPerGame: 8.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2017-18", yearLabel: "2017-18", sortOrder: 201, gamesPlayed: 37, minutesPerGame: 28.4, pointsPerGame: 10.3, reboundsPerGame: 3.1, assistsPerGame: 5.6, stealsPerGame: 1.4, fieldGoalPct: 0.467, threePointPct: 0.292, freeThrowPct: 0.658 },
      ],
      careerEvents: [
        { year: 2018, title: "Went undrafted; signed with G-League", eventType: "SIGNING" },
      ],
    },
    {
      slug: "marques-bolden",
      firstName: "Marques",
      lastName: "Bolden",
      birthYear: 1998,
      hometown: "DeSoto, TX",
      highSchool: "DeSoto High School, DeSoto, TX",
      bio: "Sophomore center who battled knee issues but played a role as the backup big. Improved defensively and was a solid rim protector when healthy.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "Texas",
        statusNote: "Returned for his junior year in 2018-19 where he had his best season. Went undrafted in 2019. Knee injuries continued to hamper his professional prospects.",
        sourceUrl: "https://en.wikipedia.org/wiki/Marques_Bolden",
      },
      membership: { role: "PLAYER", jerseyNumber: 20, position: "Center", yearsAtSchool: "2016-2019", statsNote: "2.7 PPG, 2.2 RPG · Battled knee injuries" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2017-18", yearLabel: "2017-18", sortOrder: 202, gamesPlayed: 26, minutesPerGame: 10.8, pointsPerGame: 2.7, reboundsPerGame: 2.2, blocksPerGame: 0.7, fieldGoalPct: 0.654 },
      ],
      careerEvents: [],
    },
    {
      slug: "mike-krzyzewski",
      firstName: "Mike",
      lastName: "Krzyzewski",
      birthYear: 1947,
      hometown: "Chicago, IL",
      highSchool: "Weber High School, Chicago, IL",
      bio: "Legendary head coach in his 38th season at Duke. Led the 2017-18 team to the Elite Eight with one of the most talented freshman classes in recent memory.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Retired Head Coach",
        currentEmployer: "Duke University (Emeritus)",
        location: "Durham, NC",
        statusNote: "Retired after 2021-22 with 1,202 career wins. Five-time national champion.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Krzyzewski",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "1980-2022", statsNote: "29-8 · Elite Eight (lost to Kansas)" },
      seasonStats: [
        { level: "COACHING", teamName: "Duke Blue Devils", season: "2017-18", yearLabel: "2017-18", sortOrder: 1, wins: 29, losses: 8, tournamentResult: "Elite Eight (lost to Kansas)" },
      ],
      careerEvents: [],
    },
  ],
};
