import type { TeamSeed } from "./types";

export const dukeBasketball2001: TeamSeed = {
  slug: "duke-basketball-2001",
  name: "Duke Blue Devils",
  season: "2000-2001",
  sport: "Men's Basketball",
  school: "Duke University",
  conference: "ACC",
  accomplishment: "NCAA National Champions",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  mascotName: "Blue Devil",
  people: [
    {
      slug: "shane-battier",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/2429.png",
      firstName: "Shane",
      lastName: "Battier",
      birthYear: 1978,
      hometown: "Birmingham, MI",
      highSchool: "Detroit Country Day School, Beverly Hills, MI",
      isFeatured: true,
      bio: "The 2001 Naismith and Wooden Award winner who led Duke to the national championship as a senior captain. Battier was the consummate team player and one of the greatest defenders in college basketball history.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Operating Partner / Minority Owner",
        currentEmployer: "Garnett Station Partners / Tampa Bay Rays",
        location: "Miami, FL",
        statusNote:
          "After a 13-year NBA career with the Grizzlies, Rockets, and Heat — winning two championships with Miami in 2012 and 2013 — Battier served as VP of Analytics for the Heat. He transitioned to business as an operating partner at Garnett Station Partners and became a minority owner of the Tampa Bay Rays in 2025. He serves on numerous corporate boards and runs the Battier Take Charge Foundation. His jersey #31 was retired at Duke.",
        sourceUrl: "https://en.wikipedia.org/wiki/Shane_Battier",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 31,
        position: "Small Forward",
        yearsAtSchool: "1997-2001",
        statsNote: "2001 Naismith & Wooden Award • NABC Defensive POY • National Champion",
        gamesPlayed: 36,
        pointsPerGame: 19.9,
        reboundsPerGame: 7.3,
        assistsPerGame: 2.2,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2000-2001", yearLabel: "Unknown", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 19.9, reboundsPerGame: 7.3, assistsPerGame: 2.2 },
      ],
      careerEvents: [
        { year: 2001, title: "Won NCAA National Championship with Duke", eventType: "CHAMPIONSHIP" },
        { year: 2001, title: "Selected #6 overall by the Memphis Grizzlies", eventType: "DRAFT" },
        { year: 2012, title: "Won NBA Championship with Miami Heat", eventType: "CHAMPIONSHIP" },
        { year: 2013, title: "Won second NBA Championship with Miami Heat", eventType: "CHAMPIONSHIP" },
        { year: 2014, title: "Retired from NBA; joined Heat front office as VP of Analytics", eventType: "CAREER" },
        { year: 2025, title: "Became minority owner of the Tampa Bay Rays", eventType: "CAREER" },
      ],
    },
    {
      slug: "jay-williams",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/998.png",
      firstName: "Jay",
      lastName: "Williams",
      birthYear: 1981,
      hometown: "Plainfield, NJ",
      highSchool: "St. Joseph High School, Metuchen, NJ",
      isFeatured: true,
      bio: "One of the most talented guards in Duke history, Williams won the 2002 Naismith and Wooden Awards and was the #2 pick in the NBA Draft. A motorcycle accident tragically cut short his NBA career after just one season.",
      status: {
        occupationType: "BROADCASTER_ANALYST",
        currentTitle: "NBA Analyst / Radio Host",
        currentEmployer: "ESPN",
        location: "New York, NY",
        statusNote:
          "Selected #2 overall by the Chicago Bulls in 2002, Williams' NBA career was devastated by a motorcycle accident in June 2003 that required 13 surgeries. He rebuilt his life as a broadcaster, joining ESPN in 2008. He currently co-hosts 'Keyshawn, JWill and Max' on ESPN Radio and serves as an NBA analyst. He published the memoir 'Life Is Not an Accident' in 2016.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jay_Williams_(basketball)",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 22,
        position: "Point Guard",
        yearsAtSchool: "1999-2002",
        statsNote: "2001 National Champion • 2002 Naismith & Wooden Award winner",
        gamesPlayed: 36,
        pointsPerGame: 21.6,
        reboundsPerGame: 3.7,
        assistsPerGame: 5.9,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2000-2001", yearLabel: "Unknown", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 21.6, reboundsPerGame: 3.7, assistsPerGame: 5.9 },
      ],
      careerEvents: [
        { year: 2001, title: "Won NCAA National Championship with Duke", eventType: "CHAMPIONSHIP" },
        { year: 2002, title: "Selected #2 overall by the Chicago Bulls", eventType: "DRAFT" },
        { year: 2003, title: "Career-ending motorcycle accident", eventType: "INJURY" },
        { year: 2008, title: "Joined ESPN as college basketball analyst", eventType: "CAREER" },
        { year: 2016, title: "Published memoir 'Life Is Not an Accident'", eventType: "CAREER" },
      ],
    },
    {
      slug: "carlos-boozer",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/2744.png",
      firstName: "Carlos",
      lastName: "Boozer",
      birthYear: 1981,
      hometown: "Juneau, AK",
      highSchool: "Juneau-Douglas High School, Juneau, AK",
      isFeatured: true,
      bio: "A powerful freshman forward on the 2001 championship team who left after his sophomore year to become a two-time NBA All-Star. His twin sons Cameron and Cayden currently play at Duke.",
      status: {
        occupationType: "FRONT_OFFICE",
        currentTitle: "Front Office Associate",
        currentEmployer: "Utah Jazz",
        location: "Salt Lake City, UT",
        statusNote:
          "Selected #35 overall in 2002, Boozer became a two-time All-Star and won Olympic gold with the 2008 'Redeem Team.' He played 13 NBA seasons with Cleveland, Utah, Chicago, and the Lakers before retiring in 2015. In 2025 he was inducted into the Naismith Hall of Fame as part of the Redeem Team and joined the Utah Jazz front office. His twin sons now play at Duke, continuing the family legacy.",
        sourceUrl: "https://en.wikipedia.org/wiki/Carlos_Boozer",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 4,
        position: "Power Forward",
        yearsAtSchool: "2000-2002",
        statsNote: "2001 National Champion • Left after sophomore year for NBA",
        gamesPlayed: 36,
        pointsPerGame: 8.8,
        reboundsPerGame: 5.9,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2000-2001", yearLabel: "Unknown", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 8.8, reboundsPerGame: 5.9 },
      ],
      careerEvents: [
        { year: 2001, title: "Won NCAA National Championship with Duke", eventType: "CHAMPIONSHIP" },
        { year: 2002, title: "Selected #35 overall by the Cleveland Cavaliers", eventType: "DRAFT" },
        { year: 2008, title: "Won Olympic gold with Team USA ('Redeem Team')", eventType: "AWARD" },
        { year: 2015, title: "Retired from NBA after 13 seasons", eventType: "RETIREMENT" },
        { year: 2025, title: "Inducted into Naismith Hall of Fame; joined Utah Jazz front office", eventType: "AWARD" },
      ],
    },
    {
      slug: "mike-dunleavy-jr",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1011.png",
      firstName: "Mike",
      lastName: "Dunleavy Jr.",
      birthYear: 1980,
      hometown: "Lake Oswego, OR",
      highSchool: "Jesuit High School, Beaverton, OR",
      isFeatured: true,
      bio: "A versatile sophomore wing on the 2001 championship team who became the #3 overall pick in 2002. Son of NBA coach Mike Dunleavy Sr.",
      status: {
        occupationType: "FRONT_OFFICE",
        currentTitle: "General Manager",
        currentEmployer: "Golden State Warriors",
        location: "San Francisco, CA",
        statusNote:
          "Selected #3 overall by the Warriors in 2002, Dunleavy played 15 NBA seasons with six teams, winning a championship with Cleveland in 2016. After retiring in 2017, he joined the Warriors front office as assistant GM in 2020 and was promoted to General Manager in June 2023 following Bob Myers' departure.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Dunleavy_Jr.",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 34,
        position: "Small Forward / Shooting Guard",
        yearsAtSchool: "1999-2002",
        statsNote: "2001 National Champion • Left after junior year as #3 pick",
        gamesPlayed: 36,
        pointsPerGame: 10.2,
        reboundsPerGame: 4.5,
        assistsPerGame: 2.5,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2000-2001", yearLabel: "Unknown", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 10.2, reboundsPerGame: 4.5, assistsPerGame: 2.5 },
      ],
      careerEvents: [
        { year: 2001, title: "Won NCAA National Championship with Duke", eventType: "CHAMPIONSHIP" },
        { year: 2002, title: "Selected #3 overall by the Golden State Warriors", eventType: "DRAFT" },
        { year: 2016, title: "Won NBA Championship with Cleveland Cavaliers", eventType: "CHAMPIONSHIP" },
        { year: 2017, title: "Retired from NBA after 15 seasons", eventType: "RETIREMENT" },
        { year: 2023, title: "Named General Manager of the Golden State Warriors", eventType: "CAREER" },
      ],
    },
    {
      slug: "chris-duhon",
      firstName: "Chris",
      lastName: "Duhon",
      birthYear: 1982,
      hometown: "Slidell, LA",
      highSchool: "Salmen High School, Slidell, LA",
      isFeatured: false,
      bio: "A McDonald's All-American point guard who arrived as a freshman on the 2001 championship team and became a four-year starter at Duke. Known for his leadership and defensive intensity.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "Gaston Christian School",
        location: "North Carolina",
        statusNote:
          "After going undrafted in 2004, Duhon carved out a nine-year NBA career with the Bulls, Knicks, Magic, and Lakers. After retiring, he transitioned to coaching, serving as an assistant at Marshall and Illinois State. He was inducted into the Greater New Orleans Sports Hall of Fame in 2024 and currently serves as head basketball coach at Gaston Christian School in North Carolina.",
        sourceUrl: "https://en.wikipedia.org/wiki/Chris_Duhon",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 21,
        position: "Point Guard",
        yearsAtSchool: "2000-2004",
        statsNote: "2001 National Champion • Four-year starter • Elite defender",
        gamesPlayed: 36,
        pointsPerGame: 4.3,
        assistsPerGame: 3.2,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2000-2001", yearLabel: "Unknown", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 4.3, assistsPerGame: 3.2 },
      ],
      careerEvents: [
        { year: 2001, title: "Won NCAA National Championship with Duke (freshman)", eventType: "CHAMPIONSHIP" },
        { year: 2004, title: "Signed with Chicago Bulls as undrafted free agent", eventType: "SIGNING" },
        { year: 2013, title: "Retired from NBA after 9 seasons", eventType: "RETIREMENT" },
        { year: 2024, title: "Inducted into Greater New Orleans Sports Hall of Fame", eventType: "AWARD" },
      ],
    },
    {
      slug: "nate-james",
      firstName: "Nate",
      lastName: "James",
      birthYear: 1977,
      hometown: "Washington, D.C.",
      highSchool: "St. John's Catholic Prep, Frederick, MD",
      isFeatured: false,
      bio: "A senior co-captain on the 2001 championship team whose gritty defense and leadership were vital to Duke's title run. James went on to become a long-time Duke assistant coach.",
      status: {
        occupationType: "COACH",
        currentTitle: "Associate Head Coach",
        currentEmployer: "Howard University",
        location: "Washington, D.C.",
        statusNote:
          "After the 2001 championship, James spent 13 years on Coach K's staff at Duke, rising to associate head coach. He became head coach at Austin Peay in 2021 but left after two seasons. In October 2025, he joined Howard University as associate head coach, returning to the D.C. area.",
        sourceUrl: "https://en.wikipedia.org/wiki/Nate_James_(basketball)",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 14,
        position: "Small Forward / Shooting Guard",
        yearsAtSchool: "1997-2001",
        statsNote: "Senior co-captain • 2001 National Champion • Defensive stopper",
        gamesPlayed: 36,
        pointsPerGame: 7.0,
        reboundsPerGame: 3.6,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2000-2001", yearLabel: "Senior", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 7.0, reboundsPerGame: 3.6 },
      ],
      careerEvents: [
        { year: 2001, title: "Won NCAA National Championship with Duke (co-captain)", eventType: "CHAMPIONSHIP" },
        { year: 2001, title: "Joined Duke coaching staff", eventType: "CAREER" },
        { year: 2021, title: "Named head coach at Austin Peay State University", eventType: "CAREER" },
        { year: 2025, title: "Joined Howard University as associate head coach", eventType: "CAREER" },
      ],
    },
    {
      slug: "casey-sanders",
      firstName: "Casey",
      lastName: "Sanders",
      birthYear: 1979,
      hometown: "Tampa, FL",
      highSchool: "Tampa Preparatory School, Tampa, FL",
      isFeatured: false,
      bio: "The starting center on Duke's 2001 championship team who provided rim protection and rebounding in the paint.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Financial Planner",
        location: "Tampa, FL",
        linkedInUrl: "https://www.linkedin.com/in/caseysanders-2020/",
        statusNote:
          "Starting center on the 2001 championship team who went undrafted and played overseas for 6.5 years in Sweden, Venezuela, Poland, Hungary, Latvia, and the NBA D-League. After retiring, worked in medical device sales and pharmaceutical marketing (including GlaxoSmithKline) before transitioning to financial planning. Now self-employed as a financial representative in Tampa, actively mentoring students at his alma mater Tampa Prep on financial literacy.",
        sourceUrl: "https://tampaprep.org/alumni-spotlight-casey-sanders/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 20,
        position: "Center",
        yearsAtSchool: "1999-2003",
        statsNote: "Starting center on 2001 championship team",
        gamesPlayed: 36,
        pointsPerGame: 3.4,
        reboundsPerGame: 3.2,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2000-2001", yearLabel: "Unknown", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 3.4, reboundsPerGame: 3.2 },
      ],
      careerEvents: [
        { year: 2001, title: "Won NCAA National Championship with Duke", eventType: "CHAMPIONSHIP" },
        { year: 2003, title: "Went undrafted; began overseas career", eventType: "CAREER" },
        { year: 2009, title: "Retired from professional basketball", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "nick-horvath",
      firstName: "Nick",
      lastName: "Horvath",
      birthYear: 1981,
      hometown: "Shoreview, MN",
      highSchool: "Mounds View High School, Shoreview, MN",
      isFeatured: false,
      bio: "A versatile forward who was Minnesota Mr. Basketball in 1999. Horvath double-majored in Physics and English at Duke while contributing to the 2001 championship team.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Physics Teacher / Author / Basketball Coach",
        currentEmployer: "Palmerston North Boys' High School",
        location: "Palmerston North, New Zealand",
        statusNote:
          "After Duke, Horvath played 12 years of professional basketball in Australia and New Zealand. After retiring in 2016, he became a physics teacher and head basketball coach at Palmerston North Boys' High School in New Zealand. He is also a published fiction author with novels on Amazon.",
        sourceUrl: "https://en.wikipedia.org/wiki/Nick_Horvath",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 3,
        position: "Forward",
        yearsAtSchool: "1999-2004",
        statsNote: "2001 National Champion • Minnesota Mr. Basketball 1999 • Physics/English double major",
      },
            seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2000-2001", yearLabel: "Sophomore", sortOrder: 201, gamesPlayed: 6, pointsPerGame: 2.8, reboundsPerGame: 2.3, assistsPerGame: 0.2 },
      ],
      careerEvents: [
        { year: 2001, title: "Won NCAA National Championship with Duke", eventType: "CHAMPIONSHIP" },
        { year: 2004, title: "Began pro career in Australia NBL", eventType: "CAREER" },
        { year: 2016, title: "Became physics teacher and coach in New Zealand", eventType: "CAREER" },
      ],
    },
    {
      slug: "reggie-love",
      firstName: "Reggie",
      lastName: "Love",
      birthYear: 1982,
      hometown: "Charlotte, NC",
      highSchool: "Providence Day School, Charlotte, NC",
      isFeatured: true,
      bio: "A two-sport athlete at Duke (basketball and football) who was part of the 2001 championship team. Love went on to serve as personal aide to President Barack Obama.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Senior Advisor",
        currentEmployer: "Apollo Global Management",
        location: "New York, NY",
        linkedInUrl: "https://www.linkedin.com/in/reginald-love-4085a35b/",
        statusNote:
          "After graduating from Duke in 2005, Love became the personal aide ('body man') to President Barack Obama from 2007 to 2011. He earned his MBA from Wharton in 2013 and published the NYT bestseller 'Power Forward: My Presidential Education.' Previously a Partner at RON Transatlantic EG (2012-2019) focused on financial services and energy investments, he is now Senior Advisor at Apollo Global Management.",
        sourceUrl: "https://en.wikipedia.org/wiki/Reggie_Love",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 42,
        position: "Forward",
        yearsAtSchool: "2000-2005",
        statsNote: "2001 National Champion • Two-sport athlete (basketball & football)",
      },
            seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2000-2001", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 32, pointsPerGame: 1.2, reboundsPerGame: 0.8, assistsPerGame: 0.3 },
      ],
      careerEvents: [
        { year: 2001, title: "Won NCAA National Championship with Duke", eventType: "CHAMPIONSHIP" },
        { year: 2009, title: "Named Special Assistant and Personal Aide to President Obama", eventType: "CAREER" },
        { year: 2013, title: "Earned MBA from Wharton School of Business", eventType: "CAREER" },
        { year: 2015, title: "Published 'Power Forward: My Presidential Education'", eventType: "CAREER" },
      ],
    },
    {
      slug: "matt-christensen",
      firstName: "Matt",
      lastName: "Christensen",
      birthYear: 1977,
      hometown: "Belmont, MA",
      highSchool: "Belmont High School, Belmont, MA",
      isFeatured: false,
      bio: "A unique story — Christensen enrolled at Duke in 1995, took two years off for a Mormon mission in Germany, then returned to play on the 2001 championship team as a senior.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "CEO and Portfolio Manager",
        currentEmployer: "Rose Park Advisors",
        location: "Boston, MA",
        linkedInUrl: "https://www.linkedin.com/in/matthewchristensen41/",
        statusNote:
          "Co-founded Rose Park Advisors in 2007 with his late father, Professor Clayton Christensen (Harvard Business School), who developed the theory of 'Disruptive Innovation.' Holds a BSc in Economics and BSE in Civil Engineering from Duke plus an MBA from Harvard. Made a significant gift endowing the Center for Student Design Education at Duke's Pratt School of Engineering. His Duke career was unique — he interrupted it for a two-year Mormon mission in Germany.",
        sourceUrl: "https://www.crunchbase.com/person/matthew-christensen",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 41,
        position: "Forward / Center",
        yearsAtSchool: "1995-2001",
        statsNote: "2001 National Champion • Took 2 years off for Mormon mission",
      },
            seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2000-2001", yearLabel: "Senior", sortOrder: 201, gamesPlayed: 30, pointsPerGame: 1.6, reboundsPerGame: 2.3, assistsPerGame: 0.2 },
      ],
      careerEvents: [
        { year: 2001, title: "Won NCAA National Championship with Duke", eventType: "CHAMPIONSHIP" },
        { year: 2004, title: "Earned MBA from Harvard Business School", eventType: "CAREER" },
      ],
    },
    {
      slug: "andre-buckner",
      firstName: "Andre",
      lastName: "Buckner",
      birthYear: 1981,
      hometown: "Hopkinsville, KY",
      highSchool: "University Heights Academy, Hopkinsville, KY",
      isFeatured: false,
      bio: "A walk-on guard who earned a spot on the roster with no scholarship offers and became part of the winningest senior class in ACC history at the time.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Co-Founder / General Manager",
        currentEmployer: "Higher Goals Now / Team Buckner",
        location: "Dallas, TX",
        statusNote:
          "After graduating with a B.A. in Sociology, Buckner co-founded Higher Goals Now in 2009, a youth basketball training organization in the Dallas-Fort Worth area. He also runs Team Buckner, a youth basketball program, and has over 15 years of coaching experience, having helped train players like NBA center Myles Turner.",
        sourceUrl: "https://teambuckner.sportngin.com/andre-buckner",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 2,
        position: "Guard",
        yearsAtSchool: "1999-2003",
        statsNote: "Walk-on • 2001 National Champion",
      },
            seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2000-2001", yearLabel: "Sophomore", sortOrder: 201, gamesPlayed: 22, pointsPerGame: 0.2, reboundsPerGame: 0.5, assistsPerGame: 0.3 },
      ],
      careerEvents: [
        { year: 2001, title: "Won NCAA National Championship with Duke", eventType: "CHAMPIONSHIP" },
        { year: 2009, title: "Co-founded Higher Goals Now youth basketball program", eventType: "CAREER" },
      ],
    },
    {
      slug: "jd-simpson",
      firstName: "J.D.",
      lastName: "Simpson",
      birthYear: 1978,
      hometown: "Woodside, CA",
      highSchool: "St. Francis High School, Mountain View, CA",
      isFeatured: false,
      bio: "A walk-on guard named tri-captain alongside Shane Battier and Nate James for the championship season, a testament to his leadership despite limited playing time.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Citizen",
        statusNote:
          "Simpson was a walk-on guard who earned the respect of his teammates to be named a tri-captain for the 2001 championship team despite averaging only 2.2 minutes per game. Coach K noted he 'has the respect of everybody even though he doesn't play, which is indicative of his leadership ability.' Post-Duke career information is not publicly available.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/j-d--simpson/4226",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 13,
        position: "Guard",
        yearsAtSchool: "1997-2001",
        statsNote: "Walk-on • Senior tri-captain • 2001 National Champion",
      },
            seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2000-2001", yearLabel: "Senior walk-on", sortOrder: 201, gamesPlayed: 18, pointsPerGame: 0.4, reboundsPerGame: 0.2, assistsPerGame: 0.2 },
      ],
      careerEvents: [
        { year: 2001, title: "Won NCAA National Championship with Duke (tri-captain)", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "andre-sweet",
      firstName: "Andre",
      lastName: "Sweet",
      birthYear: 1982,
      hometown: "Manhattan, NY",
      highSchool: "Rice High School, Bronx, NY",
      isFeatured: false,
      bio: "A highly regarded freshman recruit who played seven games before an academic suspension. He received a championship ring but transferred to Seton Hall after the season.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Real Estate Sales",
        currentEmployer: "Metropolitan Property Group",
        location: "New York, NY",
        statusNote:
          "Sweet played only seven games at Duke before academic suspension and transferred to Seton Hall to be closer to home. After earning a degree in Sociology and Communications at Seton Hall, he went into real estate in New York City as a salesperson at Metropolitan Property Group.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/andre-sweet/4227",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 12,
        position: "Guard / Forward",
        yearsAtSchool: "2000-2001",
        statsNote: "Freshman • Played 7 games • Transferred to Seton Hall",
      },
            seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2000-2001", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 7, pointsPerGame: 1.3, reboundsPerGame: 0.6, assistsPerGame: 0.1 },
      ],
      careerEvents: [
        { year: 2001, title: "Received championship ring; transferred to Seton Hall", eventType: "OTHER" },
      ],
    },
    {
      slug: "ryan-caldbeck",
      firstName: "Ryan",
      lastName: "Caldbeck",
      birthYear: 1979,
      hometown: "Shelburne, VT",
      highSchool: "Rice Memorial High School, South Burlington, VT",
      isFeatured: false,
      bio: "A walk-on guard who went on to become a successful tech entrepreneur, founding CircleUp, a fintech company named by CNBC as one of the Top 5 Most Disruptive Companies in Finance.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Founder & CEO",
        currentEmployer: "Waystation AI",
        location: "San Francisco, CA",
        linkedInUrl: "https://www.linkedin.com/in/ryancaldbeck",
        statusNote:
          "After graduating with a dual B.A. in Public Policy and Psychology, Caldbeck worked in private equity at Bain Capital and TSG Consumer Partners before co-founding CircleUp in 2011, a fintech investment platform named by CNBC as a Top 5 Most Disruptive Company in Finance. Served as CEO until 2020, then Chairman. He is now founder and CEO of Waystation AI, building the intelligence layer for CPG procurement. Also holds an MBA from Stanford.",
        sourceUrl: "https://ryancaldbeck.co/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 5,
        position: "Guard",
        yearsAtSchool: "1997-2001",
        statsNote: "Walk-on • 2001 National Champion",
      },
            seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2000-2001", yearLabel: "Junior walk-on", sortOrder: 201, gamesPlayed: 15, pointsPerGame: 0.3, reboundsPerGame: 0.1, assistsPerGame: 0.1 },
      ],
      careerEvents: [
        { year: 2001, title: "Won NCAA National Championship with Duke", eventType: "CHAMPIONSHIP" },
        { year: 2011, title: "Co-founded CircleUp fintech platform", eventType: "CAREER" },
        { year: 2023, title: "Founded Waystation AI", eventType: "CAREER" },
      ],
    },
    {
      slug: "andy-borman",
      firstName: "Andy",
      lastName: "Borman",
      birthYear: 1981,
      hometown: "Morrisville, NC",
      highSchool: "Fayetteville Academy, Fayetteville, NC",
      isFeatured: false,
      bio: "Coach K's nephew (his mother is the sister of Krzyzewski's wife Mickie) and grandson of astronaut Frank Borman. A five-year walk-on who also started three years on Duke's soccer team.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "Memphis, TN",
        statusNote:
          "Borman built a career in basketball development: Director of Basketball Operations at San Jose State, Director of Player Development at Cal, Executive Director of the NY Renaissance Nike EYBL program (helping 100+ players earn D-I scholarships including Jonathan Kuminga), and assistant coach at Memphis under Penny Hardaway (2022-2024). He parted ways with Memphis in May 2024.",
        sourceUrl: "https://gotigersgo.com/sports/mens-basketball/roster/coaches/andy-borman/3542",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 40,
        position: "Guard",
        yearsAtSchool: "1999-2004",
        statsNote: "Walk-on • Coach K's nephew • Grandson of astronaut Frank Borman",
      },
            seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2000-2001", yearLabel: "Sophomore walk-on", sortOrder: 201, gamesPlayed: 12, pointsPerGame: 0.2, reboundsPerGame: 0.1, assistsPerGame: 0.1 },
      ],
      careerEvents: [
        { year: 2001, title: "Won NCAA National Championship with Duke", eventType: "CHAMPIONSHIP" },
        { year: 2014, title: "Named Executive Director of NY Renaissance Nike EYBL", eventType: "CAREER" },
        { year: 2022, title: "Joined Memphis as assistant coach under Penny Hardaway", eventType: "CAREER" },
      ],
    },
    {
      slug: "mike-krzyzewski",
      firstName: "Mike",
      lastName: "Krzyzewski",
      birthYear: 1947,
      hometown: "Chicago, IL",
      highSchool: "Weber High School, Chicago, IL",
      isFeatured: true,
      bio: "The winningest coach in Division I men's basketball history with 1,202 victories and five national championships. The 2001 title was his third, cementing Duke's dynasty.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Special Advisor / Duke Ambassador",
        currentEmployer: "NBA / Duke University",
        location: "Durham, NC",
        statusNote:
          "Krzyzewski retired after the 2021-22 season as the winningest coach in Division I history with 1,202 victories and five national championships. He serves as a Special Advisor to NBA Commissioner Adam Silver, an Ambassador to Duke, a professor at Duke's Fuqua School of Business, and hosts 'Basketball and Beyond with Coach K' on SiriusXM.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Krzyzewski",
      },
      membership: {
        role: "HEAD_COACH",
        position: "Head Coach",
        yearsAtSchool: "1980-2022",
        statsNote: "1,202 career wins • 5 National Championships • 13 Final Fours",
      },
      careerEvents: [
        { year: 2001, title: "Won third NCAA National Championship", eventType: "CHAMPIONSHIP" },
        { year: 2010, title: "Won fourth NCAA National Championship", eventType: "CHAMPIONSHIP" },
        { year: 2015, title: "Won fifth NCAA National Championship", eventType: "CHAMPIONSHIP" },
        { year: 2022, title: "Retired as winningest coach in D-I history", eventType: "RETIREMENT" },
      ],
    },
  ],
};
