import type { TeamSeed } from "./types";

export const dukeBasketball2005: TeamSeed = {
  slug: "duke-basketball-2005",
  name: "Duke Blue Devils",
  season: "2004-2005",
  sport: "Men's Basketball",
  school: "Duke University",
  conference: "ACC",
  accomplishment: "Sweet Sixteen (27-6)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  mascotName: "Blue Devil",
  people: [
    {
      slug: "jj-redick",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/3024.png",
      firstName: "J.J.",
      lastName: "Redick",
      birthYear: 1984,
      hometown: "Roanoke, VA",
      highSchool: "Cave Spring High School, Roanoke, VA",
      isFeatured: true,
      bio: "Duke's all-time leading scorer and now head coach of the LA Lakers.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Coach",
        currentEmployer: "Los Angeles Lakers",
        league: "NBA",
        location: "Los Angeles, CA",
        statusNote:
          "Selected #11 overall in 2006, Redick played 15 NBA seasons as an elite shooter. After retiring in 2021, he built a media empire before being hired as Lakers head coach in June 2024.",
        sourceUrl: "https://en.wikipedia.org/wiki/J._J._Redick",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 4,
        position: "Shooting Guard",
        yearsAtSchool: "2002-2006",
        statsNote: "Junior • ACC Player of the Year candidate • Elite scorer",
        gamesPlayed: 33,
        pointsPerGame: 21.8,
      },
      careerEvents: [
        { year: 2006, title: "Selected #11 overall by the Orlando Magic", eventType: "DRAFT" },
        { year: 2024, title: "Named head coach of the Los Angeles Lakers", eventType: "CAREER" },
      ],
    },
    {
      slug: "shelden-williams",
      firstName: "Shelden",
      lastName: "Williams",
      birthYear: 1983,
      hometown: "Midwest City, OK",
      highSchool: "Midwest City High School, Midwest City, OK",
      isFeatured: false,
      bio: "A dominant shot-blocking center and Duke's all-time blocks leader.",
      status: {
        occupationType: "COACH",
        currentTitle: "Podcast Host / Foundation Director",
        location: "Atlanta, GA",
        statusNote:
          "Selected #5 overall by the Hawks in 2006. Now involved in youth basketball coaching in Atlanta.",
        sourceUrl: "https://en.wikipedia.org/wiki/Shelden_Williams",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 23,
        position: "Center / Power Forward",
        yearsAtSchool: "2002-2006",
        statsNote: "Junior • NABC Defensive POY candidate • Double-double machine",
        gamesPlayed: 33,
        pointsPerGame: 14.5,
        reboundsPerGame: 9.7,
      },
      careerEvents: [
        { year: 2006, title: "Selected #5 overall by the Atlanta Hawks", eventType: "DRAFT" },
      ],
    },
    {
      slug: "daniel-ewing",
      firstName: "Daniel",
      lastName: "Ewing",
      birthYear: 1983,
      hometown: "Houston, TX",
      highSchool: "Willowridge High School, Houston, TX",
      isFeatured: false,
      bio: "A four-year guard who developed into a key scorer and leader.",
      status: {
        occupationType: "FRONT_OFFICE",
        currentTitle: "Professional Scout",
        currentEmployer: "Los Angeles Lakers",
        league: "NBA",
        location: "Los Angeles, CA",
        statusNote:
          "Selected #32 overall by the LA Clippers in 2005. Now a professional scout for the Lakers.",
        sourceUrl: "https://en.wikipedia.org/wiki/Daniel_Ewing",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 5,
        position: "Shooting Guard",
        yearsAtSchool: "2001-2005",
        statsNote: "Senior captain • Team leader and go-to scorer",
        gamesPlayed: 33,
        pointsPerGame: 16.2,
        assistsPerGame: 3.8,
      },
      careerEvents: [
        { year: 2005, title: "Selected #32 overall by the LA Clippers", eventType: "DRAFT" },
      ],
    },
    {
      slug: "demarcus-nelson",
      firstName: "DeMarcus",
      lastName: "Nelson",
      birthYear: 1986,
      hometown: "Vallejo, CA",
      highSchool: "Jesse Bethel High School, Vallejo, CA",
      isFeatured: false,
      bio: "A versatile guard/forward who was a four-year contributor at Duke, earning ACC All-Defensive Team honors and becoming a fan favorite for his hustle.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "California",
        statusNote:
          "After graduating from Duke in 2008, Nelson went undrafted and played briefly in the NBA Summer League with the Warriors and overseas. He transitioned to coaching and player development, working with youth basketball programs in the Bay Area. He remains connected to Duke basketball.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/demarcus-nelson/4244",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 1,
        position: "Shooting Guard / Small Forward",
        yearsAtSchool: "2004-2008",
        statsNote: "Freshman contributor • ACC All-Defensive Team (later years)",
      },
      careerEvents: [
        { year: 2008, title: "Graduated from Duke; went undrafted", eventType: "CAREER" },
      ],
    },
    {
      slug: "shavlik-randolph",
      firstName: "Shavlik",
      lastName: "Randolph",
      birthYear: 1983,
      hometown: "Raleigh, NC",
      highSchool: "Broughton High School, Raleigh, NC",
      isFeatured: false,
      bio: "A McDonald's All-American power forward from Raleigh.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Owner / Investor",
        currentEmployer: "Big Prime Hauling",
        location: "Raleigh, NC",
        statusNote:
          "Randolph went undrafted but played in the NBA with the 76ers and Celtics. He now runs Big Prime Hauling, a trucking company in North Carolina.",
        sourceUrl: "https://en.wikipedia.org/wiki/Shavlik_Randolph",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 42,
        position: "Power Forward",
        yearsAtSchool: "2002-2006",
        statsNote: "Junior • Interior scorer and rebounder",
        gamesPlayed: 33,
        pointsPerGame: 8.2,
        reboundsPerGame: 5.1,
      },
      careerEvents: [
        { year: 2006, title: "Went undrafted; signed with 76ers", eventType: "SIGNING" },
      ],
    },
    {
      slug: "lee-melchionni",
      firstName: "Lee",
      lastName: "Melchionni",
      birthYear: 1983,
      hometown: "Germantown, PA",
      highSchool: "Germantown Academy, Fort Washington, PA",
      isFeatured: false,
      bio: "A sharpshooting guard and four-year contributor.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Sports Agent",
        currentEmployer: "Wasserman Media Group",
        location: "Los Angeles, CA",
        statusNote:
          "After Duke, Melchionni played one season in Italy then became an NBA player agent at Wasserman Media Group.",
        sourceUrl: "https://lancasteronline.com/sports/nba/basketball-still-melchionni-s-business/article_f4a85d66-0400-11e4-a2ab-001a4bcf6878.html",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 20,
        position: "Shooting Guard",
        yearsAtSchool: "2002-2006",
        statsNote: "Junior • Reliable perimeter shooter",
      },
      careerEvents: [
        { year: 2006, title: "Graduated from Duke", eventType: "CAREER" },
      ],
    },
    {
      slug: "sean-dockery",
      firstName: "Sean",
      lastName: "Dockery",
      birthYear: 1985,
      hometown: "Milwaukee, WI",
      highSchool: "Vincent High School, Milwaukee, WI",
      isFeatured: false,
      bio: "A quick, athletic point guard remembered for his buzzer-beating half-court shot against Virginia Tech.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Owner / Basketball Trainer",
        currentEmployer: "Dockery Basketball Academy",
        location: "San Antonio, TX",
        statusNote:
          "After Duke, Dockery played overseas then coached with the Spurs and Grizzlies. He now runs Dockery Basketball Academy in San Antonio.",
        sourceUrl: "http://www.dockerybasketball.com/about-us/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 3,
        position: "Point Guard",
        yearsAtSchool: "2003-2007",
        statsNote: "Sophomore • Hit legendary buzzer-beater vs Virginia Tech",
      },
      careerEvents: [
        { year: 2005, title: "Hit half-court buzzer-beater to beat Virginia Tech", eventType: "OTHER" },
      ],
    },
    {
      slug: "reggie-love",
      firstName: "Reggie",
      lastName: "Love",
      birthYear: 1982,
      hometown: "Charlotte, NC",
      highSchool: "Providence Day School, Charlotte, NC",
      isFeatured: false,
      bio: "A senior two-sport athlete completing his Duke career before going on to serve as personal aide to President Obama.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Partner and Vice President",
        currentEmployer: "Transatlantic Holdings",
        location: "Washington, D.C.",
        statusNote: "Served as Obama's personal aide, earned Wharton MBA, now partner at Transatlantic Holdings.",
        sourceUrl: "https://en.wikipedia.org/wiki/Reggie_Love",
      },
      membership: { role: "PLAYER", jerseyNumber: 42, position: "Forward", yearsAtSchool: "2000-2005", statsNote: "Senior • Two-sport athlete" },
      careerEvents: [{ year: 2009, title: "Named personal aide to President Obama", eventType: "CAREER" }],
    },
    {
      slug: "david-mcclure",
      firstName: "David",
      lastName: "McClure",
      birthYear: 1986,
      hometown: "Ridgefield, CT",
      highSchool: "Ridgefield High School, Ridgefield, CT",
      isFeatured: false,
      bio: "A walk-on who earned a scholarship and played five seasons at Duke (2004-09), known for his hustle and toughness.",
      status: {
        occupationType: "COACH",
        currentTitle: "Player Development Coach",
        currentEmployer: "San Antonio Spurs",
        league: "NBA",
        location: "San Antonio, TX",
        statusNote:
          "After Duke, McClure played in the D-League and Lithuania before knee injuries (six surgeries) ended his playing career. He joined the San Antonio Spurs in a player development coaching role and is a member of the NBA Coaches Association.",
        sourceUrl: "https://nbacoaches.com/david-mcclure/",
      },
      membership: { role: "PLAYER", jerseyNumber: 14, position: "Small Forward", yearsAtSchool: "2004-2009", statsNote: "Freshman walk-on • Earned scholarship" },
      careerEvents: [
        { year: 2009, title: "Graduated from Duke", eventType: "CAREER" },
        { year: 2014, title: "Joined San Antonio Spurs player development staff", eventType: "CAREER" },
      ],
    },
    {
      slug: "joe-pagliuca",
      firstName: "Joe",
      lastName: "Pagliuca",
      birthYear: 1982,
      hometown: "Weston, MA",
      highSchool: "Buckingham Browne & Nichols, Cambridge, MA",
      isFeatured: false,
      bio: "Walk-on guard and son of Celtics co-owner Stephen Pagliuca. Won the Hart Award as Duke basketball's top scholar-athlete.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Co-Founder & President",
        location: "Boston, MA",
        statusNote: "Pursued career in biotech/venture capital after Duke. Son of Bain Capital co-chairman and Celtics co-owner Stephen Pagliuca.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/joe-pagliuca/4286",
      },
      membership: { role: "PLAYER", jerseyNumber: 43, position: "Guard", yearsAtSchool: "2000-2004", statsNote: "Fifth-year walk-on • Hart Award winner" },
      careerEvents: [{ year: 2004, title: "Won Dr. Deryl Hart Award as top scholar-athlete", eventType: "AWARD" }],
    },
    {
      slug: "patrick-johnson-duke",
      firstName: "Patrick",
      lastName: "Johnson",
      birthYear: 1984,
      hometown: "Glendora, CA",
      highSchool: "Glendora High School, Glendora, CA",
      isFeatured: false,
      bio: "A walk-on who earned a scholarship entering the 2004-05 season after overcoming knee surgery that prevented him from playing high school basketball. A remarkable underdog story.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "Citrus College",
        location: "Glendora, CA",
        statusNote:
          "After earning a B.A. in Political Science from Duke in 2006, Johnson built a coaching career including assistant roles at Citrus College and head coach at Concordia University Irvine (69-31 record, two NAIA tournament appearances). He was named head men's basketball coach at Citrus College in July 2015.",
        sourceUrl: "https://www.citrusowls.com/sports/mbkb/coaches/PatrickJohnson",
      },
      membership: { role: "PLAYER", jerseyNumber: 24, position: "Forward / Center", yearsAtSchool: "2002-2006", statsNote: "Walk-on turned scholarship player • 22 games in 2004-05" },
      careerEvents: [
        { year: 2006, title: "Graduated from Duke with B.A. in Political Science", eventType: "CAREER" },
        { year: 2015, title: "Named head men's basketball coach at Citrus College", eventType: "CAREER" },
      ],
    },
    {
      slug: "mike-krzyzewski",
      firstName: "Mike",
      lastName: "Krzyzewski",
      birthYear: 1947,
      hometown: "Chicago, IL",
      highSchool: "Weber High School, Chicago, IL",
      isFeatured: true,
      bio: "The winningest coach in Division I men's basketball history.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Special Advisor / Duke Ambassador",
        currentEmployer: "NBA / Duke University",
        location: "Durham, NC",
        statusNote:
          "Retired in 2022 with 1,202 victories and five national championships.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Krzyzewski",
      },
      membership: {
        role: "HEAD_COACH",
        position: "Head Coach",
        yearsAtSchool: "1980-2022",
        statsNote: "27-6 record in 2004-05 • Sweet Sixteen",
      },
      careerEvents: [
        { year: 2022, title: "Retired as winningest coach in D-I history", eventType: "RETIREMENT" },
      ],
    },
  ],
};
