import type { TeamSeed } from "./types";

export const dukeBasketball2004: TeamSeed = {
  slug: "duke-basketball-2004",
  name: "Duke Blue Devils",
  season: "2003-2004",
  sport: "Men's Basketball",
  school: "Duke University",
  conference: "ACC",
  accomplishment: "Final Four (31-6)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  mascotName: "Blue Devil",
  people: [
    {
      slug: "luol-deng",
      firstName: "Luol",
      lastName: "Deng",
      birthYear: 1985,
      hometown: "London, England (born in Wau, Sudan)",
      highSchool: "Blair Academy, Blairstown, NJ",
      isFeatured: true,
      bio: "A one-and-done freshman sensation who led Duke to the Final Four in 2004, averaging 15.1 points. Deng was born in war-torn Sudan and became a global basketball ambassador.",
      status: {
        occupationType: "FRONT_OFFICE",
        currentTitle: "President, South Sudan Basketball Federation",
        location: "London, England",
        statusNote:
          "Selected #7 overall by the Chicago Bulls in 2004, Deng was a two-time All-Star over a 15-year NBA career with the Bulls, Cavaliers, Heat, Lakers, and Timberwolves, earning over $150 million. After retiring in 2019, he became president of the South Sudan Basketball Federation, personally funding the program. He led South Sudan to the 2024 Olympics — their first ever — establishing them as the top team in African basketball. He is also an investor in NBA Africa.",
        sourceUrl: "https://en.wikipedia.org/wiki/Luol_Deng",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 9,
        position: "Small Forward",
        yearsAtSchool: "2003-2004",
        statsNote: "One-and-done • Led Duke to Final Four • #7 overall pick",
        gamesPlayed: 37,
        pointsPerGame: 15.1,
        reboundsPerGame: 6.9,
        assistsPerGame: 1.9,
      },
      careerEvents: [
        { year: 2004, title: "Selected #7 overall by the Chicago Bulls", eventType: "DRAFT" },
        { year: 2012, title: "Named NBA All-Star", eventType: "AWARD" },
        { year: 2019, title: "Retired from NBA; became president of South Sudan Basketball", eventType: "CAREER" },
        { year: 2024, title: "Led South Sudan to first-ever Olympic Games appearance", eventType: "CAREER" },
      ],
    },
    {
      slug: "chris-duhon",
      firstName: "Chris",
      lastName: "Duhon",
      birthYear: 1982,
      hometown: "Slidell, LA",
      highSchool: "Salmen High School, Slidell, LA",
      isFeatured: false,
      bio: "A four-year starter who captained the 2004 Final Four team as a senior.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "Gaston Christian School",
        location: "North Carolina",
        statusNote:
          "After a nine-year NBA career, Duhon is now head basketball coach at Gaston Christian School.",
        sourceUrl: "https://en.wikipedia.org/wiki/Chris_Duhon",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 21,
        position: "Point Guard",
        yearsAtSchool: "2000-2004",
        statsNote: "Senior captain • Four-year starter • 2001 National Champion",
        gamesPlayed: 37,
        pointsPerGame: 10.2,
        assistsPerGame: 6.2,
      },
      careerEvents: [
        { year: 2004, title: "Signed with Chicago Bulls as undrafted free agent", eventType: "SIGNING" },
      ],
    },
    {
      slug: "jj-redick",
      firstName: "J.J.",
      lastName: "Redick",
      birthYear: 1984,
      hometown: "Roanoke, VA",
      highSchool: "Cave Spring High School, Roanoke, VA",
      isFeatured: true,
      bio: "Duke's all-time leading scorer who became one of the greatest shooters in both college and NBA history.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Coach",
        currentEmployer: "Los Angeles Lakers",
        league: "NBA",
        location: "Los Angeles, CA",
        statusNote:
          "After 15 NBA seasons as an elite shooter, Redick retired in 2021 and built a media empire with 'The Old Man and the Three' podcast. In June 2024, he was hired as head coach of the Los Angeles Lakers.",
        sourceUrl: "https://en.wikipedia.org/wiki/J._J._Redick",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 4,
        position: "Shooting Guard",
        yearsAtSchool: "2002-2006",
        statsNote: "Sophomore sharpshooter • Led team in scoring",
        gamesPlayed: 37,
        pointsPerGame: 15.9,
      },
      careerEvents: [
        { year: 2006, title: "Selected #11 overall by the Orlando Magic", eventType: "DRAFT" },
        { year: 2024, title: "Named head coach of the Los Angeles Lakers", eventType: "CAREER" },
      ],
    },
    {
      slug: "shelden-williams",
      firstName: "Shelden",
      lastName: "Williams",
      birthYear: 1983,
      hometown: "Midwest City, OK",
      highSchool: "Midwest City High School, Midwest City, OK",
      isFeatured: false,
      bio: "A dominant shot-blocking center who became Duke's all-time leader in blocked shots.",
      status: {
        occupationType: "COACH",
        currentTitle: "Podcast Host / Foundation Director",
        location: "Atlanta, GA",
        statusNote:
          "Selected #5 overall by the Hawks in 2006, Williams played six NBA seasons. He is now involved in youth basketball coaching in Atlanta.",
        sourceUrl: "https://en.wikipedia.org/wiki/Shelden_Williams",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 23,
        position: "Center / Power Forward",
        yearsAtSchool: "2002-2006",
        statsNote: "Sophomore starter • Emerging defensive force",
        gamesPlayed: 37,
        pointsPerGame: 11.2,
        reboundsPerGame: 8.3,
      },
      careerEvents: [
        { year: 2006, title: "Selected #5 overall by the Atlanta Hawks", eventType: "DRAFT" },
      ],
    },
    {
      slug: "daniel-ewing",
      firstName: "Daniel",
      lastName: "Ewing",
      birthYear: 1983,
      hometown: "Houston, TX",
      highSchool: "Willowridge High School, Houston, TX",
      isFeatured: false,
      bio: "A four-year contributor who developed into one of Duke's top scorers.",
      status: {
        occupationType: "FRONT_OFFICE",
        currentTitle: "Professional Scout",
        currentEmployer: "Los Angeles Lakers",
        league: "NBA",
        location: "Los Angeles, CA",
        statusNote:
          "Selected #32 overall in 2005, Ewing now works as a professional scout for the Lakers.",
        sourceUrl: "https://en.wikipedia.org/wiki/Daniel_Ewing",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 5,
        position: "Shooting Guard",
        yearsAtSchool: "2001-2005",
        statsNote: "Junior starter • Key scorer",
        gamesPlayed: 37,
        pointsPerGame: 13.5,
        assistsPerGame: 3.2,
      },
      careerEvents: [
        { year: 2005, title: "Selected #32 overall by the LA Clippers", eventType: "DRAFT" },
      ],
    },
    {
      slug: "shavlik-randolph",
      firstName: "Shavlik",
      lastName: "Randolph",
      birthYear: 1983,
      hometown: "Raleigh, NC",
      highSchool: "Broughton High School, Raleigh, NC",
      isFeatured: false,
      bio: "A McDonald's All-American power forward from Raleigh.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Owner / Investor",
        currentEmployer: "Big Prime Hauling",
        location: "Raleigh, NC",
        statusNote:
          "Randolph went undrafted but played in the NBA with the 76ers and Celtics. After retiring, he invested in Big Prime Hauling, a trucking company in North Carolina.",
        sourceUrl: "https://en.wikipedia.org/wiki/Shavlik_Randolph",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 42,
        position: "Power Forward",
        yearsAtSchool: "2002-2006",
        statsNote: "Sophomore contributor",
        gamesPlayed: 37,
        pointsPerGame: 6.8,
        reboundsPerGame: 4.5,
      },
      careerEvents: [
        { year: 2006, title: "Went undrafted; signed with Philadelphia 76ers", eventType: "SIGNING" },
      ],
    },
    {
      slug: "sean-dockery",
      firstName: "Sean",
      lastName: "Dockery",
      birthYear: 1985,
      hometown: "Milwaukee, WI",
      highSchool: "Vincent High School, Milwaukee, WI",
      isFeatured: false,
      bio: "A quick, athletic point guard who backed up Duhon and is remembered for his buzzer-beating half-court shot against Virginia Tech in 2005.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Owner / Basketball Trainer",
        currentEmployer: "Dockery Basketball Academy",
        location: "San Antonio, TX",
        statusNote:
          "After Duke, Dockery played professionally overseas before working as a player development coach for the San Antonio Spurs (2016-17) and Memphis Grizzlies (2017-18). He now runs Dockery Basketball Academy in San Antonio, a year-round training program for youth and professional players. Best remembered for his buzzer-beating half-court shot against Virginia Tech in 2005.",
        sourceUrl: "http://www.dockerybasketball.com/about-us/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 3,
        position: "Point Guard",
        yearsAtSchool: "2003-2007",
        statsNote: "Freshman backup PG • Athletic defender",
      },
      careerEvents: [
        { year: 2007, title: "Graduated from Duke; began overseas career", eventType: "CAREER" },
      ],
    },
    {
      slug: "lee-melchionni",
      firstName: "Lee",
      lastName: "Melchionni",
      birthYear: 1983,
      hometown: "Germantown, PA",
      highSchool: "Germantown Academy, Fort Washington, PA",
      isFeatured: false,
      bio: "A sharpshooting guard who became an NBA sports agent after Duke.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Sports Agent",
        currentEmployer: "Wasserman Media Group",
        location: "Los Angeles, CA",
        statusNote: "Became an NBA player agent at Wasserman Media Group after a season playing in Italy.",
        sourceUrl: "https://lancasteronline.com/sports/nba/basketball-still-melchionni-s-business/article_f4a85d66-0400-11e4-a2ab-001a4bcf6878.html",
      },
      membership: { role: "PLAYER", jerseyNumber: 20, position: "Shooting Guard", yearsAtSchool: "2002-2006", statsNote: "Sophomore • Perimeter shooter" },
      careerEvents: [{ year: 2010, title: "Became NBA agent at Wasserman Media Group", eventType: "CAREER" }],
    },
    {
      slug: "nick-horvath",
      firstName: "Nick",
      lastName: "Horvath",
      birthYear: 1981,
      hometown: "Shoreview, MN",
      highSchool: "Mounds View High School, Shoreview, MN",
      isFeatured: false,
      bio: "A fifth-year senior completing his Duke career. Double-majored in Physics and English.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Physics Teacher / Author",
        currentEmployer: "Palmerston North Boys' High School",
        location: "Palmerston North, New Zealand",
        statusNote: "Now a physics teacher and published author in New Zealand after 12 years playing professionally.",
        sourceUrl: "https://en.wikipedia.org/wiki/Nick_Horvath",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Forward", yearsAtSchool: "1999-2004", statsNote: "Fifth-year senior • 2001 champion" },
      careerEvents: [{ year: 2016, title: "Became physics teacher in New Zealand", eventType: "CAREER" }],
    },
    {
      slug: "reggie-love",
      firstName: "Reggie",
      lastName: "Love",
      birthYear: 1982,
      hometown: "Charlotte, NC",
      highSchool: "Providence Day School, Charlotte, NC",
      isFeatured: false,
      bio: "Two-sport athlete who later became personal aide to President Obama.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Partner and Vice President",
        currentEmployer: "Transatlantic Holdings",
        location: "Washington, D.C.",
        statusNote: "Served as Obama's personal aide, earned Wharton MBA, now partner at Transatlantic Holdings.",
        sourceUrl: "https://en.wikipedia.org/wiki/Reggie_Love",
      },
      membership: { role: "PLAYER", jerseyNumber: 42, position: "Forward", yearsAtSchool: "2000-2005", statsNote: "Junior • Two-sport athlete" },
      careerEvents: [{ year: 2009, title: "Named personal aide to President Obama", eventType: "CAREER" }],
    },
    {
      slug: "andy-borman",
      firstName: "Andy",
      lastName: "Borman",
      birthYear: 1981,
      hometown: "Morrisville, NC",
      highSchool: "Fayetteville Academy, Fayetteville, NC",
      isFeatured: false,
      bio: "Coach K's nephew completing his five-year Duke career.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "Memphis, TN",
        statusNote: "Built career in basketball development. Coached at Memphis under Penny Hardaway (2022-24).",
        sourceUrl: "https://gotigersgo.com/sports/mens-basketball/roster/coaches/andy-borman/3542",
      },
      membership: { role: "PLAYER", jerseyNumber: 40, position: "Guard", yearsAtSchool: "1999-2004", statsNote: "Senior walk-on • Coach K's nephew" },
      careerEvents: [{ year: 2022, title: "Joined Memphis as assistant coach", eventType: "CAREER" }],
    },
    {
      slug: "mike-krzyzewski",
      firstName: "Mike",
      lastName: "Krzyzewski",
      birthYear: 1947,
      hometown: "Chicago, IL",
      highSchool: "Weber High School, Chicago, IL",
      isFeatured: true,
      bio: "The winningest coach in Division I men's basketball history.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Special Advisor / Duke Ambassador",
        currentEmployer: "NBA / Duke University",
        location: "Durham, NC",
        statusNote:
          "Retired in 2022 with 1,202 victories and five national championships.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Krzyzewski",
      },
      membership: {
        role: "HEAD_COACH",
        position: "Head Coach",
        yearsAtSchool: "1980-2022",
        statsNote: "31-6 record in 2003-04 • Final Four",
      },
      careerEvents: [
        { year: 2022, title: "Retired as winningest coach in D-I history", eventType: "RETIREMENT" },
      ],
    },
  ],
};
