import type { TeamSeed } from "./types";

export const dukeBasketball2008: TeamSeed = {
  slug: "duke-basketball-2008",
  name: "Duke Blue Devils",
  season: "2007-2008",
  sport: "Men's Basketball",
  school: "Duke University",
  conference: "ACC",
  accomplishment: "ACC Tournament Champions, NCAA 2nd Round (28-6)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  mascotName: "Blue Devil",
  people: [
    {
      slug: "demarcus-nelson",
      firstName: "DeMarcus",
      lastName: "Nelson",
      birthYear: 1986,
      hometown: "Vallejo, CA",
      highSchool: "Sheldon High School, Elk Grove, CA",
      isFeatured: true,
      bio: "Senior captain who led Duke to an ACC Tournament title and a 28-6 record. Averaged 14.5 PPG and was named First-Team All-ACC.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "Vallejo, CA",
        statusNote:
          "Went undrafted in 2008 but signed with the Golden State Warriors and made his hometown NBA debut, playing 16 games before being waived. Spent the rest of his decade-plus career overseas in Italy, Greece, France, Russia, and the NBA D-League. Retired around 2018.",
        sourceUrl: "https://en.wikipedia.org/wiki/DeMarcus_Nelson",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 21,
        position: "Shooting Guard",
        yearsAtSchool: "2004-2008",
        statsNote: "Senior captain • First-Team All-ACC • 14.5 PPG, 6.0 RPG",
        gamesPlayed: 33,
        pointsPerGame: 14.5,
        reboundsPerGame: 6.0,
        assistsPerGame: 2.5,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Sheldon High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 33.7, reboundsPerGame: 11.0, assistsPerGame: 5.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2007-08", yearLabel: "2007-08 (Senior, Captain)", sortOrder: 204, gamesPlayed: 33, pointsPerGame: 14.5, reboundsPerGame: 6.0, assistsPerGame: 2.5 },
        { level: "PROFESSIONAL", teamName: "Golden State Warriors", season: "2008-09", yearLabel: "2008-09 (Rookie)", sortOrder: 301, gamesPlayed: 16, pointsPerGame: 5.4, reboundsPerGame: 1.7, assistsPerGame: 1.5 },
      ],
      careerEvents: [
        { year: 2008, title: "Named First-Team All-ACC; Duke won ACC Tournament", eventType: "AWARD" },
        { year: 2008, title: "Signed with Golden State Warriors as undrafted free agent", eventType: "SIGNING" },
      ],
    },
    {
      slug: "gerald-henderson",
      firstName: "Gerald",
      lastName: "Henderson",
      birthYear: 1987,
      hometown: "Merion Station, PA",
      highSchool: "Episcopal Academy, Merion, PA",
      isFeatured: true,
      bio: "Sophomore guard whose athleticism made him a key piece of Duke's backcourt. Would be drafted #12 overall by Charlotte the following year.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "Charlotte, NC",
        statusNote:
          "Selected #12 overall by the Charlotte Bobcats in the 2009 NBA Draft. Played 9 NBA seasons with the Bobcats/Hornets, Trail Blazers, and 76ers. Career averages: 11.0 PPG, 2.9 RPG over 530 games. Retired in 2018 and has been involved in basketball training and youth development around Charlotte.",
        sourceUrl: "https://en.wikipedia.org/wiki/Gerald_Henderson_Jr.",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 15,
        position: "Shooting Guard",
        yearsAtSchool: "2006-2009",
        statsNote: "Sophomore • 12.7 PPG, 4.8 RPG",
        gamesPlayed: 34,
        pointsPerGame: 12.7,
        reboundsPerGame: 4.8,
        assistsPerGame: 1.5,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2007-08", yearLabel: "2007-08 (Sophomore)", sortOrder: 202, gamesPlayed: 34, pointsPerGame: 12.7, reboundsPerGame: 4.8, assistsPerGame: 1.5 },
        { level: "PROFESSIONAL", teamName: "Charlotte Bobcats", season: "2012-13", yearLabel: "2012-13 (Career best)", sortOrder: 304, gamesPlayed: 68, pointsPerGame: 15.5, reboundsPerGame: 3.7, assistsPerGame: 2.6 },
      ],
      careerEvents: [
        { year: 2009, title: "Selected #12 overall by Charlotte Bobcats", eventType: "DRAFT" },
        { year: 2018, title: "Retired from professional basketball", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "kyle-singler",
      firstName: "Kyle",
      lastName: "Singler",
      birthYear: 1988,
      hometown: "Medford, OR",
      highSchool: "South Medford High School, Medford, OR",
      isFeatured: true,
      bio: "Highly recruited McDonald's All-American freshman who immediately stepped into a starting role. Would go on to be the 2010 Final Four Most Outstanding Player.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "Oklahoma",
        statusNote: "Selected #33 overall by Detroit in 2011. Played 8 NBA seasons with the Pistons and Thunder. Was the 2010 Final Four Most Outstanding Player at Duke and holds Duke career records for games played and minutes. Retired in 2019.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kyle_Singler",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 12,
        position: "Small Forward",
        yearsAtSchool: "2007-2011",
        statsNote: "Freshman • ACC All-Freshman Team • 13.3 PPG, 5.6 RPG",
        gamesPlayed: 36,
        pointsPerGame: 13.3,
        reboundsPerGame: 5.6,
        assistsPerGame: 1.2,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "South Medford High School", season: "Senior", yearLabel: "Senior (McDonald's All-American)", sortOrder: 1, pointsPerGame: 31.5, reboundsPerGame: 12.1, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2007-08", yearLabel: "2007-08 (Freshman)", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 13.3, reboundsPerGame: 5.6, assistsPerGame: 1.2 },
      ],
      careerEvents: [
        { year: 2010, title: "Won NCAA Championship; named Final Four MOP", eventType: "CHAMPIONSHIP" },
        { year: 2011, title: "Selected #33 overall by Detroit Pistons", eventType: "DRAFT" },
      ],
    },
    {
      slug: "jon-scheyer",
      firstName: "Jon",
      lastName: "Scheyer",
      birthYear: 1987,
      hometown: "Northbrook, IL",
      highSchool: "Glenbrook North High School, Northbrook, IL",
      isFeatured: true,
      bio: "Sophomore guard who shared backcourt duties and averaged 10.3 PPG. Would later become Duke's head coach after a national title as a senior in 2010.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "Duke University",
        league: "ACC",
        location: "Durham, NC",
        statusNote:
          "After winning the 2010 NCAA championship as a senior captain, a brief professional career was cut short by an eye injury. He joined Duke's coaching staff in 2013 and was named the school's 20th head coach in 2021, succeeding Coach K. His 124 wins through his first four seasons are the most by any D-I coach in history.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jon_Scheyer",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 30,
        position: "Shooting Guard",
        yearsAtSchool: "2006-2010",
        statsNote: "Sophomore • 10.3 PPG, 2.5 APG",
        gamesPlayed: 34,
        pointsPerGame: 10.3,
        reboundsPerGame: 3.2,
        assistsPerGame: 2.5,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2007-08", yearLabel: "2007-08 (Sophomore)", sortOrder: 202, gamesPlayed: 34, pointsPerGame: 10.3, reboundsPerGame: 3.2, assistsPerGame: 2.5 },
      ],
      careerEvents: [
        { year: 2010, title: "Won NCAA National Championship with Duke", eventType: "CHAMPIONSHIP" },
        { year: 2021, title: "Named Duke's 20th head coach, succeeding Coach K", eventType: "CAREER" },
      ],
    },
    {
      slug: "greg-paulus",
      firstName: "Greg",
      lastName: "Paulus",
      birthYear: 1986,
      hometown: "Syracuse, NY",
      highSchool: "Christian Brothers Academy, Syracuse, NY",
      isFeatured: false,
      bio: "Junior point guard who started for Duke and continued to direct the offense. Famously returned to football as Syracuse's quarterback after his Duke basketball career.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "Niagara University",
        league: "MAAC",
        location: "Niagara, NY",
        statusNote:
          "After his Duke basketball career ended in 2009, Paulus famously used his final year of athletic eligibility to play quarterback at Syracuse. He then transitioned into coaching, serving as an assistant at Ohio State and Louisville. Hired as head men's basketball coach at Niagara University in 2022.",
        sourceUrl: "https://en.wikipedia.org/wiki/Greg_Paulus",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 3,
        position: "Point Guard",
        yearsAtSchool: "2005-2009",
        statsNote: "Junior • 8.4 PPG, 4.8 APG",
        gamesPlayed: 34,
        pointsPerGame: 8.4,
        reboundsPerGame: 2.0,
        assistsPerGame: 4.8,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2007-08", yearLabel: "2007-08 (Junior)", sortOrder: 203, gamesPlayed: 34, pointsPerGame: 8.4, reboundsPerGame: 2.0, assistsPerGame: 4.8 },
      ],
      careerEvents: [
        { year: 2009, title: "Became starting QB at Syracuse for one season", eventType: "CAREER" },
        { year: 2022, title: "Named head men's basketball coach at Niagara University", eventType: "CAREER" },
      ],
    },
    {
      slug: "nolan-smith",
      firstName: "Nolan",
      lastName: "Smith",
      birthYear: 1988,
      hometown: "Upper Marlboro, MD",
      highSchool: "Oak Hill Academy, Mouth of Wilson, VA",
      isFeatured: true,
      bio: "Freshman guard and son of late NBA player Derek Smith. Would develop into a national champion and ACC Player of the Year by his junior year.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "Tennessee State University",
        location: "Nashville, TN",
        statusNote: "After a brief NBA career (#21 pick, 2011), Smith returned to coaching. Now head coach at Tennessee State — led them to the OVC title and March Madness in his first season (2025-26), winning OVC Co-Coach of the Year with a program-record 23 wins.",
        sourceUrl: "https://hbcugameday.com/2026/03/09/duke-legend-nolan-smith-hbcu-tennessee-state-march-madness/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 2,
        position: "Guard",
        yearsAtSchool: "2007-2011",
        statsNote: "Freshman • 5.9 PPG",
        gamesPlayed: 33,
        pointsPerGame: 5.9,
        reboundsPerGame: 1.4,
        assistsPerGame: 1.0,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Oak Hill Academy", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 31.1, reboundsPerGame: 3.8, assistsPerGame: 8.6 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2007-08", yearLabel: "2007-08 (Freshman)", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 5.9, reboundsPerGame: 1.4, assistsPerGame: 1.0 },
      ],
      careerEvents: [
        { year: 2010, title: "Won NCAA National Championship", eventType: "CHAMPIONSHIP" },
        { year: 2011, title: "Selected #21 overall by Portland Trail Blazers", eventType: "DRAFT" },
      ],
    },
    {
      slug: "lance-thomas",
      firstName: "Lance",
      lastName: "Thomas",
      birthYear: 1988,
      hometown: "Scotch Plains, NJ",
      highSchool: "St. Benedict's Prep, Newark, NJ",
      isFeatured: false,
      bio: "Sophomore power forward and defensive specialist. Would later be part of Duke's 2010 national championship team and have an 8-year NBA career.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Basketball Operations",
        location: "New York, NY",
        statusNote:
          "After winning the 2010 NCAA title, Thomas went undrafted but built an 8-year NBA career with New Orleans, OKC, and most notably the New York Knicks, where he was named co-captain in 2017-18. Has since transitioned into a basketball operations and finance role in the New York area.",
        sourceUrl: "https://en.wikipedia.org/wiki/Lance_Thomas",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 42,
        position: "Power Forward",
        yearsAtSchool: "2006-2010",
        statsNote: "Sophomore • 5.0 PPG, 4.4 RPG",
        gamesPlayed: 34,
        pointsPerGame: 5.0,
        reboundsPerGame: 4.4,
        assistsPerGame: 0.5,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2007-08", yearLabel: "2007-08 (Sophomore)", sortOrder: 202, gamesPlayed: 34, pointsPerGame: 5.0, reboundsPerGame: 4.4, assistsPerGame: 0.5 },
      ],
      careerEvents: [
        { year: 2010, title: "Won NCAA National Championship with Duke", eventType: "CHAMPIONSHIP" },
        { year: 2017, title: "Named co-captain of the New York Knicks", eventType: "CAREER" },
      ],
    },
    {
      slug: "brian-zoubek",
      firstName: "Brian",
      lastName: "Zoubek",
      birthYear: 1988,
      hometown: "Haddonfield, NJ",
      highSchool: "Haddonfield Memorial High School, Haddonfield, NJ",
      isFeatured: false,
      bio: "Sophomore center who battled foot injuries that limited his playing time. Would later grab the famous final rebound in the 2010 national championship game.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Founder",
        currentEmployer: "Zoubek Properties",
        location: "Haddonfield, NJ",
        statusNote:
          "Famously grabbed the final rebound of the 2010 NCAA title game, sealing Duke's 61-59 win over Butler. Went undrafted, briefly with the Nets. Opened Dream Puffz cream puff bakery in 2012, then pivoted to real estate. Now runs Zoubek Properties in the Haddonfield, NJ area.",
        sourceUrl: "https://en.wikipedia.org/wiki/Brian_Zoubek",
        linkedInUrl: "https://www.linkedin.com/in/brianzoubek/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 55,
        position: "Center",
        yearsAtSchool: "2006-2010",
        statsNote: "Sophomore • 1.9 PPG, 2.3 RPG",
        gamesPlayed: 19,
        pointsPerGame: 1.9,
        reboundsPerGame: 2.3,
        assistsPerGame: 0.1,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2007-08", yearLabel: "2007-08 (Sophomore)", sortOrder: 202, gamesPlayed: 19, pointsPerGame: 1.9, reboundsPerGame: 2.3, assistsPerGame: 0.1 },
      ],
      careerEvents: [
        { year: 2010, title: "Won NCAA Championship (grabbed final rebound vs Butler)", eventType: "CHAMPIONSHIP" },
        { year: 2013, title: "Founded Zoubek Properties (real estate)", eventType: "CAREER" },
      ],
    },
    {
      slug: "dave-mcclure",
      firstName: "Dave",
      lastName: "McClure",
      birthYear: 1986,
      hometown: "Carmel, NY",
      highSchool: "Carmel High School, Carmel, NY",
      isFeatured: false,
      bio: "Junior forward who provided depth, defense, and hustle plays off the bench. Now an NBA assistant coach with the Memphis Grizzlies.",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Coach",
        currentEmployer: "Memphis Grizzlies",
        league: "NBA",
        location: "Memphis, TN",
        statusNote:
          "After his Duke playing career ended in 2009, McClure transitioned into coaching. He worked his way up through the college and NBA ranks and has served as an assistant coach with the Memphis Grizzlies, contributing to player development and bench operations.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 14,
        position: "Forward",
        yearsAtSchool: "2005-2009",
        statsNote: "Junior • 3.6 PPG, 3.2 RPG",
        gamesPlayed: 33,
        pointsPerGame: 3.6,
        reboundsPerGame: 3.2,
        assistsPerGame: 0.9,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2007-08", yearLabel: "2007-08 (Junior)", sortOrder: 203, gamesPlayed: 33, pointsPerGame: 3.6, reboundsPerGame: 3.2, assistsPerGame: 0.9 },
      ],
      careerEvents: [
        { year: 2010, title: "Began coaching career after graduation from Duke", eventType: "CAREER" },
      ],
    },
    {
      slug: "taylor-king",
      firstName: "Taylor",
      lastName: "King",
      birthYear: 1989,
      hometown: "Huntington Beach, CA",
      highSchool: "Mater Dei High School, Santa Ana, CA",
      isFeatured: false,
      bio: "McDonald's All-American freshman scorer who averaged 4.6 PPG in limited minutes. Transferred to Villanova after one season at Duke.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "California",
        statusNote:
          "Transferred from Duke to Villanova after his freshman year, then later transferred again to Concordia. He played professionally in various overseas leagues for several seasons before retiring. Has remained involved in basketball training and youth development.",
        sourceUrl: "https://en.wikipedia.org/wiki/Taylor_King_(basketball)",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 34,
        position: "Forward",
        yearsAtSchool: "2007-2008",
        statsNote: "Freshman • 4.6 PPG • Transferred to Villanova",
        gamesPlayed: 33,
        pointsPerGame: 4.6,
        reboundsPerGame: 1.9,
        assistsPerGame: 0.3,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Mater Dei High School", season: "Senior", yearLabel: "Senior (McDonald's All-American)", sortOrder: 1, pointsPerGame: 24.0, reboundsPerGame: 8.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2007-08", yearLabel: "2007-08 (Freshman)", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 4.6, reboundsPerGame: 1.9 },
      ],
      careerEvents: [
        { year: 2008, title: "Transferred from Duke to Villanova", eventType: "CAREER" },
      ],
    },
    {
      slug: "olek-czyz",
      firstName: "Olek",
      lastName: "Czyz",
      birthYear: 1989,
      hometown: "Reno, NV",
      highSchool: "Reno High School, Reno, NV",
      isFeatured: false,
      bio: "Polish-born freshman forward who saw limited minutes at Duke before transferring to Nevada. Returned to play professionally in his native Poland.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "Poland",
        statusNote:
          "Transferred from Duke to Nevada after the 2007-08 season, where he became a starter for the Wolf Pack. After college he played professionally in Poland for several seasons before transitioning out of basketball.",
        sourceUrl: "https://en.wikipedia.org/wiki/Olek_Czyz",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 45,
        position: "Forward",
        yearsAtSchool: "2007-2008",
        statsNote: "Freshman • Limited minutes • Transferred to Nevada",
        gamesPlayed: 17,
        pointsPerGame: 1.2,
        reboundsPerGame: 0.9,
        assistsPerGame: 0.1,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2007-08", yearLabel: "2007-08 (Freshman)", sortOrder: 201, gamesPlayed: 17, pointsPerGame: 1.2, reboundsPerGame: 0.9 },
      ],
      careerEvents: [
        { year: 2008, title: "Transferred from Duke to Nevada", eventType: "CAREER" },
      ],
    },
    {
      slug: "jordan-davidson",
      firstName: "Jordan",
      lastName: "Davidson",
      birthYear: 1987,
      hometown: "Atlanta, GA",
      highSchool: "Westminster Schools, Atlanta, GA",
      isFeatured: false,
      bio: "Walk-on guard who provided depth and practice value for the team during his Duke career.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Citizen",
        location: "United States",
        statusNote: "Walk-on guard who graduated from Duke. Like many Duke walk-ons, transitioned to a professional career after graduation. Limited public information available.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 12,
        position: "Guard",
        yearsAtSchool: "2005-2009",
        statsNote: "Walk-on guard",
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2007-08", yearLabel: "2007-08 (Walk-on)", sortOrder: 203, gamesPlayed: 6, pointsPerGame: 0.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "steve-johnson-duke",
      firstName: "Steve",
      lastName: "Johnson",
      birthYear: 1987,
      hometown: "Durham, NC",
      highSchool: "Riverside High School, Durham, NC",
      isFeatured: false,
      bio: "Walk-on guard who provided practice depth for the Duke roster during his career.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Citizen",
        location: "United States",
        statusNote: "Walk-on guard at Duke who graduated and pursued a professional career after college. Limited public information available beyond his time on the Duke roster.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 33,
        position: "Guard",
        yearsAtSchool: "2007-2009",
        statsNote: "Walk-on guard",
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2007-08", yearLabel: "2007-08 (Walk-on)", sortOrder: 201, gamesPlayed: 4, pointsPerGame: 0.3 },
      ],
      careerEvents: [],
    },
    {
      slug: "mike-krzyzewski",
      firstName: "Mike",
      lastName: "Krzyzewski",
      birthYear: 1947,
      hometown: "Chicago, IL",
      highSchool: "Weber High School, Chicago, IL",
      isFeatured: true,
      bio: "Guided Duke to a 28-6 record, an ACC Tournament championship, and a #2 seed in the NCAA Tournament before an early exit to West Virginia in the second round.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Special Advisor / Duke Ambassador",
        currentEmployer: "Duke University",
        location: "Durham, NC",
        statusNote: "Retired after the 2021-22 season as the winningest coach in Division I men's basketball history with 1,202 victories across 47 seasons. Won five national championships, reached 13 Final Fours, and won three Olympic gold medals as Team USA head coach.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Krzyzewski",
      },
      membership: {
        role: "HEAD_COACH",
        position: "Head Coach",
        yearsAtSchool: "1980-2022",
        statsNote: "28-6 • ACC Tournament Champions • NCAA 2nd Round",
      },
      careerEvents: [
        { year: 2008, title: "Won ACC Tournament Championship", eventType: "CHAMPIONSHIP" },
        { year: 2022, title: "Retired as winningest coach in D-I history", eventType: "RETIREMENT" },
      ],
    },
  ],
};
