import type { TeamSeed } from "./types";

export const dukeBasketball2022: TeamSeed = {
  slug: "duke-basketball-2022",
  name: "Duke Blue Devils",
  season: "2021-2022",
  sport: "Basketball",
  school: "Duke University",
  conference: "ACC",
  accomplishment: "32-7, Final Four (Coach K's Final Season)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  mascotName: "Blue Devil",
  people: [
    {
      slug: "paolo-banchero",
      firstName: "Paolo",
      lastName: "Banchero",
      birthYear: 2002,
      hometown: "Seattle, WA",
      highSchool: "O'Dea High School, Seattle, WA",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1631094.png",
      bio: "The #1 overall pick in 2022. Banchero was a dominant freshman who averaged 17.2 PPG with 7.8 RPG, leading Duke to the Final Four in Coach K's farewell season. Named Most Outstanding Player of the East Regional.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Power Forward",
        currentEmployer: "Orlando Magic",
        league: "NBA",
        location: "Orlando, FL",
        statusNote: "Selected #1 overall by the Orlando Magic in the 2022 NBA Draft. Won Rookie of the Year after averaging 20.0 PPG, 6.9 RPG, and 3.7 APG. Named to his first All-Star team in 2024-25, averaging 27.0 PPG and leading the Magic to the playoffs. Signed a 5-year, $224 million max extension in 2025.",
        sourceUrl: "https://en.wikipedia.org/wiki/Paolo_Banchero",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Power Forward", yearsAtSchool: "2021-2022", statsNote: "17.2 PPG, 7.8 RPG · #1 pick · East Region MOP · All-ACC First Team", gamesPlayed: 39, pointsPerGame: 17.2, reboundsPerGame: 7.8, assistsPerGame: 3.2 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "O'Dea High School", season: "2020-21", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 22.6, reboundsPerGame: 11.0, assistsPerGame: 3.7 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2021-22", yearLabel: "2021-22", sortOrder: 201, gamesPlayed: 39, minutesPerGame: 33.1, pointsPerGame: 17.2, reboundsPerGame: 7.8, assistsPerGame: 3.2, stealsPerGame: 1.1, blocksPerGame: 0.9, fieldGoalPct: 0.478, threePointPct: 0.337, freeThrowPct: 0.726 },
        { level: "PROFESSIONAL", teamName: "Orlando Magic", season: "2022-23", yearLabel: "2022-23 (ROY)", sortOrder: 301, gamesPlayed: 72, minutesPerGame: 34.8, pointsPerGame: 20.0, reboundsPerGame: 6.9, assistsPerGame: 3.7, fieldGoalPct: 0.459, threePointPct: 0.298, freeThrowPct: 0.738 },
        { level: "PROFESSIONAL", teamName: "Orlando Magic", season: "2023-24", yearLabel: "2023-24", sortOrder: 302, gamesPlayed: 80, minutesPerGame: 34.5, pointsPerGame: 22.6, reboundsPerGame: 6.9, assistsPerGame: 5.4, fieldGoalPct: 0.455, threePointPct: 0.336, freeThrowPct: 0.728 },
        { level: "PROFESSIONAL", teamName: "Orlando Magic", season: "2024-25", yearLabel: "2024-25 (All-Star)", sortOrder: 303, gamesPlayed: 65, minutesPerGame: 36.0, pointsPerGame: 27.0, reboundsPerGame: 8.5, assistsPerGame: 5.8, fieldGoalPct: 0.470, threePointPct: 0.350, freeThrowPct: 0.750 },
      ],
      careerEvents: [
        { year: 2022, title: "Selected #1 overall by Orlando Magic", eventType: "DRAFT" },
        { year: 2023, title: "Won NBA Rookie of the Year", eventType: "AWARD" },
        { year: 2025, title: "Named to first NBA All-Star team", eventType: "AWARD" },
        { year: 2025, title: "Signed 5-year, $224M max extension", eventType: "CONTRACT" },
      ],
    },
    {
      slug: "mark-williams",
      firstName: "Mark",
      lastName: "Williams",
      birthYear: 2001,
      hometown: "Norfolk, VA",
      highSchool: "IMG Academy, Bradenton, FL",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1631110.png",
      bio: "Sophomore center who had a breakout season, averaging 11.2 PPG, 7.4 RPG, and a team-high 2.8 BPG. His shot-blocking ability was crucial to Duke's Final Four run.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "Charlotte Hornets",
        league: "NBA",
        location: "Charlotte, NC",
        statusNote: "Selected #15 overall by the Charlotte Hornets in 2022. Showed great promise in his second season (2023-24) averaging 12.0 PPG and 7.2 RPG with 1.4 BPG before a foot injury. Entering his 4th NBA season with Charlotte.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mark_Williams_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Center", yearsAtSchool: "2020-2022", statsNote: "11.2 PPG, 7.4 RPG, 2.8 BPG · ACC DPOY · #15 pick", gamesPlayed: 37, pointsPerGame: 11.2, reboundsPerGame: 7.4, assistsPerGame: 0.7 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "IMG Academy", season: "2019-20", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 15.5, reboundsPerGame: 10.8, blocksPerGame: 4.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2020-21", yearLabel: "2020-21", sortOrder: 201, gamesPlayed: 25, minutesPerGame: 11.2, pointsPerGame: 2.5, reboundsPerGame: 2.5, blocksPerGame: 1.2, fieldGoalPct: 0.636 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2021-22", yearLabel: "2021-22", sortOrder: 202, gamesPlayed: 37, minutesPerGame: 24.7, pointsPerGame: 11.2, reboundsPerGame: 7.4, blocksPerGame: 2.8, fieldGoalPct: 0.728, freeThrowPct: 0.726 },
        { level: "PROFESSIONAL", teamName: "Charlotte Hornets", season: "2022-23", yearLabel: "2022-23 (Rookie)", sortOrder: 301, gamesPlayed: 43, minutesPerGame: 17.0, pointsPerGame: 7.0, reboundsPerGame: 5.5, blocksPerGame: 1.1, fieldGoalPct: 0.624 },
        { level: "PROFESSIONAL", teamName: "Charlotte Hornets", season: "2023-24", yearLabel: "2023-24", sortOrder: 302, gamesPlayed: 25, minutesPerGame: 26.8, pointsPerGame: 12.0, reboundsPerGame: 7.2, blocksPerGame: 1.4, fieldGoalPct: 0.580, freeThrowPct: 0.700 },
      ],
      careerEvents: [
        { year: 2022, title: "Selected #15 overall by Charlotte Hornets", eventType: "DRAFT" },
      ],
    },
    {
      slug: "aj-griffin",
      firstName: "AJ",
      lastName: "Griffin",
      birthYear: 2003,
      hometown: "Ossining, NY",
      highSchool: "Archbishop Stepinac, White Plains, NY",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1631100.png",
      bio: "Freshman sharpshooter who overcame two torn ACLs in high school to become one of college basketball's best three-point shooters at 44.7%. Son of former NBA player Adrian Griffin.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NBA Player",
        location: "New York",
        statusNote: "Selected #16 overall by the Atlanta Hawks in 2022. Played two NBA seasons before surprisingly retiring in September 2024 at age 21, citing personal reasons and a desire to pursue other interests. His retirement shocked the NBA world given his talent and age. One of the youngest voluntary retirements in NBA history.",
        sourceUrl: "https://en.wikipedia.org/wiki/AJ_Griffin",
      },
      membership: { role: "PLAYER", jerseyNumber: 21, position: "Shooting Guard / Small Forward", yearsAtSchool: "2021-2022", statsNote: "10.4 PPG · 44.7% from 3PT · Overcame 2 torn ACLs · #16 pick", gamesPlayed: 39, pointsPerGame: 10.4, reboundsPerGame: 3.9, assistsPerGame: 1.0 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2021-22", yearLabel: "2021-22", sortOrder: 201, gamesPlayed: 39, minutesPerGame: 22.9, pointsPerGame: 10.4, reboundsPerGame: 3.9, assistsPerGame: 1.0, fieldGoalPct: 0.496, threePointPct: 0.447, freeThrowPct: 0.793 },
        { level: "PROFESSIONAL", teamName: "Atlanta Hawks", season: "2022-23", yearLabel: "2022-23 (Rookie)", sortOrder: 301, gamesPlayed: 64, minutesPerGame: 13.0, pointsPerGame: 5.2, reboundsPerGame: 1.6, assistsPerGame: 0.6, fieldGoalPct: 0.438, threePointPct: 0.381, freeThrowPct: 0.810 },
        { level: "PROFESSIONAL", teamName: "Atlanta Hawks", season: "2023-24", yearLabel: "2023-24", sortOrder: 302, gamesPlayed: 20, minutesPerGame: 7.5, pointsPerGame: 2.5, reboundsPerGame: 0.8, fieldGoalPct: 0.380, threePointPct: 0.320 },
      ],
      careerEvents: [
        { year: 2022, title: "Selected #16 overall by Atlanta Hawks", eventType: "DRAFT" },
        { year: 2024, title: "Retired from NBA at age 21", eventType: "RETIREMENT", detail: "Cited personal reasons; one of youngest voluntary retirements in NBA history" },
      ],
    },
    {
      slug: "wendell-moore-jr",
      firstName: "Wendell",
      lastName: "Moore Jr.",
      birthYear: 2001,
      hometown: "Concord, NC",
      highSchool: "Cox Mill High School, Concord, NC",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1631112.png",
      bio: "Junior wing who had a breakout season averaging 13.4 PPG and 4.4 APG. Named first-team All-ACC and was crucial to Duke's balanced attack.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard / Forward",
        league: "NBA / G-League",
        statusNote: "Selected #26 overall by the Dallas Mavericks (traded to Minnesota) in 2022. Has bounced between the NBA and G-League, playing for Minnesota and Detroit. Working to establish himself as an NBA rotation player.",
        sourceUrl: "https://en.wikipedia.org/wiki/Wendell_Moore_Jr.",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Small Forward", yearsAtSchool: "2019-2022", statsNote: "13.4 PPG, 5.3 RPG, 4.4 APG · 1st-team All-ACC · #26 pick", gamesPlayed: 39, pointsPerGame: 13.4, reboundsPerGame: 5.3, assistsPerGame: 4.4 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Cox Mill High School", season: "2018-19", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 24.5, reboundsPerGame: 7.2, assistsPerGame: 4.8 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2019-20", yearLabel: "2019-20", sortOrder: 201, gamesPlayed: 29, minutesPerGame: 19.3, pointsPerGame: 5.2, reboundsPerGame: 3.2, assistsPerGame: 1.4, fieldGoalPct: 0.409, threePointPct: 0.287 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2020-21", yearLabel: "2020-21", sortOrder: 202, gamesPlayed: 25, minutesPerGame: 24.2, pointsPerGame: 8.0, reboundsPerGame: 4.0, assistsPerGame: 2.3, fieldGoalPct: 0.398, threePointPct: 0.302 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2021-22", yearLabel: "2021-22 (All-ACC)", sortOrder: 203, gamesPlayed: 39, minutesPerGame: 32.3, pointsPerGame: 13.4, reboundsPerGame: 5.3, assistsPerGame: 4.4, stealsPerGame: 1.4, fieldGoalPct: 0.492, threePointPct: 0.414, freeThrowPct: 0.784 },
        { level: "PROFESSIONAL", teamName: "Minnesota Timberwolves", season: "2022-23", yearLabel: "2022-23 (Rookie)", sortOrder: 301, gamesPlayed: 30, minutesPerGame: 7.5, pointsPerGame: 2.0, reboundsPerGame: 1.2, assistsPerGame: 0.8, fieldGoalPct: 0.368 },
      ],
      careerEvents: [
        { year: 2022, title: "Selected #26 overall by Dallas (traded to Minnesota)", eventType: "DRAFT" },
      ],
    },
    {
      slug: "trevor-keels",
      firstName: "Trevor",
      lastName: "Keels",
      birthYear: 2003,
      hometown: "Lutz, FL",
      highSchool: "Paul VI Catholic High School, Chantilly, VA",
      bio: "Freshman guard who started all 39 games and was the team's most reliable perimeter defender. Averaged 11.5 PPG and was a key contributor in the NCAA Tournament.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        league: "NBA / G-League",
        statusNote: "Selected #42 overall by the New York Knicks in the 2022 Draft. Has split time between the Knicks and their G-League affiliate, the Westchester Knicks. Working to carve out a rotation role in the NBA.",
        sourceUrl: "https://en.wikipedia.org/wiki/Trevor_Keels",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Guard", yearsAtSchool: "2021-2022", statsNote: "11.5 PPG · Started all 39 games · Physical perimeter defender", gamesPlayed: 39, pointsPerGame: 11.5, reboundsPerGame: 3.4, assistsPerGame: 2.7 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Paul VI Catholic High School", season: "2020-21", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 22.0, reboundsPerGame: 5.5, assistsPerGame: 4.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2021-22", yearLabel: "2021-22", sortOrder: 201, gamesPlayed: 39, minutesPerGame: 28.8, pointsPerGame: 11.5, reboundsPerGame: 3.4, assistsPerGame: 2.7, stealsPerGame: 1.1, fieldGoalPct: 0.434, threePointPct: 0.315, freeThrowPct: 0.723 },
        { level: "PROFESSIONAL", teamName: "New York Knicks", season: "2022-23", yearLabel: "2022-23 (Rookie)", sortOrder: 301, gamesPlayed: 15, minutesPerGame: 5.0, pointsPerGame: 1.5, reboundsPerGame: 0.8, fieldGoalPct: 0.350 },
      ],
      careerEvents: [
        { year: 2022, title: "Selected #42 overall by New York Knicks", eventType: "DRAFT" },
      ],
    },
    {
      slug: "jeremy-roach",
      firstName: "Jeremy",
      lastName: "Roach",
      birthYear: 2002,
      hometown: "Leesburg, VA",
      highSchool: "Paul VI Catholic High School, Chantilly, VA",
      bio: "Sophomore point guard who was the steady hand guiding Duke's offense. Had a huge NCAA Tournament run, averaging 15.5 PPG in the Final Four and hit clutch shots throughout March.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        league: "NBA / G-League",
        statusNote: "Stayed at Duke through 2023-24 (senior year), then signed as an undrafted free agent. Known for his big-game performances — he averaged 15.5 PPG in the 2022 Final Four and was Duke's most experienced guard for four seasons under two head coaches.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jeremy_Roach",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Point Guard", yearsAtSchool: "2020-2024", statsNote: "8.6 PPG, 3.2 APG · Clutch NCAA Tournament performer · Hit big shots in Final Four", gamesPlayed: 39, pointsPerGame: 8.6, reboundsPerGame: 2.6, assistsPerGame: 3.2 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Paul VI Catholic High School", season: "2019-20", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 18.5, reboundsPerGame: 4.0, assistsPerGame: 5.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2020-21", yearLabel: "2020-21", sortOrder: 201, gamesPlayed: 24, minutesPerGame: 26.2, pointsPerGame: 8.7, reboundsPerGame: 1.8, assistsPerGame: 3.3, fieldGoalPct: 0.410, threePointPct: 0.347 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2021-22", yearLabel: "2021-22", sortOrder: 202, gamesPlayed: 39, minutesPerGame: 28.7, pointsPerGame: 8.6, reboundsPerGame: 2.6, assistsPerGame: 3.2, stealsPerGame: 0.9, fieldGoalPct: 0.421, threePointPct: 0.329, freeThrowPct: 0.726 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2022-23", yearLabel: "2022-23", sortOrder: 203, gamesPlayed: 36, minutesPerGame: 31.5, pointsPerGame: 13.2, reboundsPerGame: 3.2, assistsPerGame: 4.8, fieldGoalPct: 0.435, threePointPct: 0.370 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2023-24", yearLabel: "2023-24 (Senior)", sortOrder: 204, gamesPlayed: 36, minutesPerGame: 32.0, pointsPerGame: 13.5, reboundsPerGame: 2.8, assistsPerGame: 4.5, fieldGoalPct: 0.440, threePointPct: 0.360 },
      ],
      careerEvents: [
        { year: 2024, title: "Signed as undrafted free agent", eventType: "SIGNING" },
      ],
    },
    {
      slug: "theo-john",
      firstName: "Theo",
      lastName: "John",
      birthYear: 1999,
      hometown: "Minneapolis, MN",
      highSchool: "DeLaSalle High School, Minneapolis, MN",
      bio: "Graduate transfer center from Marquette who provided veteran presence and shot-blocking depth. Started 20 games as the backup big behind Mark Williams.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Citizen",
        location: "Minnesota",
        statusNote: "After his graduate year at Duke, John went undrafted in 2022. Had brief G-League stints but has transitioned away from professional basketball. He played four seasons at Marquette before his final year at Duke.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/theo-john/14903",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Center", yearsAtSchool: "2021-2022", statsNote: "3.4 PPG, 3.1 RPG · Graduate transfer from Marquette · Veteran presence" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2021-22", yearLabel: "2021-22", sortOrder: 205, gamesPlayed: 39, minutesPerGame: 10.3, pointsPerGame: 3.4, reboundsPerGame: 3.1, blocksPerGame: 0.7, fieldGoalPct: 0.609 },
      ],
      careerEvents: [],
    },
    {
      slug: "mike-krzyzewski",
      firstName: "Mike",
      lastName: "Krzyzewski",
      birthYear: 1947,
      hometown: "Chicago, IL",
      highSchool: "Weber High School, Chicago, IL",
      bio: "Legendary head coach in his final season (42nd year) at Duke. Led the team to the Final Four before falling to rival North Carolina in an emotional semifinal.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Retired Head Coach",
        currentEmployer: "Duke University (Emeritus)",
        location: "Durham, NC",
        statusNote: "Retired after the 2021-22 season with a career record of 1,202-368 (.766). Five-time national champion. His final game was a 81-77 loss to North Carolina in the 2022 Final Four — the first-ever NCAA Tournament meeting between the two rivals. Inducted into numerous halls of fame.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Krzyzewski",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "1980-2022", statsNote: "FINAL SEASON · 32-7 · Final Four · 1,202-368 career" },
      seasonStats: [
        { level: "COACHING", teamName: "Duke Blue Devils", season: "2021-22", yearLabel: "2021-22 (Final Season)", sortOrder: 1, wins: 32, losses: 7, tournamentResult: "Final Four (lost to UNC 81-77 in Coach K's final game)" },
      ],
      careerEvents: [
        { year: 2022, title: "Final game: lost to UNC 81-77 in Final Four", eventType: "MILESTONE" },
        { year: 2022, title: "Retired from coaching after 42 seasons at Duke", eventType: "RETIREMENT" },
      ],
    },
  ],
};
