import type { TeamSeed } from "./types";

export const dukeBasketball2025: TeamSeed = {
  slug: "duke-basketball-2025",
  name: "Duke Blue Devils",
  season: "2024-2025",
  sport: "Men's Basketball",
  school: "Duke University",
  conference: "ACC",
  accomplishment: "33-5, ACC Champions, Final Four",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  mascotName: "Blue Devil",
  people: [
    {
      slug: "cooper-flagg",
      firstName: "Cooper",
      lastName: "Flagg",
      birthYear: 2006,
      hometown: "Newport, ME",
      highSchool: "Montverde Academy, Montverde, FL",
      isFeatured: true,
      imageUrl: "https://a.espncdn.com/combiner/i?img=/i/headshots/mens-college-basketball/players/full/5105961.png",
      bio: "The consensus #1 recruit in the 2024 class and projected #1 overall pick in the 2025 NBA Draft. Flagg averaged 20.2 PPG, 8.5 RPG, and 4.0 APG as a freshman, winning ACC Player of the Year and leading Duke to the Final Four. The most hyped freshman since Zion Williamson.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player / Projected #1 Pick",
        currentEmployer: "Duke University",
        league: "ACC",
        location: "Durham, NC",
        statusNote: "Projected to be the #1 overall pick in the 2025 NBA Draft. Won ACC Player of the Year, ACC Rookie of the Year, ACC Defensive Player of the Year, and consensus National Player of the Year as a freshman. Led Duke to a 33-5 record and the Final Four. From tiny Newport, Maine — population 3,210 — Flagg is the first Maine-born player ever projected #1.",
        sourceUrl: "https://en.wikipedia.org/wiki/Cooper_Flagg",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Power Forward", yearsAtSchool: "2024-2025", statsNote: "20.2 PPG, 8.5 RPG, 4.0 APG · NPOY · ACC POY · ACC ROY · ACC DPOY", gamesPlayed: 38, pointsPerGame: 20.2, reboundsPerGame: 8.5, assistsPerGame: 4.0 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Montverde Academy", season: "2023-24", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 16.5, reboundsPerGame: 7.5, assistsPerGame: 3.5, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2024-25", yearLabel: "2024-25 (NPOY)", sortOrder: 201, gamesPlayed: 38, minutesPerGame: 34.5, pointsPerGame: 20.2, reboundsPerGame: 8.5, assistsPerGame: 4.0, stealsPerGame: 1.5, blocksPerGame: 1.5, fieldGoalPct: 0.475, threePointPct: 0.340, freeThrowPct: 0.750 },
      ],
      careerEvents: [
        { year: 2025, title: "Won ACC Player of the Year as a freshman", eventType: "AWARD" },
        { year: 2025, title: "Won consensus National Player of the Year", eventType: "AWARD" },
      ],
    },
    {
      slug: "kon-knueppel",
      firstName: "Kon",
      lastName: "Knueppel",
      birthYear: 2005,
      hometown: "Milwaukee, WI",
      highSchool: "Wisconsin Lutheran High School, Milwaukee, WI",
      isFeatured: true,
      bio: "Freshman wing who was Duke's second-leading scorer at 14.5 PPG with elite shooting. A projected lottery pick in the 2025 NBA Draft.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Duke University",
        league: "ACC",
        location: "Durham, NC",
        statusNote: "Wisconsin Mr. Basketball who chose Duke over in-state Wisconsin. Averaged 14.5 PPG on 44% from three as a freshman. Projected as a mid-first-round pick in the 2025 NBA Draft due to his shooting, size (6'7\"), and basketball IQ.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kon_Knueppel",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Small Forward", yearsAtSchool: "2024-2025", statsNote: "14.5 PPG · 44% from three · Projected lottery pick", gamesPlayed: 38, pointsPerGame: 14.5, reboundsPerGame: 4.2, assistsPerGame: 2.8 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Wisconsin Lutheran High School", season: "2023-24", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 25.8, reboundsPerGame: 6.5, assistsPerGame: 4.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2024-25", yearLabel: "2024-25", sortOrder: 201, gamesPlayed: 38, minutesPerGame: 32.0, pointsPerGame: 14.5, reboundsPerGame: 4.2, assistsPerGame: 2.8, fieldGoalPct: 0.465, threePointPct: 0.440, freeThrowPct: 0.860 },
      ],
      careerEvents: [],
    },
    {
      slug: "tyrese-proctor",
      firstName: "Tyrese",
      lastName: "Proctor",
      birthYear: 2003,
      hometown: "Sydney, Australia",
      highSchool: "NBA Global Academy, Canberra, Australia",
      isFeatured: false,
      imageUrl: "https://a.espncdn.com/combiner/i?img=/i/headshots/mens-college-basketball/players/full/4896869.png",
      bio: "Australian junior point guard who served as the team's floor general. Third-year starter who improved his shooting significantly as a junior.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Duke University",
        league: "ACC",
        location: "Durham, NC",
        statusNote: "Three-year starter at Duke who has developed from a raw Australian prospect into one of the ACC's best point guards. Expected to be a 2025 NBA Draft pick after his junior season performance. Represented Australia at youth international competitions.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/tyrese-proctor/16429",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Point Guard", yearsAtSchool: "2022-2025", statsNote: "11.0 PPG, 5.5 APG · 3-year starter · Australian international" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2022-23", yearLabel: "2022-23", sortOrder: 201, gamesPlayed: 33, minutesPerGame: 22.5, pointsPerGame: 5.5, reboundsPerGame: 2.0, assistsPerGame: 3.0, fieldGoalPct: 0.375, threePointPct: 0.310 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2023-24", yearLabel: "2023-24", sortOrder: 202, gamesPlayed: 36, minutesPerGame: 30.5, pointsPerGame: 10.0, reboundsPerGame: 2.5, assistsPerGame: 4.2, fieldGoalPct: 0.420, threePointPct: 0.360 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2024-25", yearLabel: "2024-25", sortOrder: 203, gamesPlayed: 38, minutesPerGame: 32.5, pointsPerGame: 11.0, reboundsPerGame: 3.0, assistsPerGame: 5.5, stealsPerGame: 1.2, fieldGoalPct: 0.440, threePointPct: 0.380, freeThrowPct: 0.800 },
      ],
      careerEvents: [],
    },
    {
      slug: "isaiah-evans",
      firstName: "Isaiah",
      lastName: "Evans",
      birthYear: 2006,
      hometown: "Kernersville, NC",
      highSchool: "East Forsyth High School, Kernersville, NC",
      bio: "Five-star freshman wing who provided scoring punch off the bench. Shot 38% from three in his first college season.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Duke University",
        league: "ACC",
        location: "Durham, NC",
        statusNote: "North Carolina native and five-star recruit who chose Duke over UNC and Kentucky. Showed potential as a volume scorer off the bench in his freshman year. Expected to take on a larger role in future seasons.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/isaiah-evans/17853",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Shooting Guard / Small Forward", yearsAtSchool: "2024-2025", statsNote: "8.5 PPG off bench · 38% from three · 5-star freshman" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "East Forsyth High School", season: "2023-24", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 28.5, reboundsPerGame: 6.0, assistsPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2024-25", yearLabel: "2024-25", sortOrder: 201, gamesPlayed: 38, minutesPerGame: 18.5, pointsPerGame: 8.5, reboundsPerGame: 2.5, assistsPerGame: 1.0, fieldGoalPct: 0.430, threePointPct: 0.380, freeThrowPct: 0.780 },
      ],
      careerEvents: [],
    },
    {
      slug: "maliq-brown",
      firstName: "Maliq",
      lastName: "Brown",
      birthYear: 2003,
      hometown: "Methuen, MA",
      highSchool: "Brewster Academy, Wolfeboro, NH",
      bio: "Sophomore forward who transferred from Syracuse and became a key two-way player for Duke. His versatility and energy were critical to Duke's Final Four run.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Duke University",
        league: "ACC",
        location: "Durham, NC",
        statusNote: "Transferred from Syracuse after his freshman year and sat out 2023-24 per transfer rules. Emerged as a key contributor in 2024-25, playing heavy minutes with his defensive versatility and high-energy play style.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/maliq-brown/17250",
      },
      membership: { role: "PLAYER", jerseyNumber: 14, position: "Power Forward", yearsAtSchool: "2023-2025", statsNote: "8.0 PPG, 6.0 RPG · Syracuse transfer · Key two-way player" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Brewster Academy", season: "2021-22", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 14.0, reboundsPerGame: 8.0, blocksPerGame: 2.0 },
        { level: "COLLEGE", teamName: "Syracuse Orange", season: "2022-23", yearLabel: "2022-23", sortOrder: 201, gamesPlayed: 33, minutesPerGame: 20.0, pointsPerGame: 5.5, reboundsPerGame: 4.5, fieldGoalPct: 0.470 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2024-25", yearLabel: "2024-25", sortOrder: 203, gamesPlayed: 38, minutesPerGame: 25.0, pointsPerGame: 8.0, reboundsPerGame: 6.0, assistsPerGame: 1.5, stealsPerGame: 0.8, blocksPerGame: 1.0, fieldGoalPct: 0.520, freeThrowPct: 0.680 },
      ],
      careerEvents: [
        { year: 2023, title: "Transferred from Syracuse to Duke", eventType: "OTHER" },
      ],
    },
    {
      slug: "mason-gillis",
      firstName: "Mason",
      lastName: "Gillis",
      birthYear: 2001,
      hometown: "New Castle, IN",
      highSchool: "New Castle Chrysler High School, New Castle, IN",
      bio: "Graduate transfer from Purdue who brought veteran toughness and championship experience (2024 national runner-up with Purdue). Played a key role as a stretch-four.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "Graduate Student",
        currentEmployer: "Duke University",
        location: "Durham, NC",
        statusNote: "Played four seasons at Purdue, reaching the 2024 National Championship game (lost to UConn). Used his graduate transfer year at Duke in 2024-25, providing veteran leadership and outside shooting. His basketball career has concluded after the 2025 season.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/mason-gillis/17854",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Power Forward", yearsAtSchool: "2024-2025", statsNote: "6.5 PPG · Grad transfer from Purdue · Veteran leader" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Purdue Boilermakers", season: "2023-24", yearLabel: "2023-24 (National Runner-Up)", sortOrder: 204, gamesPlayed: 40, minutesPerGame: 19.0, pointsPerGame: 5.5, reboundsPerGame: 3.2, fieldGoalPct: 0.480, threePointPct: 0.380 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2024-25", yearLabel: "2024-25 (Grad Transfer)", sortOrder: 205, gamesPlayed: 38, minutesPerGame: 20.0, pointsPerGame: 6.5, reboundsPerGame: 3.5, fieldGoalPct: 0.450, threePointPct: 0.370 },
      ],
      careerEvents: [
        { year: 2024, title: "Reached National Championship Game with Purdue (lost to UConn)", eventType: "MILESTONE" },
        { year: 2024, title: "Transferred to Duke as graduate transfer", eventType: "OTHER" },
      ],
    },
    {
      slug: "sion-james",
      firstName: "Sion",
      lastName: "James",
      birthYear: 2004,
      hometown: "Houston, TX",
      highSchool: "Kinkaid School, Houston, TX",
      bio: "Sophomore guard who transferred from Clemson and became a key two-way contributor. His toughness and versatility were crucial to Duke's Final Four run.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Duke University",
        league: "ACC",
        location: "Durham, NC",
        statusNote: "Clemson transfer who found his role at Duke as a defensive-minded guard. Expected to return for his junior season.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/sion-james/17251",
      },
      membership: { role: "PLAYER", jerseyNumber: 10, position: "Guard", yearsAtSchool: "2023-present", statsNote: "7.5 PPG · Clemson transfer · Key two-way player" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Kinkaid School", season: "2021-22", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 18.5, reboundsPerGame: 5.0, assistsPerGame: 3.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2024-25", yearLabel: "2024-25", sortOrder: 202, gamesPlayed: 38, minutesPerGame: 22.0, pointsPerGame: 7.5, reboundsPerGame: 3.0, assistsPerGame: 2.0, stealsPerGame: 1.0, fieldGoalPct: 0.440, threePointPct: 0.350 },
      ],
      careerEvents: [],
    },
    {
      slug: "patrick-ngongba",
      firstName: "Patrick",
      lastName: "Ngongba II",
      birthYear: 2005,
      hometown: "Charlotte, NC",
      highSchool: "Link Year Prep, Branson, MO",
      bio: "Freshman center who provided rim protection and rebounding. At 6-11 and 250 lbs, he gave Duke size off the bench.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Duke University",
        league: "ACC",
        location: "Durham, NC",
        statusNote: "Freshman big man expected to take on a larger role in 2025-26 as Cooper Flagg and other players depart.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/patrick-ngongba-ii/17856",
      },
      membership: { role: "PLAYER", jerseyNumber: 22, position: "Center", yearsAtSchool: "2024-present", statsNote: "3.5 PPG, 3.0 RPG · Freshman center · 6-11 250 lbs" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Link Year Prep", season: "2023-24", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 14.0, reboundsPerGame: 9.5, blocksPerGame: 3.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2024-25", yearLabel: "2024-25", sortOrder: 201, gamesPlayed: 35, minutesPerGame: 12.0, pointsPerGame: 3.5, reboundsPerGame: 3.0, blocksPerGame: 0.8, fieldGoalPct: 0.550 },
      ],
      careerEvents: [],
    },
    {
      slug: "khaman-maluach",
      firstName: "Khaman",
      lastName: "Maluach",
      birthYear: 2006,
      hometown: "Juba, South Sudan",
      highSchool: "NBA Academy Africa / AZ Compass Prep",
      bio: "Freshman center from South Sudan who was the #2 recruit in the class. At 7-2 with a massive wingspan, his rim protection and shot-blocking were elite for a freshman.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Duke University",
        league: "ACC",
        location: "Durham, NC",
        statusNote: "Born in Juba, South Sudan and developed through the NBA Academy Africa. Projected as a lottery pick in the 2026 NBA Draft due to his size, mobility, and shot-blocking ability.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/khaman-maluach/17855",
      },
      membership: { role: "PLAYER", jerseyNumber: 35, position: "Center", yearsAtSchool: "2024-present", statsNote: "6.0 PPG, 5.5 RPG, 2.0 BPG · #2 recruit · 7-2 from South Sudan" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2024-25", yearLabel: "2024-25", sortOrder: 201, gamesPlayed: 38, minutesPerGame: 18.0, pointsPerGame: 6.0, reboundsPerGame: 5.5, blocksPerGame: 2.0, fieldGoalPct: 0.580, freeThrowPct: 0.600 },
      ],
      careerEvents: [],
    },
    {
      slug: "jon-scheyer",
      firstName: "Jon",
      lastName: "Scheyer",
      birthYear: 1987,
      hometown: "Northbrook, IL",
      highSchool: "Glenbrook North High School, Northbrook, IL",
      bio: "Third-year head coach who has continued Duke's tradition of excellence. Led the 2024-25 team to a 33-5 record and Final Four, building on the foundation Coach K established.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "Duke University",
        league: "ACC",
        location: "Durham, NC",
        statusNote: "Took over from Coach K in 2022. Named AP Coach of the Year finalist in 2024-25 after leading Duke to a 33-5 record. Former Duke player (2006-2010) who was a three-year starter and 2010 national champion. Known for his elite recruiting — has landed three #1 recruiting classes in three years.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jon_Scheyer",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2022-present", statsNote: "33-5 · ACC Champions · Final Four · 3rd season as HC" },
      seasonStats: [
        { level: "COACHING", teamName: "Duke Blue Devils", season: "2024-25", yearLabel: "2024-25", sortOrder: 1, wins: 33, losses: 5, tournamentResult: "ACC Champions, Final Four" },
      ],
      careerEvents: [
        { year: 2022, title: "Named head coach at Duke, succeeding Coach K", eventType: "COACHING" },
        { year: 2025, title: "Led Duke to Final Four in third season", eventType: "MILESTONE" },
      ],
    },
  ],
};
