import type { TeamSeed } from "./types";

export const dukeBasketball2017: TeamSeed = {
  slug: "duke-basketball-2017",
  name: "Duke Blue Devils",
  season: "2016-2017",
  sport: "Men's Basketball",
  school: "Duke University",
  conference: "ACC",
  accomplishment: "28-9, ACC Regular Season Champions, Second Round",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  mascotName: "Blue Devil",
  people: [
    {
      slug: "jayson-tatum",
      firstName: "Jayson",
      lastName: "Tatum",
      birthYear: 1998,
      hometown: "St. Louis, MO",
      highSchool: "Chaminade College Prep, St. Louis, MO",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628369.png",
      isFeatured: true,
      bio: "One of the most talented freshmen in Duke history, Tatum averaged 16.8 PPG and was named ACC Rookie of the Year. He became one of the NBA's best players and led the Boston Celtics to the 2024 championship.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Small Forward",
        currentEmployer: "Boston Celtics",
        league: "NBA",
        location: "Boston, MA",
        statusNote: "Selected #3 overall by the Boston Celtics in the 2017 Draft. Has become one of the NBA's elite players, making five All-Star teams and winning the 2024 NBA Championship as the team's best player. Won a gold medal at the 2024 Paris Olympics. Signed a 5-year, $314 million supermax extension in 2024 — the largest contract in NBA history at the time.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jayson_Tatum",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Small Forward", yearsAtSchool: "2016-2017", statsNote: "16.8 PPG, 7.3 RPG · ACC ROY · All-ACC · #3 overall pick", gamesPlayed: 33, pointsPerGame: 16.8, reboundsPerGame: 7.3, assistsPerGame: 2.0 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Chaminade College Prep", season: "2015-16", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 29.6, reboundsPerGame: 9.1, assistsPerGame: 3.1 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2016-17", yearLabel: "2016-17", sortOrder: 201, gamesPlayed: 33, minutesPerGame: 33.2, pointsPerGame: 16.8, reboundsPerGame: 7.3, assistsPerGame: 2.0, stealsPerGame: 1.1, blocksPerGame: 1.3, fieldGoalPct: 0.452, threePointPct: 0.342, freeThrowPct: 0.849 },
        { level: "PROFESSIONAL", teamName: "Boston Celtics", season: "2017-18", yearLabel: "2017-18 (Rookie)", sortOrder: 301, gamesPlayed: 80, minutesPerGame: 30.5, pointsPerGame: 13.9, reboundsPerGame: 5.0, assistsPerGame: 1.6, fieldGoalPct: 0.434, threePointPct: 0.343, freeThrowPct: 0.826 },
        { level: "PROFESSIONAL", teamName: "Boston Celtics", season: "2019-20", yearLabel: "2019-20 (All-Star)", sortOrder: 303, gamesPlayed: 66, minutesPerGame: 34.3, pointsPerGame: 23.4, reboundsPerGame: 7.0, assistsPerGame: 3.0, fieldGoalPct: 0.450, threePointPct: 0.403, freeThrowPct: 0.813 },
        { level: "PROFESSIONAL", teamName: "Boston Celtics", season: "2021-22", yearLabel: "2021-22 (1st Team All-NBA)", sortOrder: 305, gamesPlayed: 76, minutesPerGame: 35.9, pointsPerGame: 26.9, reboundsPerGame: 8.0, assistsPerGame: 4.4, fieldGoalPct: 0.453, threePointPct: 0.354, freeThrowPct: 0.853 },
        { level: "PROFESSIONAL", teamName: "Boston Celtics", season: "2022-23", yearLabel: "2022-23 (All-Star)", sortOrder: 306, gamesPlayed: 74, minutesPerGame: 36.9, pointsPerGame: 30.1, reboundsPerGame: 8.8, assistsPerGame: 4.6, fieldGoalPct: 0.466, threePointPct: 0.351, freeThrowPct: 0.856 },
        { level: "PROFESSIONAL", teamName: "Boston Celtics", season: "2023-24", yearLabel: "2023-24 (Champion)", sortOrder: 307, gamesPlayed: 74, minutesPerGame: 35.7, pointsPerGame: 26.9, reboundsPerGame: 8.1, assistsPerGame: 4.9, fieldGoalPct: 0.471, threePointPct: 0.376, freeThrowPct: 0.833 },
        { level: "PROFESSIONAL", teamName: "Boston Celtics", season: "2024-25", yearLabel: "2024-25", sortOrder: 308, gamesPlayed: 68, minutesPerGame: 36.2, pointsPerGame: 28.2, reboundsPerGame: 8.5, assistsPerGame: 5.0, fieldGoalPct: 0.465, threePointPct: 0.370, freeThrowPct: 0.850 },
      ],
      careerEvents: [
        { year: 2017, title: "Selected #3 overall by Boston Celtics", eventType: "DRAFT" },
        { year: 2024, title: "Won NBA Championship with Boston Celtics", eventType: "CHAMPIONSHIP" },
        { year: 2024, title: "Won Olympic gold medal in Paris", eventType: "CHAMPIONSHIP" },
        { year: 2024, title: "Signed 5-year, $314M supermax extension", eventType: "CONTRACT" },
      ],
    },
    {
      slug: "luke-kennard",
      firstName: "Luke",
      lastName: "Kennard",
      birthYear: 1996,
      hometown: "Franklin, OH",
      highSchool: "Franklin High School, Franklin, OH",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628379.png",
      isFeatured: true,
      bio: "Sophomore sharpshooter who led Duke in scoring at 19.5 PPG on 49.3% FG. His ability to score from all three levels made him one of college basketball's best offensive players.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Shooting Guard",
        currentEmployer: "Memphis Grizzlies",
        league: "NBA",
        location: "Memphis, TN",
        statusNote: "Selected #12 overall by the Detroit Pistons in 2017. Traded to the LA Clippers in 2020, where he led the NBA in three-point percentage at 44.9% in 2021-22. Signed a 4-year, $64M deal with Memphis in 2022. One of the NBA's elite shooters — career 44.1% from three.",
        sourceUrl: "https://en.wikipedia.org/wiki/Luke_Kennard",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Shooting Guard", yearsAtSchool: "2015-2017", statsNote: "19.5 PPG (led team) · 49.3% FG · All-ACC 1st Team · #12 pick", gamesPlayed: 37, pointsPerGame: 19.5, reboundsPerGame: 5.1, assistsPerGame: 2.5 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Franklin High School", season: "2014-15", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 28.8, reboundsPerGame: 5.5, assistsPerGame: 4.2 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2015-16", yearLabel: "2015-16", sortOrder: 201, gamesPlayed: 34, minutesPerGame: 24.6, pointsPerGame: 10.6, reboundsPerGame: 3.3, assistsPerGame: 1.9, fieldGoalPct: 0.468, threePointPct: 0.370, freeThrowPct: 0.805 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2016-17", yearLabel: "2016-17", sortOrder: 202, gamesPlayed: 37, minutesPerGame: 33.6, pointsPerGame: 19.5, reboundsPerGame: 5.1, assistsPerGame: 2.5, stealsPerGame: 0.9, fieldGoalPct: 0.493, threePointPct: 0.435, freeThrowPct: 0.855 },
        { level: "PROFESSIONAL", teamName: "Detroit Pistons", season: "2017-18", yearLabel: "2017-18 (Rookie)", sortOrder: 301, gamesPlayed: 73, minutesPerGame: 20.9, pointsPerGame: 7.1, reboundsPerGame: 1.6, assistsPerGame: 2.0, fieldGoalPct: 0.442, threePointPct: 0.378, freeThrowPct: 0.852 },
        { level: "PROFESSIONAL", teamName: "Detroit Pistons", season: "2019-20", yearLabel: "2019-20", sortOrder: 303, gamesPlayed: 28, minutesPerGame: 25.4, pointsPerGame: 15.8, reboundsPerGame: 3.5, assistsPerGame: 4.1, fieldGoalPct: 0.459, threePointPct: 0.402, freeThrowPct: 0.892 },
        { level: "PROFESSIONAL", teamName: "LA Clippers", season: "2021-22", yearLabel: "2021-22 (led NBA 3P%)", sortOrder: 305, gamesPlayed: 63, minutesPerGame: 19.0, pointsPerGame: 11.9, reboundsPerGame: 2.0, assistsPerGame: 2.4, fieldGoalPct: 0.479, threePointPct: 0.449, freeThrowPct: 0.902 },
        { level: "PROFESSIONAL", teamName: "Memphis Grizzlies", season: "2023-24", yearLabel: "2023-24", sortOrder: 307, gamesPlayed: 55, minutesPerGame: 18.5, pointsPerGame: 8.0, reboundsPerGame: 2.2, assistsPerGame: 2.5, fieldGoalPct: 0.440, threePointPct: 0.420, freeThrowPct: 0.890 },
      ],
      careerEvents: [
        { year: 2017, title: "Selected #12 overall by Detroit Pistons", eventType: "DRAFT" },
        { year: 2022, title: "Led NBA in 3-point percentage at 44.9%", eventType: "MILESTONE" },
        { year: 2022, title: "Signed 4-year, $64M deal with Memphis Grizzlies", eventType: "CONTRACT" },
      ],
    },
    {
      slug: "grayson-allen",
      firstName: "Grayson",
      lastName: "Allen",
      birthYear: 1995,
      hometown: "Jacksonville, FL",
      highSchool: "Providence School, Jacksonville, FL",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628960.png",
      isFeatured: false,
      bio: "Junior who averaged 14.5 PPG. One of the most talented and polarizing players in college basketball, Allen was known for his scoring ability and controversial on-court incidents.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Shooting Guard",
        currentEmployer: "Phoenix Suns",
        league: "NBA",
        location: "Phoenix, AZ",
        statusNote: "Selected #21 overall by Utah in 2018. Has played for the Jazz, Grizzlies, Bucks (2021 champion), and Suns. Shot 45.3% from three in the 2021 NBA Finals to help Milwaukee win it all. A valuable rotation player known for his shooting and toughness.",
        sourceUrl: "https://en.wikipedia.org/wiki/Grayson_Allen",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Shooting Guard", yearsAtSchool: "2014-2018", statsNote: "14.5 PPG · 2015 NCAA champion · Polarizing player" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2016-17", yearLabel: "2016-17", sortOrder: 203, gamesPlayed: 37, minutesPerGame: 31.2, pointsPerGame: 14.5, reboundsPerGame: 3.7, assistsPerGame: 3.5, stealsPerGame: 0.8, fieldGoalPct: 0.418, threePointPct: 0.321, freeThrowPct: 0.853 },
      ],
      careerEvents: [],
    },
    {
      slug: "amile-jefferson",
      firstName: "Amile",
      lastName: "Jefferson",
      birthYear: 1994,
      hometown: "Philadelphia, PA",
      highSchool: "Friends' Central School, Wynnewood, PA",
      bio: "Super-senior center who finally got his full healthy season in 2016-17 after a medical redshirt. Averaged 10.9 PPG and 8.4 RPG as the team's emotional leader.",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Coach",
        currentEmployer: "Boston Celtics",
        league: "NBA",
        location: "Boston, MA",
        statusNote: "After a brief NBA stint, Jefferson returned to Duke as Director of Player Development before joining the Boston Celtics as an assistant coach. Won an NBA championship ring as a Celtics assistant in 2024.",
        sourceUrl: "https://en.wikipedia.org/wiki/Amile_Jefferson",
      },
      membership: { role: "PLAYER", jerseyNumber: 21, position: "Power Forward", yearsAtSchool: "2013-2017", statsNote: "10.9 PPG, 8.4 RPG · Senior captain · Program-record 150 games", gamesPlayed: 35, pointsPerGame: 10.9, reboundsPerGame: 8.4, assistsPerGame: 1.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2016-17", yearLabel: "2016-17 (Senior)", sortOrder: 205, gamesPlayed: 35, minutesPerGame: 29.7, pointsPerGame: 10.9, reboundsPerGame: 8.4, assistsPerGame: 1.5, stealsPerGame: 0.7, blocksPerGame: 1.9, fieldGoalPct: 0.613, freeThrowPct: 0.629 },
      ],
      careerEvents: [],
    },
    {
      slug: "frank-jackson",
      firstName: "Frank",
      lastName: "Jackson",
      birthYear: 1998,
      hometown: "Washington, DC",
      highSchool: "Cannon School, Concord, NC",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628402.png",
      bio: "Dynamic freshman guard who averaged 10.9 PPG off the bench. His athleticism and scoring ability made him a projected first-round pick before a foot injury.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        league: "Overseas",
        statusNote: "Selected #31 overall by Charlotte (traded to New Orleans) in 2017. Played four NBA seasons with the Pelicans, Pistons, and Pacers, averaging around 8 PPG. Has continued playing professionally overseas. Career-best 10.9 PPG with Detroit in 2020-21.",
        sourceUrl: "https://en.wikipedia.org/wiki/Frank_Jackson_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Point Guard", yearsAtSchool: "2016-2017", statsNote: "10.9 PPG off bench · Explosive athlete · #31 pick", gamesPlayed: 35, pointsPerGame: 10.9, reboundsPerGame: 1.8, assistsPerGame: 1.5 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Cannon School", season: "2015-16", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 25.5, reboundsPerGame: 4.5, assistsPerGame: 5.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2016-17", yearLabel: "2016-17", sortOrder: 201, gamesPlayed: 35, minutesPerGame: 22.2, pointsPerGame: 10.9, reboundsPerGame: 1.8, assistsPerGame: 1.5, fieldGoalPct: 0.467, threePointPct: 0.359, freeThrowPct: 0.824 },
        { level: "PROFESSIONAL", teamName: "New Orleans Pelicans", season: "2018-19", yearLabel: "2018-19", sortOrder: 301, gamesPlayed: 61, minutesPerGame: 17.2, pointsPerGame: 8.4, reboundsPerGame: 1.5, assistsPerGame: 1.0, fieldGoalPct: 0.422, threePointPct: 0.347, freeThrowPct: 0.786 },
        { level: "PROFESSIONAL", teamName: "Detroit Pistons", season: "2020-21", yearLabel: "2020-21", sortOrder: 303, gamesPlayed: 41, minutesPerGame: 19.5, pointsPerGame: 10.9, reboundsPerGame: 2.1, assistsPerGame: 1.4, fieldGoalPct: 0.429, threePointPct: 0.373, freeThrowPct: 0.788 },
      ],
      careerEvents: [
        { year: 2017, title: "Selected #31 overall by Charlotte (traded to New Orleans)", eventType: "DRAFT" },
      ],
    },
    {
      slug: "harry-giles",
      firstName: "Harry",
      lastName: "Giles III",
      birthYear: 1998,
      hometown: "Winston-Salem, NC",
      highSchool: "Oak Hill Academy, Mouth of Wilson, VA",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628385.png",
      bio: "Once the #1 recruit in the country, Giles came to Duke after two ACL surgeries in high school. His limited Duke career (11.2 MPG) couldn't showcase his immense talent, but his potential kept him in the first round of the draft.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "North Carolina",
        statusNote: "Selected #20 overall by Portland (traded to Sacramento) in 2017. Played three NBA seasons with the Kings and Blazers, showing flashes of his immense talent when healthy. Career-best 7.0 PPG with Sacramento in 2019-20. His career was ultimately defined by the injuries that robbed him of his ceiling as a potential franchise player.",
        sourceUrl: "https://en.wikipedia.org/wiki/Harry_Giles_III",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Power Forward / Center", yearsAtSchool: "2016-2017", statsNote: "3.9 PPG, 3.8 RPG in limited minutes · 2 prior ACL tears · #20 pick", gamesPlayed: 26, pointsPerGame: 3.9, reboundsPerGame: 3.8, assistsPerGame: 0.5 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Oak Hill Academy", season: "2015-16", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 16.0, reboundsPerGame: 9.0, blocksPerGame: 3.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2016-17", yearLabel: "2016-17", sortOrder: 201, gamesPlayed: 26, minutesPerGame: 11.2, pointsPerGame: 3.9, reboundsPerGame: 3.8, assistsPerGame: 0.5, blocksPerGame: 0.6, fieldGoalPct: 0.552 },
        { level: "PROFESSIONAL", teamName: "Sacramento Kings", season: "2018-19", yearLabel: "2018-19", sortOrder: 301, gamesPlayed: 58, minutesPerGame: 14.3, pointsPerGame: 5.1, reboundsPerGame: 2.9, assistsPerGame: 1.2, fieldGoalPct: 0.466 },
        { level: "PROFESSIONAL", teamName: "Sacramento Kings", season: "2019-20", yearLabel: "2019-20", sortOrder: 302, gamesPlayed: 44, minutesPerGame: 19.3, pointsPerGame: 7.0, reboundsPerGame: 4.2, assistsPerGame: 1.6, fieldGoalPct: 0.497, freeThrowPct: 0.698 },
        { level: "PROFESSIONAL", teamName: "Portland Trail Blazers", season: "2020-21", yearLabel: "2020-21", sortOrder: 303, gamesPlayed: 38, minutesPerGame: 8.5, pointsPerGame: 3.2, reboundsPerGame: 2.1, assistsPerGame: 0.6, fieldGoalPct: 0.440 },
      ],
      careerEvents: [
        { year: 2017, title: "Selected #20 overall by Portland (traded to Sacramento)", eventType: "DRAFT" },
      ],
    },
    {
      slug: "matt-jones",
      firstName: "Matt",
      lastName: "Jones",
      birthYear: 1994,
      hometown: "Chatsworth, CA",
      highSchool: "DeSoto High School, DeSoto, TX",
      bio: "Senior guard who started 35 games and shot 38.0% from three. His defense and experience were crucial to Duke's ACC championship.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Business Development",
        currentEmployer: "Total Quality Logistics",
        location: "Chicago, IL",
        statusNote: "After going undrafted, Jones played in the G-League and overseas before transitioning to business. Now works at Total Quality Logistics in Chicago.",
        sourceUrl: "https://en.wikipedia.org/wiki/Matt_Jones_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 13, position: "Shooting Guard", yearsAtSchool: "2013-2017", statsNote: "7.0 PPG · Senior starter · Defensive specialist" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2016-17", yearLabel: "2016-17 (Senior)", sortOrder: 204, gamesPlayed: 37, minutesPerGame: 32.9, pointsPerGame: 7.0, reboundsPerGame: 2.8, assistsPerGame: 1.4, stealsPerGame: 1.7, fieldGoalPct: 0.387, threePointPct: 0.380 },
      ],
      careerEvents: [],
    },
    {
      slug: "marques-bolden",
      firstName: "Marques",
      lastName: "Bolden",
      birthYear: 1998,
      hometown: "DeSoto, TX",
      highSchool: "DeSoto High School, DeSoto, TX",
      bio: "Freshman center who battled knee injuries but showed potential as a shot blocker and rim protector.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "Texas",
        statusNote: "Played three years at Duke before going undrafted in 2019. Knee injuries limited his career.",
        sourceUrl: "https://en.wikipedia.org/wiki/Marques_Bolden",
      },
      membership: { role: "PLAYER", jerseyNumber: 20, position: "Center", yearsAtSchool: "2016-2019", statsNote: "1.5 PPG · Freshman · Battled knee injuries" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "DeSoto High School", season: "2015-16", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 18.0, reboundsPerGame: 10.5, blocksPerGame: 3.8 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2016-17", yearLabel: "2016-17", sortOrder: 201, gamesPlayed: 24, minutesPerGame: 6.3, pointsPerGame: 1.5, reboundsPerGame: 1.5, blocksPerGame: 0.5, fieldGoalPct: 0.512 },
      ],
      careerEvents: [],
    },
    {
      slug: "chase-jeter",
      firstName: "Chase",
      lastName: "Jeter",
      birthYear: 1997,
      hometown: "Las Vegas, NV",
      highSchool: "Bishop Gorman High School, Las Vegas, NV",
      bio: "Sophomore forward who provided interior depth. Transferred to Arizona after the season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "Overseas",
        statusNote: "Transferred to Arizona where he became a starter (2017-19). Has played professionally overseas in Japan and Australia since going undrafted.",
        sourceUrl: "https://en.wikipedia.org/wiki/Chase_Jeter",
      },
      membership: { role: "PLAYER", jerseyNumber: 45, position: "Power Forward / Center", yearsAtSchool: "2015-2017", statsNote: "3.4 PPG · Transferred to Arizona after sophomore year" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Bishop Gorman High School", season: "2014-15", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 16.5, reboundsPerGame: 9.0, blocksPerGame: 3.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2016-17", yearLabel: "2016-17", sortOrder: 202, gamesPlayed: 34, minutesPerGame: 8.8, pointsPerGame: 3.4, reboundsPerGame: 2.2, blocksPerGame: 0.4, fieldGoalPct: 0.505 },
      ],
      careerEvents: [
        { year: 2017, title: "Transferred to University of Arizona", eventType: "OTHER" },
      ],
    },
    {
      slug: "sean-obi",
      firstName: "Sean",
      lastName: "Obi",
      birthYear: 1994,
      hometown: "Lagos, Nigeria",
      highSchool: "Greens Farms Academy, Westport, CT",
      bio: "Grad transfer from Rice who provided depth at center. The Nigerian-born big man added veteran presence to a young team.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Citizen",
        statusNote: "Played one season at Duke as a grad transfer after transferring from Rice. Did not pursue professional basketball.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/sean-obi/11118",
      },
      membership: { role: "PLAYER", jerseyNumber: 34, position: "Center", yearsAtSchool: "2016-2017", statsNote: "1.8 PPG · Grad transfer from Rice" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2016-17", yearLabel: "2016-17", sortOrder: 206, gamesPlayed: 22, minutesPerGame: 5.5, pointsPerGame: 1.8, reboundsPerGame: 1.5, fieldGoalPct: 0.480 },
      ],
      careerEvents: [],
    },
    {
      slug: "jack-white",
      firstName: "Jack",
      lastName: "White",
      birthYear: 1997,
      hometown: "Geelong, Australia",
      highSchool: "The Scots College, Sydney, Australia",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1631298.png",
      bio: "Freshman from Australia who played limited minutes but showed defensive potential that would make him a starter by 2019.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "Melbourne United (NBL)",
        league: "NBL (Australia)",
        location: "Melbourne, Australia",
        statusNote: "Returned to Australia after Duke to play in the NBL.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jack_White_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 41, position: "Small Forward", yearsAtSchool: "2016-2020", statsNote: "1.5 PPG · Australian freshman · Became starter by 2019" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2016-17", yearLabel: "2016-17", sortOrder: 207, gamesPlayed: 20, minutesPerGame: 5.0, pointsPerGame: 1.5, reboundsPerGame: 1.0, fieldGoalPct: 0.380 },
      ],
      careerEvents: [],
    },
    {
      slug: "mike-krzyzewski",
      firstName: "Mike",
      lastName: "Krzyzewski",
      birthYear: 1947,
      hometown: "Chicago, IL",
      highSchool: "Weber High School, Chicago, IL",
      bio: "Legendary head coach in his 37th season at Duke. Led the 2016-17 team to an ACC regular season championship before an early NCAA Tournament exit.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Retired Head Coach",
        currentEmployer: "Duke University (Emeritus)",
        location: "Durham, NC",
        statusNote: "Retired after the 2021-22 season with 1,202 career wins. Five-time national champion.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Krzyzewski",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "1980-2022", statsNote: "28-9 · ACC Regular Season Champions" },
      seasonStats: [
        { level: "COACHING", teamName: "Duke Blue Devils", season: "2016-17", yearLabel: "2016-17", sortOrder: 1, wins: 28, losses: 9, tournamentResult: "ACC Regular Season Champions, lost in Second Round" },
      ],
      careerEvents: [],
    },
    {
      slug: "jeff-capel",
      firstName: "Jeff",
      lastName: "Capel",
      birthYear: 1975,
      hometown: "Fayetteville, NC",
      highSchool: "South View High School, Hope Mills, NC",
      bio: "Associate head coach at Duke who was one of the top assistants and recruiters in college basketball.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "University of Pittsburgh",
        location: "Pittsburgh, PA",
        statusNote: "Left Duke in 2018 to become head coach at Pitt. Has rebuilt the Panthers program.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jeff_Capel",
      },
      membership: { role: "ASSISTANT_COACH", position: "Associate Head Coach", yearsAtSchool: "2011-2018", statsNote: "Top recruiter · Landed Zion, RJ, Cam class" },
      careerEvents: [
        { year: 2018, title: "Named head coach at University of Pittsburgh", eventType: "COACHING" },
      ],
    },
    {
      slug: "nate-james",
      firstName: "Nate",
      lastName: "James",
      birthYear: 1979,
      hometown: "Seattle, WA",
      highSchool: "Lower Merion High School, Ardmore, PA",
      bio: "Former Duke player (1997-2001) and assistant coach. Key recruiter and mentor to players.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "Austin Peay State University",
        location: "Clarksville, TN",
        statusNote: "Left Duke in 2021 to become head coach at Austin Peay. 2001 NCAA champion as a player.",
        sourceUrl: "https://en.wikipedia.org/wiki/Nate_James",
      },
      membership: { role: "ASSISTANT_COACH", position: "Assistant Coach", yearsAtSchool: "2007-2021", statsNote: "Former Duke player · Key recruiter" },
      careerEvents: [
        { year: 2021, title: "Named head coach at Austin Peay State University", eventType: "COACHING" },
      ],
    },
    {
      slug: "jon-scheyer",
      firstName: "Jon",
      lastName: "Scheyer",
      birthYear: 1987,
      hometown: "Northbrook, IL",
      highSchool: "Glenbrook North High School, Northbrook, IL",
      bio: "Former Duke player (2006-10) and 2010 national champion who served as associate head coach and head-coach-in-waiting.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "Duke University",
        league: "ACC",
        location: "Durham, NC",
        statusNote: "Succeeded Coach K in 2022. Has led Duke to three NCAA Tournaments in three seasons, including a Final Four in 2025.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jon_Scheyer",
      },
      membership: { role: "ASSISTANT_COACH", position: "Associate Head Coach / Coach-in-Waiting", yearsAtSchool: "2013-2022", statsNote: "2010 champion as player · Named successor to Coach K" },
      careerEvents: [
        { year: 2022, title: "Named head coach at Duke, succeeding Coach K", eventType: "COACHING" },
      ],
    },
  ],
};
