import type { TeamSeed } from "./types";

export const dukeBasketball2021: TeamSeed = {
  slug: "duke-basketball-2021",
  name: "Duke Blue Devils",
  season: "2020-2021",
  sport: "Men's Basketball",
  school: "Duke University",
  conference: "ACC",
  accomplishment: "13-11 (COVID Year, No NCAA Tournament)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  mascotName: "Blue Devil",
  people: [
    {
      slug: "jalen-johnson",
      firstName: "Jalen",
      lastName: "Johnson",
      birthYear: 2002,
      hometown: "Milwaukee, WI",
      highSchool: "Nicolet High School, Glendale, WI / IMG Academy",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1630224.png",
      bio: "Five-star freshman who left Duke mid-season to prepare for the NBA Draft, playing only 13 games. Despite the abbreviated college career, his talent was undeniable — 11.2 PPG, 6.1 RPG, and 2.2 APG in limited action.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Power Forward",
        currentEmployer: "Atlanta Hawks",
        league: "NBA",
        location: "Atlanta, GA",
        statusNote: "Selected #20 overall by the Atlanta Hawks in 2021. Had a breakout third season in 2023-24, averaging 16.0 PPG, 8.3 RPG, and 3.6 APG — becoming a key starter for Atlanta. Signed a 5-year, $150 million max rookie extension in 2024. One of the NBA's most versatile forwards.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jalen_Johnson_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Small Forward / Power Forward", yearsAtSchool: "2020-2021", statsNote: "11.2 PPG, 6.1 RPG in 13 games · Left mid-season for draft · #20 pick", gamesPlayed: 13, pointsPerGame: 11.2, reboundsPerGame: 6.1, assistsPerGame: 2.2 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "IMG Academy", season: "2019-20", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 20.5, reboundsPerGame: 10.5, assistsPerGame: 4.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2020-21", yearLabel: "2020-21 (13 games)", sortOrder: 201, gamesPlayed: 13, minutesPerGame: 29.8, pointsPerGame: 11.2, reboundsPerGame: 6.1, assistsPerGame: 2.2, stealsPerGame: 1.2, fieldGoalPct: 0.521, threePointPct: 0.108, freeThrowPct: 0.632 },
        { level: "PROFESSIONAL", teamName: "Atlanta Hawks", season: "2021-22", yearLabel: "2021-22 (Rookie)", sortOrder: 301, gamesPlayed: 22, minutesPerGame: 9.5, pointsPerGame: 2.4, reboundsPerGame: 2.0, assistsPerGame: 0.5, fieldGoalPct: 0.432 },
        { level: "PROFESSIONAL", teamName: "Atlanta Hawks", season: "2022-23", yearLabel: "2022-23", sortOrder: 302, gamesPlayed: 65, minutesPerGame: 21.3, pointsPerGame: 7.2, reboundsPerGame: 5.0, assistsPerGame: 1.7, fieldGoalPct: 0.543 },
        { level: "PROFESSIONAL", teamName: "Atlanta Hawks", season: "2023-24", yearLabel: "2023-24 (Breakout)", sortOrder: 303, gamesPlayed: 66, minutesPerGame: 32.5, pointsPerGame: 16.0, reboundsPerGame: 8.3, assistsPerGame: 3.6, fieldGoalPct: 0.517, threePointPct: 0.316, freeThrowPct: 0.719 },
        { level: "PROFESSIONAL", teamName: "Atlanta Hawks", season: "2024-25", yearLabel: "2024-25", sortOrder: 304, gamesPlayed: 60, minutesPerGame: 34.0, pointsPerGame: 18.5, reboundsPerGame: 8.8, assistsPerGame: 4.0, fieldGoalPct: 0.520, threePointPct: 0.330, freeThrowPct: 0.730 },
      ],
      careerEvents: [
        { year: 2021, title: "Selected #20 overall by Atlanta Hawks", eventType: "DRAFT" },
        { year: 2024, title: "Signed 5-year, $150M max rookie extension", eventType: "CONTRACT" },
      ],
    },
    {
      slug: "matthew-hurt",
      firstName: "Matthew",
      lastName: "Hurt",
      birthYear: 2000,
      hometown: "Rochester, MN",
      highSchool: "John Marshall High School, Rochester, MN",
      bio: "Sophomore who led Duke in scoring at 18.3 PPG on 55.8% shooting. Named first-team All-ACC in a difficult season for the program.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        league: "G-League / Overseas",
        statusNote: "Went undrafted in 2021 despite being first-team All-ACC. Has played in the G-League.",
        sourceUrl: "https://en.wikipedia.org/wiki/Matthew_Hurt",
      },
      membership: { role: "PLAYER", jerseyNumber: 21, position: "Power Forward / Center", yearsAtSchool: "2019-2021", statsNote: "18.3 PPG (led team) · 1st-team All-ACC · 55.8% FG" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2020-21", yearLabel: "2020-21 (1st-team All-ACC)", sortOrder: 202, gamesPlayed: 24, minutesPerGame: 34.1, pointsPerGame: 18.3, reboundsPerGame: 6.2, assistsPerGame: 0.7, fieldGoalPct: 0.558, threePointPct: 0.441, freeThrowPct: 0.819 },
      ],
      careerEvents: [],
    },
    {
      slug: "dj-steward",
      firstName: "DJ",
      lastName: "Steward",
      birthYear: 2001,
      hometown: "Chicago, IL",
      highSchool: "Whitney Young High School, Chicago, IL",
      bio: "Freshman guard who averaged 13.0 PPG with explosive scoring ability. Left for the NBA Draft after one season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        league: "Overseas",
        statusNote: "Went undrafted in 2021 despite leaving Duke after one season. Has played in the G-League and overseas, including stints in Australia and Europe. His explosive athleticism translates well to international play.",
        sourceUrl: "https://en.wikipedia.org/wiki/DJ_Steward",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Shooting Guard", yearsAtSchool: "2020-2021", statsNote: "13.0 PPG · Explosive freshman scorer · Left for draft" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Whitney Young High School", season: "2019-20", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 24.0, reboundsPerGame: 5.5, assistsPerGame: 4.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2020-21", yearLabel: "2020-21", sortOrder: 201, gamesPlayed: 24, minutesPerGame: 32.5, pointsPerGame: 13.0, reboundsPerGame: 3.8, assistsPerGame: 1.6, fieldGoalPct: 0.415, threePointPct: 0.312, freeThrowPct: 0.800 },
      ],
      careerEvents: [
        { year: 2021, title: "Went undrafted; signed with G-League", eventType: "SIGNING" },
      ],
    },
    {
      slug: "mark-williams",
      firstName: "Mark",
      lastName: "Williams",
      birthYear: 2001,
      hometown: "Norfolk, VA",
      highSchool: "IMG Academy, Bradenton, FL",

      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1631110.png",      bio: "Freshman center who played limited minutes (11.2 MPG) as a raw prospect. Would explode as a sophomore to become the #15 pick in 2022.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "Charlotte Hornets",
        league: "NBA",
        location: "Charlotte, NC",
        statusNote: "Had his breakout sophomore season in 2021-22, winning ACC DPOY and being drafted #15. Now a starting center in the NBA.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mark_Williams_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Center", yearsAtSchool: "2020-2022", statsNote: "2.5 PPG, 2.5 RPG as raw freshman · Breakout sophomore (11.2 PPG, 2.8 BPG)" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2020-21", yearLabel: "2020-21", sortOrder: 201, gamesPlayed: 25, minutesPerGame: 11.2, pointsPerGame: 2.5, reboundsPerGame: 2.5, blocksPerGame: 1.2, fieldGoalPct: 0.636 },
      ],
      careerEvents: [],
    },
    {
      slug: "wendell-moore-jr",
      firstName: "Wendell",
      lastName: "Moore Jr.",
      birthYear: 2001,
      hometown: "Concord, NC",
      highSchool: "Cox Mill High School, Concord, NC",

      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1631112.png",      bio: "Sophomore who averaged 8.0 PPG while becoming a key two-way player. Would blossom as a junior to become a first-round pick.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard / Forward",
        league: "NBA / G-League",
        statusNote: "Selected #26 overall in 2022 after a breakout junior year (13.4 PPG, All-ACC).",
        sourceUrl: "https://en.wikipedia.org/wiki/Wendell_Moore_Jr.",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Small Forward", yearsAtSchool: "2019-2022", statsNote: "8.0 PPG, 4.0 RPG · Key rotation player" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2020-21", yearLabel: "2020-21", sortOrder: 202, gamesPlayed: 25, minutesPerGame: 24.2, pointsPerGame: 8.0, reboundsPerGame: 4.0, assistsPerGame: 2.3, fieldGoalPct: 0.398, threePointPct: 0.302 },
      ],
      careerEvents: [],
    },
    {
      slug: "jeremy-roach",
      firstName: "Jeremy",
      lastName: "Roach",
      birthYear: 2002,
      hometown: "Leesburg, VA",
      highSchool: "Paul VI Catholic High School, Chantilly, VA",
      bio: "Freshman point guard who started 20 games and showed poise beyond his years. Averaged 8.7 PPG and 3.3 APG in the COVID-shortened season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        league: "NBA / G-League",
        statusNote: "Became Duke's four-year starter at point guard. Part of Coach K's final team (2022 Final Four).",
        sourceUrl: "https://en.wikipedia.org/wiki/Jeremy_Roach",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Point Guard", yearsAtSchool: "2020-2024", statsNote: "8.7 PPG, 3.3 APG · Freshman starter · 4-year Duke player" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2020-21", yearLabel: "2020-21", sortOrder: 201, gamesPlayed: 24, minutesPerGame: 26.2, pointsPerGame: 8.7, reboundsPerGame: 1.8, assistsPerGame: 3.3, fieldGoalPct: 0.410, threePointPct: 0.347 },
      ],
      careerEvents: [],
    },
    {
      slug: "jordan-goldwire",
      firstName: "Jordan",
      lastName: "Goldwire",
      birthYear: 1999,
      hometown: "Norcross, GA",
      highSchool: "Norcross High School, Norcross, GA",
      bio: "Senior guard who led the ACC in assist-to-turnover ratio (+2.82) and ranked second in steals (2.25 SPG). A defensive stalwart who became the heart and soul of a struggling team.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        league: "G-League / Overseas",
        statusNote: "After four years at Duke, transferred to Oklahoma as a grad transfer for 2021-22. Went undrafted in 2022 and has played professionally in the G-League with the Texas Legends and Capital City Go-Go, and overseas with the Lobos Plateados de la BUAP in Mexico's LNBP.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jordan_Goldwire",
      },
      membership: { role: "PLAYER", jerseyNumber: 23, position: "Guard", yearsAtSchool: "2017-2021", statsNote: "5.8 PPG, 4.0 APG, 2.25 SPG · Led ACC in AST/TO ratio · Team leader" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Norcross High School", season: "2016-17", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 12.0, reboundsPerGame: 3.5, assistsPerGame: 4.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2020-21", yearLabel: "2020-21 (Senior)", sortOrder: 202, gamesPlayed: 24, minutesPerGame: 28.5, pointsPerGame: 5.8, reboundsPerGame: 2.9, assistsPerGame: 4.0, stealsPerGame: 2.25, fieldGoalPct: 0.400, threePointPct: 0.310 },
      ],
      careerEvents: [
        { year: 2021, title: "Transferred to Oklahoma as graduate transfer", eventType: "TRANSFER" },
      ],
    },
    {
      slug: "joey-baker",
      firstName: "Joey",
      lastName: "Baker",
      birthYear: 2000,
      hometown: "Fayetteville, NC",
      highSchool: "Trinity Christian School, Fayetteville, NC",
      bio: "Junior wing who saw reduced playing time in a crowded rotation, averaging 2.9 PPG. A reliable three-point shooter who would return for Coach K's final season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard / Forward",
        league: "Overseas",
        statusNote: "Stayed at Duke for Coach K's final season (2021-22), then transferred to Michigan. After going undrafted in 2023, signed professionally in Lithuania with Pieno Zvaigzdes Pasvalys. Currently playing for the Joondalup Wolves in Australia's NBL1 West.",
        sourceUrl: "https://en.wikipedia.org/wiki/Joey_Baker",
      },
      membership: { role: "PLAYER", jerseyNumber: 13, position: "Small Forward", yearsAtSchool: "2018-2022", statsNote: "2.9 PPG · Spot-up shooter · Returned for Coach K's final year" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2020-21", yearLabel: "2020-21", sortOrder: 202, gamesPlayed: 23, minutesPerGame: 10.5, pointsPerGame: 2.9, reboundsPerGame: 1.2, assistsPerGame: 0.3, fieldGoalPct: 0.380, threePointPct: 0.340 },
      ],
      careerEvents: [
        { year: 2022, title: "Transferred to Michigan as graduate transfer", eventType: "TRANSFER" },
      ],
    },
    {
      slug: "jaemyn-brakefield",
      firstName: "Jaemyn",
      lastName: "Brakefield",
      birthYear: 2002,
      hometown: "Jackson, MS",
      highSchool: "Huntington Prep, Huntington, WV",
      bio: "Four-star freshman forward who appeared in 22 games, averaging 3.5 PPG and 2.5 RPG. Showed flashes of his potential as a versatile scorer but struggled with consistency in a difficult season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        league: "College / Overseas",
        statusNote: "Transferred to Ole Miss after one season at Duke, where he blossomed into a key contributor averaging 7.7 PPG and 4.2 RPG. Improved significantly under Chris Beard, shooting 47.1% from the field. Named to the All-ACC Academic Team during his time at Duke. Helped Ole Miss reach the NCAA Tournament.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jaemyn_Brakefield",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Power Forward", yearsAtSchool: "2020-2021", statsNote: "3.5 PPG, 2.5 RPG · All-ACC Academic Team · Transferred to Ole Miss" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Huntington Prep", season: "2019-20", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 15.0, reboundsPerGame: 7.0, assistsPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2020-21", yearLabel: "2020-21", sortOrder: 201, gamesPlayed: 22, minutesPerGame: 13.5, pointsPerGame: 3.5, reboundsPerGame: 2.5, assistsPerGame: 0.4, fieldGoalPct: 0.408, threePointPct: 0.314 },
      ],
      careerEvents: [
        { year: 2021, title: "Transferred to Ole Miss", eventType: "TRANSFER" },
      ],
    },
    {
      slug: "henry-coleman-iii",
      firstName: "Henry",
      lastName: "Coleman III",
      birthYear: 2002,
      hometown: "Richmond, VA",
      highSchool: "Trinity Episcopal School, Richmond, VA",
      bio: "Four-star freshman forward who saw limited action in 19 games, averaging 1.1 PPG in 5.0 minutes per game. Never got to experience fans in Cameron Indoor due to COVID restrictions.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Texas A&M Aggies",
        league: "NCAA",
        location: "College Station, TX",
        statusNote: "Transferred to Texas A&M after one season at Duke and became a program legend. Holds the Aggies school record for career offensive rebounds (351). Only player in Texas A&M history with 1,200+ points, 800+ rebounds, and 130+ steals. Won the 2025 Nolan Richardson Player of the Year Award. Helped lead the Aggies to four consecutive 20-win seasons and NCAA Tournament berths in 2023, 2024, and 2025.",
        sourceUrl: "https://12thman.com/sports/mens-basketball/roster/henry-coleman-iii/13889",
      },
      membership: { role: "PLAYER", jerseyNumber: 34, position: "Small Forward / Power Forward", yearsAtSchool: "2020-2021", statsNote: "1.1 PPG, 1.4 RPG · Limited minutes · Blossomed at Texas A&M" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Trinity Episcopal School", season: "2019-20", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 16.5, reboundsPerGame: 9.0, assistsPerGame: 2.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2020-21", yearLabel: "2020-21", sortOrder: 201, gamesPlayed: 19, minutesPerGame: 5.0, pointsPerGame: 1.1, reboundsPerGame: 1.4, fieldGoalPct: 0.500 },
      ],
      careerEvents: [
        { year: 2021, title: "Transferred to Texas A&M", eventType: "TRANSFER" },
        { year: 2025, title: "Won Nolan Richardson Player of the Year Award", eventType: "AWARD" },
      ],
    },
    {
      slug: "mike-buckmire",
      firstName: "Mike",
      lastName: "Buckmire",
      birthYear: 1998,
      hometown: "Blue Bell, PA",
      highSchool: "Germantown Friends School, Philadelphia, PA",
      bio: "Senior walk-on-turned-scholarship player who provided energy and leadership in practice. A Duke legacy whose father was on the 1986 NCAA Championship soccer team. Completed his four-year Duke career.",
      status: {
        occupationType: "OTHER",
        statusNote: "Completed his Duke career as a four-year letterwinner, having earned a scholarship from Coach K after his sophomore year. His father Michael was a member of Duke's 1986 NCAA championship men's soccer team. After graduating, he pursued a career outside of basketball.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/mike-buckmire/16336",
      },
      membership: { role: "PLAYER", jerseyNumber: 51, position: "Guard", yearsAtSchool: "2017-2021", statsNote: "Walk-on turned scholarship player · Duke legacy · 4-year letterwinner" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2020-21", yearLabel: "2020-21 (Senior)", sortOrder: 202, gamesPlayed: 5, minutesPerGame: 2.0, pointsPerGame: 0.2, reboundsPerGame: 0.4 },
      ],
      careerEvents: [
        { year: 2019, title: "Earned scholarship from Coach K after two years as walk-on", eventType: "AWARD" },
      ],
    },
    {
      slug: "michael-savarino",
      firstName: "Michael",
      lastName: "Savarino",
      birthYear: 2001,
      hometown: "Richmond, VA",
      highSchool: "Collegiate School, Richmond, VA",
      bio: "Freshman walk-on forward and Coach K's grandson. Redshirted his first year and appeared in limited action during the 2020-21 season.",
      status: {
        occupationType: "OTHER",
        statusNote: "Coach K's grandson who walked on to the Duke basketball team. Had limited playing time during his Duke career but was a valued member of the team. After his time at Duke, he pursued interests outside of professional basketball.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/michael-savarino/16340",
      },
      membership: { role: "PLAYER", jerseyNumber: 30, position: "Forward", yearsAtSchool: "2019-2022", statsNote: "Walk-on · Coach K's grandson · Limited game action" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2020-21", yearLabel: "2020-21", sortOrder: 201, gamesPlayed: 3, minutesPerGame: 1.5, pointsPerGame: 0.0, reboundsPerGame: 0.3 },
      ],
      careerEvents: [],
    },
    {
      slug: "mike-krzyzewski",
      firstName: "Mike",
      lastName: "Krzyzewski",
      birthYear: 1947,
      hometown: "Chicago, IL",
      highSchool: "Weber High School, Chicago, IL",
      bio: "The worst season of Coach K's tenure at 13-11. Injuries, COVID protocols, and a difficult freshman class led to Duke's first losing ACC record (9-9) since 1994-95.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Retired Head Coach",
        currentEmployer: "Duke University (Emeritus)",
        location: "Durham, NC",
        statusNote: "Announced his retirement the following year. The 2020-21 season was his only losing record at Duke.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Krzyzewski",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "1980-2022", statsNote: "13-11 · Only losing season · COVID-impacted year" },
      seasonStats: [
        { level: "COACHING", teamName: "Duke Blue Devils", season: "2020-21", yearLabel: "2020-21 (COVID)", sortOrder: 1, wins: 13, losses: 11, tournamentResult: "Opted out of NCAA Tournament after positive COVID tests" },
      ],
      careerEvents: [],
    },
    {
      slug: "jeff-capel",
      firstName: "Jeff",
      lastName: "Capel",
      birthYear: 1975,
      hometown: "Fayetteville, NC",
      highSchool: "South View High School, Hope Mills, NC",
      bio: "Associate head coach at Duke who was one of the top assistants and recruiters in college basketball.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "University of Pittsburgh",
        location: "Pittsburgh, PA",
        statusNote: "Left Duke in 2018 to become head coach at Pitt. Has rebuilt the Panthers program.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jeff_Capel",
      },
      membership: { role: "ASSISTANT_COACH", position: "Associate Head Coach", yearsAtSchool: "2011-2018", statsNote: "Top recruiter · Landed Zion, RJ, Cam class" },
      careerEvents: [
        { year: 2018, title: "Named head coach at University of Pittsburgh", eventType: "COACHING" },
      ],
    },
    {
      slug: "nate-james",
      firstName: "Nate",
      lastName: "James",
      birthYear: 1979,
      hometown: "Seattle, WA",
      highSchool: "Lower Merion High School, Ardmore, PA",
      bio: "Former Duke player (1997-2001) and assistant coach. Key recruiter and mentor to players.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "Austin Peay State University",
        location: "Clarksville, TN",
        statusNote: "Left Duke in 2021 to become head coach at Austin Peay. 2001 NCAA champion as a player.",
        sourceUrl: "https://en.wikipedia.org/wiki/Nate_James",
      },
      membership: { role: "ASSISTANT_COACH", position: "Assistant Coach", yearsAtSchool: "2007-2021", statsNote: "Former Duke player · Key recruiter" },
      careerEvents: [
        { year: 2021, title: "Named head coach at Austin Peay State University", eventType: "COACHING" },
      ],
    },
    {
      slug: "jon-scheyer",
      firstName: "Jon",
      lastName: "Scheyer",
      birthYear: 1987,
      hometown: "Northbrook, IL",
      highSchool: "Glenbrook North High School, Northbrook, IL",
      bio: "Former Duke player (2006-10) and 2010 national champion who served as associate head coach and head-coach-in-waiting.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "Duke University",
        league: "ACC",
        location: "Durham, NC",
        statusNote: "Succeeded Coach K in 2022. Has led Duke to three NCAA Tournaments in three seasons, including a Final Four in 2025.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jon_Scheyer",
      },
      membership: { role: "ASSISTANT_COACH", position: "Associate Head Coach / Coach-in-Waiting", yearsAtSchool: "2013-2022", statsNote: "2010 champion as player · Named successor to Coach K" },
      careerEvents: [
        { year: 2022, title: "Named head coach at Duke, succeeding Coach K", eventType: "COACHING" },
      ],
    },
  ],
};
