import type { TeamSeed } from "./types";

export const dukeBasketball2016: TeamSeed = {
  slug: "duke-basketball-2016",
  name: "Duke Blue Devils",
  season: "2015-2016",
  sport: "Men's Basketball",
  school: "Duke University",
  conference: "ACC",
  accomplishment: "23-11, Sweet Sixteen",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  mascotName: "Blue Devil",
  people: [
    {
      slug: "brandon-ingram",
      firstName: "Brandon",
      lastName: "Ingram",
      birthYear: 1997,
      hometown: "Kinston, NC",
      highSchool: "Kinston High School, Kinston, NC",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1627742.png",
      isFeatured: true,
      bio: "The consensus #2 overall pick in 2016, Ingram was a lanky 6'9\" wing who averaged 17.3 PPG as a freshman. His scoring versatility and length made him an elite NBA prospect from the moment he stepped on campus.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Small Forward",
        currentEmployer: "New Orleans Pelicans",
        league: "NBA",
        location: "New Orleans, LA",
        statusNote: "Selected #2 overall by the Los Angeles Lakers in 2016. After three seasons in LA, he was traded to New Orleans as part of the Anthony Davis deal. Named Most Improved Player in 2019-20 after averaging 23.8 PPG and making his first All-Star team. Signed a 5-year, $158 million max extension. Has averaged 20+ PPG in five consecutive seasons with the Pelicans.",
        sourceUrl: "https://en.wikipedia.org/wiki/Brandon_Ingram",
      },
      membership: { role: "PLAYER", jerseyNumber: 14, position: "Small Forward", yearsAtSchool: "2015-2016", statsNote: "17.3 PPG, 6.8 RPG · ACC ROY · Consensus All-American · #2 pick", gamesPlayed: 34, pointsPerGame: 17.3, reboundsPerGame: 6.8, assistsPerGame: 2.0 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Kinston High School", season: "2014-15", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 28.0, reboundsPerGame: 10.4, assistsPerGame: 3.1 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2015-16", yearLabel: "2015-16", sortOrder: 201, gamesPlayed: 34, minutesPerGame: 34.8, pointsPerGame: 17.3, reboundsPerGame: 6.8, assistsPerGame: 2.0, stealsPerGame: 0.9, blocksPerGame: 1.4, fieldGoalPct: 0.443, threePointPct: 0.341, freeThrowPct: 0.682 },
        { level: "PROFESSIONAL", teamName: "Los Angeles Lakers", season: "2016-17", yearLabel: "2016-17 (Rookie)", sortOrder: 301, gamesPlayed: 79, minutesPerGame: 28.8, pointsPerGame: 9.4, reboundsPerGame: 4.0, assistsPerGame: 2.1, fieldGoalPct: 0.402, threePointPct: 0.290, freeThrowPct: 0.621 },
        { level: "PROFESSIONAL", teamName: "Los Angeles Lakers", season: "2018-19", yearLabel: "2018-19", sortOrder: 303, gamesPlayed: 52, minutesPerGame: 33.8, pointsPerGame: 18.3, reboundsPerGame: 5.1, assistsPerGame: 3.0, fieldGoalPct: 0.491, threePointPct: 0.330, freeThrowPct: 0.675 },
        { level: "PROFESSIONAL", teamName: "New Orleans Pelicans", season: "2019-20", yearLabel: "2019-20 (All-Star, MIP)", sortOrder: 304, gamesPlayed: 62, minutesPerGame: 33.9, pointsPerGame: 23.8, reboundsPerGame: 6.1, assistsPerGame: 4.2, fieldGoalPct: 0.463, threePointPct: 0.391, freeThrowPct: 0.851 },
        { level: "PROFESSIONAL", teamName: "New Orleans Pelicans", season: "2022-23", yearLabel: "2022-23", sortOrder: 307, gamesPlayed: 45, minutesPerGame: 34.5, pointsPerGame: 24.7, reboundsPerGame: 5.8, assistsPerGame: 5.8, fieldGoalPct: 0.468, threePointPct: 0.331, freeThrowPct: 0.803 },
        { level: "PROFESSIONAL", teamName: "New Orleans Pelicans", season: "2024-25", yearLabel: "2024-25", sortOrder: 309, gamesPlayed: 55, minutesPerGame: 33.0, pointsPerGame: 22.5, reboundsPerGame: 5.5, assistsPerGame: 5.0, fieldGoalPct: 0.470, threePointPct: 0.350, freeThrowPct: 0.820 },
      ],
      careerEvents: [
        { year: 2016, title: "Selected #2 overall by Los Angeles Lakers", eventType: "DRAFT" },
        { year: 2019, title: "Traded to New Orleans in Anthony Davis deal", eventType: "TRADE" },
        { year: 2020, title: "Won NBA Most Improved Player Award", eventType: "AWARD" },
        { year: 2020, title: "Named to first NBA All-Star team", eventType: "AWARD" },
        { year: 2020, title: "Signed 5-year, $158M max extension", eventType: "CONTRACT" },
      ],
    },
    {
      slug: "luke-kennard",
      firstName: "Luke",
      lastName: "Kennard",
      birthYear: 1996,
      hometown: "Franklin, OH",
      highSchool: "Franklin High School, Franklin, OH",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628379.png",
      bio: "Freshman who showed elite shooting ability from day one, averaging 10.6 PPG off the bench and shooting 37.0% from three.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Shooting Guard",
        currentEmployer: "Memphis Grizzlies",
        league: "NBA",
        location: "Memphis, TN",
        statusNote: "Returned for his sophomore year, led Duke in scoring in 2016-17 at 19.5 PPG, and was drafted #12. Elite NBA shooter with career 44.1% from three.",
        sourceUrl: "https://en.wikipedia.org/wiki/Luke_Kennard",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Shooting Guard", yearsAtSchool: "2015-2017", statsNote: "10.6 PPG as freshman · 37% from three · Returned for sophomore year" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2015-16", yearLabel: "2015-16", sortOrder: 201, gamesPlayed: 34, minutesPerGame: 24.6, pointsPerGame: 10.6, reboundsPerGame: 3.3, assistsPerGame: 1.9, fieldGoalPct: 0.468, threePointPct: 0.370, freeThrowPct: 0.805 },
      ],
      careerEvents: [],
    },
    {
      slug: "grayson-allen",
      firstName: "Grayson",
      lastName: "Allen",
      birthYear: 1995,
      hometown: "Jacksonville, FL",
      highSchool: "Providence School, Jacksonville, FL",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628960.png",
      isFeatured: false,
      bio: "Sophomore who led the team in scoring at 21.6 PPG — the highest scoring average by a Duke player since J.J. Redick. Named first-team All-ACC.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Shooting Guard",
        currentEmployer: "Phoenix Suns",
        league: "NBA",
        location: "Phoenix, AZ",
        statusNote: "Stayed at Duke through 2018 (senior year), then selected #21 overall by Utah. Won NBA Championship with Milwaukee in 2021.",
        sourceUrl: "https://en.wikipedia.org/wiki/Grayson_Allen",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Shooting Guard", yearsAtSchool: "2014-2018", statsNote: "21.6 PPG (led team) · 1st-team All-ACC · 2015 champion" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2015-16", yearLabel: "2015-16", sortOrder: 202, gamesPlayed: 34, minutesPerGame: 34.5, pointsPerGame: 21.6, reboundsPerGame: 4.6, assistsPerGame: 3.5, stealsPerGame: 1.3, fieldGoalPct: 0.460, threePointPct: 0.418, freeThrowPct: 0.854 },
      ],
      careerEvents: [],
    },
    {
      slug: "matt-jones",
      firstName: "Matt",
      lastName: "Jones",
      birthYear: 1994,
      hometown: "Chatsworth, CA",
      highSchool: "DeSoto High School, DeSoto, TX",
      bio: "Junior guard who started 33 games and shot 41.5% from three. Reliable two-way player who was the team's best perimeter defender.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Business Development",
        currentEmployer: "Total Quality Logistics",
        location: "Chicago, IL",
        statusNote: "Returned for senior year in 2016-17 before transitioning to business career.",
        sourceUrl: "https://en.wikipedia.org/wiki/Matt_Jones_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 13, position: "Shooting Guard", yearsAtSchool: "2013-2017", statsNote: "10.4 PPG · 41.5% from three · Started 33 games" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2015-16", yearLabel: "2015-16", sortOrder: 203, gamesPlayed: 35, minutesPerGame: 30.5, pointsPerGame: 10.4, reboundsPerGame: 2.5, assistsPerGame: 2.2, stealsPerGame: 1.0, fieldGoalPct: 0.430, threePointPct: 0.415, freeThrowPct: 0.800 },
      ],
      careerEvents: [],
    },
    {
      slug: "marshall-plumlee",
      firstName: "Marshall",
      lastName: "Plumlee",
      birthYear: 1992,
      hometown: "Warsaw, IN",
      highSchool: "Christ School, Arden, NC",
      bio: "Senior center and third Plumlee brother to play at Duke. Had his best season as a senior, averaging 8.4 PPG and 7.0 RPG while starting all 34 games.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Investor",
        currentEmployer: "Blackstone",
        location: "New York, NY",
        statusNote: "Played 29 NBA games (Knicks/Bucks) before pivoting to military service — served as a U.S. Army Ranger in the 75th Ranger Regiment. Then earned an MBA from Harvard Business School (Class of 2024) and joined Blackstone as an investor.",
        sourceUrl: "https://en.wikipedia.org/wiki/Marshall_Plumlee",
      },
      membership: { role: "PLAYER", jerseyNumber: 40, position: "Center", yearsAtSchool: "2011-2016", statsNote: "8.4 PPG, 7.0 RPG · Senior captain · Started all 34 games" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2015-16", yearLabel: "2015-16 (Senior)", sortOrder: 205, gamesPlayed: 34, minutesPerGame: 24.3, pointsPerGame: 8.4, reboundsPerGame: 7.0, assistsPerGame: 0.8, blocksPerGame: 0.7, fieldGoalPct: 0.645, freeThrowPct: 0.518 },
        { level: "PROFESSIONAL", teamName: "New York Knicks", season: "2016-17", yearLabel: "2016-17", sortOrder: 301, gamesPlayed: 21, minutesPerGame: 6.5, pointsPerGame: 2.0, reboundsPerGame: 2.1, fieldGoalPct: 0.520 },
      ],
      careerEvents: [
        { year: 2016, title: "Signed as UDFA with New York Knicks", eventType: "SIGNING" },
        { year: 2018, title: "Enlisted in U.S. Army; served as Ranger", eventType: "OTHER" },
        { year: 2024, title: "Graduated from Harvard Business School", eventType: "STUDENT" },
        { year: 2024, title: "Joined Blackstone as investor", eventType: "CAREER_CHANGE" },
      ],
    },
    {
      slug: "derryck-thornton",
      firstName: "Derryck",
      lastName: "Thornton",
      birthYear: 1997,
      hometown: "Chatsworth, CA",
      highSchool: "Findlay Prep, Henderson, NV",
      bio: "Freshman point guard who started 21 games before losing his starting spot. Transferred to USC after the season.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Citizen",
        location: "California",
        statusNote: "Transferred to USC after his freshman year at Duke, then later transferred to UC Davis. Did not pursue professional basketball after college. Has maintained a low public profile since leaving basketball.",
        sourceUrl: "https://en.wikipedia.org/wiki/Derryck_Thornton",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Point Guard", yearsAtSchool: "2015-2016", statsNote: "7.5 PPG, 3.0 APG · Started 21 games · Transferred to USC" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Findlay Prep", season: "2014-15", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 16.5, reboundsPerGame: 3.5, assistsPerGame: 6.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2015-16", yearLabel: "2015-16", sortOrder: 201, gamesPlayed: 34, minutesPerGame: 22.5, pointsPerGame: 7.5, reboundsPerGame: 2.2, assistsPerGame: 3.0, fieldGoalPct: 0.370, threePointPct: 0.280, freeThrowPct: 0.650 },
      ],
      careerEvents: [
        { year: 2016, title: "Transferred to USC", eventType: "OTHER" },
      ],
    },
    {
      slug: "amile-jefferson",
      firstName: "Amile",
      lastName: "Jefferson",
      birthYear: 1993,
      hometown: "Philadelphia, PA",
      highSchool: "Friends' Central School, Wynnewood, PA",
      bio: "Senior forward who was the team's leading rebounder and most experienced player before suffering a right foot fracture nine games into the season. Jefferson started all nine games he played, averaging 11.4 PPG and 10.3 RPG before his injury ended his season. He received a medical redshirt and returned for a fifth year in 2016-17.",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Coach",
        currentEmployer: "Boston Celtics",
        league: "NBA",
        location: "Boston, MA",
        statusNote: "After receiving a medical redshirt, Jefferson returned for 2016-17 and became one of the most decorated players in Duke history, playing a program-record 150 games. He played professionally in the G-League (Iowa Wolves), Turkey (Galatasaray), and had brief NBA stints with the Timberwolves and Magic. Returned to Duke as Director of Player Development in 2022, was promoted to assistant coach by Jon Scheyer, and then joined the Boston Celtics coaching staff in 2023.",
        sourceUrl: "https://en.wikipedia.org/wiki/Amile_Jefferson",
      },
      membership: { role: "PLAYER", jerseyNumber: 21, position: "Power Forward", yearsAtSchool: "2012-2017", statsNote: "11.4 PPG, 10.3 RPG in 9 games · Foot fracture ended season · Medical redshirt", gamesPlayed: 9, pointsPerGame: 11.4, reboundsPerGame: 10.3 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Friends' Central School", season: "2011-12", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 17.7, reboundsPerGame: 9.7, blocksPerGame: 1.9 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2015-16", yearLabel: "2015-16 (Injured)", sortOrder: 204, gamesPlayed: 9, minutesPerGame: 28.0, pointsPerGame: 11.4, reboundsPerGame: 10.3, fieldGoalPct: 0.683, freeThrowPct: 0.545 },
      ],
      careerEvents: [
        { year: 2015, title: "Won NCAA Championship with Duke", eventType: "CHAMPIONSHIP" },
        { year: 2016, title: "Granted medical redshirt after foot fracture", eventType: "OTHER" },
        { year: 2017, title: "Signed with Minnesota Timberwolves (waived in preseason)", eventType: "SIGNING" },
        { year: 2022, title: "Joined Duke coaching staff as Director of Player Development", eventType: "CAREER_CHANGE" },
        { year: 2023, title: "Joined Boston Celtics as assistant coach", eventType: "CAREER_CHANGE" },
      ],
    },
    {
      slug: "chase-jeter",
      firstName: "Chase",
      lastName: "Jeter",
      birthYear: 1997,
      hometown: "Las Vegas, NV",
      highSchool: "Bishop Gorman High School, Las Vegas, NV",
      bio: "Five-star freshman forward and McDonald's All-American who was Nevada's Gatorade Player of the Year. Saw limited playing time behind Marshall Plumlee and Amile Jefferson, averaging 1.9 PPG and 1.9 RPG in 32 games. Transferred to Arizona after his sophomore year.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Power Forward / Center",
        league: "G-League / Overseas",
        statusNote: "Transferred to Arizona after his sophomore year and had a productive career with the Wildcats, averaging 10.4 PPG and 6.5 RPG as a senior. Went undrafted in 2020 and has bounced between the G-League and overseas leagues, playing in Austria, the Czech Republic, and for various G-League teams. Most recently played for the Capital City Go-Go in the G-League in 2025.",
        sourceUrl: "https://en.wikipedia.org/wiki/Chase_Jeter",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Power Forward", yearsAtSchool: "2015-2017", statsNote: "1.9 PPG, 1.9 RPG · McDonald's All-American · Transferred to Arizona" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Bishop Gorman High School", season: "2014-15", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 18.0, reboundsPerGame: 9.5, blocksPerGame: 3.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2015-16", yearLabel: "2015-16", sortOrder: 201, gamesPlayed: 32, minutesPerGame: 7.2, pointsPerGame: 1.9, reboundsPerGame: 1.9, fieldGoalPct: 0.500, freeThrowPct: 0.556 },
      ],
      careerEvents: [
        { year: 2017, title: "Transferred to University of Arizona", eventType: "OTHER" },
        { year: 2020, title: "Went undrafted; pursued G-League and overseas career", eventType: "OTHER" },
      ],
    },
    {
      slug: "sean-obi",
      firstName: "Sean",
      lastName: "Obi",
      birthYear: 1995,
      hometown: "Lagos, Nigeria",
      highSchool: "Prestonwood Christian Academy, Plano, TX",
      bio: "Transfer from Rice who sat out 2014-15 per NCAA rules. At Rice, he had averaged 11.4 PPG and a Conference USA-leading 9.3 RPG as a freshman. Saw very limited action in 2015-16 with only 10 games played, averaging 0.5 PPG and 1.0 RPG.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Business Professional",
        location: "Maryland",
        statusNote: "Missed the entire 2016-17 season due to knee surgery. Graduated from Duke and transferred to Maryland as a graduate student in the Smith School of Business studying supply chain management. Played 21 games for the Terps in 2017-18. Has maintained a low profile since graduating from Maryland.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/sean-obi/4420",
      },
      membership: { role: "PLAYER", jerseyNumber: 34, position: "Center", yearsAtSchool: "2014-2017", statsNote: "0.5 PPG, 1.0 RPG in 10 games · Transfer from Rice" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Rice Owls", season: "2013-14", yearLabel: "2013-14 (Freshman at Rice)", sortOrder: 101, gamesPlayed: 31, minutesPerGame: 27.5, pointsPerGame: 11.4, reboundsPerGame: 9.3, fieldGoalPct: 0.477, freeThrowPct: 0.593 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2015-16", yearLabel: "2015-16", sortOrder: 202, gamesPlayed: 10, minutesPerGame: 4.5, pointsPerGame: 0.5, reboundsPerGame: 1.0, fieldGoalPct: 0.333 },
      ],
      careerEvents: [
        { year: 2014, title: "Transferred from Rice to Duke", eventType: "OTHER" },
        { year: 2017, title: "Graduated from Duke; transferred to Maryland as grad student", eventType: "OTHER" },
      ],
    },
    {
      slug: "justin-robinson-duke",
      firstName: "Justin",
      lastName: "Robinson",
      birthYear: 1996,
      hometown: "San Antonio, TX",
      highSchool: "IMG Academy, Bradenton, FL",
      bio: "Son of NBA Hall of Famer David Robinson. Redshirted his first season in 2015-16. A 6'8\" forward who became a team captain and fan favorite, Robinson was a five-year Blue Devil who contributed as a role player and beloved teammate across four active seasons.",
      status: {
        occupationType: "COACH",
        currentTitle: "Director of Player Development",
        currentEmployer: "Duke University",
        location: "Durham, NC",
        statusNote: "After graduating from Duke, Robinson played professionally overseas for Mornar Bar in Montenegro and Elitzur Maccabi Netanya in Israel, averaging 13.9 PPG and 8.2 RPG during the 2022-23 Israeli season. In November 2023, he was named Duke's Director of Player Development by head coach Jon Scheyer, returning to his alma mater in a coaching capacity.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/coaches/justin-robinson/5016",
      },
      membership: { role: "PLAYER", jerseyNumber: 50, position: "Forward", yearsAtSchool: "2015-2020", statsNote: "Redshirted 2015-16 · Team captain · Son of David Robinson" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2015-16", yearLabel: "2015-16 (Redshirt)", sortOrder: 200, gamesPlayed: 0 },
      ],
      careerEvents: [
        { year: 2016, title: "Redshirted freshman season at Duke", eventType: "OTHER" },
        { year: 2021, title: "Signed with Mornar Bar (Montenegro)", eventType: "SIGNING" },
        { year: 2023, title: "Named Duke Director of Player Development", eventType: "CAREER_CHANGE" },
      ],
    },
    {
      slug: "brennan-besser",
      firstName: "Brennan",
      lastName: "Besser",
      birthYear: 1997,
      hometown: "Chicago, IL",
      highSchool: "Latin School, Chicago, IL",
      bio: "Walk-on guard from Chicago who was known for his tireless work ethic and commitment to the team. Founded Walk On America, a charity to raise money and awareness for the Intellectual and Developmental Disability community, biking from Seattle to New York City in a two-month ride.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Director, Strategic Partnerships",
        currentEmployer: "Intersport",
        location: "Chicago, IL",
        statusNote: "After graduating from Duke, Besser pursued a career in sports business. He is currently a Director of Strategic Partnerships at Intersport, a Chicago-based sports marketing agency. He also founded Walk On America, a nonprofit that raised money and awareness for the Intellectual and Developmental Disability community through a cross-country bicycle ride from Seattle to New York City.",
        sourceUrl: "https://www.linkedin.com/in/brennan-besser-10a7921a7/",
      },
      membership: { role: "PLAYER", jerseyNumber: 53, position: "Guard", yearsAtSchool: "2015-2019", statsNote: "Walk-on · 6 career games · Founded Walk On America" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Latin School", season: "2014-15", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 14.6, reboundsPerGame: 7.1 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2015-16", yearLabel: "2015-16", sortOrder: 201, gamesPlayed: 1, minutesPerGame: 1.0, pointsPerGame: 0.0, reboundsPerGame: 0.0 },
      ],
      careerEvents: [
        { year: 2018, title: "Founded Walk On America charity", eventType: "OTHER" },
      ],
    },
    {
      slug: "nick-pagliuca",
      firstName: "Nick",
      lastName: "Pagliuca",
      birthYear: 1995,
      hometown: "Weston, MA",
      highSchool: "Milton Academy, Milton, MA",
      bio: "Walk-on guard and son of Bain Capital managing director and Boston Celtics co-owner Steve Pagliuca. A computer science major who was named to the NABC Honors Court in 2016, Pagliuca appeared in 29 career games across his Duke career.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Vice President of Business Development",
        currentEmployer: "Liquid AI",
        location: "Boston, MA",
        statusNote: "After graduating from Duke with a degree in computer science, Pagliuca pursued a career in tech and business. He interned at Apple and Myomo and worked at Bain & Company and Cove Hill Partners before earning an MBA from Harvard Business School. He is currently Vice President of Business Development at Liquid AI, an MIT-spinout AI startup.",
        sourceUrl: "https://www.linkedin.com/in/nick-pagliuca-6b0a62b3/",
      },
      membership: { role: "PLAYER", jerseyNumber: 45, position: "Guard", yearsAtSchool: "2013-2017", statsNote: "Walk-on · 29 career games · NABC Honors Court 2016" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2015-16", yearLabel: "2015-16", sortOrder: 206, gamesPlayed: 10, minutesPerGame: 2.0, pointsPerGame: 0.0, reboundsPerGame: 0.4 },
      ],
      careerEvents: [
        { year: 2017, title: "Graduated from Duke with CS degree", eventType: "STUDENT" },
        { year: 2024, title: "Earned MBA from Harvard Business School", eventType: "STUDENT" },
        { year: 2024, title: "Joined Liquid AI as VP of Business Development", eventType: "CAREER_CHANGE" },
      ],
    },
    {
      slug: "sean-kelly",
      firstName: "Sean",
      lastName: "Kelly",
      birthYear: 1993,
      hometown: "Raleigh, NC",
      highSchool: "Ravenscroft School, Raleigh, NC",
      bio: "Former team manager who walked on to the roster as a senior in 2014-15 and won a national championship. Returned for a fifth year in 2015-16. Kelly spent three years as a student manager before approaching associate head coach Jeff Capel about joining the roster.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Education and Social Media Professional",
        location: "Los Angeles, CA",
        statusNote: "After graduating from Duke as a 2015 national champion, Kelly worked in admissions at Carlthorp School in Santa Monica. He has also become known for his social media expertise, helping analyze and manage social media strategies. An avid marathon runner, he completed the NYC Marathon in 2022 while balancing fatherhood and a full-time career.",
        sourceUrl: "https://thesocialinstitute.com/blog/qa-sean-kelly/",
      },
      membership: { role: "PLAYER", jerseyNumber: 42, position: "Guard", yearsAtSchool: "2014-2016", statsNote: "Walk-on · Former team manager · 2015 national champion" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2015-16", yearLabel: "2015-16", sortOrder: 207, gamesPlayed: 4, minutesPerGame: 1.0, pointsPerGame: 0.0, reboundsPerGame: 0.0 },
      ],
      careerEvents: [
        { year: 2015, title: "Won NCAA Championship with Duke", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "mike-krzyzewski",
      firstName: "Mike",
      lastName: "Krzyzewski",
      birthYear: 1947,
      hometown: "Chicago, IL",
      highSchool: "Weber High School, Chicago, IL",
      bio: "Legendary head coach defending the 2015 national championship. The 2015-16 team had a disappointing season by Duke standards, losing in the Sweet Sixteen.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Retired Head Coach",
        currentEmployer: "Duke University (Emeritus)",
        location: "Durham, NC",
        statusNote: "Retired after 2021-22 with 1,202 career wins.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Krzyzewski",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "1980-2022", statsNote: "23-11 · Sweet Sixteen · Defending champions" },
      seasonStats: [
        { level: "COACHING", teamName: "Duke Blue Devils", season: "2015-16", yearLabel: "2015-16", sortOrder: 1, wins: 23, losses: 11, tournamentResult: "Sweet Sixteen (lost to Oregon)" },
      ],
      careerEvents: [],
    },
    {
      slug: "jeff-capel",
      firstName: "Jeff",
      lastName: "Capel",
      birthYear: 1975,
      hometown: "Fayetteville, NC",
      highSchool: "South View High School, Hope Mills, NC",
      bio: "Associate head coach at Duke who was one of the top assistants and recruiters in college basketball.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "University of Pittsburgh",
        location: "Pittsburgh, PA",
        statusNote: "Left Duke in 2018 to become head coach at Pitt. Has rebuilt the Panthers program.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jeff_Capel",
      },
      membership: { role: "ASSISTANT_COACH", position: "Associate Head Coach", yearsAtSchool: "2011-2018", statsNote: "Top recruiter · Landed Zion, RJ, Cam class" },
      careerEvents: [
        { year: 2018, title: "Named head coach at University of Pittsburgh", eventType: "COACHING" },
      ],
    },
    {
      slug: "nate-james",
      firstName: "Nate",
      lastName: "James",
      birthYear: 1979,
      hometown: "Seattle, WA",
      highSchool: "Lower Merion High School, Ardmore, PA",
      bio: "Former Duke player (1997-2001) and assistant coach. Key recruiter and mentor to players.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "Austin Peay State University",
        location: "Clarksville, TN",
        statusNote: "Left Duke in 2021 to become head coach at Austin Peay. 2001 NCAA champion as a player.",
        sourceUrl: "https://en.wikipedia.org/wiki/Nate_James",
      },
      membership: { role: "ASSISTANT_COACH", position: "Assistant Coach", yearsAtSchool: "2007-2021", statsNote: "Former Duke player · Key recruiter" },
      careerEvents: [
        { year: 2021, title: "Named head coach at Austin Peay State University", eventType: "COACHING" },
      ],
    },
    {
      slug: "jon-scheyer",
      firstName: "Jon",
      lastName: "Scheyer",
      birthYear: 1987,
      hometown: "Northbrook, IL",
      highSchool: "Glenbrook North High School, Northbrook, IL",
      bio: "Former Duke player (2006-10) and 2010 national champion who served as associate head coach and head-coach-in-waiting.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "Duke University",
        league: "ACC",
        location: "Durham, NC",
        statusNote: "Succeeded Coach K in 2022. Has led Duke to three NCAA Tournaments in three seasons, including a Final Four in 2025.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jon_Scheyer",
      },
      membership: { role: "ASSISTANT_COACH", position: "Associate Head Coach / Coach-in-Waiting", yearsAtSchool: "2013-2022", statsNote: "2010 champion as player · Named successor to Coach K" },
      careerEvents: [
        { year: 2022, title: "Named head coach at Duke, succeeding Coach K", eventType: "COACHING" },
      ],
    },
  ],
};
