import type { TeamSeed } from "./types";

export const dukeBasketball2021: TeamSeed = {
  slug: "duke-basketball-2021",
  name: "Duke Blue Devils",
  season: "2020-2021",
  sport: "Basketball",
  school: "Duke University",
  conference: "ACC",
  accomplishment: "13-11 (COVID Year, No NCAA Tournament)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  mascotName: "Blue Devil",
  people: [
    {
      slug: "jalen-johnson",
      firstName: "Jalen",
      lastName: "Johnson",
      birthYear: 2002,
      hometown: "Milwaukee, WI",
      highSchool: "Nicolet High School, Glendale, WI / IMG Academy",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1630224.png",
      bio: "Five-star freshman who left Duke mid-season to prepare for the NBA Draft, playing only 13 games. Despite the abbreviated college career, his talent was undeniable — 11.2 PPG, 6.1 RPG, and 2.2 APG in limited action.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Power Forward",
        currentEmployer: "Atlanta Hawks",
        league: "NBA",
        location: "Atlanta, GA",
        statusNote: "Selected #20 overall by the Atlanta Hawks in 2021. Had a breakout third season in 2023-24, averaging 16.0 PPG, 8.3 RPG, and 3.6 APG — becoming a key starter for Atlanta. Signed a 5-year, $150 million max rookie extension in 2024. One of the NBA's most versatile forwards.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jalen_Johnson_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Small Forward / Power Forward", yearsAtSchool: "2020-2021", statsNote: "11.2 PPG, 6.1 RPG in 13 games · Left mid-season for draft · #20 pick", gamesPlayed: 13, pointsPerGame: 11.2, reboundsPerGame: 6.1, assistsPerGame: 2.2 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "IMG Academy", season: "2019-20", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 20.5, reboundsPerGame: 10.5, assistsPerGame: 4.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2020-21", yearLabel: "2020-21 (13 games)", sortOrder: 201, gamesPlayed: 13, minutesPerGame: 29.8, pointsPerGame: 11.2, reboundsPerGame: 6.1, assistsPerGame: 2.2, stealsPerGame: 1.2, fieldGoalPct: 0.521, threePointPct: 0.108, freeThrowPct: 0.632 },
        { level: "PROFESSIONAL", teamName: "Atlanta Hawks", season: "2021-22", yearLabel: "2021-22 (Rookie)", sortOrder: 301, gamesPlayed: 22, minutesPerGame: 9.5, pointsPerGame: 2.4, reboundsPerGame: 2.0, assistsPerGame: 0.5, fieldGoalPct: 0.432 },
        { level: "PROFESSIONAL", teamName: "Atlanta Hawks", season: "2022-23", yearLabel: "2022-23", sortOrder: 302, gamesPlayed: 65, minutesPerGame: 21.3, pointsPerGame: 7.2, reboundsPerGame: 5.0, assistsPerGame: 1.7, fieldGoalPct: 0.543 },
        { level: "PROFESSIONAL", teamName: "Atlanta Hawks", season: "2023-24", yearLabel: "2023-24 (Breakout)", sortOrder: 303, gamesPlayed: 66, minutesPerGame: 32.5, pointsPerGame: 16.0, reboundsPerGame: 8.3, assistsPerGame: 3.6, fieldGoalPct: 0.517, threePointPct: 0.316, freeThrowPct: 0.719 },
        { level: "PROFESSIONAL", teamName: "Atlanta Hawks", season: "2024-25", yearLabel: "2024-25", sortOrder: 304, gamesPlayed: 60, minutesPerGame: 34.0, pointsPerGame: 18.5, reboundsPerGame: 8.8, assistsPerGame: 4.0, fieldGoalPct: 0.520, threePointPct: 0.330, freeThrowPct: 0.730 },
      ],
      careerEvents: [
        { year: 2021, title: "Selected #20 overall by Atlanta Hawks", eventType: "DRAFT" },
        { year: 2024, title: "Signed 5-year, $150M max rookie extension", eventType: "CONTRACT" },
      ],
    },
    {
      slug: "matthew-hurt",
      firstName: "Matthew",
      lastName: "Hurt",
      birthYear: 2000,
      hometown: "Rochester, MN",
      highSchool: "John Marshall High School, Rochester, MN",
      bio: "Sophomore who led Duke in scoring at 18.3 PPG on 55.8% shooting. Named first-team All-ACC in a difficult season for the program.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        league: "G-League / Overseas",
        statusNote: "Went undrafted in 2021 despite being first-team All-ACC. Has played in the G-League.",
        sourceUrl: "https://en.wikipedia.org/wiki/Matthew_Hurt",
      },
      membership: { role: "PLAYER", jerseyNumber: 21, position: "Power Forward / Center", yearsAtSchool: "2019-2021", statsNote: "18.3 PPG (led team) · 1st-team All-ACC · 55.8% FG" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2020-21", yearLabel: "2020-21 (1st-team All-ACC)", sortOrder: 202, gamesPlayed: 24, minutesPerGame: 34.1, pointsPerGame: 18.3, reboundsPerGame: 6.2, assistsPerGame: 0.7, fieldGoalPct: 0.558, threePointPct: 0.441, freeThrowPct: 0.819 },
      ],
      careerEvents: [],
    },
    {
      slug: "dj-steward",
      firstName: "DJ",
      lastName: "Steward",
      birthYear: 2001,
      hometown: "Chicago, IL",
      highSchool: "Whitney Young High School, Chicago, IL",
      bio: "Freshman guard who averaged 13.0 PPG with explosive scoring ability. Left for the NBA Draft after one season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        league: "Overseas",
        statusNote: "Went undrafted in 2021 despite leaving Duke after one season. Has played in the G-League and overseas, including stints in Australia and Europe. His explosive athleticism translates well to international play.",
        sourceUrl: "https://en.wikipedia.org/wiki/DJ_Steward",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Shooting Guard", yearsAtSchool: "2020-2021", statsNote: "13.0 PPG · Explosive freshman scorer · Left for draft" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Whitney Young High School", season: "2019-20", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 24.0, reboundsPerGame: 5.5, assistsPerGame: 4.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2020-21", yearLabel: "2020-21", sortOrder: 201, gamesPlayed: 24, minutesPerGame: 32.5, pointsPerGame: 13.0, reboundsPerGame: 3.8, assistsPerGame: 1.6, fieldGoalPct: 0.415, threePointPct: 0.312, freeThrowPct: 0.800 },
      ],
      careerEvents: [
        { year: 2021, title: "Went undrafted; signed with G-League", eventType: "SIGNING" },
      ],
    },
    {
      slug: "mark-williams",
      firstName: "Mark",
      lastName: "Williams",
      birthYear: 2001,
      hometown: "Norfolk, VA",
      highSchool: "IMG Academy, Bradenton, FL",
      bio: "Freshman center who played limited minutes (11.2 MPG) as a raw prospect. Would explode as a sophomore to become the #15 pick in 2022.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "Charlotte Hornets",
        league: "NBA",
        location: "Charlotte, NC",
        statusNote: "Had his breakout sophomore season in 2021-22, winning ACC DPOY and being drafted #15. Now a starting center in the NBA.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mark_Williams_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Center", yearsAtSchool: "2020-2022", statsNote: "2.5 PPG, 2.5 RPG as raw freshman · Breakout sophomore (11.2 PPG, 2.8 BPG)" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2020-21", yearLabel: "2020-21", sortOrder: 201, gamesPlayed: 25, minutesPerGame: 11.2, pointsPerGame: 2.5, reboundsPerGame: 2.5, blocksPerGame: 1.2, fieldGoalPct: 0.636 },
      ],
      careerEvents: [],
    },
    {
      slug: "wendell-moore-jr",
      firstName: "Wendell",
      lastName: "Moore Jr.",
      birthYear: 2001,
      hometown: "Concord, NC",
      highSchool: "Cox Mill High School, Concord, NC",
      bio: "Sophomore who averaged 8.0 PPG while becoming a key two-way player. Would blossom as a junior to become a first-round pick.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard / Forward",
        league: "NBA / G-League",
        statusNote: "Selected #26 overall in 2022 after a breakout junior year (13.4 PPG, All-ACC).",
        sourceUrl: "https://en.wikipedia.org/wiki/Wendell_Moore_Jr.",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Small Forward", yearsAtSchool: "2019-2022", statsNote: "8.0 PPG, 4.0 RPG · Key rotation player" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2020-21", yearLabel: "2020-21", sortOrder: 202, gamesPlayed: 25, minutesPerGame: 24.2, pointsPerGame: 8.0, reboundsPerGame: 4.0, assistsPerGame: 2.3, fieldGoalPct: 0.398, threePointPct: 0.302 },
      ],
      careerEvents: [],
    },
    {
      slug: "jeremy-roach",
      firstName: "Jeremy",
      lastName: "Roach",
      birthYear: 2002,
      hometown: "Leesburg, VA",
      highSchool: "Paul VI Catholic High School, Chantilly, VA",
      bio: "Freshman point guard who started 20 games and showed poise beyond his years. Averaged 8.7 PPG and 3.3 APG in the COVID-shortened season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        league: "NBA / G-League",
        statusNote: "Became Duke's four-year starter at point guard. Part of Coach K's final team (2022 Final Four).",
        sourceUrl: "https://en.wikipedia.org/wiki/Jeremy_Roach",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Point Guard", yearsAtSchool: "2020-2024", statsNote: "8.7 PPG, 3.3 APG · Freshman starter · 4-year Duke player" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2020-21", yearLabel: "2020-21", sortOrder: 201, gamesPlayed: 24, minutesPerGame: 26.2, pointsPerGame: 8.7, reboundsPerGame: 1.8, assistsPerGame: 3.3, fieldGoalPct: 0.410, threePointPct: 0.347 },
      ],
      careerEvents: [],
    },
    {
      slug: "mike-krzyzewski",
      firstName: "Mike",
      lastName: "Krzyzewski",
      birthYear: 1947,
      hometown: "Chicago, IL",
      highSchool: "Weber High School, Chicago, IL",
      bio: "The worst season of Coach K's tenure at 13-11. Injuries, COVID protocols, and a difficult freshman class led to Duke's first losing ACC record (9-9) since 1994-95.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Retired Head Coach",
        currentEmployer: "Duke University (Emeritus)",
        location: "Durham, NC",
        statusNote: "Announced his retirement the following year. The 2020-21 season was his only losing record at Duke.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Krzyzewski",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "1980-2022", statsNote: "13-11 · Only losing season · COVID-impacted year" },
      seasonStats: [
        { level: "COACHING", teamName: "Duke Blue Devils", season: "2020-21", yearLabel: "2020-21 (COVID)", sortOrder: 1, wins: 13, losses: 11, tournamentResult: "Opted out of NCAA Tournament after positive COVID tests" },
      ],
      careerEvents: [],
    },
  ],
};
