import type { TeamSeed } from "./types";

export const dukeBasketball2010: TeamSeed = {
  slug: "duke-basketball-2010",
  name: "Duke Blue Devils",
  season: "2009-2010",
  sport: "Men's Basketball",
  school: "Duke University",
  conference: "ACC",
  accomplishment: "NCAA National Champions (35-5)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  mascotName: "Blue Devil",
  people: [
    {
      slug: "jon-scheyer",
      firstName: "Jon",
      lastName: "Scheyer",
      birthYear: 1987,
      hometown: "Northbrook, IL",
      highSchool: "Glenbrook North High School, Northbrook, IL",
      isFeatured: true,
      bio: "The senior captain who averaged 18.2 PPG and was a consensus Second-Team All-American. Scheyer would later become Duke's head coach, succeeding Coach K.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "Duke University",
        league: "ACC",
        location: "Durham, NC",
        statusNote:
          "After a brief playing career in Israel cut short by an eye condition, Scheyer joined Duke's coaching staff in 2013. Named Duke's 20th head coach in 2021, succeeding Coach K. His 124 wins through his first four seasons are the most by any D-I coach in history. In 2025-26, led Duke to a 35-3 record with ACC titles behind National POY Cameron Boozer. Named NABC Coach of the Year and signed a six-year extension through 2030-31.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jon_Scheyer",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 30,
        position: "Shooting Guard / Point Guard",
        yearsAtSchool: "2006-2010",
        statsNote: "Senior captain • 2nd-Team All-American • 18.2 PPG • National Champion",
        gamesPlayed: 38,
        pointsPerGame: 18.2,
        reboundsPerGame: 4.1,
        assistsPerGame: 4.9,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Glenbrook North High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 32.3, reboundsPerGame: 4.1, assistsPerGame: 8.4 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2006-07", yearLabel: "2006-07 (Freshman)", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 9.3, reboundsPerGame: 3.3, assistsPerGame: 1.7 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2007-08", yearLabel: "2007-08", sortOrder: 202, gamesPlayed: 34, pointsPerGame: 10.3, reboundsPerGame: 3.2, assistsPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2008-09", yearLabel: "2008-09", sortOrder: 203, gamesPlayed: 37, pointsPerGame: 14.9, reboundsPerGame: 3.6, assistsPerGame: 4.2 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2009-10", yearLabel: "2009-10 (Champion, All-American)", sortOrder: 204, gamesPlayed: 38, pointsPerGame: 18.2, reboundsPerGame: 4.1, assistsPerGame: 4.9, fieldGoalPct: 0.481, threePointPct: 0.436, freeThrowPct: 0.895 },
      ],
      careerEvents: [
        { year: 2010, title: "Won NCAA National Championship with Duke", eventType: "CHAMPIONSHIP" },
        { year: 2013, title: "Joined Duke coaching staff as special assistant", eventType: "CAREER" },
        { year: 2021, title: "Named Duke's 20th head coach, succeeding Coach K", eventType: "CAREER" },
        { year: 2026, title: "Named NABC Coach of the Year; Duke 35-3 with Cameron Boozer", eventType: "AWARD" },
      ],
    },
    {
      slug: "kyle-singler",
      firstName: "Kyle",
      lastName: "Singler",
      birthYear: 1988,
      hometown: "Medford, OR",
      highSchool: "South Medford High School, Medford, OR",
      isFeatured: true,
      bio: "The 2010 Final Four Most Outstanding Player who averaged 17.7 PPG as a junior. Singler holds Duke career records for games played (148) and consecutive games played.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "Oklahoma",
        statusNote: "Selected #33 overall in 2011. Played 8 NBA seasons with Pistons and Thunder. 2010 Final Four MOP. Holds Duke career records for games and minutes played. Retired in 2019.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kyle_Singler",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Small Forward", yearsAtSchool: "2007-2011", statsNote: "Junior • Final Four MOP • 17.7 PPG, 7.0 RPG", gamesPlayed: 38, pointsPerGame: 17.7, reboundsPerGame: 7.0, assistsPerGame: 1.9 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "South Medford High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 31.5, reboundsPerGame: 12.1, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2007-08", yearLabel: "2007-08 (Freshman)", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 13.3, reboundsPerGame: 5.6, assistsPerGame: 1.2 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2008-09", yearLabel: "2008-09", sortOrder: 202, gamesPlayed: 37, pointsPerGame: 17.0, reboundsPerGame: 6.3, assistsPerGame: 1.9 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2009-10", yearLabel: "2009-10 (Champion, Final Four MOP)", sortOrder: 203, gamesPlayed: 38, pointsPerGame: 17.7, reboundsPerGame: 7.0, assistsPerGame: 1.9, fieldGoalPct: 0.491, threePointPct: 0.415 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2010-11", yearLabel: "2010-11 (Senior)", sortOrder: 204, gamesPlayed: 37, pointsPerGame: 16.9, reboundsPerGame: 6.8, assistsPerGame: 1.6 },
      ],
      careerEvents: [
        { year: 2010, title: "Won NCAA Championship; named Final Four MOP", eventType: "CHAMPIONSHIP" },
        { year: 2011, title: "Selected #33 overall by Detroit Pistons", eventType: "DRAFT" },
      ],
    },
    {
      slug: "nolan-smith",
      firstName: "Nolan",
      lastName: "Smith",
      birthYear: 1988,
      hometown: "Upper Marlboro, MD",
      highSchool: "Oak Hill Academy, Mouth of Wilson, VA",
      isFeatured: true,
      bio: "A junior who averaged 17.4 PPG on the championship team. Would become ACC Player of the Year the following season.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "Tennessee State University",
        location: "Nashville, TN",
        statusNote: "After a brief NBA career (#21 pick, 2011), Smith returned to coaching. Now head coach at Tennessee State — led them to the OVC title and March Madness in his first season (2025-26), winning OVC Co-Coach of the Year with a program-record 23 wins.",
        sourceUrl: "https://hbcugameday.com/2026/03/09/duke-legend-nolan-smith-hbcu-tennessee-state-march-madness/",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Guard", yearsAtSchool: "2007-2011", statsNote: "Junior • 17.4 PPG • Third-Team All-ACC • National Champion", gamesPlayed: 38, pointsPerGame: 17.4, reboundsPerGame: 3.8, assistsPerGame: 5.1 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Oak Hill Academy", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 31.1, reboundsPerGame: 3.8, assistsPerGame: 8.6 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2009-10", yearLabel: "2009-10 (Champion)", sortOrder: 203, gamesPlayed: 38, pointsPerGame: 17.4, reboundsPerGame: 3.8, assistsPerGame: 5.1 },
      ],
      careerEvents: [
        { year: 2010, title: "Won NCAA National Championship", eventType: "CHAMPIONSHIP" },
        { year: 2025, title: "Named head coach at Tennessee State", eventType: "CAREER" },
        { year: 2026, title: "Led TSU to OVC title and March Madness", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "brian-zoubek",
      firstName: "Brian",
      lastName: "Zoubek",
      birthYear: 1988,
      hometown: "Haddonfield, NJ",
      highSchool: "Haddonfield Memorial High School, Haddonfield, NJ",
      isFeatured: false,
      bio: "The senior center who grabbed the most famous rebound in Duke history — the final rebound in the 2010 championship game, sealing Duke's 61-59 win over Butler.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Founder",
        currentEmployer: "Zoubek Properties",
        location: "Haddonfield, NJ",
        statusNote:
          "Set Duke's single-season offensive rebound record (145) as a senior. Famously grabbed the final rebound of the 2010 title game and was fouled, sealing Duke's 61-59 win over Butler. Went undrafted, briefly signed by the Nets. Opened Dream Puffz cream puff bakery in 2012 (closed 2013), then pivoted to real estate. Now runs Zoubek Properties in the Haddonfield, NJ area.",
        sourceUrl: "https://en.wikipedia.org/wiki/Brian_Zoubek",
        linkedInUrl: "https://www.linkedin.com/in/brianzoubek/",
      },
      membership: { role: "PLAYER", jerseyNumber: 55, position: "Center", yearsAtSchool: "2006-2010", statsNote: "Senior • Grabbed final rebound of title game • Duke record 145 offensive rebounds", gamesPlayed: 35, pointsPerGame: 4.1, reboundsPerGame: 7.7, assistsPerGame: 0.5 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Haddonfield Memorial High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 11.1, reboundsPerGame: 13.0, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2008-09", yearLabel: "2008-09", sortOrder: 202, gamesPlayed: 37, pointsPerGame: 2.2, reboundsPerGame: 2.5, assistsPerGame: 0.2 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2009-10", yearLabel: "2009-10 (Champion, final rebound!)", sortOrder: 203, gamesPlayed: 35, pointsPerGame: 4.1, reboundsPerGame: 7.7, assistsPerGame: 0.5 },
      ],
      careerEvents: [
        { year: 2010, title: "Won NCAA Championship (grabbed final rebound, sealing 61-59 win over Butler)", eventType: "CHAMPIONSHIP" },
        { year: 2012, title: "Opened Dream Puffz bakery in Haddonfield, NJ", eventType: "CAREER" },
        { year: 2013, title: "Founded Zoubek Properties (real estate)", eventType: "CAREER" },
      ],
    },
    {
      slug: "lance-thomas",
      firstName: "Lance",
      lastName: "Thomas",
      birthYear: 1988,
      hometown: "Scotch Plains, NJ",
      highSchool: "St. Benedict's Prep, Newark, NJ",
      isFeatured: false,
      bio: "A senior power forward and defensive specialist who earned All-ACC Defensive Team honors.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Basketball Operations",
        location: "New York, NY",
        statusNote:
          "Went undrafted but carved out an 8-year NBA career with New Orleans, OKC, and most notably the New York Knicks, where he was named co-captain in 2017-18 and became a beloved fan favorite. Averaged 5.1 PPG in 399 career NBA games. After being waived in 2019, he has been connected to the Brooklyn Nets organization in a basketball operations role.",
        sourceUrl: "https://en.wikipedia.org/wiki/Lance_Thomas",
      },
      membership: { role: "PLAYER", jerseyNumber: 42, position: "Power Forward", yearsAtSchool: "2006-2010", statsNote: "Senior • ACC All-Defensive Team • 4.8 PPG, 4.9 RPG", gamesPlayed: 38, pointsPerGame: 4.8, reboundsPerGame: 4.9, assistsPerGame: 0.5 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "St. Benedict's Prep", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 12.2, reboundsPerGame: 9.4, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2009-10", yearLabel: "2009-10 (Champion)", sortOrder: 204, gamesPlayed: 38, pointsPerGame: 4.8, reboundsPerGame: 4.9, assistsPerGame: 0.5 },
        { level: "PROFESSIONAL", teamName: "New Orleans Hornets", season: "2010-11", yearLabel: "2010-11", sortOrder: 301, gamesPlayed: 37, pointsPerGame: 3.0, reboundsPerGame: 2.0, assistsPerGame: 0.3 },
        { level: "PROFESSIONAL", teamName: "New York Knicks", season: "2015-16", yearLabel: "2015-16", sortOrder: 306, gamesPlayed: 63, pointsPerGame: 7.2, reboundsPerGame: 3.4, assistsPerGame: 0.9 },
        { level: "PROFESSIONAL", teamName: "New York Knicks", season: "2017-18", yearLabel: "2017-18 (Co-Captain)", sortOrder: 308, gamesPlayed: 46, pointsPerGame: 5.3, reboundsPerGame: 2.5, assistsPerGame: 0.6 },
      ],
      careerEvents: [
        { year: 2010, title: "Won NCAA National Championship", eventType: "CHAMPIONSHIP" },
        { year: 2015, title: "Signed with the New York Knicks", eventType: "SIGNING" },
        { year: 2017, title: "Named Knicks co-captain", eventType: "CAREER" },
      ],
    },
    {
      slug: "mason-plumlee",
      firstName: "Mason",
      lastName: "Plumlee",
      birthYear: 1990,
      hometown: "Warsaw, IN",
      highSchool: "Christ School, Arden, NC",
      isFeatured: false,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/203486.png",
      bio: "A freshman big man on the championship team who would develop into a first-round NBA pick over four years at Duke.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "Charlotte Hornets",
        league: "NBA",
        location: "Charlotte, NC",
        statusNote: "Selected #22 overall in 2013. Now in his 13th NBA season. 2016 Olympic gold medalist with Team USA.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mason_Plumlee",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Forward / Center", yearsAtSchool: "2009-2013", statsNote: "Freshman • National Champion • Youngest Plumlee brother", gamesPlayed: 36, pointsPerGame: 3.1, reboundsPerGame: 2.8, assistsPerGame: 0.3 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Christ School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 9.7, reboundsPerGame: 6.6, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2009-10", yearLabel: "2009-10 (Champion)", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 3.1, reboundsPerGame: 2.8, assistsPerGame: 0.3 },
      ],
      careerEvents: [
        { year: 2010, title: "Won NCAA National Championship", eventType: "CHAMPIONSHIP" },
        { year: 2013, title: "Selected #22 overall by Brooklyn Nets", eventType: "DRAFT" },
        { year: 2016, title: "Won Olympic Gold with Team USA", eventType: "AWARD" },
      ],
    },
    {
      slug: "ryan-kelly",
      firstName: "Ryan",
      lastName: "Kelly",
      birthYear: 1991,
      hometown: "Raleigh, NC",
      highSchool: "Ravenscroft School, Raleigh, NC",
      isFeatured: false,
      bio: "A freshman stretch forward who would play all four years at Duke. Now playing professionally in Japan's B.League.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Fukui Blowinds",
        league: "B.League (Japan)",
        location: "Fukui, Japan",
        statusNote: "Selected #48 overall by the Lakers in 2013. Played 4 NBA seasons with the Lakers and Hawks, then moved to Japan where he's played 7 seasons. Averaging 15.9 PPG, 6.5 RPG in 2025-26 with the Fukui Blowinds.",
        sourceUrl: "https://en.wikipedia.org/wiki/Ryan_Kelly_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 34, position: "Power Forward", yearsAtSchool: "2009-2013", statsNote: "Freshman • National Champion • Stretch four", gamesPlayed: 35, pointsPerGame: 3.4, reboundsPerGame: 2.7, assistsPerGame: 0.5 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Ravenscroft School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 10.1, reboundsPerGame: 6.5, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2009-10", yearLabel: "2009-10 (Champion)", sortOrder: 201, gamesPlayed: 35, pointsPerGame: 3.4, reboundsPerGame: 2.7, assistsPerGame: 0.5 },
      ],
      careerEvents: [
        { year: 2010, title: "Won NCAA National Championship", eventType: "CHAMPIONSHIP" },
        { year: 2013, title: "Selected #48 overall by the LA Lakers", eventType: "DRAFT" },
        { year: 2017, title: "Moved to Japan (Sun Rockers Shibuya)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "andre-dawkins",
      firstName: "Andre",
      lastName: "Dawkins",
      birthYear: 1991,
      hometown: "Chesapeake, VA",
      highSchool: "Atlantic Shores Christian School, Chesapeake, VA",
      isFeatured: false,
      bio: "A freshman sharpshooter on the championship team. Tragically lost his sister Lacey in a car accident during the season.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "Charlottesville High School",
        location: "Charlottesville, VA",
        statusNote: "After Duke, went undrafted. Brief NBA/G-League stints with Miami Heat. Transitioned to coaching — posted a 38-13 record over two seasons at Mount St. Mary HS in OKC before becoming head coach at Charlottesville High School and director of Pro Skills Basketball.",
        sourceUrl: "https://www.si.com/college/duke/basketball/duke-basketball-andre-dawkins-new-job",
      },
      membership: { role: "PLAYER", jerseyNumber: 20, position: "Shooting Guard", yearsAtSchool: "2009-2014", statsNote: "Freshman • National Champion • 7.6 PPG", gamesPlayed: 36, pointsPerGame: 7.6, reboundsPerGame: 1.8, assistsPerGame: 0.7 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Atlantic Shores Christian School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 16.4, reboundsPerGame: 1.8, assistsPerGame: 2.9 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2009-10", yearLabel: "2009-10 (Champion)", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 7.6, reboundsPerGame: 1.8, assistsPerGame: 0.7, threePointPct: 0.442 },
      ],
      careerEvents: [
        { year: 2009, title: "Sister Lacey killed in car accident while traveling to watch him play", eventType: "OTHER" },
        { year: 2010, title: "Won NCAA National Championship", eventType: "CHAMPIONSHIP" },
        { year: 2024, title: "Named head coach at Charlottesville HS", eventType: "CAREER" },
      ],
    },
    {
      slug: "mike-krzyzewski",
      firstName: "Mike",
      lastName: "Krzyzewski",
      birthYear: 1947,
      hometown: "Chicago, IL",
      highSchool: "Weber High School, Chicago, IL",
      isFeatured: true,
      bio: "Won his fourth national championship with a team built on upperclassmen leadership and depth.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Special Advisor / Duke Ambassador",
        currentEmployer: "NBA / Duke University",
        location: "Durham, NC",
        statusNote: "Retired after the 2021-22 season as the winningest coach in Division I men's basketball history with 1,202 victories across 47 seasons. Won five national championships, reached 13 Final Fours, and won three Olympic gold medals.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Krzyzewski",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "1980-2022", statsNote: "35-5 • 4th National Championship • ACC Regular Season & Tournament Champions" },
      careerEvents: [
        { year: 2010, title: "Won fourth NCAA National Championship", eventType: "CHAMPIONSHIP" },
        { year: 2022, title: "Retired as winningest coach in D-I history", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "seth-curry",
      firstName: "Seth",
      lastName: "Curry",
      birthYear: 1990,
      hometown: "Charlotte, NC",
      highSchool: "Charlotte Christian School, Charlotte, NC",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/203552.png",
      bio: "Younger brother of Stephen Curry who walked on at Duke as a freshman. Transferred to Liberty after his sophomore year before returning to Duke.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Golden State Warriors",
        league: "NBA",
        location: "San Francisco, CA",
        statusNote: "Has had an 11-year NBA career with Sacramento, Dallas, Portland, Philadelphia, Brooklyn, and Charlotte. Career 44.1% from three. Signed with Golden State in 2025.",
        sourceUrl: "https://en.wikipedia.org/wiki/Seth_Curry",
      },
      membership: { role: "PLAYER", jerseyNumber: 30, position: "Guard", yearsAtSchool: "2008-2013", statsNote: "3.5 PPG as freshman · Later became NBA sharpshooter" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Charlotte Christian School", season: "2007-08", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 22.3, reboundsPerGame: 3.5, assistsPerGame: 4.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2009-10", yearLabel: "2009-10 (Champion)", sortOrder: 201, gamesPlayed: 25, minutesPerGame: 5.2, pointsPerGame: 3.5, reboundsPerGame: 0.5, fieldGoalPct: 0.419, threePointPct: 0.364 },
      ],
      careerEvents: [],
    },
    {
      slug: "andre-dawkins",
      firstName: "Andre",
      lastName: "Dawkins",
      birthYear: 1991,
      hometown: "Chesapeake, VA",
      highSchool: "Atlantic Shores Christian School, Chesapeake, VA",
      bio: "Freshman sharpshooter who provided bench scoring on the championship team. Hit key three-pointers throughout the run.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "Charlottesville High School",
        location: "Charlottesville, VA",
        statusNote: "After Duke, had a brief NBA stint with Orlando. Now coaches high school basketball.",
        sourceUrl: "https://en.wikipedia.org/wiki/Andre_Dawkins",
      },
      membership: { role: "PLAYER", jerseyNumber: 20, position: "Shooting Guard", yearsAtSchool: "2009-2014", statsNote: "5.3 PPG · Freshman bench scorer · Sharpshooter" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Atlantic Shores Christian", season: "2008-09", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 24.0, reboundsPerGame: 4.5, assistsPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2009-10", yearLabel: "2009-10 (Champion)", sortOrder: 201, gamesPlayed: 36, minutesPerGame: 12.5, pointsPerGame: 5.3, reboundsPerGame: 1.2, fieldGoalPct: 0.421, threePointPct: 0.385 },
      ],
      careerEvents: [],
    },
    {
      slug: "ryan-kelly",
      firstName: "Ryan",
      lastName: "Kelly",
      birthYear: 1991,
      hometown: "Zionsville, IN",
      highSchool: "Ravenscroft School, Raleigh, NC",
      bio: "Freshman forward who played limited minutes on the championship team but would develop into a starter by his junior and senior years.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "Fukui Blowinds (Japan B.League)",
        league: "Japan B.League",
        location: "Fukui, Japan",
        statusNote: "Played two NBA seasons with the Lakers. Has played overseas in Japan for several seasons.",
        sourceUrl: "https://en.wikipedia.org/wiki/Ryan_Kelly_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 34, position: "Power Forward", yearsAtSchool: "2009-2013", statsNote: "1.0 PPG as freshman · Became starter by junior year" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Ravenscroft School", season: "2008-09", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 18.5, reboundsPerGame: 8.0, blocksPerGame: 2.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2009-10", yearLabel: "2009-10 (Champion)", sortOrder: 201, gamesPlayed: 30, minutesPerGame: 4.5, pointsPerGame: 1.0, reboundsPerGame: 0.8, fieldGoalPct: 0.400 },
      ],
      careerEvents: [],
    },
    {
      slug: "tyler-thornton",
      firstName: "Tyler",
      lastName: "Thornton",
      birthYear: 1991,
      hometown: "Silver Spring, MD",
      highSchool: "Gonzaga College High School, Washington, DC",
      bio: "Freshman guard and defensive specialist who contributed on the championship team. Son of former Georgetown player Al Thornton.",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Coach",
        currentEmployer: "Duke University",
        location: "Durham, NC",
        statusNote: "Returned to Duke as an assistant coach in 2025 under Jon Scheyer after coaching at Howard University.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Guard", yearsAtSchool: "2009-2013", statsNote: "1.2 PPG · Defensive specialist · 2010 champion" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Gonzaga College High School", season: "2008-09", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 14.0, reboundsPerGame: 3.0, assistsPerGame: 5.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2009-10", yearLabel: "2009-10 (Champion)", sortOrder: 201, gamesPlayed: 33, minutesPerGame: 5.8, pointsPerGame: 1.2, reboundsPerGame: 0.5, assistsPerGame: 0.5, fieldGoalPct: 0.350, threePointPct: 0.310 },
      ],
      careerEvents: [
        { year: 2025, title: "Hired as assistant coach at Duke", eventType: "COACHING" },
      ],
    },
    {
      slug: "olek-czyz",
      firstName: "Olek",
      lastName: "Czyz",
      birthYear: 1990,
      hometown: "Madison, WI",
      highSchool: "Madison Memorial High School, Madison, WI",
      bio: "Walk-on forward who was a part of the 2010 championship roster. Contributed in practice and earned playing time in blowouts.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Private Citizen",
        location: "Madison, WI",
        statusNote: "Walk-on who graduated from Duke. Transitioned to business after graduation.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster",
      },
      membership: { role: "PLAYER", jerseyNumber: 24, position: "Forward", yearsAtSchool: "2008-2012", statsNote: "Walk-on · 2010 champion" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2009-10", yearLabel: "2009-10 (Champion)", sortOrder: 201, gamesPlayed: 10, minutesPerGame: 2.0, pointsPerGame: 0.5, reboundsPerGame: 0.5 },
      ],
      careerEvents: [],
    },
  ],
};
