import type { TeamSeed } from "./types";

export const dukeBasketball2004: TeamSeed = {
  slug: "duke-basketball-2004",
  name: "Duke Blue Devils",
  season: "2003-2004",
  sport: "Men's Basketball",
  school: "Duke University",
  conference: "ACC",
  accomplishment: "Final Four (31-6)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  mascotName: "Blue Devil",
  people: [
    {
      slug: "luol-deng",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/2736.png",
      firstName: "Luol",
      lastName: "Deng",
      birthYear: 1985,
      hometown: "London, England (born in Wau, Sudan)",
      highSchool: "Blair Academy, Blairstown, NJ",
      isFeatured: true,
      bio: "A one-and-done freshman sensation who led Duke to the Final Four in 2004, averaging 15.1 points. Deng was born in war-torn Sudan and became a global basketball ambassador.",
      status: {
        occupationType: "FRONT_OFFICE",
        currentTitle: "President, South Sudan Basketball Federation",
        location: "London, England",
        statusNote:
          "Selected #7 overall by the Chicago Bulls in 2004, Deng was a two-time All-Star earning ~$151M over a 15-year NBA career. After retiring in 2019, he became president of the South Sudan Basketball Federation, personally funding the entire program out of his own pocket — including the historic run to the 2024 Paris Olympics where South Sudan beat Puerto Rico for their first Olympic win. Re-elected president in 2024, he also serves as assistant coach. Has an extensive real estate portfolio valued at ~$200M. Born in war-torn Sudan, he fled civil war as a child and grew up in London.",
        sourceUrl: "https://en.wikipedia.org/wiki/Luol_Deng",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 9,
        position: "Small Forward",
        yearsAtSchool: "2003-2004",
        statsNote: "One-and-done • Led Duke to Final Four • #7 overall pick",
        gamesPlayed: 37,
        pointsPerGame: 15.1,
        reboundsPerGame: 6.9,
        assistsPerGame: 1.9,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2003-2004", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 15.1, reboundsPerGame: 6.9, assistsPerGame: 1.9 },
      ],
      careerEvents: [
        { year: 2004, title: "Selected #7 overall by the Chicago Bulls", eventType: "DRAFT" },
        { year: 2012, title: "Named NBA All-Star", eventType: "AWARD" },
        { year: 2019, title: "Retired from NBA; became president of South Sudan Basketball", eventType: "CAREER" },
        { year: 2024, title: "Led South Sudan to first-ever Olympic Games appearance", eventType: "CAREER" },
      ],
    },
    {
      slug: "chris-duhon",
      firstName: "Chris",
      lastName: "Duhon",
      birthYear: 1982,
      hometown: "Slidell, LA",
      highSchool: "Salmen High School, Slidell, LA",
      isFeatured: false,
      bio: "A four-year starter who captained the 2004 Final Four team as a senior.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "Gaston Christian School",
        location: "North Carolina",
        statusNote:
          "After going undrafted in 2004, Duhon signed with the Chicago Bulls as a free agent and played nine NBA seasons with the Bulls, Knicks, Magic, and Lakers. He was a key starter for the Knicks in 2008-09, setting a then-franchise record with 22 assists in a game. After retiring in 2013, he transitioned to coaching — assistant at Marshall (2014-17), Illinois State (2018-19), director of scouting at Bryant (2021-23). Inducted into the Greater New Orleans Sports Hall of Fame in 2024, he now serves as head basketball coach at Gaston Christian School in North Carolina.",
        sourceUrl: "https://en.wikipedia.org/wiki/Chris_Duhon",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 21,
        position: "Point Guard",
        yearsAtSchool: "2000-2004",
        statsNote: "Senior captain • Four-year starter • 2001 National Champion",
        gamesPlayed: 37,
        pointsPerGame: 10.2,
        assistsPerGame: 6.2,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2000-2001", yearLabel: "Freshman (National Champion)", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 4.3, reboundsPerGame: 1.7, assistsPerGame: 3.2, stealsPerGame: 1.2 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2001-2002", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 35, pointsPerGame: 8.5, reboundsPerGame: 2.8, assistsPerGame: 5.9, stealsPerGame: 1.9 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2002-2003", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 33, pointsPerGame: 9.8, reboundsPerGame: 2.5, assistsPerGame: 5.7, stealsPerGame: 1.6 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2003-2004", yearLabel: "Senior (Captain)", sortOrder: 204, gamesPlayed: 37, pointsPerGame: 10.2, reboundsPerGame: 3.0, assistsPerGame: 6.2, stealsPerGame: 1.8, fieldGoalPct: 0.413, threePointPct: 0.386, freeThrowPct: 0.815 },
        { level: "PROFESSIONAL", teamName: "Chicago Bulls", season: "2004-05", yearLabel: "2004-05", sortOrder: 301, gamesPlayed: 82, pointsPerGame: 5.9, reboundsPerGame: 2.1, assistsPerGame: 4.9, stealsPerGame: 0.8, fieldGoalPct: 0.381, threePointPct: 0.361 },
        { level: "PROFESSIONAL", teamName: "Chicago Bulls", season: "2005-06", yearLabel: "2005-06", sortOrder: 302, gamesPlayed: 82, pointsPerGame: 6.0, reboundsPerGame: 2.5, assistsPerGame: 5.0, fieldGoalPct: 0.397, threePointPct: 0.386 },
        { level: "PROFESSIONAL", teamName: "New York Knicks", season: "2008-09", yearLabel: "2008-09 (22-ast game)", sortOrder: 305, gamesPlayed: 79, pointsPerGame: 11.1, reboundsPerGame: 3.5, assistsPerGame: 7.2, stealsPerGame: 1.3, fieldGoalPct: 0.397, threePointPct: 0.395 },
      ],
      careerEvents: [
        { year: 2004, title: "Signed with Chicago Bulls as undrafted free agent", eventType: "SIGNING" },
      ],
    },
    {
      slug: "jj-redick",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/3024.png",
      firstName: "J.J.",
      lastName: "Redick",
      birthYear: 1984,
      hometown: "Roanoke, VA",
      highSchool: "Cave Spring High School, Roanoke, VA",
      isFeatured: true,
      bio: "Duke's all-time leading scorer who became one of the greatest shooters in both college and NBA history.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Coach",
        currentEmployer: "Los Angeles Lakers",
        league: "NBA",
        location: "Los Angeles, CA",
        statusNote:
          "After 15 NBA seasons as an elite shooter, Redick retired in 2021 and built a media empire with 'The Old Man and the Three' podcast. In June 2024, he was hired as head coach of the Los Angeles Lakers.",
        sourceUrl: "https://en.wikipedia.org/wiki/J._J._Redick",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 4,
        position: "Shooting Guard",
        yearsAtSchool: "2002-2006",
        statsNote: "Sophomore sharpshooter • Led team in scoring",
        gamesPlayed: 37,
        pointsPerGame: 15.9,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2003-2004", yearLabel: "Sophomore", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 15.9 },
      ],
      careerEvents: [
        { year: 2006, title: "Selected #11 overall by the Orlando Magic", eventType: "DRAFT" },
        { year: 2024, title: "Named head coach of the Los Angeles Lakers", eventType: "CAREER" },
      ],
    },
    {
      slug: "shelden-williams",
      firstName: "Shelden",
      lastName: "Williams",
      birthYear: 1983,
      hometown: "Midwest City, OK",
      highSchool: "Midwest City High School, Midwest City, OK",
      isFeatured: false,
      bio: "A dominant shot-blocking center who became Duke's all-time leader in blocked shots.",
      status: {
        occupationType: "COACH",
        currentTitle: "Podcast Host / Foundation Director",
        location: "Atlanta, GA",
        statusNote:
          "Selected #5 overall by the Hawks in 2006, Williams played six NBA seasons. He is now involved in youth basketball coaching in Atlanta.",
        sourceUrl: "https://en.wikipedia.org/wiki/Shelden_Williams",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 23,
        position: "Center / Power Forward",
        yearsAtSchool: "2002-2006",
        statsNote: "Sophomore starter • Emerging defensive force",
        gamesPlayed: 37,
        pointsPerGame: 11.2,
        reboundsPerGame: 8.3,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2003-2004", yearLabel: "Sophomore", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 11.2, reboundsPerGame: 8.3 },
      ],
      careerEvents: [
        { year: 2006, title: "Selected #5 overall by the Atlanta Hawks", eventType: "DRAFT" },
      ],
    },
    {
      slug: "daniel-ewing",
      firstName: "Daniel",
      lastName: "Ewing",
      birthYear: 1983,
      hometown: "Houston, TX",
      highSchool: "Willowridge High School, Houston, TX",
      isFeatured: false,
      bio: "A four-year contributor who developed into one of Duke's top scorers.",
      status: {
        occupationType: "FRONT_OFFICE",
        currentTitle: "Professional Scout",
        currentEmployer: "Los Angeles Lakers",
        league: "NBA",
        location: "Los Angeles, CA",
        statusNote:
          "Selected 32nd overall by the LA Clippers in 2005, Ewing played briefly in the NBA before spending nearly a decade playing professionally overseas in France, Spain, and Italy. In September 2022, he joined the Los Angeles Lakers as a professional scout in their scouting department under Jesse Buss, evaluating domestic and international talent for one of the NBA's marquee franchises.",
        sourceUrl: "https://en.wikipedia.org/wiki/Daniel_Ewing",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 5,
        position: "Shooting Guard",
        yearsAtSchool: "2001-2005",
        statsNote: "Junior starter • Key scorer",
        gamesPlayed: 37,
        pointsPerGame: 13.5,
        assistsPerGame: 3.2,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2003-2004", yearLabel: "Junior", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 13.5, assistsPerGame: 3.2 },
      ],
      careerEvents: [
        { year: 2005, title: "Selected #32 overall by the LA Clippers", eventType: "DRAFT" },
      ],
    },
    {
      slug: "shavlik-randolph",
      firstName: "Shavlik",
      lastName: "Randolph",
      birthYear: 1983,
      hometown: "Raleigh, NC",
      highSchool: "Broughton High School, Raleigh, NC",
      isFeatured: false,
      bio: "A McDonald's All-American power forward from Raleigh.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Owner / Investor",
        currentEmployer: "Big Prime Hauling",
        location: "Raleigh, NC",
        statusNote:
          "Randolph went undrafted but played in the NBA with the 76ers and Celtics. After retiring, he invested in Big Prime Hauling, a trucking company in North Carolina.",
        sourceUrl: "https://en.wikipedia.org/wiki/Shavlik_Randolph",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 42,
        position: "Power Forward",
        yearsAtSchool: "2002-2006",
        statsNote: "Sophomore contributor",
        gamesPlayed: 37,
        pointsPerGame: 6.8,
        reboundsPerGame: 4.5,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2003-2004", yearLabel: "Sophomore", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 6.8, reboundsPerGame: 4.5 },
      ],
      careerEvents: [
        { year: 2006, title: "Went undrafted; signed with Philadelphia 76ers", eventType: "SIGNING" },
      ],
    },
    {
      slug: "sean-dockery",
      firstName: "Sean",
      lastName: "Dockery",
      birthYear: 1985,
      hometown: "Milwaukee, WI",
      highSchool: "Vincent High School, Milwaukee, WI",
      isFeatured: false,
      bio: "A quick, athletic point guard who backed up Duhon and is remembered for his buzzer-beating half-court shot against Virginia Tech in 2005.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Owner / Basketball Trainer",
        currentEmployer: "Dockery Basketball Academy",
        location: "San Antonio, TX",
        statusNote:
          "After Duke, Dockery played professionally overseas before working as a player development coach for the San Antonio Spurs (2016-17) and Memphis Grizzlies (2017-18). He now runs Dockery Basketball Academy in San Antonio, a year-round training program for youth and professional players. Best remembered for his buzzer-beating half-court shot against Virginia Tech in 2005.",
        sourceUrl: "http://www.dockerybasketball.com/about-us/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 3,
        position: "Point Guard",
        yearsAtSchool: "2003-2007",
        statsNote: "Freshman backup PG • Athletic defender",
      },
            seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2003-2004", yearLabel: "Sophomore", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 3.0, reboundsPerGame: 1.4, assistsPerGame: 1.3 },
      ],
      careerEvents: [
        { year: 2007, title: "Graduated from Duke; began overseas career", eventType: "CAREER" },
      ],
    },
    {
      slug: "lee-melchionni",
      firstName: "Lee",
      lastName: "Melchionni",
      birthYear: 1983,
      hometown: "Germantown, PA",
      highSchool: "Germantown Academy, Fort Washington, PA",
      isFeatured: false,
      bio: "A sharpshooting guard who became an NBA sports agent after Duke.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Sports Agent",
        currentEmployer: "Wasserman Media Group",
        location: "Los Angeles, CA",
        statusNote: "Nicknamed 'The Landlord' at Duke, Williams holds the school's career records for blocks and rebounds. Selected #5 overall by the Atlanta Hawks in 2006, he played six NBA seasons with the Hawks, Kings, Celtics, Nuggets, and Nets. Inducted into the Duke Athletics Hall of Fame in 2018. After retiring, he founded the Shelden Williams Foundation in 2019 to empower student-athletes through education and community involvement, and hosts the 'Bleav in Duke' podcast covering Blue Devils basketball.",
        sourceUrl: "https://lancasteronline.com/sports/nba/basketball-still-melchionni-s-business/article_f4a85d66-0400-11e4-a2ab-001a4bcf6878.html",
      },
      membership: { role: "PLAYER", jerseyNumber: 20, position: "Shooting Guard", yearsAtSchool: "2002-2006", statsNote: "Sophomore • Perimeter shooter" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2003-2004", yearLabel: "Sophomore", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 6.5, reboundsPerGame: 2.2, assistsPerGame: 1.0 },
      ],
      careerEvents: [{ year: 2010, title: "Became NBA agent at Wasserman Media Group", eventType: "CAREER" }],
    },
    {
      slug: "nick-horvath",
      firstName: "Nick",
      lastName: "Horvath",
      birthYear: 1981,
      hometown: "Shoreview, MN",
      highSchool: "Mounds View High School, Shoreview, MN",
      isFeatured: false,
      bio: "A fifth-year senior completing his Duke career. Double-majored in Physics and English.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Physics Teacher / Author",
        currentEmployer: "Palmerston North Boys' High School",
        location: "Palmerston North, New Zealand",
        statusNote: "After a five-year Duke career including the 2001 national championship and a double major in Physics and English, Horvath played 12 years of professional basketball in Australia (West Sydney Razorbacks, Adelaide 36ers) and New Zealand. After retiring in 2016, he became a physics teacher and head basketball coach at Palmerston North Boys' High School in New Zealand. He has also become a published fiction author, writing the 'Sledge vs.' action-noir book series on Amazon. Featured in Physics World's 'Once a Physicist' series.",
        sourceUrl: "https://en.wikipedia.org/wiki/Nick_Horvath",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Forward", yearsAtSchool: "1999-2004", statsNote: "Fifth-year senior • 2001 champion" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2000-2001", yearLabel: "Sophomore (6 games, knee injury)", sortOrder: 201, gamesPlayed: 6, pointsPerGame: 2.8, reboundsPerGame: 2.3, assistsPerGame: 0.2 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2001-2002", yearLabel: "Junior", sortOrder: 202, gamesPlayed: 31, pointsPerGame: 1.5, reboundsPerGame: 2.1, assistsPerGame: 0.2 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2002-2003", yearLabel: "Senior", sortOrder: 203, gamesPlayed: 33, pointsPerGame: 4.5, reboundsPerGame: 2.8, assistsPerGame: 0.4 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2003-2004", yearLabel: "Fifth-year Senior", sortOrder: 204, gamesPlayed: 37, pointsPerGame: 3.2, reboundsPerGame: 2.5, assistsPerGame: 0.3 },
      ],
      careerEvents: [{ year: 2016, title: "Became physics teacher in New Zealand", eventType: "CAREER" }],
    },
    {
      slug: "reggie-love",
      firstName: "Reggie",
      lastName: "Love",
      birthYear: 1982,
      hometown: "Charlotte, NC",
      highSchool: "Providence Day School, Charlotte, NC",
      isFeatured: false,
      bio: "Two-sport athlete who later became personal aide to President Obama.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Partner and Vice President",
        currentEmployer: "Transatlantic Holdings",
        location: "Washington, D.C.",
        statusNote: "After graduating from Duke in 2005 (where he was a two-sport athlete in basketball and football, and member of the 2001 championship team), Love joined Barack Obama's presidential campaign in 2007 and served as the President's personal aide ('body man') from 2009 to 2011. He earned his MBA from Wharton in 2013, published the NYT bestseller 'Power Forward: My Presidential Education,' and built a career in finance and consulting. Previously Partner at RON Transatlantic EG (2012-2019), he is now Senior Advisor at Apollo Global Management.",
        sourceUrl: "https://en.wikipedia.org/wiki/Reggie_Love",
      },
      membership: { role: "PLAYER", jerseyNumber: 42, position: "Forward", yearsAtSchool: "2000-2005", statsNote: "Junior • Two-sport athlete" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2003-2004", yearLabel: "Junior", sortOrder: 201, gamesPlayed: 35, pointsPerGame: 1.5, reboundsPerGame: 0.9, assistsPerGame: 0.3 },
      ],
      careerEvents: [{ year: 2009, title: "Named personal aide to President Obama", eventType: "CAREER" }],
    },
    {
      slug: "andy-borman",
      firstName: "Andy",
      lastName: "Borman",
      birthYear: 1981,
      hometown: "Morrisville, NC",
      highSchool: "Fayetteville Academy, Fayetteville, NC",
      isFeatured: false,
      bio: "Coach K's nephew completing his five-year Duke career.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "Memphis, TN",
        statusNote: "Coach K's nephew (his mother is the sister of Krzyzewski's wife Mickie) and grandson of astronaut Frank Borman. A five-year walk-on who also played soccer at Duke. Built a career in basketball development: Director of Basketball Operations at San Jose State, Director of Player Development at Cal, Executive Director of the New York Renaissance Nike EYBL program (helping 100+ players earn D-I scholarships including Jonathan Kuminga and Hamidou Diallo), and assistant coach at Memphis under Penny Hardaway (2022-2024). Let go from Memphis in May 2024; current role unconfirmed.",
        sourceUrl: "https://gotigersgo.com/sports/mens-basketball/roster/coaches/andy-borman/3542",
      },
      membership: { role: "PLAYER", jerseyNumber: 40, position: "Guard", yearsAtSchool: "1999-2004", statsNote: "Senior walk-on • Coach K's nephew" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2003-2004", yearLabel: "Senior walk-on", sortOrder: 201, gamesPlayed: 20, pointsPerGame: 0.5, reboundsPerGame: 0.3, assistsPerGame: 0.1 },
      ],
      careerEvents: [{ year: 2022, title: "Joined Memphis as assistant coach", eventType: "CAREER" }],
    },
    {
      slug: "joe-pagliuca",
      firstName: "Joe",
      lastName: "Pagliuca",
      birthYear: 1982,
      hometown: "Weston, MA",
      highSchool: "Buckingham Browne & Nichols, Cambridge, MA",
      isFeatured: false,
      bio: "A walk-on guard and team's lone senior in 2003-04 who won the Dr. Deryl Hart Award as Duke basketball's top scholar-athlete. Son of Boston Celtics co-owner Stephen Pagliuca.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Co-Founder and President",
        currentEmployer: "Parquet Capital",
        location: "Boston, MA",
        linkedInUrl: "https://www.linkedin.com/in/joseph-pagliuca-81352436/",
        statusNote:
          "BSc in Economics from Duke (cum laude, 3.8 GPA), MBA from Harvard Business School (2012). Co-founded Parquet Capital in 2017, an alternative investment management firm. Son of Stephen Pagliuca (Boston Celtics co-owner, Bain Capital co-chairman). His wife Felicia co-founded Semma Therapeutics (diabetes cell therapy, acquired by Vertex).",
        sourceUrl: "https://www.linkedin.com/in/joseph-pagliuca-81352436/",
      },
      membership: { role: "PLAYER", jerseyNumber: 43, position: "Guard", yearsAtSchool: "2000-2004", statsNote: "Senior walk-on • Hart Award winner • Son of Celtics co-owner" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2003-2004", yearLabel: "Walk-on", sortOrder: 201, gamesPlayed: 4, pointsPerGame: 0.0, reboundsPerGame: 0.0, assistsPerGame: 0.0 },
      ],
      careerEvents: [{ year: 2004, title: "Won Dr. Deryl Hart Award as top scholar-athlete", eventType: "AWARD" }],
    },
    {
      slug: "michael-thompson-duke",
      firstName: "Michael",
      lastName: "Thompson",
      birthYear: 1983,
      hometown: "Joliet, IL",
      highSchool: "Providence Catholic High School, New Lenox, IL",
      isFeatured: false,
      bio: "A McDonald's All-American center who transferred mid-season to Northwestern.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Citizen",
        statusNote: "A McDonald's All-American center from the highly rated 2002 recruiting class who appeared in 16 games at Duke in 2002-03 and 3 games in 2003-04 before transferring to Northwestern in January 2004. His career at Northwestern was impacted by an irregular heartbeat condition. Post-college career information is limited; he may have played briefly overseas.",
        sourceUrl: "https://www.sports-reference.com/cbb/players/michael-thompson-1.html",
      },
      membership: { role: "PLAYER", jerseyNumber: 33, position: "Center", yearsAtSchool: "2002-2004", statsNote: "Sophomore • Transferred mid-season to Northwestern" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2003-2004", yearLabel: "Sophomore", sortOrder: 201, gamesPlayed: 3, pointsPerGame: 0.7, reboundsPerGame: 0.3, assistsPerGame: 0.0 },
      ],
      careerEvents: [{ year: 2004, title: "Transferred to Northwestern", eventType: "OTHER" }],
    },
    {
      slug: "matt-christensen",
      firstName: "Matt",
      lastName: "Christensen",
      birthYear: 1977,
      hometown: "Belmont, MA",
      highSchool: "Belmont High School, Belmont, MA",
      isFeatured: false,
      bio: "A senior with extra eligibility from his Mormon mission. Christensen played 97 career games at Duke across his unusual 5-season career.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "CEO and Portfolio Manager",
        currentEmployer: "Rose Park Advisors",
        location: "Boston, MA",
        statusNote: "Earned MBA from Harvard Business School. Now CEO and portfolio manager at Rose Park Advisors, a Boston-based investment firm focused on disruptive innovation.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/matt-christensen/11543",
      },
      membership: { role: "PLAYER", jerseyNumber: 41, position: "Forward / Center", yearsAtSchool: "1995-2004", statsNote: "Senior • 97 career games • 2001 National Champion" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2003-2004", yearLabel: "Senior", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 2.5, reboundsPerGame: 2.0, assistsPerGame: 0.3 },
      ],
      careerEvents: [
        { year: 2001, title: "Won NCAA National Championship with Duke", eventType: "CHAMPIONSHIP" },
        { year: 2004, title: "Earned MBA from Harvard Business School", eventType: "CAREER" },
      ],
    },
    {
      slug: "mike-krzyzewski",
      firstName: "Mike",
      lastName: "Krzyzewski",
      birthYear: 1947,
      hometown: "Chicago, IL",
      highSchool: "Weber High School, Chicago, IL",
      isFeatured: true,
      bio: "The winningest coach in Division I men's basketball history.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Special Advisor / Duke Ambassador",
        currentEmployer: "NBA / Duke University",
        location: "Durham, NC",
        statusNote:
          "Retired after the 2021-22 season as the winningest coach in Division I men's basketball history with 1,202 victories across 47 seasons (5 at Army, 42 at Duke). Won five national championships (1991, 1992, 2001, 2010, 2015), reached 13 Final Fours, and won three Olympic gold medals as Team USA coach (2008, 2012, 2016). Now serves as Special Advisor to NBA Commissioner Adam Silver, Ambassador to Duke University, professor at Duke's Fuqua School of Business, and hosts 'Basketball and Beyond with Coach K' on SiriusXM.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Krzyzewski",
      },
      membership: {
        role: "HEAD_COACH",
        position: "Head Coach",
        yearsAtSchool: "1980-2022",
        statsNote: "31-6 record in 2003-04 • Final Four",
      },
      careerEvents: [
        { year: 2022, title: "Retired as winningest coach in D-I history", eventType: "RETIREMENT" },
      ],
    },
  ],
};
