import type { TeamSeed } from "./types";

export const dukeBasketball2003: TeamSeed = {
  slug: "duke-basketball-2003",
  name: "Duke Blue Devils",
  season: "2002-2003",
  sport: "Men's Basketball",
  school: "Duke University",
  conference: "ACC",
  accomplishment: "Sweet Sixteen (26-7)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  mascotName: "Blue Devil",
  people: [
    {
      slug: "chris-duhon",
      firstName: "Chris",
      lastName: "Duhon",
      birthYear: 1982,
      hometown: "Slidell, LA",
      highSchool: "Salmen High School, Slidell, LA",
      isFeatured: false,
      bio: "A McDonald's All-American point guard who was a four-year starter at Duke, known for defensive intensity.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "Gaston Christian School",
        location: "North Carolina",
        statusNote:
          "After a nine-year NBA career with the Bulls, Knicks, Magic, and Lakers, Duhon transitioned to coaching. He currently serves as head basketball coach at Gaston Christian School in North Carolina.",
        sourceUrl: "https://en.wikipedia.org/wiki/Chris_Duhon",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 21,
        position: "Point Guard",
        yearsAtSchool: "2000-2004",
        statsNote: "Junior starter • Floor general",
        gamesPlayed: 33,
        pointsPerGame: 9.8,
        assistsPerGame: 5.7,
      },
      careerEvents: [
        { year: 2001, title: "Won NCAA National Championship with Duke", eventType: "CHAMPIONSHIP" },
        { year: 2004, title: "Signed with Chicago Bulls as undrafted free agent", eventType: "SIGNING" },
      ],
    },
    {
      slug: "dahntay-jones",
      firstName: "Dahntay",
      lastName: "Jones",
      birthYear: 1980,
      hometown: "Trenton, NJ",
      highSchool: "Steinert High School, Hamilton Township, NJ",
      isFeatured: false,
      bio: "A tough, physical guard/forward who transferred from Rutgers. Jones was known for his defensive toughness.",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Coach",
        currentEmployer: "Los Angeles Clippers",
        league: "NBA",
        location: "Los Angeles, CA",
        statusNote:
          "Selected #20 overall in 2003, Jones played 14 NBA seasons and won a title with Cleveland in 2016. He is now an assistant coach with the LA Clippers.",
        sourceUrl: "https://en.wikipedia.org/wiki/Dahntay_Jones",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 30,
        position: "Shooting Guard / Small Forward",
        yearsAtSchool: "2001-2003",
        statsNote: "Senior captain • Drafted #20 overall",
        gamesPlayed: 33,
        pointsPerGame: 14.4,
        reboundsPerGame: 4.7,
      },
      careerEvents: [
        { year: 2003, title: "Selected #20 overall by the Celtics (traded to Memphis)", eventType: "DRAFT" },
        { year: 2016, title: "Won NBA Championship with Cleveland Cavaliers", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "jj-redick",
      firstName: "J.J.",
      lastName: "Redick",
      birthYear: 1984,
      hometown: "Roanoke, VA",
      highSchool: "Cave Spring High School, Roanoke, VA",
      isFeatured: true,
      bio: "Duke's all-time leading scorer and one of the greatest shooters in college basketball history. Redick was a two-time consensus All-American who played 15 NBA seasons.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Coach",
        currentEmployer: "Los Angeles Lakers",
        league: "NBA",
        location: "Los Angeles, CA",
        statusNote:
          "Selected #11 overall by the Orlando Magic in 2006, Redick played 15 NBA seasons with the Magic, Bucks, Clippers, 76ers, Pelicans, and Mavericks, becoming one of the league's elite three-point shooters. After retiring in 2021, he launched 'The Old Man and the Three' podcast which became one of the top sports podcasts. In June 2024, he was hired as head coach of the Los Angeles Lakers, jumping directly from media to an NBA head coaching role.",
        sourceUrl: "https://en.wikipedia.org/wiki/J._J._Redick",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 4,
        position: "Shooting Guard",
        yearsAtSchool: "2002-2006",
        statsNote: "Freshman contributor • Duke's all-time leading scorer (2,769 pts)",
      },
      careerEvents: [
        { year: 2006, title: "Selected #11 overall by the Orlando Magic", eventType: "DRAFT" },
        { year: 2021, title: "Retired from NBA after 15 seasons", eventType: "RETIREMENT" },
        { year: 2024, title: "Named head coach of the Los Angeles Lakers", eventType: "CAREER" },
      ],
    },
    {
      slug: "shelden-williams",
      firstName: "Shelden",
      lastName: "Williams",
      birthYear: 1983,
      hometown: "Midwest City, OK",
      highSchool: "Midwest City High School, Midwest City, OK",
      isFeatured: false,
      bio: "A dominant shot-blocking center who became Duke's all-time leader in blocked shots. Williams was the 2006 NABC Defensive Player of the Year.",
      status: {
        occupationType: "COACH",
        currentTitle: "Podcast Host / Foundation Director",
        location: "Atlanta, GA",
        statusNote:
          "Selected #5 overall by the Atlanta Hawks in 2006, Williams played six NBA seasons with the Hawks, Kings, Celtics, Nuggets, and Nets. After his playing career, he has been involved in youth basketball coaching and player development in the Atlanta area. He was formerly married to WNBA star Candace Parker.",
        sourceUrl: "https://en.wikipedia.org/wiki/Shelden_Williams",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 23,
        position: "Center / Power Forward",
        yearsAtSchool: "2002-2006",
        statsNote: "Freshman contributor • Duke's all-time blocks leader",
      },
      careerEvents: [
        { year: 2006, title: "Selected #5 overall by the Atlanta Hawks", eventType: "DRAFT" },
        { year: 2012, title: "Final NBA season with Brooklyn Nets", eventType: "CAREER" },
      ],
    },
    {
      slug: "daniel-ewing",
      firstName: "Daniel",
      lastName: "Ewing",
      birthYear: 1983,
      hometown: "Houston, TX",
      highSchool: "Willowridge High School, Houston, TX",
      isFeatured: false,
      bio: "A talented guard who became a four-year contributor at Duke.",
      status: {
        occupationType: "FRONT_OFFICE",
        currentTitle: "Professional Scout",
        currentEmployer: "Los Angeles Lakers",
        league: "NBA",
        location: "Los Angeles, CA",
        statusNote:
          "Selected #32 overall by the LA Clippers in 2005, Ewing played overseas for nearly a decade. He joined the Lakers as a professional scout in 2022.",
        sourceUrl: "https://en.wikipedia.org/wiki/Daniel_Ewing",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 5,
        position: "Shooting Guard",
        yearsAtSchool: "2001-2005",
        statsNote: "Sophomore starter • Developing scorer",
        gamesPlayed: 33,
        pointsPerGame: 10.5,
        assistsPerGame: 2.8,
      },
      careerEvents: [
        { year: 2005, title: "Selected #32 overall by the LA Clippers", eventType: "DRAFT" },
        { year: 2022, title: "Joined Lakers as professional scout", eventType: "CAREER" },
      ],
    },
    {
      slug: "shavlik-randolph",
      firstName: "Shavlik",
      lastName: "Randolph",
      birthYear: 1983,
      hometown: "Raleigh, NC",
      highSchool: "Broughton High School, Raleigh, NC",
      isFeatured: false,
      bio: "A highly touted McDonald's All-American power forward from nearby Raleigh who joined Duke as a top-10 recruit.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Owner / Investor",
        currentEmployer: "Big Prime Hauling",
        location: "Raleigh, NC",
        statusNote:
          "The #1 recruit in the nation when he signed with Duke, Randolph went undrafted in 2005 but played in the NBA with the 76ers and Celtics plus overseas. After retiring, he invested in Big Prime Hauling, a minority-owned trucking and heavy equipment transport company in North Carolina. In 2021 it was acquired by Bright Hope Capital, which invested $2.5 million to expand operations by 2025.",
        sourceUrl: "https://en.wikipedia.org/wiki/Shavlik_Randolph",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 42,
        position: "Power Forward",
        yearsAtSchool: "2002-2006",
        statsNote: "McDonald's All-American • Local recruit from Raleigh",
      },
      careerEvents: [
        { year: 2006, title: "Went undrafted; signed with Philadelphia 76ers", eventType: "SIGNING" },
      ],
    },
    {
      slug: "nick-horvath",
      firstName: "Nick",
      lastName: "Horvath",
      birthYear: 1981,
      hometown: "Shoreview, MN",
      highSchool: "Mounds View High School, Shoreview, MN",
      isFeatured: false,
      bio: "A versatile forward who double-majored in Physics and English at Duke.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Physics Teacher / Author / Basketball Coach",
        currentEmployer: "Palmerston North Boys' High School",
        location: "Palmerston North, New Zealand",
        statusNote:
          "After Duke, Horvath played 12 years professionally in Australia and New Zealand. He is now a physics teacher, basketball coach, and published author in New Zealand.",
        sourceUrl: "https://en.wikipedia.org/wiki/Nick_Horvath",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 3,
        position: "Forward",
        yearsAtSchool: "1999-2004",
        statsNote: "Junior contributor • Physics/English double major",
      },
      careerEvents: [
        { year: 2001, title: "Won NCAA National Championship with Duke", eventType: "CHAMPIONSHIP" },
        { year: 2016, title: "Became physics teacher in New Zealand", eventType: "CAREER" },
      ],
    },
    {
      slug: "lee-melchionni",
      firstName: "Lee",
      lastName: "Melchionni",
      birthYear: 1983,
      hometown: "Germantown, PA",
      highSchool: "Germantown Academy, Fort Washington, PA",
      isFeatured: false,
      bio: "A sharpshooting guard who was a four-year contributor and became a reliable perimeter threat for the Blue Devils.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Sports Agent",
        currentEmployer: "Wasserman Media Group",
        location: "Los Angeles, CA",
        statusNote:
          "After graduating from Duke in 2006, Melchionni played one professional season in Italy with Cimberio Novara. He then transitioned to sports representation, becoming an NBA player agent at Wasserman Media Group, representing clients such as Danilo Gallinari. He also attended Loyola Law School. His father Bill Melchionni was an ABA star with the New York Nets.",
        sourceUrl: "https://lancasteronline.com/sports/nba/basketball-still-melchionni-s-business/article_f4a85d66-0400-11e4-a2ab-001a4bcf6878.html",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 20,
        position: "Shooting Guard",
        yearsAtSchool: "2002-2006",
        statsNote: "Freshman contributor • Sharpshooter",
      },
      careerEvents: [
        { year: 2006, title: "Graduated from Duke; played briefly overseas", eventType: "CAREER" },
      ],
    },
    {
      slug: "mike-krzyzewski",
      firstName: "Mike",
      lastName: "Krzyzewski",
      birthYear: 1947,
      hometown: "Chicago, IL",
      highSchool: "Weber High School, Chicago, IL",
      isFeatured: true,
      bio: "The winningest coach in Division I men's basketball history with five national championships.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Special Advisor / Duke Ambassador",
        currentEmployer: "NBA / Duke University",
        location: "Durham, NC",
        statusNote:
          "Krzyzewski retired after the 2021-22 season with 1,202 victories and five national championships.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Krzyzewski",
      },
      membership: {
        role: "HEAD_COACH",
        position: "Head Coach",
        yearsAtSchool: "1980-2022",
        statsNote: "26-7 record in 2002-03 • Sweet Sixteen",
      },
      careerEvents: [
        { year: 2022, title: "Retired as winningest coach in D-I history", eventType: "RETIREMENT" },
      ],
    },
  ],
};
