import type { TeamSeed } from "./types";

export const dukeBasketball2019: TeamSeed = {
  slug: "duke-basketball-2019",
  name: "Duke Blue Devils",
  season: "2018-2019",
  sport: "Men's Basketball",
  school: "Duke University",
  conference: "ACC",
  accomplishment: "32-6, ACC Champions, Elite Eight",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  mascotName: "Blue Devil",
  people: [
    {
      slug: "zion-williamson",
      firstName: "Zion",
      lastName: "Williamson",
      birthYear: 2000,
      hometown: "Spartanburg, SC",
      highSchool: "Spartanburg Day School, Spartanburg, SC",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1629627.png",
      isFeatured: true,
      bio: "The most hyped college basketball prospect in a generation. Williamson averaged 22.6 PPG with 8.9 RPG as a freshman, winning virtually every national player of the year award. His shoe-blowing-out moment against UNC became an iconic sports moment.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Power Forward",
        currentEmployer: "New Orleans Pelicans",
        league: "NBA",
        location: "New Orleans, LA",
        statusNote: "Selected #1 overall by the New Orleans Pelicans in 2019. Despite battling injuries throughout his career, Williamson has shown superstar-level production when healthy — averaging 25.0 PPG on 60.8% shooting in 2022-23. Signed a 5-year, $197 million max extension in 2022. Has played 192 games over 6 NBA seasons, with career averages of 24.6 PPG, 6.8 RPG, and 4.0 APG.",
        sourceUrl: "https://en.wikipedia.org/wiki/Zion_Williamson",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Power Forward", yearsAtSchool: "2018-2019", statsNote: "Consensus NPOY · 22.6 PPG, 8.9 RPG · AP Player of the Year · ACC POTY", gamesPlayed: 33, pointsPerGame: 22.6, reboundsPerGame: 8.9, assistsPerGame: 2.1 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Spartanburg Day School", season: "2017-18", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 36.4, reboundsPerGame: 11.4, assistsPerGame: 3.5, blocksPerGame: 3.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2018-19", yearLabel: "2018-19", sortOrder: 201, gamesPlayed: 33, minutesPerGame: 30.0, pointsPerGame: 22.6, reboundsPerGame: 8.9, assistsPerGame: 2.1, stealsPerGame: 2.1, blocksPerGame: 1.8, fieldGoalPct: 0.680, threePointPct: 0.338, freeThrowPct: 0.640 },
        { level: "PROFESSIONAL", teamName: "New Orleans Pelicans", season: "2019-20", yearLabel: "2019-20 (Rookie)", sortOrder: 301, gamesPlayed: 24, minutesPerGame: 27.8, pointsPerGame: 22.5, reboundsPerGame: 6.3, assistsPerGame: 2.1, stealsPerGame: 0.7, fieldGoalPct: 0.582, threePointPct: 0.429, freeThrowPct: 0.642 },
        { level: "PROFESSIONAL", teamName: "New Orleans Pelicans", season: "2020-21", yearLabel: "2020-21", sortOrder: 302, gamesPlayed: 61, minutesPerGame: 33.2, pointsPerGame: 27.0, reboundsPerGame: 7.2, assistsPerGame: 3.7, fieldGoalPct: 0.611, freeThrowPct: 0.698 },
        { level: "PROFESSIONAL", teamName: "New Orleans Pelicans", season: "2022-23", yearLabel: "2022-23", sortOrder: 304, gamesPlayed: 29, minutesPerGame: 33.3, pointsPerGame: 26.0, reboundsPerGame: 7.0, assistsPerGame: 4.6, fieldGoalPct: 0.608, freeThrowPct: 0.717 },
        { level: "PROFESSIONAL", teamName: "New Orleans Pelicans", season: "2024-25", yearLabel: "2024-25", sortOrder: 306, gamesPlayed: 45, minutesPerGame: 31.5, pointsPerGame: 23.5, reboundsPerGame: 6.5, assistsPerGame: 4.2, fieldGoalPct: 0.590, freeThrowPct: 0.710 },
      ],
      careerEvents: [
        { year: 2019, title: "Selected #1 overall by New Orleans Pelicans", eventType: "DRAFT" },
        { year: 2022, title: "Signed 5-year, $197M max extension", eventType: "CONTRACT" },
      ],
    },
    {
      slug: "rj-barrett",
      firstName: "RJ",
      lastName: "Barrett",
      birthYear: 2000,
      hometown: "Mississauga, ON, Canada",
      highSchool: "Montverde Academy, Montverde, FL",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1629628.png",
      isFeatured: true,
      bio: "Canadian-born wing who led Duke in scoring as a freshman with 22.6 PPG. A McDonald's All-American and Gatorade National Player of the Year in high school, Barrett was the co-alpha alongside Zion Williamson.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Shooting Guard / Small Forward",
        currentEmployer: "Toronto Raptors",
        league: "NBA",
        location: "Toronto, ON",
        statusNote: "Selected #3 overall by the New York Knicks in 2019. Averaged 17.6 PPG in his second season. Traded to the Toronto Raptors in December 2023 along with Immanuel Quickley for OG Anunoby. Has played six NBA seasons, representing Canada internationally at the 2023 FIBA World Cup.",
        sourceUrl: "https://en.wikipedia.org/wiki/RJ_Barrett",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Small Forward", yearsAtSchool: "2018-2019", statsNote: "22.6 PPG (led team) · 7.6 RPG · 4.3 APG · All-ACC First Team", gamesPlayed: 38, pointsPerGame: 22.6, reboundsPerGame: 7.6, assistsPerGame: 4.3 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Montverde Academy", season: "2017-18", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 28.0, reboundsPerGame: 9.8, assistsPerGame: 4.2 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2018-19", yearLabel: "2018-19", sortOrder: 201, gamesPlayed: 38, minutesPerGame: 35.7, pointsPerGame: 22.6, reboundsPerGame: 7.6, assistsPerGame: 4.3, stealsPerGame: 0.9, fieldGoalPct: 0.454, threePointPct: 0.305, freeThrowPct: 0.665 },
        { level: "PROFESSIONAL", teamName: "New York Knicks", season: "2019-20", yearLabel: "2019-20 (Rookie)", sortOrder: 301, gamesPlayed: 56, minutesPerGame: 30.4, pointsPerGame: 14.3, reboundsPerGame: 5.0, assistsPerGame: 2.6, fieldGoalPct: 0.402, threePointPct: 0.321, freeThrowPct: 0.614 },
        { level: "PROFESSIONAL", teamName: "New York Knicks", season: "2020-21", yearLabel: "2020-21", sortOrder: 302, gamesPlayed: 72, minutesPerGame: 34.9, pointsPerGame: 17.6, reboundsPerGame: 5.8, assistsPerGame: 3.0, fieldGoalPct: 0.440, threePointPct: 0.401, freeThrowPct: 0.746 },
        { level: "PROFESSIONAL", teamName: "New York Knicks", season: "2022-23", yearLabel: "2022-23", sortOrder: 304, gamesPlayed: 73, minutesPerGame: 32.8, pointsPerGame: 16.1, reboundsPerGame: 5.2, assistsPerGame: 2.8, fieldGoalPct: 0.440, threePointPct: 0.344, freeThrowPct: 0.737 },
        { level: "PROFESSIONAL", teamName: "Toronto Raptors", season: "2023-24", yearLabel: "2023-24", sortOrder: 305, gamesPlayed: 58, minutesPerGame: 34.0, pointsPerGame: 21.8, reboundsPerGame: 6.4, assistsPerGame: 4.1, fieldGoalPct: 0.458, threePointPct: 0.354, freeThrowPct: 0.754 },
        { level: "PROFESSIONAL", teamName: "Toronto Raptors", season: "2024-25", yearLabel: "2024-25", sortOrder: 306, gamesPlayed: 55, minutesPerGame: 33.0, pointsPerGame: 19.5, reboundsPerGame: 5.8, assistsPerGame: 4.5, fieldGoalPct: 0.445, threePointPct: 0.340, freeThrowPct: 0.750 },
      ],
      careerEvents: [
        { year: 2019, title: "Selected #3 overall by New York Knicks", eventType: "DRAFT" },
        { year: 2023, title: "Traded to Toronto Raptors for OG Anunoby", eventType: "TRADE" },
      ],
    },
    {
      slug: "cam-reddish",
      firstName: "Cam",
      lastName: "Reddish",
      birthYear: 2000,
      hometown: "Norristown, PA",
      highSchool: "Westtown School, West Chester, PA",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1629629.png",
      isFeatured: true,
      bio: "Five-star recruit and McDonald's All-American who was the third member of Duke's historically talented freshman class. His shooting struggled at Duke but his NBA potential was always evident due to his 6'8\" frame and versatile skill set.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Small Forward",
        currentEmployer: "Los Angeles Lakers",
        league: "NBA",
        location: "Los Angeles, CA",
        statusNote: "Selected #10 overall by the Atlanta Hawks in 2019. Has bounced between several teams including the Knicks, Blazers, and Lakers. Best season was 2020-21 with Atlanta (11.2 PPG). Signed with the Lakers in 2025 seeking to revive his career.",
        sourceUrl: "https://en.wikipedia.org/wiki/Cam_Reddish",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Small Forward", yearsAtSchool: "2018-2019", statsNote: "13.5 PPG · 3.7 RPG · Struggled with shooting but showed flashes", gamesPlayed: 36, pointsPerGame: 13.5, reboundsPerGame: 3.7, assistsPerGame: 1.6 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Westtown School", season: "2017-18", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 22.5, reboundsPerGame: 7.0, assistsPerGame: 2.8 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2018-19", yearLabel: "2018-19", sortOrder: 201, gamesPlayed: 36, minutesPerGame: 28.1, pointsPerGame: 13.5, reboundsPerGame: 3.7, assistsPerGame: 1.6, stealsPerGame: 0.9, fieldGoalPct: 0.355, threePointPct: 0.333, freeThrowPct: 0.772 },
        { level: "PROFESSIONAL", teamName: "Atlanta Hawks", season: "2019-20", yearLabel: "2019-20 (Rookie)", sortOrder: 301, gamesPlayed: 58, minutesPerGame: 26.7, pointsPerGame: 10.5, reboundsPerGame: 3.7, assistsPerGame: 1.5, fieldGoalPct: 0.388, threePointPct: 0.333, freeThrowPct: 0.808 },
        { level: "PROFESSIONAL", teamName: "Atlanta Hawks", season: "2020-21", yearLabel: "2020-21", sortOrder: 302, gamesPlayed: 26, minutesPerGame: 26.7, pointsPerGame: 11.2, reboundsPerGame: 3.0, assistsPerGame: 1.4, fieldGoalPct: 0.408, threePointPct: 0.263, freeThrowPct: 0.898 },
        { level: "PROFESSIONAL", teamName: "ATL / New York Knicks", season: "2021-22", yearLabel: "2021-22", sortOrder: 303, gamesPlayed: 53, minutesPerGame: 24.3, pointsPerGame: 8.3, reboundsPerGame: 2.5, assistsPerGame: 1.1, fieldGoalPct: 0.392, threePointPct: 0.305, freeThrowPct: 0.842 },
        { level: "PROFESSIONAL", teamName: "Portland Trail Blazers", season: "2023-24", yearLabel: "2023-24", sortOrder: 305, gamesPlayed: 42, minutesPerGame: 15.5, pointsPerGame: 5.2, reboundsPerGame: 1.8, assistsPerGame: 0.8, fieldGoalPct: 0.380, threePointPct: 0.310, freeThrowPct: 0.800 },
      ],
      careerEvents: [
        { year: 2019, title: "Selected #10 overall by Atlanta Hawks", eventType: "DRAFT" },
        { year: 2022, title: "Traded to New York Knicks", eventType: "TRADE" },
      ],
    },
    {
      slug: "tre-jones",
      firstName: "Tre",
      lastName: "Jones",
      birthYear: 2000,
      hometown: "Apple Valley, MN",
      highSchool: "Apple Valley High School, Apple Valley, MN",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1630200.png",
      isFeatured: false,
      bio: "Younger brother of Tyus Jones, Tre was the starting point guard who orchestrated Duke's offense. Named ACC Defensive Player of the Year as a freshman — the first freshman to win it.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Point Guard",
        currentEmployer: "San Antonio Spurs",
        league: "NBA",
        location: "San Antonio, TX",
        statusNote: "Returned for his sophomore year at Duke (2019-20) where he was named ACC Player of the Year. Selected #41 in the 2020 Draft by the San Antonio Spurs. Has been a reliable backup point guard, averaging career-best 8.8 PPG in 2023-24. Entering his 6th NBA season.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tre_Jones",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Point Guard", yearsAtSchool: "2018-2020", statsNote: "ACC Defensive POY · 9.4 PPG, 5.3 APG · 112 assists as freshman" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Apple Valley High School", season: "2017-18", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 24.0, reboundsPerGame: 5.0, assistsPerGame: 7.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2018-19", yearLabel: "2018-19", sortOrder: 201, gamesPlayed: 38, minutesPerGame: 30.5, pointsPerGame: 9.4, reboundsPerGame: 3.8, assistsPerGame: 5.3, stealsPerGame: 1.9, fieldGoalPct: 0.414, threePointPct: 0.265, freeThrowPct: 0.700 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2019-20", yearLabel: "2019-20 (ACC POY)", sortOrder: 202, gamesPlayed: 31, minutesPerGame: 34.8, pointsPerGame: 16.2, reboundsPerGame: 4.2, assistsPerGame: 6.4, stealsPerGame: 1.8, fieldGoalPct: 0.445, threePointPct: 0.363, freeThrowPct: 0.772 },
        { level: "PROFESSIONAL", teamName: "San Antonio Spurs", season: "2020-21", yearLabel: "2020-21 (Rookie)", sortOrder: 301, gamesPlayed: 53, minutesPerGame: 14.0, pointsPerGame: 4.9, reboundsPerGame: 1.3, assistsPerGame: 2.5, fieldGoalPct: 0.454, threePointPct: 0.286, freeThrowPct: 0.780 },
        { level: "PROFESSIONAL", teamName: "San Antonio Spurs", season: "2022-23", yearLabel: "2022-23", sortOrder: 303, gamesPlayed: 78, minutesPerGame: 22.8, pointsPerGame: 8.3, reboundsPerGame: 2.8, assistsPerGame: 4.1, fieldGoalPct: 0.448, threePointPct: 0.341, freeThrowPct: 0.756 },
        { level: "PROFESSIONAL", teamName: "San Antonio Spurs", season: "2023-24", yearLabel: "2023-24", sortOrder: 304, gamesPlayed: 74, minutesPerGame: 24.0, pointsPerGame: 8.8, reboundsPerGame: 2.5, assistsPerGame: 4.5, fieldGoalPct: 0.440, threePointPct: 0.330, freeThrowPct: 0.780 },
      ],
      careerEvents: [
        { year: 2020, title: "Named ACC Player of the Year", eventType: "AWARD" },
        { year: 2020, title: "Selected #41 by San Antonio Spurs", eventType: "DRAFT" },
      ],
    },
    {
      slug: "marques-bolden",
      firstName: "Marques",
      lastName: "Bolden",
      birthYear: 1998,
      hometown: "DeSoto, TX",
      highSchool: "DeSoto High School, DeSoto, TX",
      bio: "Junior center who battled knee injuries throughout his Duke career but was a key contributor in 2018-19, starting 24 games and providing rim protection.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "Texas",
        statusNote: "Went undrafted in 2019 and had brief stints with the Cleveland Cavaliers and G-League. Knee injuries that plagued his Duke career continued to hinder his professional prospects. Has been out of professional basketball since 2021.",
        sourceUrl: "https://en.wikipedia.org/wiki/Marques_Bolden",
      },
      membership: { role: "PLAYER", jerseyNumber: 20, position: "Center", yearsAtSchool: "2016-2019", statsNote: "5.3 PPG, 4.5 RPG, 1.2 BPG as junior · Started 24 games" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "DeSoto High School", season: "2015-16", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 18.0, reboundsPerGame: 10.5, blocksPerGame: 3.8 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2016-17", yearLabel: "2016-17", sortOrder: 201, gamesPlayed: 24, minutesPerGame: 6.3, pointsPerGame: 1.5, reboundsPerGame: 1.5, blocksPerGame: 0.5, fieldGoalPct: 0.512 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2017-18", yearLabel: "2017-18", sortOrder: 202, gamesPlayed: 26, minutesPerGame: 10.8, pointsPerGame: 2.7, reboundsPerGame: 2.2, blocksPerGame: 0.7, fieldGoalPct: 0.654 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2018-19", yearLabel: "2018-19", sortOrder: 203, gamesPlayed: 31, minutesPerGame: 17.9, pointsPerGame: 5.3, reboundsPerGame: 4.5, blocksPerGame: 1.2, fieldGoalPct: 0.657 },
      ],
      careerEvents: [
        { year: 2019, title: "Went undrafted; signed with Cleveland Cavaliers", eventType: "SIGNING" },
      ],
    },
    {
      slug: "jack-white",
      firstName: "Jack",
      lastName: "White",
      birthYear: 1997,
      hometown: "Geelong, Australia",
      highSchool: "The Scots College, Sydney, Australia",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1631298.png",
      bio: "Australian-born junior wing who was a key glue guy and defensive specialist on the 2019 team. His toughness and effort earned him a starting spot despite modest scoring numbers.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "Melbourne United (NBL)",
        league: "NBL (Australia)",
        location: "Melbourne, Australia",
        statusNote: "After going undrafted in 2020, White returned to Australia to play in the NBL. He has played for Melbourne United and the South East Melbourne Phoenix, becoming a rotation player in Australia's top league. His defense-first mentality has translated well to pro basketball in his home country.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jack_White_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 41, position: "Small Forward", yearsAtSchool: "2016-2020", statsNote: "3.5 PPG, 3.0 RPG · Defensive specialist · Started 32 games as junior" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2017-18", yearLabel: "2017-18", sortOrder: 201, gamesPlayed: 34, minutesPerGame: 15.6, pointsPerGame: 3.2, reboundsPerGame: 2.5, assistsPerGame: 0.5, fieldGoalPct: 0.461, threePointPct: 0.438 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2018-19", yearLabel: "2018-19", sortOrder: 202, gamesPlayed: 38, minutesPerGame: 22.1, pointsPerGame: 3.5, reboundsPerGame: 3.0, assistsPerGame: 0.8, fieldGoalPct: 0.398, threePointPct: 0.333 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2019-20", yearLabel: "2019-20", sortOrder: 203, gamesPlayed: 26, minutesPerGame: 18.5, pointsPerGame: 3.0, reboundsPerGame: 2.8, fieldGoalPct: 0.350, threePointPct: 0.310 },
      ],
      careerEvents: [
        { year: 2021, title: "Signed with South East Melbourne Phoenix (NBL)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "javin-delaurier",
      firstName: "Javin",
      lastName: "DeLaurier",
      birthYear: 1997,
      hometown: "Shippensburg, PA",
      highSchool: "IMG Academy, Bradenton, FL",
      bio: "Senior center and energy player who was a fan favorite for his effort and emotion. Provided key minutes as the backup big behind Bolden and Williamson.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Citizen",
        location: "Pennsylvania",
        statusNote: "After his senior year (2019-20), DeLaurier went undrafted and had brief G-League stints. He transitioned away from professional basketball and has maintained a low public profile since leaving the sport.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/javin-delaurier/11459",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Power Forward / Center", yearsAtSchool: "2016-2020", statsNote: "2.6 PPG, 3.0 RPG · Energy/hustle player off bench" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "IMG Academy", season: "2015-16", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 10.2, reboundsPerGame: 8.5, blocksPerGame: 2.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2018-19", yearLabel: "2018-19", sortOrder: 203, gamesPlayed: 37, minutesPerGame: 11.7, pointsPerGame: 2.6, reboundsPerGame: 3.0, blocksPerGame: 0.5, fieldGoalPct: 0.618 },
      ],
      careerEvents: [],
    },
    {
      slug: "alex-oconnell",
      firstName: "Alex",
      lastName: "O'Connell",
      birthYear: 1998,
      hometown: "Milton, GA",
      highSchool: "Milton High School, Alpharetta, GA",
      bio: "Sophomore guard who provided outside shooting off the bench. Hit a key three-pointer to send the UCF game to overtime in the NCAA Tournament second round.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "Overseas",
        statusNote: "After transferring to Creighton for his final season (2021-22), O'Connell has played professionally overseas in leagues across Europe. Known for his sharpshooting ability.",
        sourceUrl: "https://en.wikipedia.org/wiki/Alex_O%27Connell",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Shooting Guard", yearsAtSchool: "2017-2021", statsNote: "5.2 PPG · Key bench scorer · Hit crucial 3 vs UCF in NCAAs" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Milton High School", season: "2016-17", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 18.5, reboundsPerGame: 4.0, assistsPerGame: 3.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2018-19", yearLabel: "2018-19", sortOrder: 202, gamesPlayed: 36, minutesPerGame: 12.6, pointsPerGame: 5.2, reboundsPerGame: 1.4, assistsPerGame: 0.5, fieldGoalPct: 0.436, threePointPct: 0.383, freeThrowPct: 0.810 },
      ],
      careerEvents: [
        { year: 2021, title: "Transferred to Creighton University", eventType: "OTHER" },
      ],
    },
    {
      slug: "joey-baker",
      firstName: "Joey",
      lastName: "Baker",
      birthYear: 1999,
      hometown: "Fayetteville, NC",
      highSchool: "Trinity Christian School, Fayetteville, NC",
      bio: "Freshman sharpshooter who had a limited role in 2018-19 but developed into a key rotation player in subsequent seasons. Shot 38.4% from three across his Duke career.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Citizen",
        location: "North Carolina",
        statusNote: "Baker played five seasons at Duke (2018-23), becoming a reliable bench scorer. He was part of Coach K's final team that reached the 2022 Final Four. After going undrafted in 2023, he pursued opportunities overseas.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/joey-baker/11460",
      },
      membership: { role: "PLAYER", jerseyNumber: 13, position: "Small Forward", yearsAtSchool: "2018-2023", statsNote: "Limited role as freshman · Became key bench player by 2022" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Trinity Christian School", season: "2017-18", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 20.0, reboundsPerGame: 5.0, assistsPerGame: 2.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2018-19", yearLabel: "2018-19", sortOrder: 201, gamesPlayed: 20, minutesPerGame: 4.5, pointsPerGame: 1.8, reboundsPerGame: 0.5, fieldGoalPct: 0.390, threePointPct: 0.370 },
      ],
      careerEvents: [],
    },
    {
      slug: "jordan-goldwire",
      firstName: "Jordan",
      lastName: "Goldwire",
      birthYear: 1998,
      hometown: "Norcross, GA",
      highSchool: "Greater Atlanta Christian School, Norcross, GA",
      bio: "Sophomore guard who was one of Duke's best on-ball defenders. Provided key minutes off the bench as a disruptive perimeter defender.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        league: "Overseas",
        statusNote: "Transferred to Oklahoma for his senior year (2021-22) where he averaged 6.9 PPG and 4.0 APG. Has played professionally overseas since going undrafted.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jordan_Goldwire",
      },
      membership: { role: "PLAYER", jerseyNumber: 14, position: "Point Guard", yearsAtSchool: "2017-2020", statsNote: "2.2 PPG · Defensive specialist · Key backup PG" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Greater Atlanta Christian School", season: "2016-17", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 15.0, reboundsPerGame: 3.5, assistsPerGame: 5.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2018-19", yearLabel: "2018-19", sortOrder: 202, gamesPlayed: 37, minutesPerGame: 11.5, pointsPerGame: 2.2, reboundsPerGame: 0.8, assistsPerGame: 1.1, stealsPerGame: 0.7, fieldGoalPct: 0.371, threePointPct: 0.276 },
      ],
      careerEvents: [
        { year: 2020, title: "Transferred to University of Oklahoma", eventType: "OTHER" },
      ],
    },
    {
      slug: "javin-delaurier",
      firstName: "Javin",
      lastName: "DeLaurier",
      birthYear: 1997,
      hometown: "Shippensburg, PA",
      highSchool: "IMG Academy, Bradenton, FL",
      bio: "Junior forward who provided energy and effort off the bench. Known for his hustle plays and emotion on the court.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Citizen",
        location: "Pennsylvania",
        statusNote: "Returned for his senior year (2019-20), then went undrafted. Had brief G-League stints before transitioning away from basketball.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/javin-delaurier/11459",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Power Forward / Center", yearsAtSchool: "2016-2020", statsNote: "2.6 PPG, 3.0 RPG · Energy/hustle player" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2018-19", yearLabel: "2018-19", sortOrder: 203, gamesPlayed: 37, minutesPerGame: 11.7, pointsPerGame: 2.6, reboundsPerGame: 3.0, blocksPerGame: 0.5, fieldGoalPct: 0.618 },
      ],
      careerEvents: [],
    },
    {
      slug: "antonio-vrankovic",
      firstName: "Antonio",
      lastName: "Vrankovic",
      birthYear: 1997,
      hometown: "Zagreb, Croatia",
      highSchool: "St. Andrew's School, Boca Raton, FL",
      bio: "Senior walk-on center from Croatia who provided depth as a practice player. Son of former NBA player Stojko Vrankovic.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Private Citizen",
        location: "Croatia",
        statusNote: "Son of former NBA center Stojko Vrankovic. Graduated from Duke and returned to Croatia. Did not pursue professional basketball.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/antonio-vrankovic/11464",
      },
      membership: { role: "PLAYER", jerseyNumber: 44, position: "Center", yearsAtSchool: "2015-2019", statsNote: "Walk-on · Son of NBA player Stojko Vrankovic" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2018-19", yearLabel: "2018-19", sortOrder: 204, gamesPlayed: 8, minutesPerGame: 2.0, pointsPerGame: 0.5, reboundsPerGame: 0.4 },
      ],
      careerEvents: [],
    },
    {
      slug: "mike-buckmire",
      firstName: "Mike",
      lastName: "Buckmire",
      birthYear: 1998,
      hometown: "Bronx, NY",
      highSchool: "The Hotchkiss School, Lakeville, CT",
      bio: "Walk-on guard who was part of the 2018-19 roster. Contributed in practice as a scout-team player.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Private Citizen",
        location: "New York, NY",
        statusNote: "Walk-on who earned a Duke degree. Transitioned to business career after graduation.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster",
      },
      membership: { role: "PLAYER", jerseyNumber: 51, position: "Guard", yearsAtSchool: "2017-2021", statsNote: "Walk-on · Practice contributor" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2018-19", yearLabel: "2018-19", sortOrder: 205, gamesPlayed: 5, minutesPerGame: 1.5, pointsPerGame: 0.2 },
      ],
      careerEvents: [],
    },
    {
      slug: "mike-krzyzewski",
      firstName: "Mike",
      lastName: "Krzyzewski",
      birthYear: 1947,
      hometown: "Chicago, IL",
      highSchool: "Weber High School, Chicago, IL",
      bio: "Legendary head coach in his 39th season at Duke. Led the program to five national championships, 13 Final Fours, and over 1,100 career wins. The 2018-19 team featured perhaps the most talented freshman class in college basketball history.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Retired Head Coach",
        currentEmployer: "Duke University (Emeritus)",
        location: "Durham, NC",
        statusNote: "Retired after the 2021-22 season with a career record of 1,202-368 (.766). Five-time national champion (1991, 1992, 2001, 2010, 2015). Named to the Naismith Basketball Hall of Fame in 2001. Led USA Basketball to three Olympic gold medals (2008, 2012, 2016). His final game was a loss to North Carolina in the 2022 Final Four.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Krzyzewski",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "1980-2022", statsNote: "1,202-368 career · 5x National Champion · 13 Final Fours" },
      seasonStats: [
        { level: "COACHING", teamName: "Duke Blue Devils", season: "2018-19", yearLabel: "2018-19", sortOrder: 1, wins: 32, losses: 6, tournamentResult: "ACC Champions, Elite Eight (lost to Michigan State)" },
      ],
      careerEvents: [
        { year: 2022, title: "Retired from coaching after 42 seasons at Duke", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "jeff-capel",
      firstName: "Jeff",
      lastName: "Capel",
      birthYear: 1975,
      hometown: "Fayetteville, NC",
      highSchool: "South View High School, Hope Mills, NC",
      bio: "Associate head coach at Duke who was one of the top assistants and recruiters in college basketball.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "University of Pittsburgh",
        location: "Pittsburgh, PA",
        statusNote: "Left Duke in 2018 to become head coach at Pitt. Has rebuilt the Panthers program.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jeff_Capel",
      },
      membership: { role: "ASSISTANT_COACH", position: "Associate Head Coach", yearsAtSchool: "2011-2018", statsNote: "Top recruiter · Landed Zion, RJ, Cam class" },
      careerEvents: [
        { year: 2018, title: "Named head coach at University of Pittsburgh", eventType: "COACHING" },
      ],
    },
    {
      slug: "nate-james",
      firstName: "Nate",
      lastName: "James",
      birthYear: 1979,
      hometown: "Seattle, WA",
      highSchool: "Lower Merion High School, Ardmore, PA",
      bio: "Former Duke player (1997-2001) and assistant coach. Key recruiter and mentor to players.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "Austin Peay State University",
        location: "Clarksville, TN",
        statusNote: "Left Duke in 2021 to become head coach at Austin Peay. 2001 NCAA champion as a player.",
        sourceUrl: "https://en.wikipedia.org/wiki/Nate_James",
      },
      membership: { role: "ASSISTANT_COACH", position: "Assistant Coach", yearsAtSchool: "2007-2021", statsNote: "Former Duke player · Key recruiter" },
      careerEvents: [
        { year: 2021, title: "Named head coach at Austin Peay State University", eventType: "COACHING" },
      ],
    },
    {
      slug: "jon-scheyer",
      firstName: "Jon",
      lastName: "Scheyer",
      birthYear: 1987,
      hometown: "Northbrook, IL",
      highSchool: "Glenbrook North High School, Northbrook, IL",
      bio: "Former Duke player (2006-10) and 2010 national champion who served as associate head coach and head-coach-in-waiting.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "Duke University",
        league: "ACC",
        location: "Durham, NC",
        statusNote: "Succeeded Coach K in 2022. Has led Duke to three NCAA Tournaments in three seasons, including a Final Four in 2025.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jon_Scheyer",
      },
      membership: { role: "ASSISTANT_COACH", position: "Associate Head Coach / Coach-in-Waiting", yearsAtSchool: "2013-2022", statsNote: "2010 champion as player · Named successor to Coach K" },
      careerEvents: [
        { year: 2022, title: "Named head coach at Duke, succeeding Coach K", eventType: "COACHING" },
      ],
    },
  ],
};
