import type { TeamSeed } from "./types";

export const dukeBasketball2018: TeamSeed = {
  slug: "duke-basketball-2018",
  name: "Duke Blue Devils",
  season: "2017-2018",
  sport: "Men's Basketball",
  school: "Duke University",
  conference: "ACC",
  accomplishment: "29-8, Elite Eight",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  mascotName: "Blue Devil",
  people: [
    {
      slug: "marvin-bagley-iii",
      firstName: "Marvin",
      lastName: "Bagley III",
      birthYear: 2000,
      hometown: "Phoenix, AZ",
      highSchool: "Sierra Canyon School, Chatsworth, CA",
      isFeatured: true,
      imageUrl: "https://a.espncdn.com/combiner/i?img=/i/headshots/mens-college-basketball/players/full/4395724.png",
      bio: "The consensus #1 recruit who reclassified to join Duke a year early. Averaged 21.0 PPG and 11.1 RPG — recording 22 double-doubles, the most by a Duke freshman ever. Named ACC Player of the Year and Rookie of the Year.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Power Forward / Center",
        league: "NBA / Overseas",
        statusNote: "Selected #2 overall by Sacramento in 2018. Injuries and inconsistency have plagued his NBA career. Played for Sacramento, Detroit, and Washington over six seasons, averaging around 10 PPG. His athleticism and touch remain elite but he has struggled to find a permanent home. Currently seeking a roster spot.",
        sourceUrl: "https://en.wikipedia.org/wiki/Marvin_Bagley_III",
      },
      membership: { role: "PLAYER", jerseyNumber: 35, position: "Power Forward", yearsAtSchool: "2017-2018", statsNote: "21.0 PPG, 11.1 RPG · ACC POY · ACC ROY · #2 pick · 22 double-doubles", gamesPlayed: 33, pointsPerGame: 21.0, reboundsPerGame: 11.1, assistsPerGame: 0.8 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Sierra Canyon School", season: "2016-17", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 32.5, reboundsPerGame: 14.8, blocksPerGame: 2.8 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2017-18", yearLabel: "2017-18 (ACC POY)", sortOrder: 201, gamesPlayed: 33, minutesPerGame: 32.9, pointsPerGame: 21.0, reboundsPerGame: 11.1, assistsPerGame: 0.8, blocksPerGame: 0.8, fieldGoalPct: 0.614, freeThrowPct: 0.628 },
        { level: "PROFESSIONAL", teamName: "Sacramento Kings", season: "2018-19", yearLabel: "2018-19 (Rookie)", sortOrder: 301, gamesPlayed: 62, minutesPerGame: 25.3, pointsPerGame: 14.9, reboundsPerGame: 7.6, blocksPerGame: 1.0, fieldGoalPct: 0.502, freeThrowPct: 0.692 },
        { level: "PROFESSIONAL", teamName: "Sacramento Kings", season: "2020-21", yearLabel: "2020-21", sortOrder: 303, gamesPlayed: 43, minutesPerGame: 24.3, pointsPerGame: 14.1, reboundsPerGame: 7.4, fieldGoalPct: 0.504, freeThrowPct: 0.716 },
        { level: "PROFESSIONAL", teamName: "Detroit Pistons", season: "2021-22", yearLabel: "2021-22", sortOrder: 304, gamesPlayed: 58, minutesPerGame: 23.3, pointsPerGame: 11.1, reboundsPerGame: 6.4, fieldGoalPct: 0.497, freeThrowPct: 0.660 },
        { level: "PROFESSIONAL", teamName: "Washington Wizards", season: "2023-24", yearLabel: "2023-24", sortOrder: 306, gamesPlayed: 42, minutesPerGame: 18.0, pointsPerGame: 8.0, reboundsPerGame: 5.5, fieldGoalPct: 0.480, freeThrowPct: 0.650 },
      ],
      careerEvents: [
        { year: 2018, title: "Selected #2 overall by Sacramento Kings", eventType: "DRAFT" },
        { year: 2022, title: "Traded to Detroit Pistons", eventType: "TRADE" },
      ],
    },
    {
      slug: "wendell-carter-jr",
      firstName: "Wendell",
      lastName: "Carter Jr.",
      birthYear: 2000,
      hometown: "Atlanta, GA",
      highSchool: "Pace Academy, Atlanta, GA",
      isFeatured: true,
      imageUrl: "https://a.espncdn.com/combiner/i?img=/i/headshots/mens-college-basketball/players/full/4395725.png",
      bio: "Five-star freshman center who was the team's defensive anchor. Averaged 13.5 PPG, 9.1 RPG, and 2.0 BPG, earning All-ACC Freshman Team honors.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "Orlando Magic",
        league: "NBA",
        location: "Orlando, FL",
        statusNote: "Selected #7 overall by the Chicago Bulls in 2018. Traded to Orlando in 2021 and has become the Magic's starting center, averaging a career-best 12.8 PPG in 2022-23. Signed a 4-year, $50 million extension with Orlando in 2023. A dependable two-way center entering his 8th NBA season.",
        sourceUrl: "https://en.wikipedia.org/wiki/Wendell_Carter_Jr.",
      },
      membership: { role: "PLAYER", jerseyNumber: 34, position: "Center", yearsAtSchool: "2017-2018", statsNote: "13.5 PPG, 9.1 RPG, 2.0 BPG · All-ACC Freshman · #7 pick", gamesPlayed: 37, pointsPerGame: 13.5, reboundsPerGame: 9.1, assistsPerGame: 2.0 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Pace Academy", season: "2016-17", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 22.0, reboundsPerGame: 12.5, blocksPerGame: 3.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2017-18", yearLabel: "2017-18", sortOrder: 201, gamesPlayed: 37, minutesPerGame: 28.5, pointsPerGame: 13.5, reboundsPerGame: 9.1, assistsPerGame: 2.0, blocksPerGame: 2.0, fieldGoalPct: 0.560, freeThrowPct: 0.743 },
        { level: "PROFESSIONAL", teamName: "Chicago Bulls", season: "2018-19", yearLabel: "2018-19 (Rookie)", sortOrder: 301, gamesPlayed: 44, minutesPerGame: 25.6, pointsPerGame: 10.3, reboundsPerGame: 7.0, blocksPerGame: 1.3, fieldGoalPct: 0.483, freeThrowPct: 0.748 },
        { level: "PROFESSIONAL", teamName: "CHI / Orlando Magic", season: "2020-21", yearLabel: "2020-21", sortOrder: 303, gamesPlayed: 56, minutesPerGame: 28.0, pointsPerGame: 12.0, reboundsPerGame: 8.0, blocksPerGame: 1.0, fieldGoalPct: 0.505, freeThrowPct: 0.730 },
        { level: "PROFESSIONAL", teamName: "Orlando Magic", season: "2022-23", yearLabel: "2022-23", sortOrder: 305, gamesPlayed: 56, minutesPerGame: 29.5, pointsPerGame: 12.8, reboundsPerGame: 7.1, assistsPerGame: 2.4, blocksPerGame: 0.9, fieldGoalPct: 0.522, threePointPct: 0.326, freeThrowPct: 0.755 },
        { level: "PROFESSIONAL", teamName: "Orlando Magic", season: "2024-25", yearLabel: "2024-25", sortOrder: 307, gamesPlayed: 58, minutesPerGame: 27.0, pointsPerGame: 10.5, reboundsPerGame: 6.8, assistsPerGame: 2.0, fieldGoalPct: 0.510, freeThrowPct: 0.740 },
      ],
      careerEvents: [
        { year: 2018, title: "Selected #7 overall by Chicago Bulls", eventType: "DRAFT" },
        { year: 2021, title: "Traded to Orlando Magic", eventType: "TRADE" },
        { year: 2023, title: "Signed 4-year, $50M extension with Magic", eventType: "CONTRACT" },
      ],
    },
    {
      slug: "gary-trent-jr",
      firstName: "Gary",
      lastName: "Trent Jr.",
      birthYear: 1999,
      hometown: "Columbus, OH",
      highSchool: "Prolific Prep, Napa, CA",
      isFeatured: false,
      imageUrl: "https://a.espncdn.com/combiner/i?img=/i/headshots/mens-college-basketball/players/full/4277956.png",
      bio: "Freshman guard who shot 40.2% from three and was Duke's most reliable perimeter shooter. Son of former NBA player Gary Trent Sr.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Shooting Guard",
        currentEmployer: "Milwaukee Bucks",
        league: "NBA",
        location: "Milwaukee, WI",
        statusNote: "Selected #37 by Sacramento (traded to Portland) in 2018. Had breakout seasons in Portland (15.3 PPG) and Toronto (18.3 PPG in 2022-23). Signed with Milwaukee in 2024. Known as one of the NBA's best perimeter defenders and a streaky shooter. Career-best 18.3 PPG with the Raptors.",
        sourceUrl: "https://en.wikipedia.org/wiki/Gary_Trent_Jr.",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Shooting Guard", yearsAtSchool: "2017-2018", statsNote: "14.5 PPG · 40.2% from three · #37 pick", gamesPlayed: 37, pointsPerGame: 14.5, reboundsPerGame: 4.2, assistsPerGame: 1.4 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Prolific Prep", season: "2016-17", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 24.0, reboundsPerGame: 5.0, assistsPerGame: 3.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2017-18", yearLabel: "2017-18", sortOrder: 201, gamesPlayed: 37, minutesPerGame: 29.6, pointsPerGame: 14.5, reboundsPerGame: 4.2, assistsPerGame: 1.4, stealsPerGame: 1.0, fieldGoalPct: 0.438, threePointPct: 0.402, freeThrowPct: 0.817 },
        { level: "PROFESSIONAL", teamName: "Portland Trail Blazers", season: "2019-20", yearLabel: "2019-20", sortOrder: 302, gamesPlayed: 61, minutesPerGame: 16.8, pointsPerGame: 8.9, reboundsPerGame: 1.7, stealsPerGame: 0.6, fieldGoalPct: 0.399, threePointPct: 0.382, freeThrowPct: 0.778 },
        { level: "PROFESSIONAL", teamName: "Portland Trail Blazers", season: "2020-21", yearLabel: "2020-21", sortOrder: 303, gamesPlayed: 57, minutesPerGame: 33.1, pointsPerGame: 15.3, reboundsPerGame: 2.4, stealsPerGame: 1.0, fieldGoalPct: 0.425, threePointPct: 0.387, freeThrowPct: 0.773 },
        { level: "PROFESSIONAL", teamName: "Toronto Raptors", season: "2021-22", yearLabel: "2021-22", sortOrder: 304, gamesPlayed: 70, minutesPerGame: 36.3, pointsPerGame: 16.5, reboundsPerGame: 2.8, stealsPerGame: 1.7, fieldGoalPct: 0.414, threePointPct: 0.385, freeThrowPct: 0.848 },
        { level: "PROFESSIONAL", teamName: "Toronto Raptors", season: "2022-23", yearLabel: "2022-23", sortOrder: 305, gamesPlayed: 75, minutesPerGame: 35.0, pointsPerGame: 18.3, reboundsPerGame: 2.6, stealsPerGame: 1.2, fieldGoalPct: 0.435, threePointPct: 0.368, freeThrowPct: 0.867 },
        { level: "PROFESSIONAL", teamName: "Milwaukee Bucks", season: "2024-25", yearLabel: "2024-25", sortOrder: 307, gamesPlayed: 62, minutesPerGame: 28.0, pointsPerGame: 13.5, reboundsPerGame: 2.5, stealsPerGame: 1.0, fieldGoalPct: 0.420, threePointPct: 0.370, freeThrowPct: 0.850 },
      ],
      careerEvents: [
        { year: 2018, title: "Selected #37 by Sacramento (traded to Portland)", eventType: "DRAFT" },
        { year: 2021, title: "Traded to Toronto Raptors for Norman Powell", eventType: "TRADE" },
        { year: 2024, title: "Signed with Milwaukee Bucks", eventType: "SIGNING" },
      ],
    },
    {
      slug: "grayson-allen",
      firstName: "Grayson",
      lastName: "Allen",
      birthYear: 1995,
      hometown: "Jacksonville, FL",
      highSchool: "Providence School, Jacksonville, FL",
      isFeatured: false,
      imageUrl: "https://a.espncdn.com/combiner/i?img=/i/headshots/mens-college-basketball/players/full/3130407.png",
      bio: "Senior captain who led the team in experience. Averaged 15.5 PPG and was the emotional leader of the 2017-18 squad that reached the Elite Eight.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Shooting Guard",
        currentEmployer: "Phoenix Suns",
        league: "NBA",
        location: "Phoenix, AZ",
        statusNote: "Selected #21 overall by Utah in 2018. Won NBA Championship with Milwaukee in 2021 (45.3% from three in Finals). Has played for Jazz, Grizzlies, Bucks, and Suns. A reliable shooter and tough competitor at the NBA level.",
        sourceUrl: "https://en.wikipedia.org/wiki/Grayson_Allen",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Shooting Guard", yearsAtSchool: "2014-2018", statsNote: "15.5 PPG · Senior captain · 2015 champion · #21 pick" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2017-18", yearLabel: "2017-18 (Senior)", sortOrder: 204, gamesPlayed: 37, minutesPerGame: 33.8, pointsPerGame: 15.5, reboundsPerGame: 4.6, assistsPerGame: 3.3, stealsPerGame: 1.2, fieldGoalPct: 0.451, threePointPct: 0.378, freeThrowPct: 0.864 },
        { level: "PROFESSIONAL", teamName: "Utah Jazz", season: "2018-19", yearLabel: "2018-19 (Rookie)", sortOrder: 301, gamesPlayed: 38, minutesPerGame: 9.6, pointsPerGame: 3.3, reboundsPerGame: 0.8, fieldGoalPct: 0.380, threePointPct: 0.308, freeThrowPct: 0.833 },
        { level: "PROFESSIONAL", teamName: "Memphis Grizzlies", season: "2020-21", yearLabel: "2020-21", sortOrder: 303, gamesPlayed: 50, minutesPerGame: 18.0, pointsPerGame: 10.6, reboundsPerGame: 2.2, assistsPerGame: 2.2, fieldGoalPct: 0.448, threePointPct: 0.385, freeThrowPct: 0.872 },
        { level: "PROFESSIONAL", teamName: "Milwaukee Bucks", season: "2021-22", yearLabel: "2021-22 (Champion)", sortOrder: 304, gamesPlayed: 66, minutesPerGame: 25.3, pointsPerGame: 11.1, reboundsPerGame: 3.4, assistsPerGame: 2.2, fieldGoalPct: 0.447, threePointPct: 0.409, freeThrowPct: 0.878 },
        { level: "PROFESSIONAL", teamName: "Phoenix Suns", season: "2023-24", yearLabel: "2023-24", sortOrder: 306, gamesPlayed: 56, minutesPerGame: 22.0, pointsPerGame: 8.5, reboundsPerGame: 2.8, assistsPerGame: 2.5, fieldGoalPct: 0.430, threePointPct: 0.395, freeThrowPct: 0.860 },
      ],
      careerEvents: [
        { year: 2018, title: "Selected #21 overall by Utah Jazz", eventType: "DRAFT" },
        { year: 2022, title: "Won NBA Championship with Milwaukee Bucks", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "trevon-duval",
      firstName: "Trevon",
      lastName: "Duval",
      birthYear: 1999,
      hometown: "New Castle, DE",
      highSchool: "IMG Academy, Bradenton, FL",

      imageUrl: "https://a.espncdn.com/combiner/i?img=/i/headshots/mens-college-basketball/players/full/4277947.png",      bio: "The #1 point guard recruit in the 2017 class who ran Duke's offense. His passing and speed were elite, but his outside shooting was inconsistent. Averaged 10.3 PPG and 5.6 APG.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Point Guard",
        league: "Overseas / G-League",
        statusNote: "Went undrafted in 2018 despite being the top PG recruit. Has bounced between the G-League and overseas leagues, playing in Japan, Puerto Rico, and various G-League teams. His inability to shoot from the outside limited his NBA prospects despite elite athleticism.",
        sourceUrl: "https://en.wikipedia.org/wiki/Trevon_Duval",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Point Guard", yearsAtSchool: "2017-2018", statsNote: "10.3 PPG, 5.6 APG · #1 PG recruit · Elite passer" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "IMG Academy", season: "2016-17", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 18.4, reboundsPerGame: 4.2, assistsPerGame: 8.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2017-18", yearLabel: "2017-18", sortOrder: 201, gamesPlayed: 37, minutesPerGame: 28.4, pointsPerGame: 10.3, reboundsPerGame: 3.1, assistsPerGame: 5.6, stealsPerGame: 1.4, fieldGoalPct: 0.467, threePointPct: 0.292, freeThrowPct: 0.658 },
      ],
      careerEvents: [
        { year: 2018, title: "Went undrafted; signed with G-League", eventType: "SIGNING" },
      ],
    },
    {
      slug: "marques-bolden",
      firstName: "Marques",
      lastName: "Bolden",
      birthYear: 1998,
      hometown: "DeSoto, TX",
      highSchool: "DeSoto High School, DeSoto, TX",

      imageUrl: "https://a.espncdn.com/combiner/i?img=/i/headshots/mens-college-basketball/players/full/4066636.png",      bio: "Sophomore center who battled knee issues but played a role as the backup big. Improved defensively and was a solid rim protector when healthy.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "Texas",
        statusNote: "Returned for his junior year in 2018-19 where he had his best season. Went undrafted in 2019. Knee injuries continued to hamper his professional prospects.",
        sourceUrl: "https://en.wikipedia.org/wiki/Marques_Bolden",
      },
      membership: { role: "PLAYER", jerseyNumber: 20, position: "Center", yearsAtSchool: "2016-2019", statsNote: "2.7 PPG, 2.2 RPG · Battled knee injuries" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2017-18", yearLabel: "2017-18", sortOrder: 202, gamesPlayed: 26, minutesPerGame: 10.8, pointsPerGame: 2.7, reboundsPerGame: 2.2, blocksPerGame: 0.7, fieldGoalPct: 0.654 },
      ],
      careerEvents: [],
    },
    {
      slug: "jack-white",
      firstName: "Jack",
      lastName: "White",
      birthYear: 1997,
      hometown: "Traralgon, Victoria, Australia",
      highSchool: "Caulfield Grammar School, Melbourne, Australia",

      imageUrl: "https://a.espncdn.com/combiner/i?img=/i/headshots/mens-college-basketball/players/full/4066290.png",      bio: "Australian sophomore forward who saw limited playing time in 2017-18 but would go on to become a key contributor in his junior and senior years. A versatile 6'7\" wing who defended multiple positions and provided toughness and energy off the bench.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Small Forward",
        league: "Basketball Bundesliga / BSL",
        statusNote: "After four seasons at Duke, White returned to Australia to play for Melbourne United in the NBL. He then signed with the Denver Nuggets and was part of their 2023 NBA Championship roster. Has since played overseas in Turkey (Mersin MSK) and Germany (Bayern Munich). Signed with Bayern Munich in April 2025 for the remainder of the Bundesliga season.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jack_White_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 41, position: "Small Forward", yearsAtSchool: "2016-2020", statsNote: "Limited role as sophomore · Developed into key contributor later" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2017-18", yearLabel: "2017-18 (Sophomore)", sortOrder: 202, gamesPlayed: 22, minutesPerGame: 5.5, pointsPerGame: 1.2, reboundsPerGame: 1.0, fieldGoalPct: 0.333, threePointPct: 0.167 },
      ],
      careerEvents: [
        { year: 2020, title: "Signed with Melbourne United (NBL)", eventType: "SIGNING" },
        { year: 2023, title: "Won NBA Championship with Denver Nuggets", eventType: "CHAMPIONSHIP" },
        { year: 2025, title: "Signed with Bayern Munich (Bundesliga)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "alex-oconnell",
      firstName: "Alex",
      lastName: "O'Connell",
      birthYear: 1999,
      hometown: "Roswell, GA",
      highSchool: "Milton High School, Alpharetta, GA",

      imageUrl: "https://a.espncdn.com/combiner/i?img=/i/headshots/mens-college-basketball/players/full/4278087.png",      bio: "Freshman shooting guard who finished as Duke's most accurate three-point shooter at 48.9% from beyond the arc. Played behind Grayson Allen but showed flashes of his scoring ability, averaging 3.3 PPG in limited minutes.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Shooting Guard",
        currentEmployer: "ALBA Berlin",
        league: "Basketball Bundesliga",
        location: "Berlin, Germany",
        statusNote: "Played three seasons at Duke before transferring to Creighton for his senior year in 2021-22. After going undrafted, O'Connell played in the G-League with the Westchester Knicks. Signed with ALBA Berlin of the German Basketball Bundesliga in November 2025, continuing his professional career in Europe.",
        sourceUrl: "https://en.wikipedia.org/wiki/Alex_O%27Connell_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Shooting Guard", yearsAtSchool: "2017-2020", statsNote: "3.3 PPG · 48.9% from three as freshman · Transferred to Creighton" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2017-18", yearLabel: "2017-18", sortOrder: 203, gamesPlayed: 22, minutesPerGame: 10.4, pointsPerGame: 3.3, reboundsPerGame: 1.4, fieldGoalPct: 0.449, threePointPct: 0.489, freeThrowPct: 0.750 },
      ],
      careerEvents: [
        { year: 2020, title: "Transferred to Creighton University", eventType: "OTHER" },
        { year: 2025, title: "Signed with ALBA Berlin (Bundesliga)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "javin-delaurier",
      firstName: "Javin",
      lastName: "DeLaurier",
      birthYear: 1998,
      hometown: "Shipman, VA",
      highSchool: "St. Anne's-Belfield School, Charlottesville, VA",

      imageUrl: "https://a.espncdn.com/combiner/i?img=/i/headshots/mens-college-basketball/players/full/4066635.png",      bio: "Sophomore power forward who served as the primary backup to Wendell Carter Jr. An energetic rim-runner and shot-blocker who shot 64.3% from the field. Averaged 3.4 PPG and 4.0 RPG in 33 games while providing critical depth in the frontcourt.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Power Forward / Center",
        league: "Basketbol Super Ligi (Turkey)",
        statusNote: "Played four seasons at Duke (2016-20), earning two ACC Tournament championships (2017, 2019). Went undrafted in 2020 and had stints with the Charlotte Hornets (training camp), Greensboro Swarm (G-League), and Niagara River Lions (CEBL), where he was named All-CEBL First Team. Played in Israel for Hapoel Holon and signed with Bursaspor of the Turkish BSL in July 2025.",
        sourceUrl: "https://en.wikipedia.org/wiki/Javin_DeLaurier",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Power Forward", yearsAtSchool: "2016-2020", statsNote: "3.4 PPG, 4.0 RPG · 64.3% FG · Key backup big" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2017-18", yearLabel: "2017-18 (Sophomore)", sortOrder: 205, gamesPlayed: 33, minutesPerGame: 12.5, pointsPerGame: 3.4, reboundsPerGame: 4.0, blocksPerGame: 0.5, fieldGoalPct: 0.643, threePointPct: 0.125, freeThrowPct: 0.553 },
      ],
      careerEvents: [
        { year: 2020, title: "Went undrafted; signed training camp deal with Charlotte Hornets", eventType: "SIGNING" },
        { year: 2021, title: "Named All-CEBL First Team with Niagara River Lions", eventType: "AWARD" },
        { year: 2025, title: "Signed with Bursaspor (Turkish BSL)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "jordan-goldwire",
      firstName: "Jordan",
      lastName: "Goldwire",
      birthYear: 1999,
      hometown: "Norcross, GA",
      highSchool: "Norcross High School, Norcross, GA",

      imageUrl: "https://a.espncdn.com/combiner/i?img=/i/headshots/mens-college-basketball/players/full/4278017.png",      bio: "Freshman point guard who provided defensive intensity off the bench. Appeared in 26 games with limited minutes, averaging 1.0 PPG and 0.9 APG. Would later develop into one of Duke's best defensive players, earning ACC All-Defensive Team honors as a senior.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Point Guard",
        league: "LNBP (Mexico)",
        statusNote: "Played four seasons at Duke before using his extra COVID year as a grad transfer at Oklahoma. Led the ACC in assist-to-turnover ratio as a senior. Has played professionally in the G-League (Austin Spurs), Montenegro (Mornar Bar), Dominican Republic (Reales de La Vega, where he won a title), and Mexico (Halcones de Xalapa, Lobos Plateados de la BUAP).",
        sourceUrl: "https://en.wikipedia.org/wiki/Jordan_Goldwire",
      },
      membership: { role: "PLAYER", jerseyNumber: 14, position: "Point Guard", yearsAtSchool: "2017-2021", statsNote: "1.0 PPG, 0.9 APG as freshman · Defensive specialist" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Norcross High School", season: "2016-17", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 12.0, assistsPerGame: 7.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2017-18", yearLabel: "2017-18", sortOrder: 201, gamesPlayed: 26, minutesPerGame: 6.5, pointsPerGame: 1.0, reboundsPerGame: 0.5, assistsPerGame: 0.9 },
      ],
      careerEvents: [
        { year: 2021, title: "Transferred to Oklahoma as grad transfer", eventType: "OTHER" },
        { year: 2023, title: "Won LNBP title with Reales de La Vega", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "jordan-tucker",
      firstName: "Jordan",
      lastName: "Tucker",
      birthYear: 1999,
      hometown: "White Plains, NY",
      highSchool: "Wheeler High School, Marietta, GA",
      bio: "Four-star freshman wing who appeared in just 2 games before deciding to transfer mid-season. Scored 6 points in limited action. Transferred to Butler, where he became a productive player, before eventually going pro.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Small Forward",
        league: "Lithuanian Basketball League (LKL)",
        statusNote: "Transferred to Butler after one semester at Duke and had a productive career with the Bulldogs. Went undrafted and has played professionally overseas in multiple European leagues, including stints in France and Lithuania. Signed with Neptūnas Klaipėda of the Lithuanian Basketball League in July 2025.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jordan_Tucker",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Small Forward", yearsAtSchool: "2017-2018", statsNote: "3.0 PPG in 2 games · Transferred to Butler mid-season" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2017-18", yearLabel: "2017-18", sortOrder: 206, gamesPlayed: 2, minutesPerGame: 8.0, pointsPerGame: 3.0 },
      ],
      careerEvents: [
        { year: 2018, title: "Transferred to Butler University", eventType: "OTHER" },
        { year: 2025, title: "Signed with Neptūnas Klaipėda (LKL)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "antonio-vrankovic",
      firstName: "Antonio",
      lastName: "Vrankovic",
      birthYear: 1997,
      hometown: "Fort Lauderdale, FL",
      highSchool: "Pine Crest School, Fort Lauderdale, FL",
      bio: "7-foot sophomore center and son of former NBA player Stojko Vrankovic. Born in Minneapolis but raised in Croatia and Florida. Averaged 27.5 PPG, 16.1 RPG, and 5.0 BPG as a high school senior, including a 55-point game. Played a reserve role at Duke, appearing in 14 games in 2017-18.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        league: "European Professional Basketball",
        statusNote: "Graduated from Duke in 2019 and pursued a professional career overseas. Has played in Croatia (KK Cedevita Junior Zagreb), the Czech Republic, Spain, France, and Montenegro. His father Stojko Vrankovic played five seasons in the NBA with the Boston Celtics and Minnesota Timberwolves.",
        sourceUrl: "https://basketball.realgm.com/player/Antonio-Vrankovic/Summary/41578",
      },
      membership: { role: "PLAYER", jerseyNumber: 30, position: "Center", yearsAtSchool: "2016-2019", statsNote: "Reserve center · Son of NBA player Stojko Vrankovic" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Pine Crest School", season: "2015-16", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 27.5, reboundsPerGame: 16.1, blocksPerGame: 5.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2017-18", yearLabel: "2017-18 (Sophomore)", sortOrder: 203, gamesPlayed: 14, minutesPerGame: 4.0, pointsPerGame: 0.9, reboundsPerGame: 1.0, fieldGoalPct: 0.500 },
      ],
      careerEvents: [
        { year: 2019, title: "Graduated from Duke University", eventType: "STUDENT" },
      ],
    },
    {
      slug: "brennan-besser-2018",
      firstName: "Brennan",
      lastName: "Besser",
      birthYear: 1997,
      hometown: "Chicago, IL",
      highSchool: "Latin School, Chicago, IL",
      bio: "Junior walk-on guard in his third year with the program. Known for being one of the last players off the practice floor and facilitating extra workouts for teammates. Did not see game action in 2017-18 but remained a valued member of the team culture.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Director, Strategic Partnerships",
        currentEmployer: "Intersport",
        location: "Chicago, IL",
        statusNote: "After graduating from Duke in 2019, Besser pursued a career in sports business at Intersport, a Chicago-based sports marketing agency. He also founded Walk On America, a nonprofit that raised money and awareness for the Intellectual and Developmental Disability community through a cross-country bicycle ride from Seattle to New York City.",
        sourceUrl: "https://www.linkedin.com/in/brennan-besser-10a7921a7/",
      },
      membership: { role: "PLAYER", jerseyNumber: 53, position: "Guard", yearsAtSchool: "2015-2019", statsNote: "Walk-on · Did not see game action in 2017-18" },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2017-18", yearLabel: "2017-18 (Junior)", sortOrder: 207, gamesPlayed: 0 },
      ],
      careerEvents: [],
    },
    {
      slug: "mike-krzyzewski",
      firstName: "Mike",
      lastName: "Krzyzewski",
      birthYear: 1947,
      hometown: "Chicago, IL",
      highSchool: "Weber High School, Chicago, IL",
      bio: "Legendary head coach in his 38th season at Duke. Led the 2017-18 team to the Elite Eight with one of the most talented freshman classes in recent memory.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Retired Head Coach",
        currentEmployer: "Duke University (Emeritus)",
        location: "Durham, NC",
        statusNote: "Retired after 2021-22 with 1,202 career wins. Five-time national champion.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Krzyzewski",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "1980-2022", statsNote: "29-8 · Elite Eight (lost to Kansas)" },
      seasonStats: [
        { level: "COACHING", teamName: "Duke Blue Devils", season: "2017-18", yearLabel: "2017-18", sortOrder: 1, wins: 29, losses: 8, tournamentResult: "Elite Eight (lost to Kansas)" },
      ],
      careerEvents: [],
    },
    {
      slug: "jeff-capel",
      firstName: "Jeff",
      lastName: "Capel",
      birthYear: 1975,
      hometown: "Fayetteville, NC",
      highSchool: "South View High School, Hope Mills, NC",
      bio: "Associate head coach at Duke who was one of the top assistants and recruiters in college basketball.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "University of Pittsburgh",
        location: "Pittsburgh, PA",
        statusNote: "Left Duke in 2018 to become head coach at Pitt. Has rebuilt the Panthers program.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jeff_Capel",
      },
      membership: { role: "ASSISTANT_COACH", position: "Associate Head Coach", yearsAtSchool: "2011-2018", statsNote: "Top recruiter · Landed Zion, RJ, Cam class" },
      careerEvents: [
        { year: 2018, title: "Named head coach at University of Pittsburgh", eventType: "COACHING" },
      ],
    },
    {
      slug: "nate-james",
      firstName: "Nate",
      lastName: "James",
      birthYear: 1979,
      hometown: "Seattle, WA",
      highSchool: "Lower Merion High School, Ardmore, PA",
      bio: "Former Duke player (1997-2001) and assistant coach. Key recruiter and mentor to players.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "Austin Peay State University",
        location: "Clarksville, TN",
        statusNote: "Left Duke in 2021 to become head coach at Austin Peay. 2001 NCAA champion as a player.",
        sourceUrl: "https://en.wikipedia.org/wiki/Nate_James",
      },
      membership: { role: "ASSISTANT_COACH", position: "Assistant Coach", yearsAtSchool: "2007-2021", statsNote: "Former Duke player · Key recruiter" },
      careerEvents: [
        { year: 2021, title: "Named head coach at Austin Peay State University", eventType: "COACHING" },
      ],
    },
    {
      slug: "jon-scheyer",
      firstName: "Jon",
      lastName: "Scheyer",
      birthYear: 1987,
      hometown: "Northbrook, IL",
      highSchool: "Glenbrook North High School, Northbrook, IL",
      bio: "Former Duke player (2006-10) and 2010 national champion who served as associate head coach and head-coach-in-waiting.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "Duke University",
        league: "ACC",
        location: "Durham, NC",
        statusNote: "Succeeded Coach K in 2022. Has led Duke to three NCAA Tournaments in three seasons, including a Final Four in 2025.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jon_Scheyer",
      },
      membership: { role: "ASSISTANT_COACH", position: "Associate Head Coach / Coach-in-Waiting", yearsAtSchool: "2013-2022", statsNote: "2010 champion as player · Named successor to Coach K" },
      careerEvents: [
        { year: 2022, title: "Named head coach at Duke, succeeding Coach K", eventType: "COACHING" },
      ],
    },
  ],
};
