import type { TeamSeed } from "./types";

export const dukeBasketball2005: TeamSeed = {
  slug: "duke-basketball-2005",
  name: "Duke Blue Devils",
  season: "2004-2005",
  sport: "Men's Basketball",
  school: "Duke University",
  conference: "ACC",
  accomplishment: "Sweet Sixteen (27-6)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  mascotName: "Blue Devil",
  people: [
    {
      slug: "jj-redick",
      firstName: "J.J.",
      lastName: "Redick",
      birthYear: 1984,
      hometown: "Roanoke, VA",
      highSchool: "Cave Spring High School, Roanoke, VA",
      isFeatured: true,
      bio: "Duke's all-time leading scorer and now head coach of the LA Lakers.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Coach",
        currentEmployer: "Los Angeles Lakers",
        league: "NBA",
        location: "Los Angeles, CA",
        statusNote:
          "Selected #11 overall in 2006, Redick played 15 NBA seasons as an elite shooter. After retiring in 2021, he built a media empire before being hired as Lakers head coach in June 2024.",
        sourceUrl: "https://en.wikipedia.org/wiki/J._J._Redick",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 4,
        position: "Shooting Guard",
        yearsAtSchool: "2002-2006",
        statsNote: "Junior • ACC Player of the Year candidate • Elite scorer",
        gamesPlayed: 33,
        pointsPerGame: 21.8,
      },
      careerEvents: [
        { year: 2006, title: "Selected #11 overall by the Orlando Magic", eventType: "DRAFT" },
        { year: 2024, title: "Named head coach of the Los Angeles Lakers", eventType: "CAREER" },
      ],
    },
    {
      slug: "shelden-williams",
      firstName: "Shelden",
      lastName: "Williams",
      birthYear: 1983,
      hometown: "Midwest City, OK",
      highSchool: "Midwest City High School, Midwest City, OK",
      isFeatured: false,
      bio: "A dominant shot-blocking center and Duke's all-time blocks leader.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach / Trainer",
        location: "Atlanta, GA",
        statusNote:
          "Selected #5 overall by the Hawks in 2006. Now involved in youth basketball coaching in Atlanta.",
        sourceUrl: "https://en.wikipedia.org/wiki/Shelden_Williams",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 23,
        position: "Center / Power Forward",
        yearsAtSchool: "2002-2006",
        statsNote: "Junior • NABC Defensive POY candidate • Double-double machine",
        gamesPlayed: 33,
        pointsPerGame: 14.5,
        reboundsPerGame: 9.7,
      },
      careerEvents: [
        { year: 2006, title: "Selected #5 overall by the Atlanta Hawks", eventType: "DRAFT" },
      ],
    },
    {
      slug: "daniel-ewing",
      firstName: "Daniel",
      lastName: "Ewing",
      birthYear: 1983,
      hometown: "Houston, TX",
      highSchool: "Willowridge High School, Houston, TX",
      isFeatured: false,
      bio: "A four-year guard who developed into a key scorer and leader.",
      status: {
        occupationType: "FRONT_OFFICE",
        currentTitle: "Professional Scout",
        currentEmployer: "Los Angeles Lakers",
        league: "NBA",
        location: "Los Angeles, CA",
        statusNote:
          "Selected #32 overall by the LA Clippers in 2005. Now a professional scout for the Lakers.",
        sourceUrl: "https://en.wikipedia.org/wiki/Daniel_Ewing",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 5,
        position: "Shooting Guard",
        yearsAtSchool: "2001-2005",
        statsNote: "Senior captain • Team leader and go-to scorer",
        gamesPlayed: 33,
        pointsPerGame: 16.2,
        assistsPerGame: 3.8,
      },
      careerEvents: [
        { year: 2005, title: "Selected #32 overall by the LA Clippers", eventType: "DRAFT" },
      ],
    },
    {
      slug: "demarcus-nelson",
      firstName: "DeMarcus",
      lastName: "Nelson",
      birthYear: 1986,
      hometown: "Vallejo, CA",
      highSchool: "Jesse Bethel High School, Vallejo, CA",
      isFeatured: false,
      bio: "A versatile guard/forward who was a four-year contributor at Duke, earning ACC All-Defensive Team honors and becoming a fan favorite for his hustle.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "California",
        statusNote:
          "After graduating from Duke in 2008, Nelson went undrafted and played briefly in the NBA Summer League with the Warriors and overseas. He transitioned to coaching and player development, working with youth basketball programs in the Bay Area. He remains connected to Duke basketball.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/demarcus-nelson/4244",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 1,
        position: "Shooting Guard / Small Forward",
        yearsAtSchool: "2004-2008",
        statsNote: "Freshman contributor • ACC All-Defensive Team (later years)",
      },
      careerEvents: [
        { year: 2008, title: "Graduated from Duke; went undrafted", eventType: "CAREER" },
      ],
    },
    {
      slug: "shavlik-randolph",
      firstName: "Shavlik",
      lastName: "Randolph",
      birthYear: 1983,
      hometown: "Raleigh, NC",
      highSchool: "Broughton High School, Raleigh, NC",
      isFeatured: false,
      bio: "A McDonald's All-American power forward from Raleigh.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Basketball Player",
        location: "Raleigh, NC",
        statusNote:
          "Went undrafted in 2006. Played briefly in the NBA and overseas.",
        sourceUrl: "https://en.wikipedia.org/wiki/Shavlik_Randolph",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 42,
        position: "Power Forward",
        yearsAtSchool: "2002-2006",
        statsNote: "Junior • Interior scorer and rebounder",
        gamesPlayed: 33,
        pointsPerGame: 8.2,
        reboundsPerGame: 5.1,
      },
      careerEvents: [
        { year: 2006, title: "Went undrafted; signed with 76ers", eventType: "SIGNING" },
      ],
    },
    {
      slug: "lee-melchionni",
      firstName: "Lee",
      lastName: "Melchionni",
      birthYear: 1983,
      hometown: "Germantown, PA",
      highSchool: "Germantown Academy, Fort Washington, PA",
      isFeatured: false,
      bio: "A sharpshooting guard and four-year contributor.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Business Professional",
        location: "Philadelphia, PA",
        statusNote:
          "After Duke, Melchionni played briefly overseas before transitioning to business in the Philadelphia area.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/lee-melchionni/4250",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 20,
        position: "Shooting Guard",
        yearsAtSchool: "2002-2006",
        statsNote: "Junior • Reliable perimeter shooter",
      },
      careerEvents: [
        { year: 2006, title: "Graduated from Duke", eventType: "CAREER" },
      ],
    },
    {
      slug: "sean-dockery",
      firstName: "Sean",
      lastName: "Dockery",
      birthYear: 1985,
      hometown: "Milwaukee, WI",
      highSchool: "Vincent High School, Milwaukee, WI",
      isFeatured: false,
      bio: "A quick, athletic point guard remembered for his buzzer-beating half-court shot against Virginia Tech.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "Milwaukee, WI",
        statusNote:
          "After Duke, Dockery played overseas. He transitioned to coaching and youth basketball development.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/sean-dockery/4252",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 3,
        position: "Point Guard",
        yearsAtSchool: "2003-2007",
        statsNote: "Sophomore • Hit legendary buzzer-beater vs Virginia Tech",
      },
      careerEvents: [
        { year: 2005, title: "Hit half-court buzzer-beater to beat Virginia Tech", eventType: "OTHER" },
      ],
    },
    {
      slug: "mike-krzyzewski",
      firstName: "Mike",
      lastName: "Krzyzewski",
      birthYear: 1947,
      hometown: "Chicago, IL",
      highSchool: "Weber High School, Chicago, IL",
      isFeatured: true,
      bio: "The winningest coach in Division I men's basketball history.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Special Advisor / Duke Ambassador",
        currentEmployer: "NBA / Duke University",
        location: "Durham, NC",
        statusNote:
          "Retired in 2022 with 1,202 victories and five national championships.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Krzyzewski",
      },
      membership: {
        role: "HEAD_COACH",
        position: "Head Coach",
        yearsAtSchool: "1980-2022",
        statsNote: "27-6 record in 2004-05 • Sweet Sixteen",
      },
      careerEvents: [
        { year: 2022, title: "Retired as winningest coach in D-I history", eventType: "RETIREMENT" },
      ],
    },
  ],
};
