import type { TeamSeed } from "./types";

export const dukeBasketball2011: TeamSeed = {
  slug: "duke-basketball-2011",
  name: "Duke Blue Devils",
  season: "2010-2011",
  sport: "Men's Basketball",
  school: "Duke University",
  conference: "ACC",
  accomplishment: "Sweet Sixteen (32-5)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  mascotName: "Blue Devil",
  people: [
    {
      slug: "kyrie-irving",
      firstName: "Kyrie",
      lastName: "Irving",
      birthYear: 1992,
      hometown: "West Orange, NJ",
      highSchool: "St. Patrick High School, Elizabeth, NJ",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/202681.png",
      bio: "One of the most talented players to ever play at Duke, Irving's freshman season was cut short to just 11 games by a toe injury. Despite the limited sample, he showed enough to be selected #1 overall in the 2011 NBA Draft.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Dallas Mavericks",
        league: "NBA",
        location: "Dallas, TX",
        statusNote:
          "Selected #1 overall by the Cleveland Cavaliers in 2011, Irving hit one of the most iconic shots in NBA history — the go-ahead three-pointer in Game 7 of the 2016 Finals to win Cleveland's first championship. An eight-time All-Star and 2012 Rookie of the Year, Irving has played for the Cavaliers, Celtics, Nets, and Mavericks. He re-signed a 3-year, $119M deal with Dallas in July 2025 but is sitting out the 2025-26 season recovering from ACL reconstruction surgery (torn March 2025). Mentoring rookie Cooper Flagg while he rehabs.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kyrie_Irving",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 1,
        position: "Point Guard",
        yearsAtSchool: "2010-2011",
        statsNote: "#1 overall pick • 17.5 PPG in 11 games • Toe injury limited season",
        gamesPlayed: 11,
        pointsPerGame: 17.5,
        reboundsPerGame: 3.4,
        assistsPerGame: 4.3,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2010-11", yearLabel: "2010-11 (Freshman, 11 games)", sortOrder: 201, gamesPlayed: 11, pointsPerGame: 17.5, reboundsPerGame: 3.4, assistsPerGame: 4.3, stealsPerGame: 1.5, fieldGoalPct: 0.532, threePointPct: 0.462, freeThrowPct: 0.901 },
        { level: "PROFESSIONAL", teamName: "Cleveland Cavaliers", season: "2011-12", yearLabel: "2011-12 (ROY)", sortOrder: 301, gamesPlayed: 51, pointsPerGame: 18.5, reboundsPerGame: 3.7, assistsPerGame: 5.4, stealsPerGame: 1.1, fieldGoalPct: 0.469, threePointPct: 0.399, freeThrowPct: 0.872 },
        { level: "PROFESSIONAL", teamName: "Cleveland Cavaliers", season: "2013-14", yearLabel: "2013-14 (All-Star)", sortOrder: 303, gamesPlayed: 71, pointsPerGame: 20.8, reboundsPerGame: 3.6, assistsPerGame: 6.1, fieldGoalPct: 0.430, threePointPct: 0.358, freeThrowPct: 0.861 },
        { level: "PROFESSIONAL", teamName: "Cleveland Cavaliers", season: "2015-16", yearLabel: "2015-16 (NBA Champion!)", sortOrder: 305, gamesPlayed: 53, pointsPerGame: 19.6, reboundsPerGame: 3.0, assistsPerGame: 4.7, fieldGoalPct: 0.448, threePointPct: 0.321, freeThrowPct: 0.885 },
        { level: "PROFESSIONAL", teamName: "Boston Celtics", season: "2017-18", yearLabel: "2017-18 (All-Star)", sortOrder: 307, gamesPlayed: 60, pointsPerGame: 24.4, reboundsPerGame: 3.8, assistsPerGame: 5.1, fieldGoalPct: 0.491, threePointPct: 0.401, freeThrowPct: 0.905 },
        { level: "PROFESSIONAL", teamName: "Brooklyn Nets", season: "2019-20", yearLabel: "2019-20 (All-Star)", sortOrder: 309, gamesPlayed: 20, pointsPerGame: 27.4, reboundsPerGame: 5.2, assistsPerGame: 6.4, fieldGoalPct: 0.478, threePointPct: 0.394, freeThrowPct: 0.922 },
        { level: "PROFESSIONAL", teamName: "Dallas Mavericks", season: "2022-23", yearLabel: "2022-23", sortOrder: 312, gamesPlayed: 58, pointsPerGame: 27.1, reboundsPerGame: 5.1, assistsPerGame: 5.5, fieldGoalPct: 0.487, threePointPct: 0.411, freeThrowPct: 0.905 },
        { level: "PROFESSIONAL", teamName: "Dallas Mavericks", season: "2023-24", yearLabel: "2023-24 (NBA Finals)", sortOrder: 313, gamesPlayed: 58, pointsPerGame: 25.6, reboundsPerGame: 5.2, assistsPerGame: 5.2, fieldGoalPct: 0.497, threePointPct: 0.415, freeThrowPct: 0.903 },
      ],
      careerEvents: [
        { year: 2011, title: "Selected #1 overall by the Cleveland Cavaliers", eventType: "DRAFT" },
        { year: 2012, title: "Won NBA Rookie of the Year", eventType: "AWARD" },
        { year: 2016, title: "Won NBA Championship with Cavaliers (iconic Game 7 shot)", eventType: "CHAMPIONSHIP" },
        { year: 2017, title: "Traded to the Boston Celtics", eventType: "TRADE" },
        { year: 2023, title: "Traded to the Dallas Mavericks", eventType: "TRADE" },
        { year: 2025, title: "Tore ACL; signed 3-year, $119M extension with Dallas", eventType: "INJURY" },
      ],
    },
    {
      slug: "nolan-smith",
      firstName: "Nolan",
      lastName: "Smith",
      birthYear: 1988,
      hometown: "Upper Marlboro, MD",
      highSchool: "Oak Hill Academy, Mouth of Wilson, VA",
      isFeatured: true,
      bio: "A senior captain who averaged 20.6 PPG and was named ACC Player of the Year. Son of the late Derek Smith, a former NBA player.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "Tennessee State University",
        location: "Nashville, TN",
        statusNote:
          "Selected #21 overall by Portland in 2011 but had a brief NBA career. Returned to Duke as an assistant coach under Jon Scheyer, then was hired as head coach at Tennessee State in July 2025. In his first season, he led the Tigers to the OVC championship, their first March Madness berth since 1994, a program-record 23 wins, and was named OVC Co-Coach of the Year. A remarkable start to his head coaching career at an HBCU.",
        sourceUrl: "https://hbcugameday.com/2026/03/09/duke-legend-nolan-smith-hbcu-tennessee-state-march-madness/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 2,
        position: "Guard",
        yearsAtSchool: "2007-2011",
        statsNote: "Senior captain • ACC Player of the Year • 20.6 PPG",
        gamesPlayed: 37,
        pointsPerGame: 20.6,
        reboundsPerGame: 4.5,
        assistsPerGame: 5.1,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2007-08", yearLabel: "2007-08 (Freshman)", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 5.6, reboundsPerGame: 1.7, assistsPerGame: 1.3 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2008-09", yearLabel: "2008-09", sortOrder: 202, gamesPlayed: 36, pointsPerGame: 8.9, reboundsPerGame: 2.5, assistsPerGame: 2.8 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2009-10", yearLabel: "2009-10 (National Champion)", sortOrder: 203, gamesPlayed: 39, pointsPerGame: 17.4, reboundsPerGame: 3.8, assistsPerGame: 5.1 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2010-11", yearLabel: "2010-11 (ACC POY)", sortOrder: 204, gamesPlayed: 37, pointsPerGame: 20.6, reboundsPerGame: 4.5, assistsPerGame: 5.1, fieldGoalPct: 0.468, threePointPct: 0.383, freeThrowPct: 0.835 },
      ],
      careerEvents: [
        { year: 2010, title: "Won NCAA National Championship with Duke", eventType: "CHAMPIONSHIP" },
        { year: 2011, title: "Won ACC Player of the Year; Selected #21 overall by Portland", eventType: "DRAFT" },
        { year: 2025, title: "Named head coach at Tennessee State University", eventType: "CAREER" },
        { year: 2026, title: "Led Tennessee State to OVC title and March Madness", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "kyle-singler",
      firstName: "Kyle",
      lastName: "Singler",
      birthYear: 1988,
      hometown: "Medford, OR",
      highSchool: "South Medford High School, Medford, OR",
      isFeatured: false,
      bio: "A four-year starter who was the 2010 Final Four Most Outstanding Player. Singler averaged 16.9 PPG as a senior.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NBA Player",
        location: "Oklahoma",
        statusNote:
          "Selected #33 overall by Detroit in 2011. Played 8 NBA seasons with the Pistons and Thunder before retiring in 2019. The 2010 Final Four MOP who helped Duke win the national championship. Post-career life has been challenging — he was arrested in October 2025 in Oklahoma on domestic abuse charges.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kyle_Singler",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 12,
        position: "Small Forward",
        yearsAtSchool: "2007-2011",
        statsNote: "Senior • 2010 Final Four MOP • 4-year starter • 16.9 PPG",
        gamesPlayed: 37,
        pointsPerGame: 16.9,
        reboundsPerGame: 6.8,
        assistsPerGame: 1.6,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2007-08", yearLabel: "2007-08 (Freshman)", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 13.3, reboundsPerGame: 5.6, assistsPerGame: 1.2 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2009-10", yearLabel: "2009-10 (Champion, Final Four MOP)", sortOrder: 203, gamesPlayed: 39, pointsPerGame: 17.7, reboundsPerGame: 7.0, assistsPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2010-11", yearLabel: "2010-11 (Senior)", sortOrder: 204, gamesPlayed: 37, pointsPerGame: 16.9, reboundsPerGame: 6.8, assistsPerGame: 1.6, fieldGoalPct: 0.449, threePointPct: 0.380 },
      ],
      careerEvents: [
        { year: 2010, title: "Won NCAA Championship; named Final Four MOP", eventType: "CHAMPIONSHIP" },
        { year: 2011, title: "Selected #33 overall by the Detroit Pistons", eventType: "DRAFT" },
        { year: 2019, title: "Retired from the NBA", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "seth-curry",
      firstName: "Seth",
      lastName: "Curry",
      birthYear: 1990,
      hometown: "Charlotte, NC",
      highSchool: "Charlotte Christian School, Charlotte, NC",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/203552.png",
      bio: "Steph Curry's younger brother who developed into one of the best shooters in Duke history over four years. Now teammates with his brother on the Warriors.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Golden State Warriors",
        league: "NBA",
        location: "San Francisco, CA",
        statusNote:
          "Went undrafted in 2013 but carved out an 11-year NBA career with 8 teams thanks to his elite shooting. Now playing alongside brother Stephen Curry on the Golden State Warriors in 2025-26, fulfilling a lifelong dream of playing together. A career 44.3% three-point shooter, one of the best in league history.",
        sourceUrl: "https://en.wikipedia.org/wiki/Seth_Curry",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 30,
        position: "Guard",
        yearsAtSchool: "2008-2013",
        statsNote: "Redshirt Sophomore • Developing shooter • Steph's brother",
        gamesPlayed: 37,
        pointsPerGame: 9.0,
        reboundsPerGame: 1.8,
        assistsPerGame: 2.0,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2009-10", yearLabel: "2009-10 (Champion)", sortOrder: 202, gamesPlayed: 37, pointsPerGame: 5.8, reboundsPerGame: 1.5, assistsPerGame: 1.8 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2010-11", yearLabel: "2010-11", sortOrder: 203, gamesPlayed: 37, pointsPerGame: 9.0, reboundsPerGame: 1.8, assistsPerGame: 2.0, threePointPct: 0.384 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2011-12", yearLabel: "2011-12", sortOrder: 204, gamesPlayed: 34, pointsPerGame: 13.2, reboundsPerGame: 2.5, assistsPerGame: 2.5, threePointPct: 0.416 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2012-13", yearLabel: "2012-13 (Senior, All-ACC)", sortOrder: 205, gamesPlayed: 34, pointsPerGame: 17.5, reboundsPerGame: 3.9, assistsPerGame: 2.7, threePointPct: 0.438 },
        { level: "PROFESSIONAL", teamName: "Sacramento Kings", season: "2015-16", yearLabel: "2015-16", sortOrder: 303, gamesPlayed: 44, pointsPerGame: 6.8, reboundsPerGame: 1.5, assistsPerGame: 1.5, threePointPct: 0.450 },
        { level: "PROFESSIONAL", teamName: "Dallas Mavericks", season: "2016-17", yearLabel: "2016-17", sortOrder: 304, gamesPlayed: 70, pointsPerGame: 12.8, reboundsPerGame: 2.7, assistsPerGame: 2.7, threePointPct: 0.425 },
        { level: "PROFESSIONAL", teamName: "Philadelphia 76ers", season: "2020-21", yearLabel: "2020-21", sortOrder: 308, gamesPlayed: 57, pointsPerGame: 12.5, reboundsPerGame: 2.7, assistsPerGame: 2.9, threePointPct: 0.450 },
        { level: "PROFESSIONAL", teamName: "Brooklyn Nets", season: "2021-22", yearLabel: "2021-22", sortOrder: 309, gamesPlayed: 46, pointsPerGame: 14.9, reboundsPerGame: 2.6, assistsPerGame: 2.6, threePointPct: 0.419 },
      ],
      careerEvents: [
        { year: 2010, title: "Won NCAA Championship with Duke", eventType: "CHAMPIONSHIP" },
        { year: 2013, title: "Went undrafted; began NBA journey through D-League", eventType: "CAREER" },
        { year: 2025, title: "Signed with Golden State Warriors — playing with brother Steph", eventType: "SIGNING" },
      ],
    },
    {
      slug: "mason-plumlee",
      firstName: "Mason",
      lastName: "Plumlee",
      birthYear: 1990,
      hometown: "Warsaw, IN",
      highSchool: "Christ School, Arden, NC",
      isFeatured: false,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/203486.png",
      bio: "The middle Plumlee brother who developed into a first-round pick over four years at Duke. A dominant rebounder and rim-runner.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "Charlotte Hornets",
        league: "NBA",
        location: "Charlotte, NC",
        statusNote:
          "Selected #22 overall by the Brooklyn Nets in 2013 after a senior year averaging 17.1 PPG and 10.1 RPG. Now in his 13th NBA season with the Charlotte Hornets on a 1-year, $3.6M deal. Has played for the Nets, Trail Blazers, Nuggets, Pistons, Hornets, and Clippers over a long career as a solid starting center.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mason_Plumlee",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 5,
        position: "Center / Power Forward",
        yearsAtSchool: "2009-2013",
        statsNote: "Sophomore • 2010 National Champion • Developing big man",
        gamesPlayed: 37,
        pointsPerGame: 7.5,
        reboundsPerGame: 8.0,
        assistsPerGame: 1.5,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2009-10", yearLabel: "2009-10 (Champion)", sortOrder: 201, gamesPlayed: 39, pointsPerGame: 3.8, reboundsPerGame: 3.7, assistsPerGame: 0.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2010-11", yearLabel: "2010-11", sortOrder: 202, gamesPlayed: 37, pointsPerGame: 7.5, reboundsPerGame: 8.0, assistsPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2011-12", yearLabel: "2011-12", sortOrder: 203, gamesPlayed: 34, pointsPerGame: 11.1, reboundsPerGame: 9.2, assistsPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2012-13", yearLabel: "2012-13 (Senior, 17.1/10.1)", sortOrder: 204, gamesPlayed: 36, pointsPerGame: 17.1, reboundsPerGame: 10.1, assistsPerGame: 1.8, fieldGoalPct: 0.609 },
        { level: "PROFESSIONAL", teamName: "Brooklyn Nets", season: "2013-14", yearLabel: "2013-14 (Rookie)", sortOrder: 301, gamesPlayed: 70, pointsPerGame: 7.4, reboundsPerGame: 4.4, assistsPerGame: 0.9 },
        { level: "PROFESSIONAL", teamName: "Portland Trail Blazers", season: "2015-16", yearLabel: "2015-16", sortOrder: 303, gamesPlayed: 82, pointsPerGame: 9.1, reboundsPerGame: 7.7, assistsPerGame: 2.8, fieldGoalPct: 0.519 },
        { level: "PROFESSIONAL", teamName: "Denver Nuggets", season: "2018-19", yearLabel: "2018-19", sortOrder: 306, gamesPlayed: 82, pointsPerGame: 7.8, reboundsPerGame: 5.4, assistsPerGame: 2.9 },
      ],
      careerEvents: [
        { year: 2010, title: "Won NCAA National Championship with Duke", eventType: "CHAMPIONSHIP" },
        { year: 2013, title: "Selected #22 overall by the Brooklyn Nets", eventType: "DRAFT" },
      ],
    },
    {
      slug: "miles-plumlee",
      firstName: "Miles",
      lastName: "Plumlee",
      birthYear: 1988,
      hometown: "Warsaw, IN",
      highSchool: "Christ School, Arden, NC",
      isFeatured: false,
      bio: "The eldest Plumlee brother as a junior. Would be selected #26 overall the following year.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NBA Player",
        statusNote: "Selected #26 overall by Indiana in 2012. Played 7 NBA seasons. Won NBL championship with Perth Wildcats in 2020. Signed a notable $50M deal with Milwaukee in 2016.",
        sourceUrl: "https://en.wikipedia.org/wiki/Miles_Plumlee",
      },
      membership: { role: "PLAYER", jerseyNumber: 21, position: "Forward / Center", yearsAtSchool: "2008-2012", statsNote: "Junior • 4.8 PPG, 4.6 RPG", gamesPlayed: 37, pointsPerGame: 4.8, reboundsPerGame: 4.6 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2010-11", yearLabel: "2010-11 (Junior)", sortOrder: 203, gamesPlayed: 37, pointsPerGame: 4.8, reboundsPerGame: 4.6, assistsPerGame: 0.4 },
      ],
      careerEvents: [
        { year: 2012, title: "Selected #26 overall by the Indiana Pacers", eventType: "DRAFT" },
        { year: 2020, title: "Won NBL Championship with Perth Wildcats", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "ryan-kelly",
      firstName: "Ryan",
      lastName: "Kelly",
      birthYear: 1991,
      hometown: "Raleigh, NC",
      highSchool: "Ravenscroft School, Raleigh, NC",
      isFeatured: false,
      bio: "A sophomore stretch forward. Now in his 7th season playing in Japan's B.League.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Fukui Blowinds",
        league: "B.League (Japan)",
        location: "Fukui, Japan",
        statusNote: "#48 pick by the Lakers in 2013. Now averaging 15.9 PPG in Japan's B.League in his 7th season overseas.",
        sourceUrl: "https://en.wikipedia.org/wiki/Ryan_Kelly_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 34, position: "Forward", yearsAtSchool: "2009-2013", statsNote: "Sophomore • 6.6 PPG, 3.7 RPG", gamesPlayed: 37, pointsPerGame: 6.6, reboundsPerGame: 3.7 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2010-11", yearLabel: "2010-11 (Sophomore)", sortOrder: 202, gamesPlayed: 37, pointsPerGame: 6.6, reboundsPerGame: 3.7, assistsPerGame: 0.5 },
      ],
      careerEvents: [
        { year: 2013, title: "Selected #48 overall by the LA Lakers", eventType: "DRAFT" },
      ],
    },
    {
      slug: "andre-dawkins",
      firstName: "Andre",
      lastName: "Dawkins",
      birthYear: 1991,
      hometown: "Chesapeake, VA",
      highSchool: "Atlantic Shores Christian School, Chesapeake, VA",
      isFeatured: false,
      bio: "A sophomore sharpshooter who shot 42.7% from three. Now a high school head coach in Virginia.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "Charlottesville High School",
        location: "Charlottesville, VA",
        statusNote: "After Duke, went undrafted. Brief NBA/G-League stints. Now head coach at Charlottesville HS and director of Pro Skills Basketball. Also coached at Mount St. Mary HS in OKC (38-13 record).",
        sourceUrl: "https://www.si.com/college/duke/basketball/duke-basketball-andre-dawkins-new-job",
      },
      membership: { role: "PLAYER", jerseyNumber: 20, position: "Shooting Guard", yearsAtSchool: "2009-2014", statsNote: "Sophomore • 8.1 PPG • 42.7% from three", gamesPlayed: 37, pointsPerGame: 8.1, reboundsPerGame: 1.9 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2010-11", yearLabel: "2010-11 (Sophomore)", sortOrder: 202, gamesPlayed: 37, pointsPerGame: 8.1, reboundsPerGame: 1.9, assistsPerGame: 0.6, threePointPct: 0.427 },
      ],
      careerEvents: [
        { year: 2024, title: "Named head coach at Charlottesville HS", eventType: "CAREER" },
      ],
    },
    {
      slug: "tyler-thornton",
      firstName: "Tyler",
      lastName: "Thornton",
      birthYear: 1992,
      hometown: "Washington, D.C.",
      highSchool: "Gonzaga College High School, Washington, D.C.",
      isFeatured: false,
      bio: "A freshman defensive specialist who would play all four years at Duke. Now an assistant coach on Scheyer's Duke staff.",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Coach",
        currentEmployer: "Duke University",
        league: "ACC",
        location: "Durham, NC",
        statusNote: "Four-year player at Duke. After graduating, coached at Marquette (grad assistant) and Howard University (6 seasons). Hired as Duke assistant coach under Scheyer in May 2025, returning home to Cameron Indoor.",
        sourceUrl: "https://goduke.com/staff-directory/tyler-thornton/1371",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Point Guard", yearsAtSchool: "2010-2014", statsNote: "Freshman • Defensive specialist • 2.0 PPG", gamesPlayed: 35, pointsPerGame: 2.0, reboundsPerGame: 0.9, assistsPerGame: 1.4 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2010-11", yearLabel: "2010-11 (Freshman)", sortOrder: 201, gamesPlayed: 35, pointsPerGame: 2.0, reboundsPerGame: 0.9, assistsPerGame: 1.4 },
      ],
      careerEvents: [
        { year: 2025, title: "Hired as Duke assistant coach under Scheyer", eventType: "CAREER" },
      ],
    },
    {
      slug: "josh-hairston",
      firstName: "Josh",
      lastName: "Hairston",
      birthYear: 1992,
      hometown: "Fredericksburg, VA",
      highSchool: "Montrose Christian School, Rockville, MD",
      isFeatured: false,
      bio: "A freshman forward who would become an NBA agent at Klutch Sports Group after his playing career.",
      status: {
        occupationType: "FRONT_OFFICE",
        currentTitle: "NBA Agent",
        currentEmployer: "Klutch Sports Group",
        location: "Los Angeles, CA",
        statusNote: "After four years at Duke, played professionally in Israel, Italy, Switzerland, and Sweden. Pivoted to sports agency — now an NBA agent at Klutch Sports Group (Rich Paul's agency), representing clients in the NBA Draft.",
        sourceUrl: "https://hoopshype.com/reps/josh-hairston/",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Forward", yearsAtSchool: "2010-2014", statsNote: "Freshman • 1.4 PPG", gamesPlayed: 27, pointsPerGame: 1.4, reboundsPerGame: 1.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2010-11", yearLabel: "2010-11 (Freshman)", sortOrder: 201, gamesPlayed: 27, pointsPerGame: 1.4, reboundsPerGame: 1.2 },
      ],
      careerEvents: [],
    },
    {
      slug: "mike-krzyzewski",
      firstName: "Mike",
      lastName: "Krzyzewski",
      birthYear: 1947,
      hometown: "Chicago, IL",
      highSchool: "Weber High School, Chicago, IL",
      isFeatured: true,
      bio: "The winningest coach in Division I men's basketball history. The 2010-11 season followed his fourth national championship.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Special Advisor / Duke Ambassador",
        currentEmployer: "NBA / Duke University",
        location: "Durham, NC",
        statusNote: "Retired after the 2021-22 season as the winningest coach in Division I men's basketball history with 1,202 victories across 47 seasons (5 at Army, 42 at Duke). Won five national championships (1991, 1992, 2001, 2010, 2015), reached 13 Final Fours, and won three Olympic gold medals as Team USA coach (2008, 2012, 2016). Now serves as Special Advisor to NBA Commissioner Adam Silver, Ambassador to Duke University, professor at Duke's Fuqua School of Business, and hosts 'Basketball and Beyond with Coach K' on SiriusXM.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Krzyzewski",
      },
      membership: {
        role: "HEAD_COACH",
        position: "Head Coach",
        yearsAtSchool: "1980-2022",
        statsNote: "32-5 • Sweet Sixteen • Defending national champion",
      },
      careerEvents: [
        { year: 2010, title: "Won fourth NCAA National Championship", eventType: "CHAMPIONSHIP" },
        { year: 2022, title: "Retired as winningest coach in D-I history (1,202 wins)", eventType: "RETIREMENT" },
      ],
    },
  ],
};
