import type { TeamSeed } from "./types";

export const dukeBasketball2005: TeamSeed = {
  slug: "duke-basketball-2005",
  name: "Duke Blue Devils",
  season: "2004-2005",
  sport: "Men's Basketball",
  school: "Duke University",
  conference: "ACC",
  accomplishment: "Sweet Sixteen (27-6)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  mascotName: "Blue Devil",
  people: [
    {
      slug: "jj-redick",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/3024.png",
      firstName: "J.J.",
      lastName: "Redick",
      birthYear: 1984,
      hometown: "Roanoke, VA",
      highSchool: "Cave Spring High School, Roanoke, VA",
      isFeatured: true,
      bio: "Duke's all-time leading scorer and now head coach of the LA Lakers.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Coach",
        currentEmployer: "Los Angeles Lakers",
        league: "NBA",
        location: "Los Angeles, CA",
        statusNote:
          "Selected #11 overall in 2006, Redick played 15 NBA seasons as an elite shooter. After retiring in 2021, he built a media empire before being hired as Lakers head coach in June 2024.",
        sourceUrl: "https://en.wikipedia.org/wiki/J._J._Redick",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 4,
        position: "Shooting Guard",
        yearsAtSchool: "2002-2006",
        statsNote: "Junior • ACC Player of the Year candidate • Elite scorer",
        gamesPlayed: 33,
        pointsPerGame: 21.8,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Cave Spring High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 35.0, reboundsPerGame: 3.0, assistsPerGame: 4.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2004-2005", yearLabel: "Junior", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 21.8 },
      ],
      careerEvents: [
        { year: 2006, title: "Selected #11 overall by the Orlando Magic", eventType: "DRAFT" },
        { year: 2024, title: "Named head coach of the Los Angeles Lakers", eventType: "CAREER" },
      ],
    },
    {
      slug: "shelden-williams",
      firstName: "Shelden",
      lastName: "Williams",
      birthYear: 1983,
      hometown: "Midwest City, OK",
      highSchool: "Midwest City High School, Midwest City, OK",
      isFeatured: false,
      bio: "A dominant shot-blocking center and Duke's all-time blocks leader.",
      status: {
        occupationType: "COACH",
        currentTitle: "Podcast Host / Foundation Director",
        location: "Atlanta, GA",
        statusNote:
          "Nicknamed 'The Landlord' at Duke, Williams holds the school's career records for blocks and rebounds. Selected #5 overall by the Atlanta Hawks in 2006, he played six NBA seasons with the Hawks, Kings, Celtics, Nuggets, and Nets. Inducted into the Duke Athletics Hall of Fame in 2018. After retiring, he founded the Shelden Williams Foundation in 2019 to empower student-athletes through education and community involvement, and hosts the 'Bleav in Duke' podcast covering Blue Devils basketball.",
        sourceUrl: "https://en.wikipedia.org/wiki/Shelden_Williams",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 23,
        position: "Center / Power Forward",
        yearsAtSchool: "2002-2006",
        statsNote: "Junior • NABC Defensive POY candidate • Double-double machine",
        gamesPlayed: 33,
        pointsPerGame: 14.5,
        reboundsPerGame: 9.7,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Midwest City High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 26.8, reboundsPerGame: 15.0, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2002-2003", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 8.2, reboundsPerGame: 5.9, assistsPerGame: 0.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2003-2004", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 37, pointsPerGame: 11.2, reboundsPerGame: 8.3, assistsPerGame: 0.6 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2004-2005", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 33, pointsPerGame: 14.5, reboundsPerGame: 9.7, assistsPerGame: 0.7 },
      ],
      careerEvents: [
        { year: 2006, title: "Selected #5 overall by the Atlanta Hawks", eventType: "DRAFT" },
      ],
    },
    {
      slug: "daniel-ewing",
      firstName: "Daniel",
      lastName: "Ewing",
      birthYear: 1983,
      hometown: "Houston, TX",
      highSchool: "Willowridge High School, Houston, TX",
      isFeatured: false,
      bio: "A four-year guard who developed into a key scorer and leader.",
      status: {
        occupationType: "FRONT_OFFICE",
        currentTitle: "Professional Scout",
        currentEmployer: "Los Angeles Lakers",
        league: "NBA",
        location: "Los Angeles, CA",
        statusNote:
          "Selected 32nd overall by the LA Clippers in 2005, Ewing played briefly in the NBA before spending nearly a decade playing professionally overseas in France, Spain, and Italy. In September 2022, he joined the Los Angeles Lakers as a professional scout in their scouting department under Jesse Buss, evaluating domestic and international talent for one of the NBA's marquee franchises.",
        sourceUrl: "https://en.wikipedia.org/wiki/Daniel_Ewing",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 5,
        position: "Shooting Guard",
        yearsAtSchool: "2001-2005",
        statsNote: "Senior captain • Team leader and go-to scorer",
        gamesPlayed: 33,
        pointsPerGame: 16.2,
        assistsPerGame: 3.8,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Willowridge High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 29.3, reboundsPerGame: 2.2, assistsPerGame: 6.9 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2001-2002", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 35, pointsPerGame: 6.5, reboundsPerGame: 2.2, assistsPerGame: 1.3 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2002-2003", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 33, pointsPerGame: 10.5, reboundsPerGame: 2.5, assistsPerGame: 2.8 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2003-2004", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 37, pointsPerGame: 13.5, reboundsPerGame: 3.0, assistsPerGame: 3.2 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2004-2005", yearLabel: "Senior (Captain)", sortOrder: 204, gamesPlayed: 33, pointsPerGame: 16.2, reboundsPerGame: 3.5, assistsPerGame: 3.8 },
      
        { level: "PROFESSIONAL", teamName: "Los Angeles Clippers", season: "2005-06", yearLabel: "2005-06 (Rookie)", sortOrder: 301, gamesPlayed: 57, minutesPerGame: 13.3, pointsPerGame: 4.5, reboundsPerGame: 1.2, assistsPerGame: 1.5, fieldGoalPct: 0.403, threePointPct: 0.303 }
      ],
      careerEvents: [
        { year: 2005, title: "Selected #32 overall by the LA Clippers", eventType: "DRAFT" },
      ],
    },
    {
      slug: "demarcus-nelson",
      firstName: "DeMarcus",
      lastName: "Nelson",
      birthYear: 1986,
      hometown: "Vallejo, CA",
      highSchool: "Jesse Bethel High School, Vallejo, CA",
      isFeatured: false,
      bio: "A versatile guard/forward who was a four-year contributor at Duke, earning ACC All-Defensive Team honors and becoming a fan favorite for his hustle.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Business Owner",
        currentEmployer: "Ice Ventures Unlimited LLC",
        location: "Las Vegas, NV",
        linkedInUrl: "https://www.linkedin.com/in/demarcus-nelson/",
        statusNote:
          "First undrafted rookie to start on NBA opening night (Golden State Warriors, 2008). Spent 12 years playing professionally in Europe, primarily in France — winning the LNB Pro A championship and French Cup with ASVEL Lyon-Villeurbanne in 2019 as Finals MVP. Retired in 2020 after parting ways with Limoges. Inducted into Vallejo Sports Hall of Fame (2024) and had his #21 retired by Vallejo High — the first in 150 years. Now based in Las Vegas running Ice Ventures Unlimited LLC.",
        sourceUrl: "https://en.wikipedia.org/wiki/DeMarcus_Nelson",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 1,
        position: "Shooting Guard / Small Forward",
        yearsAtSchool: "2004-2008",
        statsNote: "Freshman contributor • ACC All-Defensive Team (later years)",
      },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Jesse Bethel High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 14.3, reboundsPerGame: 8.9, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2004-2005", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 6.2, reboundsPerGame: 4.5, assistsPerGame: 0.8 },
      ],
      careerEvents: [
        { year: 2008, title: "Graduated from Duke; went undrafted", eventType: "CAREER" },
      ],
    },
    {
      slug: "shavlik-randolph",
      firstName: "Shavlik",
      lastName: "Randolph",
      birthYear: 1983,
      hometown: "Raleigh, NC",
      highSchool: "Broughton High School, Raleigh, NC",
      isFeatured: false,
      bio: "A McDonald's All-American power forward from Raleigh.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Owner / Investor",
        currentEmployer: "Big Prime Hauling",
        location: "Raleigh, NC",
        statusNote:
          "Randolph went undrafted but played in the NBA with the 76ers and Celtics. He now runs Big Prime Hauling, a trucking company in North Carolina.",
        sourceUrl: "https://en.wikipedia.org/wiki/Shavlik_Randolph",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 42,
        position: "Power Forward",
        yearsAtSchool: "2002-2006",
        statsNote: "Junior • Interior scorer and rebounder",
        gamesPlayed: 33,
        pointsPerGame: 8.2,
        reboundsPerGame: 5.1,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Broughton High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 17.3, reboundsPerGame: 9.6, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2004-2005", yearLabel: "Junior", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 8.2, reboundsPerGame: 5.1 },
      ],
      careerEvents: [
        { year: 2006, title: "Went undrafted; signed with 76ers", eventType: "SIGNING" },
      ],
    },
    {
      slug: "lee-melchionni",
      firstName: "Lee",
      lastName: "Melchionni",
      birthYear: 1983,
      hometown: "Germantown, PA",
      highSchool: "Germantown Academy, Fort Washington, PA",
      isFeatured: false,
      bio: "A sharpshooting guard and four-year contributor.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Settlement Planner / Attorney",
        currentEmployer: "Sage Settlement Consulting / Justice Partners",
        location: "Atlanta, GA",
        linkedInUrl: "https://www.linkedin.com/in/lee-m-melchionni-7b5820b4/",
        statusNote:
          "Played one season in Italy, spent 7 years as an NBA agent at Wasserman (while earning his J.D. from Loyola Law School at night), then pivoted to settlement law.",
        sourceUrl: "https://www.sagesettlements.com/our-team/lee-melchionni/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 20,
        position: "Shooting Guard",
        yearsAtSchool: "2002-2006",
        statsNote: "Junior • Reliable perimeter shooter",
      },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Germantown Academy", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 6.5, reboundsPerGame: 0.7, assistsPerGame: 2.4 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2002-2003", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 21, pointsPerGame: 1.0, reboundsPerGame: 0.7, assistsPerGame: 0.3 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2003-2004", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 37, pointsPerGame: 6.5, reboundsPerGame: 2.2, assistsPerGame: 1.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2004-2005", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 33, pointsPerGame: 7.7, reboundsPerGame: 3.4, assistsPerGame: 0.8 },
      ],
      careerEvents: [
        { year: 2006, title: "Graduated from Duke", eventType: "CAREER" },
      ],
    },
    {
      slug: "sean-dockery",
      firstName: "Sean",
      lastName: "Dockery",
      birthYear: 1985,
      hometown: "Milwaukee, WI",
      highSchool: "Vincent High School, Milwaukee, WI",
      isFeatured: false,
      bio: "A quick, athletic point guard remembered for his buzzer-beating half-court shot against Virginia Tech.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Owner / Basketball Trainer",
        currentEmployer: "Dockery Basketball Academy",
        location: "San Antonio, TX",
        statusNote:
          "After Duke, Dockery played overseas then coached with the Spurs and Grizzlies. He now runs Dockery Basketball Academy in San Antonio.",
        sourceUrl: "http://www.dockerybasketball.com/about-us/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 3,
        position: "Point Guard",
        yearsAtSchool: "2003-2007",
        statsNote: "Sophomore • Hit legendary buzzer-beater vs Virginia Tech",
      },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Vincent High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 9.9, reboundsPerGame: 1.4, assistsPerGame: 3.3 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2002-2003", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 3.3, reboundsPerGame: 1.4, assistsPerGame: 1.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2003-2004", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 37, pointsPerGame: 3.0, reboundsPerGame: 1.4, assistsPerGame: 1.3 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2004-2005", yearLabel: "Junior (buzzer-beater vs VT)", sortOrder: 203, gamesPlayed: 27, pointsPerGame: 6.2, reboundsPerGame: 2.8, assistsPerGame: 2.3 },
      ],
      careerEvents: [
        { year: 2005, title: "Hit half-court buzzer-beater to beat Virginia Tech", eventType: "OTHER" },
      ],
    },
    {
      slug: "reggie-love",
      firstName: "Reggie",
      lastName: "Love",
      birthYear: 1982,
      hometown: "Charlotte, NC",
      highSchool: "Providence Day School, Charlotte, NC",
      isFeatured: false,
      bio: "A senior two-sport athlete completing his Duke career before going on to serve as personal aide to President Obama.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Partner and Vice President",
        currentEmployer: "Transatlantic Holdings",
        location: "Washington, D.C.",
        statusNote: "After graduating from Duke in 2005 (where he was a two-sport athlete in basketball and football, and member of the 2001 championship team), Love joined Barack Obama's presidential campaign in 2007 and served as the President's personal aide ('body man') from 2009 to 2011. He earned his MBA from Wharton in 2013, published the NYT bestseller 'Power Forward: My Presidential Education,' and built a career in finance and consulting. Previously Partner at RON Transatlantic EG (2012-2019), he is now Senior Advisor at Apollo Global Management.",
        sourceUrl: "https://en.wikipedia.org/wiki/Reggie_Love",
      },
      membership: { role: "PLAYER", jerseyNumber: 42, position: "Forward", yearsAtSchool: "2000-2005", statsNote: "Senior • Two-sport athlete" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Providence Day School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 7.7, reboundsPerGame: 4.3, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2004-2005", yearLabel: "Senior", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 1.8, reboundsPerGame: 1.0, assistsPerGame: 0.4 },
      ],
      careerEvents: [{ year: 2009, title: "Named personal aide to President Obama", eventType: "CAREER" }],
    },
    {
      slug: "david-mcclure",
      firstName: "David",
      lastName: "McClure",
      birthYear: 1986,
      hometown: "Ridgefield, CT",
      highSchool: "Ridgefield High School, Ridgefield, CT",
      isFeatured: false,
      bio: "A walk-on who earned a scholarship and played five seasons at Duke (2004-09), known for his hustle and toughness.",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Coach",
        currentEmployer: "Memphis Grizzlies",
        league: "NBA",
        location: "Memphis, TN",
        statusNote:
          "After Duke, McClure played in the D-League and Lithuania before six knee surgeries ended his playing career. Got into coaching through Chip Engelland (Duke alum on the Spurs staff). Career path: Spurs player development (2014-16), Indiana Pacers assistant (2016-19), Memphis Grizzlies assistant (2019-present). Known for making the buzzer-beating game-winner vs #17 Clemson in 2007. Board member of the NBA Coaches Association.",
        sourceUrl: "https://nbacoaches.com/david-mcclure/",
      },
      membership: { role: "PLAYER", jerseyNumber: 14, position: "Small Forward", yearsAtSchool: "2004-2009", statsNote: "Freshman walk-on • Earned scholarship" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Ridgefield High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 7.5, reboundsPerGame: 4.3, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2004-2005", yearLabel: "Freshman walk-on", sortOrder: 201, gamesPlayed: 25, pointsPerGame: 1.7, reboundsPerGame: 1.0, assistsPerGame: 0.5 },
      ],
      careerEvents: [
        { year: 2009, title: "Graduated from Duke", eventType: "CAREER" },
        { year: 2014, title: "Joined San Antonio Spurs player development staff", eventType: "CAREER" },
      ],
    },
    {
      slug: "joe-pagliuca",
      firstName: "Joe",
      lastName: "Pagliuca",
      birthYear: 1982,
      hometown: "Weston, MA",
      highSchool: "Buckingham Browne & Nichols, Cambridge, MA",
      isFeatured: false,
      bio: "Walk-on guard and son of Celtics co-owner Stephen Pagliuca. Won the Hart Award as Duke basketball's top scholar-athlete.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Co-Founder & President",
        location: "Boston, MA",
        statusNote: "Pursued career in biotech/venture capital after Duke. Son of Bain Capital co-chairman and Celtics co-owner Stephen Pagliuca.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/joe-pagliuca/4286",
      },
      membership: { role: "PLAYER", jerseyNumber: 43, position: "Guard", yearsAtSchool: "2000-2004", statsNote: "Fifth-year walk-on • Hart Award winner" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Buckingham Browne & Nichols", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 5.0, reboundsPerGame: 0.0, assistsPerGame: 2.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2004-2005", yearLabel: "Walk-on", sortOrder: 201, gamesPlayed: 6, pointsPerGame: 0.0, reboundsPerGame: 0.0, assistsPerGame: 0.0 },
      ],
      careerEvents: [{ year: 2004, title: "Won Dr. Deryl Hart Award as top scholar-athlete", eventType: "AWARD" }],
    },
    {
      slug: "patrick-johnson-duke",
      firstName: "Patrick",
      lastName: "Johnson",
      birthYear: 1984,
      hometown: "Glendora, CA",
      highSchool: "Glendora High School, Glendora, CA",
      isFeatured: false,
      bio: "A walk-on who earned a scholarship entering the 2004-05 season after overcoming knee surgery that prevented him from playing high school basketball. A remarkable underdog story.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "Citrus College",
        location: "Glendora, CA",
        statusNote:
          "After earning a B.A. in Political Science from Duke in 2006, Johnson built a coaching career including assistant roles at Citrus College and head coach at Concordia University Irvine (69-31 record, two NAIA tournament appearances). He was named head men's basketball coach at Citrus College in July 2015.",
        sourceUrl: "https://www.citrusowls.com/sports/mbkb/coaches/PatrickJohnson",
      },
      membership: { role: "PLAYER", jerseyNumber: 24, position: "Forward / Center", yearsAtSchool: "2002-2006", statsNote: "Walk-on turned scholarship player • 22 games in 2004-05" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Glendora High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 5.6, reboundsPerGame: 4.4, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2004-2005", yearLabel: "Junior walk-on", sortOrder: 201, gamesPlayed: 22, pointsPerGame: 0.4, reboundsPerGame: 1.1, assistsPerGame: 0.1 },
      ],
      careerEvents: [
        { year: 2006, title: "Graduated from Duke with B.A. in Political Science", eventType: "CAREER" },
        { year: 2015, title: "Named head men's basketball coach at Citrus College", eventType: "CAREER" },
      ],
    },
    {
      slug: "mike-krzyzewski",
      firstName: "Mike",
      lastName: "Krzyzewski",
      birthYear: 1947,
      hometown: "Chicago, IL",
      highSchool: "Weber High School, Chicago, IL",
      isFeatured: true,
      bio: "The winningest coach in Division I men's basketball history.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Special Advisor / Duke Ambassador",
        currentEmployer: "NBA / Duke University",
        location: "Durham, NC",
        statusNote:
          "Retired after the 2021-22 season as the winningest coach in Division I men's basketball history with 1,202 victories across 47 seasons (5 at Army, 42 at Duke). Won five national championships (1991, 1992, 2001, 2010, 2015), reached 13 Final Fours, and won three Olympic gold medals as Team USA coach (2008, 2012, 2016). Now serves as Special Advisor to NBA Commissioner Adam Silver, Ambassador to Duke University, professor at Duke's Fuqua School of Business, and hosts 'Basketball and Beyond with Coach K' on SiriusXM.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Krzyzewski",
      },
      membership: {
        role: "HEAD_COACH",
        position: "Head Coach",
        yearsAtSchool: "1980-2022",
        statsNote: "27-6 record in 2004-05 • Sweet Sixteen",
      },
      careerEvents: [
        { year: 2022, title: "Retired as winningest coach in D-I history", eventType: "RETIREMENT" },
      ],
    },
  ],
};
