import type { TeamSeed } from "./types";

export const dukeBasketball2007: TeamSeed = {
  slug: "duke-basketball-2007",
  name: "Duke Blue Devils",
  season: "2006-2007",
  sport: "Men's Basketball",
  school: "Duke University",
  conference: "ACC",
  accomplishment: "NCAA Tournament 1st Round (22-11)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  mascotName: "Blue Devil",
  people: [
    {
      slug: "josh-mcroberts",
      firstName: "Josh",
      lastName: "McRoberts",
      birthYear: 1987,
      hometown: "Carmel, IN",
      highSchool: "Carmel High School, Carmel, IN",
      isFeatured: true,
      bio: "A McDonald's All-American sophomore forward who led the team in rebounding (7.8 RPG) and was an ACC standout. Declared for the NBA Draft after the season and was selected #37 overall by Portland.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "Indianapolis, IN",
        statusNote:
          "Selected #37 overall by Portland in the 2007 NBA Draft. Played 10 NBA seasons with the Trail Blazers, Pacers, Kings, Hornets, Magic, Lakers, Heat, and Mavericks, building a reputation as a versatile passing big man. Career averages: 4.6 PPG, 3.9 RPG, 1.9 APG over 525 games. Retired in 2018.",
        sourceUrl: "https://en.wikipedia.org/wiki/Josh_McRoberts",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 2,
        position: "Power Forward",
        yearsAtSchool: "2005-2007",
        statsNote: "Sophomore • 12.7 PPG, 7.8 RPG, 3.0 APG • Team rebounding leader",
        gamesPlayed: 33,
        pointsPerGame: 12.7,
        reboundsPerGame: 7.8,
        assistsPerGame: 3.0,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Carmel High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 22.0, reboundsPerGame: 11.0, blocksPerGame: 3.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2005-06", yearLabel: "2005-06 (Freshman)", sortOrder: 201, gamesPlayed: 35, pointsPerGame: 8.7, reboundsPerGame: 5.3, assistsPerGame: 1.7 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2006-07", yearLabel: "2006-07 (Sophomore)", sortOrder: 202, gamesPlayed: 33, pointsPerGame: 12.7, reboundsPerGame: 7.8, assistsPerGame: 3.0, fieldGoalPct: 0.585 },
        { level: "PROFESSIONAL", teamName: "Indiana Pacers", season: "2010-11", yearLabel: "2010-11", sortOrder: 304, gamesPlayed: 78, pointsPerGame: 7.4, reboundsPerGame: 5.3, assistsPerGame: 1.6 },
        { level: "PROFESSIONAL", teamName: "Charlotte Hornets", season: "2013-14", yearLabel: "2013-14 (Career best)", sortOrder: 307, gamesPlayed: 78, pointsPerGame: 8.5, reboundsPerGame: 4.8, assistsPerGame: 4.3 },
      ],
      careerEvents: [
        { year: 2007, title: "Selected #37 overall by Portland Trail Blazers", eventType: "DRAFT" },
        { year: 2014, title: "Signed four-year, $23M contract with Miami Heat", eventType: "SIGNING" },
        { year: 2018, title: "Retired from professional basketball", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "demarcus-nelson",
      firstName: "DeMarcus",
      lastName: "Nelson",
      birthYear: 1986,
      hometown: "Vallejo, CA",
      highSchool: "Sheldon High School, Elk Grove, CA",
      isFeatured: false,
      bio: "A junior guard and team leader who averaged 13.7 PPG. The California product brought toughness and scoring to the Duke backcourt before becoming a senior captain the following year.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "Vallejo, CA",
        statusNote:
          "Went undrafted in 2008 but signed with the Golden State Warriors and made his hometown NBA debut. Played 16 games for Golden State before being waived. Spent the rest of his career overseas, playing in Italy, Greece, France, Russia, and the NBA D-League over more than a decade. Retired around 2018.",
        sourceUrl: "https://en.wikipedia.org/wiki/DeMarcus_Nelson",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 21,
        position: "Shooting Guard",
        yearsAtSchool: "2004-2008",
        statsNote: "Junior • 13.7 PPG, 5.7 RPG • Backcourt leader",
        gamesPlayed: 33,
        pointsPerGame: 13.7,
        reboundsPerGame: 5.7,
        assistsPerGame: 2.5,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Sheldon High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 33.7, reboundsPerGame: 11.0, assistsPerGame: 5.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2006-07", yearLabel: "2006-07 (Junior)", sortOrder: 203, gamesPlayed: 33, pointsPerGame: 13.7, reboundsPerGame: 5.7, assistsPerGame: 2.5 },
        { level: "PROFESSIONAL", teamName: "Golden State Warriors", season: "2008-09", yearLabel: "2008-09 (Rookie)", sortOrder: 301, gamesPlayed: 16, pointsPerGame: 5.4, reboundsPerGame: 1.7, assistsPerGame: 1.5 },
      ],
      careerEvents: [
        { year: 2008, title: "Signed with Golden State Warriors as undrafted free agent", eventType: "SIGNING" },
        { year: 2009, title: "Began international career in Italy", eventType: "CAREER" },
      ],
    },
    {
      slug: "greg-paulus",
      firstName: "Greg",
      lastName: "Paulus",
      birthYear: 1986,
      hometown: "Syracuse, NY",
      highSchool: "Christian Brothers Academy, Syracuse, NY",
      isFeatured: true,
      bio: "Sophomore point guard who started 31 games for Duke and was a Gatorade National Football Player of the Year coming out of high school. Famous for later returning to football as Syracuse's starting QB after graduating from Duke.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "Niagara University",
        league: "MAAC",
        location: "Niagara, NY",
        statusNote:
          "After his Duke basketball career ended in 2009, Paulus famously used his final year of eligibility to play quarterback at Syracuse. He then transitioned into coaching, serving as an assistant at Ohio State and Louisville. Hired as head men's basketball coach at Niagara University in 2022 and continues to lead the Purple Eagles program.",
        sourceUrl: "https://en.wikipedia.org/wiki/Greg_Paulus",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 3,
        position: "Point Guard",
        yearsAtSchool: "2005-2009",
        statsNote: "Sophomore starter • 11.5 PPG, 4.6 APG",
        gamesPlayed: 33,
        pointsPerGame: 11.5,
        reboundsPerGame: 2.5,
        assistsPerGame: 4.6,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Christian Brothers Academy", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 28.0, reboundsPerGame: 5.0, assistsPerGame: 9.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2005-06", yearLabel: "2005-06 (Freshman)", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 6.7, reboundsPerGame: 2.4, assistsPerGame: 4.2 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2006-07", yearLabel: "2006-07 (Sophomore)", sortOrder: 202, gamesPlayed: 33, pointsPerGame: 11.5, reboundsPerGame: 2.5, assistsPerGame: 4.6, threePointPct: 0.388 },
      ],
      careerEvents: [
        { year: 2009, title: "Became starting QB at Syracuse for one season", eventType: "CAREER" },
        { year: 2022, title: "Named head men's basketball coach at Niagara University", eventType: "CAREER" },
      ],
    },
    {
      slug: "jon-scheyer",
      firstName: "Jon",
      lastName: "Scheyer",
      birthYear: 1987,
      hometown: "Northbrook, IL",
      highSchool: "Glenbrook North High School, Northbrook, IL",
      isFeatured: true,
      bio: "Highly recruited freshman guard who averaged 12.2 PPG in his first season at Duke. Scheyer would go on to win a national championship as a senior in 2010 and is now Duke's head coach.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "Duke University",
        league: "ACC",
        location: "Durham, NC",
        statusNote:
          "After winning the 2010 NCAA championship as a senior captain at Duke, a brief professional career was cut short by an eye injury. He joined Duke's coaching staff in 2013 and was named the school's 20th head coach in 2021, succeeding Mike Krzyzewski. His 124 wins through his first four seasons are the most by any D-I head coach in history.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jon_Scheyer",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 30,
        position: "Shooting Guard",
        yearsAtSchool: "2006-2010",
        statsNote: "Freshman • 12.2 PPG, 1.7 APG • ACC All-Freshman Team",
        gamesPlayed: 33,
        pointsPerGame: 12.2,
        reboundsPerGame: 3.3,
        assistsPerGame: 1.7,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Glenbrook North High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 32.3, reboundsPerGame: 4.1, assistsPerGame: 8.4 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2006-07", yearLabel: "2006-07 (Freshman)", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 12.2, reboundsPerGame: 3.3, assistsPerGame: 1.7 },
      ],
      careerEvents: [
        { year: 2010, title: "Won NCAA National Championship with Duke", eventType: "CHAMPIONSHIP" },
        { year: 2021, title: "Named Duke's 20th head coach, succeeding Coach K", eventType: "CAREER" },
      ],
    },
    {
      slug: "gerald-henderson",
      firstName: "Gerald",
      lastName: "Henderson",
      birthYear: 1987,
      hometown: "Merion Station, PA",
      highSchool: "Episcopal Academy, Merion, PA",
      isFeatured: true,
      bio: "McDonald's All-American freshman guard known for his explosive athleticism. Son of NBA champion Gerald Henderson Sr. Would be drafted #12 overall by Charlotte two years later.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "Charlotte, NC",
        statusNote:
          "Selected #12 overall by the Charlotte Bobcats in the 2009 NBA Draft. Played 9 NBA seasons with the Bobcats/Hornets, Trail Blazers, and 76ers. Career averages: 11.0 PPG, 2.9 RPG, 1.9 APG over 530 games. Retired in 2018 and has been involved in basketball training and youth development around Charlotte.",
        sourceUrl: "https://en.wikipedia.org/wiki/Gerald_Henderson_Jr.",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 15,
        position: "Shooting Guard",
        yearsAtSchool: "2006-2009",
        statsNote: "Freshman • 7.4 PPG, 2.7 RPG",
        gamesPlayed: 33,
        pointsPerGame: 7.4,
        reboundsPerGame: 2.7,
        assistsPerGame: 0.5,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Episcopal Academy", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 22.0, reboundsPerGame: 7.0, assistsPerGame: 3.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2006-07", yearLabel: "2006-07 (Freshman)", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 7.4, reboundsPerGame: 2.7, assistsPerGame: 0.5 },
        { level: "PROFESSIONAL", teamName: "Charlotte Bobcats", season: "2012-13", yearLabel: "2012-13", sortOrder: 304, gamesPlayed: 68, pointsPerGame: 15.5, reboundsPerGame: 3.7, assistsPerGame: 2.6 },
      ],
      careerEvents: [
        { year: 2009, title: "Selected #12 overall by Charlotte Bobcats", eventType: "DRAFT" },
        { year: 2018, title: "Retired from professional basketball", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "lance-thomas",
      firstName: "Lance",
      lastName: "Thomas",
      birthYear: 1988,
      hometown: "Scotch Plains, NJ",
      highSchool: "St. Benedict's Prep, Newark, NJ",
      isFeatured: false,
      bio: "Freshman power forward and defensive specialist who would later be part of Duke's 2010 national championship team. Carved out an 8-year NBA career as a tough defender.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Basketball Operations",
        location: "New York, NY",
        statusNote:
          "After winning the 2010 NCAA title at Duke, Thomas went undrafted but built an 8-year NBA career with New Orleans, OKC, and most notably the New York Knicks, where he was named co-captain in 2017-18. Averaged 5.1 PPG in 399 NBA games. Has since transitioned into a basketball operations and finance role in the New York area.",
        sourceUrl: "https://en.wikipedia.org/wiki/Lance_Thomas",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 42,
        position: "Power Forward",
        yearsAtSchool: "2006-2010",
        statsNote: "Freshman • 4.4 PPG, 4.0 RPG",
        gamesPlayed: 33,
        pointsPerGame: 4.4,
        reboundsPerGame: 4.0,
        assistsPerGame: 0.4,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "St. Benedict's Prep", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 12.2, reboundsPerGame: 9.4, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2006-07", yearLabel: "2006-07 (Freshman)", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 4.4, reboundsPerGame: 4.0, assistsPerGame: 0.4 },
      ],
      careerEvents: [
        { year: 2010, title: "Won NCAA National Championship with Duke", eventType: "CHAMPIONSHIP" },
        { year: 2017, title: "Named co-captain of the New York Knicks", eventType: "CAREER" },
      ],
    },
    {
      slug: "brian-zoubek",
      firstName: "Brian",
      lastName: "Zoubek",
      birthYear: 1988,
      hometown: "Haddonfield, NJ",
      highSchool: "Haddonfield Memorial High School, Haddonfield, NJ",
      isFeatured: false,
      bio: "A 7'1\" freshman center who saw limited minutes in his first season. Would later grab the most famous rebound in Duke history — the final rebound of the 2010 national championship game.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Founder",
        currentEmployer: "Zoubek Properties",
        location: "Haddonfield, NJ",
        statusNote:
          "Famously grabbed the final rebound of the 2010 NCAA title game, sealing Duke's 61-59 win over Butler. Went undrafted, briefly with the Nets. Opened Dream Puffz cream puff bakery in 2012, then pivoted to real estate. Now runs Zoubek Properties in the Haddonfield, NJ area.",
        sourceUrl: "https://en.wikipedia.org/wiki/Brian_Zoubek",
        linkedInUrl: "https://www.linkedin.com/in/brianzoubek/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 55,
        position: "Center",
        yearsAtSchool: "2006-2010",
        statsNote: "Freshman • 1.6 PPG, 2.0 RPG",
        gamesPlayed: 18,
        pointsPerGame: 1.6,
        reboundsPerGame: 2.0,
        assistsPerGame: 0.1,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Haddonfield Memorial High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 11.1, reboundsPerGame: 13.0, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2006-07", yearLabel: "2006-07 (Freshman)", sortOrder: 201, gamesPlayed: 18, pointsPerGame: 1.6, reboundsPerGame: 2.0, assistsPerGame: 0.1 },
      ],
      careerEvents: [
        { year: 2010, title: "Won NCAA Championship (grabbed final rebound, sealing 61-59 win over Butler)", eventType: "CHAMPIONSHIP" },
        { year: 2013, title: "Founded Zoubek Properties (real estate)", eventType: "CAREER" },
      ],
    },
    {
      slug: "dave-mcclure",
      firstName: "Dave",
      lastName: "McClure",
      birthYear: 1986,
      hometown: "Carmel, NY",
      highSchool: "Carmel High School, Carmel, NY",
      isFeatured: false,
      bio: "Sophomore forward who provided depth, defense, and hustle plays off the bench. Now an NBA assistant coach with the Memphis Grizzlies.",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Coach",
        currentEmployer: "Memphis Grizzlies",
        league: "NBA",
        location: "Memphis, TN",
        statusNote:
          "After his Duke playing career ended in 2009, McClure transitioned into coaching. He worked his way up through the college and NBA ranks and has served as an assistant coach with the Memphis Grizzlies, contributing to their player development and bench operations.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 14,
        position: "Forward",
        yearsAtSchool: "2005-2009",
        statsNote: "Sophomore • 2.7 PPG, 2.6 RPG",
        gamesPlayed: 33,
        pointsPerGame: 2.7,
        reboundsPerGame: 2.6,
        assistsPerGame: 0.7,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Carmel High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 18.0, reboundsPerGame: 8.0, assistsPerGame: 3.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2006-07", yearLabel: "2006-07 (Sophomore)", sortOrder: 202, gamesPlayed: 33, pointsPerGame: 2.7, reboundsPerGame: 2.6, assistsPerGame: 0.7 },
      ],
      careerEvents: [
        { year: 2010, title: "Began coaching career after graduation from Duke", eventType: "CAREER" },
      ],
    },
    {
      slug: "martynas-pocius",
      firstName: "Martynas",
      lastName: "Pocius",
      birthYear: 1986,
      hometown: "Vilnius, Lithuania",
      highSchool: "Notre Dame Prep, Fitchburg, MA",
      isFeatured: false,
      bio: "A Lithuanian sophomore guard known for his athleticism. Returned to Europe after his Duke career and built a long professional career, including time with EuroLeague powerhouse Real Madrid.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "Vilnius, Lithuania",
        statusNote:
          "After graduating from Duke in 2009, Pocius returned home and became a fixture in Lithuanian and European basketball. He won the 2014-15 EuroLeague championship with Real Madrid and represented the Lithuanian national team. He has since retired from playing and remains involved in Lithuanian basketball.",
        sourceUrl: "https://en.wikipedia.org/wiki/Martynas_Pocius",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 11,
        position: "Guard",
        yearsAtSchool: "2005-2009",
        statsNote: "Sophomore • Limited minutes due to injury",
        gamesPlayed: 16,
        pointsPerGame: 1.5,
        reboundsPerGame: 0.6,
        assistsPerGame: 0.3,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2006-07", yearLabel: "2006-07 (Sophomore)", sortOrder: 202, gamesPlayed: 16, pointsPerGame: 1.5, reboundsPerGame: 0.6, assistsPerGame: 0.3 },
        { level: "PROFESSIONAL", teamName: "Real Madrid", season: "2014-15", yearLabel: "2014-15 (EuroLeague Champion)", sortOrder: 305, pointsPerGame: 5.5 },
      ],
      careerEvents: [
        { year: 2009, title: "Returned to Europe to play professionally", eventType: "CAREER" },
        { year: 2015, title: "Won EuroLeague championship with Real Madrid", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "jamal-boykin",
      firstName: "Jamal",
      lastName: "Boykin",
      birthYear: 1988,
      hometown: "Los Angeles, CA",
      highSchool: "Fairfax High School, Los Angeles, CA",
      isFeatured: false,
      bio: "A freshman forward who played sparingly at Duke before transferring to Cal after the season. Became a captain at Cal and went on to a long pro career overseas.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "Los Angeles, CA",
        statusNote:
          "Transferred from Duke to Cal after his freshman year, where he became a captain and All-Pac-10 honorable mention selection. After college, he played professionally overseas in Israel, Lebanon, and other leagues. He has since retired and become involved in youth basketball training and mentorship in the Los Angeles area.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jamal_Boykin",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 4,
        position: "Forward",
        yearsAtSchool: "2006-2007",
        statsNote: "Freshman • Limited minutes • Transferred to Cal",
        gamesPlayed: 22,
        pointsPerGame: 1.4,
        reboundsPerGame: 1.3,
        assistsPerGame: 0.2,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Fairfax High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 20.0, reboundsPerGame: 9.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2006-07", yearLabel: "2006-07 (Freshman)", sortOrder: 201, gamesPlayed: 22, pointsPerGame: 1.4, reboundsPerGame: 1.3 },
        { level: "COLLEGE", teamName: "California Golden Bears", season: "2009-10", yearLabel: "2009-10 (Senior at Cal)", sortOrder: 204, gamesPlayed: 33, pointsPerGame: 12.4, reboundsPerGame: 7.6 },
      ],
      careerEvents: [
        { year: 2007, title: "Transferred from Duke to California", eventType: "CAREER" },
        { year: 2010, title: "Began professional career overseas", eventType: "CAREER" },
      ],
    },
    {
      slug: "eric-boateng",
      firstName: "Eric",
      lastName: "Boateng",
      birthYear: 1987,
      hometown: "London, England",
      highSchool: "St. Andrew's School, Middletown, DE",
      isFeatured: false,
      bio: "London-born freshman center who saw limited minutes at Duke before transferring to Arizona State. Played professionally for over a decade in Europe and represented England internationally.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "London, England",
        statusNote:
          "After transferring from Duke to Arizona State in 2007, Boateng started for the Sun Devils. He went on to a long professional career playing in the UK, Germany, France, and other European leagues, and represented Great Britain at the 2012 London Olympics. He has since retired and remained involved in basketball development in the UK.",
        sourceUrl: "https://en.wikipedia.org/wiki/Eric_Boateng",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 44,
        position: "Center",
        yearsAtSchool: "2006-2007",
        statsNote: "Freshman • Limited minutes • Transferred to Arizona State",
        gamesPlayed: 21,
        pointsPerGame: 1.0,
        reboundsPerGame: 1.1,
        assistsPerGame: 0.0,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "St. Andrew's School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 16.0, reboundsPerGame: 10.0, blocksPerGame: 3.0 },
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2006-07", yearLabel: "2006-07 (Freshman)", sortOrder: 201, gamesPlayed: 21, pointsPerGame: 1.0, reboundsPerGame: 1.1 },
      ],
      careerEvents: [
        { year: 2007, title: "Transferred from Duke to Arizona State", eventType: "CAREER" },
        { year: 2012, title: "Represented Great Britain at London Olympics", eventType: "AWARD" },
      ],
    },
    {
      slug: "jordan-davidson",
      firstName: "Jordan",
      lastName: "Davidson",
      birthYear: 1987,
      hometown: "Atlanta, GA",
      highSchool: "Westminster Schools, Atlanta, GA",
      isFeatured: false,
      bio: "Walk-on guard who provided depth and practice value to the team during his Duke career.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Citizen",
        location: "United States",
        statusNote: "Walk-on guard who graduated from Duke. Like many Duke walk-ons, transitioned to a professional career after graduation. Limited public information available.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 12,
        position: "Guard",
        yearsAtSchool: "2005-2009",
        statsNote: "Walk-on guard",
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2006-07", yearLabel: "2006-07 (Walk-on)", sortOrder: 202, gamesPlayed: 5, pointsPerGame: 0.4 },
      ],
      careerEvents: [],
    },
    {
      slug: "brian-greene-duke",
      firstName: "Brian",
      lastName: "Greene",
      birthYear: 1988,
      hometown: "Cary, NC",
      highSchool: "Cardinal Gibbons High School, Raleigh, NC",
      isFeatured: false,
      bio: "Local North Carolina walk-on guard who joined Duke's roster as a freshman in 2006.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Finance Professional",
        location: "Raleigh, NC",
        statusNote: "Walk-on guard who graduated from Duke in 2010 and returned to the Raleigh-Durham area to work in financial services.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster/brian-greene/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 14,
        position: "Guard",
        yearsAtSchool: "2006-2010",
        statsNote: "Freshman walk-on",
        gamesPlayed: 3,
        pointsPerGame: 0.0,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2006-07", yearLabel: "Freshman (walk-on)", sortOrder: 203, gamesPlayed: 3, pointsPerGame: 0.0 },
      ],
      careerEvents: [],
    },
    {
      slug: "steve-johnson-duke",
      firstName: "Steve",
      lastName: "Johnson",
      birthYear: 1988,
      hometown: "Wilmington, NC",
      highSchool: "New Hanover High School, Wilmington, NC",
      isFeatured: false,
      bio: "Walk-on guard from coastal North Carolina who joined Duke's practice squad during the 2006-07 season.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Citizen",
        location: "Wilmington, NC",
        statusNote: "Walk-on guard at Duke who returned to the Wilmington area after graduation. Limited public information available.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 33,
        position: "Guard",
        yearsAtSchool: "2006-2009",
        statsNote: "Walk-on guard",
        gamesPlayed: 2,
        pointsPerGame: 0.0,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2006-07", yearLabel: "Freshman (walk-on)", sortOrder: 204, gamesPlayed: 2, pointsPerGame: 0.0 },
      ],
      careerEvents: [],
    },
    {
      slug: "chris-giuliano-duke",
      firstName: "Chris",
      lastName: "Giuliano",
      birthYear: 1987,
      hometown: "Greenwich, CT",
      highSchool: "Greenwich High School, Greenwich, CT",
      isFeatured: false,
      bio: "Walk-on forward who contributed to Duke's practice squad during the 2006-07 season.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Business Professional",
        location: "New York, NY",
        statusNote: "Walk-on forward who graduated from Duke and transitioned to a career in business. Limited public information available.",
        sourceUrl: "https://goduke.com/sports/mens-basketball/roster",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 40,
        position: "Forward",
        yearsAtSchool: "2006-2010",
        statsNote: "Walk-on forward",
        gamesPlayed: 3,
        pointsPerGame: 0.0,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Duke Blue Devils", season: "2006-07", yearLabel: "Freshman (walk-on)", sortOrder: 205, gamesPlayed: 3, pointsPerGame: 0.0 },
      ],
      careerEvents: [],
    },
    {
      slug: "steve-wojciechowski",
      firstName: "Steve",
      lastName: "Wojciechowski",
      birthYear: 1976,
      hometown: "Baltimore, MD",
      highSchool: "Cardinal Gibbons High School, Baltimore, MD",
      bio: "Associate Head Coach under Coach K. Former Duke PG (1994-98) and one of the most intense competitors in program history.",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Coach",
        currentEmployer: "Utah Jazz",
        league: "NBA",
        location: "Salt Lake City, UT",
        statusNote: "After 15 years on Duke's staff (1999-2014), Wojciechowski became head coach at Marquette (2014-2021, 124-93). He then coached the Salt Lake City Stars G League team (41-17) before joining the Utah Jazz NBA coaching staff in June 2025.",
        sourceUrl: "https://en.wikipedia.org/wiki/Steve_Wojciechowski",
      },
      membership: { role: "ASSISTANT_COACH", position: "Associate Head Coach", yearsAtSchool: "1999-2014" },
      careerEvents: [],
    },
    {
      slug: "chris-collins",
      firstName: "Chris",
      lastName: "Collins",
      birthYear: 1975,
      hometown: "Northbrook, IL",
      highSchool: "Glenbrook North High School, Northbrook, IL",
      bio: "Associate Head Coach under Coach K and son of NBA coach Doug Collins. Former Duke player (1993-96) who spent 13 years on staff.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "Northwestern University",
        location: "Evanston, IL",
        statusNote: "After 13 years at Duke (2000-2013), Collins became Northwestern's head coach and is the only coach in the program's 120-year history to lead them to the NCAA Tournament. Extended through 2030 in April 2025.",
        sourceUrl: "https://en.wikipedia.org/wiki/Chris_Collins_(basketball)",
      },
      membership: { role: "ASSISTANT_COACH", position: "Associate Head Coach", yearsAtSchool: "2000-2013" },
      careerEvents: [],
    },
    {
      slug: "mike-krzyzewski",
      firstName: "Mike",
      lastName: "Krzyzewski",
      birthYear: 1947,
      hometown: "Chicago, IL",
      highSchool: "Weber High School, Chicago, IL",
      isFeatured: true,
      bio: "Coached Duke to a 22-11 record and an NCAA Tournament berth in a rebuilding year following the loss of J.J. Redick and Shelden Williams. Duke was upset by VCU in the first round.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Special Advisor / Duke Ambassador",
        currentEmployer: "Duke University",
        location: "Durham, NC",
        statusNote: "Retired after the 2021-22 season as the winningest coach in Division I men's basketball history with 1,202 victories across 47 seasons. Won five national championships, reached 13 Final Fours, and won three Olympic gold medals as Team USA head coach.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Krzyzewski",
      },
      membership: {
        role: "HEAD_COACH",
        position: "Head Coach",
        yearsAtSchool: "1980-2022",
        statsNote: "22-11 • NCAA Tournament 1st round • Rebuilding year",
      },
      careerEvents: [
        { year: 2007, title: "Duke upset by VCU in first round of NCAA Tournament", eventType: "OTHER" },
        { year: 2022, title: "Retired as winningest coach in D-I history", eventType: "RETIREMENT" },
      ],
    },
  ],
};
