import type { TeamSeed } from "./types";

export const floridaBasketball2004: TeamSeed = {
  slug: "florida-basketball-2004",
  name: "Florida Gators",
  season: "2003-2004",
  sport: "Men's Basketball",
  school: "University of Florida",
  conference: "SEC",
  accomplishment: "NIT (20-11, Future Champions Arrive)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/57.png",
  mascotName: "Albert",
  people: [
    {
      slug: "al-horford",
      firstName: "Al",
      lastName: "Horford",
      birthYear: 1986,
      hometown: "Grand Ledge, MI",
      highSchool: "Grand Ledge High School, Grand Ledge, MI",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/201143.png",
      bio: "A Dominican-born center who arrived as part of the legendary 2003 recruiting class that would win back-to-back national championships. Horford developed into one of the most versatile big men in NBA history.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "Boston Celtics",
        league: "NBA",
        location: "Boston, MA",
        statusNote:
          "Selected #3 overall by the Atlanta Hawks in the 2007 NBA Draft after three years at Florida and back-to-back national championships (2006, 2007). A six-time NBA All-Star over a 19-year career with the Hawks, Celtics, 76ers, and Thunder. Won the 2024 NBA Championship with Boston at age 37. One of the most durable and intelligent big men of his generation, known for his passing, shooting, and defensive versatility.",
        sourceUrl: "https://en.wikipedia.org/wiki/Al_Horford",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 42,
        position: "Center / Power Forward",
        yearsAtSchool: "2003-2007",
        statsNote: "Freshman • Part of legendary 2003 recruiting class • 2x National Champion",
        gamesPlayed: 31,
        pointsPerGame: 6.5,
        reboundsPerGame: 5.0,
        assistsPerGame: 0.8,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Grand Ledge High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 14.8, reboundsPerGame: 9.5, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2003-04", yearLabel: "2003-04 (Freshman)", sortOrder: 201, gamesPlayed: 31, pointsPerGame: 6.5, reboundsPerGame: 5.0, assistsPerGame: 0.8 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2004-05", yearLabel: "2004-05", sortOrder: 202, gamesPlayed: 32, pointsPerGame: 10.0, reboundsPerGame: 6.5, assistsPerGame: 1.0 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2005-06", yearLabel: "2005-06 (National Champion)", sortOrder: 203, gamesPlayed: 36, pointsPerGame: 11.3, reboundsPerGame: 7.5, assistsPerGame: 1.4 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2006-07", yearLabel: "2006-07 (National Champion)", sortOrder: 204, gamesPlayed: 35, pointsPerGame: 13.2, reboundsPerGame: 9.5, assistsPerGame: 1.9, fieldGoalPct: 0.561 },
        { level: "PROFESSIONAL", teamName: "Atlanta Hawks", season: "2007-08", yearLabel: "2007-08 (Rookie)", sortOrder: 301, gamesPlayed: 81, pointsPerGame: 10.1, reboundsPerGame: 9.7, assistsPerGame: 1.5, fieldGoalPct: 0.499 },
        { level: "PROFESSIONAL", teamName: "Atlanta Hawks", season: "2010-11", yearLabel: "2010-11 (All-Star)", sortOrder: 304, gamesPlayed: 77, pointsPerGame: 15.3, reboundsPerGame: 9.3, assistsPerGame: 3.5, fieldGoalPct: 0.557 },
        { level: "PROFESSIONAL", teamName: "Atlanta Hawks", season: "2014-15", yearLabel: "2014-15 (All-Star)", sortOrder: 308, gamesPlayed: 76, pointsPerGame: 15.2, reboundsPerGame: 7.3, assistsPerGame: 3.2, fieldGoalPct: 0.538 },
        { level: "PROFESSIONAL", teamName: "Boston Celtics", season: "2019-20", yearLabel: "2019-20", sortOrder: 313, gamesPlayed: 67, pointsPerGame: 10.2, reboundsPerGame: 6.7, assistsPerGame: 4.2, threePointPct: 0.359 },
        { level: "PROFESSIONAL", teamName: "Boston Celtics", season: "2023-24", yearLabel: "2023-24 (Champion!)", sortOrder: 317, gamesPlayed: 65, pointsPerGame: 8.6, reboundsPerGame: 5.4, assistsPerGame: 2.6, threePointPct: 0.383 },
      ],
      careerEvents: [
        { year: 2006, title: "Won NCAA National Championship with Florida", eventType: "CHAMPIONSHIP" },
        { year: 2007, title: "Won back-to-back NCAA Championship", eventType: "CHAMPIONSHIP" },
        { year: 2007, title: "Selected #3 overall by the Atlanta Hawks", eventType: "DRAFT" },
        { year: 2011, title: "First NBA All-Star selection", eventType: "AWARD" },
        { year: 2024, title: "Won NBA Championship with Boston Celtics", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "joakim-noah",
      firstName: "Joakim",
      lastName: "Noah",
      birthYear: 1985,
      hometown: "New York, NY",
      highSchool: "Lawrenceville School, Lawrenceville, NJ",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/201149.png",
      bio: "The son of French tennis legend Yannick Noah who became one of the most passionate and intense competitors in basketball history. Named Most Outstanding Player of both the 2006 and 2007 Final Fours.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Philanthropist / Entrepreneur",
        location: "New York, NY",
        statusNote:
          "Selected #9 overall by the Chicago Bulls in 2007, Noah was the 2014 NBA Defensive Player of the Year and a one-time All-Star. He anchored the Bulls' defense during their playoff runs from 2009-2015, famously battling LeBron James' Heat. After stints with the Knicks and Clippers, he retired in 2020. Now deeply involved in philanthropy through Noah's Arc Foundation, empowering youth in underserved communities. Based in New York and Los Angeles. Son of tennis legend Yannick Noah.",
        sourceUrl: "https://en.wikipedia.org/wiki/Joakim_Noah",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 13,
        position: "Center",
        yearsAtSchool: "2003-2007",
        statsNote: "Freshman • 2x MOP of Final Four • 2x National Champion",
        gamesPlayed: 31,
        pointsPerGame: 3.0,
        reboundsPerGame: 3.5,
        assistsPerGame: 0.5,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Lawrenceville School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 9.5, reboundsPerGame: 7.5, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2003-04", yearLabel: "2003-04 (Freshman)", sortOrder: 201, gamesPlayed: 31, pointsPerGame: 3.0, reboundsPerGame: 3.5, assistsPerGame: 0.5 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2004-05", yearLabel: "2004-05", sortOrder: 202, gamesPlayed: 32, pointsPerGame: 6.5, reboundsPerGame: 5.0, assistsPerGame: 1.0 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2005-06", yearLabel: "2005-06 (Champion, Final Four MOP)", sortOrder: 203, gamesPlayed: 36, pointsPerGame: 7.1, reboundsPerGame: 5.8, assistsPerGame: 0.9 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2006-07", yearLabel: "2006-07 (Champion, Final Four MOP)", sortOrder: 204, gamesPlayed: 35, pointsPerGame: 12.3, reboundsPerGame: 8.4, assistsPerGame: 2.2, fieldGoalPct: 0.576 },
        { level: "PROFESSIONAL", teamName: "Chicago Bulls", season: "2007-08", yearLabel: "2007-08 (Rookie)", sortOrder: 301, gamesPlayed: 74, pointsPerGame: 6.6, reboundsPerGame: 5.6, assistsPerGame: 1.0 },
        { level: "PROFESSIONAL", teamName: "Chicago Bulls", season: "2010-11", yearLabel: "2010-11", sortOrder: 304, gamesPlayed: 48, pointsPerGame: 10.7, reboundsPerGame: 10.4, assistsPerGame: 2.8, fieldGoalPct: 0.485 },
        { level: "PROFESSIONAL", teamName: "Chicago Bulls", season: "2013-14", yearLabel: "2013-14 (DPOY, All-Star)", sortOrder: 307, gamesPlayed: 80, pointsPerGame: 12.6, reboundsPerGame: 11.3, assistsPerGame: 5.4, fieldGoalPct: 0.475 },
      ],
      careerEvents: [
        { year: 2006, title: "Won NCAA Championship; named Final Four MOP", eventType: "CHAMPIONSHIP" },
        { year: 2007, title: "Won back-to-back NCAA Championship; 2x Final Four MOP", eventType: "CHAMPIONSHIP" },
        { year: 2007, title: "Selected #9 overall by the Chicago Bulls", eventType: "DRAFT" },
        { year: 2014, title: "Won NBA Defensive Player of the Year", eventType: "AWARD" },
        { year: 2020, title: "Retired from the NBA", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "corey-brewer",
      firstName: "Corey",
      lastName: "Brewer",
      birthYear: 1986,
      hometown: "Portland, TN",
      highSchool: "Portland High School, Portland, TN",
      isFeatured: true,
      bio: "An energy-packed wing known for his relentless defense and transition play. Part of the legendary freshman class that won back-to-back championships. Once scored 51 points in an NBA game.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NBA Player / Mentor",
        location: "Portland, TN",
        statusNote:
          "Selected #7 overall by the Minnesota Timberwolves in 2007. Played 13 NBA seasons across six teams — Timberwolves, Mavericks, Rockets, Lakers, Thunder, 76ers, and Kings. Known for his energy and defense, with a career highlight of a 51-point game for Houston against Indiana in 2014 (most points in a game that season). Has expressed interest in coaching and mentoring. Active in the Portland, TN community and regularly appears at Florida Gators events.",
        sourceUrl: "https://en.wikipedia.org/wiki/Corey_Brewer",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 2,
        position: "Small Forward / Shooting Guard",
        yearsAtSchool: "2003-2007",
        statsNote: "Freshman • 2x National Champion • #7 overall pick",
        gamesPlayed: 31,
        pointsPerGame: 5.0,
        reboundsPerGame: 2.5,
        assistsPerGame: 1.0,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Portland High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 12.5, reboundsPerGame: 6.2, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2003-04", yearLabel: "2003-04 (Freshman)", sortOrder: 201, gamesPlayed: 31, pointsPerGame: 5.0, reboundsPerGame: 2.5, assistsPerGame: 1.0 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2004-05", yearLabel: "2004-05", sortOrder: 202, gamesPlayed: 32, pointsPerGame: 8.5, reboundsPerGame: 4.0, assistsPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2005-06", yearLabel: "2005-06 (National Champion)", sortOrder: 203, gamesPlayed: 36, pointsPerGame: 11.3, reboundsPerGame: 4.4, assistsPerGame: 2.1 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2006-07", yearLabel: "2006-07 (National Champion)", sortOrder: 204, gamesPlayed: 35, pointsPerGame: 12.8, reboundsPerGame: 4.7, assistsPerGame: 2.3, stealsPerGame: 2.2, fieldGoalPct: 0.476 },
        { level: "PROFESSIONAL", teamName: "Minnesota Timberwolves", season: "2007-08", yearLabel: "2007-08 (Rookie)", sortOrder: 301, gamesPlayed: 79, pointsPerGame: 7.2, reboundsPerGame: 2.4, assistsPerGame: 1.0, stealsPerGame: 1.2 },
        { level: "PROFESSIONAL", teamName: "Minnesota Timberwolves", season: "2010-11", yearLabel: "2010-11", sortOrder: 304, gamesPlayed: 69, pointsPerGame: 12.8, reboundsPerGame: 3.6, assistsPerGame: 1.8, stealsPerGame: 2.0 },
        { level: "PROFESSIONAL", teamName: "Houston Rockets", season: "2013-14", yearLabel: "2013-14 (51-pt game!)", sortOrder: 307, gamesPlayed: 54, pointsPerGame: 8.8, reboundsPerGame: 2.7, assistsPerGame: 0.9, stealsPerGame: 1.3 },
      ],
      careerEvents: [
        { year: 2006, title: "Won NCAA National Championship with Florida", eventType: "CHAMPIONSHIP" },
        { year: 2007, title: "Won back-to-back NCAA Championship", eventType: "CHAMPIONSHIP" },
        { year: 2007, title: "Selected #7 overall by the Minnesota Timberwolves", eventType: "DRAFT" },
        { year: 2014, title: "Scored 51 points vs Indiana — most in NBA that season", eventType: "OTHER" },
        { year: 2020, title: "Retired from the NBA after 13 seasons", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "taurean-green",
      firstName: "Taurean",
      lastName: "Green",
      birthYear: 1986,
      hometown: "Hayward, CA",
      highSchool: "Mt. Zion Christian Academy, Durham, NC",
      isFeatured: false,
      bio: "The point guard of the legendary freshman class. Green was the floor general who orchestrated Florida's back-to-back championship runs.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Basketball Trainer / Youth Development",
        location: "Florida",
        statusNote:
          "Selected #52 by Portland in the 2007 NBA Draft. Had brief NBA stints but built a long professional career overseas in Israel, Italy, France, Germany, and Australia. After retiring from playing, Green transitioned to basketball training and youth development. He maintains a relatively private post-playing career but remains connected to the Florida Gators basketball community.",
        sourceUrl: "https://en.wikipedia.org/wiki/Taurean_Green",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 11,
        position: "Point Guard",
        yearsAtSchool: "2003-2007",
        statsNote: "Freshman • 2x National Champion • Floor general",
        gamesPlayed: 28,
        pointsPerGame: 3.5,
        reboundsPerGame: 1.0,
        assistsPerGame: 2.0,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Mt. Zion Christian Academy", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 10.2, reboundsPerGame: 1.0, assistsPerGame: 4.6 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2003-04", yearLabel: "2003-04 (Freshman)", sortOrder: 201, gamesPlayed: 28, pointsPerGame: 3.5, reboundsPerGame: 1.0, assistsPerGame: 2.0 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2004-05", yearLabel: "2004-05", sortOrder: 202, gamesPlayed: 32, pointsPerGame: 7.0, reboundsPerGame: 1.5, assistsPerGame: 3.5 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2005-06", yearLabel: "2005-06 (National Champion)", sortOrder: 203, gamesPlayed: 36, pointsPerGame: 11.5, reboundsPerGame: 2.0, assistsPerGame: 4.5, threePointPct: 0.423 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2006-07", yearLabel: "2006-07 (National Champion)", sortOrder: 204, gamesPlayed: 35, pointsPerGame: 13.0, reboundsPerGame: 2.2, assistsPerGame: 5.1, threePointPct: 0.401 },
      ],
      careerEvents: [
        { year: 2006, title: "Won NCAA National Championship with Florida", eventType: "CHAMPIONSHIP" },
        { year: 2007, title: "Won back-to-back NCAA Championship", eventType: "CHAMPIONSHIP" },
        { year: 2007, title: "Selected #52 overall by the Portland Trail Blazers", eventType: "DRAFT" },
      ],
    },
    {
      slug: "david-lee",
      firstName: "David",
      lastName: "Lee",
      birthYear: 1983,
      hometown: "St. Louis, MO",
      highSchool: "Chaminade College Prep, St. Louis, MO",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/101135.png",
      bio: "A skilled power forward who was the team's best player as a junior and senior before the championship freshmen fully blossomed. Lee became a two-time NBA All-Star.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NBA Player / Businessman",
        location: "St. Louis, MO",
        statusNote:
          "Selected #30 overall by the New York Knicks in the 2005 NBA Draft. Lee became a two-time All-Star (2010, 2013) over a 12-year NBA career with the Knicks, Warriors, Celtics, Mavericks, and Spurs. Won an NBA Championship with the Golden State Warriors in 2015. After retiring in 2017, Lee has been involved in real estate and business ventures in the St. Louis area. Active in philanthropic work and regularly seen at Florida Gators events.",
        sourceUrl: "https://en.wikipedia.org/wiki/David_Lee_(basketball)",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 30,
        position: "Power Forward",
        yearsAtSchool: "2001-2005",
        statsNote: "Junior • Team's leading scorer and rebounder • First-team All-SEC",
        gamesPlayed: 31,
        pointsPerGame: 15.0,
        reboundsPerGame: 9.0,
        assistsPerGame: 2.0,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Chaminade College Prep", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 27.5, reboundsPerGame: 14.7, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2001-02", yearLabel: "2001-02 (Freshman)", sortOrder: 201, gamesPlayed: 31, pointsPerGame: 5.5, reboundsPerGame: 4.8, assistsPerGame: 0.5 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2002-03", yearLabel: "2002-03", sortOrder: 202, gamesPlayed: 33, pointsPerGame: 11.5, reboundsPerGame: 7.0, assistsPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2003-04", yearLabel: "2003-04", sortOrder: 203, gamesPlayed: 31, pointsPerGame: 15.0, reboundsPerGame: 9.0, assistsPerGame: 2.0 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2004-05", yearLabel: "2004-05 (First-team All-SEC)", sortOrder: 204, gamesPlayed: 32, pointsPerGame: 16.0, reboundsPerGame: 9.5, assistsPerGame: 2.0 },
        { level: "PROFESSIONAL", teamName: "New York Knicks", season: "2005-06", yearLabel: "2005-06 (Rookie)", sortOrder: 301, gamesPlayed: 67, pointsPerGame: 5.9, reboundsPerGame: 4.4, assistsPerGame: 0.8 },
        { level: "PROFESSIONAL", teamName: "New York Knicks", season: "2008-09", yearLabel: "2008-09", sortOrder: 304, gamesPlayed: 81, pointsPerGame: 16.0, reboundsPerGame: 11.7, assistsPerGame: 3.6 },
        { level: "PROFESSIONAL", teamName: "New York Knicks", season: "2009-10", yearLabel: "2009-10 (All-Star)", sortOrder: 305, gamesPlayed: 81, pointsPerGame: 20.2, reboundsPerGame: 11.7, assistsPerGame: 3.6, fieldGoalPct: 0.545 },
        { level: "PROFESSIONAL", teamName: "Golden State Warriors", season: "2012-13", yearLabel: "2012-13 (All-Star)", sortOrder: 308, gamesPlayed: 79, pointsPerGame: 18.5, reboundsPerGame: 11.2, assistsPerGame: 3.5, fieldGoalPct: 0.519 },
        { level: "PROFESSIONAL", teamName: "Golden State Warriors", season: "2014-15", yearLabel: "2014-15 (Champion!)", sortOrder: 310, gamesPlayed: 37, pointsPerGame: 7.9, reboundsPerGame: 5.2, assistsPerGame: 1.5 },
      ],
      careerEvents: [
        { year: 2005, title: "Selected #30 overall by the New York Knicks", eventType: "DRAFT" },
        { year: 2010, title: "First NBA All-Star selection (Knicks)", eventType: "AWARD" },
        { year: 2015, title: "Won NBA Championship with Golden State Warriors", eventType: "CHAMPIONSHIP" },
        { year: 2017, title: "Retired from the NBA after 12 seasons", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "anthony-roberson",
      firstName: "Anthony",
      lastName: "Roberson",
      birthYear: 1984,
      hometown: "Saginaw, MI",
      highSchool: "Arthur Hill High School, Saginaw, MI",
      isFeatured: false,
      bio: "A sophomore guard who led the team in scoring at 17.9 PPG. Named First-Team All-SEC.",
      status: {
        occupationType: "COACH",
        currentTitle: "Lead Coach / Skill Development",
        currentEmployer: "DME Academy",
        location: "Daytona Beach, FL",
        statusNote: "Declared for the 2005 NBA Draft after his junior year. Played 65 NBA games across five teams. Had an extensive international career in Israel, France, Italy, China, Taiwan, and Mexico. Now a lead coach and skill-development specialist at DME Academy in Daytona Beach, FL.",
        sourceUrl: "https://dmeacademy.com/staff/roberson-anthony/",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Shooting Guard", yearsAtSchool: "2002-2005", statsNote: "Sophomore • First-Team All-SEC • Team-leading 17.9 PPG", gamesPlayed: 31, pointsPerGame: 17.9, reboundsPerGame: 2.4, assistsPerGame: 2.0 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Arthur Hill High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 31.8, reboundsPerGame: 2.4, assistsPerGame: 4.6 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2003-04", yearLabel: "2003-04 (Sophomore, First-Team All-SEC)", sortOrder: 202, gamesPlayed: 31, pointsPerGame: 17.9, reboundsPerGame: 2.4, assistsPerGame: 2.0 },
      ],
      careerEvents: [],
    },
    {
      slug: "matt-walsh",
      firstName: "Matt",
      lastName: "Walsh",
      birthYear: 1984,
      hometown: "Jenkintown, PA",
      highSchool: "Germantown Academy, Fort Washington, PA",
      isFeatured: false,
      bio: "A sophomore forward who averaged 15.9 PPG and was named Second-Team All-SEC. Later became a sports team owner.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Sports Team Owner / Entrepreneur",
        currentEmployer: "New Zealand Breakers / Tech Ventures",
        location: "Austin, TX",
        statusNote: "After going undrafted, played one season with the Miami Heat before building a long career in European basketball (Italy, Spain, Israel, Turkey). Became a successful entrepreneur — purchased the New Zealand Breakers (NBL) in 2017, owns a soccer team in Mexico, and runs tech ventures. Lives in Austin, TX.",
        sourceUrl: "https://en.wikipedia.org/wiki/Matt_Walsh_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 44, position: "Forward", yearsAtSchool: "2001-2005", statsNote: "Sophomore • Second-Team All-SEC • 15.9 PPG", gamesPlayed: 31, pointsPerGame: 15.9, reboundsPerGame: 5.0, assistsPerGame: 1.5 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Germantown Academy", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 28.9, reboundsPerGame: 9.5, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2003-04", yearLabel: "2003-04 (Sophomore)", sortOrder: 202, gamesPlayed: 31, pointsPerGame: 15.9, reboundsPerGame: 5.0, assistsPerGame: 1.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "christian-drejer",
      firstName: "Christian",
      lastName: "Drejer",
      birthYear: 1982,
      hometown: "Hallerup, Denmark",
      highSchool: "Danish youth system",
      isFeatured: false,
      bio: "A senior guard/forward from Denmark — the first Dane ever drafted by the NBA.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "Denmark",
        statusNote: "The first Dane ever drafted by the NBA (#51 overall in 2004 by the Nets). Never played in the NBA. Played professionally in Europe (Virtus Roma, etc.) before injuries forced retirement at age 25 in 2008.",
        sourceUrl: "https://en.wikipedia.org/wiki/Christian_Drejer",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Guard / Forward", yearsAtSchool: "2000-2004", statsNote: "Senior • First Dane drafted by NBA • 8.5 PPG", gamesPlayed: 31, pointsPerGame: 8.5, reboundsPerGame: 4.0, assistsPerGame: 2.5 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Danish youth system", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 17.8, reboundsPerGame: 8.2, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2003-04", yearLabel: "2003-04 (Senior)", sortOrder: 204, gamesPlayed: 31, pointsPerGame: 8.5, reboundsPerGame: 4.0, assistsPerGame: 2.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "adrian-moss",
      firstName: "Adrian",
      lastName: "Moss",
      birthYear: 1983,
      hometown: "Houston, TX",
      highSchool: "High school in Houston, TX",
      isFeatured: false,
      bio: "A forward who would captain the 2006 national championship team. Later became a basketball coach in Denmark.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "Denmark",
        statusNote: "Captain of the 2006 national championship team. Had an extensive professional career in Europe, South America, and Asia. Became a basketball coach in Denmark — served as head coach of BMS Herlev Wolfpack in the Danish league.",
        sourceUrl: "https://en.wikipedia.org/wiki/Adrian_Moss_(basketball,_born_1981)",
      },
      membership: { role: "PLAYER", jerseyNumber: 30, position: "Forward", yearsAtSchool: "2002-2007", statsNote: "Freshman • Future 2006 championship captain", gamesPlayed: 31, pointsPerGame: 3.5, reboundsPerGame: 2.5, assistsPerGame: 0.3 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "High school in Houston", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 10.2, reboundsPerGame: 6.2, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2003-04", yearLabel: "2003-04 (Freshman)", sortOrder: 201, gamesPlayed: 31, pointsPerGame: 3.5, reboundsPerGame: 2.5, assistsPerGame: 0.3 },
      ],
      careerEvents: [],
    },
    {
      slug: "lee-humphrey",
      firstName: "Lee",
      lastName: "Humphrey",
      birthYear: 1984,
      hometown: "Maryville, TN",
      highSchool: "Maryville High School, Maryville, TN",
      isFeatured: false,
      bio: "One of the greatest three-point shooters in Florida history, Humphrey arrived as part of the legendary 2003 recruiting class. As Tennessee's Class AAA Mr. Basketball averaging 27.6 points as a senior, he set both the single-season and career three-point records at Florida during his four years.",
      status: {
        occupationType: "BROADCASTER_ANALYST",
        currentTitle: "Sales Director / Radio Analyst",
        currentEmployer: "Pontoon Solutions / Florida Gators Radio Network",
        location: "Maryville, TN",
        statusNote:
          "After winning back-to-back NCAA championships (2006, 2007), Humphrey went undrafted but had a professional playing career overseas in Greece, Poland, Germany, France, and Lithuania. Following retirement, he joined Pontoon Solutions in 2015 and became Sales Director in April 2021. Since the 2021-22 season he has served as an analyst for Florida Gators men's basketball radio broadcasts, staying closely connected to the program. He was inducted into the Maryville High School Athletic Hall of Fame.",
        sourceUrl: "https://en.wikipedia.org/wiki/Lee_Humphrey",
        linkedInUrl: "https://www.linkedin.com/in/lee-humphrey-87377169/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 12,
        position: "Shooting Guard",
        yearsAtSchool: "2003-2007",
        statsNote: "Freshman • 26 games • 43.9% from 3-point range • 2x Future National Champion",
        gamesPlayed: 26,
        pointsPerGame: 4.0,
        reboundsPerGame: 1.0,
        assistsPerGame: 1.1,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Maryville High School", season: "2002-03", yearLabel: "Senior (TN Mr. Basketball)", sortOrder: 101, pointsPerGame: 27.6, reboundsPerGame: 8.0, assistsPerGame: 7.0 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2003-04", yearLabel: "2003-04 (Freshman)", sortOrder: 201, gamesPlayed: 26, pointsPerGame: 4.0, reboundsPerGame: 1.0, assistsPerGame: 1.1, threePointPct: 0.439 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2004-05", yearLabel: "2004-05 (Sophomore)", sortOrder: 202, gamesPlayed: 32, pointsPerGame: 6.0, reboundsPerGame: 1.5, assistsPerGame: 1.0, threePointPct: 0.411 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2005-06", yearLabel: "2005-06 (Junior, National Champion)", sortOrder: 203, gamesPlayed: 36, pointsPerGame: 9.8, reboundsPerGame: 2.0, assistsPerGame: 1.5, threePointPct: 0.451 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2006-07", yearLabel: "2006-07 (Senior, National Champion)", sortOrder: 204, gamesPlayed: 35, pointsPerGame: 11.8, reboundsPerGame: 2.2, assistsPerGame: 1.8, threePointPct: 0.431 },
      ],
      careerEvents: [
        { year: 2006, title: "Won NCAA National Championship with Florida", eventType: "CHAMPIONSHIP" },
        { year: 2007, title: "Won back-to-back NCAA Championship; set UF career 3-point record (288)", eventType: "CHAMPIONSHIP" },
        { year: 2015, title: "Joined Pontoon Solutions", eventType: "CAREER_CHANGE" },
        { year: 2021, title: "Promoted to Sales Director at Pontoon Solutions", eventType: "CAREER_CHANGE" },
        { year: 2021, title: "Became radio analyst for Florida Gators basketball", eventType: "CAREER_CHANGE" },
      ],
    },
    {
      slug: "chris-richard",
      firstName: "Chris",
      lastName: "Richard",
      birthYear: 1984,
      hometown: "Lakeland, FL",
      highSchool: "Kathleen High School, Lakeland, FL",
      isFeatured: false,
      bio: "Florida's Mr. Basketball in 2003 who arrived as a highly touted big man from Lakeland. Richard set a school freshman record by shooting 60.5% from the field in 2003-04, going on to become the SEC Sixth Man of the Year and captain of the 2007 national championship team.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Retired Professional Basketball Player",
        location: "Florida",
        statusNote:
          "After winning back-to-back national championships at Florida (2006, 2007) and becoming the winningest player in school history with 112 victories, Richard was selected #41 overall by Minnesota in the 2007 NBA Draft. He played 70 NBA games over three seasons with the Timberwolves and Bulls, averaging 1.9 points and 2.8 rebounds. He also played for the Liaoning Leopards in China's CBA. Named an SEC Men's Basketball Legend in 2023, he remains a celebrated figure in Gators history. He has maintained a private life since retiring from professional basketball.",
        sourceUrl: "https://en.wikipedia.org/wiki/Chris_Richard_(basketball)",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 24,
        position: "Power Forward / Center",
        yearsAtSchool: "2003-2007",
        statsNote: "Freshman • 30 games • School-record 60.5% FG for freshmen • 2x Future National Champion",
        gamesPlayed: 30,
        pointsPerGame: 3.8,
        reboundsPerGame: 2.6,
        assistsPerGame: 0.2,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Kathleen High School", season: "2002-03", yearLabel: "Senior (FL Mr. Basketball)", sortOrder: 101, pointsPerGame: 14.0, reboundsPerGame: 8.5, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2003-04", yearLabel: "2003-04 (Freshman)", sortOrder: 201, gamesPlayed: 30, pointsPerGame: 3.8, reboundsPerGame: 2.6, assistsPerGame: 0.2, fieldGoalPct: 0.605 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2004-05", yearLabel: "2004-05 (Sophomore)", sortOrder: 202, gamesPlayed: 32, pointsPerGame: 5.2, reboundsPerGame: 3.8, assistsPerGame: 0.3, fieldGoalPct: 0.620 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2005-06", yearLabel: "2005-06 (Junior, National Champion)", sortOrder: 203, gamesPlayed: 36, pointsPerGame: 6.1, reboundsPerGame: 4.2, assistsPerGame: 0.4, fieldGoalPct: 0.698 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2006-07", yearLabel: "2006-07 (Senior, Champion, SEC 6th Man)", sortOrder: 204, gamesPlayed: 35, pointsPerGame: 7.8, reboundsPerGame: 4.5, assistsPerGame: 0.6, fieldGoalPct: 0.690 },
        { level: "PROFESSIONAL", teamName: "Minnesota Timberwolves", season: "2007-08", yearLabel: "2007-08 (Rookie)", sortOrder: 301, gamesPlayed: 52, pointsPerGame: 2.1, reboundsPerGame: 3.1, assistsPerGame: 0.4, fieldGoalPct: 0.500 },
        { level: "PROFESSIONAL", teamName: "Chicago Bulls", season: "2009-10", yearLabel: "2009-10", sortOrder: 303, gamesPlayed: 18, pointsPerGame: 1.2, reboundsPerGame: 2.1, assistsPerGame: 0.4 },
      ],
      careerEvents: [
        { year: 2006, title: "Won NCAA National Championship with Florida", eventType: "CHAMPIONSHIP" },
        { year: 2007, title: "Won back-to-back NCAA Championship; named SEC Sixth Man of the Year", eventType: "CHAMPIONSHIP" },
        { year: 2007, title: "Selected #41 overall by the Minnesota Timberwolves", eventType: "DRAFT" },
        { year: 2010, title: "Waived by Chicago Bulls; retired from NBA", eventType: "RETIREMENT" },
        { year: 2023, title: "Honored as SEC Men's Basketball Legend", eventType: "AWARD" },
      ],
    },
    {
      slug: "billy-donovan",
      firstName: "Billy",
      lastName: "Donovan",
      birthYear: 1965,
      hometown: "Rockville Centre, NY",
      highSchool: "St. Agnes Cathedral High School, Rockville Centre, NY",
      isFeatured: true,
      bio: "The architect of Florida's basketball dynasty who won back-to-back national championships in 2006 and 2007 — one of only seven coaches to win consecutive titles. Donovan built the Gators into a perennial contender during his 19-year tenure.",
      status: {
        occupationType: "COACH",
        currentTitle: "NBA Coaching Candidate",
        location: "United States",
        statusNote:
          "After 19 seasons at Florida (1996-2015) with a 467-186 record and back-to-back national championships (2006, 2007), Donovan left for the NBA. He coached the Oklahoma City Thunder (2015-2020) and Chicago Bulls (2020-2023) before being fired by Chicago. As of 2025-26, he is not currently coaching but has been mentioned as a candidate for various NBA and college head coaching openings. Won the Naismith Coach of the Year in 2007.",
        sourceUrl: "https://en.wikipedia.org/wiki/Billy_Donovan",
      },
      membership: {
        role: "HEAD_COACH",
        position: "Head Coach",
        yearsAtSchool: "1996-2015",
        statsNote: "467-186 at Florida • 2x National Champions (2006, 2007) • SEC record 6 regular season titles",
      },
      careerEvents: [
        { year: 2006, title: "Won NCAA National Championship at Florida", eventType: "CHAMPIONSHIP" },
        { year: 2007, title: "Won back-to-back NCAA National Championship", eventType: "CHAMPIONSHIP" },
        { year: 2015, title: "Left Florida to become Oklahoma City Thunder head coach", eventType: "CAREER" },
        { year: 2020, title: "Named Chicago Bulls head coach", eventType: "CAREER" },
        { year: 2023, title: "Fired by the Chicago Bulls", eventType: "CAREER" },
      ],
    },
  ],
};
