import type { TeamSeed } from "./types";

export const floridaStateBasketball2012: TeamSeed = {
  slug: "florida-state-basketball-2012",
  name: "Florida State Seminoles",
  season: "2011-2012",
  sport: "Men's Basketball",
  school: "Florida State University",
  conference: "ACC",
  accomplishment: "2011-2012 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/52.png",
  mascotName: "Seminole",
  people: [
    {
      slug: "michael-snaer",
      firstName: "Michael",
      lastName: "Snaer",
      birthYear: 1990,
      hometown: "Moreno Valley, CA",
      highSchool: "Rancho Verde",
      bio: "Junior guard. Known for clutch buzzer-beaters.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "United States",
        statusNote: "Played briefly overseas. Famous for multiple game-winning shots at FSU.",
        sourceUrl: "https://en.wikipedia.org/wiki/Michael_Snaer",
      },
      membership: { role: "PLAYER", jerseyNumber: 21, position: "Guard", yearsAtSchool: "2011-2012", gamesPlayed: 34, pointsPerGame: 14.1, reboundsPerGame: 3.3, assistsPerGame: 1.7 },
      seasonStats: [{ level: "COLLEGE", teamName: "Florida State Seminoles", season: "2011-2012", yearLabel: "2011-2012", sortOrder: 201, gamesPlayed: 34, pointsPerGame: 14.1, reboundsPerGame: 3.3, assistsPerGame: 1.7 }],
      careerEvents: [],
    },
    {
      slug: "bernard-james",
      firstName: "Bernard",
      lastName: "James",
      birthYear: 1985,
      hometown: "Savannah, GA",
      highSchool: "Robert Munroe",
      bio: "Senior center. Air Force veteran who started college at age 26. #33 pick by Mavs.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "United States",
        statusNote: "Air Force veteran. Played 3 NBA seasons with Mavs.",
        sourceUrl: "https://en.wikipedia.org/wiki/Bernard_James",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Center", yearsAtSchool: "2011-2012", gamesPlayed: 34, pointsPerGame: 10.8, reboundsPerGame: 8.1, assistsPerGame: 0.4 },
      seasonStats: [{ level: "COLLEGE", teamName: "Florida State Seminoles", season: "2011-2012", yearLabel: "2011-2012", sortOrder: 201, gamesPlayed: 34, pointsPerGame: 10.8, reboundsPerGame: 8.1, assistsPerGame: 0.4 }],
      careerEvents: [{ date: "2012-06-28", month: 6, day: 28, year: 2012, title: "Drafted #33 by Cleveland (traded to Dallas)", description: "Selected in 2012 NBA Draft at age 27." }],
    },
    {
      slug: "leonard-hamilton",
      firstName: "Leonard",
      lastName: "Hamilton",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Coached FSU for 23 years. Elite Eight 2018. Produced 6+ first-round NBA picks.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Resigned 2025. HC Emeritus at FSU.",
        sourceUrl: "https://en.wikipedia.org/wiki/Leonard_Hamilton",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2025" },
      seasonStats: [
        { level: "COACHING", teamName: "Florida State Seminoles", season: "2011-2012", yearLabel: "2011-2012", sortOrder: 204 },
      ],
      careerEvents: [],
    },
  ],
};
