import type { TeamSeed } from "./types";

export const floridaStateBasketball2020: TeamSeed = {
  slug: "florida-state-basketball-2020",
  name: "Florida State Seminoles",
  season: "2019-2020",
  sport: "Men's Basketball",
  school: "Florida State University",
  conference: "ACC",
  accomplishment: "2019-2020 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/52.png",
  mascotName: "Seminole",
  people: [
    {
      slug: "devin-vassell",
      firstName: "Devin",
      lastName: "Vassell",
      birthYear: 2000,
      hometown: "Suwanee, GA",
      highSchool: "Peachtree Ridge",
      bio: "Sophomore wing. #11 pick by Spurs in 2020 NBA Draft.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard/Forward",
        location: "San Antonio, TX",
        statusNote: "Starting guard for Spurs. Signed 5-year $135M extension in 2023.",
        sourceUrl: "https://en.wikipedia.org/wiki/Devin_Vassell",
      },
      membership: { role: "PLAYER", jerseyNumber: 24, position: "Guard", yearsAtSchool: "2019-2020", gamesPlayed: 31, pointsPerGame: 12.7, reboundsPerGame: 5.1, assistsPerGame: 1.6 },
      seasonStats: [{ level: "COLLEGE", teamName: "Florida State Seminoles", season: "2019-2020", yearLabel: "2019-2020", sortOrder: 201, gamesPlayed: 31, pointsPerGame: 12.7, reboundsPerGame: 5.1, assistsPerGame: 1.6 }],
      careerEvents: [{ date: "2020-11-18", month: 11, day: 18, year: 2020, title: "Drafted #11 by San Antonio Spurs", description: "Selected 11th overall in 2020 NBA Draft." }],
    },
    {
      slug: "patrick-williams",
      firstName: "Patrick",
      lastName: "Williams",
      birthYear: 2001,
      hometown: "Charlotte, NC",
      highSchool: "West Charlotte",
      bio: "One-and-done freshman. #4 pick by Chicago Bulls in 2020.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        location: "Chicago, IL",
        statusNote: "Still with Chicago Bulls. Signed 5-year $90M extension in 2024.",
        sourceUrl: "https://en.wikipedia.org/wiki/Patrick_Williams_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Forward", yearsAtSchool: "2019-2020", gamesPlayed: 29, pointsPerGame: 9.2, reboundsPerGame: 4.0, assistsPerGame: 1.0 },
      seasonStats: [{ level: "COLLEGE", teamName: "Florida State Seminoles", season: "2019-2020", yearLabel: "2019-2020", sortOrder: 201, gamesPlayed: 29, pointsPerGame: 9.2, reboundsPerGame: 4.0, assistsPerGame: 1.0 }],
      careerEvents: [{ date: "2020-11-18", month: 11, day: 18, year: 2020, title: "Drafted #4 by Chicago Bulls", description: "Selected 4th overall in 2020 NBA Draft." }],
    },
    {
      slug: "trent-forrest",
      firstName: "Trent",
      lastName: "Forrest",
      birthYear: 1998,
      hometown: "Chipley, FL",
      highSchool: "Chipley",
      bio: "Senior point guard. ACC Defensive Player of the Year.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "United States",
        statusNote: "Played for Jazz and Hawks. Now playing in G League.",
        sourceUrl: "https://en.wikipedia.org/wiki/Trent_Forrest",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Guard", yearsAtSchool: "2019-2020", gamesPlayed: 31, pointsPerGame: 11.1, reboundsPerGame: 4.3, assistsPerGame: 4.1 },
      seasonStats: [{ level: "COLLEGE", teamName: "Florida State Seminoles", season: "2019-2020", yearLabel: "2019-2020", sortOrder: 201, gamesPlayed: 31, pointsPerGame: 11.1, reboundsPerGame: 4.3, assistsPerGame: 4.1 }],
      careerEvents: [],
    },
    {
      slug: "leonard-hamilton",
      firstName: "Leonard",
      lastName: "Hamilton",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Coached FSU for 23 years. Elite Eight 2018. Produced 6+ first-round NBA picks.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Resigned 2025. HC Emeritus at FSU.",
        sourceUrl: "https://en.wikipedia.org/wiki/Leonard_Hamilton",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2025" },
      seasonStats: [
        { level: "COACHING", teamName: "Florida State Seminoles", season: "2019-2020", yearLabel: "2019-2020", sortOrder: 212 },
      ],
      careerEvents: [],
    },
  ],
};
