import type { TeamSeed } from "./types";

export const floridaStateBasketball2016: TeamSeed = {
  slug: "florida-state-basketball-2016",
  name: "Florida State Seminoles",
  season: "2015-2016",
  sport: "Men's Basketball",
  school: "Florida State University",
  conference: "ACC",
  accomplishment: "2015-2016 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/52.png",
  mascotName: "Seminole",
  people: [
    {
      slug: "malik-beasley",
      firstName: "Malik",
      lastName: "Beasley",
      birthYear: 1996,
      hometown: "Atlanta, GA",
      highSchool: "St. Francis",
      bio: "One-and-done freshman guard. #19 pick by Denver Nuggets in 2016.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        location: "Detroit, MI",
        statusNote: "Now with Detroit Pistons. Elite 3-point shooter who had breakout 2024-25 season.",
        sourceUrl: "https://en.wikipedia.org/wiki/Malik_Beasley",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Guard", yearsAtSchool: "2015-2016", gamesPlayed: 34, pointsPerGame: 15.6, reboundsPerGame: 5.3, assistsPerGame: 1.5 },
      seasonStats: [{ level: "COLLEGE", teamName: "Florida State Seminoles", season: "2015-2016", yearLabel: "2015-2016", sortOrder: 201, gamesPlayed: 34, pointsPerGame: 15.6, reboundsPerGame: 5.3, assistsPerGame: 1.5 }],
      careerEvents: [{ date: "2016-06-23", month: 6, day: 23, year: 2016, title: "Drafted #19 by Denver Nuggets", description: "Selected 19th overall in 2016 NBA Draft." }],
    },
    {
      slug: "leonard-hamilton",
      firstName: "Leonard",
      lastName: "Hamilton",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Coached FSU for 23 years. Elite Eight 2018. Produced 6+ first-round NBA picks.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Resigned 2025. HC Emeritus at FSU.",
        sourceUrl: "https://en.wikipedia.org/wiki/Leonard_Hamilton",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2025" },
      seasonStats: [
        { level: "COACHING", teamName: "Florida State Seminoles", season: "2015-2016", yearLabel: "2015-2016", sortOrder: 208 },
      ],
      careerEvents: [],
    },
  ],
};
