import type { TeamSeed } from "./types";

export const floridaStateBasketball2021: TeamSeed = {
  slug: "florida-state-basketball-2021",
  name: "Florida State Seminoles",
  season: "2020-2021",
  sport: "Men's Basketball",
  school: "Florida State University",
  conference: "ACC",
  accomplishment: "2020-2021 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/52.png",
  mascotName: "Seminole",
  people: [
    {
      slug: "scottie-barnes",
      firstName: "Scottie",
      lastName: "Barnes",
      birthYear: 2001,
      hometown: "West Palm Beach, FL",
      highSchool: "Montverde Academy",
      bio: "One-and-done freshman. #4 pick by Raptors. 2022 NBA Rookie of the Year.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        location: "Toronto, ON",
        statusNote: "Raptors franchise cornerstone. 2024 NBA All-Star. Signed 5-year $270M max extension.",
        sourceUrl: "https://en.wikipedia.org/wiki/Scottie_Barnes",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Forward", yearsAtSchool: "2020-2021", gamesPlayed: 24, pointsPerGame: 10.3, reboundsPerGame: 4.0, assistsPerGame: 4.1 },
      seasonStats: [{ level: "COLLEGE", teamName: "Florida State Seminoles", season: "2020-2021", yearLabel: "2020-2021", sortOrder: 201, gamesPlayed: 24, pointsPerGame: 10.3, reboundsPerGame: 4.0, assistsPerGame: 4.1 }],
      careerEvents: [{ date: "2021-07-29", month: 7, day: 29, year: 2021, title: "Drafted #4 by Toronto Raptors", description: "Won 2022 NBA Rookie of the Year." }],
    },
    {
      slug: "mj-walker",
      firstName: "M.J.",
      lastName: "Walker",
      birthYear: 1998,
      hometown: "Jonesboro, GA",
      highSchool: "Jonesboro",
      bio: "Senior guard and floor leader.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "Overseas",
        statusNote: "Plays professionally overseas after FSU career.",
        sourceUrl: "https://en.wikipedia.org/wiki/M._J._Walker",
      },
      membership: { role: "PLAYER", jerseyNumber: 23, position: "Guard", yearsAtSchool: "2020-2021", gamesPlayed: 24, pointsPerGame: 12.4, reboundsPerGame: 3.5, assistsPerGame: 1.8 },
      seasonStats: [{ level: "COLLEGE", teamName: "Florida State Seminoles", season: "2020-2021", yearLabel: "2020-2021", sortOrder: 201, gamesPlayed: 24, pointsPerGame: 12.4, reboundsPerGame: 3.5, assistsPerGame: 1.8 }],
      careerEvents: [],
    },
    {
      slug: "leonard-hamilton",
      firstName: "Leonard",
      lastName: "Hamilton",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Coached FSU for 23 years. Elite Eight 2018. Produced 6+ first-round NBA picks.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Resigned 2025. HC Emeritus at FSU.",
        sourceUrl: "https://en.wikipedia.org/wiki/Leonard_Hamilton",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2025" },
      seasonStats: [
        { level: "COACHING", teamName: "Florida State Seminoles", season: "2020-2021", yearLabel: "2020-2021", sortOrder: 213 },
      ],
      careerEvents: [],
    },
  ],
};
