import type { TeamSeed } from "./types";

export const floridaBasketball2005: TeamSeed = {
  slug: "florida-basketball-2005",
  name: "Florida Gators",
  season: "2004-2005",
  sport: "Men's Basketball",
  school: "University of Florida",
  conference: "SEC",
  accomplishment: "SEC Regular Season Champions (24-8, NCAA 2nd Round)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/57.png",
  mascotName: "Albert",
  people: [
    {
      slug: "al-horford",
      firstName: "Al",
      lastName: "Horford",
      birthYear: 1986,
      hometown: "Grand Ledge, MI",
      highSchool: "Grand Ledge High School, Grand Ledge, MI",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/201143.png",
      bio: "A Dominican-born center developing into a dominant force as a sophomore. Part of the legendary class that would win back-to-back championships.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "Boston Celtics",
        league: "NBA",
        location: "Boston, MA",
        statusNote: "Six-time NBA All-Star over a 19-year career. Won the 2024 NBA Championship with Boston at age 37. Selected #3 overall in 2007 after three years at Florida and back-to-back national championships.",
        sourceUrl: "https://en.wikipedia.org/wiki/Al_Horford",
      },
      membership: { role: "PLAYER", jerseyNumber: 42, position: "Center / Power Forward", yearsAtSchool: "2003-2007", statsNote: "Sophomore • Emerging star • 2x Future National Champion", gamesPlayed: 32, pointsPerGame: 10.0, reboundsPerGame: 6.5, assistsPerGame: 1.0 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Grand Ledge High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 20.0, reboundsPerGame: 11.5, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2003-04", yearLabel: "2003-04 (Freshman)", sortOrder: 201, gamesPlayed: 31, pointsPerGame: 6.5, reboundsPerGame: 5.0, assistsPerGame: 0.8 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2004-05", yearLabel: "2004-05 (Sophomore)", sortOrder: 202, gamesPlayed: 32, pointsPerGame: 10.0, reboundsPerGame: 6.5, assistsPerGame: 1.0 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2005-06", yearLabel: "2005-06 (Champion)", sortOrder: 203, gamesPlayed: 36, pointsPerGame: 11.3, reboundsPerGame: 7.5, assistsPerGame: 1.4 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2006-07", yearLabel: "2006-07 (Champion)", sortOrder: 204, gamesPlayed: 35, pointsPerGame: 13.2, reboundsPerGame: 9.5, assistsPerGame: 1.9, fieldGoalPct: 0.561 },
      
        { level: "PROFESSIONAL", teamName: "Atlanta Hawks", season: "2007-08", yearLabel: "2007-08 (Rookie)", sortOrder: 301, gamesPlayed: 81, minutesPerGame: 31.4, pointsPerGame: 10.1, reboundsPerGame: 9.7, assistsPerGame: 1.5, blocksPerGame: 0.9, fieldGoalPct: 0.499 },
        { level: "PROFESSIONAL", teamName: "Atlanta Hawks", season: "2010-11", yearLabel: "2010-11 (All-Star)", sortOrder: 304, gamesPlayed: 77, minutesPerGame: 34.5, pointsPerGame: 15.3, reboundsPerGame: 9.3, assistsPerGame: 3.2, blocksPerGame: 1.0, fieldGoalPct: 0.557 },
        { level: "PROFESSIONAL", teamName: "Atlanta Hawks", season: "2014-15", yearLabel: "2014-15 (All-Star)", sortOrder: 308, gamesPlayed: 76, minutesPerGame: 31.4, pointsPerGame: 15.2, reboundsPerGame: 7.2, assistsPerGame: 3.2, blocksPerGame: 0.8, fieldGoalPct: 0.538, threePointPct: 0.344 },
        { level: "PROFESSIONAL", teamName: "Boston Celtics", season: "2017-18", yearLabel: "2017-18", sortOrder: 311, gamesPlayed: 72, minutesPerGame: 31.6, pointsPerGame: 12.9, reboundsPerGame: 7.4, assistsPerGame: 4.7, blocksPerGame: 1.1, fieldGoalPct: 0.489, threePointPct: 0.429 },
        { level: "PROFESSIONAL", teamName: "Philadelphia 76ers", season: "2019-20", yearLabel: "2019-20", sortOrder: 313, gamesPlayed: 67, minutesPerGame: 30.2, pointsPerGame: 11.9, reboundsPerGame: 6.8, assistsPerGame: 4.0, blocksPerGame: 0.8, fieldGoalPct: 0.459, threePointPct: 0.350 },
        { level: "PROFESSIONAL", teamName: "Boston Celtics", season: "2022-23", yearLabel: "2022-23", sortOrder: 316, gamesPlayed: 63, minutesPerGame: 26.6, pointsPerGame: 9.8, reboundsPerGame: 6.2, assistsPerGame: 3.0, blocksPerGame: 0.9, fieldGoalPct: 0.548, threePointPct: 0.360 },
        { level: "PROFESSIONAL", teamName: "Boston Celtics", season: "2023-24", yearLabel: "2023-24 (Champion)", sortOrder: 317, gamesPlayed: 67, minutesPerGame: 23.5, pointsPerGame: 8.6, reboundsPerGame: 5.4, assistsPerGame: 2.6, blocksPerGame: 0.6, fieldGoalPct: 0.516, threePointPct: 0.371 }
      ],
      careerEvents: [
        { year: 2006, title: "Won NCAA National Championship", eventType: "CHAMPIONSHIP" },
        { year: 2007, title: "Won back-to-back NCAA Championship; selected #3 overall", eventType: "CHAMPIONSHIP" },
        { year: 2024, title: "Won NBA Championship with Boston Celtics", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "joakim-noah",
      firstName: "Joakim",
      lastName: "Noah",
      birthYear: 1985,
      hometown: "New York, NY",
      highSchool: "Lawrenceville School, Lawrenceville, NJ",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/201149.png",
      bio: "Sophomore center who would become the heart and soul of back-to-back championship teams. Named MOP of both Final Fours.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Philanthropist / Entrepreneur",
        location: "New York, NY",
        statusNote: "Selected #9 overall by Chicago in 2007. 2014 NBA Defensive Player of the Year, one-time All-Star. Now involved in philanthropy through Noah's Arc Foundation. Son of tennis legend Yannick Noah.",
        sourceUrl: "https://en.wikipedia.org/wiki/Joakim_Noah",
      },
      membership: { role: "PLAYER", jerseyNumber: 13, position: "Center", yearsAtSchool: "2003-2007", statsNote: "Sophomore • Growing into dominant role", gamesPlayed: 32, pointsPerGame: 6.5, reboundsPerGame: 5.0, assistsPerGame: 1.0 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Lawrenceville School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 14.8, reboundsPerGame: 9.5, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2004-05", yearLabel: "2004-05 (Sophomore)", sortOrder: 202, gamesPlayed: 32, pointsPerGame: 6.5, reboundsPerGame: 5.0, assistsPerGame: 1.0 },
      
        { level: "PROFESSIONAL", teamName: "Chicago Bulls", season: "2007-08", yearLabel: "2007-08 (Rookie)", sortOrder: 301, gamesPlayed: 82, minutesPerGame: 20.5, pointsPerGame: 6.6, reboundsPerGame: 5.6, assistsPerGame: 1.0, blocksPerGame: 1.0, fieldGoalPct: 0.481 },
        { level: "PROFESSIONAL", teamName: "Chicago Bulls", season: "2010-11", yearLabel: "2010-11", sortOrder: 304, gamesPlayed: 48, minutesPerGame: 30.6, pointsPerGame: 10.7, reboundsPerGame: 10.4, assistsPerGame: 2.2, blocksPerGame: 1.5, fieldGoalPct: 0.504 },
        { level: "PROFESSIONAL", teamName: "Chicago Bulls", season: "2013-14", yearLabel: "2013-14 (All-Star, DPOY)", sortOrder: 307, gamesPlayed: 80, minutesPerGame: 35.0, pointsPerGame: 12.6, reboundsPerGame: 11.3, assistsPerGame: 5.4, blocksPerGame: 1.5, stealsPerGame: 1.2, fieldGoalPct: 0.475 },
        { level: "PROFESSIONAL", teamName: "New York Knicks", season: "2016-17", yearLabel: "2016-17", sortOrder: 310, gamesPlayed: 46, minutesPerGame: 22.1, pointsPerGame: 5.0, reboundsPerGame: 8.8, assistsPerGame: 2.2, blocksPerGame: 0.8, fieldGoalPct: 0.428 }
      ],
      careerEvents: [
        { year: 2007, title: "Selected #9 overall by the Chicago Bulls", eventType: "DRAFT" },
        { year: 2014, title: "Won NBA Defensive Player of the Year", eventType: "AWARD" },
      ],
    },
    {
      slug: "corey-brewer",
      firstName: "Corey",
      lastName: "Brewer",
      birthYear: 1986,
      hometown: "Portland, TN",
      highSchool: "Portland High School, Portland, TN",
      isFeatured: true,
      bio: "Sophomore wing whose relentless energy was becoming a defining feature of this Florida team.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NBA Player / Mentor",
        location: "Portland, TN",
        statusNote: "Selected #7 overall in 2007. Played 13 NBA seasons. Scored 51 points in a game for Houston in 2014. Active in community mentoring.",
        sourceUrl: "https://en.wikipedia.org/wiki/Corey_Brewer",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Small Forward", yearsAtSchool: "2003-2007", statsNote: "Sophomore • Defensive specialist", gamesPlayed: 32, pointsPerGame: 8.5, reboundsPerGame: 4.0, assistsPerGame: 1.5 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Portland High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 17.8, reboundsPerGame: 8.2, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2004-05", yearLabel: "2004-05 (Sophomore)", sortOrder: 202, gamesPlayed: 32, pointsPerGame: 8.5, reboundsPerGame: 4.0, assistsPerGame: 1.5 },
      
        { level: "PROFESSIONAL", teamName: "Minnesota Timberwolves", season: "2007-08", yearLabel: "2007-08 (Rookie)", sortOrder: 301, gamesPlayed: 79, minutesPerGame: 18.6, pointsPerGame: 5.8, reboundsPerGame: 2.1, assistsPerGame: 0.9, stealsPerGame: 1.0, fieldGoalPct: 0.402 },
        { level: "PROFESSIONAL", teamName: "Minnesota Timberwolves", season: "2010-11", yearLabel: "2010-11", sortOrder: 304, gamesPlayed: 82, minutesPerGame: 26.7, pointsPerGame: 10.2, reboundsPerGame: 3.4, assistsPerGame: 1.3, stealsPerGame: 1.6, fieldGoalPct: 0.440 },
        { level: "PROFESSIONAL", teamName: "Denver Nuggets", season: "2011-12", yearLabel: "2011-12", sortOrder: 305, gamesPlayed: 62, minutesPerGame: 27.5, pointsPerGame: 12.1, reboundsPerGame: 3.0, assistsPerGame: 1.3, stealsPerGame: 1.8, fieldGoalPct: 0.456, threePointPct: 0.359 },
        { level: "PROFESSIONAL", teamName: "Houston Rockets", season: "2014-15", yearLabel: "2014-15", sortOrder: 308, gamesPlayed: 76, minutesPerGame: 24.2, pointsPerGame: 11.9, reboundsPerGame: 3.0, assistsPerGame: 0.9, stealsPerGame: 1.4, fieldGoalPct: 0.428, threePointPct: 0.377 }
      ],
      careerEvents: [
        { year: 2007, title: "Selected #7 overall by Minnesota", eventType: "DRAFT" },
      ],
    },
    {
      slug: "taurean-green",
      firstName: "Taurean",
      lastName: "Green",
      birthYear: 1986,
      hometown: "Hayward, CA",
      highSchool: "Mt. Zion Christian Academy, Durham, NC",
      isFeatured: false,
      bio: "Sophomore point guard developing into the floor general for what would become a dynasty.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Basketball Trainer",
        location: "Florida",
        statusNote: "Selected #52 in 2007. Long overseas career. Now involved in basketball training and youth development.",
        sourceUrl: "https://en.wikipedia.org/wiki/Taurean_Green",
      },
      membership: { role: "PLAYER", jerseyNumber: 11, position: "Point Guard", yearsAtSchool: "2003-2007", statsNote: "Sophomore • Floor general", gamesPlayed: 32, pointsPerGame: 7.0, reboundsPerGame: 1.5, assistsPerGame: 3.5 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Mt. Zion Christian Academy", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 15.5, reboundsPerGame: 1.5, assistsPerGame: 6.5 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2004-05", yearLabel: "2004-05 (Sophomore)", sortOrder: 202, gamesPlayed: 32, pointsPerGame: 7.0, reboundsPerGame: 1.5, assistsPerGame: 3.5 },
      
        { level: "PROFESSIONAL", teamName: "Portland Trail Blazers", season: "2007-08", yearLabel: "2007-08 (Rookie)", sortOrder: 301, gamesPlayed: 11, minutesPerGame: 4.7, pointsPerGame: 1.9, reboundsPerGame: 0.3, assistsPerGame: 0.5, fieldGoalPct: 0.370 },
      ],
      careerEvents: [
        { year: 2007, title: "Selected #52 by Portland", eventType: "DRAFT" },
      ],
    },
    {
      slug: "david-lee",
      firstName: "David",
      lastName: "Lee",
      birthYear: 1983,
      hometown: "St. Louis, MO",
      highSchool: "Chaminade College Prep, St. Louis, MO",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/101135.png",
      bio: "A senior captain and the team's best player. Lee averaged 16.0 PPG and 9.5 RPG as a First-team All-SEC selection in his final season.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NBA Player / Businessman",
        location: "St. Louis, MO",
        statusNote: "Selected #30 overall in 2005. Two-time All-Star (2010, 2013). Won 2015 NBA Championship with Warriors. Retired in 2017. Now in real estate and business in St. Louis.",
        sourceUrl: "https://en.wikipedia.org/wiki/David_Lee_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 30, position: "Power Forward", yearsAtSchool: "2001-2005", statsNote: "Senior captain • First-team All-SEC • 16.0 PPG, 9.5 RPG", gamesPlayed: 32, pointsPerGame: 16.0, reboundsPerGame: 9.5, assistsPerGame: 2.0 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Chaminade College Prep", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 29.0, reboundsPerGame: 15.0, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2004-05", yearLabel: "2004-05 (Senior, All-SEC)", sortOrder: 204, gamesPlayed: 32, pointsPerGame: 16.0, reboundsPerGame: 9.5, assistsPerGame: 2.0 },
      
        { level: "PROFESSIONAL", teamName: "New York Knicks", season: "2005-06", yearLabel: "2005-06 (Rookie)", sortOrder: 301, gamesPlayed: 67, minutesPerGame: 19.3, pointsPerGame: 5.6, reboundsPerGame: 5.6, assistsPerGame: 0.8, fieldGoalPct: 0.535 },
        { level: "PROFESSIONAL", teamName: "New York Knicks", season: "2008-09", yearLabel: "2008-09 (All-Star)", sortOrder: 304, gamesPlayed: 81, minutesPerGame: 37.5, pointsPerGame: 20.2, reboundsPerGame: 11.7, assistsPerGame: 3.6, fieldGoalPct: 0.544 },
        { level: "PROFESSIONAL", teamName: "Golden State Warriors", season: "2012-13", yearLabel: "2012-13 (All-Star)", sortOrder: 308, gamesPlayed: 79, minutesPerGame: 30.3, pointsPerGame: 18.5, reboundsPerGame: 11.2, assistsPerGame: 3.5, fieldGoalPct: 0.519 },
        { level: "PROFESSIONAL", teamName: "Golden State Warriors", season: "2014-15", yearLabel: "2014-15 (Champion)", sortOrder: 310, gamesPlayed: 57, minutesPerGame: 17.6, pointsPerGame: 7.9, reboundsPerGame: 5.2, assistsPerGame: 1.3, fieldGoalPct: 0.498 },
        { level: "PROFESSIONAL", teamName: "Dallas / San Antonio", season: "2016-17", yearLabel: "2016-17 (Champion)", sortOrder: 312, gamesPlayed: 79, minutesPerGame: 12.2, pointsPerGame: 3.4, reboundsPerGame: 3.6, assistsPerGame: 0.8, fieldGoalPct: 0.554 },
      ],
      careerEvents: [
        { year: 2005, title: "Selected #30 overall by the New York Knicks", eventType: "DRAFT" },
        { year: 2015, title: "Won NBA Championship with Golden State Warriors", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "matt-walsh",
      firstName: "Matt",
      lastName: "Walsh",
      birthYear: 1982,
      hometown: "St. Petersburg, FL",
      highSchool: "Countryside High School, Clearwater, FL",
      isFeatured: false,
      bio: "A versatile senior forward who was one of the team's top scorers alongside David Lee.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Professional Basketball Player",
        location: "Florida",
        statusNote: "Went undrafted in 2005 but played one season with the Miami Heat (2005-06) before building a long, successful career in European basketball — primarily in Italy's Serie A where he became one of the top American players in the league for nearly a decade.",
        sourceUrl: "https://en.wikipedia.org/wiki/Matt_Walsh_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 44, position: "Forward", yearsAtSchool: "2001-2005", statsNote: "Senior • 15.0 PPG • Versatile scorer", gamesPlayed: 32, pointsPerGame: 15.0, reboundsPerGame: 5.0, assistsPerGame: 2.5 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Countryside High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 27.5, reboundsPerGame: 9.5, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2004-05", yearLabel: "2004-05 (Senior)", sortOrder: 204, gamesPlayed: 32, pointsPerGame: 15.0, reboundsPerGame: 5.0, assistsPerGame: 2.5 },
      
        { level: "PROFESSIONAL", teamName: "Miami Heat", season: "2005-06", yearLabel: "2005-06", sortOrder: 301, gamesPlayed: 3, minutesPerGame: 2.7, pointsPerGame: 0.7, reboundsPerGame: 0.3 },
      ],
      careerEvents: [
        { year: 2005, title: "Went undrafted; signed with Miami Heat", eventType: "SIGNING" },
        { year: 2006, title: "Began long career in Italian Serie A basketball", eventType: "CAREER" },
      ],
    },
    {
      slug: "lee-humphrey",
      firstName: "Lee",
      lastName: "Humphrey",
      birthYear: 1984,
      hometown: "Maryville, TN",
      highSchool: "Maryville High School, Maryville, TN",
      isFeatured: false,
      bio: "One of the most prolific three-point shooters in Florida history. A sophomore who would become a key contributor on both championship teams.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach / Trainer",
        location: "Tennessee",
        statusNote: "After winning back-to-back NCAA titles (2006, 2007), Humphrey went undrafted but played in the NBA Summer League and had a professional career overseas in Europe. One of the greatest three-point shooters in Florida history. Now involved in coaching and basketball programs in Tennessee.",
        sourceUrl: "https://en.wikipedia.org/wiki/Lee_Humphrey",
      },
      membership: { role: "PLAYER", jerseyNumber: 33, position: "Guard", yearsAtSchool: "2003-2007", statsNote: "Sophomore • Elite three-point shooter", gamesPlayed: 32, pointsPerGame: 6.0, reboundsPerGame: 1.5, assistsPerGame: 1.0 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Maryville High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 14.0, reboundsPerGame: 1.5, assistsPerGame: 3.3 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2004-05", yearLabel: "2004-05 (Sophomore)", sortOrder: 202, gamesPlayed: 32, pointsPerGame: 6.0, reboundsPerGame: 1.5, assistsPerGame: 1.0 },
      
        { level: "PROFESSIONAL", teamName: "Orlando Magic / overseas", season: "2007-08", yearLabel: "2007-08", sortOrder: 301, gamesPlayed: 4, minutesPerGame: 2.3, pointsPerGame: 0.5, reboundsPerGame: 0.0, fieldGoalPct: 0.250 },
      ],
      careerEvents: [
        { year: 2006, title: "Won NCAA National Championship", eventType: "CHAMPIONSHIP" },
        { year: 2007, title: "Won back-to-back NCAA Championship", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "chris-richard",
      firstName: "Chris",
      lastName: "Richard",
      birthYear: 1986,
      hometown: "Jackson, MS",
      highSchool: "Provine High School, Jackson, MS",
      isFeatured: false,
      bio: "A freshman big man who would be part of both championship teams before being drafted in 2007.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Sector",
        location: "Southern United States",
        statusNote: "Part of Florida's back-to-back championship teams. Selected #41 overall by Minnesota in the 2007 NBA Draft. Had a brief NBA career before playing overseas. Has transitioned to the private sector.",
        sourceUrl: "https://en.wikipedia.org/wiki/Chris_Richard",
      },
      membership: { role: "PLAYER", jerseyNumber: 24, position: "Forward / Center", yearsAtSchool: "2004-2007", statsNote: "Freshman • 2x Future National Champion", gamesPlayed: 25, pointsPerGame: 3.0, reboundsPerGame: 3.0 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Provine High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 9.5, reboundsPerGame: 6.9, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Florida Gators", season: "2004-05", yearLabel: "2004-05 (Freshman)", sortOrder: 201, gamesPlayed: 25, pointsPerGame: 3.0, reboundsPerGame: 3.0, assistsPerGame: 0.3 },
      ],
      careerEvents: [
        { year: 2007, title: "Selected #41 overall by Minnesota", eventType: "DRAFT" },
      ],
    },
    {
      slug: "billy-donovan",
      firstName: "Billy",
      lastName: "Donovan",
      birthYear: 1965,
      hometown: "Rockville Centre, NY",
      highSchool: "St. Agnes Cathedral High School, Rockville Centre, NY",
      isFeatured: true,
      bio: "Building towards a dynasty — the 2004-05 season was the launch pad for back-to-back championships.",
      status: {
        occupationType: "COACH",
        currentTitle: "NBA Coaching Candidate",
        location: "United States",
        statusNote: "Won back-to-back NCAA championships (2006, 2007) during 19 seasons at Florida (467-186 record). Later coached OKC Thunder (2015-2020) and Chicago Bulls (2020-2023).",
        sourceUrl: "https://en.wikipedia.org/wiki/Billy_Donovan",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "1996-2015", statsNote: "24-8 • SEC Regular Season Champions" },
      careerEvents: [
        { year: 2006, title: "Won NCAA National Championship", eventType: "CHAMPIONSHIP" },
        { year: 2007, title: "Won back-to-back NCAA Championship", eventType: "CHAMPIONSHIP" },
      ],
    },
  ],
};
