import type { TeamSeed } from "./types";

export const floridaStateBasketball2018: TeamSeed = {
  slug: "florida-state-basketball-2018",
  name: "Florida State Seminoles",
  season: "2017-2018",
  sport: "Men's Basketball",
  school: "Florida State University",
  conference: "ACC",
  accomplishment: "Elite Eight (23-12)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/52.png",
  mascotName: "Seminole",
  people: [
    {
      slug: "terance-mann",
      firstName: "Terance",
      lastName: "Mann",
      birthYear: 1996,
      hometown: "Lowell, MA",
      highSchool: "Tilton School, Tilton, NH",
      isFeatured: true,
      bio: "The sophomore wing who was the heart of Florida State's first Elite Eight since 1993. A versatile two-way player who did everything — score, rebound, defend, and lead. Returned for two more seasons before becoming a second-round NBA pick.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward / Guard",
        currentEmployer: "Brooklyn Nets",
        league: "NBA",
        location: "Brooklyn, NY",
        statusNote: "Selected #48 overall by the LA Clippers in 2019, Mann played 6 seasons in Los Angeles and became a fan favorite for his defensive intensity and clutch playoff performances — most famously his 39-point explosion against the Jazz in the 2021 playoffs. He was traded to the Hawks in 2025 and then to the Brooklyn Nets. In April 2025, he was also hired as assistant general manager at his alma mater Florida State under new head coach Luke Loucks, showing his commitment to the program even while still playing in the NBA.",
        sourceUrl: "https://en.wikipedia.org/wiki/Terance_Mann",
      },
      membership: { role: "PLAYER", jerseyNumber: 14, position: "Guard / Forward", yearsAtSchool: "2016-2019", statsNote: "All-around player • 39 pts in NBA playoffs • Elite Eight", gamesPlayed: 35, pointsPerGame: 11.2, reboundsPerGame: 5.8, assistsPerGame: 2.4 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Florida State Seminoles", season: "2017-18", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 35, minutesPerGame: 28.0, pointsPerGame: 11.2, reboundsPerGame: 5.8, assistsPerGame: 2.4, stealsPerGame: 1.2, fieldGoalPct: 0.476 },
        { level: "PROFESSIONAL", teamName: "LA Clippers", season: "2020-21", yearLabel: "2020-21 (39-pt playoff game)", sortOrder: 302, gamesPlayed: 67, pointsPerGame: 7.0, reboundsPerGame: 2.9 },
      ],
      careerEvents: [
        { year: 2018, title: "Led Florida State to first Elite Eight since 1993", eventType: "MILESTONE" },
        { year: 2019, title: "Selected #48 overall by the LA Clippers", eventType: "DRAFT", month: 6, day: 20 },
        { year: 2021, title: "Scored 39 points vs Utah Jazz in Western Conference Semifinals", eventType: "MILESTONE" },
        { year: 2025, title: "Also hired as FSU assistant general manager while still playing NBA", eventType: "CAREER_CHANGE" },
      ],
    },
    {
      slug: "trent-forrest",
      firstName: "Trent",
      lastName: "Forrest",
      birthYear: 1998,
      hometown: "Chipley, FL",
      highSchool: "Chipley High School, Chipley, FL",
      bio: "A freshman point guard from rural north Florida who provided backcourt playmaking. Stayed four years at FSU and became the program's all-time leader in several categories before brief NBA stints.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "G League / Overseas",
        location: "United States",
        statusNote: "After four years at Florida State, Forrest went undrafted but signed with the Utah Jazz and played parts of 3 NBA seasons. He has continued playing in the G League and overseas. The Chipley, FL native became one of the most decorated players in FSU history by the time he graduated.",
        sourceUrl: "https://en.wikipedia.org/wiki/Trent_Forrest",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Point Guard", yearsAtSchool: "2017-2021", statsNote: "Freshman • Small-town FL product • Elite Eight", gamesPlayed: 33, pointsPerGame: 5.5, reboundsPerGame: 2.8, assistsPerGame: 2.1 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Florida State Seminoles", season: "2017-18", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 33, minutesPerGame: 18.0, pointsPerGame: 5.5, reboundsPerGame: 2.8, assistsPerGame: 2.1 },
      ],
      careerEvents: [
        { year: 2018, title: "Reached Elite Eight with Florida State as a freshman", eventType: "MILESTONE" },
      ],
    },
    {
      slug: "mfiondu-kabengele",
      firstName: "Mfiondu",
      lastName: "Kabengele",
      birthYear: 1997,
      hometown: "Burlington, Ontario",
      highSchool: "Hamilton Heights Christian Academy, Chattanooga, TN",
      bio: "A sophomore center from Canada whose shot-blocking and energy off the bench were critical during the Elite Eight run. His uncle Dikembe Mutombo was an NBA Hall of Famer.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "G League / Overseas",
        location: "United States",
        statusNote: "Kabengele stayed one more year at FSU and won the ACC Sixth Man of the Year award as a junior before being selected #27 overall by the Brooklyn Nets (traded to the Clippers) in 2019. He played parts of 3 NBA seasons with the Clippers and Cavaliers and has continued his career in the G League and overseas. His uncle was NBA legend Dikembe Mutombo.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mfiondu_Kabengele",
      },
      membership: { role: "PLAYER", jerseyNumber: 13, position: "Center / Power Forward", yearsAtSchool: "2016-2019", statsNote: "Mutombo's nephew • Future #27 pick • Elite Eight", gamesPlayed: 35, pointsPerGame: 7.5, reboundsPerGame: 4.0, assistsPerGame: 0.3 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Florida State Seminoles", season: "2017-18", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 35, minutesPerGame: 16.0, pointsPerGame: 7.5, reboundsPerGame: 4.0, blocksPerGame: 0.8, fieldGoalPct: 0.515 },
      ],
      careerEvents: [
        { year: 2018, title: "Reached Elite Eight with Florida State", eventType: "MILESTONE" },
        { year: 2019, title: "Won ACC Sixth Man of the Year", eventType: "AWARD" },
        { year: 2019, title: "Selected #27 overall by the Brooklyn Nets (traded to Clippers)", eventType: "DRAFT" },
      ],
    },
    {
      slug: "braian-angola",
      firstName: "Braian",
      lastName: "Angola",
      birthYear: 1996,
      hometown: "Cordoba, Argentina",
      highSchool: "St. Thomas More School, Oakdale, CT",
      bio: "The junior guard from Argentina whose three-point shooting and toughness provided perimeter scoring. Represented Argentina internationally and embodied FSU's international recruiting pipeline.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "Overseas",
        location: "Argentina",
        statusNote: "After graduating from FSU, Angola played professionally in Argentina's Liga Nacional and represented the Argentine national team. He embodies FSU's longstanding tradition of developing international talent under Leonard Hamilton.",
        sourceUrl: "https://seminoles.com/sports/mens-basketball/roster/braian-angola/",
      },
      membership: { role: "PLAYER", jerseyNumber: 11, position: "Guard", yearsAtSchool: "2015-2019", statsNote: "Argentine guard • International pipeline • Elite Eight", gamesPlayed: 33, pointsPerGame: 9.2, reboundsPerGame: 2.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Florida State Seminoles", season: "2017-18", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 33, minutesPerGame: 24.0, pointsPerGame: 9.2, reboundsPerGame: 2.5, threePointPct: 0.365 },
      ],
      careerEvents: [
        { year: 2018, title: "Reached Elite Eight with Florida State", eventType: "MILESTONE" },
      ],
    },
    {
      slug: "phil-cofer",
      firstName: "Phil",
      lastName: "Cofer",
      birthYear: 1995,
      hometown: "Tallahassee, FL",
      highSchool: "Lincoln High School, Tallahassee, FL",
      bio: "A junior forward and son of former NFL linebacker Mike Cofer. Local Tallahassee product who provided interior scoring and toughness. His father's passing during the 2019 NCAA Tournament was one of the most emotional moments in FSU basketball history.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Professional",
        location: "Tallahassee, FL",
        statusNote: "After four years at FSU, Cofer went undrafted and played in the G League briefly. He returned to Tallahassee and has been involved in community work. His father Mike Cofer, a former NFL player, passed away during the 2019 NCAA Tournament — Phil learned of his father's death after FSU's second-round win and chose to remain with the team. The moment of his teammates carrying him off the court became one of the most emotional images in college basketball that year.",
        sourceUrl: "https://seminoles.com/sports/mens-basketball/roster/phil-cofer/",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Power Forward", yearsAtSchool: "2015-2019", statsNote: "Local Tallahassee product • Son of NFL player • Elite Eight", gamesPlayed: 34, pointsPerGame: 8.0, reboundsPerGame: 4.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Florida State Seminoles", season: "2017-18", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 34, minutesPerGame: 21.0, pointsPerGame: 8.0, reboundsPerGame: 4.2, fieldGoalPct: 0.460 },
      ],
      careerEvents: [
        { year: 2018, title: "Reached Elite Eight with Florida State", eventType: "MILESTONE" },
        { year: 2019, title: "Father Mike Cofer passed away during NCAA Tournament — chose to stay with team", eventType: "MILESTONE" },
      ],
    },
    {
      slug: "pj-savoy",
      firstName: "PJ",
      lastName: "Savoy",
      birthYear: 1996,
      hometown: "Jacksonville, FL",
      highSchool: "Bolles School, Jacksonville, FL",
      bio: "A sophomore guard whose three-point shooting provided spark off the bench. Hit key threes during the tournament run that fueled FSU's Elite Eight push.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Professional",
        location: "Florida",
        statusNote: "After his time at FSU, Savoy played professional basketball briefly before transitioning to a career off the court. He was known for his deep range and ability to catch fire from three-point territory.",
        sourceUrl: "https://seminoles.com/sports/mens-basketball/roster/pj-savoy/",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Guard", yearsAtSchool: "2016-2020", statsNote: "Sophomore • Three-point shooter • Elite Eight", gamesPlayed: 33, pointsPerGame: 6.5, reboundsPerGame: 1.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Florida State Seminoles", season: "2017-18", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 33, minutesPerGame: 16.0, pointsPerGame: 6.5, threePointPct: 0.385 },
      ],
      careerEvents: [
        { year: 2018, title: "Reached Elite Eight with Florida State", eventType: "MILESTONE" },
      ],
    },
    {
      slug: "leonard-hamilton",
      firstName: "Leonard",
      lastName: "Hamilton",
      birthYear: 1948,
      hometown: "Gastonia, NC",
      highSchool: "Highland High School, Gastonia, NC",
      isFeatured: true,
      bio: "The legendary head coach who led Florida State to their first Elite Eight since 1993 — proving that the Seminoles could compete with the traditional ACC basketball powers. Known for developing NBA talent and maintaining one of the deepest rosters in college basketball.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Head Coach Emeritus",
        currentEmployer: "Florida State University (Emeritus)",
        location: "Tallahassee, FL",
        statusNote: "Leonard Hamilton coached Florida State for 23 seasons (2002-2025), compiling over 400 wins and establishing the Seminoles as a legitimate ACC basketball power. He reached the Elite Eight in 2018, the Sweet 16 in 2019, and consistently produced NBA talent including Jonathan Isaac (#6 pick), Malik Beasley (#19 pick), Terance Mann, Devin Vassell (#11 pick), Patrick Williams (#4 pick), and Scottie Barnes (#4 pick). He was inducted into the NC Sports Hall of Fame in 2026 alongside Tyler Hansbrough. Hamilton resigned after the 2024-25 season at age 76.",
        sourceUrl: "https://en.wikipedia.org/wiki/Leonard_Hamilton",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2002-2025", statsNote: "23 seasons • 400+ wins • Elite Eight 2018 • Prolific NBA talent developer" },
      seasonStats: [
        { level: "COACHING", teamName: "Florida State Seminoles", season: "2017-18", yearLabel: "2017-18", sortOrder: 216, wins: 23, losses: 12, tournamentResult: "Elite Eight" },
      ],
      careerEvents: [
        { year: 2018, title: "Led FSU to first Elite Eight since 1993", eventType: "MILESTONE" },
        { year: 2025, title: "Resigned after 23 seasons at Florida State", eventType: "RETIREMENT" },
        { year: 2026, title: "Inducted into NC Sports Hall of Fame", eventType: "AWARD" },
      ],
    },
  ],
};
