import type { TeamSeed } from "./types";

export const georgiaTechBasketball2010: TeamSeed = {
  slug: "georgia-tech-basketball-2010",
  name: "Georgia Tech Yellow Jackets",
  season: "2009-2010",
  sport: "Men's Basketball",
  school: "Georgia Institute of Technology",
  conference: "ACC",
  accomplishment: "NCAA Tournament (23-9)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/59.png",
  mascotName: "Yellow Jacket",
  people: [
    {
      slug: "derrick-favors",
      firstName: "Derrick",
      lastName: "Favors",
      birthYear: 1991,
      hometown: "Atlanta, GA",
      highSchool: "South Atlanta High School, Atlanta, GA",
      isFeatured: true,
      bio: "The dominant freshman center who was the #3 overall pick in the 2010 NBA Draft after just one season at Georgia Tech. His combination of size, athleticism, and motor made him the most physically gifted player in the ACC as a freshman.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NBA Player",
        location: "Atlanta, GA",
        statusNote: "Selected #3 overall by the New Jersey Nets in 2010, Favors was traded to the Utah Jazz where he spent 8 seasons and became one of the franchise's most reliable frontcourt players. He also played for the Pelicans, Thunder, and Rockets over a 13-year NBA career, averaging 11.1 PPG and 6.6 RPG. After his NBA career ended, he played briefly in the G League with the Windy City Bulls before retiring. Known for his consistency and blue-collar work ethic throughout his NBA career.",
        sourceUrl: "https://en.wikipedia.org/wiki/Derrick_Favors",
      },
      membership: { role: "PLAYER", jerseyNumber: 14, position: "Center / Power Forward", yearsAtSchool: "2009-2010", statsNote: "#3 pick • One-and-done • 13-year NBA career", gamesPlayed: 32, pointsPerGame: 12.3, reboundsPerGame: 8.5, assistsPerGame: 0.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Georgia Tech Yellow Jackets", season: "2009-10", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 32, minutesPerGame: 27.8, pointsPerGame: 12.3, reboundsPerGame: 8.5, blocksPerGame: 1.7, fieldGoalPct: 0.531 },
        { level: "PROFESSIONAL", teamName: "Utah Jazz", season: "2015-16", yearLabel: "2015-16 (Best season)", sortOrder: 306, gamesPlayed: 62, pointsPerGame: 16.4, reboundsPerGame: 8.1 },
      ],
      careerEvents: [
        { year: 2010, title: "Selected #3 overall by the New Jersey Nets", eventType: "DRAFT", month: 6, day: 24 },
        { year: 2010, title: "Traded to the Utah Jazz", eventType: "TRADE" },
      ],
    },
    {
      slug: "iman-shumpert",
      firstName: "Iman",
      lastName: "Shumpert",
      birthYear: 1990,
      hometown: "Chicago, IL",
      highSchool: "Oak Park and River Forest High School, Oak Park, IL",
      isFeatured: true,
      bio: "The sophomore guard who emerged as Georgia Tech's most versatile perimeter player. Stayed one more year before being selected #17 overall by the Knicks in 2011. Won an NBA championship with the Cavaliers in 2016 and later won Dancing with the Stars in 2021.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Media Personality / Entrepreneur",
        location: "Los Angeles, CA",
        statusNote: "Selected #17 overall by the New York Knicks in 2011, Shumpert played 9 NBA seasons with the Knicks, Cavaliers, Kings, Rockets, and Nets, winning the 2016 NBA Championship with Cleveland alongside LeBron James and Kyrie Irving. After retiring from basketball, he won Season 30 of Dancing with the Stars in 2021, becoming the first NBA player to win the show. He has since become a media personality and entrepreneur in Los Angeles. He was formerly married to recording artist Teyana Taylor.",
        sourceUrl: "https://en.wikipedia.org/wiki/Iman_Shumpert",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Guard", yearsAtSchool: "2008-2011", statsNote: "#17 pick • 2016 NBA Champion • DWTS winner", gamesPlayed: 32, pointsPerGame: 12.1, reboundsPerGame: 5.3, assistsPerGame: 3.0 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Georgia Tech Yellow Jackets", season: "2009-10", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 32, minutesPerGame: 33.5, pointsPerGame: 12.1, reboundsPerGame: 5.3, assistsPerGame: 3.0, stealsPerGame: 2.0, fieldGoalPct: 0.410 },
      ],
      careerEvents: [
        { year: 2011, title: "Selected #17 overall by the New York Knicks", eventType: "DRAFT" },
        { year: 2016, title: "Won NBA Championship with Cleveland Cavaliers", eventType: "CHAMPIONSHIP" },
        { year: 2021, title: "Won Season 30 of Dancing with the Stars", eventType: "AWARD" },
      ],
    },
    {
      slug: "gani-lawal",
      firstName: "Gani",
      lastName: "Lawal",
      birthYear: 1988,
      hometown: "Dallas, TX",
      highSchool: "Greenhill School, Addison, TX",
      bio: "The junior forward of Nigerian descent who was Georgia Tech's most experienced frontcourt player alongside freshman Favors. A bruising rebounder and post scorer who was selected #46 overall by the Suns.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "Overseas",
        location: "South America",
        statusNote: "Selected #46 overall by the Phoenix Suns in 2010, Lawal played briefly in the NBA before building an extensive international career spanning over a decade in Turkey, France, Japan, Venezuela, and Argentina. He has played for the Nigerian national team in FIBA competition. Most recently played for Trotamundos in Venezuela's SuperLiga.",
        sourceUrl: "https://en.wikipedia.org/wiki/Gani_Lawal",
      },
      membership: { role: "PLAYER", jerseyNumber: 31, position: "Power Forward / Center", yearsAtSchool: "2007-2010", statsNote: "#46 pick • Nigerian national team • Frontcourt anchor", gamesPlayed: 32, pointsPerGame: 12.5, reboundsPerGame: 8.3 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Georgia Tech Yellow Jackets", season: "2009-10", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 32, minutesPerGame: 30.0, pointsPerGame: 12.5, reboundsPerGame: 8.3, fieldGoalPct: 0.505 },
      ],
      careerEvents: [
        { year: 2010, title: "Selected #46 overall by the Phoenix Suns", eventType: "DRAFT", month: 6, day: 24 },
      ],
    },
    {
      slug: "mfon-udofia",
      firstName: "Mfon",
      lastName: "Udofia",
      birthYear: 1989,
      hometown: "Stone Mountain, GA",
      highSchool: "Redan High School, Stone Mountain, GA",
      bio: "A sophomore guard from suburban Atlanta who provided backcourt scoring and playmaking. His local roots made him a fan favorite at McCamish Pavilion.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Professional",
        location: "Atlanta, GA",
        statusNote: "After graduating from Georgia Tech, Udofia played professional basketball overseas in Europe before returning to the Atlanta area. He has been involved in basketball training and youth development in the metro Atlanta community.",
        sourceUrl: "https://ramblinwreck.com/roster/mfon-udofia/",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Guard", yearsAtSchool: "2008-2013", statsNote: "Sophomore • Local GA product", gamesPlayed: 32, pointsPerGame: 9.5, reboundsPerGame: 2.3, assistsPerGame: 3.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Georgia Tech Yellow Jackets", season: "2009-10", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 32, minutesPerGame: 26.0, pointsPerGame: 9.5, assistsPerGame: 3.2 },
      ],
      careerEvents: [],
    },
    {
      slug: "maurice-miller-gt",
      firstName: "Maurice",
      lastName: "Miller",
      birthYear: 1988,
      hometown: "Smyrna, GA",
      highSchool: "Campbell High School, Smyrna, GA",
      bio: "A junior guard who provided veteran leadership and perimeter defense. Another local Atlanta-area product on a team with strong Georgia roots.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Atlanta, GA",
        statusNote: "After graduating from Georgia Tech, Miller returned to the Atlanta metro area. He has been involved in youth basketball and community programs in the Smyrna/Atlanta area.",
        sourceUrl: "https://ramblinwreck.com/roster/maurice-miller/",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Guard", yearsAtSchool: "2007-2011", statsNote: "Junior • Local GA product", gamesPlayed: 30, pointsPerGame: 5.8, reboundsPerGame: 2.0 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Georgia Tech Yellow Jackets", season: "2009-10", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 30, minutesPerGame: 18.0, pointsPerGame: 5.8 },
      ],
      careerEvents: [],
    },
    {
      slug: "daniel-miller-gt",
      firstName: "Daniel",
      lastName: "Miller",
      birthYear: 1990,
      hometown: "Tampa, FL",
      highSchool: "Wharton High School, Tampa, FL",
      bio: "A freshman center who provided rim protection and interior depth behind Favors and Lawal. His shot-blocking ability gave Georgia Tech frontcourt versatility.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Professional",
        location: "Florida",
        statusNote: "Miller stayed four years at Georgia Tech and became a key interior player by his senior season. After graduating, he played professional basketball overseas before transitioning to a career off the court.",
        sourceUrl: "https://ramblinwreck.com/roster/daniel-miller/",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Center", yearsAtSchool: "2009-2014", statsNote: "Freshman reserve center", gamesPlayed: 28, pointsPerGame: 3.2, reboundsPerGame: 2.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Georgia Tech Yellow Jackets", season: "2009-10", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 28, minutesPerGame: 12.0, pointsPerGame: 3.2, reboundsPerGame: 2.8 },
      ],
      careerEvents: [],
    },
    {
      slug: "paul-hewitt",
      firstName: "Paul",
      lastName: "Hewitt",
      birthYear: 1963,
      hometown: "New York, NY",
      highSchool: "St. Bernard's School, New York, NY",
      isFeatured: true,
      bio: "Head coach who led Georgia Tech during the Favors/Shumpert era. Previously coached the Yellow Jackets to the 2004 national championship game, making him one of only a few coaches to take Georgia Tech deep in the NCAA Tournament.",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Coach",
        location: "United States",
        statusNote: "Hewitt coached Georgia Tech for 11 seasons (2000-2011), leading the program to the 2004 national championship game. He was fired after the 2010-11 season and later coached at George Mason (2011-2015). After his head coaching career, he has been involved in coaching at various levels and has served as an assistant and advisor. He led Georgia Tech to the 2004 national title game — the school's only championship game appearance since 1990.",
        sourceUrl: "https://en.wikipedia.org/wiki/Paul_Hewitt",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2000-2011", statsNote: "2004 National Championship Game • 11 seasons" },
      seasonStats: [
        { level: "COACHING", teamName: "Georgia Tech Yellow Jackets", season: "2009-10", yearLabel: "2009-10", sortOrder: 210, wins: 23, losses: 9, tournamentResult: "NCAA Tournament" },
      ],
      careerEvents: [
        { year: 2004, title: "Led Georgia Tech to the national championship game", eventType: "MILESTONE" },
        { year: 2011, title: "Fired after 11 seasons at Georgia Tech", eventType: "CAREER_CHANGE" },
      ],
    },
  ],
};
