import type { TeamSeed } from "./types";

export const kentuckyBasketball2011: TeamSeed = {
  slug: "kentucky-basketball-2011",
  name: "Kentucky Wildcats",
  season: "2010-2011",
  sport: "Men's Basketball",
  school: "University of Kentucky",
  conference: "SEC",
  accomplishment: "Final Four (29-9) — lost to UConn",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png",
  mascotName: "Wildcat",
  people: [
    {
      slug: "brandon-knight",
      firstName: "Brandon",
      lastName: "Knight",
      birthYear: 1991,
      hometown: "Coral Springs, FL",
      highSchool: "Pine Crest School, Fort Lauderdale, FL",
      bio: "The point guard who hit the game-winning shot against Princeton in the first round and led Kentucky to the Final Four. The #8 overall pick in 2011.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NBA Player",
        location: "Miami, FL",
        statusNote: "Played 8 NBA seasons with the Pistons, Bucks, Suns, Rockets, Cavaliers, and Mavericks. Retired from the NBA around 2021 after injuries slowed his career. Was known as an academic star who delayed his NBA career to maintain his GPA.",
        sourceUrl: "https://en.wikipedia.org/wiki/Brandon_Knight_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Point Guard", yearsAtSchool: "2010-2011", statsNote: "Final Four • #8 overall pick", gamesPlayed: 38, pointsPerGame: 17.3, reboundsPerGame: 4.1, assistsPerGame: 4.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2010-11", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 38, pointsPerGame: 17.3, assistsPerGame: 4.2 },
        { level: "PROFESSIONAL", teamName: "Detroit Pistons", season: "2011-12", yearLabel: "2011-12 (Rookie)", sortOrder: 301, gamesPlayed: 66, pointsPerGame: 12.8 },
      ],
      careerEvents: [
        { year: 2011, title: "Hit game-winning shot vs Princeton in NCAA Tournament", eventType: "AWARD" },
        { year: 2011, title: "Selected #8 overall by the Detroit Pistons", eventType: "DRAFT" },
      ],
    },
    {
      slug: "terrence-jones",
      firstName: "Terrence",
      lastName: "Jones",
      birthYear: 1992,
      hometown: "Portland, OR",
      highSchool: "Jefferson High School, Portland, OR",
      bio: "A versatile freshman forward who averaged 15.7 PPG. Would return for his sophomore year and win a national championship.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Overseas",
        league: "International",
        location: "Europe / Asia",
        statusNote: "Played 6 NBA seasons before moving to international leagues. Has played in China and the Philippines in recent years.",
        sourceUrl: "https://en.wikipedia.org/wiki/Terrence_Jones",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Power Forward", yearsAtSchool: "2010-2012", statsNote: "Final Four • Future NCAA Champion", gamesPlayed: 38, pointsPerGame: 15.7, reboundsPerGame: 8.8, assistsPerGame: 1.3 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2010-11", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 38, pointsPerGame: 15.7, reboundsPerGame: 8.8 },
      ],
      careerEvents: [],
    },
    {
      slug: "doron-lamb",
      firstName: "Doron",
      lastName: "Lamb",
      birthYear: 1991,
      hometown: "Queens, NY",
      highSchool: "Oak Hill Academy, Mouth of Wilson, VA",
      bio: "A sharpshooting freshman guard from Oak Hill Academy who added scoring punch off the bench.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Professional Athlete",
        location: "New York, NY",
        statusNote: "Selected #42 by the Milwaukee Bucks in 2012. Played briefly in the NBA before a lengthy overseas career in Israel, Russia, Turkey, and China.",
        sourceUrl: "https://en.wikipedia.org/wiki/Doron_Lamb",
      },
      membership: { role: "PLAYER", jerseyNumber: 20, position: "Shooting Guard", yearsAtSchool: "2010-2012", statsNote: "Final Four • Future NCAA Champion", gamesPlayed: 38, pointsPerGame: 12.3, reboundsPerGame: 2.5, assistsPerGame: 1.1 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2010-11", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 38, pointsPerGame: 12.3 },
      ],
      careerEvents: [],
    },
    {
      slug: "deandre-liggins",
      firstName: "DeAndre",
      lastName: "Liggins",
      birthYear: 1988,
      hometown: "Chicago, IL",
      highSchool: "Findlay College Prep, Henderson, NV",
      bio: "A junior defensive stopper who was SEC Defensive Player of the Year.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Overseas",
        league: "International",
        location: "Various",
        statusNote: "Selected #53 by Orlando in 2011. Played briefly in the NBA and has spent most of his career in the G League and international leagues.",
        sourceUrl: "https://en.wikipedia.org/wiki/DeAndre_Liggins",
      },
      membership: { role: "PLAYER", jerseyNumber: 34, position: "Guard", yearsAtSchool: "2008-2011", statsNote: "SEC DPOY • Final Four", gamesPlayed: 38, pointsPerGame: 8.6, reboundsPerGame: 4.0, assistsPerGame: 2.7 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2010-11", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 38, pointsPerGame: 8.6 },
      ],
      careerEvents: [
        { year: 2011, title: "Named SEC Defensive Player of the Year", eventType: "AWARD" },
        { year: 2011, title: "Selected #53 overall by the Orlando Magic", eventType: "DRAFT" },
      ],
    },
    {
      slug: "darius-miller",
      firstName: "Darius",
      lastName: "Miller",
      birthYear: 1990,
      hometown: "Maysville, KY",
      highSchool: "Mason County High School, Maysville, KY",
      bio: "The Kentucky native junior provided consistent veteran contributions and would win a title the following year.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Overseas",
        league: "International",
        location: "Europe",
        statusNote: "Played parts of 5 NBA seasons with the New Orleans Pelicans, with extended stints overseas in Germany.",
        sourceUrl: "https://en.wikipedia.org/wiki/Darius_Miller",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Small Forward", yearsAtSchool: "2008-2012", statsNote: "Kentucky native • Future NCAA Champion", gamesPlayed: 38, pointsPerGame: 7.8, reboundsPerGame: 3.3, assistsPerGame: 1.4 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2010-11", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 38, pointsPerGame: 7.8 },
      ],
      careerEvents: [],
    },
    {
      slug: "josh-harrellson",
      firstName: "Josh",
      lastName: "Harrellson",
      birthYear: 1989,
      hometown: "St. Charles, MO",
      highSchool: "Francis Howell North HS, St. Charles, MO",
      bio: "The senior cult hero 'Jorts' stepped into a starting role after Daniel Orton's departure and averaged 7.6 rebounds. Had a breakout Sweet 16 vs Ohio State.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Professional Athlete",
        location: "St. Louis, MO",
        statusNote: "Selected #45 overall by the New Orleans Hornets (traded to Knicks). Played briefly in the NBA for the Knicks, Heat, and Pistons. Famous for his jean shorts and 'Jorts' nickname.",
        sourceUrl: "https://en.wikipedia.org/wiki/Josh_Harrellson",
      },
      membership: { role: "PLAYER", jerseyNumber: 55, position: "Center", yearsAtSchool: "2009-2011", statsNote: "'Jorts' • Final Four", gamesPlayed: 38, pointsPerGame: 7.6, reboundsPerGame: 8.8, assistsPerGame: 0.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2010-11", yearLabel: "Senior", sortOrder: 204, gamesPlayed: 38, pointsPerGame: 7.6, reboundsPerGame: 8.8 },
      ],
      careerEvents: [
        { year: 2011, title: "Selected #45 overall by New Orleans Hornets (traded to Knicks)", eventType: "DRAFT" },
      ],
    },
    {
      slug: "eloy-vargas",
      firstName: "Eloy",
      lastName: "Vargas",
      birthYear: 1988,
      hometown: "Bani, Dominican Republic",
      highSchool: "Notre Dame Preparatory, Fitchburg, MA",
      bio: "A Florida transfer center from the Dominican Republic who provided frontcourt depth.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Professional Athlete",
        location: "Santo Domingo, Dominican Republic",
        statusNote: "After Kentucky, Vargas played professionally in Spain (LEB Oro) and other Latin American leagues. Now involved with Dominican basketball.",
        sourceUrl: "https://www.basketball-reference.com/cbb/players/eloy-vargas-1.html",
      },
      membership: { role: "PLAYER", jerseyNumber: 30, position: "Center", yearsAtSchool: "2010-2013", statsNote: "Florida transfer", gamesPlayed: 22, pointsPerGame: 1.1, reboundsPerGame: 1.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2010-11", yearLabel: "Sophomore (transfer)", sortOrder: 202, gamesPlayed: 22, pointsPerGame: 1.1 },
      ],
      careerEvents: [],
    },
    {
      slug: "stacey-poole-jr",
      firstName: "Stacey",
      lastName: "Poole Jr.",
      birthYear: 1991,
      hometown: "Jacksonville, FL",
      highSchool: "Arlington Country Day School, Jacksonville, FL",
      bio: "A freshman guard who transferred to Georgia Tech after the season.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Jacksonville, FL",
        statusNote: "After transferring to Georgia Tech, Poole finished his college career. Has worked professionally after his basketball career.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/stacey-poole-jr/",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Guard", yearsAtSchool: "2010-2011", statsNote: "Transferred to Georgia Tech", gamesPlayed: 27, pointsPerGame: 1.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2010-11", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 27, pointsPerGame: 1.2 },
      ],
      careerEvents: [
        { year: 2011, title: "Transferred to Georgia Tech", eventType: "CAREER" },
      ],
    },
    {
      slug: "jon-hood",
      firstName: "Jon",
      lastName: "Hood",
      birthYear: 1990,
      hometown: "Madisonville, KY",
      highSchool: "Madisonville North Hopkins HS, Madisonville, KY",
      bio: "A sophomore Kentucky native walk-on.",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Coach",
        currentEmployer: "Kentucky High School",
        location: "Kentucky",
        statusNote: "After his Kentucky career, Hood has coached at the high school level in Kentucky.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jon_Hood",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Guard", yearsAtSchool: "2009-2014", statsNote: "Sophomore walk-on • Final Four", gamesPlayed: 16 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2010-11", yearLabel: "Sophomore (walk-on)", sortOrder: 202, gamesPlayed: 16 },
      ],
      careerEvents: [],
    },
    {
      slug: "jarrod-polson",
      firstName: "Jarrod",
      lastName: "Polson",
      birthYear: 1991,
      hometown: "Nicholasville, KY",
      highSchool: "West Jessamine High School, Nicholasville, KY",
      bio: "A freshman Kentucky native walk-on guard.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Nicholasville, KY",
        statusNote: "After graduating from Kentucky, Polson returned to work in the local area.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/jarrod-polson/",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Guard", yearsAtSchool: "2010-2014", statsNote: "Freshman walk-on • Kentucky native", gamesPlayed: 7 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2010-11", yearLabel: "Freshman (walk-on)", sortOrder: 201, gamesPlayed: 7 },
      ],
      careerEvents: [],
    },
    {
      slug: "eric-lindsey",
      firstName: "Eric",
      lastName: "Lindsey",
      birthYear: 1992,
      hometown: "Lexington, KY",
      highSchool: "Henry Clay High School, Lexington, KY",
      bio: "A Lexington native freshman walk-on.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Lexington, KY",
        statusNote: "Lexington native who walked on at Kentucky. After leaving the program, has worked professionally in the Lexington area.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/eric-lindsey/",
      },
      membership: { role: "PLAYER", jerseyNumber: 13, position: "Guard", yearsAtSchool: "2010-2012", statsNote: "Freshman walk-on", gamesPlayed: 8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2010-11", yearLabel: "Freshman (walk-on)", sortOrder: 201, gamesPlayed: 8 },
      ],
      careerEvents: [],
    },
    {
      slug: "brian-long",
      firstName: "Brian",
      lastName: "Long",
      birthYear: 1992,
      hometown: "Lexington, KY",
      highSchool: "Lexington Christian Academy, Lexington, KY",
      bio: "A freshman Lexington native walk-on forward.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Business Professional",
        location: "Lexington, KY",
        statusNote: "Kentucky native walk-on who has worked in business in the Lexington area.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/brian-long/",
      },
      membership: { role: "PLAYER", jerseyNumber: 34, position: "Forward", yearsAtSchool: "2010-2014", statsNote: "Freshman walk-on", gamesPlayed: 7 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2010-11", yearLabel: "Freshman (walk-on)", sortOrder: 201, gamesPlayed: 7 },
      ],
      careerEvents: [],
    },
    {
      slug: "sam-malone",
      firstName: "Sam",
      lastName: "Malone",
      birthYear: 1991,
      hometown: "Louisiana",
      highSchool: "Ruston High School, Ruston, LA",
      bio: "A freshman walk-on and son of NBA Hall of Famer Karl Malone.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Louisiana",
        statusNote: "Son of NBA legend Karl Malone. Walked on at Kentucky before eventually working in Louisiana.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/sam-malone/",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Guard", yearsAtSchool: "2010-2013", statsNote: "Son of Karl Malone • Walk-on", gamesPlayed: 9 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2010-11", yearLabel: "Freshman (walk-on)", sortOrder: 201, gamesPlayed: 9 },
      ],
      careerEvents: [],
    },
    {
      slug: "enes-kanter-kentucky",
      firstName: "Enes",
      lastName: "Kanter",
      birthYear: 1992,
      hometown: "Zurich, Switzerland",
      highSchool: "Stoneridge Preparatory School, Simi Valley, CA",
      bio: "The Turkish big man was ruled permanently ineligible by the NCAA in 2010 for accepting money from his Turkish pro club and never played a game at Kentucky.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NBA Player / Activist",
        location: "New York, NY",
        statusNote: "Selected #3 overall by the Utah Jazz in the 2011 NBA Draft despite never playing a college game. Played 11 NBA seasons with the Jazz, Thunder, Knicks, Trail Blazers, Celtics, and Rockets. Became an outspoken political activist and critic of the Turkish government, legally changing his name to Enes Kanter Freedom.",
        sourceUrl: "https://en.wikipedia.org/wiki/Enes_Kanter_Freedom",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Center", yearsAtSchool: "2010-2011", statsNote: "Ruled ineligible by NCAA • Never played", gamesPlayed: 0 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2010-11", yearLabel: "Freshman (ineligible)", sortOrder: 201, gamesPlayed: 0 },
      ],
      careerEvents: [
        { year: 2011, title: "Selected #3 overall by the Utah Jazz", eventType: "DRAFT" },
      ],
    },
    {
      slug: "orlando-antigua",
      firstName: "Orlando",
      lastName: "Antigua",
      birthYear: 1975,
      hometown: "New York, NY",
      highSchool: "George Washington High School, New York, NY",
      bio: "Dominican-American assistant who followed Calipari from Memphis. Top recruiter, especially with international talent. First Dominican-born D1 coach.",
      status: {
        occupationType: "COACH",
        currentTitle: "Associate Head Coach",
        currentEmployer: "University of Illinois",
        location: "Champaign, IL",
        statusNote: "Antigua was a Kentucky assistant (2009-2014, 2021-2024), sandwiching stints as South Florida HC and Illinois associate HC. After Calipari left for Arkansas in 2024, Antigua returned to Illinois under Brad Underwood.",
        sourceUrl: "https://en.wikipedia.org/wiki/Orlando_Antigua",
      },
      membership: { role: "ASSISTANT_COACH", position: "Assistant Coach", yearsAtSchool: "2009-2014" },
      careerEvents: [],
    },
    {
      slug: "kenny-payne",
      firstName: "Kenny",
      lastName: "Payne",
      birthYear: 1966,
      hometown: "Louisville, KY",
      highSchool: "Shawnee High School, Louisville, KY",
      bio: "Kentucky's primary big-man developer for a decade. Former NBA player and Louisville native. His post coaching was key to multiple lottery picks.",
      status: {
        occupationType: "COACH",
        currentTitle: "Associate Head Coach",
        currentEmployer: "University of Arkansas",
        location: "Fayetteville, AR",
        statusNote: "After 10 years as Kentucky assistant (2010-2020), Payne became Louisville HC but was fired in 2024 after going 12-52. He reunited with Calipari at Arkansas as associate HC.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kenny_Payne",
      },
      membership: { role: "ASSISTANT_COACH", position: "Associate Head Coach", yearsAtSchool: "2010-2020" },
      careerEvents: [],
    },
    {
      slug: "john-calipari",
      firstName: "John",
      lastName: "Calipari",
      birthYear: 1959,
      hometown: "Moon Township, PA",
      highSchool: "Moon Area High School, Moon Township, PA",
      bio: "Coached Kentucky to the Final Four in his second year with a much younger, less-heralded roster than his first Elite Eight team.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "University of Arkansas",
        league: "SEC",
        location: "Fayetteville, AR",
        statusNote: "Left Kentucky for Arkansas in April 2024 on a 5-year, $35M deal after 15 seasons at UK.",
        sourceUrl: "https://en.wikipedia.org/wiki/John_Calipari",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2024", statsNote: "29-9 • Final Four" },
      careerEvents: [],
    },
  ],
};
