import type { TeamSeed } from "./types";

export const kentuckyBasketball2016: TeamSeed = {
  slug: "kentucky-basketball-2016",
  name: "Kentucky Wildcats",
  season: "2015-2016",
  sport: "Men's Basketball",
  school: "University of Kentucky",
  conference: "SEC",
  accomplishment: "SEC Tournament Champions (27-9)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png",
  mascotName: "Wildcat",
  people: [
    {
      slug: "tyler-ulis",
      firstName: "Tyler",
      lastName: "Ulis",
      birthYear: 1996,
      hometown: "Matteson, IL",
      highSchool: "Marian Catholic High School, Chicago Heights, IL",
      isFeatured: true,
      imageUrl: "https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3907497.png",
      bio: "A 5-9 point guard who defied his size to become one of the best players in Kentucky history. Won SEC Player of the Year as a sophomore.",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Coach",
        currentEmployer: "University of Arkansas",
        location: "Fayetteville, AR",
        statusNote: "Drafted #34 by the Phoenix Suns in 2016, Ulis' NBA career was cut short by injuries from a car accident. He returned to Kentucky as a student assistant (2022-24) and led the 'La Familia' TBT team. Now an assistant coach at Arkansas under John Calipari.",
        sourceUrl: "https://arkansasrazorbacks.com/support-staff/tyler-ulis/",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Point Guard", yearsAtSchool: "2014-2016", statsNote: "Sophomore • SEC Player of the Year • 17.3 PPG, 7.0 APG", gamesPlayed: 36, pointsPerGame: 17.3, reboundsPerGame: 2.9, assistsPerGame: 7.0 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Marian Catholic High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 31.0, reboundsPerGame: 2.9, assistsPerGame: 11.1 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2015-2016", yearLabel: "Sophomore", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 17.3, reboundsPerGame: 2.9, assistsPerGame: 7.0 },
      
        { level: "PROFESSIONAL", teamName: "Phoenix Suns", season: "2016-17", yearLabel: "2016-17 (Rookie)", sortOrder: 301, gamesPlayed: 61, minutesPerGame: 18.9, pointsPerGame: 7.3, reboundsPerGame: 1.3, assistsPerGame: 3.2, stealsPerGame: 0.7, fieldGoalPct: 0.376, threePointPct: 0.341, freeThrowPct: 0.776 },
        { level: "PROFESSIONAL", teamName: "Phoenix / Chicago / SAC", season: "2017-18", yearLabel: "2017-18", sortOrder: 302, gamesPlayed: 40, minutesPerGame: 11.2, pointsPerGame: 3.7, reboundsPerGame: 0.8, assistsPerGame: 2.2, fieldGoalPct: 0.343, threePointPct: 0.289 },
      ],
      careerEvents: [
        { year: 2016, title: "Won SEC Player of the Year", eventType: "AWARD" },
        { year: 2016, title: "Selected #34 overall by the Phoenix Suns", eventType: "DRAFT" },
        { year: 2024, title: "Joined Arkansas coaching staff under Calipari", eventType: "CAREER" },
      ],
    },
    {
      slug: "jamal-murray",
      firstName: "Jamal",
      lastName: "Murray",
      birthYear: 1997,
      hometown: "Kitchener, ON, Canada",
      highSchool: "Orangeville Prep, Orangeville, ON",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1627750.png",
      bio: "A Canadian freshman guard who averaged 20.0 PPG and became the #7 overall pick. Murray scored 35 points against UCLA in the Sweet Sixteen.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Denver Nuggets",
        league: "NBA",
        location: "Denver, CO",
        statusNote: "Drafted #7 overall by the Denver Nuggets in 2016, Murray was a key contributor to the Nuggets' 2023 NBA Championship. Named a 2026 NBA All-Star (first career selection), averaging 25.5 PPG and 7.2 APG in 2025-26.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jamal_Murray",
      },
      membership: { role: "PLAYER", jerseyNumber: 23, position: "Guard", yearsAtSchool: "2015-2016", statsNote: "Freshman • 20.0 PPG • #7 overall pick", gamesPlayed: 36, pointsPerGame: 20.0, reboundsPerGame: 5.2, assistsPerGame: 2.2 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Orangeville Prep", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 35.0, reboundsPerGame: 5.2, assistsPerGame: 4.9 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2015-16", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 36, minutesPerGame: 34.5, pointsPerGame: 20.0, reboundsPerGame: 5.2, assistsPerGame: 2.2, stealsPerGame: 1.0, fieldGoalPct: 0.454, threePointPct: 0.408, freeThrowPct: 0.783 },
        { level: "PROFESSIONAL", teamName: "Denver Nuggets", season: "2016-17", yearLabel: "2016-17", sortOrder: 301, gamesPlayed: 82, minutesPerGame: 21.5, pointsPerGame: 9.9, reboundsPerGame: 2.1, assistsPerGame: 2.1, fieldGoalPct: 0.404, threePointPct: 0.334, freeThrowPct: 0.880 },
        { level: "PROFESSIONAL", teamName: "Denver Nuggets", season: "2017-18", yearLabel: "2017-18", sortOrder: 302, gamesPlayed: 81, minutesPerGame: 31.7, pointsPerGame: 16.7, reboundsPerGame: 3.4, assistsPerGame: 3.4, fieldGoalPct: 0.451, threePointPct: 0.378, freeThrowPct: 0.905 },
        { level: "PROFESSIONAL", teamName: "Denver Nuggets", season: "2018-19", yearLabel: "2018-19", sortOrder: 303, gamesPlayed: 75, minutesPerGame: 33.4, pointsPerGame: 18.2, reboundsPerGame: 4.2, assistsPerGame: 4.8, fieldGoalPct: 0.437, threePointPct: 0.366, freeThrowPct: 0.848 },
        { level: "PROFESSIONAL", teamName: "Denver Nuggets", season: "2019-20", yearLabel: "2019-20 (Bubble)", sortOrder: 304, gamesPlayed: 59, minutesPerGame: 32.3, pointsPerGame: 18.5, reboundsPerGame: 4.0, assistsPerGame: 4.8, fieldGoalPct: 0.455, threePointPct: 0.346, freeThrowPct: 0.881 },
        { level: "PROFESSIONAL", teamName: "Denver Nuggets", season: "2020-21", yearLabel: "2020-21 (ACL)", sortOrder: 305, gamesPlayed: 48, minutesPerGame: 35.5, pointsPerGame: 21.2, reboundsPerGame: 4.0, assistsPerGame: 4.8, fieldGoalPct: 0.477, threePointPct: 0.408, freeThrowPct: 0.867 },
        { level: "PROFESSIONAL", teamName: "Denver Nuggets", season: "2022-23", yearLabel: "2022-23 (Champion)", sortOrder: 307, gamesPlayed: 65, minutesPerGame: 32.5, pointsPerGame: 20.0, reboundsPerGame: 4.0, assistsPerGame: 6.2, fieldGoalPct: 0.454, threePointPct: 0.398, freeThrowPct: 0.836 },
        { level: "PROFESSIONAL", teamName: "Denver Nuggets", season: "2025-26", yearLabel: "2025-26 (All-Star)", sortOrder: 310, gamesPlayed: 55, pointsPerGame: 25.5, assistsPerGame: 7.2, reboundsPerGame: 4.4 },
      ],
      careerEvents: [
        { year: 2016, title: "Selected #7 overall by the Denver Nuggets", eventType: "DRAFT" },
        { year: 2023, title: "Won NBA Championship with the Nuggets", eventType: "CHAMPIONSHIP" },
        { year: 2026, title: "Named NBA All-Star for the first time", eventType: "AWARD" },
      ],
    },
    {
      slug: "skal-labissiere",
      firstName: "Skal",
      lastName: "Labissiere",
      birthYear: 1996,
      hometown: "Port-au-Prince, Haiti",
      highSchool: "Lausanne Collegiate School, Memphis, TN",
      isFeatured: false,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1627746.png",
      bio: "A Haitian-born center who was the #1 recruit in his class. Declared for the NBA after a quiet freshman season but showed flashes of brilliance.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward / Center",
        currentEmployer: "Capital City Go-Go (G League)",
        league: "NBA G League",
        location: "Washington, D.C.",
        statusNote: "Drafted #28 by the Sacramento Kings in 2016. Played for the Kings and Trail Blazers before bouncing between the G League and international play. Currently a top performer in the G League (19.2 PPG, 7.8 RPG) and signed 10-day deals with the Wizards in January 2026.",
        sourceUrl: "https://en.wikipedia.org/wiki/Skal_Labissi%C3%A8re",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Center / Forward", yearsAtSchool: "2015-2016", statsNote: "Freshman • #1 recruit • #28 overall pick" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Lausanne Collegiate School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 23.9, reboundsPerGame: 11.2, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2015-2016", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 12.6, reboundsPerGame: 6.3, assistsPerGame: 0.6 },
      
        { level: "PROFESSIONAL", teamName: "Sacramento Kings", season: "2016-17", yearLabel: "2016-17 (Rookie)", sortOrder: 301, gamesPlayed: 33, pointsPerGame: 5.2, reboundsPerGame: 2.5, assistsPerGame: 0.3 },
        { level: "PROFESSIONAL", teamName: "Sacramento Kings", season: "2017-18", yearLabel: "2017-18", sortOrder: 302, gamesPlayed: 55, pointsPerGame: 7.7, reboundsPerGame: 3.7, assistsPerGame: 0.5 },
        { level: "PROFESSIONAL", teamName: "Sacramento Kings", season: "2018-19", yearLabel: "2018-19", sortOrder: 303, gamesPlayed: 21, pointsPerGame: 4.8, reboundsPerGame: 2.6, assistsPerGame: 0.5 },
        { level: "PROFESSIONAL", teamName: "Portland Trail Blazers", season: "2019-20", yearLabel: "2019-20", sortOrder: 304, gamesPlayed: 33, pointsPerGame: 5.0, reboundsPerGame: 2.8, assistsPerGame: 0.6 },
        { level: "PROFESSIONAL", teamName: "Capital City Go-Go (G League)", season: "2025-26", yearLabel: "2025-26 (G League star)", sortOrder: 308, gamesPlayed: 40, pointsPerGame: 19.2, reboundsPerGame: 7.8, assistsPerGame: 1.5 },
      ],
      careerEvents: [
        { year: 2016, title: "Selected #28 overall by the Sacramento Kings", eventType: "DRAFT" },
      ],
    },
    {
      slug: "alex-poythress",
      firstName: "Alex",
      lastName: "Poythress",
      birthYear: 1993,
      hometown: "Clarksville, TN",
      highSchool: "Northeast High School, Clarksville, TN",
      isFeatured: false,
      bio: "A senior forward who overcame a torn ACL to return for his final season and provide veteran leadership.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Zenit Saint Petersburg",
        league: "VTB United League (Russia)",
        location: "Saint Petersburg, Russia",
        statusNote: "Went undrafted in 2016 but has built a long overseas career in Israel, Turkey, South Korea, Australia, and Russia. Averaging 14.3 PPG and 7.0 RPG with Zenit St. Petersburg in 2025-26.",
        sourceUrl: "https://www.proballers.com/basketball/player/12067/alex-poythress",
      },
      membership: { role: "PLAYER", jerseyNumber: 22, position: "Power Forward", yearsAtSchool: "2012-2016", statsNote: "Senior • Overcame torn ACL • Veteran leader" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Northeast High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 20.3, reboundsPerGame: 10.2, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2015-2016", yearLabel: "Senior", sortOrder: 201, gamesPlayed: 35, pointsPerGame: 10.2, reboundsPerGame: 5.5, assistsPerGame: 0.8 },
      
        { level: "PROFESSIONAL", teamName: "Indiana Pacers", season: "2017-18", yearLabel: "2017-18", sortOrder: 301, gamesPlayed: 21, minutesPerGame: 8.2, pointsPerGame: 3.3, reboundsPerGame: 2.0, fieldGoalPct: 0.417 },
      ],
      careerEvents: [
        { year: 2016, title: "Went undrafted; began overseas career", eventType: "CAREER" },
      ],
    },
    {
      slug: "marcus-lee",
      firstName: "Marcus",
      lastName: "Lee",
      birthYear: 1994,
      hometown: "Antioch, CA",
      highSchool: "Deer Valley High School, Antioch, CA",
      isFeatured: false,
      bio: "An athletic forward who withdrew from the 2016 NBA Draft and transferred to Cal.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Cairns Taipans",
        league: "NBL Australia",
        location: "Cairns, Australia",
        statusNote: "After transferring to Cal-Berkeley, Lee went undrafted in 2018. Has played in the G League, Philippines, and Australia. Currently averaging 6.8 PPG and 5.5 RPG with the Cairns Taipans in Australia's NBL.",
        sourceUrl: "https://en.wikipedia.org/wiki/Marcus_Lee",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Forward", yearsAtSchool: "2013-2016", statsNote: "Junior • Athletic rim-runner • Transferred to Cal" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Deer Valley High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 11.3, reboundsPerGame: 9.1, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2015-2016", yearLabel: "Junior", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 4.2, reboundsPerGame: 4.7, assistsPerGame: 0.5 },
      
        { level: "PROFESSIONAL", teamName: "Cairns Taipans (NBL)", season: "2018-19", yearLabel: "2018-19", sortOrder: 301, gamesPlayed: 28, minutesPerGame: 18.0, pointsPerGame: 7.5, reboundsPerGame: 6.8, blocksPerGame: 1.0, fieldGoalPct: 0.520 },
      ],
      careerEvents: [
        { year: 2016, title: "Withdrew from NBA Draft; transferred to Cal", eventType: "OTHER" },
      ],
    },
    {
      slug: "derek-willis",
      firstName: "Derek",
      lastName: "Willis",
      birthYear: 1994,
      hometown: "Frankfort, KY",
      highSchool: "Western Hills High School, Frankfort, KY",
      isFeatured: false,
      bio: "A Kentucky native who developed into a reliable stretch four over four years.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Paris Basketball",
        league: "LNB Pro A / EuroLeague (France)",
        location: "Paris, France",
        statusNote: "After going undrafted in 2017, Willis built an impressive European career across Germany, Italy, Spain, and Turkey (including EuroLeague with Anadolu Efes). Signed a 2-year deal with Paris Basketball for the 2025-26 season.",
        sourceUrl: "https://parisbasketball.com/en/2025/07/derek-willis-arrives-in-paris/",
      },
      membership: { role: "PLAYER", jerseyNumber: 35, position: "Power Forward", yearsAtSchool: "2013-2017", statsNote: "Junior • In-state recruit • Stretch four" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Western Hills High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 15.2, reboundsPerGame: 7.4, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2015-2016", yearLabel: "Junior", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 6.8, reboundsPerGame: 3.4, assistsPerGame: 0.5 },
      ],
      careerEvents: [
        { year: 2017, title: "Went undrafted; began European career", eventType: "CAREER" },
        { year: 2025, title: "Signed with Paris Basketball (EuroLeague)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "isaiah-briscoe",
      firstName: "Isaiah",
      lastName: "Briscoe",
      birthYear: 1996,
      hometown: "Newark, NJ",
      highSchool: "Roselle Catholic High School, Roselle, NJ",
      isFeatured: false,
      bio: "A tough, physical freshman guard from New Jersey who was a McDonald's All-American.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Fujian Sturgeons",
        league: "CBA (China)",
        location: "China",
        statusNote: "After going undrafted in 2017, Briscoe has played across the globe — NBA G League, Israel, Lithuania, Taiwan (32.8 PPG), Indonesia, and China's CBA. Scored a career-high 33 points on Jan 6, 2026 with the Fujian Sturgeons.",
        sourceUrl: "https://en.wikipedia.org/wiki/Isaiah_Briscoe",
      },
      membership: { role: "PLAYER", jerseyNumber: 13, position: "Guard", yearsAtSchool: "2015-2017", statsNote: "Freshman • McDonald's All-American" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Roselle Catholic High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 19.4, reboundsPerGame: 5.3, assistsPerGame: 6.0 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2015-2016", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 9.6, reboundsPerGame: 5.3, assistsPerGame: 3.1 },
      ],
      careerEvents: [
        { year: 2017, title: "Went undrafted; began professional career", eventType: "CAREER" },
      ],
    },
    {
      slug: "dominique-hawkins",
      firstName: "Dominique",
      lastName: "Hawkins",
      birthYear: 1994,
      hometown: "Richmond, KY",
      highSchool: "Madison Central High School, Richmond, KY",
      isFeatured: false,
      bio: "A beloved walk-on from Richmond, KY who was the 2013 Kentucky Mr. Basketball. Fan favorite for his hustle.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Youth Basketball Trainer",
        location: "Kentucky",
        linkedInUrl: "https://www.linkedin.com/in/dominique-hawkins-25966492/",
        statusNote: "Named Most Outstanding Player of the 2017 SEC Tournament. After Kentucky, played overseas in Estonia (Avis Rapla), Denmark, Latvia-Estonia League, and Slovakia (Lucenec, where he scored a career-high 31 in a 2021 playoff game). Since retiring around 2021, he runs D-Hawk Training, a youth basketball business in Richmond, KY. Inducted into the Madison County Sports Hall of Fame in 2024.",
        sourceUrl: "https://www.kentuckytoday.com/sports/dominique-hawkins-inducted-into-the-madison-county-sports-hall-of-fame/article_59f5e238-1648-11ef-b29a-9beeb0cc718f.html",
      },
      membership: { role: "PLAYER", jerseyNumber: 25, position: "Guard", yearsAtSchool: "2013-2017", statsNote: "Junior • Walk-on • 2013 KY Mr. Basketball • Fan favorite" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Madison Central High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 10.2, reboundsPerGame: 1.9, assistsPerGame: 4.3 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2015-2016", yearLabel: "Junior", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 3.5, reboundsPerGame: 1.9, assistsPerGame: 1.8 },
      ],
      careerEvents: [
        { year: 2017, title: "Graduated from Kentucky; played overseas", eventType: "CAREER" },
      ],
    },
    {
      slug: "isaac-humphries",
      firstName: "Isaac",
      lastName: "Humphries",
      birthYear: 1998,
      hometown: "Sydney, Australia",
      highSchool: "La Lumiere School, La Porte, IN",
      isFeatured: false,
      bio: "A 7-foot Australian center who made history as the first openly gay active male professional basketball player in a top-flight league.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "Adelaide 36ers",
        league: "NBL Australia",
        location: "Adelaide, Australia",
        statusNote: "After leaving Kentucky, Humphries won NBL Rookie of the Year with the Sydney Kings and played 5 games for the Atlanta Hawks. In his 5th season as co-captain of the Adelaide 36ers, averaging 13.4 PPG. Made history in 2023 by coming out as the first openly gay active male professional basketball player in a top-flight league.",
        sourceUrl: "https://www.adelaide36ers.com/player/isaac-humphries",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Center", yearsAtSchool: "2015-2017", statsNote: "Freshman • 7-footer from Australia" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "La Lumiere School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 7.4, reboundsPerGame: 4.6, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2015-2016", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 28, pointsPerGame: 1.6, reboundsPerGame: 1.2, assistsPerGame: 0.2 },
      ],
      careerEvents: [
        { year: 2017, title: "NBL Rookie of the Year with Sydney Kings", eventType: "AWARD" },
        { year: 2023, title: "Came out as first openly gay active male pro basketball player in top league", eventType: "OTHER" },
      ],
    },
    {
      slug: "charles-matthews-uk",
      firstName: "Charles",
      lastName: "Matthews",
      birthYear: 1997,
      hometown: "Chicago, IL",
      highSchool: "St. Rita of Cascia High School, Chicago, IL",
      isFeatured: false,
      bio: "A freshman guard who transferred to Michigan after one season and started on Michigan's 2018 NCAA runner-up team.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Valley Suns (G League)",
        league: "NBA G League",
        statusNote: "After transferring to Michigan, started on their 2018 national championship game team. Tore his ACL at a Celtics predraft workout and went undrafted in 2019. Played 12 NBA games for the Cleveland Cavaliers in 2020-21. Won the NBL1 Men's MVP award in Australia with the Bendigo Braves in 2025 (20.4 PPG). G League rights traded to the Valley Suns (Suns affiliate) in January 2026.",
        sourceUrl: "https://en.wikipedia.org/wiki/Charles_Matthews_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Guard", yearsAtSchool: "2015-2016", statsNote: "Freshman • Transferred to Michigan • 2018 NCAA runner-up" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "St. Rita of Cascia High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 8.8, reboundsPerGame: 1.4, assistsPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2015-2016", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 28, pointsPerGame: 2.5, reboundsPerGame: 1.4, assistsPerGame: 0.4 },
      ],
      careerEvents: [
        { year: 2016, title: "Transferred to University of Michigan", eventType: "OTHER" },
        { year: 2018, title: "Started on Michigan's NCAA Championship game team", eventType: "CAREER" },
      ],
    },
    {
      slug: "mychal-mulder",
      firstName: "Mychal",
      lastName: "Mulder",
      birthYear: 1994,
      hometown: "Windsor, ON, Canada",
      highSchool: "Vincent Massey Secondary School, Windsor, ON",
      isFeatured: false,
      bio: "A Canadian junior guard who provided perimeter shooting. Later played in the NBA for the Golden State Warriors.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Vancouver Bandits",
        league: "CEBL (Canada)",
        location: "Vancouver, BC",
        statusNote: "Played in the NBA for the Golden State Warriors (2020-21) and had stints with the Magic and Grizzlies. Signed with the Vancouver Bandits of Canada's CEBL in March 2026.",
        sourceUrl: "https://www.cebl.ca/bandits-ink-nba-experienced-guard-mulder",
      },
      membership: { role: "PLAYER", jerseyNumber: 11, position: "Guard", yearsAtSchool: "2013-2017", statsNote: "Junior • Canadian sharpshooter" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Vincent Massey Secondary School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 9.9, reboundsPerGame: 1.0, assistsPerGame: 2.6 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2015-2016", yearLabel: "Junior", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 3.3, reboundsPerGame: 1.0, assistsPerGame: 0.5 },
      ],
      careerEvents: [
        { year: 2020, title: "Signed with Golden State Warriors (NBA)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "dillon-pulliam",
      firstName: "Dillon",
      lastName: "Pulliam",
      birthYear: 1995,
      hometown: "Cynthiana, KY",
      highSchool: "Harrison County High School, Cynthiana, KY",
      isFeatured: false,
      bio: "A former high school valedictorian and Transylvania University transfer who joined Kentucky as a walk-on guard in 2015. The computer engineering major embraced his role as the oldest player on Calipari's famously young rosters.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Software Engineer",
        currentEmployer: "Toyota Connected North America",
        location: "Plano, TX",
        statusNote: "After walking on at Kentucky for the 2015-16 and 2016-17 seasons, Pulliam transferred to Carnegie Mellon University to pursue computer engineering while continuing to play basketball at the NCAA Division III level. He built his post-basketball career in machine learning and autonomous vehicle technology, and as of 2026 works as a software engineer at Toyota Connected North America, focusing on self-driving car research and applied machine learning.",
        sourceUrl: "https://www.linkedin.com/in/dillonpulliam/",
        linkedInUrl: "https://www.linkedin.com/in/dillonpulliam/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 10,
        position: "Guard",
        yearsAtSchool: "2015-2017",
        statsNote: "Walk-on guard • Transfer from Transylvania University • Computer engineering major",
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Harrison County High School", season: "2012-13", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 18.0, reboundsPerGame: 6.0, assistsPerGame: 4.0 },
        { level: "COLLEGE", teamName: "Transylvania Pioneers", season: "2014-15", yearLabel: "Freshman", sortOrder: 200, gamesPlayed: 25, pointsPerGame: 4.8, reboundsPerGame: 3.4 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2015-16", yearLabel: "Sophomore (walk-on)", sortOrder: 201, gamesPlayed: 8, minutesPerGame: 1.4, pointsPerGame: 0.4 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2016-17", yearLabel: "Junior (walk-on)", sortOrder: 202, gamesPlayed: 12, minutesPerGame: 1.9, pointsPerGame: 0.5 },
      ],
      careerEvents: [
        { year: 2015, title: "Joined Kentucky as a walk-on transfer from Transylvania", eventType: "SIGNING" },
        { year: 2017, title: "Transferred to Carnegie Mellon for computer engineering", eventType: "OTHER" },
        { year: 2020, title: "Began career in autonomous vehicle software", eventType: "OTHER" },
      ],
    },
    {
      slug: "jonny-david",
      firstName: "Jonny",
      lastName: "David",
      birthYear: 1996,
      hometown: "Pittsburgh, PA",
      highSchool: "Mount Lebanon High School, Pittsburgh, PA",
      isFeatured: false,
      bio: "A walk-on guard from Pittsburgh whose father Joe played for John Calipari at Pitt in the 1980s. David passed up multiple Division I scholarship offers to chase the Kentucky dream and spent four seasons as a fan-favorite reserve.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Kinesiology Graduate",
        statusNote: "Walked on at Kentucky from 2015 to 2019, appearing in 33 career games while earning the respect of teammates as a practice player and locker-room glue guy. Graduated with a degree in kinesiology and was named to the 2019 SEC Community Service Team for his work around Lexington. During his senior season he produced \"Jonny David All-Access,\" a behind-the-scenes video series that gave Big Blue Nation a unique look inside the program.",
        sourceUrl: "https://www.sports-reference.com/cbb/players/jonny-david-1.html",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 5,
        position: "Guard",
        yearsAtSchool: "2015-2019",
        statsNote: "Walk-on guard • 33 career games • 2019 SEC Community Service Team",
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Mount Lebanon High School", season: "2014-15", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 18.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2015-16", yearLabel: "Freshman (walk-on)", sortOrder: 201, gamesPlayed: 4, minutesPerGame: 1.0, pointsPerGame: 0.3 },
      ],
      careerEvents: [
        { year: 2015, title: "Joined Kentucky as a walk-on guard", eventType: "SIGNING" },
        { year: 2019, title: "Named to SEC Community Service Team; graduated in kinesiology", eventType: "AWARD" },
      ],
    },
    {
      slug: "ej-floreal",
      firstName: "EJ",
      lastName: "Floreal",
      birthYear: 1994,
      hometown: "Palo Alto, CA",
      highSchool: "Paul Laurence Dunbar High School, Lexington, KY",
      isFeatured: false,
      bio: "The son of two Olympians who walked on at Kentucky for three basketball seasons before switching to track and field under his father, UK track head coach Edrick Floreal. A rare two-sport athlete whose athletic bloodlines trace back to the Olympic podium.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Former Kentucky Two-Sport Athlete",
        statusNote: "Appeared in 29 games across three seasons (2013-16) as a walk-on guard at Kentucky during three NCAA Tournament runs including two Final Fours. In August 2016 he gave up basketball to focus exclusively on track and field under his father, UK head coach Edrick Floreal, competing as a sprinter. His mother LaVonna Martin-Floreal won 100m hurdles silver at the 1992 Olympics, and his father competed for Canada in the 1988 and 1992 Games.",
        sourceUrl: "https://ukathletics.com/sports/mbball/roster/player/ej-floreal-2/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 24,
        position: "Guard",
        yearsAtSchool: "2013-2016",
        statsNote: "Walk-on guard • Son of Olympians • Switched to track & field in 2016",
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Paul Laurence Dunbar High School", season: "2012-13", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 10.0 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2013-14", yearLabel: "Freshman (walk-on)", sortOrder: 201, gamesPlayed: 10, pointsPerGame: 0.2 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2014-15", yearLabel: "Sophomore (walk-on)", sortOrder: 202, gamesPlayed: 9, pointsPerGame: 0.1 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2015-16", yearLabel: "Junior (walk-on)", sortOrder: 203, gamesPlayed: 10, pointsPerGame: 0.1 },
      ],
      careerEvents: [
        { year: 2016, title: "Gave up basketball to focus on UK track & field", eventType: "OTHER" },
      ],
    },
    {
      slug: "tai-wynyard",
      firstName: "Tai",
      lastName: "Wynyard",
      birthYear: 1997,
      hometown: "Auckland, New Zealand",
      highSchool: "Scots College, Wellington, New Zealand",
      isFeatured: false,
      bio: "A 6-foot-10 New Zealand center who enrolled at Kentucky in December 2015 as a mid-year addition. The Tall Blacks senior national team member never quite broke through at Kentucky but has carved out a professional career across leagues in Europe, Asia and Oceania.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "New Zealand Breakers",
        league: "NBL (Australia)",
        location: "Auckland, New Zealand",
        statusNote: "Played only 97 minutes across two seasons at Kentucky and was suspended in February 2018 for a team rules violation, after which he returned home to New Zealand. Debuted for the senior Tall Blacks at age 16 and has since played professionally in New Zealand, the Chinese Basketball Association with the Shanghai Sharks, and most recently signed with the New Zealand Breakers in December 2024 as an injury-replacement big man.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tai_Wynyard",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 42,
        position: "Center",
        yearsAtSchool: "2015-2018",
        statsNote: "Mid-year enrollee (December 2015) • Redshirted freshman year",
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Scots College", season: "2014-15", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 16.0, reboundsPerGame: 11.0 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2015-16", yearLabel: "Freshman (redshirt)", sortOrder: 201, gamesPlayed: 0 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2016-17", yearLabel: "RS Freshman", sortOrder: 202, gamesPlayed: 14, minutesPerGame: 4.2, pointsPerGame: 1.1, reboundsPerGame: 1.2 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2017-18", yearLabel: "Sophomore", sortOrder: 203, gamesPlayed: 14, minutesPerGame: 2.5, pointsPerGame: 0.3 },
      ],
      careerEvents: [
        { year: 2015, title: "Enrolled at Kentucky as mid-year addition", eventType: "SIGNING" },
        { year: 2018, title: "Left Kentucky and returned to New Zealand", eventType: "OTHER" },
        { year: 2024, title: "Signed with New Zealand Breakers (NBL)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "john-calipari",
      firstName: "John",
      lastName: "Calipari",
      birthYear: 1959,
      hometown: "Moon Township, PA",
      highSchool: "Moon Area High School, Moon Township, PA",
      isFeatured: true,
      bio: "The architect of Kentucky's one-and-done era who produced more NBA Draft picks than any other coach in history.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "University of Arkansas",
        league: "SEC",
        location: "Fayetteville, AR",
        statusNote: "Left Kentucky for Arkansas in April 2024 after 15 seasons. Won the 2026 SEC Tournament Championship with Arkansas — the first men's coach to win an SEC Tournament title at multiple schools.",
        sourceUrl: "https://en.wikipedia.org/wiki/John_Calipari",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2024", statsNote: "27-9 • SEC Tournament Champions" },
      careerEvents: [
        { year: 2012, title: "Won NCAA National Championship at Kentucky", eventType: "CHAMPIONSHIP" },
        { year: 2024, title: "Left Kentucky for Arkansas", eventType: "CAREER" },
        { year: 2026, title: "Won SEC Tournament Championship with Arkansas", eventType: "CHAMPIONSHIP" },
      ],
    },
  ],
};
