import type { TeamSeed } from "./types";

export const kentuckyBasketball2019: TeamSeed = {
  slug: "kentucky-basketball-2019",
  name: "Kentucky Wildcats",
  season: "2018-2019",
  sport: "Men's Basketball",
  school: "University of Kentucky",
  conference: "SEC",
  accomplishment: "Elite Eight (30-7)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png",
  mascotName: "Wildcat",
  people: [
    {
      slug: "tyler-herro",
      firstName: "Tyler",
      lastName: "Herro",
      birthYear: 2000,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1629639.png",
      hometown: "Milwaukee, WI",
      highSchool: "Whitnall High School, Greenfield, WI",
      isFeatured: true,
      bio: "A fearless freshman sharpshooter who became one of the most prolific scorers in Kentucky history. Herro declared for the NBA Draft after one season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Miami Heat",
        league: "NBA",
        location: "Miami, FL",
        statusNote: "Drafted 13th overall by the Miami Heat in 2019, Herro won the 2022 Sixth Man of the Year award and signed a 4-year, $120M contract extension. He is averaging 21.6 PPG in 2025-26 and has developed into one of the Heat's core players.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tyler_Herro",
      },
      membership: { role: "PLAYER", jerseyNumber: 14, position: "Guard", yearsAtSchool: "2018-2019", statsNote: "Freshman • 14.0 PPG • Declared for NBA Draft", gamesPlayed: 37, pointsPerGame: 14.0, reboundsPerGame: 4.5, assistsPerGame: 2.5 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Whitnall High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 26.0, reboundsPerGame: 4.5, assistsPerGame: 5.2 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2018-19", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 37, minutesPerGame: 28.3, pointsPerGame: 14.0, reboundsPerGame: 4.5, assistsPerGame: 2.5, stealsPerGame: 0.9, fieldGoalPct: 0.462, threePointPct: 0.355, freeThrowPct: 0.935 },
        { level: "PROFESSIONAL", teamName: "Miami Heat", season: "2019-20", yearLabel: "2019-20 (NBA Finals)", sortOrder: 301, gamesPlayed: 55, minutesPerGame: 27.4, pointsPerGame: 13.5, reboundsPerGame: 4.1, assistsPerGame: 2.2, stealsPerGame: 0.6, fieldGoalPct: 0.427, threePointPct: 0.389, freeThrowPct: 0.873 },
        { level: "PROFESSIONAL", teamName: "Miami Heat", season: "2020-21", yearLabel: "2020-21", sortOrder: 302, gamesPlayed: 54, minutesPerGame: 31.9, pointsPerGame: 15.1, reboundsPerGame: 5.0, assistsPerGame: 3.4, stealsPerGame: 0.8, fieldGoalPct: 0.440, threePointPct: 0.361, freeThrowPct: 0.846 },
        { level: "PROFESSIONAL", teamName: "Miami Heat", season: "2021-22", yearLabel: "2021-22 (6MOY)", sortOrder: 303, gamesPlayed: 66, minutesPerGame: 32.6, pointsPerGame: 20.7, reboundsPerGame: 5.0, assistsPerGame: 4.0, stealsPerGame: 0.7, fieldGoalPct: 0.449, threePointPct: 0.399, freeThrowPct: 0.868 },
        { level: "PROFESSIONAL", teamName: "Miami Heat", season: "2022-23", yearLabel: "2022-23 (NBA Finals)", sortOrder: 304, gamesPlayed: 59, minutesPerGame: 33.0, pointsPerGame: 20.1, reboundsPerGame: 5.4, assistsPerGame: 4.5, fieldGoalPct: 0.443, threePointPct: 0.385, freeThrowPct: 0.858 },
        { level: "PROFESSIONAL", teamName: "Miami Heat", season: "2024-25", yearLabel: "2024-25", sortOrder: 306, gamesPlayed: 77, minutesPerGame: 35.4, pointsPerGame: 23.9, reboundsPerGame: 5.2, assistsPerGame: 5.5, stealsPerGame: 0.9, fieldGoalPct: 0.472 },
        { level: "PROFESSIONAL", teamName: "Miami Heat", season: "2023-24", yearLabel: "2023-24", sortOrder: 305, gamesPlayed: 42, minutesPerGame: 33.0, pointsPerGame: 20.8, reboundsPerGame: 5.3, assistsPerGame: 4.5, fieldGoalPct: 0.440, threePointPct: 0.390, freeThrowPct: 0.870 },
        { level: "PROFESSIONAL", teamName: "Miami Heat", season: "2025-26", yearLabel: "2025-26", sortOrder: 307, gamesPlayed: 55, pointsPerGame: 21.6, reboundsPerGame: 4.7, assistsPerGame: 3.8, fieldGoalPct: 0.450 },
      ],
      careerEvents: [
        { year: 2019, title: "Selected #13 overall by the Miami Heat", eventType: "DRAFT" },
        { year: 2022, title: "Won NBA Sixth Man of the Year", eventType: "AWARD" },
      ],
    },
    {
      slug: "pj-washington",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1629023.png",
      firstName: "PJ",
      lastName: "Washington",
      birthYear: 1998,
      hometown: "Dallas, TX",
      highSchool: "Findlay Prep, Henderson, NV",
      isFeatured: true,
      bio: "A powerful forward who returned for his sophomore season and elevated his game to become a first-round NBA pick.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Dallas Mavericks",
        league: "NBA",
        location: "Dallas, TX",
        statusNote: "Drafted 12th overall by the Charlotte Hornets in 2019, Washington was traded to Dallas in February 2024 and signed a 4-year, $89M extension. Averaging 14.2 PPG, 7.1 RPG in 2025-26.",
        sourceUrl: "https://en.wikipedia.org/wiki/P._J._Washington",
      },
      membership: { role: "PLAYER", jerseyNumber: 25, position: "Forward", yearsAtSchool: "2017-2019", statsNote: "Sophomore • 15.2 PPG • First-round pick", gamesPlayed: 37, pointsPerGame: 15.2, reboundsPerGame: 7.5, assistsPerGame: 1.7 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Findlay Prep", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 27.8, reboundsPerGame: 12.8, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2018-2019", yearLabel: "Sophomore", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 15.2, reboundsPerGame: 7.5, assistsPerGame: 1.7 },
      
        { level: "PROFESSIONAL", teamName: "Charlotte Hornets", season: "2019-20", yearLabel: "2019-20 (Rookie)", sortOrder: 301, gamesPlayed: 58, pointsPerGame: 12.2, reboundsPerGame: 5.4, assistsPerGame: 2.1 },
        { level: "PROFESSIONAL", teamName: "Charlotte Hornets", season: "2020-21", yearLabel: "2020-21", sortOrder: 302, gamesPlayed: 64, pointsPerGame: 12.6, reboundsPerGame: 6.5, assistsPerGame: 2.5 },
        { level: "PROFESSIONAL", teamName: "Charlotte Hornets", season: "2022-23", yearLabel: "2022-23", sortOrder: 304, gamesPlayed: 74, pointsPerGame: 15.7, reboundsPerGame: 6.2, assistsPerGame: 2.4 },
        { level: "PROFESSIONAL", teamName: "CHA / Dallas Mavericks", season: "2023-24", yearLabel: "2023-24 (traded)", sortOrder: 305, gamesPlayed: 73, pointsPerGame: 13.6, reboundsPerGame: 5.5, assistsPerGame: 2.5 },
        { level: "PROFESSIONAL", teamName: "Dallas Mavericks", season: "2024-25", yearLabel: "2024-25 ($89M deal)", sortOrder: 306, gamesPlayed: 72, pointsPerGame: 14.2, reboundsPerGame: 7.1, assistsPerGame: 1.8 },
      ],
      careerEvents: [
        { year: 2019, title: "Selected #12 overall by the Charlotte Hornets", eventType: "DRAFT" },
        { year: 2024, title: "Traded to Dallas Mavericks; signed $89M extension", eventType: "SIGNING" },
      ],
    },
    {
      slug: "keldon-johnson",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1629640.png",
      firstName: "Keldon",
      lastName: "Johnson",
      birthYear: 1999,
      hometown: "South Hill, VA",
      highSchool: "Oak Hill Academy, Mouth of Wilson, VA",
      isFeatured: false,
      bio: "A physical guard/forward who declared for the NBA after his freshman year and became a key contributor for the San Antonio Spurs.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "San Antonio Spurs",
        league: "NBA",
        location: "San Antonio, TX",
        statusNote: "Drafted 29th overall by the San Antonio Spurs in 2019. Now the longest-tenured Spur on the roster, Johnson has been a consistent contributor throughout the team's rebuilding process.",
        sourceUrl: "https://en.wikipedia.org/wiki/Keldon_Johnson",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Guard / Forward", yearsAtSchool: "2018-2019", statsNote: "Freshman • 13.5 PPG • First-round pick", gamesPlayed: 37, pointsPerGame: 13.5, reboundsPerGame: 5.9, assistsPerGame: 1.6 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Oak Hill Academy", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 25.2, reboundsPerGame: 10.7, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2018-2019", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 13.5, reboundsPerGame: 5.9, assistsPerGame: 1.6 },
      
        { level: "PROFESSIONAL", teamName: "San Antonio Spurs", season: "2019-20", yearLabel: "2019-20 (Rookie)", sortOrder: 301, gamesPlayed: 25, pointsPerGame: 9.1, reboundsPerGame: 3.4, assistsPerGame: 0.9 },
        { level: "PROFESSIONAL", teamName: "San Antonio Spurs", season: "2020-21", yearLabel: "2020-21", sortOrder: 302, gamesPlayed: 69, pointsPerGame: 12.8, reboundsPerGame: 6.0, assistsPerGame: 1.8 },
        { level: "PROFESSIONAL", teamName: "San Antonio Spurs", season: "2021-22", yearLabel: "2021-22", sortOrder: 303, gamesPlayed: 75, pointsPerGame: 17.0, reboundsPerGame: 6.1, assistsPerGame: 2.1 },
        { level: "PROFESSIONAL", teamName: "San Antonio Spurs", season: "2022-23", yearLabel: "2022-23", sortOrder: 304, gamesPlayed: 63, pointsPerGame: 22.0, reboundsPerGame: 5.0, assistsPerGame: 3.2 },
        { level: "PROFESSIONAL", teamName: "San Antonio Spurs", season: "2024-25", yearLabel: "2024-25", sortOrder: 306, gamesPlayed: 70, pointsPerGame: 12.5, reboundsPerGame: 4.5, assistsPerGame: 2.5 },
      ],
      careerEvents: [
        { year: 2019, title: "Selected #29 overall by the San Antonio Spurs", eventType: "DRAFT" },
      ],
    },
    {
      slug: "ashton-hagans",
      firstName: "Ashton",
      lastName: "Hagans",
      birthYear: 1999,
      hometown: "Cartersville, GA",
      highSchool: "Newton High School, Covington, GA",
      isFeatured: false,
      bio: "An aggressive, defense-first point guard who led the SEC in steals as a freshman.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Rip City Remix (G League)",
        league: "NBA G League",
        location: "Portland, OR",
        statusNote: "Went undrafted in 2020 after leaving Kentucky following his sophomore year. Has bounced between the G League, CBA (China), and NBL (Australia). Currently with the Rip City Remix, the Portland Trail Blazers' G League affiliate.",
        sourceUrl: "https://en.wikipedia.org/wiki/Ashton_Hagans",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Point Guard", yearsAtSchool: "2018-2020", statsNote: "Freshman • Led SEC in steals • Elite defender" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Newton High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 16.6, reboundsPerGame: 3.4, assistsPerGame: 7.6 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2018-2019", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 7.7, reboundsPerGame: 3.4, assistsPerGame: 4.3 },
      ],
      careerEvents: [
        { year: 2020, title: "Went undrafted; began G League career", eventType: "CAREER" },
      ],
    },
    {
      slug: "nick-richards",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1630208.png",
      firstName: "Nick",
      lastName: "Richards",
      birthYear: 1997,
      hometown: "Kingston, Jamaica",
      highSchool: "The Patrick School, Elizabeth, NJ",
      isFeatured: false,
      bio: "A Jamaican-born center who developed into a dominant rim protector over three years at Kentucky.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "Chicago Bulls",
        league: "NBA",
        location: "Chicago, IL",
        statusNote: "Drafted 42nd overall by the Charlotte Hornets in 2020, Richards developed into a solid NBA rotation center. He was traded from Charlotte to Phoenix, then Milwaukee, then Chicago in 2025-26. On a 3-year, $15M deal.",
        sourceUrl: "https://www.basketball-reference.com/players/r/richani01.html",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Center", yearsAtSchool: "2017-2020", statsNote: "Sophomore • Developing shot-blocker" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "The Patrick School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 11.0, reboundsPerGame: 7.7, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2018-2019", yearLabel: "Sophomore", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 4.0, reboundsPerGame: 3.6, assistsPerGame: 0.3 },
      ],
      careerEvents: [
        { year: 2020, title: "Selected #42 overall by the Charlotte Hornets", eventType: "DRAFT" },
      ],
    },
    {
      slug: "reid-travis",
      firstName: "Reid",
      lastName: "Travis",
      birthYear: 1995,
      hometown: "Minneapolis, MN",
      highSchool: "DeLaSalle High School, Minneapolis, MN",
      isFeatured: false,
      bio: "A graduate transfer from Stanford who brought veteran leadership and toughness to the frontcourt.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        location: "Overseas",
        statusNote: "Went undrafted in 2019 and has played professionally overseas in Japan's B.League and Taiwan's TPBL, plus stints in the G League. A basketball journeyman still competing internationally.",
        sourceUrl: "https://en.wikipedia.org/wiki/Reid_Travis",
      },
      membership: { role: "PLAYER", jerseyNumber: 22, position: "Forward", yearsAtSchool: "2018-2019", statsNote: "Graduate Senior • Transfer from Stanford • Team leader" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "DeLaSalle High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 21.8, reboundsPerGame: 12.4, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2018-2019", yearLabel: "Graduate Senior", sortOrder: 201, gamesPlayed: 28, pointsPerGame: 11.2, reboundsPerGame: 7.2, assistsPerGame: 0.6 },
      
        { level: "PROFESSIONAL", teamName: "Medi Bayreuth (Germany)", season: "2019-20", yearLabel: "2019-20 (Germany)", sortOrder: 301, gamesPlayed: 20, pointsPerGame: 12.5, reboundsPerGame: 6.0, assistsPerGame: 1.0 },
        { level: "PROFESSIONAL", teamName: "Shimane Susanoo Magic (Japan)", season: "2020-21", yearLabel: "2020-21 (Japan B.League)", sortOrder: 302, gamesPlayed: 30, pointsPerGame: 15.0, reboundsPerGame: 7.5, assistsPerGame: 1.2 },
        { level: "PROFESSIONAL", teamName: "Sun Rockers Shibuya (Japan)", season: "2024-25", yearLabel: "2024-25 (Japan)", sortOrder: 306, gamesPlayed: 40, pointsPerGame: 13.2, reboundsPerGame: 6.9, assistsPerGame: 1.0 },
        { level: "PROFESSIONAL", teamName: "Kaohsiung Aquas (Taiwan)", season: "2025-26", yearLabel: "2025-26 (Taiwan TPBL)", sortOrder: 307, gamesPlayed: 15, pointsPerGame: 13.7, reboundsPerGame: 9.3, assistsPerGame: 0.8 },
      ],
      careerEvents: [
        { year: 2019, title: "Went undrafted; began overseas career", eventType: "CAREER" },
      ],
    },
    {
      slug: "ej-montgomery",
      firstName: "EJ",
      lastName: "Montgomery",
      birthYear: 1999,
      hometown: "Fort Pierce, FL",
      highSchool: "Wheeler High School, Marietta, GA",
      isFeatured: false,
      bio: "A highly recruited five-star forward who played two years at Kentucky before declaring for the NBA Draft.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "MKS Dabrowa Gornicza",
        league: "Polish Basketball League (PLK)",
        location: "Poland",
        statusNote: "Went undrafted in 2020 after his sophomore year. Has played in the G League and overseas. Currently averaging 7.4 PPG and 7.9 RPG in Poland's PLK.",
        sourceUrl: "https://www.proballers.com/basketball/player/178401/montgomery-e-j",
      },
      membership: { role: "PLAYER", jerseyNumber: 23, position: "Forward", yearsAtSchool: "2018-2020", statsNote: "Freshman • Five-star recruit" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Wheeler High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 10.7, reboundsPerGame: 8.5, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2018-2019", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 35, pointsPerGame: 3.8, reboundsPerGame: 4.2, assistsPerGame: 0.4 },
      ],
      careerEvents: [
        { year: 2020, title: "Went undrafted; began G League/overseas career", eventType: "CAREER" },
      ],
    },
    {
      slug: "immanuel-quickley",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1630193.png",
      firstName: "Immanuel",
      lastName: "Quickley",
      birthYear: 1999,
      hometown: "Havre de Grace, MD",
      highSchool: "The John Carroll School, Bel Air, MD",
      isFeatured: true,
      bio: "A dynamic guard who blossomed into the SEC Player of the Year as a sophomore and became a first-round NBA pick.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Point Guard",
        currentEmployer: "Toronto Raptors",
        league: "NBA",
        location: "Toronto, ON",
        statusNote: "Drafted 25th overall by the New York Knicks in 2020, Quickley was traded to Toronto in December 2023 and signed a 5-year, $162.5M max contract in July 2024. Averaging 17.0 PPG in 2025-26.",
        sourceUrl: "https://en.wikipedia.org/wiki/Immanuel_Quickley",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Guard", yearsAtSchool: "2018-2020", statsNote: "Freshman • Developed into 2020 SEC POY as sophomore" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "The John Carroll School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 12.8, reboundsPerGame: 1.5, assistsPerGame: 3.2 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2018-2019", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 5.2, reboundsPerGame: 1.5, assistsPerGame: 0.9 },
      ],
      careerEvents: [
        { year: 2020, title: "Selected #25 overall by the New York Knicks", eventType: "DRAFT" },
        { year: 2024, title: "Signed 5-year, $162.5M contract with Toronto Raptors", eventType: "SIGNING" },
      ],
    },
    {
      slug: "jemarl-baker",
      firstName: "Jemarl",
      lastName: "Baker Jr.",
      birthYear: 1998,
      hometown: "Menifee, CA",
      highSchool: "Eleanor Roosevelt High School, Eastvale, CA",
      isFeatured: false,
      bio: "Redshirted his freshman year with a torn meniscus, then played as a sophomore before transferring.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "Eisbaren Bremerhaven",
        league: "German ProA",
        location: "Germany",
        statusNote: "After transferring from Kentucky to Arizona, then Fresno State and New Mexico, Baker went undrafted and is now playing professionally in Germany's ProA second division.",
        sourceUrl: "https://basketball.eurobasket.com/player/Jemarl-Baker-Jr/421563",
      },
      membership: { role: "PLAYER", jerseyNumber: 13, position: "Guard", yearsAtSchool: "2017-2019", statsNote: "Sophomore • Redshirted freshman year • Transferred to Arizona" },
      careerEvents: [
        { year: 2019, title: "Transferred to University of Arizona", eventType: "OTHER" },
      ],
    },
    {
      slug: "brad-calipari",
      firstName: "Brad",
      lastName: "Calipari",
      birthYear: 1996,
      hometown: "Franklin Lakes, NJ",
      highSchool: "MacDuffie School, Granby, MA",
      isFeatured: false,
      bio: "Coach Calipari's son who walked on at Kentucky and was a beloved team member despite limited playing time.",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Coach / Director of Player Development",
        currentEmployer: "University of Arkansas",
        location: "Fayetteville, AR",
        statusNote: "After transferring to Detroit Mercy for his senior year, Brad joined his father's coaching staff. He is now in his second year as an assistant at Arkansas under John Calipari, focusing on player development.",
        sourceUrl: "https://arkansasrazorbacks.com/coache/brad-calipari/",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Guard", yearsAtSchool: "2016-2019", statsNote: "Junior walk-on • Coach's son" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "MacDuffie School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 5.6, reboundsPerGame: 0.2, assistsPerGame: 2.3 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2018-2019", yearLabel: "Junior walk-on", sortOrder: 201, gamesPlayed: 14, pointsPerGame: 0.4, reboundsPerGame: 0.2, assistsPerGame: 0.2 },
      ],
      careerEvents: [
        { year: 2024, title: "Joined Arkansas staff under father John Calipari", eventType: "CAREER" },
      ],
    },
    {
      slug: "dontaie-allen",
      firstName: "Dontaie",
      lastName: "Allen",
      birthYear: 2001,
      hometown: "Falmouth, KY",
      highSchool: "Pendleton County High School, Falmouth, KY",
      isFeatured: false,
      bio: "Kentucky Mr. Basketball in 2019 who committed to his home state Wildcats. Tore his ACL in December 2018 during his senior year of high school, redshirted his first year at Kentucky, and later became famous for a 23-point outburst against Mississippi State.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Ole Miss (transfer portal)",
        league: "SEC",
        location: "In transfer portal",
        statusNote: "The 2019 Kentucky Mr. Basketball averaged 42.9 PPG in limited senior games before tearing his ACL. After redshirting his first year at UK, he scored 23 points against Mississippi State on 7-of-11 threes in one of Kentucky's most memorable recent performances. After three seasons at UK, he transferred to WKU and then Wyoming. His jersey was retired by Pendleton County High School. He entered the transfer portal in April 2025 seeking a final season of eligibility.",
        sourceUrl: "https://www.sports-reference.com/cbb/players/dontaie-allen-1.html",
      },
      membership: { role: "PLAYER", jerseyNumber: 11, position: "Guard", yearsAtSchool: "2019-2022", statsNote: "Redshirt Freshman (2019-20) • 2019 KY Mr. Basketball • Famous 23-pt game vs MSU" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Pendleton County High School", season: "Senior", yearLabel: "Senior (ACL injury)", sortOrder: 1, pointsPerGame: 42.9, reboundsPerGame: 14.2, assistsPerGame: 5.0 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2019-2020", yearLabel: "Redshirt Freshman", sortOrder: 201, gamesPlayed: 0 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2020-2021", yearLabel: "Redshirt Sophomore", sortOrder: 202, gamesPlayed: 22, pointsPerGame: 5.4, reboundsPerGame: 1.7, assistsPerGame: 0.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2021-2022", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 18, pointsPerGame: 2.2, reboundsPerGame: 1.2, assistsPerGame: 0.2 },
      ],
      careerEvents: [
        { year: 2019, title: "Won Kentucky Mr. Basketball award", eventType: "AWARD" },
        { year: 2022, title: "Transferred to Western Kentucky University", eventType: "OTHER" },
      ],
    },
    {
      slug: "nate-sestina",
      firstName: "Nate",
      lastName: "Sestina",
      birthYear: 1997,
      hometown: "Emporium, PA",
      highSchool: "Cameron County High School, Emporium, PA",
      isFeatured: false,
      bio: "A graduate transfer from Bucknell who joined Kentucky for the 2019-20 season, bringing veteran stretch-four scoring. Committed to UK in April 2019.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "Olimpia Milano",
        league: "Italian Lega Basket Serie A / EuroLeague",
        location: "Milan, Italy",
        statusNote: "After his graduate year at Kentucky, Sestina built an impressive European career spanning Israel (Hapoel Holon), Turkey (Denizli Basket, Turk Telekom), EuroLeague with Fenerbahce (2023-24), Spain's Liga ACB with Valencia Basket (8.4 PPG on 43.4% from three), and now Olimpia Milano in Italy's Serie A and EuroLeague (signed October 2025). A Bucknell graduate who has risen to top-tier European basketball.",
        sourceUrl: "https://www.eurohoops.net/en/euroleague/1883231/nate-sestina-signs-with-olimpia-milan-euroleague/",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Forward", yearsAtSchool: "2019-2020", statsNote: "Graduate Senior (2019-20) • Transfer from Bucknell • Stretch four" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Cameron County High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 13.6, reboundsPerGame: 9.0, blocksPerGame: 1.0 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2019-2020", yearLabel: "Graduate Senior", sortOrder: 201, gamesPlayed: 30, pointsPerGame: 5.7, reboundsPerGame: 4.6, assistsPerGame: 0.7 },
      ],
      careerEvents: [
        { year: 2020, title: "Began professional career in Europe", eventType: "CAREER" },
        { year: 2025, title: "Signed with Olimpia Milano (EuroLeague)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "keion-brooks-2019",
      firstName: "Keion",
      lastName: "Brooks Jr.",
      birthYear: 2000,
      hometown: "Fort Wayne, IN",
      highSchool: "La Lumiere School, La Porte, IN",
      isFeatured: false,
      bio: "A four-star freshman forward who enrolled at Kentucky in 2019-20 and stayed for three seasons before transferring to Washington.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "Noblesville Boom (G League)",
        league: "NBA G League",
        location: "Indiana",
        statusNote: "Went undrafted in 2024 after three years at Kentucky and one at Washington. Played 14 games for the Pelicans in 2024-25 (10.1 PPG on a two-way contract). Now in the Pacers' G League affiliate (Noblesville Boom), working toward his first full NBA roster spot.",
        sourceUrl: "https://en.wikipedia.org/wiki/Keion_Brooks_Jr.",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Forward", yearsAtSchool: "2019-2022", statsNote: "Freshman (2019-20) • Four-star recruit from Fort Wayne" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "La Lumiere School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 11.8, reboundsPerGame: 7.2, blocksPerGame: 1.0 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2019-2020", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 28, pointsPerGame: 4.5, reboundsPerGame: 3.2, assistsPerGame: 0.4 },
      ],
      careerEvents: [
        { year: 2022, title: "Transferred to University of Washington", eventType: "OTHER" },
        { year: 2024, title: "Signed two-way deal with New Orleans Pelicans", eventType: "SIGNING" },
      ],
    },
    {
      slug: "john-calipari",
      firstName: "John",
      lastName: "Calipari",
      birthYear: 1959,
      hometown: "Moon Township, PA",
      highSchool: "Moon Area High School, Moon Township, PA",
      isFeatured: true,
      bio: "The architect of Kentucky's one-and-done era who produced more NBA Draft picks than any other coach in history. Led Kentucky to the 2012 national championship.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "University of Arkansas",
        league: "SEC",
        location: "Fayetteville, AR",
        statusNote: "After 15 seasons at Kentucky (2009-2024) with a 410-127 record, one national championship (2012), four Final Fours, and more NBA Draft picks than any coach in history, Calipari left for Arkansas in April 2024. He is building the Razorbacks in his image with heavy transfer portal use.",
        sourceUrl: "https://en.wikipedia.org/wiki/John_Calipari",
      },
      membership: {
        role: "HEAD_COACH",
        position: "Head Coach",
        yearsAtSchool: "2009-2024",
        statsNote: "30-7 in 2018-19 • Elite Eight",
      },
      careerEvents: [
        { year: 2012, title: "Won NCAA National Championship at Kentucky", eventType: "CHAMPIONSHIP" },
        { year: 2024, title: "Left Kentucky for Arkansas", eventType: "CAREER" },
      ],
    },
  ],
};
