import type { TeamSeed } from "./types";

export const kentuckyBasketball2018: TeamSeed = {
  slug: "kentucky-basketball-2018",
  name: "Kentucky Wildcats",
  season: "2017-2018",
  sport: "Men's Basketball",
  school: "University of Kentucky",
  conference: "SEC",
  accomplishment: "SEC Tournament Champions, Sweet Sixteen (26-11)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png",
  mascotName: "Wildcat",
  people: [
    {
      slug: "shai-gilgeous-alexander",
      firstName: "Shai",
      lastName: "Gilgeous-Alexander",
      birthYear: 1998,
      hometown: "Hamilton, ON, Canada",
      highSchool: "Hamilton Heights Christian Academy, Chattanooga, TN",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628983.png",
      bio: "A Canadian freshman guard who went from unranked recruit to lottery pick in one season. SGA averaged 14.4 PPG and 5.1 APG, leading Kentucky to the Sweet Sixteen.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Oklahoma City Thunder",
        league: "NBA",
        location: "Oklahoma City, OK",
        statusNote: "Drafted #11 by the Charlotte Hornets (traded to Clippers) in 2018, then traded to OKC in 2019. Won the 2024-25 NBA MVP award and is the front-runner for a repeat in 2025-26, averaging 31.7 PPG, 6.6 APG on 55% shooting. Tied Wilt Chamberlain's record of 126 consecutive games with 20+ points. Arguably the best player in the NBA.",
        sourceUrl: "https://en.wikipedia.org/wiki/Shai_Gilgeous-Alexander",
      },
      membership: { role: "PLAYER", jerseyNumber: 22, position: "Guard", yearsAtSchool: "2017-2018", statsNote: "Freshman • 14.4 PPG, 5.1 APG • #11 overall pick • Now NBA MVP" },
      careerEvents: [
        { year: 2018, title: "Selected #11 overall by Charlotte (traded to Clippers)", eventType: "DRAFT" },
        { year: 2019, title: "Traded to Oklahoma City Thunder", eventType: "TRADE" },
        { year: 2025, title: "Won NBA Most Valuable Player award", eventType: "AWARD" },
      ],
    },
    {
      slug: "kevin-knox",
      firstName: "Kevin",
      lastName: "Knox II",
      birthYear: 1999,
      hometown: "Tampa, FL",
      highSchool: "Tampa Catholic High School, Tampa, FL",
      isFeatured: false,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628995.png",
      bio: "A talented freshman forward who declared for the NBA Draft after one season and was selected #9 overall.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Windy City Bulls (G League)",
        league: "NBA G League",
        statusNote: "Drafted #9 by the New York Knicks in 2018. Played for the Knicks, Hawks, Pistons, Blazers, and Warriors. Now in the G League with the Windy City Bulls (16 PPG), working toward another NBA opportunity.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kevin_Knox_II",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Forward", yearsAtSchool: "2017-2018", statsNote: "Freshman • 15.6 PPG • #9 overall pick" },
      careerEvents: [
        { year: 2018, title: "Selected #9 overall by the New York Knicks", eventType: "DRAFT" },
      ],
    },
    {
      slug: "pj-washington",
      firstName: "PJ",
      lastName: "Washington",
      birthYear: 1998,
      hometown: "Dallas, TX",
      highSchool: "Findlay Prep, Henderson, NV",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/4278078.png",
      bio: "A freshman forward who would return for his sophomore year and become a lottery pick.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Dallas Mavericks",
        league: "NBA",
        location: "Dallas, TX",
        statusNote: "Returned for sophomore year. Drafted #12 overall in 2019 by Charlotte. Now with the Dallas Mavericks on a 4-year, $89M extension.",
        sourceUrl: "https://en.wikipedia.org/wiki/P._J._Washington",
      },
      membership: { role: "PLAYER", jerseyNumber: 25, position: "Forward", yearsAtSchool: "2017-2019", statsNote: "Freshman • 10.8 PPG, 5.7 RPG • Returned for sophomore year" },
      careerEvents: [
        { year: 2019, title: "Selected #12 overall by the Charlotte Hornets", eventType: "DRAFT" },
      ],
    },
    {
      slug: "hamidou-diallo",
      firstName: "Hamidou",
      lastName: "Diallo",
      birthYear: 1998,
      hometown: "Queens, NY",
      highSchool: "Putnam Science Academy, Putnam, CT",
      isFeatured: false,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628977.png",
      bio: "After redshirting in 2016-17, the explosive guard declared for the NBA Draft and won the 2019 Slam Dunk Contest.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Shanxi Loongs",
        league: "CBA (China)",
        statusNote: "Drafted #45 in 2018. Won the 2019 NBA Slam Dunk Contest. Now playing in China's CBA.",
        sourceUrl: "https://en.wikipedia.org/wiki/Hamidou_Diallo",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Guard", yearsAtSchool: "2016-2018", statsNote: "Redshirt Freshman • 10.0 PPG • 2019 Dunk Contest winner" },
      careerEvents: [
        { year: 2018, title: "Selected #45 overall by the Brooklyn Nets", eventType: "DRAFT" },
        { year: 2019, title: "Won NBA Slam Dunk Contest", eventType: "AWARD" },
      ],
    },
    {
      slug: "nick-richards",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/4395726.png",
      firstName: "Nick",
      lastName: "Richards",
      birthYear: 1997,
      hometown: "Kingston, Jamaica",
      highSchool: "The Patrick School, Elizabeth, NJ",
      isFeatured: false,
      bio: "A Jamaican freshman center who would stay three years at Kentucky and develop into a second-round NBA pick.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "Chicago Bulls",
        league: "NBA",
        location: "Chicago, IL",
        statusNote: "Stayed 3 years. Drafted #42 in 2020. Now with the Chicago Bulls after multiple trades.",
        sourceUrl: "https://www.basketball-reference.com/players/r/richani01.html",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Center", yearsAtSchool: "2017-2020", statsNote: "Freshman • 5.5 PPG, 3.3 RPG" },
      careerEvents: [{ year: 2020, title: "Selected #42 overall by Charlotte Hornets", eventType: "DRAFT" }],
    },
    {
      slug: "jarred-vanderbilt",
      firstName: "Jarred",
      lastName: "Vanderbilt",
      birthYear: 1999,
      hometown: "Houston, TX",
      highSchool: "Victory Prep Academy, Houston, TX",
      isFeatured: false,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628981.png",
      bio: "A freshman forward who declared for the NBA after one injury-plagued season and became a valued NBA role player.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Los Angeles Lakers",
        league: "NBA",
        location: "Los Angeles, CA",
        statusNote: "Drafted #41 in 2018. Has played for the Nuggets, Timberwolves, Jazz, and Lakers. On a 4-year, $48M extension with the Lakers, valued for his defense and energy.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jarred_Vanderbilt",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Forward", yearsAtSchool: "2017-2018", statsNote: "Freshman • Limited by injury • #41 overall pick" },
      careerEvents: [
        { year: 2018, title: "Selected #41 overall by Orlando (traded to Denver)", eventType: "DRAFT" },
        { year: 2023, title: "Signed 4-year, $48M extension with Lakers", eventType: "SIGNING" },
      ],
    },
    {
      slug: "quade-green",
      firstName: "Quade",
      lastName: "Green",
      birthYear: 1999,
      hometown: "Philadelphia, PA",
      highSchool: "Neumann-Goretti High School, Philadelphia, PA",
      isFeatured: false,
      bio: "A freshman point guard who transferred to Washington after his first year due to academic eligibility issues.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        location: "Free Agent",
        statusNote: "Transferred to Washington after freshman year. Went undrafted in 2021. Has been a journeyman across the G League, Mexico, Venezuela, Great Britain, Kosovo, and Morocco.",
        sourceUrl: "https://en.wikipedia.org/wiki/Quade_Green",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Point Guard", yearsAtSchool: "2017-2018", statsNote: "Freshman • 9.3 PPG • Transferred to Washington" },
      careerEvents: [{ year: 2018, title: "Transferred to University of Washington", eventType: "OTHER" }],
    },
    {
      slug: "wenyen-gabriel",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1629117.png",
      firstName: "Wenyen",
      lastName: "Gabriel",
      birthYear: 1997,
      hometown: "Manchester, NH",
      highSchool: "Wilbraham & Monson Academy, Wilbraham, MA",
      isFeatured: false,
      bio: "A sophomore forward who showed flashes with his 3-point shooting and defensive versatility.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "FC Bayern Munich",
        league: "German BBL / EuroLeague",
        location: "Munich, Germany",
        statusNote: "Played for 7 NBA teams. Now with FC Bayern Munich in Germany and EuroLeague.",
        sourceUrl: "https://en.wikipedia.org/wiki/Wenyen_Gabriel",
      },
      membership: { role: "PLAYER", jerseyNumber: 32, position: "Forward", yearsAtSchool: "2016-2018", statsNote: "Sophomore • Versatile wing" },
      careerEvents: [{ year: 2018, title: "Went undrafted; began pro career", eventType: "CAREER" }],
    },
    {
      slug: "jemarl-baker",
      firstName: "Jemarl",
      lastName: "Baker Jr.",
      birthYear: 1998,
      hometown: "Menifee, CA",
      highSchool: "Eleanor Roosevelt High School, Eastvale, CA",
      isFeatured: false,
      bio: "Missed his entire freshman season with a knee injury.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "Eisbaren Bremerhaven",
        league: "German ProA",
        location: "Germany",
        statusNote: "After transferring through Arizona, Fresno State, and New Mexico, Baker is now playing professionally in Germany.",
        sourceUrl: "https://basketball.eurobasket.com/player/Jemarl-Baker-Jr/421563",
      },
      membership: { role: "PLAYER", jerseyNumber: 13, position: "Guard", yearsAtSchool: "2017-2019", statsNote: "Freshman • Missed season with knee injury" },
      careerEvents: [{ year: 2019, title: "Transferred to University of Arizona", eventType: "OTHER" }],
    },
    {
      slug: "john-calipari",
      firstName: "John",
      lastName: "Calipari",
      birthYear: 1959,
      hometown: "Moon Township, PA",
      highSchool: "Moon Area High School, Moon Township, PA",
      isFeatured: true,
      bio: "Led a roster featuring the future NBA MVP (Shai Gilgeous-Alexander) to the Sweet Sixteen.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "University of Arkansas",
        league: "SEC",
        location: "Fayetteville, AR",
        statusNote: "Left Kentucky for Arkansas in April 2024.",
        sourceUrl: "https://en.wikipedia.org/wiki/John_Calipari",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2024", statsNote: "26-11 • SEC Tournament Champions • Sweet Sixteen • Future NBA MVP on roster" },
      careerEvents: [{ year: 2024, title: "Left Kentucky for Arkansas", eventType: "CAREER" }],
    },
  ],
};
