import type { TeamSeed } from "./types";

export const kentuckyBasketball2014: TeamSeed = {
  slug: "kentucky-basketball-2014",
  name: "Kentucky Wildcats",
  season: "2013-2014",
  sport: "Men's Basketball",
  school: "University of Kentucky",
  conference: "SEC",
  accomplishment: "NCAA Runner-up (29-11) — lost to UConn",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png",
  mascotName: "Wildcat",
  people: [
    {
      slug: "julius-randle",
      firstName: "Julius",
      lastName: "Randle",
      birthYear: 1994,
      hometown: "Dallas, TX",
      highSchool: "Prestonwood Christian Academy, Plano, TX",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/203944.png",
      bio: "A powerful 6-9 freshman forward who dominated with 24 double-doubles and led Kentucky to the championship game. Selected #7 overall by the Lakers.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Power Forward",
        currentEmployer: "Minnesota Timberwolves",
        league: "NBA",
        location: "Minneapolis, MN",
        statusNote: "A 3-time NBA All-Star with the New York Knicks, Randle was traded to the Minnesota Timberwolves in October 2024 in the Karl-Anthony Towns deal. Helped lead the Wolves to the Western Conference Finals in his first season.",
        sourceUrl: "https://en.wikipedia.org/wiki/Julius_Randle",
      },
      membership: { role: "PLAYER", jerseyNumber: 30, position: "Power Forward", yearsAtSchool: "2013-2014", statsNote: "NCAA Runner-up • 24 double-doubles • #7 pick", gamesPlayed: 40, pointsPerGame: 15.0, reboundsPerGame: 10.4, assistsPerGame: 1.4 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2013-14", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 40, pointsPerGame: 15.0, reboundsPerGame: 10.4 },
        { level: "PROFESSIONAL", teamName: "New York Knicks", season: "2020-21", yearLabel: "2020-21 (MIP)", sortOrder: 306, gamesPlayed: 71, pointsPerGame: 24.1, reboundsPerGame: 10.2, assistsPerGame: 6.0 },
        { level: "PROFESSIONAL", teamName: "Minnesota Timberwolves", season: "2024-25", yearLabel: "2024-25", sortOrder: 310, gamesPlayed: 69, pointsPerGame: 18.7, reboundsPerGame: 7.1, assistsPerGame: 4.7 },
      ],
      careerEvents: [
        { year: 2014, title: "NCAA Championship Game runner-up", eventType: "AWARD" },
        { year: 2014, title: "Selected #7 overall by the Los Angeles Lakers", eventType: "DRAFT" },
        { year: 2021, title: "Won NBA Most Improved Player", eventType: "AWARD" },
        { year: 2024, title: "Traded to Minnesota Timberwolves", eventType: "TRADE" },
      ],
    },
    {
      slug: "aaron-harrison",
      firstName: "Aaron",
      lastName: "Harrison",
      birthYear: 1994,
      hometown: "Richmond, TX",
      highSchool: "Travis High School, Richmond, TX",
      bio: "Hit THREE clutch tournament game-winning three-pointers during the 2014 NCAA run — vs Louisville, Michigan, and Wisconsin. One of the most iconic runs in tournament history.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Shooting Guard",
        currentEmployer: "G League / Overseas",
        league: "International",
        location: "Various",
        statusNote: "Went undrafted in 2015 and played briefly for the Charlotte Hornets. Has spent most of his career in the G League and overseas leagues. Will always be remembered for his clutch tournament shots.",
        sourceUrl: "https://en.wikipedia.org/wiki/Aaron_Harrison",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Shooting Guard", yearsAtSchool: "2013-2015", statsNote: "NCAA Runner-up • Hit 3 tournament game-winners", gamesPlayed: 40, pointsPerGame: 13.7, reboundsPerGame: 3.0, assistsPerGame: 1.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2013-14", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 40, pointsPerGame: 13.7 },
      ],
      careerEvents: [
        { year: 2014, title: "Hit game-winning threes vs Louisville, Michigan, and Wisconsin", eventType: "AWARD" },
      ],
    },
    {
      slug: "andrew-harrison",
      firstName: "Andrew",
      lastName: "Harrison",
      birthYear: 1994,
      hometown: "Richmond, TX",
      highSchool: "Travis High School, Richmond, TX",
      bio: "The starting point guard who led Kentucky to the championship game. Twin brother of Aaron. Drafted #44 overall in 2015.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Point Guard",
        currentEmployer: "Overseas",
        league: "International",
        location: "Europe",
        statusNote: "Played 3 seasons with the Memphis Grizzlies after being drafted #44 by the Suns (traded to Memphis). Has played professionally in Germany and Italy in recent years.",
        sourceUrl: "https://en.wikipedia.org/wiki/Andrew_Harrison_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Point Guard", yearsAtSchool: "2013-2015", statsNote: "NCAA Runner-up • #44 pick", gamesPlayed: 40, pointsPerGame: 10.9, reboundsPerGame: 2.6, assistsPerGame: 4.0 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2013-14", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 40, pointsPerGame: 10.9, assistsPerGame: 4.0 },
      ],
      careerEvents: [
        { year: 2014, title: "NCAA Championship Game runner-up", eventType: "AWARD" },
        { year: 2015, title: "Selected #44 overall by the Phoenix Suns", eventType: "DRAFT" },
      ],
    },
    {
      slug: "james-young",
      firstName: "James",
      lastName: "Young",
      birthYear: 1995,
      hometown: "Rochester, MI",
      highSchool: "Rochester High School, Rochester Hills, MI",
      bio: "A smooth-scoring freshman wing who scored 20 points in the championship game despite the loss. #17 pick by the Celtics.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Shooting Guard / Small Forward",
        currentEmployer: "Overseas",
        league: "International",
        location: "Europe",
        statusNote: "Selected #17 by the Boston Celtics in 2014, Young played 3 seasons for Boston before moving overseas. Has played in Italy, Israel, and the G League in recent years.",
        sourceUrl: "https://en.wikipedia.org/wiki/James_Young_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Small Forward", yearsAtSchool: "2013-2014", statsNote: "NCAA Runner-up • #17 pick", gamesPlayed: 40, pointsPerGame: 14.3, reboundsPerGame: 4.3, assistsPerGame: 1.7 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2013-14", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 40, pointsPerGame: 14.3 },
      ],
      careerEvents: [
        { year: 2014, title: "Scored 20 in NCAA Championship Game", eventType: "AWARD" },
        { year: 2014, title: "Selected #17 overall by the Boston Celtics", eventType: "DRAFT" },
      ],
    },
    {
      slug: "willie-cauley-stein",
      firstName: "Willie",
      lastName: "Cauley-Stein",
      birthYear: 1993,
      hometown: "Spearville, KS",
      highSchool: "Olathe Northwest High School, Olathe, KS",
      bio: "The 7-foot sophomore was injured during the tournament run and missed the final games but was a key piece of the frontcourt.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "Overseas / G League",
        league: "International",
        location: "Various",
        statusNote: "Selected #6 overall by the Sacramento Kings in 2015. Played 8 NBA seasons before moving to G League and overseas leagues. Known for his art and painting outside basketball.",
        sourceUrl: "https://en.wikipedia.org/wiki/Willie_Cauley-Stein",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Center", yearsAtSchool: "2012-2015", statsNote: "NCAA Runner-up • Future #6 pick", gamesPlayed: 34, pointsPerGame: 7.2, reboundsPerGame: 6.2, assistsPerGame: 0.7 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2013-14", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 34, pointsPerGame: 7.2, reboundsPerGame: 6.2 },
      ],
      careerEvents: [
        { year: 2015, title: "Selected #6 overall by the Sacramento Kings", eventType: "DRAFT" },
      ],
    },
    {
      slug: "dakari-johnson",
      firstName: "Dakari",
      lastName: "Johnson",
      birthYear: 1995,
      hometown: "Brooklyn, NY",
      highSchool: "Montverde Academy, Montverde, FL",
      bio: "A freshman backup center who stepped up during the tournament run when Cauley-Stein was injured. Later the #48 pick by the Thunder.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "Overseas",
        league: "International",
        location: "Europe",
        statusNote: "Selected #48 by OKC in 2015. Played briefly in the NBA before a lengthy overseas career in Spain, Turkey, Israel and other European leagues.",
        sourceUrl: "https://en.wikipedia.org/wiki/Dakari_Johnson",
      },
      membership: { role: "PLAYER", jerseyNumber: 44, position: "Center", yearsAtSchool: "2013-2015", statsNote: "NCAA Runner-up • Future #48 pick", gamesPlayed: 40, pointsPerGame: 5.4, reboundsPerGame: 4.2, assistsPerGame: 0.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2013-14", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 40, pointsPerGame: 5.4, reboundsPerGame: 4.2 },
      ],
      careerEvents: [
        { year: 2015, title: "Selected #48 overall by Oklahoma City Thunder", eventType: "DRAFT" },
      ],
    },
    {
      slug: "marcus-lee",
      firstName: "Marcus",
      lastName: "Lee",
      birthYear: 1995,
      hometown: "Antioch, CA",
      highSchool: "Deer Valley High School, Antioch, CA",
      bio: "A high-flying freshman forward who had a memorable dunk-fest performance in the Elite Eight win over Michigan.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Overseas",
        league: "International",
        location: "Australia / Asia",
        statusNote: "Transferred to Cal for his senior year. Has played professionally in Australia's NBL with Melbourne United and other overseas leagues.",
        sourceUrl: "https://en.wikipedia.org/wiki/Marcus_Lee_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Power Forward", yearsAtSchool: "2013-2017", statsNote: "NCAA Runner-up", gamesPlayed: 40, pointsPerGame: 1.6, reboundsPerGame: 1.8, assistsPerGame: 0.1 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2013-14", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 40, pointsPerGame: 1.6 },
      ],
      careerEvents: [],
    },
    {
      slug: "alex-poythress",
      firstName: "Alex",
      lastName: "Poythress",
      birthYear: 1993,
      hometown: "Clarksville, TN",
      highSchool: "Northeast High School, Clarksville, TN",
      bio: "A sophomore forward who provided veteran leadership to the young roster.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Overseas",
        league: "International",
        location: "Europe",
        statusNote: "After graduating from Kentucky in 2016, Poythress went undrafted but had brief NBA stints with the Pacers and Pistons. Has spent most of his career overseas.",
        sourceUrl: "https://en.wikipedia.org/wiki/Alex_Poythress",
      },
      membership: { role: "PLAYER", jerseyNumber: 22, position: "Power Forward", yearsAtSchool: "2012-2016", statsNote: "NCAA Runner-up", gamesPlayed: 40, pointsPerGame: 5.9, reboundsPerGame: 3.9, assistsPerGame: 0.4 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2013-14", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 40, pointsPerGame: 5.9, reboundsPerGame: 3.9 },
      ],
      careerEvents: [],
    },
    {
      slug: "derek-willis",
      firstName: "Derek",
      lastName: "Willis",
      birthYear: 1995,
      hometown: "Bullitt County, KY",
      highSchool: "Bullitt East High School, Mt. Washington, KY",
      bio: "A Kentucky native freshman who was a rotation reserve on the championship game team.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Overseas",
        league: "International",
        location: "Europe",
        statusNote: "Has played professionally in Germany, Turkey, France, and Israel after going undrafted in 2017.",
        sourceUrl: "https://en.wikipedia.org/wiki/Derek_Willis",
      },
      membership: { role: "PLAYER", jerseyNumber: 35, position: "Power Forward", yearsAtSchool: "2013-2017", statsNote: "Kentucky native • NCAA Runner-up", gamesPlayed: 15, pointsPerGame: 0.9, reboundsPerGame: 0.6 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2013-14", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 15, pointsPerGame: 0.9 },
      ],
      careerEvents: [],
    },
    {
      slug: "jarrod-polson",
      firstName: "Jarrod",
      lastName: "Polson",
      birthYear: 1991,
      hometown: "Nicholasville, KY",
      highSchool: "West Jessamine High School, Nicholasville, KY",
      bio: "The senior captain walk-on turned scholarship player — a fan favorite who represented the heart of Kentucky basketball.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Nicholasville, KY",
        statusNote: "After graduating, Polson returned to Kentucky and works in the local area. Part of two Final Four teams and the 2012 championship.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/jarrod-polson/",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Guard", yearsAtSchool: "2010-2014", statsNote: "NCAA Runner-up • Senior captain walk-on", gamesPlayed: 27, pointsPerGame: 1.1 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2013-14", yearLabel: "Senior (walk-on)", sortOrder: 204, gamesPlayed: 27, pointsPerGame: 1.1 },
      ],
      careerEvents: [],
    },
    {
      slug: "dominique-hawkins",
      firstName: "Dominique",
      lastName: "Hawkins",
      birthYear: 1994,
      hometown: "Richmond, KY",
      highSchool: "Madison Central High School, Richmond, KY",
      bio: "The 2013 Kentucky Mr. Basketball who became a scholarship freshman guard on the runner-up team.",
      status: {
        occupationType: "COACH",
        currentTitle: "Coach / Community Basketball",
        location: "Richmond, KY",
        statusNote: "Kentucky Mr. Basketball who walked on, earned a scholarship, and played on two Final Four teams. Has stayed involved with Kentucky basketball.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/dominique-hawkins/",
      },
      membership: { role: "PLAYER", jerseyNumber: 25, position: "Point Guard", yearsAtSchool: "2013-2017", statsNote: "Kentucky native • NCAA Runner-up", gamesPlayed: 21, pointsPerGame: 0.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2013-14", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 21, pointsPerGame: 0.8 },
      ],
      careerEvents: [],
    },
    {
      slug: "jon-hood",
      firstName: "Jon",
      lastName: "Hood",
      birthYear: 1990,
      hometown: "Madisonville, KY",
      highSchool: "Madisonville North Hopkins HS, Madisonville, KY",
      bio: "A senior Kentucky native walk-on and beloved veteran of the program.",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Coach",
        currentEmployer: "Kentucky High School",
        location: "Kentucky",
        statusNote: "After his Kentucky career that included a championship (2012) and runner-up (2014), Hood has coached at the high school level in Kentucky.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jon_Hood",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Guard", yearsAtSchool: "2009-2014", statsNote: "Senior • NCAA Runner-up", gamesPlayed: 19, pointsPerGame: 0.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2013-14", yearLabel: "Senior", sortOrder: 204, gamesPlayed: 19, pointsPerGame: 0.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "tod-lanter",
      firstName: "Tod",
      lastName: "Lanter",
      birthYear: 1992,
      hometown: "Frankfort, KY",
      highSchool: "Western Hills High School, Frankfort, KY",
      bio: "A Kentucky native junior walk-on guard on the championship game team.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Kentucky",
        statusNote: "The Frankfort native walk-on is part of Kentucky's long tradition of local walk-on contributors.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/tod-lanter/",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Guard", yearsAtSchool: "2011-2015", statsNote: "Junior walk-on • NCAA Runner-up", gamesPlayed: 15 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2013-14", yearLabel: "Junior (walk-on)", sortOrder: 203, gamesPlayed: 15 },
      ],
      careerEvents: [],
    },
    {
      slug: "sam-malone",
      firstName: "Sam",
      lastName: "Malone",
      birthYear: 1993,
      hometown: "El Dorado, AR",
      highSchool: "El Dorado High School, El Dorado, AR",
      bio: "A junior walk-on guard and son of NBA legend Karl Malone on the 2014 NCAA runner-up team.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Louisiana",
        statusNote: "Son of Hall of Famer Karl Malone, Sam finished his Kentucky career as a walk-on and has since kept a low profile in business outside basketball.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/sam-malone/",
      },
      membership: { role: "PLAYER", jerseyNumber: 14, position: "Guard", yearsAtSchool: "2011-2015", statsNote: "Junior walk-on • NCAA Runner-up", gamesPlayed: 10 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2013-14", yearLabel: "Junior (walk-on)", sortOrder: 202, gamesPlayed: 10 },
      ],
      careerEvents: [],
    },
    {
      slug: "brian-long",
      firstName: "Brian",
      lastName: "Long",
      birthYear: 1993,
      hometown: "Lexington, KY",
      highSchool: "Lexington Catholic High School, Lexington, KY",
      bio: "A Lexington native junior walk-on forward on the NCAA runner-up squad.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Lexington, KY",
        statusNote: "A hometown walk-on who earned his Kentucky degree, Long has remained in the Lexington area after his playing career.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/brian-long/",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Forward", yearsAtSchool: "2011-2015", statsNote: "Junior walk-on • NCAA Runner-up", gamesPlayed: 9 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2013-14", yearLabel: "Junior (walk-on)", sortOrder: 202, gamesPlayed: 9 },
      ],
      careerEvents: [],
    },
    {
      slug: "ej-floreal",
      firstName: "EJ",
      lastName: "Floreal",
      birthYear: 1994,
      hometown: "Lexington, KY",
      highSchool: "Paul Laurence Dunbar HS, Lexington, KY",
      bio: "A sophomore walk-on forward and son of Kentucky track coach Edrick Floreal on the NCAA runner-up team.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Lexington, KY",
        statusNote: "Son of longtime track coach Edrick Floreal, EJ remained around the Lexington area after his Kentucky basketball career.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/ej-floreal/",
      },
      membership: { role: "PLAYER", jerseyNumber: 21, position: "Forward", yearsAtSchool: "2012-2015", statsNote: "Sophomore walk-on • NCAA Runner-up", gamesPlayed: 8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2013-14", yearLabel: "Sophomore (walk-on)", sortOrder: 202, gamesPlayed: 8 },
      ],
      careerEvents: [],
    },
    {
      slug: "orlando-antigua",
      firstName: "Orlando",
      lastName: "Antigua",
      birthYear: 1975,
      hometown: "New York, NY",
      highSchool: "George Washington High School, New York, NY",
      bio: "Dominican-American assistant who followed Calipari from Memphis. Top recruiter, especially with international talent. First Dominican-born D1 coach.",
      status: {
        occupationType: "COACH",
        currentTitle: "Associate Head Coach",
        currentEmployer: "University of Illinois",
        location: "Champaign, IL",
        statusNote: "Antigua was a Kentucky assistant (2009-2014, 2021-2024), sandwiching stints as South Florida HC and Illinois associate HC. After Calipari left for Arkansas in 2024, Antigua returned to Illinois under Brad Underwood.",
        sourceUrl: "https://en.wikipedia.org/wiki/Orlando_Antigua",
      },
      membership: { role: "ASSISTANT_COACH", position: "Assistant Coach", yearsAtSchool: "2009-2014" },
      careerEvents: [],
    },
    {
      slug: "kenny-payne",
      firstName: "Kenny",
      lastName: "Payne",
      birthYear: 1966,
      hometown: "Louisville, KY",
      highSchool: "Shawnee High School, Louisville, KY",
      bio: "Kentucky's primary big-man developer for a decade. Former NBA player and Louisville native. His post coaching was key to multiple lottery picks.",
      status: {
        occupationType: "COACH",
        currentTitle: "Associate Head Coach",
        currentEmployer: "University of Arkansas",
        location: "Fayetteville, AR",
        statusNote: "After 10 years as Kentucky assistant (2010-2020), Payne became Louisville HC but was fired in 2024 after going 12-52. He reunited with Calipari at Arkansas as associate HC.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kenny_Payne",
      },
      membership: { role: "ASSISTANT_COACH", position: "Associate Head Coach", yearsAtSchool: "2010-2020" },
      careerEvents: [],
    },
    {
      slug: "john-calipari",
      firstName: "John",
      lastName: "Calipari",
      birthYear: 1959,
      hometown: "Moon Township, PA",
      highSchool: "Moon Area High School, Moon Township, PA",
      bio: "Took one of his youngest rosters ever to the NCAA Championship Game — ultimately losing to UConn in one of the most memorable tournament runs in Kentucky history.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "University of Arkansas",
        league: "SEC",
        location: "Fayetteville, AR",
        statusNote: "Left Kentucky for Arkansas in April 2024 on a 5-year, $35M deal after 15 seasons at UK.",
        sourceUrl: "https://en.wikipedia.org/wiki/John_Calipari",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2024", statsNote: "29-11 • NCAA Runner-up" },
      careerEvents: [],
    },
  ],
};
