import type { TeamSeed } from "./types";

export const kentuckyBasketball2020: TeamSeed = {
  slug: "kentucky-basketball-2020",
  name: "Kentucky Wildcats",
  season: "2019-2020",
  sport: "Men's Basketball",
  school: "University of Kentucky",
  conference: "SEC",
  accomplishment: "SEC Champions (25-6, NCAA Tournament cancelled)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png",
  mascotName: "Wildcat",
  people: [
    {
      slug: "tyrese-maxey",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1630178.png",
      firstName: "Tyrese",
      lastName: "Maxey",
      birthYear: 2000,
      hometown: "Garland, TX",
      highSchool: "South Garland High School, Garland, TX",
      isFeatured: true,
      bio: "A dynamic freshman guard who became the team's go-to scorer. Maxey declared for the NBA Draft after one electrifying season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Philadelphia 76ers",
        league: "NBA",
        location: "Philadelphia, PA",
        statusNote: "Drafted 21st overall by the 76ers in 2020, Maxey won the 2024 NBA Most Improved Player award and has become one of the league's premier guards. Averaging 28.8 PPG and 6.8 APG in 2025-26.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tyrese_Maxey",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Guard", yearsAtSchool: "2019-2020", statsNote: "Freshman • 14.0 PPG • SEC Champions", gamesPlayed: 31, pointsPerGame: 14.0, reboundsPerGame: 3.7, assistsPerGame: 3.2 },
      careerEvents: [
        { year: 2020, title: "Selected #21 overall by the Philadelphia 76ers", eventType: "DRAFT" },
        { year: 2024, title: "Won NBA Most Improved Player award", eventType: "AWARD" },
      ],
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "South Garland High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 26.0, reboundsPerGame: 3.7, assistsPerGame: 6.2 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2019-20", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 31, minutesPerGame: 30.3, pointsPerGame: 14.0, reboundsPerGame: 3.7, assistsPerGame: 3.2, stealsPerGame: 0.9, fieldGoalPct: 0.427, threePointPct: 0.292, freeThrowPct: 0.833 },
        { level: "PROFESSIONAL", teamName: "Philadelphia 76ers", season: "2020-21", yearLabel: "2020-21", sortOrder: 301, gamesPlayed: 61, minutesPerGame: 15.3, pointsPerGame: 8.0, reboundsPerGame: 1.7, assistsPerGame: 2.0, stealsPerGame: 0.4, fieldGoalPct: 0.462, threePointPct: 0.301, freeThrowPct: 0.870 },
        { level: "PROFESSIONAL", teamName: "Philadelphia 76ers", season: "2021-22", yearLabel: "2021-22", sortOrder: 302, gamesPlayed: 75, minutesPerGame: 35.3, pointsPerGame: 17.5, reboundsPerGame: 3.5, assistsPerGame: 4.3, stealsPerGame: 0.7, fieldGoalPct: 0.485, threePointPct: 0.405, freeThrowPct: 0.866 },
        { level: "PROFESSIONAL", teamName: "Philadelphia 76ers", season: "2022-23", yearLabel: "2022-23", sortOrder: 303, gamesPlayed: 60, minutesPerGame: 34.6, pointsPerGame: 20.3, reboundsPerGame: 3.5, assistsPerGame: 3.5, fieldGoalPct: 0.481, threePointPct: 0.382, freeThrowPct: 0.849 },
        { level: "PROFESSIONAL", teamName: "Philadelphia 76ers", season: "2023-24", yearLabel: "2023-24 (MIP)", sortOrder: 304, gamesPlayed: 70, minutesPerGame: 37.5, pointsPerGame: 25.9, reboundsPerGame: 3.7, assistsPerGame: 6.2, stealsPerGame: 1.0, fieldGoalPct: 0.450, threePointPct: 0.371, freeThrowPct: 0.870 },
        { level: "PROFESSIONAL", teamName: "Philadelphia 76ers", season: "2025-26", yearLabel: "2025-26", sortOrder: 306, gamesPlayed: 55, pointsPerGame: 28.8, assistsPerGame: 6.8, fieldGoalPct: 0.470 },
      ],
    },
    {
      slug: "immanuel-quickley",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1630193.png",
      firstName: "Immanuel",
      lastName: "Quickley",
      birthYear: 1999,
      hometown: "Havre de Grace, MD",
      highSchool: "The John Carroll School, Bel Air, MD",
      isFeatured: true,
      bio: "Blossomed into the SEC Player of the Year as a sophomore after a quiet freshman season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Point Guard",
        currentEmployer: "Toronto Raptors",
        league: "NBA",
        location: "Toronto, ON",
        statusNote: "Drafted 25th overall in 2020. Signed 5-year, $162.5M max contract with the Raptors in 2024. Averaging 17.0 PPG in 2025-26.",
        sourceUrl: "https://en.wikipedia.org/wiki/Immanuel_Quickley",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Guard", yearsAtSchool: "2018-2020", statsNote: "Sophomore • SEC Player of the Year • 16.1 PPG", gamesPlayed: 31, pointsPerGame: 16.1, reboundsPerGame: 4.2, assistsPerGame: 1.9 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "The John Carroll School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 29.2, reboundsPerGame: 4.2, assistsPerGame: 4.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2019-2020", yearLabel: "Sophomore", sortOrder: 201, gamesPlayed: 31, pointsPerGame: 16.1, reboundsPerGame: 4.2, assistsPerGame: 1.9 },
      
        { level: "PROFESSIONAL", teamName: "New York Knicks", season: "2020-21", yearLabel: "2020-21 (Rookie)", sortOrder: 301, gamesPlayed: 64, pointsPerGame: 11.4, reboundsPerGame: 2.1, assistsPerGame: 2.0 },
        { level: "PROFESSIONAL", teamName: "New York Knicks", season: "2021-22", yearLabel: "2021-22", sortOrder: 302, gamesPlayed: 78, pointsPerGame: 11.3, reboundsPerGame: 3.2, assistsPerGame: 3.5 },
        { level: "PROFESSIONAL", teamName: "New York Knicks", season: "2022-23", yearLabel: "2022-23", sortOrder: 303, gamesPlayed: 81, pointsPerGame: 14.9, reboundsPerGame: 4.1, assistsPerGame: 3.4 },
        { level: "PROFESSIONAL", teamName: "NYK / Toronto Raptors", season: "2023-24", yearLabel: "2023-24 (traded)", sortOrder: 304, gamesPlayed: 38, pointsPerGame: 18.6, reboundsPerGame: 4.8, assistsPerGame: 6.8 },
        { level: "PROFESSIONAL", teamName: "Toronto Raptors", season: "2024-25", yearLabel: "2024-25 ($162.5M)", sortOrder: 305, gamesPlayed: 33, pointsPerGame: 15.3, reboundsPerGame: 4.0, assistsPerGame: 4.0 },
        { level: "PROFESSIONAL", teamName: "Toronto Raptors", season: "2025-26", yearLabel: "2025-26", sortOrder: 306, gamesPlayed: 55, pointsPerGame: 17.0, reboundsPerGame: 4.2, assistsPerGame: 6.0 },
      ],
      careerEvents: [
        { year: 2020, title: "Won SEC Player of the Year", eventType: "AWARD" },
        { year: 2020, title: "Selected #25 overall by the New York Knicks", eventType: "DRAFT" },
      ],
    },
    {
      slug: "nick-richards",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1630208.png",
      firstName: "Nick",
      lastName: "Richards",
      birthYear: 1997,
      hometown: "Kingston, Jamaica",
      highSchool: "The Patrick School, Elizabeth, NJ",
      isFeatured: false,
      bio: "A junior center who developed into a dominant interior force and SEC Defensive POY candidate.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "Chicago Bulls",
        league: "NBA",
        location: "Chicago, IL",
        statusNote: "Drafted 42nd overall in 2020 by Charlotte. Now with the Chicago Bulls after multiple trades in 2025-26.",
        sourceUrl: "https://www.basketball-reference.com/players/r/richani01.html",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Center", yearsAtSchool: "2017-2020", statsNote: "Junior • 14.0 PPG, 7.8 RPG • SEC Defensive POY candidate" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "The Patrick School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 8.8, reboundsPerGame: 6.0, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2017-2018", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 2.5, reboundsPerGame: 2.3, assistsPerGame: 0.2 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2018-2019", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 36, pointsPerGame: 4.0, reboundsPerGame: 3.6, assistsPerGame: 0.3 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2019-2020", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 31, pointsPerGame: 14.0, reboundsPerGame: 7.8, assistsPerGame: 0.6 },
      
        { level: "PROFESSIONAL", teamName: "Charlotte Hornets", season: "2020-21", yearLabel: "2020-21 (Rookie)", sortOrder: 301, gamesPlayed: 23, pointsPerGame: 2.4, reboundsPerGame: 1.4, assistsPerGame: 0.2 },
        { level: "PROFESSIONAL", teamName: "Charlotte Hornets", season: "2021-22", yearLabel: "2021-22", sortOrder: 302, gamesPlayed: 64, pointsPerGame: 4.1, reboundsPerGame: 3.7, assistsPerGame: 0.4 },
        { level: "PROFESSIONAL", teamName: "Charlotte Hornets", season: "2022-23", yearLabel: "2022-23", sortOrder: 303, gamesPlayed: 74, pointsPerGame: 9.2, reboundsPerGame: 5.5, assistsPerGame: 0.5 },
        { level: "PROFESSIONAL", teamName: "Charlotte Hornets", season: "2023-24", yearLabel: "2023-24", sortOrder: 304, gamesPlayed: 60, pointsPerGame: 8.0, reboundsPerGame: 5.0, assistsPerGame: 0.6 },
        { level: "PROFESSIONAL", teamName: "CHA / PHX / CHI", season: "2025-26", yearLabel: "2025-26 (traded 3x)", sortOrder: 306, gamesPlayed: 50, pointsPerGame: 5.8, reboundsPerGame: 5.1, assistsPerGame: 0.4 },
      ],
      careerEvents: [
        { year: 2020, title: "Selected #42 overall by the Charlotte Hornets", eventType: "DRAFT" },
      ],
    },
    {
      slug: "ashton-hagans",
      firstName: "Ashton",
      lastName: "Hagans",
      birthYear: 1999,
      hometown: "Cartersville, GA",
      highSchool: "Newton High School, Covington, GA",
      isFeatured: false,
      bio: "Returned as a sophomore but left the team late in the season for personal reasons.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Rip City Remix (G League)",
        league: "NBA G League",
        location: "Portland, OR",
        statusNote: "A defense-first point guard who led the SEC in steals as both a freshman and sophomore. Left Kentucky early for the 2020 NBA Draft but went undrafted. Has bounced between the G League (Stockton Kings, Austin Spurs), China's CBA (Xinjiang Flying Tigers), NBL Australia (Cairns Taipans), and currently the Rip City Remix (Portland's G League affiliate). Named a G League All-Star previously. Still chasing his NBA dream at 26.",
        sourceUrl: "https://en.wikipedia.org/wiki/Ashton_Hagans",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Point Guard", yearsAtSchool: "2018-2020", statsNote: "Sophomore • Left team late season" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Newton High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 16.6, reboundsPerGame: 3.4, assistsPerGame: 7.6 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2018-2019", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 7.7, reboundsPerGame: 3.4, assistsPerGame: 4.3 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2019-2020", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 30, pointsPerGame: 11.5, reboundsPerGame: 3.7, assistsPerGame: 6.4 },
      ],
      careerEvents: [{ year: 2020, title: "Went undrafted; began professional career", eventType: "CAREER" }],
    },
    {
      slug: "nate-sestina",
      firstName: "Nate",
      lastName: "Sestina",
      birthYear: 1997,
      hometown: "Emporium, PA",
      highSchool: "Cameron County High School, Emporium, PA",
      isFeatured: false,
      bio: "A graduate transfer from Bucknell who provided veteran leadership and stretch-four scoring.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "Olimpia Milano",
        league: "Italian Lega Basket Serie A / EuroLeague",
        location: "Milan, Italy",
        statusNote: "After his graduate year at Kentucky, Sestina built an impressive European career: Israel (Hapoel Holon), Turkey (Denizli Basket, Turk Telekom), EuroLeague debut with Fenerbahce (2023-24), Spain's Valencia Basket (8.4 PPG on 43.4% from three across 33 Liga ACB games), and now Olimpia Milano in Italy's Serie A and EuroLeague (signed October 2025). A Bucknell graduate who has risen to the top tier of European basketball.",
        sourceUrl: "https://www.eurohoops.net/en/euroleague/1883231/nate-sestina-signs-with-olimpia-milan-euroleague/",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Forward", yearsAtSchool: "2019-2020", statsNote: "Graduate Senior • Transfer from Bucknell • Stretch four" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Cameron County High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 13.6, reboundsPerGame: 9.0, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2019-2020", yearLabel: "Graduate Senior", sortOrder: 201, gamesPlayed: 30, pointsPerGame: 5.7, reboundsPerGame: 4.6, assistsPerGame: 0.7 },
      ],
      careerEvents: [
        { year: 2020, title: "Began professional career in Europe", eventType: "CAREER" },
        { year: 2025, title: "Signed with Olimpia Milano (EuroLeague)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "keion-brooks",
      firstName: "Keion",
      lastName: "Brooks Jr.",
      birthYear: 2000,
      hometown: "Fort Wayne, IN",
      highSchool: "La Lumiere School, La Porte, IN",
      isFeatured: false,
      bio: "A four-star freshman forward who played three years at Kentucky before transferring to Washington.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "Noblesville Boom (G League)",
        league: "NBA G League",
        location: "Indiana",
        statusNote: "Went undrafted in 2024 after college at Kentucky (3 years) and Washington (1 year). Played 14 games for the Pelicans in 2024-25 (10.1 PPG). Now with the Pacers' G League affiliate.",
        sourceUrl: "https://en.wikipedia.org/wiki/Keion_Brooks_Jr.",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Forward", yearsAtSchool: "2019-2022", statsNote: "Freshman • Four-star recruit" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "La Lumiere School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 11.8, reboundsPerGame: 7.2, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2019-2020", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 28, pointsPerGame: 4.5, reboundsPerGame: 3.2, assistsPerGame: 0.4 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2020-2021", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 18, pointsPerGame: 10.3, reboundsPerGame: 4.4, assistsPerGame: 0.8 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2021-2022", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 34, pointsPerGame: 10.8, reboundsPerGame: 4.4, assistsPerGame: 1.2 },
      ],
      careerEvents: [
        { year: 2024, title: "Went undrafted; signed with New Orleans Pelicans", eventType: "SIGNING" },
      ],
    },
    {
      slug: "johnny-juzang",
      firstName: "Johnny",
      lastName: "Juzang",
      birthYear: 2001,
      hometown: "Los Angeles, CA",
      highSchool: "Harvard-Westlake School, Los Angeles, CA",
      isFeatured: false,
      bio: "A talented freshman guard who transferred to UCLA after one season and famously led the Bruins to the 2021 Final Four.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "Zenit Saint Petersburg",
        league: "VTB United League (Russia)",
        location: "Saint Petersburg, Russia",
        statusNote: "Transferred to UCLA and became a national sensation leading the 11-seed Bruins to the 2021 Final Four (22.8 PPG in the tournament). Signed with the Utah Jazz and played three seasons (102 games, up to 8.9 PPG with 37.6% three-point shooting). Waived by Utah in 2025, signed with the Timberwolves (21 games) before being waived in February 2026 and signing with Zenit Saint Petersburg in Russia's VTB United League.",
        sourceUrl: "https://www.hoopsrumors.com/2026/02/johnny-juzang-signs-with-zenit-bc.html",
      },
      membership: { role: "PLAYER", jerseyNumber: 10, position: "Guard", yearsAtSchool: "2019-2020", statsNote: "Freshman • Transferred to UCLA • Led UCLA to 2021 Final Four" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Harvard-Westlake School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 9.3, reboundsPerGame: 1.9, assistsPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2019-2020", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 28, pointsPerGame: 2.9, reboundsPerGame: 1.9, assistsPerGame: 0.4 },
      ],
      careerEvents: [
        { year: 2020, title: "Transferred to UCLA", eventType: "OTHER" },
        { year: 2021, title: "Led UCLA to Final Four as Most Outstanding Player candidate", eventType: "CAREER" },
      ],
    },
    {
      slug: "kahlil-whitney",
      firstName: "Kahlil",
      lastName: "Whitney",
      birthYear: 2001,
      hometown: "Chicago, IL",
      highSchool: "Roselle Catholic High School, Roselle, NJ",
      isFeatured: false,
      bio: "A five-star recruit who left the team mid-season in January 2020 and declared for the NBA Draft.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "China NBL",
        statusNote: "One of the most cautionary tales of the one-and-done era. Left Kentucky mid-season as a five-star recruit, went undrafted, and bounced through the G League (Greensboro, RGV), Mexico, Croatia, New Zealand, and China (Suke Lions). In summer 2025 he returned to play for Kentucky's La Familia TBT team. On February 18, 2026, he announced he is exploring a return to college basketball, stating 'Recruitment officially open' and seeking NCAA reinstatement.",
        sourceUrl: "https://www.on3.com/teams/kentucky-wildcats/news/return-of-the-dragon-kahlil-whitney-wants-to-return-to-college-basketball/",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Forward", yearsAtSchool: "2019-2020", statsNote: "Freshman • Five-star recruit • Left team mid-season" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Roselle Catholic High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 9.9, reboundsPerGame: 4.6, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2019-2020", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 10, pointsPerGame: 3.3, reboundsPerGame: 1.2, assistsPerGame: 0.3 },
      ],
      careerEvents: [
        { year: 2020, title: "Left Kentucky mid-season; declared for NBA Draft", eventType: "OTHER" },
      ],
    },
    {
      slug: "ej-montgomery",
      firstName: "EJ",
      lastName: "Montgomery",
      birthYear: 1999,
      hometown: "Fort Pierce, FL",
      highSchool: "Wheeler High School, Marietta, GA",
      isFeatured: false,
      bio: "Sophomore forward who declared for the NBA Draft after this season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "MKS Dabrowa Gornicza",
        league: "Polish Basketball League",
        location: "Poland",
        statusNote: "A five-star recruit who played two seasons at Kentucky before going undrafted in 2020. Spent time in the G League (Birmingham Squadron) and has played overseas in multiple countries. Currently averaging 7.4 PPG and 7.9 RPG with MKS Dabrowa Gornicza in Poland's PLK, carving out a professional career in European basketball.",
        sourceUrl: "https://www.proballers.com/basketball/player/178401/montgomery-e-j",
      },
      membership: { role: "PLAYER", jerseyNumber: 23, position: "Forward", yearsAtSchool: "2018-2020", statsNote: "Sophomore • Declared for NBA Draft" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Wheeler High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 10.7, reboundsPerGame: 8.5, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2018-2019", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 35, pointsPerGame: 3.8, reboundsPerGame: 4.2, assistsPerGame: 0.4 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2019-2020", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 31, pointsPerGame: 5.8, reboundsPerGame: 5.2, assistsPerGame: 0.6 },
      ],
      careerEvents: [{ year: 2020, title: "Went undrafted; began overseas career", eventType: "CAREER" }],
    },
    {
      slug: "dontaie-allen-2020",
      firstName: "Dontaie",
      lastName: "Allen",
      birthYear: 2001,
      hometown: "Falmouth, KY",
      highSchool: "Pendleton County High School, Falmouth, KY",
      isFeatured: false,
      bio: "The 2019 Kentucky Mr. Basketball who redshirted his freshman year recovering from a torn ACL suffered in December 2018. Wore #11 in honor of his favorite double number.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Ole Miss (transfer portal)",
        league: "SEC",
        location: "In transfer portal",
        statusNote: "Redshirted his first year at Kentucky recovering from a torn ACL. Would later become known for a sensational 23-point, 7-of-11 three-pointer game against Mississippi State in 2021. After three seasons at UK he transferred to WKU and then Wyoming (7.8 PPG in 2024-25). Pendleton County HS retired his jersey. He entered the transfer portal in April 2025 seeking a sixth year of eligibility.",
        sourceUrl: "https://www.sports-reference.com/cbb/players/dontaie-allen-1.html",
      },
      membership: { role: "PLAYER", jerseyNumber: 11, position: "Guard", yearsAtSchool: "2019-2022", statsNote: "Redshirt Freshman (2019-20) • Recovering from ACL • 2019 KY Mr. Basketball" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Pendleton County High School", season: "Senior", yearLabel: "Senior (ACL injury)", sortOrder: 1, pointsPerGame: 42.9, reboundsPerGame: 14.2, assistsPerGame: 5.0 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2019-2020", yearLabel: "Redshirt Freshman", sortOrder: 201, gamesPlayed: 0 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2020-2021", yearLabel: "Redshirt Sophomore", sortOrder: 202, gamesPlayed: 22, pointsPerGame: 5.4, reboundsPerGame: 1.7, assistsPerGame: 0.5 },
      ],
      careerEvents: [
        { year: 2019, title: "Won Kentucky Mr. Basketball award", eventType: "AWARD" },
        { year: 2022, title: "Transferred to Western Kentucky University", eventType: "OTHER" },
      ],
    },
    {
      slug: "lance-ware",
      firstName: "Lance",
      lastName: "Ware",
      birthYear: 2002,
      hometown: "Camden, NJ",
      highSchool: "Camden High School, Camden, NJ",
      isFeatured: false,
      bio: "A four-star power forward from Camden, NJ who enrolled at Kentucky in fall 2020 as son of former NBA coach Kenny Payne's primary recruit. Known for his hustle, physicality, and defensive contributions over three seasons.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "New York Knicks (Summer League)",
        league: "NBA / G League",
        location: "New York, NY",
        statusNote: "After three seasons at Kentucky (2020-23) and a final year at UT Arlington (2024-25), Ware went undrafted in the 2025 NBA Draft. The New York Knicks named him to their 2025 Summer League roster, making his dream of playing at the NBA level a reality. He never averaged more than 2 PPG at Kentucky but was valued for his rebounding and energy.",
        sourceUrl: "https://www.sports-reference.com/cbb/players/lance-ware-1.html",
      },
      membership: { role: "PLAYER", jerseyNumber: 55, position: "Forward", yearsAtSchool: "2020-2023", statsNote: "Freshman • Four-star recruit from Camden, NJ • Hustle/energy player" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Camden High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 16.0, reboundsPerGame: 9.0, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2019-2020", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 21, pointsPerGame: 1.7, reboundsPerGame: 2.2, assistsPerGame: 0.2 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2020-2021", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 22, pointsPerGame: 1.3, reboundsPerGame: 2.4, assistsPerGame: 0.2 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2021-2022", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 34, pointsPerGame: 2.0, reboundsPerGame: 2.2, assistsPerGame: 0.3 },
      ],
      careerEvents: [
        { year: 2023, title: "Transferred to UT Arlington", eventType: "OTHER" },
        { year: 2025, title: "Named to New York Knicks Summer League roster", eventType: "SIGNING" },
      ],
    },
    {
      slug: "camron-fletcher",
      firstName: "Cam'Ron",
      lastName: "Fletcher",
      birthYear: 2002,
      hometown: "St. Louis, MO",
      highSchool: "Vashon High School, St. Louis, MO",
      isFeatured: false,
      bio: "A four-star freshman forward from St. Louis who played nine games at Kentucky before transferring, ultimately finding his stride at Florida State, Xavier, and High Point.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "High Point University",
        league: "Big South",
        location: "High Point, NC",
        statusNote: "Played nine games as a freshman at Kentucky before leaving. Spent three seasons at Florida State before playing one year at Xavier. At High Point in 2025-26, Fletcher averaged 17.0 PPG and 8.1 RPG through the first 14 games and showed his best basketball before briefly stepping away for personal reasons. He returned to High Point to compete and is draft eligible in 2026.",
        sourceUrl: "https://www.espn.com/mens-college-basketball/player/_/id/4432182/camron-fletcher",
      },
      membership: { role: "PLAYER", jerseyNumber: 21, position: "Forward", yearsAtSchool: "2020-2021", statsNote: "Freshman • 9 games played • Transferred after one season" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Vashon High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 18.0, reboundsPerGame: 9.0, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2020-2021", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 9, pointsPerGame: 1.7, reboundsPerGame: 1.7, assistsPerGame: 0.3 },
      ],
      careerEvents: [
        { year: 2021, title: "Transferred to Florida State University", eventType: "OTHER" },
      ],
    },
    {
      slug: "davion-mintz",
      firstName: "Davion",
      lastName: "Mintz",
      birthYear: 1997,
      hometown: "Charlotte, NC",
      highSchool: "North Mecklenburg High School, Charlotte, NC",
      isFeatured: false,
      bio: "A graduate transfer from Creighton who joined Kentucky in 2020-21 and led the team in scoring (11.5 PPG) and assists. Returned for a COVID year and finished his career in Lexington.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "Capital City Go-Go (G League)",
        league: "NBA G League",
        location: "Washington, D.C.",
        statusNote: "Led Kentucky in scoring (11.5 PPG) and assists (3.1 APG) as a graduate transfer in 2020-21, then returned for his COVID season (8.5 PPG). Went undrafted in 2022. Signed an Exhibit 10 deal with the Washington Wizards and has bounced through the G League with the Capital City Go-Go. A crafty veteran guard who still competes at the professional level.",
        sourceUrl: "https://www.basketball-reference.com/players/m/mintzda01.html",
      },
      membership: { role: "PLAYER", jerseyNumber: 10, position: "Guard", yearsAtSchool: "2020-2022", statsNote: "Graduate Transfer • Led UK in scoring 11.5 PPG & assists 3.1 APG" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "North Mecklenburg High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 12.3, reboundsPerGame: 4.2, assistsPerGame: 2.8 },
        { level: "COLLEGE", teamName: "Creighton Bluejays", season: "2019-2020", yearLabel: "Junior (Creighton)", sortOrder: 201, gamesPlayed: 31, pointsPerGame: 9.3, reboundsPerGame: 2.8, assistsPerGame: 3.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2020-2021", yearLabel: "Graduate Senior", sortOrder: 202, gamesPlayed: 25, pointsPerGame: 11.5, reboundsPerGame: 3.2, assistsPerGame: 3.1 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2021-2022", yearLabel: "COVID year", sortOrder: 203, gamesPlayed: 28, pointsPerGame: 8.5, reboundsPerGame: 2.2, assistsPerGame: 1.8 },
      ],
      careerEvents: [
        { year: 2022, title: "Went undrafted; signed Exhibit 10 with Washington Wizards", eventType: "CAREER" },
      ],
    },
    {
      slug: "john-calipari",
      firstName: "John",
      lastName: "Calipari",
      birthYear: 1959,
      hometown: "Moon Township, PA",
      highSchool: "Moon Area High School, Moon Township, PA",
      isFeatured: true,
      bio: "The architect of Kentucky's one-and-done era. This was his SEC Championship team whose NCAA Tournament was cancelled by COVID-19.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "University of Arkansas",
        league: "SEC",
        location: "Fayetteville, AR",
        statusNote: "Left Kentucky for Arkansas in April 2024 after 15 seasons, a national championship, and more NBA Draft picks than any coach in history.",
        sourceUrl: "https://en.wikipedia.org/wiki/John_Calipari",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2024", statsNote: "25-6 • SEC Champions • NCAA Tournament cancelled (COVID)" },
      careerEvents: [
        { year: 2012, title: "Won NCAA National Championship at Kentucky", eventType: "CHAMPIONSHIP" },
        { year: 2024, title: "Left Kentucky for Arkansas", eventType: "CAREER" },
      ],
    },
  ],
};
