import type { TeamSeed } from "./types";

export const kentuckyBasketball2020: TeamSeed = {
  slug: "kentucky-basketball-2020",
  name: "Kentucky Wildcats",
  season: "2019-2020",
  sport: "Men's Basketball",
  school: "University of Kentucky",
  conference: "SEC",
  accomplishment: "SEC Champions (25-6, NCAA Tournament cancelled)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png",
  mascotName: "Wildcat",
  people: [
    {
      slug: "tyrese-maxey",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/4431678.png",
      firstName: "Tyrese",
      lastName: "Maxey",
      birthYear: 2000,
      hometown: "Garland, TX",
      highSchool: "South Garland High School, Garland, TX",
      isFeatured: true,
      bio: "A dynamic freshman guard who became the team's go-to scorer. Maxey declared for the NBA Draft after one electrifying season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Philadelphia 76ers",
        league: "NBA",
        location: "Philadelphia, PA",
        statusNote: "Drafted 21st overall by the 76ers in 2020, Maxey won the 2024 NBA Most Improved Player award and has become one of the league's premier guards. Averaging 28.8 PPG and 6.8 APG in 2025-26.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tyrese_Maxey",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Guard", yearsAtSchool: "2019-2020", statsNote: "Freshman • 14.0 PPG • SEC Champions" },
      careerEvents: [
        { year: 2020, title: "Selected #21 overall by the Philadelphia 76ers", eventType: "DRAFT" },
        { year: 2024, title: "Won NBA Most Improved Player award", eventType: "AWARD" },
      ],
    },
    {
      slug: "immanuel-quickley",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/4395724.png",
      firstName: "Immanuel",
      lastName: "Quickley",
      birthYear: 1999,
      hometown: "Havre de Grace, MD",
      highSchool: "The John Carroll School, Bel Air, MD",
      isFeatured: true,
      bio: "Blossomed into the SEC Player of the Year as a sophomore after a quiet freshman season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Point Guard",
        currentEmployer: "Toronto Raptors",
        league: "NBA",
        location: "Toronto, ON",
        statusNote: "Drafted 25th overall in 2020. Signed 5-year, $162.5M max contract with the Raptors in 2024. Averaging 17.0 PPG in 2025-26.",
        sourceUrl: "https://en.wikipedia.org/wiki/Immanuel_Quickley",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Guard", yearsAtSchool: "2018-2020", statsNote: "Sophomore • SEC Player of the Year • 16.1 PPG" },
      careerEvents: [
        { year: 2020, title: "Won SEC Player of the Year", eventType: "AWARD" },
        { year: 2020, title: "Selected #25 overall by the New York Knicks", eventType: "DRAFT" },
      ],
    },
    {
      slug: "nick-richards",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/4395726.png",
      firstName: "Nick",
      lastName: "Richards",
      birthYear: 1997,
      hometown: "Kingston, Jamaica",
      highSchool: "The Patrick School, Elizabeth, NJ",
      isFeatured: false,
      bio: "A junior center who developed into a dominant interior force and SEC Defensive POY candidate.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "Chicago Bulls",
        league: "NBA",
        location: "Chicago, IL",
        statusNote: "Drafted 42nd overall in 2020 by Charlotte. Now with the Chicago Bulls after multiple trades in 2025-26.",
        sourceUrl: "https://www.basketball-reference.com/players/r/richani01.html",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Center", yearsAtSchool: "2017-2020", statsNote: "Junior • 14.0 PPG, 7.8 RPG • SEC Defensive POY candidate" },
      careerEvents: [
        { year: 2020, title: "Selected #42 overall by the Charlotte Hornets", eventType: "DRAFT" },
      ],
    },
    {
      slug: "ashton-hagans",
      firstName: "Ashton",
      lastName: "Hagans",
      birthYear: 1999,
      hometown: "Cartersville, GA",
      highSchool: "Newton High School, Covington, GA",
      isFeatured: false,
      bio: "Returned as a sophomore but left the team late in the season for personal reasons.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Rip City Remix (G League)",
        league: "NBA G League",
        location: "Portland, OR",
        statusNote: "Has bounced between the G League, CBA, and NBL Australia since going undrafted in 2020.",
        sourceUrl: "https://en.wikipedia.org/wiki/Ashton_Hagans",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Point Guard", yearsAtSchool: "2018-2020", statsNote: "Sophomore • Left team late season" },
      careerEvents: [{ year: 2020, title: "Went undrafted; began professional career", eventType: "CAREER" }],
    },
    {
      slug: "nate-sestina",
      firstName: "Nate",
      lastName: "Sestina",
      birthYear: 1997,
      hometown: "Emporium, PA",
      highSchool: "Cameron County High School, Emporium, PA",
      isFeatured: false,
      bio: "A graduate transfer from Bucknell who provided veteran leadership and stretch-four scoring.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "Olimpia Milano",
        league: "Italian Lega Basket Serie A / EuroLeague",
        location: "Milan, Italy",
        statusNote: "Has built a strong European career playing in Spain's Liga ACB (Valencia Basket) and Italy's Serie A (Olimpia Milano). Signed with Milano in October 2025.",
        sourceUrl: "https://en.wikipedia.org/wiki/Nate_Sestina",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Forward", yearsAtSchool: "2019-2020", statsNote: "Graduate Senior • Transfer from Bucknell • Stretch four" },
      careerEvents: [
        { year: 2020, title: "Began professional career in Europe", eventType: "CAREER" },
        { year: 2025, title: "Signed with Olimpia Milano (EuroLeague)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "keion-brooks",
      firstName: "Keion",
      lastName: "Brooks Jr.",
      birthYear: 2000,
      hometown: "Fort Wayne, IN",
      highSchool: "La Lumiere School, La Porte, IN",
      isFeatured: false,
      bio: "A four-star freshman forward who played three years at Kentucky before transferring to Washington.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "Noblesville Boom (G League)",
        league: "NBA G League",
        location: "Indiana",
        statusNote: "Went undrafted in 2024 after college at Kentucky (3 years) and Washington (1 year). Played 14 games for the Pelicans in 2024-25 (10.1 PPG). Now with the Pacers' G League affiliate.",
        sourceUrl: "https://en.wikipedia.org/wiki/Keion_Brooks_Jr.",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Forward", yearsAtSchool: "2019-2022", statsNote: "Freshman • Four-star recruit" },
      careerEvents: [
        { year: 2024, title: "Went undrafted; signed with New Orleans Pelicans", eventType: "SIGNING" },
      ],
    },
    {
      slug: "johnny-juzang",
      firstName: "Johnny",
      lastName: "Juzang",
      birthYear: 2001,
      hometown: "Los Angeles, CA",
      highSchool: "Harvard-Westlake School, Los Angeles, CA",
      isFeatured: false,
      bio: "A talented freshman guard who transferred to UCLA after one season and famously led the Bruins to the 2021 Final Four.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "Zenit Saint Petersburg",
        league: "VTB United League (Russia)",
        location: "Saint Petersburg, Russia",
        statusNote: "After transferring to UCLA and leading them to the 2021 Final Four, Juzang went undrafted twice (2022, 2023). He had a brief NBA stint with the Timberwolves (21 games in 2025-26) before signing with Zenit Saint Petersburg in Russia.",
        sourceUrl: "https://en.wikipedia.org/wiki/Johnny_Juzang",
      },
      membership: { role: "PLAYER", jerseyNumber: 10, position: "Guard", yearsAtSchool: "2019-2020", statsNote: "Freshman • Transferred to UCLA • Led UCLA to 2021 Final Four" },
      careerEvents: [
        { year: 2020, title: "Transferred to UCLA", eventType: "OTHER" },
        { year: 2021, title: "Led UCLA to Final Four as Most Outstanding Player candidate", eventType: "CAREER" },
      ],
    },
    {
      slug: "kahlil-whitney",
      firstName: "Kahlil",
      lastName: "Whitney",
      birthYear: 2001,
      hometown: "Chicago, IL",
      highSchool: "Roselle Catholic High School, Roselle, NJ",
      isFeatured: false,
      bio: "A five-star recruit who left the team mid-season in January 2020 and declared for the NBA Draft.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "China NBL",
        statusNote: "Went undrafted in 2020 after leaving Kentucky mid-season. Has played in the G League, Mexico, Croatia, New Zealand, and China's NBL. Exploring a return to college basketball as of early 2026.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kahlil_Whitney",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Forward", yearsAtSchool: "2019-2020", statsNote: "Freshman • Five-star recruit • Left team mid-season" },
      careerEvents: [
        { year: 2020, title: "Left Kentucky mid-season; declared for NBA Draft", eventType: "OTHER" },
      ],
    },
    {
      slug: "ej-montgomery",
      firstName: "EJ",
      lastName: "Montgomery",
      birthYear: 1999,
      hometown: "Fort Pierce, FL",
      highSchool: "Wheeler High School, Marietta, GA",
      isFeatured: false,
      bio: "Sophomore forward who declared for the NBA Draft after this season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "MKS Dabrowa Gornicza",
        league: "Polish Basketball League",
        location: "Poland",
        statusNote: "Went undrafted in 2020. Now playing in Poland's PLK, averaging 7.4 PPG and 7.9 RPG.",
        sourceUrl: "https://www.proballers.com/basketball/player/178401/montgomery-e-j",
      },
      membership: { role: "PLAYER", jerseyNumber: 23, position: "Forward", yearsAtSchool: "2018-2020", statsNote: "Sophomore • Declared for NBA Draft" },
      careerEvents: [{ year: 2020, title: "Went undrafted; began overseas career", eventType: "CAREER" }],
    },
    {
      slug: "john-calipari",
      firstName: "John",
      lastName: "Calipari",
      birthYear: 1959,
      hometown: "Moon Township, PA",
      highSchool: "Moon Area High School, Moon Township, PA",
      isFeatured: true,
      bio: "The architect of Kentucky's one-and-done era. This was his SEC Championship team whose NCAA Tournament was cancelled by COVID-19.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "University of Arkansas",
        league: "SEC",
        location: "Fayetteville, AR",
        statusNote: "Left Kentucky for Arkansas in April 2024 after 15 seasons, a national championship, and more NBA Draft picks than any coach in history.",
        sourceUrl: "https://en.wikipedia.org/wiki/John_Calipari",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2024", statsNote: "25-6 • SEC Champions • NCAA Tournament cancelled (COVID)" },
      careerEvents: [
        { year: 2012, title: "Won NCAA National Championship at Kentucky", eventType: "CHAMPIONSHIP" },
        { year: 2024, title: "Left Kentucky for Arkansas", eventType: "CAREER" },
      ],
    },
  ],
};
