import type { TeamSeed } from "./types";

export const kentuckyBasketball2017: TeamSeed = {
  slug: "kentucky-basketball-2017",
  name: "Kentucky Wildcats",
  season: "2016-2017",
  sport: "Men's Basketball",
  school: "University of Kentucky",
  conference: "SEC",
  accomplishment: "SEC Champions, Elite Eight (32-6)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png",
  mascotName: "Wildcat",
  people: [
    {
      slug: "deaaron-fox",
      firstName: "De'Aaron",
      lastName: "Fox",
      birthYear: 1997,
      hometown: "Katy, TX",
      highSchool: "Cypress Lakes High School, Katy, TX",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628368.png",
      bio: "An explosive freshman point guard who famously outdueled Lonzo Ball in the Sweet Sixteen. Fox scored 39 points to eliminate UCLA.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "San Antonio Spurs",
        league: "NBA",
        location: "San Antonio, TX",
        statusNote: "Drafted #5 overall by the Sacramento Kings in 2017, Fox became a three-time All-Star and franchise player. Traded to the San Antonio Spurs mid-season in 2025-26, scoring 24 points and 13 assists in his Spurs debut. Named 2026 All-Star replacement.",
        sourceUrl: "https://en.wikipedia.org/wiki/De%27Aaron_Fox",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Point Guard", yearsAtSchool: "2016-2017", statsNote: "Freshman • 16.7 PPG • 39 pts vs UCLA • #5 overall pick", gamesPlayed: 38, pointsPerGame: 16.7, reboundsPerGame: 4.0, assistsPerGame: 4.6 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2016-17", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 38, minutesPerGame: 32.2, pointsPerGame: 16.7, reboundsPerGame: 4.0, assistsPerGame: 4.6, stealsPerGame: 1.5, fieldGoalPct: 0.479, threePointPct: 0.246, freeThrowPct: 0.739 },
        { level: "PROFESSIONAL", teamName: "Sacramento Kings", season: "2017-18", yearLabel: "2017-18", sortOrder: 301, gamesPlayed: 73, minutesPerGame: 27.8, pointsPerGame: 11.6, reboundsPerGame: 2.8, assistsPerGame: 4.4, stealsPerGame: 1.0, fieldGoalPct: 0.412, threePointPct: 0.307, freeThrowPct: 0.726 },
        { level: "PROFESSIONAL", teamName: "Sacramento Kings", season: "2018-19", yearLabel: "2018-19", sortOrder: 302, gamesPlayed: 81, minutesPerGame: 31.6, pointsPerGame: 17.3, reboundsPerGame: 3.8, assistsPerGame: 7.3, stealsPerGame: 1.6, fieldGoalPct: 0.458, threePointPct: 0.371, freeThrowPct: 0.727 },
        { level: "PROFESSIONAL", teamName: "Sacramento Kings", season: "2019-20", yearLabel: "2019-20", sortOrder: 303, gamesPlayed: 51, minutesPerGame: 32.0, pointsPerGame: 21.1, reboundsPerGame: 3.8, assistsPerGame: 6.8, stealsPerGame: 1.5, fieldGoalPct: 0.480, freeThrowPct: 0.703 },
        { level: "PROFESSIONAL", teamName: "Sacramento Kings", season: "2020-21", yearLabel: "2020-21", sortOrder: 304, gamesPlayed: 58, minutesPerGame: 35.1, pointsPerGame: 25.2, reboundsPerGame: 3.5, assistsPerGame: 7.2, stealsPerGame: 1.5, fieldGoalPct: 0.472, freeThrowPct: 0.719 },
        { level: "PROFESSIONAL", teamName: "Sacramento Kings", season: "2022-23", yearLabel: "2022-23 (All-Star)", sortOrder: 306, gamesPlayed: 73, minutesPerGame: 33.6, pointsPerGame: 25.0, reboundsPerGame: 4.2, assistsPerGame: 6.1, fieldGoalPct: 0.512, freeThrowPct: 0.783 },
        { level: "PROFESSIONAL", teamName: "Sacramento Kings", season: "2023-24", yearLabel: "2023-24", sortOrder: 307, gamesPlayed: 74, minutesPerGame: 35.5, pointsPerGame: 26.6, reboundsPerGame: 4.6, assistsPerGame: 5.6, stealsPerGame: 2.0, fieldGoalPct: 0.466, freeThrowPct: 0.735 },
        { level: "PROFESSIONAL", teamName: "Sacramento Kings", season: "2024-25", yearLabel: "2024-25", sortOrder: 308, gamesPlayed: 62, pointsPerGame: 23.5, reboundsPerGame: 4.8, assistsPerGame: 6.3, fieldGoalPct: 0.470 },
        { level: "PROFESSIONAL", teamName: "San Antonio Spurs", season: "2025-26", yearLabel: "2025-26 (traded)", sortOrder: 309, gamesPlayed: 58, pointsPerGame: 19.1, reboundsPerGame: 3.7, assistsPerGame: 6.3 },
      ],
      careerEvents: [
        { year: 2017, title: "Selected #5 overall by the Sacramento Kings", eventType: "DRAFT" },
        { year: 2023, title: "Named NBA All-Star", eventType: "AWARD" },
        { year: 2026, title: "Traded to San Antonio Spurs", eventType: "TRADE" },
      ],
    },
    {
      slug: "malik-monk",
      firstName: "Malik",
      lastName: "Monk",
      birthYear: 1998,
      hometown: "Lepanto, AR",
      highSchool: "Bentonville High School, Bentonville, AR",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628370.png",
      bio: "A high-flying freshman guard who scored 47 points in an overtime loss to UNC — the second-highest freshman scoring game in Kentucky history.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Sacramento Kings",
        league: "NBA",
        location: "Sacramento, CA",
        statusNote: "Drafted #11 by the Charlotte Hornets in 2017. After stints with Charlotte and the Lakers, Monk signed with the Sacramento Kings in 2022 and is under contract through 2027, averaging 12.6 PPG in 2025-26.",
        sourceUrl: "https://en.wikipedia.org/wiki/Malik_Monk",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Guard", yearsAtSchool: "2016-2017", statsNote: "Freshman • 19.8 PPG • 47 pts vs UNC • #11 overall pick", gamesPlayed: 38, pointsPerGame: 19.8, reboundsPerGame: 2.5, assistsPerGame: 2.3 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2016-2017", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 38, pointsPerGame: 19.8, reboundsPerGame: 2.5, assistsPerGame: 2.3 },
      ],
      careerEvents: [
        { year: 2017, title: "Selected #11 overall by the Charlotte Hornets", eventType: "DRAFT" },
      ],
    },
    {
      slug: "bam-adebayo",
      firstName: "Bam",
      lastName: "Adebayo",
      birthYear: 1997,
      hometown: "Pinetown, NC",
      highSchool: "Northside High School, Pinetown, NC",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628389.png",
      bio: "A dominant freshman center whose physical play anchored Kentucky's frontcourt. Declared for the NBA after one season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "Miami Heat",
        league: "NBA",
        location: "Miami, FL",
        statusNote: "Drafted #14 by the Miami Heat in 2017, Adebayo has become a three-time All-Star, 2020 Olympic gold medalist, and franchise cornerstone. On March 10, 2026, he scored 83 points against the Washington Wizards — the second-highest single-game total in NBA history behind Wilt Chamberlain's 100.",
        sourceUrl: "https://en.wikipedia.org/wiki/Bam_Adebayo",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Center / Power Forward", yearsAtSchool: "2016-2017", statsNote: "Freshman • 13.0 PPG, 8.0 RPG • #14 overall pick", gamesPlayed: 38, pointsPerGame: 13.0, reboundsPerGame: 8.0, assistsPerGame: 1.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2016-17", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 38, minutesPerGame: 24.9, pointsPerGame: 13.0, reboundsPerGame: 8.0, assistsPerGame: 1.5, stealsPerGame: 0.6, blocksPerGame: 1.5, fieldGoalPct: 0.599, freeThrowPct: 0.604 },
        { level: "PROFESSIONAL", teamName: "Miami Heat", season: "2017-18", yearLabel: "2017-18", sortOrder: 301, gamesPlayed: 69, minutesPerGame: 19.8, pointsPerGame: 6.9, reboundsPerGame: 5.5, assistsPerGame: 1.5, blocksPerGame: 0.5, fieldGoalPct: 0.515, freeThrowPct: 0.721 },
        { level: "PROFESSIONAL", teamName: "Miami Heat", season: "2018-19", yearLabel: "2018-19", sortOrder: 302, gamesPlayed: 82, minutesPerGame: 23.3, pointsPerGame: 8.9, reboundsPerGame: 7.3, assistsPerGame: 2.2, blocksPerGame: 0.8, fieldGoalPct: 0.576, freeThrowPct: 0.735 },
        { level: "PROFESSIONAL", teamName: "Miami Heat", season: "2019-20", yearLabel: "2019-20 (All-Star)", sortOrder: 303, gamesPlayed: 72, minutesPerGame: 33.6, pointsPerGame: 15.9, reboundsPerGame: 10.2, assistsPerGame: 5.1, stealsPerGame: 1.1, blocksPerGame: 1.3, fieldGoalPct: 0.557, freeThrowPct: 0.691 },
        { level: "PROFESSIONAL", teamName: "Miami Heat", season: "2020-21", yearLabel: "2020-21 (All-Star)", sortOrder: 304, gamesPlayed: 64, minutesPerGame: 33.5, pointsPerGame: 18.7, reboundsPerGame: 9.0, assistsPerGame: 5.4, stealsPerGame: 1.2, blocksPerGame: 1.0, fieldGoalPct: 0.570, freeThrowPct: 0.799 },
        { level: "PROFESSIONAL", teamName: "Miami Heat", season: "2021-22", yearLabel: "2021-22 (All-Star)", sortOrder: 305, gamesPlayed: 56, minutesPerGame: 32.6, pointsPerGame: 19.1, reboundsPerGame: 10.1, assistsPerGame: 3.4, stealsPerGame: 1.4, blocksPerGame: 0.8, fieldGoalPct: 0.557, freeThrowPct: 0.753 },
        { level: "PROFESSIONAL", teamName: "Miami Heat", season: "2022-23", yearLabel: "2022-23", sortOrder: 306, gamesPlayed: 75, minutesPerGame: 34.6, pointsPerGame: 20.4, reboundsPerGame: 9.2, assistsPerGame: 3.2, stealsPerGame: 1.1, blocksPerGame: 0.8, fieldGoalPct: 0.540, freeThrowPct: 0.790 },
        { level: "PROFESSIONAL", teamName: "Miami Heat", season: "2023-24", yearLabel: "2023-24", sortOrder: 307, gamesPlayed: 71, minutesPerGame: 34.0, pointsPerGame: 19.3, reboundsPerGame: 10.4, assistsPerGame: 3.9, stealsPerGame: 1.1, blocksPerGame: 0.9, fieldGoalPct: 0.520, freeThrowPct: 0.810 },
        { level: "PROFESSIONAL", teamName: "Miami Heat", season: "2024-25", yearLabel: "2024-25", sortOrder: 308, gamesPlayed: 72, pointsPerGame: 20.3, reboundsPerGame: 10.0, assistsPerGame: 3.0, fieldGoalPct: 0.439 },
        { level: "PROFESSIONAL", teamName: "Miami Heat", season: "2025-26", yearLabel: "2025-26 (83-pt game!)", sortOrder: 309, gamesPlayed: 58, pointsPerGame: 20.0, reboundsPerGame: 9.8, assistsPerGame: 2.9, fieldGoalPct: 0.448 },
      ],
      careerEvents: [
        { year: 2017, title: "Selected #14 overall by the Miami Heat", eventType: "DRAFT" },
        { year: 2020, title: "Won Olympic gold medal with Team USA", eventType: "AWARD" },
        { year: 2026, title: "Scored 83 points vs Wizards — 2nd most in NBA history", eventType: "OTHER" },
      ],
    },
    {
      slug: "wenyen-gabriel",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1629117.png",
      firstName: "Wenyen",
      lastName: "Gabriel",
      birthYear: 1997,
      hometown: "Manchester, NH",
      highSchool: "Wilbraham & Monson Academy, Wilbraham, MA",
      isFeatured: false,
      bio: "A South Sudanese-American freshman forward who developed into a versatile contributor over two seasons.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "FC Bayern Munich",
        league: "German BBL / EuroLeague",
        location: "Munich, Germany",
        statusNote: "Went undrafted in 2018 but played for 7 NBA teams including the Kings, Trail Blazers, Pelicans, Nets, Clippers, Lakers, and Grizzlies. Now playing for FC Bayern Munich in Germany and EuroLeague.",
        sourceUrl: "https://en.wikipedia.org/wiki/Wenyen_Gabriel",
      },
      membership: { role: "PLAYER", jerseyNumber: 32, position: "Forward", yearsAtSchool: "2016-2018", statsNote: "Freshman • South Sudanese-American • Versatile wing" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2016-2017", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 3.3, reboundsPerGame: 2.5, assistsPerGame: 0.3 },
      ],
      careerEvents: [
        { year: 2018, title: "Went undrafted; began G League/NBA journey", eventType: "CAREER" },
      ],
    },
    {
      slug: "hamidou-diallo",
      firstName: "Hamidou",
      lastName: "Diallo",
      birthYear: 1998,
      hometown: "Queens, NY",
      highSchool: "Putnam Science Academy, Putnam, CT",
      isFeatured: false,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628977.png",
      bio: "An explosive freshman guard who redshirted this season before playing in 2017-18 and winning the 2019 NBA Slam Dunk Contest.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Shanxi Loongs",
        league: "CBA (China)",
        location: "China",
        statusNote: "Drafted #45 in 2018. Won the 2019 NBA Slam Dunk Contest with OKC Thunder. Played for the Pistons and Wizards before moving overseas to Spain and China's CBA.",
        sourceUrl: "https://en.wikipedia.org/wiki/Hamidou_Diallo",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Guard", yearsAtSchool: "2016-2018", statsNote: "Redshirt Freshman • Did not play this season" },
      careerEvents: [
        { year: 2018, title: "Selected #45 overall by the Brooklyn Nets (traded to OKC)", eventType: "DRAFT" },
        { year: 2019, title: "Won NBA Slam Dunk Contest", eventType: "AWARD" },
      ],
    },
    {
      slug: "isaiah-briscoe",
      firstName: "Isaiah",
      lastName: "Briscoe",
      birthYear: 1996,
      hometown: "Newark, NJ",
      highSchool: "Roselle Catholic High School, Roselle, NJ",
      isFeatured: false,
      bio: "A tough sophomore guard who was the team's second-leading scorer.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Fujian Sturgeons",
        league: "CBA (China)",
        location: "China",
        statusNote: "After going undrafted in 2017, Briscoe has become one of basketball's most well-traveled journeymen. Brief NBA stints with the Orlando Magic were followed by seasons across the globe — Israel (Maccabi Rishon LeZion), Lithuania, Taiwan (Kaohsiung Steelers, where he averaged a staggering 32.8 PPG, 8.7 RPG, and 8.4 APG in 2024-25), Indonesia (Borneo Hornbills), and China (Fujian Sturgeons, where he scored a career-high 33 points on January 6, 2026). At Kentucky he was a McDonald's All-American who averaged 13.5 PPG as a sophomore.",
        sourceUrl: "https://en.wikipedia.org/wiki/Isaiah_Briscoe",
      },
      membership: { role: "PLAYER", jerseyNumber: 13, position: "Guard", yearsAtSchool: "2015-2017", statsNote: "Sophomore • 13.5 PPG • Team's second-leading scorer" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2016-2017", yearLabel: "Sophomore", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 13.2, reboundsPerGame: 5.4, assistsPerGame: 3.1 },
      ],
      careerEvents: [{ year: 2017, title: "Went undrafted", eventType: "CAREER" }],
    },
    {
      slug: "derek-willis",
      firstName: "Derek",
      lastName: "Willis",
      birthYear: 1994,
      hometown: "Frankfort, KY",
      highSchool: "Western Hills High School, Frankfort, KY",
      isFeatured: false,
      bio: "A senior stretch four from Kentucky who graduated and went on to a strong European career.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Paris Basketball",
        league: "LNB Pro A / EuroLeague",
        location: "Paris, France",
        statusNote: "A Kentucky native from Frankfort who developed into a reliable stretch four over four years, shooting 38.5% from three as a senior. After going undrafted in 2017, Willis built an impressive European career across six countries — Germany (BG Gottingen, 12.0 PPG; Ratiopharm Ulm), Italy (Happy Casa Brindisi; Reyer Venezia), Spain (Joventut Badalona), and Turkey (Anadolu Efes, EuroLeague competition). Signed a 2-year deal with Paris Basketball for the 2025-26 LNB Pro A and EuroLeague seasons.",
        sourceUrl: "https://parisbasketball.com/en/2025/07/derek-willis-arrives-in-paris/",
      },
      membership: { role: "PLAYER", jerseyNumber: 35, position: "Power Forward", yearsAtSchool: "2013-2017", statsNote: "Senior • In-state recruit" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2016-2017", yearLabel: "Senior", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 8.6, reboundsPerGame: 4.1, assistsPerGame: 0.7 },
      ],
      careerEvents: [{ year: 2017, title: "Graduated; began European career", eventType: "CAREER" }],
    },
    {
      slug: "dominique-hawkins",
      firstName: "Dominique",
      lastName: "Hawkins",
      birthYear: 1994,
      hometown: "Richmond, KY",
      highSchool: "Madison Central High School, Richmond, KY",
      isFeatured: false,
      bio: "Senior walk-on and fan favorite completing his four-year Kentucky career.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Youth Basketball Trainer",
        location: "Kentucky",
        statusNote: "Named Most Outstanding Player of the 2017 SEC Tournament — one of the program's proudest walk-on moments. After graduating, played overseas in Estonia (Avis Rapla), Denmark, Latvia-Estonia League, and Slovakia (Lucenec), scoring a career-high 31 in a 2021 playoff game. Since retiring around 2021, returned to Richmond, KY to run D-Hawk Training, a youth basketball business serving kids from third grade up across central Kentucky. Inducted into the Madison County Sports Hall of Fame in 2024.",
        sourceUrl: "https://www.linkedin.com/in/dominique-hawkins-25966492/",
      },
      membership: { role: "PLAYER", jerseyNumber: 25, position: "Guard", yearsAtSchool: "2013-2017", statsNote: "Senior • Walk-on • 2013 KY Mr. Basketball" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2016-2017", yearLabel: "Senior", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 3.4, reboundsPerGame: 1.7, assistsPerGame: 1.7 },
      ],
      careerEvents: [{ year: 2017, title: "Graduated from Kentucky", eventType: "CAREER" }],
    },
    {
      slug: "isaac-humphries",
      firstName: "Isaac",
      lastName: "Humphries",
      birthYear: 1998,
      hometown: "Sydney, Australia",
      highSchool: "La Lumiere School, La Porte, IN",
      isFeatured: false,
      bio: "Sophomore center from Australia who would later become the first openly gay active pro basketball player in a top league.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "Adelaide 36ers",
        league: "NBL Australia",
        location: "Adelaide, Australia",
        statusNote: "A 7-foot Australian center who left Kentucky after his sophomore year and won NBL Rookie of the Year with the Sydney Kings. Had 5 NBA games with the Atlanta Hawks in 2019. In his 5th season as co-captain of the Adelaide 36ers (13.4 PPG, 5.0 RPG in 2025-26). Made global headlines in 2023 by coming out as the first openly gay active male professional basketball player in a top-flight league — a courageous act that earned widespread support.",
        sourceUrl: "https://www.adelaide36ers.com/player/isaac-humphries",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Center", yearsAtSchool: "2015-2017", statsNote: "Sophomore • 7-footer from Australia" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2016-2017", yearLabel: "Sophomore", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 4.5, reboundsPerGame: 3.1, assistsPerGame: 0.5 },
      ],
      careerEvents: [{ year: 2023, title: "Came out publicly as gay — first in a top league", eventType: "OTHER" }],
    },
    {
      slug: "sacha-killeya-jones",
      firstName: "Sacha",
      lastName: "Killeya-Jones",
      birthYear: 1997,
      hometown: "Charlottesville, VA",
      highSchool: "Hamilton Heights Christian Academy, Chattanooga, TN",
      isFeatured: false,
      bio: "A freshman big man who would later transfer to NC State before turning pro.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward / Center",
        currentEmployer: "Kawasaki Brave Thunders",
        league: "B.League (Japan)",
        location: "Kawasaki, Japan",
        statusNote: "After transferring from Kentucky to NC State (then leaving before playing), Killeya-Jones turned pro. Now playing in Japan's B.League with the Kawasaki Brave Thunders, averaging 14.8 PPG and leading the league in blocks.",
        sourceUrl: "https://en.wikipedia.org/wiki/Sacha_Killeya-Jones",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Power Forward / Center", yearsAtSchool: "2016-2018", statsNote: "Freshman • Five-star recruit" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2016-2017", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 24, pointsPerGame: 1.7, reboundsPerGame: 1.0, assistsPerGame: 0.1 },
      ],
      careerEvents: [
        { year: 2018, title: "Transferred to NC State", eventType: "OTHER" },
        { year: 2024, title: "Signed with Kawasaki Brave Thunders (Japan)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "tai-wynyard",
      firstName: "Tai",
      lastName: "Wynyard",
      birthYear: 1997,
      hometown: "Auckland, New Zealand",
      highSchool: "Rangitoto College, Auckland, New Zealand",
      isFeatured: false,
      bio: "A freshman forward from New Zealand who was the first New Zealander to play for Kentucky basketball.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        location: "New Zealand",
        statusNote: "Left Kentucky early in 2018 (suspended). Had a journeyman career across Australia, China, New Zealand, and the US. Appeared in 4 games as an injury replacement for the New Zealand Breakers in 2024-25.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tai_Wynyard",
      },
      membership: { role: "PLAYER", jerseyNumber: 14, position: "Forward", yearsAtSchool: "2016-2018", statsNote: "Freshman • First New Zealander at Kentucky" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2016-2017", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 22, pointsPerGame: 1.4, reboundsPerGame: 0.9, assistsPerGame: 0.2 },
      ],
      careerEvents: [{ year: 2018, title: "Left Kentucky; suspended", eventType: "OTHER" }],
    },
    {
      slug: "john-calipari",
      firstName: "John",
      lastName: "Calipari",
      birthYear: 1959,
      hometown: "Moon Township, PA",
      highSchool: "Moon Area High School, Moon Township, PA",
      isFeatured: true,
      bio: "Led one of his most talented rosters to the Elite Eight, with three future NBA lottery picks (Fox, Monk, Adebayo).",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "University of Arkansas",
        league: "SEC",
        location: "Fayetteville, AR",
        statusNote: "After 15 seasons at Kentucky (2009-2024) compiling a 410-127 record, one national championship (2012), four Final Fours, and more NBA Draft picks than any coach in history (42 first-round picks), Calipari left for Arkansas in April 2024 on a 5-year, $35M deal. In his first full season at Arkansas (2025-26), he won the SEC Tournament Championship — becoming the first men's coach to win SEC Tournament titles at multiple schools. He ranks 5th on the all-time NCAA Division I wins list with 900+ career victories.",
        sourceUrl: "https://en.wikipedia.org/wiki/John_Calipari",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2024", statsNote: "32-6 • SEC Champions • Elite Eight • 3 lottery picks" },
      careerEvents: [{ year: 2024, title: "Left Kentucky for Arkansas", eventType: "CAREER" }],
    },
  ],
};
