import type { TeamSeed } from "./types";

export const kentuckyBasketball2025: TeamSeed = {
  slug: "kentucky-basketball-2025",
  name: "Kentucky Wildcats",
  season: "2024-2025",
  sport: "Men's Basketball",
  school: "University of Kentucky",
  conference: "SEC",
  accomplishment: "NCAA Tournament Second Round (23-10)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png",
  mascotName: "Wildcat",
  people: [
    {
      slug: "mark-pope",
      firstName: "Mark",
      lastName: "Pope",
      birthYear: 1972,
      hometown: "Lincoln, NE",
      highSchool: "Bellevue West High School, Bellevue, NE",
      isFeatured: true,
      bio: "A former Kentucky player on the 1996 national championship team who returned to Lexington as head coach in 2024, replacing John Calipari. Pope previously built BYU into an NCAA Tournament program.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "University of Kentucky",
        league: "SEC",
        location: "Lexington, KY",
        statusNote:
          "Pope was a member of Kentucky's 1996 national championship team under Rick Pitino, played in the NBA for the Pacers, Bucks, and Nuggets, and built a coaching career at Georgia, Wake Forest, and BYU (where he won the 2021 NIT Championship). Named Kentucky's head coach in April 2024, he led the Wildcats to a 23-10 record and NCAA Tournament appearance in his first season.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mark_Pope",
      },
      membership: {
        role: "HEAD_COACH",
        position: "Head Coach",
        yearsAtSchool: "2024-present",
        statsNote: "23-10 in Year 1 • NCAA Tournament 2nd Round",
      },
      careerEvents: [
        { year: 1996, title: "Won NCAA Championship as Kentucky player", eventType: "CHAMPIONSHIP" },
        { year: 2019, title: "Named BYU head coach", eventType: "CAREER" },
        { year: 2024, title: "Named Kentucky head coach, replacing Calipari", eventType: "CAREER" },
      ],
    },
    {
      slug: "otega-oweh",
      firstName: "Otega",
      lastName: "Oweh",
      birthYear: 2003,
      hometown: "Manalapan, NJ",
      highSchool: "Montverde Academy, Montverde, FL",
      isFeatured: true,
      bio: "A versatile guard/wing who transferred from Oklahoma and became one of Kentucky's top players under Mark Pope.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Kentucky",
        league: "SEC",
        location: "Lexington, KY",
        statusNote: "Returned to Kentucky for the 2025-26 season as a junior and one of the team's top returning players. Expected to be a potential NBA Draft pick after this season.",
        sourceUrl: "https://ukathletics.com/sports/mens-basketball/roster/otega-oweh/",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Guard / Wing", yearsAtSchool: "2023-present", statsNote: "Sophomore • Transfer from Oklahoma • Key contributor" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2024-2025", yearLabel: "Sophomore", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 15.2, reboundsPerGame: 4.8, assistsPerGame: 2.1 },
      ],
      careerEvents: [],
    },
    {
      slug: "lamont-butler",
      firstName: "Lamont",
      lastName: "Butler",
      birthYear: 2001,
      hometown: "Riverside, CA",
      highSchool: "Riverside Polytechnic High School, Riverside, CA",
      isFeatured: true,
      bio: "Famous for hitting the buzzer-beater that sent San Diego State to the 2023 National Championship game. Transferred to Kentucky as a senior leader.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        location: "United States",
        statusNote: "After an impressive preseason with the Atlanta Hawks (18 pts, 6 reb, 5 ast in one game), Butler was waived and assigned to their G League affiliate. Tragically, he tore his ACL and meniscus just three days later on October 27, 2025, ending his season. At Kentucky he averaged 11.4 PPG, 4.3 APG, leading the team to the Sweet 16.",
        sourceUrl: "https://en.wikipedia.org/wiki/Lamont_Butler",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Point Guard", yearsAtSchool: "2024-2025", statsNote: "Senior • Transfer from San Diego State • Starting PG" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2024-2025", yearLabel: "Senior", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 11.4, reboundsPerGame: 2.9, assistsPerGame: 4.3 },
      ],
      careerEvents: [
        { year: 2023, title: "Hit buzzer-beater to send SDSU to National Championship game", eventType: "OTHER" },
      ],
    },
    {
      slug: "jaxson-robinson",
      firstName: "Jaxson",
      lastName: "Robinson",
      birthYear: 2002,
      hometown: "Ada, OK",
      highSchool: "Ada High School, Ada, OK",
      isFeatured: false,
      bio: "An elite three-point shooter who transferred from BYU to Arkansas to Kentucky, following his connection to Mark Pope.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "Memphis Grizzlies",
        league: "NBA",
        location: "Memphis, TN",
        statusNote: "Selected in the second round of the 2025 NBA Draft by the Memphis Grizzlies. One of Kentucky's top scorers in 2024-25, known for elite three-point shooting.",
        sourceUrl: "https://ukathletics.com/sports/mens-basketball/roster/jaxson-robinson/",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Guard / Wing", yearsAtSchool: "2024-2025", statsNote: "Senior • Transfer from Arkansas/BYU • Elite shooter" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2024-2025", yearLabel: "Senior", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 14.5, reboundsPerGame: 3.2, assistsPerGame: 1.8 },
      ],
      careerEvents: [
        { year: 2025, title: "Selected in 2nd round of NBA Draft by Memphis Grizzlies", eventType: "DRAFT" },
      ],
    },
    {
      slug: "amari-williams",
      firstName: "Amari",
      lastName: "Williams",
      birthYear: 2001,
      hometown: "London, England",
      highSchool: "Sunrise Christian Academy, Bel Aire, KS",
      isFeatured: false,
      bio: "A dominant defensive center from London who transferred from Drexel and led the SEC in blocks.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "Boston Celtics",
        league: "NBA",
        location: "Boston, MA",
        statusNote: "Drafted #46 overall by the Orlando Magic in 2025 and traded to Boston. Signed a two-way deal converted to a standard 2-year, $2.7M contract in February 2026. In the G League he dominated with 15.3 PPG, 11.4 RPG, 5.0 APG and a 33-point, 16-rebound double-double. At Kentucky he was the first 7-footer to record 115 assists in a season.",
        sourceUrl: "https://www.espn.com/nba/player/_/id/4702745/amari-williams",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Center", yearsAtSchool: "2024-2025", statsNote: "Senior • Transfer from Drexel • Led SEC in blocks" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2024-2025", yearLabel: "Senior", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 10.9, reboundsPerGame: 8.5, assistsPerGame: 3.2 },
      ],
      careerEvents: [],
    },
    {
      slug: "andrew-carr",
      firstName: "Andrew",
      lastName: "Carr",
      birthYear: 2001,
      hometown: "Berwyn, PA",
      highSchool: "Perkiomen School, Pennsburg, PA",
      isFeatured: false,
      bio: "A versatile stretch forward who transferred from Wake Forest and provided key minutes both off the bench and in the starting lineup.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        statusNote: "Exhausted eligibility after 2024-25. Pursuing professional basketball career.",
        sourceUrl: "https://ukathletics.com/sports/mens-basketball/roster/andrew-carr/",
      },
      membership: { role: "PLAYER", jerseyNumber: 13, position: "Forward", yearsAtSchool: "2024-2025", statsNote: "Senior • Transfer from Wake Forest • Stretch four" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2024-2025", yearLabel: "Senior", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 8.5, reboundsPerGame: 4.2, assistsPerGame: 1.0 },
      ],
      careerEvents: [],
    },
    {
      slug: "kerr-kriisa",
      firstName: "Kerr",
      lastName: "Kriisa",
      birthYear: 2000,
      hometown: "Tallinn, Estonia",
      highSchool: "DME Academy, Daytona Beach, FL",
      isFeatured: false,
      bio: "A journeyman college point guard from Estonia who played at Arizona and West Virginia before finishing his career at Kentucky.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Cincinnati",
        league: "Big 12",
        location: "Cincinnati, OH",
        statusNote: "Remarkably still playing college basketball in his 7th year of eligibility. Transferred to Cincinnati for 2025-26, averaging 7.3 PPG, 3.8 APG in 14 games (12 starts). The Estonian native has played at Arizona, West Virginia, Kentucky, and now Cincinnati across his marathon college career.",
        sourceUrl: "https://gobearcats.com/sports/mens-basketball/roster/player/kerr-kriisa",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Point Guard", yearsAtSchool: "2024-2025", statsNote: "6th-year Senior • Transfer from Arizona/WVU • Estonian national" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2024-2025", yearLabel: "6th-year Senior", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 6.2, reboundsPerGame: 1.5, assistsPerGame: 3.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "koby-brea",
      firstName: "Koby",
      lastName: "Brea",
      birthYear: 2000,
      hometown: "Montreal, QC, Canada",
      highSchool: "Northfield Mount Hermon, Gill, MA",
      isFeatured: false,
      bio: "A Canadian sharpshooter who transferred from Dayton and shot over 40% from three at Kentucky.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Phoenix Suns (two-way)",
        league: "NBA / G League",
        location: "Phoenix, AZ",
        statusNote: "Drafted #41 overall by Golden State and traded to the Phoenix Suns. The first player drafted under Mark Pope at Kentucky. On a two-way deal, he's averaging 21.2 PPG in the G League and getting NBA call-ups. At Kentucky he led the SEC in three-point percentage at 43.5%.",
        sourceUrl: "https://www.espn.com/nba/player/gamelog/_/id/4591259/koby-brea",
      },
      membership: { role: "PLAYER", jerseyNumber: 14, position: "Guard / Wing", yearsAtSchool: "2024-2025", statsNote: "6th-year Senior • Transfer from Dayton • 40%+ from three" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2024-2025", yearLabel: "6th-year Senior", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 11.6, reboundsPerGame: 2.8, assistsPerGame: 1.2 },
      ],
      careerEvents: [],
    },
    {
      slug: "brandon-garrison",
      firstName: "Brandon",
      lastName: "Garrison",
      birthYear: 2004,
      hometown: "Austin, TX",
      highSchool: "Vandegrift High School, Austin, TX",
      isFeatured: false,
      bio: "An athletic big man who showed flashes as a shot-blocker and rim-runner.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Kentucky",
        league: "SEC",
        location: "Lexington, KY",
        statusNote: "Returned to Kentucky for the 2025-26 season. Part of the returning core for Mark Pope's second year.",
        sourceUrl: "https://ukathletics.com/sports/mens-basketball/roster/brandon-garrison/",
      },
      membership: { role: "PLAYER", jerseyNumber: 22, position: "Forward / Center", yearsAtSchool: "2023-present", statsNote: "Sophomore • Athletic rim protector" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2024-2025", yearLabel: "Sophomore", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 3.8, reboundsPerGame: 3.0, assistsPerGame: 0.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "travis-perry",
      firstName: "Travis",
      lastName: "Perry",
      birthYear: 2005,
      hometown: "Eddyville, KY",
      highSchool: "Lyon County High School, Eddyville, KY",
      isFeatured: true,
      bio: "Kentucky's Mr. Basketball and the all-time leading scorer in Kentucky high school history (4,437 points). A beloved in-state recruit.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Kentucky",
        league: "SEC",
        location: "Lexington, KY",
        statusNote: "Returned to Kentucky for 2025-26 as a sophomore with an expanded role. Perry is the all-time leading scorer in Kentucky high school basketball history with 4,437 points at Lyon County.",
        sourceUrl: "https://ukathletics.com/sports/mens-basketball/roster/travis-perry/",
      },
      membership: { role: "PLAYER", jerseyNumber: 10, position: "Guard", yearsAtSchool: "2024-present", statsNote: "Freshman • KY Mr. Basketball • All-time KY HS scoring leader (4,437 pts)" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2024-2025", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 5.5, reboundsPerGame: 1.8, assistsPerGame: 1.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "ansley-almonor",
      firstName: "Ansley",
      lastName: "Almonor",
      birthYear: 2001,
      hometown: "Paterson, NJ",
      highSchool: "Roselle Catholic High School, Roselle, NJ",
      isFeatured: false,
      bio: "Gained fame as a key player in Fairleigh Dickinson's historic 16-over-1 upset of Purdue in the 2023 NCAA Tournament.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard / Forward",
        currentEmployer: "Salon Vilpas",
        league: "Finnish Korisliiga",
        location: "Salo, Finland",
        statusNote: "Signed his first professional contract with Salon Vilpas in Finland in August 2025. Averaging 14.2 PPG with a career-high 40-point game (9-13 from three). Won Finnish Korisliiga Player of the Week. At Kentucky he made history as the first player to shoot 50/40/90 splits in a season.",
        sourceUrl: "https://basketball.eurobasket.com/player/Ansley-Almonor/560681",
      },
      membership: { role: "PLAYER", jerseyNumber: 11, position: "Wing / Forward", yearsAtSchool: "2024-2025", statsNote: "Senior • Transfer from FDU • Key player in 16-over-1 Purdue upset" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2024-2025", yearLabel: "Senior", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 9.8, reboundsPerGame: 3.5, assistsPerGame: 1.0 },
      ],
      careerEvents: [
        { year: 2023, title: "Part of FDU's historic 16-over-1 upset of Purdue", eventType: "OTHER" },
      ],
    },
    {
      slug: "jayden-quaintance",
      firstName: "Jayden",
      lastName: "Quaintance",
      birthYear: 2006,
      hometown: "Denton, TX",
      highSchool: "IMG Academy, Bradenton, FL",
      isFeatured: true,
      bio: "A five-star freshman with elite athleticism and defensive versatility. One of the top recruits in the 2024 class.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Kentucky",
        league: "SEC",
        location: "Lexington, KY",
        statusNote: "Tore his ACL during the 2024-25 season. Returned for 4 games in December 2025 (10 pts, 8 reb, 2 blk vs St. John's in debut) before knee swelling returned. Projected top-5 to top-10 pick in the 2026 NBA Draft (ESPN: #6 to Memphis Grizzlies). The 6-10 sophomore is one of the most athletic prospects in college basketball.",
        sourceUrl: "https://www.tankathon.com/players/jayden-quaintance",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Forward", yearsAtSchool: "2024-present", statsNote: "Freshman • Five-star • Tore ACL • Projected top-10 pick 2026" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2024-2025", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 4, pointsPerGame: 5.0, reboundsPerGame: 5.0, assistsPerGame: 0.5 },
      ],
      careerEvents: [
        { year: 2025, title: "Tore ACL during freshman season", eventType: "INJURY" },
      ],
    },
    {
      slug: "collin-chandler",
      firstName: "Collin",
      lastName: "Chandler",
      birthYear: 2004,
      hometown: "Boise, ID",
      highSchool: "Boise High School, Boise, ID",
      isFeatured: false,
      bio: "A sharpshooting guard who followed Mark Pope from BYU to Kentucky.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Kentucky",
        league: "SEC",
        location: "Lexington, KY",
        statusNote: "Transferred from BYU following Pope to Kentucky. Contributing guard on the 2024-25 roster.",
        sourceUrl: "https://ukathletics.com/sports/mens-basketball/roster/collin-chandler/",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Guard", yearsAtSchool: "2024-present", statsNote: "Sophomore • Transfer from BYU • Followed Pope" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2024-2025", yearLabel: "Sophomore", sortOrder: 201, gamesPlayed: 30, pointsPerGame: 3.2, reboundsPerGame: 1.0, assistsPerGame: 0.8 },
      ],
      careerEvents: [],
    },
    {
      slug: "jasper-johnson",
      firstName: "Jasper",
      lastName: "Johnson",
      birthYear: 2006,
      hometown: "Southern California",
      highSchool: "Reclassified to 2024 class",
      isFeatured: false,
      bio: "A five-star guard who reclassified from the 2025 class to join Kentucky a year early. Dynamic combo guard with pro potential.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Kentucky",
        league: "SEC",
        location: "Lexington, KY",
        statusNote: "Returned to Kentucky for 2025-26 as a freshman (originally a 2025 class recruit). Averaging 4.9 PPG and 1.6 APG in 35 games off the bench. Gold medalist at the U18 Americas Championship (2024) and U19 World Cup (2025). From Versailles, KY, attended Link Academy and Overtime Elite.",
        sourceUrl: "https://ukathletics.com/sports/mbball/roster/player/jasper-johnson/",
      },
      membership: { role: "PLAYER", position: "Guard", yearsAtSchool: "2024-present", statsNote: "Freshman • Five-star recruit • U19 World Cup gold medalist" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2024-2025", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 35, pointsPerGame: 4.9, reboundsPerGame: 1.1, assistsPerGame: 1.6 },
      ],
      careerEvents: [
        { year: 2025, title: "Won gold at U19 World Cup with Team USA", eventType: "AWARD" },
      ],
    },
  ],
};
