import type { TeamSeed } from "./types";

export const kentuckyBasketball2026: TeamSeed = {
  slug: "kentucky-basketball-2026",
  name: "Kentucky Wildcats",
  season: "2025-2026",
  sport: "Men's Basketball",
  school: "University of Kentucky",
  conference: "SEC",
  accomplishment: "Mark Pope Year 2 (current season)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png",
  mascotName: "Wildcat",
  people: [
    {
      slug: "otega-oweh",
      firstName: "Otega",
      lastName: "Oweh",
      birthYear: 2003,
      hometown: "Manalapan, NJ",
      highSchool: "Montverde Academy, Montverde, FL",
      isFeatured: true,
      bio: "Returning as the team's best player and an All-SEC performer in his junior season.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Kentucky",
        league: "SEC",
        location: "Lexington, KY",
        statusNote: "The team's leading scorer and an All-SEC performer. Potential NBA Draft pick after this season.",
        sourceUrl: "https://ukathletics.com/sports/mbball/roster/",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Guard", yearsAtSchool: "2023-present", statsNote: "Junior • All-SEC • Team's best player" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Montverde Academy", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 32.8, reboundsPerGame: 5.2, assistsPerGame: 5.2 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2025-2026", yearLabel: "Junior", sortOrder: 201, gamesPlayed: 55, pointsPerGame: 18.5, reboundsPerGame: 5.2, assistsPerGame: 2.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "jaland-lowe",
      firstName: "Jaland",
      lastName: "Lowe",
      birthYear: 2003,
      hometown: "Pittsburgh, PA",
      highSchool: "Allderdice High School, Pittsburgh, PA",
      isFeatured: true,
      bio: "A dynamic transfer point guard from Pittsburgh who brings elite playmaking and scoring ability.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Kentucky",
        league: "SEC",
        location: "Lexington, KY",
        statusNote: "Transfer from Pitt who was one of the top portal additions in the country. Potential NBA Draft pick.",
        sourceUrl: "https://ukathletics.com/sports/mbball/roster/",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Guard", yearsAtSchool: "2025-present", statsNote: "Transfer from Pitt • Elite playmaker" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Allderdice High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 26.3, reboundsPerGame: 3.0, assistsPerGame: 9.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2025-2026", yearLabel: "Junior", sortOrder: 201, gamesPlayed: 55, pointsPerGame: 14.2, reboundsPerGame: 3.0, assistsPerGame: 5.8 },
      ],
      careerEvents: [],
    },
    {
      slug: "jayden-quaintance",
      firstName: "Jayden",
      lastName: "Quaintance",
      birthYear: 2006,
      hometown: "Denton, TX",
      highSchool: "IMG Academy, Bradenton, FL",
      isFeatured: true,
      bio: "A transfer from Arizona State who was originally a five-star recruit. Elite athlete with defensive versatility.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Kentucky",
        league: "SEC",
        location: "Lexington, KY",
        statusNote: "Recovering from a torn ACL suffered during his freshman year. Returned for 4 games in December (10 pts, 8 reb, 2 blk in debut) before swelling returned. Projected top-5 to top-10 pick in the 2026 NBA Draft despite the injury.",
        sourceUrl: "https://ukathletics.com/sports/mbball/roster/",
      },
      membership: { role: "PLAYER", jerseyNumber: 21, position: "Forward", yearsAtSchool: "2025-present", statsNote: "Transfer from Arizona State • Five-star talent" },
      careerEvents: [],
    },
    {
      slug: "jasper-johnson",
      firstName: "Jasper",
      lastName: "Johnson",
      birthYear: 2006,
      hometown: "Southern California",
      highSchool: "Reclassified to 2025 class",
      isFeatured: false,
      bio: "A five-star guard who committed to Kentucky for the 2025-26 season. Dynamic combo guard with pro potential.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Kentucky",
        league: "SEC",
        location: "Lexington, KY",
        statusNote: "Five-star freshman guard. Potential one-and-done NBA prospect.",
        sourceUrl: "https://ukathletics.com/sports/mbball/roster/",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Guard", yearsAtSchool: "2025-present", statsNote: "Freshman • Five-star recruit" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Reclassified to 2025 class", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 17.8, reboundsPerGame: 2.2, assistsPerGame: 5.6 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2025-2026", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 55, pointsPerGame: 8.5, reboundsPerGame: 2.2, assistsPerGame: 2.8 },
      ],
      careerEvents: [],
    },
    {
      slug: "denzel-aberdeen",
      firstName: "Denzel",
      lastName: "Aberdeen",
      birthYear: 2004,
      hometown: "Montreal, QC, Canada",
      highSchool: "Transferred to Kentucky from Florida",
      isFeatured: false,
      bio: "A Canadian guard who transferred from Florida and brings shooting and versatility.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Kentucky",
        league: "SEC",
        location: "Lexington, KY",
        statusNote: "Transfer from Florida. Canadian guard who adds perimeter shooting.",
        sourceUrl: "https://ukathletics.com/sports/mbball/roster/",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Guard", yearsAtSchool: "2025-present", statsNote: "Transfer from Florida • Canadian" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Transferred to Kentucky from Florida", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 17.0, reboundsPerGame: 2.5, assistsPerGame: 4.0 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2025-2026", yearLabel: "Junior (transfer from Florida)", sortOrder: 201, gamesPlayed: 30, pointsPerGame: 8.0, reboundsPerGame: 2.5, assistsPerGame: 1.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "kam-williams-uk",
      firstName: "Kam",
      lastName: "Williams",
      birthYear: 2003,
      hometown: "Unknown",
      highSchool: "Transferred from Tulane",
      isFeatured: false,
      bio: "A 6-8 versatile guard who transferred from Tulane, bringing size and length to the backcourt.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Kentucky",
        league: "SEC",
        location: "Lexington, KY",
        statusNote: "Transfer from Tulane. Brings size at 6-8 to the guard position.",
        sourceUrl: "https://ukathletics.com/sports/mbball/roster/",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Guard", yearsAtSchool: "2025-present", statsNote: "Transfer from Tulane • 6-8 guard" },
      careerEvents: [],
    },
    {
      slug: "mouhamed-dioubate",
      firstName: "Mouhamed",
      lastName: "Dioubate",
      birthYear: 2003,
      hometown: "Guinea",
      highSchool: "Transferred from Alabama",
      isFeatured: false,
      bio: "A physical 6-7 forward who transferred from Alabama to add toughness and rebounding.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Kentucky",
        league: "SEC",
        location: "Lexington, KY",
        statusNote: "Transfer from Alabama. Physical forward who adds frontcourt depth.",
        sourceUrl: "https://ukathletics.com/sports/mbball/roster/",
      },
      membership: { role: "PLAYER", jerseyNumber: 23, position: "Forward", yearsAtSchool: "2025-present", statsNote: "Transfer from Alabama • Physical forward" },
      careerEvents: [],
    },
    {
      slug: "brandon-garrison",
      firstName: "Brandon",
      lastName: "Garrison",
      birthYear: 2004,
      hometown: "Austin, TX",
      highSchool: "Vandegrift High School, Austin, TX",
      isFeatured: false,
      bio: "Returning junior center expected to play a much bigger role with Amari Williams' departure.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Kentucky",
        league: "SEC",
        location: "Lexington, KY",
        statusNote: "Returning junior. Expected to start at center with an expanded role.",
        sourceUrl: "https://ukathletics.com/sports/mbball/roster/",
      },
      membership: { role: "PLAYER", jerseyNumber: 10, position: "Center", yearsAtSchool: "2023-present", statsNote: "Junior • Returning big man • Expanded role" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Vandegrift High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 14.3, reboundsPerGame: 10.2, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2025-2026", yearLabel: "Junior", sortOrder: 201, gamesPlayed: 55, pointsPerGame: 6.2, reboundsPerGame: 5.5, assistsPerGame: 1.0 },
      ],
      careerEvents: [],
    },
    {
      slug: "collin-chandler",
      firstName: "Collin",
      lastName: "Chandler",
      birthYear: 2004,
      hometown: "Boise, ID",
      highSchool: "Boise High School, Boise, ID",
      isFeatured: false,
      bio: "Returning guard who followed Pope from BYU. Entering his third year.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Kentucky",
        league: "SEC",
        location: "Lexington, KY",
        statusNote: "Returning junior. Followed Pope from BYU.",
        sourceUrl: "https://ukathletics.com/sports/mbball/roster/",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Guard", yearsAtSchool: "2024-present", statsNote: "Junior • Followed Pope from BYU" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Boise High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 13.2, reboundsPerGame: 1.5, assistsPerGame: 3.6 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2025-2026", yearLabel: "Junior", sortOrder: 201, gamesPlayed: 45, pointsPerGame: 5.5, reboundsPerGame: 1.5, assistsPerGame: 1.2 },
      ],
      careerEvents: [],
    },
    {
      slug: "malachi-moreno",
      firstName: "Malachi",
      lastName: "Moreno",
      birthYear: 2006,
      hometown: "Unknown",
      highSchool: "High school in the U.S.",
      isFeatured: false,
      bio: "A 6-11 freshman center who is one of Mark Pope's top recruits in the 2025 class.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Kentucky",
        league: "SEC",
        location: "Lexington, KY",
        statusNote: "Freshman center. Four-star recruit who brings size at 6-11.",
        sourceUrl: "https://ukathletics.com/sports/mbball/roster/",
      },
      membership: { role: "PLAYER", jerseyNumber: 24, position: "Center", yearsAtSchool: "2025-present", statsNote: "Freshman • 6-11 center" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "High school in the U.S.", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 11.8, reboundsPerGame: 6.9, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2025-2026", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 25, pointsPerGame: 4.5, reboundsPerGame: 3.0, assistsPerGame: 0.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "andrija-jelavic",
      firstName: "Andrija",
      lastName: "Jelavic",
      birthYear: 2006,
      hometown: "Croatia",
      highSchool: "Croatian youth system",
      isFeatured: false,
      bio: "A 6-11 Croatian forward who adds international depth to the frontcourt.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Kentucky",
        league: "SEC",
        location: "Lexington, KY",
        statusNote: "Freshman international prospect from Croatia.",
        sourceUrl: "https://ukathletics.com/sports/mbball/roster/",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Forward", yearsAtSchool: "2025-present", statsNote: "Freshman • 6-11 Croatian forward" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Croatian youth system", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 9.5, reboundsPerGame: 6.2, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2025-2026", yearLabel: "Freshman (Croatian)", sortOrder: 201, gamesPlayed: 20, pointsPerGame: 3.0, reboundsPerGame: 2.5, assistsPerGame: 0.3 },
      ],
      careerEvents: [],
    },
    {
      slug: "braydon-hawthorne",
      firstName: "Braydon",
      lastName: "Hawthorne",
      birthYear: 2006,
      hometown: "Unknown",
      highSchool: "High school in the U.S.",
      isFeatured: false,
      bio: "A 6-8 freshman forward and four-star recruit who adds length and athleticism.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Kentucky",
        league: "SEC",
        location: "Lexington, KY",
        statusNote: "Freshman forward. Four-star recruit who stepped in against #1 Purdue.",
        sourceUrl: "https://ukathletics.com/sports/mbball/roster/",
      },
      membership: { role: "PLAYER", jerseyNumber: 22, position: "Forward", yearsAtSchool: "2025-present", statsNote: "Freshman • Four-star recruit" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "High school in the U.S.", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 12.5, reboundsPerGame: 7.5, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2025-2026", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 25, pointsPerGame: 5.0, reboundsPerGame: 3.5, assistsPerGame: 0.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "reece-potter",
      firstName: "Reece",
      lastName: "Potter",
      birthYear: 2004,
      hometown: "Unknown",
      highSchool: "Transferred from Miami (OH)",
      isFeatured: false,
      bio: "A 7-1 transfer center from Miami (OH) who adds depth in the post.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Kentucky",
        league: "SEC",
        location: "Lexington, KY",
        statusNote: "Transfer from Miami (OH). 7-1 center providing frontcourt depth.",
        sourceUrl: "https://ukathletics.com/sports/mbball/roster/",
      },
      membership: { role: "PLAYER", jerseyNumber: 33, position: "Center", yearsAtSchool: "2025-present", statsNote: "Transfer from Miami (OH) • 7-1 center" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Transferred from Miami (OH)", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 10.2, reboundsPerGame: 8.2, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2025-2026", yearLabel: "Junior (transfer from Miami OH)", sortOrder: 201, gamesPlayed: 20, pointsPerGame: 3.5, reboundsPerGame: 4.0, assistsPerGame: 0.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "trent-noah-uk",
      firstName: "Trent",
      lastName: "Noah",
      birthYear: 2005,
      hometown: "Radcliff, KY",
      highSchool: "John Hardin High School, Radcliff, KY",
      isFeatured: false,
      bio: "A returning walk-on guard from Kentucky providing depth and practice competition.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Kentucky",
        league: "SEC",
        location: "Lexington, KY",
        statusNote: "Returning sophomore walk-on. In-state player from Radcliff, KY.",
        sourceUrl: "https://ukathletics.com/sports/mbball/roster/",
      },
      membership: { role: "PLAYER", jerseyNumber: 9, position: "Forward", yearsAtSchool: "2024-present", statsNote: "Sophomore walk-on • In-state player" },
      careerEvents: [],
    },
    {
      slug: "chin-coleman",
      firstName: "Chin",
      lastName: "Coleman",
      birthYear: 1979,
      hometown: "Chicago, IL",
      highSchool: "Chicago, IL",
      bio: "Assistant coach who came to Kentucky from Illinois alongside Orlando Antigua in 2021. Known as an elite recruiter and player developer.",
      status: { occupationType: "COACH", currentTitle: "Assistant Coach", currentEmployer: "Kentucky basketball program", location: "Lexington, KY", statusNote: "Coleman joined Kentucky's staff in 2021 after working at Illinois. He remained on staff through Calipari's final season and the transition to Mark Pope. Known for his recruiting connections in the Midwest and South.", sourceUrl: "https://ukathletics.com/sports/mbball/roster/coach/chin-coleman/" },
      membership: { role: "ASSISTANT_COACH", position: "Assistant Coach", yearsAtSchool: "2021-2024" },
      careerEvents: [],
    },
    {
      slug: "mark-pope",
      firstName: "Mark",
      lastName: "Pope",
      birthYear: 1972,
      hometown: "Lincoln, NE",
      highSchool: "Bellevue West High School, Bellevue, NE",
      isFeatured: true,
      bio: "In his second year as Kentucky head coach, building his roster through the transfer portal and recruiting.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "University of Kentucky",
        league: "SEC",
        location: "Lexington, KY",
        statusNote: "Former Kentucky player (1996 national champion) in his second season as head coach. Led Kentucky to a 23-10 record and NCAA Tournament in Year 1.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mark_Pope",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2024-present", statsNote: "Year 2 • Built roster through transfer portal" },
      careerEvents: [
        { year: 2024, title: "Named Kentucky head coach", eventType: "CAREER" },
      ],
    },
  ],
};
