import type { TeamSeed } from "./types";

export const kentuckyBasketball2024: TeamSeed = {
  slug: "kentucky-basketball-2024",
  name: "Kentucky Wildcats",
  season: "2023-2024",
  sport: "Men's Basketball",
  school: "University of Kentucky",
  conference: "SEC",
  accomplishment: "Calipari's Last Year (23-10, lost to Oakland R1)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png",
  mascotName: "Wildcat",
  people: [
    {
      slug: "reed-sheppard",
      firstName: "Reed",
      lastName: "Sheppard",
      birthYear: 2005,
      hometown: "London, KY",
      highSchool: "North Laurel High School, London, KY",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1642263.png",
      bio: "Son of former Kentucky players Jeff Sheppard and Stacey Reed. Shot an absurd 52.1% from three as a freshman — the best in the nation — and was drafted #3 overall.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Houston Rockets",
        league: "NBA",
        location: "Houston, TX",
        statusNote: "Drafted #3 overall by the Houston Rockets in 2024 after leading the nation in three-point shooting at 52.1%. Averaging 13.5 PPG in 2025-26, shooting 40.7% from three. Scored 27 points with 9 threes (career high) vs. the Bucks on April 2, 2026. Son of UK legends Jeff Sheppard and Stacey Reed.",
        sourceUrl: "https://www.nba.com/player/1642263/reed-sheppard",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Guard", yearsAtSchool: "2023-2024", statsNote: "Freshman • 12.5 PPG • 52.1% from three (led nation) • #3 overall pick", gamesPlayed: 33, pointsPerGame: 12.5, reboundsPerGame: 4.1, assistsPerGame: 4.5 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "North Laurel High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 23.8, reboundsPerGame: 4.1, assistsPerGame: 7.9 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2023-2024", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 12.5, reboundsPerGame: 4.1, assistsPerGame: 4.5 },
      
        { level: "PROFESSIONAL", teamName: "Houston Rockets", season: "2024-25", yearLabel: "2024-25 (Rookie)", sortOrder: 301, gamesPlayed: 70, pointsPerGame: 10.5, reboundsPerGame: 2.8, assistsPerGame: 3.0 },
        { level: "PROFESSIONAL", teamName: "Houston Rockets", season: "2025-26", yearLabel: "2025-26", sortOrder: 302, gamesPlayed: 65, pointsPerGame: 13.5, reboundsPerGame: 3.4, assistsPerGame: 2.9 },
      ],
      careerEvents: [
        { year: 2024, title: "Selected #3 overall by the Houston Rockets", eventType: "DRAFT" },
      ],
    },
    {
      slug: "rob-dillingham",
      firstName: "Rob",
      lastName: "Dillingham",
      birthYear: 2005,
      hometown: "Hickory, NC",
      highSchool: "Overtime Elite (previously Donda Academy)",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1642265.png",
      bio: "A flashy freshman point guard who came off the bench but provided instant offense with 15.2 PPG and 44.4% from three.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Chicago Bulls",
        league: "NBA",
        location: "Chicago, IL",
        statusNote: "Drafted #8 overall by the San Antonio Spurs in 2024 and immediately traded to the Minnesota Timberwolves. Traded again to the Chicago Bulls in February 2026.",
        sourceUrl: "https://en.wikipedia.org/wiki/Rob_Dillingham",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Guard", yearsAtSchool: "2023-2024", statsNote: "Freshman • 15.2 PPG off bench • 44.4% from three • #8 overall pick", gamesPlayed: 33, pointsPerGame: 15.2, assistsPerGame: 3.9 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Overtime Elite (previously Donda Academy)", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 27.8, reboundsPerGame: 1.0, assistsPerGame: 7.1 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2023-2024", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 15.2, assistsPerGame: 3.9 },
      
        { level: "PROFESSIONAL", teamName: "Minnesota Timberwolves", season: "2024-25", yearLabel: "2024-25 (Rookie)", sortOrder: 301, gamesPlayed: 49, pointsPerGame: 4.5, reboundsPerGame: 1.0, assistsPerGame: 2.0 },
        { level: "PROFESSIONAL", teamName: "Chicago Bulls", season: "2025-26", yearLabel: "2025-26 (traded)", sortOrder: 302, gamesPlayed: 30, pointsPerGame: 8.0, reboundsPerGame: 1.5, assistsPerGame: 3.5 },
      ],
      careerEvents: [
        { year: 2024, title: "Selected #8 overall by San Antonio (traded to Minnesota)", eventType: "DRAFT" },
        { year: 2026, title: "Traded to Chicago Bulls", eventType: "TRADE" },
      ],
    },
    {
      slug: "dj-wagner",
      firstName: "DJ",
      lastName: "Wagner",
      birthYear: 2005,
      hometown: "Camden, NJ",
      highSchool: "Camden High School, Camden, NJ",
      isFeatured: false,
      bio: "Son of Dajuan Wagner and grandson of Milt Wagner — a third-generation Kentucky basketball player. Started 28 of 29 games as a freshman.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Arkansas",
        league: "SEC",
        location: "Fayetteville, AR",
        statusNote: "Followed John Calipari to Arkansas after Calipari left Kentucky. Averaged 7.6 PPG with 2.4 APG as a junior in 2025-26. Third-generation Kentucky basketball legacy.",
        sourceUrl: "https://arkansasrazorbacks.com/roster/d-j-wagner/",
      },
      membership: { role: "PLAYER", jerseyNumber: 21, position: "Guard", yearsAtSchool: "2023-2024", statsNote: "Freshman • 9.9 PPG, 3.3 APG • 3rd-gen UK legacy • Transferred to Arkansas" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Camden High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 19.9, reboundsPerGame: 1.6, assistsPerGame: 6.3 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2023-2024", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 29, pointsPerGame: 9.9, reboundsPerGame: 1.6, assistsPerGame: 3.3 },
      ],
      careerEvents: [
        { year: 2024, title: "Transferred to Arkansas to follow Calipari", eventType: "OTHER" },
      ],
    },
    {
      slug: "antonio-reeves",
      firstName: "Antonio",
      lastName: "Reeves",
      birthYear: 2001,
      hometown: "Chicago, IL",
      highSchool: "Simeon Career Academy, Chicago, IL",

      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1641810.png",
      isFeatured: false,
      bio: "Returned for a second season at Kentucky as the team's leading scorer.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Charlotte Hornets (two-way)",
        league: "NBA / G League",
        statusNote: "A sharpshooting transfer from Illinois State who won SEC Co-Sixth Man of the Year in 2022-23, then returned as the team's leading scorer in 2023-24 (14.8 PPG). Drafted #47 overall by the Orlando Magic in 2024 and traded to the New Orleans Pelicans. Waived by New Orleans in July 2025, then signed a two-way deal with the Charlotte Hornets. In limited NBA minutes (7.6 MPG), shooting 47.4% from the field and 50.0% from three. Mostly plays for the Greensboro Swarm (G League).",
        sourceUrl: "https://www.nba.com/player/1641810/antonio-reeves",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Guard", yearsAtSchool: "2022-2024", statsNote: "Graduate Senior • Team's leading scorer • 14.8 PPG" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Simeon Career Academy", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 26.9, reboundsPerGame: 2.5, assistsPerGame: 3.7 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2022-2023", yearLabel: "Senior (SEC Co-6MOY)", sortOrder: 201, gamesPlayed: 34, pointsPerGame: 14.6, reboundsPerGame: 2.5, assistsPerGame: 1.3 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2023-2024", yearLabel: "Graduate Senior", sortOrder: 202, gamesPlayed: 33, pointsPerGame: 16.6, reboundsPerGame: 2.6, assistsPerGame: 1.5 },
      
        { level: "PROFESSIONAL", teamName: "New Orleans Pelicans", season: "2024-25", yearLabel: "2024-25", sortOrder: 301, gamesPlayed: 44, minutesPerGame: 10.0, pointsPerGame: 6.9, reboundsPerGame: 1.4, assistsPerGame: 0.9, fieldGoalPct: 0.456, threePointPct: 0.395, freeThrowPct: 0.850 },
      ],
      careerEvents: [
        { year: 2024, title: "Selected #47 overall by the Orlando Magic", eventType: "DRAFT" },
      ],
    },
    {
      slug: "justin-edwards",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1642348.png",
      firstName: "Justin",
      lastName: "Edwards",
      birthYear: 2005,
      hometown: "Philadelphia, PA",
      highSchool: "Imhotep Institute Charter High School, Philadelphia, PA",
      isFeatured: false,
      bio: "A five-star freshman forward from Philadelphia who went undrafted but earned an NBA spot with the hometown 76ers.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Philadelphia 76ers",
        league: "NBA",
        location: "Philadelphia, PA",
        statusNote: "Went undrafted in 2024 but signed a two-way with the hometown 76ers, later converted to a standard contract. Made 44 appearances (26 starts) in 2024-25, averaging 10.1 PPG. Re-signed on a 3-year, $2M deal.",
        sourceUrl: "https://www.nba.com/player/1642348/justin-edwards",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Forward", yearsAtSchool: "2023-2024", statsNote: "Freshman • Five-star recruit • 8.8 PPG • Now with 76ers" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Imhotep Institute Charter High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 18.2, reboundsPerGame: 7.4, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2023-2024", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 8.8, reboundsPerGame: 3.4, assistsPerGame: 1.6 },
      
        { level: "PROFESSIONAL", teamName: "Philadelphia 76ers", season: "2024-25", yearLabel: "2024-25 (undrafted)", sortOrder: 301, gamesPlayed: 44, pointsPerGame: 10.1, reboundsPerGame: 3.4, assistsPerGame: 1.6 },
        { level: "PROFESSIONAL", teamName: "Philadelphia 76ers", season: "2025-26", yearLabel: "2025-26", sortOrder: 302, gamesPlayed: 50, pointsPerGame: 8.5, reboundsPerGame: 3.0, assistsPerGame: 1.5 },
      ],
      careerEvents: [
        { year: 2024, title: "Went undrafted; signed two-way with Philadelphia 76ers", eventType: "SIGNING" },
      ],
    },
    {
      slug: "tre-mitchell",
      firstName: "Tre",
      lastName: "Mitchell",
      birthYear: 2001,
      hometown: "Pittsburgh, PA",
      highSchool: "Woodrow Wilson High School, Washington, D.C.",
      isFeatured: false,
      bio: "A well-traveled graduate transfer who provided experience in the post, having previously played at UMass, West Virginia, and Texas.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward / Center",
        currentEmployer: "JL Bourg",
        league: "LNB Pro A / EuroCup (France)",
        location: "Bourg-en-Bresse, France",
        statusNote: "A well-traveled graduate transfer who played at UMass, West Virginia, and Texas before arriving at Kentucky. Averaged 10.7 PPG, 7.2 RPG, and 2.6 APG for the Wildcats. Went undrafted in 2024 but moved to Europe — first Germany's Lowen Braunschweig (FIBA Europe Cup), then JL Bourg-en-Bresse in France's LNB Pro A and EuroCup where he's averaging 10.9 PPG and 3.0 SPG.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tre_Mitchell",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Forward / Center", yearsAtSchool: "2023-2024", statsNote: "Graduate • Transfer from Texas/WVU/UMass • 10.7 PPG, 7.2 RPG" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Woodrow Wilson High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 24.5, reboundsPerGame: 10.9, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2023-2024", yearLabel: "Graduate", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 13.0, reboundsPerGame: 6.1, assistsPerGame: 1.3 },
      
        { level: "PROFESSIONAL", teamName: "Lowen Braunschweig (Germany)", season: "2024-25", yearLabel: "2024-25 (Germany)", sortOrder: 301, gamesPlayed: 25, pointsPerGame: 12.0, reboundsPerGame: 5.0, assistsPerGame: 2.0 },
        { level: "PROFESSIONAL", teamName: "JL Bourg (France)", season: "2025-26", yearLabel: "2025-26 (France/EuroCup)", sortOrder: 302, gamesPlayed: 15, pointsPerGame: 10.9, reboundsPerGame: 3.0, assistsPerGame: 1.8 },
      ],
      careerEvents: [{ year: 2024, title: "Went undrafted; began European career", eventType: "CAREER" }],
    },
    {
      slug: "adou-thiero",
      firstName: "Adou",
      lastName: "Thiero",
      birthYear: 2004,
      hometown: "Washington, D.C.",
      highSchool: "Transferred to Kentucky from Guinea via D.C.",

      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1642876.png",
      isFeatured: false,
      bio: "A sophomore guard/forward who followed Calipari to Arkansas and became their leading scorer.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Los Angeles Lakers",
        league: "NBA",
        statusNote: "Followed Calipari to Arkansas, led team in scoring (15.1 PPG). Drafted #36 in 2025 (traded to Lakers). Rookie in 2025-26.",
        sourceUrl: "https://www.nba.com/player/1642876/adou-thiero",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Guard / Forward", yearsAtSchool: "2022-2024", statsNote: "Sophomore • 5.7 PPG • Later led Arkansas at 15.1 PPG" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Transferred to Kentucky from Guinea via D.C.", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 11.8, reboundsPerGame: 6.6, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2022-2023", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 31, pointsPerGame: 4.5, reboundsPerGame: 2.8, assistsPerGame: 0.9 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2023-2024", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 33, pointsPerGame: 5.7, reboundsPerGame: 3.1, assistsPerGame: 1.1 },
      
        { level: "PROFESSIONAL", teamName: "Los Angeles Lakers", season: "2025-26", yearLabel: "2025-26 (Rookie, #36 pick)", sortOrder: 301, gamesPlayed: 15, pointsPerGame: 1.4, reboundsPerGame: 1.0, assistsPerGame: 0.3 },
      ],
      careerEvents: [
        { year: 2024, title: "Transferred to Arkansas", eventType: "OTHER" },
        { year: 2025, title: "Selected #36 overall (traded to Lakers)", eventType: "DRAFT" },
      ],
    },
    {
      slug: "zvonimir-ivisic",
      firstName: "Zvonimir",
      lastName: "Ivisic",
      birthYear: 2003,
      hometown: "Vodice, Croatia",
      highSchool: "Croatian youth system",
      isFeatured: false,
      bio: "A 7-2 Croatian freshman center who missed the first 16 games due to eligibility issues but showed promise when he played.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Illinois",
        league: "Big Ten",
        statusNote: "A 7-2 Croatian center who missed the first 16 games of his freshman year at Kentucky due to eligibility issues, then showed promise in 15 games (5.5 PPG, 3.3 RPG, 1.3 BPG). Followed Calipari to Arkansas for 2024-25, then transferred to Illinois for 2025-26 to play alongside his twin brother Tomislav — the first brothers to play together for Illinois since the Judson twins in 1956. Has 2.0 BPG and 5 blocks vs #5 UConn.",
        sourceUrl: "https://www.espn.com/mens-college-basketball/player/_/id/5174665/zvonimir-ivisic",
      },
      membership: { role: "PLAYER", jerseyNumber: 44, position: "Center", yearsAtSchool: "2023-2024", statsNote: "Freshman • 7-2 Croatian • 5.5 PPG in 15 games • Missed first 16 (eligibility)" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Croatian youth system", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 13.2, reboundsPerGame: 7.3, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2023-2024", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 15, pointsPerGame: 5.5, reboundsPerGame: 3.3, assistsPerGame: 0.5 },
      ],
      careerEvents: [
        { year: 2024, title: "Transferred to Arkansas, then Illinois", eventType: "OTHER" },
      ],
    },
    {
      slug: "aaron-bradshaw",
      firstName: "Aaron",
      lastName: "Bradshaw",
      birthYear: 2005,
      hometown: "Camden, NJ",
      highSchool: "IMG Academy, Bradenton, FL",
      isFeatured: false,
      bio: "A McDonald's All-American 7-1 freshman center and DJ Wagner's high school teammate.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Memphis",
        league: "AAC",
        statusNote: "After Kentucky and Ohio State, transferred to Memphis for 2025-26 where he's having a career-best season (8.6 PPG, 4.6 RPG, 55.6% FG).",
        sourceUrl: "https://gotigersgo.com/sports/mens-basketball/roster/aaron-bradshaw/12209",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Center", yearsAtSchool: "2023-2024", statsNote: "Freshman • McDonald's All-American • 4.9 PPG" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "IMG Academy", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 12.4, reboundsPerGame: 7.3, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2023-2024", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 26, pointsPerGame: 4.9, reboundsPerGame: 3.3, assistsPerGame: 0.3 },
      ],
      careerEvents: [
        { year: 2024, title: "Transferred to Ohio State", eventType: "OTHER" },
      ],
    },
    {
      slug: "ugonna-onyenso",
      firstName: "Ugonna",
      lastName: "Onyenso",
      birthYear: 2003,
      hometown: "Nigeria",
      highSchool: "Prep school in the U.S.",
      isFeatured: false,
      bio: "A sophomore shot-blocker who continued to develop his game.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Virginia",
        league: "ACC",
        statusNote: "A Nigerian center with elite shot-blocking ability who played two seasons at Kentucky. After transferring to Kansas State (2024-25) and then Virginia (2025-26), he exploded into one of the nation's best defenders — leading all power conferences in blocks (3.0 per game), setting the ACC Tournament record with 21 blocks in 3 games (shattering a 31-year-old record), and earning All-ACC Defensive Team honors. Block percentage of 16.8% was the highest in the nation per KenPom.",
        sourceUrl: "https://www.espn.com/mens-college-basketball/player/_/id/5037878/ugonna-onyenso",
      },
      membership: { role: "PLAYER", jerseyNumber: 33, position: "Center", yearsAtSchool: "2022-2024", statsNote: "Sophomore • Elite shot-blocker" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Prep school in the U.S.", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 8.9, reboundsPerGame: 6.4, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2022-2023", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 28, pointsPerGame: 2.6, reboundsPerGame: 2.6, assistsPerGame: 0.2 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2023-2024", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 30, pointsPerGame: 3.2, reboundsPerGame: 3.0, assistsPerGame: 0.2 },
      ],
      careerEvents: [
        { year: 2026, title: "Set ACC Tournament blocks record at Virginia", eventType: "OTHER" },
      ],
    },
    {
      slug: "joey-hart",
      firstName: "Joey",
      lastName: "Hart",
      birthYear: 2005,
      hometown: "Linton, IN",
      highSchool: "Linton-Stockton High School, Linton, IN",
      isFeatured: false,
      bio: "An Indiana sharpshooter and the seventh freshman in Kentucky's 2023 class who decommitted from UCF to join the Wildcats. Transferred home to Ball State after one season.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Ball State Cardinals",
        league: "Mid-American Conference",
        statusNote: "Averaged 23.6 PPG while shooting better than 40% from three at Linton-Stockton High School, leading them to the Indiana Class 2A State Finals as an Indiana Mr. Basketball finalist. Decommitted from UCF and joined Kentucky in June 2023, then appeared in just 7 games for 9 total minutes as a freshman, hitting his first career three vs. Marshall. Transferred home to Indiana in April 2024 to play for Ball State.",
        sourceUrl: "https://ballstatesports.com/news/2024/4/18/kentucky-transfer-and-former-indiana-mr-basketball-finalist-signs-with-ball-state",
      },
      membership: { role: "PLAYER", jerseyNumber: 20, position: "Guard", yearsAtSchool: "2023-2024", statsNote: "Freshman • Indiana Mr. Basketball finalist • Sharpshooter" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Linton-Stockton High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 23.6, threePointPct: 0.400 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2023-2024", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 7, pointsPerGame: 0.4 },
      ],
      careerEvents: [
        { year: 2024, title: "Transferred to Ball State", eventType: "TRANSFER" },
      ],
    },
    {
      slug: "jordan-burks",
      firstName: "Jordan",
      lastName: "Burks",
      birthYear: 2005,
      hometown: "Atlanta, GA",
      highSchool: "Overtime Elite Academy, Atlanta, GA",
      isFeatured: false,
      bio: "A 6-foot-9 forward who led Overtime Elite in scoring before reopening his recruitment and committing to Kentucky. Transferred to Georgetown after Calipari left for Arkansas.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Georgetown Hoyas",
        league: "Big East",
        statusNote: "Originally committed to Ole Miss but reopened his recruitment after Kermit Davis was fired and joined Kentucky in June 2023 after averaging 27.1 PPG at Overtime Elite the prior year. Appeared in 20 games for the 2023-24 Wildcats, averaging 1.9 PPG on 60% shooting in 7.1 minutes per game with a season-high 13 points on 6-of-6 shooting at Vanderbilt. After Calipari left for Arkansas, Burks entered the portal and committed to Ed Cooley and Georgetown for 2024-25.",
        sourceUrl: "https://www.casualhoya.com/2024/5/8/24152213/hoya-saxa-kentucky-transfer-wing-jordan-burks-commits-to-georgetown-hoyas-ed-cooley-portal-big-east",
      },
      membership: { role: "PLAYER", jerseyNumber: 14, position: "Forward", yearsAtSchool: "2023-2024", statsNote: "Freshman • Overtime Elite product" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Overtime Elite", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 27.1, fieldGoalPct: 0.467 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2023-2024", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 20, pointsPerGame: 1.9, reboundsPerGame: 1.7 },
      ],
      careerEvents: [
        { year: 2024, title: "Transferred to Georgetown", eventType: "TRANSFER" },
      ],
    },
    {
      slug: "brennan-canada",
      firstName: "Brennan",
      lastName: "Canada",
      birthYear: 2000,
      hometown: "Mount Sterling, KY",
      highSchool: "George Rogers Clark High School, Winchester, KY",
      isFeatured: false,
      bio: "A scholarship walk-on graduate forward in his fifth and final season at Kentucky. Beloved locker-room leader who finished his Wildcat career on the 2023-24 NCAA Tournament team.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Sport Leadership Graduate",
        statusNote: "Closed his five-year Kentucky career in 2023-24 as a graduate scholarship player after originally walking on in 2019. Appeared in five games as a graduate, was named to the 2024 SEC Community Service Team, and earned his master's in sport leadership in May 2024. One of the most respected locker-room presences of the Calipari era at UK.",
        sourceUrl: "https://ukathletics.com/sports/mbball/roster/player/brennan-canada/",
      },
      membership: { role: "PLAYER", jerseyNumber: 33, position: "Forward", yearsAtSchool: "2019-2024", statsNote: "Graduate • Walk-on turned scholarship player" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "George Rogers Clark High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 15.0, reboundsPerGame: 9.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2023-2024", yearLabel: "Graduate", sortOrder: 201, gamesPlayed: 5, pointsPerGame: 0.4 },
      ],
      careerEvents: [
        { year: 2024, title: "Earned master's in sport leadership", eventType: "EDUCATION" },
      ],
    },
    {
      slug: "grant-darbyshire",
      firstName: "Grant",
      lastName: "Darbyshire",
      birthYear: 2003,
      hometown: "Cincinnati, OH",
      highSchool: "Sycamore High School, Montgomery, OH",
      isFeatured: false,
      bio: "A walk-on guard and National Merit Scholar in his sophomore year at Kentucky. Three-year Wildcat who later transferred to Cincinnati.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Cincinnati Bearcats",
        league: "Big 12",
        statusNote: "Joined Kentucky as a walk-on in 2022 after captaining Sycamore High School and graduating summa cum laude as a National Merit Scholar Commended student. Saw action in four wins during the 2023-24 season (Marshall, Louisville, Illinois State, Vanderbilt) plus the LSU finale and the NCAA Tournament opener vs. Troy. SEC Honor Roll honoree and inducted into UK's Frank G. Ham Society of Character. Transferred to Cincinnati in 2025 to join former teammate Kerr Kriisa.",
        sourceUrl: "https://www.on3.com/teams/kentucky-wildcats/news/former-kentucky-walk-on-grant-darbyshire-transfers-cincinnati/",
      },
      membership: { role: "PLAYER", jerseyNumber: 13, position: "Guard", yearsAtSchool: "2022-2025", statsNote: "Walk-on • National Merit Scholar" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Sycamore High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 12.0, assistsPerGame: 4.0 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2023-2024", yearLabel: "Sophomore", sortOrder: 201, gamesPlayed: 6, pointsPerGame: 0.2 },
      ],
      careerEvents: [
        { year: 2025, title: "Transferred to Cincinnati", eventType: "TRANSFER" },
      ],
    },
    {
      slug: "walker-horn",
      firstName: "Walker",
      lastName: "Horn",
      birthYear: 2003,
      hometown: "Austin, TX",
      highSchool: "Westlake High School, Austin, TX",
      isFeatured: false,
      bio: "A walk-on guard and son of Northern Kentucky head coach Darrin Horn in his sophomore year at Kentucky. Continued his career at UK under Mark Pope.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Kentucky Wildcats",
        league: "SEC",
        statusNote: "Joined Kentucky as a walk-on in 2022 after a high school career split between Covington Catholic (KY) and Westlake High School (Austin, TX), where he averaged 9.3 PPG and 5.2 APG. Son of former South Carolina and current Northern Kentucky head coach Darrin Horn. Returned to Kentucky for an additional season after the House Settlement approval in June 2025 and scored his first career points as a senior under Mark Pope.",
        sourceUrl: "https://www.aseaofblue.com/2025/6/7/24445151/walker-horn-kentucky-basketball-ncaa-house-settlement-approval",
      },
      membership: { role: "PLAYER", jerseyNumber: 22, position: "Guard", yearsAtSchool: "2022-2026", statsNote: "Walk-on • Son of coach Darrin Horn" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Westlake High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 9.3, reboundsPerGame: 2.4, assistsPerGame: 5.2 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2023-2024", yearLabel: "Sophomore", sortOrder: 201, gamesPlayed: 4, pointsPerGame: 0.0 },
      ],
      careerEvents: [
        { year: 2025, title: "Returned to Kentucky after House Settlement", eventType: "OTHER" },
      ],
    },
    {
      slug: "john-calipari",
      firstName: "John",
      lastName: "Calipari",
      birthYear: 1959,
      hometown: "Moon Township, PA",
      highSchool: "Moon Area High School, Moon Township, PA",
      isFeatured: true,
      bio: "His final season at Kentucky ended with a stunning first-round upset loss to Oakland, 80-76. Calipari left for Arkansas shortly after.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "University of Arkansas",
        league: "SEC",
        location: "Fayetteville, AR",
        statusNote: "Left Kentucky for Arkansas in April 2024 after 15 seasons (410-127 record, 1 title, 4 Final Fours). His final game was a stunning loss to Oakland.",
        sourceUrl: "https://en.wikipedia.org/wiki/John_Calipari",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2024", statsNote: "23-10 • Lost to Oakland 80-76 in R1 • Calipari's last game as UK coach" },
      careerEvents: [
        { year: 2024, title: "Lost to Oakland in NCAA R1; left Kentucky for Arkansas", eventType: "CAREER" },
      ],
    },
  ],
};
