import type { TeamSeed } from "./types";

export const kentuckyBasketball2018: TeamSeed = {
  slug: "kentucky-basketball-2018",
  name: "Kentucky Wildcats",
  season: "2017-2018",
  sport: "Men's Basketball",
  school: "University of Kentucky",
  conference: "SEC",
  accomplishment: "SEC Tournament Champions, Sweet Sixteen (26-11)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png",
  mascotName: "Wildcat",
  people: [
    {
      slug: "shai-gilgeous-alexander",
      firstName: "Shai",
      lastName: "Gilgeous-Alexander",
      birthYear: 1998,
      hometown: "Hamilton, ON, Canada",
      highSchool: "Hamilton Heights Christian Academy, Chattanooga, TN",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628983.png",
      bio: "A Canadian freshman guard who went from unranked recruit to lottery pick in one season. SGA averaged 14.4 PPG and 5.1 APG, leading Kentucky to the Sweet Sixteen.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Oklahoma City Thunder",
        league: "NBA",
        location: "Oklahoma City, OK",
        statusNote: "Drafted #11 by the Charlotte Hornets (traded to Clippers) in 2018, then traded to OKC in 2019. Won the 2024-25 NBA MVP award and is the front-runner for a repeat in 2025-26, averaging 31.7 PPG, 6.6 APG on 55% shooting. Tied Wilt Chamberlain's record of 126 consecutive games with 20+ points. Arguably the best player in the NBA.",
        sourceUrl: "https://en.wikipedia.org/wiki/Shai_Gilgeous-Alexander",
      },
      membership: { role: "PLAYER", jerseyNumber: 22, position: "Guard", yearsAtSchool: "2017-2018", statsNote: "Freshman • 14.4 PPG, 5.1 APG • #11 overall pick • Now NBA MVP", gamesPlayed: 37, pointsPerGame: 14.4, reboundsPerGame: 4.1, assistsPerGame: 5.1 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Hamilton Heights Christian Academy", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 26.6, reboundsPerGame: 4.1, assistsPerGame: 8.6 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2017-18", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 37, minutesPerGame: 32.6, pointsPerGame: 14.4, reboundsPerGame: 4.1, assistsPerGame: 5.1, stealsPerGame: 1.2, fieldGoalPct: 0.485, threePointPct: 0.404, freeThrowPct: 0.817 },
        { level: "PROFESSIONAL", teamName: "LA Clippers", season: "2018-19", yearLabel: "2018-19", sortOrder: 301, gamesPlayed: 82, minutesPerGame: 26.5, pointsPerGame: 10.8, reboundsPerGame: 2.8, assistsPerGame: 3.3, stealsPerGame: 1.2, fieldGoalPct: 0.477, threePointPct: 0.367, freeThrowPct: 0.800 },
        { level: "PROFESSIONAL", teamName: "Oklahoma City Thunder", season: "2019-20", yearLabel: "2019-20", sortOrder: 302, gamesPlayed: 70, minutesPerGame: 34.7, pointsPerGame: 19.0, reboundsPerGame: 6.0, assistsPerGame: 3.3, stealsPerGame: 1.1, fieldGoalPct: 0.472, threePointPct: 0.347, freeThrowPct: 0.807 },
        { level: "PROFESSIONAL", teamName: "Oklahoma City Thunder", season: "2020-21", yearLabel: "2020-21", sortOrder: 303, gamesPlayed: 35, minutesPerGame: 33.7, pointsPerGame: 23.7, reboundsPerGame: 4.7, assistsPerGame: 5.9, stealsPerGame: 0.8, fieldGoalPct: 0.508, threePointPct: 0.341, freeThrowPct: 0.871 },
        { level: "PROFESSIONAL", teamName: "Oklahoma City Thunder", season: "2021-22", yearLabel: "2021-22", sortOrder: 304, gamesPlayed: 56, minutesPerGame: 35.3, pointsPerGame: 24.5, reboundsPerGame: 5.0, assistsPerGame: 5.9, stealsPerGame: 1.3, fieldGoalPct: 0.453, threePointPct: 0.300, freeThrowPct: 0.810 },
        { level: "PROFESSIONAL", teamName: "Oklahoma City Thunder", season: "2022-23", yearLabel: "2022-23", sortOrder: 305, gamesPlayed: 68, minutesPerGame: 35.5, pointsPerGame: 31.4, reboundsPerGame: 4.8, assistsPerGame: 5.5, stealsPerGame: 1.6, fieldGoalPct: 0.510, threePointPct: 0.345, freeThrowPct: 0.905 },
        { level: "PROFESSIONAL", teamName: "Oklahoma City Thunder", season: "2023-24", yearLabel: "2023-24", sortOrder: 306, gamesPlayed: 75, minutesPerGame: 34.0, pointsPerGame: 30.1, reboundsPerGame: 5.5, assistsPerGame: 6.2, stealsPerGame: 2.0, fieldGoalPct: 0.535, threePointPct: 0.353, freeThrowPct: 0.874 },
        { level: "PROFESSIONAL", teamName: "Oklahoma City Thunder", season: "2024-25", yearLabel: "2024-25 (MVP, Finals MVP)", sortOrder: 307, gamesPlayed: 76, minutesPerGame: 34.2, pointsPerGame: 32.7, reboundsPerGame: 5.0, assistsPerGame: 6.4, stealsPerGame: 1.7, blocksPerGame: 1.0, fieldGoalPct: 0.519, threePointPct: 0.375, freeThrowPct: 0.898 },
        { level: "PROFESSIONAL", teamName: "Oklahoma City Thunder", season: "2025-26", yearLabel: "2025-26", sortOrder: 308, gamesPlayed: 64, pointsPerGame: 31.6, reboundsPerGame: 4.4, assistsPerGame: 6.5, fieldGoalPct: 0.550 },
      ],
      careerEvents: [
        { year: 2018, title: "Selected #11 overall by Charlotte (traded to Clippers)", eventType: "DRAFT" },
        { year: 2019, title: "Traded to Oklahoma City Thunder", eventType: "TRADE" },
        { year: 2025, title: "Won NBA Most Valuable Player award", eventType: "AWARD" },
      ],
    },
    {
      slug: "kevin-knox",
      firstName: "Kevin",
      lastName: "Knox II",
      birthYear: 1999,
      hometown: "Tampa, FL",
      highSchool: "Tampa Catholic High School, Tampa, FL",
      isFeatured: false,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628995.png",
      bio: "A talented freshman forward who declared for the NBA Draft after one season and was selected #9 overall.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Windy City Bulls (G League)",
        league: "NBA G League",
        statusNote: "Drafted #9 by the New York Knicks in 2018. Played for the Knicks, Hawks, Pistons, Blazers, and Warriors. Now in the G League with the Windy City Bulls (16 PPG), working toward another NBA opportunity.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kevin_Knox_II",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Forward", yearsAtSchool: "2017-2018", statsNote: "Freshman • 15.6 PPG • #9 overall pick", gamesPlayed: 37, pointsPerGame: 15.6, reboundsPerGame: 5.4, assistsPerGame: 1.3 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Tampa Catholic High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 28.4, reboundsPerGame: 10.0, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2017-2018", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 15.6, reboundsPerGame: 5.4, assistsPerGame: 1.3 },
      
        { level: "PROFESSIONAL", teamName: "New York Knicks", season: "2018-19", yearLabel: "2018-19 (Rookie, #9 pick)", sortOrder: 301, gamesPlayed: 75, pointsPerGame: 12.8, reboundsPerGame: 4.5, assistsPerGame: 1.1 },
        { level: "PROFESSIONAL", teamName: "New York Knicks", season: "2019-20", yearLabel: "2019-20", sortOrder: 302, gamesPlayed: 65, pointsPerGame: 6.4, reboundsPerGame: 2.8, assistsPerGame: 0.5 },
        { level: "PROFESSIONAL", teamName: "New York Knicks", season: "2020-21", yearLabel: "2020-21", sortOrder: 303, gamesPlayed: 46, pointsPerGame: 3.9, reboundsPerGame: 1.9, assistsPerGame: 0.4 },
        { level: "PROFESSIONAL", teamName: "Atlanta Hawks", season: "2021-22", yearLabel: "2021-22", sortOrder: 304, gamesPlayed: 17, pointsPerGame: 3.3, reboundsPerGame: 1.5, assistsPerGame: 0.3 },
        { level: "PROFESSIONAL", teamName: "Windy City Bulls (G League)", season: "2025-26", yearLabel: "2025-26 (G League)", sortOrder: 308, gamesPlayed: 30, pointsPerGame: 16.0, reboundsPerGame: 7.0, assistsPerGame: 2.0 },
      ],
      careerEvents: [
        { year: 2018, title: "Selected #9 overall by the New York Knicks", eventType: "DRAFT" },
      ],
    },
    {
      slug: "pj-washington",
      firstName: "PJ",
      lastName: "Washington",
      birthYear: 1998,
      hometown: "Dallas, TX",
      highSchool: "Findlay Prep, Henderson, NV",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1629023.png",
      bio: "A freshman forward who would return for his sophomore year and become a lottery pick.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Dallas Mavericks",
        league: "NBA",
        location: "Dallas, TX",
        statusNote: "Returned for sophomore year. Drafted #12 overall in 2019 by Charlotte. Now with the Dallas Mavericks on a 4-year, $89M extension.",
        sourceUrl: "https://en.wikipedia.org/wiki/P._J._Washington",
      },
      membership: { role: "PLAYER", jerseyNumber: 25, position: "Forward", yearsAtSchool: "2017-2019", statsNote: "Freshman • 10.8 PPG, 5.7 RPG • Returned for sophomore year" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Findlay Prep", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 21.2, reboundsPerGame: 10.4, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2017-2018", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 10.8, reboundsPerGame: 5.7, assistsPerGame: 1.0 },
      ],
      careerEvents: [
        { year: 2019, title: "Selected #12 overall by the Charlotte Hornets", eventType: "DRAFT" },
      ],
    },
    {
      slug: "hamidou-diallo",
      firstName: "Hamidou",
      lastName: "Diallo",
      birthYear: 1998,
      hometown: "Queens, NY",
      highSchool: "Putnam Science Academy, Putnam, CT",
      isFeatured: false,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1628977.png",
      bio: "After redshirting in 2016-17, the explosive guard declared for the NBA Draft and won the 2019 Slam Dunk Contest.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Shanxi Loongs",
        league: "CBA (China)",
        statusNote: "Redshirted his freshman year (2016-17), then averaged 10.0 PPG as a redshirt freshman before declaring for the 2018 Draft. Selected #45 overall by the Nets and traded to OKC, he electrified the basketball world by winning the 2019 NBA Slam Dunk Contest with a legendary dunk over Shaquille O'Neal. Played five NBA seasons with the Thunder, Pistons, and Wizards. Now playing for the Shanxi Loongs in China's CBA after a stint with Baskonia in Spain's Liga ACB.",
        sourceUrl: "https://en.wikipedia.org/wiki/Hamidou_Diallo",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Guard", yearsAtSchool: "2016-2018", statsNote: "Redshirt Freshman • 10.0 PPG • 2019 Dunk Contest winner" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Putnam Science Academy", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 20.0, reboundsPerGame: 3.6, assistsPerGame: 3.6 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2017-2018", yearLabel: "Redshirt Freshman", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 10.0, reboundsPerGame: 3.6, assistsPerGame: 1.2 },
      
        { level: "PROFESSIONAL", teamName: "Oklahoma City Thunder", season: "2018-19", yearLabel: "2018-19 (Rookie)", sortOrder: 301, gamesPlayed: 51, minutesPerGame: 17.1, pointsPerGame: 5.9, reboundsPerGame: 2.2, assistsPerGame: 0.5, fieldGoalPct: 0.474 },
        { level: "PROFESSIONAL", teamName: "Oklahoma City Thunder", season: "2019-20", yearLabel: "2019-20", sortOrder: 302, gamesPlayed: 56, minutesPerGame: 24.0, pointsPerGame: 6.9, reboundsPerGame: 3.5, assistsPerGame: 0.6, fieldGoalPct: 0.429 },
        { level: "PROFESSIONAL", teamName: "Detroit Pistons", season: "2021-22", yearLabel: "2021-22", sortOrder: 304, gamesPlayed: 58, minutesPerGame: 26.1, pointsPerGame: 11.0, reboundsPerGame: 4.8, assistsPerGame: 1.5, fieldGoalPct: 0.436 },
      ],
      careerEvents: [
        { year: 2018, title: "Selected #45 overall by the Brooklyn Nets", eventType: "DRAFT" },
        { year: 2019, title: "Won NBA Slam Dunk Contest", eventType: "AWARD" },
      ],
    },
    {
      slug: "nick-richards",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1630208.png",
      firstName: "Nick",
      lastName: "Richards",
      birthYear: 1997,
      hometown: "Kingston, Jamaica",
      highSchool: "The Patrick School, Elizabeth, NJ",
      isFeatured: false,
      bio: "A Jamaican freshman center who would stay three years at Kentucky and develop into a second-round NBA pick.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "Chicago Bulls",
        league: "NBA",
        location: "Chicago, IL",
        statusNote: "A Jamaican-born center who stayed three years at Kentucky, developing from a raw freshman into the SEC's top shot-blocker. Drafted #42 overall by the Charlotte Hornets in 2020, Richards became a reliable rotation center in his fourth NBA season. He's been traded multiple times in 2025-26 — from Charlotte to Phoenix (January 2025), then to Milwaukee, then to Chicago (February 2026). On a 3-year, $15M contract.",
        sourceUrl: "https://www.basketball-reference.com/players/r/richani01.html",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Center", yearsAtSchool: "2017-2020", statsNote: "Freshman • 5.5 PPG, 3.3 RPG" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "The Patrick School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 8.8, reboundsPerGame: 6.0, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2017-2018", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 2.5, reboundsPerGame: 2.3, assistsPerGame: 0.2 },
      ],
      careerEvents: [{ year: 2020, title: "Selected #42 overall by Charlotte Hornets", eventType: "DRAFT" }],
    },
    {
      slug: "jarred-vanderbilt",
      firstName: "Jarred",
      lastName: "Vanderbilt",
      birthYear: 1999,
      hometown: "Houston, TX",
      highSchool: "Victory Prep Academy, Houston, TX",
      isFeatured: false,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1629020.png",
      bio: "A freshman forward who declared for the NBA after one injury-plagued season and became a valued NBA role player.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Los Angeles Lakers",
        league: "NBA",
        location: "Los Angeles, CA",
        statusNote: "Drafted #41 in 2018. Has played for the Nuggets, Timberwolves, Jazz, and Lakers. On a 4-year, $48M extension with the Lakers, valued for his defense and energy.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jarred_Vanderbilt",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Forward", yearsAtSchool: "2017-2018", statsNote: "Freshman • Limited by injury • #41 overall pick" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Victory Prep Academy", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 13.9, reboundsPerGame: 12.2, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2017-2018", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 14, pointsPerGame: 5.9, reboundsPerGame: 7.1, assistsPerGame: 1.4 },
      
        { level: "PROFESSIONAL", teamName: "Denver Nuggets", season: "2019-20", yearLabel: "2019-20", sortOrder: 301, gamesPlayed: 14, pointsPerGame: 2.4, reboundsPerGame: 3.1, assistsPerGame: 0.5 },
        { level: "PROFESSIONAL", teamName: "Minnesota Timberwolves", season: "2021-22", yearLabel: "2021-22", sortOrder: 303, gamesPlayed: 74, pointsPerGame: 6.9, reboundsPerGame: 8.4, assistsPerGame: 1.3 },
        { level: "PROFESSIONAL", teamName: "Utah / LA Lakers", season: "2022-23", yearLabel: "2022-23 (traded)", sortOrder: 304, gamesPlayed: 64, pointsPerGame: 8.8, reboundsPerGame: 7.2, assistsPerGame: 1.5 },
        { level: "PROFESSIONAL", teamName: "Los Angeles Lakers", season: "2024-25", yearLabel: "2024-25 ($48M deal)", sortOrder: 306, gamesPlayed: 58, pointsPerGame: 5.5, reboundsPerGame: 5.0, assistsPerGame: 1.5 },
      ],
      careerEvents: [
        { year: 2018, title: "Selected #41 overall by Orlando (traded to Denver)", eventType: "DRAFT" },
        { year: 2023, title: "Signed 4-year, $48M extension with Lakers", eventType: "SIGNING" },
      ],
    },
    {
      slug: "quade-green",
      firstName: "Quade",
      lastName: "Green",
      birthYear: 1999,
      hometown: "Philadelphia, PA",
      highSchool: "Neumann-Goretti High School, Philadelphia, PA",
      isFeatured: false,
      bio: "A freshman point guard who transferred to Washington after his first year due to academic eligibility issues.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        location: "Free Agent",
        statusNote: "Transferred to Washington after freshman year. Went undrafted in 2021. Has been a journeyman across the G League, Mexico, Venezuela, Great Britain, Kosovo, and Morocco.",
        sourceUrl: "https://en.wikipedia.org/wiki/Quade_Green",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Point Guard", yearsAtSchool: "2017-2018", statsNote: "Freshman • 9.3 PPG • Transferred to Washington" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Neumann-Goretti High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 19.0, reboundsPerGame: 2.0, assistsPerGame: 5.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2017-2018", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 9.3, reboundsPerGame: 2.0, assistsPerGame: 2.7 },
      ],
      careerEvents: [{ year: 2018, title: "Transferred to University of Washington", eventType: "OTHER" }],
    },
    {
      slug: "wenyen-gabriel",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1629117.png",
      firstName: "Wenyen",
      lastName: "Gabriel",
      birthYear: 1997,
      hometown: "Manchester, NH",
      highSchool: "Wilbraham & Monson Academy, Wilbraham, MA",
      isFeatured: false,
      bio: "A sophomore forward who showed flashes with his 3-point shooting and defensive versatility.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "FC Bayern Munich",
        league: "German BBL / EuroLeague",
        location: "Munich, Germany",
        statusNote: "South Sudanese-American forward who went undrafted in 2018 but persisted through the G League to earn NBA minutes with seven different teams — the Kings, Trail Blazers, Pelicans, Nets, Clippers, Lakers, and Grizzlies. Known for his energy and defensive versatility, he moved to Europe in late 2024, playing for Panathinaikos (Greece/EuroLeague) before signing with FC Bayern Munich in Germany for the 2025-26 BBL and EuroLeague seasons.",
        sourceUrl: "https://en.wikipedia.org/wiki/Wenyen_Gabriel",
      },
      membership: { role: "PLAYER", jerseyNumber: 32, position: "Forward", yearsAtSchool: "2016-2018", statsNote: "Sophomore • Versatile wing" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Wilbraham & Monson Academy", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 9.9, reboundsPerGame: 6.2, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2016-2017", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 3.3, reboundsPerGame: 2.5, assistsPerGame: 0.3 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2017-2018", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 37, pointsPerGame: 7.4, reboundsPerGame: 5.0, assistsPerGame: 0.5 },
      
        { level: "PROFESSIONAL", teamName: "Los Angeles Lakers", season: "2021-22", yearLabel: "2021-22", sortOrder: 301, gamesPlayed: 25, minutesPerGame: 12.3, pointsPerGame: 3.9, reboundsPerGame: 3.2, blocksPerGame: 0.6, fieldGoalPct: 0.508 },
        { level: "PROFESSIONAL", teamName: "Los Angeles Lakers", season: "2022-23", yearLabel: "2022-23", sortOrder: 302, gamesPlayed: 44, minutesPerGame: 8.6, pointsPerGame: 2.5, reboundsPerGame: 2.4, fieldGoalPct: 0.524 },
      ],
      careerEvents: [{ year: 2018, title: "Went undrafted; began pro career", eventType: "CAREER" }],
    },
    {
      slug: "jemarl-baker",
      firstName: "Jemarl",
      lastName: "Baker Jr.",
      birthYear: 1998,
      hometown: "Menifee, CA",
      highSchool: "Eleanor Roosevelt High School, Eastvale, CA",
      isFeatured: false,
      bio: "Missed his entire freshman season with a knee injury.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "Eisbaren Bremerhaven",
        league: "German ProA",
        location: "Germany",
        statusNote: "After missing his entire freshman year at Kentucky with a torn meniscus (while teammates SGA and Kevin Knox headed to the NBA), Baker transferred through four colleges — Arizona, Fresno State, and New Mexico. Graduated in 2024 and began his professional career in Denmark's top league with the Svendborg Rabbits, then signed with Eisbaren Bremerhaven in Germany's ProA where he's averaging 14.8 PPG and was named 'Man of the Match' after hitting seven three-pointers against VfL Bochum.",
        sourceUrl: "https://basketball.eurobasket.com/player/Jemarl-Baker-Jr/421563",
      },
      membership: { role: "PLAYER", jerseyNumber: 13, position: "Guard", yearsAtSchool: "2017-2019", statsNote: "Freshman • Missed season with knee injury" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Eleanor Roosevelt High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 12.5, reboundsPerGame: 3.0, assistsPerGame: 4.0 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2017-2018", yearLabel: "Freshman (missed season — knee injury)", sortOrder: 201, gamesPlayed: 0 },
      ],
      careerEvents: [{ year: 2019, title: "Transferred to University of Arizona", eventType: "OTHER" }],
    },
    {
      slug: "sacha-killeya-jones",
      firstName: "Sacha",
      lastName: "Killeya-Jones",
      birthYear: 1998,
      hometown: "Chapel Hill, NC",
      highSchool: "Virginia Episcopal School, Lynchburg, VA",
      isFeatured: false,
      bio: "A five-star power forward out of Virginia who spent two seasons at Kentucky behind a loaded frontcourt before transferring to NC State. Since leaving college, the British-American big man has built a productive international pro career, leading the Israeli league in scoring and most recently playing in China.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "Shandong Hi-Speed Kirin",
        league: "CBA (China)",
        location: "Jinan, China",
        statusNote: "Averaged 3.3 points and 2.9 rebounds as a sophomore in 2017-18 before transferring to NC State, where he departed in February 2019 to pursue a pro career. Led the Israeli Basketball Premier League in scoring (18.4 PPG) with Hapoel Gilboa Galil in 2021-22, briefly signed with the Oklahoma City Thunder in 2022, and has since played across Europe and Asia. As of 2026 he is suiting up for Shandong Hi-Speed Kirin of the Chinese Basketball Association.",
        sourceUrl: "https://en.wikipedia.org/wiki/Sacha_Killeya-Jones",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 1,
        position: "Power Forward",
        yearsAtSchool: "2016-2018",
        statsNote: "Sophomore • Five-star recruit • Transferred to NC State",
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Virginia Episcopal School", season: "2015-16", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 18.0, reboundsPerGame: 8.0 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2016-17", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 20, minutesPerGame: 4.6, pointsPerGame: 0.9, reboundsPerGame: 1.1 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2017-18", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 36, minutesPerGame: 11.9, pointsPerGame: 3.3, reboundsPerGame: 2.9 },
      ],
      careerEvents: [
        { year: 2018, title: "Transferred from Kentucky to NC State", eventType: "OTHER" },
        { year: 2022, title: "Led Israeli Premier League in scoring (18.4 PPG)", eventType: "AWARD" },
      ],
    },
    {
      slug: "tai-wynyard-2018",
      firstName: "Tai",
      lastName: "Wynyard",
      birthYear: 1997,
      hometown: "Auckland, New Zealand",
      highSchool: "Scots College, Wellington, New Zealand",
      isFeatured: false,
      bio: "New Zealand's Tall Blacks senior-national-team big man in his third season at Kentucky. Wynyard was suspended from the program in February 2018 for a team rules violation and returned home to New Zealand in April to restart his career abroad.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "New Zealand Breakers",
        league: "NBL (Australia)",
        location: "Auckland, New Zealand",
        statusNote: "After logging just 97 minutes across his Kentucky career, Wynyard returned home to New Zealand in 2018 and began playing professionally in the NBL and overseas leagues. He spent time with the Shanghai Sharks in the Chinese Basketball Association and in December 2024 signed with the New Zealand Breakers as an injury replacement, appearing in four NBL games that season.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tai_Wynyard",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 14,
        position: "Center",
        yearsAtSchool: "2015-2018",
        statsNote: "Sophomore • Suspended and left program in 2018",
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Scots College", season: "2014-15", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 16.0, reboundsPerGame: 11.0 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2017-18", yearLabel: "Sophomore", sortOrder: 201, gamesPlayed: 14, minutesPerGame: 2.5, pointsPerGame: 0.3 },
      ],
      careerEvents: [
        { year: 2018, title: "Suspended; left Kentucky and returned to New Zealand", eventType: "OTHER" },
        { year: 2024, title: "Signed with New Zealand Breakers (NBL)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "brad-calipari-2018",
      firstName: "Brad",
      lastName: "Calipari",
      birthYear: 1997,
      hometown: "Lexington, KY",
      highSchool: "MacDuffie School, Granby, MA",
      isFeatured: false,
      bio: "The head coach's son appearing in his second season at Kentucky as a reserve guard on the 2017-18 Sweet Sixteen team. Brad ultimately transferred to Detroit Mercy and has built a coaching career alongside his father.",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Coach / Director of On-Court Player Development",
        currentEmployer: "Arkansas Razorbacks",
        league: "NCAA",
        location: "Fayetteville, AR",
        statusNote: "Spent three seasons as a Kentucky reserve before transferring to Detroit Mercy for his final two collegiate years, where he became a rotation player averaging double-digit points. He moved into coaching with stops at Long Island University (2022-23) and Vanderbilt (2023-24) before joining his father's staff at Arkansas in 2024 as assistant coach and director of on-court player development.",
        sourceUrl: "https://arkansasrazorbacks.com/coache/brad-calipari/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 12,
        position: "Guard",
        yearsAtSchool: "2016-2019",
        statsNote: "Sophomore reserve • Son of head coach John Calipari",
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "MacDuffie School", season: "2015-16", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 18.0 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2017-18", yearLabel: "Sophomore", sortOrder: 201, gamesPlayed: 14, minutesPerGame: 2.9, pointsPerGame: 0.4 },
      ],
      careerEvents: [
        { year: 2019, title: "Transferred to Detroit Mercy", eventType: "OTHER" },
        { year: 2024, title: "Named assistant coach at Arkansas", eventType: "HIRED" },
      ],
    },
    {
      slug: "dillon-pulliam-2018",
      firstName: "Dillon",
      lastName: "Pulliam",
      birthYear: 1995,
      hometown: "Cynthiana, KY",
      highSchool: "Harrison County High School, Cynthiana, KY",
      isFeatured: false,
      bio: "The walk-on computer engineering major who returned for a third season at Kentucky. Dubbed the oldest player on the nation's youngest team, Pulliam became a fan favorite for his academic achievements and consistent practice effort.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Software Engineer",
        currentEmployer: "Toyota Connected North America",
        location: "Plano, TX",
        statusNote: "After his final season at Kentucky in 2017-18, Pulliam transferred to Carnegie Mellon University to finish his computer engineering degree and keep playing at the Division III level. As of 2026 he works as a software engineer at Toyota Connected North America, focusing on autonomous vehicle and machine learning research.",
        sourceUrl: "https://www.linkedin.com/in/dillonpulliam/",
        linkedInUrl: "https://www.linkedin.com/in/dillonpulliam/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 30,
        position: "Guard",
        yearsAtSchool: "2015-2018",
        statsNote: "Walk-on senior • Computer engineering major",
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Harrison County High School", season: "2012-13", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 18.0 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2017-18", yearLabel: "Senior (walk-on)", sortOrder: 201, gamesPlayed: 10, minutesPerGame: 1.5, pointsPerGame: 0.3 },
      ],
      careerEvents: [
        { year: 2018, title: "Graduated; transferred to Carnegie Mellon for grad school", eventType: "OTHER" },
      ],
    },
    {
      slug: "jonny-david-2018",
      firstName: "Jonny",
      lastName: "David",
      birthYear: 1996,
      hometown: "Pittsburgh, PA",
      highSchool: "Mount Lebanon High School, Pittsburgh, PA",
      isFeatured: false,
      bio: "A walk-on junior guard whose father Joe was a former Calipari player at Pitt. David was a trusted practice player for Kentucky's loaded 2017-18 recruiting class and a locker-room glue guy throughout his Kentucky tenure.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Kinesiology Graduate",
        statusNote: "Continued as a Kentucky walk-on through 2018-19, making his first career start on Senior Day against Florida and playing a career-high 14 minutes that night. Graduated with a kinesiology degree, was named to the 2019 SEC Community Service Team, and produced the \"Jonny David All-Access\" behind-the-scenes video series during his senior year.",
        sourceUrl: "https://www.sports-reference.com/cbb/players/jonny-david-1.html",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 10,
        position: "Guard",
        yearsAtSchool: "2015-2019",
        statsNote: "Walk-on junior guard",
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Mount Lebanon High School", season: "2014-15", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 18.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2017-18", yearLabel: "Junior (walk-on)", sortOrder: 201, gamesPlayed: 7, minutesPerGame: 1.1, pointsPerGame: 0.1 },
      ],
      careerEvents: [
        { year: 2019, title: "Named to SEC Community Service Team; graduated", eventType: "AWARD" },
      ],
    },
    {
      slug: "john-calipari",
      firstName: "John",
      lastName: "Calipari",
      birthYear: 1959,
      hometown: "Moon Township, PA",
      highSchool: "Moon Area High School, Moon Township, PA",
      isFeatured: true,
      bio: "Led a roster featuring the future NBA MVP (Shai Gilgeous-Alexander) to the Sweet Sixteen.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "University of Arkansas",
        league: "SEC",
        location: "Fayetteville, AR",
        statusNote: "After 15 seasons at Kentucky (2009-2024) compiling a 410-127 record, one national championship (2012), four Final Fours, and more NBA Draft picks than any coach in history (42 first-round picks), Calipari left for Arkansas in April 2024 on a 5-year, $35M deal. In his first full season at Arkansas (2025-26), he won the SEC Tournament Championship — becoming the first men's coach to win SEC Tournament titles at multiple schools. He ranks 5th on the all-time NCAA Division I wins list with 900+ career victories.",
        sourceUrl: "https://en.wikipedia.org/wiki/John_Calipari",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2024", statsNote: "26-11 • SEC Tournament Champions • Sweet Sixteen • Future NBA MVP on roster" },
      careerEvents: [{ year: 2024, title: "Left Kentucky for Arkansas", eventType: "CAREER" }],
    },
  ],
};
