import type { TeamSeed } from "./types";

export const kentuckyBasketball2023: TeamSeed = {
  slug: "kentucky-basketball-2023",
  name: "Kentucky Wildcats",
  season: "2022-2023",
  sport: "Men's Basketball",
  school: "University of Kentucky",
  conference: "SEC",
  accomplishment: "NCAA Tournament Second Round (22-12)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png",
  mascotName: "Wildcat",
  people: [
    {
      slug: "cason-wallace",
      firstName: "Cason",
      lastName: "Wallace",
      birthYear: 2004,
      hometown: "Richardson, TX",
      highSchool: "Richardson High School, Richardson, TX",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1641717.png",
      bio: "A dynamic freshman guard who was one of the top defenders in the SEC and declared for the NBA Draft after one season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Oklahoma City Thunder",
        league: "NBA",
        location: "Oklahoma City, OK",
        statusNote: "Drafted #10 overall by the Oklahoma City Thunder in 2023. Won an NBA Championship with the Thunder in 2025. Averaging 8.6 PPG in 2025-26.",
        sourceUrl: "https://www.nba.com/player/1641717/cason-wallace",
      },
      membership: { role: "PLAYER", jerseyNumber: 22, position: "Guard", yearsAtSchool: "2022-2023", statsNote: "Freshman • #10 overall pick • 2025 NBA Champion" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2022-2023", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 35, pointsPerGame: 11.7, reboundsPerGame: 3.7, assistsPerGame: 3.6 },
      ],
      careerEvents: [
        { year: 2023, title: "Selected #10 overall by the Oklahoma City Thunder", eventType: "DRAFT" },
        { year: 2025, title: "Won NBA Championship with the Thunder", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "oscar-tshiebwe",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1631290.png",
      firstName: "Oscar",
      lastName: "Tshiebwe",
      birthYear: 1999,
      hometown: "Lubumbashi, DR Congo",
      highSchool: "Kennedy Catholic High School, Hermitage, PA",
      isFeatured: true,
      bio: "Returned for his senior year and won SEC Player of the Year again despite battling injuries.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward / Center",
        currentEmployer: "Utah Jazz (two-way)",
        league: "NBA / G League",
        statusNote: "Two-time National/SEC POY. Went undrafted in 2023 but slowly working his way into the NBA with the Utah Jazz.",
        sourceUrl: "https://en.wikipedia.org/wiki/Oscar_Tshiebwe",
      },
      membership: { role: "PLAYER", jerseyNumber: 34, position: "Forward / Center", yearsAtSchool: "2020-2023", statsNote: "Senior • SEC POY again • 16.5 PPG, 13.7 RPG" },
      careerEvents: [{ year: 2023, title: "Won SEC Player of the Year (2nd time)", eventType: "AWARD" }],
    },
    {
      slug: "chris-livingston",
      firstName: "Chris",
      lastName: "Livingston",
      birthYear: 2004,
      hometown: "Akron, OH",
      highSchool: "Oak Hill Academy, Mouth of Wilson, VA",
      isFeatured: false,
      bio: "A five-star freshman forward from LeBron James' hometown who declared for the NBA after one season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Capital City Go-Go (G League)",
        league: "NBA G League",
        statusNote: "Drafted #58 by the Milwaukee Bucks in 2023. Waived by the Bucks, briefly with the Cavaliers on a two-way, then waived in January 2026. Now in the G League.",
        sourceUrl: "https://en.wikipedia.org/wiki/Chris_Livingston",
      },
      membership: { role: "PLAYER", jerseyNumber: 33, position: "Forward", yearsAtSchool: "2022-2023", statsNote: "Freshman • Five-star from Akron • #58 overall pick" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2022-2023", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 32, pointsPerGame: 6.4, reboundsPerGame: 3.0, assistsPerGame: 0.8 },
      ],
      careerEvents: [
        { year: 2023, title: "Selected #58 overall by the Milwaukee Bucks", eventType: "DRAFT" },
      ],
    },
    {
      slug: "antonio-reeves",
      firstName: "Antonio",
      lastName: "Reeves",
      birthYear: 2001,
      hometown: "Chicago, IL",
      highSchool: "Simeon Career Academy, Chicago, IL",
      isFeatured: false,
      bio: "A sharpshooting transfer from Illinois State who won SEC Co-Sixth Man of the Year and returned for a second season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Charlotte Hornets (two-way)",
        league: "NBA / G League",
        statusNote: "Won SEC Co-Sixth Man of the Year in 2023, returned as team's leading scorer in 2024. Drafted #47 in 2024 by Orlando, traded to New Orleans, then signed a two-way with the Charlotte Hornets.",
        sourceUrl: "https://www.nba.com/player/1641810/antonio-reeves",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Guard", yearsAtSchool: "2022-2024", statsNote: "Senior • Transfer from Illinois State • SEC Co-6th Man of Year" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2022-2023", yearLabel: "Senior", sortOrder: 201, gamesPlayed: 34, pointsPerGame: 14.6, reboundsPerGame: 2.5, assistsPerGame: 1.3 },
      ],
      careerEvents: [
        { year: 2023, title: "Won SEC Co-Sixth Man of the Year", eventType: "AWARD" },
        { year: 2024, title: "Selected #47 overall by the Orlando Magic", eventType: "DRAFT" },
      ],
    },
    {
      slug: "adou-thiero",
      firstName: "Adou",
      lastName: "Thiero",
      birthYear: 2004,
      hometown: "Washington, D.C.",
      highSchool: "Transferred to Kentucky from Guinea via D.C.",
      isFeatured: false,
      bio: "A Guinean-American freshman guard/forward who would go on to follow Calipari to Arkansas and get drafted by the Lakers.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Los Angeles Lakers",
        league: "NBA",
        location: "Los Angeles, CA",
        statusNote: "After two years at Kentucky and one at Arkansas (where he led the team in scoring at 15.1 PPG), Thiero was drafted #36 overall in 2025 by the Nets (traded to Lakers). Rookie season in 2025-26.",
        sourceUrl: "https://www.nba.com/player/1642876/adou-thiero",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Guard / Forward", yearsAtSchool: "2022-2024", statsNote: "Freshman • From Guinea • Later followed Calipari to Arkansas" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2022-2023", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 4.5, reboundsPerGame: 2.8, assistsPerGame: 0.9 },
      ],
      careerEvents: [
        { year: 2024, title: "Transferred to Arkansas to follow Calipari", eventType: "OTHER" },
        { year: 2025, title: "Selected #36 overall by the Nets (traded to Lakers)", eventType: "DRAFT" },
      ],
    },
    {
      slug: "ugonna-onyenso",
      firstName: "Ugonna",
      lastName: "Onyenso",
      birthYear: 2003,
      hometown: "Nigeria",
      highSchool: "Prep school in the U.S.",
      isFeatured: false,
      bio: "A Nigerian freshman center with elite shot-blocking ability who would later set ACC Tournament records at Virginia.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Virginia",
        league: "ACC",
        statusNote: "After two years at Kentucky, transferred to Kansas State, then Virginia. Set the ACC Tournament record for blocks (21 in 3 games including 9 in the championship). Led all power conferences in blocks (3.0 per game) in 2025-26.",
        sourceUrl: "https://www.espn.com/mens-college-basketball/player/_/id/5037878/ugonna-onyenso",
      },
      membership: { role: "PLAYER", jerseyNumber: 33, position: "Center", yearsAtSchool: "2022-2024", statsNote: "Freshman • Elite shot-blocker from Nigeria" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2022-2023", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 28, pointsPerGame: 2.6, reboundsPerGame: 2.6, assistsPerGame: 0.2 },
      ],
      careerEvents: [
        { year: 2024, title: "Transferred to Kansas State", eventType: "OTHER" },
        { year: 2026, title: "Set ACC Tournament blocks record at Virginia (21 in 3 games)", eventType: "OTHER" },
      ],
    },
    {
      slug: "sahvir-wheeler",
      firstName: "Sahvir",
      lastName: "Wheeler",
      birthYear: 2001,
      hometown: "Houston, TX",
      highSchool: "Houston Christian High School, Houston, TX",
      isFeatured: false,
      bio: "Senior point guard completing his second year at Kentucky.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Wisconsin Herd (G League)",
        league: "NBA G League",
        statusNote: "At 5-10, one of the smallest point guards in the SEC, but led the conference in assists in both of his Kentucky seasons. After graduating, transferred to Washington for a fifth year, then went undrafted in the 2024 NBA Draft. Has bounced through the G League — Maine Celtics, Memphis Hustle, and currently the Wisconsin Herd (Bucks affiliate) — trying to earn an NBA roster spot.",
        sourceUrl: "https://en.wikipedia.org/wiki/Sahvir_Wheeler",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Point Guard", yearsAtSchool: "2021-2023", statsNote: "Senior • Led SEC in assists" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2022-2023", yearLabel: "Senior", sortOrder: 201, gamesPlayed: 35, pointsPerGame: 8.8, reboundsPerGame: 2.3, assistsPerGame: 5.8 },
      ],
      careerEvents: [{ year: 2023, title: "Transferred to University of Washington", eventType: "OTHER" }],
    },
    {
      slug: "jacob-toppin",
      firstName: "Jacob",
      lastName: "Toppin",
      birthYear: 2000,
      hometown: "Brooklyn, NY",
      highSchool: "Ossining High School, Ossining, NY",
      isFeatured: false,
      bio: "Senior forward completing his Kentucky career.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Atlanta Hawks (two-way)",
        league: "NBA",
        statusNote: "Obi Toppin's younger brother who transferred from Rhode Island and became a fan favorite at Kentucky for his high-flying dunks over four seasons. Went undrafted in 2023 but signed a two-way deal with the Atlanta Hawks. Signed a new deal in July 2025 but suffered a torn labrum in his right shoulder in a G League game on November 29, 2025 — requiring season-ending surgery. Before the injury: 18.0 PPG and 10.4 RPG in 5 G League games.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jacob_Toppin",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Forward", yearsAtSchool: "2020-2023", statsNote: "Senior • Fan favorite for dunking ability" },
            seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2022-2023", yearLabel: "Senior", sortOrder: 201, gamesPlayed: 35, pointsPerGame: 8.2, reboundsPerGame: 4.6, assistsPerGame: 1.0 },
      ],
      careerEvents: [{ year: 2023, title: "Went undrafted; signed two-way with Hawks", eventType: "SIGNING" }],
    },
    {
      slug: "john-calipari",
      firstName: "John",
      lastName: "Calipari",
      birthYear: 1959,
      hometown: "Moon Township, PA",
      highSchool: "Moon Area High School, Moon Township, PA",
      isFeatured: true,
      bio: "Led Kentucky to the NCAA Tournament second round.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "University of Arkansas",
        league: "SEC",
        location: "Fayetteville, AR",
        statusNote: "After 15 seasons at Kentucky (2009-2024) compiling a 410-127 record, one national championship (2012), four Final Fours, and more NBA Draft picks than any coach in history (42 first-round picks), Calipari left for Arkansas in April 2024 on a 5-year, $35M deal. In his first full season at Arkansas (2025-26), he won the SEC Tournament Championship — becoming the first men's coach to win SEC Tournament titles at multiple schools. He ranks 5th on the all-time NCAA Division I wins list with 900+ career victories.",
        sourceUrl: "https://en.wikipedia.org/wiki/John_Calipari",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2024", statsNote: "22-12 • NCAA Tournament R2" },
      careerEvents: [{ year: 2024, title: "Left Kentucky for Arkansas", eventType: "CAREER" }],
    },
  ],
};
