import type { TeamSeed } from "./types";

export const kentuckyBasketball2013: TeamSeed = {
  slug: "kentucky-basketball-2013",
  name: "Kentucky Wildcats",
  season: "2012-2013",
  sport: "Men's Basketball",
  school: "University of Kentucky",
  conference: "SEC",
  accomplishment: "NIT First Round (21-12) — missed NCAA Tournament",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png",
  mascotName: "Wildcat",
  people: [
    {
      slug: "nerlens-noel",
      firstName: "Nerlens",
      lastName: "Noel",
      birthYear: 1994,
      hometown: "Everett, MA",
      highSchool: "Tilton School, Tilton, NH",
      bio: "The presumptive #1 pick until tearing his ACL in February 2013. A dominant shot-blocker who still went #6 overall despite the injury.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NBA Player",
        location: "Philadelphia, PA",
        statusNote: "Played 9 NBA seasons with the 76ers, Mavericks, Thunder, and Knicks before retiring in 2022. Known for his elite shot-blocking ability despite injury-shortened college career.",
        sourceUrl: "https://en.wikipedia.org/wiki/Nerlens_Noel",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Center", yearsAtSchool: "2012-2013", statsNote: "#6 overall pick despite ACL injury", gamesPlayed: 24, pointsPerGame: 10.5, reboundsPerGame: 9.5, assistsPerGame: 1.7 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2012-13", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 24, pointsPerGame: 10.5, reboundsPerGame: 9.5, blocksPerGame: 4.4 },
        { level: "PROFESSIONAL", teamName: "Philadelphia 76ers", season: "2014-15", yearLabel: "2014-15", sortOrder: 301, gamesPlayed: 75, pointsPerGame: 9.9, reboundsPerGame: 8.1, blocksPerGame: 1.9 },
      ],
      careerEvents: [
        { year: 2013, title: "Suffered season-ending ACL tear in February", eventType: "CAREER" },
        { year: 2013, title: "Selected #6 overall by New Orleans Pelicans (traded to 76ers)", eventType: "DRAFT" },
        { year: 2022, title: "Retired from the NBA", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "archie-goodwin",
      firstName: "Archie",
      lastName: "Goodwin",
      birthYear: 1994,
      hometown: "Little Rock, AR",
      highSchool: "Sylvan Hills High School, Sherwood, AR",
      bio: "A freshman combo guard who led Kentucky in scoring at 14.1 PPG. Selected #29 by the Suns, brief NBA career.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Overseas",
        league: "International",
        location: "Europe",
        statusNote: "Played briefly in the NBA with the Suns, Pelicans, and Nets before moving overseas. Has played in Russia, Turkey, and the G League.",
        sourceUrl: "https://en.wikipedia.org/wiki/Archie_Goodwin_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 10, position: "Shooting Guard", yearsAtSchool: "2012-2013", statsNote: "Team leading scorer • #29 pick", gamesPlayed: 32, pointsPerGame: 14.1, reboundsPerGame: 4.6, assistsPerGame: 2.4 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2012-13", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 32, pointsPerGame: 14.1 },
      ],
      careerEvents: [
        { year: 2013, title: "Selected #29 overall by the Golden State Warriors (traded to Phoenix)", eventType: "DRAFT" },
      ],
    },
    {
      slug: "alex-poythress",
      firstName: "Alex",
      lastName: "Poythress",
      birthYear: 1993,
      hometown: "Clarksville, TN",
      highSchool: "Northeast High School, Clarksville, TN",
      bio: "A freshman forward with elite athleticism who averaged 11.2 PPG. Later played for the Pacers and Pistons.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Overseas",
        league: "International",
        location: "Europe",
        statusNote: "Graduated from Kentucky in 2016. Went undrafted but played briefly in the NBA. Has spent most of his career overseas.",
        sourceUrl: "https://en.wikipedia.org/wiki/Alex_Poythress",
      },
      membership: { role: "PLAYER", jerseyNumber: 22, position: "Power Forward", yearsAtSchool: "2012-2016", statsNote: "Freshman", gamesPlayed: 33, pointsPerGame: 11.2, reboundsPerGame: 6.0, assistsPerGame: 0.6 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2012-13", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 11.2 },
      ],
      careerEvents: [],
    },
    {
      slug: "willie-cauley-stein",
      firstName: "Willie",
      lastName: "Cauley-Stein",
      birthYear: 1993,
      hometown: "Spearville, KS",
      highSchool: "Olathe Northwest High School, Olathe, KS",
      bio: "A raw 7-footer in his freshman season who would later become the anchor of Kentucky's 38-1 team.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "Overseas / G League",
        league: "International",
        location: "Various",
        statusNote: "Selected #6 overall by the Kings in 2015 after his junior year. Played 8 NBA seasons before moving to overseas leagues.",
        sourceUrl: "https://en.wikipedia.org/wiki/Willie_Cauley-Stein",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Center", yearsAtSchool: "2012-2015", statsNote: "Freshman • Future #6 pick", gamesPlayed: 33, pointsPerGame: 8.3, reboundsPerGame: 6.2, assistsPerGame: 0.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2012-13", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 8.3, reboundsPerGame: 6.2 },
      ],
      careerEvents: [],
    },
    {
      slug: "ryan-harrow",
      firstName: "Ryan",
      lastName: "Harrow",
      birthYear: 1991,
      hometown: "Marietta, GA",
      highSchool: "Walton High School, Marietta, GA",
      bio: "An NC State transfer who took over point guard duties. Struggled with inconsistency but led the team in assists.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Point Guard",
        currentEmployer: "Overseas",
        league: "International",
        location: "Various",
        statusNote: "After Kentucky, Harrow transferred to Georgia State for his senior year. Has played professionally overseas in Israel, Turkey, and other international leagues.",
        sourceUrl: "https://www.basketball-reference.com/cbb/players/ryan-harrow-1.html",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Point Guard", yearsAtSchool: "2011-2013", statsNote: "NC State transfer", gamesPlayed: 32, pointsPerGame: 9.9, reboundsPerGame: 1.7, assistsPerGame: 2.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2012-13", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 32, pointsPerGame: 9.9, assistsPerGame: 2.8 },
      ],
      careerEvents: [],
    },
    {
      slug: "kyle-wiltjer",
      firstName: "Kyle",
      lastName: "Wiltjer",
      birthYear: 1992,
      hometown: "Portland, OR",
      highSchool: "Jesuit High School, Portland, OR",
      bio: "A sophomore forward who led Kentucky in three-point shooting. Transferred to Gonzaga after the season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Overseas",
        league: "International",
        location: "Europe / Asia",
        statusNote: "After transferring to Gonzaga, Wiltjer was WCC Player of the Year in 2016. Had brief NBA stints with Houston and Memphis before a long overseas career.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kyle_Wiltjer",
      },
      membership: { role: "PLAYER", jerseyNumber: 33, position: "Power Forward", yearsAtSchool: "2011-2013", statsNote: "Transferred to Gonzaga", gamesPlayed: 33, pointsPerGame: 10.2, reboundsPerGame: 4.2, assistsPerGame: 0.7 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2012-13", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 33, pointsPerGame: 10.2 },
      ],
      careerEvents: [
        { year: 2013, title: "Transferred to Gonzaga", eventType: "CAREER" },
      ],
    },
    {
      slug: "julius-mays",
      firstName: "Julius",
      lastName: "Mays",
      birthYear: 1990,
      hometown: "Marion, IN",
      highSchool: "Marion High School, Marion, IN",
      bio: "A graduate transfer from Wright State (via VCU) who provided veteran leadership. Hit 41% from three on the year.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Indiana",
        statusNote: "After his senior year at Kentucky, Mays went undrafted. Has worked professionally in the Indiana area since his basketball career ended.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/julius-mays/",
      },
      membership: { role: "PLAYER", jerseyNumber: 34, position: "Guard", yearsAtSchool: "2012-2013", statsNote: "Graduate transfer", gamesPlayed: 33, pointsPerGame: 8.9, reboundsPerGame: 2.5, assistsPerGame: 2.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2012-13", yearLabel: "Senior (transfer)", sortOrder: 204, gamesPlayed: 33, pointsPerGame: 8.9, threePointPct: 0.413 },
      ],
      careerEvents: [],
    },
    {
      slug: "jarrod-polson",
      firstName: "Jarrod",
      lastName: "Polson",
      birthYear: 1991,
      hometown: "Nicholasville, KY",
      highSchool: "West Jessamine High School, Nicholasville, KY",
      bio: "The junior walk-on turned scholarship guard from Nicholasville, KY provided depth off the bench.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Nicholasville, KY",
        statusNote: "A Kentucky native who worked his way from walk-on to scholarship player. After graduating, returned to Kentucky and works in the local area.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/jarrod-polson/",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Guard", yearsAtSchool: "2010-2014", statsNote: "Kentucky native walk-on", gamesPlayed: 31, pointsPerGame: 2.1 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2012-13", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 31, pointsPerGame: 2.1 },
      ],
      careerEvents: [],
    },
    {
      slug: "jon-hood",
      firstName: "Jon",
      lastName: "Hood",
      birthYear: 1990,
      hometown: "Madisonville, KY",
      highSchool: "Madisonville North Hopkins HS, Madisonville, KY",
      bio: "A junior Kentucky native guard returning from the 2012 championship roster.",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Coach",
        currentEmployer: "Kentucky High School",
        location: "Kentucky",
        statusNote: "After his Kentucky career, Hood has coached at the high school level in Kentucky.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jon_Hood",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Guard", yearsAtSchool: "2009-2014", statsNote: "Junior", gamesPlayed: 22, pointsPerGame: 0.9 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2012-13", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 22 },
      ],
      careerEvents: [],
    },
    {
      slug: "sam-malone",
      firstName: "Sam",
      lastName: "Malone",
      birthYear: 1991,
      hometown: "Louisiana",
      highSchool: "Ruston High School, Ruston, LA",
      bio: "A sophomore walk-on son of Karl Malone.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Louisiana",
        statusNote: "Son of NBA legend Karl Malone. After Kentucky, returned to Louisiana and worked in business.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/sam-malone/",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Guard", yearsAtSchool: "2011-2013", statsNote: "Son of Karl Malone • Walk-on", gamesPlayed: 14 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2012-13", yearLabel: "Sophomore (walk-on)", sortOrder: 202, gamesPlayed: 14 },
      ],
      careerEvents: [],
    },
    {
      slug: "brian-long",
      firstName: "Brian",
      lastName: "Long",
      birthYear: 1992,
      hometown: "Lexington, KY",
      highSchool: "Lexington Christian Academy, Lexington, KY",
      bio: "A Lexington native junior walk-on forward.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Business Professional",
        location: "Lexington, KY",
        statusNote: "The Lexington native walk-on works in business in the Lexington area.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/brian-long/",
      },
      membership: { role: "PLAYER", jerseyNumber: 34, position: "Forward", yearsAtSchool: "2010-2014", statsNote: "Kentucky native walk-on", gamesPlayed: 11 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2012-13", yearLabel: "Junior (walk-on)", sortOrder: 203, gamesPlayed: 11 },
      ],
      careerEvents: [],
    },
    {
      slug: "twany-beckham",
      firstName: "Twany",
      lastName: "Beckham",
      birthYear: 1989,
      hometown: "Indianapolis, IN",
      highSchool: "North Central High School, Indianapolis, IN",
      bio: "A redshirt senior walk-on guard and Mississippi State transfer.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Indianapolis, IN",
        statusNote: "After earning his Kentucky degree, Beckham has worked in the Indianapolis area.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/twany-beckham/",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Guard", yearsAtSchool: "2010-2013", statsNote: "Mississippi State transfer", gamesPlayed: 15, pointsPerGame: 0.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2012-13", yearLabel: "RS Senior", sortOrder: 204, gamesPlayed: 15 },
      ],
      careerEvents: [],
    },
    {
      slug: "ej-floreal",
      firstName: "EJ",
      lastName: "Floreal",
      birthYear: 1994,
      hometown: "Lexington, KY",
      highSchool: "Paul Laurence Dunbar HS, Lexington, KY",
      bio: "A freshman walk-on forward, son of Kentucky track coach Edrick Floreal. His sister is Olympic hurdler Sydney McLaughlin-Levrone (via marriage).",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Lexington, KY",
        statusNote: "Son of Kentucky track coach Edrick Floreal. After Kentucky basketball career, has worked in the Lexington area.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/ej-floreal/",
      },
      membership: { role: "PLAYER", jerseyNumber: 21, position: "Forward", yearsAtSchool: "2012-2015", statsNote: "Walk-on • Kentucky native", gamesPlayed: 9 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2012-13", yearLabel: "Freshman (walk-on)", sortOrder: 201, gamesPlayed: 9 },
      ],
      careerEvents: [],
    },
    {
      slug: "tod-lanter",
      firstName: "Tod",
      lastName: "Lanter",
      birthYear: 1992,
      hometown: "Frankfort, KY",
      highSchool: "Western Hills High School, Frankfort, KY",
      bio: "A freshman walk-on guard from Frankfort who joined the Wildcats during the 2012-13 NIT season.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Kentucky",
        statusNote: "A Kentucky native walk-on who stayed with the program through 2015, now works in the Kentucky area.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/tod-lanter/",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Guard", yearsAtSchool: "2012-2015", statsNote: "Freshman walk-on", gamesPlayed: 6 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2012-13", yearLabel: "Freshman (walk-on)", sortOrder: 201, gamesPlayed: 6 },
      ],
      careerEvents: [],
    },
    {
      slug: "orlando-antigua",
      firstName: "Orlando",
      lastName: "Antigua",
      birthYear: 1975,
      hometown: "New York, NY",
      highSchool: "George Washington High School, New York, NY",
      bio: "Dominican-American assistant who followed Calipari from Memphis. Top recruiter, especially with international talent. First Dominican-born D1 coach.",
      status: {
        occupationType: "COACH",
        currentTitle: "Associate Head Coach",
        currentEmployer: "University of Illinois",
        location: "Champaign, IL",
        statusNote: "Antigua was a Kentucky assistant (2009-2014, 2021-2024), sandwiching stints as South Florida HC and Illinois associate HC. After Calipari left for Arkansas in 2024, Antigua returned to Illinois under Brad Underwood.",
        sourceUrl: "https://en.wikipedia.org/wiki/Orlando_Antigua",
      },
      membership: { role: "ASSISTANT_COACH", position: "Assistant Coach", yearsAtSchool: "2009-2014" },
      careerEvents: [],
    },
    {
      slug: "kenny-payne",
      firstName: "Kenny",
      lastName: "Payne",
      birthYear: 1966,
      hometown: "Louisville, KY",
      highSchool: "Shawnee High School, Louisville, KY",
      bio: "Kentucky's primary big-man developer for a decade. Former NBA player and Louisville native. His post coaching was key to multiple lottery picks.",
      status: {
        occupationType: "COACH",
        currentTitle: "Associate Head Coach",
        currentEmployer: "University of Arkansas",
        location: "Fayetteville, AR",
        statusNote: "After 10 years as Kentucky assistant (2010-2020), Payne became Louisville HC but was fired in 2024 after going 12-52. He reunited with Calipari at Arkansas as associate HC.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kenny_Payne",
      },
      membership: { role: "ASSISTANT_COACH", position: "Associate Head Coach", yearsAtSchool: "2010-2020" },
      careerEvents: [],
    },
    {
      slug: "john-calipari",
      firstName: "John",
      lastName: "Calipari",
      birthYear: 1959,
      hometown: "Moon Township, PA",
      highSchool: "Moon Area High School, Moon Township, PA",
      bio: "Coached the worst season of his Kentucky tenure — defending national champions who failed to even make the NCAA Tournament after Nerlens Noel's ACL tear derailed the season.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "University of Arkansas",
        league: "SEC",
        location: "Fayetteville, AR",
        statusNote: "Left Kentucky for Arkansas in April 2024. This 2012-13 team is his only Kentucky squad to miss the NCAA Tournament.",
        sourceUrl: "https://en.wikipedia.org/wiki/John_Calipari",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2024", statsNote: "21-12 • NIT 1st Round • Only NCAA miss" },
      careerEvents: [],
    },
  ],
};
