import type { TeamSeed } from "./types";

export const kentuckyBasketball2022: TeamSeed = {
  slug: "kentucky-basketball-2022",
  name: "Kentucky Wildcats",
  season: "2021-2022",
  sport: "Men's Basketball",
  school: "University of Kentucky",
  conference: "SEC",
  accomplishment: "SEC Tournament Champions (26-8, lost to Saint Peter's R1)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png",
  mascotName: "Wildcat",
  people: [
    {
      slug: "oscar-tshiebwe",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1631131.png",
      firstName: "Oscar",
      lastName: "Tshiebwe",
      birthYear: 1999,
      hometown: "Lubumbashi, DR Congo",
      highSchool: "Kennedy Catholic High School, Hermitage, PA",
      isFeatured: true,
      bio: "The consensus National Player of the Year who averaged 17.4 PPG and 15.1 RPG — the highest rebounding average in 50 years. A transfer from West Virginia who became the most dominant rebounder in college basketball history.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward / Center",
        currentEmployer: "Utah Jazz (two-way)",
        league: "NBA / G League",
        location: "Salt Lake City, UT",
        statusNote: "Two-time National/SEC Player of the Year. Won consensus National Player of the Year in 2021-22 with historically dominant numbers (17.4 PPG, 15.1 RPG — highest rebounding average in 50 years), then returned for 2022-23 and won SEC POY again. Despite those accolades, went undrafted in 2023. Signed two-way deals with the Pacers and Jazz. In the G League, set a career-high 30 rebounds in a single game. Made 14 NBA appearances for the Jazz in 2024-25 (7.6 PPG, 8.7 RPG).",
        sourceUrl: "https://en.wikipedia.org/wiki/Oscar_Tshiebwe",
      },
      membership: { role: "PLAYER", jerseyNumber: 34, position: "Forward / Center", yearsAtSchool: "2020-2023", statsNote: "Junior • Consensus National POY • 17.4 PPG, 15.1 RPG", gamesPlayed: 34, pointsPerGame: 17.4, reboundsPerGame: 15.1, assistsPerGame: 1.3 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Kennedy Catholic High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 31.1, reboundsPerGame: 15.0, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2021-2022", yearLabel: "Junior", sortOrder: 201, gamesPlayed: 34, pointsPerGame: 17.4, reboundsPerGame: 15.1, assistsPerGame: 1.3 },
      ],
      careerEvents: [
        { year: 2022, title: "Won Consensus National Player of the Year", eventType: "AWARD" },
        { year: 2023, title: "Went undrafted; signed with Indiana Pacers", eventType: "SIGNING" },
      ],
    },
    {
      slug: "tyty-washington",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1631102.png",
      firstName: "TyTy",
      lastName: "Washington Jr.",
      birthYear: 2002,
      hometown: "Phoenix, AZ",
      highSchool: "Dream City Christian Academy, Glendale, AZ",
      isFeatured: false,
      bio: "A freshman point guard who declared for the NBA Draft after one season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "LA Clippers (two-way)",
        league: "NBA / G League",
        location: "Los Angeles, CA",
        statusNote: "Drafted #29 overall by the Memphis Grizzlies in 2022. Has bounced around on two-way deals with the Bucks, Suns, and now Clippers. Primarily plays in the G League.",
        sourceUrl: "https://www.nba.com/player/1631102/tyty-washington-jr",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Guard", yearsAtSchool: "2021-2022", statsNote: "Freshman • 12.5 PPG • #29 overall pick" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Dream City Christian Academy", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 23.8, reboundsPerGame: 3.5, assistsPerGame: 7.1 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2021-2022", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 29, pointsPerGame: 12.5, reboundsPerGame: 3.5, assistsPerGame: 3.9 },
      
        { level: "PROFESSIONAL", teamName: "Memphis Grizzlies", season: "2022-23", yearLabel: "2022-23 (Rookie)", sortOrder: 301, gamesPlayed: 22, pointsPerGame: 3.4, reboundsPerGame: 1.3, assistsPerGame: 1.5 },
        { level: "PROFESSIONAL", teamName: "Various", season: "2023-26", yearLabel: "2023-26 (two-way)", sortOrder: 302, gamesPlayed: 40, pointsPerGame: 2.5, reboundsPerGame: 1.0, assistsPerGame: 1.2 },
      ],
      careerEvents: [
        { year: 2022, title: "Selected #29 overall by the Memphis Grizzlies", eventType: "DRAFT" },
      ],
    },
    {
      slug: "shaedon-sharpe",
      firstName: "Shaedon",
      lastName: "Sharpe",
      birthYear: 2003,
      hometown: "London, ON, Canada",
      highSchool: "Dream City Christian Academy, Glendale, AZ",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1631101.png",
      bio: "A five-star freshman who enrolled early but never played a single game at Kentucky before declaring for the NBA Draft and going #7 overall.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Portland Trail Blazers",
        league: "NBA",
        location: "Portland, OR",
        statusNote: "Never played a game at Kentucky but was drafted #7 overall by the Portland Trail Blazers in 2022. Had a breakout 2025-26 season averaging 21.4 PPG before being sidelined in February 2026 with a stress reaction in his left fibula. Signed a 4-year, $90M extension in October 2025 — considered a bargain by many.",
        sourceUrl: "https://en.wikipedia.org/wiki/Shaedon_Sharpe",
      },
      membership: { role: "PLAYER", jerseyNumber: 21, position: "Guard", yearsAtSchool: "2021-2022", statsNote: "Freshman • Did NOT play • #7 overall pick without playing a game" },
      careerEvents: [
        { year: 2022, title: "Selected #7 overall by Portland (never played at UK)", eventType: "DRAFT" },
        { year: 2025, title: "Signed 4-year, $90M extension with Blazers", eventType: "SIGNING" },
      ],
    },
    {
      slug: "sahvir-wheeler",
      firstName: "Sahvir",
      lastName: "Wheeler",
      birthYear: 2001,
      hometown: "Houston, TX",
      highSchool: "Houston Christian High School, Houston, TX",
      isFeatured: false,
      bio: "A speedy transfer point guard from Georgia who led the SEC in assists.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Wisconsin Herd (G League)",
        league: "NBA G League",
        statusNote: "After two seasons at Kentucky and one at Washington, Wheeler went undrafted in 2024. Has bounced through the G League (Maine Celtics, Memphis Hustle, Wisconsin Herd).",
        sourceUrl: "https://en.wikipedia.org/wiki/Sahvir_Wheeler",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Point Guard", yearsAtSchool: "2021-2023", statsNote: "Junior • Transfer from Georgia • Led SEC in assists" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Houston Christian High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 20.1, reboundsPerGame: 2.6, assistsPerGame: 11.0 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2021-2022", yearLabel: "Junior", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 10.1, reboundsPerGame: 2.6, assistsPerGame: 6.9 },
      
        { level: "PROFESSIONAL", teamName: "Portland Trail Blazers", season: "2022-23", yearLabel: "2022-23 (Rookie)", sortOrder: 301, gamesPlayed: 65, pointsPerGame: 9.9, reboundsPerGame: 2.6, assistsPerGame: 1.5 },
        { level: "PROFESSIONAL", teamName: "Portland Trail Blazers", season: "2023-24", yearLabel: "2023-24", sortOrder: 302, gamesPlayed: 48, pointsPerGame: 15.9, reboundsPerGame: 3.5, assistsPerGame: 2.0 },
        { level: "PROFESSIONAL", teamName: "Portland Trail Blazers", season: "2024-25", yearLabel: "2024-25", sortOrder: 303, gamesPlayed: 72, pointsPerGame: 18.5, reboundsPerGame: 4.0, assistsPerGame: 2.4 },
        { level: "PROFESSIONAL", teamName: "Portland Trail Blazers", season: "2025-26", yearLabel: "2025-26 ($90M extension)", sortOrder: 304, gamesPlayed: 40, pointsPerGame: 21.4, reboundsPerGame: 4.4, assistsPerGame: 2.6 },
      ],
      careerEvents: [{ year: 2024, title: "Went undrafted; began G League career", eventType: "CAREER" }],
    },
    {
      slug: "kellan-grady",
      firstName: "Kellan",
      lastName: "Grady",
      birthYear: 1999,
      hometown: "Needham, MA",
      highSchool: "Northfield Mount Hermon School, Gill, MA",
      isFeatured: false,
      bio: "A graduate transfer sharpshooter from Davidson who provided veteran scoring and leadership.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Zastal Zielona Gora",
        league: "Polish Basketball League (PLK)",
        location: "Poland",
        statusNote: "Went undrafted in 2022. Built a European career in France, Germany, and Poland. Currently with Zastal Zielona Gora in Poland's PLK.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kellan_Grady",
      },
      membership: { role: "PLAYER", jerseyNumber: 31, position: "Guard", yearsAtSchool: "2021-2022", statsNote: "Graduate Senior • Transfer from Davidson • Elite three-point shooter" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Northfield Mount Hermon School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 21.8, reboundsPerGame: 2.7, assistsPerGame: 3.3 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2021-2022", yearLabel: "Graduate Senior", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 11.2, reboundsPerGame: 2.7, assistsPerGame: 1.0 },
      ],
      careerEvents: [{ year: 2022, title: "Went undrafted; began European career", eventType: "CAREER" }],
    },
    {
      slug: "keion-brooks",
      firstName: "Keion",
      lastName: "Brooks Jr.",
      birthYear: 2000,
      hometown: "Fort Wayne, IN",
      highSchool: "La Lumiere School, La Porte, IN",
      isFeatured: false,
      bio: "A junior forward in his third year at Kentucky.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Noblesville Boom (G League)",
        league: "NBA G League",
        statusNote: "Transferred to Washington for his senior year. Went undrafted in 2024. Now in the G League with Pelicans call-ups.",
        sourceUrl: "https://en.wikipedia.org/wiki/Keion_Brooks_Jr.",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Forward", yearsAtSchool: "2019-2022", statsNote: "Junior • 10.8 PPG" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "La Lumiere School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 21.2, reboundsPerGame: 8.7, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2021-2022", yearLabel: "Junior", sortOrder: 201, gamesPlayed: 34, pointsPerGame: 10.8, reboundsPerGame: 4.4, assistsPerGame: 1.2 },
      ],
      careerEvents: [{ year: 2022, title: "Transferred to University of Washington", eventType: "OTHER" }],
    },
    {
      slug: "jacob-toppin",
      firstName: "Jacob",
      lastName: "Toppin",
      birthYear: 2000,
      hometown: "Brooklyn, NY",
      highSchool: "Ossining High School, Ossining, NY",

      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1631210.png",
      isFeatured: false,
      bio: "Obi Toppin's younger brother who developed into a high-flying contributor.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Atlanta Hawks (two-way)",
        league: "NBA",
        location: "Atlanta, GA",
        statusNote: "Signed a two-way with the Hawks but is out for 2025-26 after season-ending shoulder surgery (torn labrum). Before injury: 18.0 PPG, 10.4 RPG in 5 G League games.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jacob_Toppin",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Forward", yearsAtSchool: "2020-2023", statsNote: "Junior • Obi Toppin's brother • High-flying dunker" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Ossining High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 12.5, reboundsPerGame: 7.3, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2020-2021", yearLabel: "Sophomore", sortOrder: 201, gamesPlayed: 24, pointsPerGame: 5.0, reboundsPerGame: 3.3, assistsPerGame: 0.6 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2021-2022", yearLabel: "Junior", sortOrder: 202, gamesPlayed: 34, pointsPerGame: 6.2, reboundsPerGame: 3.2, assistsPerGame: 0.7 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2022-2023", yearLabel: "Senior", sortOrder: 203, gamesPlayed: 35, pointsPerGame: 8.2, reboundsPerGame: 4.6, assistsPerGame: 1.0 },
      ],
      careerEvents: [{ year: 2023, title: "Went undrafted; signed two-way with Hawks", eventType: "SIGNING" }],
    },
    {
      slug: "davion-mintz",
      firstName: "Davion",
      lastName: "Mintz",
      birthYear: 1998,
      hometown: "Charlotte, NC",
      highSchool: "North Mecklenburg High School, Huntersville, NC",
      isFeatured: false,
      bio: "A veteran graduate guard in his second year at Kentucky who provided steady leadership.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Wurzburg Baskets",
        league: "German Basketball Bundesliga (BBL)",
        location: "Wurzburg, Germany",
        statusNote: "A graduate transfer from Creighton who provided veteran leadership during Kentucky's difficult 9-16 season, then returned for a second year. After going undrafted in 2022, he's built a solid European career — Exhibit 10 with the Wizards, Capital City Go-Go (G League), Metros de Santiago (Dominican Republic), Filou Oostende (Belgium), and now Wurzburg Baskets in Germany's BBL where he's averaging 15.2 PPG and helped them reach the semifinals for the first time since 2012.",
        sourceUrl: "https://en.wikipedia.org/wiki/Davion_Mintz",
      },
      membership: { role: "PLAYER", jerseyNumber: 10, position: "Guard", yearsAtSchool: "2020-2022", statsNote: "Graduate • Second year at UK • Veteran leader" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "North Mecklenburg High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 22.2, reboundsPerGame: 2.8, assistsPerGame: 5.2 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2020-2021", yearLabel: "Graduate Senior", sortOrder: 201, gamesPlayed: 25, pointsPerGame: 11.5, reboundsPerGame: 2.8, assistsPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2021-2022", yearLabel: "Super Senior", sortOrder: 202, gamesPlayed: 34, pointsPerGame: 5.3, reboundsPerGame: 1.8, assistsPerGame: 1.4 },
      ],
      careerEvents: [{ year: 2022, title: "Went undrafted; began European career", eventType: "CAREER" }],
    },
    {
      slug: "daimion-collins",
      firstName: "Daimion",
      lastName: "Collins",
      birthYear: 2003,
      hometown: "Atlanta, TX",
      highSchool: "Atlanta High School, Atlanta, TX",
      isFeatured: false,
      bio: "A highly recruited five-star freshman forward/center who showed flashes of athleticism.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of South Florida",
        league: "AAC",
        statusNote: "After two years at Kentucky, transferred to LSU for two years, then to South Florida for 2025-26. His father passed away during his time at UK.",
        sourceUrl: "https://en.wikipedia.org/wiki/Daimion_Collins",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Forward / Center", yearsAtSchool: "2021-2023", statsNote: "Freshman • Five-star recruit" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Atlanta High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 8.9, reboundsPerGame: 5.3, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2021-2022", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 31, pointsPerGame: 2.6, reboundsPerGame: 1.8, assistsPerGame: 0.2 },
      ],
      careerEvents: [{ year: 2023, title: "Transferred to LSU", eventType: "OTHER" }],
    },
    {
      slug: "bryce-hopkins",
      firstName: "Bryce",
      lastName: "Hopkins",
      birthYear: 2003,
      hometown: "Chicago, IL",
      highSchool: "Oak Hill Academy, Mouth of Wilson, VA",
      isFeatured: false,
      bio: "A freshman forward who transferred after one season and eventually became an All-Big East player at St. John's.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "St. John's University",
        league: "Big East",
        statusNote: "After Kentucky, transferred to Providence (tore ACL in 2024), then St. John's. Named All-Big East Second Team in 2025-26, averaging 13.3 PPG. Played in the Sweet 16.",
        sourceUrl: "https://www.espn.com/mens-college-basketball/player/_/id/4565698/bryce-hopkins",
      },
      membership: { role: "PLAYER", jerseyNumber: 23, position: "Forward", yearsAtSchool: "2021-2022", statsNote: "Freshman • Transferred to Providence" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Oak Hill Academy", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 9.8, reboundsPerGame: 6.4, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2021-2022", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 29, pointsPerGame: 3.2, reboundsPerGame: 2.6, assistsPerGame: 0.3 },
      ],
      careerEvents: [
        { year: 2022, title: "Transferred to Providence", eventType: "OTHER" },
        { year: 2026, title: "Named All-Big East Second Team at St. John's", eventType: "AWARD" },
      ],
    },
    {
      slug: "cj-fredrick",
      firstName: "CJ",
      lastName: "Fredrick",
      birthYear: 1999,
      hometown: "Cincinnati, OH",
      highSchool: "Covington Catholic High School, Park Hills, KY",
      isFeatured: false,
      bio: "A transfer from Iowa who missed most of this season with a hamstring injury. Married former Kentucky women's basketball player Blair Green.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        statusNote: "After two seasons at Kentucky and one at Cincinnati, Fredrick retired from basketball in April 2025 due to persistent injuries (hamstring, ribs, ankle, feet, back).",
        sourceUrl: "https://www.aseaofblue.com/2025/4/10/24405583/cj-fredrick-retirement-basketball-cincinnati-bearcats-kentucky",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Guard", yearsAtSchool: "2021-2023", statsNote: "Junior • Transfer from Iowa • Missed most of season (hamstring)" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Covington Catholic High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 8.9, reboundsPerGame: 0.7, assistsPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2021-2022", yearLabel: "Junior", sortOrder: 201, gamesPlayed: 7, pointsPerGame: 2.6, reboundsPerGame: 0.7, assistsPerGame: 0.4 },
      ],
      careerEvents: [{ year: 2025, title: "Retired from basketball due to injuries", eventType: "RETIREMENT" }],
    },
    {
      slug: "lance-ware",
      firstName: "Lance",
      lastName: "Ware",
      birthYear: 2001,
      hometown: "Burlington, NJ",
      highSchool: "Camden High School, Camden, NJ",
      isFeatured: false,
      bio: "A physical sophomore forward who provided energy off the bench.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Iraklis",
        league: "Greek Heba A1",
        location: "Greece",
        statusNote: "After Kentucky, Villanova, and UT Arlington (where he earned All-WAC honors), Ware signed in Greece, averaging 8.5 PPG and 5.2 RPG.",
        sourceUrl: "https://www.proballers.com/basketball/player/233360/lance-ware",
      },
      membership: { role: "PLAYER", jerseyNumber: 55, position: "Forward", yearsAtSchool: "2020-2022", statsNote: "Sophomore • Physical rebounder" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Camden High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 8.3, reboundsPerGame: 6.4, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2020-2021", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 24, pointsPerGame: 2.2, reboundsPerGame: 2.6, assistsPerGame: 0.4 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2021-2022", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 30, pointsPerGame: 2.0, reboundsPerGame: 2.4, assistsPerGame: 0.5 },
      ],
      careerEvents: [{ year: 2025, title: "Signed in Greece after UT Arlington", eventType: "SIGNING" }],
    },
    {
      slug: "dontaie-allen-uk",
      firstName: "Dontaie",
      lastName: "Allen",
      birthYear: 2000,
      hometown: "Falmouth, KY",
      highSchool: "Pendleton County High School, Falmouth, KY",
      isFeatured: false,
      bio: "The 2019 Kentucky Mr. Basketball returned for his junior year as the lone Bluegrass-born scholarship player on a stacked roster. Saw limited minutes before transferring to Western Kentucky.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        statusNote: "Played three seasons at Kentucky (2019-22), averaging 2.2 PPG as a junior with a season-high 14 against North Florida. Transferred to Western Kentucky in April 2022 to reunite with Rick Stansbury, the coach who originally recruited him out of Pendleton County. Played two seasons at WKU (8.7 PPG) before a year at Wyoming (7.8 PPG, 17 starts) and entered the portal in April 2025 looking for a sixth and final school as a Kentucky Mr. Basketball still searching for the right fit.",
        sourceUrl: "https://www.on3.com/teams/kentucky-wildcats/news/former-kentucky-wildcat-dontaie-allen-transfer-portal-wyoming/",
      },
      membership: { role: "PLAYER", jerseyNumber: 11, position: "Guard", yearsAtSchool: "2019-2022", statsNote: "Junior • KY Mr. Basketball • Sharpshooter" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Pendleton County High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 42.9, reboundsPerGame: 11.4 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2021-2022", yearLabel: "Junior", sortOrder: 201, gamesPlayed: 21, pointsPerGame: 2.2, reboundsPerGame: 0.5 },
      ],
      careerEvents: [
        { year: 2022, title: "Transferred to Western Kentucky", eventType: "TRANSFER" },
      ],
    },
    {
      slug: "kareem-watkins",
      firstName: "Kareem",
      lastName: "Watkins",
      birthYear: 2002,
      hometown: "Camden, NJ",
      highSchool: "Kingsway Regional High School, Woolwich Township, NJ",
      isFeatured: false,
      bio: "A walk-on guard whose stepfather is former Memphis star Dajuan Wagner and whose half-brother is Kentucky guard DJ Wagner. Spent four seasons at UK before transferring to Arkansas with John Calipari.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "Graduate Walk-On Player",
        currentEmployer: "Arkansas Razorbacks",
        league: "SEC",
        location: "Fayetteville, AR",
        statusNote: "Walked on at Kentucky in November 2020 and appeared in 16 career games over four seasons (2020-24), including a senior-night start against Vanderbilt. Graduated from UK with a degree in finance and followed John Calipari to Arkansas in 2024-25 as a graduate walk-on while pursuing a master's in adult and lifelong learning. His stepfather Dajuan Wagner played for Calipari at Memphis and his half-brother DJ Wagner is the No. 1 player in the 2023 class.",
        sourceUrl: "https://arkansasrazorbacks.com/roster/kareem-watkins/",
      },
      membership: { role: "PLAYER", jerseyNumber: 25, position: "Guard", yearsAtSchool: "2020-2024", statsNote: "Walk-on • Stepson of Dajuan Wagner • Brother of DJ Wagner" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Kingsway Regional High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 8.7 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2021-2022", yearLabel: "Sophomore", sortOrder: 201, gamesPlayed: 9, pointsPerGame: 0.0, reboundsPerGame: 0.3 },
      ],
      careerEvents: [
        { year: 2024, title: "Followed Calipari to Arkansas as graduate walk-on", eventType: "TRANSFER" },
      ],
    },
    {
      slug: "brennan-canada",
      firstName: "Brennan",
      lastName: "Canada",
      birthYear: 2000,
      hometown: "Mount Sterling, KY",
      highSchool: "George Rogers Clark High School, Winchester, KY",
      isFeatured: false,
      bio: "A homegrown Kentucky walk-on forward who became a beloved locker-room presence over five seasons in Lexington. Eventually earned a scholarship from John Calipari.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Sport Leadership Graduate",
        statusNote: "Joined Kentucky as a walk-on in April 2019 after a standout career at George Rogers Clark High School (1,371 career points, 776 rebounds). Played five seasons for the Wildcats and was awarded a scholarship by John Calipari in January 2023. Named to the 2024 SEC Community Service Team and earned his master's degree in sport leadership in May 2024.",
        sourceUrl: "https://ukathletics.com/sports/mbball/roster/player/brennan-canada/",
      },
      membership: { role: "PLAYER", jerseyNumber: 33, position: "Forward", yearsAtSchool: "2019-2024", statsNote: "Walk-on • Future scholarship player • Locker-room leader" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "George Rogers Clark High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 15.0, reboundsPerGame: 9.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2021-2022", yearLabel: "Junior", sortOrder: 201, gamesPlayed: 4, pointsPerGame: 0.3 },
      ],
      careerEvents: [
        { year: 2023, title: "Awarded a scholarship by John Calipari", eventType: "OTHER" },
        { year: 2024, title: "Earned master's in sport leadership", eventType: "EDUCATION" },
      ],
    },
    {
      slug: "john-calipari",
      firstName: "John",
      lastName: "Calipari",
      birthYear: 1959,
      hometown: "Moon Township, PA",
      highSchool: "Moon Area High School, Moon Township, PA",
      isFeatured: true,
      bio: "Led Kentucky to an SEC Tournament title but suffered a historic first-round upset loss to #15 Saint Peter's.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "University of Arkansas",
        league: "SEC",
        location: "Fayetteville, AR",
        statusNote: "After 15 seasons at Kentucky (2009-2024) compiling a 410-127 record, one national championship (2012), four Final Fours, and more NBA Draft picks than any coach in history (42 first-round picks), Calipari left for Arkansas in April 2024 on a 5-year, $35M deal. In his first full season at Arkansas (2025-26), he won the SEC Tournament Championship — becoming the first men's coach to win SEC Tournament titles at multiple schools. He ranks 5th on the all-time NCAA Division I wins list with 900+ career victories.",
        sourceUrl: "https://en.wikipedia.org/wiki/John_Calipari",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2024", statsNote: "26-8 • SEC Tournament Champions • Lost to #15 Saint Peter's in NCAA R1" },
      careerEvents: [{ year: 2022, title: "Lost to #15 Saint Peter's in NCAA Tournament first round", eventType: "OTHER" }],
    },
  ],
};
