import type { TeamSeed } from "./types";

export const kentuckyBasketball2010: TeamSeed = {
  slug: "kentucky-basketball-2010",
  name: "Kentucky Wildcats",
  season: "2009-2010",
  sport: "Men's Basketball",
  school: "University of Kentucky",
  conference: "SEC",
  accomplishment: "Elite Eight (35-3) — Calipari's first season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png",
  mascotName: "Wildcat",
  people: [
    {
      slug: "john-wall",
      firstName: "John",
      lastName: "Wall",
      birthYear: 1990,
      hometown: "Raleigh, NC",
      highSchool: "Word of God Christian Academy, Raleigh, NC",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/202322.png",
      bio: "The #1 overall pick in the 2010 NBA Draft. Wall led Kentucky to the Elite Eight in Calipari's first season with an electrifying combination of speed and passing.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NBA Player / Free Agent",
        location: "Raleigh, NC",
        statusNote: "A 5-time NBA All-Star with the Washington Wizards, Wall's career was derailed by devastating injuries to his Achilles and knees. He last played in the NBA with the Los Angeles Clippers in 2022-23 and has effectively been out of the league since, though he has not officially retired.",
        sourceUrl: "https://en.wikipedia.org/wiki/John_Wall",
      },
      membership: { role: "PLAYER", jerseyNumber: 11, position: "Point Guard", yearsAtSchool: "2009-2010", statsNote: "#1 overall pick • Elite Eight", gamesPlayed: 37, pointsPerGame: 16.6, reboundsPerGame: 4.3, assistsPerGame: 6.5 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Word of God Christian Academy", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 22.0, assistsPerGame: 9.0 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2009-10", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 16.6, reboundsPerGame: 4.3, assistsPerGame: 6.5 },
        { level: "PROFESSIONAL", teamName: "Washington Wizards", season: "2016-17", yearLabel: "2016-17 (All-NBA)", sortOrder: 307, gamesPlayed: 78, pointsPerGame: 23.1, assistsPerGame: 10.7 },
      ],
      careerEvents: [
        { year: 2010, title: "Selected #1 overall by the Washington Wizards", eventType: "DRAFT" },
      ],
    },
    {
      slug: "demarcus-cousins",
      firstName: "DeMarcus",
      lastName: "Cousins",
      birthYear: 1990,
      hometown: "Mobile, AL",
      highSchool: "LeFlore High School, Mobile, AL",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/202326.png",
      bio: "A dominant freshman center who averaged 15.1 and 9.8 rebounds as Kentucky's most unstoppable interior force. The #5 overall pick in 2010.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NBA Player",
        location: "Los Angeles, CA",
        statusNote: "A 4-time NBA All-Star and 2018 NBA Champion with the Golden State Warriors (inactive in the Finals due to injury). Cousins' career was cut short by a torn Achilles in 2018. Last played in the NBA in 2022-23 with the Denver Nuggets.",
        sourceUrl: "https://en.wikipedia.org/wiki/DeMarcus_Cousins",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Center", yearsAtSchool: "2009-2010", statsNote: "#5 overall pick • Elite Eight", gamesPlayed: 38, pointsPerGame: 15.1, reboundsPerGame: 9.8, assistsPerGame: 1.0 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2009-10", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 38, pointsPerGame: 15.1, reboundsPerGame: 9.8 },
        { level: "PROFESSIONAL", teamName: "Sacramento Kings", season: "2015-16", yearLabel: "2015-16", sortOrder: 306, gamesPlayed: 65, pointsPerGame: 26.9, reboundsPerGame: 11.5 },
      ],
      careerEvents: [
        { year: 2010, title: "Selected #5 overall by the Sacramento Kings", eventType: "DRAFT" },
        { year: 2018, title: "Won NBA Championship with Golden State Warriors", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "eric-bledsoe",
      firstName: "Eric",
      lastName: "Bledsoe",
      birthYear: 1989,
      hometown: "Birmingham, AL",
      highSchool: "Parker High School, Birmingham, AL",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/202339.png",
      bio: "A tough defensive guard who played off the ball alongside John Wall. The #18 overall pick in 2010.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Point Guard",
        currentEmployer: "Overseas",
        league: "International",
        location: "Europe",
        statusNote: "Played 12 NBA seasons with the Clippers, Suns, Bucks, Pelicans, and Blazers. Known for his defensive tenacity. Has been playing overseas in recent years after his NBA career wound down.",
        sourceUrl: "https://en.wikipedia.org/wiki/Eric_Bledsoe",
      },
      membership: { role: "PLAYER", jerseyNumber: 24, position: "Guard", yearsAtSchool: "2009-2010", statsNote: "#18 overall pick", gamesPlayed: 38, pointsPerGame: 11.3, reboundsPerGame: 3.1, assistsPerGame: 2.9 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2009-10", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 38, pointsPerGame: 11.3 },
      ],
      careerEvents: [
        { year: 2010, title: "Selected #18 overall by OKC (traded to Clippers)", eventType: "DRAFT" },
      ],
    },
    {
      slug: "patrick-patterson",
      firstName: "Patrick",
      lastName: "Patterson",
      birthYear: 1989,
      hometown: "Huntington, WV",
      highSchool: "Huntington High School, Huntington, WV",
      bio: "A junior forward and the team's veteran leader. Selected #14 overall by the Houston Rockets in 2010.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NBA Player",
        location: "Toronto, ON",
        statusNote: "Played 11 NBA seasons with the Rockets, Kings, Raptors, Thunder, Clippers, and Lakers before retiring in 2021. Fondly remembered as a key veteran during the Raptors' contending years.",
        sourceUrl: "https://en.wikipedia.org/wiki/Patrick_Patterson",
      },
      membership: { role: "PLAYER", jerseyNumber: 54, position: "Power Forward", yearsAtSchool: "2007-2010", statsNote: "Team captain • #14 overall pick", gamesPlayed: 36, pointsPerGame: 14.3, reboundsPerGame: 7.4, assistsPerGame: 1.1 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2009-10", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 36, pointsPerGame: 14.3, reboundsPerGame: 7.4 },
      ],
      careerEvents: [
        { year: 2010, title: "Selected #14 overall by the Houston Rockets", eventType: "DRAFT" },
        { year: 2021, title: "Retired from the NBA", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "daniel-orton",
      firstName: "Daniel",
      lastName: "Orton",
      birthYear: 1990,
      hometown: "Oklahoma City, OK",
      highSchool: "Bishop McGuinness Catholic HS, Oklahoma City, OK",
      bio: "A freshman backup center who left early for the NBA despite limited minutes. Drafted #29 by the Orlando Magic.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Professional Athlete",
        location: "Oklahoma City, OK",
        statusNote: "Selected #29 by the Magic in 2010, Orton played briefly for Orlando and the 76ers before spending years in the G League and overseas. Retired from basketball in the mid-2010s.",
        sourceUrl: "https://en.wikipedia.org/wiki/Daniel_Orton",
      },
      membership: { role: "PLAYER", jerseyNumber: 33, position: "Center", yearsAtSchool: "2009-2010", statsNote: "#29 overall pick", gamesPlayed: 32, pointsPerGame: 3.4, reboundsPerGame: 3.3, assistsPerGame: 0.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2009-10", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 32, pointsPerGame: 3.4, reboundsPerGame: 3.3 },
      ],
      careerEvents: [
        { year: 2010, title: "Selected #29 overall by the Orlando Magic", eventType: "DRAFT" },
      ],
    },
    {
      slug: "darius-miller",
      firstName: "Darius",
      lastName: "Miller",
      birthYear: 1990,
      hometown: "Maysville, KY",
      highSchool: "Mason County High School, Maysville, KY",
      bio: "A Kentucky native sophomore forward on Calipari's first team.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Overseas",
        league: "International",
        location: "Europe",
        statusNote: "Played parts of 5 NBA seasons with the New Orleans Pelicans. Has continued his career in Europe, particularly in Germany.",
        sourceUrl: "https://en.wikipedia.org/wiki/Darius_Miller",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Small Forward", yearsAtSchool: "2008-2012", statsNote: "Kentucky native • Future NCAA Champion", gamesPlayed: 38, pointsPerGame: 6.5, reboundsPerGame: 3.0, assistsPerGame: 1.4 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2009-10", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 38, pointsPerGame: 6.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "deandre-liggins",
      firstName: "DeAndre",
      lastName: "Liggins",
      birthYear: 1988,
      hometown: "Chicago, IL",
      highSchool: "Findlay College Prep, Henderson, NV",
      bio: "A defensive-minded sophomore guard and rotation player.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Overseas",
        league: "International",
        location: "Various",
        statusNote: "Selected #53 by Orlando in 2011. Played for the Magic, Thunder, and Cavaliers in the NBA. Has spent most of his pro career in the G League and international leagues.",
        sourceUrl: "https://en.wikipedia.org/wiki/DeAndre_Liggins",
      },
      membership: { role: "PLAYER", jerseyNumber: 34, position: "Guard", yearsAtSchool: "2008-2011", statsNote: "Elite Eight team", gamesPlayed: 38, pointsPerGame: 3.9, reboundsPerGame: 2.6, assistsPerGame: 1.3 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2009-10", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 38, pointsPerGame: 3.9 },
      ],
      careerEvents: [],
    },
    {
      slug: "ramon-harris",
      firstName: "Ramon",
      lastName: "Harris",
      birthYear: 1986,
      hometown: "Anchorage, AK",
      highSchool: "East High School, Anchorage, AK",
      bio: "A senior wing who was one of the few upperclassmen on Calipari's first roster.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Professional Athlete",
        location: "Anchorage, AK",
        statusNote: "Played professionally overseas after his Kentucky career, including stints in Europe and South America. Has since returned to Alaska.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/ramon-harris/",
      },
      membership: { role: "PLAYER", jerseyNumber: 14, position: "Small Forward", yearsAtSchool: "2006-2010", statsNote: "Senior on Elite Eight team", gamesPlayed: 35, pointsPerGame: 3.0, reboundsPerGame: 2.2, assistsPerGame: 0.7 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2009-10", yearLabel: "Senior", sortOrder: 204, gamesPlayed: 35, pointsPerGame: 3.0 },
      ],
      careerEvents: [],
    },
    {
      slug: "perry-stevenson",
      firstName: "Perry",
      lastName: "Stevenson",
      birthYear: 1987,
      hometown: "Laurel, MS",
      highSchool: "West Jones High School, Laurel, MS",
      bio: "A senior shot-blocking forward who helped anchor the front line.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Professional Athlete",
        location: "Mississippi",
        statusNote: "Played professionally overseas after his Kentucky career. Has since transitioned to life outside of basketball in Mississippi.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/perry-stevenson/",
      },
      membership: { role: "PLAYER", jerseyNumber: 21, position: "Power Forward", yearsAtSchool: "2006-2010", statsNote: "Senior shot-blocker", gamesPlayed: 38, pointsPerGame: 5.1, reboundsPerGame: 4.0, assistsPerGame: 0.4 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2009-10", yearLabel: "Senior", sortOrder: 204, gamesPlayed: 38, pointsPerGame: 5.1, blocksPerGame: 1.9 },
      ],
      careerEvents: [],
    },
    {
      slug: "mark-krebs",
      firstName: "Mark",
      lastName: "Krebs",
      birthYear: 1988,
      hometown: "Wilder, KY",
      highSchool: "Newport Central Catholic, Newport, KY",
      bio: "A senior Kentucky native walk-on guard — a fan favorite.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Northern Kentucky",
        statusNote: "Kentucky native walk-on who was a beloved member of the program. After graduating has worked professionally in Kentucky.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/mark-krebs/",
      },
      membership: { role: "PLAYER", jerseyNumber: 45, position: "Guard / Forward", yearsAtSchool: "2006-2010", statsNote: "Senior walk-on • Kentucky native", gamesPlayed: 28, pointsPerGame: 0.9 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2009-10", yearLabel: "Senior (walk-on)", sortOrder: 204, gamesPlayed: 28, pointsPerGame: 0.9 },
      ],
      careerEvents: [],
    },
    {
      slug: "josh-harrellson",
      firstName: "Josh",
      lastName: "Harrellson",
      birthYear: 1989,
      hometown: "St. Charles, MO",
      highSchool: "Francis Howell North HS, St. Charles, MO",
      bio: "A junior college transfer center nicknamed 'Jorts' for his jean shorts. Would become a cult hero the following year.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Professional Athlete",
        location: "St. Louis, MO",
        statusNote: "Selected #45 by the New Orleans Hornets in 2011 (traded to Knicks). Played briefly in the NBA for the Knicks, Heat, and Pistons before years overseas. Retired in the late 2010s.",
        sourceUrl: "https://en.wikipedia.org/wiki/Josh_Harrellson",
      },
      membership: { role: "PLAYER", jerseyNumber: 55, position: "Center", yearsAtSchool: "2009-2011", statsNote: "Junior college transfer", gamesPlayed: 36, pointsPerGame: 1.8, reboundsPerGame: 2.1, assistsPerGame: 0.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2009-10", yearLabel: "Junior (transfer)", sortOrder: 203, gamesPlayed: 36, pointsPerGame: 1.8 },
      ],
      careerEvents: [],
    },
    {
      slug: "jared-carter",
      firstName: "Jared",
      lastName: "Carter",
      birthYear: 1986,
      hometown: "Maysville, KY",
      highSchool: "Mason County High School, Maysville, KY",
      bio: "A 7-foot senior walk-on from the same Kentucky hometown as Darius Miller.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Kentucky",
        statusNote: "Kentucky native walk-on and beloved senior on the Elite Eight team. After graduation has worked in his home state.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/jared-carter/",
      },
      membership: { role: "PLAYER", jerseyNumber: 50, position: "Center", yearsAtSchool: "2006-2010", statsNote: "Senior walk-on • Kentucky native", gamesPlayed: 22 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2009-10", yearLabel: "Senior (walk-on)", sortOrder: 204, gamesPlayed: 22 },
      ],
      careerEvents: [],
    },
    {
      slug: "jon-hood",
      firstName: "Jon",
      lastName: "Hood",
      birthYear: 1990,
      hometown: "Madisonville, KY",
      highSchool: "Madisonville North Hopkins HS, Madisonville, KY",
      bio: "A freshman Kentucky native walk-on on Calipari's first team.",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Coach",
        currentEmployer: "Kentucky High School",
        location: "Kentucky",
        statusNote: "After his Kentucky career, Hood has coached at the high school level in Kentucky.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jon_Hood",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Guard", yearsAtSchool: "2009-2014", statsNote: "Freshman walk-on • Kentucky native", gamesPlayed: 16 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2009-10", yearLabel: "Freshman (walk-on)", sortOrder: 201, gamesPlayed: 16 },
      ],
      careerEvents: [],
    },
    {
      slug: "john-calipari",
      firstName: "John",
      lastName: "Calipari",
      birthYear: 1959,
      hometown: "Moon Township, PA",
      highSchool: "Moon Area High School, Moon Township, PA",
      bio: "In his first season at Kentucky, Calipari brought in the greatest recruiting class ever assembled — Wall, Cousins, Bledsoe, Orton — and went 35-3 before losing to West Virginia in the Elite Eight.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "University of Arkansas",
        league: "SEC",
        location: "Fayetteville, AR",
        statusNote: "Left Kentucky for Arkansas in April 2024 on a 5-year, $35M deal after 15 seasons at UK including this 2010 Elite Eight team that was his first roster at the program.",
        sourceUrl: "https://en.wikipedia.org/wiki/John_Calipari",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2024", statsNote: "35-3 • Elite Eight • First year at UK" },
      careerEvents: [
        { year: 2009, title: "Hired as Kentucky head coach", eventType: "CAREER" },
      ],
    },
  ],
};
