import type { TeamSeed } from "./types";

export const kentuckyBasketball2024: TeamSeed = {
  slug: "kentucky-basketball-2024",
  name: "Kentucky Wildcats",
  season: "2023-2024",
  sport: "Men's Basketball",
  school: "University of Kentucky",
  conference: "SEC",
  accomplishment: "Calipari's Last Year (23-10, lost to Oakland R1)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png",
  mascotName: "Wildcat",
  people: [
    {
      slug: "reed-sheppard",
      firstName: "Reed",
      lastName: "Sheppard",
      birthYear: 2005,
      hometown: "London, KY",
      highSchool: "North Laurel High School, London, KY",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1642263.png",
      bio: "Son of former Kentucky players Jeff Sheppard and Stacey Reed. Shot an absurd 52.1% from three as a freshman — the best in the nation — and was drafted #3 overall.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Houston Rockets",
        league: "NBA",
        location: "Houston, TX",
        statusNote: "Drafted #3 overall by the Houston Rockets in 2024 after leading the nation in three-point shooting at 52.1%. Averaging 13.5 PPG in 2025-26, shooting 40.7% from three. Scored 27 points with 9 threes (career high) vs. the Bucks on April 2, 2026. Son of UK legends Jeff Sheppard and Stacey Reed.",
        sourceUrl: "https://www.nba.com/player/1642263/reed-sheppard",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Guard", yearsAtSchool: "2023-2024", statsNote: "Freshman • 12.5 PPG • 52.1% from three (led nation) • #3 overall pick", gamesPlayed: 33, pointsPerGame: 12.5, reboundsPerGame: 4.1, assistsPerGame: 4.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2023-2024", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 12.5, reboundsPerGame: 4.1, assistsPerGame: 4.5 },
      ],
      careerEvents: [
        { year: 2024, title: "Selected #3 overall by the Houston Rockets", eventType: "DRAFT" },
      ],
    },
    {
      slug: "rob-dillingham",
      firstName: "Rob",
      lastName: "Dillingham",
      birthYear: 2005,
      hometown: "Hickory, NC",
      highSchool: "Overtime Elite (previously Donda Academy)",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1642264.png",
      bio: "A flashy freshman point guard who came off the bench but provided instant offense with 15.2 PPG and 44.4% from three.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Chicago Bulls",
        league: "NBA",
        location: "Chicago, IL",
        statusNote: "Drafted #8 overall by the San Antonio Spurs in 2024 and immediately traded to the Minnesota Timberwolves. Traded again to the Chicago Bulls in February 2026.",
        sourceUrl: "https://en.wikipedia.org/wiki/Rob_Dillingham",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Guard", yearsAtSchool: "2023-2024", statsNote: "Freshman • 15.2 PPG off bench • 44.4% from three • #8 overall pick", gamesPlayed: 33, pointsPerGame: 15.2, assistsPerGame: 3.9 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2023-2024", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 15.2, assistsPerGame: 3.9 },
      ],
      careerEvents: [
        { year: 2024, title: "Selected #8 overall by San Antonio (traded to Minnesota)", eventType: "DRAFT" },
        { year: 2026, title: "Traded to Chicago Bulls", eventType: "TRADE" },
      ],
    },
    {
      slug: "dj-wagner",
      firstName: "DJ",
      lastName: "Wagner",
      birthYear: 2005,
      hometown: "Camden, NJ",
      highSchool: "Camden High School, Camden, NJ",
      isFeatured: false,
      bio: "Son of Dajuan Wagner and grandson of Milt Wagner — a third-generation Kentucky basketball player. Started 28 of 29 games as a freshman.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Arkansas",
        league: "SEC",
        location: "Fayetteville, AR",
        statusNote: "Followed John Calipari to Arkansas after Calipari left Kentucky. Averaged 7.6 PPG with 2.4 APG as a junior in 2025-26. Third-generation Kentucky basketball legacy.",
        sourceUrl: "https://arkansasrazorbacks.com/roster/d-j-wagner/",
      },
      membership: { role: "PLAYER", jerseyNumber: 21, position: "Guard", yearsAtSchool: "2023-2024", statsNote: "Freshman • 9.9 PPG, 3.3 APG • 3rd-gen UK legacy • Transferred to Arkansas" },
      careerEvents: [
        { year: 2024, title: "Transferred to Arkansas to follow Calipari", eventType: "OTHER" },
      ],
    },
    {
      slug: "antonio-reeves",
      firstName: "Antonio",
      lastName: "Reeves",
      birthYear: 2001,
      hometown: "Chicago, IL",
      highSchool: "Simeon Career Academy, Chicago, IL",
      isFeatured: false,
      bio: "Returned for a second season at Kentucky as the team's leading scorer.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Charlotte Hornets (two-way)",
        league: "NBA / G League",
        statusNote: "A sharpshooting transfer from Illinois State who won SEC Co-Sixth Man of the Year in 2022-23, then returned as the team's leading scorer in 2023-24 (14.8 PPG). Drafted #47 overall by the Orlando Magic in 2024 and traded to the New Orleans Pelicans. Waived by New Orleans in July 2025, then signed a two-way deal with the Charlotte Hornets. In limited NBA minutes (7.6 MPG), shooting 47.4% from the field and 50.0% from three. Mostly plays for the Greensboro Swarm (G League).",
        sourceUrl: "https://www.nba.com/player/1641810/antonio-reeves",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Guard", yearsAtSchool: "2022-2024", statsNote: "Graduate Senior • Team's leading scorer • 14.8 PPG" },
      careerEvents: [
        { year: 2024, title: "Selected #47 overall by the Orlando Magic", eventType: "DRAFT" },
      ],
    },
    {
      slug: "justin-edwards",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1642348.png",
      firstName: "Justin",
      lastName: "Edwards",
      birthYear: 2005,
      hometown: "Philadelphia, PA",
      highSchool: "Imhotep Institute Charter High School, Philadelphia, PA",
      isFeatured: false,
      bio: "A five-star freshman forward from Philadelphia who went undrafted but earned an NBA spot with the hometown 76ers.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Philadelphia 76ers",
        league: "NBA",
        location: "Philadelphia, PA",
        statusNote: "Went undrafted in 2024 but signed a two-way with the hometown 76ers, later converted to a standard contract. Made 44 appearances (26 starts) in 2024-25, averaging 10.1 PPG. Re-signed on a 3-year, $2M deal.",
        sourceUrl: "https://www.nba.com/player/1642348/justin-edwards",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Forward", yearsAtSchool: "2023-2024", statsNote: "Freshman • Five-star recruit • 8.8 PPG • Now with 76ers" },
      careerEvents: [
        { year: 2024, title: "Went undrafted; signed two-way with Philadelphia 76ers", eventType: "SIGNING" },
      ],
    },
    {
      slug: "tre-mitchell",
      firstName: "Tre",
      lastName: "Mitchell",
      birthYear: 2001,
      hometown: "Pittsburgh, PA",
      highSchool: "Woodrow Wilson High School, Washington, D.C.",
      isFeatured: false,
      bio: "A well-traveled graduate transfer who provided experience in the post, having previously played at UMass, West Virginia, and Texas.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward / Center",
        currentEmployer: "JL Bourg",
        league: "LNB Pro A / EuroCup (France)",
        location: "Bourg-en-Bresse, France",
        statusNote: "A well-traveled graduate transfer who played at UMass, West Virginia, and Texas before arriving at Kentucky. Averaged 10.7 PPG, 7.2 RPG, and 2.6 APG for the Wildcats. Went undrafted in 2024 but moved to Europe — first Germany's Lowen Braunschweig (FIBA Europe Cup), then JL Bourg-en-Bresse in France's LNB Pro A and EuroCup where he's averaging 10.9 PPG and 3.0 SPG.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tre_Mitchell",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Forward / Center", yearsAtSchool: "2023-2024", statsNote: "Graduate • Transfer from Texas/WVU/UMass • 10.7 PPG, 7.2 RPG" },
      careerEvents: [{ year: 2024, title: "Went undrafted; began European career", eventType: "CAREER" }],
    },
    {
      slug: "adou-thiero",
      firstName: "Adou",
      lastName: "Thiero",
      birthYear: 2004,
      hometown: "Washington, D.C.",
      highSchool: "Transferred to Kentucky from Guinea via D.C.",
      isFeatured: false,
      bio: "A sophomore guard/forward who followed Calipari to Arkansas and became their leading scorer.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Los Angeles Lakers",
        league: "NBA",
        statusNote: "Followed Calipari to Arkansas, led team in scoring (15.1 PPG). Drafted #36 in 2025 (traded to Lakers). Rookie in 2025-26.",
        sourceUrl: "https://www.nba.com/player/1642876/adou-thiero",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Guard / Forward", yearsAtSchool: "2022-2024", statsNote: "Sophomore • 5.7 PPG • Later led Arkansas at 15.1 PPG" },
      careerEvents: [
        { year: 2024, title: "Transferred to Arkansas", eventType: "OTHER" },
        { year: 2025, title: "Selected #36 overall (traded to Lakers)", eventType: "DRAFT" },
      ],
    },
    {
      slug: "zvonimir-ivisic",
      firstName: "Zvonimir",
      lastName: "Ivisic",
      birthYear: 2003,
      hometown: "Vodice, Croatia",
      highSchool: "Croatian youth system",
      isFeatured: false,
      bio: "A 7-2 Croatian freshman center who missed the first 16 games due to eligibility issues but showed promise when he played.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Illinois",
        league: "Big Ten",
        statusNote: "A 7-2 Croatian center who missed the first 16 games of his freshman year at Kentucky due to eligibility issues, then showed promise in 15 games (5.5 PPG, 3.3 RPG, 1.3 BPG). Followed Calipari to Arkansas for 2024-25, then transferred to Illinois for 2025-26 to play alongside his twin brother Tomislav — the first brothers to play together for Illinois since the Judson twins in 1956. Has 2.0 BPG and 5 blocks vs #5 UConn.",
        sourceUrl: "https://www.espn.com/mens-college-basketball/player/_/id/5174665/zvonimir-ivisic",
      },
      membership: { role: "PLAYER", jerseyNumber: 44, position: "Center", yearsAtSchool: "2023-2024", statsNote: "Freshman • 7-2 Croatian • 5.5 PPG in 15 games • Missed first 16 (eligibility)" },
      careerEvents: [
        { year: 2024, title: "Transferred to Arkansas, then Illinois", eventType: "OTHER" },
      ],
    },
    {
      slug: "aaron-bradshaw",
      firstName: "Aaron",
      lastName: "Bradshaw",
      birthYear: 2005,
      hometown: "Camden, NJ",
      highSchool: "IMG Academy, Bradenton, FL",
      isFeatured: false,
      bio: "A McDonald's All-American 7-1 freshman center and DJ Wagner's high school teammate.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Memphis",
        league: "AAC",
        statusNote: "After Kentucky and Ohio State, transferred to Memphis for 2025-26 where he's having a career-best season (8.6 PPG, 4.6 RPG, 55.6% FG).",
        sourceUrl: "https://gotigersgo.com/sports/mens-basketball/roster/aaron-bradshaw/12209",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Center", yearsAtSchool: "2023-2024", statsNote: "Freshman • McDonald's All-American • 4.9 PPG" },
      careerEvents: [
        { year: 2024, title: "Transferred to Ohio State", eventType: "OTHER" },
      ],
    },
    {
      slug: "ugonna-onyenso",
      firstName: "Ugonna",
      lastName: "Onyenso",
      birthYear: 2003,
      hometown: "Nigeria",
      highSchool: "Prep school in the U.S.",
      isFeatured: false,
      bio: "A sophomore shot-blocker who continued to develop his game.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Virginia",
        league: "ACC",
        statusNote: "A Nigerian center with elite shot-blocking ability who played two seasons at Kentucky. After transferring to Kansas State (2024-25) and then Virginia (2025-26), he exploded into one of the nation's best defenders — leading all power conferences in blocks (3.0 per game), setting the ACC Tournament record with 21 blocks in 3 games (shattering a 31-year-old record), and earning All-ACC Defensive Team honors. Block percentage of 16.8% was the highest in the nation per KenPom.",
        sourceUrl: "https://www.espn.com/mens-college-basketball/player/_/id/5037878/ugonna-onyenso",
      },
      membership: { role: "PLAYER", jerseyNumber: 33, position: "Center", yearsAtSchool: "2022-2024", statsNote: "Sophomore • Elite shot-blocker" },
      careerEvents: [
        { year: 2026, title: "Set ACC Tournament blocks record at Virginia", eventType: "OTHER" },
      ],
    },
    {
      slug: "john-calipari",
      firstName: "John",
      lastName: "Calipari",
      birthYear: 1959,
      hometown: "Moon Township, PA",
      highSchool: "Moon Area High School, Moon Township, PA",
      isFeatured: true,
      bio: "His final season at Kentucky ended with a stunning first-round upset loss to Oakland, 80-76. Calipari left for Arkansas shortly after.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "University of Arkansas",
        league: "SEC",
        location: "Fayetteville, AR",
        statusNote: "Left Kentucky for Arkansas in April 2024 after 15 seasons (410-127 record, 1 title, 4 Final Fours). His final game was a stunning loss to Oakland.",
        sourceUrl: "https://en.wikipedia.org/wiki/John_Calipari",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2024", statsNote: "23-10 • Lost to Oakland 80-76 in R1 • Calipari's last game as UK coach" },
      careerEvents: [
        { year: 2024, title: "Lost to Oakland in NCAA R1; left Kentucky for Arkansas", eventType: "CAREER" },
      ],
    },
  ],
};
