import type { TeamSeed } from "./types";

export const kentuckyBasketball2023: TeamSeed = {
  slug: "kentucky-basketball-2023",
  name: "Kentucky Wildcats",
  season: "2022-2023",
  sport: "Men's Basketball",
  school: "University of Kentucky",
  conference: "SEC",
  accomplishment: "NCAA Tournament Second Round (22-12)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png",
  mascotName: "Wildcat",
  people: [
    {
      slug: "cason-wallace",
      firstName: "Cason",
      lastName: "Wallace",
      birthYear: 2004,
      hometown: "Richardson, TX",
      highSchool: "Richardson High School, Richardson, TX",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1641717.png",
      bio: "A dynamic freshman guard who was one of the top defenders in the SEC and declared for the NBA Draft after one season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Oklahoma City Thunder",
        league: "NBA",
        location: "Oklahoma City, OK",
        statusNote: "Drafted #10 overall by the Oklahoma City Thunder in 2023. Won an NBA Championship with the Thunder in 2025. Averaging 8.6 PPG in 2025-26.",
        sourceUrl: "https://www.nba.com/player/1641717/cason-wallace",
      },
      membership: { role: "PLAYER", jerseyNumber: 22, position: "Guard", yearsAtSchool: "2022-2023", statsNote: "Freshman • #10 overall pick • 2025 NBA Champion" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Richardson High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 22.5, reboundsPerGame: 3.7, assistsPerGame: 6.7 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2022-2023", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 35, pointsPerGame: 11.7, reboundsPerGame: 3.7, assistsPerGame: 3.6 },
      
        { level: "PROFESSIONAL", teamName: "Oklahoma City Thunder", season: "2023-24", yearLabel: "2023-24 (Rookie)", sortOrder: 301, gamesPlayed: 71, pointsPerGame: 6.2, reboundsPerGame: 2.3, assistsPerGame: 1.8 },
        { level: "PROFESSIONAL", teamName: "Oklahoma City Thunder", season: "2024-25", yearLabel: "2024-25 (NBA Champion)", sortOrder: 302, gamesPlayed: 80, pointsPerGame: 8.6, reboundsPerGame: 3.1, assistsPerGame: 2.7 },
        { level: "PROFESSIONAL", teamName: "Oklahoma City Thunder", season: "2025-26", yearLabel: "2025-26", sortOrder: 303, gamesPlayed: 60, pointsPerGame: 8.6, reboundsPerGame: 3.1, assistsPerGame: 2.7 },
      ],
      careerEvents: [
        { year: 2023, title: "Selected #10 overall by the Oklahoma City Thunder", eventType: "DRAFT" },
        { year: 2025, title: "Won NBA Championship with the Thunder", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "oscar-tshiebwe",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1631131.png",
      firstName: "Oscar",
      lastName: "Tshiebwe",
      birthYear: 1999,
      hometown: "Lubumbashi, DR Congo",
      highSchool: "Kennedy Catholic High School, Hermitage, PA",
      isFeatured: true,
      bio: "Returned for his senior year and won SEC Player of the Year again despite battling injuries.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward / Center",
        currentEmployer: "Utah Jazz (two-way)",
        league: "NBA / G League",
        statusNote: "Two-time National/SEC POY. Went undrafted in 2023 but slowly working his way into the NBA with the Utah Jazz.",
        sourceUrl: "https://en.wikipedia.org/wiki/Oscar_Tshiebwe",
      },
      membership: { role: "PLAYER", jerseyNumber: 34, position: "Forward / Center", yearsAtSchool: "2020-2023", statsNote: "Senior • SEC POY again • 16.5 PPG, 13.7 RPG" },
      careerEvents: [{ year: 2023, title: "Won SEC Player of the Year (2nd time)", eventType: "AWARD" }],
    },
    {
      slug: "chris-livingston",
      firstName: "Chris",
      lastName: "Livingston",
      birthYear: 2004,
      hometown: "Akron, OH",
      highSchool: "Oak Hill Academy, Mouth of Wilson, VA",
      isFeatured: false,
      bio: "A five-star freshman forward from LeBron James' hometown who declared for the NBA after one season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Capital City Go-Go (G League)",
        league: "NBA G League",
        statusNote: "Drafted #58 by the Milwaukee Bucks in 2023. Waived by the Bucks, briefly with the Cavaliers on a two-way, then waived in January 2026. Now in the G League.",
        sourceUrl: "https://en.wikipedia.org/wiki/Chris_Livingston",
      },
      membership: { role: "PLAYER", jerseyNumber: 33, position: "Forward", yearsAtSchool: "2022-2023", statsNote: "Freshman • Five-star from Akron • #58 overall pick" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Oak Hill Academy", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 14.6, reboundsPerGame: 6.9, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2022-2023", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 32, pointsPerGame: 6.4, reboundsPerGame: 3.0, assistsPerGame: 0.8 },
      
        { level: "PROFESSIONAL", teamName: "Indiana Pacers", season: "2023-24", yearLabel: "2023-24 (two-way)", sortOrder: 301, gamesPlayed: 8, pointsPerGame: 3.0, reboundsPerGame: 3.5, assistsPerGame: 0.3 },
        { level: "PROFESSIONAL", teamName: "Indiana Pacers", season: "2024-25", yearLabel: "2024-25", sortOrder: 302, gamesPlayed: 14, pointsPerGame: 7.6, reboundsPerGame: 8.7, assistsPerGame: 0.5 },
        { level: "PROFESSIONAL", teamName: "Utah Jazz (two-way)", season: "2025-26", yearLabel: "2025-26", sortOrder: 303, gamesPlayed: 10, pointsPerGame: 5.0, reboundsPerGame: 6.0, assistsPerGame: 0.3 },
      ],
      careerEvents: [
        { year: 2023, title: "Selected #58 overall by the Milwaukee Bucks", eventType: "DRAFT" },
      ],
    },
    {
      slug: "antonio-reeves",
      firstName: "Antonio",
      lastName: "Reeves",
      birthYear: 2001,
      hometown: "Chicago, IL",
      highSchool: "Simeon Career Academy, Chicago, IL",

      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1641810.png",
      isFeatured: false,
      bio: "A sharpshooting transfer from Illinois State who won SEC Co-Sixth Man of the Year and returned for a second season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Charlotte Hornets (two-way)",
        league: "NBA / G League",
        statusNote: "Won SEC Co-Sixth Man of the Year in 2023, returned as team's leading scorer in 2024. Drafted #47 in 2024 by Orlando, traded to New Orleans, then signed a two-way with the Charlotte Hornets.",
        sourceUrl: "https://www.nba.com/player/1641810/antonio-reeves",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Guard", yearsAtSchool: "2022-2024", statsNote: "Senior • Transfer from Illinois State • SEC Co-6th Man of Year" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Simeon Career Academy", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 26.9, reboundsPerGame: 2.5, assistsPerGame: 3.7 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2022-2023", yearLabel: "Senior", sortOrder: 201, gamesPlayed: 34, pointsPerGame: 14.6, reboundsPerGame: 2.5, assistsPerGame: 1.3 },
      ],
      careerEvents: [
        { year: 2023, title: "Won SEC Co-Sixth Man of the Year", eventType: "AWARD" },
        { year: 2024, title: "Selected #47 overall by the Orlando Magic", eventType: "DRAFT" },
      ],
    },
    {
      slug: "adou-thiero",
      firstName: "Adou",
      lastName: "Thiero",
      birthYear: 2004,
      hometown: "Washington, D.C.",
      highSchool: "Transferred to Kentucky from Guinea via D.C.",

      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1642876.png",
      isFeatured: false,
      bio: "A Guinean-American freshman guard/forward who would go on to follow Calipari to Arkansas and get drafted by the Lakers.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Los Angeles Lakers",
        league: "NBA",
        location: "Los Angeles, CA",
        statusNote: "After two years at Kentucky and one at Arkansas (where he led the team in scoring at 15.1 PPG), Thiero was drafted #36 overall in 2025 by the Nets (traded to Lakers). Rookie season in 2025-26.",
        sourceUrl: "https://www.nba.com/player/1642876/adou-thiero",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Guard / Forward", yearsAtSchool: "2022-2024", statsNote: "Freshman • From Guinea • Later followed Calipari to Arkansas" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Transferred to Kentucky from Guinea via D.C.", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 11.8, reboundsPerGame: 6.6, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2022-2023", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 4.5, reboundsPerGame: 2.8, assistsPerGame: 0.9 },
      ],
      careerEvents: [
        { year: 2024, title: "Transferred to Arkansas to follow Calipari", eventType: "OTHER" },
        { year: 2025, title: "Selected #36 overall by the Nets (traded to Lakers)", eventType: "DRAFT" },
      ],
    },
    {
      slug: "ugonna-onyenso",
      firstName: "Ugonna",
      lastName: "Onyenso",
      birthYear: 2003,
      hometown: "Nigeria",
      highSchool: "Prep school in the U.S.",
      isFeatured: false,
      bio: "A Nigerian freshman center with elite shot-blocking ability who would later set ACC Tournament records at Virginia.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "University of Virginia",
        league: "ACC",
        statusNote: "After two years at Kentucky, transferred to Kansas State, then Virginia. Set the ACC Tournament record for blocks (21 in 3 games including 9 in the championship). Led all power conferences in blocks (3.0 per game) in 2025-26.",
        sourceUrl: "https://www.espn.com/mens-college-basketball/player/_/id/5037878/ugonna-onyenso",
      },
      membership: { role: "PLAYER", jerseyNumber: 33, position: "Center", yearsAtSchool: "2022-2024", statsNote: "Freshman • Elite shot-blocker from Nigeria" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Prep school in the U.S.", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 8.9, reboundsPerGame: 6.4, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2022-2023", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 28, pointsPerGame: 2.6, reboundsPerGame: 2.6, assistsPerGame: 0.2 },
      ],
      careerEvents: [
        { year: 2024, title: "Transferred to Kansas State", eventType: "OTHER" },
        { year: 2026, title: "Set ACC Tournament blocks record at Virginia (21 in 3 games)", eventType: "OTHER" },
      ],
    },
    {
      slug: "sahvir-wheeler",
      firstName: "Sahvir",
      lastName: "Wheeler",
      birthYear: 2001,
      hometown: "Houston, TX",
      highSchool: "Houston Christian High School, Houston, TX",
      isFeatured: false,
      bio: "Senior point guard completing his second year at Kentucky.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Wisconsin Herd (G League)",
        league: "NBA G League",
        statusNote: "At 5-10, one of the smallest point guards in the SEC, but led the conference in assists in both of his Kentucky seasons. After graduating, transferred to Washington for a fifth year, then went undrafted in the 2024 NBA Draft. Has bounced through the G League — Maine Celtics, Memphis Hustle, and currently the Wisconsin Herd (Bucks affiliate) — trying to earn an NBA roster spot.",
        sourceUrl: "https://en.wikipedia.org/wiki/Sahvir_Wheeler",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Point Guard", yearsAtSchool: "2021-2023", statsNote: "Senior • Led SEC in assists" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Houston Christian High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 18.2, reboundsPerGame: 2.3, assistsPerGame: 9.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2022-2023", yearLabel: "Senior", sortOrder: 201, gamesPlayed: 35, pointsPerGame: 8.8, reboundsPerGame: 2.3, assistsPerGame: 5.8 },
      ],
      careerEvents: [{ year: 2023, title: "Transferred to University of Washington", eventType: "OTHER" }],
    },
    {
      slug: "jacob-toppin",
      firstName: "Jacob",
      lastName: "Toppin",
      birthYear: 2000,
      hometown: "Brooklyn, NY",
      highSchool: "Ossining High School, Ossining, NY",

      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1631210.png",
      isFeatured: false,
      bio: "Senior forward completing his Kentucky career.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Atlanta Hawks (two-way)",
        league: "NBA",
        statusNote: "Obi Toppin's younger brother who transferred from Rhode Island and became a fan favorite at Kentucky for his high-flying dunks over four seasons. Went undrafted in 2023 but signed a two-way deal with the Atlanta Hawks. Signed a new deal in July 2025 but suffered a torn labrum in his right shoulder in a G League game on November 29, 2025 — requiring season-ending surgery. Before the injury: 18.0 PPG and 10.4 RPG in 5 G League games.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jacob_Toppin",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Forward", yearsAtSchool: "2020-2023", statsNote: "Senior • Fan favorite for dunking ability" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Ossining High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 17.3, reboundsPerGame: 9.0, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2022-2023", yearLabel: "Senior", sortOrder: 201, gamesPlayed: 35, pointsPerGame: 8.2, reboundsPerGame: 4.6, assistsPerGame: 1.0 },
      
        { level: "PROFESSIONAL", teamName: "New York Knicks / Atlanta Hawks", season: "2024-25", yearLabel: "2024-25", sortOrder: 301, gamesPlayed: 40, minutesPerGame: 8.5, pointsPerGame: 3.2, reboundsPerGame: 1.8, assistsPerGame: 0.5, fieldGoalPct: 0.480 },
      ],
      careerEvents: [{ year: 2023, title: "Went undrafted; signed two-way with Hawks", eventType: "SIGNING" }],
    },
    {
      slug: "daimion-collins",
      firstName: "Daimion",
      lastName: "Collins",
      birthYear: 2003,
      hometown: "Atlanta, TX",
      highSchool: "Atlanta High School, Atlanta, TX",
      isFeatured: false,
      bio: "A long, athletic five-star forward whose Kentucky tenure was overshadowed by family tragedy. Transferred to LSU to be closer to home after his father's sudden death.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "South Florida Bulls",
        league: "American Athletic Conference",
        statusNote: "Played two seasons at Kentucky (2021-23) as a five-star prospect from Atlanta, Texas, then transferred to LSU in 2023 to be closer to home after his father's tragic passing. Spent two injury-plagued seasons with the Tigers, averaging 8.0 PPG and 4.3 RPG on 58.1% shooting as a senior. Entered the portal again in spring 2025 and committed to South Florida under coach Bryan Hodgson for his final year of eligibility.",
        sourceUrl: "https://en.wikipedia.org/wiki/Daimion_Collins",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Forward", yearsAtSchool: "2021-2023", statsNote: "Sophomore • Five-star recruit • Texas native" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Atlanta High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 22.0, reboundsPerGame: 12.0, blocksPerGame: 4.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2022-2023", yearLabel: "Sophomore", sortOrder: 201, gamesPlayed: 26, pointsPerGame: 2.4, reboundsPerGame: 1.4, blocksPerGame: 0.7 },
      ],
      careerEvents: [
        { year: 2023, title: "Transferred to LSU", eventType: "TRANSFER" },
        { year: 2025, title: "Transferred to South Florida", eventType: "TRANSFER" },
      ],
    },
    {
      slug: "cj-fredrick",
      firstName: "CJ",
      lastName: "Fredrick",
      birthYear: 2000,
      hometown: "Cincinnati, OH",
      highSchool: "Covington Catholic High School, Park Hills, KY",
      isFeatured: false,
      bio: "A sharpshooting Iowa transfer whose Kentucky career was derailed by injuries. Eventually retired from basketball after two final seasons at Cincinnati.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Basketball Player",
        statusNote: "Came to Kentucky in 2021 as one of the nation's most coveted transfers after shooting 46.6% from three at Iowa, but redshirted his first UK season with a leg injury. Averaged 6.3 PPG and shot 31.8% from three in 2022-23 amid recurring injuries before transferring to Cincinnati in April 2023, where he played two more seasons for the Bearcats. Announced his retirement from basketball in April 2025 after a seven-year college career.",
        sourceUrl: "https://www.aseaofblue.com/2025/4/10/24405583/cj-fredrick-retirement-basketball-cincinnati-bearcats-kentucky",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Guard", yearsAtSchool: "2021-2023", statsNote: "Junior • Iowa transfer • Sharpshooter" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Covington Catholic High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 22.0, assistsPerGame: 4.0 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2022-2023", yearLabel: "Junior", sortOrder: 201, gamesPlayed: 31, pointsPerGame: 6.3, threePointPct: 0.318 },
      ],
      careerEvents: [
        { year: 2023, title: "Transferred to Cincinnati", eventType: "TRANSFER" },
        { year: 2025, title: "Retired from basketball", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "lance-ware",
      firstName: "Lance",
      lastName: "Ware",
      birthYear: 2001,
      hometown: "Burlington, NJ",
      highSchool: "Camden High School, Camden, NJ",
      isFeatured: false,
      bio: "A junior big man who provided physicality and rebounding off the bench in his final Kentucky season before transferring.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "Iraklis",
        league: "Greek Heba A1",
        location: "Greece",
        statusNote: "Spent three years at Kentucky (2020-23) as a depth big before transferring to Villanova for 2023-24 and then UT Arlington for 2024-25, where he finally broke out: 13.7 PPG, 9.8 RPG, 1.6 BPG on 58.5% shooting with 11 double-doubles, earning WAC All-Defensive Team and Second Team All-WAC honors. Signed a two-year deal with Iraklis in Greece's Heba A1 league after going undrafted in 2025.",
        sourceUrl: "https://utamavs.com/news/2025/3/10/mens-basketball-mbb-lance-ware-earns-wac-all-defensive-team.aspx",
      },
      membership: { role: "PLAYER", jerseyNumber: 55, position: "Forward / Center", yearsAtSchool: "2020-2023", statsNote: "Junior • Energy big man" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Camden High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 8.3, reboundsPerGame: 6.4, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2022-2023", yearLabel: "Junior", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 2.5, reboundsPerGame: 2.7, blocksPerGame: 0.4 },
      ],
      careerEvents: [
        { year: 2023, title: "Transferred to Villanova", eventType: "TRANSFER" },
        { year: 2025, title: "Signed with Iraklis (Greece)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "brennan-canada",
      firstName: "Brennan",
      lastName: "Canada",
      birthYear: 2000,
      hometown: "Mount Sterling, KY",
      highSchool: "George Rogers Clark High School, Winchester, KY",
      isFeatured: false,
      bio: "A homegrown Kentucky walk-on forward who was placed on scholarship by John Calipari in January 2023. Beloved for his locker-room leadership across five seasons in Lexington.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Sport Leadership Graduate",
        statusNote: "Joined Kentucky as a walk-on in April 2019 after a strong career at George Rogers Clark High School (1,371 career points). John Calipari surprised him by placing him on scholarship in January 2023 in front of the team. Played five seasons total for the Wildcats, was named to the 2024 SEC Community Service Team, and earned his master's degree in sport leadership in May 2024.",
        sourceUrl: "https://ukathletics.com/sports/mbball/roster/player/brennan-canada/",
      },
      membership: { role: "PLAYER", jerseyNumber: 33, position: "Forward", yearsAtSchool: "2019-2024", statsNote: "Walk-on • Awarded scholarship January 2023" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "George Rogers Clark High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 15.0, reboundsPerGame: 9.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2022-2023", yearLabel: "Senior", sortOrder: 201, gamesPlayed: 5, pointsPerGame: 0.4 },
      ],
      careerEvents: [
        { year: 2023, title: "Awarded a scholarship by John Calipari", eventType: "OTHER" },
        { year: 2024, title: "Earned master's in sport leadership", eventType: "EDUCATION" },
      ],
    },
    {
      slug: "kareem-watkins",
      firstName: "Kareem",
      lastName: "Watkins",
      birthYear: 2002,
      hometown: "Camden, NJ",
      highSchool: "Kingsway Regional High School, Woolwich Township, NJ",
      isFeatured: false,
      bio: "A walk-on guard who is the stepson of former Memphis star Dajuan Wagner and half-brother of DJ Wagner. Spent four years at Kentucky before following Calipari to Arkansas.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "Graduate Walk-On Player",
        currentEmployer: "Arkansas Razorbacks",
        league: "SEC",
        location: "Fayetteville, AR",
        statusNote: "Walked on at Kentucky in November 2020 and appeared in 16 career games over four seasons (2020-24), including a senior-night start against Vanderbilt. Graduated from UK with a degree in finance, then followed John Calipari to Arkansas in 2024-25 as a graduate walk-on while pursuing a master's in adult and lifelong learning.",
        sourceUrl: "https://arkansasrazorbacks.com/roster/kareem-watkins/",
      },
      membership: { role: "PLAYER", jerseyNumber: 25, position: "Guard", yearsAtSchool: "2020-2024", statsNote: "Walk-on • Brother of DJ Wagner" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Kingsway Regional High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 8.7 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2022-2023", yearLabel: "Junior", sortOrder: 201, gamesPlayed: 6, pointsPerGame: 0.0 },
      ],
      careerEvents: [
        { year: 2024, title: "Followed Calipari to Arkansas as graduate walk-on", eventType: "TRANSFER" },
      ],
    },
    {
      slug: "grant-darbyshire",
      firstName: "Grant",
      lastName: "Darbyshire",
      birthYear: 2003,
      hometown: "Cincinnati, OH",
      highSchool: "Sycamore High School, Montgomery, OH",
      isFeatured: false,
      bio: "A National Merit Scholar walk-on guard who joined Kentucky in 2022. Spent three seasons with the Wildcats before transferring to Cincinnati.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Cincinnati Bearcats",
        league: "Big 12",
        statusNote: "Joined Kentucky as a walk-on freshman guard in 2022 after captaining Sycamore High School and graduating summa cum laude as a National Merit Scholar Commended student. Appeared in 6 career UK games over three seasons, including the 2024 NCAA Tournament opener vs. Troy. Multi-year SEC Honor Roll member and was inducted into the Frank G. Ham Society of Character (UK's highest athlete honor) in 2024-25. Transferred to Cincinnati in 2025 to join former UK teammate Kerr Kriisa.",
        sourceUrl: "https://www.on3.com/teams/kentucky-wildcats/news/former-kentucky-walk-on-grant-darbyshire-transfers-cincinnati/",
      },
      membership: { role: "PLAYER", jerseyNumber: 13, position: "Guard", yearsAtSchool: "2022-2025", statsNote: "Walk-on • National Merit Scholar • Frank G. Ham Society honoree" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Sycamore High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 12.0, assistsPerGame: 4.0 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2022-2023", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 1, pointsPerGame: 0.0 },
      ],
      careerEvents: [
        { year: 2025, title: "Transferred to Cincinnati", eventType: "TRANSFER" },
      ],
    },
    {
      slug: "walker-horn",
      firstName: "Walker",
      lastName: "Horn",
      birthYear: 2003,
      hometown: "Austin, TX",
      highSchool: "Westlake High School, Austin, TX",
      isFeatured: false,
      bio: "A walk-on guard and son of Northern Kentucky head coach Darrin Horn who joined Kentucky in 2022. A fan favorite who scored his first career points as a senior.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Kentucky Wildcats",
        league: "SEC",
        statusNote: "Joined Kentucky as a walk-on freshman in 2022 after a high school career split between Covington Catholic (KY) and Westlake High School in Austin, where he averaged 9.3 PPG and 5.2 APG as a senior. Son of former South Carolina and current Northern Kentucky head coach Darrin Horn. Returned to Kentucky for an additional season following the House Settlement approval in June 2025, scoring his first career points as a senior walk-on under Mark Pope.",
        sourceUrl: "https://www.aseaofblue.com/2025/6/7/24445151/walker-horn-kentucky-basketball-ncaa-house-settlement-approval",
      },
      membership: { role: "PLAYER", jerseyNumber: 22, position: "Guard", yearsAtSchool: "2022-2026", statsNote: "Walk-on • Son of coach Darrin Horn" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Westlake High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 9.3, reboundsPerGame: 2.4, assistsPerGame: 5.2 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2022-2023", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 1, pointsPerGame: 0.0 },
      ],
      careerEvents: [
        { year: 2025, title: "Returned to Kentucky after House Settlement", eventType: "OTHER" },
      ],
    },
    {
      slug: "john-calipari",
      firstName: "John",
      lastName: "Calipari",
      birthYear: 1959,
      hometown: "Moon Township, PA",
      highSchool: "Moon Area High School, Moon Township, PA",
      isFeatured: true,
      bio: "Led Kentucky to the NCAA Tournament second round.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "University of Arkansas",
        league: "SEC",
        location: "Fayetteville, AR",
        statusNote: "After 15 seasons at Kentucky (2009-2024) compiling a 410-127 record, one national championship (2012), four Final Fours, and more NBA Draft picks than any coach in history (42 first-round picks), Calipari left for Arkansas in April 2024 on a 5-year, $35M deal. In his first full season at Arkansas (2025-26), he won the SEC Tournament Championship — becoming the first men's coach to win SEC Tournament titles at multiple schools. He ranks 5th on the all-time NCAA Division I wins list with 900+ career victories.",
        sourceUrl: "https://en.wikipedia.org/wiki/John_Calipari",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2024", statsNote: "22-12 • NCAA Tournament R2" },
      careerEvents: [{ year: 2024, title: "Left Kentucky for Arkansas", eventType: "CAREER" }],
    },
  ],
};
