import type { TeamSeed } from "./types";

export const kentuckyBasketball2015: TeamSeed = {
  slug: "kentucky-basketball-2015",
  name: "Kentucky Wildcats",
  season: "2014-2015",
  sport: "Men's Basketball",
  school: "University of Kentucky",
  conference: "SEC",
  accomplishment: "Final Four (38-1) — lost to Wisconsin",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png",
  mascotName: "Wildcat",
  people: [
    {
      slug: "karl-anthony-towns",
      firstName: "Karl-Anthony",
      lastName: "Towns",
      birthYear: 1995,
      hometown: "Piscataway, NJ",
      highSchool: "St. Joseph High School, Metuchen, NJ",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1626157.png",
      bio: "The #1 overall pick in the 2015 NBA Draft and the cornerstone of Kentucky's historic 38-1 season. A 7-footer with guard skills who averaged 10.3 points and 6.7 rebounds on a team that had no real stars.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "New York Knicks",
        league: "NBA",
        location: "New York, NY",
        statusNote: "A 4-time NBA All-Star and 2016 Rookie of the Year, Towns was traded from the Minnesota Timberwolves to the New York Knicks in October 2024. In his first season in New York, he averaged 24.4 PPG and 12.8 RPG while helping lead the Knicks to the Eastern Conference Finals.",
        sourceUrl: "https://en.wikipedia.org/wiki/Karl-Anthony_Towns",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Center", yearsAtSchool: "2014-2015", statsNote: "#1 overall pick • 38-1 season", gamesPlayed: 39, pointsPerGame: 10.3, reboundsPerGame: 6.7, assistsPerGame: 1.1 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "St. Joseph High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 20.9, reboundsPerGame: 13.4 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2014-15", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 39, pointsPerGame: 10.3, reboundsPerGame: 6.7, blocksPerGame: 2.3, fieldGoalPct: 0.566 },
        { level: "PROFESSIONAL", teamName: "Minnesota Timberwolves", season: "2015-16", yearLabel: "2015-16 (ROY)", sortOrder: 301, gamesPlayed: 82, pointsPerGame: 18.3, reboundsPerGame: 10.5 },
        { level: "PROFESSIONAL", teamName: "Minnesota Timberwolves", season: "2018-19", yearLabel: "2018-19", sortOrder: 304, gamesPlayed: 77, pointsPerGame: 24.4, reboundsPerGame: 12.4 },
        { level: "PROFESSIONAL", teamName: "New York Knicks", season: "2024-25", yearLabel: "2024-25 (Knicks debut)", sortOrder: 310, gamesPlayed: 72, pointsPerGame: 24.4, reboundsPerGame: 12.8, assistsPerGame: 3.1 },
      ],
      careerEvents: [
        { year: 2015, title: "Selected #1 overall by the Minnesota Timberwolves", eventType: "DRAFT" },
        { year: 2016, title: "Won NBA Rookie of the Year (unanimous)", eventType: "AWARD" },
        { year: 2024, title: "Traded to New York Knicks", eventType: "TRADE" },
      ],
    },
    {
      slug: "devin-booker",
      firstName: "Devin",
      lastName: "Booker",
      birthYear: 1996,
      hometown: "Moss Point, MS",
      highSchool: "Moss Point High School, Moss Point, MS",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1626164.png",
      bio: "A sixth-man freshman on the 38-1 team who played only 21 minutes per game but became one of the NBA's biggest stars. One of the most underrated Kentucky players ever.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Shooting Guard",
        currentEmployer: "Phoenix Suns",
        league: "NBA",
        location: "Phoenix, AZ",
        statusNote: "A 4-time NBA All-Star, Booker is the face of the Phoenix Suns franchise. Led Phoenix to the 2021 NBA Finals and signed a 4-year, $220M supermax extension in 2024. His 70-point game in 2017 made him the youngest player in NBA history to score 70.",
        sourceUrl: "https://en.wikipedia.org/wiki/Devin_Booker",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Shooting Guard", yearsAtSchool: "2014-2015", statsNote: "38-1 season • Future NBA superstar", gamesPlayed: 38, pointsPerGame: 10.0, reboundsPerGame: 2.0, assistsPerGame: 1.1 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Moss Point High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 30.8 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2014-15", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 38, minutesPerGame: 21.5, pointsPerGame: 10.0, threePointPct: 0.411 },
        { level: "PROFESSIONAL", teamName: "Phoenix Suns", season: "2016-17", yearLabel: "2016-17 (70-pt game)", sortOrder: 302, gamesPlayed: 78, pointsPerGame: 22.1 },
        { level: "PROFESSIONAL", teamName: "Phoenix Suns", season: "2022-23", yearLabel: "2022-23", sortOrder: 308, gamesPlayed: 53, pointsPerGame: 27.8 },
      ],
      careerEvents: [
        { year: 2015, title: "Selected #13 overall by the Phoenix Suns", eventType: "DRAFT" },
        { year: 2017, title: "Scored 70 points vs Boston Celtics", eventType: "AWARD" },
        { year: 2021, title: "Reached NBA Finals with Phoenix Suns", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "willie-cauley-stein",
      firstName: "Willie",
      lastName: "Cauley-Stein",
      birthYear: 1993,
      hometown: "Spearville, KS",
      highSchool: "Olathe Northwest High School, Olathe, KS",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/626171.png",
      bio: "A 7-foot athletic big man who was the anchor of Kentucky's elite defense on the 38-1 team. Junior leader and #6 overall pick.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "Overseas / G League",
        league: "International",
        location: "Various",
        statusNote: "Selected #6 overall by the Sacramento Kings in 2015, Cauley-Stein played 8 NBA seasons with the Kings, Warriors, Mavericks, and Rockets before moving to the G League and overseas leagues. Also known for his visual art and painting.",
        sourceUrl: "https://en.wikipedia.org/wiki/Willie_Cauley-Stein",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Center", yearsAtSchool: "2012-2015", statsNote: "#6 pick • 38-1 season", gamesPlayed: 37, pointsPerGame: 8.9, reboundsPerGame: 6.4, assistsPerGame: 1.1 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2014-15", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 37, pointsPerGame: 8.9, reboundsPerGame: 6.4, blocksPerGame: 1.7 },
        { level: "PROFESSIONAL", teamName: "Sacramento Kings", season: "2015-16", yearLabel: "2015-16 (Rookie)", sortOrder: 301, gamesPlayed: 66, pointsPerGame: 7.0, reboundsPerGame: 5.3 },
      ],
      careerEvents: [
        { year: 2015, title: "Selected #6 overall by the Sacramento Kings", eventType: "DRAFT" },
      ],
    },
    {
      slug: "trey-lyles",
      firstName: "Trey",
      lastName: "Lyles",
      birthYear: 1995,
      hometown: "Saskatoon, SK, Canada",
      highSchool: "Arsenal Technical HS, Indianapolis, IN",
      bio: "A versatile 6-10 Canadian freshman who came off the bench on the 38-1 team. The #12 overall pick in 2015.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Power Forward",
        currentEmployer: "Overseas",
        league: "International",
        location: "Europe",
        statusNote: "Selected #12 overall by the Utah Jazz in 2015, Lyles played 8 NBA seasons with the Jazz, Nuggets, Spurs, Kings, and Wolves before transitioning to European basketball. Continues to play professionally abroad.",
        sourceUrl: "https://en.wikipedia.org/wiki/Trey_Lyles",
      },
      membership: { role: "PLAYER", jerseyNumber: 41, position: "Power Forward", yearsAtSchool: "2014-2015", statsNote: "#12 overall pick • 38-1 season", gamesPlayed: 39, pointsPerGame: 8.7, reboundsPerGame: 5.2, assistsPerGame: 1.1 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2014-15", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 39, pointsPerGame: 8.7, reboundsPerGame: 5.2 },
      ],
      careerEvents: [
        { year: 2015, title: "Selected #12 overall by the Utah Jazz", eventType: "DRAFT" },
      ],
    },
    {
      slug: "andrew-harrison",
      firstName: "Andrew",
      lastName: "Harrison",
      birthYear: 1994,
      hometown: "Richmond, TX",
      highSchool: "Travis High School, Richmond, TX",
      bio: "The starting point guard for two Final Four runs, Andrew is the older twin of Aaron Harrison. Selected #44 overall in the 2015 NBA Draft.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Point Guard",
        currentEmployer: "Overseas",
        league: "International",
        location: "Europe",
        statusNote: "Selected #44 by the Suns (traded to Grizzlies) in 2015, Harrison played 3 seasons for the Memphis Grizzlies before moving overseas. Has played in Germany, Italy, and the G League.",
        sourceUrl: "https://en.wikipedia.org/wiki/Andrew_Harrison_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Point Guard", yearsAtSchool: "2013-2015", statsNote: "Two Final Fours • NCAA Runner-up 2014 • 38-1 team", gamesPlayed: 39, pointsPerGame: 9.3, reboundsPerGame: 2.2, assistsPerGame: 3.6 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2014-15", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 39, pointsPerGame: 9.3, assistsPerGame: 3.6 },
      ],
      careerEvents: [
        { year: 2014, title: "NCAA Championship Game runner-up", eventType: "AWARD" },
        { year: 2015, title: "Selected #44 overall by the Phoenix Suns", eventType: "DRAFT" },
      ],
    },
    {
      slug: "aaron-harrison",
      firstName: "Aaron",
      lastName: "Harrison",
      birthYear: 1994,
      hometown: "Richmond, TX",
      highSchool: "Travis High School, Richmond, TX",
      bio: "Twin brother of Andrew, famous for hitting three clutch game-winning threes during the 2014 NCAA Tournament run. Undrafted but signed with the Hornets.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Shooting Guard",
        currentEmployer: "G League / Overseas",
        league: "International",
        location: "Various",
        statusNote: "Went undrafted in 2015 but played briefly for the Charlotte Hornets. Has spent most of his career in the G League and overseas leagues including Mexico and South America.",
        sourceUrl: "https://en.wikipedia.org/wiki/Aaron_Harrison",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Shooting Guard", yearsAtSchool: "2013-2015", statsNote: "Famous tournament threes • 38-1 team", gamesPlayed: 39, pointsPerGame: 11.0, reboundsPerGame: 2.7, assistsPerGame: 1.3 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2014-15", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 39, pointsPerGame: 11.0 },
      ],
      careerEvents: [
        { year: 2014, title: "Hit clutch tournament game-winning threes", eventType: "AWARD" },
        { year: 2015, title: "Signed with Charlotte Hornets as undrafted free agent", eventType: "SIGNING" },
      ],
    },
    {
      slug: "dakari-johnson",
      firstName: "Dakari",
      lastName: "Johnson",
      birthYear: 1995,
      hometown: "Brooklyn, NY",
      highSchool: "Montverde Academy, Montverde, FL",
      bio: "A 7-foot backup center who provided size and rebounding on the 38-1 team. Selected #48 by the Thunder in 2015.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "Overseas",
        league: "International",
        location: "Europe",
        statusNote: "Selected #48 by the OKC Thunder in 2015, Johnson played briefly in the NBA for the Thunder and Magic before moving overseas. Has played in Spain, Turkey, Israel, and other European leagues.",
        sourceUrl: "https://en.wikipedia.org/wiki/Dakari_Johnson",
      },
      membership: { role: "PLAYER", jerseyNumber: 44, position: "Center", yearsAtSchool: "2013-2015", statsNote: "Two Final Fours • 38-1 team", gamesPlayed: 39, pointsPerGame: 6.4, reboundsPerGame: 4.4, assistsPerGame: 0.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2014-15", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 39, pointsPerGame: 6.4, reboundsPerGame: 4.4 },
      ],
      careerEvents: [
        { year: 2015, title: "Selected #48 overall by Oklahoma City Thunder", eventType: "DRAFT" },
      ],
    },
    {
      slug: "tyler-ulis",
      firstName: "Tyler",
      lastName: "Ulis",
      birthYear: 1996,
      hometown: "Matteson, IL",
      highSchool: "Marian Catholic High School, Chicago Heights, IL",
      bio: "A 5-9 freshman point guard who backed up Andrew Harrison on the 38-1 team. Later became SEC Player of the Year as a sophomore.",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Coach",
        currentEmployer: "University of Arkansas",
        location: "Fayetteville, AR",
        statusNote: "After being drafted #34 by Phoenix in 2016, Ulis' NBA career was cut short by injuries. He returned to Kentucky as a student assistant and now serves as an assistant coach at Arkansas under John Calipari.",
        sourceUrl: "https://arkansasrazorbacks.com/support-staff/tyler-ulis/",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Point Guard", yearsAtSchool: "2014-2016", statsNote: "Freshman on 38-1 team", gamesPlayed: 39, pointsPerGame: 3.8, reboundsPerGame: 1.1, assistsPerGame: 3.6 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2014-15", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 39, pointsPerGame: 3.8, assistsPerGame: 3.6 },
      ],
      careerEvents: [
        { year: 2016, title: "Selected #34 overall by Phoenix Suns", eventType: "DRAFT" },
        { year: 2024, title: "Joined Arkansas coaching staff under Calipari", eventType: "CAREER" },
      ],
    },
    {
      slug: "marcus-lee",
      firstName: "Marcus",
      lastName: "Lee",
      birthYear: 1995,
      hometown: "Antioch, CA",
      highSchool: "Deer Valley High School, Antioch, CA",
      bio: "A high-flying sophomore forward who came off the bench on the 38-1 team. Later transferred to Cal for his senior year.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Overseas",
        league: "International",
        location: "Australia / Asia",
        statusNote: "After transferring to Cal from Kentucky, Lee went undrafted and has played professionally overseas, including in Australia's NBL with Melbourne United.",
        sourceUrl: "https://en.wikipedia.org/wiki/Marcus_Lee_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Power Forward", yearsAtSchool: "2013-2017", statsNote: "38-1 team", gamesPlayed: 38, pointsPerGame: 1.7, reboundsPerGame: 2.1, assistsPerGame: 0.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2014-15", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 38, pointsPerGame: 1.7, reboundsPerGame: 2.1 },
      ],
      careerEvents: [
        { year: 2017, title: "Transferred to California Golden Bears", eventType: "CAREER" },
      ],
    },
    {
      slug: "alex-poythress",
      firstName: "Alex",
      lastName: "Poythress",
      birthYear: 1993,
      hometown: "Clarksville, TN",
      highSchool: "Northeast High School, Clarksville, TN",
      bio: "A veteran forward whose season ended in December 2014 with a torn ACL — a huge blow to Kentucky's frontcourt depth.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Overseas",
        league: "International",
        location: "Europe",
        statusNote: "After graduating from Kentucky in 2016, Poythress went undrafted but had brief NBA stints with the Pacers and Pistons. Has spent most of his career overseas in France, Russia, Spain, and Turkey.",
        sourceUrl: "https://en.wikipedia.org/wiki/Alex_Poythress",
      },
      membership: { role: "PLAYER", jerseyNumber: 22, position: "Power Forward", yearsAtSchool: "2012-2016", statsNote: "38-1 team (lost season to ACL in December)", gamesPlayed: 10, pointsPerGame: 5.9, reboundsPerGame: 4.8, assistsPerGame: 0.4 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2014-15", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 10, pointsPerGame: 5.9, reboundsPerGame: 4.8 },
      ],
      careerEvents: [
        { year: 2014, title: "Suffered season-ending ACL tear in December", eventType: "CAREER" },
      ],
    },
    {
      slug: "derek-willis",
      firstName: "Derek",
      lastName: "Willis",
      birthYear: 1995,
      hometown: "Bullitt County, KY",
      highSchool: "Bullitt East High School, Mt. Washington, KY",
      bio: "A Kentucky native sophomore forward who was a rotation player on the 38-1 team. Specialized as a three-point shooter.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Overseas",
        league: "International",
        location: "Europe",
        statusNote: "Went undrafted in 2017 and has played professionally in Germany, Turkey, France, and Israel. Known as a sharpshooting big man.",
        sourceUrl: "https://en.wikipedia.org/wiki/Derek_Willis",
      },
      membership: { role: "PLAYER", jerseyNumber: 35, position: "Power Forward", yearsAtSchool: "2013-2017", statsNote: "Kentucky native • 38-1 team", gamesPlayed: 29, pointsPerGame: 1.2, reboundsPerGame: 1.0, assistsPerGame: 0.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2014-15", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 29, pointsPerGame: 1.2 },
      ],
      careerEvents: [],
    },
    {
      slug: "dominique-hawkins",
      firstName: "Dominique",
      lastName: "Hawkins",
      birthYear: 1994,
      hometown: "Richmond, KY",
      highSchool: "Madison Central High School, Richmond, KY",
      bio: "A Kentucky native walk-on turned scholarship guard. Was part of two Final Four teams.",
      status: {
        occupationType: "COACH",
        currentTitle: "Coach / Community Basketball",
        location: "Richmond, KY",
        statusNote: "The Kentucky Mr. Basketball winner from Richmond, KY earned a scholarship at UK and played on two Final Four teams. After graduating has stayed involved with Kentucky basketball in coaching and community roles.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/dominique-hawkins/",
      },
      membership: { role: "PLAYER", jerseyNumber: 25, position: "Point Guard", yearsAtSchool: "2013-2017", statsNote: "Kentucky native • 38-1 team", gamesPlayed: 24, pointsPerGame: 0.9, reboundsPerGame: 0.4, assistsPerGame: 0.3 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2014-15", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 24, pointsPerGame: 0.9 },
      ],
      careerEvents: [],
    },
    {
      slug: "tod-lanter",
      firstName: "Tod",
      lastName: "Lanter",
      birthYear: 1992,
      hometown: "Frankfort, KY",
      highSchool: "Western Hills High School, Frankfort, KY",
      bio: "A Kentucky native senior walk-on guard on the 38-1 team — part of the 'depth' corps that helped make the season historic.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Kentucky",
        statusNote: "The Frankfort native walk-on was a beloved senior on the 38-1 team. After graduation has worked professionally in Kentucky.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/tod-lanter/",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Guard", yearsAtSchool: "2011-2015", statsNote: "Senior walk-on • 38-1 team", gamesPlayed: 17, pointsPerGame: 0.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2014-15", yearLabel: "Senior (walk-on)", sortOrder: 204, gamesPlayed: 17, pointsPerGame: 0.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "ej-floreal",
      firstName: "EJ",
      lastName: "Floreal",
      birthYear: 1994,
      hometown: "Knoxville, TN",
      highSchool: "Hardin Valley Academy, Knoxville, TN",
      bio: "A walk-on forward and son of Olympic triple jumper Edrick Floreal, EJ joined the Kentucky basketball program as a walk-on while pursuing a track career. He was a scholarshipped member of the historic 38-1 team.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Track & Field Coach",
        currentEmployer: "Kentucky track program",
        location: "Lexington, KY",
        statusNote: "After his basketball career at Kentucky, Floreal followed his father's footsteps into track and field. He has worked in track coaching roles while continuing his family's athletic legacy. His father Edrick is now the head track coach at Texas.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/ej-floreal/",
      },
      membership: { role: "PLAYER", jerseyNumber: 21, position: "Forward", yearsAtSchool: "2013-2015", statsNote: "Walk-on forward • 38-1 team", gamesPlayed: 8, pointsPerGame: 0.4 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2014-15", yearLabel: "Sophomore (walk-on)", sortOrder: 202, gamesPlayed: 8, pointsPerGame: 0.4 },
      ],
      careerEvents: [],
    },
    {
      slug: "sam-malone",
      firstName: "Sam",
      lastName: "Malone",
      birthYear: 1993,
      hometown: "Ruston, LA",
      highSchool: "Ruston High School, Ruston, LA",
      bio: "Son of NBA Hall of Famer Karl Malone, Sam joined Kentucky as a walk-on guard in 2011. Played four years as a reserve before transferring briefly to Louisiana Tech for his final year. A respected teammate across multiple Kentucky tournament runs.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Owner / Operator",
        currentEmployer: "Family business ventures",
        location: "Ruston, LA",
        statusNote: "After Kentucky, Sam Malone returned to Louisiana where he has been involved with his family's various business interests. He occasionally appears at NBA events supporting his father Karl's Hall of Fame legacy.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/sam-malone/",
      },
      membership: { role: "PLAYER", jerseyNumber: 25, position: "Guard", yearsAtSchool: "2011-2015", statsNote: "Senior walk-on • son of Karl Malone", gamesPlayed: 11, pointsPerGame: 0.3 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2014-15", yearLabel: "Senior (walk-on)", sortOrder: 204, gamesPlayed: 11, pointsPerGame: 0.3 },
      ],
      careerEvents: [],
    },
    {
      slug: "brian-long",
      firstName: "Brian",
      lastName: "Long",
      birthYear: 1993,
      hometown: "Lexington, KY",
      highSchool: "Lexington Catholic High School, Lexington, KY",
      bio: "A Lexington native walk-on forward who was a four-year team member. Long was a fan favorite as a local kid living the dream of playing for his hometown Wildcats.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Business Professional",
        location: "Lexington, KY",
        statusNote: "After graduating from Kentucky, Long has remained in the Lexington area where he has worked in business roles. A popular member of the Kentucky basketball alumni community.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/brian-long/",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Forward", yearsAtSchool: "2011-2015", statsNote: "Senior walk-on • local Lexington product", gamesPlayed: 13, pointsPerGame: 0.4 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2014-15", yearLabel: "Senior (walk-on)", sortOrder: 204, gamesPlayed: 13, pointsPerGame: 0.4 },
      ],
      careerEvents: [],
    },
    {
      slug: "jonny-david",
      firstName: "Jonny",
      lastName: "David",
      birthYear: 1994,
      hometown: "Lexington, KY",
      highSchool: "Lafayette High School, Lexington, KY",
      bio: "A Lexington native walk-on guard who joined the Kentucky program in 2013. Played sparingly as a reserve during the historic 38-1 season.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Lexington, KY",
        statusNote: "After his time at Kentucky, David returned to the Lexington area in a professional capacity. Limited publicly available information about his specific post-Kentucky career.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Guard", yearsAtSchool: "2013-2016", statsNote: "Walk-on • reserve guard", gamesPlayed: 5, pointsPerGame: 0.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2014-15", yearLabel: "Sophomore (walk-on)", sortOrder: 202, gamesPlayed: 5 },
      ],
      careerEvents: [],
    },
    {
      slug: "john-calipari",
      firstName: "John",
      lastName: "Calipari",
      birthYear: 1959,
      hometown: "Moon Township, PA",
      highSchool: "Moon Area High School, Moon Township, PA",
      bio: "Coached arguably the deepest roster in recent college basketball history to a 38-1 record, only to lose to Wisconsin in the Final Four.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "University of Arkansas",
        league: "SEC",
        location: "Fayetteville, AR",
        statusNote: "Left Kentucky for Arkansas in April 2024 on a 5-year, $35M deal after 15 seasons at UK. The 38-1 season is one of the most famous 'what if' teams in college basketball history.",
        sourceUrl: "https://en.wikipedia.org/wiki/John_Calipari",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2024", statsNote: "38-1 • Final Four • Lost to Wisconsin" },
      careerEvents: [],
    },
  ],
};
