import type { TeamSeed } from "./types";

export const kentuckyBasketball2012: TeamSeed = {
  slug: "kentucky-basketball-2012",
  name: "Kentucky Wildcats",
  season: "2011-2012",
  sport: "Men's Basketball",
  school: "University of Kentucky",
  conference: "SEC",
  accomplishment: "NCAA National Champions (38-2)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png",
  mascotName: "Wildcat",
  people: [
    {
      slug: "anthony-davis",
      firstName: "Anthony",
      lastName: "Davis",
      birthYear: 1993,
      hometown: "Chicago, IL",
      highSchool: "Perspectives Charter School, Chicago, IL",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/203076.png",
      bio: "The Naismith Player of the Year and Defensive Player of the Year as a freshman, Davis led Kentucky to the 2012 national title. He scored just 6 points in the championship game but dominated with 16 rebounds, 6 blocks, 5 assists, and 3 steals.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Power Forward / Center",
        currentEmployer: "Dallas Mavericks",
        league: "NBA",
        location: "Dallas, TX",
        statusNote: "Selected #1 overall by the New Orleans Hornets in 2012, Davis is a 10-time NBA All-Star and 4-time All-NBA First Team selection. He won the 2020 NBA Championship with the Los Angeles Lakers alongside LeBron James. Traded to the Dallas Mavericks in February 2025 in the blockbuster Luka Doncic deal.",
        sourceUrl: "https://en.wikipedia.org/wiki/Anthony_Davis",
      },
      membership: { role: "PLAYER", jerseyNumber: 23, position: "Power Forward / Center", yearsAtSchool: "2011-2012", statsNote: "Naismith POY • NCAA Champion • #1 pick", gamesPlayed: 40, pointsPerGame: 14.2, reboundsPerGame: 10.4, assistsPerGame: 1.3 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Perspectives Charter School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 32.0, reboundsPerGame: 22.0 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2011-12", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 40, minutesPerGame: 32.0, pointsPerGame: 14.2, reboundsPerGame: 10.4, assistsPerGame: 1.3, blocksPerGame: 4.7, fieldGoalPct: 0.623 },
        { level: "PROFESSIONAL", teamName: "New Orleans Hornets/Pelicans", season: "2012-13", yearLabel: "2012-13 (Rookie)", sortOrder: 301, gamesPlayed: 64, pointsPerGame: 13.5, reboundsPerGame: 8.2, blocksPerGame: 1.8 },
        { level: "PROFESSIONAL", teamName: "Los Angeles Lakers", season: "2019-20", yearLabel: "2019-20 (Champion)", sortOrder: 308, gamesPlayed: 62, pointsPerGame: 26.1, reboundsPerGame: 9.3, assistsPerGame: 3.2, blocksPerGame: 2.3 },
        { level: "PROFESSIONAL", teamName: "Dallas Mavericks", season: "2024-25", yearLabel: "2024-25", sortOrder: 313, gamesPlayed: 51, pointsPerGame: 23.6, reboundsPerGame: 11.0, assistsPerGame: 3.0, blocksPerGame: 2.0 },
      ],
      careerEvents: [
        { year: 2012, title: "Won NCAA National Championship with Kentucky", eventType: "CHAMPIONSHIP" },
        { year: 2012, title: "Won Naismith Player of the Year and Defensive Player of the Year", eventType: "AWARD" },
        { year: 2012, title: "Selected #1 overall by the New Orleans Hornets", eventType: "DRAFT" },
        { year: 2020, title: "Won NBA Championship with Los Angeles Lakers", eventType: "CHAMPIONSHIP" },
        { year: 2025, title: "Traded to Dallas Mavericks in Luka Doncic blockbuster", eventType: "TRADE" },
      ],
    },
    {
      slug: "michael-kidd-gilchrist",
      firstName: "Michael",
      lastName: "Kidd-Gilchrist",
      birthYear: 1993,
      hometown: "Somerdale, NJ",
      highSchool: "St. Patrick High School, Elizabeth, NJ",
      isFeatured: true,
      bio: "A relentless defender and the emotional leader of the 2012 championship team, Kidd-Gilchrist was selected #2 overall by Charlotte just behind Anthony Davis.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NBA Player / Stuttering Advocate",
        currentEmployer: "Change & Impact Foundation",
        location: "Charlotte, NC",
        statusNote: "Played 8 NBA seasons, primarily with the Charlotte Hornets, before retiring in 2022. Since retiring, MKG has become a prominent advocate for people who stutter through his Change & Impact Foundation and has spoken openly about his own lifelong struggle with stuttering.",
        sourceUrl: "https://en.wikipedia.org/wiki/Michael_Kidd-Gilchrist",
      },
      membership: { role: "PLAYER", jerseyNumber: 14, position: "Small Forward", yearsAtSchool: "2011-2012", statsNote: "NCAA Champion • #2 pick overall", gamesPlayed: 40, pointsPerGame: 11.9, reboundsPerGame: 7.4, assistsPerGame: 1.9 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "St. Patrick High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 15.5, reboundsPerGame: 9.1 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2011-12", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 40, pointsPerGame: 11.9, reboundsPerGame: 7.4, assistsPerGame: 1.9, stealsPerGame: 1.1, fieldGoalPct: 0.491 },
        { level: "PROFESSIONAL", teamName: "Charlotte Hornets", season: "2015-16", yearLabel: "2015-16", sortOrder: 304, gamesPlayed: 7, pointsPerGame: 12.7, reboundsPerGame: 7.4 },
      ],
      careerEvents: [
        { year: 2012, title: "Won NCAA National Championship with Kentucky", eventType: "CHAMPIONSHIP" },
        { year: 2012, title: "Selected #2 overall by the Charlotte Bobcats", eventType: "DRAFT" },
        { year: 2022, title: "Retired from professional basketball", eventType: "RETIREMENT" },
        { year: 2022, title: "Founded Change & Impact Foundation for stuttering awareness", eventType: "CAREER" },
      ],
    },
    {
      slug: "terrence-jones",
      firstName: "Terrence",
      lastName: "Jones",
      birthYear: 1992,
      hometown: "Portland, OR",
      highSchool: "Jefferson High School, Portland, OR",
      bio: "A versatile 6-9 forward who scored 9 points with 7 rebounds in the championship game. Selected #18 overall by the Houston Rockets.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Overseas (various leagues)",
        league: "International",
        location: "Europe / Asia",
        statusNote: "Played 6 NBA seasons with Houston, New Orleans, Milwaukee, and Houston again before moving overseas. Has played in the Chinese CBA, Puerto Rico, and most recently in the Philippines PBA with Meralco Bolts in 2024-25.",
        sourceUrl: "https://en.wikipedia.org/wiki/Terrence_Jones",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Power Forward", yearsAtSchool: "2010-2012", statsNote: "NCAA Champion • #18 pick overall", gamesPlayed: 40, pointsPerGame: 12.3, reboundsPerGame: 7.2, assistsPerGame: 1.3 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Jefferson High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 25.5, reboundsPerGame: 10.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2010-11", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 38, pointsPerGame: 15.7, reboundsPerGame: 8.8 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2011-12", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 40, pointsPerGame: 12.3, reboundsPerGame: 7.2, blocksPerGame: 1.8, fieldGoalPct: 0.504 },
        { level: "PROFESSIONAL", teamName: "Houston Rockets", season: "2013-14", yearLabel: "2013-14", sortOrder: 302, gamesPlayed: 76, pointsPerGame: 12.1, reboundsPerGame: 6.9 },
      ],
      careerEvents: [
        { year: 2012, title: "Won NCAA National Championship with Kentucky", eventType: "CHAMPIONSHIP" },
        { year: 2012, title: "Selected #18 overall by the Houston Rockets", eventType: "DRAFT" },
      ],
    },
    {
      slug: "marquis-teague",
      firstName: "Marquis",
      lastName: "Teague",
      birthYear: 1993,
      hometown: "Indianapolis, IN",
      highSchool: "Pike High School, Indianapolis, IN",
      bio: "The starting point guard on the 2012 championship team, and younger brother of NBA veteran Jeff Teague. Picked #29 by the Chicago Bulls.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Professional Athlete",
        location: "Indianapolis, IN",
        statusNote: "Played briefly for the Chicago Bulls and Brooklyn Nets before spending several years overseas in France, Turkey, and the G League. Retired from professional basketball in the early 2020s and returned to the Indianapolis area.",
        sourceUrl: "https://en.wikipedia.org/wiki/Marquis_Teague",
      },
      membership: { role: "PLAYER", jerseyNumber: 25, position: "Point Guard", yearsAtSchool: "2011-2012", statsNote: "NCAA Champion • #29 pick overall", gamesPlayed: 40, pointsPerGame: 10.0, reboundsPerGame: 2.5, assistsPerGame: 4.8 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Pike High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 22.0, assistsPerGame: 5.0 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2011-12", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 40, pointsPerGame: 10.0, reboundsPerGame: 2.5, assistsPerGame: 4.8, fieldGoalPct: 0.410 },
      ],
      careerEvents: [
        { year: 2012, title: "Won NCAA National Championship with Kentucky", eventType: "CHAMPIONSHIP" },
        { year: 2012, title: "Selected #29 overall by the Chicago Bulls", eventType: "DRAFT" },
      ],
    },
    {
      slug: "doron-lamb",
      firstName: "Doron",
      lastName: "Lamb",
      birthYear: 1991,
      hometown: "Queens, NY",
      highSchool: "Oak Hill Academy, Mouth of Wilson, VA",
      bio: "The sharpshooting sophomore guard hit 5 threes in the championship game and scored 22 points to help clinch the title.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Professional Athlete",
        location: "New York, NY",
        statusNote: "Selected #42 by the Milwaukee Bucks in 2012. Played briefly for the Bucks and Orlando Magic before a lengthy overseas career spanning Israel, Russia, Turkey, and China. Retired from basketball and returned home to New York.",
        sourceUrl: "https://en.wikipedia.org/wiki/Doron_Lamb",
      },
      membership: { role: "PLAYER", jerseyNumber: 20, position: "Shooting Guard", yearsAtSchool: "2010-2012", statsNote: "NCAA Champion • Hit 5 threes in title game", gamesPlayed: 40, pointsPerGame: 13.7, reboundsPerGame: 2.7, assistsPerGame: 1.5 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Oak Hill Academy", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 20.0 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2011-12", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 40, pointsPerGame: 13.7, reboundsPerGame: 2.7, threePointPct: 0.468 },
      ],
      careerEvents: [
        { year: 2012, title: "Won NCAA National Championship with Kentucky", eventType: "CHAMPIONSHIP" },
        { year: 2012, title: "Selected #42 overall by the Milwaukee Bucks", eventType: "DRAFT" },
      ],
    },
    {
      slug: "darius-miller",
      firstName: "Darius",
      lastName: "Miller",
      birthYear: 1990,
      hometown: "Maysville, KY",
      highSchool: "Mason County High School, Maysville, KY",
      bio: "A Kentucky native and the only senior on the championship roster, Miller was the ultimate glue guy across four UK seasons. Selected #46 by the New Orleans Hornets.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Overseas",
        league: "International",
        location: "Europe",
        statusNote: "Played parts of 5 seasons in the NBA with the New Orleans Pelicans, interspersed with stints in Germany with Brose Bamberg where he won multiple Bundesliga titles. Continues to play professionally in Europe as a veteran leader.",
        sourceUrl: "https://en.wikipedia.org/wiki/Darius_Miller",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Small Forward", yearsAtSchool: "2008-2012", statsNote: "NCAA Champion • #46 pick overall • Kentucky native", gamesPlayed: 40, pointsPerGame: 9.9, reboundsPerGame: 2.8, assistsPerGame: 2.0 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Mason County High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 28.0 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2011-12", yearLabel: "Senior", sortOrder: 204, gamesPlayed: 40, pointsPerGame: 9.9, reboundsPerGame: 2.8, assistsPerGame: 2.0 },
      ],
      careerEvents: [
        { year: 2012, title: "Won NCAA National Championship with Kentucky", eventType: "CHAMPIONSHIP" },
        { year: 2012, title: "Selected #46 overall by the New Orleans Hornets", eventType: "DRAFT" },
      ],
    },
    {
      slug: "kyle-wiltjer",
      firstName: "Kyle",
      lastName: "Wiltjer",
      birthYear: 1992,
      hometown: "Portland, OR",
      highSchool: "Jesuit High School, Portland, OR",
      bio: "A shooting big man who came off the bench as a freshman on the championship team, Wiltjer later transferred to Gonzaga where he became WCC Player of the Year.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Overseas",
        league: "International",
        location: "Europe / Asia",
        statusNote: "After winning a title as a Kentucky freshman, Wiltjer transferred to Gonzaga and was WCC Player of the Year in 2016. Had brief NBA stints with Houston and Memphis before a long overseas career in Turkey, Israel, Russia, Spain, and Japan.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kyle_Wiltjer",
      },
      membership: { role: "PLAYER", jerseyNumber: 33, position: "Power Forward", yearsAtSchool: "2011-2013", statsNote: "NCAA Champion • Later Gonzaga star", gamesPlayed: 40, pointsPerGame: 5.0, reboundsPerGame: 1.7, assistsPerGame: 0.4 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Jesuit High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 24.5 },
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2011-12", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 40, pointsPerGame: 5.0, reboundsPerGame: 1.7 },
      ],
      careerEvents: [
        { year: 2012, title: "Won NCAA National Championship with Kentucky", eventType: "CHAMPIONSHIP" },
        { year: 2013, title: "Transferred to Gonzaga", eventType: "CAREER" },
      ],
    },
    {
      slug: "eloy-vargas",
      firstName: "Eloy",
      lastName: "Vargas",
      birthYear: 1988,
      hometown: "Bani, Dominican Republic",
      highSchool: "Notre Dame Preparatory, Fitchburg, MA",
      bio: "A junior backup center from the Dominican Republic who contributed size off the bench. Transferred from Florida for his final two seasons.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Professional Athlete",
        location: "Santo Domingo, Dominican Republic",
        statusNote: "After Kentucky, Vargas played professionally in Spain (LEB Oro), the Dominican Republic, and other Latin American leagues. Now retired and involved with Dominican basketball development.",
        sourceUrl: "https://www.basketball-reference.com/cbb/players/eloy-vargas-1.html",
      },
      membership: { role: "PLAYER", jerseyNumber: 30, position: "Center", yearsAtSchool: "2010-2013", statsNote: "NCAA Champion • Transfer from Florida", gamesPlayed: 33, pointsPerGame: 1.6, reboundsPerGame: 2.2, assistsPerGame: 0.1 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2011-12", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 33, pointsPerGame: 1.6, reboundsPerGame: 2.2 },
      ],
      careerEvents: [
        { year: 2012, title: "Won NCAA National Championship with Kentucky", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "twany-beckham",
      firstName: "Twany",
      lastName: "Beckham",
      birthYear: 1989,
      hometown: "Indianapolis, IN",
      highSchool: "North Central High School, Indianapolis, IN",
      bio: "A walk-on guard who transferred from Mississippi State, Beckham provided veteran depth on the championship roster.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Indianapolis, IN",
        statusNote: "After earning his Kentucky degree as part of the 2012 championship team, Beckham has worked in the Indianapolis area since leaving basketball. Known as a quiet leader during his time in Lexington.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/twany-beckham/",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Guard", yearsAtSchool: "2010-2012", statsNote: "NCAA Champion • Mississippi State transfer", gamesPlayed: 19, pointsPerGame: 0.8, reboundsPerGame: 0.4, assistsPerGame: 0.4 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2011-12", yearLabel: "RS Junior", sortOrder: 203, gamesPlayed: 19, pointsPerGame: 0.8 },
      ],
      careerEvents: [
        { year: 2012, title: "Won NCAA National Championship with Kentucky", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "jon-hood",
      firstName: "Jon",
      lastName: "Hood",
      birthYear: 1990,
      hometown: "Madisonville, KY",
      highSchool: "Madisonville North Hopkins HS, Madisonville, KY",
      bio: "A Kentucky native walk-on who was a beloved fan favorite. Hood missed the championship season with a knee injury but remained part of the team.",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Coach",
        currentEmployer: "Kentucky High School",
        location: "Kentucky",
        statusNote: "Missed the 2011-12 championship season with a torn ACL but was part of the team. After his playing career, Hood has coached at the high school level in Kentucky and has been involved in local basketball development.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jon_Hood",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Guard", yearsAtSchool: "2009-2014", statsNote: "NCAA Champion (redshirted year) • Kentucky native", gamesPlayed: 0 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2011-12", yearLabel: "Redshirt Junior", sortOrder: 203, gamesPlayed: 0 },
      ],
      careerEvents: [
        { year: 2012, title: "Part of NCAA Championship team (redshirted)", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "sam-malone",
      firstName: "Sam",
      lastName: "Malone",
      birthYear: 1991,
      hometown: "Louisiana",
      highSchool: "Ruston High School, Ruston, LA",
      bio: "The son of NBA Hall of Famer Karl Malone, Sam was a freshman walk-on guard on the 2012 championship team.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Louisiana",
        statusNote: "Son of NBA legend Karl Malone. After one season at Kentucky as a walk-on on the 2012 title team, Sam transferred to Louisiana Tech where his father is also involved, and later worked in business in Louisiana.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/sam-malone/",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Guard", yearsAtSchool: "2011-2012", statsNote: "Son of Karl Malone • Walk-on", gamesPlayed: 11, pointsPerGame: 0.4 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2011-12", yearLabel: "Freshman (walk-on)", sortOrder: 201, gamesPlayed: 11, pointsPerGame: 0.4 },
      ],
      careerEvents: [
        { year: 2012, title: "Won NCAA National Championship with Kentucky", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "brian-long",
      firstName: "Brian",
      lastName: "Long",
      birthYear: 1992,
      hometown: "Lexington, KY",
      highSchool: "Lexington Christian Academy, Lexington, KY",
      bio: "A local Lexington walk-on forward, Long was a beloved student-athlete who lived the dream of winning a championship at his hometown school.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Business Professional",
        location: "Lexington, KY",
        statusNote: "The Lexington native walked on at Kentucky and was part of the 2012 championship. After graduating, Long has worked in business in the Lexington area.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/brian-long/",
      },
      membership: { role: "PLAYER", jerseyNumber: 34, position: "Forward", yearsAtSchool: "2010-2014", statsNote: "NCAA Champion • Lexington native walk-on", gamesPlayed: 9, pointsPerGame: 0.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2011-12", yearLabel: "Sophomore (walk-on)", sortOrder: 202, gamesPlayed: 9 },
      ],
      careerEvents: [
        { year: 2012, title: "Won NCAA National Championship with Kentucky", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "jarrod-polson",
      firstName: "Jarrod",
      lastName: "Polson",
      birthYear: 1991,
      hometown: "Nicholasville, KY",
      highSchool: "West Jessamine High School, Nicholasville, KY",
      bio: "A Kentucky native walk-on guard who worked his way onto the court and became a four-year member of the program.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Nicholasville, KY",
        statusNote: "A Kentucky native who walked on at UK and was part of the 2012 championship team as a freshman. Polson later earned a scholarship as an upperclassman and returned to Kentucky after graduating to work in the local area.",
        sourceUrl: "https://ukathletics.com/roster/mens-basketball/jarrod-polson/",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Guard", yearsAtSchool: "2010-2014", statsNote: "NCAA Champion • Kentucky native walk-on", gamesPlayed: 12, pointsPerGame: 0.4 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2011-12", yearLabel: "Sophomore (walk-on)", sortOrder: 202, gamesPlayed: 12, pointsPerGame: 0.4 },
      ],
      careerEvents: [
        { year: 2012, title: "Won NCAA National Championship with Kentucky", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "ryan-harrow",
      firstName: "Ryan",
      lastName: "Harrow",
      birthYear: 1991,
      hometown: "Marietta, GA",
      highSchool: "Walton High School, Marietta, GA",
      bio: "A redshirt freshman point guard who transferred in from NC State and sat out the 2011-12 championship season due to NCAA transfer rules.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Professional Athlete",
        location: "Atlanta, GA",
        statusNote: "After sitting out the 2012 title season, Harrow played sparingly in 2012-13 before transferring to Georgia State where he became an All-Sun Belt selection. Played professionally overseas in Europe and Asia after college.",
        sourceUrl: "https://en.wikipedia.org/wiki/Ryan_Harrow",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Point Guard", yearsAtSchool: "2011-2013", statsNote: "NC State transfer sit-out • NCAA Champion (redshirt)", gamesPlayed: 0 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Kentucky Wildcats", season: "2011-12", yearLabel: "Redshirt Freshman (transfer sit-out)", sortOrder: 201, gamesPlayed: 0 },
      ],
      careerEvents: [
        { year: 2012, title: "Part of NCAA Championship team (redshirted)", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "john-calipari",
      firstName: "John",
      lastName: "Calipari",
      birthYear: 1959,
      hometown: "Moon Township, PA",
      highSchool: "Moon Area High School, Moon Township, PA",
      bio: "Won his only national championship in his third year at Kentucky, with arguably the most talented freshman class in modern college basketball history.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "University of Arkansas",
        league: "SEC",
        location: "Fayetteville, AR",
        statusNote: "After 15 seasons at Kentucky (2009-2024) and a 2012 national championship, Calipari left for Arkansas in April 2024 on a 5-year, $35M deal. In his first full season at Arkansas (2025-26), he won the SEC Tournament Championship.",
        sourceUrl: "https://en.wikipedia.org/wiki/John_Calipari",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2024", statsNote: "38-2 • NCAA Champions • #1 seed" },
      careerEvents: [
        { year: 2012, title: "Won NCAA National Championship with Kentucky", eventType: "CHAMPIONSHIP" },
      ],
    },
  ],
};
