import type { TeamSeed } from "./types";

export const louisvilleBasketball2019: TeamSeed = {
  slug: "louisville-basketball-2019",
  name: "Louisville Cardinals",
  season: "2018-2019",
  sport: "Men's Basketball",
  school: "University of Louisville",
  conference: "ACC",
  accomplishment: "Sweet 16 (20-14)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/97.png",
  mascotName: "Cardinal",
  people: [
    {
      slug: "jordan-nwora",
      firstName: "Jordan",
      lastName: "Nwora",
      birthYear: 1998,
      hometown: "Buffalo, NY",
      highSchool: "The Park School of Buffalo, Buffalo, NY",
      isFeatured: true,
      bio: "The sophomore forward who was Louisville's leading scorer and a first-team All-ACC selection. Son of Nigerian NBA player Alex Nwora, he led the Cardinals to the Sweet 16 in Chris Mack's first season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "Milwaukee Bucks / Overseas",
        league: "NBA / Overseas",
        location: "United States",
        statusNote: "After returning for his junior season and winning ACC Player of the Year in 2020, Nwora was selected #45 overall by the Milwaukee Bucks in 2020. He won an NBA Championship with Milwaukee in 2021 as a rookie reserve. He has played for the Bucks and in the G League, and also played for the Nigerian national team alongside his father Alex in FIBA competition.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jordan_Nwora",
      },
      membership: { role: "PLAYER", jerseyNumber: 33, position: "Forward", yearsAtSchool: "2017-2020", statsNote: "First-Team All-ACC • Future ACC POY • NBA Champion • Sweet 16", gamesPlayed: 34, pointsPerGame: 17.0, reboundsPerGame: 7.6 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Louisville Cardinals", season: "2018-19", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 34, minutesPerGame: 30.0, pointsPerGame: 17.0, reboundsPerGame: 7.6, fieldGoalPct: 0.461, threePointPct: 0.378 },
      ],
      careerEvents: [
        { year: 2019, title: "Led Louisville to Sweet 16 — named First-Team All-ACC", eventType: "AWARD" },
        { year: 2020, title: "Named ACC Player of the Year", eventType: "AWARD" },
        { year: 2020, title: "Selected #45 overall by the Milwaukee Bucks", eventType: "DRAFT" },
        { year: 2021, title: "Won NBA Championship with the Bucks as a rookie", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "steven-enoch",
      firstName: "Steven",
      lastName: "Enoch",
      birthYear: 1997,
      hometown: "Norwalk, CT",
      highSchool: "Norwalk High School, Norwalk, CT",
      bio: "A junior center who transferred from UConn and provided interior scoring. His post moves and size gave Louisville an inside presence to complement Nwora's perimeter game.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "Overseas",
        location: "Europe",
        statusNote: "After graduating from Louisville, Enoch has played professionally overseas in various European leagues. The UConn transfer who found his footing at Louisville has leveraged his size and post skills into a professional career abroad.",
        sourceUrl: "https://gocards.com/sports/mens-basketball/roster/steven-enoch/",
      },
      membership: { role: "PLAYER", jerseyNumber: 23, position: "Center", yearsAtSchool: "2017-2020", statsNote: "UConn transfer • Interior scorer • Sweet 16", gamesPlayed: 34, pointsPerGame: 9.4, reboundsPerGame: 5.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Louisville Cardinals", season: "2018-19", yearLabel: "Junior (transfer)", sortOrder: 203, gamesPlayed: 34, minutesPerGame: 20.0, pointsPerGame: 9.4, reboundsPerGame: 5.2, fieldGoalPct: 0.540 },
      ],
      careerEvents: [],
    },
    {
      slug: "christen-cunningham",
      firstName: "Christen",
      lastName: "Cunningham",
      birthYear: 1996,
      hometown: "Oakland, CA",
      highSchool: "Bishop O'Dowd High School, Oakland, CA",
      bio: "A graduate transfer point guard from Samford who provided veteran leadership and playmaking in Chris Mack's first year. His steady hand running the offense stabilized the transition from Pitino's system.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Professional",
        location: "California",
        statusNote: "After his one year at Louisville, Cunningham played professionally overseas briefly before transitioning to a career off the court. His graduate transfer season was a key piece of Mack's rebuilding year.",
        sourceUrl: "https://gocards.com/sports/mens-basketball/roster/christen-cunningham/",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Point Guard", yearsAtSchool: "2018-2019", statsNote: "Samford grad transfer • Floor general • Sweet 16", gamesPlayed: 34, pointsPerGame: 8.5, reboundsPerGame: 2.0, assistsPerGame: 4.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Louisville Cardinals", season: "2018-19", yearLabel: "Senior (grad transfer from Samford)", sortOrder: 205, gamesPlayed: 34, minutesPerGame: 30.0, pointsPerGame: 8.5, assistsPerGame: 4.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "dwayne-sutton",
      firstName: "Dwayne",
      lastName: "Sutton",
      birthYear: 1996,
      hometown: "Louisville, KY",
      highSchool: "Waggener High School, Louisville, KY",
      bio: "A junior forward and local Louisville product who provided toughness, rebounding, and three-point shooting. His hometown connection made him a fan favorite at the KFC Yum! Center.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "Overseas",
        location: "Europe",
        statusNote: "After four years at Louisville, Sutton played professionally overseas in Europe. The local Louisville product contributed to the Sweet 16 run with his versatile play on both ends of the court.",
        sourceUrl: "https://gocards.com/sports/mens-basketball/roster/dwayne-sutton/",
      },
      membership: { role: "PLAYER", jerseyNumber: 24, position: "Forward", yearsAtSchool: "2016-2020", statsNote: "Junior • Local Louisville product • Glue guy • Sweet 16", gamesPlayed: 34, pointsPerGame: 8.0, reboundsPerGame: 6.0 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Louisville Cardinals", season: "2018-19", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 34, minutesPerGame: 26.0, pointsPerGame: 8.0, reboundsPerGame: 6.0, threePointPct: 0.360 },
      ],
      careerEvents: [],
    },
    {
      slug: "chris-mack",
      firstName: "Chris",
      lastName: "Mack",
      birthYear: 1969,
      hometown: "Cleveland, OH",
      highSchool: "Padua Franciscan High School, Parma, OH",
      isFeatured: true,
      bio: "Led Louisville to the Sweet 16 in his first season as head coach, bringing stability to a program in turmoil after the Pitino scandal. Previously built Xavier into a perennial top-25 program.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "College program",
        location: "United States",
        statusNote: "Chris Mack coached Louisville for 4 seasons (2018-2022) before parting ways amid program dysfunction. He reached the Sweet 16 in year one (2019) but the program declined afterward. Before Louisville, he was incredibly successful at Xavier (2009-2018), compiling a 215-97 record with 9 consecutive NCAA Tournament appearances. He is widely regarded as one of the best mid-major coaches of his era and has been mentioned for multiple P5 openings since leaving Louisville.",
        sourceUrl: "https://en.wikipedia.org/wiki/Chris_Mack_(basketball)",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2018-2022", statsNote: "Sweet 16 in Year 1 • Former Xavier HC (215-97)" },
      seasonStats: [
        { level: "COACHING", teamName: "Louisville Cardinals", season: "2018-19", yearLabel: "2018-19", sortOrder: 201, wins: 20, losses: 14, tournamentResult: "Sweet 16" },
      ],
      careerEvents: [
        { year: 2018, title: "Named Louisville head coach after Pitino scandal", eventType: "CAREER_CHANGE" },
        { year: 2022, title: "Parted ways with Louisville by mutual agreement", eventType: "CAREER_CHANGE" },
      ],
    },
  ],
};
