import type { TeamSeed } from "./types";

export const miamiBasketball2023: TeamSeed = {
  slug: "miami-basketball-2023",
  name: "Miami Hurricanes",
  season: "2022-2023",
  sport: "Men's Basketball",
  school: "University of Miami",
  conference: "ACC",
  accomplishment: "Final Four (29-8) — first in program history",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png",
  mascotName: "Hurricane",
  people: [
    {
      slug: "isaiah-wong",
      firstName: "Isaiah",
      lastName: "Wong",
      birthYear: 2001,
      hometown: "Piscataway, NJ",
      highSchool: "Piscataway Township High School, Piscataway, NJ",
      isFeatured: true,
      bio: "The senior guard and 2022-23 ACC Player of the Year who was the driving force behind Miami's first-ever Final Four. His scoring ability and clutch shot-making made him the most dangerous player in the ACC that season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        league: "G League / NBA",
        location: "United States",
        statusNote: "Selected #55 overall by the Indiana Pacers in the 2023 NBA Draft, Wong has bounced between the NBA and G League. He signed a two-way contract with the Charlotte Hornets in December 2024 but was waived in February 2025. He previously had a stint with the Utah Jazz organization and their G League affiliate, the Salt Lake City Stars. Wong continues to pursue his NBA dream, known for his scoring versatility and mid-range game that made him the ACC's best player in 2022-23.",
        sourceUrl: "https://en.wikipedia.org/wiki/Isaiah_Wong",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Shooting Guard", yearsAtSchool: "2019-2023", statsNote: "ACC Player of the Year • First Final Four in Miami history", gamesPlayed: 37, pointsPerGame: 15.3, reboundsPerGame: 4.3, assistsPerGame: 3.4 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Miami Hurricanes", season: "2022-23", yearLabel: "Senior", sortOrder: 204, gamesPlayed: 37, minutesPerGame: 34.2, pointsPerGame: 15.3, reboundsPerGame: 4.3, assistsPerGame: 3.4, stealsPerGame: 1.1, fieldGoalPct: 0.441, threePointPct: 0.321 },
      ],
      careerEvents: [
        { year: 2023, title: "Named ACC Player of the Year", eventType: "AWARD" },
        { year: 2023, title: "Led Miami to first Final Four in program history", eventType: "MILESTONE" },
        { year: 2023, title: "Selected #55 overall by the Indiana Pacers", eventType: "DRAFT", month: 6, day: 22 },
      ],
    },
    {
      slug: "jordan-miller",
      firstName: "Jordan",
      lastName: "Miller",
      birthYear: 2000,
      hometown: "Middleburg, VA",
      highSchool: "Middleburg Academy, Middleburg, VA",
      bio: "The senior forward who transferred from George Mason and became Miami's most versatile player during the Final Four run. His ability to guard multiple positions and score in transition was vital.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "G League / Overseas",
        location: "United States",
        statusNote: "After going undrafted in the 2023 NBA Draft, Miller has played in the G League and overseas. His size and versatility (6'7\" wing who can defend and score) made him a valued college player, and he continues to pursue professional basketball opportunities. His transfer from George Mason to Miami was one of the most impactful portal moves of the 2021 cycle.",
        sourceUrl: "https://miamihurricanes.com/roster/jordan-miller/",
      },
      membership: { role: "PLAYER", jerseyNumber: 11, position: "Small Forward", yearsAtSchool: "2021-2023", statsNote: "George Mason transfer • Versatile wing • Final Four", gamesPlayed: 37, pointsPerGame: 14.0, reboundsPerGame: 6.3, assistsPerGame: 2.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Miami Hurricanes", season: "2022-23", yearLabel: "Senior (transfer)", sortOrder: 204, gamesPlayed: 37, minutesPerGame: 33.0, pointsPerGame: 14.0, reboundsPerGame: 6.3, assistsPerGame: 2.2, fieldGoalPct: 0.478 },
      ],
      careerEvents: [
        { year: 2023, title: "Helped Miami reach first Final Four in program history", eventType: "MILESTONE" },
      ],
    },
    {
      slug: "nijel-pack",
      firstName: "Nijel",
      lastName: "Pack",
      birthYear: 2001,
      hometown: "Indianapolis, IN",
      highSchool: "Lawrence Central High School, Indianapolis, IN",
      isFeatured: true,
      bio: "The sophomore transfer from Kansas State whose arrival was one of the most high-profile NIL deals in college basketball — reportedly including a $400K package and a car for his girlfriend. His shooting and playmaking elevated Miami into a national contender.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Oklahoma Sooners",
        location: "Norman, OK",
        statusNote: "Pack's time at Miami was plagued by injuries — he missed 75% of the 2023-24 and 2024-25 seasons. After playing just 9 games in 2024-25, he entered the transfer portal and committed to Oklahoma for his final season of eligibility, receiving a medical redshirt. His move from K-State to Miami was one of the landmark NIL-era transfers, and his journey to Oklahoma represents his third school in five years. When healthy, he remains one of the most talented guards in college basketball.",
        sourceUrl: "https://en.wikipedia.org/wiki/Nijel_Pack",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Point Guard", yearsAtSchool: "2022-2025", statsNote: "K-State transfer • Landmark NIL deal • Final Four", gamesPlayed: 37, pointsPerGame: 12.4, reboundsPerGame: 3.4, assistsPerGame: 3.0 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Miami Hurricanes", season: "2022-23", yearLabel: "Sophomore (transfer from K-State)", sortOrder: 202, gamesPlayed: 37, minutesPerGame: 31.0, pointsPerGame: 12.4, reboundsPerGame: 3.4, assistsPerGame: 3.0, threePointPct: 0.381 },
      ],
      careerEvents: [
        { year: 2022, title: "Transferred to Miami in landmark NIL deal", eventType: "SIGNING" },
        { year: 2023, title: "Helped Miami reach first Final Four in program history", eventType: "MILESTONE" },
        { year: 2025, title: "Transferred to Oklahoma for final season", eventType: "SIGNING" },
      ],
    },
    {
      slug: "norchad-omier",
      firstName: "Norchad",
      lastName: "Omier",
      birthYear: 2001,
      hometown: "Bluefields, Nicaragua",
      highSchool: "Bluefields, Nicaragua",
      bio: "The junior forward from Nicaragua — one of the few Nicaraguan-born players in D1 history — who transferred from Arkansas State and became Miami's most ferocious rebounder. His energy and motor transformed Miami's frontcourt.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "NBA / G League",
        location: "United States",
        statusNote: "After the Final Four run, Omier transferred to Baylor for the 2023-24 season and became the Big 12 Newcomer of the Year. He was selected in the 2024 NBA Draft and is pursuing his NBA career. Born in Bluefields, Nicaragua, Omier's path from Central America to the Final Four is one of the most unique stories in recent college basketball. He represents the Nicaraguan national team in FIBA competition.",
        sourceUrl: "https://en.wikipedia.org/wiki/Norchad_Omier",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Power Forward", yearsAtSchool: "2022-2023", statsNote: "Nicaragua native • Arkansas State transfer • Motor and rebounding • Final Four", gamesPlayed: 37, pointsPerGame: 9.8, reboundsPerGame: 7.3 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Miami Hurricanes", season: "2022-23", yearLabel: "Junior (transfer)", sortOrder: 203, gamesPlayed: 37, minutesPerGame: 25.0, pointsPerGame: 9.8, reboundsPerGame: 7.3, fieldGoalPct: 0.551 },
      ],
      careerEvents: [
        { year: 2023, title: "Helped Miami reach first Final Four in program history", eventType: "MILESTONE" },
        { year: 2024, title: "Named Big 12 Newcomer of the Year at Baylor", eventType: "AWARD" },
        { year: 2024, title: "Selected in the 2024 NBA Draft", eventType: "DRAFT" },
      ],
    },
    {
      slug: "wooga-poplar",
      firstName: "Wooga",
      lastName: "Poplar",
      birthYear: 2002,
      hometown: "Philadelphia, PA",
      highSchool: "Overbrook High School, Philadelphia, PA",
      bio: "A sophomore guard whose perimeter shooting and defense provided key contributions during the Final Four run. He emerged as a reliable rotation player with growing confidence.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        location: "United States",
        statusNote: "Poplar returned to Miami for additional seasons after the Final Four, continuing to develop as a key backcourt player. He has been an important piece of the Hurricanes program in the post-Final Four era.",
        sourceUrl: "https://miamihurricanes.com/roster/wooga-poplar/",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Guard", yearsAtSchool: "2021-present", statsNote: "Sophomore contributor • Perimeter shooter • Final Four", gamesPlayed: 34, pointsPerGame: 5.6, reboundsPerGame: 2.1 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Miami Hurricanes", season: "2022-23", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 34, minutesPerGame: 18.0, pointsPerGame: 5.6, reboundsPerGame: 2.1, threePointPct: 0.370 },
      ],
      careerEvents: [
        { year: 2023, title: "Reached Final Four with Miami", eventType: "MILESTONE" },
      ],
    },
    {
      slug: "jim-larranaga",
      firstName: "Jim",
      lastName: "Larranaga",
      birthYear: 1949,
      hometown: "Bronx, NY",
      highSchool: "Archbishop Molloy High School, Queens, NY",
      isFeatured: true,
      bio: "The veteran head coach who led Miami to their first-ever Final Four at age 73 — matching his 2006 miracle run at George Mason as an 11-seed Final Four team. One of only two coaches to take a mid-major and a power conference team to the Final Four.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Head Coach Emeritus",
        currentEmployer: "University of Miami (Emeritus)",
        location: "Coral Gables, FL",
        statusNote: "Jim Larranaga retired after the 2023-24 season after 11 years at Miami, compiling a 215-149 record and leading the Hurricanes to their first-ever Final Four in 2023. Before Miami, he coached George Mason to a stunning Final Four appearance as an 11-seed in 2006 — making him one of only two coaches to take both a mid-major and a power conference team to the Final Four. Over his 40+ year head coaching career at five different schools, Larranaga built a reputation as one of the best culture-builders and player developers in the sport. He was succeeded by Jim Larrañaga's longtime assistant, Mario Cristobal... no — he was succeeded by a new coaching search.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jim_Larra%C3%B1aga",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2011-2024", statsNote: "First Final Four in Miami history • Also 2006 George Mason Final Four" },
      seasonStats: [
        { level: "COACHING", teamName: "Miami Hurricanes", season: "2022-23", yearLabel: "2022-23", sortOrder: 213, wins: 29, losses: 8, tournamentResult: "Final Four (first in program history)" },
      ],
      careerEvents: [
        { year: 2006, title: "Led 11-seed George Mason to Final Four", eventType: "MILESTONE" },
        { year: 2023, title: "Led Miami to first Final Four in program history at age 73", eventType: "MILESTONE" },
        { year: 2024, title: "Retired from coaching after 40+ year career", eventType: "RETIREMENT" },
      ],
    },
  ],
};
