import type { TeamSeed } from "./types";

export const montverdeAcademy2020: TeamSeed = {
  slug: "montverde-academy-2020",
  name: "Montverde Academy Eagles",
  season: "2019-2020",
  sport: "Boys Basketball",
  school: "Montverde Academy",
  accomplishment: "GEICO Nationals Champions (25-0)",
  logoUrl: undefined,
  mascotName: "Eagle",
  people: [
    // ── Batch 1: NBA Stars ──────────────────────────────────────────────────
    {
      slug: "cade-cunningham",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1630595.png",
      firstName: "Cade",
      lastName: "Cunningham",
      birthYear: 2001,
      hometown: "Arlington, TX",
      highSchool: "Bowie High School, Arlington, TX (transferred to Montverde Academy)",
      isFeatured: true,
      bio: "The consensus #1 player in the 2020 class who led Montverde to an undefeated season. Cunningham was a McDonald's All-American and Naismith Prep Player of the Year before heading to Oklahoma State.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Detroit Pistons",
        league: "NBA",
        location: "Detroit, MI",
        statusNote:
          "Selected #1 overall by the Detroit Pistons in the 2021 NBA Draft after one season at Oklahoma State. Cunningham has blossomed into an All-Star, averaging 24.5 points, 5.6 rebounds, and 9.9 assists per game in 2025-26. He made history with the first-ever 45+ point, 10+ rebound, 10+ assist, 5+ steal game in NBA history. Named an All-Star starter for the first time in January 2026, he has led the Pistons to their first Central Division title since 2008. Currently rehabbing a lung issue but expected back for the 2026 playoffs.",
        sourceUrl: "https://en.wikipedia.org/wiki/Cade_Cunningham",
      },
      membership: {
        role: "PLAYER",
        position: "Point Guard / Shooting Guard",
        yearsAtSchool: "2019-2020",
        statsNote: "Naismith Prep Player of the Year • McDonald's All-American • Led 25-0 season",
      },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Montverde Academy Eagles", season: "2019-2020", yearLabel: "Senior", sortOrder: 201, gamesPlayed: 25, pointsPerGame: 24.0, reboundsPerGame: 7.5, assistsPerGame: 4.0 },
      ],
      careerEvents: [
        { year: 2020, title: "Named Naismith Prep Player of the Year", eventType: "AWARD" },
        { year: 2021, title: "Selected #1 overall by the Detroit Pistons", eventType: "DRAFT" },
        { year: 2025, title: "Named NBA All-Star for the first time", eventType: "AWARD" },
        { year: 2026, title: "Named All-Star starter; led Pistons to Central Division title", eventType: "AWARD" },
      ],
    },
    {
      slug: "scottie-barnes",
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1630567.png",
      firstName: "Scottie",
      lastName: "Barnes",
      birthYear: 2001,
      hometown: "West Palm Beach, FL",
      highSchool: "Cardinal Newman High School, West Palm Beach, FL (transferred to Montverde Academy)",
      isFeatured: true,
      bio: "A uniquely versatile 6'7\" forward who could play every position. Barnes was a McDonald's All-American and five-star recruit who chose Florida State before becoming a top-5 NBA pick.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward-Guard",
        currentEmployer: "Toronto Raptors",
        league: "NBA",
        location: "Toronto, ON",
        statusNote:
          "Selected #4 overall by the Toronto Raptors in the 2021 NBA Draft, Barnes won the 2022 NBA Rookie of the Year award. He has developed into a franchise cornerstone, averaging 19.3 points, 8.3 rebounds, 5.5 assists, 1.6 blocks, and 1.3 steals in 2025-26 while shooting a career-best 50.5% from the field. He recorded a historic triple-double of 23 points, 25 rebounds, and 10 assists against Golden State and was named to his second All-Star team in 2026.",
        sourceUrl: "https://en.wikipedia.org/wiki/Scottie_Barnes",
      },
      membership: {
        role: "PLAYER",
        position: "Small Forward / Power Forward",
        yearsAtSchool: "2018-2020",
        statsNote: "McDonald's All-American • Five-star recruit • Ultimate versatile playmaker",
      },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Montverde Academy Eagles", season: "2019-2020", yearLabel: "Senior", sortOrder: 201, gamesPlayed: 25, pointsPerGame: 16.0, reboundsPerGame: 8.0, assistsPerGame: 5.5 },
      ],
      careerEvents: [
        { year: 2021, title: "Selected #4 overall by the Toronto Raptors", eventType: "DRAFT" },
        { year: 2022, title: "Won NBA Rookie of the Year", eventType: "AWARD" },
        { year: 2025, title: "Named NBA All-Star for the first time", eventType: "AWARD" },
        { year: 2026, title: "Second All-Star selection; posted 23-25-10 triple-double", eventType: "AWARD" },
      ],
    },
    {
      slug: "dayron-sharpe",
      firstName: "Day'Ron",
      lastName: "Sharpe",
      birthYear: 2001,
      hometown: "Greenville, NC",
      highSchool: "South Central High School, Winterville, NC (transferred to Montverde Academy)",

      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1630549.png",
      isFeatured: false,
      bio: "A physically imposing center who anchored Montverde's frontcourt. Sharpe was a McDonald's All-American who chose North Carolina before being drafted into the NBA.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        currentEmployer: "Brooklyn Nets",
        league: "NBA",
        location: "Brooklyn, NY",
        statusNote:
          "Selected 29th overall by the Phoenix Suns in the 2021 NBA Draft and immediately traded to the Brooklyn Nets. Sharpe has developed into a reliable rotation center, averaging 8.7 points, 6.7 rebounds, 2.3 assists, and 1.1 steals in 62 games during the 2025-26 season on a one-year, $6.25 million deal. His season was cut short by thumb surgery in March 2026.",
        sourceUrl: "https://www.basketball-reference.com/players/s/sharpda01.html",
      },
      membership: {
        role: "PLAYER",
        position: "Center",
        yearsAtSchool: "2019-2020",
        statsNote: "McDonald's All-American • Dominant rebounder and rim protector",
      },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Montverde Academy Eagles", season: "2019-2020", yearLabel: "Senior", sortOrder: 201, gamesPlayed: 25, pointsPerGame: 12.5, reboundsPerGame: 9.0, assistsPerGame: 1.0 },
      ],
      careerEvents: [
        { year: 2021, title: "Selected #29 overall by the Suns (traded to Nets)", eventType: "DRAFT" },
        { year: 2025, title: "Signed one-year, $6.25M deal with Brooklyn Nets", eventType: "SIGNING" },
      ],
    },
    {
      slug: "moses-moody",
      firstName: "Moses",
      lastName: "Moody",
      birthYear: 2002,
      hometown: "Little Rock, AR",
      highSchool: "North Little Rock High School, North Little Rock, AR (transferred to Montverde Academy)",

      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1630541.png",
      isFeatured: false,
      bio: "A silky-smooth shooting guard with an NBA-ready game from day one. Moody was a five-star recruit and McDonald's All-American who spent one year at Arkansas before going pro.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Golden State Warriors",
        league: "NBA",
        location: "San Francisco, CA",
        statusNote:
          "Selected 14th overall by the Golden State Warriors in the 2021 NBA Draft, Moody won an NBA championship as a rookie in 2022. In the 2025-26 season, he broke out with career-high averages of 12.1 points, 3.3 rebounds, and 1.6 assists while shooting 40.1% from three-point range in 60 games. Unfortunately, he suffered a torn patellar tendon in his left knee requiring season-ending surgery, though a full recovery is expected.",
        sourceUrl: "https://en.wikipedia.org/wiki/Moses_Moody",
      },
      membership: {
        role: "PLAYER",
        position: "Shooting Guard / Small Forward",
        yearsAtSchool: "2019-2020",
        statsNote: "McDonald's All-American • Five-star recruit • Elite shooter",
      },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Montverde Academy Eagles", season: "2019-2020", yearLabel: "Junior", sortOrder: 201, gamesPlayed: 25, pointsPerGame: 14.0, reboundsPerGame: 5.5, assistsPerGame: 1.5 },
      ],
      careerEvents: [
        { year: 2021, title: "Selected #14 overall by the Golden State Warriors", eventType: "DRAFT" },
        { year: 2022, title: "Won NBA Championship with the Warriors as a rookie", eventType: "CHAMPIONSHIP" },
        { year: 2026, title: "Career-best season (12.1 PPG, 40.1% 3PT) cut short by torn patellar tendon", eventType: "INJURY" },
      ],
    },
    {
      slug: "caleb-houstan",
      firstName: "Caleb",
      lastName: "Houstan",
      birthYear: 2003,
      hometown: "Mississauga, ON, Canada",
      highSchool: "Transferred to Montverde Academy from Canada",

      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1631216.png",
      isFeatured: false,
      bio: "A talented Canadian shooting guard who was one of the top international recruits in the 2021 class. Houstan spent two years at Montverde before heading to Michigan.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Atlanta Hawks",
        league: "NBA",
        location: "Atlanta, GA",
        statusNote:
          "Selected 32nd overall by the Orlando Magic in the 2022 NBA Draft after one year at Michigan. After two seasons in Orlando, Houstan signed with the Atlanta Hawks in August 2025. He began on a two-way contract before being converted to a standard deal in February 2026, earning a more permanent NBA roster spot with the Hawks.",
        sourceUrl: "https://en.wikipedia.org/wiki/Caleb_Houstan",
      },
      membership: {
        role: "PLAYER",
        position: "Shooting Guard / Small Forward",
        yearsAtSchool: "2019-2021",
        statsNote: "Top international recruit • Elite perimeter shooter",
      },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Montverde Academy Eagles", season: "2019-2020", yearLabel: "Junior", sortOrder: 201, gamesPlayed: 25, pointsPerGame: 10.0, reboundsPerGame: 4.0, assistsPerGame: 1.0 },
      ],
      careerEvents: [
        { year: 2022, title: "Selected #32 overall by the Orlando Magic", eventType: "DRAFT" },
        { year: 2025, title: "Signed with the Atlanta Hawks", eventType: "SIGNING" },
        { year: 2026, title: "Two-way contract converted to standard NBA deal", eventType: "SIGNING" },
      ],
    },
    // ── Batch 2: More Players & Coach ────────────────────────────────────────
    {
      slug: "dariq-whitehead",
      firstName: "Dariq",
      lastName: "Whitehead",
      birthYear: 2003,
      hometown: "Newark, NJ",
      highSchool: "University High School, Newark, NJ (transferred to Montverde Academy)",

      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1641727.png",
      isFeatured: false,
      bio: "A long, athletic wing who was a five-star recruit and McDonald's All-American in 2022. Whitehead spent three years at Montverde before playing one season at Duke.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard-Forward",
        currentEmployer: "Oklahoma City Blue (G League)",
        league: "NBA G League",
        location: "Oklahoma City, OK",
        statusNote:
          "Selected 31st overall by the Indiana Pacers in the 2023 NBA Draft and traded to the Brooklyn Nets. After two seasons with the Nets, Whitehead was waived in October 2025. He signed an Exhibit 10 deal with the Oklahoma City Thunder and is currently playing for their G League affiliate, the Oklahoma City Blue, working to earn another NBA roster spot.",
        sourceUrl: "https://en.wikipedia.org/wiki/Dariq_Whitehead",
      },
      membership: {
        role: "PLAYER",
        position: "Shooting Guard / Small Forward",
        yearsAtSchool: "2019-2022",
        statsNote: "McDonald's All-American (2022) • Five-star recruit",
      },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Montverde Academy Eagles", season: "2019-2020", yearLabel: "Sophomore", sortOrder: 201, gamesPlayed: 25, pointsPerGame: 8.0, reboundsPerGame: 3.5, assistsPerGame: 1.0 },
      ],
      careerEvents: [
        { year: 2023, title: "Selected #31 overall by the Pacers (traded to Nets)", eventType: "DRAFT" },
        { year: 2025, title: "Waived by the Brooklyn Nets", eventType: "OTHER" },
        { year: 2025, title: "Joined Oklahoma City Blue (G League)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "langston-love",
      firstName: "Langston",
      lastName: "Love",
      birthYear: 2002,
      hometown: "Houston, TX",
      highSchool: "Westfield High School, Houston, TX (transferred to Montverde Academy)",
      isFeatured: false,
      bio: "A dynamic guard who was a five-star recruit in the 2021 class. Love was a key contributor on Montverde's 2019-20 team before committing to Baylor.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Georgetown University",
        league: "Big East Conference",
        location: "Washington, D.C.",
        statusNote:
          "After three seasons at Baylor averaging 8.9 points per game as a junior, Love transferred to Georgetown for the 2025-26 season. He is playing as a senior guard for the Hoyas, averaging 3.4 points and 1.8 rebounds per game. His college career has been impacted by injuries, but he continues to compete at the Division I level.",
        sourceUrl: "https://en.wikipedia.org/wiki/Langston_Love",
      },
      membership: {
        role: "PLAYER",
        position: "Shooting Guard",
        yearsAtSchool: "2019-2021",
        statsNote: "Five-star recruit • McDonald's All-American nominee",
      },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Montverde Academy Eagles", season: "2019-2020", yearLabel: "Junior", sortOrder: 201, gamesPlayed: 25, pointsPerGame: 11.0, reboundsPerGame: 3.0, assistsPerGame: 2.0 },
      ],
      careerEvents: [
        { year: 2021, title: "Enrolled at Baylor University", eventType: "CAREER" },
        { year: 2025, title: "Transferred to Georgetown University", eventType: "CAREER" },
      ],
    },
    {
      slug: "zeb-jackson",
      firstName: "Zeb",
      lastName: "Jackson",
      birthYear: 2001,
      hometown: "Maumee, OH",
      highSchool: "Maumee High School, Maumee, OH (transferred to Montverde Academy)",
      isFeatured: false,
      bio: "A skilled point guard who was a four-star recruit in the 2020 class. Jackson was a steady floor general on the 2019-20 squad.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Point Guard",
        currentEmployer: "Spirou Basket Charleroi",
        league: "BNXT League (Belgium)",
        location: "Charleroi, Belgium",
        statusNote:
          "After playing college basketball at Michigan (2020-23) and transferring to VCU (2023-25), Jackson went overseas to play for Spirou Basket Charleroi in Belgium's BNXT League. He has shown flashes of brilliance, including a 35-point, 10-assist performance in December 2025 against Union Mons-Hainaut. He is establishing himself as a key player in European basketball.",
        sourceUrl: "https://www.proballers.com/basketball/player/259500/zeb-jackson",
      },
      membership: {
        role: "PLAYER",
        position: "Point Guard",
        yearsAtSchool: "2019-2020",
        statsNote: "Four-star recruit • Floor general and facilitator",
      },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Montverde Academy Eagles", season: "2019-2020", yearLabel: "Senior", sortOrder: 201, gamesPlayed: 25, pointsPerGame: 8.5, reboundsPerGame: 2.5, assistsPerGame: 3.5 },
      ],
      careerEvents: [
        { year: 2020, title: "Enrolled at University of Michigan", eventType: "CAREER" },
        { year: 2023, title: "Transferred to VCU", eventType: "CAREER" },
        { year: 2025, title: "Signed with Spirou Basket Charleroi in Belgium", eventType: "SIGNING" },
      ],
    },
    {
      slug: "ryan-nembhard",
      firstName: "Ryan",
      lastName: "Nembhard",
      birthYear: 2003,
      hometown: "Aurora, ON, Canada",
      highSchool: "Transferred to Montverde Academy from Canada",

      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/1642948.png",
      isFeatured: false,
      bio: "A crafty Canadian point guard who was a key playmaker on the 2019-20 Montverde team. Nembhard's vision and court sense made him a standout distributor.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Point Guard",
        currentEmployer: "Dallas Mavericks",
        league: "NBA",
        location: "Dallas, TX",
        statusNote:
          "After starring at Creighton and Gonzaga in college, Nembhard went undrafted in 2025 and signed a two-way contract with the Dallas Mavericks. He quickly proved himself, scoring a career-high 28 points against Denver and earning a double-double with 15 points and 13 assists against Miami. In March 2026, his two-way deal was converted to a standard multi-year contract with the Mavs.",
        sourceUrl: "https://en.wikipedia.org/wiki/Ryan_Nembhard",
      },
      membership: {
        role: "PLAYER",
        position: "Point Guard",
        yearsAtSchool: "2019-2020",
        statsNote: "Elite passer and floor general • Canadian national team prospect",
      },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Montverde Academy Eagles", season: "2019-2020", yearLabel: "Senior", sortOrder: 201, gamesPlayed: 25, pointsPerGame: 7.0, reboundsPerGame: 2.0, assistsPerGame: 4.5 },
      ],
      careerEvents: [
        { year: 2021, title: "Enrolled at Creighton University", eventType: "CAREER" },
        { year: 2023, title: "Transferred to Gonzaga University", eventType: "CAREER" },
        { year: 2025, title: "Signed two-way deal with the Dallas Mavericks (undrafted)", eventType: "SIGNING" },
        { year: 2026, title: "Converted to standard multi-year NBA contract", eventType: "SIGNING" },
      ],
    },
    // ── Coach ────────────────────────────────────────────────────────────────
    {
      slug: "day-day-cunningham",
      firstName: "Day'Ron",
      lastName: "Cunningham",
      birthYear: 2002,
      hometown: "Memphis, TN",
      highSchool: "Montverde Academy, Montverde, FL",
      bio: "Bench player on the historic 2019-20 Montverde team that featured four eventual NBA lottery picks. Played a supporting role as the team rolled through the season undefeated.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Citizen",
        location: "Florida",
        statusNote: "Played briefly in college after Montverde before transitioning away from basketball. Maintains a low public profile.",
        sourceUrl: "https://montverdeacademy.com/athletics/basketball/",
      },
      membership: { role: "PLAYER", jerseyNumber: 14, position: "Guard", yearsAtSchool: "2019-2020", statsNote: "Reserve guard on undefeated 2019-20 squad" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Montverde Academy", season: "2019-20", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 4.5, reboundsPerGame: 1.8, assistsPerGame: 1.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "ace-baldwin",
      firstName: "Ace",
      lastName: "Baldwin Jr.",
      birthYear: 2002,
      hometown: "Baltimore, MD",
      highSchool: "Montverde Academy, Montverde, FL",
      bio: "Underclassman point guard on the 2019-20 Montverde team. Would later become the Atlantic 10 Player of the Year at VCU before transferring to Penn State.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Point Guard",
        league: "Overseas / G-League",
        statusNote: "Played college ball at VCU (2020-23) where he won A-10 Player of the Year, then transferred to Penn State for his senior year. Has played professionally overseas and in the G-League since going undrafted in 2024.",
        sourceUrl: "https://en.wikipedia.org/wiki/Ace_Baldwin_Jr.",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Point Guard", yearsAtSchool: "2019-2020", statsNote: "Underclassman PG · Later A-10 POY at VCU" },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Montverde Academy", season: "2019-20", yearLabel: "Junior", sortOrder: 1, pointsPerGame: 8.5, reboundsPerGame: 2.5, assistsPerGame: 4.0 },
      ],
      careerEvents: [],
    },
    // ── Coach ────────────────────────────────────────────────────────────────
    {
      slug: "kevin-boyle",
      firstName: "Kevin",
      lastName: "Boyle",
      birthYear: 1963,
      hometown: "Jersey City, NJ",
      highSchool: "St. Peter's Prep, Jersey City, NJ",
      isFeatured: true,
      bio: "The legendary high school basketball coach who built Montverde Academy into the nation's top prep program. Boyle produced more than 30 NBA draft picks during his tenure at Montverde and St. Patrick (NJ).",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Basketball Coach",
        currentEmployer: "SPIRE Academy",
        location: "Geneva, OH",
        statusNote:
          "After two decades of dominance at Montverde Academy where he won multiple national championships and produced over 30 NBA draft picks, Boyle departed the program. He was hired as head basketball coach at SPIRE Academy in Geneva, Ohio, continuing his mission of developing elite basketball talent. Boyle is widely considered one of the greatest high school basketball coaches in American history, with alumni including Ben Simmons, D'Angelo Russell, RJ Barrett, Cade Cunningham, and Scottie Barnes.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kevin_Boyle_(basketball)",
      },
      membership: {
        role: "HEAD_COACH",
        position: "Head Coach",
        yearsAtSchool: "2011-2024",
        statsNote: "Multiple national championships • 30+ NBA draft picks produced • Built Montverde into top program",
      },
      careerEvents: [
        { year: 2013, title: "Won first GEICO Nationals championship at Montverde", eventType: "CHAMPIONSHIP" },
        { year: 2020, title: "Led Montverde to undefeated 25-0 season (GEICO Nationals cancelled due to COVID)", eventType: "CAREER" },
        { year: 2024, title: "Departed Montverde Academy", eventType: "CAREER" },
        { year: 2024, title: "Hired as head coach at SPIRE Academy", eventType: "CAREER" },
      ],
    },
    {
      slug: "jesse-jones-mva",
      firstName: "Jesse",
      lastName: "Jones",
      birthYear: 2001,
      hometown: "Clermont, FL",
      highSchool: "Montverde Academy, Montverde, FL",
      isFeatured: false,
      bio: "Valedictorian with a 4.47 GPA and Student-Athlete of the Year. A guard who prioritized academics alongside basketball.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Finance Professional",
        location: "Florida",
        statusNote:
          "After Montverde, Jones played at Babson College for two years then transferred to Florida State, where he earned both a bachelor's (2024) and master's (2025) in finance. A standout student-athlete who was valedictorian at Montverde.",
        sourceUrl: "https://seminoles.com/sports/mens-basketball/roster/jesse-jones/7256",
      },
      membership: { role: "PLAYER", position: "Guard", yearsAtSchool: "2019-2020", statsNote: "Senior • Valedictorian (4.47 GPA) • Student-Athlete of the Year" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Montverde Academy Eagles", season: "2019-2020", yearLabel: "Senior (Valedictorian)", sortOrder: 201, gamesPlayed: 25, pointsPerGame: 5.0, reboundsPerGame: 2.0, assistsPerGame: 2.0 },
      ],
      careerEvents: [
        { year: 2025, title: "Earned master's degree in finance from Florida State", eventType: "CAREER" },
      ],
    },
    {
      slug: "keegan-harvey",
      firstName: "Keegan",
      lastName: "Harvey",
      birthYear: 2002,
      hometown: "Newcastle, Australia",
      highSchool: "Montverde Academy, Montverde, FL (from Australia)",
      isFeatured: false,
      bio: "An Australian forward who came to Montverde as an international recruit.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Bryant University",
        location: "Smithfield, RI",
        statusNote:
          "After Montverde, Harvey played at the College of Charleston, transferred to George Washington, then transferred again to Bryant University. His journey from Newcastle, Australia through multiple college programs is a testament to his persistence.",
        sourceUrl: "https://news.bryant.edu/keegan-harveys-walkabout-route-australia-bryant",
      },
      membership: { role: "PLAYER", position: "Forward", yearsAtSchool: "2019-2020", statsNote: "Senior • International recruit from Australia" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Montverde Academy Eagles", season: "2019-2020", yearLabel: "Senior (Australian)", sortOrder: 201, gamesPlayed: 25, pointsPerGame: 4.0, reboundsPerGame: 3.5, assistsPerGame: 0.5 },
      ],
      careerEvents: [
        { year: 2020, title: "Enrolled at College of Charleston", eventType: "CAREER" },
      ],
    },
    {
      slug: "abdou-halil-barre",
      firstName: "Abdou-Halil",
      lastName: "Barre",
      birthYear: 2003,
      hometown: "Paris, France (born in Cotonou, Benin)",
      highSchool: "Montverde Academy, Montverde, FL",
      isFeatured: false,
      bio: "A versatile forward/center from Benin who was raised in Paris, France before coming to Montverde.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Duquesne University",
        location: "Pittsburgh, PA",
        statusNote:
          "After Montverde, Barre enrolled at Duquesne University where he plays college basketball. An international prospect who came to the U.S. from France via Benin.",
        sourceUrl: "https://247sports.com/player/abdou-halil-barre-46103241/",
      },
      membership: { role: "PLAYER", position: "Forward / Center", yearsAtSchool: "2019-2021", statsNote: "Junior • International recruit from Benin/France" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Montverde Academy Eagles", season: "2019-2020", yearLabel: "Junior (from Benin/France)", sortOrder: 201, gamesPlayed: 20, pointsPerGame: 3.5, reboundsPerGame: 4.0, assistsPerGame: 0.5 },
      ],
      careerEvents: [
        { year: 2021, title: "Enrolled at Duquesne University", eventType: "CAREER" },
      ],
    },
    {
      slug: "yonghao-michael-wu",
      firstName: "Yonghao Michael",
      lastName: "Wu",
      birthYear: 2002,
      hometown: "Beijing, China",
      highSchool: "Montverde Academy, Montverde, FL (from China)",
      isFeatured: false,
      bio: "A forward from Beijing, China who was part of Montverde's deep and internationally diverse roster.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Citizen",
        location: "China",
        statusNote:
          "Wu was part of Montverde's internationally diverse 2019-20 roster. Post-Montverde career information is limited. He is believed to have returned to China after his time at the academy.",
        sourceUrl: "https://mvasports.com/sports/mens-basketball/roster/yonghao-michael-wu/1387",
      },
      membership: { role: "PLAYER", position: "Forward", yearsAtSchool: "2019-2020", statsNote: "Junior • International player from Beijing, China" },
            seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Montverde Academy Eagles", season: "2019-2020", yearLabel: "Junior (from Beijing)", sortOrder: 201, gamesPlayed: 15, pointsPerGame: 2.0, reboundsPerGame: 2.0, assistsPerGame: 0.3 },
      ],
      careerEvents: [],
    },
  ],
};
