import type { TeamSeed } from "./types";

export const ncstateBasketball2023: TeamSeed = {
  slug: "ncstate-basketball-2023",
  name: "NC State Wolfpack",
  season: "2022-2023",
  sport: "Men's Basketball",
  school: "North Carolina State University",
  conference: "ACC",
  accomplishment: "2022-2023 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/152.png",
  mascotName: "Wolfpack",
  people: [
    {
      slug: "terquavion-smith",
      firstName: "Terquavion",
      lastName: "Smith",
      birthYear: 2003,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore star who declared for 2023 NBA Draft.",
      status: { occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Guard", location: "United States", statusNote: "2023 NBA Draft pick. Dynamic scorer.", sourceUrl: "https://en.wikipedia.org/wiki/Terquavion_Smith" },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 17.5, reboundsPerGame: 4, assistsPerGame: 3 },
      seasonStats: [{ level: "COLLEGE", teamName: "NC State Wolfpack", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 17.5, reboundsPerGame: 4, assistsPerGame: 3 }],
      careerEvents: [],
    },
    {
      slug: "jarkel-joiner",
      firstName: "Jarkel",
      lastName: "Joiner",
      birthYear: 1999,
      hometown: "United States",
      highSchool: "United States",
      bio: "Grad transfer from Ole Miss.",
      status: { occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Pro Player", location: "Overseas", statusNote: "Played overseas after NC State.", sourceUrl: "https://en.wikipedia.org/wiki/Jarkel_Joiner" },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 14.5, reboundsPerGame: 3, assistsPerGame: 2.5 },
      seasonStats: [{ level: "COLLEGE", teamName: "NC State Wolfpack", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 14.5, reboundsPerGame: 3, assistsPerGame: 2.5 }],
      careerEvents: [],
    },
    {
      slug: "kevin-keatts",
      firstName: "Kevin",
      lastName: "Keatts",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Led NC State to the 2024 ACC Tournament title and Final Four — first since 1983.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Still coaching at NC State. Contract extended after 2024 Final Four.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kevin_Keatts",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2018-2026" },
      seasonStats: [
        { level: "COACHING", teamName: "NC State Wolfpack", season: "2022-2023", yearLabel: "2022-2023", sortOrder: 215 },
      ],
      careerEvents: [],
    },
  ],
};
