import type { TeamSeed } from "./types";

export const ncstateBasketball2014: TeamSeed = {
  slug: "ncstate-basketball-2014",
  name: "NC State Wolfpack",
  season: "2013-2014",
  sport: "Men's Basketball",
  school: "North Carolina State University",
  conference: "ACC",
  accomplishment: "2013-2014 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/152.png",
  mascotName: "Wolfpack",
  people: [
    {
      slug: "tj-warren",
      firstName: "T.J.",
      lastName: "Warren",
      birthYear: 1993,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore ACC POY who was #14 pick. Scored 24+ PPG.",
      status: { occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Forward", location: "United States", statusNote: "#14 pick by Suns. Averaged 50 PPG in NBA bubble. Injuries derailed career. Comeback attempts ongoing.", sourceUrl: "https://en.wikipedia.org/wiki/T.J._Warren" },
      membership: { role: "PLAYER", jerseyNumber: 24, position: "Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 24.9, reboundsPerGame: 7.1, assistsPerGame: 1.5 },
      seasonStats: [{ level: "COLLEGE", teamName: "NC State Wolfpack", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 24.9, reboundsPerGame: 7.1, assistsPerGame: 1.5 }],
      careerEvents: [],
    },
    {
      slug: "mark-gottfried",
      firstName: "Mark",
      lastName: "Gottfried",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Led NC State to 4 NCAA Tournaments in 6 seasons before being fired.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Fired mid-2017 season. Later coached at Cal State Northridge.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mark_Gottfried",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2012-2017" },
      seasonStats: [
        { level: "COACHING", teamName: "NC State Wolfpack", season: "2013-2014", yearLabel: "2013-2014", sortOrder: 206 },
      ],
      careerEvents: [],
    },
  ],
};
