import type { TeamSeed } from "./types";

export const ncstateBasketball2020: TeamSeed = {
  slug: "ncstate-basketball-2020",
  name: "NC State Wolfpack",
  season: "2019-2020",
  sport: "Men's Basketball",
  school: "North Carolina State University",
  conference: "ACC",
  accomplishment: "2019-2020 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/152.png",
  mascotName: "Wolfpack",
  people: [
    {
      slug: "markell-johnson",
      firstName: "Markell",
      lastName: "Johnson",
      birthYear: 1997,
      hometown: "United States",
      highSchool: "United States",
      bio: "Senior captain.",
      status: { occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Pro Player", location: "Overseas", statusNote: "4-year starter. Went overseas after graduation.", sourceUrl: "https://en.wikipedia.org/wiki/Markell_Johnson" },
      membership: { role: "PLAYER", jerseyNumber: 11, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 13, reboundsPerGame: 3.5, assistsPerGame: 5.5 },
      seasonStats: [{ level: "COLLEGE", teamName: "NC State Wolfpack", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 13, reboundsPerGame: 3.5, assistsPerGame: 5.5 }],
      careerEvents: [],
    },
    {
      slug: "devon-daniels",
      firstName: "Devon",
      lastName: "Daniels",
      birthYear: 1998,
      hometown: "United States",
      highSchool: "United States",
      bio: "Junior guard and athletic scorer.",
      status: { occupationType: "OTHER", currentTitle: "Professional", location: "United States", statusNote: "Career cut short by knee injury.", sourceUrl: "https://en.wikipedia.org/wiki/Devon_Daniels" },
      membership: { role: "PLAYER", jerseyNumber: 24, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 13, reboundsPerGame: 4, assistsPerGame: 1.5 },
      seasonStats: [{ level: "COLLEGE", teamName: "NC State Wolfpack", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 13, reboundsPerGame: 4, assistsPerGame: 1.5 }],
      careerEvents: [],
    },
    {
      slug: "kevin-keatts",
      firstName: "Kevin",
      lastName: "Keatts",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Led NC State to the 2024 ACC Tournament title and Final Four — first since 1983.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Still coaching at NC State. Contract extended after 2024 Final Four.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kevin_Keatts",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2018-2026" },
      seasonStats: [
        { level: "COACHING", teamName: "NC State Wolfpack", season: "2019-2020", yearLabel: "2019-2020", sortOrder: 212 },
      ],
      careerEvents: [],
    },
  ],
};
