import type { TeamSeed } from "./types";

export const ncstateBasketball2011: TeamSeed = {
  slug: "ncstate-basketball-2011",
  name: "NC State Wolfpack",
  season: "2010-2011",
  sport: "Men's Basketball",
  school: "North Carolina State University",
  conference: "ACC",
  accomplishment: "2010-2011 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/152.png",
  mascotName: "Wolfpack",
  people: [
    {
      slug: "cj-leslie",
      firstName: "C.J.",
      lastName: "Leslie",
      birthYear: 1991,
      hometown: "United States",
      highSchool: "United States",
      bio: "Freshman forward with NBA athleticism.",
      status: { occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Pro Player", location: "Overseas", statusNote: "Drafted #47 in 2013. Long overseas career.", sourceUrl: "https://en.wikipedia.org/wiki/C.J._Leslie" },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 11, reboundsPerGame: 5.5, assistsPerGame: 0.8 },
      seasonStats: [{ level: "COLLEGE", teamName: "NC State Wolfpack", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 11, reboundsPerGame: 5.5, assistsPerGame: 0.8 }],
      careerEvents: [],
    },
    {
      slug: "scott-wood-ncst",
      firstName: "Scott",
      lastName: "Wood",
      birthYear: 1990,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore sharpshooter. One of ACC's best 3-pt shooters.",
      status: { occupationType: "OTHER", currentTitle: "Professional", location: "NC", statusNote: "NC State's all-time 3-point leader.", sourceUrl: "https://en.wikipedia.org/wiki/Scott_Wood" },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 11, reboundsPerGame: 2, assistsPerGame: 1 },
      seasonStats: [{ level: "COLLEGE", teamName: "NC State Wolfpack", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 11, reboundsPerGame: 2, assistsPerGame: 1 }],
      careerEvents: [],
    },
    {
      slug: "sidney-lowe",
      firstName: "Sidney",
      lastName: "Lowe",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Former NC State point guard from the 1983 championship team who coached his alma mater.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Fired after 2011. Now a basketball consultant.",
        sourceUrl: "https://en.wikipedia.org/wiki/Sidney_Lowe",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2011" },
      seasonStats: [
        { level: "COACHING", teamName: "NC State Wolfpack", season: "2010-2011", yearLabel: "2010-2011", sortOrder: 203 },
      ],
      careerEvents: [],
    },
  ],
};
