import type { TeamSeed } from "./types";

export const ncstateBasketball2018: TeamSeed = {
  slug: "ncstate-basketball-2018",
  name: "NC State Wolfpack",
  season: "2017-2018",
  sport: "Men's Basketball",
  school: "North Carolina State University",
  conference: "ACC",
  accomplishment: "2017-2018 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/152.png",
  mascotName: "Wolfpack",
  people: [
    {
      slug: "markell-johnson",
      firstName: "Markell",
      lastName: "Johnson",
      birthYear: 1997,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore guard who became team's primary playmaker under Keatts.",
      status: { occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Pro Player", location: "Overseas", statusNote: "Played overseas after NC State.", sourceUrl: "https://en.wikipedia.org/wiki/Markell_Johnson" },
      membership: { role: "PLAYER", jerseyNumber: 11, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 12.5, reboundsPerGame: 3.5, assistsPerGame: 4.5 },
      seasonStats: [{ level: "COLLEGE", teamName: "NC State Wolfpack", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 12.5, reboundsPerGame: 3.5, assistsPerGame: 4.5 }],
      careerEvents: [],
    },
    {
      slug: "torin-dorn",
      firstName: "Torin",
      lastName: "Dorn",
      birthYear: 1996,
      hometown: "United States",
      highSchool: "United States",
      bio: "Junior guard and team leader.",
      status: { occupationType: "OTHER", currentTitle: "Professional", location: "NC", statusNote: "Played overseas briefly.", sourceUrl: "https://en.wikipedia.org/wiki/Torin_Dorn" },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 14, reboundsPerGame: 5, assistsPerGame: 2 },
      seasonStats: [{ level: "COLLEGE", teamName: "NC State Wolfpack", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 14, reboundsPerGame: 5, assistsPerGame: 2 }],
      careerEvents: [],
    },
    {
      slug: "kevin-keatts",
      firstName: "Kevin",
      lastName: "Keatts",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Led NC State to the 2024 ACC Tournament title and Final Four — first since 1983.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Still coaching at NC State. Contract extended after 2024 Final Four.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kevin_Keatts",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2018-2026" },
      seasonStats: [
        { level: "COACHING", teamName: "NC State Wolfpack", season: "2017-2018", yearLabel: "2017-2018", sortOrder: 210 },
      ],
      careerEvents: [],
    },
  ],
};
