import type { TeamSeed } from "./types";

export const ncstateBasketball2024: TeamSeed = {
  slug: "ncstate-basketball-2024",
  name: "NC State Wolfpack",
  season: "2023-2024",
  sport: "Men's Basketball",
  school: "North Carolina State University",
  conference: "ACC",
  accomplishment: "ACC Tournament Champions, Final Four (26-10)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/152.png",
  mascotName: "Wolfpack",
  people: [
    {
      slug: "dj-burns-jr",
      firstName: "DJ",
      lastName: "Burns Jr.",
      birthYear: 2001,
      hometown: "Windsor, CT",
      highSchool: "Loomis Chaffee School, Windsor, CT",
      isFeatured: true,
      bio: "The 6'9\" 275-lb center who became the face of the 2024 NCAA Tournament with his improbable combination of nimble footwork, spin moves, and infectious personality. Named ACC Tournament MVP and NCAA South Regional MOP.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "Greensboro Swarm (NBA G League)",
        league: "G League",
        location: "Greensboro, NC",
        statusNote: "After going undrafted in 2024, Burns played NBA Summer League with the Cleveland Cavaliers, then signed overseas with the Goyang Sono Skygunners in South Korea and Bnei Herzliya in the Israeli Basketball Premier League. In October 2025, he was acquired by the Greensboro Swarm (Charlotte Hornets' G League affiliate), bringing him back to North Carolina. He went viral during the 2024 tournament for his spin moves and gained a massive social media following.",
        sourceUrl: "https://en.wikipedia.org/wiki/D._J._Burns",
      },
      membership: { role: "PLAYER", jerseyNumber: 30, position: "Center", yearsAtSchool: "2020-2024", statsNote: "ACC Tournament MVP • NCAA South Regional MOP • Final Four", gamesPlayed: 36, pointsPerGame: 13.5, reboundsPerGame: 5.3, assistsPerGame: 2.9 },
      seasonStats: [
        { level: "COLLEGE", teamName: "NC State Wolfpack", season: "2023-24", yearLabel: "5th Year Senior", sortOrder: 205, gamesPlayed: 36, minutesPerGame: 24.5, pointsPerGame: 13.5, reboundsPerGame: 5.3, assistsPerGame: 2.9, fieldGoalPct: 0.614 },
      ],
      careerEvents: [
        { year: 2024, title: "Named ACC Tournament MVP — NC State's first ACC title since 1987", eventType: "AWARD", month: 3, day: 16 },
        { year: 2024, title: "Led NC State to first Final Four since 1983", eventType: "MILESTONE", month: 3, day: 31 },
        { year: 2025, title: "Acquired by Greensboro Swarm (G League)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "dj-horne",
      firstName: "DJ",
      lastName: "Horne",
      birthYear: 2001,
      hometown: "Chandler, AZ",
      highSchool: "Chandler High School, Chandler, AZ",
      isFeatured: true,
      bio: "The junior transfer from Arizona State who was NC State's leading scorer during the magical tournament run. A clutch perimeter shooter who hit timely threes throughout March.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "USC Heidelberg",
        league: "BBL (Germany)",
        location: "Heidelberg, Germany",
        statusNote: "After NC State's Final Four run, Horne played NBA Summer League with the San Antonio Spurs. He signed with MLP Academics Heidelberg in Germany's top basketball league (BBL) in August 2024. In his first pro season, he is averaging 14.2 PPG, 2.7 RPG, 2.2 APG in 29 games, with several standout performances including 28 points against Würzburg.",
        sourceUrl: "https://en.wikipedia.org/wiki/DJ_Horne",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Guard", yearsAtSchool: "2023-2024", statsNote: "Leading scorer • Transfer from Arizona State • Final Four", gamesPlayed: 36, pointsPerGame: 16.1, reboundsPerGame: 2.9, assistsPerGame: 2.4 },
      seasonStats: [
        { level: "COLLEGE", teamName: "NC State Wolfpack", season: "2023-24", yearLabel: "Junior (transfer)", sortOrder: 203, gamesPlayed: 36, minutesPerGame: 33.0, pointsPerGame: 16.1, reboundsPerGame: 2.9, assistsPerGame: 2.4, threePointPct: 0.370 },
      ],
      careerEvents: [
        { year: 2024, title: "Won ACC Tournament with NC State (first since 1987)", eventType: "CHAMPIONSHIP", month: 3, day: 16 },
        { year: 2024, title: "Reached Final Four with NC State (first since 1983)", eventType: "MILESTONE" },
        { year: 2024, title: "Signed with USC Heidelberg in Germany's BBL", eventType: "SIGNING" },
      ],
    },
    {
      slug: "jayden-taylor",
      firstName: "Jayden",
      lastName: "Taylor",
      birthYear: 2002,
      hometown: "Indianapolis, IN",
      highSchool: "Perry Meridian High School, Indianapolis, IN",
      bio: "A junior guard who transferred from Butler and provided scoring punch and toughness throughout the ACC Tournament and March Madness run.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "Overseas",
        location: "Europe",
        statusNote: "After the Final Four run, Taylor entered the transfer portal and moved to another school for his final year of eligibility. He is pursuing a professional basketball career.",
        sourceUrl: "https://gopack.com/sports/mens-basketball/roster/jayden-taylor/",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Guard", yearsAtSchool: "2023-2024", statsNote: "Transfer from Butler • Clutch scorer • Final Four", gamesPlayed: 35, pointsPerGame: 10.5, reboundsPerGame: 2.7, assistsPerGame: 1.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "NC State Wolfpack", season: "2023-24", yearLabel: "Junior (transfer)", sortOrder: 203, gamesPlayed: 35, minutesPerGame: 28.1, pointsPerGame: 10.5, reboundsPerGame: 2.7, assistsPerGame: 1.8 },
      ],
      careerEvents: [
        { year: 2024, title: "Reached Final Four with NC State", eventType: "MILESTONE" },
      ],
    },
    {
      slug: "casey-morsell",
      firstName: "Casey",
      lastName: "Morsell",
      birthYear: 2000,
      hometown: "Fort Washington, MD",
      highSchool: "St. John's College High School, Washington, DC",
      bio: "A fifth-year senior guard who transferred from Virginia — meaning he won a national championship (2019 as a recruit/redshirt) and then made a Final Four with NC State. Elite perimeter defender.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "Overseas",
        location: "Europe",
        statusNote: "After his college career, Morsell has pursued professional basketball overseas. He was one of the most experienced players on the 2024 Final Four roster, having played at both Virginia and NC State.",
        sourceUrl: "https://gopack.com/sports/mens-basketball/roster/casey-morsell/",
      },
      membership: { role: "PLAYER", jerseyNumber: 14, position: "Guard", yearsAtSchool: "2021-2024", statsNote: "5th year senior • Transfer from Virginia • Final Four", gamesPlayed: 36, pointsPerGame: 9.8, reboundsPerGame: 3.2, assistsPerGame: 1.1 },
      seasonStats: [
        { level: "COLLEGE", teamName: "NC State Wolfpack", season: "2023-24", yearLabel: "5th Year (transfer from UVA)", sortOrder: 205, gamesPlayed: 36, minutesPerGame: 29.3, pointsPerGame: 9.8, reboundsPerGame: 3.2 },
      ],
      careerEvents: [
        { year: 2024, title: "Reached Final Four with NC State", eventType: "MILESTONE" },
      ],
    },
    {
      slug: "michael-oconnell",
      firstName: "Michael",
      lastName: "O'Connell",
      birthYear: 2000,
      hometown: "Palo Alto, CA",
      highSchool: "Sacred Heart Preparatory, Atherton, CA",
      bio: "A senior point guard who transferred from Stanford and brought leadership and floor generalship to the Wolfpack. His steady hand running the offense was critical during the tournament.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "California",
        statusNote: "After the Final Four run, O'Connell graduated and has explored professional basketball opportunities while also considering a career in business or tech given his Stanford and NC State education.",
        sourceUrl: "https://gopack.com/sports/mens-basketball/roster/michael-oconnell/",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Point Guard", yearsAtSchool: "2022-2024", statsNote: "Transfer from Stanford • Floor general • Final Four", gamesPlayed: 36, pointsPerGame: 8.2, reboundsPerGame: 2.4, assistsPerGame: 4.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "NC State Wolfpack", season: "2023-24", yearLabel: "Senior (transfer)", sortOrder: 204, gamesPlayed: 36, minutesPerGame: 30.8, pointsPerGame: 8.2, reboundsPerGame: 2.4, assistsPerGame: 4.5 },
      ],
      careerEvents: [
        { year: 2024, title: "Reached Final Four with NC State", eventType: "MILESTONE" },
      ],
    },
    {
      slug: "ben-middlebrooks",
      firstName: "Ben",
      lastName: "Middlebrooks",
      birthYear: 2003,
      hometown: "Fort Mill, SC",
      highSchool: "Fort Mill High School, Fort Mill, SC",
      bio: "A sophomore forward who provided interior depth and rim protection during the Final Four run. One of the few non-transfers on the roster.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Clemson University",
        location: "Clemson, SC",
        statusNote: "After the Final Four, Middlebrooks entered the transfer portal and committed to Clemson, staying within the ACC. He continues to develop as a versatile frontcourt player.",
        sourceUrl: "https://gopack.com/sports/mens-basketball/roster/ben-middlebrooks/",
      },
      membership: { role: "PLAYER", jerseyNumber: 34, position: "Forward", yearsAtSchool: "2022-2024", statsNote: "Sophomore reserve • Rim protector • Final Four", gamesPlayed: 34, pointsPerGame: 5.1, reboundsPerGame: 3.0 },
      seasonStats: [
        { level: "COLLEGE", teamName: "NC State Wolfpack", season: "2023-24", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 34, minutesPerGame: 14.2, pointsPerGame: 5.1, reboundsPerGame: 3.0 },
      ],
      careerEvents: [
        { year: 2024, title: "Reached Final Four with NC State", eventType: "MILESTONE" },
        { year: 2024, title: "Transferred to Clemson", eventType: "SIGNING" },
      ],
    },
    {
      slug: "mohamed-diarra",
      firstName: "Mohamed",
      lastName: "Diarra",
      birthYear: 2001,
      hometown: "Montreal, QC",
      highSchool: "Putnam Science Academy, Putnam, CT",
      bio: "A junior forward who transferred from Pittsburgh and provided athleticism and defensive versatility. His energy off the bench was crucial during the tournament run.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        location: "United States",
        statusNote: "After NC State's Final Four run, Diarra has continued his basketball career, using his remaining eligibility. He remains an active college player.",
        sourceUrl: "https://gopack.com/sports/mens-basketball/roster/mohamed-diarra/",
      },
      membership: { role: "PLAYER", jerseyNumber: 23, position: "Forward", yearsAtSchool: "2023-2024", statsNote: "Transfer from Pitt • Athletic defender • Final Four", gamesPlayed: 32, pointsPerGame: 4.8, reboundsPerGame: 3.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "NC State Wolfpack", season: "2023-24", yearLabel: "Junior (transfer)", sortOrder: 203, gamesPlayed: 32, minutesPerGame: 14.0, pointsPerGame: 4.8, reboundsPerGame: 3.5 },
      ],
      careerEvents: [
        { year: 2024, title: "Reached Final Four with NC State", eventType: "MILESTONE" },
      ],
    },
    {
      slug: "dennis-parker-jr",
      firstName: "Dennis",
      lastName: "Parker Jr.",
      birthYear: 2004,
      hometown: "Normal, IL",
      highSchool: "University High School, Normal, IL",
      bio: "A freshman guard who provided youthful energy and ballhandling off the bench during the historic Final Four run.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "NC State University",
        location: "Raleigh, NC",
        statusNote: "Parker returned to NC State after the Final Four run and continues to develop as a key member of the Wolfpack roster. One of the few players from the 2024 team who remained at NC State.",
        sourceUrl: "https://gopack.com/sports/mens-basketball/roster/dennis-parker-jr/",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Guard", yearsAtSchool: "2023-present", statsNote: "Freshman reserve • Stayed at NC State • Final Four", gamesPlayed: 28, pointsPerGame: 3.2, assistsPerGame: 1.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "NC State Wolfpack", season: "2023-24", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 28, minutesPerGame: 12.5, pointsPerGame: 3.2, assistsPerGame: 1.5 },
      ],
      careerEvents: [
        { year: 2024, title: "Reached Final Four with NC State as a freshman", eventType: "MILESTONE" },
      ],
    },
    {
      slug: "kevin-keatts",
      firstName: "Kevin",
      lastName: "Keatts",
      birthYear: 1972,
      hometown: "Norfolk, VA",
      highSchool: "Maury High School, Norfolk, VA",
      isFeatured: true,
      bio: "Led NC State to their first ACC Tournament championship since 1987 and first Final Four since 1983. Received a contract extension and massive raise after the Cinderella run.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "NC State University",
        location: "Raleigh, NC",
        statusNote: "Kevin Keatts has been NC State's head coach since 2017. The 2024 Final Four run — entering the ACC Tournament as an 11-seed and winning 5 games in 5 days — was the defining moment of his tenure. He received a multi-year contract extension and significant raise following the run. Previously coached at UNC-Wilmington where he went 72-28 in three seasons.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kevin_Keatts",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2017-present", statsNote: "2024 ACC Tournament Champions • Final Four • Contract extension" },
      seasonStats: [
        { level: "COACHING", teamName: "NC State Wolfpack", season: "2023-24", yearLabel: "2023-24", sortOrder: 208, wins: 26, losses: 10, tournamentResult: "Final Four" },
      ],
      careerEvents: [
        { year: 2024, title: "Led NC State to ACC Tournament title (first since 1987) and Final Four (first since 1983)", eventType: "CHAMPIONSHIP", month: 3, day: 16 },
        { year: 2024, title: "Received multi-year contract extension after Final Four run", eventType: "MILESTONE" },
      ],
    },
  ],
};
