import type { TeamSeed } from "./types";

export const ncstateBasketball2013: TeamSeed = {
  slug: "ncstate-basketball-2013",
  name: "NC State Wolfpack",
  season: "2012-2013",
  sport: "Men's Basketball",
  school: "North Carolina State University",
  conference: "ACC",
  accomplishment: "2012-2013 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/152.png",
  mascotName: "Wolfpack",
  people: [
    {
      slug: "cj-leslie",
      firstName: "C.J.",
      lastName: "Leslie",
      birthYear: 1991,
      hometown: "United States",
      highSchool: "United States",
      bio: "Junior who declared for draft. #47 pick.",
      status: { occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Pro Player", location: "Overseas", statusNote: "Drafted #47 by Celtics.", sourceUrl: "https://en.wikipedia.org/wiki/C.J._Leslie" },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 15, reboundsPerGame: 7.5, assistsPerGame: 1 },
      seasonStats: [{ level: "COLLEGE", teamName: "NC State Wolfpack", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 15, reboundsPerGame: 7.5, assistsPerGame: 1 }],
      careerEvents: [],
    },
    {
      slug: "scott-wood-ncst",
      firstName: "Scott",
      lastName: "Wood",
      birthYear: 1990,
      hometown: "United States",
      highSchool: "United States",
      bio: "Senior. NC State's all-time 3-pt leader.",
      status: { occupationType: "OTHER", currentTitle: "Professional", location: "NC", statusNote: "NC State career 3-point record.", sourceUrl: "https://en.wikipedia.org/wiki/Scott_Wood" },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 13, reboundsPerGame: 2, assistsPerGame: 1.5 },
      seasonStats: [{ level: "COLLEGE", teamName: "NC State Wolfpack", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 13, reboundsPerGame: 2, assistsPerGame: 1.5 }],
      careerEvents: [],
    },
    {
      slug: "lorenzo-brown",
      firstName: "Lorenzo",
      lastName: "Brown",
      birthYear: 1990,
      hometown: "United States",
      highSchool: "United States",
      bio: "Senior captain and floor general.",
      status: { occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Pro Player", location: "Overseas", statusNote: "Played for Raptors and in EuroLeague.", sourceUrl: "https://en.wikipedia.org/wiki/Lorenzo_Brown" },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 13, reboundsPerGame: 5, assistsPerGame: 6.5 },
      seasonStats: [{ level: "COLLEGE", teamName: "NC State Wolfpack", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 13, reboundsPerGame: 5, assistsPerGame: 6.5 }],
      careerEvents: [],
    },
    {
      slug: "mark-gottfried",
      firstName: "Mark",
      lastName: "Gottfried",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Led NC State to 4 NCAA Tournaments in 6 seasons before being fired.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Fired mid-2017 season. Later coached at Cal State Northridge.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mark_Gottfried",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2012-2017" },
      seasonStats: [
        { level: "COACHING", teamName: "NC State Wolfpack", season: "2012-2013", yearLabel: "2012-2013", sortOrder: 205 },
      ],
      careerEvents: [],
    },
  ],
};
