import type { TeamSeed } from "./types";

export const ncstateBasketball2015: TeamSeed = {
  slug: "ncstate-basketball-2015",
  name: "NC State Wolfpack",
  season: "2014-2015",
  sport: "Men's Basketball",
  school: "North Carolina State University",
  conference: "ACC",
  accomplishment: "2014-2015 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/152.png",
  mascotName: "Wolfpack",
  people: [
    {
      slug: "ralston-turner",
      firstName: "Ralston",
      lastName: "Turner",
      birthYear: 1992,
      hometown: "United States",
      highSchool: "United States",
      bio: "Senior guard. LSU transfer who led NC State scoring.",
      status: { occupationType: "OTHER", currentTitle: "Professional", location: "United States", statusNote: "Played overseas briefly after NC State.", sourceUrl: "https://en.wikipedia.org/wiki/Ralston_Turner" },
      membership: { role: "PLAYER", jerseyNumber: 22, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 12, reboundsPerGame: 3, assistsPerGame: 1.5 },
      seasonStats: [{ level: "COLLEGE", teamName: "NC State Wolfpack", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 12, reboundsPerGame: 3, assistsPerGame: 1.5 }],
      careerEvents: [],
    },
    {
      slug: "trevor-lacey",
      firstName: "Trevor",
      lastName: "Lacey",
      birthYear: 1993,
      hometown: "United States",
      highSchool: "United States",
      bio: "Junior guard. Alabama transfer who was team's go-to scorer.",
      status: { occupationType: "RETIRED_ATHLETE", currentTitle: "Professional", location: "United States", statusNote: "Played overseas briefly.", sourceUrl: "https://en.wikipedia.org/wiki/Trevor_Lacey" },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 15.5, reboundsPerGame: 3.5, assistsPerGame: 2.5 },
      seasonStats: [{ level: "COLLEGE", teamName: "NC State Wolfpack", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 15.5, reboundsPerGame: 3.5, assistsPerGame: 2.5 }],
      careerEvents: [],
    },
    {
      slug: "mark-gottfried",
      firstName: "Mark",
      lastName: "Gottfried",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Led NC State to 4 NCAA Tournaments in 6 seasons before being fired.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Fired mid-2017 season. Later coached at Cal State Northridge.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mark_Gottfried",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2012-2017" },
      seasonStats: [
        { level: "COACHING", teamName: "NC State Wolfpack", season: "2014-2015", yearLabel: "2014-2015", sortOrder: 207 },
      ],
      careerEvents: [],
    },
  ],
};
