import type { TeamSeed } from "./types";

export const ncstateBasketball2016: TeamSeed = {
  slug: "ncstate-basketball-2016",
  name: "NC State Wolfpack",
  season: "2015-2016",
  sport: "Men's Basketball",
  school: "North Carolina State University",
  conference: "ACC",
  accomplishment: "2015-2016 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/152.png",
  mascotName: "Wolfpack",
  people: [
    {
      slug: "dennis-smith-jr",
      firstName: "Dennis",
      lastName: "Smith Jr.",
      birthYear: 1997,
      hometown: "United States",
      highSchool: "United States",
      bio: "5-star freshman who was #9 pick in 2017. Electric athlete.",
      status: { occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Guard", location: "United States", statusNote: "#9 pick by Mavericks. Played for Mavs, Knicks, Pistons, Nets, Hornets, Trail Blazers. Career affected by injuries.", sourceUrl: "https://en.wikipedia.org/wiki/Dennis_Smith_Jr." },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Point Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 18.1, reboundsPerGame: 4.6, assistsPerGame: 6.2 },
      seasonStats: [{ level: "COLLEGE", teamName: "NC State Wolfpack", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 18.1, reboundsPerGame: 4.6, assistsPerGame: 6.2 }],
      careerEvents: [],
    },
    {
      slug: "mark-gottfried",
      firstName: "Mark",
      lastName: "Gottfried",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Led NC State to 4 NCAA Tournaments in 6 seasons before being fired.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Fired mid-2017 season. Later coached at Cal State Northridge.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mark_Gottfried",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2012-2017" },
      seasonStats: [
        { level: "COACHING", teamName: "NC State Wolfpack", season: "2015-2016", yearLabel: "2015-2016", sortOrder: 208 },
      ],
      careerEvents: [],
    },
  ],
};
