import type { TeamSeed } from "./types";

export const ncstateBasketball2009: TeamSeed = {
  slug: "ncstate-basketball-2009",
  name: "NC State Wolfpack",
  season: "2008-2009",
  sport: "Men's Basketball",
  school: "North Carolina State University",
  conference: "ACC",
  accomplishment: "2008-2009 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/152.png",
  mascotName: "Wolfpack",
  people: [
    {
      slug: "tracy-smith-ncst",
      firstName: "Tracy",
      lastName: "Smith",
      birthYear: 1987,
      hometown: "United States",
      highSchool: "United States",
      bio: "Senior forward and team leader under Sidney Lowe.",
      status: { occupationType: "RETIRED_ATHLETE", currentTitle: "Retired", location: "NC", statusNote: "Played overseas briefly after NC State.", sourceUrl: "https://en.wikipedia.org/wiki/Tracy_Smith" },
      membership: { role: "PLAYER", jerseyNumber: 30, position: "Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 14, reboundsPerGame: 7.5, assistsPerGame: 1 },
      seasonStats: [{ level: "COLLEGE", teamName: "NC State Wolfpack", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 14, reboundsPerGame: 7.5, assistsPerGame: 1 }],
      careerEvents: [],
    },
    {
      slug: "brandon-costner",
      firstName: "Brandon",
      lastName: "Costner",
      birthYear: 1987,
      hometown: "United States",
      highSchool: "United States",
      bio: "Senior forward and scorer.",
      status: { occupationType: "RETIRED_ATHLETE", currentTitle: "Professional", location: "NC", statusNote: "Played overseas after NC State.", sourceUrl: "https://en.wikipedia.org/wiki/Brandon_Costner" },
      membership: { role: "PLAYER", jerseyNumber: 33, position: "Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 12.5, reboundsPerGame: 5, assistsPerGame: 1 },
      seasonStats: [{ level: "COLLEGE", teamName: "NC State Wolfpack", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 12.5, reboundsPerGame: 5, assistsPerGame: 1 }],
      careerEvents: [],
    },
    {
      slug: "sidney-lowe",
      firstName: "Sidney",
      lastName: "Lowe",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Former NC State point guard from the 1983 championship team who coached his alma mater.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Fired after 2011. Now a basketball consultant.",
        sourceUrl: "https://en.wikipedia.org/wiki/Sidney_Lowe",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2011" },
      seasonStats: [
        { level: "COACHING", teamName: "NC State Wolfpack", season: "2008-2009", yearLabel: "2008-2009", sortOrder: 201 },
      ],
      careerEvents: [],
    },
  ],
};
