import type { TeamSeed } from "./types";

export const ncstateBasketball2022: TeamSeed = {
  slug: "ncstate-basketball-2022",
  name: "NC State Wolfpack",
  season: "2021-2022",
  sport: "Men's Basketball",
  school: "North Carolina State University",
  conference: "ACC",
  accomplishment: "2021-2022 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/152.png",
  mascotName: "Wolfpack",
  people: [
    {
      slug: "dereon-seabron",
      firstName: "Dereon",
      lastName: "Seabron",
      birthYear: 2000,
      hometown: "United States",
      highSchool: "United States",
      bio: "Junior who led team in scoring. Two-way with Pelicans.",
      status: { occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Guard", location: "United States", statusNote: "Signed two-way with New Orleans Pelicans.", sourceUrl: "https://en.wikipedia.org/wiki/Dereon_Seabron" },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 17.5, reboundsPerGame: 6.5, assistsPerGame: 3.5 },
      seasonStats: [{ level: "COLLEGE", teamName: "NC State Wolfpack", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 17.5, reboundsPerGame: 6.5, assistsPerGame: 3.5 }],
      careerEvents: [],
    },
    {
      slug: "terquavion-smith",
      firstName: "Terquavion",
      lastName: "Smith",
      birthYear: 2003,
      hometown: "United States",
      highSchool: "United States",
      bio: "Freshman sensation and NC Mr. Basketball.",
      status: { occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Guard", location: "United States", statusNote: "Selected in 2023 NBA Draft. NC's Mr. Basketball in 2022.", sourceUrl: "https://en.wikipedia.org/wiki/Terquavion_Smith" },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 16, reboundsPerGame: 3.5, assistsPerGame: 2.5 },
      seasonStats: [{ level: "COLLEGE", teamName: "NC State Wolfpack", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 16, reboundsPerGame: 3.5, assistsPerGame: 2.5 }],
      careerEvents: [],
    },
    {
      slug: "kevin-keatts",
      firstName: "Kevin",
      lastName: "Keatts",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Led NC State to the 2024 ACC Tournament title and Final Four — first since 1983.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Still coaching at NC State. Contract extended after 2024 Final Four.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kevin_Keatts",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2018-2026" },
      seasonStats: [
        { level: "COACHING", teamName: "NC State Wolfpack", season: "2021-2022", yearLabel: "2021-2022", sortOrder: 214 },
      ],
      careerEvents: [],
    },
  ],
};
