import type { TeamSeed } from "./types";

export const notreDameBasketball2016: TeamSeed = {
  slug: "notre-dame-basketball-2016",
  name: "Notre Dame Fighting Irish",
  season: "2015-2016",
  sport: "Men's Basketball",
  school: "University of Notre Dame",
  conference: "ACC",
  accomplishment: "Elite Eight (24-12)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/87.png",
  mascotName: "Fighting Irish",
  people: [
    {
      slug: "demetrius-jackson",
      firstName: "Demetrius",
      lastName: "Jackson",
      birthYear: 1995,
      hometown: "Cicero, IL",
      highSchool: "Morton High School, Cicero, IL",
      isFeatured: true,
      bio: "The junior point guard who was the engine of Notre Dame's Elite Eight run. A lightning-fast scorer who declared for the NBA Draft after leading the Irish to their deepest tournament run since joining the ACC.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Skills Development Coach / Founder",
        currentEmployer: "Elevate with Eleven",
        location: "Indiana",
        statusNote: "Selected #45 overall by the Boston Celtics in 2016, Jackson played brief NBA stints with the Celtics, Sixers, and Rockets, plus time in the G League. After his playing career, he transitioned into coaching and founded 'Elevate with Eleven' in 2023, a basketball training program focused on athletic and personal development for young players. His entrepreneurial pivot from player to skills coach/trainer reflects a growing trend among former college stars.",
        sourceUrl: "https://en.wikipedia.org/wiki/Demetrius_Jackson",
      },
      membership: { role: "PLAYER", jerseyNumber: 11, position: "Point Guard", yearsAtSchool: "2013-2016", statsNote: "#45 pick • Junior floor general • Elite Eight", gamesPlayed: 35, pointsPerGame: 15.8, reboundsPerGame: 3.2, assistsPerGame: 3.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Notre Dame Fighting Irish", season: "2015-16", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 35, minutesPerGame: 34.0, pointsPerGame: 15.8, reboundsPerGame: 3.2, assistsPerGame: 3.5, stealsPerGame: 1.3, fieldGoalPct: 0.450, threePointPct: 0.382 },
      ],
      careerEvents: [
        { year: 2016, title: "Led Notre Dame to Elite Eight", eventType: "MILESTONE" },
        { year: 2016, title: "Selected #45 overall by the Boston Celtics", eventType: "DRAFT", month: 6, day: 23 },
        { year: 2023, title: "Founded 'Elevate with Eleven' basketball training program", eventType: "CAREER_CHANGE" },
      ],
    },
    {
      slug: "zach-auguste",
      firstName: "Zach",
      lastName: "Auguste",
      birthYear: 1993,
      hometown: "Brooklyn, NY",
      highSchool: "St. Thomas More School, Oakdale, CT",
      bio: "The senior center and Brooklyn native who anchored Notre Dame's frontcourt. His inside scoring and rebounding gave the Irish a physical presence that complemented their guard-heavy attack.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "Shiga Lakestars",
        league: "B.League (Japan)",
        location: "Shiga, Japan",
        statusNote: "After going undrafted in 2016, Auguste built a professional career spanning the G League, FIBA Americas, and multiple international leagues. He has been playing in Japan's B.League since 2023, first with SeaHorses Mikawa and currently leading the Shiga Lakestars in scoring (17.7 PPG) and rebounds (7.3 RPG) in the 2025-26 season. The Greek-American center represents one of the best examples of a college star finding long-term success overseas.",
        sourceUrl: "https://en.wikipedia.org/wiki/Zach_Auguste",
      },
      membership: { role: "PLAYER", jerseyNumber: 30, position: "Center", yearsAtSchool: "2012-2016", statsNote: "Senior captain • Interior anchor • Elite Eight", gamesPlayed: 35, pointsPerGame: 14.1, reboundsPerGame: 7.5, assistsPerGame: 1.0 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Notre Dame Fighting Irish", season: "2015-16", yearLabel: "Senior", sortOrder: 204, gamesPlayed: 35, minutesPerGame: 28.0, pointsPerGame: 14.1, reboundsPerGame: 7.5, fieldGoalPct: 0.575 },
      ],
      careerEvents: [
        { year: 2016, title: "Led Notre Dame to Elite Eight as senior captain", eventType: "MILESTONE" },
        { year: 2023, title: "Began playing in Japan's B.League", eventType: "SIGNING" },
      ],
    },
    {
      slug: "vj-beachem",
      firstName: "V.J.",
      lastName: "Beachem",
      birthYear: 1995,
      hometown: "Fort Wayne, IN",
      highSchool: "New Haven High School, New Haven, IN",
      bio: "A junior forward whose outside shooting and length made him a dangerous matchup in the ACC. His ability to stretch the floor from the power forward spot was ahead of his time.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Professional",
        location: "Indiana",
        statusNote: "After graduating from Notre Dame, Beachem played professional basketball in the G League and overseas. The Indiana native has since returned to the Fort Wayne area and transitioned to a career off the court.",
        sourceUrl: "https://fightingirish.com/roster/vj-beachem/",
      },
      membership: { role: "PLAYER", jerseyNumber: 23, position: "Forward", yearsAtSchool: "2013-2017", statsNote: "Junior • Floor-spacing forward • Elite Eight", gamesPlayed: 35, pointsPerGame: 10.2, reboundsPerGame: 3.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Notre Dame Fighting Irish", season: "2015-16", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 35, minutesPerGame: 25.0, pointsPerGame: 10.2, reboundsPerGame: 3.8, threePointPct: 0.380 },
      ],
      careerEvents: [
        { year: 2016, title: "Led Notre Dame to Elite Eight", eventType: "MILESTONE" },
      ],
    },
    {
      slug: "steve-vasturia",
      firstName: "Steve",
      lastName: "Vasturia",
      birthYear: 1994,
      hometown: "Warwick, NY",
      highSchool: "Warwick Valley High School, Warwick, NY",
      bio: "A junior guard from New York who was one of Notre Dame's most reliable shooters. His clutch shot-making in tournament play helped fuel the Elite Eight run.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Professional",
        location: "New York",
        statusNote: "After graduating from Notre Dame, Vasturia played professional basketball in Europe and the G League before transitioning to a career off the court. He returned to the Northeast and has been involved in business.",
        sourceUrl: "https://fightingirish.com/roster/steve-vasturia/",
      },
      membership: { role: "PLAYER", jerseyNumber: 32, position: "Guard", yearsAtSchool: "2013-2017", statsNote: "Junior • Clutch shooter • Elite Eight", gamesPlayed: 35, pointsPerGame: 9.5, reboundsPerGame: 3.0, assistsPerGame: 2.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Notre Dame Fighting Irish", season: "2015-16", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 35, minutesPerGame: 30.0, pointsPerGame: 9.5, reboundsPerGame: 3.0, assistsPerGame: 2.5 },
      ],
      careerEvents: [
        { year: 2016, title: "Led Notre Dame to Elite Eight", eventType: "MILESTONE" },
      ],
    },
    {
      slug: "bonzie-colson",
      firstName: "Bonzie",
      lastName: "Colson",
      birthYear: 1996,
      hometown: "New Bedford, MA",
      highSchool: "New Hampton School, New Hampton, NH",
      bio: "A sophomore forward who was already emerging as Notre Dame's best player during the Elite Eight run. Went on to become one of the most decorated players in program history, earning All-ACC honors multiple times.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "Overseas",
        location: "Europe",
        statusNote: "After graduating from Notre Dame, Colson played for the Cleveland Cavaliers on a two-way contract and in the G League before pursuing an international career. He has played in multiple European countries. At Notre Dame, he became the program's all-time leader in double-doubles and was named to the All-ACC team multiple times.",
        sourceUrl: "https://en.wikipedia.org/wiki/Bonzie_Colson",
      },
      membership: { role: "PLAYER", jerseyNumber: 35, position: "Power Forward", yearsAtSchool: "2014-2018", statsNote: "Sophomore • Emerging star • Future All-ACC • Elite Eight", gamesPlayed: 34, pointsPerGame: 11.8, reboundsPerGame: 6.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Notre Dame Fighting Irish", season: "2015-16", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 34, minutesPerGame: 24.0, pointsPerGame: 11.8, reboundsPerGame: 6.5, fieldGoalPct: 0.520 },
      ],
      careerEvents: [
        { year: 2016, title: "Reached Elite Eight with Notre Dame as a sophomore", eventType: "MILESTONE" },
      ],
    },
    {
      slug: "mike-brey",
      firstName: "Mike",
      lastName: "Brey",
      birthYear: 1959,
      hometown: "Bethesda, MD",
      highSchool: "DeMatha Catholic High School, Hyattsville, MD",
      isFeatured: true,
      bio: "The winningest coach in Notre Dame basketball history who led the Irish to back-to-back Elite Eights in 2015 and 2016 and established the program as a consistent ACC contender. A former Duke assistant under Coach K.",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Coach",
        currentEmployer: "Atlanta Hawks",
        league: "NBA",
        location: "Atlanta, GA",
        statusNote: "Mike Brey coached Notre Dame for 23 seasons (2000-2023), compiling a 480-275 record and winning the 2009 NIT Championship, 2 ACC Tournament titles, and reaching 2 Elite Eights (2015, 2016). He stepped down after the 2022-23 season and joined the Atlanta Hawks as an NBA assistant coach. Before Notre Dame, he was an assistant at Duke under Mike Krzyzewski (1987-2000) and head coach at Delaware (1995-2000). A member of the Coach K coaching tree.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Brey",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2000-2023", statsNote: "480-275 record • 2 Elite Eights • Winningest ND coach • Coach K protege" },
      seasonStats: [
        { level: "COACHING", teamName: "Notre Dame Fighting Irish", season: "2015-16", yearLabel: "2015-16", sortOrder: 216, wins: 24, losses: 12, tournamentResult: "Elite Eight" },
      ],
      careerEvents: [
        { year: 2000, title: "Named Notre Dame head coach after 13 years as Duke assistant", eventType: "CAREER_CHANGE" },
        { year: 2015, title: "Led Notre Dame to Elite Eight", eventType: "MILESTONE" },
        { year: 2016, title: "Led Notre Dame to back-to-back Elite Eight", eventType: "MILESTONE" },
        { year: 2023, title: "Stepped down after 23 seasons — joined Atlanta Hawks as NBA assistant", eventType: "CAREER_CHANGE" },
      ],
    },
  ],
};
