import type { TeamSeed } from "./types";

export const notreDameBasketball2015: TeamSeed = {
  slug: "notre-dame-basketball-2015",
  name: "Notre Dame Fighting Irish",
  season: "2014-2015",
  sport: "Men's Basketball",
  school: "University of Notre Dame",
  conference: "ACC",
  accomplishment: "2014-2015 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/87.png",
  mascotName: "Fighting Irish",
  people: [
    {
      slug: "jerian-grant",
      firstName: "Jerian",
      lastName: "Grant",
      birthYear: 1992,
      hometown: "Bowie, MD",
      highSchool: "DeMatha Catholic",
      bio: "Senior PG. Led Elite Eight run. #19 pick by Wizards (traded to Knicks).",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "Overseas",
        statusNote: "Brother of Jerami/Jerian Grant. NBA stints with Knicks, Bulls, Magic. Now overseas.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jerian_Grant",
      },
      membership: { role: "PLAYER", jerseyNumber: 22, position: "Guard", yearsAtSchool: "2014-2015", gamesPlayed: 37, pointsPerGame: 16.6, reboundsPerGame: 3.1, assistsPerGame: 6.7 },
      seasonStats: [{ level: "COLLEGE", teamName: "Notre Dame Fighting Irish", season: "2014-2015", yearLabel: "2014-2015", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 16.6, reboundsPerGame: 3.1, assistsPerGame: 6.7 }],
      careerEvents: [{ date: "2015-06-25", month: 6, day: 25, year: 2015, title: "Drafted #19 by Washington Wizards", description: "Selected 19th overall, traded to Knicks." }],
    },
    {
      slug: "pat-connaughton",
      firstName: "Pat",
      lastName: "Connaughton",
      birthYear: 1993,
      hometown: "Arlington, MA",
      highSchool: "St. John's Prep",
      bio: "Senior guard and two-sport star (also drafted by Orioles). #41 pick.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        location: "Milwaukee, WI",
        statusNote: "2021 NBA Champion with Bucks. Still with Milwaukee. Known for 44-inch vertical.",
        sourceUrl: "https://en.wikipedia.org/wiki/Pat_Connaughton",
      },
      membership: { role: "PLAYER", jerseyNumber: 24, position: "Guard", yearsAtSchool: "2014-2015", gamesPlayed: 37, pointsPerGame: 12.1, reboundsPerGame: 7.4, assistsPerGame: 2.7 },
      seasonStats: [{ level: "COLLEGE", teamName: "Notre Dame Fighting Irish", season: "2014-2015", yearLabel: "2014-2015", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 12.1, reboundsPerGame: 7.4, assistsPerGame: 2.7 }],
      careerEvents: [{ date: "2015-06-25", month: 6, day: 25, year: 2015, title: "Drafted #41 by Brooklyn Nets", description: "Selected 41st, won 2021 NBA title with Bucks." }],
    },
    {
      slug: "demetrius-jackson",
      firstName: "Demetrius",
      lastName: "Jackson",
      birthYear: 1994,
      hometown: "Mishawaka, IN",
      highSchool: "Marian",
      bio: "Sophomore PG. Future #45 pick by Celtics.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "United States",
        statusNote: "Brief NBA career with Celtics, Rockets, 76ers. Now retired.",
        sourceUrl: "https://en.wikipedia.org/wiki/Demetrius_Jackson",
      },
      membership: { role: "PLAYER", jerseyNumber: 11, position: "Guard", yearsAtSchool: "2014-2015", gamesPlayed: 37, pointsPerGame: 12.4, reboundsPerGame: 3.0, assistsPerGame: 2.5 },
      seasonStats: [{ level: "COLLEGE", teamName: "Notre Dame Fighting Irish", season: "2014-2015", yearLabel: "2014-2015", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 12.4, reboundsPerGame: 3.0, assistsPerGame: 2.5 }],
      careerEvents: [{ date: "2016-06-23", month: 6, day: 23, year: 2016, title: "Drafted #45 by Boston Celtics", description: "Selected 45th overall in 2016 NBA Draft." }],
    },
    {
      slug: "zach-auguste",
      firstName: "Zach",
      lastName: "Auguste",
      birthYear: 1993,
      hometown: "Marlborough, MA",
      highSchool: "New Hampton",
      bio: "Junior big man.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "Overseas",
        statusNote: "Long EuroLeague career after Notre Dame.",
        sourceUrl: "https://en.wikipedia.org/wiki/Zach_Auguste",
      },
      membership: { role: "PLAYER", jerseyNumber: 30, position: "Forward", yearsAtSchool: "2014-2015", gamesPlayed: 37, pointsPerGame: 10.7, reboundsPerGame: 6.7, assistsPerGame: 0.9 },
      seasonStats: [{ level: "COLLEGE", teamName: "Notre Dame Fighting Irish", season: "2014-2015", yearLabel: "2014-2015", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 10.7, reboundsPerGame: 6.7, assistsPerGame: 0.9 }],
      careerEvents: [],
    },
    {
      slug: "mike-brey",
      firstName: "Mike",
      lastName: "Brey",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Winningest coach in ND history (480-275). Two Elite Eights. Coach K protege.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Stepped down 2023. Now Atlanta Hawks NBA assistant.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Brey",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2023" },
      seasonStats: [
        { level: "COACHING", teamName: "Notre Dame Fighting Irish", season: "2014-2015", yearLabel: "2014-2015", sortOrder: 207 },
      ],
      careerEvents: [],
    },
  ],
};
