import type { TeamSeed } from "./types";

export const notreDameBasketball2022: TeamSeed = {
  slug: "notre-dame-basketball-2022",
  name: "Notre Dame Fighting Irish",
  season: "2021-2022",
  sport: "Men's Basketball",
  school: "University of Notre Dame",
  conference: "ACC",
  accomplishment: "2021-2022 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/87.png",
  mascotName: "Fighting Irish",
  people: [
    {
      slug: "blake-wesley",
      firstName: "Blake",
      lastName: "Wesley",
      birthYear: 2003,
      hometown: "South Bend, IN",
      highSchool: "South Bend Riley",
      bio: "One-and-done freshman guard. #25 pick by San Antonio Spurs.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        location: "San Antonio, TX",
        statusNote: "Still with Spurs on rookie contract.",
        sourceUrl: "https://en.wikipedia.org/wiki/Blake_Wesley",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Guard", yearsAtSchool: "2021-2022", gamesPlayed: 35, pointsPerGame: 14.4, reboundsPerGame: 3.7, assistsPerGame: 2.4 },
      seasonStats: [{ level: "COLLEGE", teamName: "Notre Dame Fighting Irish", season: "2021-2022", yearLabel: "2021-2022", sortOrder: 201, gamesPlayed: 35, pointsPerGame: 14.4, reboundsPerGame: 3.7, assistsPerGame: 2.4 }],
      careerEvents: [{ date: "2022-06-23", month: 6, day: 23, year: 2022, title: "Drafted #25 by San Antonio Spurs", description: "Selected 25th overall in 2022 NBA Draft." }],
    },
    {
      slug: "paul-atkinson-jr",
      firstName: "Paul",
      lastName: "Atkinson Jr.",
      birthYear: 1999,
      hometown: "Winter Garden, FL",
      highSchool: "Windermere",
      bio: "Yale grad transfer. Key frontcourt piece for NCAA Tournament run.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "Overseas",
        statusNote: "Plays professionally overseas after Notre Dame career.",
        sourceUrl: "https://en.wikipedia.org/wiki/Paul_Atkinson_Jr.",
      },
      membership: { role: "PLAYER", jerseyNumber: 44, position: "Forward", yearsAtSchool: "2021-2022", gamesPlayed: 35, pointsPerGame: 11.2, reboundsPerGame: 5.3, assistsPerGame: 1.3 },
      seasonStats: [{ level: "COLLEGE", teamName: "Notre Dame Fighting Irish", season: "2021-2022", yearLabel: "2021-2022", sortOrder: 201, gamesPlayed: 35, pointsPerGame: 11.2, reboundsPerGame: 5.3, assistsPerGame: 1.3 }],
      careerEvents: [],
    },
    {
      slug: "mike-brey",
      firstName: "Mike",
      lastName: "Brey",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Winningest coach in ND history (480-275). Two Elite Eights. Coach K protege.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Stepped down 2023. Now Atlanta Hawks NBA assistant.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Brey",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2023" },
      seasonStats: [
        { level: "COACHING", teamName: "Notre Dame Fighting Irish", season: "2021-2022", yearLabel: "2021-2022", sortOrder: 214 },
      ],
      careerEvents: [],
    },
  ],
};
