import type { TeamSeed } from "./types";

export const notreDameBasketball2018: TeamSeed = {
  slug: "notre-dame-basketball-2018",
  name: "Notre Dame Fighting Irish",
  season: "2017-2018",
  sport: "Men's Basketball",
  school: "University of Notre Dame",
  conference: "ACC",
  accomplishment: "2017-2018 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/87.png",
  mascotName: "Fighting Irish",
  people: [
    {
      slug: "bonzie-colson",
      firstName: "Bonzie",
      lastName: "Colson",
      birthYear: 1995,
      hometown: "New Bedford, MA",
      highSchool: "St. Andrew's",
      bio: "Senior forward. ACC All-Conference. Undersized star. #54 pick by Timberwolves.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "Overseas",
        statusNote: "Brief NBA stint with Timberwolves. Long EuroLeague career.",
        sourceUrl: "https://en.wikipedia.org/wiki/Bonzie_Colson",
      },
      membership: { role: "PLAYER", jerseyNumber: 35, position: "Forward", yearsAtSchool: "2017-2018", gamesPlayed: 17, pointsPerGame: 19.7, reboundsPerGame: 10.1, assistsPerGame: 2.1 },
      seasonStats: [{ level: "COLLEGE", teamName: "Notre Dame Fighting Irish", season: "2017-2018", yearLabel: "2017-2018", sortOrder: 201, gamesPlayed: 17, pointsPerGame: 19.7, reboundsPerGame: 10.1, assistsPerGame: 2.1 }],
      careerEvents: [{ date: "2018-06-21", month: 6, day: 21, year: 2018, title: "Drafted #54 by Minnesota Timberwolves", description: "Selected 54th overall in 2018 NBA Draft." }],
    },
    {
      slug: "matt-farrell",
      firstName: "Matt",
      lastName: "Farrell",
      birthYear: 1995,
      hometown: "Point Pleasant, NJ",
      highSchool: "Point Pleasant Boro",
      bio: "Senior PG and captain.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "Overseas",
        statusNote: "Plays professionally in Europe after Notre Dame.",
        sourceUrl: "https://en.wikipedia.org/wiki/Matt_Farrell",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Guard", yearsAtSchool: "2017-2018", gamesPlayed: 32, pointsPerGame: 16.3, reboundsPerGame: 2.9, assistsPerGame: 5.5 },
      seasonStats: [{ level: "COLLEGE", teamName: "Notre Dame Fighting Irish", season: "2017-2018", yearLabel: "2017-2018", sortOrder: 201, gamesPlayed: 32, pointsPerGame: 16.3, reboundsPerGame: 2.9, assistsPerGame: 5.5 }],
      careerEvents: [],
    },
    {
      slug: "mike-brey",
      firstName: "Mike",
      lastName: "Brey",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Winningest coach in ND history (480-275). Two Elite Eights. Coach K protege.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Stepped down 2023. Now Atlanta Hawks NBA assistant.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Brey",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2023" },
      seasonStats: [
        { level: "COACHING", teamName: "Notre Dame Fighting Irish", season: "2017-2018", yearLabel: "2017-2018", sortOrder: 210 },
      ],
      careerEvents: [],
    },
  ],
};
