import type { TeamSeed } from "./types";

export const pittBasketball2013: TeamSeed = {
  slug: "pitt-basketball-2013",
  name: "Pittsburgh Panthers",
  season: "2012-2013",
  sport: "Men's Basketball",
  school: "University of Pittsburgh",
  conference: "ACC",
  accomplishment: "2012-2013 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/221.png",
  mascotName: "Panther",
  people: [
    {
      slug: "steven-adams",
      firstName: "Steven",
      lastName: "Adams",
      birthYear: 1993,
      hometown: "Rotorua, New Zealand",
      highSchool: "Notre Dame Prep",
      bio: "One-and-done freshman center from New Zealand. #12 pick by Thunder.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Center",
        location: "Houston, TX",
        statusNote: "Now with Houston Rockets. 10+ NBA seasons. Known for toughness and mustache.",
        sourceUrl: "https://en.wikipedia.org/wiki/Steven_Adams",
      },
      membership: { role: "PLAYER", jerseyNumber: 13, position: "Center", yearsAtSchool: "2012-2013", gamesPlayed: 32, pointsPerGame: 7.2, reboundsPerGame: 6.3, assistsPerGame: 0.3 },
      seasonStats: [{ level: "COLLEGE", teamName: "Pittsburgh Panthers", season: "2012-2013", yearLabel: "2012-2013", sortOrder: 201, gamesPlayed: 32, pointsPerGame: 7.2, reboundsPerGame: 6.3, assistsPerGame: 0.3 }],
      careerEvents: [{ date: "2013-06-27", month: 6, day: 27, year: 2013, title: "Drafted #12 by Oklahoma City Thunder", description: "Selected 12th overall in 2013 NBA Draft." }],
    },
    {
      slug: "tray-woodall",
      firstName: "Tray",
      lastName: "Woodall",
      birthYear: 1989,
      hometown: "Brooklyn, NY",
      highSchool: "Lincoln",
      bio: "Senior PG and captain.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "United States",
        statusNote: "Played overseas after Pitt career.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tray_Woodall",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Guard", yearsAtSchool: "2012-2013", gamesPlayed: 30, pointsPerGame: 11.7, reboundsPerGame: 2.1, assistsPerGame: 4.1 },
      seasonStats: [{ level: "COLLEGE", teamName: "Pittsburgh Panthers", season: "2012-2013", yearLabel: "2012-2013", sortOrder: 201, gamesPlayed: 30, pointsPerGame: 11.7, reboundsPerGame: 2.1, assistsPerGame: 4.1 }],
      careerEvents: [],
    },
    {
      slug: "jamie-dixon",
      firstName: "Jamie",
      lastName: "Dixon",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "328-123 at Pitt. 11 NCAA Tournaments. Left for TCU.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Now HC at TCU.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jamie_Dixon",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2016" },
      seasonStats: [
        { level: "COACHING", teamName: "Pittsburgh Panthers", season: "2012-2013", yearLabel: "2012-2013", sortOrder: 205 },
      ],
      careerEvents: [],
    },
  ],
};
