import type { TeamSeed } from "./types";

export const pittBasketball2023: TeamSeed = {
  slug: "pitt-basketball-2023",
  name: "Pittsburgh Panthers",
  season: "2022-2023",
  sport: "Men's Basketball",
  school: "University of Pittsburgh",
  conference: "ACC",
  accomplishment: "2022-2023 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/221.png",
  mascotName: "Panther",
  people: [
    {
      slug: "blake-hinson",
      firstName: "Blake",
      lastName: "Hinson",
      birthYear: 1999,
      hometown: "Deltona, FL",
      highSchool: "Deltona",
      bio: "Senior forward. Led NCAA Tournament Sweet Sixteen run. Elite 3-point shooter.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "Overseas",
        statusNote: "Plays professionally overseas. Pitt's all-time 3-point record holder.",
        sourceUrl: "https://en.wikipedia.org/wiki/Blake_Hinson",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Forward", yearsAtSchool: "2022-2023", gamesPlayed: 35, pointsPerGame: 15.6, reboundsPerGame: 6.5, assistsPerGame: 1.3 },
      seasonStats: [{ level: "COLLEGE", teamName: "Pittsburgh Panthers", season: "2022-2023", yearLabel: "2022-2023", sortOrder: 201, gamesPlayed: 35, pointsPerGame: 15.6, reboundsPerGame: 6.5, assistsPerGame: 1.3 }],
      careerEvents: [],
    },
    {
      slug: "jamarius-burton",
      firstName: "Jamarius",
      lastName: "Burton",
      birthYear: 1999,
      hometown: "Charlotte, NC",
      highSchool: "Providence Day",
      bio: "Senior guard. Led Sweet Sixteen run.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "Overseas",
        statusNote: "Plays overseas. Pitt captain for 2023 Sweet Sixteen team.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jamarius_Burton",
      },
      membership: { role: "PLAYER", jerseyNumber: 11, position: "Guard", yearsAtSchool: "2022-2023", gamesPlayed: 35, pointsPerGame: 11.7, reboundsPerGame: 3.4, assistsPerGame: 3.5 },
      seasonStats: [{ level: "COLLEGE", teamName: "Pittsburgh Panthers", season: "2022-2023", yearLabel: "2022-2023", sortOrder: 201, gamesPlayed: 35, pointsPerGame: 11.7, reboundsPerGame: 3.4, assistsPerGame: 3.5 }],
      careerEvents: [],
    },
    {
      slug: "jeff-capel",
      firstName: "Jeff",
      lastName: "Capel",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Former Duke assistant and Oklahoma HC. Rebuilding Pitt.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Currently coaching at Pittsburgh.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jeff_Capel",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2019-2026" },
      seasonStats: [
        { level: "COACHING", teamName: "Pittsburgh Panthers", season: "2022-2023", yearLabel: "2022-2023", sortOrder: 215 },
      ],
      careerEvents: [],
    },
  ],
};
