import type { TeamSeed } from "./types";

export const pittBasketball2024: TeamSeed = {
  slug: "pitt-basketball-2024",
  name: "Pittsburgh Panthers",
  season: "2023-2024",
  sport: "Men's Basketball",
  school: "University of Pittsburgh",
  conference: "ACC",
  accomplishment: "2023-2024 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/221.png",
  mascotName: "Panther",
  people: [
    {
      slug: "bub-carrington",
      firstName: "Carlton \"Bub\"",
      lastName: "Carrington",
      birthYear: 2005,
      hometown: "Baltimore, MD",
      highSchool: "St. Frances Academy",
      bio: "One-and-done freshman guard. #14 pick by Portland Trail Blazers.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        location: "Washington, DC",
        statusNote: "Traded to Washington Wizards on draft night. Rookie of the Year candidate.",
        sourceUrl: "https://en.wikipedia.org/wiki/Bub_Carrington",
      },
      membership: { role: "PLAYER", jerseyNumber: 7, position: "Guard", yearsAtSchool: "2023-2024", gamesPlayed: 33, pointsPerGame: 13.8, reboundsPerGame: 5.2, assistsPerGame: 4.1 },
      seasonStats: [{ level: "COLLEGE", teamName: "Pittsburgh Panthers", season: "2023-2024", yearLabel: "2023-2024", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 13.8, reboundsPerGame: 5.2, assistsPerGame: 4.1 }],
      careerEvents: [{ date: "2024-06-26", month: 6, day: 26, year: 2024, title: "Drafted #14 by Portland (traded to Wizards)", description: "Selected 14th overall in 2024 NBA Draft." }],
    },
    {
      slug: "jeff-capel",
      firstName: "Jeff",
      lastName: "Capel",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Former Duke assistant and Oklahoma HC. Rebuilding Pitt.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Currently coaching at Pittsburgh.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jeff_Capel",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2019-2026" },
      seasonStats: [
        { level: "COACHING", teamName: "Pittsburgh Panthers", season: "2023-2024", yearLabel: "2023-2024", sortOrder: 216 },
      ],
      careerEvents: [],
    },
  ],
};
