import type { TeamSeed } from "./types";

export const pittBasketball2014: TeamSeed = {
  slug: "pitt-basketball-2014",
  name: "Pittsburgh Panthers",
  season: "2013-2014",
  sport: "Men's Basketball",
  school: "University of Pittsburgh",
  conference: "ACC",
  accomplishment: "NCAA Tournament (26-10) — First ACC season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/221.png",
  mascotName: "Panther",
  people: [
    {
      slug: "talib-zanna",
      firstName: "Talib",
      lastName: "Zanna",
      birthYear: 1991,
      hometown: "Lagos, Nigeria",
      highSchool: "Hargrave Military",
      bio: "Senior big man from Nigeria. Played overseas pro career.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "Overseas",
        statusNote: "Plays professionally in Europe after Pitt career.",
        sourceUrl: "https://en.wikipedia.org/wiki/Talib_Zanna",
      },
      membership: { role: "PLAYER", jerseyNumber: 42, position: "Forward", yearsAtSchool: "2013-2014", gamesPlayed: 36, pointsPerGame: 13.1, reboundsPerGame: 8.2, assistsPerGame: 0.7 },
      seasonStats: [{ level: "COLLEGE", teamName: "Pittsburgh Panthers", season: "2013-2014", yearLabel: "2013-2014", sortOrder: 201, gamesPlayed: 36, pointsPerGame: 13.1, reboundsPerGame: 8.2, assistsPerGame: 0.7 }],
      careerEvents: [],
    },
    {
      slug: "lamar-patterson",
      firstName: "Lamar",
      lastName: "Patterson",
      birthYear: 1991,
      hometown: "Lancaster, PA",
      highSchool: "Brewster Academy, Wolfeboro, NH",
      isFeatured: true,
      bio: "The senior swingman who led Pitt in their first season in the ACC. A versatile 6'5\" do-everything player who could score, pass, and defend, earning ACC All-Conference honors. Selected in the 2nd round of the NBA Draft.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "Ipswich Force",
        league: "NBL One (Australia)",
        location: "Australia",
        statusNote: "Selected #48 overall by the Milwaukee Bucks (traded to Atlanta) in 2014, Patterson played 40 NBA games with the Hawks from 2015-17. He has since built an extensive international career spanning Puerto Rico, Italy, Australia, China, and New Zealand. Most recently plays for Ipswich Force in Australia's NBL One league. His versatility as a 6'5\" playmaker has translated well to international basketball.",
        sourceUrl: "https://en.wikipedia.org/wiki/Lamar_Patterson",
      },
      membership: { role: "PLAYER", jerseyNumber: 21, position: "Guard / Forward", yearsAtSchool: "2010-2014", statsNote: "All-ACC • #48 pick • Senior leader in first ACC season", gamesPlayed: 36, pointsPerGame: 17.1, reboundsPerGame: 4.5, assistsPerGame: 4.4 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Pittsburgh Panthers", season: "2013-14", yearLabel: "Senior", sortOrder: 204, gamesPlayed: 36, minutesPerGame: 35.0, pointsPerGame: 17.1, reboundsPerGame: 4.5, assistsPerGame: 4.4, fieldGoalPct: 0.458, threePointPct: 0.380 },
      ],
      careerEvents: [
        { year: 2014, title: "Led Pitt through first ACC season", eventType: "MILESTONE" },
        { year: 2014, title: "Selected #48 overall by the Milwaukee Bucks (traded to Atlanta)", eventType: "DRAFT", month: 6, day: 26 },
      ],
    },
    {
      slug: "talib-zanna",
      firstName: "Talib",
      lastName: "Zanna",
      birthYear: 1991,
      hometown: "Kaduna, Nigeria",
      highSchool: "Hargrave Military Academy, Chatham, VA",
      bio: "The senior power forward from Nigeria who was Pitt's most physical interior player. His rebounding and toughness set the tone for the Panthers' identity in their ACC debut season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "Overseas",
        location: "Europe",
        statusNote: "After graduating from Pitt, Zanna played professionally overseas in Turkey, Italy, Israel, and Germany. The Nigerian native has also represented Nigeria in FIBA competition. His physical style of play has made him a valued interior player in European leagues.",
        sourceUrl: "https://pittsburghpanthers.com/sports/mens-basketball/roster/talib-zanna/",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Power Forward", yearsAtSchool: "2010-2014", statsNote: "Senior • Nigerian forward • Physical interior presence", gamesPlayed: 36, pointsPerGame: 12.5, reboundsPerGame: 7.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Pittsburgh Panthers", season: "2013-14", yearLabel: "Senior", sortOrder: 204, gamesPlayed: 36, minutesPerGame: 28.0, pointsPerGame: 12.5, reboundsPerGame: 7.8, fieldGoalPct: 0.520 },
      ],
      careerEvents: [
        { year: 2014, title: "Completed senior season in Pitt's first ACC year", eventType: "MILESTONE" },
      ],
    },
    {
      slug: "james-robinson-pitt",
      firstName: "James",
      lastName: "Robinson",
      birthYear: 1993,
      hometown: "Pittsburgh, PA",
      highSchool: "South Side Area High School, Hookstown, PA",
      bio: "A junior point guard and local Pittsburgh product who provided floor leadership and perimeter scoring. His hometown connection made him a fan favorite at the Petersen Events Center.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Pittsburgh, PA",
        statusNote: "After four years at Pitt, Robinson played professional basketball overseas briefly before returning to the Pittsburgh area. The local product has remained connected to the Pitt basketball community.",
        sourceUrl: "https://pittsburghpanthers.com/sports/mens-basketball/roster/james-robinson/",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Point Guard", yearsAtSchool: "2011-2015", statsNote: "Junior • Local Pittsburgh product • First ACC season", gamesPlayed: 34, pointsPerGame: 10.5, reboundsPerGame: 2.3, assistsPerGame: 3.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Pittsburgh Panthers", season: "2013-14", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 34, minutesPerGame: 30.0, pointsPerGame: 10.5, assistsPerGame: 3.8 },
      ],
      careerEvents: [],
    },
    {
      slug: "cameron-wright-pitt",
      firstName: "Cameron",
      lastName: "Wright",
      birthYear: 1993,
      hometown: "Richmond, VA",
      highSchool: "Collegiate School, Richmond, VA",
      bio: "A junior guard who provided perimeter shooting and defensive toughness. His three-point ability stretched defenses and opened driving lanes for Patterson.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Virginia",
        statusNote: "After graduating from Pitt, Wright pursued professional basketball briefly before transitioning to a career off the court. He has been involved in business in the Virginia area.",
        sourceUrl: "https://pittsburghpanthers.com/sports/mens-basketball/roster/cameron-wright/",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Guard", yearsAtSchool: "2011-2015", statsNote: "Junior • Perimeter shooter • First ACC season", gamesPlayed: 35, pointsPerGame: 7.8, reboundsPerGame: 2.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Pittsburgh Panthers", season: "2013-14", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 35, minutesPerGame: 22.0, pointsPerGame: 7.8, threePointPct: 0.370 },
      ],
      careerEvents: [],
    },
    {
      slug: "michael-young-pitt",
      firstName: "Michael",
      lastName: "Young",
      birthYear: 1995,
      hometown: "Houston, TX",
      highSchool: "Westbury Christian School, Houston, TX",
      bio: "A talented freshman forward who showed flashes of star potential during Pitt's first ACC season. Went on to become one of the program's best players over the next three years.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "Overseas",
        location: "Europe",
        statusNote: "After four years at Pitt, Young played in the NBA G League and overseas. His size and skill level made him a productive college player, though his professional career has been primarily in international leagues and the G League.",
        sourceUrl: "https://pittsburghpanthers.com/sports/mens-basketball/roster/michael-young/",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Forward", yearsAtSchool: "2013-2017", statsNote: "Freshman • Emerging talent • First ACC season", gamesPlayed: 33, pointsPerGame: 6.2, reboundsPerGame: 3.0 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Pittsburgh Panthers", season: "2013-14", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 33, minutesPerGame: 15.0, pointsPerGame: 6.2, reboundsPerGame: 3.0 },
      ],
      careerEvents: [],
    },
    {
      slug: "jamie-dixon",
      firstName: "Jamie",
      lastName: "Dixon",
      birthYear: 1965,
      hometown: "Canoga Park, CA",
      highSchool: "Crespi Carmelite High School, Encino, CA",
      isFeatured: true,
      bio: "The head coach who guided Pitt through their transition from the Big East to the ACC. A former Pitt player who led the Panthers to 11 NCAA Tournaments in 13 seasons, making him one of the most successful coaches in program history.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "TCU",
        location: "Fort Worth, TX",
        statusNote: "Jamie Dixon coached Pitt for 13 seasons (2003-2016), compiling a 328-123 record (.727) and reaching 11 NCAA Tournaments, including multiple Sweet 16 appearances. He left for his home-state school TCU in 2016 and has rebuilt the Horned Frogs into an NCAA Tournament team — leading TCU to their first NCAA Tournament berth since 1998 in 2022 and their first-ever second-round win. Before becoming head coach, Dixon was a longtime Pitt assistant and former Pitt player (1983-87).",
        sourceUrl: "https://en.wikipedia.org/wiki/Jamie_Dixon",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2003-2016", statsNote: "328-123 record • 11 NCAA Tournaments • Led Pitt's ACC transition" },
      seasonStats: [
        { level: "COACHING", teamName: "Pittsburgh Panthers", season: "2013-14", yearLabel: "2013-14", sortOrder: 211, wins: 26, losses: 10, tournamentResult: "NCAA Tournament (first ACC season)" },
      ],
      careerEvents: [
        { year: 2003, title: "Named Pitt head coach after longtime assistant role", eventType: "CAREER_CHANGE" },
        { year: 2016, title: "Left Pitt to become TCU head coach", eventType: "CAREER_CHANGE" },
        { year: 2022, title: "Led TCU to first NCAA Tournament since 1998", eventType: "MILESTONE" },
      ],
    },
  ],
};
