import type { TeamSeed } from "./types";

export const pittBasketball2022: TeamSeed = {
  slug: "pitt-basketball-2022",
  name: "Pittsburgh Panthers",
  season: "2021-2022",
  sport: "Men's Basketball",
  school: "University of Pittsburgh",
  conference: "ACC",
  accomplishment: "2021-2022 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/221.png",
  mascotName: "Panther",
  people: [
    {
      slug: "jamarius-burton",
      firstName: "Jamarius",
      lastName: "Burton",
      birthYear: 1999,
      hometown: "Charlotte, NC",
      highSchool: "Providence Day",
      bio: "Junior guard. Transferred from Texas Tech.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "Overseas",
        statusNote: "Plays overseas after finishing career at Pitt.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jamarius_Burton",
      },
      membership: { role: "PLAYER", jerseyNumber: 11, position: "Guard", yearsAtSchool: "2021-2022", gamesPlayed: 30, pointsPerGame: 10.9, reboundsPerGame: 3.3, assistsPerGame: 3.0 },
      seasonStats: [{ level: "COLLEGE", teamName: "Pittsburgh Panthers", season: "2021-2022", yearLabel: "2021-2022", sortOrder: 201, gamesPlayed: 30, pointsPerGame: 10.9, reboundsPerGame: 3.3, assistsPerGame: 3.0 }],
      careerEvents: [],
    },
    {
      slug: "jeff-capel",
      firstName: "Jeff",
      lastName: "Capel",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Former Duke assistant and Oklahoma HC. Rebuilding Pitt.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Currently coaching at Pittsburgh.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jeff_Capel",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2019-2026" },
      seasonStats: [
        { level: "COACHING", teamName: "Pittsburgh Panthers", season: "2021-2022", yearLabel: "2021-2022", sortOrder: 214 },
      ],
      careerEvents: [],
    },
  ],
};
