import type { TeamSeed } from "./types";

export const syracuseBasketball2014: TeamSeed = {
  slug: "syracuse-basketball-2014",
  name: "Syracuse Orange",
  season: "2013-2014",
  sport: "Men's Basketball",
  school: "Syracuse University",
  conference: "ACC",
  accomplishment: "2013-2014 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/183.png",
  mascotName: "Orange",
  people: [
    {
      slug: "tyler-ennis",
      firstName: "Tyler",
      lastName: "Ennis",
      birthYear: 1994,
      hometown: "United States",
      highSchool: "United States",
      bio: "Canadian freshman who was #18 pick after one season.",
      status: { occupationType: "RETIRED_ATHLETE", currentTitle: "Retired", location: "Canada", statusNote: "#18 pick by Suns in 2014. Brief NBA career, played overseas.", sourceUrl: "https://en.wikipedia.org/wiki/Tyler_Ennis" },
      membership: { role: "PLAYER", jerseyNumber: 11, position: "Point Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 12.9, reboundsPerGame: 3.4, assistsPerGame: 5.5 },
      seasonStats: [{ level: "COLLEGE", teamName: "Syracuse Orange", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 12.9, reboundsPerGame: 3.4, assistsPerGame: 5.5 }],
      careerEvents: [],
    },
    {
      slug: "jerami-grant",
      firstName: "Jerami",
      lastName: "Grant",
      birthYear: 1994,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore. Future All-Star and $160M contract.",
      status: { occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Forward", location: "Portland, OR", statusNote: "NBA All-Star 2021. $160M contract with Trail Blazers.", sourceUrl: "https://en.wikipedia.org/wiki/Jerami_Grant" },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 12, reboundsPerGame: 6, assistsPerGame: 1 },
      seasonStats: [{ level: "COLLEGE", teamName: "Syracuse Orange", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 12, reboundsPerGame: 6, assistsPerGame: 1 }],
      careerEvents: [],
    },
    {
      slug: "jim-boeheim",
      firstName: "Jim",
      lastName: "Boeheim",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Legendary coach with 1,015 career wins. 2003 champion. 2-3 zone architect. Retired after 47 seasons.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Retired 2023. Head Coach Emeritus at Syracuse.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jim_Boeheim",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2023" },
      seasonStats: [
        { level: "COACHING", teamName: "Syracuse Orange", season: "2013-2014", yearLabel: "2013-2014", sortOrder: 206 },
      ],
      careerEvents: [],
    },
  ],
};
