import type { TeamSeed } from "./types";

export const syracuseBasketball2015: TeamSeed = {
  slug: "syracuse-basketball-2015",
  name: "Syracuse Orange",
  season: "2014-2015",
  sport: "Men's Basketball",
  school: "Syracuse University",
  conference: "ACC",
  accomplishment: "2014-2015 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/183.png",
  mascotName: "Orange",
  people: [
    {
      slug: "rakeem-christmas",
      firstName: "Rakeem",
      lastName: "Christmas",
      birthYear: 1991,
      hometown: "United States",
      highSchool: "United States",
      bio: "Senior center. ACC DPOY. #36 pick.",
      status: { occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Pro Player", location: "Europe", statusNote: "ACC DPOY. Drafted #36 by Pacers. Long overseas career.", sourceUrl: "https://en.wikipedia.org/wiki/Rakeem_Christmas" },
      membership: { role: "PLAYER", jerseyNumber: 25, position: "Center", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 17.5, reboundsPerGame: 9, assistsPerGame: 1.5 },
      seasonStats: [{ level: "COLLEGE", teamName: "Syracuse Orange", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 17.5, reboundsPerGame: 9, assistsPerGame: 1.5 }],
      careerEvents: [],
    },
    {
      slug: "michael-gbinije",
      firstName: "Michael",
      lastName: "Gbinije",
      birthYear: 1993,
      hometown: "United States",
      highSchool: "United States",
      bio: "Junior guard. Duke transfer who became team leader.",
      status: { occupationType: "RETIRED_ATHLETE", currentTitle: "Retired", location: "Connecticut", statusNote: "Duke transfer. Played for Pistons briefly.", sourceUrl: "https://en.wikipedia.org/wiki/Michael_Gbinije" },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Guard/Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 11, reboundsPerGame: 3.5, assistsPerGame: 3 },
      seasonStats: [{ level: "COLLEGE", teamName: "Syracuse Orange", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 11, reboundsPerGame: 3.5, assistsPerGame: 3 }],
      careerEvents: [],
    },
    {
      slug: "jim-boeheim",
      firstName: "Jim",
      lastName: "Boeheim",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Legendary coach with 1,015 career wins. 2003 champion. 2-3 zone architect. Retired after 47 seasons.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Retired 2023. Head Coach Emeritus at Syracuse.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jim_Boeheim",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2023" },
      seasonStats: [
        { level: "COACHING", teamName: "Syracuse Orange", season: "2014-2015", yearLabel: "2014-2015", sortOrder: 207 },
      ],
      careerEvents: [],
    },
  ],
};
