import type { TeamSeed } from "./types";

export const syracuseBasketball2024: TeamSeed = {
  slug: "syracuse-basketball-2024",
  name: "Syracuse Orange",
  season: "2023-2024",
  sport: "Men's Basketball",
  school: "Syracuse University",
  conference: "ACC",
  accomplishment: "2023-2024 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/183.png",
  mascotName: "Orange",
  people: [
    {
      slug: "judah-mintz",
      firstName: "Judah",
      lastName: "Mintz",
      birthYear: 2003,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore star. Declared for 2024 NBA Draft.",
      status: { occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Guard", location: "United States", statusNote: "2024 NBA Draft pick. Dynamic scorer and playmaker.", sourceUrl: "https://en.wikipedia.org/wiki/Judah_Mintz" },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 19.5, reboundsPerGame: 4, assistsPerGame: 6 },
      seasonStats: [{ level: "COLLEGE", teamName: "Syracuse Orange", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 19.5, reboundsPerGame: 4, assistsPerGame: 6 }],
      careerEvents: [],
    },
    {
      slug: "adrian-autry",
      firstName: "Adrian",
      lastName: "Autry",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Former Syracuse player and longtime Boeheim assistant who succeeded the legend.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Currently coaching at Syracuse.",
        sourceUrl: "https://en.wikipedia.org/wiki/Adrian_Autry",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2024-2026" },
      seasonStats: [
        { level: "COACHING", teamName: "Syracuse Orange", season: "2023-2024", yearLabel: "2023-2024", sortOrder: 216 },
      ],
      careerEvents: [],
    },
  ],
};
