import type { TeamSeed } from "./types";

export const syracuseBasketball2016: TeamSeed = {
  slug: "syracuse-basketball-2016",
  name: "Syracuse Orange",
  season: "2015-2016",
  sport: "Men's Basketball",
  school: "Syracuse University",
  conference: "ACC",
  accomplishment: "Final Four (23-14) — 10-seed Cinderella run",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/183.png",
  mascotName: "Orange",
  people: [
    {
      slug: "malachi-richardson",
      firstName: "Malachi",
      lastName: "Richardson",
      birthYear: 1997,
      hometown: "Trenton, NJ",
      highSchool: "Trenton Catholic Academy, Hamilton, NJ",
      isFeatured: true,
      bio: "The freshman guard who carried Syracuse to the Final Four with one of the most electrifying tournament performances in school history. He scored 21 of his 23 points in the second half of the Elite Eight comeback against Virginia — erasing a 16-point deficit to become just the fourth 10-seed ever to make the Final Four.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "Overseas / TBT",
        location: "United States",
        statusNote: "Selected #22 overall by the Charlotte Hornets (traded to Sacramento) in 2016, Richardson played 2 NBA seasons with the Kings and Raptors before pursuing an international career across Indonesia, Israel, Italy, Mexico, Poland, and Puerto Rico. He won the TBT championship in 2021 with Boeheim's Army (the Syracuse alumni team) and returned for TBT 2025 — his third appearance with the squad. He continues to play professionally overseas while remaining connected to the Syracuse basketball community.",
        sourceUrl: "https://en.wikipedia.org/wiki/Malachi_Richardson",
      },
      membership: { role: "PLAYER", jerseyNumber: 23, position: "Shooting Guard", yearsAtSchool: "2015-2016", statsNote: "21 pts in 2nd half vs Virginia Elite Eight • #22 pick • Final Four", gamesPlayed: 37, pointsPerGame: 13.4, reboundsPerGame: 4.3, assistsPerGame: 1.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Syracuse Orange", season: "2015-16", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 37, minutesPerGame: 30.4, pointsPerGame: 13.4, reboundsPerGame: 4.3, assistsPerGame: 1.5, fieldGoalPct: 0.401, threePointPct: 0.336 },
        { level: "PROFESSIONAL", teamName: "Sacramento Kings", season: "2016-17", yearLabel: "2016-17 (Rookie)", sortOrder: 301, gamesPlayed: 34, pointsPerGame: 3.1 },
      ],
      careerEvents: [
        { year: 2016, title: "Led Syracuse to Final Four as 10-seed — 21 pts vs Virginia in comeback", eventType: "MILESTONE", month: 3, day: 27 },
        { year: 2016, title: "Selected #22 overall by Charlotte (traded to Sacramento)", eventType: "DRAFT", month: 6, day: 23 },
        { year: 2021, title: "Won TBT championship with Boeheim's Army", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "tyler-lydon",
      firstName: "Tyler",
      lastName: "Lydon",
      birthYear: 1997,
      hometown: "Pine Plains, NY",
      highSchool: "New Hampton School, New Hampton, NH",
      isFeatured: true,
      bio: "The versatile freshman forward who averaged 10.2 PPG and 6.3 RPG as the only player in the 2016 Final Four to average 30 minutes per game off the bench. His length and shooting range stretched defenses in the zone.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Founder / Head Trainer",
        currentEmployer: "Tyler Lydon Basketball Training",
        location: "New York",
        statusNote: "Selected #24 overall by the Denver Nuggets in 2017 after returning for his sophomore year. Lydon's NBA career was brief — he spent time with Denver and the Sacramento Kings organization before stepping away from playing. He now runs Tyler Lydon Basketball Training, a player development business offering private sessions, group training, camps, and clinics focused on skill development, game strategy, and mental toughness for athletes of all ages.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tyler_Lydon",
      },
      membership: { role: "PLAYER", jerseyNumber: 20, position: "Power Forward", yearsAtSchool: "2015-2017", statsNote: "Only Final Four player averaging 30 MPG off bench • #24 pick", gamesPlayed: 37, pointsPerGame: 10.2, reboundsPerGame: 6.3, assistsPerGame: 1.0 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Syracuse Orange", season: "2015-16", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 37, minutesPerGame: 27.3, pointsPerGame: 10.2, reboundsPerGame: 6.3, fieldGoalPct: 0.468, threePointPct: 0.382 },
      ],
      careerEvents: [
        { year: 2016, title: "Reached Final Four with Syracuse as a freshman", eventType: "MILESTONE" },
        { year: 2017, title: "Selected #24 overall by the Denver Nuggets", eventType: "DRAFT", month: 6, day: 22 },
        { year: 2022, title: "Founded Tyler Lydon Basketball Training", eventType: "CAREER_CHANGE" },
      ],
    },
    {
      slug: "michael-gbinije",
      firstName: "Michael",
      lastName: "Gbinije",
      birthYear: 1993,
      hometown: "Stamford, CT",
      highSchool: "Benedictine High School, Richmond, VA",
      bio: "The senior captain and leading scorer who transferred from Duke and became the heart of the Final Four team. A mature, complete player who orchestrated the offense in Boeheim's 2-3 zone.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Professional Basketball Player",
        location: "Connecticut",
        statusNote: "After going undrafted in 2016, Gbinije played briefly with the Detroit Pistons on a two-way contract and spent time in the G League before playing overseas. He originally started his college career at Duke (2011-13) before transferring to Syracuse for two seasons. His journey from transferring out of Duke to leading a team to the Final Four is one of the best stories of the transfer portal era.",
        sourceUrl: "https://en.wikipedia.org/wiki/Michael_Gbinije",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Guard / Forward", yearsAtSchool: "2013-2016", statsNote: "Senior captain • Transfer from Duke • Team leader • Final Four", gamesPlayed: 37, pointsPerGame: 17.5, reboundsPerGame: 4.1, assistsPerGame: 4.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Syracuse Orange", season: "2015-16", yearLabel: "Senior", sortOrder: 204, gamesPlayed: 37, minutesPerGame: 37.0, pointsPerGame: 17.5, reboundsPerGame: 4.1, assistsPerGame: 4.2, stealsPerGame: 1.5, fieldGoalPct: 0.440, threePointPct: 0.339 },
      ],
      careerEvents: [
        { year: 2016, title: "Led Syracuse to Final Four as senior captain", eventType: "MILESTONE" },
      ],
    },
    {
      slug: "tyler-roberson",
      firstName: "Tyler",
      lastName: "Roberson",
      birthYear: 1994,
      hometown: "East Orange, NJ",
      highSchool: "Roselle Catholic High School, Roselle, NJ",
      bio: "A junior forward whose rebounding and defensive intensity were critical to the 2-3 zone. He grabbed double-digit rebounds multiple times during the tournament run.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Professional Basketball Player",
        location: "New Jersey",
        statusNote: "After four years at Syracuse, Roberson played professional basketball overseas before transitioning to a post-playing career. He remains connected to the Syracuse basketball alumni community.",
        sourceUrl: "https://cuse.com/sports/mens-basketball/roster/tyler-roberson/",
      },
      membership: { role: "PLAYER", jerseyNumber: 43, position: "Power Forward", yearsAtSchool: "2013-2017", statsNote: "Rebounding machine • Zone anchor • Final Four", gamesPlayed: 35, pointsPerGame: 6.6, reboundsPerGame: 6.6 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Syracuse Orange", season: "2015-16", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 35, minutesPerGame: 23.0, pointsPerGame: 6.6, reboundsPerGame: 6.6, fieldGoalPct: 0.520 },
      ],
      careerEvents: [
        { year: 2016, title: "Reached Final Four with Syracuse", eventType: "MILESTONE" },
      ],
    },
    {
      slug: "trevor-cooney",
      firstName: "Trevor",
      lastName: "Cooney",
      birthYear: 1993,
      hometown: "Sanford, FL",
      highSchool: "Seminole High School, Sanford, FL",
      bio: "The senior sharpshooter whose three-point shooting was the most dangerous weapon in the zone offense. When Cooney got hot from three, the Syracuse zone was nearly unbeatable.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Professional Basketball Player",
        location: "Florida",
        statusNote: "After his senior season at Syracuse, Cooney played professionally overseas in Germany and Greece before transitioning away from playing. He has remained connected to the Syracuse alumni basketball community and participates in TBT events with Boeheim's Army.",
        sourceUrl: "https://cuse.com/sports/mens-basketball/roster/trevor-cooney/",
      },
      membership: { role: "PLAYER", jerseyNumber: 10, position: "Shooting Guard", yearsAtSchool: "2012-2016", statsNote: "Senior sniper • 3-point specialist • Final Four", gamesPlayed: 37, pointsPerGame: 12.4, reboundsPerGame: 2.4, assistsPerGame: 1.1 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Syracuse Orange", season: "2015-16", yearLabel: "Senior", sortOrder: 204, gamesPlayed: 37, minutesPerGame: 31.5, pointsPerGame: 12.4, reboundsPerGame: 2.4, threePointPct: 0.341, fieldGoalPct: 0.384 },
      ],
      careerEvents: [
        { year: 2016, title: "Reached Final Four with Syracuse as a senior", eventType: "MILESTONE" },
      ],
    },
    {
      slug: "dajuan-coleman",
      firstName: "DaJuan",
      lastName: "Coleman",
      birthYear: 1994,
      hometown: "Jamesville, NY",
      highSchool: "Jamesville-DeWitt High School, Jamesville, NY",
      bio: "The junior center and local product who overcame multiple knee surgeries to contribute to the Final Four run. His perseverance through injuries made him a beloved figure in the program.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Syracuse, NY",
        statusNote: "Coleman's career was derailed by knee injuries — he had two major knee surgeries during his time at Syracuse. After graduating, he remained in the Syracuse area and has been involved in community work and youth basketball. His story of overcoming adversity despite never reaching his full potential due to injuries is one of the most poignant in Syracuse basketball history.",
        sourceUrl: "https://cuse.com/sports/mens-basketball/roster/dajuan-coleman/",
      },
      membership: { role: "PLAYER", jerseyNumber: 32, position: "Center", yearsAtSchool: "2013-2017", statsNote: "Local product • Overcame knee surgeries • Final Four", gamesPlayed: 30, pointsPerGame: 5.6, reboundsPerGame: 4.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Syracuse Orange", season: "2015-16", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 30, minutesPerGame: 15.0, pointsPerGame: 5.6, reboundsPerGame: 4.2, fieldGoalPct: 0.550 },
      ],
      careerEvents: [
        { year: 2016, title: "Reached Final Four with Syracuse", eventType: "MILESTONE" },
      ],
    },
    {
      slug: "gerry-mcnamara",
      firstName: "Gerry",
      lastName: "McNamara",
      birthYear: 1983,
      hometown: "Scranton, PA",
      highSchool: "Bishop Hannan High School, Scranton, PA",
      bio: "Former Syracuse star guard (2002-06) who became Jim Boeheim's top assistant. Known as one of the greatest players in Syracuse history — hit 6 threes in the 2003 title game.",
      status: { occupationType: "COACH", currentTitle: "Assistant Coach", currentEmployer: "Syracuse University", location: "Syracuse, NY", statusNote: "After a brief professional career, McNamara joined Boeheim's coaching staff and has been a Syracuse assistant since 2011. He is widely considered the leading candidate to eventually become Syracuse's head coach. As a player, he hit 6 three-pointers in the 2003 national championship game against Kansas.", sourceUrl: "https://en.wikipedia.org/wiki/Gerry_McNamara" },
      membership: { role: "ASSISTANT_COACH", position: "Assistant Coach", yearsAtSchool: "2011-present" },
      careerEvents: [],
    },
    {
      slug: "jim-boeheim",
      firstName: "Jim",
      lastName: "Boeheim",
      birthYear: 1944,
      hometown: "Lyons, NY",
      highSchool: "Lyons Central High School, Lyons, NY",
      isFeatured: true,
      bio: "The legendary Hall of Fame coach who led Syracuse to the Final Four in his 40th season — a run that came amid NCAA sanctions that forced him to serve a 9-game suspension earlier in the season. His 2-3 zone defense remains one of the most iconic systems in college basketball.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Head Coach Emeritus / Senior Advisor",
        currentEmployer: "Syracuse University (Emeritus)",
        location: "Syracuse, NY",
        statusNote: "Jim Boeheim retired after the 2022-23 season with 1,015 career victories — second most in Division I history at the time of his retirement. He coached Syracuse for 47 seasons (1976-2023), winning the 2003 national championship and reaching five Final Fours. His signature 2-3 zone defense became synonymous with Syracuse basketball. He was inducted into the Naismith Basketball Hall of Fame in 2005. He was succeeded by his longtime assistant Adrian Autry. Boeheim remains a senior advisor to the program and a prominent figure in the Syracuse community.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jim_Boeheim",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "1976-2023", statsNote: "1,015 career wins • 2003 NCAA Champion • Hall of Fame • 2-3 zone architect" },
      seasonStats: [
        { level: "COACHING", teamName: "Syracuse Orange", season: "2015-16", yearLabel: "2015-16", sortOrder: 240, wins: 23, losses: 14, tournamentResult: "Final Four (10-seed)" },
      ],
      careerEvents: [
        { year: 2003, title: "Won NCAA National Championship with Syracuse", eventType: "CHAMPIONSHIP" },
        { year: 2005, title: "Inducted into Naismith Basketball Hall of Fame", eventType: "AWARD" },
        { year: 2016, title: "Led 10-seed Syracuse to Final Four in 40th season", eventType: "MILESTONE" },
        { year: 2023, title: "Retired with 1,015 career victories — 47 seasons at Syracuse", eventType: "RETIREMENT" },
      ],
    },
  ],
};
