import type { TeamSeed } from "./types";

export const syracuseBasketball2012: TeamSeed = {
  slug: "syracuse-basketball-2012",
  name: "Syracuse Orange",
  season: "2011-2012",
  sport: "Men's Basketball",
  school: "Syracuse University",
  conference: "ACC",
  accomplishment: "2011-2012 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/183.png",
  mascotName: "Orange",
  people: [
    {
      slug: "kris-joseph",
      firstName: "Kris",
      lastName: "Joseph",
      birthYear: 1988,
      hometown: "United States",
      highSchool: "United States",
      bio: "Senior captain. Drafted by Celtics.",
      status: { occupationType: "RETIRED_ATHLETE", currentTitle: "Professional", location: "Canada", statusNote: "Played for Celtics and overseas.", sourceUrl: "https://en.wikipedia.org/wiki/Kris_Joseph" },
      membership: { role: "PLAYER", jerseyNumber: 32, position: "Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 14.5, reboundsPerGame: 5, assistsPerGame: 2 },
      seasonStats: [{ level: "COLLEGE", teamName: "Syracuse Orange", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 14.5, reboundsPerGame: 5, assistsPerGame: 2 }],
      careerEvents: [],
    },
    {
      slug: "dion-waiters",
      firstName: "Dion",
      lastName: "Waiters",
      birthYear: 1991,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore star. #4 pick in 2012.",
      status: { occupationType: "RETIRED_ATHLETE", currentTitle: "Retired NBA Player", location: "Philadelphia, PA", statusNote: "#4 pick by Cavs. 8 NBA seasons. Won 2020 NBA title with Lakers.", sourceUrl: "https://en.wikipedia.org/wiki/Dion_Waiters" },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 12.5, reboundsPerGame: 2.5, assistsPerGame: 2.5 },
      seasonStats: [{ level: "COLLEGE", teamName: "Syracuse Orange", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 12.5, reboundsPerGame: 2.5, assistsPerGame: 2.5 }],
      careerEvents: [],
    },
    {
      slug: "fab-melo",
      firstName: "Fab",
      lastName: "Melo",
      birthYear: 1990,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore center. #22 pick. Tragically passed away in 2017.",
      status: { occupationType: "OTHER", currentTitle: "Deceased", location: "Brazil", statusNote: "Selected #22 by Celtics in 2012. Tragically died in 2017 at age 26 in Brazil.", sourceUrl: "https://en.wikipedia.org/wiki/Fab_Melo" },
      membership: { role: "PLAYER", jerseyNumber: 51, position: "Center", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 7.8, reboundsPerGame: 5.8, assistsPerGame: 0.3 },
      seasonStats: [{ level: "COLLEGE", teamName: "Syracuse Orange", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 7.8, reboundsPerGame: 5.8, assistsPerGame: 0.3 }],
      careerEvents: [],
    },
    {
      slug: "jim-boeheim",
      firstName: "Jim",
      lastName: "Boeheim",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Legendary coach with 1,015 career wins. 2003 champion. 2-3 zone architect. Retired after 47 seasons.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Retired 2023. Head Coach Emeritus at Syracuse.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jim_Boeheim",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2023" },
      seasonStats: [
        { level: "COACHING", teamName: "Syracuse Orange", season: "2011-2012", yearLabel: "2011-2012", sortOrder: 204 },
      ],
      careerEvents: [],
    },
  ],
};
