import type { TeamSeed } from "./types";

export const syracuseBasketball2009: TeamSeed = {
  slug: "syracuse-basketball-2009",
  name: "Syracuse Orange",
  season: "2008-2009",
  sport: "Men's Basketball",
  school: "Syracuse University",
  conference: "ACC",
  accomplishment: "2008-2009 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/183.png",
  mascotName: "Orange",
  people: [
    {
      slug: "jonny-flynn",
      firstName: "Jonny",
      lastName: "Flynn",
      birthYear: 1989,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore star who was #6 pick. Led Cuse to NCAA Tourney.",
      status: { occupationType: "RETIRED_ATHLETE", currentTitle: "Retired", location: "United States", statusNote: "#6 pick by Timberwolves in 2009. Career derailed by hip injuries after 3 NBA seasons.", sourceUrl: "https://en.wikipedia.org/wiki/Jonny_Flynn" },
      membership: { role: "PLAYER", jerseyNumber: 10, position: "Point Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 17.4, reboundsPerGame: 3, assistsPerGame: 6.7 },
      seasonStats: [{ level: "COLLEGE", teamName: "Syracuse Orange", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 17.4, reboundsPerGame: 3, assistsPerGame: 6.7 }],
      careerEvents: [],
    },
    {
      slug: "eric-devendorf",
      firstName: "Eric",
      lastName: "Devendorf",
      birthYear: 1987,
      hometown: "United States",
      highSchool: "United States",
      bio: "Senior guard and team's emotional leader.",
      status: { occupationType: "RETIRED_ATHLETE", currentTitle: "Professional", location: "United States", statusNote: "Played overseas after Syracuse.", sourceUrl: "https://en.wikipedia.org/wiki/Eric_Devendorf" },
      membership: { role: "PLAYER", jerseyNumber: 23, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 14.5, reboundsPerGame: 2.5, assistsPerGame: 2.5 },
      seasonStats: [{ level: "COLLEGE", teamName: "Syracuse Orange", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 14.5, reboundsPerGame: 2.5, assistsPerGame: 2.5 }],
      careerEvents: [],
    },
    {
      slug: "jim-boeheim",
      firstName: "Jim",
      lastName: "Boeheim",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Legendary coach with 1,015 career wins. 2003 champion. 2-3 zone architect. Retired after 47 seasons.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Retired 2023. Head Coach Emeritus at Syracuse.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jim_Boeheim",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2023" },
      seasonStats: [
        { level: "COACHING", teamName: "Syracuse Orange", season: "2008-2009", yearLabel: "2008-2009", sortOrder: 201 },
      ],
      careerEvents: [],
    },
  ],
};
