import type { TeamSeed } from "./types";

export const syracuseBasketball2018: TeamSeed = {
  slug: "syracuse-basketball-2018",
  name: "Syracuse Orange",
  season: "2017-2018",
  sport: "Men's Basketball",
  school: "Syracuse University",
  conference: "ACC",
  accomplishment: "2017-2018 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/183.png",
  mascotName: "Orange",
  people: [
    {
      slug: "tyus-battle",
      firstName: "Tyus",
      lastName: "Battle",
      birthYear: 1997,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore guard and team's best scorer.",
      status: { occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Pro Player", location: "Overseas", statusNote: "3-year starter. Played overseas after Syracuse.", sourceUrl: "https://en.wikipedia.org/wiki/Tyus_Battle" },
      membership: { role: "PLAYER", jerseyNumber: 25, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 19.2, reboundsPerGame: 3, assistsPerGame: 2 },
      seasonStats: [{ level: "COLLEGE", teamName: "Syracuse Orange", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 19.2, reboundsPerGame: 3, assistsPerGame: 2 }],
      careerEvents: [],
    },
    {
      slug: "oshae-brissett",
      firstName: "Oshae",
      lastName: "Brissett",
      birthYear: 1998,
      hometown: "United States",
      highSchool: "United States",
      bio: "Freshman forward from Canada.",
      status: { occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Forward", location: "United States", statusNote: "Played for Pacers and Celtics. NBA career ongoing.", sourceUrl: "https://en.wikipedia.org/wiki/Oshae_Brissett" },
      membership: { role: "PLAYER", jerseyNumber: 11, position: "Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 14, reboundsPerGame: 7, assistsPerGame: 1.5 },
      seasonStats: [{ level: "COLLEGE", teamName: "Syracuse Orange", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 14, reboundsPerGame: 7, assistsPerGame: 1.5 }],
      careerEvents: [],
    },
    {
      slug: "jim-boeheim",
      firstName: "Jim",
      lastName: "Boeheim",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Legendary coach with 1,015 career wins. 2003 champion. 2-3 zone architect. Retired after 47 seasons.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Retired 2023. Head Coach Emeritus at Syracuse.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jim_Boeheim",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2023" },
      seasonStats: [
        { level: "COACHING", teamName: "Syracuse Orange", season: "2017-2018", yearLabel: "2017-2018", sortOrder: 210 },
      ],
      careerEvents: [],
    },
  ],
};
