import type { TeamSeed } from "./types";

export const syracuseBasketball2011: TeamSeed = {
  slug: "syracuse-basketball-2011",
  name: "Syracuse Orange",
  season: "2010-2011",
  sport: "Men's Basketball",
  school: "Syracuse University",
  conference: "ACC",
  accomplishment: "2010-2011 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/183.png",
  mascotName: "Orange",
  people: [
    {
      slug: "kris-joseph",
      firstName: "Kris",
      lastName: "Joseph",
      birthYear: 1988,
      hometown: "United States",
      highSchool: "United States",
      bio: "Junior forward from Montreal.",
      status: { occupationType: "RETIRED_ATHLETE", currentTitle: "Professional", location: "Canada", statusNote: "Played for Celtics and overseas. Canadian national team.", sourceUrl: "https://en.wikipedia.org/wiki/Kris_Joseph" },
      membership: { role: "PLAYER", jerseyNumber: 32, position: "Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 14, reboundsPerGame: 4.5, assistsPerGame: 1.5 },
      seasonStats: [{ level: "COLLEGE", teamName: "Syracuse Orange", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 14, reboundsPerGame: 4.5, assistsPerGame: 1.5 }],
      careerEvents: [],
    },
    {
      slug: "scoop-jardine",
      firstName: "Scoop",
      lastName: "Jardine",
      birthYear: 1989,
      hometown: "United States",
      highSchool: "United States",
      bio: "Junior point guard and floor general.",
      status: { occupationType: "RETIRED_ATHLETE", currentTitle: "Professional", location: "United States", statusNote: "Played overseas after Syracuse.", sourceUrl: "https://en.wikipedia.org/wiki/Scoop_Jardine" },
      membership: { role: "PLAYER", jerseyNumber: 11, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 10, reboundsPerGame: 3, assistsPerGame: 4.5 },
      seasonStats: [{ level: "COLLEGE", teamName: "Syracuse Orange", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 10, reboundsPerGame: 3, assistsPerGame: 4.5 }],
      careerEvents: [],
    },
    {
      slug: "jim-boeheim",
      firstName: "Jim",
      lastName: "Boeheim",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Legendary coach with 1,015 career wins. 2003 champion. 2-3 zone architect. Retired after 47 seasons.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Retired 2023. Head Coach Emeritus at Syracuse.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jim_Boeheim",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2023" },
      seasonStats: [
        { level: "COACHING", teamName: "Syracuse Orange", season: "2010-2011", yearLabel: "2010-2011", sortOrder: 203 },
      ],
      careerEvents: [],
    },
  ],
};
