import type { TeamSeed } from "./types";

export const syracuseBasketball2025: TeamSeed = {
  slug: "syracuse-basketball-2025",
  name: "Syracuse Orange",
  season: "2024-2025",
  sport: "Men's Basketball",
  school: "Syracuse University",
  conference: "ACC",
  accomplishment: "2024-2025 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/183.png",
  mascotName: "Orange",
  people: [
    {
      slug: "jj-starling",
      firstName: "J.J.",
      lastName: "Starling",
      birthYear: 2003,
      hometown: "United States",
      highSchool: "United States",
      bio: "Notre Dame transfer. Team's top scorer under Adrian Autry.",
      status: { occupationType: "STUDENT", currentTitle: "College Player", location: "Syracuse, NY", statusNote: "Notre Dame transfer providing scoring.", sourceUrl: "https://en.wikipedia.org/wiki/J.J._Starling" },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 15, reboundsPerGame: 3, assistsPerGame: 2.5 },
      seasonStats: [{ level: "COLLEGE", teamName: "Syracuse Orange", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 15, reboundsPerGame: 3, assistsPerGame: 2.5 }],
      careerEvents: [],
    },
    {
      slug: "adrian-autry",
      firstName: "Adrian",
      lastName: "Autry",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Former Syracuse player and longtime Boeheim assistant who succeeded the legend.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Currently coaching at Syracuse.",
        sourceUrl: "https://en.wikipedia.org/wiki/Adrian_Autry",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2024-2026" },
      seasonStats: [
        { level: "COACHING", teamName: "Syracuse Orange", season: "2024-2025", yearLabel: "2024-2025", sortOrder: 217 },
      ],
      careerEvents: [],
    },
  ],
};
