import type { TeamSeed } from "./types";

export const syracuseBasketball2010: TeamSeed = {
  slug: "syracuse-basketball-2010",
  name: "Syracuse Orange",
  season: "2009-2010",
  sport: "Men's Basketball",
  school: "Syracuse University",
  conference: "ACC",
  accomplishment: "2009-2010 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/183.png",
  mascotName: "Orange",
  people: [
    {
      slug: "wes-johnson",
      firstName: "Wes",
      lastName: "Johnson",
      birthYear: 1987,
      hometown: "United States",
      highSchool: "United States",
      bio: "Syracuse transfer who was #4 pick in 2010.",
      status: { occupationType: "RETIRED_ATHLETE", currentTitle: "Retired NBA Player", location: "United States", statusNote: "#4 overall pick by Timberwolves. 9 NBA seasons.", sourceUrl: "https://en.wikipedia.org/wiki/Wes_Johnson" },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 16.5, reboundsPerGame: 6, assistsPerGame: 2 },
      seasonStats: [{ level: "COLLEGE", teamName: "Syracuse Orange", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 16.5, reboundsPerGame: 6, assistsPerGame: 2 }],
      careerEvents: [],
    },
    {
      slug: "andy-rautins",
      firstName: "Andy",
      lastName: "Rautins",
      birthYear: 1986,
      hometown: "United States",
      highSchool: "United States",
      bio: "Senior sharpshooter. Canadian national team member.",
      status: { occupationType: "RETIRED_ATHLETE", currentTitle: "Professional", location: "Canada", statusNote: "Played for Knicks and overseas. Son of Syracuse legend Leo Rautins.", sourceUrl: "https://en.wikipedia.org/wiki/Andy_Rautins" },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 12, reboundsPerGame: 3, assistsPerGame: 4 },
      seasonStats: [{ level: "COLLEGE", teamName: "Syracuse Orange", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 12, reboundsPerGame: 3, assistsPerGame: 4 }],
      careerEvents: [],
    },
    {
      slug: "jim-boeheim",
      firstName: "Jim",
      lastName: "Boeheim",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Legendary coach with 1,015 career wins. 2003 champion. 2-3 zone architect. Retired after 47 seasons.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Retired 2023. Head Coach Emeritus at Syracuse.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jim_Boeheim",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2023" },
      seasonStats: [
        { level: "COACHING", teamName: "Syracuse Orange", season: "2009-2010", yearLabel: "2009-2010", sortOrder: 202 },
      ],
      careerEvents: [],
    },
  ],
};
