import type { TeamSeed } from "./types";

export const syracuseBasketball2020: TeamSeed = {
  slug: "syracuse-basketball-2020",
  name: "Syracuse Orange",
  season: "2019-2020",
  sport: "Men's Basketball",
  school: "Syracuse University",
  conference: "ACC",
  accomplishment: "2019-2020 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/183.png",
  mascotName: "Orange",
  people: [
    {
      slug: "elijah-hughes",
      firstName: "Elijah",
      lastName: "Hughes",
      birthYear: 1998,
      hometown: "United States",
      highSchool: "United States",
      bio: "Junior wing. Team's leading scorer and All-ACC.",
      status: { occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Pro Player", location: "Overseas", statusNote: "Drafted by Jazz. Played in G League and overseas.", sourceUrl: "https://en.wikipedia.org/wiki/Elijah_Hughes" },
      membership: { role: "PLAYER", jerseyNumber: 33, position: "Guard/Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 19, reboundsPerGame: 5, assistsPerGame: 3.5 },
      seasonStats: [{ level: "COLLEGE", teamName: "Syracuse Orange", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 19, reboundsPerGame: 5, assistsPerGame: 3.5 }],
      careerEvents: [],
    },
    {
      slug: "jim-boeheim",
      firstName: "Jim",
      lastName: "Boeheim",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Legendary coach with 1,015 career wins. 2003 champion. 2-3 zone architect. Retired after 47 seasons.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Retired 2023. Head Coach Emeritus at Syracuse.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jim_Boeheim",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2023" },
      seasonStats: [
        { level: "COACHING", teamName: "Syracuse Orange", season: "2019-2020", yearLabel: "2019-2020", sortOrder: 212 },
      ],
      careerEvents: [],
    },
  ],
};
