import type { TeamSeed } from "./types";

export const syracuseBasketball2013: TeamSeed = {
  slug: "syracuse-basketball-2013",
  name: "Syracuse Orange",
  season: "2012-2013",
  sport: "Men's Basketball",
  school: "Syracuse University",
  conference: "Big East (final season)",
  accomplishment: "Final Four (30-10) — last Big East season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/183.png",
  mascotName: "Orange",
  people: [
    {
      slug: "michael-carter-williams",
      firstName: "Michael",
      lastName: "Carter-Williams",
      birthYear: 1991,
      hometown: "Hamilton, MA",
      highSchool: "St. Andrew's School, Barrington, RI",
      isFeatured: true,
      bio: "The sophomore point guard who led Syracuse to the Final Four and was selected #11 overall, then won the 2014 NBA Rookie of the Year award with Philadelphia — the first Syracuse player to win the award.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NBA Player / Media",
        location: "Massachusetts",
        statusNote: "Selected #11 overall by the Philadelphia 76ers in 2013, MCW famously won the 2014 NBA Rookie of the Year despite being traded mid-season from Philadelphia to Milwaukee. He played 8 NBA seasons with the 76ers, Bucks, Bulls, Hornets, Magic, and Rockets. Known for his size at the PG position (6'6\") and his triple-double in his first NBA game. After retiring, he has been involved in media and basketball content creation.",
        sourceUrl: "https://en.wikipedia.org/wiki/Michael_Carter-Williams",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Point Guard", yearsAtSchool: "2011-2013", statsNote: "#11 pick • NBA ROY • Triple-double in NBA debut • Final Four", gamesPlayed: 40, pointsPerGame: 11.9, reboundsPerGame: 4.9, assistsPerGame: 7.3 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Syracuse Orange", season: "2012-13", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 40, minutesPerGame: 32.0, pointsPerGame: 11.9, reboundsPerGame: 4.9, assistsPerGame: 7.3, stealsPerGame: 2.5, fieldGoalPct: 0.408 },
        { level: "PROFESSIONAL", teamName: "Philadelphia 76ers", season: "2013-14", yearLabel: "2013-14 (ROY)", sortOrder: 301, gamesPlayed: 70, pointsPerGame: 16.7, reboundsPerGame: 6.3, assistsPerGame: 6.3 },
      ],
      careerEvents: [
        { year: 2013, title: "Led Syracuse to Final Four", eventType: "MILESTONE" },
        { year: 2013, title: "Selected #11 overall by the Philadelphia 76ers", eventType: "DRAFT", month: 6, day: 27 },
        { year: 2013, title: "Recorded triple-double in first NBA game", eventType: "MILESTONE" },
        { year: 2014, title: "Won NBA Rookie of the Year", eventType: "AWARD" },
      ],
    },
    {
      slug: "jerami-grant",
      firstName: "Jerami",
      lastName: "Grant",
      birthYear: 1994,
      hometown: "Portland, OR",
      highSchool: "DeMatha Catholic High School, Hyattsville, MD",
      isFeatured: true,
      bio: "A freshman forward from a basketball family (father Harvey and uncle Horace were NBA players) who provided explosive athleticism off the bench during the Final Four run. Went on to have a decade-long NBA All-Star caliber career.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Portland Trail Blazers",
        league: "NBA",
        location: "Portland, OR",
        statusNote: "Selected #39 overall by the 76ers in 2014, Grant developed into an All-Star caliber player with the Denver Nuggets, Detroit Pistons, and Portland Trail Blazers. He averaged 20+ PPG multiple seasons and was named to the 2021 All-Star team. He signed a 5-year, $160M contract with Portland in 2022. Part of the Grant basketball family — his father Harvey played 11 NBA seasons and his uncle Horace won 4 NBA championships.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jerami_Grant",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Forward", yearsAtSchool: "2012-2014", statsNote: "Freshman • NBA Grant family • Future All-Star • $160M contract • Final Four", gamesPlayed: 40, pointsPerGame: 7.5, reboundsPerGame: 4.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Syracuse Orange", season: "2012-13", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 40, minutesPerGame: 19.0, pointsPerGame: 7.5, reboundsPerGame: 4.5, blocksPerGame: 1.0, fieldGoalPct: 0.480 },
        { level: "PROFESSIONAL", teamName: "Detroit Pistons", season: "2020-21", yearLabel: "2020-21 (All-Star)", sortOrder: 307, gamesPlayed: 54, pointsPerGame: 22.3, reboundsPerGame: 4.6 },
      ],
      careerEvents: [
        { year: 2013, title: "Reached Final Four with Syracuse as a freshman", eventType: "MILESTONE" },
        { year: 2014, title: "Selected #39 overall by the Philadelphia 76ers", eventType: "DRAFT" },
        { year: 2021, title: "Named NBA All-Star with the Detroit Pistons", eventType: "AWARD" },
        { year: 2022, title: "Signed 5-year, $160M contract with Portland Trail Blazers", eventType: "SIGNING" },
      ],
    },
    {
      slug: "brandon-triche",
      firstName: "Brandon",
      lastName: "Triche",
      birthYear: 1990,
      hometown: "Jamesville, NY",
      highSchool: "Jamesville-DeWitt High School, Jamesville, NY",
      bio: "The senior guard and local Syracuse product who was the team's most experienced player during the Final Four run. His scoring ability and leadership as a hometown hero made him beloved by the Carrier Dome faithful.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Professional",
        location: "Syracuse, NY",
        statusNote: "After graduating from Syracuse, Triche played professionally overseas in France and Italy before returning to the Syracuse area. The local Jamesville-DeWitt product remains connected to the Orange basketball community.",
        sourceUrl: "https://cuse.com/sports/mens-basketball/roster/brandon-triche/",
      },
      membership: { role: "PLAYER", jerseyNumber: 20, position: "Guard", yearsAtSchool: "2009-2013", statsNote: "Senior • Local Syracuse product • Carrier Dome hero • Final Four", gamesPlayed: 40, pointsPerGame: 13.2, reboundsPerGame: 2.5, assistsPerGame: 3.0 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Syracuse Orange", season: "2012-13", yearLabel: "Senior", sortOrder: 204, gamesPlayed: 40, minutesPerGame: 30.0, pointsPerGame: 13.2, reboundsPerGame: 2.5, assistsPerGame: 3.0, fieldGoalPct: 0.425, threePointPct: 0.370 },
      ],
      careerEvents: [
        { year: 2013, title: "Reached Final Four with Syracuse as a senior captain", eventType: "MILESTONE" },
      ],
    },
    {
      slug: "cj-fair",
      firstName: "C.J.",
      lastName: "Fair",
      birthYear: 1991,
      hometown: "Baltimore, MD",
      highSchool: "Cardinal Gibbons School, Baltimore, MD",
      bio: "A junior forward who was Syracuse's second-leading scorer and most versatile offensive weapon. His ability to score from all three levels made him a matchup nightmare in the zone offense.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "Overseas",
        location: "Europe",
        statusNote: "After returning for his senior year and being named to several All-American teams, Fair went undrafted in 2014 but has built a long professional career overseas in Europe, the Middle East, and Asia. He has played professionally for over a decade across multiple countries.",
        sourceUrl: "https://en.wikipedia.org/wiki/C._J._Fair",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Forward", yearsAtSchool: "2010-2014", statsNote: "Junior • Second-leading scorer • Versatile offensive weapon • Final Four", gamesPlayed: 40, pointsPerGame: 14.5, reboundsPerGame: 5.0 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Syracuse Orange", season: "2012-13", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 40, minutesPerGame: 28.0, pointsPerGame: 14.5, reboundsPerGame: 5.0, fieldGoalPct: 0.450 },
      ],
      careerEvents: [
        { year: 2013, title: "Reached Final Four with Syracuse", eventType: "MILESTONE" },
      ],
    },
    {
      slug: "rakeem-christmas",
      firstName: "Rakeem",
      lastName: "Christmas",
      birthYear: 1991,
      hometown: "Philadelphia, PA",
      highSchool: "Prep School / Philadelphia, PA",
      bio: "A sophomore center from Philadelphia who provided rim protection and interior scoring. His shot-blocking in the 2-3 zone made him a crucial piece of Boeheim's defense.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "Overseas",
        location: "Europe",
        statusNote: "Christmas stayed 4 years at Syracuse and was named the 2015 ACC Defensive Player of the Year as a senior. He was selected #36 overall by the Indiana Pacers in 2015. After brief NBA time, he has played professionally overseas for nearly a decade.",
        sourceUrl: "https://en.wikipedia.org/wiki/Rakeem_Christmas",
      },
      membership: { role: "PLAYER", jerseyNumber: 25, position: "Center", yearsAtSchool: "2011-2015", statsNote: "Sophomore • Shot-blocker • Future ACC DPOY • Final Four", gamesPlayed: 40, pointsPerGame: 5.5, reboundsPerGame: 4.0 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Syracuse Orange", season: "2012-13", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 40, minutesPerGame: 16.0, pointsPerGame: 5.5, reboundsPerGame: 4.0 },
      ],
      careerEvents: [
        { year: 2013, title: "Reached Final Four with Syracuse", eventType: "MILESTONE" },
        { year: 2015, title: "Named ACC Defensive Player of the Year", eventType: "AWARD" },
        { year: 2015, title: "Selected #36 overall by the Indiana Pacers", eventType: "DRAFT" },
      ],
    },
    {
      slug: "jim-boeheim",
      firstName: "Jim",
      lastName: "Boeheim",
      birthYear: 1944,
      hometown: "Lyons, NY",
      highSchool: "Lyons Central High School, Lyons, NY",
      isFeatured: true,
      bio: "Led Syracuse to their second Final Four under his watch and their last before the program's move to the ACC. The 2013 team went 30-10 in the Big East's final season before conference realignment.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Head Coach Emeritus / Senior Advisor",
        currentEmployer: "Syracuse University (Emeritus)",
        location: "Syracuse, NY",
        statusNote: "Jim Boeheim retired after the 2022-23 season with 1,015 career victories — second most in Division I history. He coached Syracuse for 47 seasons (1976-2023), winning the 2003 championship and reaching 5 Final Fours.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jim_Boeheim",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "1976-2023", statsNote: "1,015 wins • 2003 Champion • 5 Final Fours • 2-3 zone legend" },
      seasonStats: [
        { level: "COACHING", teamName: "Syracuse Orange", season: "2012-13", yearLabel: "2012-13", sortOrder: 237, wins: 30, losses: 10, tournamentResult: "Final Four (Big East's final season)" },
      ],
      careerEvents: [],
    },
  ],
};
