import type { TeamSeed } from "./types";

export const syracuseBasketball2017: TeamSeed = {
  slug: "syracuse-basketball-2017",
  name: "Syracuse Orange",
  season: "2016-2017",
  sport: "Men's Basketball",
  school: "Syracuse University",
  conference: "ACC",
  accomplishment: "2016-2017 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/183.png",
  mascotName: "Orange",
  people: [
    {
      slug: "john-gillon",
      firstName: "John",
      lastName: "Gillon",
      birthYear: 1993,
      hometown: "United States",
      highSchool: "United States",
      bio: "Grad transfer who provided veteran backcourt play.",
      status: { occupationType: "ACTIVE_PRO_ATHLETE", currentTitle: "Pro Player", location: "Overseas", statusNote: "Played overseas in Israel, Greece, and Italy.", sourceUrl: "https://en.wikipedia.org/wiki/John_Gillon" },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 11, reboundsPerGame: 2, assistsPerGame: 5 },
      seasonStats: [{ level: "COLLEGE", teamName: "Syracuse Orange", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 11, reboundsPerGame: 2, assistsPerGame: 5 }],
      careerEvents: [],
    },
    {
      slug: "andrew-white-iii",
      firstName: "Andrew",
      lastName: "White III",
      birthYear: 1993,
      hometown: "United States",
      highSchool: "United States",
      bio: "Grad transfer and team's leading scorer.",
      status: { occupationType: "RETIRED_ATHLETE", currentTitle: "Professional", location: "United States", statusNote: "Played overseas after Syracuse.", sourceUrl: "https://en.wikipedia.org/wiki/Andrew_White_III" },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 18.5, reboundsPerGame: 5, assistsPerGame: 1 },
      seasonStats: [{ level: "COLLEGE", teamName: "Syracuse Orange", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 18.5, reboundsPerGame: 5, assistsPerGame: 1 }],
      careerEvents: [],
    },
    {
      slug: "jim-boeheim",
      firstName: "Jim",
      lastName: "Boeheim",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Legendary coach with 1,015 career wins. 2003 champion. 2-3 zone architect. Retired after 47 seasons.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Retired 2023. Head Coach Emeritus at Syracuse.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jim_Boeheim",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2023" },
      seasonStats: [
        { level: "COACHING", teamName: "Syracuse Orange", season: "2016-2017", yearLabel: "2016-2017", sortOrder: 209 },
      ],
      careerEvents: [],
    },
  ],
};
