import type { TeamSeed } from "./types";

export const texasBasketball2003: TeamSeed = {
  slug: "texas-basketball-2003",
  name: "Texas Longhorns",
  season: "2002-2003",
  sport: "Men's Basketball",
  school: "University of Texas",
  conference: "Big 12",
  accomplishment: "#1 Seed, Final Four (26-7)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/251.png",
  mascotName: "Bevo",
  people: [
    {
      slug: "tj-ford",
      firstName: "T.J.",
      lastName: "Ford",
      birthYear: 1983,
      hometown: "Houston, TX",
      highSchool: "Willowridge High School, Missouri City, TX",
      isFeatured: true,
      bio: "The 2003 Naismith and Wooden Award winner who led Texas to the program's first Final Four since 1947. The first freshman in NCAA history to lead the nation in assists, Ford was a generational point guard whose jersey #11 was retired at Texas.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Founder & Director",
        currentEmployer: "T.J. Ford Academy",
        location: "Houston, TX",
        statusNote:
          "Selected #8 overall by Milwaukee in 2003 after winning the Naismith and Wooden Awards as a sophomore. Played 8 NBA seasons with the Bucks, Raptors, Pacers, and Spurs, averaging 11.2 PPG and 5.8 APG. Career cut short by spinal stenosis — retired at age 28 in 2012. Earned his bachelor's degree from UT in 2017. Opened the T.J. Ford Academy in Fresno, TX (Houston area) in 2021, a basketball training facility for young players. Jersey #11 retired at Texas. Inducted into the Texas Sports Hall of Fame in 2016.",
        sourceUrl: "https://en.wikipedia.org/wiki/T._J._Ford",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 11,
        position: "Point Guard",
        yearsAtSchool: "2001-2003",
        statsNote: "Sophomore • Naismith & Wooden POY • Led Texas to Final Four • 15.0 PPG, 7.7 APG",
        gamesPlayed: 33,
        pointsPerGame: 15.0,
        reboundsPerGame: 3.9,
        assistsPerGame: 7.7,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Willowridge High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 27.5, reboundsPerGame: 3.9, assistsPerGame: 12.0 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2001-02", yearLabel: "2001-02 (Freshman, led NCAA in assists)", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 10.8, reboundsPerGame: 3.7, assistsPerGame: 8.3, stealsPerGame: 2.0, fieldGoalPct: 0.441, freeThrowPct: 0.699 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2002-03", yearLabel: "2002-03 (Sophomore, Naismith/Wooden POY, Final Four)", sortOrder: 202, gamesPlayed: 33, minutesPerGame: 33.5, pointsPerGame: 15.0, reboundsPerGame: 3.9, assistsPerGame: 7.7, stealsPerGame: 2.3, fieldGoalPct: 0.466, threePointPct: 0.343, freeThrowPct: 0.739 },
        { level: "PROFESSIONAL", teamName: "Milwaukee Bucks", season: "2003-04", yearLabel: "2003-04 (Rookie, #8 pick)", sortOrder: 301, gamesPlayed: 55, pointsPerGame: 7.1, reboundsPerGame: 2.2, assistsPerGame: 4.2, stealsPerGame: 1.1, fieldGoalPct: 0.423 },
        { level: "PROFESSIONAL", teamName: "Milwaukee Bucks", season: "2005-06", yearLabel: "2005-06", sortOrder: 303, gamesPlayed: 73, pointsPerGame: 12.0, reboundsPerGame: 2.4, assistsPerGame: 6.3, stealsPerGame: 1.5, fieldGoalPct: 0.453 },
        { level: "PROFESSIONAL", teamName: "Toronto Raptors", season: "2006-07", yearLabel: "2006-07", sortOrder: 304, gamesPlayed: 63, pointsPerGame: 14.0, reboundsPerGame: 3.0, assistsPerGame: 7.3, stealsPerGame: 1.3, fieldGoalPct: 0.437 },
        { level: "PROFESSIONAL", teamName: "Indiana Pacers", season: "2008-09", yearLabel: "2008-09", sortOrder: 306, gamesPlayed: 61, pointsPerGame: 11.9, reboundsPerGame: 2.2, assistsPerGame: 5.8, fieldGoalPct: 0.448 },
      ],
      careerEvents: [
        { year: 2002, title: "First freshman in NCAA history to lead nation in assists (8.3 APG)", eventType: "AWARD" },
        { year: 2003, title: "Won Naismith & Wooden Awards (National Player of the Year)", eventType: "AWARD" },
        { year: 2003, title: "Led Texas to first Final Four since 1947", eventType: "CAREER" },
        { year: 2003, title: "Selected #8 overall by the Milwaukee Bucks", eventType: "DRAFT" },
        { year: 2012, title: "Retired from NBA due to spinal stenosis at age 28", eventType: "RETIREMENT" },
        { year: 2016, title: "Inducted into the Texas Sports Hall of Fame", eventType: "AWARD" },
        { year: 2021, title: "Opened T.J. Ford Academy in Houston area", eventType: "CAREER" },
      ],
    },
    {
      slug: "royal-ivey",
      firstName: "Royal",
      lastName: "Ivey",
      birthYear: 1981,
      hometown: "Harlem, NY",
      highSchool: "St. Raymond's High School, Bronx, NY",
      isFeatured: true,
      bio: "A junior guard and the 2003 Big 12 Defensive Player of the Year. Ivey held the school record with 126 career starts and went on to a remarkable dual career as NBA player-turned-coach and head coach of the South Sudan national team.",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Coach",
        currentEmployer: "Houston Rockets",
        league: "NBA",
        location: "Houston, TX",
        statusNote:
          "A four-year starter who holds the Texas record for career starts (126). Named 2003 Big 12 Defensive Player of the Year. Drafted #37 overall by Atlanta in 2004, he played 10 NBA seasons as a backup guard with the Hawks, Bucks, 76ers, and Thunder (492 games, 3.3 PPG). After retiring in 2014, he built an impressive coaching career — assistant with OKC Blue, Thunder, Knicks, and Nets before joining the Houston Rockets under Ime Udoka in 2023. Also serves as head coach of the South Sudan national basketball team, which he coached at the 2023 FIBA World Cup and the 2024 Paris Olympics — their first-ever Olympic appearance. Inducted into the UT Hall of Honor in 2025.",
        sourceUrl: "https://en.wikipedia.org/wiki/Royal_Ivey",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 12,
        position: "Guard",
        yearsAtSchool: "2000-2004",
        statsNote: "Junior • Big 12 Defensive POY • School record 126 career starts • 7.9 PPG",
        gamesPlayed: 33,
        pointsPerGame: 7.9,
        reboundsPerGame: 2.5,
        assistsPerGame: 1.6,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "St. Raymond's High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 16.9, reboundsPerGame: 2.5, assistsPerGame: 4.1 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2000-01", yearLabel: "2000-01 (Freshman)", sortOrder: 201, gamesPlayed: 34, pointsPerGame: 5.5, reboundsPerGame: 2.0, assistsPerGame: 1.0 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2001-02", yearLabel: "2001-02 (Sophomore)", sortOrder: 202, gamesPlayed: 33, pointsPerGame: 10.9, reboundsPerGame: 3.0, assistsPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2002-03", yearLabel: "2002-03 (Junior, Big 12 DPOY, Final Four)", sortOrder: 203, gamesPlayed: 33, pointsPerGame: 7.9, reboundsPerGame: 2.5, assistsPerGame: 1.6, stealsPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2003-04", yearLabel: "2003-04 (Senior captain)", sortOrder: 204, gamesPlayed: 33, pointsPerGame: 9.4, reboundsPerGame: 3.0, assistsPerGame: 2.0 },
        { level: "PROFESSIONAL", teamName: "Atlanta Hawks", season: "2004-05", yearLabel: "2004-05 (Rookie, #37 pick)", sortOrder: 301, gamesPlayed: 50, pointsPerGame: 2.1, reboundsPerGame: 0.8, assistsPerGame: 0.9 },
        { level: "PROFESSIONAL", teamName: "Oklahoma City Thunder", season: "2010-11", yearLabel: "2010-11", sortOrder: 307, gamesPlayed: 52, pointsPerGame: 2.5, reboundsPerGame: 1.0, assistsPerGame: 0.8 },
      ],
      careerEvents: [
        { year: 2003, title: "Named Big 12 Defensive Player of the Year", eventType: "AWARD" },
        { year: 2003, title: "Helped lead Texas to Final Four", eventType: "CAREER" },
        { year: 2004, title: "Selected #37 overall by the Atlanta Hawks", eventType: "DRAFT" },
        { year: 2014, title: "Retired from NBA; began coaching career", eventType: "RETIREMENT" },
        { year: 2021, title: "Named head coach of South Sudan national basketball team", eventType: "CAREER" },
        { year: 2024, title: "Coached South Sudan at Paris Olympics (first ever Olympic appearance)", eventType: "CAREER" },
        { year: 2025, title: "Inducted into UT Hall of Honor", eventType: "AWARD" },
      ],
    },
    {
      slug: "james-thomas",
      firstName: "James",
      lastName: "Thomas",
      birthYear: 1980,
      hometown: "Schenectady, NY",
      highSchool: "Schenectady High School, Schenectady, NY",
      isFeatured: false,
      bio: "Texas's all-time leading rebounder and a key contributor on the 2003 Final Four team. Thomas's story of returning to earn his degree 16 years after his playing career is deeply inspiring.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Dean of Students",
        currentEmployer: "Albany Leadership Charter High School",
        location: "Albany, NY",
        statusNote:
          "Finished as Texas's all-time leading rebounder and was a key contributor on the 2003 Final Four team. After college, played 10 years of professional basketball including NBA stints with the Trail Blazers, Hawks, 76ers, and Bulls, plus extensive overseas play. After retiring in 2015, coached with the Maine Red Claws (G League) and girls' basketball at his alma mater Schenectady HS. In an inspiring chapter, returned to the University of Texas in 2019 and earned his bachelor's degree in Youth and Community Studies in 2020 — 16 years after his playing career ended. Now Dean of Students at Albany Leadership Charter High School.",
        sourceUrl: "https://en.wikipedia.org/wiki/James_Thomas_(basketball)",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 35,
        position: "Power Forward / Center",
        yearsAtSchool: "2001-2004",
        statsNote: "Sophomore • Texas all-time leading rebounder • 10.0 PPG, 9.5 RPG",
        gamesPlayed: 33,
        pointsPerGame: 10.0,
        reboundsPerGame: 9.5,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Schenectady High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 20.0, reboundsPerGame: 15.0, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2001-02", yearLabel: "2001-02 (Freshman)", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 7.0, reboundsPerGame: 7.5 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2002-03", yearLabel: "2002-03 (Sophomore, Final Four)", sortOrder: 202, gamesPlayed: 33, pointsPerGame: 10.0, reboundsPerGame: 9.5 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2003-04", yearLabel: "2003-04 (Junior)", sortOrder: 203, gamesPlayed: 33, pointsPerGame: 9.5, reboundsPerGame: 8.0 },
      ],
      careerEvents: [
        { year: 2003, title: "Helped lead Texas to Final Four", eventType: "CAREER" },
        { year: 2015, title: "Retired from professional basketball", eventType: "RETIREMENT" },
        { year: 2020, title: "Earned bachelor's degree from UT — 16 years after playing career", eventType: "CAREER" },
      ],
    },
    {
      slug: "brandon-mouton",
      firstName: "Brandon",
      lastName: "Mouton",
      birthYear: 1981,
      hometown: "Lafayette, LA",
      highSchool: "St. Thomas More Catholic High School, Lafayette, LA",
      isFeatured: false,
      bio: "A junior scorer who led the team in NCAA Tournament scoring during the 2003 Final Four run. The eighth-leading scorer in Texas basketball history at the time.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Community Leader / Youth Development",
        location: "Lafayette, LA",
        statusNote:
          "A four-year player who became the eighth-leading scorer in Texas history (1,582 career points). Earned First-Team All-Big 12 as a senior. After going undrafted in 2004, returned to his hometown of Lafayette, LA. Has worked with NCIC (inmate phone provider) and operates Longhorn Lock and Load as a licensed firearms dealer. Also served as Director of the Richmond-Rosenberg Boys and Girls Club in Richmond, TX, focusing on providing opportunities to youth.",
        sourceUrl: "https://en.wikipedia.org/wiki/Brandon_Mouton",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 3,
        position: "Shooting Guard",
        yearsAtSchool: "2000-2004",
        statsNote: "Junior • Led team in NCAA Tournament scoring • 17.8 PPG in March",
        gamesPlayed: 33,
        pointsPerGame: 17.8,
        reboundsPerGame: 4.6,
        assistsPerGame: 1.3,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "St. Thomas More Catholic High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 31.7, reboundsPerGame: 4.6, assistsPerGame: 3.7 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2000-01", yearLabel: "2000-01 (Freshman)", sortOrder: 201, gamesPlayed: 34, pointsPerGame: 5.4, reboundsPerGame: 2.3, assistsPerGame: 1.3 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2001-02", yearLabel: "2001-02 (Sophomore)", sortOrder: 202, gamesPlayed: 33, pointsPerGame: 13.7, reboundsPerGame: 4.6, assistsPerGame: 1.3, threePointPct: 0.394 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2002-03", yearLabel: "2002-03 (Junior, Final Four)", sortOrder: 203, gamesPlayed: 33, pointsPerGame: 17.8, reboundsPerGame: 4.6, assistsPerGame: 1.3 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2003-04", yearLabel: "2003-04 (Senior, First-Team All-Big 12)", sortOrder: 204, gamesPlayed: 33, pointsPerGame: 13.5, reboundsPerGame: 3.5, assistsPerGame: 1.5 },
      ],
      careerEvents: [
        { year: 2003, title: "Led team in scoring during Final Four run", eventType: "CAREER" },
        { year: 2004, title: "Went undrafted; returned to Lafayette, LA", eventType: "CAREER" },
      ],
    },
    {
      slug: "brian-boddicker",
      firstName: "Brian",
      lastName: "Boddicker",
      birthYear: 1981,
      hometown: "Duncanville, TX",
      highSchool: "Duncanville High School, Duncanville, TX",
      isFeatured: false,
      bio: "A stretch forward who shot 43.9% from three during the 2003 Final Four run — a school record. Shot 11-of-21 from three in the NCAA Tournament.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Sector",
        location: "Texas",
        statusNote:
          "A four-year letterwinner who held the top two single-season three-point percentage records at Texas (.448 in 2003-04, .439 in 2002-03). Shot 11-of-21 from three during the 2003 NCAA Tournament run. After going undrafted in 2004, played professionally in Europe (Turkey, Spain, Germany, France). Transitioned to the private sector after retiring from basketball.",
        sourceUrl: "https://texaslonghorns.com/news/2006/6/22/062206aas_823",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 45,
        position: "Power Forward",
        yearsAtSchool: "2000-2004",
        statsNote: "Junior • School-record 43.9% from three • 10.6 PPG, 7.0 RPG in NCAAs",
        gamesPlayed: 33,
        pointsPerGame: 10.6,
        reboundsPerGame: 7.0,
        assistsPerGame: 0.5,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Duncanville High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 20.9, reboundsPerGame: 12.1, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2002-03", yearLabel: "2002-03 (Junior, Final Four, 43.9% 3PT)", sortOrder: 203, gamesPlayed: 33, pointsPerGame: 10.6, reboundsPerGame: 7.0, assistsPerGame: 0.5, threePointPct: 0.439 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2003-04", yearLabel: "2003-04 (Senior, 44.8% 3PT record)", sortOrder: 204, gamesPlayed: 33, pointsPerGame: 8.5, reboundsPerGame: 5.0, assistsPerGame: 0.5, threePointPct: 0.448 },
      ],
      careerEvents: [
        { year: 2003, title: "Shot 11-of-21 from three in NCAA Tournament (Final Four run)", eventType: "OTHER" },
        { year: 2004, title: "Began professional career in Europe", eventType: "CAREER" },
      ],
    },
    {
      slug: "brad-buckman",
      firstName: "Brad",
      lastName: "Buckman",
      birthYear: 1984,
      hometown: "Austin, TX",
      highSchool: "Westlake High School, Austin, TX",
      isFeatured: false,
      bio: "A freshman McDonald's All-American from nearby Westlake High School who wore #22 in honor of his deceased high school teammate. Would play all four years at Texas.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Commercial Real Estate Broker",
        currentEmployer: "AQUILA Commercial / Elevate Growth Partners",
        location: "Austin, TX",
        statusNote:
          "A 2002 McDonald's All-American who played four years at Texas (2002-06), contributing to the 2003 Final Four and three Sweet Sixteen appearances. After going undrafted, played one D-League season with the Austin Toros and seven seasons of international basketball in Europe. Joined AQUILA Commercial in Austin in 2015 as a tenant representation broker specializing in commercial real estate. Married to former Survivor contestant Alexis Jones.",
        sourceUrl: "https://www.reportingtexas.com/basketball-behind-him-buckman-looks-for-new-challenges/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 22,
        position: "Power Forward",
        yearsAtSchool: "2002-2006",
        statsNote: "Freshman • McDonald's All-American • Wore #22 for deceased teammate",
        gamesPlayed: 33,
        pointsPerGame: 5.0,
        reboundsPerGame: 3.5,
        assistsPerGame: 0.3,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Westlake High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 12.5, reboundsPerGame: 7.5, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2002-03", yearLabel: "2002-03 (Freshman, Final Four)", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 5.0, reboundsPerGame: 3.5, assistsPerGame: 0.3 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2003-04", yearLabel: "2003-04 (Sophomore)", sortOrder: 202, gamesPlayed: 33, pointsPerGame: 8.5, reboundsPerGame: 6.0, assistsPerGame: 0.5 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2004-05", yearLabel: "2004-05 (Junior)", sortOrder: 203, gamesPlayed: 31, pointsPerGame: 12.5, reboundsPerGame: 8.3, assistsPerGame: 0.5, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2005-06", yearLabel: "2005-06 (Senior)", sortOrder: 204, gamesPlayed: 37, pointsPerGame: 6.4, reboundsPerGame: 4.8, assistsPerGame: 0.7 },
      ],
      careerEvents: [
        { year: 2003, title: "Part of Texas Final Four team as freshman", eventType: "CAREER" },
        { year: 2006, title: "Went undrafted; joined Austin Toros (D-League)", eventType: "CAREER" },
        { year: 2015, title: "Joined AQUILA Commercial as real estate broker", eventType: "CAREER" },
      ],
    },
    {
      slug: "jason-klotz",
      firstName: "Jason",
      lastName: "Klotz",
      birthYear: 1983,
      hometown: "Weatherford, TX",
      highSchool: "Weatherford High School, Weatherford, TX",
      isFeatured: false,
      bio: "A junior center who provided interior toughness during the Final Four run.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Business Owner",
        currentEmployer: "Clearly Faded",
        location: "Houston, TX",
        statusNote: "Played all five years at Texas (medical redshirt). Part of five NCAA Tournament teams including the 2003 Final Four. After going undrafted, played professionally overseas in China, Turkey, Spain, Japan, and the G-League. Now a business owner (Clearly Faded) in the Houston area.",
        sourceUrl: "https://texaslonghorns.com/news/2005/3/17/031705aaa_459.aspx",
      },
      membership: { role: "PLAYER", jerseyNumber: 33, position: "Center", yearsAtSchool: "2000-2005", statsNote: "Junior • 6.7 PPG, 4.5 RPG • Interior presence", gamesPlayed: 33, pointsPerGame: 6.7, reboundsPerGame: 4.5, assistsPerGame: 0.5 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Weatherford High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 15.1, reboundsPerGame: 8.9, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2002-03", yearLabel: "2002-03 (Junior, Final Four)", sortOrder: 203, gamesPlayed: 33, pointsPerGame: 6.7, reboundsPerGame: 4.5, assistsPerGame: 0.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "sydmill-harris",
      firstName: "Sydmill",
      lastName: "Harris",
      birthYear: 1982,
      hometown: "Hoofddorp, Netherlands",
      highSchool: "Dutch youth system",
      isFeatured: false,
      bio: "A Dutch sophomore guard who represented the Netherlands national team.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Professional Basketball Player",
        location: "Netherlands",
        statusNote: "After four years at Texas (2002-05), played professionally in the Dutch Basketball League with Amsterdam Basketball, Matrixx Magixx, and West-Brabant Giants. Represented the Netherlands national team (22 caps).",
        sourceUrl: "https://en.wikipedia.org/wiki/Sydmill_Harris",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Guard", yearsAtSchool: "2001-2005", statsNote: "Sophomore • Dutch national team player • 5.6 PPG", gamesPlayed: 33, pointsPerGame: 5.6, reboundsPerGame: 2.0, assistsPerGame: 1.5 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Dutch youth system", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 13.4, reboundsPerGame: 2.0, assistsPerGame: 4.0 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2002-03", yearLabel: "2002-03 (Sophomore, Final Four)", sortOrder: 202, gamesPlayed: 33, pointsPerGame: 5.6, reboundsPerGame: 2.0, assistsPerGame: 1.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "deginald-erskin",
      firstName: "Deginald",
      lastName: "Erskin",
      birthYear: 1981,
      hometown: "Houston, TX",
      highSchool: "High school in Houston, TX",
      isFeatured: false,
      bio: "A junior transfer from North Texas who became a key contributor during the Final Four run, shooting 51.2% from the field.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "Texas",
        statusNote: "Walk-on transfer from North Texas who became a key contributor during the 2003 Final Four run, shooting .512 from the field in the postseason. Played professionally in the UK with the Leicester Riders (2005-06).",
        sourceUrl: "https://www.espn.com/mens-college-basketball/player/_/id/5349/deginald-erskin",
      },
      membership: { role: "PLAYER", jerseyNumber: 24, position: "Forward", yearsAtSchool: "2001-2004", statsNote: "Junior • Transfer from North Texas • 5.8 PPG, .512 FG", gamesPlayed: 33, pointsPerGame: 5.8, reboundsPerGame: 2.8, assistsPerGame: 0.3 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "High school in Houston", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 13.7, reboundsPerGame: 6.6, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2002-03", yearLabel: "2002-03 (Junior, Final Four)", sortOrder: 203, gamesPlayed: 33, pointsPerGame: 5.8, reboundsPerGame: 2.8, assistsPerGame: 0.3 },
      ],
      careerEvents: [],
    },
    {
      slug: "edgar-moreno",
      firstName: "Edgar",
      lastName: "Moreno",
      birthYear: 1981,
      hometown: "Bogota, Colombia",
      highSchool: "International prep, Colombia",
      isFeatured: false,
      bio: "A Colombian point guard who served as a backup behind T.J. Ford on the 2003 Final Four team. Transferred to UTEP after his sophomore year and went on to a long professional career across Latin America while representing the Colombian national team.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Professional Basketball Player",
        location: "Colombia",
        statusNote: "Played two seasons at Texas as a reserve point guard before transferring to UTEP, where he graduated in 2006. Built a 15+ year professional career across Colombia, Mexico, Puerto Rico, Venezuela, and the United States, most recently with Sabios de Manizales in Colombia's Liga Wplay. Represented the Colombian national team at multiple FIBA AmeriCup tournaments.",
        sourceUrl: "https://www.proballers.com/basketball/player/34864/edgar-moreno",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Point Guard", yearsAtSchool: "2001-2003", statsNote: "Sophomore reserve PG behind T.J. Ford", gamesPlayed: 28, pointsPerGame: 1.8, reboundsPerGame: 0.7, assistsPerGame: 1.0 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Colombian prep", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 14.0, assistsPerGame: 5.5 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2002-03", yearLabel: "2002-03 (Sophomore, Final Four)", sortOrder: 202, gamesPlayed: 28, pointsPerGame: 1.8, reboundsPerGame: 0.7, assistsPerGame: 1.0 },
        { level: "COLLEGE", teamName: "UTEP Miners", season: "2004-05", yearLabel: "2004-05 (Junior at UTEP)", sortOrder: 203, gamesPlayed: 27, pointsPerGame: 6.5, assistsPerGame: 3.5 },
        { level: "PROFESSIONAL", teamName: "Sabios de Manizales", season: "Career", yearLabel: "Pro career", sortOrder: 301, pointsPerGame: 11.0, assistsPerGame: 4.5 },
      ],
      careerEvents: [
        { year: 2003, title: "Reached Final Four with Texas", eventType: "CAREER" },
        { year: 2004, title: "Transferred to UTEP", eventType: "CAREER" },
        { year: 2017, title: "Represented Colombia at FIBA AmeriCup", eventType: "CAREER" },
      ],
    },
    {
      slug: "kenton-paulino-2003",
      firstName: "Kenton",
      lastName: "Paulino",
      birthYear: 1984,
      hometown: "Miami, FL",
      highSchool: "Miami Senior High School, Miami, FL",
      isFeatured: false,
      bio: "A freshman guard on the 2003 Final Four team who would go on to hit one of the greatest shots in Texas history — a buzzer-beater against West Virginia in the 2006 Sweet Sixteen. Now an associate head coach at Wichita State.",
      status: {
        occupationType: "COACH",
        currentTitle: "Associate Head Coach",
        currentEmployer: "Wichita State University",
        league: "AAC",
        location: "Wichita, KS",
        statusNote: "Played four years at Texas (2002-06), finishing as one of just five players in school history to shoot above .400 from three-point range. Hit a 25-foot buzzer-beater to beat West Virginia 74-71 in the 2006 NCAA Sweet Sixteen — widely considered one of the greatest shots in Longhorns history. After a brief pro career he turned to coaching, starting as a special assistant under Rick Barnes at Texas (2008-11) before joining Wichita State, where he has been a key assistant and was promoted to associate head coach in 2023.",
        sourceUrl: "https://goshockers.com/sports/mens-basketball/roster/coaches/kenton-paulino/1242",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Guard", yearsAtSchool: "2002-2006", statsNote: "Freshman • Future hero of 2006 Sweet 16", gamesPlayed: 32, pointsPerGame: 2.4, reboundsPerGame: 0.9, assistsPerGame: 0.8 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Miami Senior High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 18.5, assistsPerGame: 4.5 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2002-03", yearLabel: "2002-03 (Freshman, Final Four)", sortOrder: 201, gamesPlayed: 32, pointsPerGame: 2.4, reboundsPerGame: 0.9, assistsPerGame: 0.8 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2005-06", yearLabel: "2005-06 (Senior, Elite Eight)", sortOrder: 204, gamesPlayed: 37, pointsPerGame: 8.5, assistsPerGame: 2.4, threePointPct: 0.421 },
      ],
      careerEvents: [
        { year: 2003, title: "Reached Final Four as a freshman", eventType: "CAREER" },
        { year: 2006, title: "Hit buzzer-beater vs. West Virginia in NCAA Sweet 16", eventType: "CAREER" },
        { year: 2011, title: "Joined Wichita State as assistant coach", eventType: "CAREER" },
        { year: 2023, title: "Promoted to Associate Head Coach at Wichita State", eventType: "CAREER" },
      ],
    },
    {
      slug: "terrell-ross",
      firstName: "Terrell",
      lastName: "Ross",
      birthYear: 1980,
      hometown: "Baltimore, MD",
      highSchool: "Baltimore-area high school",
      isFeatured: false,
      bio: "A senior backup point guard who provided veteran depth behind T.J. Ford on the 2003 Final Four team. Transferred to Texas from Allegany College and played in 33 games during the historic season.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Sector",
        location: "Baltimore, MD",
        statusNote: "A two-year letterwinner at Texas (2001-03) after transferring from Allegany College in Maryland, Ross played in 63 of 67 possible games and helped the Longhorns reach the 2002 Sweet 16 and 2003 Final Four. As a senior in 2002-03 he averaged 9.9 minutes per game as Ford's backup, recording 39 assists against just 25 turnovers. After his playing career he returned to the Baltimore area.",
        sourceUrl: "https://texaslonghorns.com/news/2006/6/22/062206aah_9",
      },
      membership: { role: "PLAYER", jerseyNumber: 14, position: "Point Guard", yearsAtSchool: "2001-2003", statsNote: "Senior • Backup PG to T.J. Ford", gamesPlayed: 33, pointsPerGame: 1.5, reboundsPerGame: 0.8, assistsPerGame: 1.2 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Baltimore-area HS", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 16.0, assistsPerGame: 5.0 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2002-03", yearLabel: "2002-03 (Senior, Final Four)", sortOrder: 204, gamesPlayed: 33, minutesPerGame: 9.9, pointsPerGame: 1.5, reboundsPerGame: 0.8, assistsPerGame: 1.2 },
      ],
      careerEvents: [
        { year: 2001, title: "Transferred to Texas from Allegany College", eventType: "CAREER" },
        { year: 2003, title: "Reached Final Four as senior backup point guard", eventType: "CAREER" },
      ],
    },
    {
      slug: "rick-barnes",
      firstName: "Rick",
      lastName: "Barnes",
      birthYear: 1954,
      hometown: "Hickory, NC",
      highSchool: "Hickory High School, Hickory, NC",
      isFeatured: true,
      bio: "Led Texas to the program's first Final Four since 1947 as the #1 overall seed, featuring Naismith POY T.J. Ford.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "University of Tennessee",
        league: "SEC",
        location: "Knoxville, TN",
        statusNote: "Texas's winningest coach (402-180). Led Texas to the 2003 Final Four (#1 seed). After being fired in 2015, rebuilt Tennessee into a perennial top-10 program. 2019 Naismith Coach of the Year. Recorded 800th career win in 2024. Still coaching at Tennessee in 2025-26.",
        sourceUrl: "https://en.wikipedia.org/wiki/Rick_Barnes",
      },
      membership: {
        role: "HEAD_COACH",
        position: "Head Coach",
        yearsAtSchool: "1998-2015",
        statsNote: "26-7 • #1 Seed • Final Four (first since 1947) • Naismith POY on roster",
      },
      careerEvents: [
        { year: 2003, title: "Led Texas to first Final Four since 1947 as #1 overall seed", eventType: "CAREER" },
        { year: 2015, title: "Fired by Texas; hired by Tennessee", eventType: "CAREER" },
        { year: 2019, title: "Named Naismith Coach of the Year at Tennessee", eventType: "AWARD" },
      ],
    },
  ],
};
