import type { TeamSeed } from "./types";

export const texasBasketball2006: TeamSeed = {
  slug: "texas-basketball-2006",
  name: "Texas Longhorns",
  season: "2005-2006",
  sport: "Men's Basketball",
  school: "University of Texas",
  conference: "Big 12",
  accomplishment: "Big 12 Champions, Elite Eight (30-7)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/251.png",
  mascotName: "Bevo",
  people: [
    {
      slug: "lamarcus-aldridge",
      firstName: "LaMarcus",
      lastName: "Aldridge",
      birthYear: 1985,
      hometown: "Dallas, TX",
      highSchool: "Seagoville High School, Dallas, TX",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/200746.png",
      bio: "A dominant sophomore big man who averaged 15.0 PPG and 9.2 RPG, earning Big 12 Player of the Year honors and leading Texas to the Elite Eight. Selected #2 overall in the 2006 NBA Draft.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NBA Player / Entrepreneur",
        location: "Dallas, TX",
        statusNote:
          "Selected #2 overall by the Chicago Bulls in 2006 (immediately traded to the Portland Trail Blazers). A seven-time NBA All-Star and five-time All-NBA selection over 16 seasons with Portland (2006-2015), San Antonio (2015-2021), and Brooklyn (2021). Career averages: 19.4 PPG, 8.3 RPG. Retired in April 2023 after a brief heart condition scare in 2021. Now involved in philanthropic work, real estate, and wellness ventures in the Dallas-Fort Worth area. Occasionally appears as an NBA analyst.",
        sourceUrl: "https://en.wikipedia.org/wiki/LaMarcus_Aldridge",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 2,
        position: "Power Forward / Center",
        yearsAtSchool: "2004-2006",
        statsNote: "Sophomore • Big 12 POY • #2 overall pick • 15.0 PPG, 9.2 RPG",
        gamesPlayed: 35,
        pointsPerGame: 15.0,
        reboundsPerGame: 9.2,
        assistsPerGame: 0.9,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2004-05", yearLabel: "2004-05 (Freshman)", sortOrder: 201, gamesPlayed: 32, pointsPerGame: 9.9, reboundsPerGame: 6.2, assistsPerGame: 0.5, blocksPerGame: 2.0, fieldGoalPct: 0.544 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2005-06", yearLabel: "2005-06 (Sophomore, Big 12 POY, #2 pick)", sortOrder: 202, gamesPlayed: 35, minutesPerGame: 32.5, pointsPerGame: 15.0, reboundsPerGame: 9.2, assistsPerGame: 0.9, blocksPerGame: 2.2, fieldGoalPct: 0.545, freeThrowPct: 0.595 },
        { level: "PROFESSIONAL", teamName: "Portland Trail Blazers", season: "2006-07", yearLabel: "2006-07 (Rookie)", sortOrder: 301, gamesPlayed: 63, pointsPerGame: 9.0, reboundsPerGame: 5.0, assistsPerGame: 0.7, fieldGoalPct: 0.458 },
        { level: "PROFESSIONAL", teamName: "Portland Trail Blazers", season: "2010-11", yearLabel: "2010-11 (All-Star)", sortOrder: 305, gamesPlayed: 81, pointsPerGame: 21.8, reboundsPerGame: 8.8, assistsPerGame: 2.1, fieldGoalPct: 0.501 },
        { level: "PROFESSIONAL", teamName: "Portland Trail Blazers", season: "2013-14", yearLabel: "2013-14 (All-NBA)", sortOrder: 308, gamesPlayed: 69, pointsPerGame: 23.2, reboundsPerGame: 11.1, assistsPerGame: 2.6, fieldGoalPct: 0.460 },
        { level: "PROFESSIONAL", teamName: "San Antonio Spurs", season: "2015-16", yearLabel: "2015-16 (All-Star)", sortOrder: 310, gamesPlayed: 74, pointsPerGame: 18.0, reboundsPerGame: 8.5, assistsPerGame: 1.5, fieldGoalPct: 0.515 },
        { level: "PROFESSIONAL", teamName: "San Antonio Spurs", season: "2018-19", yearLabel: "2018-19 (All-Star)", sortOrder: 313, gamesPlayed: 81, pointsPerGame: 21.3, reboundsPerGame: 9.2, assistsPerGame: 2.4, fieldGoalPct: 0.519 },
      ],
      careerEvents: [
        { year: 2006, title: "Selected #2 overall by the Chicago Bulls (traded to Portland)", eventType: "DRAFT" },
        { year: 2011, title: "First NBA All-Star selection", eventType: "AWARD" },
        { year: 2015, title: "Signed with the San Antonio Spurs as free agent", eventType: "SIGNING" },
        { year: 2021, title: "Retired briefly due to heart condition; returned with Brooklyn Nets", eventType: "CAREER" },
        { year: 2023, title: "Officially retired from the NBA after 16 seasons", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "pj-tucker",
      firstName: "P.J.",
      lastName: "Tucker",
      birthYear: 1985,
      hometown: "Raleigh, NC",
      highSchool: "William G. Enloe High School, Raleigh, NC",
      isFeatured: true,
      bio: "A physical junior forward who averaged 13.9 PPG and 6.8 RPG. Tucker would become one of the NBA's great comeback stories, spending five years overseas before returning to become an NBA champion and legendary sneaker collector.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NBA Champion / Fashion Entrepreneur",
        location: "Houston, TX",
        statusNote:
          "Selected #35 overall by Toronto in 2006 but spent five years overseas (Israel, Ukraine, Germany, Italy, Greece, Puerto Rico) before returning to the NBA with the Phoenix Suns in 2012. Played for the Suns, Rockets, Bucks (won 2021 NBA Championship), Heat, 76ers, and Clippers. Retired after the 2023-24 season. Known as one of the NBA's premier sneaker collectors (reportedly 5,000+ pairs). Deeply involved in fashion and streetwear culture. Based in Houston.",
        sourceUrl: "https://en.wikipedia.org/wiki/P.J._Tucker",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 22,
        position: "Small Forward / Power Forward",
        yearsAtSchool: "2003-2006",
        statsNote: "Junior • 13.9 PPG, 6.8 RPG • Left for NBA after junior year",
        gamesPlayed: 37,
        pointsPerGame: 13.9,
        reboundsPerGame: 6.8,
        assistsPerGame: 1.6,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2003-04", yearLabel: "2003-04 (Freshman)", sortOrder: 201, gamesPlayed: 31, pointsPerGame: 7.5, reboundsPerGame: 5.0, assistsPerGame: 1.2 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2004-05", yearLabel: "2004-05 (Sophomore)", sortOrder: 202, gamesPlayed: 32, pointsPerGame: 11.0, reboundsPerGame: 5.8, assistsPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2005-06", yearLabel: "2005-06 (Junior, left for NBA)", sortOrder: 203, gamesPlayed: 37, pointsPerGame: 13.9, reboundsPerGame: 6.8, assistsPerGame: 1.6, stealsPerGame: 1.3, fieldGoalPct: 0.462, threePointPct: 0.376 },
        { level: "PROFESSIONAL", teamName: "Toronto Raptors", season: "2006-07", yearLabel: "2006-07 (Rookie, 17 games)", sortOrder: 301, gamesPlayed: 17, pointsPerGame: 1.8, reboundsPerGame: 1.4, assistsPerGame: 0.2 },
        { level: "PROFESSIONAL", teamName: "Phoenix Suns", season: "2012-13", yearLabel: "2012-13 (NBA comeback!)", sortOrder: 308, gamesPlayed: 65, pointsPerGame: 7.3, reboundsPerGame: 6.4, assistsPerGame: 0.9, stealsPerGame: 1.2 },
        { level: "PROFESSIONAL", teamName: "Houston Rockets", season: "2017-18", yearLabel: "2017-18", sortOrder: 312, gamesPlayed: 82, pointsPerGame: 6.0, reboundsPerGame: 5.8, assistsPerGame: 0.6, stealsPerGame: 1.4 },
        { level: "PROFESSIONAL", teamName: "Milwaukee Bucks", season: "2020-21", yearLabel: "2020-21 (NBA Champion!)", sortOrder: 315, gamesPlayed: 41, pointsPerGame: 2.6, reboundsPerGame: 3.2, assistsPerGame: 0.3 },
      ],
      careerEvents: [
        { year: 2006, title: "Selected #35 overall by the Toronto Raptors", eventType: "DRAFT" },
        { year: 2007, title: "Went overseas — played 5 years in Israel, Ukraine, Germany, Italy, Greece, Puerto Rico", eventType: "CAREER" },
        { year: 2012, title: "Returned to NBA with the Phoenix Suns", eventType: "SIGNING" },
        { year: 2021, title: "Won NBA Championship with the Milwaukee Bucks", eventType: "CHAMPIONSHIP" },
        { year: 2024, title: "Retired from the NBA after 17-year professional career", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "daniel-gibson",
      firstName: "Daniel",
      lastName: "Gibson",
      birthYear: 1986,
      hometown: "Houston, TX",
      highSchool: "Jones High School, Houston, TX",
      isFeatured: false,
      bio: "A one-and-done freshman guard nicknamed 'Boobie' who averaged 10.1 PPG alongside LaMarcus Aldridge. Known for his clutch playoff shooting with the Cleveland Cavaliers.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NBA Player / Community Leader",
        location: "Houston, TX",
        statusNote:
          "Selected #42 overall by the Cleveland Cavaliers in 2006. Played for the Cavs from 2006-2013, earning the nickname 'Boobie.' Best remembered for scoring 31 points in Game 6 of the 2007 Eastern Conference Finals vs. Detroit, helping LeBron James reach his first NBA Finals. Career ended due to injuries around 2013. Has been involved in community work in the Houston area since retirement.",
        sourceUrl: "https://en.wikipedia.org/wiki/Daniel_Gibson_(basketball)",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 1,
        position: "Shooting Guard",
        yearsAtSchool: "2005-2006",
        statsNote: "Freshman • One-and-done • 10.1 PPG • 'Boobie' • 31 pts in 2007 NBA Playoffs",
        gamesPlayed: 34,
        pointsPerGame: 10.1,
        reboundsPerGame: 2.2,
        assistsPerGame: 2.4,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2005-06", yearLabel: "2005-06 (Freshman, one-and-done)", sortOrder: 201, gamesPlayed: 34, pointsPerGame: 10.1, reboundsPerGame: 2.2, assistsPerGame: 2.4, fieldGoalPct: 0.445, threePointPct: 0.390, freeThrowPct: 0.825 },
        { level: "PROFESSIONAL", teamName: "Cleveland Cavaliers", season: "2006-07", yearLabel: "2006-07 (Rookie, 31 pts playoff game!)", sortOrder: 301, gamesPlayed: 55, pointsPerGame: 3.9, reboundsPerGame: 0.9, assistsPerGame: 1.0, fieldGoalPct: 0.370, threePointPct: 0.313 },
        { level: "PROFESSIONAL", teamName: "Cleveland Cavaliers", season: "2009-10", yearLabel: "2009-10", sortOrder: 304, gamesPlayed: 59, pointsPerGame: 10.2, reboundsPerGame: 2.3, assistsPerGame: 2.7, fieldGoalPct: 0.417, threePointPct: 0.411 },
        { level: "PROFESSIONAL", teamName: "Cleveland Cavaliers", season: "2010-11", yearLabel: "2010-11", sortOrder: 305, gamesPlayed: 68, pointsPerGame: 7.9, reboundsPerGame: 1.6, assistsPerGame: 2.2, threePointPct: 0.368 },
      ],
      careerEvents: [
        { year: 2006, title: "Selected #42 overall by the Cleveland Cavaliers", eventType: "DRAFT" },
        { year: 2007, title: "Scored 31 points in Game 6 of ECF vs. Detroit (clutch playoff performance)", eventType: "OTHER" },
        { year: 2013, title: "Retired from the NBA due to injuries", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "kenton-paulino",
      firstName: "Kenton",
      lastName: "Paulino",
      birthYear: 1985,
      hometown: "Galveston, TX",
      highSchool: "Ball High School, Galveston, TX",
      isFeatured: false,
      bio: "A sharpshoooting sophomore guard best remembered for hitting the game-winning three-pointer to beat West Virginia in the 2006 Sweet Sixteen.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Sector",
        location: "Texas",
        statusNote:
          "Played all four years at Texas (2004-2008). Best remembered for his game-winning three-pointer that beat West Virginia in the 2006 NCAA Tournament Sweet Sixteen. Went undrafted and played briefly overseas before transitioning to the private sector in Texas.",
        sourceUrl: "https://texassports.com",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 30,
        position: "Shooting Guard",
        yearsAtSchool: "2004-2008",
        statsNote: "Sophomore • Sweet 16 game-winner vs WVU • 8.4 PPG sharpshooter",
        gamesPlayed: 37,
        pointsPerGame: 8.4,
        reboundsPerGame: 1.7,
        assistsPerGame: 1.5,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2005-06", yearLabel: "2005-06 (Sophomore, Sweet 16 game-winner!)", sortOrder: 202, gamesPlayed: 37, pointsPerGame: 8.4, reboundsPerGame: 1.7, assistsPerGame: 1.5, threePointPct: 0.405 },
      ],
      careerEvents: [
        { year: 2006, title: "Hit game-winning three-pointer vs West Virginia in Sweet 16", eventType: "OTHER" },
      ],
    },
    {
      slug: "aj-abrams",
      firstName: "A.J.",
      lastName: "Abrams",
      birthYear: 1987,
      hometown: "Round Rock, TX",
      highSchool: "Plano East Senior High School, Plano, TX",
      isFeatured: false,
      bio: "A freshman sharpshooter who would become Texas's all-time leader in three-pointers made.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Realtor / Basketball Analyst",
        currentEmployer: "JBGoodwin Realtors / Horns247",
        location: "Austin, TX",
        statusNote: "Played all four years at Texas (2005-09), finishing as the program's all-time leader in three-pointers made (337). Went undrafted; played professionally in Greece, Italy, and Czech Republic (winning championships with Nymburk in 2011 and 2012). Now a realtor at JBGoodwin Realtors in Austin and basketball analyst for Horns247. Active in youth basketball camps.",
        sourceUrl: "https://thedailytexan.com/2014/11/12/where-are-they-now-texas-guard-aj-abrams/",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Shooting Guard", yearsAtSchool: "2005-2009", statsNote: "Freshman • Would become Texas all-time 3PT leader (337)", gamesPlayed: 37, pointsPerGame: 8.4, reboundsPerGame: 1.3, assistsPerGame: 1.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2005-06", yearLabel: "2005-06 (Freshman)", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 8.4, reboundsPerGame: 1.3, assistsPerGame: 1.2 },
      ],
      careerEvents: [],
    },
    {
      slug: "brad-buckman",
      firstName: "Brad",
      lastName: "Buckman",
      birthYear: 1984,
      hometown: "Austin, TX",
      highSchool: "Westlake High School, Austin, TX",
      isFeatured: false,
      bio: "A senior forward completing his four-year career. Wore #22 in honor of deceased high school teammate.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Commercial Real Estate Broker",
        currentEmployer: "AQUILA Commercial",
        location: "Austin, TX",
        statusNote: "2002 McDonald's All-American. Played four years at Texas spanning the Final Four through the Aldridge era. After going undrafted, played D-League and 7 years of international basketball. Now a commercial real estate broker at AQUILA Commercial in Austin. Married to former Survivor contestant Alexis Jones.",
        sourceUrl: "https://www.reportingtexas.com/basketball-behind-him-buckman-looks-for-new-challenges/",
      },
      membership: { role: "PLAYER", jerseyNumber: 35, position: "Power Forward", yearsAtSchool: "2002-2006", statsNote: "Senior • McDonald's All-American • 9.5 PPG, 7.0 RPG", gamesPlayed: 33, pointsPerGame: 9.5, reboundsPerGame: 7.0, assistsPerGame: 0.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2005-06", yearLabel: "2005-06 (Senior)", sortOrder: 204, gamesPlayed: 33, pointsPerGame: 9.5, reboundsPerGame: 7.0, assistsPerGame: 0.8 },
      ],
      careerEvents: [],
    },
    {
      slug: "connor-atchley",
      firstName: "Connor",
      lastName: "Atchley",
      birthYear: 1986,
      hometown: "Clear Lake, TX",
      highSchool: "Clear Lake High School, Houston, TX",
      isFeatured: false,
      bio: "A redshirt freshman center who would finish with the third-most blocks in Texas history.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Sector",
        location: "Austin, TX",
        statusNote: "Finished career at Texas with the third-most blocks (189) in school history. Three-time Academic All-Big 12. Now in the private sector in Austin.",
        sourceUrl: "https://texaslonghorns.com/sports/mens-basketball/roster/connor-atchley/2340",
      },
      membership: { role: "PLAYER", jerseyNumber: 32, position: "Center / Forward", yearsAtSchool: "2005-2010", statsNote: "Redshirt Freshman • 2.2 PPG", gamesPlayed: 28, pointsPerGame: 2.2, reboundsPerGame: 1.5, assistsPerGame: 0.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2005-06", yearLabel: "2005-06 (Redshirt Freshman)", sortOrder: 201, gamesPlayed: 28, pointsPerGame: 2.2, reboundsPerGame: 1.5, assistsPerGame: 0.2 },
      ],
      careerEvents: [],
    },
    {
      slug: "ian-mooney",
      firstName: "Ian",
      lastName: "Mooney",
      birthYear: 1984,
      hometown: "Austin, TX",
      highSchool: "St. Michael's Academy, Austin, TX",
      isFeatured: false,
      bio: "A walk-on who would later found D1 Approved, an NIL platform for student-athletes.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Founder",
        currentEmployer: "D1 Approved",
        location: "Austin, TX",
        statusNote: "Walk-on at Texas who earned his master's in advertising from UT. Built 15+ years in media, tech, and publishing. Founded D1 Approved in March 2024 — an NIL platform helping student-athletes with Name, Image, and Likeness opportunities through edutainment content.",
        sourceUrl: "https://www.kvue.com/article/sports/ncaa/longhorns/d1-approved-nil-ian-mooney/269-5a4853e7-a4a0-4a15-b1bb-11bfea14010d",
      },
      membership: { role: "PLAYER", jerseyNumber: 22, position: "Forward", yearsAtSchool: "2004-2007", statsNote: "Junior walk-on • 1.0 PPG • Now NIL entrepreneur", gamesPlayed: 30, pointsPerGame: 1.0, reboundsPerGame: 0.8, assistsPerGame: 0.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2005-06", yearLabel: "2005-06 (Junior walk-on)", sortOrder: 203, gamesPlayed: 30, pointsPerGame: 1.0, reboundsPerGame: 0.8, assistsPerGame: 0.2 },
      ],
      careerEvents: [],
    },
    {
      slug: "rick-barnes",
      firstName: "Rick",
      lastName: "Barnes",
      birthYear: 1954,
      hometown: "Hickory, NC",
      highSchool: "Hickory High School, Hickory, NC",
      isFeatured: true,
      bio: "Led Texas to the Elite Eight and Big 12 regular season championship. Would recruit Kevin Durant the following year.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "University of Tennessee",
        league: "SEC",
        location: "Knoxville, TN",
        statusNote: "Texas's winningest coach (402-180). After being fired in 2015, rebuilt Tennessee into a perennial top-10 program. Multiple SEC Coach of the Year awards. Still coaching in 2025-26.",
        sourceUrl: "https://en.wikipedia.org/wiki/Rick_Barnes",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "1998-2015", statsNote: "30-7 • Big 12 Champions • Elite Eight" },
      careerEvents: [
        { year: 2003, title: "Led Texas to Final Four", eventType: "CAREER" },
        { year: 2015, title: "Fired by Texas; hired by Tennessee", eventType: "CAREER" },
      ],
    },
  ],
};
