import type { TeamSeed } from "./types";

export const texasBasketball2007: TeamSeed = {
  slug: "texas-basketball-2007",
  name: "Texas Longhorns",
  season: "2006-2007",
  sport: "Men's Basketball",
  school: "University of Texas",
  conference: "Big 12",
  accomplishment: "NCAA Tournament Second Round (25-10)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/251.png",
  mascotName: "Bevo",
  people: [
    {
      slug: "kevin-durant",
      firstName: "Kevin",
      lastName: "Durant",
      birthYear: 1988,
      hometown: "Suitland, MD",
      highSchool: "Montrose Christian School, Rockville, MD",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/201142.png",
      bio: "The greatest one-and-done in college basketball history. Durant averaged 25.8 PPG and 11.1 RPG as a freshman — the first freshman ever to win a major National Player of the Year award (Naismith, Wooden, AP). One of the most transcendent talents the sport has ever seen.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Phoenix Suns",
        league: "NBA",
        location: "Phoenix, AZ",
        statusNote:
          "Selected #2 overall by the Seattle SuperSonics in 2007 (moved to OKC in 2008). One of the greatest scorers in NBA history — 14-time All-Star, 4-time scoring champion, 2014 MVP, 2-time NBA Champion and Finals MVP with Golden State (2017, 2018), 2-time Olympic gold medalist. Career average ~27 PPG across 18 seasons with OKC, Golden State, Brooklyn, and Phoenix. Also a visionary entrepreneur through Thirty Five Ventures, with investments in dozens of companies. One of the wealthiest and most influential athletes in the world.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kevin_Durant",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 35,
        position: "Small Forward",
        yearsAtSchool: "2006-2007",
        statsNote: "Freshman • Unanimous National POY • First freshman to win Naismith/Wooden • 25.8 PPG, 11.1 RPG",
        gamesPlayed: 35,
        pointsPerGame: 25.8,
        reboundsPerGame: 11.1,
        assistsPerGame: 1.3,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2006-07", yearLabel: "2006-07 (Freshman, Unanimous Naismith/Wooden POY)", sortOrder: 201, gamesPlayed: 35, minutesPerGame: 35.9, pointsPerGame: 25.8, reboundsPerGame: 11.1, assistsPerGame: 1.3, stealsPerGame: 1.9, blocksPerGame: 1.9, fieldGoalPct: 0.473, threePointPct: 0.404, freeThrowPct: 0.816 },
        { level: "PROFESSIONAL", teamName: "Seattle SuperSonics", season: "2007-08", yearLabel: "2007-08 (Rookie, ROY)", sortOrder: 301, gamesPlayed: 80, pointsPerGame: 20.3, reboundsPerGame: 4.4, assistsPerGame: 2.4, stealsPerGame: 1.0, fieldGoalPct: 0.430, threePointPct: 0.288, freeThrowPct: 0.873 },
        { level: "PROFESSIONAL", teamName: "Oklahoma City Thunder", season: "2009-10", yearLabel: "2009-10 (Scoring Title)", sortOrder: 303, gamesPlayed: 82, pointsPerGame: 30.1, reboundsPerGame: 7.6, assistsPerGame: 2.8, fieldGoalPct: 0.476, threePointPct: 0.365, freeThrowPct: 0.900 },
        { level: "PROFESSIONAL", teamName: "Oklahoma City Thunder", season: "2011-12", yearLabel: "2011-12 (NBA Finals)", sortOrder: 305, gamesPlayed: 66, pointsPerGame: 28.0, reboundsPerGame: 8.0, assistsPerGame: 3.5, fieldGoalPct: 0.496, threePointPct: 0.387, freeThrowPct: 0.860 },
        { level: "PROFESSIONAL", teamName: "Oklahoma City Thunder", season: "2013-14", yearLabel: "2013-14 (MVP!)", sortOrder: 307, gamesPlayed: 81, pointsPerGame: 32.0, reboundsPerGame: 7.4, assistsPerGame: 5.5, stealsPerGame: 1.3, fieldGoalPct: 0.503, threePointPct: 0.391, freeThrowPct: 0.873 },
        { level: "PROFESSIONAL", teamName: "Golden State Warriors", season: "2016-17", yearLabel: "2016-17 (Champion, Finals MVP)", sortOrder: 310, gamesPlayed: 62, pointsPerGame: 25.1, reboundsPerGame: 8.3, assistsPerGame: 4.8, fieldGoalPct: 0.537, threePointPct: 0.375, freeThrowPct: 0.875 },
        { level: "PROFESSIONAL", teamName: "Golden State Warriors", season: "2017-18", yearLabel: "2017-18 (Champion, Finals MVP)", sortOrder: 311, gamesPlayed: 68, pointsPerGame: 26.4, reboundsPerGame: 6.8, assistsPerGame: 5.4, fieldGoalPct: 0.516, threePointPct: 0.419, freeThrowPct: 0.889 },
        { level: "PROFESSIONAL", teamName: "Brooklyn Nets", season: "2020-21", yearLabel: "2020-21", sortOrder: 314, gamesPlayed: 35, pointsPerGame: 26.9, reboundsPerGame: 7.1, assistsPerGame: 5.6, fieldGoalPct: 0.537, threePointPct: 0.450, freeThrowPct: 0.882 },
        { level: "PROFESSIONAL", teamName: "Phoenix Suns", season: "2023-24", yearLabel: "2023-24", sortOrder: 317, gamesPlayed: 75, pointsPerGame: 27.1, reboundsPerGame: 6.6, assistsPerGame: 5.0, fieldGoalPct: 0.523, threePointPct: 0.415, freeThrowPct: 0.856 },
      ],
      careerEvents: [
        { year: 2007, title: "Unanimous National Player of the Year — first freshman to win Naismith/Wooden", eventType: "AWARD" },
        { year: 2007, title: "Selected #2 overall by the Seattle SuperSonics", eventType: "DRAFT" },
        { year: 2008, title: "Won NBA Rookie of the Year", eventType: "AWARD" },
        { year: 2014, title: "Won NBA Most Valuable Player award (32.0 PPG)", eventType: "AWARD" },
        { year: 2017, title: "Won NBA Championship with Warriors (Finals MVP)", eventType: "CHAMPIONSHIP" },
        { year: 2018, title: "Won second consecutive NBA Championship (Finals MVP)", eventType: "CHAMPIONSHIP" },
        { year: 2023, title: "Traded to the Phoenix Suns", eventType: "TRADE" },
      ],
    },
    {
      slug: "dj-augustin",
      firstName: "D.J.",
      lastName: "Augustin",
      birthYear: 1987,
      hometown: "New Orleans, LA",
      highSchool: "Brother Martin High School, New Orleans, LA",
      isFeatured: true,
      bio: "A dynamic freshman point guard who averaged 14.4 PPG and 5.2 APG alongside Kevin Durant. Would become the #9 overall pick after his sophomore year.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NBA Player / Mentor",
        location: "Texas",
        statusNote:
          "Selected #9 overall by the Charlotte Bobcats in 2008 after a sophomore season averaging 19.2 PPG (First-Team All-American). Played 14 NBA seasons across 10 teams, most notably with the Orlando Magic (2018-19 playoff run where he hit a game-winning three against Toronto). Career averages: 10.0 PPG, 4.0 APG. Retired after the 2021-22 season. Has been involved in mentoring young players in the Texas/Louisiana area.",
        sourceUrl: "https://en.wikipedia.org/wiki/D.J._Augustin",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 14,
        position: "Point Guard",
        yearsAtSchool: "2006-2008",
        statsNote: "Freshman • 14.4 PPG, 5.2 APG • Kevin Durant's PG • Future #9 pick",
        gamesPlayed: 32,
        pointsPerGame: 14.4,
        reboundsPerGame: 2.3,
        assistsPerGame: 5.2,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2006-07", yearLabel: "2006-07 (Freshman)", sortOrder: 201, gamesPlayed: 32, pointsPerGame: 14.4, reboundsPerGame: 2.3, assistsPerGame: 5.2, fieldGoalPct: 0.452, threePointPct: 0.404, freeThrowPct: 0.854 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2007-08", yearLabel: "2007-08 (Sophomore, All-American, Big 12 POY)", sortOrder: 202, gamesPlayed: 38, minutesPerGame: 35.5, pointsPerGame: 19.2, reboundsPerGame: 2.5, assistsPerGame: 6.2, fieldGoalPct: 0.470, threePointPct: 0.422, freeThrowPct: 0.892 },
        { level: "PROFESSIONAL", teamName: "Charlotte Bobcats", season: "2008-09", yearLabel: "2008-09 (Rookie, #9 pick)", sortOrder: 301, gamesPlayed: 72, pointsPerGame: 11.7, reboundsPerGame: 1.9, assistsPerGame: 5.5, fieldGoalPct: 0.413, threePointPct: 0.366, freeThrowPct: 0.847 },
        { level: "PROFESSIONAL", teamName: "Indiana Pacers", season: "2012-13", yearLabel: "2012-13", sortOrder: 305, gamesPlayed: 78, pointsPerGame: 9.7, reboundsPerGame: 1.5, assistsPerGame: 4.3, threePointPct: 0.386 },
        { level: "PROFESSIONAL", teamName: "Orlando Magic", season: "2018-19", yearLabel: "2018-19 (Playoff hero)", sortOrder: 311, gamesPlayed: 81, pointsPerGame: 11.7, reboundsPerGame: 1.7, assistsPerGame: 5.3, threePointPct: 0.411 },
      ],
      careerEvents: [
        { year: 2008, title: "Selected #9 overall by the Charlotte Bobcats", eventType: "DRAFT" },
        { year: 2019, title: "Hit game-winning three vs Toronto in NBA Playoffs (with Orlando)", eventType: "OTHER" },
        { year: 2022, title: "Retired from NBA after 14 seasons", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "aj-abrams",
      firstName: "A.J.",
      lastName: "Abrams",
      birthYear: 1986,
      hometown: "Plano, TX",
      highSchool: "Plano East Senior High School, Plano, TX",
      isFeatured: false,
      bio: "An elite freshman three-point shooter who played alongside Kevin Durant. Would become Texas's all-time leader in three-pointers made.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Basketball Trainer / Youth Coach",
        location: "Dallas-Fort Worth, TX",
        statusNote:
          "Played all four years at Texas (2005-2009), finishing as the program's all-time leader in three-pointers made (337 at the time). Went undrafted in 2009 and played professionally overseas in Israel (Maccabi Haifa), France, and other European leagues through 2015. Now involved in basketball training and youth coaching in the DFW area.",
        sourceUrl: "https://en.wikipedia.org/wiki/A.J._Abrams",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 3,
        position: "Shooting Guard",
        yearsAtSchool: "2005-2009",
        statsNote: "Sophomore • 12.0 PPG • Elite three-point shooter",
        gamesPlayed: 35,
        pointsPerGame: 12.0,
        reboundsPerGame: 1.5,
        assistsPerGame: 1.2,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2005-06", yearLabel: "2005-06 (Freshman)", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 8.5, reboundsPerGame: 1.3, assistsPerGame: 1.0, threePointPct: 0.395 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2006-07", yearLabel: "2006-07 (Sophomore)", sortOrder: 202, gamesPlayed: 35, pointsPerGame: 12.0, reboundsPerGame: 1.5, assistsPerGame: 1.2, threePointPct: 0.410 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2007-08", yearLabel: "2007-08 (Junior)", sortOrder: 203, gamesPlayed: 38, pointsPerGame: 14.8, reboundsPerGame: 1.8, assistsPerGame: 1.7, threePointPct: 0.422 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2008-09", yearLabel: "2008-09 (Senior, all-time 3PT leader)", sortOrder: 204, gamesPlayed: 34, pointsPerGame: 13.1, reboundsPerGame: 1.8, assistsPerGame: 2.0, threePointPct: 0.398 },
      ],
      careerEvents: [
        { year: 2009, title: "Graduated as Texas's all-time leader in three-pointers made (337)", eventType: "CAREER" },
      ],
    },
    {
      slug: "damion-james",
      firstName: "Damion",
      lastName: "James",
      birthYear: 1987,
      hometown: "Nacogdoches, TX",
      highSchool: "Nacogdoches High School, Nacogdoches, TX",
      isFeatured: false,
      bio: "A freshman forward who would develop into a First-Team All-Big 12 selection by his senior year.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Community Engagement / Youth Basketball",
        location: "Nacogdoches, TX",
        statusNote:
          "Played all four years at Texas (2006-2010), averaging 16.2 PPG and 9.1 RPG as a senior (First-Team All-Big 12). Selected #24 overall by the Dallas Mavericks in 2010, traded to the New Jersey Nets. Played 2 NBA seasons (56 games). Later played overseas in Turkey, Israel, Puerto Rico, and South Korea. Now involved in community engagement and youth basketball in East Texas.",
        sourceUrl: "https://en.wikipedia.org/wiki/Damion_James",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 5,
        position: "Small Forward / Power Forward",
        yearsAtSchool: "2006-2010",
        statsNote: "Freshman • 5.3 PPG • Would become First-Team All-Big 12 senior",
        gamesPlayed: 26,
        pointsPerGame: 5.3,
        reboundsPerGame: 4.1,
        assistsPerGame: 0.5,
      },
      seasonStats: [
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2006-07", yearLabel: "2006-07 (Freshman)", sortOrder: 201, gamesPlayed: 26, pointsPerGame: 5.3, reboundsPerGame: 4.1, assistsPerGame: 0.5 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2007-08", yearLabel: "2007-08 (Sophomore)", sortOrder: 202, gamesPlayed: 35, pointsPerGame: 10.5, reboundsPerGame: 7.0, assistsPerGame: 0.9 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2008-09", yearLabel: "2008-09 (Junior)", sortOrder: 203, gamesPlayed: 34, pointsPerGame: 12.8, reboundsPerGame: 8.3, assistsPerGame: 1.1 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2009-10", yearLabel: "2009-10 (Senior, First-Team All-Big 12)", sortOrder: 204, gamesPlayed: 34, pointsPerGame: 16.2, reboundsPerGame: 9.1, assistsPerGame: 1.5 },
        { level: "PROFESSIONAL", teamName: "New Jersey Nets", season: "2010-11", yearLabel: "2010-11 (Rookie, #24 pick)", sortOrder: 301, gamesPlayed: 30, pointsPerGame: 3.5, reboundsPerGame: 2.5, assistsPerGame: 0.3 },
      ],
      careerEvents: [
        { year: 2010, title: "Selected #24 overall by the Dallas Mavericks (traded to Nets)", eventType: "DRAFT" },
      ],
    },
    {
      slug: "rick-barnes",
      firstName: "Rick",
      lastName: "Barnes",
      birthYear: 1954,
      hometown: "Hickory, NC",
      highSchool: "Hickory High School, Hickory, NC",
      isFeatured: true,
      bio: "The winningest coach in Texas basketball history who recruited Kevin Durant — arguably the greatest recruiting achievement in college basketball history. Barnes led Texas to 16 NCAA Tournament appearances in 17 years.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "University of Tennessee",
        league: "SEC",
        location: "Knoxville, TN",
        statusNote:
          "After 17 seasons at Texas (1998-2015, 402-180 record, 16 NCAA Tournaments), Barnes was fired despite being the winningest coach in program history. Immediately hired by Tennessee, where he has rebuilt the Volunteers into a perennial top-10 program. Multiple SEC Coach of the Year awards (2018, 2019). Led Tennessee to the #1 overall seed in the 2019 NCAA Tournament. Still coaching at Tennessee in 2025-26, one of the most respected active coaches in college basketball.",
        sourceUrl: "https://en.wikipedia.org/wiki/Rick_Barnes",
      },
      membership: {
        role: "HEAD_COACH",
        position: "Head Coach",
        yearsAtSchool: "1998-2015",
        statsNote: "25-10 • Coached Kevin Durant • 402-180 at Texas (winningest in program history)",
      },
      careerEvents: [
        { year: 2003, title: "Led Texas to Final Four", eventType: "CAREER" },
        { year: 2007, title: "Coached Kevin Durant — first freshman Naismith POY", eventType: "CAREER" },
        { year: 2015, title: "Fired by Texas after 402 wins; hired by Tennessee", eventType: "CAREER" },
        { year: 2019, title: "Led Tennessee to #1 overall seed in NCAA Tournament", eventType: "CAREER" },
      ],
    },
  ],
};
