import type { TeamSeed } from "./types";

export const texasBasketball2007: TeamSeed = {
  slug: "texas-basketball-2007",
  name: "Texas Longhorns",
  season: "2006-2007",
  sport: "Men's Basketball",
  school: "University of Texas",
  conference: "Big 12",
  accomplishment: "NCAA Tournament Second Round (25-10)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/251.png",
  mascotName: "Bevo",
  people: [
    {
      slug: "kevin-durant",
      firstName: "Kevin",
      lastName: "Durant",
      birthYear: 1988,
      hometown: "Suitland, MD",
      highSchool: "Montrose Christian School, Rockville, MD",
      isFeatured: true,
      imageUrl: "https://cdn.nba.com/headshots/nba/latest/1040x760/201142.png",
      bio: "The greatest one-and-done in college basketball history. Durant averaged 25.8 PPG and 11.1 RPG as a freshman — the first freshman ever to win a major National Player of the Year award (Naismith, Wooden, AP). One of the most transcendent talents the sport has ever seen.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Phoenix Suns",
        league: "NBA",
        location: "Phoenix, AZ",
        statusNote:
          "Selected #2 overall by the Seattle SuperSonics in 2007 (moved to OKC in 2008). One of the greatest scorers in NBA history — 14-time All-Star, 4-time scoring champion, 2014 MVP, 2-time NBA Champion and Finals MVP with Golden State (2017, 2018), 2-time Olympic gold medalist. Career average ~27 PPG across 18 seasons with OKC, Golden State, Brooklyn, and Phoenix. Also a visionary entrepreneur through Thirty Five Ventures, with investments in dozens of companies. One of the wealthiest and most influential athletes in the world.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kevin_Durant",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 35,
        position: "Small Forward",
        yearsAtSchool: "2006-2007",
        statsNote: "Freshman • Unanimous National POY • First freshman to win Naismith/Wooden • 25.8 PPG, 11.1 RPG",
        gamesPlayed: 35,
        pointsPerGame: 25.8,
        reboundsPerGame: 11.1,
        assistsPerGame: 1.3,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Montrose Christian School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 35.0, reboundsPerGame: 15.0, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2006-07", yearLabel: "2006-07 (Freshman, Unanimous Naismith/Wooden POY)", sortOrder: 201, gamesPlayed: 35, minutesPerGame: 35.9, pointsPerGame: 25.8, reboundsPerGame: 11.1, assistsPerGame: 1.3, stealsPerGame: 1.9, blocksPerGame: 1.9, fieldGoalPct: 0.473, threePointPct: 0.404, freeThrowPct: 0.816 },
        { level: "PROFESSIONAL", teamName: "Seattle SuperSonics", season: "2007-08", yearLabel: "2007-08 (Rookie, ROY)", sortOrder: 301, gamesPlayed: 80, pointsPerGame: 20.3, reboundsPerGame: 4.4, assistsPerGame: 2.4, stealsPerGame: 1.0, fieldGoalPct: 0.430, threePointPct: 0.288, freeThrowPct: 0.873 },
        { level: "PROFESSIONAL", teamName: "Oklahoma City Thunder", season: "2009-10", yearLabel: "2009-10 (Scoring Title)", sortOrder: 303, gamesPlayed: 82, pointsPerGame: 30.1, reboundsPerGame: 7.6, assistsPerGame: 2.8, fieldGoalPct: 0.476, threePointPct: 0.365, freeThrowPct: 0.900 },
        { level: "PROFESSIONAL", teamName: "Oklahoma City Thunder", season: "2011-12", yearLabel: "2011-12 (NBA Finals)", sortOrder: 305, gamesPlayed: 66, pointsPerGame: 28.0, reboundsPerGame: 8.0, assistsPerGame: 3.5, fieldGoalPct: 0.496, threePointPct: 0.387, freeThrowPct: 0.860 },
        { level: "PROFESSIONAL", teamName: "Oklahoma City Thunder", season: "2013-14", yearLabel: "2013-14 (MVP!)", sortOrder: 307, gamesPlayed: 81, pointsPerGame: 32.0, reboundsPerGame: 7.4, assistsPerGame: 5.5, stealsPerGame: 1.3, fieldGoalPct: 0.503, threePointPct: 0.391, freeThrowPct: 0.873 },
        { level: "PROFESSIONAL", teamName: "Golden State Warriors", season: "2016-17", yearLabel: "2016-17 (Champion, Finals MVP)", sortOrder: 310, gamesPlayed: 62, pointsPerGame: 25.1, reboundsPerGame: 8.3, assistsPerGame: 4.8, fieldGoalPct: 0.537, threePointPct: 0.375, freeThrowPct: 0.875 },
        { level: "PROFESSIONAL", teamName: "Golden State Warriors", season: "2017-18", yearLabel: "2017-18 (Champion, Finals MVP)", sortOrder: 311, gamesPlayed: 68, pointsPerGame: 26.4, reboundsPerGame: 6.8, assistsPerGame: 5.4, fieldGoalPct: 0.516, threePointPct: 0.419, freeThrowPct: 0.889 },
        { level: "PROFESSIONAL", teamName: "Brooklyn Nets", season: "2020-21", yearLabel: "2020-21", sortOrder: 314, gamesPlayed: 35, pointsPerGame: 26.9, reboundsPerGame: 7.1, assistsPerGame: 5.6, fieldGoalPct: 0.537, threePointPct: 0.450, freeThrowPct: 0.882 },
        { level: "PROFESSIONAL", teamName: "Phoenix Suns", season: "2023-24", yearLabel: "2023-24", sortOrder: 317, gamesPlayed: 75, pointsPerGame: 27.1, reboundsPerGame: 6.6, assistsPerGame: 5.0, fieldGoalPct: 0.523, threePointPct: 0.415, freeThrowPct: 0.856 },
      ],
      careerEvents: [
        { year: 2007, title: "Unanimous National Player of the Year — first freshman to win Naismith/Wooden", eventType: "AWARD" },
        { year: 2007, title: "Selected #2 overall by the Seattle SuperSonics", eventType: "DRAFT" },
        { year: 2008, title: "Won NBA Rookie of the Year", eventType: "AWARD" },
        { year: 2014, title: "Won NBA Most Valuable Player award (32.0 PPG)", eventType: "AWARD" },
        { year: 2017, title: "Won NBA Championship with Warriors (Finals MVP)", eventType: "CHAMPIONSHIP" },
        { year: 2018, title: "Won second consecutive NBA Championship (Finals MVP)", eventType: "CHAMPIONSHIP" },
        { year: 2023, title: "Traded to the Phoenix Suns", eventType: "TRADE" },
      ],
    },
    {
      slug: "dj-augustin",
      firstName: "D.J.",
      lastName: "Augustin",
      birthYear: 1987,
      hometown: "New Orleans, LA",
      highSchool: "Brother Martin High School, New Orleans, LA",
      isFeatured: true,
      bio: "A dynamic freshman point guard who averaged 14.4 PPG and 5.2 APG alongside Kevin Durant. Would become the #9 overall pick after his sophomore year.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NBA Player / Mentor",
        location: "Texas",
        statusNote:
          "Selected #9 overall by the Charlotte Bobcats in 2008 after a sophomore season averaging 19.2 PPG (First-Team All-American). Played 14 NBA seasons across 10 teams, most notably with the Orlando Magic (2018-19 playoff run where he hit a game-winning three against Toronto). Career averages: 10.0 PPG, 4.0 APG. Retired after the 2021-22 season. Has been involved in mentoring young players in the Texas/Louisiana area.",
        sourceUrl: "https://en.wikipedia.org/wiki/D.J._Augustin",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 14,
        position: "Point Guard",
        yearsAtSchool: "2006-2008",
        statsNote: "Freshman • 14.4 PPG, 5.2 APG • Kevin Durant's PG • Future #9 pick",
        gamesPlayed: 32,
        pointsPerGame: 14.4,
        reboundsPerGame: 2.3,
        assistsPerGame: 5.2,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Brother Martin High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 26.6, reboundsPerGame: 2.3, assistsPerGame: 8.8 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2006-07", yearLabel: "2006-07 (Freshman)", sortOrder: 201, gamesPlayed: 32, pointsPerGame: 14.4, reboundsPerGame: 2.3, assistsPerGame: 5.2, fieldGoalPct: 0.452, threePointPct: 0.404, freeThrowPct: 0.854 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2007-08", yearLabel: "2007-08 (Sophomore, All-American, Big 12 POY)", sortOrder: 202, gamesPlayed: 38, minutesPerGame: 35.5, pointsPerGame: 19.2, reboundsPerGame: 2.5, assistsPerGame: 6.2, fieldGoalPct: 0.470, threePointPct: 0.422, freeThrowPct: 0.892 },
        { level: "PROFESSIONAL", teamName: "Charlotte Bobcats", season: "2008-09", yearLabel: "2008-09 (Rookie, #9 pick)", sortOrder: 301, gamesPlayed: 72, pointsPerGame: 11.7, reboundsPerGame: 1.9, assistsPerGame: 5.5, fieldGoalPct: 0.413, threePointPct: 0.366, freeThrowPct: 0.847 },
        { level: "PROFESSIONAL", teamName: "Indiana Pacers", season: "2012-13", yearLabel: "2012-13", sortOrder: 305, gamesPlayed: 78, pointsPerGame: 9.7, reboundsPerGame: 1.5, assistsPerGame: 4.3, threePointPct: 0.386 },
        { level: "PROFESSIONAL", teamName: "Orlando Magic", season: "2018-19", yearLabel: "2018-19 (Playoff hero)", sortOrder: 311, gamesPlayed: 81, pointsPerGame: 11.7, reboundsPerGame: 1.7, assistsPerGame: 5.3, threePointPct: 0.411 },
      ],
      careerEvents: [
        { year: 2008, title: "Selected #9 overall by the Charlotte Bobcats", eventType: "DRAFT" },
        { year: 2019, title: "Hit game-winning three vs Toronto in NBA Playoffs (with Orlando)", eventType: "OTHER" },
        { year: 2022, title: "Retired from NBA after 14 seasons", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "aj-abrams",
      firstName: "A.J.",
      lastName: "Abrams",
      birthYear: 1986,
      hometown: "Plano, TX",
      highSchool: "Plano East Senior High School, Plano, TX",
      isFeatured: false,
      bio: "An elite freshman three-point shooter who played alongside Kevin Durant. Would become Texas's all-time leader in three-pointers made.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Basketball Trainer / Youth Coach",
        location: "Dallas-Fort Worth, TX",
        statusNote:
          "Played all four years at Texas (2005-2009), finishing as the program's all-time leader in three-pointers made (337 at the time). Went undrafted in 2009 and played professionally overseas in Israel (Maccabi Haifa), France, and other European leagues through 2015. Now involved in basketball training and youth coaching in the DFW area.",
        sourceUrl: "https://en.wikipedia.org/wiki/A.J._Abrams",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 3,
        position: "Shooting Guard",
        yearsAtSchool: "2005-2009",
        statsNote: "Sophomore • 12.0 PPG • Elite three-point shooter",
        gamesPlayed: 35,
        pointsPerGame: 12.0,
        reboundsPerGame: 1.5,
        assistsPerGame: 1.2,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Plano East Senior High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 23.0, reboundsPerGame: 1.5, assistsPerGame: 3.6 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2005-06", yearLabel: "2005-06 (Freshman)", sortOrder: 201, gamesPlayed: 37, pointsPerGame: 8.5, reboundsPerGame: 1.3, assistsPerGame: 1.0, threePointPct: 0.395 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2006-07", yearLabel: "2006-07 (Sophomore)", sortOrder: 202, gamesPlayed: 35, pointsPerGame: 12.0, reboundsPerGame: 1.5, assistsPerGame: 1.2, threePointPct: 0.410 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2007-08", yearLabel: "2007-08 (Junior)", sortOrder: 203, gamesPlayed: 38, pointsPerGame: 14.8, reboundsPerGame: 1.8, assistsPerGame: 1.7, threePointPct: 0.422 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2008-09", yearLabel: "2008-09 (Senior, all-time 3PT leader)", sortOrder: 204, gamesPlayed: 34, pointsPerGame: 13.1, reboundsPerGame: 1.8, assistsPerGame: 2.0, threePointPct: 0.398 },
      ],
      careerEvents: [
        { year: 2009, title: "Graduated as Texas's all-time leader in three-pointers made (337)", eventType: "CAREER" },
      ],
    },
    {
      slug: "damion-james",
      firstName: "Damion",
      lastName: "James",
      birthYear: 1987,
      hometown: "Nacogdoches, TX",
      highSchool: "Nacogdoches High School, Nacogdoches, TX",
      isFeatured: false,
      bio: "A freshman forward who would develop into a First-Team All-Big 12 selection by his senior year.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Community Engagement / Youth Basketball",
        location: "Nacogdoches, TX",
        statusNote:
          "Played all four years at Texas (2006-2010), averaging 16.2 PPG and 9.1 RPG as a senior (First-Team All-Big 12). Selected #24 overall by the Dallas Mavericks in 2010, traded to the New Jersey Nets. Played 2 NBA seasons (56 games). Later played overseas in Turkey, Israel, Puerto Rico, and South Korea. Now involved in community engagement and youth basketball in East Texas.",
        sourceUrl: "https://en.wikipedia.org/wiki/Damion_James",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 5,
        position: "Small Forward / Power Forward",
        yearsAtSchool: "2006-2010",
        statsNote: "Freshman • 5.3 PPG • Would become First-Team All-Big 12 senior",
        gamesPlayed: 26,
        pointsPerGame: 5.3,
        reboundsPerGame: 4.1,
        assistsPerGame: 0.5,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Nacogdoches High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 12.9, reboundsPerGame: 8.3, blocksPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2006-07", yearLabel: "2006-07 (Freshman)", sortOrder: 201, gamesPlayed: 26, pointsPerGame: 5.3, reboundsPerGame: 4.1, assistsPerGame: 0.5 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2007-08", yearLabel: "2007-08 (Sophomore)", sortOrder: 202, gamesPlayed: 35, pointsPerGame: 10.5, reboundsPerGame: 7.0, assistsPerGame: 0.9 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2008-09", yearLabel: "2008-09 (Junior)", sortOrder: 203, gamesPlayed: 34, pointsPerGame: 12.8, reboundsPerGame: 8.3, assistsPerGame: 1.1 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2009-10", yearLabel: "2009-10 (Senior, First-Team All-Big 12)", sortOrder: 204, gamesPlayed: 34, pointsPerGame: 16.2, reboundsPerGame: 9.1, assistsPerGame: 1.5 },
        { level: "PROFESSIONAL", teamName: "New Jersey Nets", season: "2010-11", yearLabel: "2010-11 (Rookie, #24 pick)", sortOrder: 301, gamesPlayed: 30, pointsPerGame: 3.5, reboundsPerGame: 2.5, assistsPerGame: 0.3 },
      ],
      careerEvents: [
        { year: 2010, title: "Selected #24 overall by the Dallas Mavericks (traded to Nets)", eventType: "DRAFT" },
      ],
    },
    {
      slug: "connor-atchley",
      firstName: "Connor",
      lastName: "Atchley",
      birthYear: 1986,
      hometown: "Clear Lake, TX",
      highSchool: "Clear Lake High School, Houston, TX",
      isFeatured: false,
      bio: "A sophomore center who would finish with the third-most blocks (189) in Texas history.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Graduate Manager / Private Sector",
        location: "Austin, TX",
        statusNote: "Finished career at Texas with the third-most blocks (189) in school history. Three-time Academic All-Big 12. Earned bachelor's in corporate communications, then master's in advertising at UT. Undrafted, played two D-League seasons. Returned to Texas as a graduate manager under Barnes in 2011-12.",
        sourceUrl: "https://texaslonghorns.com/sports/mens-basketball/roster/connor-atchley/2340",
      },
      membership: { role: "PLAYER", jerseyNumber: 32, position: "Center / Forward", yearsAtSchool: "2005-2010", statsNote: "Sophomore • 3rd all-time in blocks (189)", gamesPlayed: 35, pointsPerGame: 5.2, reboundsPerGame: 3.5, assistsPerGame: 0.4 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Clear Lake High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 12.8, reboundsPerGame: 7.5, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2006-07", yearLabel: "2006-07 (Sophomore)", sortOrder: 202, gamesPlayed: 35, pointsPerGame: 5.2, reboundsPerGame: 3.5, assistsPerGame: 0.4 },
      ],
      careerEvents: [],
    },
    {
      slug: "justin-mason",
      firstName: "Justin",
      lastName: "Mason",
      birthYear: 1987,
      hometown: "Killeen, TX",
      highSchool: "Shoemaker High School, Killeen, TX",
      isFeatured: false,
      bio: "A freshman guard who would become a three-year team captain and four-year starter.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Director / Head Coach",
        currentEmployer: "1891 Basketball",
        location: "Texas",
        statusNote: "Three-year team captain, four-year starter. Ranked 3rd all-time in career games played (141) and 2nd in career starts (132). Led Texas to the 2008 Elite Eight. Named to Big 12 All-Defensive Team multiple times. Now Director and Head Coach of 1891 Basketball, a basketball training organization.",
        sourceUrl: "https://www.1891basketball.com/about-us",
      },
      membership: { role: "PLAYER", jerseyNumber: 24, position: "Guard", yearsAtSchool: "2006-2010", statsNote: "Freshman • Would become 3-year captain • 4.5 PPG", gamesPlayed: 35, pointsPerGame: 4.5, reboundsPerGame: 2.2, assistsPerGame: 1.8 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Shoemaker High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 11.8, reboundsPerGame: 2.2, assistsPerGame: 4.3 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2006-07", yearLabel: "2006-07 (Freshman)", sortOrder: 201, gamesPlayed: 35, pointsPerGame: 4.5, reboundsPerGame: 2.2, assistsPerGame: 1.8 },
      ],
      careerEvents: [],
    },
    {
      slug: "dexter-pittman",
      firstName: "Dexter",
      lastName: "Pittman",
      birthYear: 1988,
      hometown: "Rosenberg, TX",
      highSchool: "B.F. Terry High School, Rosenberg, TX",
      isFeatured: false,
      bio: "A freshman center who would develop into a dominant Big 12 player and 2012 NBA champion.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        location: "Mexico/Texas",
        statusNote: "Developed from an overweight freshman into a dominant Big 12 center. Drafted #32 overall by the Miami Heat in 2010. Won the 2012 NBA Championship with Miami alongside LeBron, Wade, and Bosh. Continued playing professionally through 2024 in Mexico (Halcones de Xalapa). A 14-year professional career.",
        sourceUrl: "https://en.wikipedia.org/wiki/Dexter_Pittman",
      },
      membership: { role: "PLAYER", jerseyNumber: 34, position: "Center", yearsAtSchool: "2006-2010", statsNote: "Freshman • 1.8 PPG • Would become #32 pick and NBA champion", gamesPlayed: 25, pointsPerGame: 1.8, reboundsPerGame: 1.5, assistsPerGame: 0.1 },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "B.F. Terry High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 7.7, reboundsPerGame: 5.0, blocksPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2006-07", yearLabel: "2006-07 (Freshman)", sortOrder: 201, gamesPlayed: 25, pointsPerGame: 1.8, reboundsPerGame: 1.5, assistsPerGame: 0.1 },
      ],
      careerEvents: [],
    },
    {
      slug: "matt-hill",
      firstName: "Matt",
      lastName: "Hill",
      birthYear: 1988,
      hometown: "Lincoln, NE",
      highSchool: "Lincoln Southeast High School, Lincoln, NE",
      isFeatured: false,
      bio: "Nebraska's Mr. Basketball and Gatorade Player of the Year who played alongside Kevin Durant as a freshman. Hill holds Lincoln Southeast's all-time records in points, rebounds, and blocks.",
      status: {
        occupationType: "COACH",
        currentTitle: "Assistant Coach",
        currentEmployer: "Charlotte Hornets",
        league: "NBA",
        location: "Charlotte, NC",
        statusNote:
          "Nebraska's Mr. Basketball (2006) who averaged 20.1 PPG and 12.7 RPG his senior year at Lincoln Southeast. At Texas (2006-10), battled foot and heel injuries but became a key frontcourt contributor. After college, briefly attempted pro play (a camp in China) before pivoting to coaching. Built his NBA career from the ground up — video analyst then player development coach with the Orlando Magic (2012-17), assistant coach with the Atlanta Hawks (2018-23), assistant with the Phoenix Suns (2023-24), and since 2024 an assistant coach with the Charlotte Hornets.",
        sourceUrl: "https://en.wikipedia.org/wiki/Matt_Hill_(basketball)",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 21,
        position: "Power Forward / Center",
        yearsAtSchool: "2006-2010",
        statsNote: "Freshman • Nebraska Mr. Basketball • 3.2 PPG • Battled foot injury",
        gamesPlayed: 23,
        pointsPerGame: 3.2,
        reboundsPerGame: 2.5,
        assistsPerGame: 0.2,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Lincoln Southeast High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 20.1, reboundsPerGame: 12.7, blocksPerGame: 3.6 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2006-07", yearLabel: "2006-07 (Freshman, played w/ Durant)", sortOrder: 201, gamesPlayed: 23, pointsPerGame: 3.2, reboundsPerGame: 2.5, assistsPerGame: 0.2, blocksPerGame: 0.7 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2007-08", yearLabel: "2007-08 (Sophomore)", sortOrder: 202, gamesPlayed: 35, pointsPerGame: 5.8, reboundsPerGame: 4.5, assistsPerGame: 0.3 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2009-10", yearLabel: "2009-10 (Senior, after medical redshirt)", sortOrder: 204, gamesPlayed: 33, pointsPerGame: 7.2, reboundsPerGame: 5.3, assistsPerGame: 0.5 },
      ],
      careerEvents: [
        { year: 2006, title: "Named Nebraska Mr. Basketball and Gatorade Player of the Year", eventType: "AWARD" },
        { year: 2012, title: "Began NBA coaching career as video analyst with Orlando Magic", eventType: "CAREER" },
        { year: 2018, title: "Promoted to assistant coach with the Atlanta Hawks", eventType: "CAREER" },
        { year: 2024, title: "Joined Charlotte Hornets as assistant coach", eventType: "CAREER" },
      ],
    },
    {
      slug: "jd-lewis",
      firstName: "J.D.",
      lastName: "Lewis",
      birthYear: 1985,
      hometown: "Amarillo, TX",
      highSchool: "Amarillo High School, Amarillo, TX",
      isFeatured: false,
      bio: "A senior guard and veteran transfer from Midland College who provided perimeter scoring and leadership alongside Kevin Durant. Named Academic All-Big 12 First Team in 2006-07.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Executive Managing Director, Office Leasing",
        currentEmployer: "HPI Real Estate Services & Investments",
        location: "Austin, TX",
        statusNote:
          "A two-year letterwinner at Texas (2005-07) who transferred from Midland College, where he was an NJCAA first-team All-American. Shot an outstanding 50% from three-point range during his senior season alongside Kevin Durant. Named Academic All-Big 12 First Team in 2006-07. Earned a sports management degree and transitioned to commercial real estate in Austin, where he is now Executive Managing Director of Office Leasing at HPI Real Estate Services & Investments.",
        sourceUrl: "https://texaslonghorns.com/sports/mens-basketball/roster/j-d--lewis/198",
        linkedInUrl: "https://www.linkedin.com/in/j-d-lewis-56229514/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 13,
        position: "Shooting Guard",
        yearsAtSchool: "2005-2007",
        statsNote: "Senior • Academic All-Big 12 • 50% 3PT shooting senior year • 4.5 PPG",
        gamesPlayed: 35,
        pointsPerGame: 4.5,
        reboundsPerGame: 1.2,
        assistsPerGame: 1.8,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Amarillo High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 14.0, reboundsPerGame: 2.5, assistsPerGame: 3.0 },
        { level: "COLLEGE", teamName: "Midland College", season: "2004-05", yearLabel: "2004-05 (NJCAA All-American, 17.6 PPG)", sortOrder: 151, gamesPlayed: 30, pointsPerGame: 17.6, reboundsPerGame: 2.8, assistsPerGame: 2.5, threePointPct: 0.449 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2005-06", yearLabel: "2005-06 (Junior transfer)", sortOrder: 203, gamesPlayed: 37, pointsPerGame: 5.2, reboundsPerGame: 1.3, assistsPerGame: 1.5 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2006-07", yearLabel: "2006-07 (Senior, Academic All-Big 12)", sortOrder: 204, gamesPlayed: 35, pointsPerGame: 4.5, reboundsPerGame: 1.2, assistsPerGame: 1.8, threePointPct: 0.500 },
      ],
      careerEvents: [
        { year: 2005, title: "NJCAA first-team All-American at Midland College", eventType: "AWARD" },
        { year: 2007, title: "Named Academic All-Big 12 First Team; graduated from Texas", eventType: "AWARD" },
      ],
    },
    {
      slug: "harrison-smith",
      firstName: "Harrison",
      lastName: "Smith",
      birthYear: 1988,
      hometown: "Houston, TX",
      highSchool: "Jones High School, Houston, TX",
      isFeatured: false,
      bio: "A freshman reserve guard from Houston who played in 8 games during Kevin Durant's only season at Texas.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Sector",
        location: "Houston, TX",
        statusNote:
          "A freshman reserve guard from Jones High School in Houston who played 8 games during the 2006-07 season alongside Kevin Durant. Was ranked No. 96 nationally coming out of high school and named all-state and district MVP. Played three more seasons at Texas (2007-10), appearing in 59 total career games. Went undrafted; transitioned to the private sector in the Houston area after college.",
        sourceUrl: "https://texaslonghorns.com/sports/mens-basketball/roster/harrison-smith/2343",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 2,
        position: "Guard",
        yearsAtSchool: "2006-2010",
        statsNote: "Freshman • 8 games played • Reserve guard • 0.8 PPG",
        gamesPlayed: 8,
        pointsPerGame: 0.8,
        reboundsPerGame: 0.5,
        assistsPerGame: 0.3,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Jones High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 15.0, reboundsPerGame: 3.5, assistsPerGame: 4.0 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2006-07", yearLabel: "2006-07 (Freshman)", sortOrder: 201, gamesPlayed: 8, pointsPerGame: 0.8, reboundsPerGame: 0.5, assistsPerGame: 0.3 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2007-08", yearLabel: "2007-08 (Sophomore)", sortOrder: 202, gamesPlayed: 12, pointsPerGame: 1.5, reboundsPerGame: 0.8, assistsPerGame: 0.4 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2009-10", yearLabel: "2009-10 (Senior)", sortOrder: 204, gamesPlayed: 20, pointsPerGame: 2.5, reboundsPerGame: 1.0, assistsPerGame: 0.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "ian-mooney",
      firstName: "Ian",
      lastName: "Mooney",
      birthYear: 1984,
      hometown: "Austin, TX",
      highSchool: "St. Michael's Academy, Austin, TX",
      isFeatured: false,
      bio: "A senior walk-on forward who played a supporting role on the Kevin Durant team, earning a master's degree in advertising from UT. Would later found D1 Approved, an NIL platform for student-athletes.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Founder",
        currentEmployer: "D1 Approved",
        location: "Austin, TX",
        statusNote:
          "A walk-on forward who contributed to Texas through the 2003 Final Four, 2006 Elite Eight, and Kevin Durant's 2007 team. Earned his master's degree in advertising from UT. Built 15+ years of experience in media, tech, and publishing. Founded D1 Approved in March 2024 — an NIL education platform helping student-athletes build knowledge around Name, Image, and Likeness opportunities through edutainment content.",
        sourceUrl: "https://www.kvue.com/article/sports/ncaa/longhorns/d1-approved-nil-ian-mooney/269-5a4853e7-a4a0-4a15-b1bb-11bfea14010d",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 22,
        position: "Forward",
        yearsAtSchool: "2004-2007",
        statsNote: "Senior walk-on • 1.2 PPG • NIL entrepreneur post-career",
        gamesPlayed: 25,
        pointsPerGame: 1.2,
        reboundsPerGame: 0.8,
        assistsPerGame: 0.3,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "St. Michael's Academy", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 7.0, reboundsPerGame: 4.0, blocksPerGame: 1.0 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2005-06", yearLabel: "2005-06 (Junior walk-on, Elite Eight)", sortOrder: 203, gamesPlayed: 30, pointsPerGame: 1.0, reboundsPerGame: 0.8, assistsPerGame: 0.2 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2006-07", yearLabel: "2006-07 (Senior walk-on, Kevin Durant era)", sortOrder: 204, gamesPlayed: 25, pointsPerGame: 1.2, reboundsPerGame: 0.8, assistsPerGame: 0.3 },
      ],
      careerEvents: [
        { year: 2007, title: "Graduated from Texas with master's in advertising", eventType: "CAREER" },
        { year: 2024, title: "Founded D1 Approved NIL platform for student-athletes", eventType: "CAREER" },
      ],
    },
    {
      slug: "craig-winder",
      firstName: "Craig",
      lastName: "Winder",
      birthYear: 1983,
      hometown: "Hebron, MD",
      highSchool: "North Harford High School, Pylesville, MD",
      isFeatured: false,
      bio: "A senior guard and NJCAA All-American transfer from Cecil Community College who provided veteran experience as the final piece of Kevin Durant's supporting cast.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Professional Basketball Player",
        location: "Maryland",
        statusNote:
          "A two-year letterwinner at Texas (2005-07), Winder transferred from Cecil Community College where he earned NJCAA first-team All-America honors and averaged 18.4 PPG over two seasons. Played 52 career games at Texas across two NCAA Tournament teams, including the 2006 Elite Eight squad and the Kevin Durant team. After graduating, played in the G League (Rio Grande Valley Vipers, scoring a season-high 31 points in February 2010) and professionally in China (Ningxia Hanas) before returning to Maryland.",
        sourceUrl: "https://texaslonghorns.com/news/2007/8/17/081707aaa_505",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 34,
        position: "Shooting Guard",
        yearsAtSchool: "2005-2007",
        statsNote: "Senior • NJCAA All-American transfer • 3.8 PPG alongside Kevin Durant",
        gamesPlayed: 35,
        pointsPerGame: 3.8,
        reboundsPerGame: 1.2,
        assistsPerGame: 1.0,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "North Harford High School", season: "Senior", yearLabel: "Senior", sortOrder: 1, pointsPerGame: 14.0, reboundsPerGame: 3.5, assistsPerGame: 2.5 },
        { level: "COLLEGE", teamName: "Cecil Community College", season: "2004-05", yearLabel: "2004-05 (NJCAA All-American)", sortOrder: 151, gamesPlayed: 30, pointsPerGame: 18.4, reboundsPerGame: 3.5, assistsPerGame: 2.2 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2005-06", yearLabel: "2005-06 (Junior transfer, Elite Eight)", sortOrder: 203, gamesPlayed: 37, pointsPerGame: 4.2, reboundsPerGame: 1.5, assistsPerGame: 1.2 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2006-07", yearLabel: "2006-07 (Senior, with Kevin Durant)", sortOrder: 204, gamesPlayed: 35, pointsPerGame: 3.8, reboundsPerGame: 1.2, assistsPerGame: 1.0 },
      ],
      careerEvents: [
        { year: 2006, title: "Part of Texas Elite Eight squad", eventType: "CAREER" },
        { year: 2010, title: "Scored 31-point game for Rio Grande Valley Vipers (G League)", eventType: "CAREER" },
      ],
    },
    {
      slug: "gary-johnson",
      firstName: "Gary",
      lastName: "Johnson",
      birthYear: 1988,
      hometown: "Houston, TX",
      highSchool: "Aldine High School, Houston, TX",
      isFeatured: false,
      bio: "A four-star recruit from Houston who signed with Texas in the class of 2007, becoming part of Rick Barnes' post-Durant rebuilding era. Johnson wore jersey number 1 as tribute to former Texas stars T.J. Ford and Daniel Gibson. He appeared in 88 career games across four seasons (2007-11), twice earning Big 12 All-Reserve Team recognition.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Retired Professional Basketball Player",
        location: "Houston, TX",
        statusNote:
          "After averaging 9.4 PPG and 5.6 RPG as a senior, Johnson went undrafted in 2011. He pursued a professional career internationally, playing in South America, Australia, Chile, Dominican Republic, Ecuador, Israel, Lithuania, and Mexico. Suffered a skull fracture in a second-division Israeli league game in 2012 while playing for Hapoel Galil Elyon, requiring plastic surgery and a lengthy recovery. Made a full recovery and continued his playing career. Transitioned to working with youth in the Houston area after retiring.",
        sourceUrl: "https://texaslonghorns.com/sports/mens-basketball/roster/gary-johnson/2360",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 1,
        position: "Power Forward",
        yearsAtSchool: "2007-2011",
        statsNote: "2x Big 12 All-Reserve Team • 88 career games • 5.6 RPG senior season",
        gamesPlayed: 22,
        pointsPerGame: 5.6,
        reboundsPerGame: 3.7,
        assistsPerGame: 0.4,
      },
      seasonStats: [
        { level: "HIGH_SCHOOL", teamName: "Aldine High School", season: "2006-07", yearLabel: "Senior", sortOrder: 101, pointsPerGame: 16.5, reboundsPerGame: 8.2, blocksPerGame: 2.1 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2007-08", yearLabel: "2007-08 (Freshman, cleared to play Jan. 2)", sortOrder: 201, gamesPlayed: 22, pointsPerGame: 5.6, reboundsPerGame: 3.7, assistsPerGame: 0.4 },
        { level: "COLLEGE", teamName: "Texas Longhorns", season: "2010-11", yearLabel: "2010-11 (Senior, Big 12 All-Reserve)", sortOrder: 204, gamesPlayed: 34, pointsPerGame: 9.4, reboundsPerGame: 5.6, assistsPerGame: 1.0, fieldGoalPct: 0.547 },
      ],
      careerEvents: [
        { year: 2007, title: "Signed with Texas as a four-star recruit from Houston", eventType: "CAREER" },
        { year: 2011, title: "Named Big 12 All-Reserve Team for second time; graduated from Texas", eventType: "AWARD" },
        { year: 2012, title: "Suffered skull fracture playing in Israel; made full recovery", eventType: "OTHER" },
      ],
    },
    {
      slug: "rick-barnes",
      firstName: "Rick",
      lastName: "Barnes",
      birthYear: 1954,
      hometown: "Hickory, NC",
      highSchool: "Hickory High School, Hickory, NC",
      isFeatured: true,
      bio: "The winningest coach in Texas basketball history who recruited Kevin Durant — arguably the greatest recruiting achievement in college basketball history. Barnes led Texas to 16 NCAA Tournament appearances in 17 years.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "University of Tennessee",
        league: "SEC",
        location: "Knoxville, TN",
        statusNote:
          "After 17 seasons at Texas (1998-2015, 402-180 record, 16 NCAA Tournaments), Barnes was fired despite being the winningest coach in program history. Immediately hired by Tennessee, where he has rebuilt the Volunteers into a perennial top-10 program. Multiple SEC Coach of the Year awards (2018, 2019). Led Tennessee to the #1 overall seed in the 2019 NCAA Tournament. Still coaching at Tennessee in 2025-26, one of the most respected active coaches in college basketball.",
        sourceUrl: "https://en.wikipedia.org/wiki/Rick_Barnes",
      },
      membership: {
        role: "HEAD_COACH",
        position: "Head Coach",
        yearsAtSchool: "1998-2015",
        statsNote: "25-10 • Coached Kevin Durant • 402-180 at Texas (winningest in program history)",
      },
      careerEvents: [
        { year: 2003, title: "Led Texas to Final Four", eventType: "CAREER" },
        { year: 2007, title: "Coached Kevin Durant — first freshman Naismith POY", eventType: "CAREER" },
        { year: 2015, title: "Fired by Texas after 402 wins; hired by Tennessee", eventType: "CAREER" },
        { year: 2019, title: "Led Tennessee to #1 overall seed in NCAA Tournament", eventType: "CAREER" },
      ],
    },
  ],
};
