import type { TeamSeed } from "./types";

export const uncBasketball2025: TeamSeed = {
  slug: "unc-basketball-2025",
  name: "North Carolina Tar Heels",
  season: "2024-2025",
  sport: "Men's Basketball",
  school: "University of North Carolina",
  conference: "ACC",
  accomplishment: "2024-2025 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/153.png",
  mascotName: "Tar Heel",
  people: [
    {
      slug: "rj-davis",
      firstName: "RJ",
      lastName: "Davis",
      birthYear: 2001,
      hometown: "United States",
      highSchool: "United States",
      bio: "5th-year senior and UNC's all-time scoring leader. ACC POY.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "United States",
        statusNote: "UNC's career scoring leader. 2025 NBA Draft prospect.",
        sourceUrl: "https://en.wikipedia.org/wiki/RJ_Davis",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 18, reboundsPerGame: 4, assistsPerGame: 4.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 18, reboundsPerGame: 4, assistsPerGame: 4.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "seth-trimble",
      firstName: "Seth",
      lastName: "Trimble",
      birthYear: 2004,
      hometown: "United States",
      highSchool: "United States",
      bio: "Junior guard from Wisconsin who developed into a key contributor.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Player",
        location: "Chapel Hill, NC",
        statusNote: "Developing into one of UNC's top backcourt players.",
        sourceUrl: "https://en.wikipedia.org/wiki/Seth_Trimble",
      },
      membership: { role: "PLAYER", jerseyNumber: 7, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 11, reboundsPerGame: 3.5, assistsPerGame: 3 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 11, reboundsPerGame: 3.5, assistsPerGame: 3 },
      ],
      careerEvents: [],
    },
    {
      slug: "elliot-cadeau",
      firstName: "Elliot",
      lastName: "Cadeau",
      birthYear: 2005,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore point guard and former 5-star recruit.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Player",
        location: "Chapel Hill, NC",
        statusNote: "Top recruit who has developed into UNC's starting PG.",
        sourceUrl: "https://en.wikipedia.org/wiki/Elliot_Cadeau",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Point Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 10, reboundsPerGame: 3, assistsPerGame: 5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 10, reboundsPerGame: 3, assistsPerGame: 5 },
      ],
      careerEvents: [],
    },
    {
      slug: "hubert-davis",
      firstName: "Hubert",
      lastName: "Davis",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Former UNC player and NBA veteran who succeeded Roy Williams. Led UNC to the 2022 title game in his first season.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Fired in March 2026 after blowing 19-pt lead to VCU.",
        sourceUrl: "https://en.wikipedia.org/wiki/Hubert_Davis",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2022-2026" },
      seasonStats: [
        { level: "COACHING", teamName: "North Carolina Tar Heels", season: "2024-2025", yearLabel: "2024-2025", sortOrder: 217 },
      ],
      careerEvents: [],
    },
  ],
};
