import type { TeamSeed } from "./types";

export const uncBasketball2017: TeamSeed = {
  slug: "unc-basketball-2017",
  name: "North Carolina Tar Heels",
  season: "2016-2017",
  sport: "Men's Basketball",
  school: "University of North Carolina",
  conference: "ACC",
  accomplishment: "NCAA National Champions (33-7)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/153.png",
  mascotName: "Tar Heel",
  people: [
    {
      slug: "joel-berry-ii",
      firstName: "Joel",
      lastName: "Berry II",
      birthYear: 1996,
      hometown: "Lake Worth, FL",
      highSchool: "Lake Worth Community High School, Lake Worth, FL",
      isFeatured: true,
      bio: "The junior point guard who was named Most Outstanding Player of the 2017 Final Four after scoring 22 points in the championship win over Gonzaga. Returned for his senior year and was named first-team All-ACC.",
      status: {
        occupationType: "BROADCASTER_ANALYST",
        currentTitle: "College Basketball Analyst",
        currentEmployer: "ACC Network / ESPN",
        location: "Charlotte, NC",
        statusNote: "After going undrafted in 2018, Berry played briefly in the G League and overseas before transitioning to broadcasting. He joined the ACC Network in October 2021 as a studio analyst and regularly appears on the signature show 'Nothing But Net.' He provides insights on ACC basketball across ESPN platforms and has built a growing media career covering college basketball.",
        sourceUrl: "https://en.wikipedia.org/wiki/Joel_Berry_II",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Point Guard", yearsAtSchool: "2014-2018", statsNote: "2017 Final Four MOP • NCAA Champion", gamesPlayed: 36, pointsPerGame: 14.7, reboundsPerGame: 3.1, assistsPerGame: 3.6 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2016-17", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 36, minutesPerGame: 32.5, pointsPerGame: 14.7, reboundsPerGame: 3.1, assistsPerGame: 3.6, fieldGoalPct: 0.462, threePointPct: 0.389 },
      ],
      careerEvents: [
        { year: 2017, title: "Won NCAA National Championship — named Final Four MOP", eventType: "CHAMPIONSHIP", month: 4, day: 3 },
        { year: 2021, title: "Joined ACC Network as college basketball analyst", eventType: "CAREER_CHANGE" },
      ],
    },
    {
      slug: "justin-jackson-unc",
      firstName: "Justin",
      lastName: "Jackson",
      birthYear: 1995,
      hometown: "Houston, TX",
      highSchool: "Homeschooled / Houston, TX",
      isFeatured: true,
      bio: "The consensus first-team All-American junior wing who was UNC's leading scorer during the championship season. Selected #15 overall and won an NBA title with the Bucks in 2021.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "Ottawa Blackjacks (Canada Basketball League)",
        league: "CEBL (Canada)",
        location: "Ottawa, Canada",
        statusNote: "Selected #15 overall by Portland (traded to Sacramento) in 2017, Jackson played 6 NBA seasons with the Kings, Mavericks, Thunder, Bucks, Celtics, and Suns. He won an NBA Championship with the Milwaukee Bucks in 2021. After his NBA career, he continued playing internationally, joining the Ottawa Blackjacks in the Canadian Elite Basketball League in 2025.",
        sourceUrl: "https://en.wikipedia.org/wiki/Justin_Jackson_(basketball,_born_1995)",
      },
      membership: { role: "PLAYER", jerseyNumber: 44, position: "Small Forward", yearsAtSchool: "2014-2017", statsNote: "Consensus All-American • #15 pick • NCAA Champion", gamesPlayed: 40, pointsPerGame: 18.3, reboundsPerGame: 4.7, assistsPerGame: 2.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2016-17", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 40, minutesPerGame: 33.4, pointsPerGame: 18.3, reboundsPerGame: 4.7, assistsPerGame: 2.8, fieldGoalPct: 0.450, threePointPct: 0.374 },
        { level: "PROFESSIONAL", teamName: "Sacramento Kings", season: "2017-18", yearLabel: "2017-18 (Rookie)", sortOrder: 301, gamesPlayed: 68, pointsPerGame: 6.7, reboundsPerGame: 2.3 },
        { level: "PROFESSIONAL", teamName: "Milwaukee Bucks", season: "2020-21", yearLabel: "2020-21 (Champion)", sortOrder: 304, gamesPlayed: 15, pointsPerGame: 2.9 },
      ],
      careerEvents: [
        { year: 2017, title: "Won NCAA National Championship with UNC", eventType: "CHAMPIONSHIP", month: 4, day: 3 },
        { year: 2017, title: "Selected #15 overall by Portland (traded to Sacramento)", eventType: "DRAFT", month: 6, day: 22 },
        { year: 2021, title: "Won NBA Championship with Milwaukee Bucks", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "kennedy-meeks",
      firstName: "Kennedy",
      lastName: "Meeks",
      birthYear: 1995,
      hometown: "Charlotte, NC",
      highSchool: "West Charlotte High School, Charlotte, NC",
      bio: "The senior center who grabbed 25 rebounds in the Final Four (13 vs Oregon, 12 vs Gonzaga) to anchor UNC's championship frontcourt. A dominant interior presence.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Professional Basketball Player",
        location: "Charlotte, NC",
        statusNote: "After graduating from UNC, Meeks played briefly in the NBA G League and overseas. He returned to the Charlotte area and has been involved in community work and mentoring young players.",
        sourceUrl: "https://goheels.com/sports/mens-basketball/roster/kennedy-meeks/",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Center", yearsAtSchool: "2013-2017", statsNote: "25 rebounds in Final Four • Senior anchor • NCAA Champion", gamesPlayed: 40, pointsPerGame: 12.0, reboundsPerGame: 9.4, assistsPerGame: 1.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2016-17", yearLabel: "Senior", sortOrder: 204, gamesPlayed: 40, minutesPerGame: 26.3, pointsPerGame: 12.0, reboundsPerGame: 9.4, assistsPerGame: 1.2, fieldGoalPct: 0.564 },
      ],
      careerEvents: [
        { year: 2017, title: "Won NCAA National Championship with UNC", eventType: "CHAMPIONSHIP", month: 4, day: 3 },
      ],
    },
    {
      slug: "theo-pinson",
      firstName: "Theo",
      lastName: "Pinson",
      birthYear: 1995,
      hometown: "Greensboro, NC",
      highSchool: "Wesleyan Christian Academy, High Point, NC",
      bio: "The junior swingman whose energy, defense, and celebration antics made him the emotional heartbeat of the 2017 championship team. Known for his bench celebrations as much as his play.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "Mets de Guaynabo",
        league: "BSN (Puerto Rico)",
        location: "Puerto Rico",
        statusNote: "Pinson went undrafted in 2018 but carved out an NBA career with the Nets, Knicks, and Mavericks over 5 seasons. He announced retirement in January 2025 to focus on broadcasting and family, but came back to playing in May 2025, signing with Mets de Guaynabo in Puerto Rico where he scored 25 points in his debut. Known as one of the NBA's best bench celebration artists.",
        sourceUrl: "https://en.wikipedia.org/wiki/Theo_Pinson",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Small Forward / Guard", yearsAtSchool: "2014-2018", statsNote: "Emotional leader • Defensive spark • NCAA Champion", gamesPlayed: 37, pointsPerGame: 6.3, reboundsPerGame: 4.2, assistsPerGame: 3.0 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2016-17", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 37, minutesPerGame: 25.0, pointsPerGame: 6.3, reboundsPerGame: 4.2, assistsPerGame: 3.0 },
      ],
      careerEvents: [
        { year: 2017, title: "Won NCAA National Championship with UNC", eventType: "CHAMPIONSHIP", month: 4, day: 3 },
        { year: 2025, title: "Came out of retirement, signed with Mets de Guaynabo (Puerto Rico)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "luke-maye",
      firstName: "Luke",
      lastName: "Maye",
      birthYear: 1997,
      hometown: "Cornelius, NC",
      highSchool: "Hough High School, Cornelius, NC",
      isFeatured: true,
      bio: "The sophomore walk-on-turned-starter who hit the iconic buzzer-beating jumper to beat Kentucky in the Elite Eight — one of the most famous shots in UNC history. Brother of NFL quarterback Drake Maye.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "Kobe Storks",
        league: "B.League (Japan)",
        location: "Kobe, Japan",
        statusNote: "After starring at UNC for four years (becoming a first-team All-ACC player by his senior season), Maye went undrafted and played in the G League and internationally. He currently plays for the Kobe Storks in Japan's B.League. His brother Drake Maye was selected in the first round of the 2024 NFL Draft by the New England Patriots.",
        sourceUrl: "https://en.wikipedia.org/wiki/Luke_Maye",
      },
      membership: { role: "PLAYER", jerseyNumber: 32, position: "Power Forward", yearsAtSchool: "2015-2019", statsNote: "Buzzer-beater vs Kentucky • Walk-on to All-ACC • NCAA Champion", gamesPlayed: 37, pointsPerGame: 5.5, reboundsPerGame: 3.1 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2016-17", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 37, minutesPerGame: 14.0, pointsPerGame: 5.5, reboundsPerGame: 3.1, fieldGoalPct: 0.530 },
      ],
      careerEvents: [
        { year: 2017, title: "Hit buzzer-beating jumper to beat Kentucky in Elite Eight", eventType: "MILESTONE" },
        { year: 2017, title: "Won NCAA National Championship with UNC", eventType: "CHAMPIONSHIP", month: 4, day: 3 },
      ],
    },
    {
      slug: "isaiah-hicks",
      firstName: "Isaiah",
      lastName: "Hicks",
      birthYear: 1994,
      hometown: "Oxford, NC",
      highSchool: "J.F. Webb High School, Oxford, NC",
      bio: "A senior forward who provided toughness and scoring inside. Scored 13 points in the championship game win over Gonzaga.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Professional Basketball Player",
        location: "North Carolina",
        statusNote: "After UNC, Hicks played in the NBA G League and overseas. He has since returned to North Carolina.",
        sourceUrl: "https://goheels.com/sports/mens-basketball/roster/isaiah-hicks/",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Power Forward", yearsAtSchool: "2013-2017", statsNote: "13 pts in title game • Senior leader • NCAA Champion", gamesPlayed: 40, pointsPerGame: 11.4, reboundsPerGame: 5.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2016-17", yearLabel: "Senior", sortOrder: 204, gamesPlayed: 40, minutesPerGame: 22.6, pointsPerGame: 11.4, reboundsPerGame: 5.2, fieldGoalPct: 0.554 },
      ],
      careerEvents: [
        { year: 2017, title: "Won NCAA National Championship with UNC", eventType: "CHAMPIONSHIP", month: 4, day: 3 },
      ],
    },
    {
      slug: "tony-bradley",
      firstName: "Tony",
      lastName: "Bradley",
      birthYear: 1998,
      hometown: "Bartow, FL",
      highSchool: "Bartow High School, Bartow, FL",
      bio: "A freshman center who came off the bench during the championship run and declared for the draft after one season. Selected #28 overall.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "Overseas / G League",
        location: "United States",
        statusNote: "Selected #28 overall by the Lakers (traded to Jazz) in 2017, Bradley played 5 NBA seasons with the Jazz, 76ers, Bulls, and other teams. He has continued playing professionally in the G League and overseas.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tony_Bradley_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Center", yearsAtSchool: "2016-2017", statsNote: "One-and-done • #28 pick • NCAA Champion", gamesPlayed: 38, pointsPerGame: 3.5, reboundsPerGame: 2.7 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2016-17", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 38, minutesPerGame: 8.3, pointsPerGame: 3.5, reboundsPerGame: 2.7, fieldGoalPct: 0.618 },
      ],
      careerEvents: [
        { year: 2017, title: "Won NCAA National Championship with UNC", eventType: "CHAMPIONSHIP", month: 4, day: 3 },
        { year: 2017, title: "Selected #28 overall by Lakers (traded to Utah Jazz)", eventType: "DRAFT", month: 6, day: 22 },
      ],
    },
    {
      slug: "kenny-williams-unc",
      firstName: "Kenny",
      lastName: "Williams",
      birthYear: 1996,
      hometown: "Richmond, VA",
      highSchool: "Trinity Episcopal School, Richmond, VA",
      bio: "A sophomore guard who hit timely three-pointers throughout the tournament run. Became a full-time starter by his senior year.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Virginia",
        statusNote: "After graduating from UNC in 2019, Williams pursued professional basketball briefly before transitioning to a post-playing career in Virginia.",
        sourceUrl: "https://goheels.com/sports/mens-basketball/roster/kenny-williams/",
      },
      membership: { role: "PLAYER", jerseyNumber: 24, position: "Shooting Guard", yearsAtSchool: "2015-2019", statsNote: "Sophomore contributor • Perimeter shooter • NCAA Champion", gamesPlayed: 36, pointsPerGame: 3.8, reboundsPerGame: 1.9 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2016-17", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 36, minutesPerGame: 14.8, pointsPerGame: 3.8, reboundsPerGame: 1.9, threePointPct: 0.404 },
      ],
      careerEvents: [
        { year: 2017, title: "Won NCAA National Championship with UNC", eventType: "CHAMPIONSHIP", month: 4, day: 3 },
      ],
    },
    {
      slug: "nate-britt",
      firstName: "Nate",
      lastName: "Britt",
      birthYear: 1995,
      hometown: "Upper Marlboro, MD",
      highSchool: "Gonzaga College High School, Washington, DC",
      bio: "A junior backup point guard who provided steady ballhandling off the bench during the championship season. Son of a military family.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Maryland",
        statusNote: "After graduating from UNC, Britt played professional basketball overseas briefly before transitioning to a career outside basketball.",
        sourceUrl: "https://goheels.com/sports/mens-basketball/roster/nate-britt/",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Point Guard", yearsAtSchool: "2014-2018", statsNote: "Junior reserve PG • NCAA Champion", gamesPlayed: 30, pointsPerGame: 2.3, assistsPerGame: 1.4 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2016-17", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 30, minutesPerGame: 8.7, pointsPerGame: 2.3, assistsPerGame: 1.4 },
      ],
      careerEvents: [
        { year: 2017, title: "Won NCAA National Championship with UNC", eventType: "CHAMPIONSHIP", month: 4, day: 3 },
      ],
    },
    {
      slug: "seventh-woods",
      firstName: "Seventh",
      lastName: "Woods",
      birthYear: 1998,
      hometown: "Columbia, SC",
      highSchool: "Hammond School, Columbia, SC",
      bio: "A highly-touted freshman guard who was ranked the #1 point guard in his recruiting class. Known for his explosive athleticism and viral dunk mixtapes before arriving at UNC.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "Overseas",
        location: "United States",
        statusNote: "Despite being the #1 PG recruit in 2016, Woods never broke into the starting lineup at UNC. He transferred to South Carolina after 3 seasons and has since played professional basketball overseas and in minor leagues.",
        sourceUrl: "https://en.wikipedia.org/wiki/Seventh_Woods",
      },
      membership: { role: "PLAYER", jerseyNumber: 21, position: "Point Guard", yearsAtSchool: "2016-2019", statsNote: "#1 PG recruit • Freshman reserve • NCAA Champion", gamesPlayed: 22, pointsPerGame: 1.1, assistsPerGame: 0.7 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2016-17", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 22, minutesPerGame: 4.7, pointsPerGame: 1.1 },
      ],
      careerEvents: [
        { year: 2017, title: "Won NCAA National Championship with UNC", eventType: "CHAMPIONSHIP", month: 4, day: 3 },
      ],
    },
    {
      slug: "stilman-white",
      firstName: "Stilman",
      lastName: "White",
      birthYear: 1994,
      hometown: "Wilmington, NC",
      highSchool: "Eugene Ashley High School, Wilmington, NC",
      bio: "A walk-on junior guard and fan favorite who earned playing time through his toughness and defensive intensity. One of several local North Carolina products on the championship roster.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "North Carolina",
        statusNote: "After graduating from UNC, White returned to North Carolina where he has been involved in coaching and community basketball programs.",
        sourceUrl: "https://goheels.com/sports/mens-basketball/roster/stilman-white/",
      },
      membership: { role: "PLAYER", jerseyNumber: 11, position: "Guard", yearsAtSchool: "2013-2018", statsNote: "Walk-on guard • Fan favorite • NCAA Champion", gamesPlayed: 15, pointsPerGame: 0.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2016-17", yearLabel: "Junior (walk-on)", sortOrder: 203, gamesPlayed: 15, pointsPerGame: 0.5 },
      ],
      careerEvents: [
        { year: 2017, title: "Won NCAA National Championship with UNC", eventType: "CHAMPIONSHIP", month: 4, day: 3 },
      ],
    },
    {
      slug: "roy-williams",
      firstName: "Roy",
      lastName: "Williams",
      birthYear: 1950,
      hometown: "Spruce Pine, NC",
      highSchool: "T.C. Roberson High School, Asheville, NC",
      isFeatured: true,
      bio: "Won his third and final national championship at UNC in 2017 — a redemption title after the heartbreaking buzzer-beater loss to Villanova in the 2016 championship game.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Head Coach Emeritus",
        currentEmployer: "University of North Carolina (Emeritus)",
        location: "Chapel Hill, NC",
        statusNote: "Roy Williams retired in April 2021 after 33 seasons as a head coach (15 at Kansas, 18 at UNC), compiling a career record of 903-264. He won three national championships at UNC (2005, 2009, 2017) and reached nine Final Fours. Inducted into the Naismith Basketball Hall of Fame in 2007.",
        sourceUrl: "https://en.wikipedia.org/wiki/Roy_Williams_(basketball_coach)",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2003-2021", statsNote: "903-264 career • 3x NCAA Champion • Hall of Fame" },
      seasonStats: [
        { level: "COACHING", teamName: "North Carolina Tar Heels", season: "2016-17", yearLabel: "2016-17", sortOrder: 215, wins: 33, losses: 7, tournamentResult: "NCAA National Champions" },
      ],
      careerEvents: [
        { year: 2016, title: "Lost NCAA Championship Game to Villanova at the buzzer", eventType: "MILESTONE" },
        { year: 2017, title: "Won third NCAA Championship at UNC — redemption", eventType: "CHAMPIONSHIP", month: 4, day: 3 },
        { year: 2021, title: "Retired from coaching with 903 career wins", eventType: "RETIREMENT" },
      ],
    },
  ],
};
