import type { TeamSeed } from "./types";

export const uncBasketball2024: TeamSeed = {
  slug: "unc-basketball-2024",
  name: "North Carolina Tar Heels",
  season: "2023-2024",
  sport: "Men's Basketball",
  school: "University of North Carolina",
  conference: "ACC",
  accomplishment: "2023-2024 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/153.png",
  mascotName: "Tar Heel",
  people: [
    {
      slug: "rj-davis",
      firstName: "RJ",
      lastName: "Davis",
      birthYear: 2001,
      hometown: "United States",
      highSchool: "United States",
      bio: "Senior guard and ACC POY candidate. One of UNC's all-time great scorers.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "United States",
        statusNote: "Named ACC POY. Selected in 2025 NBA Draft.",
        sourceUrl: "https://en.wikipedia.org/wiki/RJ_Davis",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 21, reboundsPerGame: 4, assistsPerGame: 3.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 21, reboundsPerGame: 4, assistsPerGame: 3.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "armando-bacot",
      firstName: "Armando",
      lastName: "Bacot",
      birthYear: 2000,
      hometown: "United States",
      highSchool: "United States",
      bio: "5th-year senior. UNC's all-time leading rebounder.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "Istanbul, Turkey",
        statusNote: "UNC career rebound record holder. Now with Fenerbahce.",
        sourceUrl: "https://en.wikipedia.org/wiki/Armando_Bacot",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Center", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 12.5, reboundsPerGame: 9, assistsPerGame: 1.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 12.5, reboundsPerGame: 9, assistsPerGame: 1.2 },
      ],
      careerEvents: [],
    },
    {
      slug: "harrison-ingram",
      firstName: "Harrison",
      lastName: "Ingram",
      birthYear: 2002,
      hometown: "United States",
      highSchool: "United States",
      bio: "Stanford transfer who provided veteran leadership.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "United States",
        statusNote: "Stanford transfer. Versatile forward who contributed to UNC.",
        sourceUrl: "https://en.wikipedia.org/wiki/Harrison_Ingram",
      },
      membership: { role: "PLAYER", jerseyNumber: 55, position: "Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 8.5, reboundsPerGame: 5.5, assistsPerGame: 2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 8.5, reboundsPerGame: 5.5, assistsPerGame: 2 },
      ],
      careerEvents: [],
    },
    {
      slug: "hubert-davis",
      firstName: "Hubert",
      lastName: "Davis",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Former UNC player and NBA veteran who succeeded Roy Williams. Led UNC to the 2022 title game in his first season.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Fired in March 2026 after blowing 19-pt lead to VCU.",
        sourceUrl: "https://en.wikipedia.org/wiki/Hubert_Davis",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2022-2026" },
      seasonStats: [
        { level: "COACHING", teamName: "North Carolina Tar Heels", season: "2023-2024", yearLabel: "2023-2024", sortOrder: 216 },
      ],
      careerEvents: [],
    },
  ],
};
