import type { TeamSeed } from "./types";

export const uncBasketball2015: TeamSeed = {
  slug: "unc-basketball-2015",
  name: "North Carolina Tar Heels",
  season: "2014-2015",
  sport: "Men's Basketball",
  school: "University of North Carolina",
  conference: "ACC",
  accomplishment: "2014-2015 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/153.png",
  mascotName: "Tar Heel",
  people: [
    {
      slug: "marcus-paige",
      firstName: "Marcus",
      lastName: "Paige",
      birthYear: 1993,
      hometown: "United States",
      highSchool: "United States",
      bio: "Junior captain and team leader.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Iowa",
        statusNote: "Famous for 2016 title game heroics. Played overseas briefly.",
        sourceUrl: "https://en.wikipedia.org/wiki/Marcus_Paige",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Point Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 14, reboundsPerGame: 2.5, assistsPerGame: 4 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 14, reboundsPerGame: 2.5, assistsPerGame: 4 },
      ],
      careerEvents: [],
    },
    {
      slug: "brice-johnson",
      firstName: "Brice",
      lastName: "Johnson",
      birthYear: 1994,
      hometown: "United States",
      highSchool: "United States",
      bio: "Junior forward emerging as UNC's best player.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "Overseas",
        statusNote: "ACC POY in 2016. #25 pick by Clippers.",
        sourceUrl: "https://en.wikipedia.org/wiki/Brice_Johnson",
      },
      membership: { role: "PLAYER", jerseyNumber: 11, position: "Power Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 12.8, reboundsPerGame: 7, assistsPerGame: 0.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 12.8, reboundsPerGame: 7, assistsPerGame: 0.8 },
      ],
      careerEvents: [],
    },
    {
      slug: "justin-jackson-unc",
      firstName: "Justin",
      lastName: "Jackson",
      birthYear: 1995,
      hometown: "United States",
      highSchool: "United States",
      bio: "Freshman wing. Future All-American and #15 pick.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "Ottawa, Canada",
        statusNote: "#15 pick in 2017. NBA champion with Bucks 2021. Now in Canada.",
        sourceUrl: "https://en.wikipedia.org/wiki/Justin_Jackson",
      },
      membership: { role: "PLAYER", jerseyNumber: 44, position: "Small Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 7.5, reboundsPerGame: 3, assistsPerGame: 1 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 7.5, reboundsPerGame: 3, assistsPerGame: 1 },
      ],
      careerEvents: [],
    },
    {
      slug: "roy-williams",
      firstName: "Roy",
      lastName: "Williams",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Hall of Fame coach with 903 career victories and 3 national championships (2005, 2009, 2017) at UNC.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Retired in April 2021. Head Coach Emeritus at UNC.",
        sourceUrl: "https://en.wikipedia.org/wiki/Roy_Williams",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2021" },
      seasonStats: [
        { level: "COACHING", teamName: "North Carolina Tar Heels", season: "2014-2015", yearLabel: "2014-2015", sortOrder: 207 },
      ],
      careerEvents: [],
    },
  ],
};
