import type { TeamSeed } from "./types";

export const uncBasketball2021: TeamSeed = {
  slug: "unc-basketball-2021",
  name: "North Carolina Tar Heels",
  season: "2020-2021",
  sport: "Men's Basketball",
  school: "University of North Carolina",
  conference: "ACC",
  accomplishment: "2020-2021 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/153.png",
  mascotName: "Tar Heel",
  people: [
    {
      slug: "armando-bacot",
      firstName: "Armando",
      lastName: "Bacot",
      birthYear: 2000,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore center becoming dominant force.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "Istanbul, Turkey",
        statusNote: "UNC's all-time leading rebounder. Now playing for Fenerbahce.",
        sourceUrl: "https://en.wikipedia.org/wiki/Armando_Bacot",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Center", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 12.3, reboundsPerGame: 7.8, assistsPerGame: 0.9 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 12.3, reboundsPerGame: 7.8, assistsPerGame: 0.9 },
      ],
      careerEvents: [],
    },
    {
      slug: "caleb-love",
      firstName: "Caleb",
      lastName: "Love",
      birthYear: 2001,
      hometown: "United States",
      highSchool: "United States",
      bio: "Freshman guard from St. Louis. Future 30-pt scorer vs Duke.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard (two-way)",
        location: "Portland, OR",
        statusNote: "Now with Portland Trail Blazers on two-way contract.",
        sourceUrl: "https://en.wikipedia.org/wiki/Caleb_Love",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 10.5, reboundsPerGame: 3, assistsPerGame: 2.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 10.5, reboundsPerGame: 3, assistsPerGame: 2.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "roy-williams",
      firstName: "Roy",
      lastName: "Williams",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Hall of Fame coach with 903 career victories and 3 national championships (2005, 2009, 2017) at UNC.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Retired in April 2021. Head Coach Emeritus at UNC.",
        sourceUrl: "https://en.wikipedia.org/wiki/Roy_Williams",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2021" },
      seasonStats: [
        { level: "COACHING", teamName: "North Carolina Tar Heels", season: "2020-2021", yearLabel: "2020-2021", sortOrder: 213 },
      ],
      careerEvents: [],
    },
  ],
};
