import type { TeamSeed } from "./types";

export const uncBasketball2009: TeamSeed = {
  slug: "unc-basketball-2009",
  name: "North Carolina Tar Heels",
  season: "2008-2009",
  sport: "Men's Basketball",
  school: "University of North Carolina",
  conference: "ACC",
  accomplishment: "NCAA National Champions (34-4)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/153.png",
  mascotName: "Tar Heel",
  people: [
    {
      slug: "tyler-hansbrough",
      firstName: "Tyler",
      lastName: "Hansbrough",
      birthYear: 1985,
      hometown: "Poplar Bluff, MO",
      highSchool: "Poplar Bluff High School, Poplar Bluff, MO",
      isFeatured: true,
      bio: "The most decorated player in UNC history, Hansbrough won the 2008 Naismith Award and remains UNC's all-time leading scorer. He led the Tar Heels to the 2009 national championship as a senior.",
      status: {
        occupationType: "BROADCASTER_ANALYST",
        currentTitle: "Color Analyst / Podcast Host",
        currentEmployer: "ACC Network / SleepHawk Worldwide",
        location: "Chapel Hill, NC",
        statusNote: "Selected #13 overall by the Indiana Pacers in 2009, Hansbrough played 7 NBA seasons with the Pacers, Raptors, and Hornets before retiring in 2016. He has since built a diverse post-playing career: he joined the ACC Network in 2021 as a color commentator, hosts the SleepHawk Worldwide podcast, and in September 2025 became a visiting professor at UNC's Hussman School of Journalism and Media, co-teaching MEJO 377: Sports Communication. He was inducted into the NC Sports Hall of Fame in 2026 as part of the inaugural class. He remains a fixture around the UNC program, frequently attending games and playing summer pickup at the Smith Center.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tyler_Hansbrough",
        linkedInUrl: "https://www.linkedin.com/in/tyler-hansbrough-199222396",
      },
      membership: { role: "PLAYER", jerseyNumber: 50, position: "Power Forward", yearsAtSchool: "2005-2009", statsNote: "2008 Naismith POY • UNC all-time leading scorer • NCAA Champion", gamesPlayed: 37, pointsPerGame: 20.7, reboundsPerGame: 8.1, assistsPerGame: 1.0 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2008-09", yearLabel: "Senior", sortOrder: 204, gamesPlayed: 37, minutesPerGame: 30.1, pointsPerGame: 20.7, reboundsPerGame: 8.1, assistsPerGame: 1.0, fieldGoalPct: 0.529, freeThrowPct: 0.809 },
        { level: "PROFESSIONAL", teamName: "Indiana Pacers", season: "2009-10", yearLabel: "2009-10 (Rookie)", sortOrder: 301, gamesPlayed: 29, pointsPerGame: 8.5, reboundsPerGame: 3.8 },
      ],
      careerEvents: [
        { year: 2008, title: "Won Naismith Player of the Year", eventType: "AWARD", month: 4, day: 6 },
        { year: 2009, title: "Won NCAA National Championship with UNC", eventType: "CHAMPIONSHIP", month: 4, day: 6 },
        { year: 2009, title: "Selected #13 overall by the Indiana Pacers", eventType: "DRAFT", month: 6, day: 25 },
        { year: 2016, title: "Retired from professional basketball", eventType: "RETIREMENT" },
        { year: 2026, title: "Inducted into NC Sports Hall of Fame", eventType: "AWARD" },
      ],
    },
    {
      slug: "ty-lawson",
      firstName: "Ty",
      lastName: "Lawson",
      birthYear: 1987,
      hometown: "Clinton, MD",
      highSchool: "Oak Hill Academy, Mouth of Wilson, VA",
      isFeatured: true,
      bio: "The lightning-fast point guard who was the engine of the 2009 championship team. Named ACC Player of the Year and the NCAA Tournament's Most Outstanding Player.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Professional Basketball Player",
        location: "Maryland",
        statusNote: "Selected #18 overall by the Denver Nuggets in 2009, Lawson became a starting NBA point guard averaging 14.2 PPG in his best season (2013-14). After 7 NBA seasons with Denver, Houston, Sacramento, and Indiana, he played internationally in China, Greece, and Venezuela. As of 2024, he was competing in The Basketball Tournament with LA Ignite.",
        sourceUrl: "https://en.wikipedia.org/wiki/Ty_Lawson",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Point Guard", yearsAtSchool: "2006-2009", statsNote: "2009 ACC POY • NCAA Tournament MOP • NCAA Champion", gamesPlayed: 38, pointsPerGame: 16.6, reboundsPerGame: 2.9, assistsPerGame: 6.6 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2008-09", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 38, minutesPerGame: 31.3, pointsPerGame: 16.6, reboundsPerGame: 2.9, assistsPerGame: 6.6, stealsPerGame: 1.8, fieldGoalPct: 0.476, threePointPct: 0.472 },
        { level: "PROFESSIONAL", teamName: "Denver Nuggets", season: "2009-10", yearLabel: "2009-10 (Rookie)", sortOrder: 301, gamesPlayed: 73, pointsPerGame: 6.6, assistsPerGame: 2.4 },
        { level: "PROFESSIONAL", teamName: "Denver Nuggets", season: "2013-14", yearLabel: "2013-14", sortOrder: 305, gamesPlayed: 62, pointsPerGame: 14.2, assistsPerGame: 8.8 },
      ],
      careerEvents: [
        { year: 2009, title: "Won NCAA National Championship with UNC", eventType: "CHAMPIONSHIP", month: 4, day: 6 },
        { year: 2009, title: "Named NCAA Tournament Most Outstanding Player", eventType: "AWARD" },
        { year: 2009, title: "Selected #18 overall by the Denver Nuggets", eventType: "DRAFT", month: 6, day: 25 },
      ],
    },
    {
      slug: "danny-green",
      firstName: "Danny",
      lastName: "Green",
      birthYear: 1987,
      hometown: "North Babylon, NY",
      highSchool: "St. Mary's High School, Manhasset, NY",
      isFeatured: true,
      bio: "Undrafted out of UNC, Green became one of the greatest success stories in college basketball history — winning 3 NBA championships with 3 different teams (Spurs 2014, Raptors 2019, Lakers 2020).",
      status: {
        occupationType: "BROADCASTER_ANALYST",
        currentTitle: "NBA Analyst / Podcast Host / Venture Fund Manager",
        currentEmployer: "ESPN / Spectrum SportsNet",
        location: "Los Angeles, CA",
        statusNote: "Retired from the NBA in October 2024 after 15 seasons. He is one of only four players in history to win NBA championships with three different teams. Since retiring, Green works as a color analyst for ESPN and Spectrum SportsNet, hosts two podcasts ('Inside the Green Room' and 'No Fouls Given' with Paul Pierce), and runs the GreenLight venture fund dedicated to empowering innovative entrepreneurs. He also leads the Between the Lines mentorship program.",
        sourceUrl: "https://en.wikipedia.org/wiki/Danny_Green_(basketball)",
        linkedInUrl: "https://www.linkedin.com/in/dannygreenjr/",
      },
      membership: { role: "PLAYER", jerseyNumber: 14, position: "Shooting Guard", yearsAtSchool: "2005-2009", statsNote: "3x NBA Champion • Senior captain • NCAA Champion", gamesPlayed: 37, pointsPerGame: 9.7, reboundsPerGame: 4.5, assistsPerGame: 2.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2008-09", yearLabel: "Senior", sortOrder: 204, gamesPlayed: 37, minutesPerGame: 26.8, pointsPerGame: 9.7, reboundsPerGame: 4.5, assistsPerGame: 2.5, fieldGoalPct: 0.455, threePointPct: 0.385 },
        { level: "PROFESSIONAL", teamName: "San Antonio Spurs", season: "2013-14", yearLabel: "2013-14 (Champion)", sortOrder: 305, gamesPlayed: 68, pointsPerGame: 9.1, threePointPct: 0.418 },
        { level: "PROFESSIONAL", teamName: "Toronto Raptors", season: "2018-19", yearLabel: "2018-19 (Champion)", sortOrder: 310, gamesPlayed: 80, pointsPerGame: 10.3, threePointPct: 0.455 },
        { level: "PROFESSIONAL", teamName: "Los Angeles Lakers", season: "2019-20", yearLabel: "2019-20 (Champion)", sortOrder: 311, gamesPlayed: 68, pointsPerGame: 8.0, threePointPct: 0.367 },
      ],
      careerEvents: [
        { year: 2009, title: "Won NCAA National Championship with UNC", eventType: "CHAMPIONSHIP", month: 4, day: 6 },
        { year: 2009, title: "Went undrafted in the 2009 NBA Draft", eventType: "DRAFT", month: 6, day: 25 },
        { year: 2014, title: "Won NBA Championship with the San Antonio Spurs", eventType: "CHAMPIONSHIP", month: 6, day: 15 },
        { year: 2019, title: "Won NBA Championship with the Toronto Raptors", eventType: "CHAMPIONSHIP", month: 6, day: 13 },
        { year: 2020, title: "Won NBA Championship with the Los Angeles Lakers", eventType: "CHAMPIONSHIP", month: 10, day: 11 },
        { year: 2024, title: "Retired from the NBA after 15 seasons", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "wayne-ellington",
      firstName: "Wayne",
      lastName: "Ellington",
      birthYear: 1987,
      hometown: "Wynnewood, PA",
      highSchool: "The Episcopal Academy, Newtown Square, PA",
      bio: "A sharpshooter who came alive in the NCAA Tournament, scoring 19 points in the championship game against Michigan State. Selected #28 overall and went on to a 14-year NBA career.",
      status: {
        occupationType: "COACH",
        currentTitle: "Player Development Coach",
        currentEmployer: "Miami Heat",
        location: "Miami, FL",
        statusNote: "Ellington retired from the NBA in 2023 after 14 seasons with 8 teams, most notably the Miami Heat where he spent three seasons under Erik Spoelstra. He joined the Heat coaching staff as a Player Development Coach in September 2023, working directly with young players on their shooting and perimeter skills.",
        sourceUrl: "https://en.wikipedia.org/wiki/Wayne_Ellington",
      },
      membership: { role: "PLAYER", jerseyNumber: 22, position: "Shooting Guard", yearsAtSchool: "2006-2009", statsNote: "19 pts in title game • #28 pick • NCAA Champion", gamesPlayed: 38, pointsPerGame: 15.8, reboundsPerGame: 4.5, assistsPerGame: 1.6 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2008-09", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 38, minutesPerGame: 31.4, pointsPerGame: 15.8, reboundsPerGame: 4.5, assistsPerGame: 1.6, fieldGoalPct: 0.458, threePointPct: 0.405 },
        { level: "PROFESSIONAL", teamName: "Minnesota Timberwolves", season: "2009-10", yearLabel: "2009-10 (Rookie)", sortOrder: 301, gamesPlayed: 62, pointsPerGame: 6.0 },
      ],
      careerEvents: [
        { year: 2009, title: "Won NCAA National Championship with UNC", eventType: "CHAMPIONSHIP", month: 4, day: 6 },
        { year: 2009, title: "Selected #28 overall by Minnesota Timberwolves", eventType: "DRAFT", month: 6, day: 25 },
        { year: 2023, title: "Joined Miami Heat as Player Development Coach", eventType: "CAREER_CHANGE" },
      ],
    },
    {
      slug: "ed-davis",
      firstName: "Ed",
      lastName: "Davis",
      birthYear: 1989,
      hometown: "Richmond, VA",
      highSchool: "Benedictine High School, Richmond, VA",
      bio: "A dominant freshman forward who contributed 6.7 PPG and 6.4 RPG to the championship run. Returned for his sophomore year before being selected #13 overall in 2010.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Power Forward / Center",
        currentEmployer: "Cleveland Cavaliers",
        league: "NBA",
        location: "Cleveland, OH",
        statusNote: "Selected #13 overall by the Toronto Raptors in 2010, Davis has had one of the longest NBA careers of any UNC player. He has played for the Raptors, Grizzlies, Lakers, Trail Blazers, Nets, Jazz, Timberwolves, Cavaliers, and Knicks over 13+ seasons, valued as an elite rebounder and energy big off the bench.",
        sourceUrl: "https://en.wikipedia.org/wiki/Ed_Davis_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 32, position: "Power Forward", yearsAtSchool: "2008-2010", statsNote: "Freshman contributor • Future #13 pick", gamesPlayed: 37, pointsPerGame: 6.7, reboundsPerGame: 6.4, assistsPerGame: 0.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2008-09", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 37, minutesPerGame: 19.2, pointsPerGame: 6.7, reboundsPerGame: 6.4, fieldGoalPct: 0.574 },
      ],
      careerEvents: [
        { year: 2009, title: "Won NCAA National Championship with UNC", eventType: "CHAMPIONSHIP", month: 4, day: 6 },
        { year: 2010, title: "Selected #13 overall by the Toronto Raptors", eventType: "DRAFT", month: 6, day: 24 },
      ],
    },
    {
      slug: "tyler-zeller",
      firstName: "Tyler",
      lastName: "Zeller",
      birthYear: 1990,
      hometown: "Washington, IN",
      highSchool: "Washington High School, Washington, IN",
      bio: "A 7-foot freshman center who provided depth in the frontcourt during the championship run. Stayed four years at UNC and was selected #17 overall in 2012.",
      status: {
        occupationType: "BROADCASTER_ANALYST",
        currentTitle: "Color Analyst / Assistant HS Basketball Coach",
        currentEmployer: "Tar Heel Sports Network / Northwood High School",
        location: "Pittsboro, NC",
        statusNote: "Selected #17 overall by the Dallas Mavericks in 2012, Zeller played 6 NBA seasons with the Cavs, Celtics, Nets, Bucks, and Hawks. After retiring, he moved to Pittsboro, NC and became an assistant coach at Northwood High School. In 2024 he joined the Tar Heel Sports Network as a color analyst for UNC basketball broadcasts.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tyler_Zeller",
      },
      membership: { role: "PLAYER", jerseyNumber: 44, position: "Center", yearsAtSchool: "2008-2012", statsNote: "Freshman reserve • Future #17 pick", gamesPlayed: 30, pointsPerGame: 3.6, reboundsPerGame: 2.3 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2008-09", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 30, minutesPerGame: 9.3, pointsPerGame: 3.6, reboundsPerGame: 2.3, fieldGoalPct: 0.567 },
      ],
      careerEvents: [
        { year: 2009, title: "Won NCAA National Championship with UNC", eventType: "CHAMPIONSHIP", month: 4, day: 6 },
        { year: 2012, title: "Selected #17 overall by the Dallas Mavericks", eventType: "DRAFT" },
      ],
    },
    {
      slug: "deon-thompson",
      firstName: "Deon",
      lastName: "Thompson",
      birthYear: 1988,
      hometown: "Torrance, CA",
      highSchool: "Narbonne High School, Harbor City, CA",
      bio: "A versatile junior forward who played in a then-record 152 career games at UNC. Went undrafted but carved out a 16-year professional career across Europe, Asia, and Africa.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player / MBA Candidate",
        currentEmployer: "Kesatria Bengawan Solo (Indonesia) / UNC Kenan-Flagler Business School",
        location: "Chapel Hill, NC",
        statusNote: "Thompson has played professionally for 16 years across Germany, Lithuania, Serbia, Israel, Greece, Indonesia, and more — winning championships in four countries. He currently plays for Kesatria Bengawan Solo in Indonesia while simultaneously pursuing his MBA at UNC Kenan-Flagler Business School. He also represents the Ivory Coast national team internationally.",
        sourceUrl: "https://en.wikipedia.org/wiki/Deon_Thompson",
        linkedInUrl: "https://www.linkedin.com/in/deon-thompson-b13901b8/",
      },
      membership: { role: "PLAYER", jerseyNumber: 21, position: "Forward", yearsAtSchool: "2006-2010", statsNote: "152 career games (then-record) • NCAA Champion", gamesPlayed: 38, pointsPerGame: 8.7, reboundsPerGame: 5.3, assistsPerGame: 0.9 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2008-09", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 38, minutesPerGame: 20.1, pointsPerGame: 8.7, reboundsPerGame: 5.3, fieldGoalPct: 0.531 },
      ],
      careerEvents: [
        { year: 2009, title: "Won NCAA National Championship with UNC", eventType: "CHAMPIONSHIP", month: 4, day: 6 },
        { year: 2010, title: "Began professional career overseas in Germany", eventType: "SIGNING" },
      ],
    },
    {
      slug: "marcus-ginyard",
      firstName: "Marcus",
      lastName: "Ginyard",
      birthYear: 1986,
      hometown: "Alexandria, VA",
      highSchool: "South Lakes High School, Reston, VA",
      bio: "A senior captain and defensive stopper who missed the 2008 season with a foot injury but returned to lead UNC's defense during the championship run. Now a UNC administrator.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Director of Special Projects",
        currentEmployer: "University of North Carolina",
        location: "Chapel Hill, NC",
        statusNote: "After an 11-year professional career playing in 8 countries across Europe, Ginyard returned to UNC where he was named Director of Special Projects in October 2025. He supports the Secretary of the University in work with the Board of Trustees and leads community engagement initiatives. He also serves as a broadcaster for the ACC Network and sits on the boards of Carolina Alumni and Make-A-Wish Eastern NC.",
        sourceUrl: "https://goheels.com/news/2025/10/14/mens-basketball-marcus-ginyard-named-director-of-special-projects-at-unc",
        linkedInUrl: "https://www.linkedin.com/in/marcus-ginyard/",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Guard / Forward", yearsAtSchool: "2005-2009", statsNote: "Senior captain • Defensive leader • NCAA Champion", gamesPlayed: 36, pointsPerGame: 5.1, reboundsPerGame: 3.2, assistsPerGame: 1.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2008-09", yearLabel: "Senior", sortOrder: 204, gamesPlayed: 36, minutesPerGame: 22.0, pointsPerGame: 5.1, reboundsPerGame: 3.2, assistsPerGame: 1.8, stealsPerGame: 1.1 },
      ],
      careerEvents: [
        { year: 2009, title: "Won NCAA National Championship with UNC", eventType: "CHAMPIONSHIP", month: 4, day: 6 },
        { year: 2025, title: "Named Director of Special Projects at UNC", eventType: "CAREER_CHANGE" },
      ],
    },
    {
      slug: "bobby-frasor",
      firstName: "Bobby",
      lastName: "Frasor",
      birthYear: 1987,
      hometown: "Blue Island, IL",
      highSchool: "Brother Rice High School, Chicago, IL",
      bio: "The steady senior point guard who served as a floor general alongside Ty Lawson. After a coaching stint at his alma mater Brother Rice, he transitioned into insurance.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Associate Broker",
        currentEmployer: "RT Specialty",
        location: "Chicago, IL",
        statusNote: "After graduating from UNC, Frasor worked as an assistant video coordinator on Roy Williams' staff before coaching at Brother Rice High School in Chicago for 7 years, compiling a 143-56 record with two regional titles. He stepped down in 2022 and transitioned into insurance, joining RT Specialty as an Associate Broker specializing in specialty insurance products.",
        sourceUrl: "https://en.wikipedia.org/wiki/Bobby_Frasor",
        linkedInUrl: "https://www.linkedin.com/in/bobby-frasor-2959a464/",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Point Guard", yearsAtSchool: "2005-2009", statsNote: "Senior floor general • NCAA Champion", gamesPlayed: 35, pointsPerGame: 3.1, reboundsPerGame: 1.5, assistsPerGame: 2.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2008-09", yearLabel: "Senior", sortOrder: 204, gamesPlayed: 35, minutesPerGame: 16.2, pointsPerGame: 3.1, reboundsPerGame: 1.5, assistsPerGame: 2.8 },
      ],
      careerEvents: [
        { year: 2009, title: "Won NCAA National Championship with UNC", eventType: "CHAMPIONSHIP", month: 4, day: 6 },
        { year: 2015, title: "Became head basketball coach at Brother Rice High School", eventType: "CAREER_CHANGE" },
        { year: 2022, title: "Stepped down from coaching, joined RT Specialty", eventType: "CAREER_CHANGE" },
      ],
    },
    {
      slug: "larry-drew-ii",
      firstName: "Larry",
      lastName: "Drew II",
      birthYear: 1990,
      hometown: "Encino, CA",
      highSchool: "Woodland Hills Taft High School, Woodland Hills, CA",
      bio: "A freshman point guard who won a championship in his first college season. Later transferred to UCLA where he broke the school's single-season assist record and earned All-Pac-12 honors.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Professional Basketball Player",
        location: "California",
        statusNote: "After transferring to UCLA and breaking their single-season assist record, Drew played professionally in the NBA (76ers, Pelicans on 10-day contracts), G League, and Lithuania. He won a gold medal with the US national team at the 2017 FIBA AmeriCup. Son of former NBA player and coach Larry Drew.",
        sourceUrl: "https://en.wikipedia.org/wiki/Larry_Drew_II",
      },
      membership: { role: "PLAYER", jerseyNumber: 11, position: "Point Guard", yearsAtSchool: "2008-2011", statsNote: "Freshman reserve PG • NCAA Champion", gamesPlayed: 32, pointsPerGame: 1.6, reboundsPerGame: 0.6, assistsPerGame: 1.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2008-09", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 32, minutesPerGame: 7.8, pointsPerGame: 1.6, assistsPerGame: 1.2 },
      ],
      careerEvents: [
        { year: 2009, title: "Won NCAA National Championship with UNC", eventType: "CHAMPIONSHIP", month: 4, day: 6 },
        { year: 2011, title: "Transferred to UCLA", eventType: "SIGNING" },
        { year: 2017, title: "Won gold with USA at FIBA AmeriCup", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "will-graves-unc",
      firstName: "Will",
      lastName: "Graves",
      birthYear: 1988,
      hometown: "Cherryville, NC",
      highSchool: "Burns High School, Lawndale, NC",
      bio: "A sophomore forward who provided frontcourt depth on the championship team. A physical, undersized big man who contributed energy and rebounding in limited minutes.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "North Carolina",
        statusNote: "After UNC, Graves played professional basketball overseas briefly before returning to North Carolina. He has remained connected to the UNC basketball community.",
        sourceUrl: "https://goheels.com/sports/mens-basketball/roster/will-graves/",
      },
      membership: { role: "PLAYER", jerseyNumber: 24, position: "Forward", yearsAtSchool: "2007-2010", statsNote: "Sophomore reserve forward", gamesPlayed: 25, pointsPerGame: 1.3, reboundsPerGame: 1.1 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2008-09", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 25, pointsPerGame: 1.3, reboundsPerGame: 1.1 },
      ],
      careerEvents: [
        { year: 2009, title: "Won NCAA National Championship with UNC", eventType: "CHAMPIONSHIP", month: 4, day: 6 },
      ],
    },
    {
      slug: "mike-copeland-unc",
      firstName: "Mike",
      lastName: "Copeland",
      birthYear: 1987,
      hometown: "Raleigh, NC",
      highSchool: "Athens Drive High School, Raleigh, NC",
      bio: "A junior forward from Raleigh who provided depth in the frontcourt during the 2009 championship season.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Raleigh, NC",
        statusNote: "After graduating from UNC, Copeland returned to the Raleigh area. Limited publicly available information about his specific post-UNC career path.",
        sourceUrl: "https://goheels.com/sports/mens-basketball/roster/",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Forward", yearsAtSchool: "2006-2009", statsNote: "Junior reserve", gamesPlayed: 18, pointsPerGame: 0.4, reboundsPerGame: 0.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2008-09", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 18, pointsPerGame: 0.4 },
      ],
      careerEvents: [
        { year: 2009, title: "Won NCAA National Championship with UNC", eventType: "CHAMPIONSHIP", month: 4, day: 6 },
      ],
    },
    {
      slug: "roy-williams",
      firstName: "Roy",
      lastName: "Williams",
      birthYear: 1950,
      hometown: "Spruce Pine, NC",
      highSchool: "T.C. Roberson High School, Asheville, NC",
      isFeatured: true,
      bio: "Hall of Fame head coach who led UNC to three national championships (2005, 2009, 2017). The 2009 title was his second, cementing his place among the greatest coaches in college basketball history.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Head Coach Emeritus",
        currentEmployer: "University of North Carolina (Emeritus)",
        location: "Chapel Hill, NC",
        statusNote: "Roy Williams retired in April 2021 after 33 seasons as a head coach (15 at Kansas, 18 at UNC), compiling a career record of 903-264 (.774). He won three national championships at UNC (2005, 2009, 2017) and reached nine Final Fours. He was inducted into the Naismith Memorial Basketball Hall of Fame in 2007. He was succeeded by his former assistant and UNC alum Hubert Davis.",
        sourceUrl: "https://en.wikipedia.org/wiki/Roy_Williams_(basketball_coach)",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2003-2021", statsNote: "903-264 career • 3x NCAA Champion • Hall of Fame" },
      seasonStats: [
        { level: "COACHING", teamName: "North Carolina Tar Heels", season: "2008-09", yearLabel: "2008-09", sortOrder: 207, wins: 34, losses: 4, tournamentResult: "NCAA National Champions" },
      ],
      careerEvents: [
        { year: 2005, title: "Won first NCAA Championship at UNC", eventType: "CHAMPIONSHIP" },
        { year: 2007, title: "Inducted into Naismith Basketball Hall of Fame", eventType: "AWARD" },
        { year: 2009, title: "Won second NCAA Championship at UNC", eventType: "CHAMPIONSHIP", month: 4, day: 6 },
        { year: 2017, title: "Won third NCAA Championship at UNC", eventType: "CHAMPIONSHIP" },
        { year: 2021, title: "Retired from coaching with 903 career wins", eventType: "RETIREMENT" },
      ],
    },
  ],
};
