import type { TeamSeed } from "./types";

export const uncBasketball2020: TeamSeed = {
  slug: "unc-basketball-2020",
  name: "North Carolina Tar Heels",
  season: "2019-2020",
  sport: "Men's Basketball",
  school: "University of North Carolina",
  conference: "ACC",
  accomplishment: "2019-2020 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/153.png",
  mascotName: "Tar Heel",
  people: [
    {
      slug: "cole-anthony",
      firstName: "Cole",
      lastName: "Anthony",
      birthYear: 2000,
      hometown: "United States",
      highSchool: "United States",
      bio: "Freshman star and son of NBA player Greg Anthony. #15 pick.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        location: "Orlando, FL",
        statusNote: "Selected #15 by Orlando Magic. Starting NBA guard.",
        sourceUrl: "https://en.wikipedia.org/wiki/Cole_Anthony",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Point Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 18.5, reboundsPerGame: 5.7, assistsPerGame: 4 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 18.5, reboundsPerGame: 5.7, assistsPerGame: 4 },
      ],
      careerEvents: [],
    },
    {
      slug: "armando-bacot",
      firstName: "Armando",
      lastName: "Bacot",
      birthYear: 2000,
      hometown: "United States",
      highSchool: "United States",
      bio: "Freshman center from Richmond. Future UNC all-time rebounder.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "Istanbul, Turkey",
        statusNote: "Now with Fenerbahce (EuroLeague). NCAA record 31 double-doubles in 2022.",
        sourceUrl: "https://en.wikipedia.org/wiki/Armando_Bacot",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Center", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 9.6, reboundsPerGame: 8.2, assistsPerGame: 0.7 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 9.6, reboundsPerGame: 8.2, assistsPerGame: 0.7 },
      ],
      careerEvents: [],
    },
    {
      slug: "roy-williams",
      firstName: "Roy",
      lastName: "Williams",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Hall of Fame coach with 903 career victories and 3 national championships (2005, 2009, 2017) at UNC.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Retired in April 2021. Head Coach Emeritus at UNC.",
        sourceUrl: "https://en.wikipedia.org/wiki/Roy_Williams",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2021" },
      seasonStats: [
        { level: "COACHING", teamName: "North Carolina Tar Heels", season: "2019-2020", yearLabel: "2019-2020", sortOrder: 212 },
      ],
      careerEvents: [],
    },
  ],
};
