import type { TeamSeed } from "./types";

export const uncBasketball2013: TeamSeed = {
  slug: "unc-basketball-2013",
  name: "North Carolina Tar Heels",
  season: "2012-2013",
  sport: "Men's Basketball",
  school: "University of North Carolina",
  conference: "ACC",
  accomplishment: "2012-2013 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/153.png",
  mascotName: "Tar Heel",
  people: [
    {
      slug: "marcus-paige",
      firstName: "Marcus",
      lastName: "Paige",
      birthYear: 1993,
      hometown: "United States",
      highSchool: "United States",
      bio: "Freshman guard from Iowa who became UNC's leader for 4 years.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Iowa",
        statusNote: "Famous for tying the 2016 title game with a double-clutch 3. Played overseas briefly.",
        sourceUrl: "https://en.wikipedia.org/wiki/Marcus_Paige",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Point Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 7.5, reboundsPerGame: 2, assistsPerGame: 3 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 7.5, reboundsPerGame: 2, assistsPerGame: 3 },
      ],
      careerEvents: [],
    },
    {
      slug: "james-michael-mcadoo",
      firstName: "James Michael",
      lastName: "McAdoo",
      birthYear: 1993,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore forward. #5 recruit who won 2 NBA titles with Warriors.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NBA Player",
        location: "Virginia",
        statusNote: "Won 2015 and 2017 NBA Championships with Golden State Warriors.",
        sourceUrl: "https://en.wikipedia.org/wiki/James Michael_McAdoo",
      },
      membership: { role: "PLAYER", jerseyNumber: 43, position: "Power Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 14.4, reboundsPerGame: 6.8, assistsPerGame: 0.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 14.4, reboundsPerGame: 6.8, assistsPerGame: 0.8 },
      ],
      careerEvents: [],
    },
    {
      slug: "pj-hairston",
      firstName: "P.J.",
      lastName: "Hairston",
      birthYear: 1992,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore sharpshooter from Greensboro. Later #26 pick.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "North Carolina",
        statusNote: "Dismissed from UNC. Drafted #26 by Heat. Career cut short.",
        sourceUrl: "https://en.wikipedia.org/wiki/P.J._Hairston",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 14.6, reboundsPerGame: 3, assistsPerGame: 1 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 14.6, reboundsPerGame: 3, assistsPerGame: 1 },
      ],
      careerEvents: [],
    },
    {
      slug: "reggie-bullock",
      firstName: "Reggie",
      lastName: "Bullock",
      birthYear: 1991,
      hometown: "United States",
      highSchool: "United States",
      bio: "Junior wing from Kinston. #25 pick. 12-year NBA career.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        location: "Houston, TX",
        statusNote: "12+ NBA seasons. 2x NBA 3-Point Contest participant. LGBTQ+ ally.",
        sourceUrl: "https://en.wikipedia.org/wiki/Reggie_Bullock",
      },
      membership: { role: "PLAYER", jerseyNumber: 35, position: "Small Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 13.5, reboundsPerGame: 5.2, assistsPerGame: 1.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 13.5, reboundsPerGame: 5.2, assistsPerGame: 1.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "roy-williams",
      firstName: "Roy",
      lastName: "Williams",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Hall of Fame coach with 903 career victories and 3 national championships (2005, 2009, 2017) at UNC.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Retired in April 2021. Head Coach Emeritus at UNC.",
        sourceUrl: "https://en.wikipedia.org/wiki/Roy_Williams",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2021" },
      seasonStats: [
        { level: "COACHING", teamName: "North Carolina Tar Heels", season: "2012-2013", yearLabel: "2012-2013", sortOrder: 205 },
      ],
      careerEvents: [],
    },
  ],
};
