import type { TeamSeed } from "./types";

export const uncBasketball2012: TeamSeed = {
  slug: "unc-basketball-2012",
  name: "North Carolina Tar Heels",
  season: "2011-2012",
  sport: "Men's Basketball",
  school: "University of North Carolina",
  conference: "ACC",
  accomplishment: "Elite Eight (32-6)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/153.png",
  mascotName: "Tar Heel",
  people: [
    {
      slug: "harrison-barnes",
      firstName: "Harrison",
      lastName: "Barnes",
      birthYear: 1992,
      hometown: "Ames, IA",
      highSchool: "Ames High School, Ames, IA",
      isFeatured: true,
      bio: "The consensus All-American sophomore and #7 overall pick who was UNC's best player. Won an NBA championship with the Warriors in 2015 and has had a 13+ year NBA career worth over $200M in contracts.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "San Antonio Spurs",
        league: "NBA",
        location: "San Antonio, TX",
        statusNote: "Selected #7 overall by the Golden State Warriors in 2012, Barnes won the 2015 NBA Championship and has played for the Warriors, Mavericks, Kings, and Spurs over a 13+ year career. He has earned over $200 million in career contracts and is known as one of the most durable and professional players in the NBA. He was traded to the Spurs in 2023 and continues to be a reliable veteran wing.",
        sourceUrl: "https://en.wikipedia.org/wiki/Harrison_Barnes",
      },
      membership: { role: "PLAYER", jerseyNumber: 40, position: "Small Forward", yearsAtSchool: "2010-2012", statsNote: "All-American • #7 pick • 2015 NBA Champion • Elite Eight", gamesPlayed: 38, pointsPerGame: 17.1, reboundsPerGame: 5.2, assistsPerGame: 1.1 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2011-12", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 38, minutesPerGame: 30.5, pointsPerGame: 17.1, reboundsPerGame: 5.2, fieldGoalPct: 0.443, threePointPct: 0.358 },
        { level: "PROFESSIONAL", teamName: "Golden State Warriors", season: "2014-15", yearLabel: "2014-15 (Champion)", sortOrder: 303, gamesPlayed: 82, pointsPerGame: 10.1, reboundsPerGame: 5.5 },
      ],
      careerEvents: [
        { year: 2012, title: "Selected #7 overall by the Golden State Warriors", eventType: "DRAFT", month: 6, day: 28 },
        { year: 2015, title: "Won NBA Championship with the Golden State Warriors", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "kendall-marshall",
      firstName: "Kendall",
      lastName: "Marshall",
      birthYear: 1991,
      hometown: "Dumfries, VA",
      highSchool: "Bishop O'Connell High School, Arlington, VA",
      isFeatured: true,
      bio: "The sophomore point guard who led the nation in assists and was the most creative passer in college basketball. His court vision and ability to run the break were unmatched, earning him the Bob Cousy Award as the nation's best point guard.",
      status: {
        occupationType: "BROADCASTER_ANALYST",
        currentTitle: "Basketball Analyst / Entrepreneur",
        location: "Virginia",
        statusNote: "Selected #13 overall by the Phoenix Suns in 2012, Marshall's NBA career was cut short by injuries — he played just 79 games across 3 seasons with the Suns, Lakers, Bucks, and 76ers. After retiring from playing, he transitioned into media and entrepreneurship. He won the 2012 Bob Cousy Award as the nation's best point guard after leading the country in assists (9.8 APG).",
        sourceUrl: "https://en.wikipedia.org/wiki/Kendall_Marshall",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Point Guard", yearsAtSchool: "2010-2012", statsNote: "Bob Cousy Award • Led nation in assists • #13 pick • Elite Eight", gamesPlayed: 37, pointsPerGame: 8.1, reboundsPerGame: 1.9, assistsPerGame: 9.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2011-12", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 37, minutesPerGame: 32.5, pointsPerGame: 8.1, reboundsPerGame: 1.9, assistsPerGame: 9.8, fieldGoalPct: 0.437, threePointPct: 0.389 },
      ],
      careerEvents: [
        { year: 2012, title: "Won Bob Cousy Award as nation's best point guard", eventType: "AWARD" },
        { year: 2012, title: "Selected #13 overall by the Phoenix Suns", eventType: "DRAFT", month: 6, day: 28 },
      ],
    },
    {
      slug: "john-henson",
      firstName: "John",
      lastName: "Henson",
      birthYear: 1990,
      hometown: "Tampa, FL",
      highSchool: "Sickles High School, Tampa, FL",
      isFeatured: true,
      bio: "The junior center whose shot-blocking dominance made him one of the most impactful defenders in ACC history. His length and timing at the rim anchored UNC's defense during the Elite Eight run.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NBA Player",
        location: "Florida",
        statusNote: "Selected #14 overall by the Milwaukee Bucks in 2012, Henson played 8 NBA seasons with the Bucks, Cavaliers, and Pistons. Known primarily for his shot-blocking (he was one of the ACC's all-time leaders in blocks at UNC), his NBA career was affected by injuries in his later years. He retired around 2021 and has returned to the Tampa area.",
        sourceUrl: "https://en.wikipedia.org/wiki/John_Henson_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 31, position: "Center / Power Forward", yearsAtSchool: "2009-2012", statsNote: "#14 pick • ACC blocks leader • Shot-blocking anchor • Elite Eight", gamesPlayed: 38, pointsPerGame: 13.7, reboundsPerGame: 9.9, assistsPerGame: 1.4 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2011-12", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 38, minutesPerGame: 30.0, pointsPerGame: 13.7, reboundsPerGame: 9.9, blocksPerGame: 2.9, fieldGoalPct: 0.560 },
      ],
      careerEvents: [
        { year: 2012, title: "Selected #14 overall by the Milwaukee Bucks", eventType: "DRAFT", month: 6, day: 28 },
      ],
    },
    {
      slug: "tyler-zeller",
      firstName: "Tyler",
      lastName: "Zeller",
      birthYear: 1990,
      hometown: "Washington, IN",
      highSchool: "Washington High School, Washington, IN",
      bio: "The senior center who won ACC Player of the Year in his final season and was the heart of UNC's frontcourt. His post scoring and rebounding alongside Henson gave UNC one of the most dominant frontlines in the country.",
      status: {
        occupationType: "BROADCASTER_ANALYST",
        currentTitle: "Color Analyst / Assistant HS Basketball Coach",
        currentEmployer: "Tar Heel Sports Network / Northwood High School",
        location: "Pittsboro, NC",
        statusNote: "Selected #17 overall by the Dallas Mavericks in 2012, Zeller played 6 NBA seasons. After retiring, he became an assistant coach at Northwood High School and joined the Tar Heel Sports Network as a color analyst for UNC basketball broadcasts in 2024.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tyler_Zeller",
      },
      membership: { role: "PLAYER", jerseyNumber: 44, position: "Center", yearsAtSchool: "2008-2012", statsNote: "ACC Player of the Year • Senior captain • #17 pick • Elite Eight", gamesPlayed: 38, pointsPerGame: 16.3, reboundsPerGame: 9.6 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2011-12", yearLabel: "Senior", sortOrder: 204, gamesPlayed: 38, minutesPerGame: 31.0, pointsPerGame: 16.3, reboundsPerGame: 9.6, fieldGoalPct: 0.553 },
      ],
      careerEvents: [
        { year: 2012, title: "Won ACC Player of the Year", eventType: "AWARD" },
        { year: 2012, title: "Selected #17 overall by the Dallas Mavericks", eventType: "DRAFT", month: 6, day: 28 },
      ],
    },
    {
      slug: "reggie-bullock",
      firstName: "Reggie",
      lastName: "Bullock",
      birthYear: 1991,
      hometown: "Kinston, NC",
      highSchool: "Kinston High School, Kinston, NC",
      bio: "A sophomore wing from Kinston, NC who provided three-point shooting and defensive toughness. Returned for his junior year and was selected #25 overall in 2013. Had a long NBA career.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        currentEmployer: "Houston Rockets",
        league: "NBA",
        location: "Houston, TX",
        statusNote: "Selected #25 overall by the LA Clippers in 2013, Bullock has played 12+ NBA seasons with the Clippers, Suns, Pistons, Lakers, Knicks, Mavericks, and Rockets. Known for his three-point shooting and 3-and-D role. He is also a prominent LGBTQ+ ally in the NBA, honoring his late transgender sister Mia Henderson by wearing rainbow warm-up gear and advocating for inclusion.",
        sourceUrl: "https://en.wikipedia.org/wiki/Reggie_Bullock",
      },
      membership: { role: "PLAYER", jerseyNumber: 35, position: "Small Forward", yearsAtSchool: "2010-2013", statsNote: "Sophomore • Future #25 pick • 12-year NBA career • LGBTQ+ ally", gamesPlayed: 38, pointsPerGame: 8.8, reboundsPerGame: 4.3 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2011-12", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 38, minutesPerGame: 24.0, pointsPerGame: 8.8, reboundsPerGame: 4.3, threePointPct: 0.385 },
      ],
      careerEvents: [
        { year: 2013, title: "Selected #25 overall by the LA Clippers", eventType: "DRAFT" },
      ],
    },
    {
      slug: "pj-hairston",
      firstName: "P.J.",
      lastName: "Hairston",
      birthYear: 1992,
      hometown: "Greensboro, NC",
      highSchool: "Dudley High School, Greensboro, NC",
      bio: "A highly-touted freshman guard who showed scoring flashes off the bench. His career at UNC was later derailed by off-court issues, but his talent was undeniable during the Elite Eight season.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Basketball Player",
        location: "North Carolina",
        statusNote: "Hairston's career at UNC ended after suspensions for off-court issues following his sophomore year. He played one season at Texas Legends (G League) before being drafted #26 overall by the Heat (traded to Charlotte) in 2014. He played 2 NBA seasons with the Hornets before off-court issues ended his career prematurely.",
        sourceUrl: "https://en.wikipedia.org/wiki/P._J._Hairston",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Guard", yearsAtSchool: "2011-2013", statsNote: "Freshman • Gifted scorer • Later #26 pick • Elite Eight", gamesPlayed: 37, pointsPerGame: 6.2, reboundsPerGame: 2.1 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2011-12", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 37, minutesPerGame: 14.0, pointsPerGame: 6.2, reboundsPerGame: 2.1 },
      ],
      careerEvents: [
        { year: 2014, title: "Selected #26 overall by the Miami Heat (traded to Charlotte)", eventType: "DRAFT" },
      ],
    },
    {
      slug: "james-michael-mcadoo",
      firstName: "James Michael",
      lastName: "McAdoo",
      birthYear: 1993,
      hometown: "Norfolk, VA",
      highSchool: "Norfolk Christian School, Norfolk, VA",
      bio: "A highly-ranked freshman forward who was expected to be a one-and-done but stayed 3 years at UNC. Later won 2 NBA championships as a reserve with the Golden State Warriors.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NBA Player",
        location: "Virginia",
        statusNote: "McAdoo was the #5 overall recruit in 2011 and was expected to be a lottery pick, but his UNC career didn't reach those heights. He went undrafted in 2014 but signed with the Warriors and won back-to-back NBA championships in 2015 and 2017 as a reserve. He later played in the G League and overseas before retiring.",
        sourceUrl: "https://en.wikipedia.org/wiki/James_Michael_McAdoo",
      },
      membership: { role: "PLAYER", jerseyNumber: 43, position: "Power Forward", yearsAtSchool: "2011-2014", statsNote: "#5 recruit • 2x NBA Champion (Warriors) • Elite Eight", gamesPlayed: 38, pointsPerGame: 6.1, reboundsPerGame: 3.9 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2011-12", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 38, minutesPerGame: 16.5, pointsPerGame: 6.1, reboundsPerGame: 3.9, fieldGoalPct: 0.510 },
      ],
      careerEvents: [
        { year: 2015, title: "Won NBA Championship with Golden State Warriors", eventType: "CHAMPIONSHIP" },
        { year: 2017, title: "Won second NBA Championship with Warriors", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "roy-williams",
      firstName: "Roy",
      lastName: "Williams",
      birthYear: 1950,
      hometown: "Spruce Pine, NC",
      highSchool: "T.C. Roberson High School, Asheville, NC",
      isFeatured: true,
      bio: "Led UNC to the Elite Eight with a roster featuring four future NBA first-round picks (Barnes, Marshall, Henson, Zeller). The 32-6 season was one of the most talented teams of the Roy Williams era.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Head Coach Emeritus",
        currentEmployer: "University of North Carolina (Emeritus)",
        location: "Chapel Hill, NC",
        statusNote: "Roy Williams retired in April 2021 with 903 career victories and three national championships (2005, 2009, 2017). Inducted into the Naismith Basketball Hall of Fame in 2007.",
        sourceUrl: "https://en.wikipedia.org/wiki/Roy_Williams_(basketball_coach)",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2003-2021", statsNote: "903-264 career • 3x NCAA Champion • Hall of Fame" },
      seasonStats: [
        { level: "COACHING", teamName: "North Carolina Tar Heels", season: "2011-12", yearLabel: "2011-12", sortOrder: 210, wins: 32, losses: 6, tournamentResult: "Elite Eight" },
      ],
      careerEvents: [],
    },
  ],
};
