import type { TeamSeed } from "./types";

export const uncBasketball2019: TeamSeed = {
  slug: "unc-basketball-2019",
  name: "North Carolina Tar Heels",
  season: "2018-2019",
  sport: "Men's Basketball",
  school: "University of North Carolina",
  conference: "ACC",
  accomplishment: "2018-2019 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/153.png",
  mascotName: "Tar Heel",
  people: [
    {
      slug: "coby-white",
      firstName: "Coby",
      lastName: "White",
      birthYear: 1999,
      hometown: "United States",
      highSchool: "United States",
      bio: "Freshman phenom from Goldsboro, NC. #7 pick in 2019.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        location: "Chicago, IL",
        statusNote: "Selected #7 by Chicago Bulls. 6+ year NBA career. Averaged 18+ PPG in 2023-24.",
        sourceUrl: "https://en.wikipedia.org/wiki/Coby_White",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Point Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 16.1, reboundsPerGame: 3.5, assistsPerGame: 4.1 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 16.1, reboundsPerGame: 3.5, assistsPerGame: 4.1 },
      ],
      careerEvents: [],
    },
    {
      slug: "cameron-johnson-unc",
      firstName: "Cameron",
      lastName: "Johnson",
      birthYear: 1996,
      hometown: "United States",
      highSchool: "United States",
      bio: "Senior and UNC's best shooter. #11 pick.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        location: "Brooklyn, NY",
        statusNote: "#11 pick by Suns. Now with Nets on $100M+ contract.",
        sourceUrl: "https://en.wikipedia.org/wiki/Cameron_Johnson",
      },
      membership: { role: "PLAYER", jerseyNumber: 13, position: "Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 16.9, reboundsPerGame: 5.8, assistsPerGame: 2.4 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 16.9, reboundsPerGame: 5.8, assistsPerGame: 2.4 },
      ],
      careerEvents: [],
    },
    {
      slug: "nassir-little",
      firstName: "Nassir",
      lastName: "Little",
      birthYear: 2000,
      hometown: "United States",
      highSchool: "United States",
      bio: "Freshman 5-star who was #25 pick.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        location: "Portland, OR",
        statusNote: "Selected #25 by Trail Blazers in 2019. NBA career ongoing.",
        sourceUrl: "https://en.wikipedia.org/wiki/Nassir_Little",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 9.8, reboundsPerGame: 4.6, assistsPerGame: 0.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 9.8, reboundsPerGame: 4.6, assistsPerGame: 0.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "roy-williams",
      firstName: "Roy",
      lastName: "Williams",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Hall of Fame coach with 903 career victories and 3 national championships (2005, 2009, 2017) at UNC.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Retired in April 2021. Head Coach Emeritus at UNC.",
        sourceUrl: "https://en.wikipedia.org/wiki/Roy_Williams",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2021" },
      seasonStats: [
        { level: "COACHING", teamName: "North Carolina Tar Heels", season: "2018-2019", yearLabel: "2018-2019", sortOrder: 211 },
      ],
      careerEvents: [],
    },
  ],
};
