import type { TeamSeed } from "./types";

export const uncBasketball2014: TeamSeed = {
  slug: "unc-basketball-2014",
  name: "North Carolina Tar Heels",
  season: "2013-2014",
  sport: "Men's Basketball",
  school: "University of North Carolina",
  conference: "ACC",
  accomplishment: "2013-2014 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/153.png",
  mascotName: "Tar Heel",
  people: [
    {
      slug: "marcus-paige",
      firstName: "Marcus",
      lastName: "Paige",
      birthYear: 1993,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore guard emerging as team leader.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Iowa",
        statusNote: "Famous for game-tying 3 in 2016 title game. Played overseas.",
        sourceUrl: "https://en.wikipedia.org/wiki/Marcus_Paige",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Point Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 10, reboundsPerGame: 2.5, assistsPerGame: 3.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 10, reboundsPerGame: 2.5, assistsPerGame: 3.8 },
      ],
      careerEvents: [],
    },
    {
      slug: "james-michael-mcadoo",
      firstName: "James Michael",
      lastName: "McAdoo",
      birthYear: 1993,
      hometown: "United States",
      highSchool: "United States",
      bio: "Junior forward who declared for draft. 2x NBA champion.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired",
        location: "Virginia",
        statusNote: "Undrafted but won 2 NBA titles with Warriors as reserve.",
        sourceUrl: "https://en.wikipedia.org/wiki/James Michael_McAdoo",
      },
      membership: { role: "PLAYER", jerseyNumber: 43, position: "Power Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 14.2, reboundsPerGame: 6.5, assistsPerGame: 0.7 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 14.2, reboundsPerGame: 6.5, assistsPerGame: 0.7 },
      ],
      careerEvents: [],
    },
    {
      slug: "brice-johnson",
      firstName: "Brice",
      lastName: "Johnson",
      birthYear: 1994,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore forward. Future All-ACC and #25 pick.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "Overseas",
        statusNote: "Selected #25 by Clippers in 2016. Played NBA and overseas.",
        sourceUrl: "https://en.wikipedia.org/wiki/Brice_Johnson",
      },
      membership: { role: "PLAYER", jerseyNumber: 11, position: "Power Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 10.3, reboundsPerGame: 5.5, assistsPerGame: 0.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 10.3, reboundsPerGame: 5.5, assistsPerGame: 0.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "roy-williams",
      firstName: "Roy",
      lastName: "Williams",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Hall of Fame coach with 903 career victories and 3 national championships (2005, 2009, 2017) at UNC.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Retired in April 2021. Head Coach Emeritus at UNC.",
        sourceUrl: "https://en.wikipedia.org/wiki/Roy_Williams",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2021" },
      seasonStats: [
        { level: "COACHING", teamName: "North Carolina Tar Heels", season: "2013-2014", yearLabel: "2013-2014", sortOrder: 206 },
      ],
      careerEvents: [],
    },
  ],
};
