import type { TeamSeed } from "./types";

export const uncBasketball2010: TeamSeed = {
  slug: "unc-basketball-2010",
  name: "North Carolina Tar Heels",
  season: "2009-2010",
  sport: "Men's Basketball",
  school: "University of North Carolina",
  conference: "ACC",
  accomplishment: "2009-2010 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/153.png",
  mascotName: "Tar Heel",
  people: [
    {
      slug: "ed-davis",
      firstName: "Ed",
      lastName: "Davis",
      birthYear: 1989,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore forward who was UNC's best player. #13 pick in 2010.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "NBA Player",
        location: "Cleveland, OH",
        statusNote: "13-year NBA career with multiple teams. Selected #13 overall by the Toronto Raptors in 2010.",
        sourceUrl: "https://en.wikipedia.org/wiki/Ed_Davis",
      },
      membership: { role: "PLAYER", jerseyNumber: 32, position: "Power Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 13.2, reboundsPerGame: 8.4, assistsPerGame: 0.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 13.2, reboundsPerGame: 8.4, assistsPerGame: 0.8 },
      ],
      careerEvents: [],
    },
    {
      slug: "deon-thompson",
      firstName: "Deon",
      lastName: "Thompson",
      birthYear: 1988,
      hometown: "United States",
      highSchool: "United States",
      bio: "Senior forward who played in record 152 career games.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player / MBA Candidate",
        location: "Chapel Hill, NC",
        statusNote: "16-year international career. Currently pursuing MBA at UNC Kenan-Flagler.",
        sourceUrl: "https://en.wikipedia.org/wiki/Deon_Thompson",
      },
      membership: { role: "PLAYER", jerseyNumber: 21, position: "Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 12.5, reboundsPerGame: 5.8, assistsPerGame: 1.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 12.5, reboundsPerGame: 5.8, assistsPerGame: 1.2 },
      ],
      careerEvents: [],
    },
    {
      slug: "larry-drew-ii",
      firstName: "Larry",
      lastName: "Drew II",
      birthYear: 1990,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore point guard. Son of NBA coach Larry Drew.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Player",
        location: "California",
        statusNote: "Transferred to UCLA where he broke the school assist record. Brief NBA career.",
        sourceUrl: "https://en.wikipedia.org/wiki/Larry_Drew_II",
      },
      membership: { role: "PLAYER", jerseyNumber: 11, position: "Point Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 5.8, reboundsPerGame: 1.5, assistsPerGame: 3.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 5.8, reboundsPerGame: 1.5, assistsPerGame: 3.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "marcus-ginyard",
      firstName: "Marcus",
      lastName: "Ginyard",
      birthYear: 1986,
      hometown: "United States",
      highSchool: "United States",
      bio: "5th-year senior who returned from injury. 2009 champion.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Director of Special Projects",
        location: "Chapel Hill, NC",
        statusNote: "Named UNC Director of Special Projects in 2025. 11-year pro career overseas.",
        sourceUrl: "https://en.wikipedia.org/wiki/Marcus_Ginyard",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Guard/Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 4.8, reboundsPerGame: 3, assistsPerGame: 1.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 4.8, reboundsPerGame: 3, assistsPerGame: 1.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "roy-williams",
      firstName: "Roy",
      lastName: "Williams",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Hall of Fame coach with 903 career victories and 3 national championships (2005, 2009, 2017) at UNC.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Retired in April 2021. Head Coach Emeritus at UNC.",
        sourceUrl: "https://en.wikipedia.org/wiki/Roy_Williams",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2021" },
      seasonStats: [
        { level: "COACHING", teamName: "North Carolina Tar Heels", season: "2009-2010", yearLabel: "2009-2010", sortOrder: 202 },
      ],
      careerEvents: [],
    },
  ],
};
