import type { TeamSeed } from "./types";

export const uncBasketball2016: TeamSeed = {
  slug: "unc-basketball-2016",
  name: "North Carolina Tar Heels",
  season: "2015-2016",
  sport: "Men's Basketball",
  school: "University of North Carolina",
  conference: "ACC",
  accomplishment: "2015-2016 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/153.png",
  mascotName: "Tar Heel",
  people: [
    {
      slug: "marcus-paige",
      firstName: "Marcus",
      lastName: "Paige",
      birthYear: 1993,
      hometown: "United States",
      highSchool: "United States",
      bio: "Senior captain. Hit iconic double-clutch 3 to tie 2016 title game vs Villanova.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Iowa",
        statusNote: "His game-tying 3 in the 2016 championship game — only to lose on Kris Jenkins' buzzer-beater — is one of the most memorable moments in NCAA history.",
        sourceUrl: "https://en.wikipedia.org/wiki/Marcus_Paige",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Point Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 12.5, reboundsPerGame: 2.5, assistsPerGame: 4 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 12.5, reboundsPerGame: 2.5, assistsPerGame: 4 },
      ],
      careerEvents: [],
    },
    {
      slug: "brice-johnson",
      firstName: "Brice",
      lastName: "Johnson",
      birthYear: 1994,
      hometown: "United States",
      highSchool: "United States",
      bio: "Senior and ACC POY. UNC's best player on the title game team.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "Overseas",
        statusNote: "ACC Player of the Year. #25 pick by Clippers.",
        sourceUrl: "https://en.wikipedia.org/wiki/Brice_Johnson",
      },
      membership: { role: "PLAYER", jerseyNumber: 11, position: "Power Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 17, reboundsPerGame: 10.2, assistsPerGame: 1 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 17, reboundsPerGame: 10.2, assistsPerGame: 1 },
      ],
      careerEvents: [],
    },
    {
      slug: "joel-berry-ii",
      firstName: "Joel",
      lastName: "Berry II",
      birthYear: 1996,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore PG who would lead UNC to the 2017 title.",
      status: {
        occupationType: "BROADCASTER_ANALYST",
        currentTitle: "ACC Network Analyst",
        location: "Charlotte, NC",
        statusNote: "Now ACC Network studio analyst. 2017 Final Four MOP.",
        sourceUrl: "https://en.wikipedia.org/wiki/Joel_Berry_II",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Point Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 12, reboundsPerGame: 3, assistsPerGame: 3.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 12, reboundsPerGame: 3, assistsPerGame: 3.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "justin-jackson-unc",
      firstName: "Justin",
      lastName: "Jackson",
      birthYear: 1995,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore wing. Future consensus All-American.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "Ottawa, Canada",
        statusNote: "Became All-American next year. #15 pick. NBA champ with Bucks.",
        sourceUrl: "https://en.wikipedia.org/wiki/Justin_Jackson",
      },
      membership: { role: "PLAYER", jerseyNumber: 44, position: "Small Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 12, reboundsPerGame: 4, assistsPerGame: 2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 12, reboundsPerGame: 4, assistsPerGame: 2 },
      ],
      careerEvents: [],
    },
    {
      slug: "roy-williams",
      firstName: "Roy",
      lastName: "Williams",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Hall of Fame coach with 903 career victories and 3 national championships (2005, 2009, 2017) at UNC.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Retired in April 2021. Head Coach Emeritus at UNC.",
        sourceUrl: "https://en.wikipedia.org/wiki/Roy_Williams",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2021" },
      seasonStats: [
        { level: "COACHING", teamName: "North Carolina Tar Heels", season: "2015-2016", yearLabel: "2015-2016", sortOrder: 208 },
      ],
      careerEvents: [],
    },
  ],
};
