import type { TeamSeed } from "./types";

export const uncBasketball2022: TeamSeed = {
  slug: "unc-basketball-2022",
  name: "North Carolina Tar Heels",
  season: "2021-2022",
  sport: "Men's Basketball",
  school: "University of North Carolina",
  conference: "ACC",
  accomplishment: "NCAA Runner-Up (29-10)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/153.png",
  mascotName: "Tar Heel",
  people: [
    {
      slug: "caleb-love",
      firstName: "Caleb",
      lastName: "Love",
      birthYear: 2001,
      hometown: "St. Louis, MO",
      highSchool: "Christian Brothers College High School, St. Louis, MO",
      isFeatured: true,
      bio: "The electrifying sophomore guard whose 30-point explosion against Duke in the Final Four semifinal — including a dagger three with under 30 seconds left — produced one of the most iconic moments in UNC basketball history. His rivalry with Duke defined the 2022 season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard (Two-Way Contract)",
        currentEmployer: "Portland Trail Blazers / Rip City Remix",
        league: "NBA / G League",
        location: "Portland, OR",
        statusNote: "After two seasons at UNC (including the 2022 title game run), Love transferred to Arizona where he played two more seasons and helped the Wildcats reach the Sweet Sixteen in 2025. He went undrafted in the 2025 NBA Draft but signed a two-way contract with the Portland Trail Blazers on July 1, 2025, splitting time between the Blazers and their G League affiliate, the Rip City Remix. His 30-point game against Duke in the 2022 Final Four remains one of the defining moments in college basketball this decade.",
        sourceUrl: "https://en.wikipedia.org/wiki/Caleb_Love",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Point Guard", yearsAtSchool: "2020-2023", statsNote: "30 pts vs Duke in Final Four • NCAA Runner-Up", gamesPlayed: 39, pointsPerGame: 15.9, reboundsPerGame: 3.4, assistsPerGame: 3.6 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2021-22", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 39, minutesPerGame: 33.6, pointsPerGame: 15.9, reboundsPerGame: 3.4, assistsPerGame: 3.6, stealsPerGame: 1.3, fieldGoalPct: 0.424, threePointPct: 0.360 },
        { level: "COLLEGE", teamName: "Arizona Wildcats", season: "2023-24", yearLabel: "Junior (transfer)", sortOrder: 203, gamesPlayed: 34, pointsPerGame: 18.0, reboundsPerGame: 4.5, assistsPerGame: 3.2 },
      ],
      careerEvents: [
        { year: 2022, title: "Scored 30 points to beat Duke in Final Four semifinal", eventType: "MILESTONE", month: 4, day: 2 },
        { year: 2022, title: "Reached NCAA Championship Game (lost to Kansas)", eventType: "MILESTONE", month: 4, day: 4 },
        { year: 2023, title: "Transferred to Arizona", eventType: "SIGNING" },
        { year: 2025, title: "Signed two-way contract with Portland Trail Blazers", eventType: "SIGNING" },
      ],
    },
    {
      slug: "armando-bacot",
      firstName: "Armando",
      lastName: "Bacot",
      birthYear: 2000,
      hometown: "Richmond, VA",
      highSchool: "Trinity Episcopal School, Richmond, VA",
      isFeatured: true,
      bio: "The bruising junior center who set the NCAA single-season record for double-doubles (31) during the 2022 run. Played through a painful ankle injury in the championship game against Kansas. Returned for two more seasons to become UNC's all-time leading rebounder.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "Fenerbahce",
        league: "EuroLeague / BSL (Turkey)",
        location: "Istanbul, Turkey",
        statusNote: "After a legendary five-year UNC career in which he became the program's all-time leading rebounder and set the NCAA single-season double-double record, Bacot went undrafted in the 2024 NBA Draft. He played NBA Summer League with the Utah Jazz, then joined the Memphis Hustle (Grizzlies' G League affiliate) where he dominated — averaging 18.2 PPG and 9.5 RPG, earning G League Player of the Week and an invite to the G League Up Next Game at All-Star Weekend. In summer 2025, he signed with Fenerbahce of the Turkish BSL and EuroLeague, one of Europe's most prestigious clubs.",
        sourceUrl: "https://en.wikipedia.org/wiki/Armando_Bacot",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Center", yearsAtSchool: "2019-2024", statsNote: "NCAA record 31 double-doubles • UNC all-time rebounder • NCAA Runner-Up", gamesPlayed: 39, pointsPerGame: 16.3, reboundsPerGame: 13.1, assistsPerGame: 1.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2021-22", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 39, minutesPerGame: 31.8, pointsPerGame: 16.3, reboundsPerGame: 13.1, assistsPerGame: 1.2, fieldGoalPct: 0.577 },
        { level: "PROFESSIONAL", teamName: "Memphis Hustle (G League)", season: "2024-25", yearLabel: "2024-25 (G League)", sortOrder: 301, gamesPlayed: 35, pointsPerGame: 18.2, reboundsPerGame: 9.5 },
      ],
      careerEvents: [
        { year: 2022, title: "Set NCAA single-season record with 31 double-doubles", eventType: "AWARD" },
        { year: 2022, title: "Reached NCAA Championship Game (lost to Kansas)", eventType: "MILESTONE", month: 4, day: 4 },
        { year: 2025, title: "Signed with Fenerbahce (EuroLeague)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "brady-manek",
      firstName: "Brady",
      lastName: "Manek",
      birthYear: 1998,
      hometown: "Harrah, OK",
      highSchool: "Harrah High School, Harrah, OK",
      bio: "The sharpshooting Oklahoma transfer whose floor-spacing and chemistry with Bacot transformed UNC's offense. His three-point shooting was the catalyst behind the Tar Heels' improbable run from 8-seed to the title game.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        currentEmployer: "Leones de Ponce",
        league: "BSN (Puerto Rico)",
        location: "Ponce, Puerto Rico",
        statusNote: "After UNC's championship game appearance, Manek was not drafted but has built a professional career overseas. He played for the Nanjing Monkey Kings in the Chinese Basketball Association (CBA) and signed with the Leones de Ponce in Puerto Rico's BSN league in June 2025. His one season at UNC — where he transferred after four years at Oklahoma — is considered one of the most impactful transfer portal moves in recent college basketball history.",
        sourceUrl: "https://en.wikipedia.org/wiki/Brady_Manek",
      },
      membership: { role: "PLAYER", jerseyNumber: 45, position: "Power Forward", yearsAtSchool: "2021-2022", statsNote: "Oklahoma transfer • Floor-spacer • NCAA Runner-Up", gamesPlayed: 39, pointsPerGame: 15.1, reboundsPerGame: 6.1, assistsPerGame: 1.0 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2021-22", yearLabel: "5th Year (transfer from Oklahoma)", sortOrder: 205, gamesPlayed: 39, minutesPerGame: 31.0, pointsPerGame: 15.1, reboundsPerGame: 6.1, threePointPct: 0.378, fieldGoalPct: 0.491 },
      ],
      careerEvents: [
        { year: 2022, title: "Reached NCAA Championship Game with UNC", eventType: "MILESTONE", month: 4, day: 4 },
        { year: 2025, title: "Signed with Leones de Ponce (Puerto Rico BSN)", eventType: "SIGNING" },
      ],
    },
    {
      slug: "rj-davis",
      firstName: "RJ",
      lastName: "Davis",
      birthYear: 2001,
      hometown: "White Plains, NY",
      highSchool: "Archbishop Stepinac High School, White Plains, NY",
      bio: "A sophomore guard who provided backcourt scoring alongside Caleb Love. Returned to UNC for three more seasons and became one of the most prolific scorers in program history.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "NBA / G League",
        location: "United States",
        statusNote: "Davis stayed at UNC through the 2024-25 season, becoming one of the most decorated players in program history. He was named ACC Player of the Year and finished as one of UNC's all-time leading scorers. He was selected in the 2025 NBA Draft and is beginning his professional career. He played NBA Summer League in 2025 and has shown promise at the next level.",
        sourceUrl: "https://en.wikipedia.org/wiki/RJ_Davis_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Guard", yearsAtSchool: "2020-2025", statsNote: "Sophomore scorer • Future ACC POY • NCAA Runner-Up", gamesPlayed: 38, pointsPerGame: 13.5, reboundsPerGame: 4.3, assistsPerGame: 3.6 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2021-22", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 38, minutesPerGame: 32.2, pointsPerGame: 13.5, reboundsPerGame: 4.3, assistsPerGame: 3.6, fieldGoalPct: 0.437, threePointPct: 0.356 },
      ],
      careerEvents: [
        { year: 2022, title: "Reached NCAA Championship Game with UNC", eventType: "MILESTONE", month: 4, day: 4 },
        { year: 2025, title: "Named ACC Player of the Year", eventType: "AWARD" },
        { year: 2025, title: "Selected in 2025 NBA Draft", eventType: "DRAFT" },
      ],
    },
    {
      slug: "leaky-black",
      firstName: "Leaky",
      lastName: "Black",
      birthYear: 1999,
      hometown: "Concord, NC",
      highSchool: "Cox Mill High School, Concord, NC",
      bio: "The junior defensive specialist who guarded the opponent's best player every night. Named to the ACC All-Defensive Team, he was UNC's lockdown perimeter defender during the entire tournament run.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "G League / Overseas",
        location: "United States",
        statusNote: "After four seasons at UNC, Black went undrafted but has pursued a professional basketball career in the G League and overseas. Known primarily for his elite defense rather than scoring, he has worked to develop his offensive game at the pro level. His defensive versatility — guarding 1 through 4 — made him a valuable college player even without gaudy stats.",
        sourceUrl: "https://goheels.com/sports/mens-basketball/roster/leaky-black/",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Small Forward", yearsAtSchool: "2019-2023", statsNote: "Lockdown defender • ACC All-Defensive Team • NCAA Runner-Up", gamesPlayed: 39, pointsPerGame: 4.5, reboundsPerGame: 3.3, assistsPerGame: 1.9 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2021-22", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 39, minutesPerGame: 28.0, pointsPerGame: 4.5, reboundsPerGame: 3.3, assistsPerGame: 1.9, stealsPerGame: 0.9 },
      ],
      careerEvents: [
        { year: 2022, title: "Reached NCAA Championship Game with UNC", eventType: "MILESTONE", month: 4, day: 4 },
      ],
    },
    {
      slug: "puff-johnson",
      firstName: "Puff",
      lastName: "Johnson",
      birthYear: 2001,
      hometown: "Moon Township, PA",
      highSchool: "Hillcrest Prep, Phoenix, AZ",
      bio: "A sophomore forward and younger brother of NBA player Cameron Johnson. Provided key minutes off the bench during the tournament run and hit clutch shots in the Sweet 16.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "G League / Overseas",
        location: "United States",
        statusNote: "After four years at UNC (including the 2022 title game run), Puff Johnson entered the professional ranks. He is the younger brother of Brooklyn Nets forward Cameron Johnson, following the family tradition of playing at the highest level. He has played in the G League while seeking an NBA opportunity.",
        sourceUrl: "https://goheels.com/sports/mens-basketball/roster/puff-johnson/",
      },
      membership: { role: "PLAYER", jerseyNumber: 14, position: "Forward", yearsAtSchool: "2020-2024", statsNote: "Sophomore reserve • Cameron Johnson's brother • NCAA Runner-Up", gamesPlayed: 33, pointsPerGame: 3.5, reboundsPerGame: 1.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2021-22", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 33, minutesPerGame: 10.5, pointsPerGame: 3.5, reboundsPerGame: 1.8, fieldGoalPct: 0.440 },
      ],
      careerEvents: [
        { year: 2022, title: "Reached NCAA Championship Game with UNC", eventType: "MILESTONE", month: 4, day: 4 },
      ],
    },
    {
      slug: "dawson-garcia",
      firstName: "Dawson",
      lastName: "Garcia",
      birthYear: 2001,
      hometown: "Prior Lake, MN",
      highSchool: "Prior Lake High School, Prior Lake, MN",
      bio: "A sophomore forward who transferred from Marquette and provided scoring punch off the bench. His shooting ability stretched defenses and complemented Bacot's interior dominance.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        location: "Minneapolis, MN",
        statusNote: "Garcia stayed at UNC through the 2024-25 season before entering the transfer portal. He is one of the most-traveled players in the transfer portal era, having played at Marquette, UNC, and potentially additional schools. He has used his extra COVID-year eligibility to extend his college career.",
        sourceUrl: "https://goheels.com/sports/mens-basketball/roster/dawson-garcia/",
      },
      membership: { role: "PLAYER", jerseyNumber: 13, position: "Forward", yearsAtSchool: "2021-2025", statsNote: "Marquette transfer • Scoring forward • NCAA Runner-Up", gamesPlayed: 27, pointsPerGame: 6.5, reboundsPerGame: 3.1 },
      seasonStats: [
        { level: "COLLEGE", teamName: "North Carolina Tar Heels", season: "2021-22", yearLabel: "Sophomore (transfer)", sortOrder: 202, gamesPlayed: 27, minutesPerGame: 15.1, pointsPerGame: 6.5, reboundsPerGame: 3.1, fieldGoalPct: 0.452 },
      ],
      careerEvents: [
        { year: 2022, title: "Reached NCAA Championship Game with UNC", eventType: "MILESTONE", month: 4, day: 4 },
      ],
    },
    {
      slug: "steve-robinson-unc",
      firstName: "Steve",
      lastName: "Robinson",
      birthYear: 1957,
      hometown: "Roanoke, VA",
      highSchool: "Radford University (played at)",
      bio: "Roy Williams' most trusted assistant who followed him from Kansas. Master recruiter who helped build three championship teams at UNC.",
      status: { occupationType: "RETIRED_COACH", currentTitle: "Retired Assistant Coach", location: "North Carolina", statusNote: "Served 18 years as assistant under Roy Williams at UNC (2003-2021), winning 3 national titles. Not retained when Hubert Davis became head coach. Previously HC at Tulsa and Florida State.", sourceUrl: "https://goheels.com/sports/mens-basketball/roster/coaches/steve-robinson/691" },
      membership: { role: "ASSISTANT_COACH", position: "Associate Head Coach", yearsAtSchool: "2003-2021" },
      careerEvents: [],
    },
    {
      slug: "hubert-davis",
      firstName: "Hubert",
      lastName: "Davis",
      birthYear: 1970,
      hometown: "Burke, VA",
      highSchool: "Lake Braddock Secondary School, Burke, VA",
      isFeatured: true,
      bio: "Led UNC to the national championship game in his first season as head coach — only the second first-year coach in history to reach the title game. A former UNC player (1988-92) and NBA veteran who succeeded Roy Williams in April 2021.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Former Head Coach",
        location: "Chapel Hill, NC",
        statusNote: "Hubert Davis was named UNC's head coach in April 2021, succeeding his mentor Roy Williams. He made history by leading UNC to the national championship game in his debut season (2021-22), where they lost to Kansas 72-69. His tenure included a 125-54 record over five seasons, but ended abruptly when he was fired on March 25, 2026 after UNC — as a #6 seed — blew a 19-point second-half lead to #11 VCU in the first round of the 2026 NCAA Tournament. It was the largest comeback in first-round March Madness history and UNC's second straight first-round exit. His buyout was over $5.3 million. Davis previously played 12 seasons in the NBA (1992-2004) and was one of the greatest three-point shooters of his era.",
        sourceUrl: "https://en.wikipedia.org/wiki/Hubert_Davis",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2021-2026", statsNote: "125-54 record • NCAA Runner-Up in 1st season • Fired 2026" },
      seasonStats: [
        { level: "COACHING", teamName: "North Carolina Tar Heels", season: "2021-22", yearLabel: "2021-22", sortOrder: 201, wins: 29, losses: 10, tournamentResult: "NCAA Runner-Up (lost to Kansas)" },
      ],
      careerEvents: [
        { year: 2021, title: "Named UNC head coach, succeeding Roy Williams", eventType: "CAREER_CHANGE" },
        { year: 2022, title: "Led UNC to national championship game in his first season", eventType: "MILESTONE", month: 4, day: 4 },
        { year: 2026, title: "Fired after blowing 19-point lead to VCU in 1st round", eventType: "CAREER_CHANGE", month: 3, day: 25 },
      ],
    },
  ],
};
