import type { TeamSeed } from "./types";

export const uscFootball2005: TeamSeed = {
  slug: "usc-football-2005",
  name: "USC Trojans",
  season: "2005",
  sport: "Football",
  school: "University of Southern California",
  conference: "Pac-10",
  accomplishment: "BCS National Championship Game Appearance (12-1)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/30.png",
  mascotName: "Traveler",
  people: [
    // ── Batch 1: Star Players ────────────────────────────────────────────────
    {
      slug: "matt-leinart",
      firstName: "Matt",
      lastName: "Leinart",
      birthYear: 1983,
      hometown: "Santa Ana, CA",
      highSchool: "Mater Dei High School, Santa Ana, CA",
      isFeatured: true,
      bio: "The 2004 Heisman Trophy-winning quarterback who led USC to consecutive BCS National Championship Games. Leinart chose to return for his senior year in 2005 and threw for 3,815 yards and 28 TDs.",
      status: {
        occupationType: "BROADCASTER_ANALYST",
        currentTitle: "College Football Analyst",
        currentEmployer: "Fox Sports",
        location: "Los Angeles, CA",
        statusNote:
          "After a seven-year NFL career spent mostly with the Arizona Cardinals, Leinart transitioned to broadcasting in 2014 and is now an analyst on Fox Sports' Big Noon Kickoff college football pregame show. He is also an active real estate investor in the Los Angeles market and runs the Matt Leinart Foundation, which creates athletic opportunities for underprivileged youth. He married actress Josie Loren in 2018 and the couple have two children, including a daughter born in February 2025.",
        sourceUrl: "https://en.wikipedia.org/wiki/Matt_Leinart",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 11,
        position: "Quarterback",
        yearsAtSchool: "2001-2005",
        statsNote: "2004 Heisman Trophy • 3,815 yds, 28 TD, 8 INT in 2005 • 37-2 career record as starter",
      },
      careerEvents: [
        { year: 2004, title: "Won Heisman Trophy", eventType: "AWARD" },
        { year: 2005, title: "BCS National Championship Game vs Texas (lost 41-38)", eventType: "CHAMPIONSHIP" },
        { year: 2006, title: "Selected #10 overall by the Arizona Cardinals", eventType: "DRAFT" },
        { year: 2012, title: "Played final NFL season with Oakland Raiders", eventType: "CAREER" },
        { year: 2014, title: "Joined Fox Sports as college football analyst", eventType: "CAREER" },
      ],
    },
    {
      slug: "reggie-bush",
      firstName: "Reggie",
      lastName: "Bush",
      birthYear: 1985,
      hometown: "La Mesa, CA",
      highSchool: "Helix High School, La Mesa, CA",
      isFeatured: true,
      bio: "One of the most electrifying college football players ever, Bush won the 2005 Heisman Trophy (vacated in 2010, restored in 2024). He rushed for 1,740 yards and had 478 receiving yards in 2005.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NFL Player / Media Personality",
        location: "Los Angeles, CA",
        statusNote:
          "Selected 2nd overall by the New Orleans Saints in 2006, Bush won Super Bowl XLIV in 2010 and played 11 NFL seasons with six teams before retiring in 2017. His Heisman Trophy was controversially vacated in 2010 due to NCAA violations but was officially restored in April 2024 amid the NIL era's shifting attitudes. He served as a Fox Sports college football analyst on Big Noon Kickoff from 2019 to 2023. Bush continues to advocate for student-athlete rights and maintains a strong media presence.",
        sourceUrl: "https://en.wikipedia.org/wiki/Reggie_Bush",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 5,
        position: "Running Back",
        yearsAtSchool: "2003-2005",
        statsNote: "2005 Heisman Trophy • 1,740 rush yds, 16 TD • 478 rec yds in 2005",
      },
      careerEvents: [
        { year: 2005, title: "Won Heisman Trophy (later vacated, restored 2024)", eventType: "AWARD" },
        { year: 2006, title: "Selected #2 overall by the New Orleans Saints", eventType: "DRAFT" },
        { year: 2010, title: "Won Super Bowl XLIV with the Saints", eventType: "CHAMPIONSHIP" },
        { year: 2010, title: "Heisman Trophy vacated due to NCAA violations", eventType: "OTHER" },
        { year: 2017, title: "Retired from the NFL after 11 seasons", eventType: "RETIREMENT" },
        { year: 2024, title: "Heisman Trophy officially restored", eventType: "AWARD" },
      ],
    },
    {
      slug: "lendale-white",
      firstName: "LenDale",
      lastName: "White",
      birthYear: 1984,
      hometown: "Denver, CO",
      highSchool: "Chatfield Senior High School, Littleton, CO",
      isFeatured: false,
      bio: "The powerful complement to Reggie Bush in USC's backfield, White rushed for 1,302 yards and 24 touchdowns in 2005. Known as 'Thunder' to Bush's 'Lightning.'",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Podcast Co-Host",
        location: "Denver, CO",
        statusNote:
          "Selected in the second round by the Tennessee Titans in 2006, White rushed for 15 TDs in 2008 as part of the famed 'Smash & Dash' duo with Chris Johnson. A torn Achilles in 2010 preseason with Denver ended his playing career. After battling depression and substance abuse issues, White rebuilt his life with support from Johnson. He now co-hosts the Smash & Dash podcast with Johnson and resides in Denver.",
        sourceUrl: "https://en.wikipedia.org/wiki/LenDale_White",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 25,
        position: "Running Back",
        yearsAtSchool: "2003-2005",
        statsNote: "1,302 rush yds, 24 TD in 2005 • 2,624 career rush yds at USC",
      },
      careerEvents: [
        { year: 2006, title: "Selected #45 overall by the Tennessee Titans", eventType: "DRAFT" },
        { year: 2008, title: "Rushed for 15 TDs as part of 'Smash & Dash' with Chris Johnson", eventType: "CAREER" },
        { year: 2010, title: "Torn Achilles ended NFL career during Denver Broncos preseason", eventType: "INJURY" },
      ],
    },
    {
      slug: "dwayne-jarrett",
      firstName: "Dwayne",
      lastName: "Jarrett",
      birthYear: 1986,
      hometown: "New Brunswick, NJ",
      highSchool: "New Brunswick High School, New Brunswick, NJ",
      isFeatured: false,
      bio: "A two-time All-American wide receiver who was Leinart's top target, Jarrett caught 91 passes for 1,274 yards and 16 TDs in 2005.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Private Citizen",
        statusNote:
          "Selected 45th overall by the Carolina Panthers in 2007, Jarrett struggled to replicate his college success in the NFL, totaling just 35 catches over four seasons. He was released following a second DUI arrest in 2010. A brief stint with the Saskatchewan Roughriders in 2012 ended his playing career at age 25. Since retiring, Jarrett has maintained a very low public profile and stepped largely out of the spotlight.",
        sourceUrl: "https://en.wikipedia.org/wiki/Dwayne_Jarrett",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 8,
        position: "Wide Receiver",
        yearsAtSchool: "2004-2006",
        statsNote: "Two-time All-American • 91 rec, 1,274 yds, 16 TD in 2005",
      },
      careerEvents: [
        { year: 2007, title: "Selected #45 overall by the Carolina Panthers", eventType: "DRAFT" },
        { year: 2010, title: "Released by Panthers after second DUI arrest", eventType: "OTHER" },
        { year: 2012, title: "Brief CFL stint with Saskatchewan Roughriders before retiring", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "steve-smith-usc",
      firstName: "Steve",
      lastName: "Smith",
      birthYear: 1985,
      hometown: "Anchorage, AK",
      highSchool: "Taft High School, Woodland Hills, CA",
      isFeatured: false,
      bio: "A reliable possession receiver who caught 63 passes for 959 yards and 6 TDs in 2005. His brother Malcolm Smith later won Super Bowl MVP with Seattle.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Co-Owner",
        currentEmployer: "Xplode Training Center",
        location: "San Fernando Valley, CA",
        statusNote:
          "Selected in the second round by the New York Giants in 2007, Smith had a Pro Bowl-caliber 2009 season with 107 catches. He played six NFL seasons with the Giants, Eagles, Rams, and Buccaneers before retiring in 2013. He now co-owns Xplode Training Center in Chatsworth, CA, specializing in youth football training camps and skill development programs. His brother Malcolm Smith won Super Bowl XLVIII MVP with the Seattle Seahawks.",
        sourceUrl: "https://en.wikipedia.org/wiki/Steve_Smith_(wide_receiver,_born_1985)",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 2,
        position: "Wide Receiver",
        yearsAtSchool: "2003-2006",
        statsNote: "63 rec, 959 yds, 6 TD in 2005 • All-American",
      },
      careerEvents: [
        { year: 2007, title: "Selected #51 overall by the New York Giants", eventType: "DRAFT" },
        { year: 2009, title: "Pro Bowl alternate season: 107 receptions, 1,220 yards", eventType: "CAREER" },
        { year: 2013, title: "Retired from the NFL after six seasons", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "keith-rivers",
      firstName: "Keith",
      lastName: "Rivers",
      birthYear: 1986,
      hometown: "Lake Mary, FL",
      highSchool: "Lake Mary High School, Lake Mary, FL",
      isFeatured: true,
      bio: "A dominant linebacker who wore the prestigious USC #55 jersey, Rivers had 240 career tackles including 18.5 for losses. A true freshman starter on the 2005 team.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Art Collector and Curator",
        location: "Los Angeles, CA",
        statusNote:
          "Selected 9th overall by the Cincinnati Bengals in 2008, Rivers played seven NFL seasons with the Bengals, Giants, and Bills before retiring in 2015. He then pivoted into an extraordinary second career as a fine art collector and curator. His collection includes works by Andy Warhol, Barbara Kruger, Kerry James Marshall, and Kara Walker. He sits on the boards of the Hirshhorn and Hammer museums and curated the 2022 exhibition 'Courage Before Expectation' at New York's Flag Art Foundation.",
        sourceUrl: "https://www.1stdibs.com/introspective-magazine/keith-rivers/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 55,
        position: "Linebacker",
        yearsAtSchool: "2004-2007",
        statsNote: "Wore USC's prestigious #55 • 240 career tackles, 18.5 TFL",
      },
      careerEvents: [
        { year: 2008, title: "Selected #9 overall by the Cincinnati Bengals", eventType: "DRAFT" },
        { year: 2015, title: "Retired from the NFL after seven seasons", eventType: "RETIREMENT" },
        { year: 2015, title: "Began collecting fine art; first purchase was an Andy Warhol", eventType: "CAREER" },
        { year: 2022, title: "Curated 'Courage Before Expectation' at Flag Art Foundation, NYC", eventType: "CAREER" },
      ],
    },
    {
      slug: "rey-maualuga",
      firstName: "Rey",
      lastName: "Maualuga",
      birthYear: 1987,
      hometown: "Eureka, CA",
      highSchool: "Eureka High School, Eureka, CA",
      isFeatured: false,
      bio: "A ferocious linebacker and unanimous First-Team All-American in 2008, Maualuga was USC's only Bednarik Award winner. He played in four consecutive Rose Bowls and was the 2008 Rose Bowl Defensive MVP.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired / Full-Time Father",
        location: "Cincinnati, OH",
        statusNote:
          "Selected in the second round by the Cincinnati Bengals in 2009, Maualuga spent eight seasons as a Bengals starter, accumulating 607 career tackles. After a brief 2017 stint with the Dolphins, his career ended amid multiple off-field incidents including several DUI arrests. After a 2021 arrest, he entered a substance abuse program and achieved sobriety. He now focuses on raising his four children, has lost significant weight after peaking at 380 pounds, and was named to the Polynesian Football Hall of Fame Class of 2026.",
        sourceUrl: "https://247sports.com/college/usc/article/usc-football-column-dan-weber-just-sayin-former-linebacker-rey-maualuga-sobriety-fatherhood-253023556/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 58,
        position: "Linebacker",
        yearsAtSchool: "2005-2008",
        statsNote: "Bednarik Award winner • Unanimous All-American • 4 Rose Bowls • 2008 Rose Bowl Defensive MVP",
      },
      careerEvents: [
        { year: 2009, title: "Selected #38 overall by the Cincinnati Bengals", eventType: "DRAFT" },
        { year: 2017, title: "Final NFL season with the Miami Dolphins", eventType: "CAREER" },
        { year: 2023, title: "Achieved sobriety and became full-time father", eventType: "OTHER" },
        { year: 2026, title: "Named to Polynesian Football Hall of Fame Class of 2026", eventType: "AWARD" },
      ],
    },
    // ── Batch 2: Defensive Stars & Linemen ───────────────────────────────────
    {
      slug: "brian-cushing",
      firstName: "Brian",
      lastName: "Cushing",
      birthYear: 1987,
      hometown: "Park Ridge, NJ",
      highSchool: "Bergen Catholic High School, Oradell, NJ",
      isFeatured: false,
      bio: "A true freshman on the 2005 team who became one of the most decorated linebackers in USC history. Cushing played nine NFL seasons with the Houston Texans.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NFL Player",
        location: "Houston, TX",
        statusNote:
          "Selected 15th overall by the Houston Texans in 2009, Cushing won the 2009 AP NFL Defensive Rookie of the Year award and became the Texans' all-time leading tackler over nine seasons. He was suspended twice for PED violations (2010, 2017). After retiring in 2018, he served as the Texans' assistant strength and conditioning coach from 2019 to 2020. He remains connected to the organization and resides in Houston.",
        sourceUrl: "https://en.wikipedia.org/wiki/Brian_Cushing",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 10,
        position: "Linebacker",
        yearsAtSchool: "2005-2008",
        statsNote: "True freshman in 2005 • Part of legendary USC LB corps with Rivers, Maualuga, Clay Matthews",
      },
      careerEvents: [
        { year: 2009, title: "Selected #15 overall by the Houston Texans", eventType: "DRAFT" },
        { year: 2009, title: "Won AP NFL Defensive Rookie of the Year", eventType: "AWARD" },
        { year: 2018, title: "Retired as Houston Texans all-time leading tackler", eventType: "RETIREMENT" },
        { year: 2019, title: "Became Texans assistant strength and conditioning coach", eventType: "CAREER" },
      ],
    },
    {
      slug: "sedrick-ellis",
      firstName: "Sedrick",
      lastName: "Ellis",
      birthYear: 1985,
      hometown: "Chino, CA",
      highSchool: "Chino High School, Chino, CA",
      isFeatured: false,
      bio: "A dominant defensive tackle and unanimous All-American who was the Pac-10 Defensive Player of the Year in 2007. Ellis anchored USC's defensive line during the 2005 season.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NFL Player",
        location: "Southern California",
        statusNote:
          "Selected 7th overall by the New Orleans Saints in 2008, Ellis started in Super Bowl XLIV, helping the Saints win their first championship. He retired abruptly in 2013 at age 28, walking away from a contract with the Chicago Bears. 'I was sick of football and football was sick of me,' he said in a 2015 interview. Since retirement he has embraced a life of travel, visiting Thailand, London, Brazil, and Mexico, and lives contentedly in Southern California.",
        sourceUrl: "https://en.wikipedia.org/wiki/Sedrick_Ellis",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 49,
        position: "Defensive Tackle",
        yearsAtSchool: "2004-2007",
        statsNote: "Unanimous All-American • Pac-10 Defensive Player of the Year 2007",
      },
      careerEvents: [
        { year: 2008, title: "Selected #7 overall by the New Orleans Saints", eventType: "DRAFT" },
        { year: 2010, title: "Won Super Bowl XLIV with the Saints", eventType: "CHAMPIONSHIP" },
        { year: 2013, title: "Abruptly retired at age 28 from the Chicago Bears", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "frostee-rucker",
      firstName: "Frostee",
      lastName: "Rucker",
      birthYear: 1983,
      hometown: "Tustin, CA",
      highSchool: "Tustin High School, Tustin, CA",
      isFeatured: false,
      bio: "A veteran defensive end who transferred from Colorado State and became a key contributor on USC's defensive line. Rucker played 13 NFL seasons across four teams.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "VP of Sports and Entertainment",
        currentEmployer: "Fortuna Investments",
        location: "Tustin, CA",
        statusNote:
          "Selected in the third round by the Cincinnati Bengals in 2006, Rucker had a remarkably long 13-year NFL career with the Bengals, Browns, Cardinals, and Raiders, appearing in 170 games with 21.5 career sacks. After retiring in 2018, he joined Fortuna Investments as Vice President of Sports and Entertainment. He also runs STAY READY, a youth football training program operating under Frostee's Challenge, his 501(c)(3) nonprofit providing athletic opportunities for underserved youth.",
        sourceUrl: "https://en.wikipedia.org/wiki/Frostee_Rucker",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 90,
        position: "Defensive End",
        yearsAtSchool: "2002-2005",
        statsNote: "First Team All-Pac-10 2005 • Transfer from Colorado State",
      },
      careerEvents: [
        { year: 2006, title: "Selected #91 overall by the Cincinnati Bengals", eventType: "DRAFT" },
        { year: 2018, title: "Retired after 13 NFL seasons and 170 games", eventType: "RETIREMENT" },
        { year: 2023, title: "Joined Fortuna Investments as VP of Sports and Entertainment", eventType: "CAREER" },
      ],
    },
    {
      slug: "winston-justice",
      firstName: "Winston",
      lastName: "Justice",
      birthYear: 1984,
      hometown: "Long Beach, CA",
      highSchool: "Long Beach Polytechnic High School, Long Beach, CA",
      isFeatured: false,
      bio: "A massive offensive tackle who protected Matt Leinart's blind side. Justice was a two-year starter at USC before entering the 2006 NFL Draft.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NFL Player",
        statusNote:
          "Selected in the second round by the Philadelphia Eagles in 2006, Justice played seven NFL seasons with the Eagles and Indianapolis Colts. He started 53 games and was known as a dependable pass protector. After retiring from the NFL, Justice has maintained a low public profile.",
        sourceUrl: "https://en.wikipedia.org/wiki/Winston_Justice",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 74,
        position: "Offensive Tackle",
        yearsAtSchool: "2003-2005",
        statsNote: "Two-year starter protecting Matt Leinart's blind side",
      },
      careerEvents: [
        { year: 2006, title: "Selected #39 overall by the Philadelphia Eagles", eventType: "DRAFT" },
        { year: 2012, title: "Final NFL season with the Indianapolis Colts", eventType: "CAREER" },
      ],
    },
    {
      slug: "sam-baker",
      firstName: "Sam",
      lastName: "Baker",
      birthYear: 1985,
      hometown: "Tustin, CA",
      highSchool: "Tustin High School, Tustin, CA",
      isFeatured: false,
      bio: "A dominant offensive tackle who started on the 2005 line as a sophomore. Baker went on to be a first-round NFL draft pick and started for the Atlanta Falcons.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NFL Player",
        location: "Southern California",
        statusNote:
          "Selected 21st overall by the Atlanta Falcons in 2008, Baker was a key starter on Atlanta's offensive line for five seasons. Chronic knee injuries forced him out of the league after 2013 despite starting 59 games. Since retirement, Baker has maintained a private life in Southern California.",
        sourceUrl: "https://en.wikipedia.org/wiki/Sam_Baker_(offensive_tackle)",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 72,
        position: "Offensive Tackle",
        yearsAtSchool: "2004-2007",
        statsNote: "Started as sophomore on 2005 line • First-round pick",
      },
      careerEvents: [
        { year: 2008, title: "Selected #21 overall by the Atlanta Falcons", eventType: "DRAFT" },
        { year: 2013, title: "Retired from the NFL due to chronic knee injuries", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "lawrence-jackson",
      firstName: "Lawrence",
      lastName: "Jackson",
      birthYear: 1985,
      hometown: "Inglewood, CA",
      highSchool: "Morningside High School, Inglewood, CA",
      isFeatured: false,
      bio: "An explosive pass rusher who developed into one of the Pac-10's top defensive ends during his time at USC. Jackson had 8 sacks in his senior season.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NFL Player",
        statusNote:
          "Selected in the first round (28th overall) by the Seattle Seahawks in 2008, Jackson played four NFL seasons with Seattle and Detroit. He recorded 10.5 career sacks before leaving the league in 2012. Since retirement, he has maintained a quiet private life.",
        sourceUrl: "https://en.wikipedia.org/wiki/Lawrence_Jackson_(American_football)",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 86,
        position: "Defensive End",
        yearsAtSchool: "2004-2007",
        statsNote: "8 sacks in senior season • First-round pick",
      },
      careerEvents: [
        { year: 2008, title: "Selected #28 overall by the Seattle Seahawks", eventType: "DRAFT" },
        { year: 2012, title: "Final NFL season with the Detroit Lions", eventType: "CAREER" },
      ],
    },
    // ── Batch 3: Role Players & Coaches ──────────────────────────────────────
    {
      slug: "darnell-bing",
      firstName: "Darnell",
      lastName: "Bing",
      birthYear: 1984,
      hometown: "Los Angeles, CA",
      highSchool: "Manual Arts High School, Los Angeles, CA",
      isFeatured: false,
      bio: "A hard-hitting safety who was one of the most highly recruited players in the country coming out of high school. Bing was a key contributor in USC's secondary.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Citizen",
        statusNote:
          "Bing went undrafted after the 2006 NFL Draft and had brief stints with the Oakland Raiders and Arizona Cardinals before leaving professional football. He has maintained a very low public profile since retiring from football and is believed to reside in the Los Angeles area.",
        sourceUrl: "https://en.wikipedia.org/wiki/Darnell_Bing",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 27,
        position: "Safety",
        yearsAtSchool: "2003-2005",
        statsNote: "Key starter in secondary • Originally recruited as WR/ATH",
      },
      careerEvents: [
        { year: 2006, title: "Went undrafted; signed as free agent with Oakland Raiders", eventType: "SIGNING" },
      ],
    },
    {
      slug: "oscar-lua",
      firstName: "Oscar",
      lastName: "Lua",
      birthYear: 1983,
      hometown: "Indio, CA",
      highSchool: "Indio High School, Indio, CA",
      isFeatured: false,
      bio: "A reliable inside linebacker who was a four-year contributor at USC. Lua was a steady tackler and leader on the defensive side of the ball.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Citizen",
        statusNote:
          "Lua went undrafted in 2006 and had a brief stint with the Cleveland Browns before his professional football career ended. He returned to Southern California and has maintained a private life since leaving the sport. Limited public information is available about his post-football career.",
        sourceUrl: "https://usctrojans.com/sports/football/roster/oscar-lua/1734",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 46,
        position: "Inside Linebacker",
        yearsAtSchool: "2002-2005",
        statsNote: "Four-year contributor • Steady tackler and defensive leader",
      },
      careerEvents: [
        { year: 2006, title: "Went undrafted; brief stint with Cleveland Browns", eventType: "SIGNING" },
      ],
    },
    {
      slug: "david-kirtman",
      firstName: "David",
      lastName: "Kirtman",
      birthYear: 1983,
      hometown: "Oceanside, CA",
      highSchool: "El Camino High School, Oceanside, CA",
      isFeatured: false,
      bio: "A bruising fullback who served as the lead blocker for Reggie Bush and LenDale White. Kirtman was a selfless player who made the ground game go.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Citizen",
        statusNote:
          "Kirtman went undrafted after the 2006 draft and had a brief NFL stint with the San Diego Chargers. He later played in NFL Europe for the Hamburg Sea Devils. After leaving football, Kirtman returned to Southern California and has kept a low profile.",
        sourceUrl: "https://en.wikipedia.org/wiki/David_Kirtman",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 40,
        position: "Fullback",
        yearsAtSchool: "2002-2005",
        statsNote: "Lead blocker for Bush and White • Key contributor to USC's rushing attack",
      },
      careerEvents: [
        { year: 2006, title: "Went undrafted; signed as free agent with San Diego Chargers", eventType: "SIGNING" },
      ],
    },
    {
      slug: "josh-pinkard",
      firstName: "Josh",
      lastName: "Pinkard",
      birthYear: 1983,
      hometown: "Copperas Cove, TX",
      highSchool: "Copperas Cove High School, Copperas Cove, TX",
      isFeatured: false,
      bio: "A physical cornerback who was a key member of USC's secondary in the 2005 season. Pinkard provided reliable coverage on the outside.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Citizen",
        statusNote:
          "Pinkard went undrafted in 2006 and was signed by the Houston Texans as an undrafted free agent. He appeared in 15 games for Houston before being released. After a brief professional career, he stepped away from football and has maintained a low public profile.",
        sourceUrl: "https://en.wikipedia.org/wiki/Josh_Pinkard",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 19,
        position: "Cornerback",
        yearsAtSchool: "2002-2005",
        statsNote: "Starting cornerback in 2005 secondary",
      },
      careerEvents: [
        { year: 2006, title: "Signed as undrafted free agent with Houston Texans", eventType: "SIGNING" },
      ],
    },
    // ── Coaches ──────────────────────────────────────────────────────────────
    {
      slug: "pete-carroll",
      firstName: "Pete",
      lastName: "Carroll",
      birthYear: 1951,
      hometown: "San Francisco, CA",
      highSchool: "Redwood High School, Larkspur, CA",
      isFeatured: true,
      bio: "One of three coaches to win both a Super Bowl and a college national championship. Carroll built USC into a dynasty, going 97-19 from 2001-2009 with two national titles and seven straight Pac-10 championships.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Former Head Coach",
        location: "Los Angeles, CA",
        statusNote:
          "After transforming USC into a powerhouse (97-19 from 2001-2009, two national titles), Carroll left for the Seattle Seahawks where he won Super Bowl XLVIII in 2014. He coached the Seahawks for 14 seasons (2010-2023) before transitioning to an advisory role. In 2025 he was hired as Las Vegas Raiders head coach but was fired after a disastrous 3-14 season in January 2026. He is currently out of coaching and was announced as the 2026 commencement speaker for USC's Marshall School of Business.",
        sourceUrl: "https://en.wikipedia.org/wiki/Pete_Carroll",
      },
      membership: {
        role: "HEAD_COACH",
        position: "Head Coach",
        yearsAtSchool: "2001-2009",
        statsNote: "97-19 at USC • 2 National Championships (2003, 2004) • 7 straight Pac-10 titles",
      },
      careerEvents: [
        { year: 2004, title: "Won BCS National Championship (USC vs Oklahoma)", eventType: "CHAMPIONSHIP" },
        { year: 2005, title: "Lost BCS National Championship Game to Texas 41-38", eventType: "CHAMPIONSHIP" },
        { year: 2010, title: "Left USC to become Seattle Seahawks head coach", eventType: "CAREER" },
        { year: 2014, title: "Won Super Bowl XLVIII with the Seattle Seahawks", eventType: "CHAMPIONSHIP" },
        { year: 2025, title: "Hired as Las Vegas Raiders head coach", eventType: "CAREER" },
        { year: 2026, title: "Fired by Raiders after 3-14 season", eventType: "CAREER" },
      ],
    },
    {
      slug: "lane-kiffin",
      firstName: "Lane",
      lastName: "Kiffin",
      birthYear: 1975,
      hometown: "Lincoln, NE",
      highSchool: "Jefferson High School, Bloomington, MN",
      isFeatured: true,
      bio: "The offensive coordinator who designed the plays for Leinart, Bush, and White. Kiffin's creative playcalling helped USC's offense rank among the nation's best.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Football Coach",
        currentEmployer: "LSU Tigers",
        location: "Baton Rouge, LA",
        statusNote:
          "After serving as USC's offensive coordinator (2005-2006), Kiffin became the youngest head coach in NFL history with the Oakland Raiders at age 31. He later served as head coach at Tennessee and USC before building Ole Miss into a powerhouse (55-19 over six seasons). In November 2025, he controversially left Ole Miss mid-season for LSU, signing a seven-year, $91 million deal. He is now preparing for his first season as LSU's head coach in 2026.",
        sourceUrl: "https://en.wikipedia.org/wiki/Lane_Kiffin",
      },
      membership: {
        role: "ASSISTANT_COACH",
        position: "Offensive Coordinator",
        yearsAtSchool: "2001-2006",
        statsNote: "OC who designed offense for Leinart, Bush, and White",
      },
      careerEvents: [
        { year: 2007, title: "Named Oakland Raiders head coach at age 31 (youngest in NFL history)", eventType: "CAREER" },
        { year: 2010, title: "Became USC head coach", eventType: "CAREER" },
        { year: 2013, title: "Fired by USC midseason, famously dismissed on the tarmac at LAX", eventType: "CAREER" },
        { year: 2017, title: "Named Florida Atlantic head coach; won C-USA title", eventType: "CAREER" },
        { year: 2020, title: "Named Ole Miss head coach", eventType: "CAREER" },
        { year: 2025, title: "Left Ole Miss for LSU, signing $91M deal", eventType: "CAREER" },
      ],
    },
    {
      slug: "nick-holt",
      firstName: "Nick",
      lastName: "Holt",
      birthYear: 1962,
      hometown: "Stockton, CA",
      highSchool: "Stagg High School, Stockton, CA",
      isFeatured: false,
      bio: "A longtime defensive coach who served multiple stints at USC. Holt was USC's linebackers coach from 2001-2003 and returned as defensive coordinator from 2006-2008, bookending the 2005 season.",
      status: {
        occupationType: "COACH",
        currentTitle: "Associate Head Coach / Co-DC / DL Coach",
        currentEmployer: "Abilene Christian University",
        location: "Abilene, TX",
        statusNote:
          "After serving as USC's linebackers coach (2001-2003) and defensive coordinator (2006-2008), Holt had a journeyman coaching career spanning Idaho (head coach), Washington (DC), USC, Purdue (DC), Italian football, and Texas Tech (analyst). Since 2022, he has served as associate head coach, co-defensive coordinator, and defensive line coach at Abilene Christian University, helping the Wildcats to a 9-5 season and FCS playoff berth in 2024. Notably, his maternal grandfather was Olympic swimmer and actor Buster Crabbe.",
        sourceUrl: "https://en.wikipedia.org/wiki/Nick_Holt",
      },
      membership: {
        role: "ASSISTANT_COACH",
        position: "Linebackers Coach (2001-03) / Defensive Coordinator (2006-08)",
        yearsAtSchool: "2001-2003, 2006-2008",
        statsNote: "Two stints at USC • Coached USC's #2 overall defense in 2008",
      },
      careerEvents: [
        { year: 2004, title: "Named head coach at University of Idaho", eventType: "CAREER" },
        { year: 2006, title: "Returned to USC as defensive coordinator", eventType: "CAREER" },
        { year: 2009, title: "Named Washington defensive coordinator", eventType: "CAREER" },
        { year: 2022, title: "Joined Abilene Christian as associate head coach and co-DC", eventType: "CAREER" },
      ],
    },
  ],
};
