import type { TeamSeed } from "./types";

export const uscFootball2005: TeamSeed = {
  slug: "usc-football-2005",
  name: "USC Trojans",
  season: "2005-2006",
  sport: "Football",
  school: "University of Southern California",
  conference: "Pac-10",
  accomplishment: "BCS National Championship Game Appearance (12-1)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/30.png",
  mascotName: "Traveler",
  people: [
    // ── Batch 1: Star Players ────────────────────────────────────────────────
    {
      slug: "matt-leinart",
      firstName: "Matt",
      lastName: "Leinart",
      birthYear: 1983,
      hometown: "Santa Ana, CA",
      highSchool: "Mater Dei High School, Santa Ana, CA",
      isFeatured: true,
      bio: "The 2004 Heisman Trophy-winning quarterback who led USC to consecutive BCS National Championship Games. Leinart chose to return for his senior year in 2005 and threw for 3,815 yards and 28 TDs.",
      status: {
        occupationType: "BROADCASTER_ANALYST",
        currentTitle: "College Football Analyst",
        currentEmployer: "Fox Sports",
        location: "Los Angeles, CA",
        statusNote:
          "After a seven-year NFL career spent mostly with the Arizona Cardinals, Leinart transitioned to broadcasting in 2014 and is now an analyst on Fox Sports' Big Noon Kickoff college football pregame show. He is also an active real estate investor in the Los Angeles market and runs the Matt Leinart Foundation, which creates athletic opportunities for underprivileged youth. He married actress Josie Loren in 2018 and the couple have two children, including a daughter born in February 2025.",
        sourceUrl: "https://en.wikipedia.org/wiki/Matt_Leinart",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 11,
        position: "Quarterback",
        yearsAtSchool: "2001-2005",
        statsNote: "2004 Heisman Trophy • 3,815 yds, 28 TD, 8 INT in 2005 • 37-2 career record as starter", gamesPlayed: 13,
      },
            seasonStats: [
        { level: "COLLEGE", teamName: "USC Trojans", season: "2003", yearLabel: "Sophomore (National Champion)", sortOrder: 102, gamesPlayed: 13, pointsPerGame: 3556, reboundsPerGame: 38, assistsPerGame: 9, stealsPerGame: 383, fieldGoalPct: 0.666, tournamentResult: "255/383 passing, 3,556 yds, 38 TD, 9 INT" },
        { level: "COLLEGE", teamName: "USC Trojans", season: "2004", yearLabel: "Junior (Heisman)", sortOrder: 103, gamesPlayed: 13, pointsPerGame: 3322, reboundsPerGame: 33, assistsPerGame: 6, stealsPerGame: 412, fieldGoalPct: 0.701, tournamentResult: "289/412 passing, 3,322 yds, 33 TD, 6 INT" },
        { level: "COLLEGE", teamName: "USC Trojans", season: "2005", yearLabel: "Senior", sortOrder: 104, gamesPlayed: 12, pointsPerGame: 3815, reboundsPerGame: 28, assistsPerGame: 8, stealsPerGame: 360, fieldGoalPct: 0.656, tournamentResult: "236/360 passing, 3,815 yds, 28 TD, 8 INT" },
        { level: "PROFESSIONAL", teamName: "Arizona Cardinals", season: "2006", yearLabel: "2006 (Rookie)", sortOrder: 301, gamesPlayed: 11, pointsPerGame: 2547, reboundsPerGame: 11, assistsPerGame: 12, stealsPerGame: 377, fieldGoalPct: 0.568, tournamentResult: "214/377 passing, 2,547 yds, 11 TD, 12 INT" },
        { level: "PROFESSIONAL", teamName: "Arizona Cardinals", season: "2007", yearLabel: "2007", sortOrder: 302, gamesPlayed: 5, pointsPerGame: 396, reboundsPerGame: 2, assistsPerGame: 4, stealsPerGame: 67, fieldGoalPct: 0.597, tournamentResult: "40/67 passing, 396 yds, 2 TD, 4 INT" },
        { level: "PROFESSIONAL", teamName: "Arizona Cardinals", season: "2009", yearLabel: "2009", sortOrder: 304, gamesPlayed: 6, pointsPerGame: 500, reboundsPerGame: 2, assistsPerGame: 3, stealsPerGame: 72, fieldGoalPct: 0.597, tournamentResult: "43/72 passing, 500 yds, 2 TD, 3 INT" },
      ],
      careerEvents: [
        { year: 2004, title: "Won Heisman Trophy", eventType: "AWARD" },
        { year: 2005, title: "BCS National Championship Game vs Texas (lost 41-38)", eventType: "CHAMPIONSHIP" },
        { year: 2006, title: "Selected #10 overall by the Arizona Cardinals", eventType: "DRAFT" },
        { year: 2012, title: "Played final NFL season with Oakland Raiders", eventType: "CAREER" },
        { year: 2014, title: "Joined Fox Sports as college football analyst", eventType: "CAREER" },
      ],
    },
    {
      slug: "reggie-bush",
      firstName: "Reggie",
      lastName: "Bush",
      birthYear: 1985,
      hometown: "La Mesa, CA",
      highSchool: "Helix High School, La Mesa, CA",
      isFeatured: true,
      bio: "One of the most electrifying college football players ever, Bush won the 2005 Heisman Trophy (vacated in 2010, restored in 2024). He rushed for 1,740 yards and had 478 receiving yards in 2005.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NFL Player / Media Personality",
        location: "Los Angeles, CA",
        statusNote:
          "Selected 2nd overall by the New Orleans Saints in 2006, Bush won Super Bowl XLIV in 2010 and played 11 NFL seasons with six teams before retiring in 2017. His Heisman Trophy was controversially vacated in 2010 but officially restored in April 2024 amid the NIL era. He served as Fox Sports analyst on Big Noon Kickoff (2019-2023) before parting ways over contract disagreements. Now actively pursuing a defamation lawsuit against the NCAA over being 'labeled a cheater,' and a separate NIL compensation lawsuit against USC, the Pac-12, and the NCAA.",
        sourceUrl: "https://en.wikipedia.org/wiki/Reggie_Bush",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 5,
        position: "Running Back",
        yearsAtSchool: "2003-2005",
        statsNote: "2005 Heisman Trophy • 1,740 rush yds, 16 TD • 478 rec yds in 2005", gamesPlayed: 13,
      },
            seasonStats: [
        { level: "COLLEGE", teamName: "USC Trojans", season: "2003", yearLabel: "Freshman", sortOrder: 101, gamesPlayed: 13, pointsPerGame: 521, reboundsPerGame: 8, assistsPerGame: 15, tournamentResult: "521 rush yds, 8 TD, 15 rec" },
        { level: "COLLEGE", teamName: "USC Trojans", season: "2004", yearLabel: "Sophomore", sortOrder: 102, gamesPlayed: 13, pointsPerGame: 908, reboundsPerGame: 9, assistsPerGame: 37, tournamentResult: "908 rush yds, 9 TD, 37 rec" },
        { level: "COLLEGE", teamName: "USC Trojans", season: "2005", yearLabel: "Junior (Heisman)", sortOrder: 103, gamesPlayed: 12, pointsPerGame: 1740, reboundsPerGame: 16, assistsPerGame: 37, tournamentResult: "1,740 rush yds, 16 TD, 37 rec, 478 rec yds" },
        { level: "PROFESSIONAL", teamName: "New Orleans Saints", season: "2006", yearLabel: "2006 (Rookie)", sortOrder: 301, gamesPlayed: 16, pointsPerGame: 565, reboundsPerGame: 6, assistsPerGame: 88, tournamentResult: "565 rush yds, 6 TD, 88 rec" },
        { level: "PROFESSIONAL", teamName: "New Orleans Saints", season: "2009", yearLabel: "2009 (Super Bowl Champion)", sortOrder: 304, gamesPlayed: 14, pointsPerGame: 390, reboundsPerGame: 5, assistsPerGame: 47, tournamentResult: "390 rush yds, 5 TD, 47 rec" },
        { level: "PROFESSIONAL", teamName: "Miami Dolphins", season: "2011", yearLabel: "2011", sortOrder: 306, gamesPlayed: 15, pointsPerGame: 1086, reboundsPerGame: 6, assistsPerGame: 43, tournamentResult: "1,086 rush yds, 6 TD, 43 rec" },
        { level: "PROFESSIONAL", teamName: "Miami Dolphins", season: "2012", yearLabel: "2012", sortOrder: 307, gamesPlayed: 16, pointsPerGame: 986, reboundsPerGame: 6, assistsPerGame: 35, tournamentResult: "986 rush yds, 6 TD, 35 rec" },
        { level: "PROFESSIONAL", teamName: "Detroit Lions", season: "2013", yearLabel: "2013", sortOrder: 308, gamesPlayed: 14, pointsPerGame: 506, reboundsPerGame: 3, assistsPerGame: 54, tournamentResult: "506 rush yds, 3 TD, 54 rec" },
      ],
      careerEvents: [
        { year: 2005, title: "Won Heisman Trophy (later vacated, restored 2024)", eventType: "AWARD" },
        { year: 2006, title: "Selected #2 overall by the New Orleans Saints", eventType: "DRAFT" },
        { year: 2010, title: "Won Super Bowl XLIV with the Saints", eventType: "CHAMPIONSHIP" },
        { year: 2010, title: "Heisman Trophy vacated due to NCAA violations", eventType: "OTHER" },
        { year: 2017, title: "Retired from the NFL after 11 seasons", eventType: "RETIREMENT" },
        { year: 2024, title: "Heisman Trophy officially restored", eventType: "AWARD" },
      ],
    },
    {
      slug: "lendale-white",
      firstName: "LenDale",
      lastName: "White",
      birthYear: 1984,
      hometown: "Denver, CO",
      highSchool: "Chatfield Senior High School, Littleton, CO",
      isFeatured: false,
      bio: "The powerful complement to Reggie Bush in USC's backfield, White rushed for 1,302 yards and 24 touchdowns in 2005. Known as 'Thunder' to Bush's 'Lightning.'",
      status: {
        occupationType: "BROADCASTER_ANALYST",
        currentTitle: "Podcast Co-Host / Media Personality",
        currentEmployer: "Smash & Dash Podcast (Bleav Network)",
        location: "Denver, CO",
        statusNote:
          "Selected in the second round by the Tennessee Titans in 2006, White rushed for 15 TDs in 2008 as part of the famed 'Smash & Dash' duo with Chris Johnson. A torn Achilles in 2010 preseason with Denver ended his playing career. After battling depression and substance abuse issues, White rebuilt his life with support from Johnson. He now co-hosts the Smash & Dash podcast with Johnson and resides in Denver.",
        sourceUrl: "https://en.wikipedia.org/wiki/LenDale_White",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 25,
        position: "Running Back",
        yearsAtSchool: "2003-2005",
        statsNote: "1,302 rush yds, 24 TD in 2005 • 2,624 career rush yds at USC", gamesPlayed: 13,
      },
            seasonStats: [
        { level: "COLLEGE", teamName: "USC Trojans", season: "2003", yearLabel: "Freshman", sortOrder: 101, gamesPlayed: 13, pointsPerGame: 412, reboundsPerGame: 6, tournamentResult: "412 rush yds, 6 TD" },
        { level: "COLLEGE", teamName: "USC Trojans", season: "2004", yearLabel: "Sophomore", sortOrder: 102, gamesPlayed: 13, pointsPerGame: 1136, reboundsPerGame: 15, tournamentResult: "1,136 rush yds, 15 TD" },
        { level: "COLLEGE", teamName: "USC Trojans", season: "2005", yearLabel: "Junior", sortOrder: 103, gamesPlayed: 12, pointsPerGame: 1302, reboundsPerGame: 24, tournamentResult: "1,302 rush yds, 24 TD" },
        { level: "PROFESSIONAL", teamName: "Tennessee Titans", season: "2006", yearLabel: "2006", sortOrder: 301, gamesPlayed: 14, pointsPerGame: 244, reboundsPerGame: 2, tournamentResult: "244 rush yds, 2 TD" },
        { level: "PROFESSIONAL", teamName: "Tennessee Titans", season: "2007", yearLabel: "2007", sortOrder: 302, gamesPlayed: 16, pointsPerGame: 1110, reboundsPerGame: 7, tournamentResult: "1,110 rush yds, 7 TD" },
        { level: "PROFESSIONAL", teamName: "Tennessee Titans", season: "2008", yearLabel: "2008 (Smash & Dash)", sortOrder: 303, gamesPlayed: 16, pointsPerGame: 773, reboundsPerGame: 15, tournamentResult: "773 rush yds, 15 TD" },
      ],
      careerEvents: [
        { year: 2006, title: "Selected #45 overall by the Tennessee Titans", eventType: "DRAFT" },
        { year: 2008, title: "Rushed for 15 TDs as part of 'Smash & Dash' with Chris Johnson", eventType: "CAREER" },
        { year: 2010, title: "Torn Achilles ended NFL career during Denver Broncos preseason", eventType: "INJURY" },
      ],
    },
    {
      slug: "dwayne-jarrett",
      firstName: "Dwayne",
      lastName: "Jarrett",
      birthYear: 1986,
      hometown: "New Brunswick, NJ",
      highSchool: "New Brunswick High School, New Brunswick, NJ",
      isFeatured: false,
      bio: "A two-time All-American wide receiver who was Leinart's top target, Jarrett caught 91 passes for 1,274 yards and 16 TDs in 2005.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Entrepreneur",
        location: "Southern California",
        statusNote:
          "USC's all-time receptions leader (216) and Pac-10 all-time TD receptions leader (41), Jarrett was drafted 45th overall by the Panthers in 2007 but struggled in the NFL (35 career catches). Two DUI arrests led to his release in 2010, and a brief CFL stint in 2012 ended his career at 25. LinkedIn profiles suggest he may be involved in media production (AVI Media LLC) or entrepreneurship (Fast&Curious36), though specifics are unconfirmed. He maintains an Instagram presence (@dwaynejarrett_) and appears to reside in the Los Angeles area.",
        sourceUrl: "https://en.wikipedia.org/wiki/Dwayne_Jarrett",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 8,
        position: "Wide Receiver",
        yearsAtSchool: "2004-2006",
        statsNote: "Two-time All-American • 91 rec, 1,274 yds, 16 TD in 2005", gamesPlayed: 13,
      },
            seasonStats: [
        { level: "COLLEGE", teamName: "USC Trojans", season: "2004", yearLabel: "Freshman", sortOrder: 101, gamesPlayed: 13, pointsPerGame: 56, reboundsPerGame: 1029, assistsPerGame: 9, tournamentResult: "56 rec, 1,029 yds, 9 TD" },
        { level: "COLLEGE", teamName: "USC Trojans", season: "2005", yearLabel: "Sophomore", sortOrder: 102, gamesPlayed: 12, pointsPerGame: 91, reboundsPerGame: 1274, assistsPerGame: 16, tournamentResult: "91 rec, 1,274 yds, 16 TD" },
        { level: "COLLEGE", teamName: "USC Trojans", season: "2006", yearLabel: "Junior", sortOrder: 103, gamesPlayed: 13, pointsPerGame: 64, reboundsPerGame: 1060, assistsPerGame: 11, tournamentResult: "64 rec, 1,060 yds, 11 TD" },
      ],
      careerEvents: [
        { year: 2007, title: "Selected #45 overall by the Carolina Panthers", eventType: "DRAFT" },
        { year: 2010, title: "Released by Panthers after second DUI arrest", eventType: "OTHER" },
        { year: 2012, title: "Brief CFL stint with Saskatchewan Roughriders before retiring", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "steve-smith-usc",
      firstName: "Steve",
      lastName: "Smith",
      birthYear: 1985,
      hometown: "Anchorage, AK",
      highSchool: "Taft High School, Woodland Hills, CA",
      isFeatured: false,
      bio: "A reliable possession receiver who caught 63 passes for 959 yards and 6 TDs in 2005. His brother Malcolm Smith later won Super Bowl MVP with Seattle.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Co-Owner",
        currentEmployer: "Xplode Training Center",
        location: "San Fernando Valley, CA",
        statusNote:
          "Selected in the second round by the New York Giants in 2007, Smith had a Pro Bowl-caliber 2009 season with 107 catches. He played six NFL seasons with the Giants, Eagles, Rams, and Buccaneers before retiring in 2013. He now co-owns Xplode Training Center in Chatsworth, CA, specializing in youth football training camps and skill development programs. His brother Malcolm Smith won Super Bowl XLVIII MVP with the Seattle Seahawks.",
        sourceUrl: "https://en.wikipedia.org/wiki/Steve_Smith_(wide_receiver,_born_1985)",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 2,
        position: "Wide Receiver",
        yearsAtSchool: "2003-2006",
        statsNote: "63 rec, 959 yds, 6 TD in 2005 • All-American", gamesPlayed: 13,
      },
            seasonStats: [
        { level: "COLLEGE", teamName: "USC Trojans", season: "2004", yearLabel: "Junior", sortOrder: 102, gamesPlayed: 13, pointsPerGame: 49, reboundsPerGame: 635, assistsPerGame: 3, tournamentResult: "49 rec, 635 yds, 3 TD" },
        { level: "COLLEGE", teamName: "USC Trojans", season: "2005", yearLabel: "Senior", sortOrder: 103, gamesPlayed: 12, pointsPerGame: 63, reboundsPerGame: 959, assistsPerGame: 6, tournamentResult: "63 rec, 959 yds, 6 TD" },
        { level: "PROFESSIONAL", teamName: "New York Giants", season: "2007", yearLabel: "2007", sortOrder: 301, gamesPlayed: 10, pointsPerGame: 11, reboundsPerGame: 108, assistsPerGame: 0, tournamentResult: "11 rec, 108 yds, 0 TD" },
        { level: "PROFESSIONAL", teamName: "New York Giants", season: "2009", yearLabel: "2009 (Pro Bowl alt)", sortOrder: 303, gamesPlayed: 16, pointsPerGame: 107, reboundsPerGame: 1220, assistsPerGame: 7, tournamentResult: "107 rec, 1,220 yds, 7 TD" },
        { level: "PROFESSIONAL", teamName: "Philadelphia Eagles", season: "2011", yearLabel: "2011", sortOrder: 305, gamesPlayed: 15, pointsPerGame: 11, reboundsPerGame: 124, assistsPerGame: 0, tournamentResult: "11 rec, 124 yds, 0 TD" },
      ],
      careerEvents: [
        { year: 2007, title: "Selected #51 overall by the New York Giants", eventType: "DRAFT" },
        { year: 2009, title: "Pro Bowl alternate season: 107 receptions, 1,220 yards", eventType: "CAREER" },
        { year: 2013, title: "Retired from the NFL after six seasons", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "keith-rivers",
      firstName: "Keith",
      lastName: "Rivers",
      birthYear: 1986,
      hometown: "Lake Mary, FL",
      highSchool: "Lake Mary High School, Lake Mary, FL",
      isFeatured: true,
      bio: "A dominant linebacker who wore the prestigious USC #55 jersey, Rivers had 240 career tackles including 18.5 for losses. A true freshman starter on the 2005 team.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Art Collector and Curator",
        location: "Los Angeles, CA",
        statusNote:
          "Selected 9th overall by the Cincinnati Bengals in 2008, Rivers played seven NFL seasons with the Bengals, Giants, and Bills before retiring in 2015. He then pivoted into an extraordinary second career as a fine art collector and curator. His collection includes works by Andy Warhol, Barbara Kruger, Kerry James Marshall, and Kara Walker. He sits on the boards of the Hirshhorn and Hammer museums and curated the 2022 exhibition 'Courage Before Expectation' at New York's Flag Art Foundation.",
        sourceUrl: "https://www.1stdibs.com/introspective-magazine/keith-rivers/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 55,
        position: "Linebacker",
        yearsAtSchool: "2004-2007",
        statsNote: "Wore USC's prestigious #55 • 240 career tackles, 18.5 TFL", gamesPlayed: 13,
      },
            seasonStats: [
        { level: "COLLEGE", teamName: "USC Trojans", season: "2005", yearLabel: "Sophomore", sortOrder: 102, gamesPlayed: 13, pointsPerGame: 80, tournamentResult: "80 tackles, 7 TFL" },
        { level: "COLLEGE", teamName: "USC Trojans", season: "2006", yearLabel: "Junior", sortOrder: 103, gamesPlayed: 13, pointsPerGame: 81, tournamentResult: "81 tackles, 10 TFL" },
        { level: "COLLEGE", teamName: "USC Trojans", season: "2007", yearLabel: "Senior", sortOrder: 104, gamesPlayed: 13, pointsPerGame: 79, reboundsPerGame: 1.5, tournamentResult: "79 tackles, 1.5 sacks" },
        { level: "PROFESSIONAL", teamName: "Cincinnati Bengals", season: "2008", yearLabel: "2008 (#9 pick, broken jaw)", sortOrder: 301, gamesPlayed: 7, pointsPerGame: 24, tournamentResult: "24 tackles (broken jaw, Hines Ward block)" },
        { level: "PROFESSIONAL", teamName: "Cincinnati Bengals", season: "2010", yearLabel: "2010", sortOrder: 303, gamesPlayed: 15, pointsPerGame: 55, tournamentResult: "55 tackles" },
        { level: "PROFESSIONAL", teamName: "New York Giants", season: "2012", yearLabel: "2012", sortOrder: 305, gamesPlayed: 16, pointsPerGame: 52, tournamentResult: "52 tackles" },
      ],
      careerEvents: [
        { year: 2008, title: "Selected #9 overall by the Cincinnati Bengals", eventType: "DRAFT" },
        { year: 2015, title: "Retired from the NFL after seven seasons", eventType: "RETIREMENT" },
        { year: 2015, title: "Began collecting fine art; first purchase was an Andy Warhol", eventType: "CAREER" },
        { year: 2022, title: "Curated 'Courage Before Expectation' at Flag Art Foundation, NYC", eventType: "CAREER" },
      ],
    },
    {
      slug: "rey-maualuga",
      firstName: "Rey",
      lastName: "Maualuga",
      birthYear: 1987,
      hometown: "Eureka, CA",
      highSchool: "Eureka High School, Eureka, CA",
      isFeatured: false,
      bio: "A ferocious linebacker and unanimous First-Team All-American in 2008, Maualuga was USC's only Bednarik Award winner. He played in four consecutive Rose Bowls and was the 2008 Rose Bowl Defensive MVP.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired / Full-Time Father",
        location: "Cincinnati, OH",
        statusNote:
          "Selected in the second round by the Cincinnati Bengals in 2009, Maualuga spent eight seasons as a Bengals starter, accumulating 607 career tackles. After a brief 2017 stint with the Dolphins, his career ended amid multiple off-field incidents including several DUI arrests. After a 2021 arrest, he entered a substance abuse program and achieved sobriety. He now focuses on raising his four children, has lost significant weight after peaking at 380 pounds, and was named to the Polynesian Football Hall of Fame Class of 2026.",
        sourceUrl: "https://247sports.com/college/usc/article/usc-football-column-dan-weber-just-sayin-former-linebacker-rey-maualuga-sobriety-fatherhood-253023556/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 58,
        position: "Linebacker",
        yearsAtSchool: "2005-2008",
        statsNote: "Bednarik Award winner • Unanimous All-American • 4 Rose Bowls • 2008 Rose Bowl Defensive MVP", gamesPlayed: 13,
      },
            seasonStats: [
        { level: "COLLEGE", teamName: "USC Trojans", season: "2005", yearLabel: "Freshman", sortOrder: 101, gamesPlayed: 13, tournamentResult: "Limited role as true freshman" },
        { level: "COLLEGE", teamName: "USC Trojans", season: "2006", yearLabel: "Sophomore", sortOrder: 102, gamesPlayed: 13, pointsPerGame: 74, reboundsPerGame: 6.5, tournamentResult: "74 tackles, 6.5 sacks" },
        { level: "COLLEGE", teamName: "USC Trojans", season: "2007", yearLabel: "Junior (Rose Bowl Def. MVP)", sortOrder: 103, gamesPlayed: 14, pointsPerGame: 92, reboundsPerGame: 7.0, tournamentResult: "92 tackles, 7.0 sacks" },
        { level: "COLLEGE", teamName: "USC Trojans", season: "2008", yearLabel: "Senior (Bednarik Award)", sortOrder: 104, gamesPlayed: 13, pointsPerGame: 86, reboundsPerGame: 3.5, tournamentResult: "86 tackles, 3.5 sacks (unanimous All-American)" },
        { level: "PROFESSIONAL", teamName: "Cincinnati Bengals", season: "2009", yearLabel: "2009", sortOrder: 301, gamesPlayed: 16, pointsPerGame: 63, tournamentResult: "63 tackles" },
        { level: "PROFESSIONAL", teamName: "Cincinnati Bengals", season: "2012", yearLabel: "2012", sortOrder: 304, gamesPlayed: 16, pointsPerGame: 83, tournamentResult: "83 tackles" },
        { level: "PROFESSIONAL", teamName: "Cincinnati Bengals", season: "2015", yearLabel: "2015", sortOrder: 307, gamesPlayed: 16, pointsPerGame: 52, tournamentResult: "52 tackles" },
      ],
      careerEvents: [
        { year: 2009, title: "Selected #38 overall by the Cincinnati Bengals", eventType: "DRAFT" },
        { year: 2017, title: "Final NFL season with the Miami Dolphins", eventType: "CAREER" },
        { year: 2023, title: "Achieved sobriety and became full-time father", eventType: "OTHER" },
        { year: 2026, title: "Named to Polynesian Football Hall of Fame Class of 2026", eventType: "AWARD" },
      ],
    },
    // ── Batch 2: Defensive Stars & Linemen ───────────────────────────────────
    {
      slug: "brian-cushing",
      firstName: "Brian",
      lastName: "Cushing",
      birthYear: 1987,
      hometown: "Park Ridge, NJ",
      highSchool: "Bergen Catholic High School, Oradell, NJ",
      isFeatured: false,
      bio: "A true freshman on the 2005 team who became one of the most decorated linebackers in USC history. Cushing played nine NFL seasons with the Houston Texans.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Founder / Community Leader",
        currentEmployer: "TACT Group (Cushing's Crusaders)",
        location: "Houston, TX",
        statusNote:
          "Selected 15th overall by the Houston Texans in 2009, Cushing won AP Defensive Rookie of the Year and became the franchise's all-time leading tackler over nine seasons. After retiring in 2018, he served as the Texans' assistant S&C coach (2019-2020). He now runs his TACT Group (also known as Cushing's Crusaders), a community-focused organization partnering with the Texans for charitable events. He also works as a motivational speaker through ENGAGE talent agency and remains deeply involved in Houston's sports and community scene.",
        sourceUrl: "https://www.letsengage.com/talent/brian-cushing",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 10,
        position: "Linebacker",
        yearsAtSchool: "2005-2008",
        statsNote: "True freshman in 2005 • Part of legendary USC LB corps with Rivers, Maualuga, Clay Matthews", gamesPlayed: 13,
      },
            seasonStats: [
        { level: "COLLEGE", teamName: "USC Trojans", season: "2005", yearLabel: "Freshman", sortOrder: 101, gamesPlayed: 13, tournamentResult: "Limited role as true freshman LB" },
        { level: "COLLEGE", teamName: "USC Trojans", season: "2007", yearLabel: "Junior", sortOrder: 103, gamesPlayed: 13, pointsPerGame: 64, reboundsPerGame: 5.5, tournamentResult: "64 tackles, 5.5 sacks" },
        { level: "COLLEGE", teamName: "USC Trojans", season: "2008", yearLabel: "Senior", sortOrder: 104, gamesPlayed: 13, pointsPerGame: 75, reboundsPerGame: 4.5, tournamentResult: "75 tackles, 4.5 sacks" },
        { level: "PROFESSIONAL", teamName: "Houston Texans", season: "2009", yearLabel: "2009 (DROY)", sortOrder: 301, gamesPlayed: 16, pointsPerGame: 89, reboundsPerGame: 4.0, tournamentResult: "89 tackles, 4.0 sacks (AP Def. Rookie of Year)" },
        { level: "PROFESSIONAL", teamName: "Houston Texans", season: "2011", yearLabel: "2011", sortOrder: 303, gamesPlayed: 16, pointsPerGame: 81, reboundsPerGame: 5.5, tournamentResult: "81 tackles, 5.5 sacks (Pro Bowl)" },
        { level: "PROFESSIONAL", teamName: "Houston Texans", season: "2014", yearLabel: "2014", sortOrder: 306, gamesPlayed: 13, pointsPerGame: 60, reboundsPerGame: 2.0, tournamentResult: "60 tackles, 2.0 sacks" },
      ],
      careerEvents: [
        { year: 2009, title: "Selected #15 overall by the Houston Texans", eventType: "DRAFT" },
        { year: 2009, title: "Won AP NFL Defensive Rookie of the Year", eventType: "AWARD" },
        { year: 2018, title: "Retired as Houston Texans all-time leading tackler", eventType: "RETIREMENT" },
        { year: 2019, title: "Became Texans assistant strength and conditioning coach", eventType: "CAREER" },
      ],
    },
    {
      slug: "sedrick-ellis",
      firstName: "Sedrick",
      lastName: "Ellis",
      birthYear: 1985,
      hometown: "Chino, CA",
      highSchool: "Chino High School, Chino, CA",
      isFeatured: false,
      bio: "A dominant defensive tackle and unanimous All-American who was the Pac-10 Defensive Player of the Year in 2007. Ellis anchored USC's defensive line during the 2005 season.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NFL Player",
        location: "Southern California",
        statusNote:
          "Selected 7th overall by the New Orleans Saints in 2008, Ellis started in Super Bowl XLIV, helping the Saints win their first championship. He retired abruptly in 2013 at age 28, walking away from a contract with the Chicago Bears. 'I was sick of football and football was sick of me,' he said in a 2015 interview. Since retirement he has embraced a life of travel, visiting Thailand, London, Brazil, and Mexico, and lives contentedly in Southern California.",
        sourceUrl: "https://en.wikipedia.org/wiki/Sedrick_Ellis",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 49,
        position: "Defensive Tackle",
        yearsAtSchool: "2004-2007",
        statsNote: "Unanimous All-American • Pac-10 Defensive Player of the Year 2007", gamesPlayed: 13,
      },
            seasonStats: [
        { level: "COLLEGE", teamName: "USC Trojans", season: "2005", yearLabel: "Sophomore", sortOrder: 102, gamesPlayed: 13, pointsPerGame: 35, reboundsPerGame: 4.0, tournamentResult: "35 tackles, 4.0 sacks" },
        { level: "COLLEGE", teamName: "USC Trojans", season: "2006", yearLabel: "Junior", sortOrder: 103, gamesPlayed: 13, pointsPerGame: 42, reboundsPerGame: 5.5, tournamentResult: "42 tackles, 5.5 sacks" },
        { level: "COLLEGE", teamName: "USC Trojans", season: "2007", yearLabel: "Senior (Pac-10 DPOY)", sortOrder: 104, gamesPlayed: 13, pointsPerGame: 55, reboundsPerGame: 12.5, tournamentResult: "55 tackles, 12.5 sacks" },
        { level: "PROFESSIONAL", teamName: "New Orleans Saints", season: "2008", yearLabel: "2008 (#7 pick)", sortOrder: 301, gamesPlayed: 16, pointsPerGame: 30, reboundsPerGame: 2.0, tournamentResult: "30 tackles, 2.0 sacks" },
        { level: "PROFESSIONAL", teamName: "New Orleans Saints", season: "2009", yearLabel: "2009 (Super Bowl Champion)", sortOrder: 302, gamesPlayed: 16, pointsPerGame: 37, reboundsPerGame: 2.5, tournamentResult: "37 tackles, 2.5 sacks" },
        { level: "PROFESSIONAL", teamName: "New Orleans Saints", season: "2010", yearLabel: "2010", sortOrder: 303, gamesPlayed: 16, pointsPerGame: 44, reboundsPerGame: 6.0, tournamentResult: "44 tackles, 6.0 sacks" },
      ],
      careerEvents: [
        { year: 2008, title: "Selected #7 overall by the New Orleans Saints", eventType: "DRAFT" },
        { year: 2010, title: "Won Super Bowl XLIV with the Saints", eventType: "CHAMPIONSHIP" },
        { year: 2013, title: "Abruptly retired at age 28 from the Chicago Bears", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "frostee-rucker",
      firstName: "Frostee",
      lastName: "Rucker",
      birthYear: 1983,
      hometown: "Tustin, CA",
      highSchool: "Tustin High School, Tustin, CA",
      isFeatured: false,
      bio: "A veteran defensive end who transferred from Colorado State and became a key contributor on USC's defensive line. Rucker played 13 NFL seasons across four teams.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "VP of Sports and Entertainment",
        currentEmployer: "Fortuna Investments",
        location: "Tustin, CA",
        statusNote:
          "Selected in the third round by the Cincinnati Bengals in 2006, Rucker had a remarkably long 13-year NFL career with the Bengals, Browns, Cardinals, and Raiders, appearing in 170 games with 21.5 career sacks. After retiring in 2018, he joined Fortuna Investments as Vice President of Sports and Entertainment. He also runs STAY READY, a youth football training program operating under Frostee's Challenge, his 501(c)(3) nonprofit providing athletic opportunities for underserved youth.",
        sourceUrl: "https://en.wikipedia.org/wiki/Frostee_Rucker",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 90,
        position: "Defensive End",
        yearsAtSchool: "2002-2005",
        statsNote: "First Team All-Pac-10 2005 • Transfer from Colorado State", gamesPlayed: 13,
      },
            seasonStats: [
        { level: "COLLEGE", teamName: "USC Trojans", season: "2004", yearLabel: "Junior", sortOrder: 102, gamesPlayed: 13, pointsPerGame: 28, reboundsPerGame: 3.5, tournamentResult: "28 tackles, 3.5 sacks" },
        { level: "COLLEGE", teamName: "USC Trojans", season: "2005", yearLabel: "Senior (All-Pac-10)", sortOrder: 103, gamesPlayed: 13, pointsPerGame: 38, reboundsPerGame: 5.0, tournamentResult: "38 tackles, 5.0 sacks" },
        { level: "PROFESSIONAL", teamName: "Cincinnati Bengals", season: "2006", yearLabel: "2006", sortOrder: 301, gamesPlayed: 16, pointsPerGame: 22, reboundsPerGame: 2.0, tournamentResult: "22 tackles, 2.0 sacks" },
        { level: "PROFESSIONAL", teamName: "Cincinnati Bengals", season: "2010", yearLabel: "2010", sortOrder: 305, gamesPlayed: 16, pointsPerGame: 32, reboundsPerGame: 3.5, tournamentResult: "32 tackles, 3.5 sacks" },
        { level: "PROFESSIONAL", teamName: "Arizona Cardinals", season: "2013", yearLabel: "2013", sortOrder: 308, gamesPlayed: 16, pointsPerGame: 37, reboundsPerGame: 4.0, tournamentResult: "37 tackles, 4.0 sacks" },
        { level: "PROFESSIONAL", teamName: "Arizona Cardinals", season: "2016", yearLabel: "2016", sortOrder: 311, gamesPlayed: 16, pointsPerGame: 25, reboundsPerGame: 3.0, tournamentResult: "25 tackles, 3.0 sacks" },
      ],
      careerEvents: [
        { year: 2006, title: "Selected #91 overall by the Cincinnati Bengals", eventType: "DRAFT" },
        { year: 2018, title: "Retired after 13 NFL seasons and 170 games", eventType: "RETIREMENT" },
        { year: 2023, title: "Joined Fortuna Investments as VP of Sports and Entertainment", eventType: "CAREER" },
      ],
    },
    {
      slug: "winston-justice",
      firstName: "Winston",
      lastName: "Justice",
      birthYear: 1984,
      hometown: "Long Beach, CA",
      highSchool: "Long Beach Polytechnic High School, Long Beach, CA",
      isFeatured: false,
      bio: "A massive offensive tackle who protected Matt Leinart's blind side. Justice was a two-year starter at USC before entering the 2006 NFL Draft.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "CEO",
        currentEmployer: "SageSpring Private Wealth",
        location: "Philadelphia, PA",
        linkedInUrl: "https://www.linkedin.com/in/winstonjustice/",
        statusNote:
          "One of the most impressive post-NFL career pivots. After seven seasons with the Eagles and Colts, Justice earned his MBA and CFA certification, completed programs at Wharton and Notre Dame, and worked his way up from associate analyst at Wells Fargo to portfolio manager at Pacific Income Advisors to VP at AllianceBernstein managing institutional assets. He is now CEO of SageSpring Private Wealth. He also owns Elixr Coffee Roasters, a chain with four locations in Philadelphia and one in State College, PA.",
        sourceUrl: "https://www.linkedin.com/in/winstonjustice/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 74,
        position: "Offensive Tackle",
        yearsAtSchool: "2003-2005",
        statsNote: "Two-year starter protecting Matt Leinart's blind side", gamesPlayed: 13,
      },
      careerEvents: [
        { year: 2006, title: "Selected #39 overall by the Philadelphia Eagles", eventType: "DRAFT" },
        { year: 2012, title: "Final NFL season with the Indianapolis Colts", eventType: "CAREER" },
      ],
    },
    {
      slug: "sam-baker",
      firstName: "Sam",
      lastName: "Baker",
      birthYear: 1985,
      hometown: "Tustin, CA",
      highSchool: "Tustin High School, Tustin, CA",
      isFeatured: false,
      bio: "A dominant offensive tackle who started on the 2005 line as a sophomore. Baker went on to be a first-round NFL draft pick and started for the Atlanta Falcons.",
      status: {
        occupationType: "COACH",
        currentTitle: "High School Football Coach",
        location: "California",
        statusNote:
          "Selected 21st overall by the Atlanta Falcons in 2008, Baker was a key starter for five seasons before chronic knee injuries forced him out at age 30 despite starting 59 games. After his release in 2015, Baker transitioned to high school football coaching in California, leveraging his experience as a three-time All-American at USC and seven-year NFL veteran to mentor the next generation.",
        sourceUrl: "https://en.wikipedia.org/wiki/Sam_Baker_(offensive_tackle)",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 72,
        position: "Offensive Tackle",
        yearsAtSchool: "2004-2007",
        statsNote: "Started as sophomore on 2005 line • First-round pick", gamesPlayed: 13,
      },
      careerEvents: [
        { year: 2008, title: "Selected #21 overall by the Atlanta Falcons", eventType: "DRAFT" },
        { year: 2013, title: "Retired from the NFL due to chronic knee injuries", eventType: "RETIREMENT" },
      ],
    },
    {
      slug: "lawrence-jackson",
      firstName: "Lawrence",
      lastName: "Jackson",
      birthYear: 1985,
      hometown: "Inglewood, CA",
      highSchool: "Morningside High School, Inglewood, CA",
      isFeatured: false,
      bio: "An explosive pass rusher who developed into one of the Pac-10's top defensive ends during his time at USC. Jackson had 8 sacks in his senior season.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Social Entrepreneur / Community Leader",
        currentEmployer: "A World Fit For Kids / Torch LA",
        location: "Inglewood, CA",
        statusNote:
          "Selected 28th overall by the Seattle Seahawks in 2008, Jackson played four NFL seasons with Seattle and Detroit (10.5 career sacks). After retiring in 2013, he became a social entrepreneur and community leader in his hometown of Inglewood. He serves as Chair of the USC Black Alumni Young Professionals Association, co-chairs the American Heart Association's Inglewood Active Community Coalition, and is Director of Torch LA. He also works with A World Fit For Kids, empowering underserved communities through youth mentoring. He was a speaker at the MIT Sloan Sports Analytics Conference.",
        sourceUrl: "https://worldfitforkids.org/our_team/lawrence-jackson/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 86,
        position: "Defensive End",
        yearsAtSchool: "2004-2007",
        statsNote: "8 sacks in senior season • First-round pick", gamesPlayed: 13,
      },
      careerEvents: [
        { year: 2008, title: "Selected #28 overall by the Seattle Seahawks", eventType: "DRAFT" },
        { year: 2012, title: "Final NFL season with the Detroit Lions", eventType: "CAREER" },
      ],
    },
    // ── Batch 3: Role Players & Coaches ──────────────────────────────────────
    {
      slug: "darnell-bing",
      firstName: "Darnell",
      lastName: "Bing",
      birthYear: 1984,
      hometown: "Los Angeles, CA",
      highSchool: "Manual Arts High School, Los Angeles, CA",
      isFeatured: false,
      bio: "A hard-hitting safety who was one of the most highly recruited players in the country coming out of high school. Bing was a key contributor in USC's secondary.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Educator / Graduate Student",
        location: "Los Angeles, CA",
        statusNote:
          "One of the most highly recruited players in the country out of high school, Bing went undrafted in 2006 and had brief stints with the Raiders, 49ers, Jets, Lions, and Texans before his career ended. In an inspiring post-football chapter, he returned to USC to pursue his master's degree in education, even trying to hide his identity from undergrads by claiming he worked in real estate. His return to school shows the value of education beyond football.",
        sourceUrl: "https://news.usc.edu/trojan-family/football-players-return-to-usc-nfl/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 27,
        position: "Safety",
        yearsAtSchool: "2003-2005",
        statsNote: "Key starter in secondary • Originally recruited as WR/ATH", gamesPlayed: 13,
      },
      careerEvents: [
        { year: 2006, title: "Went undrafted; signed as free agent with Oakland Raiders", eventType: "SIGNING" },
      ],
    },
    {
      slug: "oscar-lua",
      firstName: "Oscar",
      lastName: "Lua",
      birthYear: 1983,
      hometown: "Indio, CA",
      highSchool: "Indio High School, Indio, CA",
      isFeatured: false,
      bio: "A reliable inside linebacker who was a four-year contributor at USC. Lua was a steady tackler and leader on the defensive side of the ball.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "President / Partner",
        currentEmployer: "Statewide Services Inc.",
        location: "Indio, CA",
        statusNote:
          "After a brief NFL stint with the Patriots (7th round, 2007) and Browns, Lua returned to his hometown of Indio, CA and pivoted to construction and property development. He worked his way up in property management in Orange County before becoming president and partner at Statewide Services Inc., a general contractor building affordable housing developments in the Coachella Valley. In 2024, his company completed a major new apartment complex in Indio, giving back to the community where he grew up.",
        sourceUrl: "https://kesq.com/news/2024/05/24/local-native-and-former-nfl-player-gives-back-to-community-with-new-apartments/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 46,
        position: "Inside Linebacker",
        yearsAtSchool: "2002-2005",
        statsNote: "Four-year contributor • Steady tackler and defensive leader", gamesPlayed: 13,
      },
      careerEvents: [
        { year: 2006, title: "Went undrafted; brief stint with Cleveland Browns", eventType: "SIGNING" },
      ],
    },
    {
      slug: "david-kirtman",
      firstName: "David",
      lastName: "Kirtman",
      birthYear: 1983,
      hometown: "Oceanside, CA",
      highSchool: "El Camino High School, Oceanside, CA",
      isFeatured: false,
      bio: "A bruising fullback who served as the lead blocker for Reggie Bush and LenDale White. Kirtman was a selfless player who made the ground game go.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Sales Trader, Japanese Equities",
        currentEmployer: "Merrill Lynch Japan Securities",
        location: "Tokyo, Japan",
        statusNote:
          "After 4 years in the NFL (Chargers, Hamburg Sea Devils in NFL Europe), Kirtman made a remarkable career pivot — moving to Tokyo to work in finance. He traded on the Merrill Lynch Japan Securities proprietary desk for a year, then after the 2011 Tohoku earthquake, moved to the sell side as a sales trader for Japanese equities. Graduated from USC with a degree in business with a marketing emphasis. His blocking for Reggie Bush and LenDale White earned him the catchphrase 'Another Touchdown Courtesy of Kirtman.'",
        sourceUrl: "https://en.wikipedia.org/wiki/David_Kirtman",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 40,
        position: "Fullback",
        yearsAtSchool: "2002-2005",
        statsNote: "Lead blocker for Bush and White • Key contributor to USC's rushing attack", gamesPlayed: 13,
      },
      careerEvents: [
        { year: 2006, title: "Went undrafted; signed as free agent with San Diego Chargers", eventType: "SIGNING" },
      ],
    },
    {
      slug: "josh-pinkard",
      firstName: "Josh",
      lastName: "Pinkard",
      birthYear: 1983,
      hometown: "Copperas Cove, TX",
      highSchool: "Copperas Cove High School, Copperas Cove, TX",
      isFeatured: false,
      bio: "A physical cornerback who was a key member of USC's secondary in the 2005 season. Pinkard provided reliable coverage on the outside.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Citizen",
        statusNote:
          "Pinkard went undrafted in 2006, signed with the Houston Texans, and appeared in 15 games before being released. He later signed with the Seahawks but was waived after failing his physical. After football, Pinkard has chosen to live entirely out of the public eye — extensive searches of LinkedIn, social media, and news sources have not revealed his current occupation. Some former players prefer complete privacy after their careers end.",
        sourceUrl: "https://en.wikipedia.org/wiki/Josh_Pinkard",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 19,
        position: "Cornerback",
        yearsAtSchool: "2002-2005",
        statsNote: "Starting cornerback in 2005 secondary", gamesPlayed: 13,
      },
      careerEvents: [
        { year: 2006, title: "Signed as undrafted free agent with Houston Texans", eventType: "SIGNING" },
      ],
    },
    // ── Coaches ──────────────────────────────────────────────────────────────
    {
      slug: "pete-carroll",
      firstName: "Pete",
      lastName: "Carroll",
      birthYear: 1951,
      hometown: "San Francisco, CA",
      highSchool: "Redwood High School, Larkspur, CA",
      isFeatured: true,
      bio: "One of three coaches to win both a Super Bowl and a college national championship. Carroll built USC into a dynasty, going 97-19 from 2001-2009 with two national titles and seven straight Pac-10 championships.",
      status: {
        occupationType: "RETIRED_COACH",
        currentTitle: "Former Head Coach",
        location: "Los Angeles, CA",
        statusNote:
          "After transforming USC into a powerhouse (97-19 from 2001-2009, two national titles), Carroll left for the Seattle Seahawks where he won Super Bowl XLVIII in 2014. He coached the Seahawks for 14 seasons (2010-2023) before transitioning to an advisory role. In 2025 he was hired as Las Vegas Raiders head coach but was fired after a disastrous 3-14 season in January 2026. He is currently out of coaching and was announced as the 2026 commencement speaker for USC's Marshall School of Business.",
        sourceUrl: "https://en.wikipedia.org/wiki/Pete_Carroll",
      },
      membership: {
        role: "HEAD_COACH",
        position: "Head Coach",
        yearsAtSchool: "2001-2009",
        statsNote: "97-19 at USC • 2 National Championships (2003, 2004) • 7 straight Pac-10 titles",
      },
      careerEvents: [
        { year: 2004, title: "Won BCS National Championship (USC vs Oklahoma)", eventType: "CHAMPIONSHIP" },
        { year: 2005, title: "Lost BCS National Championship Game to Texas 41-38", eventType: "CHAMPIONSHIP" },
        { year: 2010, title: "Left USC to become Seattle Seahawks head coach", eventType: "CAREER" },
        { year: 2014, title: "Won Super Bowl XLVIII with the Seattle Seahawks", eventType: "CHAMPIONSHIP" },
        { year: 2025, title: "Hired as Las Vegas Raiders head coach", eventType: "CAREER" },
        { year: 2026, title: "Fired by Raiders after 3-14 season", eventType: "CAREER" },
      ],
    },
    {
      slug: "lane-kiffin",
      firstName: "Lane",
      lastName: "Kiffin",
      birthYear: 1975,
      hometown: "Lincoln, NE",
      highSchool: "Jefferson High School, Bloomington, MN",
      isFeatured: true,
      bio: "The offensive coordinator who designed the plays for Leinart, Bush, and White. Kiffin's creative playcalling helped USC's offense rank among the nation's best.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Football Coach",
        currentEmployer: "LSU Tigers",
        location: "Baton Rouge, LA",
        statusNote:
          "After serving as USC's offensive coordinator (2005-2006), Kiffin became the youngest head coach in NFL history with the Oakland Raiders at age 31. He later served as head coach at Tennessee and USC before building Ole Miss into a powerhouse (55-19 over six seasons). In November 2025, he controversially left Ole Miss mid-season for LSU, signing a seven-year, $91 million deal. He is now preparing for his first season as LSU's head coach in 2026.",
        sourceUrl: "https://en.wikipedia.org/wiki/Lane_Kiffin",
      },
      membership: {
        role: "ASSISTANT_COACH",
        position: "Offensive Coordinator",
        yearsAtSchool: "2001-2006",
        statsNote: "OC who designed offense for Leinart, Bush, and White",
      },
      careerEvents: [
        { year: 2007, title: "Named Oakland Raiders head coach at age 31 (youngest in NFL history)", eventType: "CAREER" },
        { year: 2010, title: "Became USC head coach", eventType: "CAREER" },
        { year: 2013, title: "Fired by USC midseason, famously dismissed on the tarmac at LAX", eventType: "CAREER" },
        { year: 2017, title: "Named Florida Atlantic head coach; won C-USA title", eventType: "CAREER" },
        { year: 2020, title: "Named Ole Miss head coach", eventType: "CAREER" },
        { year: 2025, title: "Left Ole Miss for LSU, signing $91M deal", eventType: "CAREER" },
      ],
    },
    {
      slug: "nick-holt",
      firstName: "Nick",
      lastName: "Holt",
      birthYear: 1962,
      hometown: "Stockton, CA",
      highSchool: "Stagg High School, Stockton, CA",
      isFeatured: false,
      bio: "A longtime defensive coach who served multiple stints at USC. Holt was USC's linebackers coach from 2001-2003 and returned as defensive coordinator from 2006-2008, bookending the 2005 season.",
      status: {
        occupationType: "COACH",
        currentTitle: "Associate Head Coach / Co-DC / DL Coach",
        currentEmployer: "Abilene Christian University",
        location: "Abilene, TX",
        statusNote:
          "After serving as USC's linebackers coach (2001-2003) and defensive coordinator (2006-2008), Holt had a journeyman coaching career spanning Idaho (head coach), Washington (DC), USC, Purdue (DC), Italian football, and Texas Tech (analyst). Since 2022, he has served as associate head coach, co-defensive coordinator, and defensive line coach at Abilene Christian University, helping the Wildcats to a 9-5 season and FCS playoff berth in 2024. Notably, his maternal grandfather was Olympic swimmer and actor Buster Crabbe.",
        sourceUrl: "https://en.wikipedia.org/wiki/Nick_Holt",
      },
      membership: {
        role: "ASSISTANT_COACH",
        position: "Linebackers Coach (2001-03) / Defensive Coordinator (2006-08)",
        yearsAtSchool: "2001-2003, 2006-2008",
        statsNote: "Two stints at USC • Coached USC's #2 overall defense in 2008",
      },
      careerEvents: [
        { year: 2004, title: "Named head coach at University of Idaho", eventType: "CAREER" },
        { year: 2006, title: "Returned to USC as defensive coordinator", eventType: "CAREER" },
        { year: 2009, title: "Named Washington defensive coordinator", eventType: "CAREER" },
        { year: 2022, title: "Joined Abilene Christian as associate head coach and co-DC", eventType: "CAREER" },
      ],
    },
    // ── Batch 4: Additional Notable Players ──────────────────────────────────
    {
      slug: "clay-matthews-iii",
      firstName: "Clay",
      lastName: "Matthews III",
      birthYear: 1986,
      hometown: "Agoura Hills, CA",
      highSchool: "Agoura High School, Agoura Hills, CA",
      isFeatured: true,
      bio: "A walk-on who became a six-time Pro Bowler. Matthews won three consecutive USC Special Teams Player of the Year awards and developed into a star pass rusher. Part of the legendary Matthews football family.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NFL Player",
        location: "Los Angeles, CA",
        statusNote:
          "Selected 26th overall by the Green Bay Packers in 2009, Matthews became one of the NFL's most feared pass rushers, earning six Pro Bowl selections and winning Super Bowl XLV. He played 10 seasons with the Packers and two with the Rams, retiring in 2022. He was inducted into the Packers Hall of Fame in 2024. He is the son and grandson of NFL players Clay Matthews Jr. and Clay Matthews Sr.",
        sourceUrl: "https://en.wikipedia.org/wiki/Clay_Matthews_III",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 47,
        position: "Outside Linebacker",
        yearsAtSchool: "2004-2008",
        statsNote: "Walk-on turned star • 3x USC Special Teams Player of the Year", gamesPlayed: 13,
      },
            seasonStats: [
        { level: "PROFESSIONAL", teamName: "Green Bay Packers", season: "2009", yearLabel: "2009 (DROY finalist)", sortOrder: 301, gamesPlayed: 16, pointsPerGame: 51, reboundsPerGame: 10.0, tournamentResult: "51 tackles, 10.0 sacks" },
        { level: "PROFESSIONAL", teamName: "Green Bay Packers", season: "2010", yearLabel: "2010 (Super Bowl Champion)", sortOrder: 302, gamesPlayed: 15, pointsPerGame: 54, reboundsPerGame: 13.5, tournamentResult: "54 tackles, 13.5 sacks" },
        { level: "PROFESSIONAL", teamName: "Green Bay Packers", season: "2012", yearLabel: "2012", sortOrder: 304, gamesPlayed: 16, pointsPerGame: 50, reboundsPerGame: 13.0, tournamentResult: "50 tackles, 13.0 sacks" },
        { level: "PROFESSIONAL", teamName: "Green Bay Packers", season: "2014", yearLabel: "2014 (Pro Bowl)", sortOrder: 306, gamesPlayed: 15, pointsPerGame: 68, reboundsPerGame: 11.0, tournamentResult: "68 tackles, 11.0 sacks" },
        { level: "PROFESSIONAL", teamName: "Green Bay Packers", season: "2017", yearLabel: "2017", sortOrder: 309, gamesPlayed: 14, pointsPerGame: 52, reboundsPerGame: 8.5, tournamentResult: "52 tackles, 8.5 sacks" },
        { level: "PROFESSIONAL", teamName: "Los Angeles Rams", season: "2019", yearLabel: "2019", sortOrder: 311, gamesPlayed: 16, pointsPerGame: 37, reboundsPerGame: 8.0, tournamentResult: "37 tackles, 8.0 sacks" },
      ],
      careerEvents: [
        { year: 2009, title: "Selected #26 overall by the Green Bay Packers", eventType: "DRAFT" },
        { year: 2011, title: "Won Super Bowl XLV with the Packers", eventType: "CHAMPIONSHIP" },
        { year: 2022, title: "Retired from the NFL after 12 seasons", eventType: "RETIREMENT" },
        { year: 2024, title: "Inducted into Packers Hall of Fame", eventType: "AWARD" },
      ],
    },
    {
      slug: "mark-sanchez",
      firstName: "Mark",
      lastName: "Sanchez",
      birthYear: 1986,
      hometown: "Long Beach, CA",
      highSchool: "Mission Viejo High School, Mission Viejo, CA",
      isFeatured: false,
      bio: "Redshirted as a freshman in 2005 behind Matt Leinart, then waited behind John David Booty before leading USC to a Rose Bowl victory as a junior starter in 2008.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NFL Player",
        location: "Southern California",
        statusNote:
          "Selected 5th overall by the New York Jets in 2009, Sanchez led the Jets to consecutive AFC Championship Games in his first two seasons. He played seven NFL seasons with the Jets, Eagles, Cowboys, Bears, and Washington. After retiring, he became a college football analyst for Fox Sports but was let go in November 2025 following an off-field incident in Indianapolis.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mark_Sanchez",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 6,
        position: "Quarterback",
        yearsAtSchool: "2005-2008",
        statsNote: "Redshirt freshman in 2005 • Led USC to 2009 Rose Bowl victory as junior starter", gamesPlayed: 0,
      },
            seasonStats: [
        { level: "COLLEGE", teamName: "USC Trojans", season: "2005", yearLabel: "Freshman (Redshirt)", sortOrder: 101, gamesPlayed: 0, tournamentResult: "Redshirted behind Matt Leinart" },
        { level: "COLLEGE", teamName: "USC Trojans", season: "2008", yearLabel: "Junior (Rose Bowl MVP)", sortOrder: 104, gamesPlayed: 13, pointsPerGame: 3207, reboundsPerGame: 34, assistsPerGame: 10, stealsPerGame: 351, fieldGoalPct: 0.607, tournamentResult: "213/351 passing, 3,207 yds, 34 TD, 10 INT" },
        { level: "PROFESSIONAL", teamName: "New York Jets", season: "2009", yearLabel: "2009 (AFC Championship)", sortOrder: 301, gamesPlayed: 16, pointsPerGame: 2444, reboundsPerGame: 12, assistsPerGame: 20, stealsPerGame: 364, fieldGoalPct: 0.538, tournamentResult: "196/364 passing, 2,444 yds, 12 TD, 20 INT" },
        { level: "PROFESSIONAL", teamName: "New York Jets", season: "2010", yearLabel: "2010 (AFC Championship)", sortOrder: 302, gamesPlayed: 16, pointsPerGame: 3291, reboundsPerGame: 17, assistsPerGame: 13, stealsPerGame: 369, fieldGoalPct: 0.539, tournamentResult: "199/369 passing, 3,291 yds, 17 TD, 13 INT" },
        { level: "PROFESSIONAL", teamName: "New York Jets", season: "2012", yearLabel: "2012 (Butt Fumble)", sortOrder: 304, gamesPlayed: 11, pointsPerGame: 1364, reboundsPerGame: 6, assistsPerGame: 14, stealsPerGame: 225, fieldGoalPct: 0.52, tournamentResult: "117/225 passing, 1,364 yds, 6 TD, 14 INT" },
      ],
      careerEvents: [
        { year: 2009, title: "Selected #5 overall by the New York Jets", eventType: "DRAFT" },
        { year: 2010, title: "Led Jets to AFC Championship Game (back-to-back years)", eventType: "CAREER" },
        { year: 2018, title: "Retired from the NFL", eventType: "RETIREMENT" },
        { year: 2025, title: "Let go from Fox Sports analyst role", eventType: "CAREER" },
      ],
    },
    {
      slug: "ryan-kalil",
      firstName: "Ryan",
      lastName: "Kalil",
      birthYear: 1985,
      hometown: "Anaheim, CA",
      highSchool: "Servite High School, Anaheim, CA",
      isFeatured: false,
      bio: "An elite center who anchored USC's offensive line in 2005 as a junior. Kalil was a two-year starter and first-team All-Pac-10 selection.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Entrepreneur / Film Producer",
        currentEmployer: "Mortal Media / Audiorama",
        location: "Los Angeles, CA",
        statusNote:
          "Selected in the second round by the Carolina Panthers in 2007, Kalil became a five-time Pro Bowl center over 12 NFL seasons. After retiring in 2019, he co-founded Mortal Media with Blake Griffin, producing Apple TV+'s Hello Tomorrow! and other projects. He co-founded podcast network Audiorama with Greg Olsen and Vince Vaughn, launched premium tequila brand Celaya with his brother Matt, and in 2025 acquired a majority stake in a Mexican professional football team, rebranding it as Osos Monterrey.",
        sourceUrl: "https://en.wikipedia.org/wiki/Ryan_Kalil",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 67,
        position: "Center",
        yearsAtSchool: "2003-2006",
        statsNote: "Two-year starter • First-team All-Pac-10 • Anchored line for Leinart and Bush", gamesPlayed: 13,
      },
            seasonStats: [
        { level: "COLLEGE", teamName: "USC Trojans", season: "2004", yearLabel: "Sophomore", sortOrder: 101, gamesPlayed: 13, tournamentResult: "Started 13 games at center" },
        { level: "COLLEGE", teamName: "USC Trojans", season: "2005", yearLabel: "Junior", sortOrder: 102, gamesPlayed: 12, tournamentResult: "Started 12 games, All-Pac-10" },
        { level: "COLLEGE", teamName: "USC Trojans", season: "2006", yearLabel: "Senior", sortOrder: 103, gamesPlayed: 13, tournamentResult: "Started 13 games" },
        { level: "PROFESSIONAL", teamName: "Carolina Panthers", season: "2007", yearLabel: "2007", sortOrder: 301, gamesPlayed: 16, tournamentResult: "Started 16 games" },
        { level: "PROFESSIONAL", teamName: "Carolina Panthers", season: "2009", yearLabel: "2009 (Pro Bowl)", sortOrder: 303, gamesPlayed: 16, tournamentResult: "Started 16 games" },
        { level: "PROFESSIONAL", teamName: "Carolina Panthers", season: "2011", yearLabel: "2011 (Pro Bowl)", sortOrder: 305, gamesPlayed: 16, tournamentResult: "Started 16 games" },
        { level: "PROFESSIONAL", teamName: "Carolina Panthers", season: "2013", yearLabel: "2013 (Pro Bowl)", sortOrder: 307, gamesPlayed: 16, tournamentResult: "Started 16 games" },
        { level: "PROFESSIONAL", teamName: "Carolina Panthers", season: "2015", yearLabel: "2015 (Super Bowl, Pro Bowl)", sortOrder: 309, gamesPlayed: 16, tournamentResult: "Started 16 games, Super Bowl 50" },
        { level: "PROFESSIONAL", teamName: "Carolina Panthers", season: "2018", yearLabel: "2018 (Pro Bowl)", sortOrder: 312, gamesPlayed: 16, tournamentResult: "Started 16 games" },
      ],
      careerEvents: [
        { year: 2007, title: "Selected #59 overall by the Carolina Panthers", eventType: "DRAFT" },
        { year: 2019, title: "Retired after 12 NFL seasons (5x Pro Bowl)", eventType: "RETIREMENT" },
        { year: 2016, title: "Co-founded Mortal Media production company with Blake Griffin", eventType: "CAREER" },
        { year: 2022, title: "Co-founded Audiorama podcast network with Greg Olsen and Vince Vaughn", eventType: "CAREER" },
        { year: 2025, title: "Acquired majority stake in Mexican football team (Osos Monterrey)", eventType: "CAREER" },
      ],
    },
    {
      slug: "john-david-booty",
      firstName: "John David",
      lastName: "Booty",
      birthYear: 1984,
      hometown: "Shreveport, LA",
      highSchool: "Evangel Christian Academy, Shreveport, LA",
      isFeatured: false,
      bio: "The backup quarterback behind Matt Leinart in 2005 who became USC's starter in 2007. Booty threw a key touchdown to Dwayne Jarrett in the 2005 season.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Executive Vice President",
        currentEmployer: "Ventus Group",
        location: "Southern California",
        linkedInUrl: "https://www.linkedin.com/in/john-david-booty-54046977/",
        statusNote:
          "After a 20-3 career record as USC's starting QB (6,125 passing yards, 55 TDs — both top-5 in school history), Booty was drafted in the 5th round by the Minnesota Vikings in 2008. His NFL career was brief. He pivoted to real estate development and is now Executive Vice President at Ventus Group, a Southern California-based developer specializing in multifamily housing. He writes for Multifamily Executive magazine and is a motivational speaker on leadership and resilience.",
        sourceUrl: "https://www.linkedin.com/in/john-david-booty-54046977/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 10,
        position: "Quarterback",
        yearsAtSchool: "2003-2007",
        statsNote: "Backup QB in 2005 • Started for USC in 2007", gamesPlayed: 10,
      },
      careerEvents: [
        { year: 2008, title: "Selected by the Minnesota Vikings (5th round)", eventType: "DRAFT" },
      ],
    },
    {
      slug: "fred-davis",
      firstName: "Fred",
      lastName: "Davis",
      birthYear: 1986,
      hometown: "Agoura Hills, CA",
      highSchool: "Agoura High School, Agoura Hills, CA",
      isFeatured: false,
      bio: "A talented tight end who caught 13 passes for 145 yards and 2 touchdowns in 2005 as a true freshman. Davis developed into a second-round NFL draft pick.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NFL Player",
        statusNote:
          "Selected 48th overall by the Washington Redskins in 2008, Davis had a productive NFL career highlighted by a 2011 season with 59 catches for 796 yards. Multiple suspensions for violating the NFL's substance abuse policy limited his career, and he last played in 2015 with the New England Patriots. He has kept a low profile since retiring from football.",
        sourceUrl: "https://en.wikipedia.org/wiki/Fred_Davis_(American_football)",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 85,
        position: "Tight End",
        yearsAtSchool: "2005-2007",
        statsNote: "True freshman in 2005 • 13 rec, 145 yds, 2 TD • Second-round NFL pick", gamesPlayed: 13,
      },
      careerEvents: [
        { year: 2008, title: "Selected #48 overall by the Washington Redskins", eventType: "DRAFT" },
        { year: 2015, title: "Final NFL season with the New England Patriots", eventType: "CAREER" },
      ],
    },
    {
      slug: "taitusi-lutui",
      firstName: "Taitusi",
      lastName: "Lutui",
      birthYear: 1983,
      hometown: "Tonga",
      highSchool: "Waianae High School, Waianae, HI",
      isFeatured: false,
      bio: "A powerful offensive guard who was a key run blocker in USC's dominant ground game. Lutui paved the way for Reggie Bush and LenDale White.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NFL Player",
        statusNote:
          "Selected in the second round by the Arizona Cardinals in 2006, Lutui started 52 games over five NFL seasons with the Cardinals and Titans. He was part of the Cardinals team that reached Super Bowl XLIII. After leaving the NFL, Lutui returned to his Tongan roots and has been involved in community work in Hawaii.",
        sourceUrl: "https://en.wikipedia.org/wiki/Deuce_Lutui",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 78,
        position: "Offensive Guard",
        yearsAtSchool: "2002-2005",
        statsNote: "Key run blocker for Bush and White • Second-round NFL pick", gamesPlayed: 13,
      },
      careerEvents: [
        { year: 2006, title: "Selected #41 overall by the Arizona Cardinals", eventType: "DRAFT" },
        { year: 2009, title: "Played in Super Bowl XLIII with the Cardinals", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "dominique-byrd",
      firstName: "Dominique",
      lastName: "Byrd",
      birthYear: 1984,
      hometown: "Ridgecrest, CA",
      highSchool: "Burroughs High School, Ridgecrest, CA",
      isFeatured: false,
      bio: "A versatile tight end who served as both a receiving threat and effective blocker in USC's offense during the 2005 season.",
      status: {
        occupationType: "OTHER",
        currentTitle: "USC Graduate / Community Leader",
        location: "Los Angeles, CA",
        statusNote:
          "Selected in the third round by the St. Louis Rams in 2006, Byrd played four NFL seasons with the Rams and Cardinals before injuries ended his career. In an inspiring post-football chapter, he returned to USC to complete his degree — proving that education was never forgotten. Active in community engagement and mentoring in the Los Angeles area.",
        sourceUrl: "https://today.usc.edu/dominique-byrd-returns-from-a-career-in-football-to-earn-his-usc-degree/",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 86,
        position: "Tight End",
        yearsAtSchool: "2002-2005",
        statsNote: "Versatile TE • Third-round NFL pick", gamesPlayed: 13,
      },
      careerEvents: [
        { year: 2006, title: "Selected #71 overall by the St. Louis Rams", eventType: "DRAFT" },
      ],
    },
    {
      slug: "kevin-ellison",
      firstName: "Kevin",
      lastName: "Ellison",
      birthYear: 1984,
      hometown: "Redondo Beach, CA",
      highSchool: "Mira Costa High School, Manhattan Beach, CA",
      isFeatured: false,
      bio: "An athletic safety/linebacker hybrid who was a key contributor in USC's secondary and special teams during the 2005 season.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Deceased",
        statusNote:
          "Selected in the 5th round by the San Diego Chargers in 2006, Ellison played one NFL season before being released. After brief stints with the Seahawks, he coached at the high school level and played arena football. Tragically, Kevin Ellison passed away on October 4, 2018, at age 31. His family believed he was suffering from CTE, which was posthumously confirmed by Boston University researchers in September 2019 as Stage II chronic traumatic encephalopathy. His story highlights the devastating long-term effects of football on brain health.",
        sourceUrl: "https://www.espn.com/college-football/story/_/id/24918562/former-usc-trojans-safety-kevin-ellison-dies-31",
      },
      membership: {
        role: "PLAYER",
        jerseyNumber: 9,
        position: "Safety / Linebacker",
        yearsAtSchool: "2002-2005",
        statsNote: "Versatile defender • Fifth-round NFL pick", gamesPlayed: 13,
      },
      careerEvents: [
        { year: 2006, title: "Selected by the San Diego Chargers (5th round)", eventType: "DRAFT" },
      ],
    },
    // ── Batch 5: Missing Starters & Key Contributors ─────────────────────────
    {
      slug: "terrell-thomas",
      firstName: "Terrell",
      lastName: "Thomas",
      birthYear: 1985,
      hometown: "Rancho Cucamonga, CA",
      highSchool: "Rancho Cucamonga High School, Rancho Cucamonga, CA",
      isFeatured: false,
      bio: "Starting cornerback who tore knee ligaments in the second game but went on to become a 2nd round NFL pick and Super Bowl champion with the Giants.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Real Estate Agent / Football Analyst",
        currentEmployer: "eXp Realty / Boston College",
        location: "Los Angeles, CA",
        statusNote: "Selected in the 2nd round by the NY Giants in 2008, Thomas won Super Bowl XLVI and had 5 INTs in 2009. After retiring, he became a real estate agent at eXp Realty, a Senior Football Analyst at Boston College, and published a book titled 'DIG.' He is also a strategic advisor at First Women's Bank.",
        sourceUrl: "https://life.exprealty.com/terrell-thomas-ny-giants-exp-realty/",
      },
      membership: { role: "PLAYER", jerseyNumber: 28, position: "Cornerback", yearsAtSchool: "2004-2007", statsNote: "Started first 2 games before knee injury • 2nd-round pick • Super Bowl champ", gamesPlayed: 2 },
            seasonStats: [
        { level: "COLLEGE", teamName: "USC Trojans", season: "2005", yearLabel: "Sophomore (knee injury game 2)", sortOrder: 101, gamesPlayed: 2, tournamentResult: "Tore knee ligaments vs Arkansas" },
        { level: "COLLEGE", teamName: "USC Trojans", season: "2007", yearLabel: "Senior", sortOrder: 103, gamesPlayed: 13, pointsPerGame: 54, reboundsPerGame: 4, fieldGoalPct: 4, tournamentResult: "54 tackles, 4 INT" },
        { level: "PROFESSIONAL", teamName: "New York Giants", season: "2008", yearLabel: "2008", sortOrder: 301, gamesPlayed: 16, pointsPerGame: 63, reboundsPerGame: 2, fieldGoalPct: 2, tournamentResult: "63 tackles, 2 INT" },
        { level: "PROFESSIONAL", teamName: "New York Giants", season: "2009", yearLabel: "2009", sortOrder: 302, gamesPlayed: 16, pointsPerGame: 57, reboundsPerGame: 5, fieldGoalPct: 5, tournamentResult: "57 tackles, 5 INT" },
        { level: "PROFESSIONAL", teamName: "New York Giants", season: "2011", yearLabel: "2011 (Super Bowl Champion)", sortOrder: 304, gamesPlayed: 4, pointsPerGame: 12, tournamentResult: "12 tackles (torn ACL, won Super Bowl XLVI)" },
      ],
      careerEvents: [
        { year: 2008, title: "Selected in 2nd round by the NY Giants", eventType: "DRAFT" },
        { year: 2012, title: "Won Super Bowl XLVI with the Giants", eventType: "CHAMPIONSHIP" },
      ],
    },
    {
      slug: "scott-ware",
      firstName: "Scott",
      lastName: "Ware",
      birthYear: 1983,
      hometown: "Santa Rosa, CA",
      highSchool: "Montgomery High School, Santa Rosa, CA",
      isFeatured: false,
      bio: "Starting free safety and All-Pac-10 second team selection in 2005.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Football Player",
        statusNote: "Senior starting free safety who earned All-Pac-10 second team honors. Signed as a UDFA by the Eagles in 2006, also played for the Colts and Sacramento Mountain Lions (UFL).",
        sourceUrl: "https://en.wikipedia.org/wiki/Scott_Ware",
      },
      membership: { role: "PLAYER", jerseyNumber: 29, position: "Free Safety", yearsAtSchool: "2002-2005", statsNote: "Senior starter • All-Pac-10 second team", gamesPlayed: 13 },
      careerEvents: [{ year: 2006, title: "Signed as UDFA by Philadelphia Eagles", eventType: "SIGNING" }],
    },
    {
      slug: "justin-wyatt",
      firstName: "Justin",
      lastName: "Wyatt",
      birthYear: 1984,
      hometown: "Compton, CA",
      highSchool: "Dominguez High School, Compton, CA",
      isFeatured: false,
      bio: "Starting cornerback and two-year starter in the secondary.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Citizen",
        statusNote: "Senior starting cornerback in 2005. Signed as UDFA with the Arizona Cardinals. Had a brief NFL career before leaving football.",
        sourceUrl: "https://usctrojans.com/sports/football/roster/justin-wyatt/1822",
      },
      membership: { role: "PLAYER", jerseyNumber: 24, position: "Cornerback", yearsAtSchool: "2002-2005", statsNote: "Senior starter • Two-year starting CB", gamesPlayed: 13 },
      careerEvents: [{ year: 2006, title: "Signed as UDFA with Arizona Cardinals", eventType: "SIGNING" }],
    },
    {
      slug: "dallas-sartz",
      firstName: "Dallas",
      lastName: "Sartz",
      birthYear: 1983,
      hometown: "Granite Bay, CA",
      highSchool: "Granite Bay High School, Granite Bay, CA",
      isFeatured: false,
      bio: "Starting strongside linebacker and two-time team captain who dislocated his shoulder early in the Arkansas game.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Real Estate Agent / Head Coach",
        currentEmployer: "The Bishop Real Estate Group",
        location: "Granite Bay, CA",
        statusNote: "Selected in the 5th round by the Washington Redskins in 2007. Also played for the Vikings and Seahawks. Now a real estate agent in Placer County, CA and head coach for girls' flag football at Granite Bay High School.",
        sourceUrl: "https://www.thebishoprealestategroup.com/dallas-sartz",
      },
      membership: { role: "PLAYER", jerseyNumber: 42, position: "Linebacker", yearsAtSchool: "2002-2005", statsNote: "Senior starter • 2x team captain • Dislocated shoulder vs Arkansas", gamesPlayed: 3 },
      careerEvents: [{ year: 2007, title: "Selected by Washington Redskins (5th round)", eventType: "DRAFT" }],
    },
    {
      slug: "fred-matua",
      firstName: "Fred",
      lastName: "Matua",
      birthYear: 1984,
      hometown: "Wilmington, CA",
      highSchool: "Banning High School, Wilmington, CA",
      isFeatured: false,
      bio: "Starting offensive guard and three-year starter (2003-05) who earned All-Pac-10 second team honors. Tragically passed away in 2012 at age 28.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Deceased",
        statusNote: "Starting guard who left after his junior year for the 2006 NFL Draft. Selected in the 7th round by the Detroit Lions. Tragically died on August 5, 2012 at age 28 due to a heart-related issue in Los Angeles.",
        sourceUrl: "https://usctrojans.com/news/2012/8/5/Ex_USC_Lineman_Fred_Matua_Dies",
      },
      membership: { role: "PLAYER", jerseyNumber: 51, position: "Offensive Guard", yearsAtSchool: "2003-2006", statsNote: "3-year starter • All-Pac-10 second team • 7th-round pick", gamesPlayed: 13 },
      careerEvents: [
        { year: 2006, title: "Selected by Detroit Lions (7th round)", eventType: "DRAFT" },
        { year: 2012, title: "Passed away at age 28 due to heart-related issue", eventType: "OTHER" },
      ],
    },
    {
      slug: "mario-danelo",
      firstName: "Mario",
      lastName: "Danelo",
      birthYear: 1985,
      hometown: "San Pedro, CA",
      highSchool: "San Pedro High School, San Pedro, CA",
      isFeatured: false,
      bio: "Starting placekicker who set an NCAA record with 83-of-86 PATs in 2005. Son of former NFL kicker Joe Danelo. Tragically passed away in 2007 at age 21.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Deceased",
        statusNote: "Set NCAA/Pac-10/USC record with 83-of-86 PATs and went 11-of-12 on field goals in 2005. Tragically died on January 6, 2007 at age 21, found at the bottom of a cliff near his family home in San Pedro. His father Joe Danelo was an NFL kicker for the NY Giants.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mario_Danelo",
      },
      membership: { role: "PLAYER", jerseyNumber: 19, position: "Placekicker", yearsAtSchool: "2004-2006", statsNote: "83-of-86 PATs (NCAA record) • 11-of-12 FGs in 2005", gamesPlayed: 13 },
      careerEvents: [{ year: 2007, title: "Passed away at age 21", eventType: "OTHER" }],
    },
    {
      slug: "tom-malone-usc",
      firstName: "Tom",
      lastName: "Malone",
      birthYear: 1984,
      hometown: "Lake Elsinore, CA",
      highSchool: "Temescal Canyon High School, Lake Elsinore, CA",
      isFeatured: false,
      bio: "Starting punter and four-year starter who became USC's first-ever All-American punter. First-team All-American and All-Pac-10 first team in 2005.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired Football Player",
        statusNote: "USC's first-ever All-American punter. Signed as UDFA by the 49ers in 2006, also played for the Patriots, Seahawks, Rams, and in the UFL (2006-2012).",
        sourceUrl: "https://en.wikipedia.org/wiki/Tom_Malone_(American_football)",
      },
      membership: { role: "PLAYER", jerseyNumber: 14, position: "Punter", yearsAtSchool: "2002-2005", statsNote: "4-year starter • First-team All-American • First All-American punter in USC history", gamesPlayed: 13 },
      careerEvents: [{ year: 2006, title: "Signed as UDFA by San Francisco 49ers", eventType: "SIGNING" }],
    },
    {
      slug: "chris-mcfoy",
      firstName: "Chris",
      lastName: "McFoy",
      birthYear: 1983,
      hometown: "Chino, CA",
      highSchool: "Chino High School, Chino, CA",
      isFeatured: false,
      bio: "Starting wide receiver who started 6 games and caught 17 passes for 172 yards in 2005.",
      status: {
        occupationType: "ENTREPRENEUR_BUSINESS",
        currentTitle: "Regional General Agent",
        currentEmployer: "American Income Life Insurance Company",
        location: "California",
        statusNote: "Signed as a free agent by the Oakland Raiders in 2007 and played in the last 3 games. After football, he transitioned to insurance sales and currently works as a Regional General Agent at American Income Life Insurance Company.",
        sourceUrl: "https://en.wikipedia.org/wiki/Chris_McFoy",
      },
      membership: { role: "PLAYER", jerseyNumber: 82, position: "Wide Receiver", yearsAtSchool: "2002-2005", statsNote: "Started 6 games • 17 rec, 172 yds in 2005", gamesPlayed: 13 },
      careerEvents: [{ year: 2007, title: "Signed as free agent with Oakland Raiders", eventType: "SIGNING" }],
    },
    {
      slug: "patrick-turner",
      firstName: "Patrick",
      lastName: "Turner",
      birthYear: 1987,
      hometown: "Madison, TN",
      highSchool: "Goodpasture Christian School, Madison, TN",
      isFeatured: false,
      bio: "A freshman backup wide receiver who caught 12 passes for 170 yards and 2 TDs in 2005 and later became a 3rd-round NFL pick.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Private Citizen",
        statusNote: "Selected 87th overall by the Miami Dolphins in 2009, Turner caught just 10 passes in 24 NFL games before leaving football in 2012. A native of Madison, TN who attended Goodpasture Christian School, Turner has chosen to live privately since his playing career ended. Extensive searches have not revealed his current profession.",
        sourceUrl: "https://en.wikipedia.org/wiki/Patrick_Turner",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Wide Receiver", yearsAtSchool: "2005-2008", statsNote: "Freshman • 12 rec, 170 yds, 2 TD • Later 3rd-round pick", gamesPlayed: 13 },
      careerEvents: [{ year: 2009, title: "Selected by Miami Dolphins (3rd round, #87)", eventType: "DRAFT" }],
    },
    {
      slug: "chauncey-washington",
      firstName: "Chauncey",
      lastName: "Washington",
      birthYear: 1985,
      hometown: "Torrance, CA",
      highSchool: "South Torrance High School, Torrance, CA",
      isFeatured: false,
      bio: "Backup running back behind Reggie Bush and LenDale White who later became a 7th-round NFL pick.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NFL Player",
        statusNote: "Selected in the 7th round by the Jacksonville Jaguars in the 2008 NFL Draft. Also played for the Rams and Cowboys.",
        sourceUrl: "https://en.wikipedia.org/wiki/Chauncey_Washington",
      },
      membership: { role: "PLAYER", jerseyNumber: 23, position: "Running Back", yearsAtSchool: "2003-2007", statsNote: "Backup RB behind Bush and White", gamesPlayed: 13 },
      careerEvents: [{ year: 2008, title: "Selected by Jacksonville Jaguars (7th round)", eventType: "DRAFT" }],
    },
    {
      slug: "kevin-thomas-usc",
      firstName: "Kevin",
      lastName: "Thomas",
      birthYear: 1986,
      hometown: "Oxnard, CA",
      highSchool: "Pacifica High School, Oxnard, CA",
      isFeatured: false,
      bio: "A freshman reserve cornerback who played in 9 games on special teams and later became a 3rd-round NFL pick.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NFL Player",
        statusNote: "Selected in the 3rd round by the Indianapolis Colts in the 2010 NFL Draft after developing into a starter at USC.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kevin_Thomas_(cornerback,_born_1986)",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Cornerback", yearsAtSchool: "2005-2009", statsNote: "Freshman reserve • Later 3rd-round pick by Colts", gamesPlayed: 9 },
      careerEvents: [{ year: 2010, title: "Selected by Indianapolis Colts (3rd round)", eventType: "DRAFT" }],
    },
    {
      slug: "steve-sarkisian",
      firstName: "Steve",
      lastName: "Sarkisian",
      birthYear: 1974,
      hometown: "Torrance, CA",
      highSchool: "West Torrance High School, Torrance, CA",
      isFeatured: true,
      bio: "Assistant head coach and quarterbacks coach who returned to USC in 2005. Coached Matt Leinart, Mark Sanchez, and John David Booty.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Football Coach",
        currentEmployer: "University of Texas",
        location: "Austin, TX",
        statusNote: "After coaching USC's quarterbacks (2005-08), Sarkisian became head coach at Washington (2009-13) and USC (2014-15) before being fired for alcohol issues. He rehabilitated his career as Alabama's OC (2016, 2019-20), then was named head coach at Texas in 2021, leading the Longhorns to the College Football Playoff.",
        sourceUrl: "https://en.wikipedia.org/wiki/Steve_Sarkisian",
      },
      membership: { role: "ASSISTANT_COACH", position: "Assistant Head Coach / Quarterbacks Coach", yearsAtSchool: "2005-2008", statsNote: "Coached Leinart, Sanchez, and Booty" },
      careerEvents: [
        { year: 2009, title: "Named head coach at University of Washington", eventType: "CAREER" },
        { year: 2014, title: "Named head coach at USC", eventType: "CAREER" },
        { year: 2021, title: "Named head coach at University of Texas", eventType: "CAREER" },
      ],
    },
  ],
};
