import type { TeamSeed } from "./types";

export const virginiaBasketball2012: TeamSeed = {
  slug: "virginia-basketball-2012",
  name: "Virginia Cavaliers",
  season: "2011-2012",
  sport: "Men's Basketball",
  school: "University of Virginia",
  conference: "ACC",
  accomplishment: "2011-2012 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/258.png",
  mascotName: "Cavalier",
  people: [
    {
      slug: "mike-scott-uva",
      firstName: "Mike",
      lastName: "Scott",
      birthYear: 1988,
      hometown: "United States",
      highSchool: "United States",
      bio: "Senior forward and UVA's leading scorer. ACC honorable mention.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Retired NBA Player",
        location: "Virginia",
        statusNote: "8-year NBA career. 'The Emoji Man'.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mike_Scott",
      },
      membership: { role: "PLAYER", jerseyNumber: 23, position: "Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 15, reboundsPerGame: 8, assistsPerGame: 1.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 15, reboundsPerGame: 8, assistsPerGame: 1.2 },
      ],
      careerEvents: [],
    },
    {
      slug: "joe-harris",
      firstName: "Joe",
      lastName: "Harris",
      birthYear: 1991,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore wing developing his shooting.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        location: "Detroit, MI",
        statusNote: "Became elite NBA shooter. 2x 3-Point Contest winner.",
        sourceUrl: "https://en.wikipedia.org/wiki/Joe_Harris",
      },
      membership: { role: "PLAYER", jerseyNumber: 25, position: "Guard/Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 9.5, reboundsPerGame: 3.5, assistsPerGame: 1.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 9.5, reboundsPerGame: 3.5, assistsPerGame: 1.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "malcolm-brogdon",
      firstName: "Malcolm",
      lastName: "Brogdon",
      birthYear: 1992,
      hometown: "United States",
      highSchool: "United States",
      bio: "Freshman guard. Future ACC POY and NBA ROY.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        location: "Washington, DC",
        statusNote: "2017 NBA ROY as #36 pick — lowest ever to win. Master's in public policy.",
        sourceUrl: "https://en.wikipedia.org/wiki/Malcolm_Brogdon",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 3.5, reboundsPerGame: 1.5, assistsPerGame: 1 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 3.5, reboundsPerGame: 1.5, assistsPerGame: 1 },
      ],
      careerEvents: [],
    },
    {
      slug: "tony-bennett-uva",
      firstName: "Tony",
      lastName: "Bennett",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Architect of the Pack Line defense who led Virginia to the 2019 national championship — redemption after the 2018 UMBC loss.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Still coaching at Virginia. 2019 NCAA Champion.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tony_Bennett",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2026" },
      seasonStats: [
        { level: "COACHING", teamName: "Virginia Cavaliers", season: "2011-2012", yearLabel: "2011-2012", sortOrder: 204 },
      ],
      careerEvents: [],
    },
  ],
};
