import type { TeamSeed } from "./types";

export const virginiaBasketball2023: TeamSeed = {
  slug: "virginia-basketball-2023",
  name: "Virginia Cavaliers",
  season: "2022-2023",
  sport: "Men's Basketball",
  school: "University of Virginia",
  conference: "ACC",
  accomplishment: "2022-2023 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/258.png",
  mascotName: "Cavalier",
  people: [
    {
      slug: "reece-beekman",
      firstName: "Reece",
      lastName: "Beekman",
      birthYear: 2002,
      hometown: "United States",
      highSchool: "United States",
      bio: "Junior guard and elite defender.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        location: "United States",
        statusNote: "ACC DPOY. 2024 NBA Draft pick.",
        sourceUrl: "https://en.wikipedia.org/wiki/Reece_Beekman",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 9.5, reboundsPerGame: 3, assistsPerGame: 5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 9.5, reboundsPerGame: 3, assistsPerGame: 5 },
      ],
      careerEvents: [],
    },
    {
      slug: "kihei-clark",
      firstName: "Kihei",
      lastName: "Clark",
      birthYear: 2000,
      hometown: "United States",
      highSchool: "United States",
      bio: "5th-year senior. UVA's all-time leader in assists, wins, 3-pointers.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        location: "Belgium",
        statusNote: "Most wins by any player in UVA history.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kihei_Clark",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Point Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 11.5, reboundsPerGame: 3, assistsPerGame: 4.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 11.5, reboundsPerGame: 3, assistsPerGame: 4.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "tony-bennett-uva",
      firstName: "Tony",
      lastName: "Bennett",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Architect of the Pack Line defense who led Virginia to the 2019 national championship — redemption after the 2018 UMBC loss.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Still coaching at Virginia. 2019 NCAA Champion.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tony_Bennett",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2026" },
      seasonStats: [
        { level: "COACHING", teamName: "Virginia Cavaliers", season: "2022-2023", yearLabel: "2022-2023", sortOrder: 215 },
      ],
      careerEvents: [],
    },
  ],
};
