import type { TeamSeed } from "./types";

export const virginiaBasketball2009: TeamSeed = {
  slug: "virginia-basketball-2009",
  name: "Virginia Cavaliers",
  season: "2008-2009",
  sport: "Men's Basketball",
  school: "University of Virginia",
  conference: "ACC",
  accomplishment: "2008-2009 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/258.png",
  mascotName: "Cavalier",
  people: [
    {
      slug: "sylven-landesberg",
      firstName: "Sylven",
      lastName: "Landesberg",
      birthYear: 1990,
      hometown: "United States",
      highSchool: "United States",
      bio: "Freshman guard who was ACC Rookie of the Year. Later dismissed from team.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "Overseas",
        statusNote: "ACC ROY as freshman. Dismissed from UVA. Long overseas career in Israel, Turkey, Italy.",
        sourceUrl: "https://en.wikipedia.org/wiki/Sylven_Landesberg",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 17.3, reboundsPerGame: 4.8, assistsPerGame: 2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 17.3, reboundsPerGame: 4.8, assistsPerGame: 2 },
      ],
      careerEvents: [],
    },
    {
      slug: "sammy-zeglinski",
      firstName: "Sammy",
      lastName: "Zeglinski",
      birthYear: 1989,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore guard and perimeter shooter.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "Virginia",
        statusNote: "Played 4 years at UVA. Now in business in Virginia.",
        sourceUrl: "https://en.wikipedia.org/wiki/Sammy_Zeglinski",
      },
      membership: { role: "PLAYER", jerseyNumber: 13, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 8.5, reboundsPerGame: 2.5, assistsPerGame: 2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 8.5, reboundsPerGame: 2.5, assistsPerGame: 2 },
      ],
      careerEvents: [],
    },
    {
      slug: "tony-bennett-uva",
      firstName: "Tony",
      lastName: "Bennett",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Architect of the Pack Line defense who led Virginia to the 2019 national championship — redemption after the 2018 UMBC loss.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Still coaching at Virginia. 2019 NCAA Champion.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tony_Bennett",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2026" },
      seasonStats: [
        { level: "COACHING", teamName: "Virginia Cavaliers", season: "2008-2009", yearLabel: "2008-2009", sortOrder: 201 },
      ],
      careerEvents: [],
    },
  ],
};
