import type { TeamSeed } from "./types";

export const virginiaBasketball2017: TeamSeed = {
  slug: "virginia-basketball-2017",
  name: "Virginia Cavaliers",
  season: "2016-2017",
  sport: "Men's Basketball",
  school: "University of Virginia",
  conference: "ACC",
  accomplishment: "2016-2017 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/258.png",
  mascotName: "Cavalier",
  people: [
    {
      slug: "london-perrantes",
      firstName: "London",
      lastName: "Perrantes",
      birthYear: 1994,
      hometown: "United States",
      highSchool: "United States",
      bio: "Senior captain and 4-year starter.",
      status: {
        occupationType: "COACH",
        currentTitle: "Coach",
        location: "Virginia",
        statusNote: "UVA's all-time starting games leader. Now coaching.",
        sourceUrl: "https://en.wikipedia.org/wiki/London_Perrantes",
      },
      membership: { role: "PLAYER", jerseyNumber: 32, position: "Point Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 12.5, reboundsPerGame: 2.5, assistsPerGame: 4 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 12.5, reboundsPerGame: 2.5, assistsPerGame: 4 },
      ],
      careerEvents: [],
    },
    {
      slug: "isaiah-wilkins",
      firstName: "Isaiah",
      lastName: "Wilkins",
      birthYear: 1996,
      hometown: "United States",
      highSchool: "United States",
      bio: "Junior forward and son of Dominique Wilkins.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Professional",
        location: "Atlanta, GA",
        statusNote: "Son of NBA legend. Played overseas briefly.",
        sourceUrl: "https://en.wikipedia.org/wiki/Isaiah_Wilkins",
      },
      membership: { role: "PLAYER", jerseyNumber: 21, position: "Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 5.5, reboundsPerGame: 5, assistsPerGame: 0.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 5.5, reboundsPerGame: 5, assistsPerGame: 0.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "kyle-guy",
      firstName: "Kyle",
      lastName: "Guy",
      birthYear: 1997,
      hometown: "United States",
      highSchool: "United States",
      bio: "Freshman shooter from Indianapolis. Future Final Four MOP.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        location: "Noblesville, IN",
        statusNote: "2019 Final Four MOP. Now with Noblesville Boom (G League).",
        sourceUrl: "https://en.wikipedia.org/wiki/Kyle_Guy",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 8, reboundsPerGame: 2, assistsPerGame: 1.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 8, reboundsPerGame: 2, assistsPerGame: 1.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "ty-jerome",
      firstName: "Ty",
      lastName: "Jerome",
      birthYear: 1997,
      hometown: "United States",
      highSchool: "United States",
      bio: "Freshman PG from New Rochelle. Future #24 pick.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        location: "Memphis, TN",
        statusNote: "#24 pick. Averaging 20.1 PPG for Grizzlies in 2025-26.",
        sourceUrl: "https://en.wikipedia.org/wiki/Ty_Jerome",
      },
      membership: { role: "PLAYER", jerseyNumber: 11, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 4.5, reboundsPerGame: 1.5, assistsPerGame: 2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 4.5, reboundsPerGame: 1.5, assistsPerGame: 2 },
      ],
      careerEvents: [],
    },
    {
      slug: "deandre-hunter",
      firstName: "De'Andre",
      lastName: "Hunter",
      birthYear: 1997,
      hometown: "United States",
      highSchool: "United States",
      bio: "Freshman forward. Future #4 pick.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        location: "Sacramento, CA",
        statusNote: "#4 pick by Hawks. Now with Kings.",
        sourceUrl: "https://en.wikipedia.org/wiki/De'Andre_Hunter",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 2, reboundsPerGame: 1, assistsPerGame: 0.3 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 2, reboundsPerGame: 1, assistsPerGame: 0.3 },
      ],
      careerEvents: [],
    },
    {
      slug: "tony-bennett-uva",
      firstName: "Tony",
      lastName: "Bennett",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Architect of the Pack Line defense who led Virginia to the 2019 national championship — redemption after the 2018 UMBC loss.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Still coaching at Virginia. 2019 NCAA Champion.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tony_Bennett",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2026" },
      seasonStats: [
        { level: "COACHING", teamName: "Virginia Cavaliers", season: "2016-2017", yearLabel: "2016-2017", sortOrder: 209 },
      ],
      careerEvents: [],
    },
  ],
};
