import type { TeamSeed } from "./types";

export const virginiaBasketball2013: TeamSeed = {
  slug: "virginia-basketball-2013",
  name: "Virginia Cavaliers",
  season: "2012-2013",
  sport: "Men's Basketball",
  school: "University of Virginia",
  conference: "ACC",
  accomplishment: "2012-2013 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/258.png",
  mascotName: "Cavalier",
  people: [
    {
      slug: "joe-harris",
      firstName: "Joe",
      lastName: "Harris",
      birthYear: 1991,
      hometown: "United States",
      highSchool: "United States",
      bio: "Junior wing becoming team's best scorer.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        location: "Detroit, MI",
        statusNote: "2x NBA 3-Point Contest winner.",
        sourceUrl: "https://en.wikipedia.org/wiki/Joe_Harris",
      },
      membership: { role: "PLAYER", jerseyNumber: 25, position: "Guard/Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 11, reboundsPerGame: 4, assistsPerGame: 2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 11, reboundsPerGame: 4, assistsPerGame: 2 },
      ],
      careerEvents: [],
    },
    {
      slug: "malcolm-brogdon",
      firstName: "Malcolm",
      lastName: "Brogdon",
      birthYear: 1992,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore guard developing into a leader.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        location: "Washington, DC",
        statusNote: "NBA ROY. Founded Brogdon Family Foundation for East African water wells.",
        sourceUrl: "https://en.wikipedia.org/wiki/Malcolm_Brogdon",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 6.5, reboundsPerGame: 2, assistsPerGame: 1.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 6.5, reboundsPerGame: 2, assistsPerGame: 1.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "akil-mitchell",
      firstName: "Akil",
      lastName: "Mitchell",
      birthYear: 1992,
      hometown: "United States",
      highSchool: "United States",
      bio: "Junior forward from Charlotte. Physical interior player.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "New Zealand",
        statusNote: "Long career in NZ basketball. Survived horrific eye injury in 2017.",
        sourceUrl: "https://en.wikipedia.org/wiki/Akil_Mitchell",
      },
      membership: { role: "PLAYER", jerseyNumber: 25, position: "Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 7.5, reboundsPerGame: 6, assistsPerGame: 0.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 7.5, reboundsPerGame: 6, assistsPerGame: 0.8 },
      ],
      careerEvents: [],
    },
    {
      slug: "tony-bennett-uva",
      firstName: "Tony",
      lastName: "Bennett",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Architect of the Pack Line defense who led Virginia to the 2019 national championship — redemption after the 2018 UMBC loss.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Still coaching at Virginia. 2019 NCAA Champion.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tony_Bennett",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2026" },
      seasonStats: [
        { level: "COACHING", teamName: "Virginia Cavaliers", season: "2012-2013", yearLabel: "2012-2013", sortOrder: 205 },
      ],
      careerEvents: [],
    },
  ],
};
