import type { TeamSeed } from "./types";

export const virginiaBasketball2018: TeamSeed = {
  slug: "virginia-basketball-2018",
  name: "Virginia Cavaliers",
  season: "2017-2018",
  sport: "Men's Basketball",
  school: "University of Virginia",
  conference: "ACC",
  accomplishment: "2017-2018 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/258.png",
  mascotName: "Cavalier",
  people: [
    {
      slug: "kyle-guy",
      firstName: "Kyle",
      lastName: "Guy",
      birthYear: 1997,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore shooter and growing scorer.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        location: "Noblesville, IN",
        statusNote: "2019 Final Four MOP. Now G League.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kyle_Guy",
      },
      membership: { role: "PLAYER", jerseyNumber: 5, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 14, reboundsPerGame: 3, assistsPerGame: 2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 14, reboundsPerGame: 3, assistsPerGame: 2 },
      ],
      careerEvents: [],
    },
    {
      slug: "ty-jerome",
      firstName: "Ty",
      lastName: "Jerome",
      birthYear: 1997,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore PG with growing confidence.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        location: "Memphis, TN",
        statusNote: "20.1 PPG for Grizzlies. #24 pick.",
        sourceUrl: "https://en.wikipedia.org/wiki/Ty_Jerome",
      },
      membership: { role: "PLAYER", jerseyNumber: 11, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 10.5, reboundsPerGame: 3.5, assistsPerGame: 3.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 10.5, reboundsPerGame: 3.5, assistsPerGame: 3.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "deandre-hunter",
      firstName: "De'Andre",
      lastName: "Hunter",
      birthYear: 1997,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore forward. Redshirted in 2018 due to wrist injury.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        location: "Sacramento, CA",
        statusNote: "Redshirted this year. Returned to win 2019 title.",
        sourceUrl: "https://en.wikipedia.org/wiki/De'Andre_Hunter",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 0, reboundsPerGame: 0, assistsPerGame: 0 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 0, reboundsPerGame: 0, assistsPerGame: 0 },
      ],
      careerEvents: [],
    },
    {
      slug: "devon-hall",
      firstName: "Devon",
      lastName: "Hall",
      birthYear: 1995,
      hometown: "United States",
      highSchool: "United States",
      bio: "Senior guard and team captain. UMBC loss devastated this team.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Professional",
        location: "United States",
        statusNote: "Played in G League and overseas after UVA. Part of the infamous UMBC loss.",
        sourceUrl: "https://en.wikipedia.org/wiki/Devon_Hall",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 11.5, reboundsPerGame: 3.5, assistsPerGame: 3 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 11.5, reboundsPerGame: 3.5, assistsPerGame: 3 },
      ],
      careerEvents: [],
    },
    {
      slug: "tony-bennett-uva",
      firstName: "Tony",
      lastName: "Bennett",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Architect of the Pack Line defense who led Virginia to the 2019 national championship — redemption after the 2018 UMBC loss.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Still coaching at Virginia. 2019 NCAA Champion.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tony_Bennett",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2026" },
      seasonStats: [
        { level: "COACHING", teamName: "Virginia Cavaliers", season: "2017-2018", yearLabel: "2017-2018", sortOrder: 210 },
      ],
      careerEvents: [],
    },
  ],
};
