import type { TeamSeed } from "./types";

export const virginiaBasketball2020: TeamSeed = {
  slug: "virginia-basketball-2020",
  name: "Virginia Cavaliers",
  season: "2019-2020",
  sport: "Men's Basketball",
  school: "University of Virginia",
  conference: "ACC",
  accomplishment: "2019-2020 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/258.png",
  mascotName: "Cavalier",
  people: [
    {
      slug: "mamadi-diakite",
      firstName: "Mamadi",
      lastName: "Diakite",
      birthYear: 1996,
      hometown: "United States",
      highSchool: "United States",
      bio: "Senior from Guinea. Hit iconic buzzer-beater vs Purdue in 2019.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "Europe",
        statusNote: "#46 pick by Bucks. Playing overseas.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mamadi_Diakite",
      },
      membership: { role: "PLAYER", jerseyNumber: 25, position: "Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 13, reboundsPerGame: 6.5, assistsPerGame: 1 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 13, reboundsPerGame: 6.5, assistsPerGame: 1 },
      ],
      careerEvents: [],
    },
    {
      slug: "kihei-clark",
      firstName: "Kihei",
      lastName: "Clark",
      birthYear: 2000,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore PG. Famous for half-court pass vs Purdue.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        location: "Kortrijk, Belgium",
        statusNote: "UVA all-time assists leader. Now playing in Belgium.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kihei_Clark",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Point Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 10, reboundsPerGame: 3, assistsPerGame: 5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 10, reboundsPerGame: 3, assistsPerGame: 5 },
      ],
      careerEvents: [],
    },
    {
      slug: "jay-huff",
      firstName: "Jay",
      lastName: "Huff",
      birthYear: 1998,
      hometown: "United States",
      highSchool: "United States",
      bio: "Junior stretch-five with shot-blocking ability.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "United States",
        statusNote: "Played for Wizards. G League and overseas.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jay_Huff",
      },
      membership: { role: "PLAYER", jerseyNumber: 30, position: "Center", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 8, reboundsPerGame: 4, assistsPerGame: 0.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 8, reboundsPerGame: 4, assistsPerGame: 0.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "tony-bennett-uva",
      firstName: "Tony",
      lastName: "Bennett",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Architect of the Pack Line defense who led Virginia to the 2019 national championship — redemption after the 2018 UMBC loss.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Still coaching at Virginia. 2019 NCAA Champion.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tony_Bennett",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2026" },
      seasonStats: [
        { level: "COACHING", teamName: "Virginia Cavaliers", season: "2019-2020", yearLabel: "2019-2020", sortOrder: 212 },
      ],
      careerEvents: [],
    },
  ],
};
