import type { TeamSeed } from "./types";

export const virginiaBasketball2022: TeamSeed = {
  slug: "virginia-basketball-2022",
  name: "Virginia Cavaliers",
  season: "2021-2022",
  sport: "Men's Basketball",
  school: "University of Virginia",
  conference: "ACC",
  accomplishment: "2021-2022 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/258.png",
  mascotName: "Cavalier",
  people: [
    {
      slug: "kihei-clark",
      firstName: "Kihei",
      lastName: "Clark",
      birthYear: 2000,
      hometown: "United States",
      highSchool: "United States",
      bio: "Senior PG. UVA's all-time assists and wins leader.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        location: "Belgium",
        statusNote: "Most decorated PG in UVA history. Now in Belgium.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kihei_Clark",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Point Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 10, reboundsPerGame: 3, assistsPerGame: 4.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 10, reboundsPerGame: 3, assistsPerGame: 4.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "jayden-gardner",
      firstName: "Jayden",
      lastName: "Gardner",
      birthYear: 1999,
      hometown: "United States",
      highSchool: "United States",
      bio: "Grad transfer from East Carolina. Physical interior scorer.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "Overseas",
        statusNote: "ECU transfer who provided interior scoring for UVA.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jayden_Gardner",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 12, reboundsPerGame: 5.5, assistsPerGame: 1 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 12, reboundsPerGame: 5.5, assistsPerGame: 1 },
      ],
      careerEvents: [],
    },
    {
      slug: "reece-beekman",
      firstName: "Reece",
      lastName: "Beekman",
      birthYear: 2002,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore guard and ACC Defensive POY. Future NBA draft pick.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        location: "United States",
        statusNote: "ACC DPOY. Drafted in 2024 NBA Draft.",
        sourceUrl: "https://en.wikipedia.org/wiki/Reece_Beekman",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 8, reboundsPerGame: 2.5, assistsPerGame: 4 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 8, reboundsPerGame: 2.5, assistsPerGame: 4 },
      ],
      careerEvents: [],
    },
    {
      slug: "tony-bennett-uva",
      firstName: "Tony",
      lastName: "Bennett",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Architect of the Pack Line defense who led Virginia to the 2019 national championship — redemption after the 2018 UMBC loss.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Still coaching at Virginia. 2019 NCAA Champion.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tony_Bennett",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2026" },
      seasonStats: [
        { level: "COACHING", teamName: "Virginia Cavaliers", season: "2021-2022", yearLabel: "2021-2022", sortOrder: 214 },
      ],
      careerEvents: [],
    },
  ],
};
