import type { TeamSeed } from "./types";

export const virginiaBasketball2014: TeamSeed = {
  slug: "virginia-basketball-2014",
  name: "Virginia Cavaliers",
  season: "2013-2014",
  sport: "Men's Basketball",
  school: "University of Virginia",
  conference: "ACC",
  accomplishment: "Sweet 16, ACC Regular Season Champions (30-7)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/258.png",
  mascotName: "Cavalier",
  people: [
    {
      slug: "joe-harris",
      firstName: "Joe",
      lastName: "Harris",
      birthYear: 1991,
      hometown: "Chelan, WA",
      highSchool: "Chelan High School, Chelan, WA",
      isFeatured: true,
      bio: "The senior sharpshooter from small-town Washington state who became one of the best three-point shooters in NBA history. Won 2 NBA Three-Point Contests (2019, 2021) and was a key piece on Brooklyn's superteam alongside KD and Kyrie.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard / Forward",
        currentEmployer: "Detroit Pistons",
        league: "NBA",
        location: "Detroit, MI",
        statusNote: "Selected #33 overall by the Cleveland Cavaliers in 2014, Harris became one of the NBA's premier three-point shooters with the Brooklyn Nets. He won back-to-back NBA Three-Point Contests in 2019 and 2021 and led the league in three-point percentage in 2016-17 (.474) and 2018-19 (.475). After 8 seasons with the Nets, he signed with the Pistons. His journey from Chelan, Washington (population 3,900) to NBA stardom is one of the most improbable paths in recent basketball history.",
        sourceUrl: "https://en.wikipedia.org/wiki/Joe_Harris_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 25, position: "Guard / Forward", yearsAtSchool: "2010-2014", statsNote: "2x NBA 3-Point Contest winner • ACC POY candidate • Sweet 16", gamesPlayed: 37, pointsPerGame: 11.7, reboundsPerGame: 4.2, assistsPerGame: 2.3 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "2013-14", yearLabel: "Senior", sortOrder: 204, gamesPlayed: 37, minutesPerGame: 32.0, pointsPerGame: 11.7, reboundsPerGame: 4.2, assistsPerGame: 2.3, threePointPct: 0.419, fieldGoalPct: 0.477 },
        { level: "PROFESSIONAL", teamName: "Brooklyn Nets", season: "2018-19", yearLabel: "2018-19 (3PT Contest winner)", sortOrder: 305, gamesPlayed: 76, pointsPerGame: 13.7, threePointPct: 0.475 },
      ],
      careerEvents: [
        { year: 2014, title: "Selected #33 overall by the Cleveland Cavaliers", eventType: "DRAFT", month: 6, day: 26 },
        { year: 2019, title: "Won NBA Three-Point Contest", eventType: "AWARD" },
        { year: 2021, title: "Won second NBA Three-Point Contest", eventType: "AWARD" },
      ],
    },
    {
      slug: "malcolm-brogdon",
      firstName: "Malcolm",
      lastName: "Brogdon",
      birthYear: 1992,
      hometown: "Atlanta, GA",
      highSchool: "Greater Atlanta Christian School, Norcross, GA",
      isFeatured: true,
      bio: "A sophomore guard who was just beginning to emerge during the 2014 Sweet 16 run. Returned for 2 more years and won the 2016 ACC Player of the Year before becoming the 2017 NBA Rookie of the Year with Milwaukee — the lowest draft pick (#36) ever to win the award.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        currentEmployer: "Washington Wizards",
        league: "NBA",
        location: "Washington, DC",
        statusNote: "Selected #36 overall by the Milwaukee Bucks in 2016, Brogdon won the 2017 NBA Rookie of the Year — the lowest draft pick ever to win it. He's played for the Bucks, Pacers, Celtics, Trail Blazers, and Wizards over 8+ NBA seasons. Off the court, he founded the Brogdon Family Foundation to build clean water wells in East Africa and is widely regarded as one of the most socially conscious players in the NBA. He has a master's degree from UVA in public policy.",
        sourceUrl: "https://en.wikipedia.org/wiki/Malcolm_Brogdon",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Guard", yearsAtSchool: "2012-2016", statsNote: "Sophomore • Future ACC POY • NBA ROY (#36 pick) • Sweet 16", gamesPlayed: 37, pointsPerGame: 8.8, reboundsPerGame: 3.0, assistsPerGame: 1.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "2013-14", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 37, minutesPerGame: 24.0, pointsPerGame: 8.8, reboundsPerGame: 3.0, assistsPerGame: 1.8 },
        { level: "PROFESSIONAL", teamName: "Milwaukee Bucks", season: "2016-17", yearLabel: "2016-17 (ROY)", sortOrder: 301, gamesPlayed: 75, pointsPerGame: 10.2, reboundsPerGame: 2.8, assistsPerGame: 4.2 },
      ],
      careerEvents: [
        { year: 2016, title: "Won ACC Player of the Year at Virginia", eventType: "AWARD" },
        { year: 2016, title: "Selected #36 overall by the Milwaukee Bucks", eventType: "DRAFT" },
        { year: 2017, title: "Won NBA Rookie of the Year (lowest pick ever)", eventType: "AWARD" },
      ],
    },
    {
      slug: "london-perrantes",
      firstName: "London",
      lastName: "Perrantes",
      birthYear: 1994,
      hometown: "Walnut, CA",
      highSchool: "Los Altos High School, Hacienda Heights, CA",
      bio: "A freshman point guard from California who would go on to start for 4 years and become the floor general of Virginia's rise to national prominence under Tony Bennett.",
      status: {
        occupationType: "COACH",
        currentTitle: "Graduate Assistant / Coach",
        location: "Virginia",
        statusNote: "After 4 years at Virginia, Perrantes played briefly in the G League and overseas before transitioning to coaching. He is one of the most decorated players in UVA history, starting for all four years of his career. His leadership helped bridge the gap between Virginia's early Bennett years and the championship era.",
        sourceUrl: "https://virginiasports.com/sports/mbball/roster/player/london-perrantes",
      },
      membership: { role: "PLAYER", jerseyNumber: 32, position: "Point Guard", yearsAtSchool: "2013-2017", statsNote: "Freshman • 4-year starter • Bennett's floor general • Sweet 16", gamesPlayed: 37, pointsPerGame: 5.5, reboundsPerGame: 2.0, assistsPerGame: 3.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "2013-14", yearLabel: "Freshman", sortOrder: 201, gamesPlayed: 37, minutesPerGame: 22.0, pointsPerGame: 5.5, assistsPerGame: 3.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "justin-anderson",
      firstName: "Justin",
      lastName: "Anderson",
      birthYear: 1993,
      hometown: "Montross, VA",
      highSchool: "Montross, VA",
      bio: "A sophomore wing whose athleticism and defensive ability made him a perfect fit for the Pack Line defense. Returned for his junior year and was selected #21 overall by Dallas.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "G League / Overseas",
        location: "United States",
        statusNote: "Selected #21 overall by the Dallas Mavericks in 2015, Anderson played 5 NBA seasons with the Mavericks, 76ers, Hawks, and Nets. He has continued playing in the G League and overseas. A local Virginia product who was one of the most athletic players in the ACC during his time at UVA.",
        sourceUrl: "https://en.wikipedia.org/wiki/Justin_Anderson_(basketball)",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Guard / Forward", yearsAtSchool: "2012-2015", statsNote: "Sophomore • Future #21 pick • Athletic wing • Sweet 16", gamesPlayed: 37, pointsPerGame: 7.5, reboundsPerGame: 3.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "2013-14", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 37, minutesPerGame: 20.0, pointsPerGame: 7.5, reboundsPerGame: 3.2, fieldGoalPct: 0.470 },
      ],
      careerEvents: [
        { year: 2015, title: "Selected #21 overall by the Dallas Mavericks", eventType: "DRAFT" },
      ],
    },
    {
      slug: "akil-mitchell",
      firstName: "Akil",
      lastName: "Mitchell",
      birthYear: 1992,
      hometown: "Charlotte, NC",
      highSchool: "Olympic High School, Charlotte, NC",
      bio: "A senior forward from Charlotte who was Virginia's emotional leader and most physical interior player. His rebounding and toughness set the tone for the Pack Line defense.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Professional Basketball Player",
        league: "Overseas",
        location: "New Zealand",
        statusNote: "After graduating from UVA, Mitchell played professionally in the NBA G League and overseas in New Zealand and Australia. He suffered a horrific eye injury during a game in New Zealand's NBL in 2017 but recovered and continued playing. He has become a respected figure in the NZ basketball community.",
        sourceUrl: "https://en.wikipedia.org/wiki/Akil_Mitchell",
      },
      membership: { role: "PLAYER", jerseyNumber: 25, position: "Power Forward", yearsAtSchool: "2010-2014", statsNote: "Senior captain • Physical interior • Charlotte native • Sweet 16", gamesPlayed: 37, pointsPerGame: 8.8, reboundsPerGame: 7.0 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "2013-14", yearLabel: "Senior", sortOrder: 204, gamesPlayed: 37, minutesPerGame: 27.0, pointsPerGame: 8.8, reboundsPerGame: 7.0, fieldGoalPct: 0.535 },
      ],
      careerEvents: [],
    },
    {
      slug: "tony-bennett-uva",
      firstName: "Tony",
      lastName: "Bennett",
      birthYear: 1969,
      hometown: "Green Bay, WI",
      highSchool: "Preble High School, Green Bay, WI",
      isFeatured: true,
      bio: "In just his fifth season at Virginia, Bennett won the ACC regular season title and reached the Sweet 16. This season established UVA as a legitimate ACC power and laid the foundation for the 2019 national championship.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "University of Virginia",
        location: "Charlottesville, VA",
        statusNote: "Tony Bennett has been Virginia's head coach since 2009. The 2014 season (30-7, ACC regular season champs) was the breakout year that announced Virginia as a national contender. He went on to win the 2019 national championship — one year after the infamous UMBC loss.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tony_Bennett_(basketball)",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-present", statsNote: "30-7 • ACC Champs • Sweet 16 • Building a dynasty" },
      seasonStats: [
        { level: "COACHING", teamName: "Virginia Cavaliers", season: "2013-14", yearLabel: "2013-14", sortOrder: 205, wins: 30, losses: 7, tournamentResult: "Sweet 16, ACC Regular Season Champions" },
      ],
      careerEvents: [],
    },
  ],
};
