import type { TeamSeed } from "./types";

export const virginiaBasketball2016: TeamSeed = {
  slug: "virginia-basketball-2016",
  name: "Virginia Cavaliers",
  season: "2015-2016",
  sport: "Men's Basketball",
  school: "University of Virginia",
  conference: "ACC",
  accomplishment: "2015-2016 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/258.png",
  mascotName: "Cavalier",
  people: [
    {
      slug: "malcolm-brogdon",
      firstName: "Malcolm",
      lastName: "Brogdon",
      birthYear: 1992,
      hometown: "United States",
      highSchool: "United States",
      bio: "Senior and ACC POY. Future NBA ROY as #36 pick.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        location: "Washington, DC",
        statusNote: "ACC POY. NBA ROY. Master's in public policy from UVA.",
        sourceUrl: "https://en.wikipedia.org/wiki/Malcolm_Brogdon",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 18.2, reboundsPerGame: 4.1, assistsPerGame: 3.1 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 18.2, reboundsPerGame: 4.1, assistsPerGame: 3.1 },
      ],
      careerEvents: [],
    },
    {
      slug: "london-perrantes",
      firstName: "London",
      lastName: "Perrantes",
      birthYear: 1994,
      hometown: "United States",
      highSchool: "United States",
      bio: "Junior floor general and 4-year starter.",
      status: {
        occupationType: "COACH",
        currentTitle: "Coach",
        location: "Virginia",
        statusNote: "Transitioned to coaching.",
        sourceUrl: "https://en.wikipedia.org/wiki/London_Perrantes",
      },
      membership: { role: "PLAYER", jerseyNumber: 32, position: "Point Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 10, reboundsPerGame: 2.5, assistsPerGame: 4.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 10, reboundsPerGame: 2.5, assistsPerGame: 4.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "isaiah-wilkins",
      firstName: "Isaiah",
      lastName: "Wilkins",
      birthYear: 1996,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore defensive stopper. Son of Dominique Wilkins.",
      status: {
        occupationType: "RETIRED_ATHLETE",
        currentTitle: "Professional",
        location: "Atlanta, GA",
        statusNote: "Son of NBA legend Dominique Wilkins. Played overseas briefly.",
        sourceUrl: "https://en.wikipedia.org/wiki/Isaiah_Wilkins",
      },
      membership: { role: "PLAYER", jerseyNumber: 21, position: "Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 5, reboundsPerGame: 4, assistsPerGame: 0.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 5, reboundsPerGame: 4, assistsPerGame: 0.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "tony-bennett-uva",
      firstName: "Tony",
      lastName: "Bennett",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Architect of the Pack Line defense who led Virginia to the 2019 national championship — redemption after the 2018 UMBC loss.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Still coaching at Virginia. 2019 NCAA Champion.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tony_Bennett",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2026" },
      seasonStats: [
        { level: "COACHING", teamName: "Virginia Cavaliers", season: "2015-2016", yearLabel: "2015-2016", sortOrder: 208 },
      ],
      careerEvents: [],
    },
  ],
};
