import type { TeamSeed } from "./types";

export const virginiaBasketball2010: TeamSeed = {
  slug: "virginia-basketball-2010",
  name: "Virginia Cavaliers",
  season: "2009-2010",
  sport: "Men's Basketball",
  school: "University of Virginia",
  conference: "ACC",
  accomplishment: "2009-2010 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/258.png",
  mascotName: "Cavalier",
  people: [
    {
      slug: "sylven-landesberg",
      firstName: "Sylven",
      lastName: "Landesberg",
      birthYear: 1990,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore guard. ACC ROY previous year. Would be dismissed after this season.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "Overseas",
        statusNote: "Long overseas career after dismissal from UVA.",
        sourceUrl: "https://en.wikipedia.org/wiki/Sylven_Landesberg",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 16, reboundsPerGame: 4.5, assistsPerGame: 2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 16, reboundsPerGame: 4.5, assistsPerGame: 2 },
      ],
      careerEvents: [],
    },
    {
      slug: "mustapha-farrakhan",
      firstName: "Mustapha",
      lastName: "Farrakhan",
      birthYear: 1989,
      hometown: "United States",
      highSchool: "United States",
      bio: "Junior guard who provided backcourt scoring.",
      status: {
        occupationType: "OTHER",
        currentTitle: "Professional",
        location: "United States",
        statusNote: "Played overseas briefly after UVA.",
        sourceUrl: "https://en.wikipedia.org/wiki/Mustapha_Farrakhan",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 12, reboundsPerGame: 2.5, assistsPerGame: 3 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 12, reboundsPerGame: 2.5, assistsPerGame: 3 },
      ],
      careerEvents: [],
    },
    {
      slug: "tony-bennett-uva",
      firstName: "Tony",
      lastName: "Bennett",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Architect of the Pack Line defense who led Virginia to the 2019 national championship — redemption after the 2018 UMBC loss.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Still coaching at Virginia. 2019 NCAA Champion.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tony_Bennett",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2026" },
      seasonStats: [
        { level: "COACHING", teamName: "Virginia Cavaliers", season: "2009-2010", yearLabel: "2009-2010", sortOrder: 202 },
      ],
      careerEvents: [],
    },
  ],
};
