import type { TeamSeed } from "./types";

export const virginiaBasketball2025: TeamSeed = {
  slug: "virginia-basketball-2025",
  name: "Virginia Cavaliers",
  season: "2024-2025",
  sport: "Men's Basketball",
  school: "University of Virginia",
  conference: "ACC",
  accomplishment: "2024-2025 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/258.png",
  mascotName: "Cavalier",
  people: [
    {
      slug: "isaac-mckneely",
      firstName: "Isaac",
      lastName: "McKneely",
      birthYear: 2003,
      hometown: "United States",
      highSchool: "United States",
      bio: "Junior guard and UVA's top scorer.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Player",
        location: "Charlottesville, VA",
        statusNote: "Emerged as UVA's go-to scorer in 2024-25.",
        sourceUrl: "https://en.wikipedia.org/wiki/Isaac_McKneely",
      },
      membership: { role: "PLAYER", jerseyNumber: 11, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 15, reboundsPerGame: 3, assistsPerGame: 2.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 15, reboundsPerGame: 3, assistsPerGame: 2.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "andrew-rohde",
      firstName: "Andrew",
      lastName: "Rohde",
      birthYear: 2003,
      hometown: "United States",
      highSchool: "United States",
      bio: "Sophomore guard and 3-point shooter.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Player",
        location: "Charlottesville, VA",
        statusNote: "Developing into key backcourt player.",
        sourceUrl: "https://en.wikipedia.org/wiki/Andrew_Rohde",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 10, reboundsPerGame: 2.5, assistsPerGame: 2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 10, reboundsPerGame: 2.5, assistsPerGame: 2 },
      ],
      careerEvents: [],
    },
    {
      slug: "tony-bennett-uva",
      firstName: "Tony",
      lastName: "Bennett",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Architect of the Pack Line defense who led Virginia to the 2019 national championship — redemption after the 2018 UMBC loss.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Still coaching at Virginia. 2019 NCAA Champion.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tony_Bennett",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2026" },
      seasonStats: [
        { level: "COACHING", teamName: "Virginia Cavaliers", season: "2024-2025", yearLabel: "2024-2025", sortOrder: 217 },
      ],
      careerEvents: [],
    },
  ],
};
