import type { TeamSeed } from "./types";

export const virginiaBasketball2021: TeamSeed = {
  slug: "virginia-basketball-2021",
  name: "Virginia Cavaliers",
  season: "2020-2021",
  sport: "Men's Basketball",
  school: "University of Virginia",
  conference: "ACC",
  accomplishment: "2020-2021 Season",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/258.png",
  mascotName: "Cavalier",
  people: [
    {
      slug: "sam-hauser",
      firstName: "Sam",
      lastName: "Hauser",
      birthYear: 1997,
      hometown: "United States",
      highSchool: "United States",
      bio: "Grad transfer from Marquette. Elite shooter who joined Celtics.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Forward",
        location: "Boston, MA",
        statusNote: "Won 2024 NBA Championship with Celtics. $45M contract. Elite 3-point shooter.",
        sourceUrl: "https://en.wikipedia.org/wiki/Sam_Hauser",
      },
      membership: { role: "PLAYER", jerseyNumber: 10, position: "Forward", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 16, reboundsPerGame: 6.8, assistsPerGame: 1.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 16, reboundsPerGame: 6.8, assistsPerGame: 1.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "kihei-clark",
      firstName: "Kihei",
      lastName: "Clark",
      birthYear: 2000,
      hometown: "United States",
      highSchool: "United States",
      bio: "Junior PG and UVA's floor general.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Guard",
        location: "Belgium",
        statusNote: "UVA all-time assists leader. Now in Belgium's BNXT League.",
        sourceUrl: "https://en.wikipedia.org/wiki/Kihei_Clark",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Point Guard", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 9.5, reboundsPerGame: 2.5, assistsPerGame: 4.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 9.5, reboundsPerGame: 2.5, assistsPerGame: 4.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "jay-huff",
      firstName: "Jay",
      lastName: "Huff",
      birthYear: 1998,
      hometown: "United States",
      highSchool: "United States",
      bio: "Senior center with 3-point range and shot-blocking.",
      status: {
        occupationType: "ACTIVE_PRO_ATHLETE",
        currentTitle: "Pro Player",
        location: "United States",
        statusNote: "Played for Wizards. Rare stretch-5 with shot-blocking.",
        sourceUrl: "https://en.wikipedia.org/wiki/Jay_Huff",
      },
      membership: { role: "PLAYER", jerseyNumber: 30, position: "Center", yearsAtSchool: "undefined", gamesPlayed: 33, pointsPerGame: 13, reboundsPerGame: 7, assistsPerGame: 0.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Virginia Cavaliers", season: "undefined", yearLabel: "undefined", sortOrder: 201, gamesPlayed: 33, pointsPerGame: 13, reboundsPerGame: 7, assistsPerGame: 0.8 },
      ],
      careerEvents: [],
    },
    {
      slug: "tony-bennett-uva",
      firstName: "Tony",
      lastName: "Bennett",
      birthYear: 1960,
      hometown: "United States",
      highSchool: "United States",
      isFeatured: true,
      bio: "Architect of the Pack Line defense who led Virginia to the 2019 national championship — redemption after the 2018 UMBC loss.",
      status: {
        occupationType: "COACH",
        currentTitle: "Basketball Coach",
        location: "United States",
        statusNote: "Still coaching at Virginia. 2019 NCAA Champion.",
        sourceUrl: "https://en.wikipedia.org/wiki/Tony_Bennett",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2009-2026" },
      seasonStats: [
        { level: "COACHING", teamName: "Virginia Cavaliers", season: "2020-2021", yearLabel: "2020-2021", sortOrder: 213 },
      ],
      careerEvents: [],
    },
  ],
};
