import type { TeamSeed } from "./types";

export const wakeForestBasketball2025: TeamSeed = {
  slug: "wake-forest-basketball-2025",
  name: "Wake Forest Demon Deacons",
  season: "2024-2025",
  sport: "Men's Basketball",
  school: "Wake Forest University",
  conference: "ACC",
  accomplishment: "NCAA Tournament (20-14)",
  logoUrl: "https://a.espncdn.com/i/teamlogos/ncaa/500/154.png",
  mascotName: "Demon Deacon",
  people: [
    {
      slug: "hunter-sallis",
      firstName: "Hunter",
      lastName: "Sallis",
      birthYear: 2003,
      hometown: "Omaha, NE",
      highSchool: "Millard North High School, Omaha, NE",
      isFeatured: true,
      bio: "The senior guard who became the first Wake Forest player to earn back-to-back first-team All-ACC honors since Tim Duncan (1995-97). A former five-star recruit who blossomed into one of the ACC's most dynamic scorers, averaging 18.0 PPG with career highs in rebounding and assists in his final season.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "2025 NBA Draft Prospect",
        location: "Omaha, NE",
        statusNote: "After four years at Wake Forest, Sallis declared for the 2025 NBA Draft. He finished his career as one of the most decorated players in program history — the first Demon Deacon with multiple first-team All-ACC selections since Tim Duncan. Sallis was named to the Oscar Robertson Trophy midseason watch list in 2025. Originally the #6 overall recruit in the 2021 class, he chose Wake Forest over blue-blood programs and delivered on his potential by becoming the face of the program during his junior and senior seasons.",
        sourceUrl: "https://en.wikipedia.org/wiki/Hunter_Sallis",
      },
      membership: { role: "PLAYER", jerseyNumber: 22, position: "Guard", yearsAtSchool: "2021-2025", statsNote: "2x First-Team All-ACC • First since Tim Duncan • 18.0 PPG", gamesPlayed: 34, pointsPerGame: 18.0, reboundsPerGame: 5.1, assistsPerGame: 2.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Wake Forest Demon Deacons", season: "2024-25", yearLabel: "Senior", sortOrder: 204, gamesPlayed: 34, minutesPerGame: 34.0, pointsPerGame: 18.0, reboundsPerGame: 5.1, assistsPerGame: 2.8, fieldGoalPct: 0.450, threePointPct: 0.350 },
      ],
      careerEvents: [
        { year: 2024, title: "Named First-Team All-ACC for second consecutive year", eventType: "AWARD" },
        { year: 2025, title: "Declared for the 2025 NBA Draft", eventType: "DRAFT" },
      ],
    },
    {
      slug: "cameron-hildreth",
      firstName: "Cameron",
      lastName: "Hildreth",
      birthYear: 2002,
      hometown: "London, England",
      highSchool: "Sunrise Christian Academy, Bel Aire, KS",
      bio: "A junior guard from London who earned All-ACC Honorable Mention and was Sallis's backcourt partner. His international background and steady play made Wake Forest's backcourt one of the best in the conference.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "2025 NBA Draft Prospect / Transfer Portal",
        location: "London, England",
        statusNote: "After three years at Wake Forest, Hildreth entered the 2025 NBA Draft process. The London native came to the US through Sunrise Christian Academy in Kansas before joining the Demon Deacons. He and Sallis formed one of the ACC's best guard duos during the 2024-25 season, with Hildreth providing a calming defensive presence and secondary scoring option.",
        sourceUrl: "https://godeacs.com/sports/mens-basketball/roster/cameron-hildreth/",
      },
      membership: { role: "PLAYER", jerseyNumber: 2, position: "Guard", yearsAtSchool: "2022-2025", statsNote: "All-ACC Honorable Mention • London native • Backcourt partner", gamesPlayed: 34, pointsPerGame: 13.5, reboundsPerGame: 4.2, assistsPerGame: 3.1 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Wake Forest Demon Deacons", season: "2024-25", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 34, minutesPerGame: 32.0, pointsPerGame: 13.5, reboundsPerGame: 4.2, assistsPerGame: 3.1 },
      ],
      careerEvents: [
        { year: 2025, title: "Earned All-ACC Honorable Mention", eventType: "AWARD" },
      ],
    },
    {
      slug: "ty-laur-johnson",
      firstName: "Ty-Laur",
      lastName: "Johnson",
      birthYear: 2003,
      hometown: "Norfolk, VA",
      highSchool: "Norview High School, Norfolk, VA",
      bio: "A junior point guard who emerged as Wake Forest's primary playmaker, dishing out a season-high 8 assists against Duke. His floor leadership was critical to the Deacons' NCAA Tournament bid.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Wake Forest University",
        location: "Winston-Salem, NC",
        statusNote: "Johnson continues to develop as one of the ACC's top point guards. His combination of speed, court vision, and defensive intensity has made him a key piece of Wake Forest's backcourt alongside Sallis and Hildreth.",
        sourceUrl: "https://godeacs.com/sports/mens-basketball/roster/ty-laur-johnson/",
      },
      membership: { role: "PLAYER", jerseyNumber: 4, position: "Point Guard", yearsAtSchool: "2022-present", statsNote: "8 assists vs Duke • Primary floor general", gamesPlayed: 34, pointsPerGame: 8.5, reboundsPerGame: 2.8, assistsPerGame: 4.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Wake Forest Demon Deacons", season: "2024-25", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 34, minutesPerGame: 28.0, pointsPerGame: 8.5, reboundsPerGame: 2.8, assistsPerGame: 4.2 },
      ],
      careerEvents: [],
    },
    {
      slug: "trevon-spillers",
      firstName: "TreVon",
      lastName: "Spillers",
      birthYear: 2003,
      hometown: "Reidsville, NC",
      highSchool: "Reidsville High School, Reidsville, NC",
      bio: "A junior forward and local North Carolina product who was Wake Forest's most physical interior player. Set a season-high 16 rebounds against NC A&T and provided toughness and energy off the bench.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Wake Forest University",
        location: "Winston-Salem, NC",
        statusNote: "Spillers has been a key frontcourt piece for Wake Forest, providing rebounding and defensive energy. His physical style complements the guard-heavy roster and his 16-rebound game showcased his ceiling as an interior player.",
        sourceUrl: "https://godeacs.com/sports/mens-basketball/roster/trevon-spillers/",
      },
      membership: { role: "PLAYER", jerseyNumber: 15, position: "Forward", yearsAtSchool: "2022-present", statsNote: "16 rebounds vs NC A&T • Local NC product", gamesPlayed: 34, pointsPerGame: 6.2, reboundsPerGame: 5.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Wake Forest Demon Deacons", season: "2024-25", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 34, minutesPerGame: 22.0, pointsPerGame: 6.2, reboundsPerGame: 5.5 },
      ],
      careerEvents: [],
    },
    {
      slug: "efton-reid",
      firstName: "Efton",
      lastName: "Reid",
      birthYear: 2002,
      hometown: "Baton Rouge, LA",
      highSchool: "Steele Canyon High School, Spring Valley, CA",
      bio: "A senior center who transferred from LSU and provided shot-blocking and rim protection. A former McDonald's All-American who was a five-star recruit out of high school.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Wake Forest University",
        location: "Winston-Salem, NC",
        statusNote: "Reid came to Wake Forest after two seasons at LSU, bringing his imposing 7-foot frame and shot-blocking ability. Originally a five-star recruit and McDonald's All-American, his career trajectory took an unconventional path through the transfer portal. He set a season-high 4 blocks against James Madison.",
        sourceUrl: "https://godeacs.com/sports/mens-basketball/roster/efton-reid/",
      },
      membership: { role: "PLAYER", jerseyNumber: 25, position: "Center", yearsAtSchool: "2023-present", statsNote: "LSU transfer • Former McDonald's All-American • 4 blocks vs JMU", gamesPlayed: 32, pointsPerGame: 5.8, reboundsPerGame: 4.3 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Wake Forest Demon Deacons", season: "2024-25", yearLabel: "Senior (transfer from LSU)", sortOrder: 204, gamesPlayed: 32, minutesPerGame: 18.0, pointsPerGame: 5.8, reboundsPerGame: 4.3 },
      ],
      careerEvents: [],
    },
    {
      slug: "nate-calmese",
      firstName: "Nate",
      lastName: "Calmese",
      birthYear: 2004,
      hometown: "Virginia Beach, VA",
      highSchool: "Bishop Sullivan Catholic High School, Virginia Beach, VA",
      bio: "A sophomore guard from Virginia Beach who provided backcourt depth and will be expected to take on a much larger role after the departures of Sallis and Hildreth.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Wake Forest University",
        location: "Winston-Salem, NC",
        statusNote: "Calmese is expected to step into a starting role for the 2025-26 season with both Sallis and Hildreth departing. His development in the backcourt will be crucial for Wake Forest's future.",
        sourceUrl: "https://godeacs.com/sports/mens-basketball/roster/nate-calmese/",
      },
      membership: { role: "PLAYER", jerseyNumber: 1, position: "Guard", yearsAtSchool: "2023-present", statsNote: "Sophomore reserve • Future starter", gamesPlayed: 30, pointsPerGame: 4.2, reboundsPerGame: 1.5, assistsPerGame: 1.8 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Wake Forest Demon Deacons", season: "2024-25", yearLabel: "Sophomore", sortOrder: 202, gamesPlayed: 30, minutesPerGame: 14.0, pointsPerGame: 4.2, assistsPerGame: 1.8 },
      ],
      careerEvents: [],
    },
    {
      slug: "kevin-miller-wf",
      firstName: "Kevin",
      lastName: "Miller",
      birthYear: 2003,
      hometown: "Silver Spring, MD",
      highSchool: "St. John's College High School, Washington, DC",
      bio: "A junior forward who provided energy and athleticism off the bench. A key rotation piece in Steve Forbes's up-tempo system.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Wake Forest University",
        location: "Winston-Salem, NC",
        statusNote: "Miller has been a valuable bench contributor for Wake Forest, providing athletic wing play and defensive versatility in the ACC.",
        sourceUrl: "https://godeacs.com/sports/mens-basketball/roster/kevin-miller/",
      },
      membership: { role: "PLAYER", jerseyNumber: 0, position: "Forward", yearsAtSchool: "2022-present", statsNote: "Junior reserve • Athletic wing", gamesPlayed: 32, pointsPerGame: 5.0, reboundsPerGame: 3.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Wake Forest Demon Deacons", season: "2024-25", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 32, minutesPerGame: 16.0, pointsPerGame: 5.0, reboundsPerGame: 3.2 },
      ],
      careerEvents: [],
    },
    {
      slug: "parker-friedrichsen",
      firstName: "Parker",
      lastName: "Friedrichsen",
      birthYear: 2003,
      hometown: "Overland Park, KS",
      highSchool: "Blue Valley Northwest High School, Overland Park, KS",
      bio: "A junior guard who transferred from Nebraska and provided perimeter shooting depth. A reliable three-point option in the rotation.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Wake Forest University",
        location: "Winston-Salem, NC",
        statusNote: "Friedrichsen came to Wake Forest via the transfer portal from Nebraska, adding shooting and ballhandling to the backcourt rotation.",
        sourceUrl: "https://godeacs.com/sports/mens-basketball/roster/parker-friedrichsen/",
      },
      membership: { role: "PLAYER", jerseyNumber: 12, position: "Guard", yearsAtSchool: "2023-present", statsNote: "Nebraska transfer • Perimeter shooter", gamesPlayed: 28, pointsPerGame: 3.5, reboundsPerGame: 1.2 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Wake Forest Demon Deacons", season: "2024-25", yearLabel: "Junior (transfer)", sortOrder: 203, gamesPlayed: 28, minutesPerGame: 12.0, pointsPerGame: 3.5, threePointPct: 0.380 },
      ],
      careerEvents: [],
    },
    {
      slug: "quadry-adams",
      firstName: "Quadry",
      lastName: "Adams",
      birthYear: 2003,
      hometown: "Philadelphia, PA",
      highSchool: "Camden High School, Camden, NJ",
      bio: "A junior guard from the Philadelphia area who provided defensive intensity and transition scoring off the bench.",
      status: {
        occupationType: "STUDENT",
        currentTitle: "College Basketball Player",
        currentEmployer: "Wake Forest University",
        location: "Winston-Salem, NC",
        statusNote: "Adams has been a rotation guard for Wake Forest, valued for his defensive energy and ability to push the pace in transition. He came from the fertile New Jersey/Philadelphia recruiting area.",
        sourceUrl: "https://godeacs.com/sports/mens-basketball/roster/quadry-adams/",
      },
      membership: { role: "PLAYER", jerseyNumber: 3, position: "Guard", yearsAtSchool: "2022-present", statsNote: "Junior reserve • Defensive energy", gamesPlayed: 30, pointsPerGame: 3.8, reboundsPerGame: 1.5 },
      seasonStats: [
        { level: "COLLEGE", teamName: "Wake Forest Demon Deacons", season: "2024-25", yearLabel: "Junior", sortOrder: 203, gamesPlayed: 30, minutesPerGame: 13.0, pointsPerGame: 3.8 },
      ],
      careerEvents: [],
    },
    {
      slug: "steve-forbes",
      firstName: "Steve",
      lastName: "Forbes",
      birthYear: 1963,
      hometown: "Lone Star, TX",
      highSchool: "Lone Star High School, Lone Star, TX",
      isFeatured: true,
      bio: "The head coach who rebuilt Wake Forest into an NCAA Tournament program after years in the wilderness. Previously led East Tennessee State to a 130-43 record and three Southern Conference titles before taking over the Demon Deacons in 2020.",
      status: {
        occupationType: "COACH",
        currentTitle: "Head Men's Basketball Coach",
        currentEmployer: "Wake Forest University",
        location: "Winston-Salem, NC",
        statusNote: "Steve Forbes has been Wake Forest's head coach since 2020, inheriting a struggling program and steadily improving it. He led the Demon Deacons to the 2023 ACC Tournament Championship — the program's first conference title since 2003 — and has built a culture of toughness and player development. Before Wake Forest, he was head coach at East Tennessee State (2015-2020) where he compiled a 130-43 record. He is known for his up-tempo offensive style and ability to develop under-recruited players into NBA prospects.",
        sourceUrl: "https://en.wikipedia.org/wiki/Steve_Forbes_(basketball)",
      },
      membership: { role: "HEAD_COACH", position: "Head Coach", yearsAtSchool: "2020-present", statsNote: "2023 ACC Tournament Champions • Rebuilt Wake Forest program" },
      seasonStats: [
        { level: "COACHING", teamName: "Wake Forest Demon Deacons", season: "2024-25", yearLabel: "2024-25", sortOrder: 205, wins: 20, losses: 14, tournamentResult: "NCAA Tournament" },
      ],
      careerEvents: [
        { year: 2020, title: "Named Wake Forest head coach", eventType: "CAREER_CHANGE" },
        { year: 2023, title: "Won ACC Tournament Championship at Wake Forest", eventType: "CHAMPIONSHIP" },
      ],
    },
  ],
};
